### ISSUE TITLE
Restricted users reviving maps through the old site

### ISSUE THREAD

**Issue by MChecaH** [ppy/osu-web#10007]
The name doesn't paint the full picture, so let me explain:

Restricted users users can revive Beatmaps through the old site, or through some other means. [This will not actually revive the beatmap in the BSS](https://osu.ppy.sh/beatmapsets?m=3&q="Xnery"&s=any). However, a notification still appears to users who were previously following that user's mapping output.

[Xnery](https://osu.ppy.sh/users/9661048) has been restricted for a while. Despite this, they've been able to notify a few users. It's not a one-off case:

<p align="center">
<img src="https://cdn.discordapp.com/attachments/1072841610498408500/1086856463915421738/image.png" width=70% height=70%>
</p>

<p align="center">
<img src="https://cdn.discordapp.com/attachments/1072841610498408500/1086856529745022976/image.png" width=70% height=70%>
</p>

I'm not sure how to tackle this problem programming wise, but for a robust solution this should probably be looked in two ways:
· Actions made through the old site that cannot be changed as they are feature locked should have a backup check with the restrictions added in the new site.
· Completely remove the possibility for restricted users to trigger a notification.

**Comment by CX13BVA** [comment]
I remember doing this too, while I was restricted (2017-2020), although it stopped working for me at the latter end of 2019. Maybe it was fixed back then but a later change undid it?

**Comment by Xnery** [comment]
Thanks for advertising my maps, but let me warn you that the versions uploaded on the website are not the latest versions of the maps shown above. Please use these links to download the latest versions:

https://drive.google.com/file/d/1ElG0UTEf1UKbmxmI1Brj4o-VcUCE_U5Q/view?usp=sharing
https://drive.google.com/file/d/1nXe73VQWKxqWqpTFL147BdiNYju51_Ta/view?usp=sharing

**Comment by cl8n** [comment]
should be fixed now since you can't log in to the old site at all
