### ISSUE TITLE
maybe add tooltip for hyperlinks

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#10012]
![uPQWAQB](https://user-images.githubusercontent.com/32525896/226429731-8ae811e4-a5d6-414e-b833-ae25419ec7eb.png)
you can still decide if you wanna click on it or not

also wondering if it would be showing the name of the page's tab or url? not sure what's more common

**Comment by nanaya** [comment]
....just look at bottom left corner of your browser

**Comment by Lyawi** [comment]
oh
