### ISSUE TITLE
Backgrounds of deleted beatmaps are still publicly accessible

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#10013]
Now that moderators can view deleted maps the background are no longer deleted, however the permission for viewing the assets isnt locked to moderators only. Quite yikes considering that these backgrounds could be of explicit nature

Example: https://assets.ppy.sh/beatmaps/1882266/covers/raw.jpg

**Comment by squareclicker** [comment]
mods can view deleted maps now? can you source this? i have some deleted maps i'd like to recover

**Comment by peppy** [comment]
> mods can view deleted maps now? can you source this? i have some deleted maps i'd like to recover

You can contact support for this.

> Now that moderators can view deleted maps the background are no longer deleted, however the permission for viewing the assets isnt locked to moderators only. Quite yikes considering that these backgrounds could be of explicit nature

honestly i don't see this as a huge deal if they are not linked anywhere. if it's bad enough (ie. illegal) please let me know and i'll remove the content manually.
