### ISSUE TITLE
Top plays missing from lazer profile

### ISSUE THREAD

**Issue by W00dss** [ppy/osu-web#10029]
I dont really know why its happening, but my pp value is similar so it might be visual.
Stable top plays:
![Screenshot 2023-03-23 012249](https://user-images.githubusercontent.com/128684935/227144398-7479d436-d19c-4fc9-b61c-69fa12dfae6d.png)
Lazer top plays:
![Screenshot 2023-03-23 012348](https://user-images.githubusercontent.com/128684935/227144565-a42a06eb-563f-4a05-87c7-b338fd3a5892.png)

**Comment by MaxKruse** [comment]
same issue, see https://lazer.ppy.sh/users/1199528 vs https://osu.ppy.sh/users/1199528

**Comment by peppy** [comment]
Should be resolved by now.
