### ISSUE TITLE
indexing of graveyard forum

### ISSUE THREAD

**Issue by silk-hyacinth** [ppy/osu-web#10036]
Currently this forum [(https://osu.ppy.sh/community/forums/19)](url) is not indexed by the website search function, even when selecting the forum specifically:

![image](https://user-images.githubusercontent.com/105128796/227762663-b15d06fa-9575-4308-9ae9-40c3cf20f5d0.png)

I'd imagine this is done to avoid further bloat of the website search, but it can be useful to be able to search this forum, as it is a permanent record of past uploaded maps, even if the map itself has been deleted by the creator - I was trying to see what maps I had deleted previously + see some metadata on a map I thought existed but can't find in the regular beatmap search.

would it be possible to index this forum (and also 6 and 10, I guess), but only have the results display when specifically selecting them in the search function, thus avoiding bloat but still keeping the forum searchable? Or is there another reason this forum is not currently indexed?

**Comment by silk-hyacinth** [comment]
Oh so will the currently unindexed forums never be indexed?

**Comment by peppy** [comment]
I don't think this will be indexed sorry. Finding deleted maps is not really a great use case for indexing either.
