### ISSUE TITLE
Forum tags don't work when subject line is too long

### ISSUE THREAD

**Issue by pishifat** [ppy/osu-web#10033]
relevant to https://osu.ppy.sh/community/forums/92

im not entirely sure what the cause is, but threads with long titles can't have forum tags for some reason. it works after shortening the title though
example broken threads:
https://osu.ppy.sh/community/forums/topics/1587597?n=1
https://osu.ppy.sh/community/forums/topics/1564613?n=1

https://user-images.githubusercontent.com/31551350/227630208-96ad5910-ce04-4edf-93d0-a816c620a965.mp4

**Comment by nanaya** [comment]
the title most likely exceeded the length limit (100) with the new tag (as it's just part of title). The part which adds the tag thing needs a fix to show correct error message at least...
