### ISSUE TITLE
Loved maps appearing in Pending/WIP categories

### ISSUE THREAD

**Issue by iap0rt** [ppy/osu-web#10046]
I don't know if this is intentional, or if this is even the place to go, but if one goes to Pending or WIP, then sorts by play count, favorites, or rating, several loved maps show up. It seems that all the affected loved maps have difficulties that are labeled as "Pending" or "WIP," so that might be involved. 

![loved-in-pendingwip-1](https://user-images.githubusercontent.com/113390561/228094817-7e2cfef8-93a7-4e4e-8d40-a2199cc187a8.PNG)
![loved-in-pendingwip-2](https://user-images.githubusercontent.com/113390561/228094819-bb2c7f59-2ff5-4dd6-b005-3afed0b2a074.PNG)
![loved-in-pendingwip-3](https://user-images.githubusercontent.com/113390561/228094821-d5efe886-96a4-4b49-bfe4-3f6e6b5cb86d.PNG)

**Comment by nanaya** [comment]
Yes, its searches difficulty so if there's any match, it'll be shown even though the set have different status.
