### ISSUE TITLE
Upgrade Laravel

### ISSUE THREAD

**Issue by lexisother** [ppy/osu-web#10042]
We are running two major versions behind with the release of Laravel 10. Outdated practices such as the use of Laravel Mix have been dropped and replaced with Vite, Artisan has gotten a makeover, amongst many other things. (I recommend reading the update logs)

While I wouldn't mind picking up this task by myself, I'd like to hear anything from maintainers to gather if they think it is worth the time spent.

**Comment by nanaya** [comment]
That you mention laravel mix at all makes me wonder if you've seen the project beyond its composer.json file.

**Comment by lexisother** [comment]
I indeed did not at all. (please update your `SETUP.md` :) ) That is a nitpick however.

My question still stands.

**Comment by nanaya** [comment]
My last upgrade attempt:

- some packages haven't been updated to support laravel 10 (some probably are now)
- there were test failures on laravel 9 which seems to come from weird database transaction behaviour

otherwise feel free to attempt upgrading.

**Comment by lexisother** [comment]
I'll have a try at it sometime. Thanks for the swift responses!
