### ISSUE TITLE
Forum quotes no longer have space at the end

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#10047]
New forum formatting changes resulted in quoted content loosing spacing below, which causes the overall content to look like a wall of text

![](https://i.imgur.com/jiT0GQK.png)
[(Referenced post)](https://osu.ppy.sh/community/forums/posts/9047908)

**Comment by nanaya** [comment]
if you put no newline between the quote and sentence, you get no newline.

**Comment by abraker95** [comment]
That makes sense. While previous behavior is taken for granted, adopting to the new behavior is not too bad. The main issue is that it makes every post prior to the change now look bad.

**Comment by nanaya** [comment]
yeah, the default quote button giving barely no newline didn't help either. Unless it's really distracting (mainly for the older posts?) and that people always want blank space after quotes, I think the current behaviour is better as it give more or less exact control over newlines.

**Comment by abraker95** [comment]
There is some feedback regarding the changes in this thread:
https://osu.ppy.sh/community/forums/posts/9048851

![](https://i.imgur.com/skiMh4w.png)

**Comment by Felixland** [comment]
I personally prefer the old way it was handled rather than this. And it seems like the people on the forums prefer that too.
