### ISSUE TITLE
Hybrid bot accounts cannot use OAuth delegation

### ISSUE THREAD

**Issue by ThePooN** [ppy/osu-web#10056]
There are two kinds of bot accounts:
- Full bot accounts
  They have the bot usergroup assigned as their main group. They cannot log in in-game on osu!stable, can only use the IRC gateway and APIv2. Since they're not considered players, most of their profile is hidden. Example: [Corsace](https://osu.ppy.sh/users/29191632)
- Hybrid bot accounts
  They have the bot usergroup but it is not assigned as their main group because they also need to log in in-game, whether it is for playing the game or spectating tournament matches. This case is very rare but includes [myself](https://osu.ppy.sh/users/718454), [osufrlive](https://osu.ppy.sh/users/15337466) as well as [Tillerino](https://osu.ppy.sh/users/2070907).

Users with hybrid bot accounts are currently hit by the following error when trying to use the `delegate` scope:
```json
{"error":"Delegation with Client Credentials is only available to chat bots."}
```

This came up as Tillerino is looking to switch from IRC to APIv2/WebSockets, but is currently blocked by [this check](https://github.com/ppy/osu-web/blob/2c6d0ddc5e0d82b536e0092b43a8897e15ffb28f/app/Models/OAuth/Token.php#L121), as [isBot](https://github.com/ppy/osu-web/blob/b11cc8cdfa2e0670d984d3b069e1eb884ca83446/app/Models/User.php#L1015) only considers full bot accounts. This is also going to hit me and osu!frlive when we eventually start working on organizing full-scale osu!(lazer) tournaments.

Fixing this is non-trivial as all side-effects of making `isBot` return `true` for hybrid bots are not desirable. I started working on a patch, adding an `isHybridBot` method to the `User` model and replacing usage of `isBot` by `isHybridBot` where applicable, please let me know if this is the right direction.

**Comment by nanaya** [comment]
It's currently a bit more work but it's already possible to get normal auth code token with `chat.write` scope as long it's for your own user.

If anything I'd rather remove the delegate thing and add a way to create the chat token through settings page directly.

**Comment by nanaya** [comment]
Yeah, auth code with `chat.write` seems to work just fine.
