### ISSUE TITLE
Restricted users can't be set as difficulty owner

### ISSUE THREAD

**Issue by Dopaminos** [ppy/osu-web#10066]
I uploaded a [set](https://osu.ppy.sh/beatmapsets/1965579#mania/4075801) where [MORGENSHTERN-](https://osu.ppy.sh/users/10840129) was participating in, 
but for some reason, i couldn't set them as the difficulty owner when [previously](https://osu.ppy.sh/beatmapsets/1265602#mania/2653412) i had such possibility.

i'm asking to give such possibility back, please.
if there is some issue unrelated to anything but their user account (other kind of ban) - please, let me know

**Comment by peppy** [comment]
This is correct behaviour. Restricted users are not visible to any systems.
