### ISSUE TITLE
Users with the same name as language channels can't be reached via IRC

### ISSUE THREAD

**Issue by Eliteronix** [ppy/osu-web#10069]
Tested with the users "French" and "Finnish" and using IceChat (also happens for chat4osu and using bancho.js)

Trying to message anyone with a name the same as language channels doesn't work.

Messages sent ingame on the 26th march:
![image](https://user-images.githubusercontent.com/64707347/229188029-e9079c9b-6150-4788-8053-f93ba18b0bbf.png)

The messages sent did not get received by the French ingame and the messages also don't appear on the website:
![image](https://user-images.githubusercontent.com/64707347/229189071-8f91a84b-5108-445c-8d6d-c4e34aef495f.png)

The messages also don't get sent into the language channels though and just seem to go nowhere.

**Comment by peppy** [comment]
I've fixed this in bancho. Basically in the case of a matching channel name, it would do a pre-check to ensure the sender was in the channel before allowing the PM to go through. This check was not confirming whether a prefixing `#` was present or not, so it would fail in the case of a user and channel naming clash where the user (the bot) is not in the matching channel.

Will deploy sometime this week.

**Comment by ThePooN** [comment]
Wow, that explains why I wasn't able to reproduce with French... Thanks.
