### ISSUE TITLE
Modding rank command fails to run occasionally

### ISSUE THREAD

**Issue by dz-ss** [ppy/osu-web#10070]
The rank command is scheduled to run every 20 minutes, but ranked times of past beatmapsets show the command often fails to run.

If we calculate the earliest time that a beatmapset can be ranked* and compare it with the ranked time on the website, we should expect these times to match. But for many beatmapsets, they don't.

*when the beatmapset fulfills all the conditions and is added to the toBeRankedQuery [ModdingRankCommand.php#L69-L72](https://github.com/ppy/osu-web/blob/master/app/Console/Commands/ModdingRankCommand.php#L69-L72)

Here are 2 google sheets comparing the two times:
[beatmapsets ranked from 2022/12/14 to 2022/12/22](https://docs.google.com/spreadsheets/d/1LoLKkkA1K8XDQDqghthsmM7o4G12ysRMNX4-bzOZqI8/edit?usp=sharing)
[beatmapsets ranked from 2023/03/30 to 2023/04/01](https://docs.google.com/spreadsheets/d/13vwiRj_8BvXx7uD6L-gqLnn88x8mPIEjrsvEwrckZtI/edit?usp=sharing)
In the 2nd sheet alone, the rank command missed at least 40 of its scheduled runs.

The issue started occurring on 2022/12/16, around when [this beatmapset](https://osu.ppy.sh/beatmapsets/1883253/discussion/-/events) was ranked.

A fix (https://github.com/ppy/osu-web/commit/46238780df533e3f7b13177d67d2eaf4f7b60694, https://github.com/ppy/osu-web/commit/cfa63a3a392436b1c81a7688b3f4a082cbaa92a0) was applied back in December but it seems like this issue is still occurring.

**Comment by peppy** [comment]
There's no guarantee for when this should run. It is made to catch up as required.

Is this somehow affecting you?

**Comment by dz-ss** [comment]
I'm not too sure what you mean by catch up as required.

Just to clarify what the issue is:
The expected behavior is that modding rank command runs every 20 minutes. But what I'm observing is that it's not actually running every 20 minutes and is missing many of the scheduled runs.

https://github.com/ppy/osu-web/blob/bef554265633c0330c13878fe813d3c4df05e30d/app/Console/Kernel.php#L113-L116
I'm looking at the code here and the modding rank command should run every 20 min. Unless that's not how it's actually implemented on the server?

If this is intended behavior then it's fine. I thought I'd report it because it seemed like a bug, especially since this started happening right after a beatmapset had a duplicate ranked event bug.
![image](https://user-images.githubusercontent.com/52870410/229327572-b99fee8d-435d-44f3-9382-68ef3df563bf.png)
