### ISSUE TITLE
Problem with entering nickname "discord"

### ISSUE THREAD

**Issue by Provodahehe** [ppy/osu-web#10075]
Hello
I already changed my nickname

![image](https://user-images.githubusercontent.com/129757830/229515609-ee5a481e-063c-49a1-a36a-c416077be705.png)
![image](https://user-images.githubusercontent.com/129757830/229515661-31e49a73-750b-4e9c-b3ce-150349c8667c.png)

I'm terrible at English and I use a translator, sorry for the mistakes
hehe

**Comment by nanaya** [comment]
did you put an extra space afterthe `#1158`?
