### ISSUE TITLE
Move api v1 and irc token retrieval to osu-web

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#10073]
These are the only two (known) pieces required to turn off the old site.

**Comment by Hiviexd** [comment]
would like to add that it would be a good idea to also port the kudosu leaderboard to osu-web, it's currently one of the very few things only accessible through the old site

**Comment by nanaya** [comment]
The original issue has been completed but how about the kudosu leaderboard thing?

**Comment by cl8n** [comment]
opened  #10207 to track other old website stuff
