### ISSUE TITLE
General (difficulty name) page in beatmap discussion refuses to load

### ISSUE THREAD

**Issue by aryoadhi** [ppy/osu-web#10097]
Opening Discussion page and going to General (diff name) of this map causes the page to not load at all. I can load General (diff name) of other beatmaps, but this one in particular blanks out. Happens on both mobile and PC, and with both wireless and mobile data.

https://osu.ppy.sh/beatmapsets/1925721

Video or screenshot showing the problem:
![](https://cdn.discordapp.com/attachments/1081274084115091508/1094520296951779448/image.png)

**Comment by Sebola3461** [comment]
This is fixed. Can you confirm?

**Comment by aryoadhi** [comment]
Yep. It's fixed already. Unsure why this happened...
