### ISSUE TITLE
Inccorect icon for achivement: Video Game Pack vol.2

### ISSUE THREAD

**Issue by TedTheRed** [ppy/osu-web#101]
it seems that the icon for Video Game Pack vol.2 is replaced by the icon for Video Game Pack vol.1
![video game pack vol.1](http://puu.sh/kvXeW/2d34686a5d.jpg) ![video game pack vol.2](http://puu.sh/kvXgu/2ca1c8ebe4.jpg)

**Comment by nanaya** [comment]
Turns out I put in wrong data.

@peppy: slug for that achievement (id 12) needs fixing :D

**Comment by peppy** [comment]
Done
