### ISSUE TITLE
ScoreV2 plays increase Plays on the Play History graph while not adding any other stats or showing in Recent Plays

### ISSUE THREAD

**Issue by respektive** [ppy/osu-web#10114]
So I played a map with ScoreV2 today and as expected the play does not submit to my recent plays or increase any profile stats.

However, I noticed that the Plays on my Play History graph were increased by that play. I'm assuming this is a bug and not supposed to happen as ScoreV2 plays don't increase any other stats.

**Comment by peppy** [comment]
Not really sure about this. Probably won't change though because the code surrounding score v2 and score submissions is.. not easy to work with due to the number of special cases.
