### ISSUE TITLE
Open the WebSocket chat API to 3rd-party apps

### ISSUE THREAD

**Issue by ThePooN** [ppy/osu-web#10118]
Currently, the WebSocket API requires scopes that aren't available to 3rd-party apps (https://github.com/ppy/osu-notification-server/blob/693fab53e75d4e5d227426b15985228ade6f02f0/src/oauth-verifier.ts#L92); `*` can only be granted through the lazer-specific password grant, and `read` doesn't seem to exist.

This is necessary in order to actually switch from the legacy IRC API to osu-web APIs, as has been encouraged for years 😅

The API endpoint that returns the WebSocket gateway URL is also lazer-only.

Note that this cannot be restricted to whitelisted chat bots only; building a chat bot on a normal user account first is necessary per [current process](https://osu.ppy.sh/wiki/en/Bot_account) to be eligible.

Opened this issue here rather than osu-notification-server since OAuth scope stuff probably makes more sense to handle/track here, but feel free to move this issue across.

Received requests about this from @Tillerino and @RoanH.

**Comment by venix12** [comment]
related to #7862?

**Comment by ThePooN** [comment]
Well, both the chat updates endpoint and websockets allow to do the same thing, but I assume chat updates is such a drain as mentioned by peppy it's never going to be open.

**Comment by peppy** [comment]
From my end it seems like we can go ahead with implementing this. @nanaya mentioned a few quirks with the current scopes and the `ack` requirement, but we can smooth those out as required.

**Comment by notbakaneko** [comment]
Just to set expectations here, the chat API won't be opened up to the extent of being used as a general chat interface - it's still intended to be for chatbots and lazer only.

**Comment by ThePooN** [comment]
That's kind of contradictory with the existence of the forums API endpoints.  
Web chat is here for end-users willing to chat without opening a client anyway, so I don't think that's an issue.

**Comment by ravener** [comment]
> Just to set expectations here, the chat API won't be opened up to the extent of being used as a general chat interface - it's still intended to be for chatbots (and the associated process around getting chatbot permissions) and lazer only.

Apologize if this is not the right place or time to ask this but will there be any plans to do so in the future? (i.e allow creating 3rd party chat clients without IRC)

**Comment by peppy** [comment]
Any API would be made mostly for the purpose of bots, not for creating third party chat clients (super out of scope of what osu! is, IMHO).

**Comment by Rekunan** [comment]
The biggest use for having those clients is to ref tournament matches without having to open up the game. Since you can do everything with mp commands, there's no need to waste resources on rendering the game, clutter up mp history's with 0 score from refs, etc.

**Comment by peppy** [comment]
> The biggest use-case for having those clients is to ref tournament matches without having to open up the game. Since you can do everything with mp commands, there's no need to waste resources on rendering the game, clutter up mp history's with 0 score from refs, etc.

We've already committed to adding such tools into the game client. If anything, external tools will likely interface with an osu!lazer instance running locally, rather than the API directly.

**Comment by Rekunan** [comment]
Ahh okay, makes sense then.
