### ISSUE TITLE
Allow multiple redirect URIs for an OAuth 2 application

### ISSUE THREAD

**Issue by MiraiSubject** [ppy/osu-web#10137]
Currently we're developing an application that is separated in a couple of different microservices. 

These all have authentication implemented using osu! in a different way due to structural differences, but we ran into a roadblock where only one Redirect URI is allowed in an application.

Maintaining multiple IDs and secrets in the environment is inconvenient but may also be confusing for users of the applications, considering they're part of a larger stack.  

Example OAuth 2 provider (discord) that does allows the same feature: 
<img width="916" alt="CleanShot 2023-04-17 at 14 46 57@2x" src="https://user-images.githubusercontent.com/803255/232488375-4ceb1d65-2166-40a0-b224-fb7722b3998d.png">

Having this implemented would certainly improve the developer experience for us. 

- co-signed by @omkelderman

**Comment by MiraiSubject** [comment]
Ah yeah you're right it works.

Setting my application callback URL to a comma-separated list like `http://localhost:8000/auth/osu/callback/,http://localhost:9000/auth/callback/` (note: no space between the entries) makes it usable for both redirect URIs.

FWIW it does overflow if used with many urls:
<img width="1055" alt="CleanShot 2023-04-20 at 12 19 42@2x" src="https://user-images.githubusercontent.com/803255/233337516-1af498cb-95bf-4543-8c52-2053c01fe62e.png">

**Comment by ThePooN** [comment]
> I haven't tried it but it may already work by specifying multiple urls separated by comma

I wasted HOURS implementing and testing authentication for Corsace website**S** through a single callback URL for nothing. Thanks XD
