### ISSUE TITLE
Add authorized scopes to the `oauth/token` API response

### ISSUE THREAD

**Issue by 112batuhan** [ppy/osu-web#10146]
The current response from `https://osu.ppy.sh/oauth/token` endpoint does not include scopes. This is especially needed for authorization code grant flow where the scopes can be manipulated in the browser URL. There should be a way to understand which scope accesses are granted during browser authentication.

We are developing a website with osu! v2 API's and currently there is no way for us to confirm the scopes without making additional API calls or coming up with workarounds.

**Comment by nanaya** [comment]
Technically it's already in the token (jwt) itself in the `scopes` field.

**Comment by 112batuhan** [comment]
When I first saw it, I also thought that it was a jwt. But I couldn't get it decoded. When I checked the laravel docs and the repo itself, I saw that the data is encrypted with key stored in the environment variables. So I don't think it's possible to decode the token as 3rd party.

**Comment by 112batuhan** [comment]
Ok thanks for the hints. I was tunnel visioned on the code that is given after the authorization code grant workflow. But the access token after the workflow is in fact decodable jwt.
