### ISSUE TITLE
add `limit` param to `/beatmaps/{beatmap}/scores` endpoint

### ISSUE THREAD

**Issue by tybug** [ppy/osu-web#10153]
Currently `/beatmaps/{beatmap}/scores` only returns the top 50 scores, with no way to adjust the number of returned results.

This would match api v1 behavior, which allows requesting top 100 scores with `limit=100`.

**Comment by notbakaneko** [comment]
This was already added #9983

**Comment by tybug** [comment]
huh, I even left a thumbs up on the linked issue. 

This parameter does still needs to be added to the docs though.
