### ISSUE TITLE
The [profile] BBCode box sometimes does not get parsed by BBCode

### ISSUE THREAD

**Issue by Paladynee** [ppy/osu-web#10158]
https://i.imgur.com/D6M3OIl.png

Happened for the second time today. I saved the .HTML of the broken thing, I can share if it's needed.

https://osu.ppy.sh/beatmapsets/1985112#osu/4129167

**Comment by Paladynee** [comment]
It gets fixed when I remove the 1 single space after `[/img]` and before `[profile]`. I can add it back and it wont be broken.

**Comment by tailsdk** [comment]
It happens when you upload the beatmap. Thats what breaks it.

**Comment by nanaya** [comment]
The bbcode parser on submission server needs updating.

**Comment by nanaya** [comment]
Tracking in #7051.
