### ISSUE TITLE
pp on lazer.ppy.sh doesnt match expectations due to lazer max combo discrepancy

### ISSUE THREAD

**Issue by dktharrop** [ppy/osu-web#10155]
Because lazer doesn't count sliderends for combo, scores on the experimental website calculate pp as if that combo was missing. 
[This is pretty much the same issue that happened on the results screen in the lazer client.](https://github.com/ppy/osu/issues/12542)

**Comment by peppy** [comment]
This will be fixed via other infrastructure components, as it is not handled by osu-web. It looks to have already been fixed osu! side, so that will propagate out to other places.
