### ISSUE TITLE
A strange error with the calculation of the place in the rating in the "Recent".

### ISSUE THREAD

**Issue by vetkover** [ppy/osu-web#10167]
10/5/2023 played a map with not the best result, but for some reason in the last activity "Recent" it was indicated that after playing took first place on this map. But in the Ranks menu in the First Place Ranks item nothing has changed and the value is 0.

Fetch result from osu.ppy.sh/users/32684847/extra-pages/recent_activity?mode=osu

`{"created_at":"2023-05-10T14:37:18+00:00","createdAt":"2023-05-10T14:37:18+00:00","id":787818877,"type ":"rank","scoreRank":"B","rank":1,"mode":"osu","beatmap":{"title":"tokiwa - Memoirs feat. Aitsuki Nakuru [Kujinn's Expert]" ,"url":"\/b\/3655549?m=0"}`

**Comment by nanaya** [comment]
That's what the database says and it's not generated by osu-web...

**Comment by vetkover** [comment]
I understand that this is information from the database, but I won’t write about it in the branch with the game itself

**Comment by peppy** [comment]
This looks like a very lucky (unlucky) case of a failure in response handling between microservices. I've added more safeties to hopefully avoid it happening in the future.

Luckily this doesn't affect anything but the event on your profile.
