### ISSUE TITLE
tempBubblesV2 is not embeded in the new lazer changelog

### ISSUE THREAD

**Issue by HoriKyoukosimp** [ppy/osu-web#10170]
i dont know if you do that on purpose or not but the tempBubbleV2.webm is not embeded like other video on changelog
![firefox_MLIegRzSm1](https://github.com/ppy/osu-web/assets/36318840/73576447-8238-4fde-9356-4afb0f6c3e1f)

same results on msedge (using chromium so i wont try another browser) and firefox

**Comment by Joehuu** [comment]
The video has been removed, see https://discord.com/channels/188630481301012481/188630652340404224/1106141194850926602.
