### ISSUE TITLE
imgur links don't embed in beatmap discussions anymore 

### ISSUE THREAD

**Issue by Aquaaaaaaaaaa** [ppy/osu-web#10192]
![image](https://github.com/ppy/osu-web/assets/95394229/17c8e677-80e9-41ce-9a06-5957d1885010)

it used to work before but now it just keeps loading, and yes i made sure i was formatting it correctly 

![image](https://github.com/ppy/osu-web/assets/95394229/4a77707a-2eb4-4285-a12a-5b7e918694ba)

don't think it's a me issue either since other image hosting sites work fine

**Comment by peppy** [comment]
imgur have changed their rate limit rules, and are likely not going to exist much longer (at least not in the way you want them to).

https://meta.discourse.org/t/imgur-images-not-embedding-with-429-error/263131

We've already investigated this and there's nothing we can do. Choose another hosting service.
