### ISSUE TITLE
Getting internal server error when trying to edit a post

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#10196]
I have been running a forum game since 2018 called "Thread Necromancy" ([link here](https://osu.ppy.sh/community/forums/topics/802725)). The objective is to get points with respect to how much time passes since the last post. The first post displays the leaderboard as well as historical winners, and it is updated upon every new post in the thread. 

Fast forward to today - I have started getting "HTTP 500 Internal Server Error" upon trying to edit the post. That one post has accumulated over 65,535 edits and I suspect the data structure used to store that value is 16 bit, leading to the failure.

**Comment by nanaya** [comment]
can either reset the counter for that specific post or increase the column size
