### ISSUE TITLE
pics on userpages broke

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#10195]
![oeXnRNy](https://github.com/ppy/osu-web/assets/32525896/979533a8-f24c-46a7-aa30-12e8bc6c6682)
![0e45KFN](https://github.com/ppy/osu-web/assets/32525896/6d7dc5a9-9a24-49dc-a094-28abe47fcc39)
doesn't matter when it got uploaded to file hosters, also not all of them

**Comment by RockRoller01** [comment]
cause of this is probably whats mentioned in #10192
