### ISSUE TITLE
Nominated beatmap difficulties disappeared

### ISSUE THREAD

**Issue by tailsdk** [ppy/osu-web#10223]
A beatmap that was nominated somehow had all difficulties deleted. 
It has been fixed now after an update to the mapset, but its still worth mentioning here since this is very bizarre bug.

Mapset in question https://osu.ppy.sh/beatmapsets/1965533#mania/4148473

Image of beatmap discussion 
![image](https://github.com/ppy/osu-web/assets/38273421/4251526d-4bee-4b54-a274-4ac75e61316d)

Image of beatmap page
![image](https://github.com/ppy/osu-web/assets/38273421/3bc49d7e-d7a8-40b0-be69-4e3a2fb12f83)

Image of the beatmap from their profile
![image](https://github.com/ppy/osu-web/assets/38273421/9c2c07ec-3979-476e-8eaf-fc26ae7baf0e)

**Comment by peppy** [comment]
Thanks for the report.

This sounds like the mapper made a mistake while submitting an update. Not sure this needs immediate action, but when I get to rewriting the beatmap submission system I'll make sure these kinds of issues are resolved.
