### ISSUE TITLE
Deleted user reappearing on leaderboards

### ISSUE THREAD

**Issue by willyosu** [ppy/osu-web#10224]
DeletedUser_613592, who was previously deleted under GDPR had many of their scores reappear on leaderboards around May 5, and have remained there since. Not sure what could have caused this.

![image](https://github.com/ppy/osu-web/assets/11691902/30a3d378-7a8b-4035-aedf-40cd1fe1852d)

Some maps where their scores are visible in the leaderboard:
* [Wing my Way](https://osu.ppy.sh/beatmapsets/12035#osu/46827) - [(score)](https://osu.ppy.sh/scores/osu/2787567360)
* [Science is Fun](https://osu.ppy.sh/beatmapsets/31071#osu/102290) - [(score)](https://osu.ppy.sh/scores/osu/2799422910)
* [Shiroi Yuki no Princess wa](https://osu.ppy.sh/beatmapsets/439609#osu/946082) - [(score)](https://osu.ppy.sh/scores/osu/3732540302)
* and more...

**Comment by peppy** [comment]
This is intentional and how we display deleted users. We recently fixed an issue causing a small number to not display.

This is the best we can do to preserve history of the leaderboards while also respecting privacy of users which want to be deleted from history.
