### ISSUE TITLE
Different scheme for username-based profile url

### ISSUE THREAD

**Issue by nanaya** [ppy/osu-web#10236]
The current url scheme of username-based (`/users/myname`) and id-based (`/users/123`) profile page being exactly the same has been causing headaches.

The current "solution" of `?key=id` gets verbose real quick especially when creating the links as it means we have to add that to every generated links that have known user id to prevent [this problem](https://github.com/ppy/osu-web/issues/9532#issuecomment-1555889832) from happening.

I'd rather have a different scheme for both. Something like `/users/123` for id (no change) and `/users/@myname` for username (prefixed with `@`) would help a lot.

For compatibility reason we can still support `/users/myname` but only if `myname` is not entirely numeric in which case it'll be strictly id lookup to prevent `/users/141` being a redirect to a different user id.

**Comment by peppy** [comment]
So basically in all places we want to link via username, we should add the `@` prefix to ensure it only matches on username even when numeric? This sounds logical.
