### ISSUE TITLE
Wiki search text box shouldn't have yellow border color when unfocused

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#10238]
I keep thinking that it's focused and type something but nothing is happening:
![XW4R3DQmUC](https://github.com/ppy/osu-web/assets/35318437/445dfbdf-c9f5-46d4-b045-93511165c6d2)

I would expect the same behavior as the text box in beatmap listing:
![x4nNzFgOG0](https://github.com/ppy/osu-web/assets/35318437/8efea9f7-4c25-46f1-a69c-820e7410c312)

**Comment by notbakaneko** [comment]
I think it makes sense to remove the outline or at least make it look less "highlighted" when not focused @arflyte

**Comment by peppy** [comment]
Agree with removing.

**Comment by frenzibyte** [comment]
Resolved in #11132
