### ISSUE TITLE
Add Country Rank for the user in RankingType "performance"

### ISSUE THREAD

**Issue by QamiKazu** [ppy/osu-web#10233]
Is it possible to add the Country Rank for the user in ranking type "performance" currently its not possible to get his/her countryrank.

**Comment by tybug** [comment]
While country_rank isn't included in the response of `/rankings/{mode}/{type}`, you can request against `/users/{user}/{mode?}` and check `user.statistics.country_rank` for each user to get this information.

**Comment by nanaya** [comment]
If it's on the global ranking, the values would be too expensive to compute at once. If it's on the country ranking, just calculate from current page number.
