### ISSUE TITLE
Remove "#" Symbol Requirement in osu Profiles for Discord Usernames

### ISSUE THREAD

**Issue by kesku** [ppy/osu-web#10257]
**Description:**
**Issue Overview**
Following the recent changes in Discord's username system, some users (like myself) are experiencing the removal of four-digit discriminators from their Discord usernames. However, osu profiles still enforce the inclusion of a "#" symbol in usernames, causing inconsistencies between users' Discord usernames and their appearance within osu profiles.t.

**Expected Behavior**
The expected behavior is that osu profiles should accurately reflect users' Discord usernames with or without the need for the "#" symbol. Discord usernames without four-digit discriminators should display as intended in osu profiles.

**Current Behavior**
Currently, osu profiles continue to enforce the inclusion of a "#" symbol in usernames, despite Discord's new username system no longer using four-digit discriminators. This results in the unnecessary presence of "#" symbols in osu profiles, leading to inconsistencies between users' Discord usernames and their appearance within osu profiles.

![image](https://github.com/ppy/osu-web/assets/62210496/00006ae9-a1f7-40c0-85cb-cb54f13630e8)
![image](https://github.com/ppy/osu-web/assets/62210496/06bcc665-98ca-4612-9484-cad72f0a31a0)

**Proposed Solution**
To address this issue, the following modification should be implemented in the osu client:

1. Update the osu profile system to remove the requirement for "#" symbols in usernames.
2. Adjust the profile display to accurately reflect Discord usernames without four-digit discriminators.

**Comment by tybug** [comment]
Of note, the discord username change rollout hasn't finished yet, so it's probably not a good idea to make any changes until it's finalized. As it will be wrong for some portion of users during that time no matter what osu-web displays.

[Discord claimed](https://discord.com/blog/usernames) the rollout will take "several months", starting a few weeks ago.
