### ISSUE TITLE
official beatmap mirrors are very slow

### ISSUE THREAD

**Issue by its0ka** [ppy/osu-web#10263]
![image](https://github.com/ppy/osu-web/assets/125186204/aea4efb1-50f8-451c-8b2c-5862201ad6be)
my internet isn't working well today and the official beatmap mirrors are unusable, https://osu.direct/ works much better
![image](https://github.com/ppy/osu-web/assets/125186204/53008a64-4750-49c4-a256-eafc0e0bca14)
@peppy please consider enabling tcp BBR (helps lossy networks) on servers or/and using cloudflare like http://osu.direct

**Comment by peppy** [comment]
Cloudflare has an arbitrary timeout on large files which causes download failures for slower connections (this used to be 60 seconds).

I've tested the mirrors and speeds are fine. Hopefully your routing will improve over the coming days.

**Comment by its0ka** [comment]
> Cloudflare has an arbitrary timeout on large files which causes download failures

@peppy, what size? i was able to download https://osu.direct/api/d/29157 for 2 minutes and 40 seconds without any issues by limiting speed to 5mbit/sec. Also cloudflare is much faster even on good internet, its a shame that only mirrors use it...

> I've tested the mirrors and speeds are fine

i met about 20 people who complained about the speed on official mirrors, but mirrors like http://osu.direct or google drive worked fine

what about bbr? @peppy, cloudflare already uses it. honestly i have never seen a server that is faster without cloudflare than with it

**Comment by its0ka** [comment]
i set my network card to 10mbit half duplex mode so download speed should be ~5mbit
![image](https://github.com/ppy/osu-web/assets/125186204/5ef430c0-f69b-4e2f-a64f-1cd6eb413321)
bm10 gives 2.5mbit/sec, bm4 is even worse with 2.2mbit/sec
![image](https://github.com/ppy/osu-web/assets/125186204/14567ce1-0082-4831-8ead-b121ac104717)
osu.direct  gives 4mbit/sec

**Comment by ThePooN** [comment]
Tentatively set the TCP congestion algorithm to BBR on bm7 and bm10, please let me know of any effect.

**Comment by its0ka** [comment]
@ThePooN as i can see, bm4 and bm10 are in the same data center, so i need to use them for proper testing. bm4 now has cubic and bm10 has bbr, right?
what commands did you use to enable bbr?
what's the os and kernel version there? bbr has several versions now and it updates with the kernel.

**Comment by ThePooN** [comment]
bm4, bm5 and bm10 are in the same city, you can indeed use them for comparison.

bm7 and bm10 are set to use BBR at the moment on kernel series 4.19 using:
```
sysctl -w net.core.default_qdisc=fq
sysctl -w net.ipv4.tcp_congestion_control=bbr
```
The rest is on cubic.

**Comment by ThePooN** [comment]
can't reboot on a whim. please let me know of any improvements

**Comment by its0ka** [comment]
downloading from bm10 is slower than downloading from bm4 at the moment by ~40%. can you revert bm10 so i can compare it with bm4?
default value of net.core.default_qdisc is fq_codel btw

**Comment by ThePooN** [comment]
Have reverted and will likely leave as is for now. Can't do much more atm, sorry

**Comment by its0ka** [comment]
@ThePooN average values from 20 downloads
bm4: 6.5MB/s
bm10: 2.9MB/s

**Comment by ThePooN** [comment]
These speeds are much better than what you first reported and are much better aligned with our expectations, not sure what there's to do here.

> also what about enabling cloudflare?

💸💸💸

**Comment by ThePooN** [comment]
BBR will only help stabilize it to a slightly higher and consistent speed. Yes we could work on it and further tune our settings, but at the end of the day it's not something we can reproduce or easily measure, plus internet conditions are always evolving, so we are literally working on a black box with pretty much no idea what we're doing at the moment, especially as you're not affected either.

If you come by an user with terrible download speeds, I'd be interested in [OVH speedtests](https://proof.ovh.net/) from them targetting Beauharnois, Limburg and Roubaix.

An actual solution would be to get a beatmap mirror in the region. If you know a community member in the region who would be willing to host one please have them reach out.

Regarding Cloudflare, beatmap downloads represent hundreds of terabytes of traffic every month and we doubt they'd serve it for free.

**Comment by its0ka** [comment]
@ThePooN "BBR will only help stabilize it to a slightly higher and consistent speed" - I hope you will change your mind after viewing the test results.

"it's not something we can reproduce or easily measure" - it's easy to simulate bad network conditions, i'll do it in my tests, there is no need to have a user with bad network (that's actually a bad idea because bad network changes its characteristics very often, test results are never the same).

below i used 2 linux VMs (kernel 6.1) on my pc to run tests, network latency and loss were simulated using [netem](https://srtlab.github.io/srt-cookbook/how-to-articles/using-netem-to-emulate-networks.html)


cubic tcp tests: `sysctl -w net.ipv4.tcp_congestion_control=cubic`
test 1: lossless network, almost 0ms of latency `tc qdisc replace dev enp0s3 root netem delay 0ms loss random 0%`
downloading a file of 123MB from one to another shows this
![image](https://github.com/ppy/osu-web/assets/125186204/74643137-98e4-4e2f-afba-f7621597bdce)
~570MB/s

test 2: lossless network, 100ms of latency `tc qdisc replace dev enp0s3 root netem delay 50ms loss random 0%`
![image](https://github.com/ppy/osu-web/assets/125186204/8a8ecb38-b84e-455f-a107-ab298d413a2b)
~11.4MB/s


100ms latency alone drops speed by a lot

test 3: 10% packet loss, almost 0ms latency `tc qdisc replace dev enp0s3 root netem delay 0ms loss random 5%`
![image](https://github.com/ppy/osu-web/assets/125186204/1c001976-12e3-4717-af6f-a50d3f8dfc5c)
~9.5MB/s

test 4: 10% packet loss, 100ms of latency `tc qdisc replace dev enp0s3 root netem delay 50ms loss random 5%`
![image](https://github.com/ppy/osu-web/assets/125186204/df422612-9bba-4ea8-aff0-815661686ec8)
<100KB/s and i stopped the download after 2 minutes

100ms latency + only 10% loss drops speed to unusable values (dropped for more than ~130 times, almost as bad as in my first post)

bbr tcp tests: `sysctl -w net.ipv4.tcp_congestion_control=bbr`
test 1: lossless network, almost 0ms of latency - same as cubic
test 2: lossless network, 100ms of latency `tc qdisc replace dev enp0s3 root netem delay 50ms loss random 0%`
![image](https://github.com/ppy/osu-web/assets/125186204/650ce698-4366-45d1-a713-6c4133ea2241)
~22.3MB/s (~2 times better than cubic)

test 3: 10% packet loss, almost 0ms latency `tc qdisc replace dev enp0s3 root netem delay 0ms loss random 5%`
![image](https://github.com/ppy/osu-web/assets/125186204/b96ebf5e-eaff-4a45-8643-9a9f2daccde6)
~146MB/s (~15 times better than cubic)

test 4: 10% packet loss, 100ms of latency `tc qdisc replace dev enp0s3 root netem delay 50ms loss random 5%`
![image](https://github.com/ppy/osu-web/assets/125186204/e5971c1f-5284-4027-aa0b-37a9b5cebb87)
~6.2MB/s (~73 times better than cubic)

bbr wins with a big margin


and just fyi, here is the comparison between non-cf and cf-enabled bm10.ppy.sh
`curl --output /dev/null "https://bm10.ppy.sh/xxx"`
![image](https://github.com/ppy/osu-web/assets/125186204/f751d3ab-8c12-4597-84a2-7d08d8b1ec7e)
`curl --output /dev/null "https://bm10.ppy.sh/xxx" --connect-to ::188.114.99.224` 188.114.99.224 is the cloudflare ip, it works because cloudflare already knows about your domain on their network
![image](https://github.com/ppy/osu-web/assets/125186204/3072ee51-6b50-4fd0-af57-5865bc6258cf)
cloudflare is ~4 times faster (their server has much less latency than my network, so it pulls the file fast, then it sends to me using bbr)

"An actual solution would be to get a beatmap mirror in the region" - it would help, but by so little, it's not worth it at all, better to look at CDN

"Regarding Cloudflare, beatmap downloads represent hundreds of terabytes of traffic every month and we doubt they'd serve it for free." - if you are on the PRO plan you can issue a ticket and ask them, it might be cheaper to have only 2 bm + cloudflare, than just 5 bm

i hope this doesn't go unanswered, thank you

**Comment by ThePooN** [comment]
> it would help, but by so little, it's not worth it at all, better to look at CDN

This approach is working well for us in Oceania. Besides, Cloudflare isn't well-implemented everywhere, for example access to their China network is available only to Enterprise+++++ customers. Even if a CDN might work well for Russia, this is a solution we need to keep in the long run, and while not excluding it, mixing both systems would require additional development while it's pretty easy to onboard a new mirror for us.

Not immediately working on beatmap mirrors atm but I'll make sure to look into TCP tunings again next time around.

**Comment by its0ka** [comment]
@ThePooN not sure about Oceania because i can't see any beatmap mirrors close to it, same for China, but anyway. i'm also not sure why you don't partner with osu.direct or other unofficial mirrors, but anyway.

> I'll make sure to look into TCP tunings

thanks a lot.

**Comment by its0ka** [comment]
@ThePooN anything new?

**Comment by ThePooN** [comment]
No, TCP tunings still cannot be applied to all mirrors. Also haven't heard of anybody offering a mirror in your region.

**Comment by its0ka** [comment]
@ThePooN osu.direct is technically in every region (except china) bc they use cloudflare.
if you can't enable bbr, another server with bbr and nginx caching proxy or just tcp proxy will work.
how much traffic do the servers use per month? what's the size of the beatmap library?

**Comment by ThePooN** [comment]
> if you can't enable bbr, another server with bbr and nginx caching proxy or just tcp proxy will work.
We can't afford this

> how much traffic do the servers use per month? what's the size of the beatmap library?

500Mbps and a few terabytes of storage in RAID1 would do. Doesn't have to be SSDs

**Comment by its0ka** [comment]
@ThePooN that's not what i asked, bandwidth is 500mbit/s, ok, what's the amount of data per month? 10tb, 50tb, 100tb? will caching proxy work? if you don't have a solution for it i can make one. and why are you ignoring all mentions of osu.direct? they clearly have the resources

**Comment by ThePooN** [comment]
Our mirrors have unmetered traffic so we don't keep track of that.

I did not ignore your proposal, I already told you months ago: CF will not handle all of osu!'s traffic for free.

**Comment by its0ka** [comment]
> we don't keep track of that

just run ifconfig and uptime

**Comment by peppy** [comment]
The speeds you report are already ample. Thanks for your input.
