### ISSUE TITLE
Update landing page video to use the new argon skin

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu-web#10275]
### Proposal

High quality (18 mb)

https://github.com/ppy/osu-web/assets/36758269/11511311-8af6-4fd6-9597-17e07425d42c

- Human gameplay
- Includes spinner
- Loops smoothly instead of the crossfade

### Attempted encoding

1. 1632x734 px `-preset veryslow -c:v libx264 -crf 36` (cropped from 1920x1080 recording, no scaling):

<details><summary>5.1 mb</summary>

https://github.com/ppy/osu-web/assets/36758269/f1ed00fd-0d6d-4312-a347-ba66b967558d

</details>

2. 1280x576 px `-preset veryslow -vf "scale=w=1280:h=576" -c:v libx264 -crf 32` (scaled to same width as original landing page video):

5.1 mb

https://github.com/ppy/osu-web/assets/36758269/d92484c3-d4e3-4b32-ba40-c64258526451

### How it looks

(second encoding)

![image](https://github.com/ppy/osu-web/assets/36758269/da5dabfb-888f-4d21-99c5-9cd5172ee547)

original

![image](https://github.com/ppy/osu-web/assets/36758269/f2af0498-18dc-4ad7-a043-3503ca3534b0)

### Potential improvements

As is, it's about the same quality as the original, but shortening it to 30 seconds allows for an increased bitrate as per [peppy's feedback](https://discord.com/channels/188630481301012481/188630616286167041/1116624380655570957). may need to remove the spinner if it feels too frequent, but will try both options

**Comment by peppy** [comment]
I still think reducing to 30s before attempting to improve the code is in our best interests. Both the old and the new look pretty bad at 5mb.

**Comment by nanaya** [comment]
just for reference, the video is configured through `LANDING_VIDEO_URL` env (default is `https://assets.ppy.sh/media/landing.mp4`).

**Comment by Walavouchey** [comment]
### 30s version

lossless high quality (144 MB):

https://wala.s-ul.eu/8J4mHoiq

<details><summary>unscaled 1660x746 `-preset veryslow -c:v libx264 -crf 28`:</summary>

https://github.com/ppy/osu-web/assets/36758269/edf681a6-f6a2-497b-8e39-6c297570b365

</details>

scaled 1280x576 `-preset veryslow -vf "scale=w=1280:h=576" -c:v libx264 -crf 24`:

https://github.com/ppy/osu-web/assets/36758269/2db98dc2-09d1-454e-8810-58094765811a

- having the spinner every 30 seconds feels ok-ish? will defer to another opinion, but without a spinner it'll be more effort to make a seamless loop
- i've adjusted the zoom and positioning to be almost pixel-perfect compared to the original
- both encodings here have pretty much the same file size, <0.5% bigger than the original landing page video. comparing with a magnifying glass, the scaled version seems *very slightly* better in quality to my eyes
- this time i've noticed to disable parallax like in the original
- also noticed my recording is slightly brighter at 50% dim, dunno about the original dim level but it probably doesn't matter

**Comment by peppy** [comment]
Looking really good.

**Comment by peppy** [comment]
I've updated the live version to use the scaled compressed iteration.

It may take a few hours to update depending on how long cloudflare decides to cache it.
