### ISSUE TITLE
Enable kudosu for replies that reopen others' resolved mods

### ISSUE THREAD

**Issue by kongehund** [ppy/osu-web#10270]
Currently, mods that were previously resolved by the mapper can be reopened by other modders if they think it is still an issue. It takes as much effort (or more) to reopen another mod and make an argument about it as it does to make a new mod, and if that effort ends up improving the map, it makes sense that it can be rewarded with kudosu. 

Here's an example of a mod with two high-effort reopening replies that improve the map, neither of which can be rewarded kudosu: https://osu.ppy.sh/beatmapsets/1980408/discussion/-/generalAll#/3723268

**Comment by tailsdk** [comment]
Its probably fine right now as it is since kudosu don't really have any use currently other than being a number on your profile. If they do get a use then yeah maybe this would be something to look into.

**Comment by kongehund** [comment]
There are minimum kudosu requirements for applying for BN though, so it does have some use, albeit small

**Comment by nanaya** [comment]
Seems like duplicate of #1892.

**Comment by cl8n** [comment]
^
