### ISSUE TITLE
Cannot play beatmap audio preview on firefox. 

### ISSUE THREAD

**Issue by peace20021** [ppy/osu-web#10277]
Like the title, for some reason osu web cannot play beatmaps audio preview. I'm wondering if this has a fix yet.

**Comment by Blooshing** [comment]
> Like the title, for some reason osu web cannot play beatmaps audio preview. I'm wondering if this has a fix yet. 

Can you link the beatmap in question? There are some beatmaps that use media files that aren't compatible with osu-web. I'm just curious to see if this is the issue

**Comment by peace20021** [comment]
It's actually the whole website, to be exact, I just searched Kairiki Bear
and play the top one. All of them doesn't play any sound at all.

**Comment by notbakaneko** [comment]
Going to need more information, works fine here on firefox.

**Comment by peace20021** [comment]
I can provide you, what information do you need?

**Comment by peace20021** [comment]
[image: image.png]
This is what it says on the console when I press preview songs.
Firefox browser 114.0.1 (64-bit)
Windows 10 22H2 19045.2965

**Comment by nanaya** [comment]
The attached(?) image doesn't show.

**Comment by peace20021** [comment]
![image](https://github.com/ppy/osu-web/assets/41183826/ce42b04b-a496-4582-94b5-69db8d4d0542)

**Comment by nanaya** [comment]
That looks like browser error. Does youtube or any other media play any sound?

**Comment by peace20021** [comment]
Yes, other websites play audio just fine.

**Comment by nanaya** [comment]
how about the preview file itself directly? (https://b.ppy.sh/preview/1765296.mp3)

**Comment by peace20021** [comment]
Interesting.
That doesn't run either.

**Comment by peppy** [comment]
I think we can close this. Seems like a system misconfiguration and out of our scope.

**Comment by peace20021** [comment]
Hmm seems like it's a Firefox thing, Firefox does not support above 192KHz audio format properly.

**Comment by peppy** [comment]
good thing we don't use that.
