### ISSUE TITLE
First Place Ranks not appearing on user profile

### ISSUE THREAD

**Issue by RhymesWithMash** [ppy/osu-web#10284]
I noticed my global number 1 on Ricky Bobby [[7K] mash's nm] (https://osu.ppy.sh/beatmapsets/1808528#mania/372193) has disappeared from my userpage "first place ranks" section (https://osu.ppy.sh/users/18834550). It was there a few days ago (around when I set the score). I'm still listed as number 1 on the leaderboard, and the "recent" section of my profile does not show that I've lost it. 
![image](https://github.com/ppy/osu-web/assets/74639253/106f2480-15ad-4cdb-bdd6-6f572e61161e)
Still first on the leaderboard:
![image](https://github.com/ppy/osu-web/assets/74639253/188f4159-7284-4ae0-9039-fd193b1e531d)
All activity since I set the first place rank:
![image](https://github.com/ppy/osu-web/assets/74639253/e06ffcb6-ae47-4c04-b162-b12a07e1d93e)

I have number 1 on the "hd" diff as well, and the difficulty in question is my own guest difficulty.

**Comment by Blooshing** [comment]
https://i.imgur.com/dsbHOcU.png it is infact there, not sure what happened but it is there now.
