### ISSUE TITLE
Mania's 4K/7K country leaderboards don't take banned players into account on your profile

### ISSUE THREAD

**Issue by Mortelspawn** [ppy/osu-web#10285]
Hi there,

I have noticed that when I look at my 4K rank on my profile, it is one rank lower than on the actual leaderboard page:
![image](https://github.com/ppy/osu-web/assets/16947102/e449c67c-260a-4b60-a333-2ab612d4c81c)![image](https://github.com/ppy/osu-web/assets/16947102/95a8f935-beb6-43ef-b42f-a3b2aab666ae)

We recently had a player who got banned for cheating that reached first in our country and it has been like that since then. So I'm wondering if this is caused by said banned player or the way it is shown on your profile.

I haven't seen it anywhere else so I don't know if it's been reported already so please excuse me if that's the case.

**Comment by tailsdk** [comment]
Its just that the 7k/4k rankings on profiles don't update that often if you look at your 4k rank compared to yetii on the profiles it is higher. It probably should update slightly more frequently, but its not the end of the world

**Comment by Mortelspawn** [comment]
It's not really annoying and I personnaly don't care that much but if we look the top 7K player in Belgium which is LoligodBE, it is shown he's ranked 2 in 7K on his profile though he's been first for a while now.

I do believe there's a problem somewhere, but it is worth looking into ? I'm not sure myself, just thought of reporting it.

**Comment by peppy** [comment]
It updates once a day FWIW.

I'm pushing out a fix for restricted users still taking up rank slots.
