### ISSUE TITLE
Allow escape in markdown for beatmap discussions

### ISSUE THREAD

**Issue by reealy** [ppy/osu-web#10302]
Currently, there's no way to properly escape a special markdown character like `\ `` * _ { } [ ] ( ) # + - . !`, with `\` which can create unintended italic texts, and lists for the more common cases.

**Comment by nanaya** [comment]
is it on review post? the escape works as expected on normal post

**Comment by reealy** [comment]
![](https://cdn.discordapp.com/attachments/1109937287468433549/1121496234922868917/image.png)

I really thought it wasn't working on a normal post, but maybe it was just me forgetting the backslash before the + when modding
But as you said, it doesn't work on review posts

**Comment by nanaya** [comment]
It's covered in issue #9867.
