### ISSUE TITLE
Lazer profile not updating for PP

### ISSUE THREAD

**Issue by ThaneGames** [ppy/osu-web#10315]
![image_2023-06-28_011002180](https://github.com/ppy/osu-web/assets/137976077/31f9cf44-6af8-49a3-a1b2-22cd238cd26c)
![image_2023-06-28_011101255](https://github.com/ppy/osu-web/assets/137976077/37a43cf4-42b1-47b5-893c-cd438b630b13)
![image_2023-06-28_011130625](https://github.com/ppy/osu-web/assets/137976077/71df83ac-5ac1-4341-a341-3ca344ecfbda)
ive been playing lazer for a month ish now, and my scores havent updated since the first few days of playing. i have hundreds of ranked scores worth 10-30 pp each and none have scored.

if anyone would like to give me some info or like help i would greatly appreciate

**Comment by ThaneGames** [comment]
> 

even with mods, will the score eventually update even after the reset?
like if i get more ranked scores after

**Comment by peppy** [comment]
We still need to go through mods and mark which are valid for PP.
