### ISSUE TITLE
Avatar image gap/display is broken / has regressed.

### ISSUE THREAD

**Issue by Blooshing** [ppy/osu-web#10318]
:sweat_smile: seems like osu-web is being weird with avatars. This is pretty much exclusively to the userpage. In the forums and elsewhere they seem to be fine.

![](https://puu.sh/JK9eU.png), ![](https://puu.sh/JKaCm.png)

seems to have a little black space on the top even if they are the right dimensions. 

Works fine on firefox and safari, but when on chrome it seems to be broken.

**Comment by nanaya** [comment]
I can't reproduce the problem on any zoom level on chrome 114
