### ISSUE TITLE
Turkey country name is displayed in Turkish with English settings

### ISSUE THREAD

**Issue by TechnoZamb** [ppy/osu-web#10310]
Why is Turkey the only country which name is displayed as its Turkish equivalent "Türkiye" instead of the English translation "Turkey" like for every other country?

**Comment by peppy** [comment]
https://en.m.wikipedia.org/wiki/Name_of_Turkey#:~:text=Official%20name,-Turkey%20adopted%20its&text=the%20Board%20on%20Geographic%20Names,understood%20by%20the%20American%20public.
