### ISSUE TITLE
Broken preview on a specific beatmap

### ISSUE THREAD

**Issue by soopax** [ppy/osu-web#10331]
https://osu.ppy.sh/beatmapsets/2016750#osu/4198674 – The preview on this beatmap doesn't play when clicked.

Here is a screenshot of the browser console:

![image](https://github.com/ppy/osu-web/assets/101510334/8fa082b2-3c51-47dc-b05a-88f8d695da9b)

This is also broken in the beatmap listing in osu lazer version: osu! 2023.621.0-lazer https://github.com/ppy/osu/releases/tag/2023.621.0

osu!lazer logs:

[database.log](https://github.com/ppy/osu-web/files/11945803/database.log)
[input.log](https://github.com/ppy/osu-web/files/11945804/input.log)
[network.log](https://github.com/ppy/osu-web/files/11945805/network.log)
[performance.log](https://github.com/ppy/osu-web/files/11945806/performance.log)
[performance-audio.log](https://github.com/ppy/osu-web/files/11945807/performance-audio.log)
[performance-input.log](https://github.com/ppy/osu-web/files/11945808/performance-input.log)
[performance-update.log](https://github.com/ppy/osu-web/files/11945809/performance-update.log)
[runtime.log](https://github.com/ppy/osu-web/files/11945810/runtime.log)

Edit: Another beatmap with the same problem: https://osu.ppy.sh/beatmapsets/153141#osu/376592

**Comment by peppy** [comment]
We have plans on reprocessing all beatmap previews in some future, which will probably handle edge cases like this.

**Comment by nanaya** [comment]
Combining all audio preview issues to #2748
