### ISSUE TITLE
Difficulty 'pills' in beatmap listing can be come too spread apart

### ISSUE THREAD

**Issue by Skubers** [ppy/osu-web#10333]
See the spread between pink-red pill and orange pill

![image](https://github.com/ppy/osu-web/assets/82095491/bf311972-2521-4ca6-8cfd-abe8e5aa1176)
![image](https://github.com/ppy/osu-web/assets/82095491/4bc4567f-eb68-4629-94ab-26e4571df5d7)

**Comment by notbakaneko** [comment]
Are you using a zoom scale other than 100%?

**Comment by Skubers** [comment]
Nope, all regular

**Comment by nanaya** [comment]
Zoom scale here includes OS level zoom (in windows, the one in display settings)

**Comment by Skubers** [comment]
ok, i had 125%, but i changed back to recommended 100% and still seeing these
![image](https://github.com/ppy/osu-web/assets/82095491/fdbbeb6b-6ba4-4f32-b845-6b730bb187d4)

**Comment by nanaya** [comment]
Yeah, those are aligned properly

![](https://s.myconan.tk/2023/07/i_view64_2023-07-04_18-26-21.png)

**Comment by Skubers** [comment]
OH, It's probably caused by my monitor's subpixel layout. Regular monitors have RGB layout, but my monitor has RWBG, so some pixels can be switched. My bad then!
