### ISSUE TITLE
[Question] Is a translation manager relevant for the website ?

### ISSUE THREAD

**Issue by leonekmi** [ppy/osu-web#1033]
Many people i know want to translate osu! website (because my translation/other translations is not perfect at all). I am ready to create a community-driven translation tool with votes and aprooval from admins.
If you accept, i plan to do my best (i learn actively Laravel).
_#893 was a test of my translation manager, but too much broke the comments, etc..._

> Also if you're suggesting usage of some kind of tool better suggest the tool itself instead of making pull request of its output.
-- nanya

I post this just here to ask reviews about my idea, so what do you think of that ?

**Comment by nekodex** [comment]
We're looking into third-party tools to do this right now but it's not something we want to build into the site.
