### ISSUE TITLE
About me, [img] bug

### ISSUE THREAD

**Issue by MeuhMeuh62** [ppy/osu-web#10358]
I can't see my pictures upload on category "about me" on my profile.
Video : https://youtu.be/FIqYci4soCY

**Comment by RockRoller01** [comment]
cause of this is probably whats mentioned in #10192

**Comment by MeuhMeuh62** [comment]
no sorry for me it's not working
![image](https://github.com/ppy/osu-web/assets/86471514/73db21c1-09c9-4035-a0b1-372786603995)
![image](https://github.com/ppy/osu-web/assets/86471514/e8dfd9e4-38e2-43b4-808d-ff0705770f66)

Idk why is only me? But now i change to other image hosting: GitHub, and it's work perfectly

**Comment by peppy** [comment]
This is probably since you edited and added imgur links quite recently. We'll eventually run the migration more often, but it was run a single time previously which probably didn't catch your profile.
