### ISSUE TITLE
Score without rank/grade

### ISSUE THREAD

**Issue by MaxOhn** [ppy/osu-web#10371]
There's this score https://osu.ppy.sh/scores/osu/151968 which has no rank so the api v2 just gives an empty string for the rank.
I'm not aware of any other scores like that but I imagine it's not the only one.

I figured ranks are fairly simple to calculate so maybe they can be added retroactively?

**Comment by cl8n** [comment]
idk the cause but will just add that Ivalset has this on their userpage

> Possessor of five invisible ranks.

so maybe you can ask them how that happened lol.

**Comment by MaxOhn** [comment]
Not sure about other scores with missing grades, if there are any, but at least the one I mentioned seems to be fixed.
