### ISSUE TITLE
I have played many map and most of them are ranked, but its seem i wont level up, but my pp still goin up

### ISSUE THREAD

**Issue by hduccv** [ppy/osu-web#10373]
so i have played the lazer for month, i notice that im not level up in lazer, i check both lazer.ppy and osu .ppy and still not be able to see my level, stucked in level 8, my pp from 50 to 143 and im still not level up, can someone could help me

**Comment by BioCla** [comment]
https://osu.ppy.sh/community/forums/topics/178611?n=1

https://osu.ppy.sh/wiki/en/Gameplay/Score
https://osu.ppy.sh/wiki/en/Performance_points

Levels are an old artifact of the game and don't necessarily record your skill/progression (that'd be PP, performance points) but how long you've been playing and how many maps you completed.

**Comment by peppy** [comment]
Was probably related to one of the issues we had over the last few weeks. I'm guessing things should look better for you now (as long as you're checking your lazer profile).
