### ISSUE TITLE
User profile badges render with low quality on macOS/iOS

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu-web#10376]
Apparently the website/browser always renders the `@1x` version, which looks awful:

![CleanShot 2023-07-16 at 12 57 09](https://github.com/ppy/osu-web/assets/22781491/7de7fb00-4f05-42e4-bad2-ed25b6eb37c1)

Here's how it looks by forcing all badges to `@2x`:

![CleanShot 2023-07-16 at 12 56 33](https://github.com/ppy/osu-web/assets/22781491/3eae157d-9de3-45b4-82fb-ee2a7287f966)

Can repro on both Safari & Firefox, at both my machine (M1 Pro) and my phone (iPhone 12).

cc @notbakaneko

**Comment by Hiviexd** [comment]
i highly suspect that @2x simply doesn't work at all in all platforms, i face the same issue with phones and my windows PC, it makes badges look extremely bad on anything above 100% zoom

**Comment by nanaya** [comment]
I think it was because at the time I wasn't sure if all the badges have 2x version.

I just checked it now and there are 543 badges currently missing the 2x version.
