### ISSUE TITLE
Add support for user initiated flag changes

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#10382]
We've now got the required data dating back 6 months, so we can add proposed support for flag changes.

## Data structure

```sql
root@db-master:osu> show create table user_country_history\G;
***************************[ 1. row ]***************************
Table        | user_country_history
Create Table | CREATE TABLE `user_country_history` (
  `user_id` int unsigned NOT NULL,
  `year_month` char(4) NOT NULL,
  `country_acronym` char(2) NOT NULL,
  `count` int unsigned NOT NULL DEFAULT '1',
  `last_updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`,`year_month`,`country_acronym`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='tracking user access from different countries for the purpose of country change requests'

root@db-master:osu> select * from user_country_history where user_id = 2;
| user_id | year_month | country_acronym | count | last_updated        |
|---------|------------|-----------------|-------|---------------------|
| 2       | 2302       | JP              | 23    | 2023-02-28 10:13:00 |
| 2       | 2303       | JP              | 19    | 2023-03-30 07:09:52 |
| 2       | 2304       | JP              | 2     | 2023-04-04 07:30:10 |
| 2       | 2305       | JP              | 24    | 2023-05-31 02:24:18 |
| 2       | 2306       | JP              | 21    | 2023-06-26 15:34:06 |
```

## Initial rules

A flag change can be initiated by a user when:

- There are 6 months of data
- At least 4 of the 6 months have logins from only one `country_acronym`, and all are the same `country_acronym`
- The user is not registered for any ongoing tournaments

We may relax or change this in the future.

## Proposed UX

Country change available:

![2023-07-18 22 41 48@2x](https://github.com/ppy/osu-web/assets/191335/52af9cfd-b8e6-40d1-9066-a6764203636f)

Country change unavailable:

![2023-07-18 22 39 23@2x](https://github.com/ppy/osu-web/assets/191335/315a9e1c-2c7d-40bf-9c11-6ae2875da557)

**Comment by notbakaneko** [comment]
> - There are 6 months of data
> - At least 4 of the 6 months have logins from only one country_acronym, and all are the same country_acronym

This means 6 months from the same country, right?

**Comment by peppy** [comment]
> This means 6 months from the same country, right?

Yeah, starting quite stringent, we'll see how things go.

**Comment by peppy** [comment]
> But what about some mainland Chinese gamers who have to open proxy software to play

We can't support such cases well, sorry.

**Comment by carsoon1** [comment]
Does login mean sign in to the site/game or does it mean just anytime I open the game

**Comment by peppy** [comment]
No further details are disclosed. Also it may change at any time.
