### ISSUE TITLE
Some pass medals are not on the correct column

### ISSUE THREAD

**Issue by wowcake** [ppy/osu-web#10383]
Event Horizon and Phantasm pass medals (the silver ones on the bottom) are in the FC column, where it should have been with the other pass medal instead.

![Screenshot_2023-07-18-21-52-36-702_com android chrome](https://github.com/ppy/osu-web/assets/76740201/953d48fc-aac4-40d9-979d-b81d9ce2fb6c)

**Comment by peppy** [comment]
Dunno, the `ordering` column seems to not be respected, and it's ordered by primary key or something?

**Comment by nanaya** [comment]
it's a bug in both code: ignoring order from backend; and database: both types have same ordering and progression.

**Comment by nanaya** [comment]
actually the code bug kinda saved the database bug. This is how the order looks when sorted by ordering and progression (instead of id as of currently)

![](https://s.myconan.tk/2023/07/firefox_2023-07-19_01-52-17.png)

**Comment by Ephemeralis** [comment]
The ordering for this category has been changed db-side using the following based on achievement `slug`:

```osu-combo-% = 0
osu-plays-% = 1
all-skill-% = 2
<mode>-hits-% = 3
<mode>-skill-pass-% = 4
<mode>-skill-fc-% = 5```

Should get everything looking vaguely logical when #10385 is applied. Someone may want to smack task-list-completed on that one, for what it's worth.
