### ISSUE TITLE
Old username still shown in recent activity after redacted

### ISSUE THREAD

**Issue by 0xallie** [ppy/osu-web#10392]
If someone changes their username and emails accounts@ppy.sh requesting their old username to be hidden, and it is approved, their old username may still be visible in recent activity like this:

> * [oldname] has changed their username to [newname]!
> * [oldname] has received the gift of osu!supporter!

I'm not providing a specific example publicly for privacy reasons, but I can provide one privately if needed.

**Comment by peppy** [comment]
I've fixed this in our tooling. If you or someone else has their old username still showing, please contact accounts@ppy.sh to get it removed.
