### ISSUE TITLE
O2i3 Featured Artist Page Obsolete Links

### ISSUE THREAD

**Issue by Glinte** [ppy/osu-web#10401]
@Ephemeralis 
Sorry if I shouldn't ping you but you seem to be the one responsible for FA related stuff.

https://osu.ppy.sh/beatmaps/artists/74
![image](https://github.com/ppy/osu-web/assets/96855131/7820968a-0e3d-4bd8-bbb2-78e06767af40)
Website and Twitter deleted. Soundcloud account still exists but no tracks can be found.

**Comment by Ephemeralis** [comment]
Confirmed the above and have nulled out the links for now.
