### ISSUE TITLE
Beatmap song preview error on Firefox

### ISSUE THREAD

**Issue by nyaruku** [ppy/osu-web#10403]
![grafik](https://github.com/ppy/osu-web/assets/38096703/581629b9-ded8-4a6f-ae0a-efe98e44b6b4)
Forum:
https://osu.ppy.sh/community/forums/topics/1165717?n=6
another image from the forum, displaying the error in english: https://imgur.com/a/pHwAZRz
a CORS header is missing, and i stumbled across the same error when developing something with API access, so it's easy to fix i would say

**Comment by nanaya** [comment]
Do you have any extensions installed? Have you tried disabling them? The player doesn't use anything which require cors.

**Comment by nyaruku** [comment]
> Do you have any extensions installed? Have you tried disabling them? The player doesn't use anything which require cors.

![grafik](https://github.com/ppy/osu-web/assets/38096703/f08b2b86-042b-408d-aa10-a8a43becb9e5)
only these

**Comment by nyaruku** [comment]
Edit: it was the Audio Equalizer blocking the audio playback
