### ISSUE TITLE
Display former country on profile like `formerly known as`

### ISSUE THREAD

**Issue by Kotoki1337** [ppy/osu-web#10411]
Implementing a feature that shows (temporarily?) the player's former country as well. There will be a lot of flag changes recently so this additional display will help other players identify them more easily, and it can also help players to help staff to make some abuse reports. But to maintain relevance, the display could be temporary and automatically disappear after a few months. So adding stuff like this can promote transparency while providing a useful reference for players and osu! staff.

**Comment by peppy** [comment]
This is already logged for internal use, but I don't see a need to make it public.
