### ISSUE TITLE
Optimize Regular Expression for Nested Square Brackets Matching

### ISSUE THREAD

**Issue by BioCla** [ppy/osu-web#10431]
In: `app/Libraries/BBCodeForDB.php`
```php
public function parseBox($text)
    {
        $text = preg_replace('#\[box=((\\\[\[\]]|[^][]|\[(\\\[\[\]]|[^][]|(?R))*\])*?)\]#s', "[box=\\1:{$this->uid}]", $text);

        return strtr($text, [
            '[/box]' => "[/box:{$this->uid}]",
            '[spoilerbox]' => "[spoilerbox:{$this->uid}]",
            '[/spoilerbox]' => "[/spoilerbox:{$this->uid}]",
        ]);
    }
```

The current regular expression used to match strings in the format [box=...] with nested square brackets is overly complex and can be optimized for both readability and performance. The regex is intended to handle nested square brackets inside the content of the box attribute.

Original: https://regex101.com/r/MffWRs/2
```
\[box=((\\\[\[\]]|[^][]|\[(\\\[\[\]]|[^][]|(?R))*\])*?)\]
```
Optimized: https://regex101.com/r/Rql6e7/7 
```
\[box=([^\[\]\\\n]+|\\.|\[(?1)*+\])*+\]
```

A side by side comparison, tested on the cases from the examples found in the code:
![image](https://github.com/ppy/osu-web/assets/81859084/184ecef1-c694-43ba-aeab-26d64fe0db65)
![image](https://github.com/ppy/osu-web/assets/81859084/18ea30a5-a61e-4df2-9985-24654ce08450)

> The extended version of the regex, and it's tests can be found in the aforementioned Optimization's link
> Showing it can also match on a vast scale of differently formatted title strings, without losing coherency

### Expected Benefits:
The optimized regex is easier to understand and maintain. It should also lead to improved performance as it avoids unnecessary backtracking and complexity associated with nested quantifiers.
The tests show an overall 91% improvement in efficiency on the operation.
The theta function has decreased to a linear function ~= T(n)

### Potential Concerns:
Regular expressions can still be limited when dealing with deeply nested structures. It's essential to ensure that this regex meets the specific requirements of the use case and doesn't introduce unexpected behaviors in certain edge cases.
For this reason I've replicated the tests from `tests/Libraries/bbcode_examples` in the unit tests section for each regex101 page linked above

Proposed Solution:
Replace the current regex with the optimized version provided above in the relevant codebase. Make sure to thoroughly test the updated regex with various input scenarios, including nested square brackets, to verify correctness and performance.

Sources:
https://www.php.net/manual/en/function.preg-replace.php
https://csunibo.github.io/linguaggi-di-programmazione/lucidi/07-analisi-lessicale-espressioni-regolari-dfa-nfa-1.pdf
https://csunibo.github.io/linguaggi-di-programmazione/lucidi/08-analisi-lessicale-espressioni-regolari-dfa-nfa-2.pdf
https://csunibo.github.io/linguaggi-di-programmazione/lucidi/09-analisi-lessicale-espressioni-regolari-dfa-nfa-3.pdf
https://csunibo.github.io/algoritmi-e-strutture-di-dati/lucidi/02-notazione-asintotica.pdf

**Comment by nanaya** [comment]
I don't know what the website is doing wrong but `[box=[\[] weird \[ title]box content[/box]` is supposed to match with current regex.

**Comment by BioCla** [comment]
> I don't know what the website is doing wrong but `[box=[\[] weird \[ title]box content[/box]` is supposed to match with current regex.

Backtrack here:
![Screenshot 2023-08-02 at 10 53 26](https://github.com/ppy/osu-web/assets/81859084/62fd7eb8-9f68-4cf6-af4e-8dc585462ca8)

**Comment by nanaya** [comment]
It's php string quoting behavior. The actual regexp is `\\[\[\]]`

**Comment by BioCla** [comment]
I was just trying to find some better solutions and came across:
![Screenshot 2023-08-02 at 18 02 28](https://github.com/ppy/osu-web/assets/81859084/8517e8e8-d753-4c00-a8f8-7db3da8cc12c)

**Comment by nanaya** [comment]
The original pattern wasn't even correct. I must've originally tested it against `[ some nested [ braces ] ]`, saw it worked, and then jammed it inside the full regexp without realizing `(?R)` makes no sense there.

**Comment by BioCla** [comment]
I've managed to hit a wall:
https://regex101.com/r/Rql6e7/6 (this one considers empty title, without `=`)
eg: 
```
[box]
```
and if you want to go even further beyond:
https://regex101.com/r/Rql6e7/7 (which consideres the fixed `=` like the original)
[box=]
```
