### ISSUE TITLE
Website doesn't show my stats 

### ISSUE THREAD

**Issue by Randomdudeeee** [ppy/osu-web#10432]
In the osu!lazer, it shows my current rank globally and and the country. It also shows other stats like my PP, recent completions, best performances, A completions, S completions, first rankings, and so on. However, in the website version, it only shows the PP count, hit accuracy, play count, total score, total hits, and maximum combo. The rankings are just - and other stats like the A scores are zero.

Here are my stats in the web:
![Screenshot (1160)](https://github.com/ppy/osu-web/assets/141294243/d9393f76-a07d-4aa2-aea0-2105100778ac)

Here are my stats in osu!lazer
![Screenshot (1163)](https://github.com/ppy/osu-web/assets/141294243/d82f100c-db9c-461b-8df6-f460efaedfaf)
![Screenshot (1164)](https://github.com/ppy/osu-web/assets/141294243/c328ce4d-986f-48ab-b5a4-0ec491b3f76c)
![Screenshot (1165)](https://github.com/ppy/osu-web/assets/141294243/975a70e9-728d-48cd-be4f-dd040185268f)
![Screenshot (1166)](https://github.com/ppy/osu-web/assets/141294243/df4c35ab-ae40-4f08-8490-be83d4ab34fe)

**Comment by nanaya** [comment]
lazer stats are currently visible on https://lazer.ppy.sh
