### ISSUE TITLE
"Show more" button moves while scrolling through profile page

### ISSUE THREAD

**Issue by TheRealStevie** [ppy/osu-web#10442]
https://github.com/ppy/osu-web/assets/75444413/e08e8efc-d013-485a-ad45-1c8fbe71b7e9

Edit: I don't know if this is intended behaviour but this differs from the lazer client.

**Comment by agatemosu** [comment]
That's a feature, only follows when you are in a list that can show more

**Comment by peppy** [comment]
Kinda weird it follows if there's still results to be seen below the fold 🤔

**Comment by nanaya** [comment]
the point is so you can scroll around and load more without having to move the mouse

**Comment by peppy** [comment]
Probably fine to close this if it's intended.
