### ISSUE TITLE
Suggestion: allow [youtube] tag in forums to parse full URLs

### ISSUE THREAD

**Issue by Corne2Plum3** [ppy/osu-web#10448]
Currently, to use the `[youtube]` to embed a YouTube video in the forums, you have to use *only* the video ID. For example, if the video URL is `https://youtu.be/dQw4w9WgXcQ`, then you have to keep only the `dQw4w9WgXcQ`, and remove the rest. 

On mobile, it's not very convenient, as when getting the video URL from the YouTube application, you get the full URL, and have to manually remove the rest of the link, and if you use a browser, extract the video from the URL at the bar isn't very convenient too.

Also, with the time I use the forums, I noticed that dozens of people who, when using the `[youtube]` tag, made the mistake of putting the full URL and not understanding why this is not working (the error displayed doesn't help.)

That's why I think, alongside with the ability to put videos ID inside the `[youtube]` tag, we should allows full URLs too, such as ```https://youtu.be/dQw4w9WgXcQ``` but also
```https://m.youtube.com/watch?v=dQw4w9WgXcQ``` (idk if there are other valid formats)

It will be more convenient to use, for both mobile and desktop users, and also less confusing. The implementation shouldn't be difficult, it's easy to differenciate a video ID and a full URL (for example, a YouTube video ID can't have a `/`)

**Comment by peppy** [comment]
I think it's probably fine to support both formats just to make things easier for users.
