### ISSUE TITLE
osu!lazer server takes an exceptionally long time to calculate pp score

### ISSUE THREAD

**Issue by ideaexplorer233** [ppy/osu-web#10456]
Description:
When I enable the Accuracy Challenge mod, the osu!lazer server takes an exceptionally long time to calculate the pp score.

My Situation:
As of the time of writing this issue, [this score](https://lazer.ppy.sh/scores/2378346948) has been stuck in the "calculating pp" state for the past 11 days. However, when I played the same map just now without the Accuracy Challenge mod enabled, the server was able to correctly calculate the pp. Examples of scores include [this score](https://lazer.ppy.sh/scores/2388216234) and [this score](https://lazer.ppy.sh/scores/2388191442).

Wider Scope:
This issue isn't limited to just a single map. I've encountered the same problem on other maps as well. For example, [this score](https://lazer.ppy.sh/scores/2382910046) and [this score](https://lazer.ppy.sh/scores/2387434605) also experienced exceptionally pp calculation times.

*My native language is not English. If there is any grammatical error here, please let me know so I can correct it.*
```[tasklist]
### Tasks
```

**Comment by peppy** [comment]
This was a temporary issue which has now been permanently resolved (the processor crashed a few time and wasn't setup to automatically restart; now it is).

**Comment by ideaexplorer233** [comment]
https://lazer.ppy.sh/scores/2400702298
I don't think it works. My old scores cannot be calculated, and this latest one is not working too.

**Comment by Joehuu** [comment]
See https://github.com/ppy/osu/discussions/23396#discussioncomment-5823849.
