### ISSUE TITLE
Migrations which upgrade `mediumint` columns to `int` do not have any effect

### ISSUE THREAD

**Issue by bdach** [ppy/osu-web#10453]
Originally reported [on discord](https://discord.com/channels/188630481301012481/188630616286167041/1139257326801530910).

It appears that since https://github.com/ppy/osu-web/pull/10247 (I've confirmed experimentally that it's since the laravel 10 upgrade specifically), migrations that upgrade/widen `mediumint` columns to `int` have stopped functioning correctly. One such instance is this:

https://github.com/ppy/osu-web/blob/36d197ddf7ffcbdea041c7a088ebd104042a0851/database/migrations/2015_01_01_133337_base_tables.php#L175

to this:

https://github.com/ppy/osu-web/blob/36d197ddf7ffcbdea041c7a088ebd104042a0851/database/migrations/2020_05_15_083037_sync_structure.php#L223

After running all migrations, the table should have type `int unsigned`, while in fact it appears to have type `mediumint unsigned`.

The direct implications of this are that:

- [test databases](https://github.com/ppy/osu-web/blob/master/SETUP.md#initializing-the-test-database) will not be consistent schema-wise with production
- in local setups, databases may fail to seed as the seeding data will not be insertable to tables due to columns being too narrow

[Here is a gist](https://gist.github.com/bdach/8d756f9bcaf8b42a4d2b587bb6695f27) with 2 excerpts of mysql statements executed during  captured using `general_log` while the aforementioned migration was running.

- On 2023.706.0 (last commit before merge of aforementioned PR) the column width changes are successfully generated
- On current master the column width changes are skipped entirely.

There are several threads of possibility where this might have broken (changes in dbal, laravel itself...) but given I know very little about the php ecosystem I'm not willing to hazard guesses or link any links.

It may be wise to run a full cross-check of test/local db schemas against production to make sure no other cases of such silent breakage have occurred somewhere else.

**Comment by nanaya** [comment]
Fixed in #10454
