### ISSUE TITLE
Country change tests fail without active solo scores schema

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#10466]
https://github.com/ppy/osu-web/blob/38cb333fd0a988abc40c68a970e282fee79e7960/app/Libraries/User/CountryChange.php#L40-L44

I didn't want to add the tests to EsSoloScores group since they're testing unrelated things. all the tests pass if you comment out that command, which is what I've been doing for now

**Comment by notbakaneko** [comment]
If it depends on solo-scores ES, then it should go in that group
