### ISSUE TITLE
Scores set on osu!lazer need to show settings used in mods

### ISSUE THREAD

**Issue by 0xallie** [ppy/osu-web#10471]
Sorry if this is already known, I couldn't find another issue for it.

For example [this score](https://lazer.ppy.sh/scores/2393070015) was done using HT 0.50x but it only shows as HT even if I hover over it.

**Comment by peppy** [comment]
We definitely need to look into exposing this in some way as we approach getting lazer more involved in leaderboards.

**Comment by nanaya** [comment]
An export of descriptive settings name is required for this.
