### ISSUE TITLE
Profile BBCode partially works

### ISSUE THREAD

**Issue by timelessnesses** [ppy/osu-web#10480]
When you trying to use Profile feature of osu's BBCode (ex [profile=8938068]ksenikust[/profile]) previewing it is fine but when it is updated on a beatmap description it did not formatted correctly.  
Preview:
![image](https://github.com/ppy/osu-web/assets/59832159/648ff43f-e9c5-4ff6-bca4-bff2b0b74c67)  
Updated beatmap description:
![image](https://github.com/ppy/osu-web/assets/59832159/ccdf12b5-ec4f-4680-b2d7-787209000ac3)  
Beatmap link: https://osu.ppy.sh/beatmapsets/2035084#osu/4242949

**Comment by nanaya** [comment]
is it when updated through web or client?

**Comment by timelessnesses** [comment]
through both osu and web

**Comment by nanaya** [comment]
can you try with web again?

**Comment by nanaya** [comment]
The save button doesn't actually do anything if it's exactly the same content as the original. Otherwise it looks like you're hitting the bug #7051.
