### ISSUE TITLE
User can't nominate map whose first nomination is from a NAT member with no assigned mode

### ISSUE THREAD

**Issue by pishifat** [ppy/osu-web#10481]
this map for context: https://osu.ppy.sh/beatmapsets/2015526/discussion/-/generalAll#/3885752

i'm in the NAT with no assigned mode, which *should* allow me to nominate maps in any mode. i nominated the map above, but the user who plans to give the map its second nomination sees this:

![Screenshot_20230819-235708](https://github.com/ppy/osu-web/assets/31551350/a3edfe2d-5789-41a5-8708-282ca827b5ba)

they're a BN for the correct game mode

**Comment by nanaya** [comment]
are they full bn? can they qualify any other maps?

**Comment by pishifat** [comment]
yes and yes
