### ISSUE TITLE
Beatmap has a 2-minute preview point

### ISSUE THREAD

**Issue by Hiviexd** [ppy/osu-web#10497]
reported in [#osu-web](https://discord.com/channels/188630481301012481/188630616286167041/1145183714272366682)

beatmap: https://osu.ppy.sh/beatmapsets/1956190#osu/4052446

seems very unintentional considering that all preview points are supposed to be 30 seconds at most

**Comment by peppy** [comment]
Dunno, it's 320kbit and 48khz and outside of expectations. We eventually plan to upgrade the audio preview generation system and at that point it'll probably get fixed.

Not worth tracking for this case IMO.
