### ISSUE TITLE
Incorrect `has_replay` value in `solo_scores` for overwritten replays

### ISSUE THREAD

**Issue by Magnus-Cosmos** [ppy/osu-web#10515]
[`2400443387`](https://osu.ppy.sh/scores/2400443387) shows a download replay button (meaning `has_replay` is `true`):
![image](https://github.com/ppy/osu-web/assets/39173355/101753dd-8dfb-42af-80d6-88318ae1d3f8)
But when clicking the download replay button, an error occurs (since this play has been overwritten by [`2406024684`](https://osu.ppy.sh/scores/2406024684) and no longer has replay data):
![image](https://github.com/ppy/osu-web/assets/39173355/066d426c-f652-470f-be6d-9e138321b58a)

**Comment by peppy** [comment]
In this kind of case the score would usually not exist at all. This will be covered by the cleanup process which is already implemented but not running yet (see https://github.com/ppy/osu-queue-score-statistics/pull/144)
