### ISSUE TITLE
Change to Country section on Rankings page

### ISSUE THREAD

**Issue by Bubbleman532** [ppy/osu-web#10525]
Right now, the country page lists each country and rankes them according to the cumulative sum of pp achieved by members with the country flag. This offers no information apart from which countries have the most users.

![image](https://github.com/ppy/osu-web/assets/117375368/bed3199e-b712-43fd-ba72-f288ed492723)

My suggestion is to change the way this page works. Countries should be ranked by the weighted sum of their players' pp values, in the same way as players are ranked by the weighted sum of their scores' pp values. To elaborate, the rank 1 player in a country should contribute 100% of their pp to the country's total, the rank 2 contributing 95% etc etc down to a suitable value, possibly even just top 100.

![image](https://github.com/ppy/osu-web/assets/117375368/bd5fd530-4923-428e-b3f8-a6a1668557d0)
(ignore central column - the value being sorted is the right-most one)

This in my opinion would bring a greater sense of community to the country ranking boards, and can lead to community efforts such as attempting to gain ranks on this board instead of only for solo goals.

Other metrics can still stay visible, and I can see that this _could_ be confusing for newer players, however it would be an immensely cool metric to have access to on the main site and gives a greater purpose to this country ranking page.

**Comment by peppy** [comment]
I think this sounds fine to be implemented.

**Comment by nanaya** [comment]
Just need to decide on the formula.

Using the same one as user pp (`f(x) = 0.95^x`) means the lower ranked people will have way less influence compared to the top 30-ish.

An alternative is a linear one like `f(x) = 1-0.01*x` to account top 100 in linear fashion. 1st rank counted 100%, 50th counted 50%, etc.

**Comment by peppy** [comment]
Shot a quick poll to see what people think: https://twitter.com/ppy/status/1707702245712974039

**Comment by Bubbleman532** [comment]
> Just need to decide on the formula.
> 
> Using the same one as user pp (`f(x) = 0.95^x`) means the lower ranked people will have way less influence compared to the top 30-ish.
> 
> An alternative is a linear one like `f(x) = 1-0.01*x` to account top 100 in linear fashion. 1st rank counted 100%, 50th counted 50%, etc.

I'm in favour of testing out other formulas but in theory lower ranks having lesser influence causes the leaderboard to become a more accurate top-level power ranking where things like OWC are concerned, the weighting dropoff could come slower but I don't know how well linear would work (USA would be unassailable simply because of how many players they have now and the leaderboards simply wouldn't change much - if at all - from what they represent already)

**Comment by WitherFlower** [comment]
This might be out of scope for this issue, but i would like to suggest changing the ranked score column to actually function like ranked score, that is only consider the best play of any player in each country on every difficulty. Put another way, that'd be equal to the sum of all national #1s. That'd make the metric more interesting than just being yet another multiple of the country's player count.
