### ISSUE TITLE
State of the feature requests forum

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#10521]
I was linked into a topic of the [feature requests forum](https://osu.ppy.sh/community/forums/4) earlier, and can't help but notice this forum has been in a state of [not being actively read by developers](https://osu.ppy.sh/community/forums/topics/962192) for many years now, probably since even longer ago than that post. browsing around, many of the topics just get replies redirecting them to one of the github repos instead, many of them get no replies, and the forum overall doesn't appear to be actively managed. the whole star priority thing seems kind of pointless these days too, if it's not helping to actually prioritize anything.

if there is not a foreseeable future where developers will actively address that forum, or at least where someone can curate that forum into meaningful requests to developers, I think it should be made read-only.

**Comment by peppy** [comment]
thanks for bringing this up!

the hope of leaving it open is that the portion of the community that are scared of github have somewhere to voice their requests.

not sure it needs to be read only. will take a look when i have some time and assess the situation.

will close this for now as i've added this to my own todo list and its not really an osu web issue.
