### ISSUE TITLE
add comments to a score page

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu-web#10539]
It's kinda strange that we don't have them yet, since `Changelogs`, `News` and `Beatmaps` already have them.
I am talking about this page: https://osu.ppy.sh/scores/taiko/180719159

**Comment by cl8n** [comment]
imo the view is too out-of-the-way to warrant its own comments section. most of the time I'm looking at scores on the website, it's via beatmap leaderboards, where I already have enough info and so don't bother to visit the actual score page. in fact that seems to be where people comment about notable scores already

**Comment by cyperdark** [comment]
👍
