### ISSUE TITLE
The mode field is null on beatmap object if mode_int is unknown.

### ISSUE THREAD

**Issue by ilsubyeega** [ppy/osu-web#10537]
Current docs shows that mode is not nullable: https://osu.ppy.sh/docs/index.html#beatmapcompact
Rather than putting a PR in the documentation, I'm adding this as an issue because I think there's a better way to handle it.

/api/v2/beatmaps/1482781
```js
{
  "beatmapset_id": 700402,
  "difficulty_rating": 4.53,
  "id": 1482781,
  "mode": null, // <--- Null
  "status": "graveyard",
  "total_length": 91,
  "user_id": 7726082,
  "version": "Snowflake",
  "accuracy": 8,
  "ar": 9,
  "bpm": 166.06,
  "convert": false,
  "count_circles": 234,
  "count_sliders": 40,
  "count_spinners": 3,
  "cs": 4,
  "deleted_at": null,
  "drain": 5,
  "hit_length": 85,
  "is_scoreable": false,
  "last_updated": "2017-12-01T03:25:33Z",
  "mode_int": 4, // <-- ruleset_id is > 3.
  "passcount": 1,
  "playcount": 6,
  "ranked": -2,
...
```

```
  "mode": null, // <--- Null
  "mode_int": 4, // <-- ruleset_id is > 3.
```

**Comment by cl8n** [comment]
support for more online rulesets/gamemodes is planned but hasn't made much progress yet.

in this case, it's more concerning to me that this map was processed and given an ID at all...

**Comment by peppy** [comment]
I've deleted these beatmaps and will add rules to avoid uploads of similar cases.
