### ISSUE TITLE
Add `type: lazer_score` to scores api v2

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu-web#10551]
`/users/{user}/scores/{type}` already have field `type`, why there cannot be a `type: "lazer_score_osu"`, instread of `type: "score_osu"` for lazer score, like sometimes people play maps with DT and use `Difficulty Adjustments`, but it not visible in api and bots calculate it as normal DT score, Which ends up posting scores like it from stable and making people confuse

![1694533538_Z50ijFGrc2](https://github.com/ppy/osu-web/assets/21735205/f988bf9f-7a51-47c8-9009-b0129926f0d6)

**Comment by peppy** [comment]
Going forward, the best way of finding lazer scores will be looking for scores without the "classic" mod. Things should be coming together soon to allow this. I don't think we'll be adding any stop-gap measure like proposed here until that happens.
