### ISSUE TITLE
Api `/users` doesn't return statistics for `4k` and `7k`

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu-web#10556]
Recently i started tracking other modes, as well as `4k` and `7k` for mania, but today i discovered that they are not separed in `/v2/users`. Which is strange

```json
[
  {
    "avatar_url": "https://a.ppy.sh/25426411?1693932430.jpeg",
    "country_code": "AR",
    "default_group": "default",
    "id": 25426411,
    "is_active": true,
    "is_bot": false,
    "is_deleted": false,
    "is_online": true,
    "is_supporter": false,
    "last_visit": "2023-09-13T19:05:13+00:00",
    "pm_friends_only": false,
    "profile_colour": null,
    "username": "Focoo",
    "country": {
      "code": "AR",
      "name": "Argentina"
    },
    "cover": {
      "custom_url": "https://assets.ppy.sh/user-profile-covers/25426411/e5dd2a10bba3df3485c36526f65e2343d3394cf153a8dfda64e2343c73b88785.jpeg",
      "url": "https://assets.ppy.sh/user-profile-covers/25426411/e5dd2a10bba3df3485c36526f65e2343d3394cf153a8dfda64e2343c73b88785.jpeg",
      "id": null
    },
    "groups": [],
    "statistics_rulesets": {
      "osu": {{ ... },
      "taiko": { ... },
      "fruits": { ... },
      "mania": {
        "count_100": 3962603,
        "count_300": 30832415,
        "count_50": 215795,
        "count_miss": 880582,
        "level": {
          "current": 97,
          "progress": 69
        },
        "global_rank": 1000,
        "global_rank_exp": null,
        "pp": 11424.4,
        "pp_exp": 0,
        "ranked_score": 1041730399,
        "hit_accuracy": 97.1972,
        "play_count": 24230,
        "play_time": 2529457,
        "total_score": 11588865718,
        "total_hits": 35010813,
        "maximum_combo": 19289,
        "replays_watched_by_others": 2,
        "is_ranked": true,
        "grade_counts": {
          "ss": 6,
          "ssh": 0,
          "s": 809,
          "sh": 3,
          "a": 258
        }
      }
    }
  }
]
```

**Comment by cyperdark** [comment]
same goes for `/users/{user}/{mode?}`. I guess we can add same query parameter `variant` as in `/rankings/{mode}/{type}`
![image](https://github.com/ppy/osu-web/assets/21735205/5f54e8d3-310e-41b3-8fbb-dd7cc03d263c)

**Comment by cyperdark** [comment]
any updates on this one?

**Comment by cyperdark** [comment]
hello, any updates on this one?

**Comment by cl8n** [comment]
> same goes for `/users/{user}/{mode?}`

variants are already included in this one, when the requested or default mode is mania. do you need more info than is provided there?

for `/users`, seems fine to me to add it considering all modes' statistics are already returned there :thinking:

**Comment by cyperdark** [comment]
> variants are already included in this one

wait, i guess i missed the time when it was added, can i know when it was added? because 3 weeks ago it wasnt there
<br>
>do you need more info than is provided there?

current is enough
<br>

> for /users, seems fine to me to add it considering

~`statistics_rulesets.mania.variants`?~ nvm, you already added it


<br>
Also, since we talking about api, would be possible to add `country_rank` to `v2/rankings/osu/performance`?
it's kinda bad to not have it there, because in order to get it you need to make another call to `user profile`, which increase amount of api requests for site like https://osudaily.net/, and other stats related sites, and by adding this field it'll reduce usage a bit

**Comment by cl8n** [comment]
> would be possible to add `country_rank` to `v2/rankings/osu/performance`?

maybe... it's expensive to calculate, but there was also a "request cost" mechanism added to the API for situations just like this. please open a separate issue though. in your case, I think #9637 would also be sufficient to reduce calls

**Comment by cyperdark** [comment]
ah, i thought it's stored like a property in user schema, then will stick with requesting user profile instead
