### ISSUE TITLE
header-v4 box shadow is inconsistent across different pages

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#10579]
compare:
https://osu.ppy.sh/beatmapsets/events - box shadow below first header
https://osu.ppy.sh/beatmaps/artists - box shadow is covered by the second header, so it's only visible further to the left and right

most pages end up looking like the latter, which imo is the better option. I think the header should be updated so that this shadow will always be covered by the following content

honestly all of the box shadows that overlap contents of `osu-page`s look weird to me but maybe that's a bigger/separate issue :thinking:

**Comment by nanaya** [comment]
I don't think the first one was even intentional. When everything were relative positioned, the shadow was not visible except very slightly on the outside page area. That box shadow can probably just be removed.
