### ISSUE TITLE
wiki page

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-web#1060]
![image](https://cloud.githubusercontent.com/assets/18349191/24579918/905863e6-1731-11e7-9678-7b2fca0fdff6.png)
![image](https://cloud.githubusercontent.com/assets/18349191/24579922/9fb88f78-1731-11e7-9453-b713c4508bf6.png)
we can see those words and images are out of the container

**Comment by benpigchu** [comment]
![image](https://cloud.githubusercontent.com/assets/9023067/24585928/926d1a72-17c8-11e7-9661-afce0dee0913.png)
【
The issue is caused by this long link
】

**Comment by kj415j45** [comment]
:thinking: will check it

**Comment by benpigchu** [comment]
【
add a `width: 100%;overflow-wrap: break-word;` to the `.wiki-page__content` seems fix this issue
】
