### ISSUE TITLE
Provide `/scores/catch/<id>` as an alternative to `/scores/fruits/<id>`

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-web#10616]
`fruits` is outdated terminology that is slowly being phased out of existence, and lazer makes strides to not refer to it except when absolutely necessary, preferring the `catch` term instead.

**Comment by nanaya** [comment]
I forgot about that and it's fruits in a lot of places in osu-web...

**Comment by smoogipoo** [comment]
It’s a personal UX issue that only affects me while typing it in the URL bar. It doesn’t affect any tool I have or something like that. So it’s not a big deal if this isn’t a simple as a redirect :)

**Comment by peppy** [comment]
I think last time we discussed this we were going to wait until rulesets became more of a "thing" and switch then.

But I don't see harm in getting this one right in the mean time. If we do make this change, `fruits/` URLs should redirect to `catch/` which would be the new "correct" endpoints.

**Comment by nanaya** [comment]
The endpoint has been added although without redirect. The endpoint itself should probably be deprecated anyway (and redirect to `/scores/<id>` instead) so no need to add redirect for this one? 🤷  

(feel free to reopen if the redirect should be added anyway)
