### ISSUE TITLE
"Failed to save post" when attempting to post to the timeline of a nominated map - beatmap discussions

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#1061]
https://puu.sh/v715n/5d3d9d51e0.jpg

Attempting to post to the timeline of beatmap that is currently nominated (https://new.ppy.sh/beatmapsets/527051/discussion as of the time of posting) does not function.

Posting in General does.

**Comment by nanaya** [comment]
Seems working...?

**Comment by Ephemeralis** [comment]
Odd. It definitely wasn't last night.

I'll close for now and reopen if it reoccurs.
