### ISSUE TITLE
`deleted_at` field on beatmap/set seems useless as it always set null.

### ISSUE THREAD

**Issue by ilsubyeega** [ppy/osu-web#10636]
I cannot find a non-null value for the 'deleted_at' field in the following cases
- valid beatmapset: [3](https://osu.ppy.sh/beatmapsets/3)
- deleted with takedown: [1116713](https://osu.ppy.sh/beatmapsets/1116713)
- deleted with full afk: [1912886](https://osu.ppy.sh/beatmapsets/1912886)

I believe the following beatmapset has a `deleted_at` field, but I think that public users cannot access this beatmapsets as this throws 404.
- deleted beatmapset that shows 404: [2065985](https://osu.ppy.sh/beatmapsets/2065985)

So, I believe that the `deleted_at` field should only be accessible to internal usage, so it would be better to mark it as an optional field instead of nullable.

**Comment by nanaya** [comment]
I haven't checked it but I think it may be visible on discussion endpoint. At any rate, the documentation is correct and the attribute is used by osu-web frontend.
