### ISSUE TITLE
Beatmap title text allegedly cannot be changed by NAT, and cannot be changed by beatmap hosts

### ISSUE THREAD

**Issue by RoxieWattz** [ppy/osu-web#10643]
According to one member of the NAT (who I will keep anonymous), The beatmap title text (the flyover text for online beatmaps on osu!stable) cannot be changed by NAT on the new website, and can't be accessed on the old website as it is now read-only.

I think a string editor or perhaps even a graphical editor that beatmap hosts could also access would be great. I know this is kind of requesting a feature, but the bug lies in functionality that doesn't exist anymore that used to exist.

**Comment by peppy** [comment]
This is deprecated functionality, intentionally not editable anymore.

We may reconsider it in the future, but it was historically only used in older beatmaps. It's unsure whether this will be reimagined in lazer.
