### ISSUE TITLE
Only top 5 best performance can be seen

### ISSUE THREAD

**Issue by ThePooN** [ppy/osu-web#10642]
For some reason, the "show more" button is missing on [DeathxShinigami's osu!catch user profile](https://osu.ppy.sh/users/49516/fruits) under Best Performance, despite the count showing 100.

**Comment by peppy** [comment]
Should be fixed now.

This can happen if a user has been inactive for a very long period (last pp reprocess skipped such users). For reference, you can fix this in the future using the `.reindex <user_id>` command.
