### ISSUE TITLE
Random `#` character in recent activity

### ISSUE THREAD

**Issue by amnezziaa** [ppy/osu-web#10656]
When looking at players recent activity in certain laguages there is a random `#` character in front of rank that shouldn't appear.

Example with `french` as a selected language :
![image](https://github.com/ppy/osu-web/assets/94064103/d1871751-6aaa-4b8e-b2e7-5297003c02dd)
Example with `spanish` as a selected language : 
![image](https://github.com/ppy/osu-web/assets/94064103/188e1384-e162-49c3-944b-a2bc3e21aee6)
This behaviour doesn't appear with `english` as a selected language:
![image](https://github.com/ppy/osu-web/assets/94064103/042003fb-6458-4207-8a63-9c9f3acac1dd)

Please note that `french` and `spanish` are not the only languages where I noticed the behaviour, there is more than that.

**Comment by agatemosu** [comment]
I have fixed it on crowdin for:
catalan
spanish
french
portuguese
portuguese (brazil) <- need a vote
