### ISSUE TITLE
Prevent qualified maps with open issues/suggestions from getting ranked

### ISSUE THREAD

**Issue by tailsdk** [ppy/osu-web#10654]
While most issues are currently resolved before maps get ranked sometimes a few maps slip through and either never get to apply the suggestion/issue or has to be unranked.

The solution to prevent this from happening is to prevent maps with suggestions/issues from being ranked until the posts have been resolved either by the original poster or an NAT (the NAT will make sure that these posts get resolved)

**Comment by notbakaneko** [comment]
Shouldn't qualified maps with issues that should prevent them from being ranked be disqualified in the first place?

**Comment by tailsdk** [comment]
yes, but sometimes there may be discussion ongoing and the time just runs out. This just ensures that this doesn't happen

**Comment by peppy** [comment]
@ppy/team-web please prioritise this one! already been agreed on by the team.

**Comment by cl8n** [comment]
do you want this to apply to posts by anyone or only posts by BNs?

also, can it be clarified what relation this has to #4405 ? it sounds like Suggestion posts should get this blocking behavior, but do you also want to change Problem posts to that, or leave them as-is (disqualify on BN post)? I ask because I was talking to Hivie about this and our conclusion at the time was more like the former, based on all the continued concerns raised in 4405.

**Comment by tailsdk** [comment]
Anyones posts the person shouldnt matter. Its just to prevent having awkward moment where a map got ranked with open suggestions either because the  BN forgot or the mapper didnt have time to go look yet

As for the second question unsure as we havent discussed it. I would leave as it is now. A lot of non BNs also post problems as suggestions because they are unsure if its actually a problem.

**Comment by peppy** [comment]
Yep, should be prevented by any kind of post. They can easily be resolved if non-important.

It shouldn't reset the position in queue.

**Comment by Hiviexd** [comment]
one thing i want to request regarding implementation is if the beatmapset api response could have some sort of clear indication/flag that a map is in a blocked state, that would make things easier in terms of internal tooling (specifically what we'll make to get notified of any blocked maps)

maybe it could even have its own filter in the beatmap listing?

**Comment by notbakaneko** [comment]
So unresolved suggestions and problems should block?

**Comment by tailsdk** [comment]
Yep
