### ISSUE TITLE
Featured Artist tag not being removed upon changing artist and title

### ISSUE THREAD

**Issue by BigbyWJ** [ppy/osu-web#10653]
If a featured artist song is uploaded and the map is updated to another artist and title, the featured artist tag does not get removed.

**Comment by cl8n** [comment]
I think most artist and title changes are just corrections though and aren't intending to actually change what song it's referring to. probably better to request to remove these on a case-by-case basis

**Comment by peppy** [comment]
Please provide context.

**Comment by BigbyWJ** [comment]
Yeah it seem like a niche issue, I can link where i spotted it https://osu.ppy.sh/beatmapsets/966081

The original artist was a featured artist, but when it gets replaced the link to the featured artist still stays
