### ISSUE TITLE
Double-clicking wiki link before fully loading prepends higher-level paths

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#10662]
Kind of a weird bug, but users with poor network / are impatient will probably click the link again and encounter this. Needs a 2+ level link (i.e. `Client/Installation`) and clicking it more just prepends more higher-level paths. Tested on firefox and safari.

https://github.com/ppy/osu-web/assets/35318437/f2d282cf-7891-477f-baa3-3a9f814f305a

**Comment by lnd1** [comment]
Sorry for my copy ticket. I tried looking for any already existing tickets on the same problem. But I didn't know what it would be called. And I didn't know how to filter through all the different tickets to find it.

**Comment by respektive** [comment]
While I can't replicate the original issue in the video, I just happened to accidentally run across this in the index page the OWC. So this doesn't seem to be completely fixed.

https://github.com/ppy/osu-web/assets/22381687/834a0751-d01a-4ecc-871f-34f9dbb2d9ff

**Comment by Joehuu** [comment]
Superseded by https://github.com/ppy/osu-web/issues/11384.
