### ISSUE TITLE
Beatmap contest entry titles should be clickable

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu-web#10673]
[example listing](https://osu.ppy.sh/community/contests/180)

it's not obvious that the thumbnails are clickable, while i'd expect the text to be

![image](https://github.com/ppy/osu-web/assets/36758269/b2c170d3-2e77-42b3-a99b-8dc0dd39e9f5)

![image](https://github.com/ppy/osu-web/assets/36758269/aad07a5d-8914-4e5c-9f84-8e62e2710278)

**Comment by Joehuu** [comment]
I'd also want the thumbnails to play the song preview to be consistent with beatmap and featured artist listing behavior.

**Comment by itsayopapi** [comment]
@Walavouchey I would like to work on this..please direct me to the codebase where the issue is coming from
