### ISSUE TITLE
mutual friends not showing properly

### ISSUE THREAD

**Issue by skyskytaiko** [ppy/osu-web#10699]
So recently I have been experiencing issues where the website seemingly stopped registering mutual friends properly, some time ago a friend of mine literally added me while screensharing on discord and it still somehow showed as green 
![image](https://github.com/ppy/osu-web/assets/149628868/d968172a-d9fd-45e1-82b3-d5f33ee12432)

![image](https://github.com/ppy/osu-web/assets/149628868/3e7bfd63-37d7-437b-bb97-f2640b58270c)
it has happened to me many times and as I have said before it's not simply a case of them not actually adding me back as there have been situations where someone added me right in front of me and it STILL did not register, I have absolutely no clue what could cause this.

**Comment by peppy** [comment]
Could you please provide your (and their) username / profile URL?

We don't cache this at all, so the only way I can imagine this failing is if one of the parties has not actually added the other.

**Comment by skyskytaiko** [comment]
Hello, the profiles are as follows
https://osu.ppy.sh/users/12863098
https://osu.ppy.sh/users/20324559
I have also thought that they just simply agreed to the mutual but didn’t
actually add me but as I have mentioned before I’ve been in a discord call
with a friend of mine who has added me in game while sharing their screen
yet it still showed as green until they added me through the osu website. I
have no idea what could be the case here..

**Comment by skyskytaiko** [comment]
On Fri, 17 Nov 2023 at 10:29, Tooner ***@***.***> wrote:

> Hello, the profiles are as follows
> https://osu.ppy.sh/users/12863098
> https://osu.ppy.sh/users/20324559
>
And here’s mine:
https://osu.ppy.sh/users/13563599
I also thought they simply didn’t add me back but as I said I have
literally seen my friend add me in a discord call and it still displayed as
green for me until they’ve added me back on the osu website. I have no idea
what could be the case..

> <https://osu.ppy.sh/users/20324559>
> I have also thought that they just simply agreed to the mutual but didn’t
> actually add me but as I have mentioned before I’ve been in a discord call
> with a friend of mine who has added me in game while sharing their screen
> yet it still showed as green until they added me through the osu website. I
> have no idea what could be the case here..
>
>
>

**Comment by peppy** [comment]
Neither of these users have you added as a friend.

**Comment by swerize** [comment]
The same thing has happened to me four times already.

Three of these took place in a twitch stream.

They added me in-game, and when I checked the site, it was still green.

**Comment by peppy** [comment]
They probably removed you.

**Comment by swerize** [comment]
This is impossible, because I never got the mutual.

Not even for a single moment.

I am 100% sure that they did not remove me before I checked the site.

**Comment by peppy** [comment]
You can provide your and their user id and I can check for you if you'd like.

**Comment by swerize** [comment]
My user ID: 13201170

Their user IDs: 5199332, 7562902, 7342622, 948713

**Comment by peppy** [comment]
I think we can be pretty sure friends are working at this point. Gonna lock this thread as I don't want to have to give bad news to people like this.
