### ISSUE TITLE
Multiplayer rooms are missing their scores

### ISSUE THREAD

**Issue by TTTaevas** [ppy/osu-web#10725]
(note I'm only talking about **the type of rooms where players play against each other in real time**, not the type of room where players have 7 days to play specific maps)

Up until somewhat recently, on the page of a room, the beatmaps (the items) that were played in that room would be displayed
Now they simply do not display anymore, and the "Map Count" remains on 0
Example: https://osu.ppy.sh/multiplayer/rooms/413097

Similarly, on the side of the API, [the endpoint to get scores from a room's item](https://osu.ppy.sh/docs/index.html#get-scores) doesn't seem to work anymore, but it's important to note [the undocumented endpoint that is used to list a room's items](https://osu.ppy.sh/docs/index.html#get-apiv2roomsroom) **does work**, its `playlist` array has all the items you'd expect it to have
What I mean by "the endpoint to get scores from a room doesn't seem to work anymore" is that it'll always give this as a response: `{
  params: { limit: 50, sort: 'score_desc' },
  scores: [],
  total: 0,
  user_score: null,
  cursor: null,
  cursor_string: null
}`

So there must be some issue going on with playlist items

**Comment by nanaya** [comment]
It was some migration failure before (somehow score links aren't created properly) and then the remaining scores got wiped/archived sometime in jan.

**Comment by peppy** [comment]
I'll track progress in here.

So far I have removed all links to old `solo_scores`.

I'm currently working on re-importing these scores with `ranked=0` so they can be restored in the leaderboards.

**Comment by peppy** [comment]
All recoverable scores have now been reimported!

**Comment by TTTaevas** [comment]
Thank you very much!!
