### ISSUE TITLE
Web sign in not working on Mozilla Firefox

### ISSUE THREAD

**Issue by racecraftr** [ppy/osu-web#10754]
When trying to sign into either osu.ppy.sh and lazer.ppy.sh on Mozilla Firefox, I get the following message:
![image](https://github.com/ppy/osu-web/assets/29521802/34aab08e-1021-4038-9fc6-e40c89a649dc)
However, signing in works normally on Google Chrome.

Even with all extensions and protections disabled, signing in on Firefox doesn't work.

**Comment by nanaya** [comment]
try clearing the cookies and site data.

**Comment by racecraftr** [comment]
Even after clearing all cookies and site data, it's still not working.

**Comment by nanaya** [comment]
try logging in from [a new firefox profile](https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles?redirectslug=profile-manager-create-and-remove-firefox-profiles&redirectlocale=en-US#w_create-remove-or-rename-a-profile). Alternatively please provide login request log from dev tools.

also, what version of firefox and operating system is it?

**Comment by racecraftr** [comment]
I used a new Firefox profile with the same extensions and was able to sign in and download beatmaps. I'm not sure why my original profile wasn't working, though. 

I was using Firefox 1.20.0 on MacOS X (ARM processor).

**Comment by nanaya** [comment]
maybe try checking site permission and privacy settings.
