### ISSUE TITLE
The website loads slowly due to government internet censonship in russia

### ISSUE THREAD

**Issue by its0ka** [ppy/osu-web#10753]
*.ppy.sh uses a very common cloudflare ip address (it may change depending on your location, but for me its 188.114.98.224 and 188.114.99.224)
![image](https://github.com/ppy/osu-web/assets/125186204/0d4d7b49-33b3-4eda-8599-4e2f805c6a9c)

Some websites banned by the government also use the same IP address, so they had to implement a Deep Packet Inspection system that blocks them, but they messed it up and now the QUIC protocol on those IP addresses is broken.
![image](https://github.com/ppy/osu-web/assets/125186204/a206dc45-842d-4b80-85a0-96872d4a772f)
you can see on the screenshot that my web browser tried to use h3 (http3) and it failed(timeout) after getting 469 bytes (after that my browser falls back to http2 and continues to work fine until it tries to use http3 again).

i also used wireshark and you can see that in the end my pc sends data but doesn't get any response (government DPI system blocked the connection after packet no. 27)
![image](https://github.com/ppy/osu-web/assets/125186204/4961c2a7-b49e-4949-bdab-f3d8f5befe5b)

to fix this i can manually assign another ip address (for example 172.67.0.128 from another cloudflare website) for *.ppy.sh using hosts file or disable QUIC protocol in my web browser completely. But can you please do it on your side to fix this issue for users in russia? Changing ip adress is problematic on cloudflare but you can disable QUIC (cloudflare dash - ppy.sh - speed - optimization - protocol optimization - HTTP/3 with QUIC), can you do it please? thank you

**Comment by its0ka** [comment]
i already have 2 people who have this issue https://osu.ppy.sh/community/forums/topics/1848583

**Comment by nanaya** [comment]
if it's a cloudflare wide thing, wouldn't it be better to do it on the browser itself? Or are you going to request all websites hosted on cloudflare to turn off quic?

**Comment by its0ka** [comment]
@nanaya only some of cloudflare websites suffer from this, and yes i can disabled it on my side, but most other people won't because they have no clue

**Comment by peppy** [comment]
@ThePooN thoughts on this?

**Comment by ThePooN** [comment]
from what I've seen on Twitter yesterday, this may not affect just Russia.
i think HTTP3/QUIC is pretty bleeding edge still and the biggest performance improvements are in HTTP2, so i wouldn't mind disabling it for now

**Comment by its0ka** [comment]
@ThePooN the QUIC is not a problem at all, it's really good when it works. it's the government that accidentally breaks the internet, i remember when they blocked the ip address of osu.ppy.sh completely for 3 days https://osu.ppy.sh/community/forums/topics/1629771?n=1

**Comment by its0ka** [comment]
@ThePooN did you see this? https://github.com/ppy/osu-web/issues/10263

**Comment by ThePooN** [comment]
have you confirmed this is still an issue to this day? as in, have you tried re-enabling QUIC today and see if it breaks?

QUIC is not essential for us, we can easily disable it, but it's a nuclear work-around for 3 testimonies from a massive country. i've bumped the forum thread just in case.

**Comment by its0ka** [comment]
@ThePooN it's still an issue. it doesn't affect everyone because different isps use different filters, and some of them don't block quic. it's an issue on my rostelecom home internet but not on my mobile megafon internet

**Comment by ThePooN** [comment]
have disabled QUIC for now
