### ISSUE TITLE
Popular Beatmap's Order

### ISSUE THREAD

**Issue by 5ublimity** [ppy/osu-web#1075]
https://my.mixtape.moe/cnyzzg.png
The popular beatmaps is not sorted by amount of plays

**Comment by nekodex** [comment]
It's sorted by the number of plays _today_, not by the number of plays _overall_ (which is displayed).

I agree this looks weird, maybe we should show number of plays today as well/instead? ping @arflyte

**Comment by nekodex** [comment]
Uh disregard that, I thought I fixed the ordering already but I was mistaken... carry on.
