### ISSUE TITLE
[Feedback] Reply box on beatmap discussions

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#1077]
(sorry if this doesn't belong here)

Currently, the beatmap discussions are all fully expanded by default, showing both replies and the reply box for every discussion. While the former is helpful, I think the latter just adds a lot of unnecessary bulk to the page, since it's unrealistic to expect a user to want to reply to every discussion's thread (except the map's creator, maybe).

I think it would make more sense for the reply box to be controlled independently and have them all collapsed by default. A user could open the reply box by clicking a button or hovering over the discussion, etc.

**Comment by nekodex** [comment]
Thoughts on doing this @arflyte?
