### ISSUE TITLE
Featured Artist showcase video players disregard source aspect ratio

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu-web#10788]
example: https://osu.ppy.sh/beatmaps/artists/212 (https://osu.ppy.sh/home/news/2021-10-30-new-featured-artist-garlagan)

![image](https://github.com/ppy/osu-web/assets/36758269/2b33dd5d-5b10-45ec-b1da-92876efbfc84)

**Comment by notbakaneko** [comment]
There can be a fixed aspect ratio or a flexible aspect ratio, not both, without knowing the ratio of the video in advance.

**Comment by peppy** [comment]
I think what we have is already correct.
