### ISSUE TITLE
Lazer website not pinning scores, scores not showing up on "best performance" tab of player profile

### ISSUE THREAD

**Issue by akitorunsyou** [ppy/osu-web#10792]
When I try to pin my scores on the lazer website, I get an error saying "You cannot pin this type of score." This is for all ganmemodes. I also recently set a score on the convert map Ayono-iki no Bus ni Notte Saraba. by Tuyu, in osu!mania. Here is my mania profile: https://lazer.ppy.sh/users/23457449/mania. I used the mods DoubleTime and 4Keys. Here is the score: https://lazer.ppy.sh/scores/2496557786.

**Comment by nanaya** [comment]
`USER_HIDE_PINNED_SOLO_SCORES` needs to be set to `false` @peppy

**Comment by nanaya** [comment]
This has been fixed.
