### ISSUE TITLE
Featured Artist tag redirects to invalid link

### ISSUE THREAD

**Issue by pishifat** [ppy/osu-web#10793]
example: https://osu.ppy.sh/beatmapsets/2015526

clicking the fa tag will go to https://osu.ppy.sh/beatmaps/artists/tracks/8823
this template osz was replaced after the map was uploaded, so 8823 no longer exists

**Comment by cl8n** [comment]
the example has been fixed. is this resolved or are there still more with the same problem? will future reuploads still cause this issue?

**Comment by peppy** [comment]
I fixed this and will fix the command to fix this going forward
