### ISSUE TITLE
scores not showing up on "best performance" tab of osu!lazer website

### ISSUE THREAD

**Issue by akitorunsyou** [ppy/osu-web#10806]
I recently got my top play and it won't show up on my top plays. 

heres the score: https://lazer.ppy.sh/scores/2506384856
heres my profile https://lazer.ppy.sh/users/23457449

from my end, it won't show up on the top plays tab.

**update: it showed up after a bit, sorry. but another issue is scores on the lazer site not pinning. it gives me an error saying "can't submit this type of score"**

**Comment by cl8n** [comment]
closing this one since you've reported the remaining pinning problem in a different issue already.
