### ISSUE TITLE
Qualified maps that are blocked from getting ranked need a visible warning

### ISSUE THREAD

**Issue by Hiviexd** [ppy/osu-web#10801]
currently, these kind of maps lack visibility which is causing nats (who are supposed to swiftly address them) a hard time keeping track of them, and it's causing complaints among players/mappers because of unexpected rank delays because of not understanding the feature / not being aware of it.

the following text could be an acceptable approach, though it'd be preferred to have some kind of a more visible warning in the modding page.

![image](https://github.com/ppy/osu-web/assets/62819481/d3d1de0f-f850-4900-9636-5f497bc8f590)

i'd really appreciate if this could be prioritized a bit because of the UX concerns mentioned above.

**Comment by tsunyoku** [comment]
could you expand on what actually "blocks" a map from being qualified? i'm unsure if it should display if there's any open suggestions or if it's only for open issues

**Comment by Hiviexd** [comment]
any unresolved suggestion or problem post blocks the map from leaving qualified.
