### ISSUE TITLE
osu!lazer score system

### ISSUE THREAD

**Issue by dimosikrus** [ppy/osu-web#10812]
(((I use Translator)))
![image](https://github.com/ppy/osu-web/assets/30956599/a37a23d5-c7fa-4544-94a5-ac59defaee9d)
Previously, **osu!laser** had the ability to set the old _score system (**from stable**)_ through the settings.
Settings now:
----Classic
----Standardized
Do not change the scoring system _(always **score v2** (or other))_
--_Points are taken (minus) away when you miss_

It seems to me that many players will find it more convenient to look at the old scoring system, just like me

**Comment by cl8n** [comment]
moved to https://github.com/ppy/osu/discussions/25922
