### ISSUE TITLE
Stable scores don't show classic mod on lazer website in the pinned setion

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu-web#10813]
![image](https://github.com/ppy/osu-web/assets/53081750/0b2bf7a7-5355-47f6-aab4-fc5da9e44410)
![image](https://github.com/ppy/osu-web/assets/53081750/bf9c5018-e7b8-45d0-8deb-9ff14bb05a38)

**Comment by LikiaBili** [comment]
![image](https://github.com/ppy/osu-web/assets/103659676/fc2b3a51-9a17-42a0-b67d-46e51606afdc)
Can't believe it's still here after a month

additional information:
in @peppy 's profile, his pinned 72pp play (which is https://osu.ppy.sh/scores/osu/1720541511) and the play in the top play (https://osu.ppy.sh/scores/166715063) have a different link to, also which haves a different Global Rank, but appears to be submitted at the exact same time and have the exact same score in the live "stable" mode, which in lazer mode, the pinned one looks like to prefer not capped to a million.

discussion: https://discord.com/channels/188630481301012481/188630616286167041/1203175230495793152
