### ISSUE TITLE
Online users in changelog page differ between web and lazer for all versions

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu-web#10810]
Opening the changelog page and the game at the same time, the two show a difference in player numbers, web looks correct while lazer underestimates everything (apart from cutting edge?)
![image](https://github.com/ppy/osu-web/assets/53081750/d19ae48a-c783-41b3-8683-f98f1f22f9db)
![image](https://github.com/ppy/osu-web/assets/53081750/c768c72c-7e32-4ed2-a6aa-97a289ddfcab)

**Comment by cl8n** [comment]
web is counting all users on the stream, while lazer is only counting the latest build
