### ISSUE TITLE
Home page user count should include lazer users

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#10816]
Currently, it's sourcing from an `osu_counts` row that bancho is responsible for.

Instead, it should add up all users across all active builds (`allow_bancho = 1`) and probably cache once a minute or so. Probably quite a simple one:

```
root@db-master:osu> select sum(users) from osu_builds where allow_bancho = 1;
+------------+
| sum(users) |
+------------+
| 8323       |
+------------+
```

**Comment by nanaya** [comment]
The one using `osu_counts` table looks like for a different total users. It's the one being incremented on user registration. Do you mean the current online users count from `osu_banchostats` table?

**Comment by peppy** [comment]
Tracking at #10991 with more up-to-date information.
