### ISSUE TITLE
Some scores set in the old client are not displayed in the new.

### ISSUE THREAD

**Issue by muesqtk** [ppy/osu-web#10824]
In general, for some reason my records are not displayed in the new client. I noticed this a long time ago, since Chicony also do not have all the scores. It's like they aren't updating. Is there any way to fix this, or is this the norm and how it should be?

 (old)![image](https://github.com/ppy/osu-web/assets/96974431/e859bace-2d2b-45b7-b966-8618e63c237e)
 (new)![image](https://github.com/ppy/osu-web/assets/96974431/c5d59fb2-b147-48ae-8abe-7525cf0e0659)

**Comment by bdach** [comment]
OP hasn't supplied their profile link, https://osu.ppy.sh/users/5199332 looks fine to me, and the experimental deploy is dead. Closing for now, please report back again if there is breakage anywhere still.
