### ISSUE TITLE
t+pazolite's TPZREMAKE versions of the songs have Featured Artist tags despite these versions not being listed in t+pazolite's FA page

### ISSUE THREAD

**Issue by Skubers** [ppy/osu-web#10835]
Does the licensing include their TPZREMAKE versions of the songs? https://tpazolite.bandcamp.com/album/tpzremake-01

If not, then most likely the beatmaps that do use the TPZREMAKE version of the songs shouldn't have the FA badge, right? (The meta is the same as the non-remake versions and its correct)
https://osu.ppy.sh/beatmapsets/1749630#mania/3579382
You can compare the versions by listening to preview points of these two ranked sets
[https://osu.ppy.sh/beatmapsets?q=title%3D""Cheatreal""](https://osu.ppy.sh/beatmapsets?q=title%3D%22%22Cheatreal%22%22)

**Comment by peppy** [comment]
We think this usage should be fine.
