### ISSUE TITLE
Some beatmap downloads broken for people in Australia

### ISSUE THREAD

**Issue by K0nomi** [ppy/osu-web#10846]
Attempting to download a beatmap just gives a 0 byte file, for most beatmaps. I've encountered quite a few others having this exact issue, and they are all in Australia. Using a VPN circumvents it, so i assume its an error with some regional servers

Here's a [forum thread](https://osu.ppy.sh/community/forums/topics/1868057) that someone made, but I've seen at least 5 other Australians mention having this issue over discord

**Comment by ThePooN** [comment]
Should be fixed now, thanks for reporting!
