### ISSUE TITLE
Profile seems to be broken after a score submission failed

### ISSUE THREAD

**Issue by Adrriii** [ppy/osu-web#10847]
I played two maps this morning and my profile broke: 
![image](https://github.com/ppy/osu-web/assets/16978299/92050a28-e34e-4e51-8c6c-c12006e116f0)

It was fine before my session, and I noticed it was broken after submitting this play : https://lazer.ppy.sh/scores/2605152259

However, there was a score submission failure with the attached replay, so this might be related : 
[replay_and_map.zip](https://github.com/ppy/osu-web/files/13871417/replay_and_map.zip)

I played a total of 5 scores: 
- 3 scores on FFT (unranked), first play failed to submit
- 1 score with DT 1.4 (unranked) on a ranked map (this is where i noticed the profile broke)
- 1 score with DT (ranked) on the same map

The plays that submitted : 
![image](https://github.com/ppy/osu-web/assets/16978299/4004a491-c95b-4751-ac23-9e90367b6b51)
https://lazer.ppy.sh/scores/2605153198
https://lazer.ppy.sh/scores/2605152259
https://lazer.ppy.sh/scores/2605151147
https://lazer.ppy.sh/scores/2605150626

**Comment by bdach** [comment]
Profile looks fixed now, and all 4 linked scores are dead links, so closing?
