### ISSUE TITLE
include BeatmapPack id in API response

### ISSUE THREAD

**Issue by notbakaneko** [ppy/osu-web#10843]
Doesn't make sense to exclude it anymore, since the id can be used for lookups and the response cursor uses the id instead of the tag

**Comment by nanaya** [comment]
Last I checked the id shouldn't be used anymore and lookup on id probably [doesn't work](https://github.com/ppy/osu-web/blob/44ae6c61bfc106082de130518479479a62830d0d/app/Models/Solo/Score.php#L52). If anything the model should pretend the tag being primary key and sort on it instead?

**Comment by nanaya** [comment]
Yeah, tag should always be used when interfacing externally.
