### ISSUE TITLE
Acc has errors, Is it a bug or is the website statistics algorithm updated?

### ISSUE THREAD

**Issue by wanjiaXG** [ppy/osu-web#10855]
Same pp，Acc 98.98% -> 96.04%

2024-01-11:
![N2J ISY@9U46 WJQIZ})@YS](https://github.com/ppy/osu-web/assets/26690346/0ab42d89-aaed-4e8f-8ec8-c4859de4d1cb)

2024-01-06:
![Q4S6XOZAK1~2W8X7UOAQWG1](https://github.com/ppy/osu-web/assets/26690346/a6999a22-f77d-4e5e-beec-54195ca2e6aa)

My profile now also shows 96.04%.

During the period of 2024.01.06-2024.01.11, I almost not played on stable and did not update BP100, but I played on Lazer a few times during this period, and I am not sure if it is related to this.

**Comment by wanjiaXG** [comment]
Resolved，just update new BP 1-100.
maybe there was an issue with the database.
After updating the BP, data was recalculated.

**Comment by Joehuu** [comment]
Closing as resolved.
