### ISSUE TITLE
bugged profile or something else

### ISSUE THREAD

**Issue by HA3APKO-UA** [ppy/osu-web#10850]
When I go onto my profile, I see no A ranks on the counter when (I’m pretty sure) I should have gotten one. Scrolling down to the best performances tab, it shows me random performances that are definitely not my best ones, but sometimes it does show my best. On the standard osu page it doesnt show any best performances. Another issue is when i try to pin any of my performances, it just tells me "cant pin this type of score. I also noticed that it shows on my pp counter as 7 instead of 26, when the ones i added together in recently played add up to that. Is this normal or is there something wrong my with my account? 

Screenshots:
https://imgur.com/evOuUes
https://imgur.com/pxdz9hf
https://imgur.com/GdxrnsO

Profile Link https://lazer.ppy.sh/users/35146012

**Comment by Blooshing** [comment]
To my knowledge they are not currently tracked unless you played from stable, as those are going to be imported. Please be patient, lazer is undergoing dev work to migrate scores/turn on scores and features that the main site has.

**Comment by peppy** [comment]
Please stay tuned as we'll be bringing everything in line over the coming weeks.
