### ISSUE TITLE
User with negative ranked score

### ISSUE THREAD

**Issue by MaxOhn** [ppy/osu-web#10861]
The user [togan2266](https://osu.ppy.sh/users/9236859/taiko) has negative ranked score in taiko.
![image](https://github.com/ppy/osu-web/assets/41148446/41bd3ceb-451e-42c0-a225-b6dedf97aff7)

**Comment by peppy** [comment]
Have fixed this (and multiple other cases).

**Comment by cl8n** [comment]
@peppy  do you mean that you fixed the cause, or fixed the users? because the case in OP hasn't changed

**Comment by peppy** [comment]
oops, fixed again.
