### ISSUE TITLE
Remove beatmap legacy nomination mode

### ISSUE THREAD

**Issue by notbakaneko** [ppy/osu-web#10882]
This was kept around when the new beatmapset nomination code was implemented since there were plenty of existing nominations for pending beatmaps, but now there's only 5 pending/wip beatmaps with legacy mode nominations left and they're pretty old nominations

beatmapset_id | created_at
--------------- | ----------------
690222	| 2018-03-06 08:11:31
535792	| 2018-07-12 19:53:17
749623	| 2018-08-22 18:19:47
516707	| 2019-07-17 02:38:58
1031432	| 2019-09-24 13:55:13

**Comment by Hiviexd** [comment]
if these nominations need to be reset because of this then that can be arranged. all of them will need to be reset anyways if any were to be pushed to Ranked because of broken rules/guidelines that were made after the maps were abandoned.

**Comment by peppy** [comment]
What's required to make this happen? I think we should just reset them and get this closed out.

**Comment by notbakaneko** [comment]
They should just be reset.

**Comment by notbakaneko** [comment]
Actually, since these all seem to be single mode sets, maybe the modes modes can just be filled in instead.

**Comment by peppy** [comment]
I've reset all the remaining beatmaps using the legacy system.

**Comment by nanaya** [comment]
shouldn't all the codes relating to this also be removed?

**Comment by peppy** [comment]
I did think that was the plan 🤔

**Comment by peppy** [comment]
cc @notbakaneko in case you missed this
