### ISSUE TITLE
Create a buffer for loading modding discussions posts

### ISSUE THREAD

**Issue by Rekunan** [ppy/osu-web#10885]
On this map, due to the sheer amount of mod posts, if you try loading in and scrolling on the discussions page with a decent connection, you get 429'd error'd and rate limited: https://osu.ppy.sh/beatmapsets/2007015/discussion/4174629/timeline

The mapper even made another difficulty so that modding could continue.

My suggestion is to create a buffer for loading mods so that this doesn't happen, maybe only after x mods, as I've seen people with slow Wi-Fi be perfectly fine.

**Comment by nanaya** [comment]
The actual problem is something else and it's been fixed.
