### ISSUE TITLE
Very old pending/WIP maps are not being moved to graveyard

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#10897]
many examples at https://osu.ppy.sh/beatmapsets?sort=updated_asc&s=pending

**Comment by entwastaken** [comment]
The only actually strange example seems to be https://osu.ppy.sh/beatmapsets/394957#mania/864166

All the other instances are stuck because they have received at least one nomination, but never received the final one to move into Qualified and were never updated to reset their nominations.

**Comment by peppy** [comment]
I went through and fixed these recently. I'll look at that remaining one but close this issue.
