### ISSUE TITLE
Ability to change store orders from admin page

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#109]
Right now I'm making changes manually at a database level when a user requests an address or t-shirt design/size changes. We need the ability to edit orders from the admin page (/store/admin/).

Requirements:
- Ability to edit address.
- Ability to change product to another product of same value (different size/design) using a dropdown.
- Changes should be saved instantly.
- Should only be allowed for orders in a "paid" state. Shipped or Delivered orders should not be changeable.
- Remaining stock should be checked (products without stock shouldn't be shown in the dropdown) and updated on change.

**[Bounty](https://goo.gl/nFdoyI) offered**: 50

**Comment by echojc** [comment]
I'm gonna give this a shot.

@peppy I'd be grateful if you could take a look at the current state of my PR and tell me if I'm on the right track style- and architecture-wise since it's my first time working with such a heavily ORM-based framework!

**Comment by echojc** [comment]
Should editing the address save to the same row or create a new row? I can see use cases for both ("I entered my address wrong" and "send this order to this other address").

**Comment by peppy** [comment]
I ended up doing this myself, so closing the issue.
