### ISSUE TITLE
Beatmap search length filter not working as expected.

### ISSUE THREAD

**Issue by brandondong** [ppy/osu-web#10902]
https://osu.ppy.sh/beatmapsets?m=0&q=length%3D6m%20toaru
![image](https://github.com/ppy/osu-web/assets/13722457/3e362e26-0cb4-40fe-9a86-45a3bec60d28)
![image](https://github.com/ppy/osu-web/assets/13722457/73ef8d7f-b3f7-44f8-ac31-eb0557f5b40f)

Am I misunderstanding something about how this length filter works? I would expect it to match for `length=7m`.

If I download the map on lazer and then filter in the song select screen, the same query (`length=6m toaru`) will result in no matches. `length=7m toaru` will work. So either the web search or lazer is wrong.

**Comment by notbakaneko** [comment]
web matches against the drain length which is `6:05`

**Comment by brandondong** [comment]
Thanks, I was not aware of this. I personally think the song length makes more sense because you can't skip breaks anyways while playing but I understand if this is intended and has always been that way.

If this is the desired behavior, do you want me to file a bug against lazer? There should not be a discrepancy when using the same query but in the song select menu.

https://github.com/ppy/osu/blob/7cdedfb6ca408b8ace311944bc3bf8b8454c515d/osu.Game/Screens/Select/Carousel/CarouselBeatmap.cs#L66 is the relevant lazer code.
