### ISSUE TITLE
Wrong beatmap leaderboard ranking after recent update

### ISSUE THREAD

**Issue by kafibu** [ppy/osu-web#10922]
This [player](https://osu.ppy.sh/users/15434024/osu) lost his no1 ranking on this [beatmap](https://osu.ppy.sh/beatmapsets/2060600#osu/4324907) after latest update (It the same whether lazer mode is on or not)

![2024-01-30 (1)](https://github.com/ppy/osu-web/assets/111474179/d9e0c5ec-e4e2-47c7-9d4f-bd8936766cdc)

Note his no1 ranking still appear in his profile

![2024-01-30 (2)](https://github.com/ppy/osu-web/assets/111474179/0ac43267-6fcd-4a5f-8e6c-56cb41295e93)

**Comment by nanaya** [comment]
The id order probably doesn't match when the score is imported. Not sure how to get that fixed...

One would be to include legacy_score_id in the index and sort by that but that wouldn't work for lazer mode. Another alternative would be to sort by one of the timestamp columns (started_at etc) before by id.

@peppy

**Comment by peppy** [comment]
Order was matched on import, I made special care to ensure that. Will investigate.

**Comment by nanaya** [comment]
It's the same on non-lazer.

| score id   | legacy score id |
|------------|-----------------|
| 1808465719 | 4561877924      |
| 1808465739 | 4561808159      |

**Comment by peppy** [comment]
Other cases brought up in linked threads:

ppy/osu#27731:

| score id   | legacy score id |
|------------|-----------------|
| [1808465719](https://osu.ppy.sh/scores/1961650557) | [214575709](https://osu.ppy.sh/scores/fruits/214575709) |
| [1808465739](https://osu.ppy.sh/scores/1961650466) | [214593084](https://osu.ppy.sh/scores/fruits/214593084) |


#11048

| score id   | legacy score id |
|------------|-----------------|
| [1961647015](https://osu.ppy.sh/scores/1961647015) | [214615400](https://osu.ppy.sh/scores/fruits/214615400) |
| [1961647016](https://osu.ppy.sh/scores/1961647016) | [214584096](https://osu.ppy.sh/scores/fruits/214584096) |

**Comment by peppy** [comment]
Repairs have been run for this across all beatmaps / rulesets!
