### ISSUE TITLE
I just played osu!lazer and my pp total is kind of messed up

### ISSUE THREAD

**Issue by kyleacuna** [ppy/osu-web#10927]
Hello! I'm wondering what's up with the total pp counter on the website (and in-game). It states that I have 2,350pp in total after playing osu!lazer. Before I played osu!lazer, my total pp is 2,056pp (still the same "before" pp on api's like osu profile banners).
https://osu.ppy.sh/users/33637952
![image](https://github.com/ppy/osu-web/assets/134776227/d9a3c1bf-438c-4a17-ba8c-80851a6c060f)

I calculated my total pp using a calculator and it's too far on being 2,350pp.

**Comment by peppy** [comment]
It will change depending on which version you play. Eventually this will be standardised. Play on stable again if you want your previous pp value back.
