### ISSUE TITLE
User profile shows outdated "Highest Rank"

### ISSUE THREAD

**Issue by nmi5** [ppy/osu-web#10937]
The "Highest Rank" section on the user profile that shows when you mouse over the current rank is showing an outdated number.

This is on my profile (https://osu.ppy.sh/users/10431595) if that helps.

![image](https://github.com/ppy/osu-web/assets/53661687/b986f9b4-ae35-4d6a-97f0-c68ff25b1f53)

**Comment by nanaya** [comment]
The data isn't generated/updated by osu-web. Technically it can be worked around by checking against current statistics or rank history but I think it's better fixed at the component that is handling it? @peppy

**Comment by bdach** [comment]
@peppy is this something you want/need to be doing specifically, or can I perhaps take over? As far as I can tell web-10 updates this, so it'd just be a question of porting whatever it does to `osu-queue-score-statistics`?
