### ISSUE TITLE
Landing page video embed

### ISSUE THREAD

**Issue by Seventth** [ppy/osu-web#1093]
Just some feedback, but it seems the embedded video acts rough/odd in certain situations.

For example, on mobile (Android/Latest Google Chrome Application), if Chrome is suspended and unsuspended, the landing page shows suggested videos.

There also a bit of a noticeable delay at the end where it cuts and replays again which I assume is intended, but isn't quite seamless. 

Other then those two, landing page looks quite awesome and is going the right direction.

**Comment by nekodex** [comment]
We're planning on replacing the YouTube embed with a native HTML5 version that should fix these issues.

**Comment by nanaya** [comment]
"fixed" (well, except on android which shows nothing)
