### ISSUE TITLE
User with unranked maps in their top scores

### ISSUE THREAD

**Issue by MaxOhn** [ppy/osu-web#10932]
The user [/u/32743279](https://osu.ppy.sh/users/32743279) currently has two scores on unranked maps in their top plays, i.e. maps [/b/3082728](https://osu.ppy.sh/beatmapsets/825086#osu/3082728) and [/b/1731073](https://osu.ppy.sh/beatmapsets/825086#osu/1731073)
![image](https://github.com/ppy/osu-web/assets/41148446/5065bcaf-6032-4a72-8474-b1f73e6cb4f0)
They only appear when lazer mode is enabled.

**Comment by MaxOhn** [comment]
Similarly, user [/u/5366933](https://osu.ppy.sh/users/5366933) has a bunch of loved maps in their top scores
![image](https://github.com/ppy/osu-web/assets/41148446/a6e00cf3-b2b7-4b85-a0d0-12b1479ac27c)

**Comment by peppy** [comment]
https://osu.ppy.sh/users/32743279 looks to have already been resolved.

still investigating the second (loved) case

**Comment by peppy** [comment]
Second case fixed via https://github.com/ppy/osu-web/pull/11153.
