### ISSUE TITLE
osu! API returns score as `0`

### ISSUE THREAD

**Issue by YoruNoKen** [ppy/osu-web#10957]
![image](https://github.com/ppy/osu-web/assets/69751661/02e253bc-471a-4721-8d5d-40675ed0e8b8)
only happens in lazer.

**Comment by nanaya** [comment]
lazer scores don't have legacy total score.

**Comment by YoruNoKen** [comment]
any way to get legacy score, then? I don't see anything else that has the name `score`

**Comment by nanaya** [comment]
I'm not quite sure what you're asking.

**Comment by nanaya** [comment]
lazer score data is available on the newer json structure, specified using x-api-version header with value of 20220705 or higher
