### ISSUE TITLE
Top play missing

### ISSUE THREAD

**Issue by JezzRBX** [ppy/osu-web#10965]
When I checked my profile today, I noticed that one of my top plays had disappeared. I achieved it about a week ago, but it is no longer there.

Here is the proof of the score:
![image](https://github.com/ppy/osu-web/assets/158737906/ec5d30e1-a465-4ac6-986d-6473498f1cff)
 https://link.issou.best/aUsVJ2

profile: https://osu.ppy.sh/users/23010893

map: https://osu.ppy.sh/beatmapsets/364401#osu/799913

I would like to know what happened.

**Comment by cl8n** [comment]
@peppy just making sure you see this because it looks similar to #10923
