### ISSUE TITLE
Performance ranking reset

### ISSUE THREAD

**Issue by StealthBlad3** [ppy/osu-web#10968]
During the rollout of an update a few days ago, my performance ranking disappeared. Thought it was just a visual bug so kept playing and ended up getting a low ranking after a few maps. Now that the update's over, it's kept this much lower ranking even on the website. Can still see the previous beatmap performances before the update and the performance points for each, but they're not added to my overall count.

**Comment by peppy** [comment]
Are you referring to the one on lazer.ppy.sh? If so, we have reset lazer scores to bring the full leaderboards online, so your rank may have dropped in line with this change. We may restore some of the older scores but please don't count on it (sorry for the inconvenience though!)
