### ISSUE TITLE
``api/v2/matches/{match}`` missing params in documentation

### ISSUE THREAD

**Issue by ArtemOsuskyi** [ppy/osu-web#10974]
According to #9589, for ``api/v2/matches/{match}`` there should be `before` and `after` params which seem to be missing

![image](https://github.com/ppy/osu-web/assets/96246908/70780122-549f-4e9c-af42-7b3cc1db6de9)

**Comment by cl8n** [comment]
well the whole endpoint is undocumented (look at what section it's in). I'll keep this issue open because I've seen a lot of questions about this endpoint in particular, probably because it's supposed to be a direct alternative to something api v1 has.
