### ISSUE TITLE
lazer.ppy.sh and dev.ppy.sh indexed by search engines

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#10980]
hard to consistently get these results but they do sometimes come up when i search something osu-related on DDG or google, usually pages on the wiki but through those domains. I think they should be excluded

**Comment by peppy** [comment]
lazer.ppy.sh is going away soon, but I guess we should add an envvar for noindex rules for dev, unless there's another way to have this applied?

**Comment by notbakaneko** [comment]
google supports the `X-Robots-Tag: noindex` http header, I'm not sure about others

**Comment by peppy** [comment]
Would be a good start.

**Comment by notbakaneko** [comment]
(I mean as this part can be added via nginx for those domains, if it wasn't clear 👀 )

**Comment by ThePooN** [comment]
lazer.ppy.sh is gone, and header has been added to dev.ppy.sh :ok_hand:
