### ISSUE TITLE
Lazer score submitted but doesn't show on map leaderboard

### ISSUE THREAD

**Issue by Flamiii** [ppy/osu-web#10989]
I set a score on this [map](https://osu.ppy.sh/beatmapsets/1231048#osu/2559287) which was 619,526, and then afterwards I set a score that was [690,158](https://osu.ppy.sh/scores/2324071069). The higher score submitted to the website and shows up in my recent plays, it has an associated replay that can be downloaded, and it has a score page. On the score page, it even says that my play is Global Rank 4, but if you look at the [map's leaderboard](https://osu.ppy.sh/beatmapsets/1231048#osu/2559287), that play is nowhere to be seen and my lower score is the only one on the leaderboard.

Logs in case they're helpful:
[compressed-logs.zip](https://github.com/ppy/osu-web/files/14230973/compressed-logs.zip)

Edit: The score is on the leaderboard now after several hours.

Edit 2: It seems that this was not an isolated incident, as [it happened again.](https://osu.ppy.sh/scores/2331796385) I set another score that submitted with a score page and it is just not showing up on the map's leaderboard. It might show up at some point but scores taking this long to show up seems like a serious issue. I'm not sure if this is relevant at all, but in both cases I already had an existing score on the map with the same mod combination and I exited the results screen very quickly after setting both scores.

Edit 3: This score also showed up on the leaderboard but took 3 hours to do so.

Final Edit: I think this is mostly resolved now, as score submission just seemed to be temporarily slow over the weekend. Recently, scores have been submitting to leaderboards very fast, and I think the slow score submission may have been the cause of this.

**Comment by cl8n** [comment]
I'm going to close this one since it seems to have resolved itself and there's not much to investigate here, but please re-open if you see it happen again
