### ISSUE TITLE
Add Terms of Use and Copyright pages

### ISSUE THREAD

**Issue by nekodex** [ppy/osu-web#1100]
Add a top-level route that just points at the relevant wiki pages for now:

https://new.ppy.sh/wiki/Legal/TOS
https://new.ppy.sh/wiki/Legal/Copyright

**Comment by nanaya** [comment]
Seems to have been added a while ago.

**Comment by nekodex** [comment]
Not quite sir, we want the tos/copyright pages to be displayed at the top level, e.g. `/tos` or `/dmca` instead of just redirects/links to the wiki. The referenced pull request just changes the footer links to point at the wiki pages.
