### ISSUE TITLE
Score not submitting

### ISSUE THREAD

**Issue by J0nyee** [ppy/osu-web#11014]
So I just got my new top play in lazer but it's not showing in either my plays in the last 24 hours or in my top plays.

here's my profile: https://osu.ppy.sh/users/19958098
here's the score: ![1](https://github.com/ppy/osu-web/assets/160526607/c69f4b81-84e5-4498-8eb8-3bc40f7be3c8)

Will it just get added later or is it lost?

**Comment by J0nyee** [comment]
So ok I found out about new scores I set that weren't submitted and noticed that the majority of them were set in a time frame of about 40min before I downloaded the newest update.

**Comment by peppy** [comment]
Hard to say anything without knowing what version you were running. Please pay attention to any error messages that show in game, as when the game fails to submit it will tell you why. If you get further information feel free to reply with it.
