### ISSUE TITLE
``/beatmaps/{beatmap}/scores/users/{user}`` returns wrong data

### ISSUE THREAD

**Issue by thanosbousios** [ppy/osu-web#11025]
![2024-02-23 16-52-34](https://github.com/ppy/osu-web/assets/52247806/a2d2908a-5c13-43d4-9ad5-04152f3b6acf)
As shown here on a score submitted on lazer, ``scores`` field returns '0' and ``rank`` field is incorrect, as though it was calculated in classic mod.

Also, on screenshot below, ``rank`` returns wrong value. It should be an ``SH`` (just like it does on the beatmap page) because the score has exactly 1% 50s, as explained on the [wiki](https://osu.ppy.sh/wiki/en/Gameplay/Grade#osu!).
![2024-02-23 17-32-55](https://github.com/ppy/osu-web/assets/52247806/4f2f3109-a041-4931-a2e2-ba365094dc76)

**Comment by nanaya** [comment]
Lazer scores don't have legacy total score value. Use new response to see lazer total score.

**Comment by peppy** [comment]
We should probably error out if a user requests the old api endpoint for a new score or something? Also do we have documentation of the new response somewhere yet?
