### ISSUE TITLE
Lazer mode beatmap leaderboard is completely broken

### ISSUE THREAD

**Issue by Flamiii** [ppy/osu-web#11027]
https://osu.ppy.sh/beatmapsets/675779#osu/1431549

Honestly, I am not sure what is even happening here.

**Comment by bdach** [comment]
This is a failure of the score conversion algorithm, caused by the beatmap being......... special. [I've seen it in previous travels.](https://gist.github.com/bdach/414d5289f65b0399fa8f9732245a4f7c#ken-doll-on-nuclear-star-by-camellia-momokos-absolute-051)

Investigating possible fixes.
