### ISSUE TITLE
api feature request: add `is_mutual` to User parameter

### ISSUE THREAD

**Issue by Dopaminos** [ppy/osu-web#11033]
i want to write some kind of parser (?) that checks your mutual friends, but with current api it's not really possible to scrape mutuals only, but i can find if i friended someone. 

would be nice to add `is_mutual` to User so this parser would be possible to make.

**Comment by Joehuu** [comment]
Does https://github.com/ppy/osu-web/issues/7637 also achieve what you want?

**Comment by Dopaminos** [comment]
oh, pretty sure it does

**Comment by Joehuu** [comment]
Closing as duplicate then.
