### ISSUE TITLE
Loved maps being filtered as graveyard

### ISSUE THREAD

**Issue by DaiterGoD** [ppy/osu-web#11034]
![Screenshot_38](https://github.com/ppy/osu-web/assets/64665908/c6456ee9-5f61-4e09-88ee-7a44d513c205)
![Screenshot_39](https://github.com/ppy/osu-web/assets/64665908/7917ad48-ce23-4d7b-bd70-49a0bc44e570)
https://osu.ppy.sh/beatmapsets/1105209
https://osu.ppy.sh/beatmapsets/1240175
https://osu.ppy.sh/beatmapsets/1240175

**Comment by cl8n** [comment]
these maps do contain graveyarded difficulties, which is why they show up here
