### ISSUE TITLE
Request new `api` endpoints

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu-web#11043]
I've been rewriting my api wrapper, and notice that some important, or nice to have endpoints doesn't exists. So it'll be nice to have them as json endpoints, rather than scaping the page, and i've collected list of some endpoints i wish will be added:

1. route to pin comments
2. List of forums and subforums: https://osu.ppy.sh/community/forums
3. list of posts within the forum: https://osu.ppy.sh/community/forums/15
4. list of followed mappers (like we have for friends): https://osu.ppy.sh/home/follows/mapping
5. And since we talking about this ^, we can have similar endpoints for: [beatmap disscussion](https://osu.ppy.sh/home/follows/modding) [forum topics](https://osu.ppy.sh/home/follows/forum_topic) and [comments](https://osu.ppy.sh/home/follows/comment)
6. Feature artists list: https://osu.ppy.sh/beatmaps/artists
7. FA songs search: https://osu.ppy.sh/beatmaps/artists/tracks
8. FA information page: https://osu.ppy.sh/beatmaps/artists/45
9. List of contests: https://osu.ppy.sh/community/contests
10. Contest information page: https://osu.ppy.sh/community/contests/204
11. Also will be cool to have an endpoint to vote for active contest entries
12. Modding (idk this maybe already has their own endpoint that i forget): https://osu.ppy.sh/users/9893708/modding
13. List of users within a certain groups: https://osu.ppy.sh/groups/11

**Comment by cl8n** [comment]
1 and 11 are probably going to need their motivation explained. I can't come up with any reason that a third party should be doing these things on behalf of a user

**Comment by peppy** [comment]
Basically every one of these requires a use case before we'd expend the time on implementing.

**Comment by cyperdark** [comment]
### **_1_** :
i dont exact usecase of this one, but i assume it'll be used in lazer later on. And also we already have "Vote Comment" route

### **_2 & 3_**: 
It used in my discord bot ([screenshot](https://i.osuck.link/1709241586_5OvbVbRHZW.png)) to post new skins from two subreddits, and i believe "skinship" scraping page itself too

### **_4 & 5_** :
At the moment i dont have examples for usecase, so it can be skipped for now

### **_6, 7, 8_** :
No usecase i can think of. Just thought it'll be nice too have

### **_9_** :
Well im not sure, it's needed once in a while, so it can be skipped

### **_10_** :
But this one i'll use to make a request to get "Skins Contests" Entries, to put them on [the site](https://skins.osuck.net/skins/contests).

### **_11_** :
For this one it'll be usefull, because that way i can add voting directly on [this page](https://skins.osuck.net/skins/contests/3) (only when contest is active), so people do need to search the skin on page. This page is have all contest skins, with all their screenshots in one place, instead of going thought each one

### **_12_** :
No usecase

### **_13_** :
For a discord bot to [post this](https://i.osuck.link/1709242180_ATjioR7O2m.png), instead of scraping page itself

**Comment by peppy** [comment]
Sorry but just continue use scraping if you must. The api isn't intended to duplicate web content like this.

**Comment by cyperdark** [comment]
okay i'll continue scraping for 2, 3 and 13, but what about 11 usecase?

**Comment by peppy** [comment]
No, it's weird. You should only be voting via the website.
