### ISSUE TITLE
`/rooms/{room}/playlist/{playlist}/scores` doesn't work anymore

### ISSUE THREAD

**Issue by TTTaevas** [ppy/osu-web#11064]
The endpoint to get scores from multiplayer rooms always returns a response with an empty `scores` array
Tested with `https://osu.ppy.sh/api/v2/rooms/51693/playlist/130053/scores?limit=50&sort=score_desc` and `https://osu.ppy.sh/api/v2/rooms/499640/playlist/4296482/scores?limit=50&sort=score_desc` with valid tokens

**Comment by nanaya** [comment]
Most of the rooms before feb 2024 have missing scores. Duplicate of #10725
