### ISSUE TITLE
`api/v2/comments`'s commentable_meta array always holds a Deleted Item

### ISSUE THREAD

**Issue by TTTaevas** [ppy/osu-web#11077]
I guess it's kinda minor, but no matter the parameters used when getting `/comments`, there will always be a Deleted Item at the end of the `commentable_meta` array
While Deleted Items have been documented since #9936, the issue is that there's always one Deleted Item, even if it presumably makes no sense for one to be there

**Comment by nanaya** [comment]
Feel free to make a pr to conditionally remove it but otherwise I don't think it's a problem. The array is for lookup anyway.
