### ISSUE TITLE
Ranked beatmap does not have Storyboard icon (even with osb following correct file name format)

### ISSUE THREAD

**Issue by Coppertine** [ppy/osu-web#11099]
More so something i noticed and could not figure out why the website thinks there is no storyboard to the map.
Map: https://osu.ppy.sh/beatmapsets/2067109#mania/4324528
![image](https://github.com/ppy/osu-web/assets/37494321/f1dc0840-846b-49cd-89a9-002ce0b5e836)

It could be the usage of `;` within the file name (although unlikely)

For reference:
`.osu` - `Noriko Mitose - ClassEXSPHERE_NOSURGE; (eZmmR) [QuelI-EXiV[zod]-EXiV[noz]-EXiV[nux]- ExiV[bomb]-ExiV[endi]-ExeC-{RW};].osu`
`.osb` - `Noriko Mitose - ClassEXSPHERE_NOSURGE; (eZmmR).osb`

**Comment by peppy** [comment]
I've fixed this beatmap.
