### ISSUE TITLE
idk how

### ISSUE THREAD

**Issue by Keith1R0blox** [ppy/osu-web#11112]
![Screenshot 2024-03-23 182314](https://github.com/ppy/osu-web/assets/155455657/f32adfd3-33bd-46a6-a68f-0c51494679c1)

so I downloaded osu!lazer and after logging in, it tells me to type the verification code by taking it from email, but in the email box it didn't showed me the code, and idk what to do

**Comment by cl8n** [comment]
try checking your spam folder as well
