### ISSUE TITLE
Licence notice for Torus?

### ISSUE THREAD

**Issue by OfficialCRUGG** [ppy/osu-web#11124]
Since this repo includes the Torus Font, but is licensed under APGL, wouldn't there be the need for a separate notice that the Torus Font is not included under this license, similar to how already the case in https://github.com/ppy/osu-resources?

**Comment by agatemosu** [comment]
the torus licence is in https://github.com/ppy/osu-web/blob/master/resources/css/torus.less

**Comment by peppy** [comment]
osu-web isn't made to be used by third parties outside of dev work, so i'm not sure this is important at all,
