### ISSUE TITLE
regarding blocking in russia

### ISSUE THREAD

**Issue by its0ka** [ppy/osu-web#11136]
i analyzed the blocking and it seems that it doesn't affect just cloudflare but a TLS certificate, for me it only affects websites with default cloudflare TLS certificate (google trust cervices)
![image](https://github.com/ppy/osu-web/assets/125186204/d676849d-92b8-41e1-978f-542f1b1cb4b3)

www.speedtest.com for example has a different certificate
![image](https://github.com/ppy/osu-web/assets/125186204/ecbd405d-8642-48ac-8202-6cd290e9e8e5)
and i have no issues accessing it

if you can, please try to change your tls cert, it costs 10$/mo to order "Advanced Certificate Manager" on cloudflare, maybe it will help?

the ip address is not blocked https://ping-admin.com/free_ping/result/1711957027w9bchdetvh1u6zmyi6257.html

**Comment by its0ka** [comment]
does osu support tls 1.3? setting minimal tls version in cloudflare dash to 1.3 makes my own domain work fine

**Comment by its0ka** [comment]
https://ntc.party/t/%D0%BD%D0%B5%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%BD%D0%BE%D1%81%D1%82%D1%8C-apiauthortoday-%D0%B8%D0%B7-%D0%BF%D1%80%D0%B8%D0%BB%D0%BE%D0%B6%D0%B5%D0%BD%D0%B8%D1%8F/7618/6

"Advanced Certificate Manager" on cloudflare can do "Custom Cipher Suite settings" so it should help

**Comment by its0ka** [comment]
https://osu.ppy.sh/community/forums/posts/9489580 working fix

**Comment by peppy** [comment]
We have resolved this issue as of yesterday.

**Comment by its0ka** [comment]
how?
