### ISSUE TITLE
global ranking bug

### ISSUE THREAD

**Issue by kyleacuna** [ppy/osu-web#11140]
![image](https://github.com/ppy/osu-web/assets/134776227/03df3219-be62-4f72-b49e-6cf2bb8351e7)
I just saw Mrekk's profile that he is currently #2 global but on leaderboards, he's #1.

why did this happen and will Mrekk's graph be back to normal? (is it going to be a straight line or permanent?)

**Comment by peppy** [comment]
This is already fixed and will be resolved next time the user plays.
