### ISSUE TITLE
User's 1mil scores in mania gamemode are always shown in the "Recent Plays (24h)" section in their userpage

### ISSUE THREAD

**Issue by MarioUniverseZ** [ppy/osu-web#11143]
which almost all of the scores are played over 24 hours ago
I'm taking GrillledCheeese's userpage as an example:
![image](https://github.com/ppy/osu-web/assets/118989308/8284b713-69c6-42a0-b2bf-b8916a71b88d)

**Comment by peppy** [comment]
duplicate https://github.com/ppy/osu-web/issues/11144#issuecomment-2036047440
