### ISSUE TITLE
"Recent Plays (24h)" profile section displays random scores in a random date order

### ISSUE THREAD

**Issue by amnezziaa** [ppy/osu-web#11144]
Might be linked to https://github.com/ppy/osu-web/issues/11143

This issue takes a look at the `STD` gamemode part of profiles.

When looking at the `"Recent Plays (24h)" profile section` [for this user](https://osu.ppy.sh/users/12765882). We can see that it shows random scores in a random date order (all being `HD{DT|NC}HRFLCL`) dating from almost 15 months ago (28/12/2022) for the oldest ones.
**Screenshot:**
![image](https://github.com/ppy/osu-web/assets/94064103/eef602af-54bb-4ee6-b14b-1570c81cf940)

Same behaviour happens for other players, example: https://osu.ppy.sh/users/18607342. Once again, all scores are `HD{DT|NC}HRFLCL` apart [from one](https://osu.ppy.sh/scores/1813061206).
**Screenshots:**
![image](https://github.com/ppy/osu-web/assets/94064103/33532621-39e0-48ed-b7d8-51f75c688d42)
![image](https://github.com/ppy/osu-web/assets/94064103/320bef39-90f7-4796-8a0c-a7a7c0e71a67)

**Comment by peppy** [comment]
This will resolve soon.
