### ISSUE TITLE
Bounty program link on supporter page points to legacy Google Sheet

### ISSUE THREAD

**Issue by ggliv** [ppy/osu-web#11179]
![image](https://github.com/ppy/osu-web/assets/47010459/bd7601e2-3fb4-44a7-bab9-fab62792d46f)

The "Find out more" link on [this page](https://osu.ppy.sh/home/support) should probably be updated to send you to OpenCollective.

See also: https://github.com/ppy/osu-web/pull/10063

**Comment by Joehuu** [comment]
Was going to change but seems to be set with an envar:

https://github.com/ppy/osu-web/blob/130b05ceb9784fbc86fb16000491251c09e84a78/config/osu.php#L220
