### ISSUE TITLE
5-year-old scores without classic mod appearing on leaderboards with lazer mode on

### ISSUE THREAD

**Issue by Evill98** [ppy/osu-web#11194]
Example beatmaps:
https://osu.ppy.sh/beatmapsets/383070#osu/837567
https://osu.ppy.sh/beatmapsets/357777#osu/861164
https://osu.ppy.sh/beatmapsets/644642#osu/1366190

Example scores:
https://osu.ppy.sh/scores/2502027021
https://osu.ppy.sh/scores/2502027022
https://osu.ppy.sh/scores/2502024625
https://osu.ppy.sh/scores/2502024626
https://osu.ppy.sh/scores/2502024627
https://osu.ppy.sh/scores/2502027020

I found a large amount of these by slightly changing the score ID to a nearby one. The scores also have a higher max combo and object count than the beatmap they were set on.

**Comment by peppy** [comment]
`build_id = null` cases, broke with recent reindexing, am running a fix.

**Comment by peppy** [comment]
Flagging of scores has been fixed, and indexing is in progress (the scores listed in this issue are already resolved).

Thanks again for finding this one!
