### ISSUE TITLE
Scaling preset

### ISSUE THREAD

**Issue by MikuOgiwara** [ppy/osu-web#11218]
For Taiko players, we frequently like to change resolutions. However, in Lazer, we cannot change the resolution in windowed mode (which is annoying), and in full-screen mode, Lazer changes the screen resolution directly, causing issues on Windows when you quit lazer. 
Exemple of the issue:
![image](https://github.com/ppy/osu-web/assets/108834620/54d538f5-4007-4898-9bc8-c663e5ba0bdd)

The current solution is to play in full-screen mode with scaling, but since scaling doesn't have presets, it is difficult to change resolutions quickly.

Therefore, would it be possible to have resolution presets for scaling as well as for windowed mode? Thank you very much.

**Comment by notbakaneko** [comment]
Did you mean to make this in https://github.com/ppy/osu ? 
osu-web is for issues related to the website

**Comment by MikuOgiwara** [comment]
oups :')
