### ISSUE TITLE
Topic covers not viewable or editable

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#11226]
I briefly looked into this and it seems like somewhere around #10703 or #10655 is where this all stopped working. not 100% sure though

if it's as bad as it sounds (entirely broken for 6 months) and nobody reported it, I feel like that says something about how low the demand is for this feature... so maybe relevant as a future design consideration or something.

**Comment by nanaya** [comment]
the cover area is a lot smaller now...
