### ISSUE TITLE
Match title on web doesn't update with `!mp name`

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#11230]
```
<clayton> !mp settings
<BanchoBot> Room name: Test title (old), History: https://osu.ppy.sh/mp/114019435
<BanchoBot> Team mode: HeadToHead, Win condition: Score
<BanchoBot> Players: 0
<clayton> !mp name Test title (new)
<BanchoBot> Room name updated to "Test title (new)"
<clayton> !mp settings
<BanchoBot> Room name: Test title (new), History: https://osu.ppy.sh/mp/114019435
<BanchoBot> Team mode: HeadToHead, Win condition: Score
<BanchoBot> Players: 0
```

the new title should be in use at this point, but the page still says old. <https://osu.ppy.sh/community/matches/114019435>

**Comment by nanaya** [comment]
the new title isn't set in database so there's nothing osu-web can do here

**Comment by peppy** [comment]
Is it agreed upon that the newest room name should be used in rename circumstances? If so, I can add support in bancho to do this.

cc @ThePooN for any tournament perspective on this.

**Comment by ThePooN** [comment]
Yep, heard this complaint before, and I see no reason not to. Fine to implement.
