### ISSUE TITLE
Cptcha not appearing

### ISSUE THREAD

**Issue by Bigben9907PC** [ppy/osu-web#11232]
I used Microsoft Edge, Chrome and Opera Gx. The cptcha used for log in does not appear. I do not have any ad block.

**Comment by peppy** [comment]
Please take a screenshot after you click login.

**Comment by Bigben9907PC** [comment]
Here are 2 png.

Text in the captcha (osu.png) : The verification takes too much time.
Please verify your internet connection and refresh the page if the problem
persists.

Text at the bottom (osuerror.png) : Too many failed login attempts. Please
complete the captcha and retry. (Refresh the page if you do not see the
captcha)

I think it might be something with me because I have seen this in Persec
too (I just got a new PC so this is maybe the issue, but if it is, I don't
know how to fix it)

Le dim. 26 mai 2024, à 08 h 46, Dean Herbert ***@***.***> a
écrit :

**Comment by peppy** [comment]
Images not showing up. You'll likely have to use the web interface.

**Comment by Bigben9907PC** [comment]
Unfortunately, I do not know how To do that.

Le lun. 27 mai 2024 07 h 51, Dean Herbert ***@***.***> a
écrit :

**Comment by Bigben9907PC** [comment]
Hello

It seems that it started working again.
Sorry for taking your time for this and have a great day/night !

Le mar. 28 mai 2024 20 h 53, Dean Herbert ***@***.***> a
écrit :
