### ISSUE TITLE
Ambiguous rank change icon in rankings for players with no recent change.

### ISSUE THREAD

**Issue by poroshinleonid** [ppy/osu-web#11241]
The icon for no rank change in #10597 is supposed to signify equality, i.e. no rank change:
<img width="297" alt="Screenshot 2024-05-30 at 17 25 27" src="https://github.com/ppy/osu-web/assets/80582995/92f7d6c1-b6b4-419e-8a5d-68e25830fa74">
However, it looks very similar to a "drag to reorder" icon that is used in Google Material Design:
https://m3.material.io/components/lists/guidelines#60f903da-f93d-411c-be8f-f1299383c44d
Example from a youtube playlist:
<img width="178" alt="Screenshot 2024-05-30 at 17 27 59" src="https://github.com/ppy/osu-web/assets/80582995/c01c6353-1757-4125-ae97-2049d5189611">

Although internal osu! web design guidelines use different "hamburger icon" i.e. three horizontal bars for reordering, considering how ubiquitous the two-bar version is across the internet, I suggest omitting it or at least changing the icon to avoid confusion and make the design more clean and minimalistic.
Example of a ranking table without any icon for players with no rank change: https://www.chess.com/ratings

**Comment by cl8n** [comment]
I don't feel strongly about this so will wait for more opinions. seems fine to me as long as the "not enough history" case keeps its special icon/tooltip

**Comment by notbakaneko** [comment]
maybe a sideways arrow? 🤷

**Comment by peppy** [comment]
I'd either show nothing at all, or a single dash.
