### ISSUE TITLE
Increase the number of maps that can be ranked per day

### ISSUE THREAD

**Issue by Lyti4n** [ppy/osu-web#11267]
The queue is currently the fullest it has ever been with a map just recently qualified is estimated to be ranked in 12 days rather than the 7 its supposed to. There is no sign of this slowing down as 30 mapsets! were qualified in std in the last 24hrs. 

A long term solution should definitely be worked out at some point. But currently there are over 100 bns in std which as far as I'm aware is the most there has ever been. So something has to be done.

**Comment by peppy** [comment]
Yep, I've been getting alerts about this. Will raise with the team.

**Comment by peppy** [comment]
We've decided to increase the daily rank limit to 16 (up from 12). This has been enacted.
