### ISSUE TITLE
[Proposal] Show Qualified maps when searching with "Has Leaderboard"

### ISSUE THREAD

**Issue by Userlog2** [ppy/osu-web#11274]
I believe this change is helpful because it would give Qualified maps much more visibility, since Has Leaderboard is the default setting.

**Comment by cl8n** [comment]
I don't think most people want to search for qualified maps by default though (scores reset)

**Comment by Userlog2** [comment]
If people don't wish to play Qualified maps, they can simply not download them, since they're clearly marked.

**Comment by peppy** [comment]
This would break the default display, so I doubt we'd change it.

Please read "has leaderboard" as "has permanent leaderboard".
