### ISSUE TITLE
Malformed BBCode showing UID

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#11290]
I don't know what causes this or if it's even possible anymore

examples:
<https://osu.ppy.sh/community/forums/posts/2128649>
<https://osu.ppy.sh/community/forums/posts/3177554>

anecdotally I was told this can be found on some older userpages too, but I don't have any examples to show.

**Comment by peppy** [comment]
Thanks, I've applied a fix to these two posts and quite a few others. I don't believe this can be repro'd these days, so we should be good.

```sql
osu> update phpbb_posts set `bbcode_uid` = '1337' where post_text like '%:1337]%' and `bbcode_uid` != '1337'
[2024-06-25 20:48:44] 171 rows affected in 3 m 32 s 306 ms
```

**Comment by cl8n** [comment]
the second one in OP doesn't look fixed, but maybe it's not actually the same problem...? the [bbcode returned for quoting](https://osu.ppy.sh/community/forums/posts/3177554/raw) seems right at least, just an odd/unexpected usage of `[list]`
