### ISSUE TITLE
Scores on leaderboards sometimes display in wrong order 

### ISSUE THREAD

**Issue by Finadoggie** [ppy/osu-web#11295]
Context: I general view the osu! site while not on lazer mode. However, in the midst of a debate with a friend, I switched to lazer mode while looking at the beatmap page for [Padoru Padoru](https://osu.ppy.sh/beatmapsets/1073074#osu/2245774) to grab a reference for lazer score multipiers. It was here where I noticed that the scores were being displayed in the wrong order.
![image](https://github.com/ppy/osu-web/assets/75299710/e7012976-c158-4dde-862b-1271f6be1ea4)
I'm not entirely sure what caused this, as when looking at the site on my computer, the scores display in the correct order. The issue is only present on the specific difficulty I was initially looking at, on only global leaderboards while not filtering by mods. The issue did not persist after reloading the page, and I don't know how to reproduce it.

Phone is iPhone SE (2nd generation), browser is Google Chrome version 216.0.6478.54

**Comment by WindowsMeosu** [comment]
I'll add –  when trying to reproduce the scores are numbered the exact same without lazer mode scoring enabled

**Comment by Finadoggie** [comment]
You can't see it on the screenshot but lazer scores were present on the leaderboard. Could very likely be the result of a browser cache

**Comment by WindowsMeosu** [comment]
> You can't see it on the screenshot but lazer scores were present on the leaderboard. Could very likely be the result of a browser cache

Were they all positioned in a specific place on the scoreboard (e.g., most, if not all, lazer scores were positioned at the bottom of the scoreboard) or were they spread apart? I ask this because .#16 was set on lazer and should've been positioned there. Either way, if lazer scores were present, then I don't think the cause was the result of a cache.

**Comment by Finadoggie** [comment]
can't say if they were in the exact correct spots, but I remember the two lazer hdhr being in the correct spots relative to the hddt scores (spaek above all sses, niccy above all 1x100s)
