### ISSUE TITLE
osu.ppy.sh/scores/osu/xxx returns an odd score

### ISSUE THREAD

**Issue by praeludiumOrbis** [ppy/osu-web#11297]
![image](https://github.com/ppy/osu-web/assets/28674643/015992e9-25a6-411e-8f04-ccf7ceed65f8)

As the title says, putting anything that doesn't start with numbers into https://osu.ppy.sh/scores/osu/xxx returns the above score

For example, https://osu.ppy.sh/scores/osu/h99h causes the behaviour, however with https://osu.ppy.sh/scores/osu/99h I get a "page missing" error.

Since the API always returns the same error, I am assuming that this is a website issue.

Other game modes give a similar result, although not on that map

This works with as many characters as you wish, including special characters and emojis:

https://osu.ppy.sh/scores/osu/Lorem%20ipsum%20dolor%20sit%20amet,%20consectetur%20adipiscing%20elit,%20sed%20do%20eiusmod%20tempor%20incididunt%20ut%20labore%20et%20dolore%20magna%20aliqua.%20Ut%20enim%20ad%20minim%20veniam,%20quis%20nostrud%20exercitation%20ullamco%20laboris%20nisi%20ut%20aliquip%20ex%20ea%20commodo%20consequat.%20Duis%20aute%20irure%20dolor%20in%20reprehenderit%20in%20voluptate%20velit%20esse%20cillum%20dolore%20eu%20fugiat%20nulla%20pariatur.%20Excepteur%20sint%20occaecat%20cupidatat%20non%20proident,%20sunt%20in%20culpa%20qui%20officia%20deserunt%20mollit%20anim%20id%20est%20laborum

https://osu.ppy.sh/scores/osu/⭐⭐⭐⭐⭐

**Comment by peppy** [comment]
Looks like some weird php best-effort casting. Probably should check for numeric and hard bail if not.
