### ISSUE TITLE
profile A ranks achieved not accurate

### ISSUE THREAD

**Issue by boredzoomr** [ppy/osu-web#11308]
when you set an S rank on a score you have an A rank on the A rank gets removed but when doing this I noticed it only happened sometimes, what I saw was that if the A rank was set on lazer and the S rank on stable the S rank gets added but the A rank does not get removed.

So,
if stable score:
A rank 10 ---> A rank 9
S rank 10 ---> S rank 11

if lazer score:
A rank 10 ---> A rank 10
S rank 10 ---> S rank 11

the behavior stays the same when lazer mode is disabled or enabled

I noticed this on mania and do not know if this also happens on standard

**Comment by cl8n** [comment]
it's not reporting the same problem but the cause is the same as has been reported under #8443
