### ISSUE TITLE
modder info does not load for some users

### ISSUE THREAD

**Issue by Shmiklak** [ppy/osu-web#11340]
Today I've experienced an issue on the website when I tried to look up my modding activity to realize I cannot load the page. All I am seeing is an empty page:
![image](https://github.com/user-attachments/assets/7b17732a-8eea-4659-9bb5-fbc263564ff2)
Not sure if the error below might be helpful but it seems to be related:
![image](https://github.com/user-attachments/assets/5fbb7f43-0543-4527-8e8a-d25b9becfb72)

Some profiles I've found where the page does not load as intended are:
https://osu.ppy.sh/users/5504231/modding
https://osu.ppy.sh/users/4452992/modding
https://osu.ppy.sh/users/7777875/modding

At the moment of posting this, the following profiles worked as intended:
https://osu.ppy.sh/users/5596337/modding
https://osu.ppy.sh/users/14102976/modding

Tested it on different devices and browsers, the result is the same.

**Comment by Joehuu** [comment]
Seems to be resolved now.
