### ISSUE TITLE
Daily challenge box is visible without lazer mode

### ISSUE THREAD

**Issue by mcendu** [ppy/osu-web#11357]
Stable do not have daily challenges (and won't for the foreseeable future) and stable players won't find it to be of any use, so might be a good idea to make the daily challenge box Lazer mode only.

**Comment by cl8n** [comment]
personally indifferent, but I'm not sure if people thought that disabling "lazer mode" was meant to truly hide everything possible related to lazer

I know this isn't much in the way of precedent, but fwiw lazer-only spotlights badges have always been showing regardless of "lazer mode" as well

**Comment by archhaze24** [comment]
third-party opinion: this should remain as it is
1) daily challenge might be a thing that will push players towards playing lazer, something like its advertiser
2) daily challenge results might be considered as a player's personal achievement, so it will be kind of disappointing for player who put effort in playing daily challenge to remove it from the majority of people's website

**Comment by peppy** [comment]
Other stable-only stats are visible in lazer mode.

The lazer mode toggle is for scoring, not *anything and everything*.
