### ISSUE TITLE
Some profiles show a wrong daily challenge streak count

### ISSUE THREAD

**Issue by felipemarins** [ppy/osu-web#11378]
Some profiles show the incorrect count for streaks and total days played on the daily challenge stats. They somehow show a number greater than the actual number of times the daily challenge happened (which is 7 days, counting the current one).

Examples:
https://osu.ppy.sh/users/25147623
https://osu.ppy.sh/users/16426425
https://osu.ppy.sh/users/1023489

**Comment by peppy** [comment]
@nanaya can you take a look into this?
