### ISSUE TITLE
Time says "now" for every score on the leaderboard

### ISSUE THREAD

**Issue by Phippe** [ppy/osu-web#11404]
For [this map's](https://osu.ppy.sh/beatmapsets/1282615#osu/2663920) leaderboard, every score was set "now":

![now](https://github.com/user-attachments/assets/c8890fea-c28f-4dd0-b07b-2b7c62addac2)

It depends on which language you're viewing the page in. It happens for English and maybe a third of the other languages (Belarusian, Catalan, Czeck, and more).

As this map seems to be a bit buggy, this might be related: I've got first place by being the first to play the map and have lost it since.  I got a message on [my profile](https://osu.ppy.sh/users/6902843#recent_activity) for the former, but nothing for the latter.

**Comment by notbakaneko** [comment]
This is intentional #6567

**Comment by Phippe** [comment]
I see. In that case it's a matter of updating the translations.

Personally, I would've put it only for scores set within the last minute, since a whole hour is a generous definition of "now". But yeah, then we're back at the problem of differentiating minutes and months, making everything harder to parse. I see, I see...

**Comment by nanaya** [comment]
Intentional, as mentioned above. Feel free to update the translations in crowdin or ping relevant translators.
