### ISSUE TITLE
Incorrect display of Strick in the Daily Challenge statistics when Russian is enabled

### ISSUE THREAD

**Issue by SenorNikicho** [ppy/osu-web#11429]
In the Daily Challenge statistics, the Streak in days and weeks is displayed as "[count]dд" and "[count]wнед", respectively (instead of "[count]д" and "[count]нед"), if the Russian language is enabled on the site.

Screenshots: 
![Screenshot_20240812_211223_Yandex Start](https://github.com/user-attachments/assets/d5748425-f19e-4cf7-8bee-50d20e23d343)
![Screenshot_20240812_211237_Yandex Start](https://github.com/user-attachments/assets/c50adf01-fb51-45c1-b54e-9ec863f8ca61)

**Comment by nanaya** [comment]
looks like it's been fixed in crowdin so it should be fixed by the next translation update and deploy
