### ISSUE TITLE
Daily challenge stage colour doesn't change

### ISSUE THREAD

**Issue by Tenexxt** [ppy/osu-web#11424]
DC streaks have stages, 
7 days+ - bronze 
14 days+ silver
The problem is that on the smaller display of the DCS the gradient is shown as bronze, even tho after hovering on it to show full statistics it shows silver
![Untitled50_20240810193127](https://github.com/user-attachments/assets/dc0c96be-69d8-4bd6-90be-61f02941cb74)

This happens on mobile and PC

**Comment by nanaya** [comment]
the main stats (playcount) takes three times as long compared to the streaks count
