### ISSUE TITLE
Daily challenge streak continues even after missing one day

### ISSUE THREAD

**Issue by felipemarins** [ppy/osu-web#11422]
As far as I know, the streak should break if you don't set a passing score on some day. But my profile still shows the daily challenge streak as if I did set a score on all of them, even though I didn't set one on august 5.

Profile: https://osu.ppy.sh/users/25147623

Edit: The august 5 daily challenge shows up on playlists tab of my profile, but I didn't set any passing score on it as I stated above.

**Comment by DanonymousCoder** [comment]
Hi, can I work on this issue?

**Comment by peppy** [comment]
![Safari 2024-08-13 at 10 14 11](https://github.com/user-attachments/assets/386ef152-541a-4c86-a4bd-2ecba7d6da39)

It looks correct?

The main number on your profile is not streak but total days participated, if that's what might be confusing you.
