### ISSUE TITLE
View Country inside Rankedscore leaderboard 

### ISSUE THREAD

**Issue by nyaruku** [ppy/osu-web#11434]
I think it would be good to be able to see a country's rankedscore leaderboard, as for now you can only see who have the most pp in a country.

**Comment by Maximilian-Maag** [comment]
So this means you like to see for example 0 points for germany and 12 for sweden for example?

**Comment by WindowsMeosu** [comment]
duplicate?
https://github.com/ppy/osu-web/issues/4816

**Comment by Joehuu** [comment]
yep
