### ISSUE TITLE
Outdated ruleset chat channel descriptions in web/lazer

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#11444]
`#taiko`, `#ctb`, and `#osumania`

E.g.

![firefox_4F2raAMBxq](https://github.com/user-attachments/assets/d1ce550d-cdc1-4de7-89ee-a7792d5681e0)

Seems like stable's was updated but didn't transfer over:

![osu!_bQBVAaOG1p](https://github.com/user-attachments/assets/e5d9f0d1-c657-4ca1-a93a-12d8f633c05e)

**Comment by peppy** [comment]
Closed via https://github.com/peppy/osu-bancho/commit/48584f52fb437d241b2a04b91cc3b1c46420d792! Deploying today.
