### ISSUE TITLE
Allow beatmap searches to return undownloadable maps that you've played

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#11447]
from <https://discord.com/channels/188630481301012481/1097318920991559880/1276144550263525398> but I've had this idea before too and seen similar frustration among friends.

currently, undownloadable (because DMCA basically) maps are not indexed for search at all. I understand osu wants to limit discovery of these maps to honor takedown requests properly so that's usually fine. however a case that can be really annoying is when you are trying to search for a map you already know about -- but not enough to find its link elsewhere -- and you end up wasting your time searching for a map that will never appear in the results, and you may not even know it was DMCAd. either that or you just want a search to match against the complete set of maps you've played with no exceptions

if this is negotiable at all I suggest indexing download-disabled maps, but only include them in searches if they've been played by the user. this would solve most of the annoyance while still avoiding advertising the maps to any new audience via search

**Comment by peppy** [comment]
Sorry but this isn't going to happen. Part of the DMCA procedure is to delist from all search indexing. This will not change.
