### ISSUE TITLE
Option to automatically subscribe to topics that you reply to

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#11474]
basically I want this
![image](https://github.com/user-attachments/assets/539ee1d9-45fa-4405-b4e0-f334ef2d5e98)
but for "reply to" in addition to "create". I don't think I've ever replied to a forum topic without subscribing immediately after, unless I forgot to...

I don't know if this makes more sense as a separate option or just an extension of what the existing one already does.

**Comment by peppy** [comment]
Seems like something we want. I thought this already existed.

Maybe the existing option could just include this and be reworded even? I think most people would want this.
