### ISSUE TITLE
Unable to properly highlight song artist & name on the beatmap page

### ISSUE THREAD

**Issue by 0x84f** [ppy/osu-web#11472]
This has bugged me for years, but I seemingly can't find any issues relating to it?

On the beatmap page it's just impossible to highlight the artist and song name without highlighting the mapper details as well.

I posted an example of what I'm seeing below:
![firefox_ArS88BtHRI](https://github.com/user-attachments/assets/df708b0e-f43e-46e4-88b7-10f9cb8c27c4)

You can get away with it if the artist name is longer than the song name, however it's not very intuitive:
![firefox_q55pQ8ZkFV](https://github.com/user-attachments/assets/a4311699-3895-4ceb-ba0e-21ebcd57b575)

Using Firefox 129.0.2

**Comment by 0x84f** [comment]
i figured out how to do it but its not really intuitive and again it only works if the artist name is longer than the song name?
![firefox_q55pQ8ZkFV](https://github.com/user-attachments/assets/a4311699-3895-4ceb-ba0e-21ebcd57b575)

**Comment by nanaya** [comment]
in the meantime you can hold alt, triple click the title and drag down to the artist (the actual text, not the line)
