### ISSUE TITLE
Messages from the filtered list shouldn't be filtered client-side on web

### ISSUE THREAD

**Issue by 0x84f** [ppy/osu-web#11496]
Currently, if you write a filtered word on osu-web, the message will automatically be filtered client-side, which in turn allows users to brute force words to figure out what the filter is, and figure out ways to bypass the filtered word list.

This is behaviour that only exists on osu-web (and lazer, but that's out of scope for this repo), on stable the message appears as it was originally sent to the user.

example:

https://github.com/user-attachments/assets/07c33177-b7f2-4cdc-a8b9-6481254a6de9

**Comment by bdach** [comment]
I'm not sure how realistic it is to resolve this given that the same filters are also applied to stuff like multiplayer room names, at which point you can brute-force again.

**Comment by cl8n** [comment]
I don't think it's very difficult to figure out how to bypass filters regardless, and people share lists of these filters that afaik are mostly accurate/complete. I vote just keep this how it is right now because having your message edited without your immediate knowledge has got to be one of the most unanimously hated features in the game...

**Comment by notbakaneko** [comment]
I think users should be seeing what they're getting and discover it's something else after the fact

**Comment by 0x84f** [comment]
i agree with you, however i raised this on behalf of the GMT (and some members dont necessarily agree with you) so i will let them chime in and explain their reasoning

(there is also a thread in #gmt about this but i think clayton doesnt have access so might as well keep the discussion here)

**Comment by Laurakko** [comment]
I agree with what cl8n said about it being infuriating when your message gets edited without telling you, and some filters even end messing up common words in some languages (eg. finnish word for song), but for vast majority of things that get filtered, it doesn't impair normal conversation, and those cases that do should probably be removed from the filter anyway.

Here's a simple scenario

osu_user727: skibidi toilet

filters out to public toilet

Scenario A: filters don't get applied on user end:
People either disregard them, or they ask what are they talking about, you can !faq topic that

Scenario B: filters get applied
osu_user727: loool skibidi turns to public
Then they start experimenting to try to bypass the filter.

Point being, that most of the filtered words are there for a reason, and i personally think the way stable behaves is better, from a moderator point of view anyway. You don't want the user to figure out that the game filters their favourite slur to something else, which highly likely ends up them trying to immediately bypass the filter. That adds a buffer for a moderator to be able to interject.

**Comment by peppy** [comment]
I prefer the fact that users now see it. They will infer that the word is not allowed on this game.
