### ISSUE TITLE
Change the display color for mutual subscribers.

### ISSUE THREAD

**Issue by juices95** [ppy/osu-web#11513]
[ proposal ]  We can add friends mutually through colors; why not with subscribers   ：o

https://github.com/user-attachments/assets/29d2f764-eff5-4a21-9dbd-53873779851e

**Comment by cl8n** [comment]
i dont really see the point. I also wouldn't expect my subscriptions to be (semi-)public info

**Comment by juices95** [comment]
Indeed, for some people.
However, we can access the Privacy settings to manually enable it.

**Comment by peppy** [comment]
Doesn't seem like something we'd want.
