### ISSUE TITLE
Poll option overfills when an image put inside it.

### ISSUE THREAD

**Issue by Blooshing** [ppy/osu-web#11516]
https://osu.ppy.sh/community/forums/topics/1983640?n=1 

In the post it seems the user put some images inside a poll that were a little large and this caused it to fill the page with the full image size instead of resizing it to the poll box. 

![Blushing20240929-1727583095](https://github.com/user-attachments/assets/6fbd3658-31c2-4942-9870-37025f364cad)

**Comment by peppy** [comment]
I'm not sure we should even support images inside polls, seems like a design nightmare

**Comment by notbakaneko** [comment]
Polls just support the same bbcode as regular posts, so there's spoiler boxes and what not as well...
