### ISSUE TITLE
Source is covered by difficulty icons in favourite beatmaps

### ISSUE THREAD

**Issue by Oqwert** [ppy/osu-web#1152]
![ss 2017-05-17 at 09 09 51](https://cloud.githubusercontent.com/assets/18227892/26171471/56ac8da6-3b45-11e7-9c89-db05411c5267.png)

**Comment by nekodex** [comment]
What operating system and browser are you using?

**Comment by Oqwert** [comment]
Chrome, Windows 10 x64, 1920x1080

**Comment by nanaya** [comment]
Can't reproduce. Comment here if still having this problem.

**Comment by Oqwert** [comment]
I still have this problem but it only happens on Chrome. I am not using zoom nor text scaling in windows, and font size in Chrome is set as default. I have no idea what is causing this, but I blame the browser for it since I've seen other similar overlapping stuff in other websites.

**Comment by nanaya** [comment]
do you have minimum font size set to something like 12 or larger?

![](https://s.myconan.net/2017-07/chrome_2017-07-19_18-13-03.png)

**Comment by Oqwert** [comment]
Yes, I tried using a smaller min font size and the problem was gone (which I find pretty weird since my previous settings were untouched since I resetted Chrome settings a while ago). Sadly I can barely read text this small due to sight problems, so I guess I will have to stick with the old size.
