### ISSUE TITLE
Several beatmaps have mismatched MD5 checksums between API and downloadable .osz file

### ISSUE THREAD

**Issue by quantizedSpacetime** [ppy/osu-web#11551]
This issue is functionally identical as far as I can tell to a previous issue, raised at [ppy/osu-web/issues#6407](https://github.com/ppy/osu-web/issues/6407), but I'm separating this because it involves a wider set of beatmaps than previously mentioned.

Some beatmaps have mismatches between the .osu file found in the .osz when you download off the website and the "true" most up-to-date version found, for example, on `osu.ppy.sh/osu/<beatmap_id>` or through an API request. This causes the checksum of the file not to match the expected checksum after download. I've identified the issue for all the following beatmap ids (not exhaustive, only ones I've found through playing):

| Beatmapset ID | Beatmap ID | Checksum by API request (correct) | Checksum from .osz download (incorrect) |
|-------------| ----------------|-----------------------| -----------------------------------|
| 54 | 141 | ac6e971d689e87e12d8c170e1f5b31ff | 50791b017c9d43382403f343fdb62c77 |
| 55 | 162 | eb3580e42f8510117fc2df91b71e2e73 | 74c29c4a354125c5f53ac73dc2c5c1a7 |
| 56 | 164 | 2ef0fe54648fb149dab9580df6d06080 | 6b4fd1917a8093f70c2174104788265e |
| 57 | 144 | 7c9eb2fcb5667d00eb7edf317f260adf | c8d807d2d0da513b2d0bff9c133548e9 |
| 58 | 146 | 306fd57cabaf6ede45e2513800becc59 | f9bb3d924ee9ce4d2e0e77bc55e29e83 |
| 59 | 147 | 21b4a375d307258be868737b7f1d5d6c | 05edf9da65e6652bf5954deffc2c5723 |
| 62 | 200 | 010ed9fe027189be566ccae344f401de | 8e511a406999252f108afc2ffbc3911e |
| 63 | 250 | 3275bc96a887eebf3229f4e960e53bfc | 2c292eeb874fffc5d11f639a5805a320 |
| 64 | 195 | ffb857952109af9ff1b958c3055d8f14 | fcf6f7640c0e434306554262f9ea2bee |

I confirmed that the issue can be fixed by importing files downloaded from the `osu.ppy.sh/osu/<beatmap_id>` link directly, meaning that it's an issue specifically with the downloadable .osz and not a more general problem.

All of these are from October 8th/9th 2007, but I don't know if that has anything to do with it since the map from the original issue is not a 2007 map. It's possible, though I'm not qualified to know for sure, that this is some systematic issue with old maps because these beatmaps represent nearly a third of all the beatmaps submitted on those days. Regardless, I think the .osu inside of the .osz download should be updated just like the issue cited above for each of these. 

Updating to add more IDs I found with the same issue, I won't list all the MD5's unless requested since it's all just numbers:
beatmapset ID / beatmap ID: 92 / 208, 92 / 207, 91 / 204, 65 / 155, 66 / 178, 67 / 160, 70 / 159, 71 / 161, 72 / 166, 73 / 167, 74 / 171

**Comment by HollisMeynell** [comment]
Even some beatmap id are inconsistent with the beatmap id in the file content, after I raised the issue, the developer said checksum would affect the local ranking (￣Д￣)
 [link](https://osu.ppy.sh/community/forums/topics/1983690?n=4)

**Comment by peppy** [comment]
I wrote a script to repair the osz files but stopped short because it breaks local replays and would not have updated beatmap packs.

Not sure what the path forward is yet.

**Comment by peppy** [comment]
@quantizedSpacetime all of these should now be fixed.

**Comment by iijj22gg** [comment]
Can confirm beatmap downloads are now working

**Comment by peppy** [comment]
Thanks, going to close this one for now.
