### ISSUE TITLE
can't change difficulty owner if username is numbers only

### ISSUE THREAD

**Issue by tatitatai** [ppy/osu-web#11550]
Forwarding from the help forums: https://osu.ppy.sh/community/forums/topics/1989067?n=1

Example map: https://osu.ppy.sh/beatmapsets/2262179/discussion/-/generalAll/total
Try to link user "621" to "KPolar's Insane". Tried on my own maps, didn't work aswell. 

Only assumed it might be due to the numbers because I've also tried with a random active user called "473" and didn't work aswell

**Comment by nanaya** [comment]
prefix with @ to search by username

**Comment by tatitatai** [comment]
Thank you!!
