### ISSUE TITLE
Allow replay download with client credentials token

### ISSUE THREAD

**Issue by Loluh** [ppy/osu-web#11579]
im trying to do an app for getting the top 10 monthly plays(including replays) of my country, but i do not seem to be able to get lazer replays download with client credential flow (public scope), can it be added?

**Comment by minisbett** [comment]
+1 for this, would be very neat when integrating the API in a backend service. The alternative is the developer manually doing the code-flow and ensuring the access & refresh token don't expire, which is both annoying to do and not the intended use of code-flow.

First thought was using the `delegate` scope to be the resource owner but that seems only supported by chat bots...

**Comment by peppy** [comment]
Seems probably fine.
