### ISSUE TITLE
More graphs for the user profile page

### ISSUE THREAD

**Issue by nekodex** [ppy/osu-web#1157]
Graphs for `play history` and `replays watched` are missing on the new profiles

Probably requires design work from @arflyte

**Comment by arflyte** [comment]
![photoshop_2018-02-15_12-11-14](https://user-images.githubusercontent.com/3632750/36238978-8f364848-1249-11e8-8e55-207bfe59edfc.png)

The design is already there, just that it's not implemented yet. `Replay watched` should have similar design.
