### ISSUE TITLE
"reply” button appears in the center in comments section

### ISSUE THREAD

**Issue by gkr-758** [ppy/osu-web#11586]
Previously displayed on the left side.
I assume that the comment button was also centered when it was modified in https://github.com/ppy/osu-web/pull/11560.
![image](https://github.com/user-attachments/assets/7bd4ec1d-868e-4c4c-a507-f0d5e371b0cb)

**Comment by nanaya** [comment]
for my own reference, it's `justify-self` recently updated to have effect inside block element.

**Comment by notbakaneko** [comment]
Is there something I'm missing here, I don't see it happening?
