### ISSUE TITLE
Display temporary tournament bans on user profiles

### ISSUE THREAD

**Issue by hburn7** [ppy/osu-web#11590]
This is directly related to #9018 and #9019. I'm raising a new issue as I feel the functionality of displaying temporary tournament bans was missed when implementing this feature, thus this is a bug report. If it is a deliberate decision to not display temporary tournament bans, I would be interested to know why, as both #9018 and #9019 display temporary bans in their UI mockups (and a vast majority of tournament bans are temporary).

Currently, users with temporary tournament bans do not have a matching entry in the account history section.

**Comment by Albionthegreat** [comment]
Having temporary tournament bans displayed on user profiles would be incredibly useful. I believe there are multiple benefits, making this more than worthwhile.
- Tournament-banned players will be able to tell when their tournament ban runs out, thus removing the need to send an email to support to ask.
- Allows tournament organisers to avoid recruiting staff that are tournament banned, where currently the only way they would learn this information is from the tournament banned user themselves.

Having indefinite tournament bans displayed on player profiles is great, and I believe all parties would benefit from doing the same for temporary ones. This is something we absolutely want.

**Comment by notbakaneko** [comment]
Non permanent bans aren't displayed after a certain period of time (I believe the default is 28 days?).
So is the issue that there are temporary bans that are longer than the 28 days and thus won't be displayed even if they're still active?

**Comment by Hiviexd** [comment]
solution could be to display non-permanent infractions for their entire duration, with a minimum of 28 days to maintain current behavior for most common cases.

**Comment by peppy** [comment]
Sounds fair.

**Comment by nanaya** [comment]
the table doesn't have explicit end time though, only start time and duration.

**Comment by nanaya** [comment]
yeah, I guess with the permanent flag addition it already needs to check all rows anyway.

**Comment by nanaya** [comment]
that said, there's exactly one non-permanent (`permanent = 0`) tournament ban (`ban_status = 3`) entries in the database right now. And it expired already last year.

Are they stored somewhere else?

**Comment by Hiviexd** [comment]
we were instructed to avoid applying non-permanent tournament bans because:

1. they apply silences on users
2. there's currently no way to remove them
3. they stop displaying after 28 days even when still active

1 and 2 are most likely ASS-related, so for osu-web 3 (and possibly 1?) need to be addressed.

**Comment by nanaya** [comment]
The number 3 seems weird because moderators should still be able to see everything and setting it as anything else means only moderators can see it (and no easy way to fix it now?).

**Comment by Userlog2** [comment]
Sounds good, because:
1. It allows hosts to check e.g. emergency refs for tournament bans without having to rely on the player
2. It allows non-officially supported (unbadged) hosts to consider tournament bans, including those stemming from recent restrictions

The issues Hivie points out should absolutely be fixed, though.

**Comment by Hiviexd** [comment]
- Issue being likely bancho-sided sounds possible. Maybe it's lacking the distinction for tournament bans and is applying silences to any type of active "ban"?
- Yes.

sidenote, it may be a good idea to doublecheck if there's any web limitations on some test account/local dev instance with an active tournament ban. (temporary or permanent)

**Comment by peppy** [comment]
The silence part should now be fixed.

**Comment by peppy** [comment]
Removal command also added to ASS.
