### ISSUE TITLE
News banner `@2x` images don't display anymore

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu-web#11599]
the news cover image used to display in a 2x size depending on resolution/browser via a `srcset` attribute, but it doesn't appear to be there anymore

![image](https://github.com/user-attachments/assets/ca34f869-7d01-4f38-b94c-22028e498ca0)

image in screenshot
https://github.com/ppy/osu-wiki/blob/master/wiki/shared/news/banners/pp-sr-pippi.jpg (1000 width)
https://github.com/ppy/osu-wiki/blob/master/wiki/shared/news/banners/pp-sr-pippi@2x.jpg (2000 width)

issue happens in all the places where news covers appear
https://osu.ppy.sh/ (logged in and logged out)
https://osu.ppy.sh/home/news
https://osu.ppy.sh/home/news/2024-10-28-performance-points-star-rating-updates

**Comment by nanaya** [comment]
I don't think that's ever a thing but yeah that's doable. Just need to make sure there's 2x version of all news header images
