### ISSUE TITLE
Attempt to assign country more frequently when initial assignment failed

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu-web#11592]
I guess this is happen until they have atleast 1 pp - https://osu.ppy.sh/users/35107890/osu

**Comment by Orangemoody** [comment]
usually the country assigned to users like this (xx) are placeholders until they login but for whatever reason they never got one
its unrelated to pp, _many_ accounts havent even played the game but have countries assigned to them

**Comment by peppy** [comment]
How did you find this user in this case?

**Comment by Moltanicaa** [comment]
Top 1 on some qualified map
![yQutzyYvk1cUrWZGGniBCceFkkwcHPVJ1bZQqxCrUM2LC3BnWrC69XTpYUdyLdqks1lWDNawhQgD1YuJxhgbxaax.jpg](https://github.com/user-attachments/assets/4534e14e-4078-4bbf-8bea-9d2eda3b7852)

**Comment by peppy** [comment]
@nanaya can you take a look into this one? seems like it might be related to the user creation flow on osu-web.

**Comment by nanaya** [comment]
it just takes whatever cloudflare says and reset to XX if the country doesn't exist in database

**Comment by nanaya** [comment]
I guess osu-web can keep checking the country header on access until it resolves to something known.

**Comment by peppy** [comment]
Probably on each login request yeah. web-10 does this as well, every bancho connect.
