### ISSUE TITLE
Pages not meant to be indexed in search included in search engine (Google/Bing) results

### ISSUE THREAD

**Issue by Awesome-Aasim** [ppy/osu-web#11596]
The robots.txt file that practically every website has to control search engine and web crawler indexing is missing. This results in pages like the account edit and password reset page being indexed. Such pages should not be included in external search engines for obvious reasons.

Certain pages being indexed like the wiki or the forums aren't problematic, but others like the beatmap search are.

This should be combined with other measures to disallow search engine indexing of pages not meant to be indexed.

**Comment by nanaya** [comment]
we already exclude pages that needs to be excluded through other means.

also, there's no reason to exclude pages like password reset. being able to search for "<sitename> password reset" and get the expected result can be useful for example.
