### ISSUE TITLE
Most notifications vanished over night

### ISSUE THREAD

**Issue by minetoblend** [ppy/osu-web#11611]
Of the 176 notifications I had yesterday only 19 seem to exist anymore. I asked a couple more people if the same happened to them and they're seeing the same thing. The page the `see all notifications` button redirects to doesn't show them either.
I can't really see a pattern with which notifications are gone as some from 5 months ago are still there, but some that were just a couple hours old disappeared.

### Notifs yesterday
<img width="250" alt="image" src="https://github.com/user-attachments/assets/9fd7a8ac-9294-412b-ab79-7740e6dfe421">

### Notifs today
<img width="275" alt="image" src="https://github.com/user-attachments/assets/b208495c-c115-450f-a70b-dad8d8c57716">

My profile in case its relevant: https://osu.ppy.sh/users/6411631
Other users I know this happened to are [CutoNaito](https://osu.ppy.sh/users/8064649) and [NiceAesth](https://osu.ppy.sh/users/7782553)

**Comment by nanaya** [comment]
There was some cleanup earlier today though I don't know exactly how it was done. I don't think it's supposed to touch unrelated users' notifications though...

@peppy should know the details

**Comment by peppy** [comment]
I'm working to restore these now

**Comment by peppy** [comment]
> Oh, it looks like some of the most recent notifications didn't get restored.

Restoration will be ongoing at a slow rate for the most recent 24 hours (have to wait for backup data to become available) but they will come back.

I'll close this issue now as the majority (99%) have been restored. Thanks again.
