### ISSUE TITLE
Plays with lower PP can top plays with higher PP.

### ISSUE THREAD

**Issue by ZenoG2** [ppy/osu-web#11620]
![image](https://github.com/user-attachments/assets/af0e9cb3-61bb-444a-a5ed-751cb61c9352)
Affected user: ZenoGG.

**Comment by Joehuu** [comment]
The pp of scores are being reprocessed right now, see https://osu.ppy.sh/home/news/2024-10-28-performance-points-star-rating-updates:
> During this period, scores in "best performance" may look to be out of order or not be visible at all. Also, your global rank might jump around momentarily as not all users will be recalculated at once.
