### ISSUE TITLE
Website still shows Lazer as avalable for Windows 8.1

### ISSUE THREAD

**Issue by ZenoG2** [ppy/osu-web#11621]
This is in false.
![image](https://github.com/user-attachments/assets/b75cb629-462a-4fa5-88f9-6ddadbdd925f)

**Comment by Joehuu** [comment]
It still works in Windows 8.1. GitHub shows the supported OS for some reason, but does mention this:
> If your platform is unsupported or not listed above, there is still a chance you can run the release or manually build it by following the instructions below.
