### ISSUE TITLE
can not find a score in `/beatmaps/{beatmap}/scores/users/{user}`

### ISSUE THREAD

**Issue by mas-alone** [ppy/osu-web#11643]
when i use
`https://osu.ppy.sh/api/v2/beatmaps/4663536/scores/users/5321112?mode=fruits`

The api retuen `null`

this score is played at `stable`. 

And i should need use:
`https://osu.ppy.sh/api/v2/beatmaps/4663536/scores/users/5321112?mode=fruits&legacy_only=1`
To get correct data

`legacy_only` Defaults to 0, But shouldn't it return all scores by default? Other users seem to be able to return the data correctly

At present, only this score is found to return `null` , Other score the data can be returned correctly(also played at stable):
`https://osu.ppy.sh/api/v2/beatmaps/4300876/scores/users/5321112?mode=fruits`

Header:
x-api-version: 20241009

**Comment by nanaya** [comment]
it's another case when the user's score is deleted in database but not in index. Should be fixed for this specific score.
