### ISSUE TITLE
Some scores are not sorted correctly in leaderboards

### ISSUE THREAD

**Issue by AmnezziaCS** [ppy/osu-web#11650]
## Description

Following the unban of a friend of mine, him and I have noticed that some of his scores were sorted weirdly on the website (lazer and classic mode, in-game leaderboards are not affected by this). The issue being that some of his scores are not placed at the correct leaderboard spot. On every example shown here, the maps were played with 4 mods and have no spinners meaning the first SS rank should be the `#1`.

Some examples of maps where this happens (note that there are a lot more):
- https://osu.ppy.sh/beatmapsets/1827765#osu/3818042
- https://osu.ppy.sh/beatmapsets/1900674#osu/3998229
- https://osu.ppy.sh/beatmapsets/1928041#osu/3981780

## Investigations

On every one of the maps I have linked. He was the first one to submit and this actually shows when looking at the score times ([using this map as an example](https://osu.ppy.sh/beatmapsets/1900674#osu/3998229)):
![{0C5F24DA-5316-4F47-81A7-4674C0BE7605}](https://github.com/user-attachments/assets/e6338b9f-b4ca-4948-9484-5be730faa52a)
![{F31DB084-C21E-407B-AE14-4298659162B3}](https://github.com/user-attachments/assets/cf02cdc8-b1d2-41de-9686-53b94eed0ee2)
We can clearly see that the first submitted score was MystExi's one.

It seems to me that the issue comes from the scores IDs being reprocessed while he was banned. If we take a look at the scores I've just shown the dates of:
- https://osu.ppy.sh/scores/1688279698 (ImMyyrh's score)
- https://osu.ppy.sh/scores/1688279719 (MystExi's score)

```sh
1688279698 < 1688279719 # but it should be the opposite...
```

MystExi's score should in theory have a lower id since he was the first one to submit yet it's not the case here.

**Comment by cl8n** [comment]
seems similar to #11553

**Comment by peppy** [comment]
Same issue, duplicate. Will continue tracking at #11553.
