### ISSUE TITLE
Difficulty names/star ratings not showing when hovering on beatmaps in beatmap search

### ISSUE THREAD

**Issue by MelonIs45** [ppy/osu-web#11663]
When hovering at this part of the beatmap box it should display all the difficulties and their star ratings like it does here:
![image](https://github.com/user-attachments/assets/fefd8cbc-ea95-46a5-84a2-bfed77e017f5)

But in beatmap search it does not do this:
![image](https://github.com/user-attachments/assets/eb5dcf1c-9c30-46e4-8f3e-9b8a2b9ff4d2)

**Comment by nanaya** [comment]
which browser is it? seems fine here in firefox 128 and chrome 131.

**Comment by MelonIs45** [comment]
im on firefox 132 and a friend who also has this issue is on firefox 123

**Comment by nanaya** [comment]
I just tried on firefox 132 and it works fine too. Maybe try disabling extensions/custom styles/scripts?

**Comment by MelonIs45** [comment]
oh yeah i just tried in a private window with most disabled and it works again, sorry for the false flag :S
