### ISSUE TITLE
Country ranking incorrect for Serbian players outside of top 3

### ISSUE THREAD

**Issue by 0x84f** [ppy/osu-web#11665]
As per the title, it appears that there's either a issue that occurred after the pp recalc, or there's a hidden entry on the country ranking list since everyone's country rank outside of the top 3 has +1 added to it, has been happening for over a week at this point

![image](https://github.com/user-attachments/assets/0be013bc-476f-4f74-b18e-3c235e372457)
![image](https://github.com/user-attachments/assets/c2ddc948-1906-4dd1-9c05-9223b9c5df37)

Wasn't really sure whether to just post in the Discord or make a Github issue on osu-web, let me know if this needs to be reposted anywhere.

**Comment by peppy** [comment]
This should be fixed now. Some data was in a stale state. Thanks again for pointing it out!
