### ISSUE TITLE
Profile `Recent activity` links behave weirdly

### ISSUE THREAD

**Issue by AmnezziaCS** [ppy/osu-web#11691]
## Description

When clicking a link in Profile `Recent activity`, I expect to be redirected to the beatmap difficulty mentionned in the text. However that's not always the case.

### When `left clicking` a link in `Recent activity`

❌ You get redirected to the `beatmapset` link.

Example with my recent activity:
![image](https://github.com/user-attachments/assets/243986db-777d-4955-ab6e-ce167f2f4456)
I get redirected to https://osu.ppy.sh/b/2116764?m=0 which leads me to https://osu.ppy.sh/beatmapsets/989704#osu/2108044 instead of https://osu.ppy.sh/beatmapsets/989704#osu/2116764.

### When `ctrl clicking`/`scroll clicking` a link in `Recent activity`

✔️ You get redirected to the `beatmap` link.

Example with my recent activity:
![image](https://github.com/user-attachments/assets/243986db-777d-4955-ab6e-ce167f2f4456)
I get redirected to https://osu.ppy.sh/beatmapsets/989704#osu/2116764 which is correct.

**Comment by AmnezziaCS** [comment]
perhaps duplicate of https://github.com/ppy/osu-web/issues/11682

**Comment by cl8n** [comment]
yep.
