### ISSUE TITLE
Mixed (cached?) translations in page after switching the website language

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu-web#11707]
Dashboard / any other tab (in Italian):
![image](https://github.com/user-attachments/assets/12f507f6-526b-4aaa-8d75-9bf66d0ffe02)

When I go to the friends section:
**Note the tab names in English, and I could swear that the sort options were localized before.**

![image](https://github.com/user-attachments/assets/ba2d5ebf-c949-4305-82fc-02c280918aa8)

**Comment by Gabixel** [comment]
Apparently now it's in Italian.. not sure what happened. Maybe it was a local cache

**Comment by Joehuu** [comment]
There is some sort of language setting desync of certain strings, and happens consistency. Have reproduced in Firefox and Edge.

![firefox_K7WuhUL4qL](https://github.com/user-attachments/assets/f24df7db-00e7-4074-a3d7-bf4aaa701c22)
