### ISSUE TITLE
Change Twitter to X

### ISSUE THREAD

**Issue by RutsuKun** [ppy/osu-web#11711]
Since Twitter changed its name to X it would be useful to change the logo and name on the site.

**Comment by peppy** [comment]
nah i'd sooner remove twitter altogether.

also discussion at https://github.com/ppy/osu-wiki/issues/12500 for future of "social media" presence.

**Comment by RutsuKun** [comment]
Are you sure we're talking about this button?
![image](https://github.com/user-attachments/assets/35a26962-47c7-415b-a4a4-0186fcddfb92)

**Comment by RutsuKun** [comment]
@peppy
