### ISSUE TITLE
Voting on feature requests

### ISSUE THREAD

**Issue by nekodex** [ppy/osu-web#1173]
We need to display current star priority at a minimum

**Comment by nanaya** [comment]
E_NODESIGN

**Comment by arflyte** [comment]
Welp still no design on this. Will work on it.

**Comment by peppy** [comment]
@nanaya did you already start on this one?

**Comment by nanaya** [comment]
Is it this one?

https://github.com/ppy/osu-web/blob/d87a36aa5518314634d2fe49265c5bc5944b19b9/resources/views/forum/topics/show.blade.php#L69

**Comment by peppy** [comment]
Yeah that looks relevant.

**Comment by peppy** [comment]
as discussed, since this is basically already implemented, let's get this live with an arbitrary design and rework it at some point later.
