### ISSUE TITLE
Kudosu in moddingv2

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#1261]
The kudosu system in moddingv2 needs the following:

- [ ] A disqus-style dropdown which displays a short list of the users who have upvoted/downvoted a particular post
- [x] Scaling additional kudosu based on the number of upvotes awarded (10 = +1 kudosu, 30 = +1 kudosu again, etc). Figuring out the best pattern for this may require some trial and error.

**Comment by nanaya** [comment]
@arflyte will need to design the first one.

There are already additional kudosu on +10 and +15 votes.

**Comment by Loctav** [comment]
So people get 1 kudosu per issue resolved? Or per issue posted? (besides the extra one at +10 and +15)
I would recommend per issue resolved.

**Comment by nanaya** [comment]
I don't think there's any kudosu for resolved at the moment.

**Comment by Ephemeralis** [comment]
This is actually pretty tricky to work out. Ideally, kudosu would only be given for feedback that is *positively* resolved, as in feedback that actually contributes towards the map in some way.

The only way I can think of reconciling this would be to have a mapper/bng/qat side "I applied these changes" box which gave kudosu to the poster, or some other way of verifying that changes were made to that timestamp segment.

**Comment by peppy** [comment]
Closing for now as this is implemented. Balancing will follow after we gauge usage of upvoting.
