### ISSUE TITLE
Feedback tally on difficulty change dropdown in beatmap discussions

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#1266]
![](https://puu.sh/wnrJS/15a9df600d.png)

The above dialog should contain a brief count of pending issues for each applicable difficulty, perhaps no more than a simple number if present.

Will aid with at-a-glance checking of beatmap discussions for existing unresolved feedback for all parties involved in the process.

**Comment by peppy** [comment]
Closing in favour of #1893 which has a good example of it being displayed.
