### ISSUE TITLE
Make a second column for language selection

### ISSUE THREAD

**Issue by leonekmi** [ppy/osu-web#1280]
![Screenshot 1](http://i.imgur.com/VeNAOcK.png)

Too much languages is supported, a second column will be necessary or a modal for language choice.

**Comment by kj415j45** [comment]
nanaya used to edited less to increse its height, but after `ru` added, it short again(

second column may be a good choice...

**Comment by benpigchu** [comment]
【 Make the list scrollable is also an option 】
【 Maybe in the future, the secound column is also not enough 】

**Comment by kj415j45** [comment]
also, you can't select language on mobile phone :(

**Comment by kj415j45** [comment]
this issue may happen again if new language add.

**Comment by MegaApplePi** [comment]
Maybe a button that says `Other...` then display a dialogue to select the other locales that aren't listed?

**Comment by notbakaneko** [comment]
@arflyte ↑

Maybe make the height of the menu dependent on the list being shown?
The main drop down actuallly seems like an odd place to put the language switcher.

**Comment by kj415j45** [comment]
i think `<select/>` can be a good choice

**Comment by leonekmi** [comment]
https://github.com/ppy/osu-web/commit/40916801d98135383145d6caed19e590d099a292 fixes this issue.
![image](https://user-images.githubusercontent.com/20224422/38686467-ab31edac-3e74-11e8-8495-10aa1c0f0dfd.png)
