### ISSUE TITLE
Beatmap tag overflow

### ISSUE THREAD

**Issue by benpigchu** [ppy/osu-web#1297]
https://osu.ppy.sh/beatmapsets/559248

![image](https://user-images.githubusercontent.com/9023067/27991713-08b1a15e-64b2-11e7-81be-8a989f15ae46.png)

oops

**Comment by nanaya** [comment]
I think that's by design (hiding overflown tags).

Not sure if @arflyte has better idea now.

**Comment by Joehuu** [comment]
This has been resolved already.
