### ISSUE TITLE
Get graphing library set-up and working with project

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#13]
We are looking to create graphs like this in the profile section (and other places on the site).

![](http://puu.sh/jUHL5/2ebf8c46ea.png)

As a test of how I want to move forward with development, I'm creating this issue as an open request. Whoever completed it will be rewarded (supporter tag / merchandise / money, not finalised yet but we'll figure it out).

**What needs to be done**:

- Choose a charting library. Last I checked, [Highcharts](http://www.highcharts.com/) was looking pretty good, but feel free to look through others and suggest one. **Let's reach a consensus on this before going any further.**
- Create a sample page with a graph exactly matching the styling in the screenshot above. Initially we will be using these on profile pages.
- Make sure it handles the responsive design correctly.

Your code should make it easy for us to hook up the input data to the graph.

**[Bounty](https://goo.gl/nFdoyI) offered**: 60

**Comment by Protectator** [comment]
I haven't tested Highcharts yet, but I have been using [Flot](http://www.flotcharts.org) a couple of times in some projects. It also works like a charm and is very easy to set up. Not sure if it is better, it's just a suggestion.

[Here](http://www.flotcharts.org/flot/examples/interacting/index.html) is an example of an interactive graph.

**Comment by peppy** [comment]
On first inspection, the general hover/tooltip support feels a bit lousy on that demo. Generally the thing I look for with charting libraries (customising the feel/motion of it would probably be more effort than it's worth, as opposed to choosing a library with a nice feel from the start).

**Comment by Sakisan** [comment]
Chartist may be a good candidate: http://gionkunz.github.io/chartist-js/

**Comment by nanaya** [comment]
hmm that chartist has react integration as well.

**Comment by chudooder** [comment]
[D3](http://d3js.org/) is an option, customizable and very powerful. Might be too much overhead

**Comment by vowywowy** [comment]
100% Google's charting library. You can change pretty much anything and the line charts are pretty much exactly what you are looking for: https://developers.google.com/chart/interactive/docs/gallery/linechart

**Comment by nesk** [comment]
Google Charts' license requires to load the library from Google's CDN, not sure this is what they want since they use Bower.

**Comment by peppy** [comment]
Google charts is definitely not an option (not keen on having stuff loaded from external sources, nor having no control to customise the library is required.

D3 is crazy powerful, but having used it before, the effort required to get it into a usable state is just too much.

I looked at chartist, but it felt a bit barebones. If someone wants to try and make the above-pictured graph using it then I'd be willing to reconsider. Note that the tooltip needs to travel smoothly between hover points (similar to how the performance rank history works on the old profile page).

**Comment by TheHowl** [comment]
What browsers are we supporting?

**Comment by Eclmist** [comment]
Highcharts is perfect for this, some of their examples looks rather close to what we're going for.
Won't take much tweaking to get it to look like the example above

**Comment by peppy** [comment]
No specific restrictions on browser support. Aim for as much support as possible and add more if people complain.

**Comment by chudooder** [comment]
[Here's a D3 demo for the rankings graph.](https://gist.github.com/chudooder/991841e4a1dcd0bc790f)

**Comment by Sakisan** [comment]
It's looking good, chudooder. I've put it online if you don't mind: http://pp.sakisan.be/graph/d3.html

And here's my chartist demo as well. http://pp.sakisan.be/graph/chartist.html

**Comment by abalabahaha** [comment]
[Meh Highcharts example](https://abal.moe/xperimental/highcharts.html)
* today needs tweak on narrow things
* currently hardcoded to show 24 months of data, but can be tweaked to dynamically adjust based on the data provided
* needs more browser testings

**Comment by peppy** [comment]
highcharts definitely feels the closest of the three (also the mouse interaction feels the most solid by... a long shot).

any chance of the getting the gradients correct for the vertical grid lines?

**Comment by avail** [comment]
@Sakisan the hell is going on with chartist? http://a.catgirlsare.sexy/spodfq.webm

**Comment by abalabahaha** [comment]
What does osu-web fall under? Because [Highcharts appears to be free only for non-commercial use](http://shop.highsoft.com/highcharts.html)

**Comment by chudooder** [comment]
@peppy I think the mouse interaction on D3 works the same as in chartist, but I spread out the data points so it feels choppy. Regardless chartist clearly requires much less code so hopefully we can use it

**Comment by Tom94** [comment]
@chudooder D3 is good for it's customizability, though. Currently the issues with your implementation are inconsistent interpolation rates (likely framerate-dependent updates, really should be made independent of frame rate) and the fact, that the marker can get off the graph under some circumstances: http://puu.sh/jX9uO/de81a01d22.png

**Comment by peppy** [comment]
I'm fine with paying for libraries, personally. Getting D3 to behave as well as highcharts feels like a waste of energy to me (especially as we utilise different graph styles going forward).

**Comment by chudooder** [comment]
Hopefully the multiple developers thing in Highchart's licensing policy won't become an issue: "Each person who directly or indirectly creates an application or user interface containing Highcharts is considered a developer." Would this ever become an issue if we decide to go with this library?

**Comment by peppy** [comment]
in a development scenario this project is NFP. the production deployment would require a licence (although you could argue against that, too).

**Comment by nanaya** [comment]
http://forum.highcharts.com/highcharts-usage/web-app-license-t20534/

**Comment by Blaizer** [comment]
The gradients on the grid lines are doable, but would require modifying Highcharts, or whatever you end up using. In the generated SVG, you'd have to change the lines from being <path> to <rect>, and then you can use a stroke gradient on the (0 width) rects.

**Comment by abalabahaha** [comment]
Yeah, I just did gradient grid lines with .5 width rects. Haven't changed the version on my site tho.

**Comment by tewki** [comment]
@abalabahaha you can use their own linearGradient method you know, like http://jsfiddle.net/64o9eufy/

**Comment by Blaizer** [comment]
That's really cool. Turns out Highcharts lets you specify a gradient like that for any color. It's documented here: http://www.highcharts.com/docs/chart-design-and-style/colors

**Comment by tewki** [comment]
Yea it was a pain to find out because it's rather hidden unless you read the whole documents because else you'll have to hook onto the load event and force your gradient into the defs with the svg namespace (That's important for anyone wants to try using only jQuery to make them. because of it being "xml", it won't "parsed" or whatever out a namespace thus won't it won't be rendered, which is a pain to debug).

**Comment by nanaya** [comment]
I think we should at least use same data points when doing comparison. At least the d3 example felt weird because the data jumps around. Using highcharts example: https://e.myconan.net/tmp/d3.html

**Comment by abalabahaha** [comment]
Yeah I realized the version of Highcharts I had on my local dev machine didn't have gradients for some reason...

**Comment by peppy** [comment]
@nanaya I guess we could provide slot table graphing API support if it comes to that, to avoid distributing it with the app.

Actually if it was added as a bower download i'm not sure that would even be considered as bundled anymore.

Either way, D3 feels like shit on iOS (graph flahshes every touch, tweens are basically instant, no drag support as mentioned) so there would need to be further changes before considering it. If we can get it feeling 100% like highcharts then that's another story.

**Comment by abalabahaha** [comment]
[Updated my thing with gradients and dynamic datetime label generation and mostly mobile (narrow screen) support](https://abal.moe/xperimental/highcharts.html)

**Comment by peppy** [comment]
Looking good! Unfortunately, on further investigation it looks like highcharts is definitely not GPL compatibile (http://stackoverflow.com/a/24134439).

Fucking licencing...

**Comment by peppy** [comment]
So to rephrase, the remaining issues with d3 are the tweening between points (see http://puu.sh/jYch3/b101de3e2a.mp4) and mobile support.

**Comment by chudooder** [comment]
I'll look into the mobile stuff later today, but unfortunately I don't have access to an iOS device so if someone could assist me with bugfixing that would be cool. It's pretty difficult to animate the circle perfectly along the line, and the animation actually causes it to feel unresponsive on mobile. One option is to mimic highcharts; instantly move the circle, animate only the tooltip. With enough data points it shoudn't feel too choppy to move the mouse across the graph.

**Comment by peppy** [comment]
You can put chrome into a mobile emulation mode, which should give you basically the same behaviour.

**Comment by peppy** [comment]
Going to close this since we have a working model in the profile performance history graph (pure d3).
