### ISSUE TITLE
Account Settings translation

### ISSUE THREAD

**Issue by sunghwan2789** [ppy/osu-web#1300]
![2017-07-10_191908](https://user-images.githubusercontent.com/4927894/28013657-b9dd63ee-65a4-11e7-8e63-0e397b56e588.png)

Found incorrectly translated string in Email section.
current password should be current email.

**Comment by Nekonyx** [comment]
🤔

![image](https://user-images.githubusercontent.com/16444061/28014051-0aa4e7ec-658d-11e7-857f-61acca670537.png)

**Comment by kj415j45** [comment]
nope, it's current password :(
ref: #1236

**Comment by sunghwan2789** [comment]
Ahh. It looks weired. Closed!
