### ISSUE TITLE
Remove wiki language selection

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#1313]
The displayed wiki language should always match the user's current site locale choice, rather than being selectable on the wiki page itself.

**Comment by nanaya** [comment]
There are currently some wiki pages in languages which we don't have the site translated in though. German, Indonesian, Japanese, and Korean have over 30 wiki pages translated but no site translation.

Also need a better language switcher =D

**Comment by kj415j45** [comment]
close this since wiki locale selector is :boom: ?
