### ISSUE TITLE
Mailto links on the wiki do not function

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#1335]
Attempting to link to a `mailto://` link on the wiki results in a link like the following:

`https://osu.ppy.sh/help/wiki/Help_Center/mailto://support@ppy.sh`

**Comment by nanaya** [comment]
Also the correct syntax of mailto is `mailto:some@address`, no double forward slashes.

**Comment by Ephemeralis** [comment]
Oops. Okay, will fix that on our end.
