### ISSUE TITLE
Group listing page

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#1346]
We need the [group/team listing page](https://osu.ppy.sh/g/7) to be re-implemented. Should likely use the exact same logic as the friend listing, including online/offline display.

**Comment by lunafreya** [comment]
You should have to consider this: #528 is STILL WIP right now. But about the group, are you intending to migrate old osu!web groups into new osu!web teams?

**Comment by nekodex** [comment]
Teams will be a seperate (new) system, this is different.

Also, done.
