### ISSUE TITLE
Name of Peripherals in the top of the profile 

### ISSUE THREAD

**Issue by sirthebk** [ppy/osu-web#136]
Hello, the idea that I come to propose, is to see that model, make and type of peripherals using profile by mousing peripheral certain names.

It is that in the construction of the new design, so avoid down, having to open container box profile, and you save enough to see what kind of hardware you use tap or pointing the user in question.

Well that.

If I do not stay clear, I leave this banal construction of what I propose: 

https://i.ppy.sh/db2b13dfcbbe818d11b8d87bd79d7bf6e40fe68c/687474703a2f2f6b34362e6b6e332e6e65742f352f452f332f352f332f452f4138332e706e67

( I have no idea how to put images directly :( )

The design is just a taste of the concept I want to be implemented, I'm not proposing that design, no design, no study that, but by putting the mouse pointer on the specific text of the peripheral displays the name given by the user , if the latter wants.

**Comment by arflyte** [comment]
![screen](https://cloud.githubusercontent.com/assets/3632750/10504876/5f4ec12c-7341-11e5-995d-c9196296cacf.jpg)

We already have something in mind.

**Comment by peppy** [comment]
Closing this for now. Feature requests aren't necessary. Will try and form this into a bounty if you are actually interested in helping implement it (please reply if this is the case).
