### ISSUE TITLE
Some date and time fields do not use localized format.

### ISSUE THREAD

**Issue by benpigchu** [ppy/osu-web#1365]
Some date and time fields do not use localized format.

For example:

"join_time" field on the user profile page

![image](https://user-images.githubusercontent.com/9023067/28584551-ba0ffc6c-719f-11e7-802e-375a4419761c.png)

The format of time used in this field is hard-coded to "MMMM YYYY", but in Chinese we use "YYYY年 MMMM".

Maybe we nead a new field in the locales files, for Moment.js do not support localized formats that only contain month and year.

More examples are coming.

**Comment by kj415j45** [comment]
Another:
![image](https://user-images.githubusercontent.com/18349191/28671468-65f4a684-730f-11e7-909c-220ba52c162d.png)

**Comment by benpigchu** [comment]
Another:
![image](https://user-images.githubusercontent.com/9023067/28673540-59ae5ff4-7315-11e7-87ec-60b57c5cdaf6.png)

**Comment by kj415j45** [comment]
we need to re-open this issue @benpigchu 

because join time in forum haven't been localized.
