### ISSUE TITLE
Online friends or Friends?

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-web#1366]
![image](https://user-images.githubusercontent.com/18349191/28588370-eff638e8-71ac-11e7-8ea1-90d2eff5865a.png)
the "Online friends" should be "Friends" ?

but, iirc, Online friends display ***online firends count***, not ***friends count*** in the past.

**Comment by peppy** [comment]
just friends is fine

**Comment by nekodex** [comment]
That's a bug, it should be showing online friend count.

**Comment by peppy** [comment]
Didn't see third arrow in your screenshot. Ignore my previous comment.
