### ISSUE TITLE
Notifications in the web

### ISSUE THREAD

**Issue by sirthebk** [ppy/osu-web#137]
there is a way to find you graphically forum responded by notification in your profile. or something, to not have to walk reviewing the forum every so often, it would save time, not.

**Comment by peppy** [comment]
Please don't suggest new features here. We have a lot planned - including notifications - which has not been completed yet, but making issues for each of these doesn't make sense.

**Comment by sirthebk** [comment]
I understand , thank you for taking the time to read the proposed mine ... good luck with the new functions and features.
