### ISSUE TITLE
Going to a build which doesn't exist shouldn't 404

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#1386]
Going to https://osu.ppy.sh/home/changelog?build=20170801dev should just return the user to https://osu.ppy.sh/home/changelog

**Comment by nanaya** [comment]
I'd rather show a link back to index rather than redirecting. I find redirect in this case rather _rude_ because for example I might've mistyped the build number by one character and then I have to retype everything again.

**Comment by peppy** [comment]
I don't think it should ever be typed manually (should be coming from the osu! client). If not, I need a way to get this behaviour because that's what I expect when sending users to the page.

**Comment by nanaya** [comment]
I don't get it, does that mean client sometimes tries to show changelog for nonexistent build?

**Comment by peppy** [comment]
Yep, if a build is a private build (like the example I gave above) I'd still like it to provide a changelog page. For instance, the build in the footer of the options screen will always link to the local version string, but that can possibly not exist server-side for whatever reason.

![osu _2017-08-01_16-59-10](https://user-images.githubusercontent.com/191335/28814993-c2de374c-76da-11e7-9ea2-dcd8962f50a7.png)

**Comment by nanaya** [comment]
Shouldn't it just say no changelog found for specified build instead?

**Comment by peppy** [comment]
Sure, that works too.

**Comment by peppy** [comment]
Has been resolved.
