### ISSUE TITLE
Can't choose post category in "General" modes

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#1391]
Should probably be able to choose Praise/Suggestion/Problem.

**Comment by nanaya** [comment]
As general section doesn't have timeline line, the icon would then be floating.

**Comment by peppy** [comment]
I think displaying the icon is something we can work on, but at very least when posting it should be a selectable option (even if we don't display it anywhere initially)

**Comment by nanaya** [comment]
What about general comment? Not sure if something like impression/review(?) fits in any of current types.

**Comment by peppy** [comment]
yeah, not too sure but I think for the time being we should stick to the three available options and iterate based on feedback

**Comment by nanaya** [comment]
Is it supposed to be resolvable just like in timeline? Also that mean we'll need to display the stats somewhere as well (or just reuse the filter on chart area?).

**Comment by peppy** [comment]
The whole "resolving" thing is another issue altogether! Let's go through this stuff tomorrow and come to a conclusion.

**Comment by nanaya** [comment]
Quite sure the filter buttons position needs some rethinking as well.

**Comment by nanaya** [comment]
Apparently this is done.
