### ISSUE TITLE
Timestamp should appear in anchored header area

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#1394]
There should be a way to navigate through the timeline when scrolled below the top. Also probably a "return to top" button.

**Comment by arflyte** [comment]
![a225a220f2](https://user-images.githubusercontent.com/3632750/40702765-049d69ce-641e-11e8-95cc-4c12ebc279cb.png)

Adapted the new mini navigation bar for the modding page. Timestamp and return-to-top button under the additional action button.

**Comment by TPGPL** [comment]
should unassign
