### ISSUE TITLE
Osu! buying supporter wrong site.

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu-web#1402]
on https://osu.ppy.sh/home the support osu! leads you on https://osu.ppy.sh/home/support. However clicking on "I want you suppport osu!" or the heart on the buttom leads you to the old site. But going through the store and selecting osu! supporter tag leads to the new one

**Comment by peppy** [comment]
This is intentional for now. The new site only supports paypal. Until that is resolved the old checkout page is preferred.
