### ISSUE TITLE
Silenced users should not be able to post/edit user page.

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#142]
Was [reported](https://twitter.com/meeowxi/status/6547603212449873920 that silenced users can still edit user pages.

Old site has this condition on all posting attempts:

![](http://puu.sh/kLUOv/8a8ded34a3.png)

**Comment by nanaya** [comment]
is it basically a silenced user can only view stuff?

**Comment by peppy** [comment]
Yep, they shouldn't be able to post/comment/bitch.

**Comment by nanaya** [comment]
but can they buy stuff

**Comment by peppy** [comment]
yeah
