### ISSUE TITLE
osu!wiki: reference link syntax sometimes doesn't work

### ISSUE THREAD

**Issue by MegaApplePi** [ppy/osu-web#1421]
<https://osu.ppy.sh/wiki/Contests>
![chrome_2017-08-12_11-47-28](https://user-images.githubusercontent.com/14264992/29242580-497dadfa-7f55-11e7-8d23-66900fd033de.png)
The page is parsed correctly in [GitHub](https://github.com/ppy/osu-wiki/blob/master/wiki/Contests/en.md).

**Comment by ColdVolcano** [comment]
Interestingly the Chinese version of the page renders correctly on the web

**Comment by kj415j45** [comment]
it seems that nothing different between en and zh in raw mode :/

**Comment by nanaya** [comment]
the en one has utf8 byte order mark in it confusing the parser.
