### ISSUE TITLE
Can't multi post in mafia subforum

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#1425]
I can't post after myself in the [mafia](https://osu.ppy.sh/community/forums/posts/6190337) subforum. I use new forums to be able to post comments with more than 2 nested quotes, so I can't really use old forums for this. To make sure it's not a cooldown issue, I checked if I can posted in another thread and I could.

**Comment by nanaya** [comment]
There is currently no exception in no multipost rule in (new) forum.
