### ISSUE TITLE
Show search bar even for not logged in users - but redirect to login for them.

### ISSUE THREAD

**Issue by Nicarim** [ppy/osu-web#1459]
Given that unlogged people cannot see the search seems like bad UX for me - If I'm not logged in I can't find a reason for it to be hidden, and I need to ask someone to tell me why is it - it should be obvious why is it hidden, by just show the search but don't actually make it usable for unlogged users.

**Comment by Druwaid** [comment]
The old site does not require the user to be logged in to search for both users and beatmaps. Manually searching for things on the new site is also possible so I don't see why search should only be usable by users who are logged in.

**Comment by nanaya** [comment]
I believe this has been fixed.
