### ISSUE TITLE
Multiplayer match page (mp) : Replace auto-scrolling to the bottom of the page

### ISSUE THREAD

**Issue by SpartanPlume** [ppy/osu-web#1464]
When a new information appear (like when someone enter the room), the page automatically scroll to the bottom.

I was thinking that a functionality like Discord could be better.
Instead of auto-scrolling, a message will be shown that says there is a new information, and when the user clicks on it, the page scrolls to the bottom.

**Comment by peppy** [comment]
Should be a lot better thanks to #2291.
