### ISSUE TITLE
[osu-wiki] no CJK characters in section ids

### ISSUE THREAD

**Issue by MegaApplePi** [ppy/osu-web#1465]
@kj415j45 noticed that if a section heading is in Chinese, any section links using the section heading text won't work as expected.
e.g. <https://osu.ppy.sh/help/wiki/Tournaments/CMT_4K/2017?locale=zh#比赛时间表> or <https://osu.ppy.sh/help/wiki/Tournaments/CMT_4K/2017?locale=zh#%E6%AF%94%E8%B5%9B%E6%97%B6%E9%97%B4%E8%A1%A8>

![image](https://user-images.githubusercontent.com/14264992/29715091-6b5d53ec-896b-11e7-9293-ffedbb39b731.png)

**Comment by notbakaneko** [comment]
HTML5 `id`s are allowed to contain any character except spaces, so maybe we shouldn't run `str_slug` on them? @nanaya 

I'm not sure if there's something else relying on the `id` being slugified, though :trollface:

**Comment by nanaya** [comment]
I don't think so.

**Comment by notbakaneko** [comment]
fixed by #1466
