### ISSUE TITLE
News post's Disqus forums don't update names on changes

### ISSUE THREAD

**Issue by nl-tatatat** [ppy/osu-web#1472]
When using non osu! generated disqus accounts (like accidently because your not signed in on the new site) if you go to change your name in your disqus settings the changes won't be noticeable on the osu! website, but they are noticeable on the disqus site if you view the comment thread through disqus. See
See [this](http://i.imgur.com/cEIcg6T.png) and [this](http://i.imgur.com/xfAsEty.png) . The change has been pushed to disqus servers, but not to the osu! website.

**Comment by peppy** [comment]
I mean, we just embed disqus content at the end of the day with no local modifications. I haven't looked into how disquss handle username changes, but this is likely the result of that.

**Comment by nekodex** [comment]
Disqus caches stuff, so it'll take some time before you see updates. Looks updated now?
![](https://puu.sh/xn5eN/67f1d1c7c3.png)
Closing this issue as it's a disqus-side thing, not osu!-side.
