### ISSUE TITLE
Table of Contents on mobile wiki is missing

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#1482]

**Comment by nanaya** [comment]
Hi @arflyte.

**Comment by peppy** [comment]
this is still a thing @arflyte

**Comment by TPGPL** [comment]
is there any progress on this one?

**Comment by peppy** [comment]
@arflyte

**Comment by arflyte** [comment]
![Content Index](https://user-images.githubusercontent.com/3632750/63491828-29451100-c4f3-11e9-8e0c-169d91380476.png)

Wiki ToC. Part of the new mobile view design. WIP.
