### ISSUE TITLE
User profile shows zero for all stats if no mode is specified

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#1483]
#1476 raised this issue

Example: https://osu.ppy.sh/users/2 vs. https://osu.ppy.sh/users/2/osu
The first link should redirect to their default mode, but instead it shows empty statistics

**Comment by nekodex** [comment]
This isn't a bug, peppy actually has his default mode set to taiko for some reason lol >.>

**Comment by cl8n** [comment]
it shows zeros for any profile, and peppy has stats for taiko

**Comment by nekodex** [comment]
Right, sorry I misunderstood the bug being reported
