### ISSUE TITLE
Icon for deleted replies is redundant and visually cluttering. (also shows as replies)

### ISSUE THREAD

**Issue by aticie** [ppy/osu-web#1489]
The trash bin that shows how many deleted replies are in a thread is almost always either zero or one which most of the time makes it a useless statistic to show. Also when you hover over the trash bin or the reply count, it both show as replies as shown here:

![chrome_2017-09-04_10-03-21](https://user-images.githubusercontent.com/25616662/30015207-667cd1be-9158-11e7-8a88-d5e288c65076.png)

As of 9/4/2017, 08:00 UTC, the following forums have zero deleted replies on all of the posts on the first page:

https://osu.ppy.sh/community/forums/2
https://osu.ppy.sh/community/forums/65
https://osu.ppy.sh/community/forums/87
https://osu.ppy.sh/community/forums/13
https://osu.ppy.sh/community/forums/55
https://osu.ppy.sh/community/forums/61
https://osu.ppy.sh/community/forums/105
https://osu.ppy.sh/community/forums/106
https://osu.ppy.sh/community/forums/107
https://osu.ppy.sh/community/forums/15
https://osu.ppy.sh/community/forums/109
https://osu.ppy.sh/community/forums/4
https://osu.ppy.sh/community/forums/30
https://osu.ppy.sh/community/forums/5
https://osu.ppy.sh/community/forums/29
https://osu.ppy.sh/community/forums/18
https://osu.ppy.sh/community/forums/58
https://osu.ppy.sh/community/forums/35
https://osu.ppy.sh/community/forums/103
https://osu.ppy.sh/community/forums/17
https://osu.ppy.sh/community/forums/75
https://osu.ppy.sh/community/forums/91
https://osu.ppy.sh/community/forums/8
https://osu.ppy.sh/community/forums/114
https://osu.ppy.sh/community/forums/115
https://osu.ppy.sh/community/forums/53
https://osu.ppy.sh/community/forums/19
https://osu.ppy.sh/community/forums/60
https://osu.ppy.sh/community/forums/20
https://osu.ppy.sh/community/forums/56
https://osu.ppy.sh/community/forums/10
https://osu.ppy.sh/community/forums/14
https://osu.ppy.sh/community/forums/6

Forums which have 1 deleted reply on the first page:

https://osu.ppy.sh/community/forums/116
https://osu.ppy.sh/community/forums/25
https://osu.ppy.sh/community/forums/52

Forums with more than 1 deleted replies:

https://osu.ppy.sh/community/forums/7  -  2 deleted
https://osu.ppy.sh/community/forums/68  -  7 deleted

Also, when the topic seen and replied numbers are 4 digit or bigger, the trash bin drops down 1 more line and whole thing becomes 3 lines instead of 2 and makes the size of the topic larger than others.
![chrome_2017-09-04_10-21-08](https://user-images.githubusercontent.com/25616662/30015751-d09dc894-915a-11e7-9a4d-8008e67427f2.png) compared to this ![chrome_2017-09-04_10-03-21](https://user-images.githubusercontent.com/25616662/30015207-667cd1be-9158-11e7-8a88-d5e288c65076.png)

**Comment by peppy** [comment]
Can probably jsut be removed

**Comment by nekodex** [comment]
Pretty sure this is only visible to admins/moderators fwiw

**Comment by aticie** [comment]
Issue can be closed if it shows for admins/moderators only.

**Comment by peppy** [comment]
I still think it doesn't need to display for moderators. It likely adds no value apart from visual clutter.

**Comment by nanaya** [comment]
Or just show for threads with deleted posts?

**Comment by peppy** [comment]
if we must show it at all, sure

**Comment by aticie** [comment]
I agree with peppy here, I don't think it's a necessary statistic to show even for moderators.

**Comment by nanaya** [comment]
how about the one in topic header?

![](https://s.myconan.net/2017-09/chrome_2017-09-04_17-02-18.png)

**Comment by peppy** [comment]
Header is fine, although it should probably have a gray accent, not pink.

And maybe only visible when above zero?
