### ISSUE TITLE
QAT are unable to access Management forums on new website

### ISSUE THREAD

**Issue by JBHyperion** [ppy/osu-web#1494]
Since all moderators are now required to use the new site for browsing the forum, the Management subforums have become inaccessible for QAT members.

Following a link from the old site gives a "You're not supposed to be here" message, whilst the subforum doesn't appear at all for us when attempting to access directly from the new site.

Assuming this is a missing permission, since I have replicated the issue with other QAT members, but IamKwan (who is also GMT) could access the subforum without issue.

**Comment by peppy** [comment]
Closed by https://github.com/ppy/osu-web/pull/1498
