### ISSUE TITLE
Mismatch of Color and User Title

### ISSUE THREAD

**Issue by KwaN-osu** [ppy/osu-web#1495]
User title on my profile page is Global Moderator but color of my username is red instead of green.

https://osu.ppy.sh/users/1856463
![image](https://user-images.githubusercontent.com/31646916/30050230-3d1c3e24-9250-11e7-8c50-042371ab1124.png)

**Comment by nanaya** [comment]
Looks like someone set your user color to that.

**Comment by KwaN-osu** [comment]
i asked eph and he said no idea, who am i supposed to ask?

**Comment by peppy** [comment]
Should be resolved.

**Comment by KwaN-osu** [comment]
https://osu.ppy.sh/users/1856463
it goes back lol

**Comment by kj415j45** [comment]
@KwaN-osu you can use reopen

重新打开就好了嘛。

**Comment by peppy** [comment]
except it is not related to osu-web; discussion will continue on discord
