### ISSUE TITLE
Forums: Middle clicking edit links opens a broken form

### ISSUE THREAD

**Issue by Repflez** [ppy/osu-web#1496]
Middle clicking an edit link shouldn't open a broken form:

![image](https://user-images.githubusercontent.com/659133/30050301-3a52a040-91db-11e7-8d9d-66b78417fd2f.png)

### Reproduction steps
1. Open a thread (any thread works)
2. Hover a post to show their links on the right side
3. Middle click the edit link
4. Image at top happens on the new tab

Middle clicking the delete link just links back to the post in the thread, while the quote link has the post wrapped in `[quote]` BBCode for the new post form.

**Comment by nanaya** [comment]
yeah, those buttons aren't supposed to be middle-clicked.

**Comment by peppy** [comment]
If we're not going to support middle click then at very least we should be redirecting it to open in the current tab (support would still be preferred).

**Comment by nanaya** [comment]
Are buttons now and can't be middle-clicked 💃
