### ISSUE TITLE
QAT are unable to give kudosu in the new forums

### ISSUE THREAD

**Issue by OnosakiHito** [ppy/osu-web#1497]
As of today the QAT is forced to the new forums when entering a beatmap thread. Giving / denying kudos is henceforth not possible anymore and due to that a problem for managing threads in this form.

The new forum will have another form of kudos-system as known, but till the system kicks in, QAT should be able to browse in the old forums to be able to work with the old system.

**Comment by Nicarim** [comment]
https://osu.ppy.sh/forum/6 You can?

**Comment by OnosakiHito** [comment]
Not when you get directly linked to a beatmap. (https://osu.ppy.sh/s/500602)
Neither by trying to use the search function and enter the thread this way. (http://puu.sh/xrZwb/b34dc8aafd.png)

Searching a beatmap in the Pending Beatmaps subforum is more than just an hassle.

**Comment by Nicarim** [comment]
oh yeah, it forces all topics.

**Comment by peppy** [comment]
This should be resolved (isn't an osu-web issue but an osu-web-10 issue, as it turns out).
