### ISSUE TITLE
Hovering Over 8 Covers Preview Feature

### ISSUE THREAD

**Issue by MasterBugPatch** [ppy/osu-web#15]
Hey, I really think this would be a great feature. By hovering over an image it just shows your cover as that image for a preview. I really wouldn't mind making a pull request for this as I can do it.

**Comment by arflyte** [comment]
We already had this in mind. Go ahead and give it a try.

**Comment by MasterBugPatch** [comment]
Sweet Gracias, love your work BTW. Always been keeping an eye on next.ppy.sh

**Comment by arflyte** [comment]
Haha thanks.

**Comment by MasterBugPatch** [comment]
Hmm, just finished programming it up, and I also tested it by compiling it to build. Though I can't push it, and my pull request in client isn't working.

**Comment by peppy** [comment]
you'll probably have to fork the repository first

**Comment by MasterBugPatch** [comment]
Yeah, I believe I did. I cloned it, installed Vagrant, set everything up, experimented back and forth with my localhost and editing files, saved everything, and now trying to push/pull it here.

**Comment by MasterBugPatch** [comment]
Alright, I think I did it ^.^

**Comment by nanaya** [comment]
Added in #70.
