### ISSUE TITLE
Scrolling a page when a pop-up (usercard) is open works with keyboard but not with scroll wheel (mouse)

### ISSUE THREAD

**Issue by VeilStar** [ppy/osu-web#150]
Short video of the issue: https://www.youtube.com/watch?v=mG3TGplktHE

When a pop-up such as the usercard is open the scroll bar dissapears and you're unable to scroll using the mouse scroll wheel, but you're still able to scroll the page using your keyboard, such as with the arrow keys, page up, page down, and the spacebar.

Also, if you scroll down and then close the pop-up/usercard by clicking outside of it, the page jumps back up to (almost) the position it was at before you scrolled.

And the usercard gets positioned at the center of the X axis and at the top of the page if you scroll far enough for your avatar to no longer be visible.

With that said, I guess the intention is to be unable to scroll when a pop-up like this one is open.
I'm not sure if it's possible to keep the user from scrolling the page through keyboard keys, but this is inconsistent behaviour and should be fixed I guess.

**Comment by TheHowl** [comment]
this happens only on firefox. So probably there's already a function that prevents this on webkit browsers, but that isn't yet supported on gecko browsers.

**Comment by VeilStar** [comment]
I should have checked that, but it seems you're right.
(I'm starting to have many reasons to switch my primary browser lately...)

**Comment by nanaya** [comment]
for what it's worth, you can middle-click the window to enter free scroll mode and scroll the page even in chrome.

**Comment by nanaya** [comment]
"middle click" is done using mouse's third button, usually doubles as wheel scroll. ~~If you don't have one, well, sucks to be you =]~~

**Comment by TheHowl** [comment]
Can't replicate on latest chrome canary using middle click (http://y.zxq.co/yjyxud.webm).

**Comment by nanaya** [comment]
wow, it's fixed indeed. That was unexpected.

**Comment by peppy** [comment]
Going to close this as a browser-specific quirk which doesn't necessarily need to be fixed.
