### ISSUE TITLE
Forum: Function to edit topic titles is missing

### ISSUE THREAD

**Issue by Nath789** [ppy/osu-web#1501]
*As the title says, there is no way to edit them right now.*

**Comment by peppy** [comment]
Pretty sure you just edit the first post?

**Comment by Veus** [comment]
The only option we have is to 'add' or 'delete' a cover page, if we edit the first post

**Comment by Nath789** [comment]
Nothing.
![preview](https://user-images.githubusercontent.com/5668486/30084152-cd299e12-92c3-11e7-82db-7e7c8efc6272.png)
