### ISSUE TITLE
QAT missing post/thread management options on new site

### ISSUE THREAD

**Issue by JBHyperion** [ppy/osu-web#1502]
Further to Issue #1494, QAT can now access moderator subforums (thanks for this)! 

Unfortunately we're still unable to manage posts and threads (move/delete/split/etc.), meaning we can't moderate beatmap threads, move inappropriate submissions to wasteland or (potentially, untested) bring disqualified maps back into Help/WIP from the Graveyard.

With the planned move to Moddingv2, moderating beatmap threads may no longer be necessary, but for the other aspects, post/thread management options would be extremely useful to have so we aren't constantly bothering the GMT on trivial cleanup work.

**Comment by Ephemeralis** [comment]
@nanaya this is pretty crippling for the QAT now that the new forum is forced in most circumstaces, could a fix get fast-tracked somehow?
