### ISSUE TITLE
Expensive query due to `ORDER BY`

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#1506]
```select * from `phpbb_posts` where `phpbb_posts`.`topic_id` in (85044) and `phpbb_posts`.`deleted_at` is null order by `post_id` asc limit 1```

In the old system, we use `ORDER BY post_time`, which is indexed. We should probably be using this here, or if we decide that `post_id` is preferred then we need to update the index accordingly.

**Comment by notbakaneko** [comment]
doesn't seem to be an issue anymore
