### ISSUE TITLE
news listing isn't sorted by posted timestamps

### ISSUE THREAD

**Issue by MegaApplePi** [ppy/osu-web#1523]
They appear to be listed via filenames descending.
![image](https://user-images.githubusercontent.com/14264992/30193460-d0fea320-9412-11e7-9665-affd4104a976.png)
(red = current listing; blue = the order they should actually be in)

**Comment by nanaya** [comment]
yeah it's unfortunate but there's no feasible way to fix it at the moment.

**Comment by nanaya** [comment]
Now can be done by adding `date` attribute to the metadata header.
