### ISSUE TITLE
Slow query on user search lookup

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#1536]
```select count(*) as aggregate from `phpbb_users` where `username` LIKE 'The%' and `username` NOT LIKE '%\\_old' and (`user_warnings` = 0 and `user
_type` = 0)```

```
# Attribute    pct   total     min     max     avg     95%  stddev  median
# ============ === ======= ======= ======= ======= ======= ======= =======
# Count          0     468
# Exec time      1   2167s      1s     59s      5s     11s      6s      3s
# Lock time      0   523ms    36us   401ms     1ms   176us    18ms    60us
# Rows sent      0     468       1       1       1       1       0       1
# Rows examine   0   6.04M     782  95.98k  13.21k  51.46k  19.66k   6.96k
# Rows affecte   0       0       0       0       0       0       0       0
# Bytes sent     0  32.91k      72      72      72      72       0      72
# Query size     0  71.51k     156     160  156.46  151.03    1.37  151.03
```

If possible we should stop doing a `count(*)` query and just fetch up-to-x results.

**Comment by nanaya** [comment]
Apparently adding index on `phpbb_users(username, user_warnings, user_type)` speeds things up to sub-second (`0.0X`).

Making a copy of the table with just id, name, and warnings column helped speed things up but still slower than using index (`0.XX`).

**Comment by peppy** [comment]
Did we decide it wasn't possible to remove the `count(*)` query in the end?

**Comment by Hwigaro** [comment]
if you use the laravel pagination you would limit the amount of data sent to the view, and you can use the '$paginator->total()' instead of 'count(*)'

**Comment by nanaya** [comment]
Should be fine now by limiting to first 100.
