### ISSUE TITLE
Moddingv2 nomination history is invisible to public

### ISSUE THREAD

**Issue by Okorin** [ppy/osu-web#1537]
Frankly doesn't make much sense to hide the one responsible for a map being in qualified - especially since they're not hidden right now and are posted publicly so that the activity of each member is tracable for everyone on the platform.

Not seeing the point in making that sort of thing something hidden as it even provides information for Nominators to go off of when attempting to work together - getting asked who nominated what so that they can ask that person a question about the map and why they nominated it / discuss issues that they have with the nominator should be a thing that is easily accessible.

On the chance that this is intended behaviour please consider the above points on that topic.

**Comment by nanaya** [comment]
I think qat is currently able to view the nominators.

**Comment by Raidencio** [comment]
but isn't the purpose to be visible to public for discussion? lol not only the qat

**Comment by Okorin** [comment]
Yeah, the issue isn't that I don't see this, but that not knowing who nominated their map can even confuse the mapper if the nominator in question didn't talk to them and suddenly their map is qualified.

In such cases the QAT or above would always be poked to tell them who even did that so I think this information should be publicly accessible - I mean it has been for about most of osu!'s history of being around so hiding it seems more like an inconvenience for everyone involved.
