### ISSUE TITLE
ERROR : default: Warning: Connection timeout. Retrying...

### ISSUE THREAD

**Issue by codevirtuel** [ppy/osu-web#154]
Hey !

I got this error (default: Warning: Connection timeout. Retrying...) also this message :

Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

**Comment by TheHowl** [comment]
If you go to the virtualbox GUI while doing `vagrant up`, do you see the osu-web machine as booting?

**Comment by codevirtuel** [comment]
It seems to not booting :|
![mdrdld](https://cloud.githubusercontent.com/assets/12038808/10616659/7f731074-7766-11e5-96ad-62c75e7db57e.PNG)

**Comment by IrateGod** [comment]
Although a little late, I would like to tag onto this issue.

While under Windows 8.1, I am unable to connect to the machine. Prior to adding `git.exe` to my Path due to its integrated ssh client, I would be able to run `vagrant up` but would fail on `vagrant ssh`.

Has this issue ever occurred to you during setup? I would try adjusting my configs but I don't think it's an issue with that.

**Comment by IrateGod** [comment]
Piggybacking this issue again - it's been resolved by using Putty. If no one else responds I think this can be closed.

**Comment by nanaya** [comment]
Shall assume this has been fixed or not relevant anymore.
