### ISSUE TITLE
Userpage doesn't update after removing mutual friends

### ISSUE THREAD

**Issue by Cerebi** [ppy/osu-web#1549]
It looks like removing someone who was a mutual from the friend list doesn't make the little "mutual" tag after the number of followers disappear/refresh right away.

A page refresh fixes this, but I don't think it's supposed to be doing this.

Reference: https://cdn.discordapp.com/attachments/205772326678167552/357531096583372800/unknown.png

**Comment by nanaya** [comment]
Apparently mutual text itself has been removed so it's not relevant anymore.
