### ISSUE TITLE
Impossible to reply due to scaling on low resolution mobile devices

### ISSUE THREAD

**Issue by aticie** [ppy/osu-web#1561]
On older phones like iPhone 4s, it is impossible to reply to a thread because the bottom banner overlaps with reply box and makes it unclickable. iPhone 4s resolution is 640x960 btw

Also half of the buttons on the bottom are not clickable or not even shown because that many buttons don't fit. This also applies to some higher res phones too. 

![image](https://user-images.githubusercontent.com/25616662/30682789-8ef71a24-9eb3-11e7-9d4c-a51a8977a7b2.png)

**Comment by peppy** [comment]
I believe this has mostly been fixed (tested with a 640 width device).
