### ISSUE TITLE
Achievement medal 'quest_instructions' are not used

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#1563]
`quest_instructions` in the achievements table currently contain "long hints" for each medal which further clarify how to achieve it. As far as I know, they're not utilized anywhere currently.

An easy way to achieve this would be to have the quest instruction text replace the medal mouseover text (which currently displays the flair) if the medal information dialog is left open for longer than 5-10 seconds. Just a suggestion, dunno if there's anything drafted.

Example:

Current mouseover:

![](https://puu.sh/xFdMB/35e43d0abd.png)

Proposed mouseover (fades in after 5 seconds of the dialog being open) (uses `quest_instructions` text):

![](https://puu.sh/xFdRr/a22a874315.png)

**Comment by arflyte** [comment]
Currently, show the description on hover after 2 seconds. Reworking on the medal popup, still work in progress.
![ff7a3f3757](https://user-images.githubusercontent.com/3632750/40702709-ce6f5d80-641d-11e8-8e98-0fb0526f12eb.png)

**Comment by nanaya** [comment]
Has been added.
