### ISSUE TITLE
Multiplayer match page displays wrong accuracy and score in some cases

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#1565]
This happened to most scores recorded, not all.

For every mismatched accuracy displayed on the match page, the accuracy is lower than in-game recorded accuracy by some arbitrary amount. Some scores are also by 1 or 2 points less than in-game. I have not seen mismatched combos yet.

Here is the link to the match page: https://osu.ppy.sh/community/matches/36281218

All accuracy and scores starting from and following 10K2S Collection 2 [Gojou Kai & Nakamura Meiko - fragment of tears EZ Lv.3] are correct.

## **Example of mismatch (acc and score):**

![](https://i.imgur.com/twDAKx9.png)
![](https://i.imgur.com/1YpNu2e.jpg)

## **Example of mismatch (acc only):**

![](https://i.imgur.com/7yG0W31.png)
![](https://i.imgur.com/8uqW926.jpg)

## **Example of correct match (acc and score):**

![](https://i.imgur.com/aLTzit5.png)
![](https://i.imgur.com/UTFjs6J.jpg)

**Comment by MillhioreF** [comment]
The accuracy being wrong seems to be due to playing a mania-specific map while having osu! standard selected as a mode, which causes the match page to display the score as if it was set in standard (ignoring 300g and 200)
