### ISSUE TITLE
Pippi's legs bleed through the online users graph in the home page.

### ISSUE THREAD

**Issue by Nochys** [ppy/osu-web#1593]
![this is very distracting](https://puu.sh/xUDvl.jpg)
![this is very very distracting](https://puu.sh/xUDFK.jpg)

**Comment by CrazyHatish** [comment]
I works fine on Chrome, but has this problem on Firefox. Both Pippi and the graph seem to be properly positioned in the div with `bottom: 0`. Only solution I found was to change Pippi's position to `bottom: 1px`.

**Comment by CrazyHatish** [comment]
Setting `.landing-hero__pippi { line-height: 1; }` seems to work
