### ISSUE TITLE
Mv2: Decrease how much screen darkens when clicking icons

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#1597]
https://puu.sh/xViEl/18ef6f21de.png
When you click on the diff icons tab in Mv2, the screen gets too dark. Hurts eyes a bit due to how quickly it becomes bright/dark and near impossible to read other information. Would be better if the fade was a little more transparent

**Comment by arflyte** [comment]
Requires a lot of testing. For now, let's set it to 50% and revisit it again after a week.
