### ISSUE TITLE
Issue tracking icon placement in mobile view

### ISSUE THREAD

**Issue by VeilStar** [ppy/osu-web#160]
These issue tracking icons (confirmed | assigned | resolved | added | invalid | duplicate) would probably be better off sitting elsewhere, such as on the same line as the thread title. I don't exactly have an ideal solution for this, but right now it just looks out of place.

![ss 2015-10-25 at 05 05 09](https://cloud.githubusercontent.com/assets/14024130/10714006/12fbe81c-7ad6-11e5-9650-921bcf6e8993.png)

**Comment by peppy** [comment]
Feels like it should be right aligned instead, if anything. @arflyte ?

**Comment by peppy** [comment]
@arflyte poke poke poke

**Comment by arflyte** [comment]
Let's do it this way. Left align it and increase the height of the box.

![screen-shot-2016-02-18-at-7 04 06-pm](https://cloud.githubusercontent.com/assets/3632750/13139994/db96da82-d672-11e5-8928-bb7a1ed99b1a.jpg)

**Comment by peppy** [comment]
**[Bounty](https://goo.gl/nFdoyI) offered**: 20.

As always, ask if you have any questions, and feel free to jump on the [osu!dev slack](http://osu.ppy.sh/p/slack) for more real-time discussion.
