### ISSUE TITLE
The /users/ route behave differently from the /u/ route

### ISSUE THREAD

**Issue by benpigchu** [ppy/osu-web#1605]
Found by @lslqtz 
https://osu.ppy.sh/u/2420195176 returns the profile of user whose username is 2420195176 .
https://osu.ppy.sh/users/2420195176 returns 404 .
Is this expected behavior? Or is this a bug?

**Comment by kj415j45** [comment]
duplicate example: 
https://osu.ppy.sh/users/479391372
https://osu.ppy.sh/u/479391372

https://osu.ppy.sh/users/1822538813
https://osu.ppy.sh/u/1822538813

**Comment by Lyawi** [comment]
I wonder if the person can open their profile via the button?

![chrome_2017-10-17_17-38-14](https://user-images.githubusercontent.com/32525896/31674386-fc80edfa-b361-11e7-9fb4-0f7b946d2e0e.png)

**Comment by kj415j45** [comment]
i disagree.

btw, you should use another issue to report your idea. @Lyawi

**Comment by Arocide** [comment]
It would be intended behaviour because the new website uses userIDs in the route and not usernames.
