### ISSUE TITLE
News article view still doesn't use header banner assets

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#1606]
Example:

https://osu.ppy.sh/home/news/2017-10-13-osu-world-cup-2017-registrations-now-open

Current behaviour (no display, gradient image filler):
![](https://puu.sh/xZgCL/7747e6652b.png)

Expected behaviour (mockup):
![](https://puu.sh/xZgFs/23da10684a.png)

Expected behaviour uses the first major image present in the article, the same way that ``/home/news`` views use the same image to create the frontpage previews.

**Comment by peppy** [comment]
Closing in favour of #1696.
