### ISSUE TITLE
[/list][list] BBCode showing odd behaviour

### ISSUE THREAD

**Issue by Endaris** [ppy/osu-web#1607]
1. Using multiple `[list][*]something[/list]` in succession in the _new_ forum leads to malformatted HTML in the _old_ forum.
For reference compare https://osu.ppy.sh/forum/p/6304529 in old and new forum.
This is not too problematic on its own because the old forum is eventually going down but after testing the waters a bit trying to make a BBCode that properly displays in both forums I figured that there is something more behind this. And it surely is odd that BBCodes with tags in perfect order breaks when there isn't even something wrong with it.

2. `[list]
[*] apple
[/list]
[/list]
[list]
[*] banana
[/list]
[/list]`

This results in 2 proper list elements followed by two closing `[/list]` tags (new forum). Gives the impression that [/list][list] is actually a valid way of putting BBCode. This happens only to `[/list]` tags from what I have seen, other additionalxtra tags like `[/b]` inbetween of others are displayed as plain text in the same constellation.

3. `[/list][*][list]`
Looks like a nice meme on the new forum. On the old forum it _works_ even though the tags are flipped. Pretty much confirms that the matching of the opening and closing tags is broken for the old forum.

4. `[/list][list][*]`
_Works_ in the new and old forum.

Conclusion:
Not entirely sure what has to be fixed here and how (and even if) but this thing behaves a bit odd, even on the new website so I thought I'd open an issue with my findings.

**Comment by Lyawi** [comment]
![new](https://user-images.githubusercontent.com/32525896/31636160-ab62c454-b2c9-11e7-81ef-9618372bcb9a.png)
![old](https://user-images.githubusercontent.com/32525896/31636162-ab84b0b4-b2c9-11e7-8f3e-b5f7637a6d2b.png)

**Comment by nanaya** [comment]
The behaviour should be the same now.
