### ISSUE TITLE
moddingv2 lacks subscription/notification feature

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#1608]
Currently, no obvious means exists to allow users to 'subscribe' to a beatmapset discussion, where they receive regular updates as to the activity of the discussion on a given set.

This is a major problem for those who actively maintain several concurrent sets, as the phpbb forum post subscription option is used as a way to track activity on those sets in real time.

An analogous feature needs to be implemented to achieve the same end. This is fairly important and should be considered as a major point before the service enters live use.

However, moddingv2's granular discussion format may prove prohibitively expensive from an email standpoint for both our service and the end user if a notification is sent for every discussion point, resolution and response.

I would suggest some sort of aggregate 'activity view' sent in 30 minute intervals which briefly outlines the activity happening on ALL of a person's applicable sets, including those they have subscribed to.

**Comment by dorothy3242** [comment]
There should also be a feature analogous to the current forum's bookmarking capability, which allows users to keep up with multiple threads in one place on the website without getting email notifications.

**Comment by peppy** [comment]
We now have basic email notifications / watch list support thanks to https://github.com/ppy/osu-web/pull/1664
