### ISSUE TITLE
moddingv2 outside opinion topic unresolving

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#1609]
Currently, once a discussion point is marked as "resolved" either by a moderator or the map owner, the point cannot be re-raised for discussion by any means outside of posting a duplicate issue.

While the onus on issue resolution resides with the mapper, providing them with the explicit impetus to unilaterally declare what is and is not an issue does not exactly fit the spirit of modding, especially if moddingv2 is to become the primary platform for the discussion of such issues.

Allowing upvoted comments within a resolved thread to automatically unresolve the issue would be the most intuitive approach to solving this problem. Allowing beatmap nominators to unresolve issues a la the QAT would also work here to some degree.

**Comment by nanaya** [comment]
The thread starter can already reopen it. Nominator can be added so they can unresolve issue if needed.

Not sure what you mean with "upvoted comment within a resolved thread" because there's no comment voting?

**Comment by Ephemeralis** [comment]
Allowing BNG to resolve/unresolve seems an elegant enough solution here.
