### ISSUE TITLE
Internet Pack Vol 2 achievement image is incorrect

### ISSUE THREAD

**Issue by VeilStar** [ppy/osu-web#161]
https://osu.ppy.sh/forum/t/379219
Internet! Pack Vol 2. achievement image isn't correct on the profile achievement list.
The Internet! Pack Vol. 2 shows it as Vol. 1
![01](https://cloud.githubusercontent.com/assets/14024130/10717158/cd90d286-7b4f-11e5-8a59-425298e53598.jpg)
And the other one is the actual Vol. 1
![02](https://cloud.githubusercontent.com/assets/14024130/10717159/d103a60a-7b4f-11e5-9d8f-6219a701d5f2.jpg)

Similar to https://github.com/ppy/osu-web/issues/101

**Comment by peppy** [comment]
This should now be resolved.
