### ISSUE TITLE
moddingv2 requalification

### ISSUE THREAD

**Issue by pishifat** [ppy/osu-web#1618]
currently it's common practice for QAT members to directly requalify maps that were disqualified for metadata changes. because the map is unchanged, asking two BNs to recheck is seen as a waste of resources. example: https://osu.ppy.sh/forum/p/6267481 first 5 posts here. 

it would be useful for the QAT to have an option of requalifying a map without going through the normal two nominations

**Comment by peppy** [comment]
No longer temporally valid.
