### ISSUE TITLE
Contest page navigation skips/duplicates entries

### ISSUE THREAD

**Issue by Endaris** [ppy/osu-web#1621]
Taking the current contest:
https://osu.ppy.sh/community/contests/56

Click on Serene Gorilla.
Then proceed to click the right arrow.
First thing you will notice is that Anxious Thrush will be shown a second time after Focused Tortoise.
Second thing you will notice is that after this first duplication, Magnificent Robin, Reasonable Harrier and Supportive Swift are all getting skipped as it goes right to Earnest Beaver after that.
Right after Earnest Beaver, Zealous Whale is getting skipped, etc etc.

Vice versa using mouse clicks on the left arrow button:
Starting at Debilitated Snipe, we got Zealous Whale, Earnest Beaver, Zealous Whale again and then straight to Focused Tortoise.

Effectively, when using mouse clicks to click the arrows the entire navigation turns into a mess and some of the entries will never show up which may potentially skew voting results as some entries got less exposure.

The same thing occurs when navigating with arrow keys on your keyboard, although to a lesser extent.
When starting with Serene Gorilla again, using the right arrow key will work as intended until Magnificent Robin after which Anxious Thrush comes up for the second time again, causing Reasonable Harrier to get skipped completely.

I can consistently replicate this with Firefox 56.0.1 (64bit).

**Comment by peppy** [comment]
This was due to a failure when retrieving and caching image dimensions. We've fixed it for this contest. Thanks for pointing out the issue!
