### ISSUE TITLE
It's not possible to browse pending/graveyard beatmaps by last update

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#1632]
https://osu.ppy.sh/beatmapsets?s=4
It only sorts by when a set was ranked, which only shows beatmaps that were disqualified from the ranked section. It should be changed to when it was last updated.

**Comment by shortthu** [comment]
This have been fixed I guess? I think we can close this.

**Comment by peppy** [comment]
This has indeed been fixed!
