### ISSUE TITLE
Deleting a post from the new site still exists on post history (old site)

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#1650]
Pretty much what's written in the title. Make a comment somewhere, delete it via the new site and look at your posts on the old one. In my case it's https://osu.ppy.sh/forum/search.php?author_id=5851253&sr=posts

Not sure if it gets counted. And if this is even a thing for this category here since posts are no longer a thing and we move to the new site someday anyway? Sorry if I'm wrong here.

**Comment by LiquidPL** [comment]
That's because the old website is not aware of the soft delete flag used by the new website. While not exactly a new website bug, this still should be fixed (at least until the old forums are nuked).

**Comment by peppy** [comment]
This should be resolved now; thanks for pointing it out!
