### ISSUE TITLE
Portions of the changelog chart are black if there is too many builds in the dataset

### ISSUE THREAD

**Issue by LiquidPL** [ppy/osu-web#1662]
![](https://user-images.githubusercontent.com/991831/32240612-05b74c4a-be6e-11e7-86c7-0e6f87185662.png)

This is because there is not enough colors declared in the chart styles, causing the rest of them taking a default of black. Right now, it seems like 29 builds are displayed in the cuttingedge section, so i think somewhere around 35 should be a sane number.

I'll leave this here, as I'm not sure if this should go through design first, or is it fine to just pick random colors or something.

**Comment by peppy** [comment]
We should just cycle through the available colours wen we run out.
