### ISSUE TITLE
Add visibility to modding system via beatmap listing

### ISSUE THREAD

**Issue by Naxesss** [ppy/osu-web#1667]
At the moment there is no way to browse available discussions, which in turn makes it difficult to see recent activity, most hyped beatmap, recent nominations, etc. In order to find discussions as it stands, a user needs to either look through each beatmap and go into the discussion (assuming this doesn't link to the BSS thread) until they find what they're looking for, or find the discussion through word of mouth. Unlike the old forum, where both a listing and post history exists, the new modding platform makes any kind of viewing and browsing of discussions impractical, not only for all discussions in general, but also discussion posts made by certain users.

Essentially what is missing is the ability to:
- browse available discussions
- sort and filter said discussions after recent post activity, hype, nominations, etc.
- browse discussion posts by certain users

The same kind of layout could be used for subscribed discussions, meaning users and mappers would be able to see updates on discussions without having to receive emails or the discussions otherwise bloating their personal notifications (should this feature be separate). Furthermore, seeing something similar to the search functionality of the old forums be applied for discussions, could make looking for discussions posted in by certain users or created by certain mappers much more accessible. Personally I always check threads I've posted in for modding/nominating with https://osu.ppy.sh/forum/search.php?keywords=&terms=all&author=naxess&sc=1&sd=d&sr=topics&ch=300&t=0&submit=Search

The closest to this would be [ephemeral's issue regarding a notification/subscription system](https://github.com/ppy/osu-web/issues/1608), which a listing like this could assist in addressing.

**Comment by peppy** [comment]
We're aware of this.

For now you CAN use the old forum (modv2 beatmaps still general stub posts which can still be starred etc.), as well as [see your subscribed maps here](https://osu.ppy.sh/beatmapsets/watches).

**Comment by peppy** [comment]
This needs to be done ASAP

**Comment by dorothy3242** [comment]
I think this was resolved through https://github.com/ppy/osu-web/issues/1950 ?

**Comment by peppy** [comment]
Yeah, this has mostly been resolved.
