### ISSUE TITLE
New site does not allow beatmap description editing w/o resubmission

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#1672]
Currently. beatmapset descriptions cannot be edited via moddingv2 at all. One must use the BSS to make amendments to a description, meaning that additions post-qualification or any other changes must be done via other means or old forum access gunkery.

This should probably be changed to allow editing at pending/qualified state for the creator, and all states for privileged users (QAT, BN, etc).

**Comment by peppy** [comment]
Changes shouldn’t be allowed in said states. Description is a field like all other fields from here on out (as it siiild have always been).

**Comment by Ephemeralis** [comment]
At the very least, some sort of privileged override will undoubtedly be needed. Mappers have sometimes added flair or attribution later on in the map's lifespan. A privileged override will also likely be needed for fringe cases.

**Comment by peppy** [comment]
Maybe, but mapper edits are to be made in WIP state

**Comment by Okorin** [comment]
why is wip state even needed, at best it confuses people about where to put what and when or why - moving stuff from pending to wip as a mapper to edit the description while metadata changes of the map accept submitting to pending isn't really straightforward

**Comment by peppy** [comment]
oh pending will work too. it acts just like any other field.

**Comment by Okorin** [comment]
so to fix a typo or whatever within the mapdescription past qualified the user will have to contact someone that can fuck around with the forum post by accessing them as forum posts in some way?

or are we just going to tell them "well sucks to be you ask for a dq if you really want this fixed" - seems like a huge timewaster for everyone involved

**Comment by Xinnoh** [comment]
People that do
<-(link to 4) Ranked map no. 5  ->(link to 6)
will be unable to do this, as they can't predict the future. Being unable to edit is just an extra hassle that makes life harder.

**Comment by dorothy3242** [comment]
It makes it more difficult to edit map descriptions in general. I often edit it on the forum as it is faster to format and check if the formatting displays how it was intended. Having to submit every time to make changes is silly, in addition to the problems of making post-qualification edits impossible for regular users. 
Mappers may want to do so to add information on when it was qualified, other future maps, linking to related maps they mapped later on (such as multiple songs in a series). Forcibly removing this functionality doesn't seem like a wise choice.

**Comment by peppy** [comment]
Post-qualification edits were previously used in an abusive way. Will have a think about this but this was actually a conscious decision by me here.

**Comment by peppy** [comment]
This should be implemented on the beatmap info page in a similar way to how user page editing is possible. It should only be available if the map is not in a qualified-or-greater status.
