### ISSUE TITLE
Deleting a thread from the new site still exists in the list on the old site

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#1675]
pretty much the same issue as https://github.com/ppy/osu-web/issues/1650

I tested something about bbcode on the new site, deleted it and it's still on the old site. When you click on it you don't have the permission to see it (of course, because it's deleted lol) but it just shouldn't be in the list.

https://tati.s-ul.eu/IBSxaLwZ.png

yeah, I already mentioned that in Discord once but I guess peppy didn't see it ;w;

**Comment by Okorin** [comment]
considering old site is supposed to be replaced by new site i dont think it's worth fixing something that isnt critically broken while also saying that that thing is scheduled to be phased out of existence

**Comment by peppy** [comment]
Not going to fix this one, as it's not a simple one to fix. Deleted threads are few and far between, so I do not foresee this being a huge issue until we replace the forums very-soon™.

**Comment by Xinnoh** [comment]
I thought the intention was for subscribed threads not to be shown, and that the old site was correct.
yea if the new site is correct then I wouldn't have opened htis
