### ISSUE TITLE
Settings page unavailable to restricted users on the new site.

### ISSUE THREAD

**Issue by Fyurie** [ppy/osu-web#1676]
Browsing to https://osu.ppy.sh/home/account/edit while restricted shows a page with the following:

"You shouldn't be here."
"You could try going back, though."

I've tried various steps like resetting cookies, clearing browsing history, etc, but nothing seems to change the result.

**Comment by kj415j45** [comment]
i suppose this is just a restrict to **restricted users**

**Comment by Fyurie** [comment]
Bully. :^(

(funnily enough, I did think that at first, but support confirmed otherwise, and it works on the old site)

**Comment by peppy** [comment]
We can probably allow restricted users access to their settings.
