### ISSUE TITLE
New page headers should be taken from the article

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#1696]
![image](https://user-images.githubusercontent.com/191335/32497663-a12f4ec8-c410-11e7-8b29-68496cc6df4d.png)

**Comment by peppy** [comment]
@arflyte can you confirm how you want this to be? @nekodex mentioned you may still want a news page header, so we need confirmation before going ahead.

**Comment by arflyte** [comment]
![d6f2d2e13e](https://user-images.githubusercontent.com/3632750/36409830-2ca824ce-1651-11e8-8d6d-21e52baec44e.png)

This was the unimplemented News header. Going to redesign it to match the new other redesigned pages. For now, just use this header image to replace the current one. Use the same height, expand only when the title overflows into two lines.

![newsheader](https://user-images.githubusercontent.com/3632750/36410157-b18f37c6-1652-11e8-95e5-d86db76d3efd.png)

**Comment by peppy** [comment]
Is this new design done yet?

**Comment by arflyte** [comment]
The new news page is part of the home page design, which is still being worked on.

So, here's the latest design tweak for the current design. 
The date carousel is centered on selected date. News title is out of the cover and placed below the cover.
![osu next - osu news](https://user-images.githubusercontent.com/3632750/39742349-1bb18b06-52d8-11e8-897c-30bb7a9c2662.png)

**Comment by peppy** [comment]
Let's prioritise this and get it done.

@arflyte how are you supposed to see the titles of the pages you're navigating to (since this will replace the [post listing page](https://osu.ppy.sh/home/news))?

**Comment by Joehuu** [comment]
I think the new design is in #3719.

**Comment by peppy** [comment]
Closing in favour of #3719
