### ISSUE TITLE
Badge placement for new user profiles

### ISSUE THREAD

**Issue by tastystew** [ppy/osu-web#1697]
Seeing as how there isn't any badges on the user profiles in the new website, here are some suggestions.

![image](https://i.imgur.com/KmvwuqG.png)

![image](https://user-images.githubusercontent.com/29350765/32501844-14e3ad5c-c414-11e7-9753-e1287b25a925.png)

![image](https://user-images.githubusercontent.com/29350765/32501602-6308aa1a-c413-11e7-9e9c-53230a267782.png)

**Comment by Ephemeralis** [comment]
@arflyte

**Comment by arflyte** [comment]
![photoshop_2017-11-17_16-15-56](https://user-images.githubusercontent.com/3632750/32935251-a47839d8-cbb2-11e7-87b0-4a4248e8d8ec.png)

Award badges tentatively placed on top of the user avatar. All legacy badges will be converted into the new badges with a standard template. None of the award badges has been designed yet.

There might be a slight rearrangement of all contents in the cover area (including the award badge) as it's getting too cluttered now.

**Comment by peppy** [comment]
@arflyte is going to have something by tomorrow

**Comment by peppy** [comment]
flyte has come up with something but it might not be posted here. coming soon.

**Comment by nekodex** [comment]
resolved by #2826
