### ISSUE TITLE
[Forum] No way to check the date of thread creation in the thread listing

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#1705]

**Comment by peppy** [comment]
Is this required though?

**Comment by TPGPL** [comment]
if there's a date of the latest post, then there should be a date of post *creation*

**Comment by peppy** [comment]
Do we need all this info flooding the listing, though? You can see once you enter the thread.

**Comment by TPGPL** [comment]
it can help people while browsing the forums as the threads aren't sorted by creation date, so you would have to enter *every* thread to see if it's new or not
