### ISSUE TITLE
Increase friend limit

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#1708]
Opening as an issue first to promote discussion on github
Currently one of the most popular [feature requests](https://osu.ppy.sh/forum/t/176843) is to increase maximum friends from 250 to higher.
The limit has been set to 250 for almost 5 years, and is one of the most outdated rules on the site considering how much the game has grown since.
Increasing the limit only takes a couple minutes [on this page](https://github.com/ppy/osu-web/blob/5420da692f42a7371c9c92c049f0e8cceb4b9165/config/osu.php) and would be accepted as a welcome improvement across the entire community.

There's also an option to make this a supporter exclusive feature, which would encourage more people to buy the tag.

**Comment by peppy** [comment]
It takes more than a "couple of minutes" as we would need to reconsider loading and display of friends in

- osu-stable / bancho
- lazer
- web (probably with pagination and searching)

we'd need to reassess every query that uses friends to ensure there won't be any performance regressions.

adding as a supporter feature sounds more feasible in the short term.

**Comment by Xinnoh** [comment]
i underestimate due to having literally no knowledge on how this works 👌, my bad for assuming stuff

**Comment by peppy** [comment]
Reopening pending adjustments to `osu-web` (friend limit has been increased on the old web to 500).

**Comment by Toybickler** [comment]
just a note, trying to add players past 250 in game brings this message https://osu.ppy.sh/ss/9654950 but works fine through the website

**Comment by peppy** [comment]
@Toybickler a bancho update is coming which resolves that one. Just have to wait for the right moment to deploy it.

**Comment by VINXIS** [comment]
didn't want to make a duplicate post for this and it is closed but I wanted to ask anyway (and its also been 5 years similar timeframe OP states)

would it be possible to increase the friend limit again? cant speak for everyone but ive been at the limit for like 90% of my time on osu (250 and 500), if the limit was like 2000 or even at least like 1000 it would be nice but it definitely would make the friends list massive
