### ISSUE TITLE
New beatmap listing page can essentially hide other modes in a hybrid set with standard

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#1712]
On the new beatmap information page, only standard difficulties are displayed on the osu! tab in the new beatmap listing. 
To see difficulties of other modes would request clicking on their respective tabs.
However, due to osu! standard converting to other modes, all mode tabs are visible and clickable on any set involving standard. There is currently no distinction to show when the other modes have difficulties specifically mapped for them.
In cases like https://osu.ppy.sh/beatmapsets/688590#osu/1457177 this reduces visibility of non standard modes in such a hybrid significantly.
Other modes icons should be visible on a hybrid set involving standard when on the osu! tab, similar to the old beatmap listing.

**Comment by notbakaneko** [comment]
Would adding a count next to each mode help?

![image](https://user-images.githubusercontent.com/1694544/32826795-233be9d6-ca2d-11e7-8daf-53cba95d23ac.png)

**Comment by dorothy3242** [comment]
Absolutely, this is great!
