### ISSUE TITLE
Small / Large userpage banners are covered in different areas

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#1713]
Easy summary https://puu.sh/ykQYD/8bd16118e5.png
It's hard to create banners that work well on both the small and large user panels

**Comment by dorothy3242** [comment]
If #1709  is implemented this should have a similar solution in which how these types of banner images are cropped would be adjustable for each place they appear.

**Comment by arflyte** [comment]
Cover images will be implemented differently with a different direction in the new page designs.
