### ISSUE TITLE
Unable to know how long since a nomination in modding v2

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#1714]
There is no indicator of when a map was nominated unless a BN posts at the same time they nominate. 
This is important because maps must be nominated for at least 24 hours before they can be qualified. There isn't any way to know when exactly 24 hours have passed since nomination.

**Comment by peppy** [comment]
Does this nor show up in the log?

**Comment by Xinnoh** [comment]
I forgot that even existed, it's there. Would be nice if the nomination time was in a clearer spot
