### ISSUE TITLE
User card appears too slow

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#172]
Feels like the page fade and the user card fade are being done synchronously.

**Comment by peppy** [comment]
**[Bounty](https://goo.gl/nFdoyI) offered**: 50

to make the fade and slide-in happen at the same time rather than one after each other

![](https://puu.sh/n1fPY/03ea9e5e61.gif)

**Comment by ErinvanderVeen** [comment]
Did you happen to mean a bounty of 5 rather than 50? 50 seems quite high.

**Comment by peppy** [comment]
I did not. I'm increasing bounties to get more people involved in this project. Factoring in the effort required to get started with the project too (learn the framework/layout of the system).

Expect to see more "higher than expected" bounties pop up.

**Comment by ErinvanderVeen** [comment]
Ahh, makes sense. I hope it works out.

**Comment by peppy** [comment]
@Bobo1239 congratulations on your 50 bounty for this! let me know via email if you would like to redeem it at any point (pe@ppy.sh).
