### ISSUE TITLE
Mobile view is completely broken

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#1720]
![](https://cdn.discordapp.com/attachments/361358311561363457/377622084366368769/Screenshot_2017-11-07-19-54-48.png)

**Comment by notbakaneko** [comment]
fixed by #1723?

**Comment by peppy** [comment]
![img_aa5394b8bfd6-1](https://user-images.githubusercontent.com/191335/32930577-e2f238ae-cba2-11e7-858e-f20e3725921b.jpeg)

👍
