### ISSUE TITLE
Mappers should not be able to receive kudosu from their own map

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#1739]
https://puu.sh/ynfgv/634064bfe4.png
If a mapper creates a discussion on their set, others can upvote it and the mapper gets kudosu. Map owners can't receive kudosu in mv1, and shouldn't be the case for mv2 either.

**Comment by osuShiro** [comment]
Can confirm this.

**Comment by nanaya** [comment]
But shouldn't they? Do people not mod each other difficulties for maps with GDs?

**Comment by peppy** [comment]
Let's disable the ability for mappers to post on their own map in the first place

**Comment by Xinnoh** [comment]
That's a really bad idea, it prevents the mapper from asking questions about things, as shown in the image I linked. The mapper should be able to discuss and ask questions to the community on specific parts of their map.

**Comment by peppy** [comment]
Fair point. We'll add a new "Note" type for mappers only, which cannot receive up/downvotes. This can be used for asking questions/leaving notes to viewers/whatever.
