### ISSUE TITLE
broken difficulty count for hybrid sets

### ISSUE THREAD

**Issue by lassem22** [ppy/osu-web#1741]
diffficulty count for sets that include maps for multiple game modes is broken
for example [this](https://osu.ppy.sh/beatmapsets/285577) 
shows them as https://i.imgur.com/x6C4zeI.jpg even though the set has a standard diffciulty

also happens for other hybrid sets like [this](https://osu.ppy.sh/beatmapsets/693946), but works properly for [single mode sets](https://osu.ppy.sh/beatmapsets/670579)

probably related to #1712

**Comment by notbakaneko** [comment]
The number not showing is unrelated to the set type.

**Comment by nanaya** [comment]
Fixed by #1745.
