### ISSUE TITLE
The converts shouldn't be shown in other mode tabs or transform beatmap parameters

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#1743]
![](https://puu.sh/ynt5d/1a3ff33101.jpg)
![](http://puu.sh/ynt8C/f5f470fe27.jpg)

As you can see the stats in both images are the same, they aren't converted to the specific mode parameters.

Solutions:
1. Don't show converts in other mode tabs
2. Add formulas to transform the parameters

**Comment by notbakaneko** [comment]
Changed to only show unconverted counts.
