### ISSUE TITLE
Show who has upvoted discussions

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#1747]
We should be able to view who has upvoted a discussion post, possibly by hovering the upvote button similar to disqus.

**Comment by Xinnoh** [comment]
This should also be available on kudosu history, same for denying kudosu here

(Last 3 mods are modding v1)
![screen shot 2017-11-18 at 10 30 35 pm](https://user-images.githubusercontent.com/30382015/32981431-bea7917e-ccb0-11e7-9b6d-8defbcde3abb.jpg)

**Comment by osuShiro** [comment]
This should probably be a December milestone. At the moment, upvoting has no moderation options and that makes it easily abused.

**Comment by peppy** [comment]
2017...

Let's continue discussion in #4503.
