### ISSUE TITLE
Move beatmap title away from diff selector

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#1749]
https://puu.sh/ynKSy/bf7b55d90e.png
I've accidentally clicked on the title instead of the diff selector too many times. Moving the two further away from each other would make this less annoying.

**Comment by peppy** [comment]
There should definitely be some kind of hover state change to show you're going to click a link. Also the difficulty line should probably not be part of the link

cc @arflyte

**Comment by Xinnoh** [comment]
Seems like this was unintentionally fixed by moving it down
