### ISSUE TITLE
Upvote cap fix was not applied

### ISSUE THREAD

**Issue by Mirruuu** [ppy/osu-web#1765]
Not sure if I'm the only one getting this but this fix did not apply the rate increase. I am able now to deny kudosu but I still have only 10 upvotes to give out.
As a BN I should have unlimited:
![image](https://user-images.githubusercontent.com/25852637/32949712-1f5cab52-cba4-11e7-8268-a70976317966.png)

Denying kudosu working: 
![image](https://user-images.githubusercontent.com/25852637/32949733-2a6213f2-cba4-11e7-8067-345e0b1cee1f.png)

**Comment by peppy** [comment]
Please try again now - the deployment process got stuck due to an unrelated issue

**Comment by Mirruuu** [comment]
Seems like it works, now. Thanks!
