### ISSUE TITLE
Top Navigation Header opens too easily

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#1767]
I've been running into this a _ton_ where any time I switch tabs on my browser and try to move my mouse to click something near the top of a page, I can't because the navigation hover menu opened from my quickly moving over its area. You can simply move the mouse down more and up again... but it gets irritating to have to regularly do this after a while. 
The menu is getting in the way a lot of the time.
This is especially punishing when you try to move your cursor to the top to change mode tabs and accidentally go too high, opening it again, and requiring you to move off of the menu again to get it to close. 

Video of condensed footage of frustrations:
https://youtu.be/IALcAS4EkL0

**Comment by nekodex** [comment]
Resolved by #1795. Please reopen this issue if you find the fix insufficient.
