### ISSUE TITLE
Profile page beatmaps section does not consistently display pending beatmaps

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#1772]
On many userpages I have visited since this was added, not all of a user's pending beatmaps are displayed.

Some pages it appears to be working fine, others it is not, it's a bit inconsistent.

Example page where all 10 pending maps are displayed: https://osu.ppy.sh/users/4956097
Example page where only 4 out of their 9 are displayed: https://osu.ppy.sh/users/5226970

**Comment by nathanial292** [comment]
Yup, I had this problem too. Was just talking about it with some other mapping guys
