### ISSUE TITLE
Estimation to rank isn't working as intended

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#1782]
https://osu.ppy.sh/beatmapsets/629384/discussion
My map has been in qualified for four days, there aren't enough maps in qualified to activate the 8 map per day limit. It was qualified on the 17th, hence it will be ranked on the 24th. 
The site is currently estimating it to be ranked on the 30th. It was estimated to be the 27th a couple days ago.

(I think) The code is using today as the day of qualification, not the day it was qualified.
There are 19 maps in front of mine, 19/8 = 2.1
2.1 + 7 days = 10 days in qualified, the 30th is 10 days from now.

**Comment by nanaya** [comment]
Whoops right.
