### ISSUE TITLE
Player Search for people with short names.

### ISSUE THREAD

**Issue by nathanial292** [ppy/osu-web#1788]
Okay so I have the ign of b00 in osu. If I search for "b00", The new search system doesn't prioritise the players with the exact name you typed. Instead it comes up with 50 random players that probably haven't played in ages or are not active anymore, before the player that you want. For example here I am on the 4th page... https://i.imgur.com/ULRD1Ig.png
Maybe we could implement a system to put players that are online or are more recently active first in the list?

This is pretty much the case for everyone with a 3 digit name and finding them on the new website is basically impossible without typing it directly into the url bar.

**Comment by Lewskl** [comment]
Could also make it so that if the query is a player's exact username they're first in the results

**Comment by nathanial292** [comment]
Yeah thats what I was thinking too. For example https://i.imgur.com/vFjVeOv.png
