### ISSUE TITLE
New web missing ability to revive graveyarded maps

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#1793]
^
Should be a link or button on graved maps that the mapset host can press to revive/resurrect it? Either on their userpage or the map's information page.

**Comment by Xinnoh** [comment]
This + deleting

**Comment by peppy** [comment]
Please use the old site for this for now. This will come a bit later on.

**Comment by dorothy3242** [comment]
Bumping this since the new web will be live soontm and old web wouldn't be an option.

**Comment by peppy** [comment]
May add this to the stable client as a better alternative. Marked as required either way.

**Comment by Xinnoh** [comment]
there's still people like me using fallback :x
would be nice to have it still as an option but I understand trying to get rid of fallback

**Comment by shortthu** [comment]
So reviving beatmap via client have already been added to stable, should this be closed now?
