### ISSUE TITLE
Missing popping/vetoing process in modding v2

### ISSUE THREAD

**Issue by Naxesss** [ppy/osu-web#1794]
Often referred to as a pop, this icon would prevent the map from being qualified without renomination. This is used in modding v1 by nominators to ensure beatmap rankability/quality as a proactive measure to prevent unnecessary disqualifications. For example, if a map has unrankable issues, it's bubble must be popped to fix the issue and prevent it from being qualified in that state. [See this post](https://osu.ppy.sh/forum/p/6362061), for instance.

The vetoing process is just an extension of popping, which is more directed to moderating beatmap quality, disallowing the previous nominator from renominating until the vetoing nominator allows it (when the issue is fixed or a consensus is reached). Another nominator which hasn't had their nomination vetoed can nominate regardless of the vetoing nominator's permission. However, unlike popping, it is not necessary to implement system-wise as it's simply a construct based around the ability to pop.

Essentially what is missing is a button to subtract/reset nominations before a set is qualified, accessible by nominators as well as qat. Once the set is qualified, this button would instead be replaced by the disqualify button and from there only be available to qat as it is now.

**Comment by nekodex** [comment]
How about instead of adding a button to manually do this, we instead automatically reset nominations when a BN/QAT posts a new problem on a map that has nominations?

**Comment by squirrelpascals** [comment]
@nekodex that would be kind of like automatically popping a bubble, which is very inefficient. In some cases the second nominator will only suggest minor changes before pushing the map forward, but in unrankable cases a reset will have to be done.
imo there should actually be **three** options, a bubble, bubble pop, and a veto option, since those last two things have different definitions.

**Comment by peppy** [comment]
Minor changes should still be checked by all that have previously nominated the map. We will ensure notifications are sent out in these cases so those that nominated can check back.

**Comment by peppy** [comment]
We are trying to simplify this system, not add every last option back.

**Comment by Okorin** [comment]
not having a centralized point to see the reasons might get confusing for the ones that have to deal with it (mapper and bns whose nominations have reset)- not saying people aren't going to adapt but if people search for disqualification reasons on the top of the discussion page whatever problems/vetos/bubble pop reasons should inhabit the same space as the reason for a dq would so that people only have to look in one place for relevant information?

it could link the specific issues in question that were found, but collecting it in the same way we currently have disqualification reasons displayed could make  that more straightforward?

Just an idea

**Comment by Naxesss** [comment]
Keep in mind that in order for pops and vetoes to function properly, a period of time (in this case 24 hours) must be followed by the first nomination before a set is qualified, in order to give other nominators time to look over it and place any potential pop, should they have found any major issues. This means every time the nominations are reset, the map is practically delayed by at least 24 hours. Again, this isn't something that needs to be implemented system-wise since it's already in use (despite pops and vetoes being missing), but it leads us to the first point.

With the above in mind, if the reset was connected to posting a problem in the discussion (as nekodex suggested), nominators would end up avoiding the problem type. In this situation, marking what would normally be a problem type as a suggestion type would allow them to prevent unnecessarily delaying the set, for something that may be as simple as a missing hitsound or new combo. Such minor issues are assumed to be fine with the previous nominator. I just want you to be aware that automating it based on a choice like which type of issue you post would lead to possibly unintentional behavior in that regard due to the implications of a pop. I don't think we should eliminate options to the degree where workarounds are needed for it to work efficiently, even if it may be tempting to try to make it simpler.

The popping/vetoing process isn't something that is used in every set, and isn't necessary for all either, despite being important, so generalizing it as a regular process (such as always requiring a renomination for any minor change) is not something I'd recommend for efficiency's sake. If the 24 hour rule wasn't a thing, this approach would work well, but it would also stop the popping/vetoing process from working properly, since two nominators could just nominate a map in quick succession to avoid any opportunity for a pop. The pops themselves are already extremely simple in usage and implementation; the only thing that is complicated is the way they're handled rule-wise (which is already taken care of).

Anyway if you're going to connect pops to the problem type, consider connecting disqualifications to the problem type as well for consistency or visa versa with buttons or other way. This is because pops and disqualifications are both approached and replied to in a very similar way, both often done in the same situations, just in different contexts and by different people.

**Comment by peppy** [comment]
If the nominators are avoiding pressing a button because of pissing off a mapper due to a 24 hour delay *for pointing out an issue* they can leave the team.

**Comment by Xinnoh** [comment]
if nominators pop maps for rankable issues they are kicked from the team, it's a complete 180 on the current policy.

**Comment by nekodex** [comment]
This was resolved by #1870
