### ISSUE TITLE
Modding status change notifications

### ISSUE THREAD

**Issue by lassem22** [ppy/osu-web#1802]
currently the mapper doesn't get any form of notification when their map gets nominated in the new system

would be nice to send an email notification to the mapper (and maybe also people that have the map in their "modding watchlist"), similar to when something new gets posted

**Comment by peppy** [comment]
We need a lot of intermediary notifications along with this... like

- Map nominated/denominated (people who nominated the map should be notified, along with the mapper).
- Map qualified/unqualified (people who nominated or qualified the map should be notified, along with the mapper).

**Comment by nanaya** [comment]
That watch thing already notifies nomination/disqualification...

**Comment by lassem22** [comment]
Since when is it supposed to do that? I'm watching [this](https://osu.ppy.sh/beatmapsets/688552/discussion) for example and didn't get any notification when it got nominated a day ago. And from what I heard from talking to other mappers none of them got any so far either.

**Comment by nanaya** [comment]
The content is exactly the same as notification for new posts. Did you not get any?

**Comment by lassem22** [comment]
Didn't get anything when Battle nominated it, modding notifications before worked fine and this was a long time after the last post of the map (like over a day I think)

**Comment by nanaya** [comment]
Do you have the page open when it's nominated (or within 5 minutes)?

**Comment by lassem22** [comment]
Pretty sure I had it closed, I just know I wasn't actively looking at the page. Also from the people I talked to it seemed like nobody got notified about nomination of their maps

**Comment by nanaya** [comment]
The other possibility is you're already notified for another update (new post) and haven't read it...

**Comment by lassem22** [comment]
in that case I think nomination should be something important/significant enough to ignore this and still notify the mapper? also since I replied to every problem/suggestion and there was no new praise I don't think that was the case.

**Comment by nanaya** [comment]
Should be handled by new notification system. No email yet though.
