### ISSUE TITLE
Downvoting removes kudosu and has no moderation options

### ISSUE THREAD

**Issue by Naxesss** [ppy/osu-web#1803]
Apparently if you downvote a post that was upvoted, you can take away the kudosu that the post earned. As is with any upvoting or downvoting, anyone can do this, so it's a bit concerning that there are no moderation options for this. Imagine if someone went around downvoting everything, practically removing the reward from modders' hard effort at the click of a button. Again, this opens up a lot of vulnerabilities and forces more moderation than we already need, but there's no way to actually moderate this currently. Denying the kudosu would be doing the opposite of what you'd want, and upvoting again as a moderator can only go so far.

![image](https://i.imgur.com/ewOfGp2.png)
![image](https://i.imgur.com/dDhVCx7.png)

Since [we'll be able to see who upvoted](https://github.com/ppy/osu-web/issues/1747), this could be implemented through allowing individual actions for each downvote instance in a similar fashion, for example being able to undo/nullify certain votes. So that's one way of doing it, although a quite complicated and time consuming way for something that I feel should inherently be simple, both in practice as well as implementation.

Another way, and probably much easier and effective, would be to only account for upvotes when calculating the vote sum for kudosu rewards. This would be able to apply retroactively and prevent abuse while keeping a positive enviroment in the modding community; an ideal solution in my opinion, and what I expected from the beginning.

This is essentially [the other missing moderation problem](https://github.com/ppy/osu-web/issues/1742), where upvotes needed regulation due to being part of the kudosu system, but this time for downvotes.

**Comment by Xinnoh** [comment]
Alternate solution could be 2 downvotes are required to deny kudosu, prevents one person from abusing the system alone + still allows normal users to decide if things should be denied

**Comment by peppy** [comment]
More moderation options are coming, but we will already be able to see this kind of activity from a database level (and fix it).

Also downvotes will eventually be tiered off.

**Comment by nanaya** [comment]
Downvoting has been limited to nominators/moderators since #1984.
