### ISSUE TITLE
Add the option to sort featured artist music by category

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#1804]
https://osu.ppy.sh/beatmaps/artists/16

Featured artist works are sorted alphabetically, which doesn't provide much logical order.
Adding options to sort the tracks by bpm, length and genre would make it easier for mappers to find songs that suit their preferences.

**Comment by peppy** [comment]
There are huge future plans for better navigability and filtering of featured artists, but this is post-release.

**Comment by Loreos7** [comment]
It's done now.
