### ISSUE TITLE
Suggestion: Show various modding tips under the new discussion box

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#1805]
![screen shot 2017-11-24 at 11 08 39 am](https://user-images.githubusercontent.com/30382015/33194128-a24812b8-d108-11e7-8eb7-2571e20300f1.png)

The timestamp feature under the text box is one of the less useful features, I don't think anyone has found it useful so far.
The ctrl-c tip is also common knowledge that doesn't need explaining. Once someone learns ctrl-c, they don't need to be told it again. 

Different tips could be shown to modders that have above x kudosu. The "Common Mistakes Among Modders" box from [here](https://osu.ppy.sh/u/naxess) has many good tips that could be rotated, similar to the tips on the game's main menu.

**Comment by peppy** [comment]
This *should* be shown as a timestamp is *required* before you can post a message. Not everyone is a sesasoned modder.
