### ISSUE TITLE
Beatmaps are displayed starting from oldest to newest on userpages

### ISSUE THREAD

**Issue by StarrStyx** [ppy/osu-web#1806]
Not really sure if this is intentional or not, but shouldn't beatmaps be displayed starting from newest maps at the top? Reason because the newest maps would be the ones that the mapper wants the users viewing their userpage to see first most of the time.

**Comment by Commie-Husky** [comment]
Might wanna label this "improvement" and "beatmap"

**Comment by peppy** [comment]
This does indeed sound back-to-front.

**Comment by peppy** [comment]
Is fixed, yes.
