### ISSUE TITLE
Misleading text for unupdated beatmaps

### ISSUE THREAD

**Issue by Nyxa** [ppy/osu-web#1809]
Currently, if a map hasn't been updated for x time, a message will appear reading 

> This beatmap hasn't been updated since date, and has most likely been abandoned by the creator...

The second half of that phrase is rather redundant, and it may also mislead people, since sometimes mappers just set a project aside for a while due to time constraints without having any intentions of abandoning the map. Just saying 

> This beatmap hasn't been updated since date

should be more than plenty.

**Comment by nekodex** [comment]
Actually that message only comes up if the beatmapset has been graveyarded and isn't based on x time. Maybe the message can be reworded to be more clear about that.
