### ISSUE TITLE
Kudosu history displays character references

### ISSUE THREAD

**Issue by Naxesss** [ppy/osu-web#1813]
![image](https://i.imgur.com/LcYk5re.png)
![image](https://i.imgur.com/cVvEk16.png)

![image](https://i.imgur.com/4YSpO4o.png)
![image](https://i.imgur.com/rxV7AC0.png)

![image](https://i.imgur.com/B6VBhnz.png)
![image](https://i.imgur.com/48wFcFa.png)

**Comment by notbakaneko** [comment]
Seems to be due to kudosu done on the old system using the text from the post title, which was escaped when stored.

**Comment by notbakaneko** [comment]
Should be displaying properly now
