### ISSUE TITLE
Wrong favourite count

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-web#1815]
![screenshot_20171126-133639](https://user-images.githubusercontent.com/18349191/33237440-043fc176-d2af-11e7-9e20-cbd4e07469f0.png)

**Comment by Xinnoh** [comment]
This was an issue on the old site too, so it's probably not directly tied to the new implementation

![screen shot 2017-11-26 at 1 46 52 pm](https://user-images.githubusercontent.com/30382015/33237526-7032fc62-d2b0-11e7-80e8-6be509e23d67.png)

**Comment by peppy** [comment]
Could you please link beatmap or beatmapset URLs rather than screenshotting them?

**Comment by Xinnoh** [comment]
ya https://osu.ppy.sh/s/572387 & https://osu.ppy.sh/p/beatmaplist?q=sinnoh%20granat&m=-1&r=2&g=0&la=0&ra=

**Comment by peppy** [comment]
Like related to incorrectly cached counts. Will require further investigation.

**Comment by kj415j45** [comment]
btw, if many people ❤️ , the counter only show '+ 1 other!' , not like in locale file: `+ 1 other!|+ :count others`

**Comment by peppy** [comment]
Please open separate issues in separate issues.

**Comment by VINXIS** [comment]
Not sure if this is related/the same issue but https://osu.ppy.sh/s/555864 seems to show different favourite counts on the old beatmap page (shows 39) vs the new beatmap page, and the old + new beatmap listing pages (show 43) figured i should post if it's any help

**Comment by cl8n** [comment]
the one vinxis linked looks like it has `favourite_count` (72) out of sync with actual favourite count (68), and probably an issue on old web cuz here it only increments/decrements and it's doing it correctly

**Comment by peppy** [comment]
I've fixed this on old web.
