### ISSUE TITLE
API v2 beatmaps/xxx/scores should accept ruleset ID, not acronym

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#1819]
Required for https://github.com/ppy/osu/pull/1599.

Should be switched to 
`?mode=osu` -> `?mode=0`
or at very least support both ID and acronym (using `is_numeric` or something).

The osu! client doesn't (and shouldn't) need to know the string identifiers for rulesets.

**Comment by nekodex** [comment]
Not sure I agree with this, if anything I'd argue the opposite - the client shouldn't need to know the internal id for each game mode, esp. if we're using short names publicly across the site (i.e. scoreboards, `?mode=<shortname>`, profiles `user/<userid>/<shortname>`, etc)?

If I were using the API, I'd not want to have to look up game mode ids before making requests... esp. if we're adding/supporting more community modes in the future?

**Comment by peppy** [comment]
right now the client-side database stores the online id of the ruleset. i guess we can change this to being a shortname instead, i'm indifferent. will require a fair amount of restructuring to make this happen so we need to be sure that's the direction we want to go.

fwiw i chose to base it on IDs to stay in line with other API requests (beatmaps/beatmapset) which also use primary key IDs.

**Comment by nekodex** [comment]
After further discussion, we've decided to use shortnames/acronyms to reference game modes instead of ids going forward and @peppy will make the required changes to the game client.
