### ISSUE TITLE
Taking an .png avatar forces it to .jpg

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#1832]
well, and that's bad when your avatar has some transparency in it

there's a thread about it: https://osu.ppy.sh/forum/t/668284

**Comment by peppy** [comment]
I believe we are still mixed about whether we should support transparent avatars at all. If anything we may add an editor which allows the user to choose the background colour. For not I'd recommend setting it yourself using a free image editor.

**Comment by karstenes** [comment]
Sticking with jpeg only keeps file size down and also keeps consistency, especially in the client.

**Comment by peppy** [comment]
It's mostly for design and performance reasons – we don't need to display a background layer behind every avatar just in case it's semi-transparent.

**Comment by karstenes** [comment]
Also, for that background idea, maybe use PIL and a short python script?

**Comment by Dontmakemeeatyou** [comment]
While I understand performance reasons. Unless forcing jpg / no alpha would be very beneficial, I'd probably prefer it stay really.  I'd say a fair amount of users prefer the style, including myself.

**Comment by peppy** [comment]
What style? If it's always displayed against a single colour background what's the issue with baking that background in?

**Comment by Dontmakemeeatyou** [comment]
I guess there is more of a difference In-game, compared to the website. I guess it's just nicer to have the Background of whatever is going on around your character, name, logo (whatever you got) as opposed to a solid color box. 

Transparency doesn't mean much on Forums, maybe just in-game.

**Comment by karstenes** [comment]
That would require multiple avatar images to be stored though.

**Comment by jacksonisiah** [comment]
any word on what is going to happen with this?

(had a friend email me earlier asking about this issue)

**Comment by peppy** [comment]
The current answer is "use non-transparent avatars"

**Comment by Daarling** [comment]
Peppy please keep transparency, while i do understand that server hdd space has costs, and png use more resources (almost negligible to be honest) and all its nice to have transparent background avatars, it just looks cleaner and lots of players use them. [clean](http://prntscr.com/ijeocv) [clean](http://prntscr.com/ijepec)

**Comment by peppy** [comment]
That is the opposite of clean.

Closing this for now as it's not really open for discussion.
