### ISSUE TITLE
Wiki isnt available for locales not existing in the osu-web

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#1845]
[For example the German wiki](https://github.com/ppy/osu-wiki/issues/748)

**Comment by kj415j45** [comment]
iirc, in previous ver of osu!web, there's a locale selector in wiki page's head. but it was removed in #xxx (i can't find that pr :x)

**Comment by notbakaneko** [comment]
a corresponding locale should always be required for supported languages (i.e. wiki language won’t show up if site doesn’t include the language in the supported list)
