### ISSUE TITLE
Double checkboxes

### ISSUE THREAD

**Issue by CraftedCart** [ppy/osu-web#1847]
When looking at user settings on new website design (https://osu.ppy.sh/home/account/edit), two checkboxes appear for each option in the "Playstyles" section (And I presume anywhere else on the website that uses the same styling for checkboxes). I would assume that, on Windows, the custom styled checkbox would overlap the default checkbox, hiding it behind. With the theme I use on Linux however, the default checkbox (blue) is clearly visible under the custom one (green/grey).

This seems to be easily fixed by hiding the system checkbox with the following styling.
```css
.osu-checkbox__input {
    display: none;
}
```

Browser: Firefox Quantum 58.0b5
GTK+ Theme: Adapta Nokto Eta

Before adding the style fix (How the website currently is)
![](https://i.imgur.com/w5fxnlf.png)

After adding the style fix
![](https://i.imgur.com/rr7efxn.png)

**Comment by nanaya** [comment]
Can't reproduce this. Are you using some custom userstyles? (also no, it's not hidden by overlapping the default box)

**Comment by nanaya** [comment]
![](https://s.myconan.net/2017-11/VirtualBox_2017-11-30_16-33-59.png)

**Comment by nanaya** [comment]
![](https://s.myconan.net/2017-11/VirtualBox_2017-11-30_16-33-59.png)

**Comment by CraftedCart** [comment]
Huh. Seems odd.
And no I'm not using custom userstyles.

**Comment by CraftedCart** [comment]
Ok in my Manjaro VM I don't get the issue, however in another Arch Linux VM I do?

Posting the VirtualBox machine here where I could reproduce it in case it helps: 
https://mega.nz/#!4dtDwC4Q!0OPGaRIpT7T49brp3qG5F73oQcxtEVVUPi7LoBwmaC4

User: `sayaka`
Password: `password` (Root password is the same)

Did a fresh install for that VM so there shouldn't be any odd browser tweaks or personal info.

**Comment by peppy** [comment]
If it's not happening in vanilla firefox then it's a distribution specific thing. Not something we're interested in fixing as it probably affects you and you.
