### ISSUE TITLE
Clicking on permalink does nothing

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#1848]
Clicking permalink doesn't do anything, it has to be right-clicked to copy the link or open in another tab.

![screen shot 2017-11-30 at 10 12 48 am](https://user-images.githubusercontent.com/30382015/33409564-16e648f8-d5b7-11e7-9c54-ca0ae341c757.png)

**Comment by peppy** [comment]
This has been around for quite a while. I've brought it up multiple times.
