### ISSUE TITLE
Beatmap Description goes right up against the scrollbar

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#1849]
On the current website, descriptions shift slightly to the left overall when the description is long enough for there to be a scrollbar. 
The new website's beatmap descriptions do this too, but not enough for its design, resulting in things such as centered text or banners looking uncentered and pretty funky.

This is especially unbalanced/bad looking when description banners are added, such as on this example because it goes right up to the right border but has lots of space to the left:
https://osu.ppy.sh/beatmapsets/501719#osu/1083103
![image](https://user-images.githubusercontent.com/33286824/33412932-8aaa8070-d55c-11e7-8901-a3aa4c70f3a3.png)

It happens with text as well if it is long enough to reach the right border
![image](https://user-images.githubusercontent.com/33286824/33413293-c244ede8-d55e-11e7-8c4d-28baa3c9e787.png)

**Comment by peppy** [comment]
@notbakaneko relevant..

**Comment by nanaya** [comment]
That's because the left padding isn't part of description area.

![](https://s.myconan.net/2017-11/2017-11-30_14-50-45.png)
