### ISSUE TITLE
Performance regression due to username lookup improvements

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#1863]
https://github.com/ppy/osu-web/pull/1790 causes crazy high database load for lookups, as indices cannot be used due to the `ORDER BY` statements.

For now I've disabled this server-side. Will need to look at a more permanent fix.

**Comment by notbakaneko** [comment]
I tested moving this to elasticsearch:
<img width="916" alt="screen shot 2017-12-14 at 16 39 32" src="https://user-images.githubusercontent.com/1694544/33980989-7071bf14-e0ee-11e7-9b81-502faf517431.png">

It can also do fuzzy matching, priority matching or some other fancy pants matching

**Comment by peppy** [comment]
Closing as this has been resolved (performance issue).
