### ISSUE TITLE
Avoid beatmap data overflowing off the page

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#1879]
https://osu.ppy.sh/beatmapsets/701416#mania/1484517
![screen shot 2017-12-03 at 5 09 14 pm](https://user-images.githubusercontent.com/30382015/33523895-9265285e-d84c-11e7-8649-84e1bb3ff650.png)

**Comment by peppy** [comment]
Probably should use a number formatter to reduce to 123k/123m/123b, if we are going to allow these kinds of silly maps to display.
