### ISSUE TITLE
Add counts of pending issues to difficulty selection dropdown

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#1899]
It should be possible to view the number of pending issues in the difficulty dropdown, so a map creator can easily locate any outstanding issues. This could use the same format as the tab item counter display.

![Pasted Image 1.png](https://shipusercontent.com/0d2e0007c0dcbb2eb8669ea44e2450fb/Pasted%20Image%201.png)

**Comment by dorothy3242** [comment]
https://github.com/ppy/osu-web/issues/1266 ?

**Comment by peppy** [comment]
Closing in favour of #1893 which has a good example of it being displayed
