### ISSUE TITLE
warning message for when a mod post goes over character limit

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#1901]
The character limit is perfectly well and dandy, but if you go over it, the page simply give a generic "Failed saving post" message without specifying why
this can be very confusing for a modder trying to figure out what is causing it, or lead them to mistakenly assume it's an internet problem or bug
![image](https://user-images.githubusercontent.com/33286824/33644813-29ae33da-da15-11e7-9214-a0be963d4ebb.png)
when surpassing the character limit, it could be something else such as, "Your post is too long! Please shorten it or split it into multiple points" 
or something along those lines to help encourage modders to break up what would be too lengthy.

**Comment by peppy** [comment]
The text box should really stop allowing typing, and probably show a countdown of characters remaining

**Comment by nanaya** [comment]
Added in #1908.
