### ISSUE TITLE
Linebreaks should have more spacing than default text wrapping

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#1902]
I left a linebreak in this comment, but it looks identical to text wrapping. Linebreaks should have slightly higher spacing so that there is a visual difference.
![screen shot 2017-12-06 at 12 43 14 pm](https://user-images.githubusercontent.com/30382015/33644935-1055cc86-da83-11e7-997a-daee914a2d1b.png)
Example with higher spacing for linebreaks
![screen shot 2017-12-06 at 12 43 14 pm](https://user-images.githubusercontent.com/30382015/33645014-882192cc-da83-11e7-9e6e-855e592cc873.png)

**Comment by nanaya** [comment]
Perhaps use two newlines instead?

**Comment by Xinnoh** [comment]
could but that takes up even more space

**Comment by notbakaneko** [comment]
Use 2 new lines
