### ISSUE TITLE
There is no cancel button when creating a reply

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#1903]
![screen shot 2017-12-06 at 12 49 52 pm](https://user-images.githubusercontent.com/30382015/33645112-24fe402c-da84-11e7-847f-f433796c5a39.png)

it stays there until i refresh the page, which creates even more unused space to scroll through

**Comment by nanaya** [comment]
I asked flyte months ago and he said no. Dunno if he changed his mind now.

**Comment by notbakaneko** [comment]
with the reply and resolve button now, adding the cancel button makes it too wide on narrower windows :D 💥

**Comment by notbakaneko** [comment]
Something like this maybe?

![image](https://user-images.githubusercontent.com/1694544/34097461-8e2a6e44-e41c-11e7-8646-deae9fc44a82.png)
![image](https://user-images.githubusercontent.com/1694544/34097502-a7d7ff8c-e41c-11e7-8e90-8f2c3648d9fb.png)

pressing `esc` will also cancel

**Comment by notbakaneko** [comment]
#2020
