### ISSUE TITLE
Text boxes should have the same text wrap as the final post

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#1904]
When editing a post, the editor window uses the same text wrap as when text is posted. When creating a new post, a larger text wrap is used which can hold more words per line. Sentences will look different while writing, but look correct when editing.

Example below, replies wrap on the word "finding" when posted / editing, but the box for making a new reply can also fit "discussions" on the same line.
![screen shot 2017-12-06 at 12 56 58 pm](https://user-images.githubusercontent.com/30382015/33645941-5c44c732-da88-11e7-8b39-0daeaf1f7499.png)

**Comment by peppy** [comment]
The page is a flowing layout. Also different browsers and operating systems and devices render text differently.

This is not possible and should not be expected.

**Comment by Xinnoh** [comment]
The only reason it's not working is because there's no username next to the profile image when creating a reply, while there is one while editing. If the username was added, it would already be fixed. 
This issue can be fixed by adding username to the profile image while creating new posts, it's already there while editing.

**Comment by peppy** [comment]
Try resizing the window.

**Comment by Xinnoh** [comment]
https://www.youtube.com/watch?v=lPnnk99eQ7U
