### ISSUE TITLE
Modding discussions: Linebreak doesn't work after special characters

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#1918]
First image:
A list with different items, featuring commas at the end of each line
 ![2017-12-07_00-25-40](https://user-images.githubusercontent.com/33286824/33700127-36ee18a0-dae5-11e7-8224-17e09c5e9a7e.gif)
Second image: The same thing, but without the commas at the end.
![2017-12-07_00-18-14](https://user-images.githubusercontent.com/33286824/33699942-45beec66-dae4-11e7-9ac7-5bc099c33366.gif)

Should be fixed especially since linebreaking for lists would often involve commas
this happens with other special characters such as "(" and ")" as well

**Comment by nanaya** [comment]
...whoops.
