### ISSUE TITLE
More detailed email notifications

### ISSUE THREAD

**Issue by Mirruuu** [ppy/osu-web#1925]
Not so much a bug or anything but more a suggestion. Currently, there's no real indication of what has occurred on an mv2 discussion in the email that gets sent. They're almost exclusively like this:

![image](https://user-images.githubusercontent.com/25852637/33717081-e0f5ff16-db58-11e7-885d-23fbe6b2a6bd.png)

I think it could be beneficial to have more informative messages such as:
- "Just letting you know a new issue was posted in beatmap "beatmap" since your last visit."
- "Just letting you know an issue was reopened in beatmap "beatmap" since your last visit."
- "Just letting you know you have received a nomination in beatmap "beatmap" since your last visit."
- "Just letting you know a user has contributed hype to "beatmap" since your last visit."

Something along those lines. At the moment when I get an email to look at a discussion I really have no idea what I should be looking for and it doesn't really seem all that intuitive.

**Comment by peppy** [comment]
Yep, we definitely plan to improve this system. It was implemented in the current way just to have something in place (as opposed to nothing).

**Comment by VINXIS** [comment]
any progress on this?

I'd like to just point out that a direct link to a new post or similar would also be **very** beneficial for mappers compared to just a link to the discussion board since like moddingv1 we would get a direct link to the post instead of just the thread itself

**Comment by peppy** [comment]
Our next osu-web focus is the notification system, which will include improvements here.

**Comment by nanaya** [comment]
It should be more detailed now.
