### ISSUE TITLE
Bad english on store out-of-stock message

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#1932]
![Pasted Image 1.png](https://shipusercontent.com/b14098c1a34eca28a6bad8be0bf09f9b/Pasted%20Image%201.png)

`This type is currently out of stock :(. Try other type or check back soon.`

should probably read something like

`Unfortunately this item is out of stock. Use the dropdown to choose a different type or check back later!`

**Comment by TPGPL** [comment]
gonna take this one

**Comment by peppy** [comment]
who even wrote this 🤔
