### ISSUE TITLE
Download page is outdated and incomplete 

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#1937]

**Comment by peppy** [comment]
(no shit)

but this actually does need to be addressed as pretty high priority. i think @arflyte may already have an updated design for it.

**Comment by LiquidPL** [comment]
I could pick this up, if there's a design.

**Comment by peppy** [comment]
![Pasted Image 1.png](https://shipusercontent.com/db489fb1fb75586a61188f2cdeef6d42/Pasted%20Image%201.png)

@2x
![Pasted Image 2.png](https://shipusercontent.com/265163ec5af7e3ff1a619c41070a16b8/Pasted%20Image%202.png)

header image: ![Pasted Image 3.png](https://shipusercontent.com/fc7f606051212126b525fb2eddbfcb6a/Pasted%20Image%203.png)

**Comment by peppy** [comment]
@arflyte may want to provide a cleaner header image (i just screenshotted roughly)

**Comment by arflyte** [comment]
Here are them covers.

![cover](https://user-images.githubusercontent.com/3632750/33822038-1deb2816-de91-11e7-8920-c32bc3de3db0.jpg)
![cover 2x](https://user-images.githubusercontent.com/3632750/33822039-1e3df316-de91-11e7-8750-2bcdbcc80b90.jpg)

**Comment by LiquidPL** [comment]
1. What text should go under step 2?
2. Can I have a psd with all the font sizes?
3. Is that icon above the download button used anywhere in the project right now? I can't seem to find it anywhere.

**Comment by peppy** [comment]
1. "Click the button above and run the installer."
2. I've PM'd it to you.
3. No, it's a custom one. For now just png it from the psd (we need to make a webfont for it eventually) @rbrat3 might help with that

**Comment by RBRat3** [comment]
Yea I can get it in by the end of the week... Might I suggest using a [generic download icon](http://fontawesome.io/icon/download/) in font awesome instead of uploading a PNG image for the time being. That way it's just a simple line change instead of cleaning out unused image assets later on.

**Comment by peppy** [comment]
There's many many new icons, so best ask flyte before starting on it
