### ISSUE TITLE
Locale for emails

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-web#1938]
![https://cdn.discordapp.com/attachments/388708216781012993/388726683559133185/Screenshot_20171209-001946.png](https://cdn.discordapp.com/attachments/388708216781012993/388726683559133185/Screenshot_20171209-001946.png)
as above, only the email titled be translated. I found `i18n_view()` in `app/Mail`, 
so i asked if i could add `{$file}-{$lang}.blade.php` to `resources/view/emails/`, but @nanaya said:
> I don't think it works for email yet because there's no language setter when sending them. emails are sent through different process which doesn't share language setting as web

Hope we can make osu!web more i18n.

**Comment by nanaya** [comment]
Done in #5349 and #5362.
