### ISSUE TITLE
Text cursor does not display at the beginning of a line when editing

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#1942]
![2017-12-09_00-50-53](https://user-images.githubusercontent.com/33286824/33792918-137e5708-dc7b-11e7-8699-0e4cdd08903d.gif)
minor issue but this can lead to the text cursor seeming to have dissappeared
(this happens at the start of the post as well, if the gif isn't clear about that)

**Comment by dorothy3242** [comment]
Oh no, I forgot to state that this is for the modding discussions panel. This doesn't appear to occur in the forums.

**Comment by peppy** [comment]
my bad! switched out labels.

**Comment by nanaya** [comment]
What browser and operating system version is that?

**Comment by dorothy3242** [comment]
regular Google Chrome, and windows 10
