### ISSUE TITLE
Allow users to choose the order of favourite beatmaps on their profile

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#1944]
On the userpage, beatmaps are sorted by id. The oldest six maps in favourites/ranked are listed for other players see.
The user should be able to choose which 6 maps other players initially see when browsing favourite/ranked beatmaps.

**Comment by peppy** [comment]
as a quick-fix, it should probably show the most recently favourited maps.

**Comment by nanaya** [comment]
Other sort options can be done through beatmap search :thinking:
