### ISSUE TITLE
Provide a link to beatmap discussion on sets with v1

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#1946]
https://osu.ppy.sh/beatmapsets/570924/
It's not possible to access the [v1 thread of a map](https://osu.ppy.sh/forum/t/556231) with the new forum. This makes it impossible to reach discussions that happened on the old forum.
Yes, mv2 is replacing v1, but users are unable to access v1 threads on sets ranked prior to mv2.

**Comment by peppy** [comment]
The Discussion button in these cases should link to the `thread_id` in the beatmapset row.
