### ISSUE TITLE
Sign up page is not available in new site

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-web#1951]
¯\\\_(ツ)\_/¯

**Comment by peppy** [comment]
Correct.

**Comment by kj415j45** [comment]
I think new users should have a better experience when they come to osu! world. So .... reopen

**Comment by TPGPL** [comment]
The registration will be handled by the osu!client i think

**Comment by kj415j45** [comment]
You mean all in osu!lazer ? :thinking:

However, currently we use old site to complete registration, that means no translation. (Some guys couldn't understand a word)

**Comment by peppy** [comment]
Signup will be moved completely in-game in the near future. We're finishing all other areas of the new site first, though.
