### ISSUE TITLE
Disable downvotes for anybody but BNs/QATs

### ISSUE THREAD

**Issue by Loctav** [ppy/osu-web#1955]
Currently available to everybody, downvotes are an easy tool to deny kudosu from people that may or may not have posted something unpopular or said something against everybody's darling mapper so people can easily just mob up and bully down the person.

While I believe that downvoting should be made accessible to people at some point, it should be locked behind the tiers that will  unlock abilities within the ecosystem.

Until the tier system is a thing, downvotes should remain only in the availability of the Beatmap Nominators and QATs, as it is too easy to abuse right now.

**Comment by nekodex** [comment]
This was fixed in #1984
