### ISSUE TITLE
Profile improvements list

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#1958]
Lots of stuff, image might take a while to load
![help](https://user-images.githubusercontent.com/30382015/33864004-81c2fff0-df25-11e7-81bc-0b80dc639065.jpg)

**Comment by peppy** [comment]
Please file individual issues individually. We can't deal with these kinds of reports.

Also make sure to check things before you report them. For instance, "show more" is actually a thing.

![Pasted Image 1.png](https://shipusercontent.com/8d42bcb8587f20fe805c03ff137f4da9/Pasted%20Image%201.png)

**Comment by peppy** [comment]
Okay you were talking about the "Recent" seciton itself. Regardless, it'll be much easier to follow up on things like this when you report them individually so please do that.

And I ask that you use text to describe the issue, accompanying a localised screenshot if that will help.
