### ISSUE TITLE
Medal icons are blurry on profile

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#1959]
At 1x display, they seem to be being upscaled and/or using the wrong underlying asset.

![Pasted Image 1.png](https://shipusercontent.com/ddd69b1dacb2f6f36386edc541f9c3da/Pasted%20Image%201.png)

**Comment by nanaya** [comment]
Or because chrome image scaling is blurry.

**Comment by peppy** [comment]
safari for the record

**Comment by cl8n** [comment]
still happening @peppy ? I remember seeing this too but it's resolved for me (probably a long time ago)
