### ISSUE TITLE
Rename userpages from "me!" to "Userpage"

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#1961]
It's pretty informal, profile is clearer what it means
![screen shot 2017-12-12 at 10 35 36 am](https://user-images.githubusercontent.com/30382015/33864576-43d4750e-df28-11e7-8960-7bb61cc602aa.png)

**Comment by peppy** [comment]
it's supposed to be a section describing yourself. what's wrong with "me!"?

Also "user page" is redundant because you are on the user's profile (page).

**Comment by Xinnoh** [comment]
I don't think this really needs to be added anymore
