### ISSUE TITLE
Give user more options for filtering/hiding medals

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#1962]
As more achievements get added, the medals take up more space to scroll through. Collapsing the medals by default makes it easier to scroll through profiles.

Same applies for beatmaps. Having maps in ranked, pending, graved, and favourites takes up a lot of space.

These two things make up 60-70% of the profile's screen space, and is really unnecessary

**Comment by peppy** [comment]
To who? To you? What about people who want to show the maps they made or like?

Also only *achieved* medals are shown on profiles (except for your own). Usually this makes it quite condensed already (to the medals a user cares about showing off).

Have you considered reordering your profile to move these to the bottom if they don't interest you?

**Comment by Xinnoh** [comment]
Everyone views their own profile more frequently than other people's profiles. 
In addition, many players do not care about medals, no need for them to be seen, even if it's at the bottom of the page.

**Comment by peppy** [comment]
If it's at the bottom what are you trying to see below it?

**Comment by Xinnoh** [comment]
Because not everyone puts medals last, 

Also, this should apply to the user description
https://osu.ppy.sh/u/4787150 is fine on the old site, but https://osu.ppy.sh/users/4787150 is not

**Comment by peppy** [comment]
Having show/hide and reordering within beatmaps is something I can agree with.

**Comment by shortthu** [comment]
show less medal could be related to #814 i think

**Comment by Xinnoh** [comment]
#2825 seems to be received better, closing this in favor of it.
