### ISSUE TITLE
When clicking "Show more", show 30-50 new things, not 5

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#1963]
You have to click show more 19 times before reaching a player's 100th best play. 
You have to click show more 1 time on the old site.
Increasing the number of items shown per click makes life easier.

This applies to kudosu, recent plays, most played beatmaps, recent plays, etc.

**Comment by peppy** [comment]
How often do you want to see a player's 100th play? Is this a common use case (can you describe why you'd need this)?

**Comment by Xinnoh** [comment]
I often need to check my kudosu history to see what mappers have responded to, whether they accept, reject, and whether I need to further explain my viewpoint.

**Comment by Xinnoh** [comment]
#2010 has a better title
