### ISSUE TITLE
Banner is covered in different parts on userpage and profile banner

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#1965]
Doormat placed anime girl on the left side because it's not covered by information. When viewing his profile [here](https://osu.ppy.sh/groups/28), the face is covered. This is also an issue if there is text in the banner.
![screen shot 2017-12-12 at 11 12 08 am](https://user-images.githubusercontent.com/30382015/33865599-651448ca-df2d-11e7-8894-a0f8afc3e592.png)
![screen shot 2017-12-12 at 11 12 01 am](https://user-images.githubusercontent.com/30382015/33865602-66c7453c-df2d-11e7-96f8-708ceb1f59eb.png)

**Comment by dorothy3242** [comment]
sinnoh you already made an issue for this https://github.com/ppy/osu-web/issues/1713

**Comment by Xinnoh** [comment]
holy shit I'm retarded
