### ISSUE TITLE
Add (admin level?) page to view a user’s usage of the modding discussion system

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#1969]
Moderators need some visibility of a user's posts/actions/votes-received on the system. Doesn't need to be pretty (or public-facing) but just functional.

**Comment by Okorin** [comment]
Is user activity in terms of actions in beatmap discussions so highly classified that it needs to be a moderator option? You can find all the info this would list by looking around in public places

**Comment by peppy** [comment]
No, but as an initial rough implementation I prefer to keep it this way until the design is hashed out.
