### ISSUE TITLE
new forum map description issue

### ISSUE THREAD

**Issue by Sotarks** [ppy/osu-web#1974]
When I want to edit my description on modding V2 forum, it saves correctly.
Later on when I want to update my map with BSS in game, the edit i did previously of my description doesn't appears in the update box, and when update is finish it replace what I edited with the old mv1 header for some reasons.

**Comment by notbakaneko** [comment]
Can you include a reference in the issue itself, thanks.

**Comment by peppy** [comment]
Should be https://osu.ppy.sh/beatmapsets/700726/#osu/1491266 (discussion in #osu-web-modding)

**Comment by peppy** [comment]
This has been resolved with a path to the BSS server-side components. Please test again and reopen if you are still having issues!

**Comment by Sotarks** [comment]
Everything is fine now, thanks ppy!
