### ISSUE TITLE
Mapper namechanges show on information page but not beatmap search

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#1975]
example 1:
https://osu.ppy.sh/beatmapsets/468938#osu/1002859
beatmap search will display their old name
![image](https://user-images.githubusercontent.com/33286824/33898999-1b9be7a6-df38-11e7-82c8-aaa8318e8dfb.png)
beatmap information page will display their current name
![image](https://user-images.githubusercontent.com/33286824/33899015-2b3ff724-df38-11e7-9db9-cdf6cbc5ebf9.png)

versus ingame:
![image](https://user-images.githubusercontent.com/33286824/33899063-4ac96b8e-df38-11e7-830a-ba47ad567e42.png)

It should still be displayed with the name they had when the mapset was ranked, so that it is consistent with what is seen in-game.

Example 2:
https://osu.ppy.sh/beatmapsets/375877#osu/1460396 the mapper changed his name to MariahCarey and back specifically so this beatmap could be ranked under the name MariahCarey to match the artist field, but this is not displayed on the new web's information page.. so .. uhh.. rip.

**Comment by peppy** [comment]
The most recent username should always be displayed, actually. If anything is to be fixed, it's the display on the listing, which is showing a username sourced from the beatmap rather than the user.

**Comment by Xinnoh** [comment]
Previous / old usernames should still be searchable and attached to the set.
Example https://osu.ppy.sh/p/beatmaplist?q=bor
If changed, 'All Alone With You' would not be searchable with "bor", but everyone calls the mapper bor.

**Comment by peppy** [comment]
search-ability and display are different things. they will always remain searchable.

**Comment by peppy** [comment]
Bumping in priority since this is a weird one with an easy fix.

**Comment by notbakaneko** [comment]
I think it was mentioned recently that the name shown should be the one at the time of submission, not the most recent one?

**Comment by peppy** [comment]
Correct, we always want to show the author coming from the beatmap metadata.
