### ISSUE TITLE
Beatmap descriptions getting erased following certain characters

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#1976]
not sure whether this is related to https://github.com/ppy/osu-web/issues/1974 or not. That could potentially be the beatmap header getting messed up when GD difficulty names incorporate ' , erasing the rest of the description, and causing what's left of the header to show up in BSS... somehow.
Edit: after looking at Sotark's screenshots provided in the discord server, I am 99% sure that's exactly what happened.

Step 1:
Edit my beatmap description on the new website
![image](https://user-images.githubusercontent.com/33286824/33899406-694e819c-df39-11e7-9eb1-2a021dbf35b9.png)
![image](https://user-images.githubusercontent.com/33286824/33899412-6ce00678-df39-11e7-9a24-1f50d0c8f5e5.png)
everything looks good!
Step 2:
Update my beatmap ingame
![image](https://user-images.githubusercontent.com/33286824/33899444-818aac2c-df39-11e7-835a-f1b7c7b7bab4.png)
anything in the description following the ' character in the text "rin's favorite song" got annihilated.

This does not happen if you fix it in the BSS submission window and update again, it only happens during updates following an edit on the new website

So to break it down, it's:
new website description edit -> update -> description gets partly erased
update description edit -> update -> description does not get erased

**Comment by notbakaneko** [comment]
This is likely the same issue as #1974
