### ISSUE TITLE
Stretch nomination status when nomination button is not shown

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#1977]
If I am looking at someone else's mapset, the hype train will be smaller to make space for the hype button:
![image](https://user-images.githubusercontent.com/33286824/33901006-69470f2a-df3e-11e7-9ab4-c54b4b31bafa.png)

If it's my own set, the hype train stretches out to fill the space:
![image](https://user-images.githubusercontent.com/33286824/33901017-74692cf8-df3e-11e7-98d5-1ac53bc1fa87.png)

The nomination status should also be stretched to fill the space as well if a user is not a nominator, so that there isn't that.. odd empty space left behind where the nomination button goes.

**Comment by peppy** [comment]
Indeed does look odd.

**Comment by dorothy3242** [comment]
Closing this because it got fixed at some point 🤷

**Comment by dorothy3242** [comment]
Reopening because I was mistaken, it didn't get fixed. It's apparently dependent on logged in status for some reason.
Not logged in:
![image](https://user-images.githubusercontent.com/33286824/38715381-cdfe3a32-3ea8-11e8-8f8e-37967cdc1033.png)
Logged in:
![image](https://user-images.githubusercontent.com/33286824/38715391-d6634604-3ea8-11e8-84e9-05f9a01c39bc.png)

**Comment by Xinnoh** [comment]
seems like it's always shown because you're a bn, non-bns probably don't have that

**Comment by dorothy3242** [comment]
I checked with a regular user, it displays the same way for them when logged in. It was also displaying this way for me since ever before I became a bn.

**Comment by dorothy3242** [comment]
Ok now this time it got fixed for sure, closing issue.
