### ISSUE TITLE
Display timestamp when hovering over an issue on the timeline

### ISSUE THREAD

**Issue by Okorin** [ppy/osu-web#1979]
Ported from https://osu.ppy.sh/community/forums/posts/6398427

![image](https://i.imgur.com/5Y2ovWo.png)
`It'd be pretty sweet when highlighting a pinpointed dot by moving your cursor to be shown at what exact time was the pinpoint without having to click. If you click and it's not what you thought it was you just have to scroll back up and try again lo.`

meaning, that it'd give you a bit more orientation if the timestamp the comment is attached to is shown when hovering it on said timeline, i think. so you dont end up jumping to some comment / suggestion that you didnt intend and have to scroll your way back up

**Comment by peppy** [comment]
Can agree with this one.

**Comment by dorothy3242** [comment]
![image](https://user-images.githubusercontent.com/33286824/38271814-74b4cf40-3755-11e8-9bcf-518bb32d5d72.png)
This was added at some point, should be closed?
