### ISSUE TITLE
BSS Update is bugging for some random diffs.

### ISSUE THREAD

**Issue by Sotarks** [ppy/osu-web#1987]
When I update my map there's still one diff that needs to be updated to latest version : https://i.imgur.com/DG9JdoB.png
And if I update it goes 0 stars, and corrupt my map files ...
To fix this I need to update on this diff directly, but then it's an other diff that has the same bug...

I tested on others maps and this bug happen too for some reasons I don't know.

**Comment by peppy** [comment]
This is not related to the osu-web project, and very likely specific to something you have done locally to your beatmap via manually changing .osu files.

You may want to post on the forum about this.
