### ISSUE TITLE
Deleted messages should be expandable

### ISSUE THREAD

**Issue by Naxesss** [ppy/osu-web#1991]
At the moment, if you go into **[this discussion](https://osu.ppy.sh/beatmapsets/659328/discussion)**, you'll notice that there are a few posts that take up a lot of space, and that all moderators must scroll through even if said posts are already deleted. In the same way, while trying to read through certain other discussions, people have sometimes deleted posts in conversations, which makes it confusing to follow, especially since it's not very clear which message is deleted at first glance (the transparency and italics help but they're still hard to notice, transparency also doesn't happen for deleted comments as far as I can see).

As suggestion, making deleted messages possible to expand in order to view for moderators would be more intuitive, at least for those of us who actually use the system itself for other purposes than just moderation. This in turn would also make it possible to take screenshots/videos without exposing deleted content.

How it is now
![image](https://i.imgur.com/YnIfZDb.png)

How it could look like
![image](https://i.imgur.com/9Kk9NvZ.png)

**Comment by JBHyperion** [comment]
Some kind of toggle for displaying/hiding deleted messages might work also.

Reduces a bit more clutter for when you just want to focus on modding, but anything moderation-related can pop right back up when needed.

**Comment by Ephemeralis** [comment]
This still needs to be addressed - deleted messages should preferably be hidden and naturally require folding out so as not to make our moderators want to die whenever they open a high-traffic, contentious discussion.
