### ISSUE TITLE
Unexpected demical in matches page

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-web#1993]
![ed4ddb02d6c207d](https://user-images.githubusercontent.com/18349191/33986996-5ab422c8-e0fa-11e7-8b7a-ddf59a23146c.png)
![1e94db526887e1e2](https://user-images.githubusercontent.com/18349191/33987003-5e0b32e0-e0fa-11e7-8a91-8deccffbf9f8.png)
As above

**Comment by notbakaneko** [comment]
is this happening on all matches for you?

**Comment by kj415j45** [comment]
repoter said it seems that this situation only happened on specific version of SouGou Browser ¯\_(ツ)_/¯

so, it's not neccessary to detect this issue i guess. because this browser is not very popular.
