### ISSUE TITLE
Ruleset-specific counters are missing from beatmap pages

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#1998]
We should be able to see ruleset-specific counts where necessary as per old rankings.

osu!catch -> droplets
osu!taiko -> large hits
osu!mania -> 500/MAX

**Comment by TPGPL** [comment]
Same with the Beatmap Metrics like AR

**Comment by peppy** [comment]
@nekodex can you confirm/assign this one? i think it's relevant to what you're currently working on
