### ISSUE TITLE
Add a method to enlarge forum images to full size.

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#2]
Images are scale-to-fit width (similar to old forum) but there's no way to expand them out.

Either click-to-expand (in-line, similar to old forum, seemed to work well) or click to load in new tab/lihgtbox.

I'm a fan of the expand in-line since it doesn't break the UX.

**Comment by omkelderman** [comment]
I tend to go towards the lightbox option, cause (at least now in old forums) when you expand a picture thats like big you have to scroll to the right, and with a lightbox its needly centered. But maybe the expand can also be centered, idk.

At least in my opinion that expand thing looks ugly.

**Comment by peppy** [comment]
@arflyte need your input on this

**Comment by PieInOblivion** [comment]
I'm sorry are you asking how an option should be implemented or how to do it?

**Comment by TPGPL** [comment]
isn't it finished?

**Comment by nanaya** [comment]
Sure is fixed.
