### ISSUE TITLE
Sample Data

### ISSUE THREAD

**Issue by reesebiz** [ppy/osu-web#20]
It would be really convenient for there sample data for people working on the site. When people clone the repo it should available from the get-go. Preferably already on the site too, and not just in the DB.

Looking for:
- Beatmaps
- Beatmap Sets
- Users
  - User Stats
- Forums
  - Forum Posts
- Wiki
- Tournaments
- Store
  - Store Items
- Changelog

**Comment by peppy** [comment]
We need to setup proper [seeding](http://culttt.com/2013/12/16/seeding-laravel-4-database/). If anyone is interested in looking into it, I'm happy to offer some bounty for a good implementation (amount depends on quality and completeness)

**Comment by reesebiz** [comment]
I'll look into it, but no promises.

**Comment by peppy** [comment]
**[Bounty](https://goo.gl/nFdoyI) offered**: 20

Only offered for complete implementation as described in https://github.com/ppy/osu-web/pull/26#issuecomment-136953592, and documentation added to the readme.

**Comment by ameliaikeda** [comment]
Feel free to assign this to me; I'm going to implement [Model Factories](http://laravel.com/docs/5.1/testing#model-factories) for everything so people have have a full set of data from the start.

**Comment by reesebiz** [comment]
@ameliaikeda I'm working on the pull request that I have open now and it's almost done. I'm using model factories for it too.

**Comment by Hughp135** [comment]
As someone wanting to help out on this project, some sample data would be really useful to start out with. Even if it's just a DB export with some sample users/beatmaps/score data that would be extremely helpful.

Has anyone finished implementing model factories / the seeder yet? I'd be willing to make these if I could get some sample data. @ameliaikeda  @reesebiz

**Comment by peppy** [comment]
I'll go out on a limb and say it hasn't been done yet.

I'll see what I can do with some data export. I'll presume you just need a few rows from each table to understand the format?

**Comment by Hughp135** [comment]
Yeah that would be ideal. Thanks.

**Comment by ameliaikeda** [comment]
I got a new job a while back and haven't been able to do much of anything
(deadline is in just over a month for me). This pretty much just needs a
small db dump with a user or two, a forum, a few topics and some posts in
it (and a sample beat map) and people can jump in way faster.

**Comment by peppy** [comment]
Increasing bounty to 300.

**Comment by Hughp135** [comment]
Currently working on this. I'm grabbing some sample data using the osu API atm, since I still don't have an export of peppys database :'(

**Comment by peppy** [comment]
give me a list of tables and i will provide some

**Comment by Hughp135** [comment]
Just realised that you've probs got thousands or more entries in some tables and getting a small sample size from that might not be easy with all the relationships in there. I'll think about it and let you know what's needed later if anything.

**Comment by peppy** [comment]
osu_beatmapsets: https://gist.github.com/f93ce06e18a7a3fbb493
osu_beatmaps: https://gist.github.com/7924d7b1e4b2fba9d367

**Comment by Hughp135** [comment]
Other useful tables might be: osu_countries, osu_achievements, osu_counts

In terms of user tables, the one im struggling to grasp is the osu_user_performance_rank table (the one with r0-r89 columns.

**Comment by nanaya** [comment]
osu_user_performance_rank is cyclic columns containing ranks for each user/playmode for last 90 days. Check the `RankHistory` model.

**Comment by Hughp135** [comment]
progress update - I've made a seeder for users, stats and maps using real data obtained from the osu api. These are loaded from json data stored in a zip file which is automatically unzipped before seeding the DB, and then the unzipped files are deleted afterwards.

 The reason I went with this approach as opposed to generating random strings etc was so that the data would be more meaningful (and so all the relations between maps, scores, events etc were valid). Was just wondering if this would be an acceptable way of doing things or if you would prefer the data to be generated without any dump of data dump being used.

**Comment by LiquidPL** [comment]
Are the json files within the repo? If so, I suggest against deleting them after seeding, as somebody might actually commit them deleted by accident. Also somebody might want to reset their vagrant vm and would have to redownload the data.

**Comment by Hughp135** [comment]
They would be deleted after seeding - plus they will be in a subfolder which is .gitignore'd so it shouldn't be an issue.

**Comment by LiquidPL** [comment]
So I assume you're pulling them from somewhere else while seeding?

**Comment by Hughp135** [comment]
All the data was pulled from the osu API. I did originally think of having the seeder make API calls to seed the data, but realised that would be an unnecessary extra load when I could just store the sample data I obtained and seed off that.

**Comment by peppy** [comment]
Awarding bounty of 300 to @Hughp135  (sorry for the delay!).
