### ISSUE TITLE
[Contest page] Voting form stays even after voting is finished

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2001]
![](https://puu.sh/yH1ZW/8482cc2838.png)

**Comment by LiquidPL** [comment]
How exactly should this behave for contests after voting end, but before results reveal? Should it just be a 'Voting for this contest has ended' message, and nothing else?

**Comment by peppy** [comment]
@nekodex can you check on this one?

**Comment by nekodex** [comment]
This is not a bug, this is intentional so you can check your votes before the results are released.
