### ISSUE TITLE
Allow maps in WIP state to be nominated

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2004]
Fallback can't upload marathons to pending state, it's impossible for someone who is stuck on fallback to have their marathon nominated with v2.

Not much reason to prevent wip maps from being nominated, since BNs always communicate with the mapper before nominating.
![screen shot 2017-12-16 at 11 23 30 pm](https://user-images.githubusercontent.com/30382015/34071949-ae81fdec-e2b9-11e7-9817-023afb7493d4.png)

**Comment by peppy** [comment]
Fallback is not supported. Do not use it.

**Comment by Xinnoh** [comment]
Regardless of using fallback, we should still be able to nominate wip maps if the mapper accidentally uploaded it to wip.

**Comment by peppy** [comment]
No, the mapper should then change it to pending. It's a single radio button toggle.
