### ISSUE TITLE
Adding a "Dark Theme" for the website 

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu-web#2007]
Maybe it would be nice to choose between the normal look and a "Dark" look. like [this](https://osu.ppy.sh/beatmaps/artists) it could be way better to use the website at night since the normal look is really bright

**Comment by peppy** [comment]
I believe we are pushing in that direction (dark) site-wide in upcoming refactors to the design.

Will leave this open for now.

**Comment by Joehuu** [comment]
Partly resolved in #4636. There are more recently open issues about the current design problems.

**Comment by peppy** [comment]
Closing this for now. I think we're almost there.
