### ISSUE TITLE
Total played time missing from user profile

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#2011]
<img src='https://shipusercontent.com/d00605c4cdbe2df6d13b8122ea82f68f/Pasted%20Image%201.png' title='Pasted Image 1.png' width=693>

**Comment by arflyte** [comment]
https://puu.sh/yLEeT/82cf9b8cfb.png

Thinking that playtime would be a brag-able stat, I put it on top for now.

**Comment by cl8n** [comment]
how is play time stored in db?

**Comment by LiquidPL** [comment]
won't this overflow the container box? also this design doesn't have the rank (SS/S/A/B) counters.

![image](https://user-images.githubusercontent.com/991831/35158754-676c5e2c-fd38-11e7-85c5-d3749e2eb92e.png)

**Comment by peppy** [comment]
Yeah, that's definitely an issue. @arflyte please check.

**Comment by arflyte** [comment]
![02745b7827](https://user-images.githubusercontent.com/3632750/35205913-31ba3e48-ff7c-11e7-8bd0-9a6a884cb3d8.png)

Play count left aligned and pushed the user level badge into the same box.
