### ISSUE TITLE
“Previously known as” missing from profile

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#2013]
There's no way to know a user's previous username currently.

Old site:

<img src='https://shipusercontent.com/0da30f8d0670d110f4de66579dca5846/Pasted%20Image%201.png' title='Pasted Image 1.png' width=346>

**Comment by arflyte** [comment]
https://puu.sh/yKfAc/b916dde560.png

Currently in the process of reworking on the profile headers, as it's getting way to congested now. Let's go with that temporarily.

At other areas, we can still use the hover for now. I'll figure out something for the hover name cards.

**Comment by peppy** [comment]
as clarification, should the » be included?

**Comment by Ephemeralis** [comment]
for feedback's sake, i imagine users would _vastly_ prefer the current model of obsfucation (ie: requiring mouseover) than having it plainly displayed at all times

**Comment by peppy** [comment]
Yeah, agree. Let's just go with tooltip for now.

**Comment by Kibbleru** [comment]
Rather subjective, but is it alright to have that thing toggleable? some user may not want to let their 'dark history' be known.

**Comment by peppy** [comment]
No. If there's a legitimate reason to remove your previous username (ie. if it was your phone number of real name) you can contact support.

**Comment by Xinnoh** [comment]
^, support is quite helpful on these things (but use support not pm like I did)
![screen shot 2018-02-03 at 3 11 03 pm](https://user-images.githubusercontent.com/30382015/35764081-9a19f074-08f4-11e8-9bce-e6c3dfb70c4e.png)

**Comment by dorothy3242** [comment]
Since it was relatively recent that the ability to change names multiple times was added, would it be possible to make a list of all previous names display somehow? (Unless a user specifically requests a name to be removed from the record by contacting support)
Currently a user can "hide" an old identity by changing their name twice or more because only the most recent name besides current will display.

**Comment by peppy** [comment]
Yes, all previous names should be displayed in the tooltip.
