### ISSUE TITLE
Sort Modding Watchlist Page by Most Recently updated beatmap

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2017]
Currently the maps on the page are being sorted from oldest to newest initially uploaded.

I think having the most recently updated maps at the top of the list would make more sense, with less recently updated maps as you go down. This way maps more relevant to looking at a page dedicated to keeping you up-to-date with new map posts would be at the top.

Just like the bookmarks or subscription pages for forum threads, threads most recently posted in are at the top of the list.

**Comment by Xinnoh** [comment]
Similar to #1953

**Comment by dorothy3242** [comment]
What? How? I don't see how these are similar at all besides being related to modding.
I'm talking about https://osu.ppy.sh/beatmapsets/watches

**Comment by Xinnoh** [comment]
🔫  thought this was something else

**Comment by dorothy3242** [comment]
It appears I was incorrect in my previously observing that the maps were being sorted from oldest to newest mapset ID, as my newly mod-v2 enabled map that's was uploaded earlier than all other maps on my watchlist is displaying at the bottom of the page's list.

**Comment by peppy** [comment]
I think this makes sense (should probably be the default sort).
