### ISSUE TITLE
Mapper notes should be pinned at the top of discussion

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2024]
Currently if you make a note after others have praised or given suggestions for the mapset in this section, the note will be below the other posts. If notes are to help mappers convey messages about the mapset or things in particular they want feedback on, this should not be buried among other things.
Keeping notes in general sections at the top of other posts would increase their visibility and aid it in fulfilling the intended purpose.

This does not apply to the timeline section since notes appear at relevant times, but this change would make general section notes more useful.

**Comment by peppy** [comment]
I think this makes sense.
