### ISSUE TITLE
Add the ability to view more than the top 5 most popular beatmaps

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2030]
Allowing users to click on the title of each section could bring up a larger more detailed list with more than just 5 maps.
Less important for now, but required once bubbles/pops/dqs are tracked.
![screen shot 2017-12-19 at 5 36 31 pm](https://user-images.githubusercontent.com/30382015/34150375-2a38756c-e4e3-11e7-82e4-167d8e03a690.png)

**Comment by peppy** [comment]
Can you not just check the beatmap listing, as that defaults to ranked date?

**Comment by Xinnoh** [comment]
It was more to be added with the nomination tracker if it was to be implemented in the same way as these, as the history of that one is more important. Adding it for popular beatmaps would be more of a backlog thing.

**Comment by peppy** [comment]
What I'm saying is can't you already get this information from the listing?

**Comment by Xinnoh** [comment]
The former yes, the latter no.

**Comment by peppy** [comment]
Currently only the top 5 are being calculated and stored. This is not related to beatmap nomination/modding. I'll save this as a backlog feature.

**Comment by Xinnoh** [comment]
Closed in favor of #2394
Side note, popular maps besides the top 5 are being calculated, the list is  available in osu!direct 
![screen shot 2018-02-16 at 10 53 13 am](https://user-images.githubusercontent.com/30382015/36291717-a32be9ca-1307-11e8-8eb3-c00675cd63b0.png)
