### ISSUE TITLE
Navigation of profile buttons disappear with narrow browser size

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2033]
Not fun for mobile users that don't want to scroll through the whole bee movie on [my userpage](https://osu.ppy.sh/users/4236057)
[mobile](https://user-images.githubusercontent.com/30382015/34152110-6dd21df0-e4e8-11e7-8b94-a3386146b38f.PNG)
[desktop](https://user-images.githubusercontent.com/30382015/34151878-aed52f96-e4e7-11e7-830f-680fc6a5bc94.png)

**Comment by peppy** [comment]
Or just make your user page shorter...

**Comment by Xinnoh** [comment]
Bumping this, it's a bit more important than old me made it look. Wanted to use it a few times when browsing from my phone but bug affects it.
https://streamable.com/z4w06

**Comment by Joehuu** [comment]
Resolved in https://github.com/ppy/osu-web/pull/10025.
