### ISSUE TITLE
Unexpected score in best performance area

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-web#2036]
![screenshot_20171219-194707](https://user-images.githubusercontent.com/18349191/34156198-2952ca08-e4f7-11e7-92a5-0c0eaa6e6c2a.png)
![-7d8a634278151da6](https://user-images.githubusercontent.com/18349191/34156208-3211c036-e4f7-11e7-8153-ea19ef155543.jpg)

**Comment by peppy** [comment]
I have no idea what this report is. Please include an explanation and use english where possible.

**Comment by peppy** [comment]
Also please do not abbreviate things like "bp" because it's ambiguous.

**Comment by kj415j45** [comment]
the first screenshot is best performance in his profile. the last one display his score rather than pp.

the second screenshot shows that the number there is his score. ¯\_(ツ)_/¯

**Comment by kj415j45** [comment]
btw, that score disappear in old site.

**Comment by peppy** [comment]
Okay, so the issue looks to be that 0pp scores are showing if the user doesn't have enough >0pp scores.
