### ISSUE TITLE
New web is missing the Forum Bookmarks feature

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2039]
On the old web, there was forum subscriptions and bookmarks, two seperate things.
![image](https://user-images.githubusercontent.com/33286824/34175324-1940fe32-e4ca-11e7-861e-c2517463a27f.png)
new web only has subscriptions
![image](https://user-images.githubusercontent.com/33286824/34175368-3f0e3530-e4ca-11e7-8386-1c0e6b3ae830.png)
bookmarks served the same function of helping to keep up with threads, but without spamming an email inbox about it.

If bookmarks are not added to the new website due to redundancy, a user's bookmarks and subscriptions should both be viewable from the new web's subscription page.

**Comment by peppy** [comment]
I believe we are planning on using the subscriptions for this purpose, by adding a checkbox to choose whether you'd like to receive notifications on a per-subscription level.

**Comment by dorothy3242** [comment]
Closing this in favor of https://github.com/ppy/osu-web/issues/2374
