### ISSUE TITLE
Graveyarded Maps show oldest map first? / Loved maps don't show?

### ISSUE THREAD

**Issue by hiendlxxl** [ppy/osu-web#2041]
Hey there,

I found 2 minor "issues" on the website

1) I find it to be kind of strange that on the new web page, the oldest graveyarded maps are shown at the very top. Is that intentional? I mean it is kinda bad when people see your worst maps first ^^

2) Loved maps section seems to be completely gone. This is probably on purpose but I still wanted to make sure in case you guys forgot it for some reason :D 

Other than that, new page is looking pretty good :3

**Comment by peppy** [comment]
I believe this is now resolved.
