### ISSUE TITLE
user menu existence is not obvious

### ISSUE THREAD

**Issue by nekodex** [ppy/osu-web#2049]
I've heard from a few people that they didn't know they could click their avatar to bring this menu up. Probably need a way to let people know of it's existence.

![](https://puu.sh/yKgyg/bf1a63fa94.png)

**Comment by kj415j45** [comment]
auto bring up when mouse move over avatar?

**Comment by Ephemeralis** [comment]
elegant solution to this is to pulse the yellow hilight border on mouseover at a lesser intensity to 'entice' clicking intuitively

**Comment by arflyte** [comment]
This will be fixed in the new header design.

**Comment by Joehuu** [comment]
is this still a problem? it's more or less a "get used to it" scenario.

**Comment by peppy** [comment]
I think this is fine in the current implementation.
