### ISSUE TITLE
Hide "General (all difficulties)" tab on mapsets with only one difficulty

### ISSUE THREAD

**Issue by pishifat** [ppy/osu-web#2058]
![img](http://puu.sh/yKDv3/4453ffb739.png)
redundant when both apply to the same difficulty

**Comment by cl8n** [comment]
I don't think this is a good idea. even for a single-diff mapset, the all diffs tab is usually used for mapset-related issues like audio, storyboards, metadata etc., while the general (this diff) tab is used for comments about the mapping and hitsounding

plus, if the set gets more diffs added to it after some mods are made on the general tab, it'll be confusing.

**Comment by peppy** [comment]
Yep, I think coming this far down the line people are used to posting in the correct place for specific issues.

I don't think the rename is required, even.
