### ISSUE TITLE
Forum post count and post history do not exist

### ISSUE THREAD

**Issue by E223** [ppy/osu-web#2059]
On the old userpages there is a post count which also links to a user's post history.
![](https://death.s-ul.eu/YemQYpkM.png)

**Comment by peppy** [comment]
@arflyte need to decide if we still want to show this and if so, need a design for it.

**Comment by arflyte** [comment]
![2b0550cb01](https://user-images.githubusercontent.com/3632750/36190487-06be1b4c-119c-11e8-867b-1cd91af54556.png)

Feel free to replace the words with something better; I can't think of anything better than 'post contribution' for now.

**Comment by peppy** [comment]
This needs to link to a search showing a users' posts, for what it's worth.
