### ISSUE TITLE
New website followers count

### ISSUE THREAD

**Issue by shibou3** [ppy/osu-web#2067]
When set the page to english, it shows normally the users that "follow" you but, when set to portuguese the followers count becomes 1.

**Comment by kj415j45** [comment]
`users.show.extra.followers` is not existed in 'pt-br' i18n files, it would fallback to 'en', that's the problem.

**Comment by nanaya** [comment]
Not sure if related but I found another problem with [lang.js](/rmariuzzo/Lang.js/issues/64) when messing around.
