### ISSUE TITLE
Improve Language Selector

### ISSUE THREAD

**Issue by nekodex** [ppy/osu-web#2070]
The list of languages has gotten too long:
![](https://puu.sh/yLFtH/f280d68f27.png)

Because of this, we want to reduce the number shown in the main menu and a new "other languages" menu item should be added that brings up a popup with all languages listed. Design courtesy of @arflyte:
<img src='https://shipusercontent.com/c9ee0de0b92df3507210287eca843be6/Bridge_2017-12-22_16-58-16.png' title='Bridge_2017-12-22_16-58-16.png' width=842>

The language options shown in the main menu should be the "relevant" languages (from geolocation) and the 'major' languages (e.g. English, Chinese (Simplified), Chinese (Traditional), Japanese, Korean and Russian).

(I don't think we have a Traditional Chinese translation yet though)

**Comment by nekodex** [comment]
The languages in the popup should be listed left-to-right, so the height will increase as more languages are added.

**Comment by kj415j45** [comment]
Ref: #2071
Dialect will be second menu or list in the same menu?

**Comment by nekodex** [comment]
I think same menu is probably best

**Comment by Deardrops** [comment]
Traditional Chinese translation will be done in `zh-patch10`.
Traditional Chinese will be convert by tool based on simple Chinese translation, then be reviewed by players in Hongkong and Taiwan where widely using it.

**Comment by nekodex** [comment]
This was partially addressed in #2122, so this is no longer urgent.

**Comment by nanaya** [comment]
Should be fine now with two columns popup menu.
