### ISSUE TITLE
LocaleMeta updates: Chinese (Simplified/Traditional/Cantonese)

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-web#2071]
According to @osu-translate-zh 's recent discussion, LocaleMeta will be updated in zh-patch-10.
根据 @osu-translate-zh 近期的讨论结果，我们将在10号补丁中更新 LocaleMeta 。

Here's the planing: (ISO 639-1 Variants)
下面是更新计划：（ISO 639-1 变体）

~~zh: 中文(CN)~~ //Remove because no second selector menu for dialect 由于不为方言提供二级选择菜单而移除
zh-cn: 简体中文(CN)
zh-tw: 繁体中文(TW)
zh-hk: 粤语(HK)

Then we will rename zh -> zh-cn, both on wiki and web.
同时我们重命名现有全部 zh 为 zh-cn ，本操作会涉及 wiki
 和 web 。

This issue is for public discussion before patch being applied.
本 issue 将在补丁应用之前用于公开讨论。

This issue is also reference with #2070 ，about dialect.
本 issue 同时与 #2070 相关，关于方言。

**Comment by Deardrops** [comment]
I personally suggest that using two languages as follow:
```
zh-hans / Simple Chinese / 简体中文
zh-hant / Traditional Chinese / 繁體中文
```

Cantonese（粤语） is not a proper language which can be use in web page interface.
Althought there **may be** a bit of cantonese wiki article.
I still hold the option that NOT use Cantonese, either in `osu-web` or `osu-wiki`.

**Comment by kj415j45** [comment]
though we can use [.NET style](https://msdn.microsoft.com/en-us/library/dd997383.aspx), it still has various issue: zh-hans or zh-chs. and we need to update for all languages
尽管我们可以使用 [.NET 风格](https://msdn.microsoft.com/en-us/library/dd997383.aspx) 的语言代码，但这将导致其他问题，比如：使用 zh-hans 还是 zh-chs 。此外，还得为所有的语言更新一次。

What's more, honestly, i suggest to remove Cantonese from both web and wiki too. it's more like a spoken language, not written.
说真的，我也同意从web和wiki中移除粤语，它更加口语，而不像一个书面语言。

**Comment by kj415j45** [comment]
use ISO 15924 as ISO 639-1 's extension is ok to me, but how about other languages?
我觉得使用 ISO 15924来扩展现在使用的 ISO 639-1 可以，但是其他语言呢？

**Comment by kunihiroInosu** [comment]
I also agree to remove Cantonese both wiki and web. Cantonese is a dialect which haven't it own character.As kj415j45 said, it's more like a spoken language. I personally think that spoken language shouldn't be used to use in wiki or web. 
我也同意在wiki和web中移除粵語。粵語是一個沒有自己文字的方言。如同kj415j45 說的，它更像口語。我個人認為口語不應該在wiki或web中使用。

I searched ISO 15924 and ISO 639. Maybe ISO 15924 is a good choice.
我找了下IOS 15924和ISO 639。或許ISO 15924是個好選擇。

**Comment by Raymonf** [comment]
`zh-hans` and `zh-hant` seems more logical, but `zh-cn` and `zh-tw` seems to be more common.

My apologies for this bump, I wanted to throw in my two cents:

@kunihiroInosu 

>粵語是一個沒有自己文字的方言 (Cantonese is a dialect which haven't it own character.)

This is not necessarily true. While Cantonese can be written, there is no written standard. That doesn't stop the people of Hong Kong, though.

As for the argument that Cantonese cannot be used in an interface, here's a Cantonese dictionary based on the Hong Kong variant whose site is fully vernacular Cantonese: https://words.hk/base/about/

That being said, there is no need for there to be a Cantonese localization. That's really just more to maintain. So here's yet another +1 for removal of Cantonese.
