### ISSUE TITLE
New website profile

### ISSUE THREAD

**Issue by shibou3** [ppy/osu-web#2077]
I don't really know if that's a thing for now but, I believe when the new website becomes the main website, a lot people will complain about the gradient on the banner section, so maybe change the current elements in the banner part and remove the gradient?

**Comment by peppy** [comment]
Could you please explain in more detail so we can attempt to understand the issue?

**Comment by shibou3** [comment]
Sure, this is my userpage in new website ( https://osu.ppy.sh/users/5915257 ). I used the brightest "pink" i found in Photoshop, but, because of this "gradient" (someone on osu forum told me that it was a gradient), the pink became this purple i believe. So i posted it in osu forum and he said that this gradient was because the others elements in the banner (like nickname and stats)  but i feel like i can't edit too much or make a more elaborate banner because this gradient tends to make things darker.

**Comment by peppy** [comment]
Ah. Please work your designs around this. Also keep in mind this banner will be displayed in other places, so making the design specifically for the profile page as you've done is not recommended.
