### ISSUE TITLE
Beatmap search listing missing ability to download a set without video

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2079]
Curent website a small "no vid" link below the download button when viewing maps from the beatmap listing
This is totally missing on the new web, so if someone doesn't want the video they can't download that osz straight from the listing, which makes the listing less convenient for those that rarely download with video.

**Comment by peppy** [comment]
We will likely have a user setting for preference of video/novideo which will apply as a default.

**Comment by notbakaneko** [comment]
is there a reason we’re not just adding this with a different icon?

**Comment by peppy** [comment]
We can do as a temporary thing.

![image](https://user-images.githubusercontent.com/191335/53696168-d8881180-3e07-11e9-958a-ed159d313572.png)

This is how it looks on lazer currently.

**Comment by notbakaneko** [comment]
This is for the card which doesn't have any text on the buttons; the beatmap page itself already has both options

**Comment by peppy** [comment]
ah, right. i guess that's why i proposed putting in settings. adding more buttons on the card seems like not the best idea..
