### ISSUE TITLE
Beatmap leaderboards seem to display tied scores in random order

### ISSUE THREAD

**Issue by MillhioreF** [ppy/osu-web#2082]
![image](https://user-images.githubusercontent.com/4380556/34316934-06e3a3f2-e768-11e7-8ba2-524ad3d47f93.png)
![image](https://user-images.githubusercontent.com/4380556/34316924-e2e92b2a-e767-11e7-96fc-211a3b2fc2c1.png))  

The old website and the ingame leaderboard displays tied scores in the order they were achieved, which makes sense. On the new website they don't seem to be listed in any particular order as far as I can tell.

**Comment by peppy** [comment]
hmm, i thought we already addressed this one. weird.
