### ISSUE TITLE
Reason for Disqualification gets overwritten if a nomination is reset

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2090]
I popped [this map](https://osu.ppy.sh/beatmapsets/703926/discussion) over timing issues. It was previously disqualified for a burai, but the reason underneath the nomination status disappeared after it was popped.
(Maybe the post that did the nomination reset could go where the dq reason was)

**Comment by Xinnoh** [comment]
Was this fixed? Seems like it https://osu.ppy.sh/beatmapsets/723730/discussion#/102252
![screen shot 2018-02-14 at 6 00 37 pm](https://user-images.githubusercontent.com/30382015/36198273-14572d9c-11b1-11e8-9c8f-bed818c8aff6.png)

**Comment by nanaya** [comment]
Indeed.
