### ISSUE TITLE
Show star difficulty in beatmap listing

### ISSUE THREAD

**Issue by 2Cookies2Eat** [ppy/osu-web#2091]
![star](https://user-images.githubusercontent.com/20089738/34325699-734b6da2-e8aa-11e7-8b7d-c85aed9d53bd.png)

I think it is much more practical than clicking the beatmap page just to look at the star difficulty.

**Comment by peppy** [comment]
@arflyte feedback plz

**Comment by EriiYenn** [comment]
**Haiii**

I'll take a look on it and make some previews!
Give me few days to make it perfect, please.

_Best regards,_
**EriiYenn**

**Comment by arflyte** [comment]
![photoshop_2017-12-27_13-29-11](https://user-images.githubusercontent.com/3632750/34370743-047ffa3e-eb0a-11e7-9022-0676ea8ee3fd.png)

Let's go with this for now.
