### ISSUE TITLE
Clicking "Performance" on the User page redirects you to news page, as opposed to some wiki page about performance points

### ISSUE THREAD

**Issue by mangomizer** [ppy/osu-web#2093]
Not 100% sure if this is how I make an issue, but it's pretty self explanatory in the title.

**Comment by peppy** [comment]
I can't find where the clickable "performance" is. Could you please include a screenshot or similar?

**Comment by MillhioreF** [comment]
It's on the old user profile page, doesn't seem to exist on the new one. The news article it links to is too old and doesn't load any more.

**Comment by peppy** [comment]
Not osu-web related but has been resolved!
