### ISSUE TITLE
Searching is unavailable on Mobile

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2098]

**Comment by EriiYenn** [comment]
# Haii ~~

Please provide elaboration of your problem, as here isn't anything :)

Best regards,

**Comment by TPGPL** [comment]
Read the title?

**Comment by EriiYenn** [comment]
You can share Screenshots or anything related, where the problem is etc.

**Comment by MegaApplePi** [comment]
related #1550

**Comment by TPGPL** [comment]
Right

**Comment by EriiYenn** [comment]
## Thanks ^^
