### ISSUE TITLE
Duplicate entry 0 for key primary

### ISSUE THREAD

**Issue by comentarinformal** [ppy/osu-web#21]
I found this when trying to create more than one user (with the first one's ID being 0). Now I had it happen trying to add a second address. It says 'failed loading requested page', and examining the error, it says 
'QueryException in Connection.php line 638:
SQLSTATE[23000]: Integrity constraint violation: Duplicate entry '0' for key 'PRIMARY' (SQL: insert into `osu_store`.`addresses` (`first_name`, `last_name`, `street`, `city`, `state`, `zip`, `country_code`, `phone`, `updated_at`, `created_at`) values (Test2, TEST2NAME, Street Number 2, Holidays, State, Post Code, No, 666333999, 2015-09-01 22:01:51, 2015-09-01 22:01:51))'

This is probably a matter of a misconfigured key in the database created automatically

**Comment by peppy** [comment]
sounds like auto_increment is not working correctly? did you manually insert data or something?

auto_increment should start from 1, not 0

**Comment by comentarinformal** [comment]
I haven't inserted anything manually in the addresses table, I used the Add address button

**Comment by nanaya** [comment]
apparently I managed to remove the auto increment and indexing data from the structure dump

**Comment by peppy** [comment]
Fixed in 404f65e28072a9ab3c39c22ff8a18f077949145d. Please import the database structure again.
