### ISSUE TITLE
Allow option to sort mods by date posted

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2103]
#1953 
This allows users to quickly find new issues which are the most relevant to the map. Small suggestions from months ago are grouped with important suggestions from yesterday. The time at when the issue is posted is often more important than the timestamp of the issue.

If done, sorting by latest reply would also be useful, reopening issues from a while ago should also move them to the top.

**Comment by peppy** [comment]
This needs to be done ASAP
