### ISSUE TITLE
Add filter to show specific modder's posts

### ISSUE THREAD

**Issue by shortthu** [ppy/osu-web#2105]
Basically like the "Mine" filter but by other modder

**Comment by Xinnoh** [comment]
cute mockup
![screen shot 2017-12-26 at 6 04 53 pm](https://user-images.githubusercontent.com/30382015/34354317-6610981e-ea68-11e7-814b-a404e2c32536.jpg)

**Comment by shortthu** [comment]
and a search bar too

**Comment by celerih** [comment]
Bumping this for now, since this would be more useful than ever. Some maps are getting 200+ resolved issues, and when trying to deal with kudosu/upvote abuse sorting by modders would help immensely

**Comment by peppy** [comment]
Tentatively adding to the April milestone. Would like to get this done sooner but we're more interested in getting the new site live first.

**Comment by Okorin** [comment]
bumping this as well, especially for qat and whoever evaluates modders and their abilities for anything, sorting by modder would simplify a lot of things instead of CRTL+F-ing on a page like a madman

**Comment by notbakaneko** [comment]
Are you looking for a filter by the discussion thread starter, or a filter of discussion threads that include the selected user (showing only their replies and the first post)?

**Comment by shortthu** [comment]
I'm looking for a filter by the discussion thread starter.
Something like the old forum post, all timestamps/mods inside a single forum post by modder.

**Comment by Okorin** [comment]
both can be useful under different circumstances, but filtering by thread starter would be the goto thing to use when evaluating someone's mods i think

the other would be useful when looking for how they provide additional arguments to already closed points that they feel strongly about
