### ISSUE TITLE
Change the displayed message on the tab header

### ISSUE THREAD

**Issue by AncuL001** [ppy/osu-web#2108]
![firefox_2017-12-26_18-02-13](https://user-images.githubusercontent.com/16044057/34355339-19dc2a7c-ea67-11e7-95ae-7a5a2fa61338.png)

The left one (old forum) is better than the right one (new forum) imo. it allows people to have an idea about what's inside. this is crucial especially on smaller tab width

**Comment by peppy** [comment]
Agree
