### ISSUE TITLE
Charts don't register score from Silver S/SS rank plays

### ISSUE THREAD

**Issue by Toybickler** [ppy/osu-web#2114]
https://osu.ppy.sh/p/chart

https://i.imgur.com/KR7aKiw.png
https://i.imgur.com/nKfX6Pr.png

**Comment by shortthu** [comment]
this is not on the new site ¯\_(ツ)_/¯

**Comment by Toybickler** [comment]
Let's hope that whoever runs charts has the foresight to use scores from there instead then

**Comment by peppy** [comment]
Fixed

**Comment by Toybickler** [comment]
Scores now register, however if you previously had a score and get a better one, the full points aren't awarded, only the difference between the last one.

https://i.imgur.com/QZvTq5U.jpg Doing this score again awards 25,000 even though I never received the original 32 million.
