### ISSUE TITLE
Beatmap listings should be unloaded at some point

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2117]
Same issue as #2048 but on the beatmap listing

imo having 40+ maps per page like the old system would work better because there's no correlation between maps, whereas forum posts directly affect each other.

**Comment by peppy** [comment]
Pagiantion is not coming back, but unloading is a valid concern.

**Comment by Xinnoh** [comment]
I think this one should be required for live

**Comment by peppy** [comment]
We should either limit number of paginations possible or indeed do some kind of unload/reload magic.

**Comment by notbakaneko** [comment]
I'm going to see if we can use react-virtualized or something for this, while I'm looking at a bunch of stuff related to this page

**Comment by notbakaneko** [comment]
runs fast even with 10000 items loaded ᕕ( ᐛ )ᕗ
