### ISSUE TITLE
Charts not awarding score previously lost from issue #2114 

### ISSUE THREAD

**Issue by Toybickler** [ppy/osu-web#2125]
https://github.com/ppy/osu-web/issues/2114

Reposting my follow-up as new issue:

Silver S/SS scores now register, however if you previously had a score and get a better one, the full points aren't awarded, only the difference between the last one.

https://i.imgur.com/QZvTq5U.jpg Doing this score again awards 25,000 even though the original 32 million were never awarded.

Local scores: https://osu.ppy.sh/ss/9870982

**Comment by peppy** [comment]
yeah, i might fix this if i find time

**Comment by Toybickler** [comment]
I don't want to rush you, but it would be nice if this was fixed before the end of the currently active monthly spotlights (Jan 15).

**Comment by peppy** [comment]
Sorry for the delay. Is it too late to fix this now?

**Comment by Shadowthegod** [comment]
Not yet, The chart is ended but if you can fix the leaderboard I can still change the names on the Monthly Spotlights listing so the true winners will get the reward. Although the Winter Themed Spotlights is more important because that is still on-going. 🤔

**Comment by peppy** [comment]
Is it just those two which were affected?

**Comment by peppy** [comment]
I've run a reprocess script on all recent charts (back to August). Please confirm this is fixed.

**Comment by Shadowthegod** [comment]
The #1 score on this chart is weird https://kurokami.s-ul.eu/9hYRIcDO.png due to having lower total score than ranked one. Not sure if its related to the score submission bug but most likely. I just counted the max score for the first three map in the chart and they gives higher score than 48m.

**Comment by Shadowthegod** [comment]
The leaderboard for November charts seems to be fine tho.

**Comment by peppy** [comment]
I did not adjust total scores, just ranked scores.

**Comment by Shadowthegod** [comment]
Oh, makes sense and its fixed then. Thank you.

**Comment by Toybickler** [comment]
Bless
