### ISSUE TITLE
Disqualifying errors on addHours()

### ISSUE THREAD

**Issue by Naxesss** [ppy/osu-web#2130]
This error pops up as you attempt to disqualify a map, canceling the action, practically making disqualifications impossible. Other QATs get the same error:

![image](https://i.imgur.com/YNq3v7S.png)
![image](https://i.imgur.com/Ln8Kp7W.png)
![image](https://i.imgur.com/uYp1V4B.png)

Tested on https://osu.ppy.sh/beatmapsets/696602/discussion

**Comment by peppy** [comment]
I've hotfixed this so it will work for now, please confirm

**Comment by Naxesss** [comment]
Still getting this
![image](https://i.imgur.com/Ig4CisT.png)
