### ISSUE TITLE
It's not possible to link to other modding discussion posts

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2132]
![image](https://user-images.githubusercontent.com/33286824/34424387-28e371d4-ebf1-11e7-8ba8-f4ab04890cb3.png)

due to the link not registering after the #, it is impossible to link to other discussion posts for any purpose such as reference in a format that it is clickable.

This:
- discourages discussion of related points at different times (can't cross-link two seperate posts)
- ^ the above can lead to if a modder suggests a fix at one time, and someone else wants to suggest something similar for a different time, they can't just simply link to the previous helpful post.
- can make it more difficult to say something like "if you apply a General post from a different difficulty, apply changes to this difficulty too for spread."

**Comment by peppy** [comment]
Hopefully this can be done without a full page reload if you're already at the beatmap set in question, too.
