### ISSUE TITLE
Icon for sorting timeline is distorted

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2137]
I'm pretty sure it didn't look like that before
![screen shot 2017-12-29 at 6 34 54 pm](https://user-images.githubusercontent.com/30382015/34435261-1bc1a260-ecc7-11e7-8ce6-cf806570e6ff.png)

**Comment by notbakaneko** [comment]
that's the right icon

**Comment by peppy** [comment]
It's the best icon we could find for something that looks like a "timeline". Will likely be improved in the future.
