### ISSUE TITLE
New profiles show wrong/combined S/SH and SS/XH score counts

### ISSUE THREAD

**Issue by osuLuna** [ppy/osu-web#2140]
For a few days, user profiles on the new site have been displaying the combined number of all S/SH/SS/XH ranks in their respective S/SS section, resetting the SH/XH counters to zero. SH/XH scores achieved since then get added to the appropriate counters, but existing ranks are still misattributed.
For example, my profile currently lists 6 XH scores (all of which I achieved within the last couple of days) and 1200+ SS scores, when it should be roughly 200 XH and 1000 SS.
Most likely related to this update:
https://github.com/ppy/osu-web/pull/2096
Also likely related to this one, since new SH/XH scores get added properly while old ones are now cached improperly:
https://github.com/ppy/osu-web/pull/2069

**Comment by peppy** [comment]
Interesting. We did run a full reprocess of this but something may have gone wrong along the way. Will look into it further.

**Comment by notbakaneko** [comment]
This should be resolved now, I think?

**Comment by peppy** [comment]
Yep

**Comment by AdrienBoitelle** [comment]
Hello, I'd like to point out that the solution to this problem hasn't been reflected yet to the api ^^
An issue has been opened in the respective repo ; https://github.com/ppy/osu-api/issues/206
