### ISSUE TITLE
Add ability to move a group of discussions to different diffs/sections

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2143]
I just wrote a whole mod in General (all diffs) by accident and had to copy paste each and every individual point over to the correct section. Having a feature to select a group of discussions and move them would save a lot of time and make it less tedious

**Comment by peppy** [comment]
I'm not sure this is a very common thing to require..

**Comment by Xinnoh** [comment]
I don't think this is needed anymore

**Comment by Xinnoh** [comment]
Addressed by #2900 instead
