### ISSUE TITLE
Incorrect tooltip on the supporter length slider on Polish language

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2144]
https://puu.sh/yRBUs/7bad5d6b13.webm

On USD 36 it's `1 year and 4 months`, but later it changes into  just `1 year`

**Comment by TPGPL** [comment]
also there appears nothing from USD16 to USD25

**Comment by TPGPL** [comment]
other languages are fine, so it's probably a problem with the amount of translations

**Comment by nanaya** [comment]
Looks like the translation is incomplete/wrong for pl.

**Comment by nanaya** [comment]
Fixed in the pull request saying doesn't fix this.
