### ISSUE TITLE
Add the ability to embed images into modding posts

### ISSUE THREAD

**Issue by Kibbleru** [ppy/osu-web#2145]
"A picture is worth a thousand words"

Honestly it would be really nice to be able to do embedded images onto the modding posts. I realize that this may cause a lot of clutter on the new web page so here is a solution i propose:

Have some sort of 'image' field whenever you are making a mod post, and all you have to do is put an image link into the field, and when the mod is posted, it would automatically place it somewhere with a spoilerbox so it doesn't clutter the page.

While right now you can surely just link a picture, i think it's rather annoying for people to have to actually click the links to see something like a rhythm example.

**Comment by shortthu** [comment]
I think this will be implemented with markdown since markdown have image embed (like GitHub), so ye this issue is #451 related

**Comment by notbakaneko** [comment]
#9843
