### ISSUE TITLE
Rankings and Friends endpoints don't return CoverUrl for User

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu-web#2161]
`me` returns a `CoverUrl` but users (in `rankings`) and `friends` do not. Thus their backgrounds in client remain black.

**Comment by nekodex** [comment]
Those endpoints return a cover object in the response which should be used instead (at least for the time being)

**Comment by Aergwyn** [comment]
I'll recheck because I'm pretty sure I tried this without much success.

**Comment by nekodex** [comment]
The cover does appear to be missing on the rankings response though, so I'll add that now.
