### ISSUE TITLE
Ability to assign person responsible for certain difficulty - beside the owner - for guest difficulties purposes.

### ISSUE THREAD

**Issue by Nicarim** [ppy/osu-web#2165]
Per title - I think it would be good idea to have owner of the map be able to assign person that can actually moderate only certain difficulty they own (i.e. respond to issues, resolve comments etc. like the original owner)

**Comment by peppy** [comment]
Already heavily discussed and will be done, as a backlog issue.

**Comment by dorothy3242** [comment]
I'd like to bump this. The current system is lackluster and puts it all on the host to resolve every issue. Hosts are perfectly capable of checking gd changes without needing to post "resolved" to every individual mod post on GDs after GDers posted their replies to those posts. The lack of this support as a long standing issue makes modding v2 feel unfinished and lacking in terms of supporting Guest Difficulties which have been a key part in community mapsets for over a decade.

**Comment by Sylurial** [comment]
In the process of looking to make sure I didn't submit a proposal that had already been opened by someone else, I discovered this one.

I'd genuinely appreciate a similar/joint addition where guest difficulties are listed separately from the main mapper in search results, and in certain other places on osu-web, osu-lazer, and wherever else may be relevant (if you're wondering, something like what's in [this image](https://comet.s-ul.eu/2yY7IyGp.png) is what I'm talking about).

Would be a really nice touch.

**Comment by peppy** [comment]
At that point you're not guest mapping. You're removing the concept of "beatmap sets" and just having "difficulties by mappers for a specific track". It's one way we can do things, but requires restructuring the everything ever. The systems, the community, everything. I was looking to do this at one point but the overhead and potential discontent from change is too large, so I do not forsee this happening.

Also this isn't the place to discuss that.

If you're just looking for username to be listed, that's already covered by the proposal and requires no further comment or action.

**Comment by Okorin** [comment]
Just a question regarding #7517 - is this thing able to allow multiple people to be the owner of a difficulty (collabs) or just one?

**Comment by nanaya** [comment]
just one

**Comment by peppy** [comment]
Allowing more than one sounds like a conflict nightmare. The chances of data loss from multiple people submitting to the same difficulty isn't really something I want to consider for now. Let's keep this simple and build on it later if required.

**Comment by ShiiTsuin** [comment]
Sorry if this is the wrong place to ask about #7517 (and related) but:

- How will collaborative difficulties be handled? (1 person assigned as owner of difficulty or multiple?)

- Does this allow difficulty owners to update their difficulties, or still just the mapset host? Got confused by 
>  The submission server update for handling upload permission will need to be merged in first...

- If difficulty owners can update their own difficulties, would a "Various Mappers" option for mapsets consisting mostly/entirely of Guest Difficulties (eg: https://i.imgur.com/A5cwuKj.png) be considered in the near future?

**Comment by peppy** [comment]
Locking thread. Please wait for a public announcement.
