### ISSUE TITLE
Scrolling issue sometimes appears when switching panels due to the text editor being pinned

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2168]
https://streamable.com/yxnuq

**Comment by nanaya** [comment]
can't reproduce.

**Comment by peppy** [comment]
another turbolinks issue maybe?

**Comment by Xinnoh** [comment]
i can't reproduce it either, it's really random when it appears, bug has been around for a while

**Comment by nekodex** [comment]
I'll close this for the time being. If you can reproduce or find any clues, feel free to reopen.

**Comment by Xinnoh** [comment]
i can still do the bug

**Comment by Xinnoh** [comment]
ok figured it out, it only happens when i have the chrome extension grammerly enabled
not sure if this is important to fix anymore

**Comment by peppy** [comment]
I think in a case like this it is probably not our responsibility to fix (unless it has the potential to affect many common extensions)

**Comment by notbakaneko** [comment]
We can't be fixing issues caused by extensions that run their own script hooks and mess about with the page layout.
