### ISSUE TITLE
The 3 map per day limit on nominations should only track qualifications

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2172]
The 3 map limit only applies to qualifying a beatmap, but mv2 tracks all nominations. This needs to be changed so that it only tracks qualifications, as it's preventing BNs that have bubble sets from renominating after a reset

**Comment by Xinnoh** [comment]
In addition, it seems a nominator was unable to pop a map after he reached the 3 nomination cap limit. Nominations and pops need to be independent of each other.

**Comment by Okorin** [comment]
Link examples? helps to outline the issue but i haven't seen this happen myself

**Comment by Xinnoh** [comment]
summary of discussion on bn server
![screen shot 2018-01-05 at 10 29 02 am](https://user-images.githubusercontent.com/30382015/34593760-dc7b2b58-f207-11e7-9281-e091a22683f7.png)
![screen shot 2018-01-05 at 10 29 24 am](https://user-images.githubusercontent.com/30382015/34593763-de89ab4a-f207-11e7-9066-b9d9dfe17c94.png)
![screen shot 2018-01-05 at 10 29 48 am](https://user-images.githubusercontent.com/30382015/34593776-ecbbf15a-f207-11e7-91f1-e75f400a5491.png)

**Comment by Xinnoh** [comment]
fixed with #2246
