### ISSUE TITLE
Nominating BNs not visible after beatmap is ranked on the discussion page

### ISSUE THREAD

**Issue by Mirruuu** [ppy/osu-web#2176]
![image](https://user-images.githubusercontent.com/25852637/34584488-35af4f5e-f19c-11e7-9492-244fa4b2ae8a.png)
Would be convenient to keep the nominating BNs on the page in case people are curious who nominated it. I was asked by byfar and noticed it wasn't there so I had to read the modding discussion to know who did it lol.

Beatmap in question: https://osu.ppy.sh/beatmapsets/705788/discussion

**Comment by peppy** [comment]
agree this should still be visible
