### ISSUE TITLE
Beatmap page doesn't load on new site

### ISSUE THREAD

**Issue by MillhioreF** [ppy/osu-web#2184]
https://osu.ppy.sh/beatmapsets/711286

It does work correctly on the old site, though. The beatmap has some nonstandard timing points and hit objects which may be causing an error in some of the metadata.

**Comment by JBHyperion** [comment]
Asked the mapper what changed in their most recent update that could have caused things to break. Not sure if it's helpful in pinning down the problem, but here is the response I got from them: https://puu.sh/yUMaS/b552be675a.jpg

**Comment by nekodex** [comment]
This doesn't seem to be related to the beatmap itself, it was due to some unrelated changes that were deployed yesterday. Yay coincidental timing 😛
