### ISSUE TITLE
When trying to edit profile while silenced, a blank text box appears

### ISSUE THREAD

**Issue by jacksonisiah** [ppy/osu-web#2186]
Silenced users on the new site can still not post, but when trying to edit their profile, a blank text box appears.
How would one go about fixing this issue? or is there a better place for posting this?

![blanktextbox](https://user-images.githubusercontent.com/34609781/34634873-6f0319ec-f256-11e7-8b92-6db1c5257f89.PNG)

**Comment by LiquidPL** [comment]
Are you sure it's a blank box? I just tested it and I get an `Access denied.` message. Granted it's still kinda vague, but I might be not getting something here.

![image](https://user-images.githubusercontent.com/991831/35126612-7ff25ce2-fcae-11e7-872c-69b9b9426bd3.png)

**Comment by jacksonisiah** [comment]
It was reproducible over the 3 days I tried editing it, but it may have be resolved
