### ISSUE TITLE
Detailed favorites list improvement(?)

### ISSUE THREAD

**Issue by Mirruuu** [ppy/osu-web#2188]
No idea how to title this so just watch this video:
https://puu.sh/yVG9d/00e498542b.mp4

Basically if you hover over the user and try to hover to the next user, it doesn't let you. What would be nicer is if the user's little tooltip were moved upwards or something (or the hitbox (i dont know what its called) made smaller) so you can hover to the next person on the list.

**Comment by nekodex** [comment]
Yeah, that was a known thing when it was written. It definitely could be improved, but was deemed 'good enough' at the time.
