### ISSUE TITLE
Extended Kudosu History only goes back a maximum of 101 posts.

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2189]
On the new website, extended kudosu history can only go back 101 posts / discussions which have received kudosu. 
Unlike v1 modding, there is no alternative of finding mod posts by browsing forum post history. This limitation is currently making it impossible / extremely difficult for those who actively use v2 to count their activity these past 3 months for the BN applications if they have not been manually keeping track of it themselves.

This especially disadvantages the most active modders, where their kudosu history may not even go back a single full month.

**Comment by nanaya** [comment]
The user beatmapset activities page has taken care of this?

**Comment by LiquidPL** [comment]
Perhaps we should make a separate, full-length, paginated kudosu history list, as the user profiles right now can get way too long anyway.

**Comment by komasy** [comment]
I think preparing a separate page like "Kudosu History List" is necessary. Users can view their recieved kudosu information unlimitedly in that page. This problem affects BN applications so it should be resolved quickly. Actually now BN applications of osu! Taiko / osu! Ctb / osu! Mania is open.

**Comment by peppy** [comment]
aka we need to make the user activity page public rather than limited to admin. let's look into that.

**Comment by dorothy3242** [comment]
/users/######/modding is now publicly visible so this isn't important anymore
