### ISSUE TITLE
Make page descriptions more descriptive

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#220]
At the moment it's pretty generic.

![](https://puu.sh/lpMqF/04751e041d.png)

Old site for reference:

![](https://puu.sh/lpMtb/9c4ff9d9b0.png)

**Comment by Lemmmy** [comment]
Adding onto this, opengraph should be used where possible. For example, forum threads could have the covers as an `og:image`, profiles the profile picture etc.

Also, for beatmaps:
`og:title` should be `Artist - Title [Difficulty] (mapped by Mapper)`
`og:description` should contain some information about the map like its length, BPM, stats
`og:image` the map thumbnail
`og:type` could be `music.song` (to include duration)

**Comment by TPGPL** [comment]
Is this one done or what else needs to be done here?

**Comment by peppy** [comment]
I think the main culprits have been resolved. Will close for now.
