### ISSUE TITLE
Forced avatar bounding box on new site

### ISSUE THREAD

**Issue by voli-osu** [ppy/osu-web#2201]
If the width of your avatar is smaller than the height, your avatar will partially have a black box behind it on the new site, that doesn't look very elegant. The old site has a flexible bounding box that scales with the height and width of your avatar, which might be an idea to implement on the new site too.

Comparison (in this case image was 115x128)
![image](https://user-images.githubusercontent.com/35306061/34785523-b5f50412-f631-11e7-93e5-088c4421d44d.png) ![image](https://user-images.githubusercontent.com/35306061/34785550-c5fb6f7c-f631-11e7-8eb1-05eca774e2b6.png)

**Comment by arflyte** [comment]
I personally wouldn't want to encourage non-square avatars to exist on the site as that would give me a design nightmare for the rest of the other pages. I suggest cropping the image to the shortest side of the image for now.

**Comment by peppy** [comment]
Is this how we want to display non-square though? Fit rather than fill?

**Comment by nanaya** [comment]
Apparently it's set to fit because someone's avatar wasn't square and it looked weird with fill. Complete with setting the background color to match that someone's avatar ( ﾟ◡ﾟ)

**Comment by peppy** [comment]
THAT SOMEONE DEFINITELY WASN'T ME, RIGHT.

anyways, i'm happy to fix my avatar if @arflyte comes up with an alternative he prefers. pretty sure at the time it was just "make something that works".

**Comment by nanaya** [comment]
Apparently it's fixed already. But the fit style is never updated... and then forgotten...

**Comment by nanaya** [comment]
Though in case of the thread starter, not sure if better or worse with border and text being clipped instead...

**Comment by nanaya** [comment]
There probably won't be any change in term of square sized avatar being the expected size anytime soon.
