### ISSUE TITLE
Translations Errors

### ISSUE THREAD

**Issue by DolphiiineRe** [ppy/osu-web#2208]
Hello i've found some mistakes on the translations on the latest [website](https://osu.ppy.sh/home).
I'm understand that website is not complete, and that issue will be a "low priority" for the development, But I wanted to say it so that it does not stay that way.

So i've found theses on the French Translations.

When you are on your profile and you want to change some things in your profile, you go to the settings, except that I saw that the title "Account Settings" is correct for the English translation but not for the French translation that marks "Paramètres de compte Compte" which means in English "Account Account Settings".

For now I just noticed that this error except for the modding watchlist page that does not seem to be finished which is totally in English for the French translation.

I'm gonna search all mistakes about French translations.

**Comment by kj415j45** [comment]
That's https://github.com/ppy/osu-web/blob/master/resources/lang/fr/accounts.php#L23
So what would be the correct translation for french? `Paramètres de <strong>Compte</strong>`(I guess)? or other?

If you want, you could edit `resources/lang/fr/*.php` then PR to help translate.

**Comment by DolphiiineRe** [comment]
Yes Paramètres de <strong>Compte</strong> is correct. 

I will start to search some others mistakes tonight ;).

**Comment by nanaya** [comment]
There's also open pull request here (#2187), you may want to check that and maybe add suggestions as well.
