### ISSUE TITLE
There should be a message saying you have to log in to download maps from the web

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2217]
From [this thread](https://www.reddit.com/r/osugame/comments/7ql3tk/osu_should_have_a_message_saying_you_have_to_log/) 
Should really be implemented on the new site design to avoid scaring new players away

**Comment by peppy** [comment]
Yep, we need something like this back again. Probably with the new design @arflyte is working on.

**Comment by nekodex** [comment]
superseded by #2592
