### ISSUE TITLE
Beatmap Listing has a sort by "ranked" instead of "updated" under the "My Maps" section

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2219]
Additionally, when it's set to sort from newest to oldest ranked, all the ranked maps are at the bottom.  Which is. Odd. Pending/graved maps are displayed above the ranked maps in this case, and those are sorted by last updated.... The "My  Maps" section should have ascending/descending sort by last updated, not ranked, like the old website does. Currently this "sort by ranked" filter for "my maps" is functioning similar-ish to updated, just with the ranked maps bunched together.

**Comment by peppy** [comment]
Valid
