### ISSUE TITLE
There's no text box to reply to discussion issues

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#2243]
Safari

![Pasted Image 1.png](https://shipusercontent.com/77d57ae4859e2b3f46c0751e3fa1f9c3/Pasted%20Image%201.png)

Only happens after navigating away and back to the discussions page, so likely turbolinks related.

Possibly look at/fix #2118 while at it?

**Comment by nekodex** [comment]
happens in chrome as well fwiw

**Comment by dorothy3242** [comment]
sounds similar to https://github.com/ppy/osu-web/issues/2021  ?

**Comment by peppy** [comment]
also related to #2088
