### ISSUE TITLE
Beatmap info page isn't redirecting to the correct mode

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2250]
https://streamable.com/9ya9e
Beatmap discussion is redirecting to std mode when there is only a ctb diff
In addition, all of the map issues were condensed to the start of the timeline 

https://osu.ppy.sh/beatmapsets/694107#fruits/1468584

**Comment by nekodex** [comment]
There's a deleted beatmap in this beatmap set, which due to the changes from #2205 is being shown initially... yeah, shouldn't be doing that.

**Comment by Xinnoh** [comment]
![screen shot 2018-01-19 at 3 27 11 pm](https://user-images.githubusercontent.com/30382015/35139265-485edba0-fd2d-11e7-8500-9cd68a869af2.png)
They should be automatically deleted if there are no comments, these diffs are from me messing with diff names
https://osu.ppy.sh/beatmapsets/700945/discussion

**Comment by peppy** [comment]
Yeah, let's hide any difficulties with no comments on top of fixing this.

**Comment by nanaya** [comment]
Fixed by #2253.
