### ISSUE TITLE
Issues for deleted diffs can't be resolved

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2252]
Reply is disabled, hence resolve is disabled
Deleted diffs should have a warning, rather than just disabling commenting completely.
![screen shot 2018-01-19 at 6 00 00 pm](https://user-images.githubusercontent.com/30382015/35145394-9eb176d8-fd42-11e7-83a5-1946bcb4aeff.png)

**Comment by nanaya** [comment]
It doesn't make sense to resolve issue in deleted diff. If it causes the map to be un-nominatable then there's bug in nomination check.

**Comment by Xinnoh** [comment]
Most of the time, deleted difficulties are the same map but with bss bugs or reuploads, Eg. above
If someone wants to disregard some mods, they can just delete and reupload a diff to ignore them.

**Comment by nanaya** [comment]
Shouldn't the diff be merged/fixed then if they are the same? Also no one but uploader and moderators can see discussions on deleted diffs at the moment.

**Comment by Xinnoh** [comment]
i'm neither of those 🤔

**Comment by nanaya** [comment]
Or qat

**Comment by peppy** [comment]
There's code in place now which does merge such difficulties, but it was only added very recently. If you'd like me to fix up a map which has bugged deleted difficulties, please email me with details.
