### ISSUE TITLE
WIki search post post preview shouldnt include header names nor image tooltips

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2260]

**Comment by nanaya** [comment]
Is it still happening? Any examples?

**Comment by TPGPL** [comment]
Search for FAQ

**Comment by nanaya** [comment]
This?

![](https://s.myconan.net/2018-01/firefox_2018-01-22_19-40-39.png)

**Comment by nanaya** [comment]
Do you mean the headers should not be shown in preview?

**Comment by TPGPL** [comment]
Yes, that one.
At least i dont thinl they should have the same format as normal text

**Comment by peppy** [comment]
`&quot;` too

**Comment by TPGPL** [comment]
Also there should be a solution to previewing bullet lists

**Comment by notbakaneko** [comment]
Should no longer be indexed as of #4173
