### ISSUE TITLE
Allow searching based on redirect keywords

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2261]

**Comment by nanaya** [comment]
What redirect?

**Comment by TPGPL** [comment]
The redirect.yaml file in the osu!wiki

**Comment by nanaya** [comment]
What with that?

**Comment by TPGPL** [comment]
The articles should be searched if you enter the name of the redirect

e.g. OWC2017 would give match to the osu! World Cup 2017 article

**Comment by nanaya** [comment]
Not sure if useful...

**Comment by peppy** [comment]
I think this is potentially useful as it's one of the only ways we can add "tags" to articles for common search terms. Would be nice if this could be done in markdown front matter instead..
