### ISSUE TITLE
Images should line up on user profiles

### ISSUE THREAD

**Issue by jacksonisiah** [ppy/osu-web#2269]
Profile banner (this was a 1920x1080 image) doesn't line up correctly with the top banner.

![2018-01-23](https://user-images.githubusercontent.com/34609781/35262197-a33cee34-ffe1-11e7-8ca2-21cdba8fe2ba.png)

**Comment by jacksonisiah** [comment]
using a 2000 x 700 image doesn't line up either, which is the recommended resolution

**Comment by nanaya** [comment]
They're never designed to be aligned. The size are also different on less than maximum width.

**Comment by jacksonisiah** [comment]
I guess this is unnecessary then.
