### ISSUE TITLE
ability to lock discussions 

### ISSUE THREAD

**Issue by Okorin** [ppy/osu-web#2273]
for moderation purposes it should be possible to mark a map as not suitable for nomination permanently (so just like the way nuke icons were handled) and lock a discussion thread from receiving further comments if it's getting cluttered up with spam by users with ill intent

**Comment by JBHyperion** [comment]
Some notification to users on the beatmap listing (similar to what we currently have for disqualification reasons) might also be worth considering, e.g.

_"This beatmap has been judged unsuitable for ranking and will require major revisions before being considered for nomination:"_ <reason>

Whilst it's never a great idea to go into too much detail about moderation issues, some explanation usually defuses the issue slightly, or people start speculating and it draws more attention.

**Comment by Kibbleru** [comment]
i honestly think the design of moddingv2 itself makes it harder to shitpost in general though.

but you're right i don't think the ability to lock a thread should be removed.

**Comment by Xinnoh** [comment]
There are many reasons besides shitposting that a thread would be locked. Mapper may have given up and doesn't want more feedback [eg](https://osu.ppy.sh/forum/t/628282/start=105) or someone is being brigaded and it needs to stop

**Comment by Okorin** [comment]
Bumping with [this thread](https://osu.ppy.sh/beatmapsets/935111/discussion/-/generalAll) as a reason why we need this ability in order to actually moderate modding discussions properly

this whole thing escalated into a proper shitshow and there's nothing we could do to prevent people from just making noise for shits and giggles .__.

**Comment by Okorin** [comment]
this is implemented
