### ISSUE TITLE
Disqualified .... ago ([object Object]). (Message when first nomination is reset)

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2282]
![image](https://user-images.githubusercontent.com/33286824/35401157-be98b820-01c6-11e8-8ef5-14fc9122c9bc.png)
![image](https://user-images.githubusercontent.com/33286824/35401166-c8e1dec4-01c6-11e8-8e61-729d9268be3e.png)

https://osu.ppy.sh/beatmapsets/717058/discussion
this happened after a map with 1 nomination was reset to 0, triggered by a BN posting a problem. The set in question was never qualified to begin with.

**Comment by peppy** [comment]
@nanaya can this please be fixed
