### ISSUE TITLE
Timestamps don't update when editing message

### ISSUE THREAD

**Issue by Pachiru** [ppy/osu-web#2284]
If you put a specific timestamp in the message, and then you change it, the indicator on the timeline will not update itself, and it will stay at the previous timestamp.

![mv2_li](https://user-images.githubusercontent.com/34794019/35434971-4ec3bd4c-0289-11e8-8ff6-331fab5a14e9.jpg)

**Comment by shortthu** [comment]
duplicate #1943 xd
