### ISSUE TITLE
Multiplayer history shouldn't scroll on minor events

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#2291]
Every time a user joins/leaves a multiplayer room, this history scrolls to the bottom.

Either this should only happen on major events (new matches) or the autoscroll should be disabled when the user had performed a scroll upwards (maybe based on proximity to the end of the page).

**Comment by Aergwyn** [comment]
This still happens a lot. If I want to check the scores of the latest match and I'm not entirely scrolled down (but close) it constantly goes to the bottom. It's pretty obnoxious.
Can it not scroll at all or have a hint like e.g. in twitch chat displaying that you're not scrolled down and/or there are new events?
