### ISSUE TITLE
Highlight friends on map leaderboards

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2321]
The old website highlights users you have friended when viewing a map page's leaderboard section, drawing attention to them.
![image](https://user-images.githubusercontent.com/33286824/35787157-1cc8c080-09fa-11e8-9085-e0e39446086c.png)

The new website does not
![image](https://user-images.githubusercontent.com/33286824/35787167-3a3f35a4-09fa-11e8-9304-06cbb4531804.png)

**Comment by peppy** [comment]
@arflyte need design for this one
