### ISSUE TITLE
The step numbers on the download page aren't vertically centered 

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2325]
Happens on `at least` Firefox 58.0.1 on 100% page size

![](https://puu.sh/zhSla/c5ed412131.png)

**Comment by Joehuu** [comment]
Also happens on chrome at other zooms on the same page. And happens in other places.
The supporter tag is not aligned(horizontally).
![usercard](https://user-images.githubusercontent.com/35318437/37426956-1813332e-2785-11e8-966d-5acfbe6445e3.png)
