### ISSUE TITLE
Scoreboard lagging when scrolling horizontally on mobile

### ISSUE THREAD

**Issue by Phippe** [ppy/osu-web#2327]
Occurs on an older device (iPhone 5). Also when scrolling vertically, the scores aren't already loaded but appear during scrolling (maybe this is also causing the lag with horizontal scrolling?).

**Comment by peppy** [comment]
Sorry but I don't think we can support iphone 5 as far as performance goes. That's a very old device.

**Comment by Phippe** [comment]
Please don't ignore this completely.

In the meantime I could test the scoreboard's performance on some other devices:
iPhone 6: only slightly better than iPhone 5, still pretty bad
iPhone 8: vertical scrolling ok, horizontal scrolling with very subtle lags
Galaxy Note 4: pretty ok
Huawei Nova: ok

Maybe this more of an iOS problem, I don't know. You can recreate these lags with Chrome dev tools, click on the phone icon, then online -> mid-tier mobile / low-tier mobile (you have to drag your cursor as if you're on mobile so experience the lags).

I wouldn't see a problem with an iPhone 5 performing poorly on graphic intensive games, but this is a website. Unless there are some fancy animations or things like that, there's no reason for an old device to lag while trying to display a scoreboard.

I don't expect a miracle, but please make the website perform a little better on older devices.
