### ISSUE TITLE
Unable to reveal box/spoilerbox's content on forum post preview

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2333]
![](https://puu.sh/ziG7t/db8e6bf575.jpg)
they just dont work

**Comment by LiquidPL** [comment]
![image](https://user-images.githubusercontent.com/991831/35928420-6970fb5c-0c2d-11e8-9e88-61420ff7c631.png)

the post preview seems to be covered by an overlay that prevents interaction, but I'm assuming it's there for a reason 🤔
