### ISSUE TITLE
[BBCode] Missing list types on the forum

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2335]
On the old forum there are 6 types of lists: `bulleted`, `numbered`, `lettered (lowercased`), `lettered (upper-cased)`, `roman numeral (lowercased)` and `roman numeral (upper-cased)`. For some reason on the new forum there are only 2 types of them: `bulleted` and `numbered`. 

maybe intentional?

**Comment by peppy** [comment]
probably intentional. not sure we need all those other types.

**Comment by TPGPL** [comment]
at least those missing types should be converted into numbered list, not bulleted
