### ISSUE TITLE
The discussion button should redirect to the new forum for some beatmaps, not the old forum 

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2347]
Currently it does.

maybe intentional?

**Comment by jacksonisiah** [comment]
is only for some? like specifics?

**Comment by TPGPL** [comment]
those which don't use the new modding system

**Comment by jacksonisiah** [comment]
somewhat seems intentional to me, but should redirect when the new site is implemented (possibly)

**Comment by dorothy3242** [comment]
that'd be a bad idea, the new forum doesn't support timestamps in beatmap forum threads like the current one does.

**Comment by peppy** [comment]
It's intentional that it redirects to the old site, as we are not reimplementing the modding features.

**Comment by TPGPL** [comment]
but what will happen when you get rid of the old forum

**Comment by peppy** [comment]
Any remaining beatmaps will be migrated to modding discussions. Hopefully they will all be ranked or graveyarded by this point in time.
