### ISSUE TITLE
Suggestions cannot be deleted

### ISSUE THREAD

**Issue by JBHyperion** [ppy/osu-web#2353]
A modder here: https://osu.ppy.sh/beatmapsets/725418/discussion - made some suggestions for the osu!taiko difficulty but accidentally posted them on the osu! difficulty. He then posted them on the osu!taiko difficulty as well stating that he couldn't delete the originals.

Myself and a couple of other QATs have tried to delete the posts, but to no avail. The "Are you sure you wish to delete?" notification comes up... but nothing happens, when trying to delete from either difficulty.

I created a note on one of my own mapsets and tried to delete that, but got the same result: https://osu.ppy.sh/beatmapsets/693123/discussion#/101311

Don't really know any more details than that unfortunately, but I'm about to go to bed and didn't want to forget this.

**Comment by dorothy3242** [comment]
![image](https://user-images.githubusercontent.com/33286824/36081134-050af0de-0f69-11e8-83a3-fb3be7d6ec29.png)
apparently this has been happening with praises as well
I can't delete notes on my own mapsets either, and now just tested and can't delete problem posts either.

so: nothing is deleteable at the moment. for some reason.

**Comment by peppy** [comment]
Looks like this may be a regression?
