### ISSUE TITLE
Increase number of forum threads shown per page

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2358]
15 is quite a lot lower than the old forum's 50 threads per page.  While this is in part because the new forum's thread listing is less compact and would make scrolling through 50 per page more cumbersome, 15 is _very_ low and requires a lot more of zzz click next page.. zzzz click next page... zzzz click next page, instead of being able to more quickly scroll through many thread topics at a glance.

I think 30 would be a good number o:

**Comment by peppy** [comment]
@arflyte ping for opinion

**Comment by arflyte** [comment]
Yeah sure, let's go with 30.
