### ISSUE TITLE
Implement a sitemap generator for the wiki

### ISSUE THREAD

**Issue by LiquidPL** [ppy/osu-web#2363]
After discussing with the #osu-wiki guys, a decision was made that we should implement some kind of a sitemap for the wiki (kind of like [this](https://osu.ppy.sh/wiki/Index), but automatically generated on the web side whenever there's an update).

relevant to ppy/osu-wiki#1041, ppy/osu-wiki#1042

**Comment by TPGPL** [comment]
![](https://cdn.discordapp.com/attachments/218677502141399041/316819536148037642/unknown.png)

there was this design somewhere but no idea if it's relevant anymore

**Comment by sr229** [comment]
@LiquidPL I found a NPM module that would make the sitemap dynamically but I need to investigate if I can print it out in MD

**Comment by sr229** [comment]
webhook was made but were having a hard time on the git tree at the moment

Would update if we're done. At the moment, initial layout is write to osu-wiki when a new push is made.

**Comment by sr229** [comment]
Completed Work as a Webhook that writes to `osu-wiki` when a Push is done.

**Comment by nanaya** [comment]
Added in #5652.
