### ISSUE TITLE
Implement Main Page for osu!wiki

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2364]
![](https://cdn.discordapp.com/attachments/218677502141399041/316819536148037642/unknown.png)

there was this design somewhere but no idea if it's relevant anymore

**Comment by arflyte** [comment]
This is indeed the latest design. Future design updates will just simply add image header to each box.

**Comment by TPGPL** [comment]
Is there a reason to keep the contents template, it looks the same as the things above

**Comment by LiquidPL** [comment]
Also should the main page be included in search results normally?

**Comment by peppy** [comment]
May be best to exclude from search results. As for the language picker, just follow whatever other wiki pages display IMO.

**Comment by LiquidPL** [comment]
Do we have any infrastructure in here that allows to make autocomplete suggestions for searches (like in the design)? I've seen something for that in elastic docs, but I'm not sure if it's been implemented already somewhere (and also it'll probably require some reindexing).

**Comment by peppy** [comment]
Check out existing search page, which is basically already doing autocomplete. There’s nothing special, you would just do a wildcard query.

**Comment by LiquidPL** [comment]
So what I wanted to do is take the current search page (as in https://osu.ppy.sh/home/search), and add JSON output support to it, so I could then use it from react. Do you see it having use in any other places (probably lazer), or would it be fine to just add a single route specifically for wiki?
