### ISSUE TITLE
"Recent" section of the profile is missing the "Show me more" option

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2365]
![image](https://user-images.githubusercontent.com/33286824/36172826-183760bc-10d5-11e8-829e-10c8d388c3f6.png)
old profile displays 4 by default with a show me more option, and 15 when you click the "show me more" link.

![image](https://user-images.githubusercontent.com/33286824/36172876-3cd6976c-10d5-11e8-8026-633c012458ff.png)
 new profiles display 5 by default, but does not have any "show me more" option. 5 is a pretty limited number of items if there is no way to see more than that :/

**Comment by dorothy3242** [comment]
Uhh, this was added, but now it's gone again?

**Comment by peppy** [comment]
Opening as potential regression. Needs further investigation.
