### ISSUE TITLE
Changelog should have a support promo

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#2367]
```
{if !$isSupporter}
<h1>Love this update?</h1>

<div class='paddingboth'>
	<big>Support further development of osu! and <strong><a href='/p/support'>become a supporter</a></strong> today! Not only will you help speed development, but you will also get some extra features and customisations!</big>
</div>
{/if}
```

something similar to this.

**Comment by LiquidPL** [comment]
only under specific build pages or on the main one (`/home/changelog`) too?

**Comment by peppy** [comment]
It should only be on build pages, similar to the old site.

Basically when someone arrives after updating their osu!, it's giving them a little hint to support the game if they see changes they enjoy.
