### ISSUE TITLE
Add ability to save default profile game mode

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#2368]
When changing the game mode in one's own profile, it should store this as the last visited mode (`osu_playmode` in `phpbb_users`).

**Comment by nanaya** [comment]
I find this confusing on the old site because there's no indication switching the tab on own profile switches the default mode.

**Comment by peppy** [comment]
flyte is working up a design for this, i believe.

**Comment by arflyte** [comment]
![7bfe3a4754](https://user-images.githubusercontent.com/3632750/36299730-cd70c1f8-1341-11e8-9fb1-96b545b9b45b.png)

Star determines player's default. Button appears at non default mode.
