### ISSUE TITLE
New profiles don't have level progression bar

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2372]
old website has this
![image](https://user-images.githubusercontent.com/33286824/36187742-4dce5baa-1115-11e8-8c02-377bf77b0016.png)
new website only shows the current level, and not the progress within it
![image](https://user-images.githubusercontent.com/33286824/36187761-58376136-1115-11e8-8f1d-cdd662c9a73a.png)

**Comment by peppy** [comment]
@arflyte advise please. probably a thin line display somewhere in that boxed area?

**Comment by arflyte** [comment]
![730531a580](https://user-images.githubusercontent.com/3632750/36191718-ca33aefc-11a1-11e8-96ea-0020d8fa1901.png)

Hovering the level badge will reveal their progress in the total playtime area.

**Comment by Joehuu** [comment]
are you replacing this line?
![](https://puu.sh/zq9H5/062dc1559a.png)
![](https://puu.sh/zq9Hp/43296eea88.png)
