### ISSUE TITLE
uppercase letters on difficulties name appear bigger than it should

### ISSUE THREAD

**Issue by Rivals7** [ppy/osu-web#2377]
https://puu.sh/zno4M/3931282d2a.jpg
http://puu.sh/znoc1/4d28967a4f.jpg
http://puu.sh/znocR/919d4f6566.jpg

quality of aesthetics could be improved
screenshot sample https://osu.ppy.sh/beatmapsets/533472#mania/1130160

**Comment by peppy** [comment]
What browser/OS?

**Comment by nanaya** [comment]
This is a problem of combination of the font, font size, the content, and operating system/rendering engine and not limited to the mentioned specific section.

**Comment by Rivals7** [comment]
@peppy i'm using latest firefox version on windows 8.1

**Comment by dorothy3242** [comment]
I'm seeing the exact same thing as those screenshots, and I'm using the latest version of standard google chrome on windows 10.

**Comment by peppy** [comment]
Last I checked it's just an issue with the Exo font being a bit crap. Not really fixable without switching fonts.

**Comment by TPGPL** [comment]
Seems the same on Mobile Chrome (Android 7.0)

**Comment by peppy** [comment]
Not really fixable without switching fonts.
