### ISSUE TITLE
Revived maps with 0 mods aren't automatically changing to v2

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2378]
I thought this was supposed to be a thing? It hasn't been happening
https://osu.ppy.sh/beatmapsets/661371#osu/1400205
https://osu.ppy.sh/beatmapsets/664182#osu/1405715
both of these sets when I revived them I had to ask Ephemeral to enable the modding discussion panels manually, despite the fact that they both had 0 posts in their forum threads.

Example number 3 which I revived specifically to prove this issue:
https://osu.ppy.sh/beatmapsets/587726#osu/1244445

?_?

**Comment by peppy** [comment]
It's a manual procedure. I'll look into your maps.

**Comment by peppy** [comment]
I've batch changed all graveyarded maps.
