### ISSUE TITLE
Genre/language isn't visible on the beatmap information page or panel

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2383]
Despite the fact that genre/language is still usable in the beatmap listing search. Makes it impossible to see a map, remember the genre, and use the genre as a search term to re-find the map's listing later.

**Comment by peppy** [comment]
@arflyte this needs to be added on the beatmap information page at very least.

**Comment by arflyte** [comment]
![614dbb417e](https://user-images.githubusercontent.com/3632750/36193779-87c18e46-11aa-11e8-8a96-ac6871b28c11.png)

Add the section under Tags. Increase the height of the overall box if needed.

**Comment by arflyte** [comment]
![e78c4f0030](https://user-images.githubusercontent.com/3632750/36194080-b72f0680-11ab-11e8-97aa-27b5e5c6a2fa.png)

Changed my mind. Let's go with this.
