### ISSUE TITLE
Infringements (aka silences) of users are not yet displayed

### ISSUE THREAD

**Issue by Nath789** [ppy/osu-web#2384]
Most likely we (especially the teams) need this before the old site disappears to know if the users have records of misbehaving.

I don't think there is anything else to add here.

**Comment by JBHyperion** [comment]
Currently when a user receives a silence and they try to type in chat, a message pops up telling them to "check their profile for more information" or something along those lines.

So that people aren't left asking "why was I silenced" to every available moderator, regular users would need this just as much as we would.

**Comment by TPGPL** [comment]
#1531 duplicate?

**Comment by arflyte** [comment]
![5fac6ece29](https://user-images.githubusercontent.com/3632750/36293816-7e4a7ab4-131f-11e8-9b41-7c999f5a532a.png)

![3da6b1bafb](https://user-images.githubusercontent.com/3632750/36293805-65f7992e-131f-11e8-8f8d-d3c2d7e12de8.png)

Here are the designs for Account Standing stuffs.

**Comment by nekodex** [comment]
BTW normal users should only be able to see silences `ban_status = 2` and not who performed the action.

**Comment by LiquidPL** [comment]
this should always be at the bottom, like the old website, and separate from the rearrangable sections of the profile, right?

**Comment by peppy** [comment]
It should always be the last section. It should not be user arrangeable.

**Comment by LiquidPL** [comment]
Can I also have a list of all possible `ban_status`es that could be shown?

**Comment by LiquidPL** [comment]
can i have a psd for this?

**Comment by arflyte** [comment]
[osu!next - Profile Page, Modules C.zip](https://github.com/ppy/osu-web/files/1747310/osu.next.-.Profile.Page.Modules.C.zip)

**Comment by LiquidPL** [comment]
wait actually do we need the 'restricted account' thingy if there's this:

![image](https://user-images.githubusercontent.com/991831/36729147-7339e626-1bc3-11e8-9f09-213b8bb0b445.png)

or is it for the mods/admins?

**Comment by LiquidPL** [comment]
![image](https://user-images.githubusercontent.com/991831/36729873-e471dffe-1bc5-11e8-87c1-0823039e4c9f.png)
and this

**Comment by arflyte** [comment]
i'll leave this up to the rest to decide. if the current one feels extreme and if that's not the intention, then we can use the simpler yellow bar.

**Comment by nekodex** [comment]
We can't really just have a simple yellow bar because it gives no info to the restricted user as to what 'restricted' even means (in the case of false positives, etc).

Probably fine to just leave it as is for now unless you had a redesign in mind?

**Comment by arflyte** [comment]
Let's keep the current design then. I have no new design for it for now.
