### ISSUE TITLE
Call the "news" tab on the homepage "main" instead.

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2393]
![image](https://user-images.githubusercontent.com/33286824/36223199-a42c878e-1191-11e8-90dc-4d4533e64431.png)

there's more on this page than just the news, and it can be confusing when there's another totally different page for browsing news posts. It took me a while to realize that this "news" tab and the "news" page that you can get to through the top drop down menu are _two different pages_

**Comment by peppy** [comment]
It can't be called home, since it is a tab inside home.

**Comment by dorothy3242** [comment]
"main" ?

**Comment by peppy** [comment]
`Main` works better than `news`, definitely.

**Comment by nekodex** [comment]
`Main` is too generic: _"oh you can view the latest news on the main page"_ - _"the what page?"_

I'd suggest `Welcome` or `Dashboard` or something more descriptive of what the page actually does.

**Comment by arflyte** [comment]
Let's call it `Dashboard`.
