### ISSUE TITLE
Allow for clicking the "news" heading on the homepage to take you directly to the news page

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2394]
Related to https://github.com/ppy/osu-web/issues/2393

Clicking here 
![image](https://user-images.githubusercontent.com/33286824/36223252-d38d5300-1191-11e8-9d04-23d85d18d68b.png) should be able to take you to the https://osu.ppy.sh/home/news page.

The combined result of the problems from this issue and the linked one is that it took me quite a while to figure out how to browse past news posts, as there is no clear link to do so on the homepage which is labelled "news"... Clicking the news heading to get there is how it functions on the old website too.

**Comment by peppy** [comment]
No reason this shouldn't be a thing.

**Comment by nekodex** [comment]
While there definitely should be a link to the news archives added, I don't think making the section header link there is the right approach - feels wrong and inconsistent with the rest of the site.

IMO better to add a 'view more news' link/button or something under the news stories (logically where your eyes would end up while scanning the news posts looking for older stuff)

ping @arflyte

_(also as a sidenote, `new approved` and `popular beatmaps` could probably do with links to view more too)_

**Comment by arflyte** [comment]
![osu next - user index](https://user-images.githubusercontent.com/3632750/36237989-e86baa36-1242-11e8-952b-f335cb4aeb87.png)

Here's the updated design for the home page. To see more news, just click the see more news button. Same goes to new `new approved` and `popular beatmaps`.
