### ISSUE TITLE
Beatmap management panel missing on new website

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2395]
![image](https://user-images.githubusercontent.com/33286824/36223744-5ccdfdb2-1193-11e8-8de5-f28bdc30a50a.png)
this one
was brought up in the now-closed https://github.com/ppy/osu-web/issues/1717 as well, but I don't think it'd make much sense to allow for QATs to access the old website as a band-aid option for this instead of implementing a similar panel on the new website if you're trying to move everything to the new website in earnest.

**Comment by peppy** [comment]
Admin features are out of scope for the time being. They will be added in a second pass.

**Comment by dorothy3242** [comment]
is it time for the second pass yet, accessing this panel by manually editing urls to access old pages now that the site switcher is gone is quite a hassle

related: https://github.com/ppy/osu-web/issues/3682

**Comment by peppy** [comment]
Still not sure where this fits. Probably a new admin portal page as a temporary measure, or integrated into the beatmap discussion page header area.

**Comment by dorothy3242** [comment]
I think a linked page for NAT/GMT/higher combining these management features with the old websites "manage" page would be ideal. It could be linked via a gear icon on the map's information page.
This possible page would be excluding genre/language which should be separately implemented following https://github.com/ppy/osu-web/issues/3682 

The majority of the management panel features, while necessary, are not used on a daily basis so I personally don't think containing them on the information or discussion page is required.

**Comment by peppy** [comment]
Dropping this in milestone, but it will likely be completed via https://github.com/ppy/osu-web/issues/3682#issuecomment-576368583.

**Comment by nanaya** [comment]
As offset and tags can be edited through client (and display title isn't relevant in new site?), closing this and tracking #3682 instead.

**Comment by dorothy3242** [comment]
Online tags, offset helps compensate for cases where maps get ranked with lackluster settings without requiring unranking them (rare but happens)

display title changes the in-game title and artist text that displays at the start of a beatmap, so it has nothing to do with the website besides being changed using it

**Comment by peppy** [comment]
we're going to move offset setting elsewhere and remove display title changing ability, going forward.
