### ISSUE TITLE
Allow for clicking country flag on "Quick Profile" pop-up to take you to country rankings

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2396]
![image](https://user-images.githubusercontent.com/33286824/36224072-6ff4f4a8-1194-11e8-9983-4a01158211cb.png)
this flag
Despite sharing an appearance and hover with the one you can see on the profile, the one that appears here is not clickable.

**Comment by peppy** [comment]
Should also be clickable and link to country rankings.
