### ISSUE TITLE
Userpage needs tooltips for settings-page configurable information

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2398]
(edit: i didn't realize hitting enter on github would automatically make a post, my bad)
![image](https://user-images.githubusercontent.com/33286824/36224321-3cdf39b0-1195-11e8-8b1d-626309add3dc.png)
old userpage had tooltips for these items so you could know what the symbols _mean_
![image](https://user-images.githubusercontent.com/33286824/36224342-4e262f44-1195-11e8-9f41-968601133292.png)
The new page doesn't . What on earth does the heart mean?  The suitcase? no idea, there's nothing to easily tell you what they mean on the new website.

**Comment by peppy** [comment]
Required.
