### ISSUE TITLE
Textarea is very large in mobile browsers.

### ISSUE THREAD

**Issue by ErunamoJAZZ** [ppy/osu-web#241]
Hello, I think textarea for new post looks very long in small screens.

![tmp_5434-screenshot_2015-11-28-13-06-291755891909](https://cloud.githubusercontent.com/assets/421398/11453283/f40fee2c-95d2-11e5-86ae-7fe861e3df15.png)

Thanks n.n

**Comment by nanaya** [comment]
I believe this has been fixed by having a fullscreen button and smaller textbox
