### ISSUE TITLE
Settings page doesn't really accurately preview signatures

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2413]
forums:
![image](https://user-images.githubusercontent.com/33286824/36270411-a694a232-1249-11e8-9a2c-a72effffd71b.png)

vs settings:
![image](https://user-images.githubusercontent.com/33286824/36270475-ca677aae-1249-11e8-9f77-1ada25d88524.png)

the difference of sizes between the actual forums and the setting page can make signatures harder to figure out because the settings page does not accurately reflect how it'd appear in forums 🤷

**Comment by nanaya** [comment]
It's not always the same width though. And I forgot to limit the height.

![](https://s.myconan.net/2018-02/firefox_2018-02-16_02-49-13.png)
