### ISSUE TITLE
Weighted pp% missing from best performance area

### ISSUE THREAD

**Issue by jacksonisiah** [ppy/osu-web#2419]
![capture](https://user-images.githubusercontent.com/34609781/36286928-e6de5820-127f-11e8-84b2-13a732c0d9f0.PNG)

vs. 

![capture2](https://user-images.githubusercontent.com/34609781/36286937-ef5b8cca-127f-11e8-8eb7-c831676fd2d1.PNG)

**Comment by Joehuu** [comment]
already did #1253

**Comment by jacksonisiah** [comment]
weighted pp% isn't there though.

**Comment by peppy** [comment]
did you try hovering the pp value?

**Comment by kj415j45** [comment]
It just hidden. When you hover on pp, it will show details

**Comment by jacksonisiah** [comment]
oh I see now.
