### ISSUE TITLE
logging in by submitting a post doesn't dismiss the login dialog

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#242]
If you post as guest and complete login by clicking the "Post" button, the login dialog will not disappear, even though your new post successfully appears in the background.

![](https://puu.sh/lCU6P/aa2ba502cb.png)

**Comment by nanaya** [comment]
oh, I see. Since the other post-login actions completely change page whereas this one is just modifying the page, I didn't realize the login button doesn't close the modal (and then the avatar in reply box is wrong as well).
