### ISSUE TITLE
Change player name when hovering near it on user page

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2421]
![](https://puu.sh/zoEtv/0dbb5e8282.png)
![](https://puu.sh/zoEh2/0638f100f8.png)

**Comment by peppy** [comment]
@arflyte how should we show this going forward? it links to the store page to change your username.

**Comment by arflyte** [comment]
![d4f0581622](https://user-images.githubusercontent.com/3632750/36294653-8c8b2ba4-1325-11e8-9dad-4ce2a30c7c0e.png)

**Comment by peppy** [comment]
just on hover, right?

**Comment by arflyte** [comment]
Yeah, only on hover.

**Comment by Joehuu** [comment]
This should be required, so users know if they can even change their username b/c it is really hard to find on the store or they don't know it's on the store in the first place.
