### ISSUE TITLE
Show nomination/hype counters on user profile maps

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2427]
on beatmap search, you can see nomination and hype counts for pending maps
![image](https://user-images.githubusercontent.com/33286824/36292251-3e72650e-129e-11e8-9e56-321743a08db3.png)
I think it would be _realy nice_ if this could be displayed in the User Profile for pending and graveyarded maps too
![image](https://user-images.githubusercontent.com/33286824/36292255-4edf9290-129e-11e8-8757-93550f5273f4.png)

Similar to how old profiles would show SP count

**Comment by peppy** [comment]
It definitely should be.

**Comment by dorothy3242** [comment]
Closing because this issue has been resolved
