### ISSUE TITLE
A and B ranks are too visually similar

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2429]
It's quite difficult to tell which users got an A or B rank at a glance, even harder with visual impairment.
![blur 2](https://user-images.githubusercontent.com/30382015/36292421-b4a04f52-130c-11e8-9f74-8aad7c2d1dbb.jpg)
The old site is really easy to tell what rank was achieved at a glance, despite that the icons are smaller.
![blur 3](https://user-images.githubusercontent.com/30382015/36292427-b796f9ae-130c-11e8-8c63-68cae4994257.jpg)

Giving the A and B rank more distinct colours from each other, or having a different design would make it much easier to tell them apart.

**Comment by peppy** [comment]
@arflyte may be useful to take into account when redesigning.

**Comment by arflyte** [comment]
That score grade design was not designed for the new scoring chart, as it's not as effective when it's tiny. Score grades has a new design that should fix the problem but it has not been finalised yet.

**Comment by peppy** [comment]
Closing in favour of #3945.
