### ISSUE TITLE
Funky grammar in remaining hype message

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2434]
![image](https://user-images.githubusercontent.com/33286824/36294267-8f390682-12ad-11e8-98cb-9e67af4f8923.png)
"You'll get another hype at 4 days from now"->"You'll get another hype 4 days from now"
the "at" in there looks terribly wrong

**Comment by jacksonisiah** [comment]
could also be: `You'll get another hype in 4 days from now`

**Comment by peppy** [comment]
For these kinds of changes I'd suggest just PRing the fix (it's likely faster to do so than create an issue).
