### ISSUE TITLE
Help forum doesn't have the "Get Help" button (or live-chat?)

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2435]
![image](https://user-images.githubusercontent.com/33286824/36294368-4ba6813c-12ae-11e8-9023-3414bd3139a0.png)

The Help forum is also missing the "search for answers" textbox but that doesn't even function on the old website either so no idea if a similar thing for the new website's help forum is planned

**Comment by peppy** [comment]
Not sure we'll use that going forward. It wasn't that popular. Going to go live without it, at least.
