### ISSUE TITLE
Some supporter features given for non-supporters

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2436]
I've never been a supporter, and was curious about this picture. It has pp and ranking on the old site knowing that person is a supporter, since I don't have it. The new site shows pp. Is this planned? If so, can you add the ranking too? :D
![](https://user-images.githubusercontent.com/30382015/36292427-b796f9ae-130c-11e8-8c63-68cae4994257.jpg)

**Comment by Xinnoh** [comment]
It's an osuplus feature https://osu.ppy.sh/forum/t/408541/
