### ISSUE TITLE
Distinguish between "last seen" for in-game and on the website

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2437]
Based off of https://twitter.com/velgloob/status/963757972869537793
I always have an osu tab open on my browser (the modding watchlist page so I can periodically refresh and check map statuses), so the "last seen" timestamp is now nearly always saying something within the last hour, even if I've not opened the game all day long >_> it can be a bit misleading that the two are grouped together into one "last seen" message.

**Comment by peppy** [comment]
We are moving towards consolidating this. Separating doesn't make any sense.
