### ISSUE TITLE
Read/Unread forum thread icons aren't color blind friendly

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2438]
Based off of 
https://www.reddit.com/r/osugame/comments/7xf1x5/peppy_planning_to_replace_the_old_website/du8py03

The current forum icons are not distinguishable for those who are red colorblind.

this
![image](https://user-images.githubusercontent.com/33286824/36294686-5d9178be-12b0-11e8-8dd1-ff6bf7d00f40.png)
can end up looking like this >
![image](https://user-images.githubusercontent.com/33286824/36294691-69435204-12b0-11e8-9305-6347eef2ac6f.png)
which basically look identical

Their suggestion is to add little lines in the unread icon
![image](https://user-images.githubusercontent.com/33286824/36294736-b297efbe-12b0-11e8-8d07-1b662e717071.png)
like so

**Comment by arflyte** [comment]
![91e7cfa428](https://user-images.githubusercontent.com/3632750/36296032-7e87b7ee-132e-11e8-8709-729a5bd0427d.png)

Solid icon for unread, outline icon for read.
