### ISSUE TITLE
No way to mark all forums as read

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2440]
was originally part of https://github.com/ppy/osu-web/issues/2356 but seeing as that's focused on the search modes now, I guess this should be a seperate issue instead 🤷 ?

Old forums had this link at the bottom of the main forum page
![image](https://user-images.githubusercontent.com/33286824/36294990-6e4501c4-12b2-11e8-97a6-2f91c58b0c14.png)
which would mark all threads and forums as read. This was convenient because it made it easier to tell what was new since your last visit. The new website doesn't have this feature.

**Comment by Shiguma7** [comment]
I believe this should be dealt with ASAP considering the new site is being implemented, it's a core feature necessary for forum use

**Comment by peppy** [comment]
I dont't think too many people use the forum in this way.. but I agree we should add it back.

**Comment by dorothy3242** [comment]
Also for some reason if you click the link in the old forums, it actually carries over and has the _opposite_ effect on the new forums - marking all threads as unread even if there were no new posts since they were last read using the new website.
Seems like a weird cross-site bug.

**Comment by nanaya** [comment]
Marking all threads read from old forum has been correctly carried over to new forum by #2774. Now only missing button to do it from new forum.
