### ISSUE TITLE
Multiple Polls within a single Forum Thread

### ISSUE THREAD

**Issue by Toybickler** [ppy/osu-web#2443]
Details in this image: https://i.imgur.com/ondUEGV.png
peppy reply: https://i.imgur.com/H19ldtM.png

Very niche request that would greatly benefit condensing the Project Loved forum (and may have minor practical use elsewhere)

**Comment by cl8n** [comment]
if this wouldn't be used anywhere else, I don't think project loved really needs it bc having separate threads for each map gives people a place to discuss them. it's been working out so far

**Comment by peppy** [comment]
Closing as out of scope, not worth the implementation time.
