### ISSUE TITLE
osu!website is stuck in the loading mode

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2450]
![](https://puu.sh/zp4KZ/7b0692c1ff.png)

1. Get into profile
2. Try to change the tab order
3. Wait for the verification overlay to appear

And now i'm not really sure about new steps

4. I changed the browser tab/Wait a bit
5.  The verification overlay will disappear and the website will be stuck in the loading mode

**Comment by jacksonisiah** [comment]
this also happens when logging out of the site.
