### ISSUE TITLE
Wierd/Glitched BG/thumbnails of maps on the new website (issue)

### ISSUE THREAD

**Issue by Smowokeman** [ppy/osu-web#2453]
Problem Details:

E.g. the thumbnail of this map is glitched (not as it should be) on the website https://osu.ppy.sh/beatmapsets/585856#osu/1240897. I dont know if this has ever been posted (asked around and everyone seemed to be surprised that this has been a thing for song long) but with the change to the new design you might want to look into why this happened. I uploaded and ranked this map when the new osu site was still pretty new. (https://osu.ppy.sh/beatmapsets/612722#osu/1292972 here another one of my maps with this problem but its dead so its fine)

This has been a problem since about roughly the day of the upload at least

Video or screenshot showing the problem:

https://puu.sh/zp54Q/0d33bd3afb.png  (on my profile aswell https://puu.sh/zp575/2612b3c755.png)
https://puu.sh/zp55E/6b92fe960b.png  (https://puu.sh/zp57L/88f0743c8c.png)

osu! version: 20171227.2 (latest)

**Comment by peppy** [comment]
may just need a reprocess (worth checking if the image is in a weird format that is causing the issue, though)

**Comment by nekodex** [comment]
Was a bug in the thumbnailer, mozjpeg didn't seem to handle interlaced PNGs properly.

Fixed now! 😃
