### ISSUE TITLE
Edit profile when hovering near the details on user page

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2455]
![](https://puu.sh/zpjOR/dcaaf20154.png)
![](https://puu.sh/zpkip/e6578c0af1.png)

**Comment by Xinnoh** [comment]
You can access the page to edit this information only one web page away via settings, the old site requires two so less of an issue

**Comment by Joehuu** [comment]
Should this be a thing? The feeling of pressing a button near it is better than navigating through settings.

**Comment by peppy** [comment]
It might be handy to have a link for this kind of thing, where it's not completely obvious  how to edit them.

**Comment by willowsnow** [comment]
could instead just make them editable textboxes based on whether or not the user is logged in ^^

**Comment by arflyte** [comment]
![a8eb94cd46](https://user-images.githubusercontent.com/3632750/36579880-e469ea12-18a8-11e8-8129-c52560367502.png)
Editable textboxes wouldn't fit in tight space. Added direct link to profile edit page for now, before we implement the new profile page design.
