### ISSUE TITLE
Add total kudosu earned on user's stats

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2456]
![](https://puu.sh/zpkQB/3207b8e68a.png)
![](https://puu.sh/zpkRZ/29d48e0187.png)

**Comment by kj415j45** [comment]
kudosu count is at the end of profile bh default

**Comment by Joehuu** [comment]
yeah but kudosu is showed both on the stats and a tab in the old site

**Comment by Xinnoh** [comment]
Not everything has to behave identically to the old site, if someone isn't a modder then they have no reason to require kudosu being displayed.

**Comment by Joehuu** [comment]
Modders should have it by the stats and tab. Non modders shouldn’t have it anywhere. The kudosu tab should be removed for them then.

**Comment by Xinnoh** [comment]
How is a modder defined, if someone earned 5-10 kudosu once upon a time but have no interest in it, then they're not a modder.
With v2, 5-10 kudosu becomes 50-100 kudosu. There's no level to define a modder.
If someone wants to identify as a modder, then they'd put their kudosu tab higher on their profile.

**Comment by peppy** [comment]
Kudosu is getting replaced with a new metric, which will definitely be visible on profiles!
