### ISSUE TITLE
No storyboard icon on beatmap card

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2457]
It seems that the video icon goes with storyboard.
![](https://puu.sh/zpmWe/05bee1880c.png) ![](https://puu.sh/zpn9F/ba78f0ddd0.png)
![](https://puu.sh/zpmVp/083fca7fe5.png) ![](https://puu.sh/zpn2q/ca509e5412.png)

**Comment by Xinnoh** [comment]
Would be misleading to re-implement the storyboard icon since this feature is no longer used, but having the video icon replace the sb icon is a bit 🤔

**Comment by arflyte** [comment]
This will be fixed in the new beatmap card design.

**Comment by VINXIS** [comment]
Also like to point out that the filter doesn't work at all on the old website. The newest ranked map that appears when u toggle "Has Storyboard" is from October 2012 which is not true at all

**Comment by Joehuu** [comment]
^ #3066. This issue should be resolved with it.
