### ISSUE TITLE
Edit necessary "Sort by..." categories on corresponding "Rank Status"

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2458]
Add
- [ ] Add and default sorting by "updated"
- Any, Favourites
- [ ] Add sorting by "creator": **Not yet implemented**
- All except My Maps, since it only shows your maps.

Remove
- [ ] Remove sorting by "ranked"
- Any
- [ ] Remove sorting by "rating"
- Any, Pending, Graveyard
- [ ] Remove sorting by 'plays'
- Any

~Edit: Removed proposals and stuff I can't code.~
Edit: Someone do this.

**Comment by Xinnoh** [comment]
"It's not possible to sort beatmaps by the 'any' category because it only sorts by when it was ranked, which only shows ranked maps."
https://osu.ppy.sh/beatmapsets?s=7

**Comment by peppy** [comment]
Correct me if I'm wrong, but "ranked" shouldn't even show in this filter mode.

**Comment by Joehuu** [comment]
yeah thats right

**Comment by Joehuu** [comment]
Since I think this sorting section needs a change on #2990, I'll close this and hope that the issue I referenced fixes this issue and more. And sorry, I tried fixing this issue without an environment since I don't how to set it up.
