### ISSUE TITLE
Links to specific mod posts aren't always working

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2459]
Try to click any mod post link in the history tab, or in a "Nominations reset.." message, and half the time it will just take you to the general (all difficulties) tab and NOT the mod post in question. It seems to be working on and off, which is strange.

Edit: added video. For the first bit you can see me trying to click on links only to be brought to the general (all difficultes) tab. After a bit, clicking the links suddenly starts working as it should.

https://youtu.be/hHaGSszBAJE

**Comment by nanaya** [comment]
The system has gotten several updates, reopen if still a problem.
