### ISSUE TITLE
Some images have wrong dimensions

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#246]
https://new.ppy.sh/forum/t/372346?start=4662680

**Comment by nanaya** [comment]
That's unfortunate but once an image is used in a post, the image dimensions will stay for a while even though the image itself is changed.

**Comment by abraker95** [comment]
https://osu.ppy.sh/forum/p/4662680
But it looks perfectly fine on the old forums. Maybe I'm not understanding what you meant?

**Comment by nanaya** [comment]
yes, it only applies in new forum. Try changing the url slightly by, for example, adding a trailing question mark.

**Comment by abraker95** [comment]
Adding a trialing question mark did the job! Why isn't this done automatically?

**Comment by nanaya** [comment]
because otherwise loading posts will take ages since it needs to get image dimensions first.

**Comment by abraker95** [comment]
I'm pretty sure some people will run into a similar issue when using the new forums in the future. Perhaps a warning telling them that the image size may be wrong given the URL? Or is there no way to detect that?

If not or it will slow down the loading, perhaps a general announcement then?

**Comment by nanaya** [comment]
it'll only be wrong if the image is changed after initially posted (reupload etc).

**Comment by abraker95** [comment]
That image is a screenshot from osu! How do you go about modifying or reuploading that?

**Comment by VeilStar** [comment]
Just curious more than anything, but wouldn't it be possible to compare image dimensions (see if the dimensions are still the same) when someone edits a post and is about to save it, and update it that way?

**Comment by abraker95** [comment]
That post was never edited either

**Comment by nanaya** [comment]
the image is hosted somewhere, and that exact image is then changed. The dimensions will be eventually correct after the cache expires.

**Comment by VeilStar** [comment]
Oh, I misunderstood. My bad.
