### ISSUE TITLE
Lack of outline makes it difficult to tell what is and isn't in a spoilerbox

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2460]
Once a spoiler box is opened, there is no outline or any form of distinction to show where the box's content ends. This can make it difficult to tell when it is open what does and does not belong in the opened box.  On the old website this was done by a slight variation in background color for the inside of the box.

**Comment by Xinnoh** [comment]
![screen shot 2018-02-17 at 1 48 42 pm](https://user-images.githubusercontent.com/30382015/36338408-4bb1461c-13e9-11e8-8c58-566486a99a4f.png)
Could use the same visual effect as the [notice] or move box text to the right a bit

**Comment by arflyte** [comment]
![702c90688f](https://user-images.githubusercontent.com/3632750/36362680-2de542fe-157a-11e8-872f-f01e1b19fbbb.png)
