### ISSUE TITLE
Add necessary pages under home navigation

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2462]
History, The Team, and Rules should be added in navigation. Either add it to home or another place. And remove news and friends, since news is always in the dashboard and friends can be navigated when you press your avatar. Also the download, since it's in the dashboard too.
![](https://puu.sh/zppq3/be477c0e8e.png) ![](https://puu.sh/zpppk/482b86ad01.png)

**Comment by Xinnoh** [comment]
History and the team are somewhat out of date and aren't frequently needed.
Rules however, need to be easy to access, but the Home tab is already full. Rules would probably fit under the Help tab.

**Comment by dorothy3242** [comment]
I could see friends being removed from there if needed, considering it's a tab accessible from the home page, as well as being under the **quick profile** menu.

**Comment by peppy** [comment]
- Rules should definitely go under "help".
- History can remain unlinked (on the wiki).
- Team should be added in place of friends.
- Search probably doesn't need to be there at all.

**Comment by TPGPL** [comment]
I think search should remain here, because you cant access it on mobile without it

**Comment by peppy** [comment]
Search will be added back in #2594, let's remove it for now.

**Comment by nekodex** [comment]
or just leave it there and remove it when the search box is implemented in #2594 so we're not removing functionality
