### ISSUE TITLE
Sort friends in a number of ways

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2463]
The friends list right now is sorted in alphabetical order. If you have a lot of friends, sorting them by last played is necessary, since friends can go on a hiatus. Add ascending and descending, so you can delete those friends who don't play anymore if you're that kind of person who add people randomly. And lastly, sort them by performance points.

**Comment by peppy** [comment]
Yep, this is going to eventually be added.

**Comment by peppy** [comment]
Keep in mind users with hidden presence should be at the bottom of the list (as their last visit should not be revealed to others).

**Comment by peppy** [comment]
Will be addressed by #4232.
