### ISSUE TITLE
Links on the Discussion page doesn't show correctly at higher resolutions

### ISSUE THREAD

**Issue by Mykaterasu** [ppy/osu-web#2469]
The new discussion page fails to properly show anything with a hyperlink, cropping them out in pseudo-random box shapes when I use a resolution greater than 1920x1080.
The visual effect seems to stay where I've hovered for an indeterminate amount of time.
This is consistent with multiple mapsets.
For some reason it only happens on the pending and praise tabs. I have yet to have it happen in the Resolved section.
It doesn't happen with all links, and is much more likely to occur if you scroll down so the new discussion box isn't visible.

Attempting to actually interact with this glitchy stuff (hitting respond or typing out a new discussion while it is glitching) just makes it a lot worse.

![idk what this is but this look good](https://user-images.githubusercontent.com/36574041/36344918-c9815806-1421-11e8-8cf6-654958b78f47.jpg)

**Comment by peppy** [comment]
What browser are you using (include the full version please)?

**Comment by Mykaterasu** [comment]
Google Chrome;
Version 64.0.3282.167 (Official Build) (64-bit)

**Comment by Mykaterasu** [comment]
I just had this error in standard 1920x1080 resolution. It seems that higher resolutions don't cause the problem.

**Comment by Mykaterasu** [comment]
I've confirmed that windows reminders cause the problem.

**Comment by nanaya** [comment]
Reopen if still having problem.
