### ISSUE TITLE
Home shouldn't be in the not logged main page footer

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2477]
It just redirects you to the same page. You can leave it here if this appears in another page.
![](https://puu.sh/zqpjp/1793f34df8.png)

**Comment by peppy** [comment]
I don't see a huge issue with this?

**Comment by Joehuu** [comment]
It'll be consistent to add this footer to the bottom of every page like the old site then. The home button will be useful again when you reach the bottom of the page(ex. rankings page).

**Comment by peppy** [comment]
I think it's fine as-is.
