### ISSUE TITLE
Log out link leads to missing page

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2482]
When you try to middle click or right click with context menu. The link doesn't log you out, the dialogue does.
https://osu.ppy.sh/session
![](https://puu.sh/zqOG0/9385740f57.png)

**Comment by Xinnoh** [comment]
why are you right clicking it

**Comment by Joehuu** [comment]
I was just saying how to go to that page. Having that link removed will not prevent you from logging off. I'm hoping it has a purpose.
