### ISSUE TITLE
Lowercase languages on navigation

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2483]
Already lowercased on home page logged out
![](https://puu.sh/zqPr7/132a964035.png)

**Comment by kj415j45** [comment]
![20180220_052624_rmedited](https://user-images.githubusercontent.com/18349191/36397751-f5795b3c-15fe-11e8-88d0-e48d1ec6eda6.jpg)
add screenshot for this issue

**Comment by peppy** [comment]
Hmm, looks a bit weird but maybe I'm not used to it.

Need a call from @arflyte here

**Comment by kj415j45** [comment]
https://github.com/ppy/osu-web/blob/master/resources/assets/less/bem/landing-nav.less#L39

change this to: `text-transform: capitalize` seems fix this

**Comment by nanaya** [comment]
The designer says the menu (top link) is lowercased, the entries are capitalized.

**Comment by nekodex** [comment]
Designer now says it should all be lowercase. 🎉

**Comment by Joehuu** [comment]
Don't know if I should make another issue b/c the stated issue will be the same. Is this intentional?
![](https://puu.sh/zWMDH/1d89ec6ba8.png)
