### ISSUE TITLE
Social media links could probably be moved to take less space + Show settings

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2484]
Current
![screen shot 2018-02-19 at 11 02 32 am](https://user-images.githubusercontent.com/30382015/36361262-991950e8-1565-11e8-95e2-8e36c148c403.png)

Suggested change, covers less screen, makes settings easier to find.
![change](https://user-images.githubusercontent.com/30382015/36361313-eb745c8e-1565-11e8-9dc9-1b02458b60ac.jpg)

**Comment by peppy** [comment]
It's supposed to take space.
