### ISSUE TITLE
Tap to toggle experience bar on mobile

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2492]

**Comment by peppy** [comment]
Could you explain what you mean by "experience bar"?

**Comment by TPGPL** [comment]
@peppy level experience bar on the profiles

**Comment by peppy** [comment]
Please provide a screenshot of what you are seeing

**Comment by TPGPL** [comment]
It actually hides on opening the navigation but it still should work other way

**Comment by nanaya** [comment]
...or tapping anywhere else.

**Comment by TPGPL** [comment]
I think it should hide on clicking again on the level badge, because then its not that intuitive
