### ISSUE TITLE
"Ghost" beatmaps appear when trying to upload a new map in osu-stable client and then cancel

### ISSUE THREAD

**Issue by shortthu** [ppy/osu-web#2494]
Appear in [my osu! profile](https://osu.ppy.sh/users/7985423)
I'm not canceling at the uploading scene, just this one:
![image](https://user-images.githubusercontent.com/22362633/36380258-30b86dd2-15b4-11e8-8b56-4ac8bdbbdb4e.png)
Doesn't appear on beatmap listing

**Comment by peppy** [comment]
The active or orphaned flags are not being checked, for whoever looks at fixing this.
