### ISSUE TITLE
bbcode [list] bug on the new website (on userpage)

### ISSUE THREAD

**Issue by VenixOSU** [ppy/osu-web#2497]
at least on my userpage

## Old webite
![alt text](https://venix.s-ul.eu/frC7RjC4 "100%")

## New website
![alt text](https://venix.s-ul.eu/W8Eq3BKj "100%")

**Comment by peppy** [comment]
Could you please link the post or your user page where this can be checked, rather than just a screenshot?

There is likely an issue with your bbcode being malformed, so you could also check that yourself.

**Comment by Xinnoh** [comment]
https://osu.ppy.sh/users/5999631

**Comment by VenixOSU** [comment]
https://osu.ppy.sh/forum/t/478641 I don't know, maybe this is an issue with my code, but then why is it working on the old website?

**Comment by peppy** [comment]
The old site was very lenient with coding mistakes.

**Comment by nanaya** [comment]
Difference in cleaning up between browser (old site) and new site (php html cleaner).

```
[color=#3a9ff2]Ranked:[/color][color=#747474][list]
[*][Hard][/color] [url=https://osu.ppy.sh/s/545606][color=#3a9ff2]bradbreeck - Feel It Comin[/color][/url] [color=#747474](by deadpon3)[/color]
```

`[color]` tag for `[Hard]` text starts before the list started. When finding the closing tag, in new site it means closing whatever open tags as well which includes the list.
