### ISSUE TITLE
Access denied when uploading a new avatar

### ISSUE THREAD

**Issue by Nath789** [ppy/osu-web#2498]
A user has reported ([thread](https://osu.ppy.sh/community/forums/topics/705837)) that they got an "Access denied." message when trying to upload a new avatar. This also happens to me and the other GMTs. I assume this is to prevent silenced users from using it.

**Comment by WalterToro** [comment]
To add more info, this also happens with other types of uploads, like [cover images](https://walter.s-ul.eu/vLf9rOCg.png)

**Comment by WhiteRedWolf** [comment]
It Happens to me on the Old Site aswell.

**Comment by peppy** [comment]
This should now be resolved. It was specific to the new site, for what it's worth.
