### ISSUE TITLE
Translation/grammar mistake on new osu! website (polish).

### ISSUE THREAD

**Issue by Kwiaszt** [ppy/osu-web#2499]
When viewing someone's profile on the new osu! website in polish, in a section telling what devices someone is using to play it says "tableta" and should be "tabletu".

That's it, cheers.

**Comment by kj415j45** [comment]
why not create a PR? :)

**Comment by Kwiaszt** [comment]
Dunno, never used this github thing before, i asked in #osu chat what to do and some mod linked me to https://github.com/ppy/osu-web/issues

I just wanted to help ;_;

**Comment by kj415j45** [comment]
Alright then, I will fix that
