### ISSUE TITLE
Pick "Sign" or "Log" in/out word

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2503]
Personally picked the word "sign" formatted like this:
"sign in" and "sign out": all lowered case if the other choices are lower. If not, you cap the first letter in every word. Also spaced out.
TL;DR: This lower case thing is confusing, so think what looks good. :D
1. Drop down
![](https://puu.sh/zrBiH/627aa25145.png) ![](https://puu.sh/zrB7z/cc37336804.png)
^ perfect
2. Sign in button
![](https://puu.sh/zrB9Q/294924ce36.png) ![](https://puu.sh/zrB8c/3f60580ae5.png)
^ to "sign in"
3. Sign out button
![](https://puu.sh/zrB9r/3ae7f54cef.png) ![](https://puu.sh/zrB98/b077597514.png)
^ to "Sign Out"
4. Sign in button(in game)
![](https://puu.sh/zrBMt/a0b00d02e8.png) ![](https://puu.sh/zrBmX/70375b16c7.png)
^ to "stay signed in" and "sign in"
5. Sign out button(in game)
![](https://puu.sh/zrB6g/14022825c5.png) ![](https://puu.sh/zrBoV/7181adb2c7.png)
^ to "Sign Out"

**Comment by peppy** [comment]
let's go with "sign" instead of "log". case should match elements around it
