### ISSUE TITLE
Allow multiple tags on changelog

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2507]
Like to see what the web icon looks like.
![](https://puu.sh/zrZd4/0e21f25ce0.png)
![](https://puu.sh/zrZdY/ea7c20f264.png)

**Comment by peppy** [comment]
Unnecessary, as the detail is already in the commit message. Also going forward this is going to change as we migrate the changelog to newer projects (lazer/osu-web/framework).
