### ISSUE TITLE
 Convert obtained kudosu to the one line in kudosu history

### ISSUE THREAD

**Issue by VenixOSU** [ppy/osu-web#2517]
It would be nice and more readable, example:
"Received 20 kudosu from obtaining votes in modding posts of <map name>" instead of 20x "Received 1 kudosu from obtaining votes in modding post of <map name>"

**Comment by Xinnoh** [comment]
duplicate #1957

**Comment by VenixOSU** [comment]
oh sorry, when i was looking for issues i had to miss this one
