### ISSUE TITLE
Page Navigation on Top on the Rankings Page

### ISSUE THREAD

**Issue by Xiquee** [ppy/osu-web#2532]
It would be convenient to be able to navigate the rankings pages not only from below the table, but also from above. The reason is that sometimes I am scrolling upwards in ranking and don't want to scroll all the way back down to go to the previous page. 

I'm sorry but I do not know how to add labels.

**Comment by Joehuu** [comment]
You can't add labels, only the people who can edit this repo can do that.
![](https://puu.sh/ztoFh/a4ee065e6c.png)

**Comment by peppy** [comment]
I don't disagree with this. @arflyte opinion?

**Comment by arflyte** [comment]
Yeah, just add another page navigation on top of the table.
