### ISSUE TITLE
Old beatmap thumbnails don't show

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2533]
The very first beatmaps with at least a thumbnail don't show it. Also on their beatmap page.
New Site: https://osu.ppy.sh/beatmapsets?sort=ranked_asc
![](https://puu.sh/ztp6J/5e5dd65838.png)
Old Site: https://osu.ppy.sh/p/beatmaplist?l=1&r=0&q=&g=0&la=0&ra=&s=4&o=0&r=0&q=
![](https://puu.sh/ztp67/7af9032285.png)

**Comment by Joehuu** [comment]
Now the new ones.
![dashboard home osu](https://user-images.githubusercontent.com/35318437/37298885-e101ce9c-25de-11e8-9031-c84354ceac71.png)
New site: https://osu.ppy.sh/beatmapsets/664315
Old site: https://osu.ppy.sh/s/664315
And thumbnail shows in beatmap page, but not in the listing. Ignore the right one.
https://osu.ppy.sh/beatmapsets/506544
![beatmaps listing osu](https://user-images.githubusercontent.com/35318437/37300232-ad14197e-25e2-11e8-83fd-70fc9ce5815a.png)
![setsuna no kajitsu maon kurosaki info beatmaps osu](https://user-images.githubusercontent.com/35318437/37300239-afdb792c-25e2-11e8-97ce-a532c063e328.png)
The main issue didn't get fixed on other old beatmaps. At least for that one.
![beatmap listing](https://user-images.githubusercontent.com/35318437/37300719-eb0a90a4-25e3-11e8-9ab9-820b33ab0412.png)
![beatmaps listing osu 1](https://user-images.githubusercontent.com/35318437/37300722-ee938802-25e3-11e8-9106-21320a06855f.png)

**Comment by Joehuu** [comment]
reopen, it's happening again to the new ones this time.
![](https://puu.sh/zH8SR/104c245ca3.png)

**Comment by nekodex** [comment]
The old beatmaps listed don't actually have background images, thus they don't have thumbnails.

Also please don't just change the title of resolved issues to something new after the originally reported issue was resolved.
