### ISSUE TITLE
Add notification / warning for beatmaps with mature content

### ISSUE THREAD

**Issue by JBHyperion** [ppy/osu-web#2534]
There's been lots of discussion recently about wanting clearer guidelines on what is considered appropriate (or otherwise) for mapping in osu! Where a beatmap is considered "borderline acceptable", the current cautionary measure is to ensure the mapper puts some kind of "mature content" warning flag in the beatmap description, alerting players who may be sensitive to that sort of stuff.

Would it be possible to include this as a standardised and more visible warning on the beatmap's information page? Either through a notification on the listing (e.g. below the options for Favourite / Download / osu!direct / Discussion) or a popup when you attempt to download the map?

Something along the lines of:

> "Caution! This beatmap contains mature content that may not be suitable for all players!
> Please read the beatmap description for more information."

The latter would be especially useful since currently, there's no way to warn of mature content currently when downloading beatmaps through osu!direct. I'm not sure if there's an easy way to achieve this though, since it would probably require either:

**a) A toggle option for moderators** to assign this "mature content" tag, similar to the beatmap management panel functions on the old forum, or...

**b) A mapper-enabled option** in the editor, similar to the "enable epilepsy warning" option for flashy storyboards.

If the latter is possible, it could allow for a similar content warning notification when play begins, but for now, that's probably best left under consideration for osu!lazer in the future.

**Comment by peppy** [comment]
Yep, this is something we will tackle once our backlog clears up.

**Comment by nanaya** [comment]
Continuing tracking this in #5902.
