### ISSUE TITLE
[Navigation] Submenu is in hover state, even while not hovering on it

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2543]
![](https://puu.sh/zu17s/239ab00de8.png)

**Comment by nanaya** [comment]
It's not a bug, it's a feature.

(yes, really)

**Comment by TPGPL** [comment]
@nanaya what about this ;s

![](https://puu.sh/zu1vG/70ae599e7e.png)

To reproduce
1. Enter Forum for example
2. Go to Beatmaps
3. Slowly open the navigation by hovering on the corner

**Comment by nanaya** [comment]
that looks like a bug (different than what the title says though)

**Comment by peppy** [comment]
Either way, this menu is getting replaced in the *very* near future, so I'm not sure this is worth fixing.
