### ISSUE TITLE
Deleting a modding post causes an error message

### ISSUE THREAD

**Issue by MillhioreF** [ppy/osu-web#2550]
![](https://puu.sh/zuWW2/99654a7894.png)

When clicking delete, the post is successfully deleted, but this error message shows up and the post remains displayed locally. Refreshing the page causes it to disappear as intended.

**Comment by dorothy3242** [comment]
If you attempt to delete a second time without refreshing the page, it causes a different error to show up as well.
![image](https://user-images.githubusercontent.com/33286824/36636164-c14eaea0-198e-11e8-8ad9-fa4552502891.png)

**Comment by peppy** [comment]
Reverting the cause of this regression for now.
