### ISSUE TITLE
Filter friends on rankings is missing

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2556]
Old site link:
https://osu.ppy.sh/p/pp
![](https://puu.sh/zvJzz/b470921718.png)
New site link:
https://osu.ppy.sh/rankings/osu/performance

**Comment by peppy** [comment]
@arflyte should this follow the same design as the beatmap listing page?

**Comment by arflyte** [comment]
It should have the same filters as the beatmap listing. I'll provide the design.

**Comment by arflyte** [comment]
![photoshop_2018-02-26_16-34-09](https://user-images.githubusercontent.com/3632750/36658232-fafcae42-1b12-11e8-9c69-95b3f800a7d4.png)

Updated Rankings page design.
