### ISSUE TITLE
Mod requests is missing in "Rank Status" on Beatmap Listing

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2564]
Was this intentional?
![](https://puu.sh/zwqzz/33ee48bba0.png)
![](https://puu.sh/zwqz9/2596a69ee2.png)

**Comment by dorothy3242** [comment]
Mod Requests hasn't even worked on the current website in _years_
if they were to add it back, it'd need to be fixed in general :(

**Comment by peppy** [comment]
Mod requests won't be added back in this state. We'll have something to replace it in the future, though.
