### ISSUE TITLE
 Recommended difficulty needs to state what star rating is being filtered

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2565]
There is currently no indicator to what difficulty is being filtered.
![screen shot 2018-02-27 at 10 47 59 am](https://user-images.githubusercontent.com/30382015/36707979-c3bcb884-1bab-11e8-9db9-db0b3b2b1e5e.png)
![screen shot 2018-02-27 at 10 48 05 am](https://user-images.githubusercontent.com/30382015/36707980-c3f3d5ee-1bab-11e8-879f-e7bf764b6fc9.png)

**Comment by dorothy3242** [comment]
update: This is more important now as apparently it is impossible to view the recommended difficulty search filter using the old website, it will instead force-redirect to the new-website, making the star value inaccessible. 
This makes it ambiguous/impossible to tell which difficulties in mapsets are the ones that are being recommended to players, making the feature extremely not-useful.

**Comment by peppy** [comment]
Agree
