### ISSUE TITLE
Mark threads you replied in in thread listing

### ISSUE THREAD

**Issue by Endaris** [ppy/osu-web#2572]
This is an old feature that does not exist yet and I did not find an issue for it.

New forum thread listing:
![grafik](https://user-images.githubusercontent.com/22120694/36728540-5c906f46-1bc1-11e8-91bb-7c1978e34a23.png)

Old forum thread listing:
![grafik](https://user-images.githubusercontent.com/22120694/36728586-83435310-1bc1-11e8-831f-b257c47b7e59.png)

As you can see, in the old thread listing, threads I already replied in are marked with a dot in the top left corner. This is a very important feature for regular forum users.

**Comment by arflyte** [comment]
![photoshop_2018-03-06_15-00-31](https://user-images.githubusercontent.com/3632750/37016376-34c743c0-214f-11e8-98d0-b075a4cb1e9a.png)

Replied tooltip on hover.

**Comment by Endaris** [comment]
This was finally added not too long ago.
![grafik](https://user-images.githubusercontent.com/22120694/94208891-2b825780-fecb-11ea-9d24-6830423d63bf.png)
