### ISSUE TITLE
Preview points of a map sometimes doesn't update

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2574]
https://osu.ppy.sh/s/670068  https://osu.ppy.sh/s/715088 
The web never updated the preview point of the song for these two sets. 
The 2nd map isn't even the correct song, it had its mp3 replaced a while ago from a different song and the web never updated it.

**Comment by peppy** [comment]
These need a resubmission via BSS. The second should be unqualified ASAP to make this happen.

**Comment by Xinnoh** [comment]
Resubmission as in upload again or delete the map and upload as another set
Uploading the map again didn't fix the issue so the mapper can re-submit as a new set for now

**Comment by peppy** [comment]
NOT deleting the map. just resubmission via BSS.

**Comment by Xinnoh** [comment]
https://pastebin.com/5eCjAFsa
The mp3 / preview point was changed before the mapper received mods, he uploaded the set with the current preview point quite a few times, uploading it again won't fix the problem

**Comment by Fursum** [comment]
I had a guess in which because one of the ghost diffs were created with the old mp3 and bg. The website doesnt see an issue so doesnt update.

**Comment by peppy** [comment]
Give me a bit to look into this. Best to figure out what's going on here (shouldn't take more than a day).

**Comment by czneto** [comment]
Same issue about preview point with this map https://osu.ppy.sh/s/737644
The background is also not working on the old site, but new one it is.

**Comment by Xinnoh** [comment]
Old site does not matter since it's being removed later, as long as it works on the new site then its fine

**Comment by czneto** [comment]
Okay, but the preview bug is on the new site, not old, just to make sure this is clear.

**Comment by peppy** [comment]
This has since been resolved. You can fix this by resubmitting via BSS (NOTE: THIS MEANS HITTING THE UPLOAD BUTTON IN GAME, NOT CREATING A NEW BEATMAP AND DUPLICATING THE UPLOAD)

**Comment by czneto** [comment]
Nice caps. I did indeed pressed the Upload Button multiple times ,but it never fixed the issue.

**Comment by peppy** [comment]
The caps are because someone already did this.

Please upload once more, as the fix was deployed only 38 minutes ago.

**Comment by czneto** [comment]
I actually just did it 25 minutes ago, sorry I didn't see this before https://puu.sh/zASF3.png

**Comment by peppy** [comment]
Preview points have always taken 1-24hours to update due to caching. Please give it a while.

Thumbnails are instant.

**Comment by czneto** [comment]
Ok. Thanks for the fix, I'll proceed with the map.
