### ISSUE TITLE
Display nomination status on beatmap information page

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2575]
![image](https://user-images.githubusercontent.com/33286824/36755942-acebe442-1bdb-11e8-8c6f-a809b4088c6a.png)
![image](https://user-images.githubusercontent.com/33286824/36755956-b4e1d864-1bdb-11e8-9aee-ac15b0f1aa70.png)
because if you're following a direct link such as from #modreqs , it'd be nice to be able to see straightaway whether a map is already nominated or not instead of having to go to a separate page to see that information.

**Comment by arflyte** [comment]
![8e3e3a8291](https://user-images.githubusercontent.com/3632750/36827935-f743ed08-1d59-11e8-9f23-939de3f12bae.png)

New indicator showing map's status on beatmap page. Shows all type of map status.

![410bbc6c8e](https://user-images.githubusercontent.com/3632750/36827945-1788d74a-1d5a-11e8-91bf-def71a3b3904.png)

New indicator showing map's status on beatmap card. Only show when map is not ranked (unranked, nominated etc).

**Comment by nekodex** [comment]
Should always show state in the beatmap card to be consistent
