### ISSUE TITLE
Clicking area should be only in textbox on settings

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2576]
When editing anything on settings, I tend to click outside of the blank area around it just to remove that edit highlight, and so no other inputs change it. This is the clicking area on skype. Clicking anywhere in this area will put you on the skype textbox where the text cursor is on the front by default. The clicking area should be only the textbox. Also bad when clicking an empty area on playstyles.
![](https://puu.sh/zxd8N/408eb26b62.png)
![](https://puu.sh/zxdNW/166a4bfb19.png)
![](https://puu.sh/zxey2/8dddd63bea.png)
https://osu.ppy.sh/home/account/edit

**Comment by peppy** [comment]
I agree this feels bad as it is.

**Comment by Joehuu** [comment]
Fixed in #3260.
