### ISSUE TITLE
Cannot report users

### ISSUE THREAD

**Issue by ThePooN** [ppy/osu-web#2580]
There's currently no way that I'm aware of to report an user from their profile. A quick form like on the older website would be a welcomed addition, as the only other way to report someone is in-game.

**Comment by peppy** [comment]
@arflyte 

previously looked like this:

![Pasted Image 1.png](https://shipusercontent.com/bf94684695ab327a088c9e5c9cff83f5/Pasted%20Image%201.png)

![Pasted Image 3.png](https://shipusercontent.com/6b77650325f993fcac6c7c37ab1b9ca5/Pasted%20Image%203.png)

![Pasted Image 4.png](https://shipusercontent.com/221de1b606307f6c872c5b259df260f9/Pasted%20Image%204.png)

**Comment by peppy** [comment]
This is top priority and needs to be completed before anything else. Is anyone already working on this?

**Comment by peppy** [comment]
@arflyte is a design complete for this even? if not, drop *everything* and make it happen today.

**Comment by arflyte** [comment]
Odd, I thought someone already implemented it. My bad, missed this. Here's the design.

![photoshop_180806-135547](https://user-images.githubusercontent.com/3632750/43697680-c3373e04-9980-11e8-9c2a-c8d13bf50643.png)
![photoshop_180806-135626](https://user-images.githubusercontent.com/3632750/43697685-c5bed916-9980-11e8-9f9b-34e56be933c8.png)
