### ISSUE TITLE
Open source notice somewhere on the site

### ISSUE THREAD

**Issue by jacksonisiah** [ppy/osu-web#2587]
Mentioned in osu-web Discord. It was suggested to be possibly in the footer.

Awaiting some feedback to how this should possibly be implemented. (place, text, design, etc.)

**Comment by jacksonisiah** [comment]
quite possibly. still waiting for feedback tho.

**Comment by peppy** [comment]
@arflyte are you okay with that design/layout above?

**Comment by arflyte** [comment]
Yeah. Looks fine.
