### ISSUE TITLE
Add a notice to pages stating there is additional functionality if you're logged in.

### ISSUE THREAD

**Issue by nekodex** [ppy/osu-web#2592]
This supersedes/fixes #2376 and #2217.

Assigned to @arflyte for design.

**Comment by arflyte** [comment]
![photoshop_2018-03-02_16-54-02](https://user-images.githubusercontent.com/3632750/36889006-62060bb2-1e3b-11e8-952e-f6681de53a3b.png)

Floating panel that sticks to the top of the screen. Someone need to rewrite the stuff in the box and describe stuff.

![photoshop_2018-03-02_17-00-24](https://user-images.githubusercontent.com/3632750/36889056-8cc49bde-1e3b-11e8-80e4-3967998e6907.png)

The yellow bar trails back to the avatar.

**Comment by peppy** [comment]
Is this design not current? What was the reason for not implementing this?

**Comment by peppy** [comment]
I thought it was going to appear when something was clicked that required login. If it is always there that's a bit obnoxious, agreed.

**Comment by arflyte** [comment]
It was designed to only appear when something was clicked. If you want something permanent, then I'll have to redesign it to make it less obnoxious, but it won't grab much attention telling user to login.

So, you guys want a permanent notice or non permanent notice? I prefer the latter.

**Comment by notbakaneko** [comment]
Currently, clicking on things that require login will show the actual sign-in form ready for input, which is probably better than a message and having to make another click to bring up the sign-in form.

The issue is when the functionality isn't originally visible when not logged in, like for the beatmap download button where there isn't anything to even click on in the first place.

**Comment by arflyte** [comment]
![photoshop_180809-192657](https://user-images.githubusercontent.com/3632750/43893530-3f51b1f0-9c0a-11e8-885f-86097508fcc4.png)

Permanent bar design.

**Comment by LiquidPL** [comment]
Can I get that lock symbol in full quality (or maybe just the psd, if that's easier)?

**Comment by peppy** [comment]
@LiquidPL if you’re looking to implement this, just use a generic fontawesome icon for the time being. @arflyte please provide logo if you see this.
