### ISSUE TITLE
Posts should be separated

### ISSUE THREAD

**Issue by VenixOSU** [ppy/osu-web#2599]
I mean it should use spacing equal to one between "Last seen" and "Plays with" because now it looks like posts are connected with playstyle what makes no sense.

How it looks now:
![alt text](https://venix.s-ul.eu/sS1uG1u9 "100%")

How it actually should:
![alt text](https://venix.s-ul.eu/C8BTy7wr "100%")

**Comment by peppy** [comment]
Can agree with this one. Although we may start to have too many segmented areas. @arflyte thoughts?

**Comment by arflyte** [comment]
Leave it as it is for now, as adding more segment will increase the info box's height.  It will be fixed in the new design.

**Comment by peppy** [comment]
Just going to close this one for the time being, very minor.
