### ISSUE TITLE
Hide h4 and smaller from wiki table of contents

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#2600]
Too verbose right now.

Example: https://osu.ppy.sh/help/wiki/Help_Center

**Comment by TPGPL** [comment]
and h6

**Comment by kj415j45** [comment]
Hide h5 and h6 enough, see also ppy/osu-wiki#1082

**Comment by nanaya** [comment]
So which one is it?

**Comment by peppy** [comment]
h4 and smaller, see https://osu.ppy.sh/help/wiki/Help_Center
