### ISSUE TITLE
Directories in wiki links aren't always case-insensitive

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2609]
For example: People works, PeopLe doesnt

Also subdirectories are case-sensitive as well

**Comment by nanaya** [comment]
Which url doesn't work? This seems fine: https://osu.ppy.sh/help/wiki/PeoPLe/Language_Moderators

**Comment by TPGPL** [comment]
@nanaya PeopLe alone

**Comment by nanaya** [comment]
This one? https://osu.ppy.sh/help/wiki/PeopLe ? Can you just post the full url? That ones seems working as well.

**Comment by nanaya** [comment]
Looks like you mean when the page doesn't exist in the current locale?

**Comment by TPGPL** [comment]
Yeah although it should link to the English one
