### ISSUE TITLE
[Profile page] Disable ability to break the width of the page by changing block position

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2618]
![](https://user-images.githubusercontent.com/19843905/49685653-65604f00-fae7-11e8-8f1f-fa8eedb5d514.png)

**Comment by TPGPL** [comment]
still happens, although you have to scroll to right with arrows to replicate

**Comment by peppy** [comment]
Not sure this is of huge concern?

**Comment by notbakaneko** [comment]
If you’re going to try to put the section outside the acceptable bounds of the page, I don’t think you should expect it to look correct while you try ಠ_ಠ
