### ISSUE TITLE
Apply auto-size to the bubble

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-web#2620]
![image](https://user-images.githubusercontent.com/18349191/36933851-de9a0c84-1f1a-11e8-9793-a8df51a78ee9.png)
current bubble is width-limited and has wide black edge

**Comment by peppy** [comment]
Quite possibly intended? @arflyte

**Comment by arflyte** [comment]
It's intended, although I'm not sure if there's anyway we can prevent orphans.
