### ISSUE TITLE
[News listing] Link stuck in hover state if you hold the link and throw it somewhere else

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2621]
![](https://puu.sh/zzCjf/b14ba99226.png)

To reproduce:
1. Hover over the link
2. Hold the LMB
3. Take the link somewhere else (to the right for example)
4. Stop holding

**Comment by TPGPL** [comment]
actually it happens with most of the links ❗️

**Comment by nanaya** [comment]
Or just

1. press tab enough times

It's called focus state.

**Comment by TPGPL** [comment]
o
