### ISSUE TITLE
[Beatmap Packs] No ability to hide the pack's content

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2624]
You must click another pack to hide the previous one; on the old site you could click opened pack to hide it.

**Comment by peppy** [comment]
Is there any point to closing it?

**Comment by dorothy3242** [comment]
If you're looking through multiple packs, it's easier to open/close one pack, then move your mouse slightly down to the next, rinse and repeat, than move your mouse all the way down to the next one and have to scroll down on the page more frequently.
It just feels like a missing functionality at the moment.
