### ISSUE TITLE
Retrieving beatmapset with just a beatmap's ID

### ISSUE THREAD

**Issue by naoey** [ppy/osu-web#2625]
The response from the API's `/beatmaps/:beatmap_id` endpoint currently returns a beatmap's set incompletely.

![image](https://user-images.githubusercontent.com/3889501/36937032-38a545e6-1f33-11e8-80f6-88c4028b46a9.png)

It's missing the list of the beatmaps in the set for starters. This is currently a roadblock in looking up beatmaps by ID in the client (from chat links etc.), since beatmaps need to be displayed as part of a set. Should sets be looked up by a second request using the `beatmapset_id` of the response or is the entire set supposed to be included in this response?

**Comment by peppy** [comment]
In other words, we need to decide whether we should be doing a second API request to get full `beatmapset` details from a `beatmap_id`, or whether `get_beatmap`'s return should include it from the get-go.
