### ISSUE TITLE
[Wiki] Add scrollable tables

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2630]
![](https://puu.sh/zBEDZ/59f24fd2c5.png)

Two bugs in this picture

1. Flags in the first table become that small, that they are invisible
2. Some tables might break the page width

**Comment by nanaya** [comment]
A link to the page would be useful.

**Comment by TPGPL** [comment]
osu.ppy.sh/wiki/OWC2014

**Comment by nanaya** [comment]
Turned out a bit more annoying than expected.

(though now I think again, a simple `str_replace` could probably a working hack)
