### ISSUE TITLE
Use different icon for shortened difficulty list

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2632]
![](https://puu.sh/zBGPg/d0d1bbe4b8.png)

Should be changed, because there aren't 17 extra diffs. 

https://osu.ppy.sh/beatmapsets/325158#osu/735272
https://osu.ppy.sh/beatmapsets?q=MIIRO%20vs.%20Ai%20no%20Scenario

**Comment by nanaya** [comment]
The color only shows the highest difficulty. The counter is for mode.

**Comment by VenixOSU** [comment]
In my opinion, it would be nice to just count every difficulty in the spread separately, for example on this map:
(Easy icon) 3 (Normal icon) 2 (Hard icon) 3 (Insane icon) 4 (Expert icon) 5

**Comment by peppy** [comment]
@arflyte feedback plz

**Comment by arflyte** [comment]
Split and show the difficulty count individually.

**Comment by nanaya** [comment]
And then have it overflow again for maps with multiple modes and difficulties...

**Comment by TPGPL** [comment]
if it still overflows, then maybe use `mode: count`

**Comment by VenixOSU** [comment]
maybe use `mode: count` and while hovering on it show count for individual diffs in the spread.

**Comment by notbakaneko** [comment]
![image](https://user-images.githubusercontent.com/1694544/41408364-69a30806-700d-11e8-892b-b85833024a30.png)
![image](https://user-images.githubusercontent.com/1694544/41408404-873e0cc6-700d-11e8-8a36-f66a488fb6d4.png)
ಠ_ಠ

**Comment by nekodex** [comment]
This was assigned to @arflyte for design consideration because of that exact reason... (it's also why it wasn't implemented like that in the first place)

**Comment by arflyte** [comment]
![f151e871d5](https://user-images.githubusercontent.com/3632750/41457171-c44e8054-70bd-11e8-8813-aa242fb1a1d9.png)

Still trying to figure out on how to list everything for the current design. No solution yet so far.

**Comment by peppy** [comment]
@arflyte is this still valid? has it been addressed in the not-yet implemented card design?

**Comment by peppy** [comment]
@arflyte

**Comment by arflyte** [comment]
![Beatmap Card E](https://user-images.githubusercontent.com/3632750/59660521-ba41f800-91e3-11e9-9119-a51539203658.png)

Total of difficulties is totalled. Not sure if it's necessary to show the number of available maps available per difficulty. 

Using coloured dots to represent the available difficulties. On hover, it will show the number of maps per difficulty.

**Comment by Zyfarok** [comment]
Suggestion : You could make it look like a stack of points when there's multiple maps of this difficulty, so you intuitively know that there's more than one without hovering and you have an idea for which difficulty there's the most choice.

**Comment by LiquidPL** [comment]
I can implement this, however I have a question. Should the website show a regular, ungrouped list of difficulties when those can fit in the row without overflowing, or should it just display this new design regardless of how many difficulties there are?

**Comment by peppy** [comment]
@arflyte please advise

**Comment by arflyte** [comment]
![Figma_191106-122131](https://user-images.githubusercontent.com/3632750/68265654-09ec6780-0090-11ea-8d12-004539992511.png)

In the new design, it only displays map count. I'm still not sure how to display the list of each difficulty in a neat way.

**Comment by Joehuu** [comment]
Has since been resolved with the new design.
