### ISSUE TITLE
General (All Difficulties) and General tab names are misleading and confusing.

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2641]
Anyone I know not already familiar with it can and will get these two confused. What's the difference? Huh? And would accidentally post points for the mapset in the "General" tab.

Suggestion:
General (All Difficulties) -> General (Mapset)
or
General (All Difficulties) -> Mapset

and
General -> General (DifficultyName)

Where DifficultyName would be automatically replaced with Easy, Insane, Marathon, etc, whatever the current difficulty you are on is called.  (It would need to be truncated for extra long difficulty names of course)

I think this would make it much clearer what the difference is between the two, and prevent accidental misuse of the two tabs.

**Comment by shortthu** [comment]
Let's use beatmapset then

**Comment by peppy** [comment]
How about "Global"?

**Comment by LittleEndu** [comment]
Why not just remove the "General" and name the tab "All difficulties".

P.S. I haven't used modding v2 yet but it seems pointless to have two tabs for each difficulty. Why not have a section in the discussion for stuff that posters didn't include a timestamp for. Like have a "General issue" checkbox that would remove the timestamp. Then the tab names could be just "All difficulties" and "This difficulty".

**Comment by arflyte** [comment]
![83cb37ffbe](https://user-images.githubusercontent.com/3632750/37147326-ea9830d6-2309-11e8-9b70-546d9449558f.png)
