### ISSUE TITLE
Expose API for beatmapset events

### ISSUE THREAD

**Issue by Okorin** [ppy/osu-web#2642]
Since a lot of things that track what gets ranked and whatnot rely on webscraping old stuff or something stupid, just giving people an API with the contents that the beatmapsets/events route can contain would make a lot of people making apps to watch what is happening happier: 

- https://osu.ppy.sh/beatmapsets/events?type=nominate
- BeatmapSetsEventsController@index would need to drop the priv_check to BeatmapDiscussionModerate or do it with different conditionals only

probably only the functions nominate qualify, disqualify, approve, rank, nomination_reset though,  the other things in that model would probably require the BeatmapDiscussionModerate privs (at least seeing deleted/restored)

**Comment by cl8n** [comment]
the data requested in #4042 should be available in an events API as well.
