### ISSUE TITLE
Profile history graphs are offset by one month

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#2643]
Reported [here](https://twitter.com/jehlpxyz/status/971553565704642561). Have not confirmed.

**Comment by kj415j45** [comment]
![screenshot_20180308-115429](https://user-images.githubusercontent.com/18349191/37132193-89506786-22c7-11e8-8001-c29cbe5b67fb.png)
I'm sure I played nothing in March.

**Comment by kj415j45** [comment]
Yeah, in @MegaApplePi 's view, it's Jun . But in twitter one, it's Feb.

My Status:
Location: China

TimeZone: UTC+8 (Asia/Shanghai, known as BeiJing)
Browser: Chrome Dev 66.0.3356.0 | Android 6.0.1 | LG F460

**Comment by shortthu** [comment]
So guess this is probably some timezone problem
![](https://puu.sh/zD24i/c00ab8d588.png)
My timezone: UTC+7
