### ISSUE TITLE
Infringement lengths are rounded differently compared to the old site

### ISSUE THREAD

**Issue by LiquidPL** [ppy/osu-web#2659]
![image](https://user-images.githubusercontent.com/991831/37206434-eabb2ef8-2398-11e8-875b-c82c3f766a69.png)

![image](https://user-images.githubusercontent.com/991831/37206448-f355250a-2398-11e8-8ed1-c9a2a9f7ad95.png)

how are those rounded on oldweb anyways?

**Comment by jacksonisiah** [comment]
also noticing dates are rounded differently too.

> 40 hours ago
> a day ago

**Comment by peppy** [comment]
As you can hover this to see a precise timestamp, moving to backlog.

**Comment by nanaya** [comment]
Seems fine.
