### ISSUE TITLE
The "Stop Playing" button on the beatmap preview does not change colour

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2661]
https://streamable.com/73jaq

The play button turns yellow when hovering over it, the square does not. 
The square should turn white when it's not hovered over.

**Comment by LiquidPL** [comment]
I'm pretty sure that's because yellow's supposed to be the active (playing) color, while also being the hover color.

**Comment by Xinnoh** [comment]
When I'm trying to click the the square, it doesn't change colour. I was shaking my cursor around the button trying to click it earlier because there was no feedback when I was hovering over it.
There should still be some kind of feedback to let the user know they're hovering over the button

**Comment by LiquidPL** [comment]
hm, I suppose it should be better to have @arflyte take a look at it then.

**Comment by nanaya** [comment]
I think this has been fixed
