### ISSUE TITLE
permanently deleting a beatmap should require the deleting user giving a reason

### ISSUE THREAD

**Issue by Okorin** [ppy/osu-web#2662]
In addition i'd assume the action is logged already, so the QAT usergroup and higher should be authorized to view these logs on the page, because silences for inapproprate song contents are handed out after the user has received one map of leeway in case they didnt know how we handle this matter.

**Comment by peppy** [comment]
I can see the benefit of this, but I don't think it's high priority, right?

**Comment by Okorin** [comment]
well, currently we log stuff like this in google spreadsheets and that kind of sucks because data quality depends on all of us not forgetting to do it 

And then someone asks why "X was deleted" and we have to search through a bunch of things to find out why 

but apart from confusing us more or less regularly and being a bit more error prone, nope it's not mission critical but would just greatly simplify this stuff :D!

**Comment by peppy** [comment]
Added in ASS.
