### ISSUE TITLE
Add user option to pin plays to their profile

### ISSUE THREAD

**Issue by Toybickler** [ppy/osu-web#2664]
https://www.reddit.com/r/osugame/comments/835xwo/feature_idea_being_able_to_choose_what_plays/

Has been brought up before as well, wanted to bring it to github in case you weren't aware that it could be a neat little addition to optionally show off cool scores that aren't high pp plays.

**Comment by peppy** [comment]
This is planned, but will come a bit later on.

**Comment by ronfarkash** [comment]
I thought about it as well yesterday by chance and got told this was already suggested, as it seems it's a feature a lot of people want. Is there anything I can do to push this into being developed?
https://www.reddit.com/r/osugame/comments/jfxnzk/osu_profile_suggestion/

**Comment by Gamingzone123** [comment]
related to #8442
