### ISSUE TITLE
No video download links can sometimes download videos

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2673]
https://streamable.com/9r9qm
https://osu.ppy.sh/beatmapsets/720402#osu/1520991
both are 29mb, which is the size with a video

**Comment by nanaya** [comment]
Looks like the old site also links to same file for no videoo.

**Comment by peppy** [comment]
This has been fixed now (mp4 files were not being stripped). Note that it may not instantly apply due to maps being cached.
