### ISSUE TITLE
"beatmapset activities" page should be visible for Beatmap Nominators 

### ISSUE THREAD

**Issue by lassem22** [ppy/osu-web#2675]
referring to this https://osu.ppy.sh/users/896613/beatmapset-activities

Right now it is apparently only visible for QAT (and probably GMT). 
Making it visible for BN would make sense since it helps tracking things like suggestions that received kudosu, which bn are able to deny in case they aren't justified etc.

**Comment by peppy** [comment]
I'd hope we can get this fully public, actually.
