### ISSUE TITLE
Hide map sections if a user has 0

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2681]
On the old website, the drop down catergories for favorite/loved/ranked/pending/graveyarded beatmaps would not display if a user had 0 maps in that catergory.
![image](https://user-images.githubusercontent.com/33286824/37297555-5b0bd470-25f4-11e8-8005-673d00337b74.png)
but on the new website it does.. this
![image](https://user-images.githubusercontent.com/33286824/37297571-62730f76-25f4-11e8-8d08-47b0516510a2.png)
Which is wasting space for telling you there's literally no information here.
If a user has 0 of every type like the example above, the beatmap section should be hidden in general, just like how the "Account Standing" section is not displayed if a user has no recent infringements.

**Comment by jacksonisiah** [comment]
I don't think the whole thing should be hidden.
possibly make drop-down arrows for each individual section.

**Comment by Xinnoh** [comment]
agree, rather than hiding it should just be made smaller in general

**Comment by peppy** [comment]
Needs further discussion, but definitely should be improved. Will go through this with @arflyte.

**Comment by tybug** [comment]
Any update on this? Still an issue

**Comment by nanaya** [comment]
Hi @arflyte, can you check on this. I don't see it being changed on new design either. If anything, the new design seems to be missing the different sections.

**Comment by arflyte** [comment]
will look into this and update it today.

**Comment by arflyte** [comment]
![Figma_200825-162522](https://user-images.githubusercontent.com/3632750/91144977-bc5cec00-e6ef-11ea-93ff-3ea633f72ad4.png)

"None yet" removed, as it's unnecessary, and add 0 count to the header. That'll save space.

Figma link: https://www.figma.com/file/YIVQm9d6pvOemHsdjq6j9w/Web-Profile-Page-Proposal?node-id=0%3A1
