### ISSUE TITLE
Transparent avatar has no gray bg on usercard

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2682]
Usercards don't have that gray square behind the avatar. Strongly disagree with no transparent avatars and png to jpeg stuff, but wanted to keep consistency with everything.
![](https://puu.sh/zGkBT/e25e38e712.png)
![](https://puu.sh/zGl9A/642c272412.png)

**Comment by arflyte** [comment]
All transparent avatars should have a grey bg.
