### ISSUE TITLE
Bold text is almost identical to normal text

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2683]
https://osu.ppy.sh/community/forums/posts/6535924
![screen shot 2018-03-13 at 11 12 50 am](https://user-images.githubusercontent.com/30382015/37320605-7fc3467a-26af-11e8-9ebc-5f84d92d9d93.png)

**Comment by Joehuu** [comment]
Mine looks better, using chrome.
![](https://puu.sh/zGskA/6390d36a33.png)

**Comment by Xinnoh** [comment]
I'm on osx, build:
Version 64.0.3282.186 (Official Build) (64-bit)

**Comment by peppy** [comment]
Again, this is a font and/or browser rendering issue. Apart from choosing a different font, there's no real solution. It looks fine on safari on macOS and chrome/firefox on windows, so I think it's fine.
