### ISSUE TITLE
No tooltips on joined date on forums

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2691]
Closes #2607.
![](https://puu.sh/zHgQZ/824a2212cf.png)

Already shown with these titles, but not the same tooltip as profile.
![](https://puu.sh/zHgQy/841867f0af.png)

Doesn't show.
![](https://puu.sh/zHgQN/898210d31e.png)

**Comment by Joehuu** [comment]
I think you mistake this as a PR.

**Comment by peppy** [comment]
the fuck are you doing
