### ISSUE TITLE
History navigation buttons don't work as expected

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#2696]
- Go to a beatmap page
- Scroll down to scores a click a profile
- Scroll down in profile
- Hit back button
- *page scrolls to top of page unexpectedly*
- *page does not scroll to where you were scrolled to*
- Hit forward button
- *page scrolls randomly*
- *page does not scroll to where you were scrolled to*

![Pasted Image 1.gif](https://shipusercontent.com/63ed03d1372bbe946dd7f4c1e970d90d/Pasted%20Image%201.gif)

This happens in basically all navigation site-wide and needs to be fixed as highest priority. In my eyes it makes the site frustratingly unusable.

**Comment by nekodex** [comment]
"fixed"  - peppy
