### ISSUE TITLE
Add google analytics support

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#27]
- Should be able to specify a GA identifier in .env.
- Should use latest include method (async load) and match the way other js is being handled in this project as closely as possible.
- Should only be used when present.

Should be a fun task for someone looking to get familiar with the framework.

**[Bounty](https://goo.gl/nFdoyI) offered**: 5

**Comment by nanaya** [comment]
It's probably too easy.

**Comment by peppy** [comment]
go for it :8ball:

**Comment by nanaya** [comment]
whoops, almost forgot about turbolinks \o/
