### ISSUE TITLE
Changelog page has incorrect user counts

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#2700]
Currently only the latest build from each stream is shown. This means that the user counts don't add up correctly.

old:
![Pasted Image 1.png](https://shipusercontent.com/620912b82ad8b1243b2cbcafa58a803a/Pasted%20Image%201.png)

new:

![Pasted Image 2.png](https://shipusercontent.com/52e8ad73d5742c1b0645c11fd77f248f/Pasted%20Image%202.png)

Around 3,000 user are missing (which are on the previous version of stable). We should still have all the counts on this page add up to the total users online.

**Comment by jacksonisiah** [comment]
should the users on the old version show up in the previous stable user count? (doubtfully)

or would a new user count element for old releases be better? something that might look like this?

![68747470733a6572636f6e74656e742e636f6d2f3532653861643733643537343263316230363436293474r37927947932d432](https://user-images.githubusercontent.com/34609781/37499699-7d5b6ca8-289b-11e8-8e2f-0da73df6f88e.png)

(this isn't a final design or anything, just wondering what the aim of design would be.)
