### ISSUE TITLE
"Estimated to rank" doesn't account for the recent change to the ranking process

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2703]
https://osu.ppy.sh/beatmapsets/734616/discussion

Expected to be ranked 12 days from now, but there's only a dozen taiko maps qualified

**Comment by Xinnoh** [comment]
can this be bumped because I'm seeing people complain about this way too often

**Comment by peppy** [comment]
It's already in the march milestone. It will get done.
