### ISSUE TITLE
When map preview is playing, do not display video icon and rank status labels

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2706]
![image](https://user-images.githubusercontent.com/33286824/37502787-38bec35a-28ab-11e8-83f6-902527c4be08.png)

Otherwise, this happens when you stop hovering your mouse over the map's panel. 
The stop preview icon stays because the preview is playing, and the video icon + ranked status will return because they only disappear upon hover.

It looks terrible.

**Comment by notbakaneko** [comment]
You can tell we don't see very many video icons
