### ISSUE TITLE
Russian font may be suboptimal

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#2716]
<img src='https://shipusercontent.com/fabc88f85040df86b21cef3844dc6fd0/Pasted%20Image%201.png' title='Pasted Image 1.png' width=669>

```
For some reason, the new website displays "и" as "u"
It's pretty weird, because when you copy that weird "u" and paste it somewhere, you can see that it's actually an "и", so it only displays it like this.
```

Forwarded report from email.

**Comment by LittleEndu** [comment]
Both are perfectly valid ways to write ``i`` in Cyrillic https://en.wikipedia.org/wiki/I_(Cyrillic)

Atleast everyone who can read would understand so there isn't any real reason to change it

**Comment by peppy** [comment]
Thanks.
