### ISSUE TITLE
Dashboard link missing in profile menu

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu-web#2717]
Is it called profile menu? I'm not sure how to call it.

Anyways, each category in there shows a few links and clicking on the category itself brings you to the first one listed. *listing* for beatmaps, *wiki* for help etc. The exception is home where the *dashboard* link seems to be missing.

![qq](https://user-images.githubusercontent.com/27222621/37553512-e35dd836-29c9-11e8-9e32-b6e6b25842c8.png)

**Comment by Joehuu** [comment]
If dashboard gets added under home, something needs to be removed. I think the nav box will expand if there are more than 5. In that case, team should be moved to a different menu, since it isn't in home but the wiki instead.

**Comment by notbakaneko** [comment]
`dashboard` is intentionally not listed:
- Users that are not logged in don't have a dashboard, they go to a different landing page instead.
- The dashboard/landing is considered the actual top-level "home" which is accessible via the logo or on `home` itself, whereas the first item for the other sections are pages under that category without a proper top-level page.
