### ISSUE TITLE
Flags are sometimes misplaced on the wiki tables

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2719]
![](https://puu.sh/zJvrX/29a8cd22f4.png)

https://osu.ppy.sh/help/wiki/Tournaments/OWC/2014 Organization header

**Comment by Joehuu** [comment]
It's always acts like that. The reason it looks like that on the organization header is because someone didn't space the name and the flag.

**Comment by TPGPL** [comment]
true
