### ISSUE TITLE
The hr line can be almost invisible on different page sizes

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2720]
![](https://puu.sh/zJvMS/e347c5a3e1.png)

https://osu.ppy.sh/beatmapsets/707811/discussion

**Comment by Joehuu** [comment]
Occurs everywhere that has this line. Seems to be there, but the color disappeared. Can occur at different zooms. Should change the title.
![](https://puu.sh/zJB9i/e8a9c44cce.png)
![](https://puu.sh/zJB7o/f49aa08ee9.png)
![](https://puu.sh/zJB1H/d9657fad7c.png)
![](https://puu.sh/zJB1Z/4f8e90cd13.png)

**Comment by Joehuu** [comment]
Can't reproduce now.

**Comment by nanaya** [comment]
Nice, it's fixed by itself, I guess :ghost:
