### ISSUE TITLE
egosearch on old forums should be ported over to new forums

### ISSUE THREAD

**Issue by Okorin** [ppy/osu-web#2731]
Threads you posted in having activity was the most useful event for me in my time ever on [this page](https://osu.ppy.sh/forum/search.php?search_id=egosearch) - it's a much more useful alternative to just getting a ton of emails and enables the user to follow threads more easily, previewing this in the new design suggests it's not existing so i think it should

**Comment by dorothy3242** [comment]
This missing feature has been previously addressed in https://github.com/ppy/osu-web/issues/2356
Though I do agree it's sorely needed

**Comment by Okorin** [comment]
oh oops, if that's already a thing then i'll go support that one

**Comment by peppy** [comment]
see #2059, already implemented and waiting review

**Comment by Okorin** [comment]
nah, egosearch lists threads you posted in by activity not things you posted, for what it's worth
