### ISSUE TITLE
Profile pictures are blurry on the new web

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2734]
Old web vs New web
Both versions load the 256 x 256 version, so something's up with how it's displayed
![screen shot 2018-03-19 at 2 48 59 pm](https://user-images.githubusercontent.com/30382015/37581715-b9bd6d68-2b84-11e8-9a75-094563144979.png)
![screen shot 2018-03-19 at 2 48 51 pm](https://user-images.githubusercontent.com/30382015/37581716-ba094b48-2b84-11e8-9834-87bccb4d4c38.png)

**Comment by peppy** [comment]
This is normal. It's called interpolation.
