### ISSUE TITLE
Github \ Exception \ RuntimeException (401) Bad credentials

### ISSUE THREAD

**Issue by Heniooo** [ppy/osu-web#2736]
Github \ Exception \ RuntimeException (401)
Bad credentials
   COPY
Application frames (13)  All frames (81)
80
Github\Exception\RuntimeException 
…/vendor/knplabs/github-api/lib/Github/HttpClient/Plugin/GithubExceptionThrower.php87
79
Github\HttpClient\Plugin\GithubExceptionThrower Github\HttpClient\Plugin\{closure}
…/vendor/php-http/httplug/src/Promise/HttpFulfilledPromise.php34
78
Http\Client\Promise\HttpFulfilledPromise then
…/vendor/knplabs/github-api/lib/Github/HttpClient/Plugin/GithubExceptionThrower.php88
77
Github\HttpClient\Plugin\GithubExceptionThrower handleRequest
…/vendor/php-http/client-common/src/PluginClient.php160
76
Http\Client\Common\PluginClient Http\Client\Common\{closure}
…/vendor/php-http/client-common/src/PluginClient.php174
75
Http\Client\Common\PluginClient Http\Client\Common\{closure}
…/vendor/php-http/client-common/src/PluginClient.php87
74
Http\Client\Common\PluginClient sendRequest
…/vendor/php-http/client-common/src/HttpMethodsClient.php203
73
Http\Client\Common\HttpMethodsClient sendRequest
…/vendor/php-http/client-common/src/HttpMethodsClient.php192
72
Http\Client\Common\HttpMethodsClient send
…/vendor/php-http/client-common/src/HttpMethodsClient.php61
71
Http\Client\Common\HttpMethodsClient get
…/vendor/knplabs/github-api/lib/Github/Api/AbstractApi.php109
70
Github\Api\AbstractApi get
…/vendor/knplabs/github-api/lib/Github/Api/AcceptHeaderTrait.php16
69
Github\Api\Repository\Contents get
…/vendor/knplabs/github-api/lib/Github/Api/Repository/Contents.php77
68
Github\Api\Repository\Contents show
…/app/Libraries/OsuWiki.php44

Help

**Comment by LiquidPL** [comment]
Could you specify what did you exactly do that caused this issue?

**Comment by Heniooo** [comment]
This issue is on every site website with github wiki.
Example sites: /home, /help/wiki/Welcome, /help/wiki/FAQ, /help/wiki/Rules...
User profile is also not displayed, there is only the header at the top, nothing more

**Comment by LiquidPL** [comment]
uh, is this on the official website, or when you run it locally on your machine?

**Comment by Heniooo** [comment]
I'm run this on VPS Debian 8 MySQL: 5.7 PHP: 7.1

**Comment by Heniooo** [comment]
[url=https://ibb.co/fvveec][img]https://preview.ibb.co/dNK5Kc/Screenshot_2018_03_19_22_53_38_179_com_android_chrome.png[/img][/url]

**Comment by LiquidPL** [comment]
Please generate a GitHub API token [here](https://github.com/settings/tokens) and set it in the *.env* file under the `GITHUB_TOKEN` key.

**Comment by Heniooo** [comment]
it has already been done

**Comment by Heniooo** [comment]
I run this page with the command
php -S 85.255.4.56:9000 in directory public and still an error with GitHub API

**Comment by kj415j45** [comment]
>try deleting `bootstrap/cache/config.php`;
--from @LiquidPL and me's chat history

**Comment by Heniooo** [comment]
it still does not work, I remove `bootstrap/cache/config.php;` :<

**Comment by peppy** [comment]
Please check the credentials you gave to your token. This is 100% an issue with how the token was created or entered in your config.
