### ISSUE TITLE
[code] is confusingly similar to [notice] in appearance

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2738]
Currently [code] looks nearly really similar to and can be  confused with [notice] surrounding text unless you put the two side by side. 

This could be improved by automatically labeling code boxes with a **Code:** text in front like the old forums do, to clearly indicate that.

![image](https://user-images.githubusercontent.com/33286824/37627739-4404602c-2bac-11e8-8667-de9ade3ed094.png)

![image](https://user-images.githubusercontent.com/33286824/37627732-3c5d357e-2bac-11e8-9933-f9ebb4f89cd5.png)

**Comment by peppy** [comment]
I dunno, why do they need to be discernible in the first place? Personally I'm ok with how it is.

@arflyte?

**Comment by arflyte** [comment]
I think the codebox is good as it is now. It might be updated to support the new design soon.
