### ISSUE TITLE
Opening a new tab or window on a language options returns a missing page

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2740]
Only the "not signed in" menu (not dropdown) is button.
![](https://puu.sh/zLrJM/57bf8b0b21.png)

**Comment by notbakaneko** [comment]
Please elaborate.

**Comment by Joehuu** [comment]
You can middle click or right click it and results in a missing page.

**Comment by Joehuu** [comment]
Seems the new navigation change fixed it, but still need to fix the signed out page.

**Comment by nanaya** [comment]
Already fixed.

**Comment by Joehuu** [comment]
The signed out language options can still open new tabs.
![](https://puu.sh/AqFbu/45581cb164.png)

**Comment by nanaya** [comment]
So that's what you mean by signed out page.
