### ISSUE TITLE
Add quicklinks to Private Message specific users

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2741]
Probably next to the flag like the old website?

![image](https://user-images.githubusercontent.com/33286824/37635616-0330057a-2bd3-11e8-8657-d58876154aeb.png)
![image](https://user-images.githubusercontent.com/33286824/37635622-08783804-2bd3-11e8-927d-7f8a8d96fc27.png)

These links, in the form of a little envelope icon, would automatically take you to the private messaging page with the recipient already filled in. This is very convenient for if you want to private message someone specifically. 
These links are missing on the new website, leaving you to manually go to the compose a new message page, add them as a recipient, triple check you spelled their username correctly, and so on....

**Comment by nekodex** [comment]
It's also on the usercard as part of the new PM system implementation.

However, because the new PM system won't be part of the initial site launch, a placeholder should be added and temporarily link to the old site's PM page for the time being.

**Comment by nanaya** [comment]
Rather redundant with message icon on user card already.
