### ISSUE TITLE
Missing details under user on forums

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2742]
Missing post count, ~online status, and supporter status.~
![](https://puu.sh/zLt2D/01ded59d77.png) ![](https://puu.sh/zLt3a/bdae6e2c76.png)

**Comment by VenixOSU** [comment]
Just to be sure those wings (?) around the avatar means the user is a supporter though I think it may be more clear.

**Comment by rodrigoelicer** [comment]
The 'wings' of supporter are cool, but as @VenixOSU said, something extra to make it clearer would help. Maybe adding 'osu!supporter' as text/image around there would give more feedback in that regard.

**Comment by notbakaneko** [comment]
You can hover over the username to get their usercard; I don't think frivolous user details should be repeated every post.

**Comment by Joehuu** [comment]
There is no posts count on usercard, so lets go with that.

**Comment by notbakaneko** [comment]
I'm not sure if post count is so important that it needs to be everywhere.

**Comment by peppy** [comment]
I do like the design presented [here](https://github.com/ppy/osu-web/issues/2741#issuecomment-374512540) for adding back post count and joined metadata.

I think being a forum, people tend to expect to be able to see this, and have nothing against adding it back.
