### ISSUE TITLE
Add a seek bar when previewing audio tracks on the featured artist listing

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2747]
Noticed, this when going through the tracks on the latest news post, it makes it much easier/enjoyable to quickly go through the songs and hear more of what they are, rather than just having to wait for parts to repeat for song progression

**Comment by dorothy3242** [comment]
This issue should be closed now as the feature was added.

**Comment by Xinnoh** [comment]
🎉

**Comment by Coppertine** [comment]
implemented via #5911
