### ISSUE TITLE
Post new topic button should be on top of forum page

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2753]
The old site had it on the top. The new site has it on the topic section. Pinned topics move the topic section to the bottom, so you have to scroll down to post a new topic.
![](https://puu.sh/zM2B3/86d5ae009e.png)
![](https://puu.sh/zM2AH/c204b96ca5.png)

**Comment by notbakaneko** [comment]
Having to scroll down to get to the new topic button is not an issue.

**Comment by dorothy3242** [comment]
It's an issue that the post new topic link looks extremely similar to the links to individual threads - so when its position is not consistent, it can be especially easy to overlook and make it ambiguous how to make a new thread. In the old forums it's a unique distinct button and it's always in the same spot.

atm it can feel a bit hidden, I always end up forgetting and looking all over the forum pages trying to figure out where it is "is it at the top? the bottom? left? right? wait, it's somewhere vaguely in the middle????!" before finally noticing it @_@

**Comment by Xinnoh** [comment]
that's a different thing, make a separate issue that it blends in too well

**Comment by notbakaneko** [comment]
"Button is hard to find" is a valid issue, "should be on top" isn't.
