### ISSUE TITLE
When a nomination is reset, it should say who reset in the history tab 

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2755]
The message at the top of this image has no user specified, the other messages below regarding nominations show who did what.

![screen shot 2018-03-21 at 12 07 06 pm copy](https://user-images.githubusercontent.com/30382015/37694253-9bdb330c-2d00-11e8-8188-552da7cd0053.jpg)

**Comment by nanaya** [comment]
I think it's fixed now.
