### ISSUE TITLE
"New Topic" button blends in + is difficult to notice.

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2756]
\o/

Right now the "new topic" button on the new forums can be hard to find.

It
- blends in with other topic links
- is not in a consistent position (due to appearing below subforums, below pinned threads, and above the rest of the threads)

This can result in a user needing to scan the entire page before noticing it being nudged somewhere oddly in the middle, making it ambiguous how to make a new thread. Or in the worst case, a new user may not even notice it's possible to make a new thread when it's being hidden in plain sight like this.

The old forum had a distinct button for new threads, and was typically at **both** the top and bottom left above everything else (except for a few forums where it's only on the bottom left, for some reason)

**Comment by peppy** [comment]
Agree it blends in.

**Comment by peppy** [comment]
@arflyte any updates? 5 months have passed, two milestones have been missed.

**Comment by arflyte** [comment]
![photoshop_180806-182014](https://user-images.githubusercontent.com/3632750/43708935-8bc409ea-99a6-11e8-9953-8e5dabebc61d.png)

'New Topic' button at the top and bottom of Topic listing. Button at the bottom is aligned to the navigation bar. Provide breathing space between Pinned Topic, Button and Pinned Topic.

The extra button of the right side is just a placeholder to future-proofing, just in case there's a future function.
