### ISSUE TITLE
New web font is hard to read, the spacing between letters/words should change

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2757]
On the old site, letters are touching each other very slightly. The distance of each space is about the size of a letter. This makes it easy to see each word as an individual and is easy to read
![screen shot 2018-03-21 at 12 42 20 pm](https://user-images.githubusercontent.com/30382015/37694857-64a29308-2d05-11e8-91f8-542c14c12425.png)

The new site has more distance between letters and less distance for spaces, the width of a space is less than a letter. This is much harder to read because it's not as easy to find where words start and end.
![screen shot 2018-03-21 at 12 42 16 pm](https://user-images.githubusercontent.com/30382015/37694858-64d2c406-2d05-11e8-97df-1af4bf16cc36.png)

New web needs more distance between spaces, and less distance between letters to be readable.

**Comment by nekodex** [comment]
You'll have to be more specific, there's a variety of different fonts used for different purposes across the site.

**Comment by Xinnoh** [comment]
The one I mentioned specifically referred to forum text, it's used in other stuff that's frequently read such as news posts.
https://osu.ppy.sh/forum/t/717700 vs https://osu.ppy.sh/community/forums/topics/717700
https://osu.ppy.sh/home/news/2018-03-20-featured-artist-track-updates

**Comment by nanaya** [comment]
This looks like with the old font. See if the newer one is better.

**Comment by peppy** [comment]
Closing this as very outdated and no longer relevant.
