### ISSUE TITLE
Cleared/Uncleared maps in Beatmap Packs can be hard to tell apart

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2758]
![image](https://user-images.githubusercontent.com/33286824/37695167-9a9f175e-2ca3-11e8-92c5-038993ed4440.png)

The shades of gray and green are very similar, the cleared ones do not stand out very much when looking at a list of maps in a pack as a whole.
It's difficult to skim over when trying to quickly judge what maps need to be played to complete a pack.

**Comment by arflyte** [comment]
![0c3bfe6dc6](https://user-images.githubusercontent.com/3632750/37956377-2aa402dc-31e6-11e8-8081-320041a8672f.png)

Added clear icons. Ignore the other mode icons.

**Comment by dorothy3242** [comment]
since the colors have been massively improved to actually have contrast, i don't think my original issue is present anymore
![image](https://user-images.githubusercontent.com/33286824/66015983-cc018f80-e4a2-11e9-9315-12875ad0d517.png)
