### ISSUE TITLE
The subscriptions page does not indicate what forum a thread is in

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2760]
![image](https://user-images.githubusercontent.com/33286824/37695519-663c409c-2ca6-11e8-97de-c47b22a6399b.png)
![image](https://user-images.githubusercontent.com/33286824/37695521-6c577a00-2ca6-11e8-8c43-f3c9d9db2e74.png)

Knowing what forum a thread is in can help give additional context as to what it's about when a thread topic alone is not enough to remind a user why they're subscribed to the thread to being with.

An idea is that the threads could indicate at the very least whether they belong to the 
**osu! / Beatmaps / Other / Language Specific**   
sections of the forums by having their unread indicators be the same color as the forum section they hail from, instead of being all the osu! section's pink color.

**Comment by arflyte** [comment]
Updated design for subscriptions. The forum colours are going away in the future, as the colours will be used to define something else soon.

![ab7efcf50a](https://user-images.githubusercontent.com/3632750/37889206-3c18b476-3106-11e8-8624-919789e20705.png)

**Comment by TPGPL** [comment]
should unassign
