### ISSUE TITLE
Decrease the wiki cache update time

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2763]
Currently it takes too long to update the wiki. Should probably be changed into instant updating?

**Comment by peppy** [comment]
Cache exists for a reason.

We could add webhooks to force updates, though.

**Comment by LiquidPL** [comment]
By webhooks you mean github webhooks on wiki push triggering the cache update, right?

**Comment by cl8n** [comment]
yep

might be easier to keep a local copy and git pull on new commits , instead of forcing cache updates

**Comment by LiquidPL** [comment]
Gonna do this one then.
