### ISSUE TITLE
modding watchlist email notification cooldown problems

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2766]
If you are actively on a map's modding discussion page as posts are being made, currently this causes your email to be flooded with notifications if the map is on your modding watchlist. There DOES appear to be a cooldown between notifications normally, but it doesn't work in these cases.

**Comment by nanaya** [comment]
Is this what's happening?

1. open beatmapset discussion
2. watch
3. wait until someone posts
4. receives email (with the discussion page still open)

?

**Comment by dorothy3242** [comment]
I haven't tested that case specifically, it's more like

1.) already have a map on your watch list
2.) open a beatmapset discussion
3.) wait until someone posts
4.) reply to posts as they come
5.) end up with a lot of notification emails by the time they're done
