### ISSUE TITLE
Make it more obvious that you have to hover the top panel in order to see the menu bar

### ISSUE THREAD

**Issue by x9x8x7** [ppy/osu-web#2776]
My first experience with the new site was mostly spent looking for the beatmaps button. It wasn't until after I accidentally hovered my mouse towards the top that I saw the menu pop up. It's not clear that you have to hover over this top bar in order to make the menu show up. 

Image of the menu I'm talking about, for clarity

![image](https://user-images.githubusercontent.com/35306061/37808518-0d86edc0-2e4b-11e8-8d75-d80fc40f0525.png)

Example of how issue could be resolved: Add a menu such as the one below, or another indicator.
![image](https://voli.s-ul.eu/GQ87xP4W.png)

**Comment by peppy** [comment]
This is being completely redesigned.
