### ISSUE TITLE
Remaining time of supporting missing from Supporter page 

### ISSUE THREAD

**Issue by AdamBurmeister** [ppy/osu-web#2782]
On the old osu! website when you click the supporter option it comes up with how long you have left of your supporter tag, But on the new website this feature is not there.

**Comment by jacksonisiah** [comment]
would you mind changing the title to `Remaining time of supporting missing from Supporter page` ?

**Comment by peppy** [comment]
Bumping priority of this, it is a very very common question being asked over the last week.

**Comment by nanaya** [comment]
I don't remember the conclusion of this one (where to put, how it should look like) so maybe @arflyte should chime in.
