### ISSUE TITLE
Qualifying should always remove leaderboards

### ISSUE THREAD

**Issue by Okorin** [ppy/osu-web#2787]
previously disqualified maps do not delete the leaderboards upon requalification.

[this map is an example](https://osu.ppy.sh/beatmapsets/702111#osu/1544643): the top score on it was set before this one qualified 

it nukes upon hitting ranked anyways but it can cause a ton of broken replays in case stuff is remapped and constellations where the top play of a newly qualified map is months old and doesnt make any sense potentially

**Comment by peppy** [comment]
Has been known for a while. Not a super-easy fix, but marking as high priority.
