### ISSUE TITLE
Avatar compression settings may be a bit too harsh

### ISSUE THREAD

**Issue by Okorin** [ppy/osu-web#2790]
no idea why you'd recompress it that noticably upon user uploading it (like at least i'd think people that upload pictures like that bother to some degree with the pictures themselves), but it even makes most avatars that are set through the new site be not sharp

didn't look at what the code does, but i uploaded a png and the thing that the site ended up putting there was a jpg compressed from 36KB original to like 6 or something dunno if that's _the_ saving but it certainly does make setting avatars a lot more annoying lol

is this because you enforce stuff that is uploaded to have a gray bg or is there a different reason, plus can that be reverted to at least somewhat resemble the old site's way of handling this?

**Comment by Xinnoh** [comment]
If you upload it below the file size limit, it remains uncompressed. Use https://www.osustuff.org/avatar-maker to avoid hitting the limit for now.

Some test uploads
New site, 256x256 https://a.ppy.sh/4236057?1521859603.jpeg
Old site, 256x256 https://a.ppy.sh/4236057?1521859630.jpg
New site, 700x700 https://a.ppy.sh/4236057?1521859674.jpeg

No difference between the first two, but uploading a 700x700 image results in compression.

**Comment by peppy** [comment]
Yep, this has not really changed from the old site (only improved to handle more cases). We can probably tone down the compression a small amount, but the logic is correct otherwise.

**Comment by Flanster** [comment]
I have no clue what are the requirements of filesize or resolutions at this point but the images I use are 128x128 and under 80kb at most cases. Yet they are still compressed.

# Input
PNG **52kb**
![](https://flan.s-ul.eu/1J0HKJTb.png)

JPG **20kb**
![](https://flan.s-ul.eu/rbGuXSgq.jpg)

# Output in both cases
JPEG **8kb**
![](https://flan.s-ul.eu/NRUOTpBq.jpg)

Compression artifacts are quite obvious. The original image is preserved if uploaded through the old site.

**Comment by peppy** [comment]
Sems like this could be an edge case (with small dimensions of upload)
