### ISSUE TITLE
Site bugging on modding discussion when ~2-8 comments are visible

### ISSUE THREAD

**Issue by Hiro3212** [ppy/osu-web#2792]
Video of the issue: https://gfycat.com/UnitedOrneryItalianbrownbear

I don't know if the problem only is the number of comments but it only happened to me when there were ~2-8 comments on the discussion. Then the site bugged really hard and parts were disappearing etc...

**Comment by peppy** [comment]
Could you please provide your browser and version?

**Comment by Hiro3212** [comment]
Google Chrome - Version 65.0.3325.181 (Official Build) (64-bit)

**Comment by notbakaneko** [comment]
This looks like a combination of the browser compositor and tile rendering acting up
