### ISSUE TITLE
You can't download replays from the userpage's top plays

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2797]
This star icon allows you to download an .osr file of that play
![screen shot 2018-03-24 at 1 19 46 pm](https://user-images.githubusercontent.com/30382015/37860698-132bb96a-2f66-11e8-8662-7b4b1ae005f0.png)

It's only for plays that are in the top 1000 of the leaderboard, but if its stored somewhere then might as well link it for all

**Comment by BowiePro** [comment]
New web user page is here, meaning you can now download replays!
