### ISSUE TITLE
An <a> tag with a wrong output in username changing page.

### ISSUE THREAD

**Issue by ExerciseBook** [ppy/osu-web#2798]
![test](https://user-images.githubusercontent.com/6327311/37864392-f5302430-2fa8-11e8-9daa-3567b6b90ded.png)

**Comment by AndyThePie** [comment]
I have no idea what I'm doing I'm so sorry

Looking at inspect element, it appears that the **<** and **>** are instead `&lt;` and `&gt;.`
Replacing them with the proper brackets seems to fix it.

**Comment by christopher-dG** [comment]
Looks like it's the same as #2793.

**Comment by notbakaneko** [comment]
fixed by https://github.com/ppy/osu-web/pull/2805
