### ISSUE TITLE
#1 score on leaderboard does not indicate how long it's been since it was set

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2799]
![image](https://user-images.githubusercontent.com/33286824/37866866-ce6c2598-2f66-11e8-8559-232ec2b7e3f1.png)
![image](https://user-images.githubusercontent.com/33286824/37866872-d5356204-2f66-11e8-97a1-f8d441d291a4.png)

The same applies for the listing of your own score that appears right below/next to the number one score thing.

Having a time since when it was set listed is cool, as it's like an invitation "can you beat this score that's been number one for so long?"
It's also good for knowing just by visiting a map's information page how long it's been since you set your own best score on a map.

**Comment by arflyte** [comment]
![ee073aa946](https://user-images.githubusercontent.com/3632750/37946790-47e7e9d6-31c2-11e8-998c-987f2bfd6ebe.png)

Add the date between the name and flag.
