### ISSUE TITLE
Long nicknames consisting of one word get cut

### ISSUE THREAD

**Issue by comentarinformal** [ppy/osu-web#28]
As Sulker@Slack noticed, nicks bigger than the current limit will get cut off on jizz forums, looking quite bad.

Short-term solution is easy: change the infobox from 120px to 140px. I don't know if there's people with bigger nicks than me, and if it would work in them, though.

**Comment by peppy** [comment]
Can you provide a screenshot or example link just for clarity?

**Comment by comentarinformal** [comment]
Sure thing: https://jizz.ppy.sh/forum/t/265602?start=3932241#forum-post-3932241

**Comment by peppy** [comment]
@arflyte this one needs your input.

**Comment by nanaya** [comment]
a bit confused with 'cut'. I think it's more like split. And that's how flyte decided few while ago iirc.

**Comment by lunafreya** [comment]
Is this resolved yet? Maybe we need to either resolve this immediately or close this outright.

**Comment by peppy** [comment]
For reference, this is what we're discussing here:

![image](https://cloud.githubusercontent.com/assets/191335/19301026/5d2bde0a-9098-11e6-82a1-d7b1acb8f71f.png)

**Comment by arflyte** [comment]
I'll look into this today and try to figure out something.

**Comment by arflyte** [comment]
https://puu.sh/rGesS/07a95c0595.png
https://puu.sh/rGexy/3d0ffcc7e5.png

Remove the side margins since it's center aligned anyway.
