### ISSUE TITLE
Suggestions for new forum page UI.

### ISSUE THREAD

**Issue by Kibbleru** [ppy/osu-web#2803]
This isn't really a bug, or issue, but some problems that imo should be improved on for the UI of the new forums page.

Not sure how to imbed image on github, but this summarizes most my concerns: https://i.imgur.com/TmE43dW.png

A possible solution could also be to move the navigation bar on the bottom vertically to the right side, since it seems like it's pretty much a fancier scroll bar.

The new forums looks really nice on mobile since the aspect ratio for mobile is about 2:1 height:width, however on an actual computer, alot of the navigation stuff covers up space for actual content.

Anyway, I'm definitely no expert on web design, so take it with a grain of salt, but these are my main concerns for the new site.

**Comment by nanaya** [comment]
Superseded by #4884.
