### ISSUE TITLE
User's colour doesn't appear on profiles in the skinny version of the site

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2806]
Deif has a green bar under his name because he's a gmt
it disappears when you set the website to be mobile size

![screen shot 2018-03-26 at 2 57 05 pm](https://user-images.githubusercontent.com/30382015/37891295-699ac7fe-3106-11e8-8d32-73a94f5dc63c.png)
![screen shot 2018-03-26 at 2 57 40 pm](https://user-images.githubusercontent.com/30382015/37891296-69d93066-3106-11e8-88c9-8ef981ac5d85.png)

**Comment by peppy** [comment]
@arflyte please advise

**Comment by Joehuu** [comment]
Not relevant anymore, since the user title has the color now.
