### ISSUE TITLE
Adding "Re:" on forum page

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#2808]
I'm pretty active in the forums and try to help as best as I can, but at the moment it's all a bit confusing to look at the forum page. It looks like there's a bunch of new threads though the most of them are just replies. I wouldn't click on every thread to check if it's a new thread or just a new reply from someone. On the old site peppy added that "Re:" and it makes it really easier to focus.

Old site (atm): https://lya.s-ul.eu/u1rZeBSC.png
New site (atm): https://lya.s-ul.eu/24d9xkhz.png - it literally looks like Death created this thread
New site (with Re: added): https://lya.s-ul.eu/AOOxAs2B.png

**Comment by peppy** [comment]
Hmm, I'll leave this open for discussion. I think it might make sense to add it back.
