### ISSUE TITLE
Using different colours for buttons to show meaning

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#2810]
Red can get used for the cancel-button, an orange for the reset-button, keeping blue for save. Otherwise I think you can fuck this up when you just clicked wrong once (eg. you wanted to click save but you hit reset instead) 

https://lya.s-ul.eu/U54rs55K.png

**Comment by peppy** [comment]
I agree that this looks not only bland but unintuitive at the moment.

**Comment by RockRoller01** [comment]
Isn't this already done as buttons now use green and red?

**Comment by Lyawi** [comment]
yes
