### ISSUE TITLE
error 502 on i.ppy.sh when attempting to load a freshly-uploaded image

### ISSUE THREAD

**Issue by KarBoy2314PL** [ppy/osu-web#2817]
every time an out-sourced image is pointed with the "img" bbcode, i.ppy.sh processes it and posts it to the database. However, recently I wasn't able to see them. Older images than this are visible, however.
New images fail to load and output error 502, sometimes 521

`[img]https://i.imgur.com/vGS5sEb.png[/img]`
this is the image in subject

reuploading the image in subject and pointing it with "img" bbcode is not working, because the image from i.ppy.sh will load, not the reuploaded source

EDIT1: https://osu.ppy.sh/community/forums/topics/721009

**Comment by jacksonisiah** [comment]
https://twitter.com/osustatus/status/978292300823412736

**Comment by peppy** [comment]
Was this a temporary thing? It probably was. Please re-open if this still happens.
