### ISSUE TITLE
Getting e-mail notifications from subscribed threads that are set to not send notifications

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2820]
![image](https://user-images.githubusercontent.com/33286824/37937901-9b160e88-3129-11e8-992d-f50e79c98c2e.png)

![image](https://user-images.githubusercontent.com/33286824/37937736-f3ed5742-3128-11e8-87ae-7d179afb9983.png)
I added these threads earlier as simply bookmarked, not set to send notifications, but now, hours later, I'm getting some notifications from them anyways.

Is the current stuff for toggling notifications just for display and not actually functioning yet...?

**Comment by nekodex** [comment]
@nanaya can you check this?

**Comment by nanaya** [comment]
Probably posted in old forum which doesn't check the mail flag yet?

**Comment by peppy** [comment]
Ah, I think that's my issue to fix.

**Comment by peppy** [comment]
This should be fixed now.
