### ISSUE TITLE
Forum Post Preview should stay the same size as the write tab

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#2822]
![2018-03-26_21-31-32](https://user-images.githubusercontent.com/33286824/37941618-1b07081e-313d-11e8-8e1b-0e6216a48b0e.gif)
Currently if you switch to the preview tab, it automatically makes it a height much higher than the default write tab,  initially scaling to fit the message before reaching a "maximum" before it itself is finally scrollable. This is very annoying as this means in order to preview your post, the rest of the thread content gets covered.

**Comment by nanaya** [comment]
It is so you can preview the post without scrolling too much. I didn't know people read the thread content when previewing own reply... (I don't)

**Comment by peppy** [comment]
I think the current behaviour makes sense?

**Comment by peppy** [comment]
@arflyte thoughts?

**Comment by nanaya** [comment]
I don't think this will be changed (and the proposed use case never made sense to me).
