### ISSUE TITLE
Mods on scoreboards are out of order

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2835]
https://osu.ppy.sh/beatmapsets/700945#osu/1483942
The order here is DT, FL, HD, HR, NC for some reason.
The format should be HD, HR, DT, FL else lots of people will be annoyed :x

Skipped the other mods for simplicity, but they're also out of order.

**Comment by peppy** [comment]
Could you please list the full correct order?

**Comment by Xinnoh** [comment]
NF - No fail
EZ - Easy
HD - Hidden
HR - Hard Rock
SD / PF - Sudden Death / Perfect
DT / NC / HT - Doubletime / Nightcore / Halftime
FI / FL - Fade in / Flashlight
SO - Spunout
1k - 9k - Mania keys for converts

Unsure about since they're unranked
RX - Relax
AP - Autopilot
AO - Auto
CN - Cinema
Score v2
Target Practice
