### ISSUE TITLE
The forum should automatically load new posts

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2838]
(without needing to refresh the page)
atm it doesn't, nor does it seem to indicate that there are new posts. Considering discussions are displayed real-time as they're posted in mod v2, this should be considered for consistency across how the site works as well. 

Also because it'd be cool since the forums are already in this new eternal scrolling format.

**Comment by peppy** [comment]
I believe this is the eventual plan.

**Comment by dorothy3242** [comment]
Oh wait, this is a duplicate of a really-long standing open issue, so I'll close this
https://github.com/ppy/osu-web/issues/225
