### ISSUE TITLE
Recommended difficulty star rating as a number

### ISSUE THREAD

**Issue by DLoomz** [ppy/osu-web#2840]
On the new site, there is the Recommended difficulty option (Beatmaps Listing) which is great, but I see nowhere the exact recommended difficulty star rating number, like on the old site. In my opinion it was informative, so I suggest it should appear on the new page too. (There's enough space for it too.)

**Comment by dorothy3242** [comment]
Duplicate of https://github.com/ppy/osu-web/issues/2565

**Comment by peppy** [comment]
Closing as duplicate of #2565.
