### ISSUE TITLE
Pagination on mobile causes page width to overflow

### ISSUE THREAD

**Issue by MegaApplePi** [ppy/osu-web#2843]
![image](https://user-images.githubusercontent.com/14264992/38065047-d33f50b4-32c6-11e8-8c85-5c907226baa5.png) ![image](https://user-images.githubusercontent.com/14264992/38065090-faa85a56-32c6-11e8-85dd-ab090cb21cb5.png)

On the left, you can barely see it, but the arrows are overflowing. On the right, same thing but the navigation is about the same colour as the background.

**Comment by TPGPL** [comment]
should be close as fixed

**Comment by peppy** [comment]
Fixed via https://github.com/ppy/osu-web/pull/4749
