### ISSUE TITLE
Rankings breadcrumb and page title are incorrect

### ISSUE THREAD

**Issue by kevinwlau** [ppy/osu-web#2845]
On the rankings page, selecting any criteria (Performance, Score, Country) will only show `rankings > performance` in the osu nav breadcrumbs. 

The `title` metadata incorrectly shows performance as well.

![image](https://user-images.githubusercontent.com/689163/38072473-08539588-32ec-11e8-9369-5de4b1f6d40c.png)

This occurs in the currently live website. I'm unaware whether this has been fixed in development.

**Comment by Joehuu** [comment]
This can be closed since there are no more breadcrumbs on navigation, but the tab names need work.
