### ISSUE TITLE
Add ability to view unplayed ranked maps

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#2846]
Old site had this option:

![Pasted Image 1.png](https://shipusercontent.com/98ec2aa5a82d4ef651e4d8ba6ae6efeb/Pasted%20Image%201.png)

We should add a `Rank Achieved: [None]` option to allow the same behaviour.

**Comment by notbakaneko** [comment]
the ever expanding options list
![image](https://user-images.githubusercontent.com/1694544/38236083-159743d6-375e-11e8-87e6-afd20861ab15.png)
