### ISSUE TITLE
Issue with font sizing

### ISSUE THREAD

**Issue by tatitatai** [ppy/osu-web#2849]
https://lya.s-ul.eu/wnuW4wyX.gif

That's my signature atm. I noticed that the last emote is way too small (which actually looks fine on the old page) and thought to change it to something higher than 50 and below 85. The .gif shows what'll happen

**Comment by MegaApplePi** [comment]
There are only three defined sizes `50`, `85`, and `150`. They can be found here <https://github.com/ppy/osu-web/blob/master/resources/assets/less/bbcode.less#L63>.

**Comment by Lyawi** [comment]
Okay, but 50 is still way too small for some reason. Not only in signatures

**Comment by cl8n** [comment]
fixed in #10112
