### ISSUE TITLE
Badges break profiles

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2853]
How to reproduce: Open any profile (Unsure what the trigger is)
Happens to me regardless of whether they have a badge or not
![screen shot 2018-03-30 at 4 52 20 pm](https://user-images.githubusercontent.com/30382015/38131726-bd2cd0c4-343a-11e8-913e-3cfacec7f83f.png)

**Comment by Lyawi** [comment]
Does clearing cache help? Chrome version?

**Comment by Xinnoh** [comment]
I've tried with Safari Chrome and Firefox on osx, and I've tried with Chrome on windows, and I've tried with my sister's computer. Probably not a local issue

**Comment by Xinnoh** [comment]
redeploy helped
