### ISSUE TITLE
Badge counter doesn't work on translations which are missing keys for badge counter

### ISSUE THREAD

**Issue by VenixOSU** [ppy/osu-web#2860]
![](https://venix.s-ul.eu/Ca71kVQy)
![](https://venix.s-ul.eu/IyOoDpp7)
Should be replaced with English when keys are missing I guess.

**Comment by nanaya** [comment]
Which browser is that and what's the urls?

**Comment by VenixOSU** [comment]
Google chrome, https://osu.ppy.sh/users/2757689

**Comment by nanaya** [comment]
Are you using some kind of content blocker? There should be a counter. This is how it's supposed to look like.

![](https://s.myconan.net/2018-03/firefox_2018-03-31_04-36-02.png)

**Comment by VenixOSU** [comment]
I am not using any content blocker or anything similar. Also, I tested it on Microsoft edge with the same result. Maybe it depends on the screen resolution?

**Comment by TPGPL** [comment]
@VenixOSU are you using English locale? The counter doesn't show on untranslated locales, I think

**Comment by VenixOSU** [comment]
oh okay, that's the thing
