### ISSUE TITLE
Logged in users can't see the number of total users/plays/etc.

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu-web#2861]

**Comment by peppy** [comment]
This is missing details. Not sure what you're referring to.

**Comment by LittleEndu** [comment]
The old site always has the stat displayed in the top right blue area. These stats, on new site, are only visible on home page for people that are not logged in.

**Comment by peppy** [comment]
This is intended for the new design. You can log out or use a browser in private mode to view the statistics.

There are also stats available on the home page for logged in users:

<img src='https://shipusercontent.com/d348642eba87bae5f96d5830a00e1fb8/Pasted%20Image%201.png' title='Pasted Image 1.png' width=376>
