### ISSUE TITLE
API page not accessible

### ISSUE THREAD

**Issue by Adrriii** [ppy/osu-web#2867]
When searching for osu API on google and following the usual link https://osu.ppy.sh/p/api we get redirected to the forums

(The page is still accessible at https://old.ppy.sh/p/api tho)

**Comment by Lolihunter1337** [comment]
![2018-04-01_05-16-17](https://user-images.githubusercontent.com/17437302/38169504-d806f1b8-356b-11e8-92ce-8e86c01ba74f.png)

**Comment by Adrriii** [comment]
Yup, that's what I said ^^ The issue here is that we should be redirected to the old website when visiting the usual URL

If that's not important the issue can remain open but I'd like to at least warn

**Comment by peppy** [comment]
Where does it redirect you to, out of curiosity? For me the page still loads.

**Comment by Adrriii** [comment]
Well now it redirects to the good page, but it used to redirect to the forum. Maybe a recent modification fixed it ? Anyway thanks :)

**Comment by peppy** [comment]
Nothing has changed.

**Comment by HoutarouOreki** [comment]
The issue is still present.

https://youtu.be/_CDWqrVBYh8

**Comment by InvisibleSymbol** [comment]
the website is accessible, you just have to wait a few seconds/up to a minute after logging in and retry. This behavior doesn't seem wanted tho.

**Comment by HoutarouOreki** [comment]
Definitely annoying having to tell users to retry until it works though.

**Comment by cl8n** [comment]
you need to use the site switcher in the bottom left so you aren't redirected to the new forum, or use old.ppy.sh instead (should probably use the latter for a link if you're instructing people to find their API key)

**Comment by InvisibleSymbol** [comment]
using [old.ppy.sh/p/api](url) just redirects you to the old forum instead of the new one, it doesn't fix the problem of having to reload the page multiple times.

**Comment by cl8n** [comment]
try clearing your cache then. it might be because you logged into the forum while visiting that page

**Comment by InvisibleSymbol** [comment]
https://kayo.moe/1ebF9gpd.mp4
New browser, everything cleared, old site.
Still not the correct behavior...

**Comment by cl8n** [comment]
I meant after you are already logged in, that does the trick for me

**Comment by InvisibleSymbol** [comment]
(new browser/nothing cached)
So it works instantly if you login (old.ppy.sh) and then access the api page (old.ppy.sh/p/api).

You get a wrong redirect (to the forum) if you login on the api page (old.ppy.sh/p/api) but after that it works instantly.

If you login on the new site and open the api page (osu.ppy.sh/p/api) it asks you to login a second time, but after that it works instantly.

So I guess clearing the cache makes it work instantly, but the redirects are still wrong... And having to clear the cache is also not a good solution.

**Comment by TPGPL** [comment]
http://docs.ppy.sh/ here's the documentation about the api, you can check it if you run into problems

**Comment by tybug** [comment]
http://old.ppy.sh/p/api and http://osu.ppy.sh/p/api now redirect to https://osu.ppy.sh/home/account/edit#legacy-api, so this issue is (finally) resolved.
