### ISSUE TITLE
Just some spelling mistakes in products

### ISSUE THREAD

**Issue by MasterBugPatch** [ppy/osu-web#287]
I was looking at the products and noticed a couple spelling mistakes,

- "auxillary" should be "auxiliary" in the Osu Keyboard Product
- "iphone" should be "iPhone" in all of the phone cases products.

That's all I noticed by looking, but I didn't search widely for them so it may or may not have more.

**Comment by peppy** [comment]
Fixed both of these; thanks for pointing out.
