### ISSUE TITLE
https://osu.ppy.sh/p/irc is missing

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu-web#2872]
As the title says the IRC login info page is missing ( havent found it here so sorry if its an duplicate )

**Comment by peppy** [comment]
Not sure if/where this will go.

**Comment by TPGPL** [comment]
it redirects you to forum if you are not logged in

**Comment by Lyawi** [comment]
you could put it somewhere as another category in the settings I guess

**Comment by GrilledCheeese** [comment]
Yea put this: https://osu.ppy.sh/p/irc
Here: https://osu.ppy.sh/home/account/edit

**Comment by peppy** [comment]
I'm not sure we need/want this on the new site as I'm not sure irc will be supported going forward. It'll most likely be something provided as an api service instead.

**Comment by cl8n** [comment]
I was going to try adding this to account settings (with some disclaimer about how IRC support won't be around forever) for sake of removing one more old site page, but some details are missing

- where irc passwords are stored
- how to generate a new password, if not random

**Comment by peppy** [comment]
I don't want this added to the account settings. I think we should probably just close this issue for now.
