### ISSUE TITLE
Pressing enter when replying to mods doesn't resolve

### ISSUE THREAD

**Issue by celerih** [ppy/osu-web#2875]
When replying to a mod, pressing enter to post the reply will not resolve the post in addition to putting the reply yet. Issue is more often you'd be closing an issue after replying to it than leaving it open, so it would be more practical to have pressing enter also resolve the issue. This would help make replying to mods quicker and more efficient.

**Comment by Xinnoh** [comment]
This feature disappeared after line breaks were introduced, it was a thing but it was broken by that

**Comment by AncuL001** [comment]
- enter to reply
- shift+enter to make a new line
- ctrl+enter to reply and resolve

This should be a pretty good solution
