### ISSUE TITLE
Add a mod icon for touchscreen

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2876]
+TD should also show up on leaderboards

**Comment by arflyte** [comment]
Design for current site.

![mod_touchdevice 2x](https://user-images.githubusercontent.com/3632750/38352642-dbe457e0-38ee-11e8-8104-74470e2d3b6c.png)

Design for the new site and client.
![5466877cc7](https://user-images.githubusercontent.com/3632750/38352827-65c78e50-38ef-11e8-9c7e-bddd087cd385.png)
