### ISSUE TITLE
Avatar: New site set a black box to circular or other shaped images

### ISSUE THREAD

**Issue by Ladwick** [ppy/osu-web#2879]
I searched throught the issue list so I sorry if this is a duplicate.
Well, actually I tried to upload a circle-like avatar in the new page with the current resolution **(257x257)** and it created a black box to the image, I don't know why this happens, but I uploaded the same circular image with old resolution **(128x128)** to the old site and it uploaded correctly.
(Sorry if the team is already working on this, and my super formal hispanic english)

[Actually this is in 257 res](http://fs1.directupload.net/images/180401/2e7ewdno.jpg)

**Comment by MegaApplePi** [comment]
related to #1832
I assume you are trying to upload a .png image (to achieve some kind of shape), but the new site will convert the image to .jpg which will add the black background against transparent pixels. If you don't want the background colour to be black, your best option would be to add in a background yourself.

**Comment by Ladwick** [comment]
Thanks =)
