### ISSUE TITLE
Providing a Local Translation

### ISSUE THREAD

**Issue by sandycorzeta** [ppy/osu-web#288]
Hey, i see some of your folder structures on resources/lang there is a country code based folder that has a content a full of php files filled with string array.... are those string available to be translated? i would likely to help to translate it on my local language. Thanks :D

**Comment by MasterBugPatch** [comment]
I believe that's what it's for, considering in many places code wise it uses Lang.get("directory"), here and returns the English message.

**Comment by marcostudios** [comment]
on the osu!localization page (https://docs.google.com/spreadsheets/d/1CFtMJZenkF9LZ_uji57GTDdkKGL78H-aVKKb1YC3GxQ/edit#gid=24) there's the web tab, i think when the osu!next website is done you can translate there

**Comment by TPGPL** [comment]
osu!next website will be probably able to translate on the localization page.
Close this issue.
