### ISSUE TITLE
Forum Subscriptions Suggestion !

### ISSUE THREAD

**Issue by rhalp10** [ppy/osu-web#2880]
Where can i see all of my forum comment like the  [old link ](https://osu.ppy.sh/forum/search.php?author_id=3267187&sr=posts) of forum comment post or other thread?
maybe you could add this on the Forum Subscriptions page

**Comment by dorothy3242** [comment]
You can access the equivalent of the page you linked by clicking on the post count on your profile.

**Comment by notbakaneko** [comment]
![image](https://user-images.githubusercontent.com/1694544/38183278-1c0381b0-367a-11e8-9055-47344a1af976.png)

Click the post count in your profile
