### ISSUE TITLE
Edited/deleted forum posts do not show up as so on the new site's user's post history; original posts are shown instead

### ISSUE THREAD

**Issue by Galkaan** [ppy/osu-web#2881]
Post edition/deletion status is not preserved between the sites.

[Example on the old site:](https://osu.ppy.sh/forum/search.php?author_id=1260879&sr=posts)

![image](https://user-images.githubusercontent.com/21173359/38177159-8d323116-35fc-11e8-9795-882e84a79566.png)

[Example on the new site:](https://osu.ppy.sh/users/1260879/posts) 

![image](https://user-images.githubusercontent.com/21173359/38177162-9f586216-35fc-11e8-86e1-852c9acfe9e8.png)

**Comment by Galkaan** [comment]
After some more testing it looks like there is a ~6 hours long delay before posts are updated in the history on the new site whereas it's instant on the old site. Is that delay intended?

**Comment by notbakaneko** [comment]
currently, yes.

**Comment by peppy** [comment]
Will this not be resolved by #2886?
