### ISSUE TITLE
Profile links under "Recent" broken on mobile site

### ISSUE THREAD

**Issue by asdf1337asdf** [ppy/osu-web#2882]
![alt text](https://puu.sh/zUgUp/fa328ade4d.png "Broken Link") ![alt text](https://scontent-iad3-1.xx.fbcdn.net/v/t34.0-12/29853035_598505093821790_1657692129_n.jpg?_nc_cat=0&oh=f5141a7ee6a8549465c54f1f7c1e24d2&oe=5AC40EA0 "Empty Page")

Clicking on a user's name under "Recent" while on their userpage leads to an empty page (even after loading is finished). Can replicate consistently on iOS 11.

**Comment by notbakaneko** [comment]
Can't replicate on iOS11

**Comment by nekodex** [comment]
Closing due to lack of information, please reopen if you're still encountering this.
