### ISSUE TITLE
Clicking 'reply' in a thread while not logged in (or without permission) should be more... helpful

### ISSUE THREAD

**Issue by nekodex** [ppy/osu-web#2890]
Two related problems here:
 - When scrolled to the end of a thread, the reply button doesn't appear to do anything (except change colour)
 - When clicking 'reply' mid-thread, a "Please sign in to reply." box appears with no obvious way to login.
 
Maybe disable the reply button in cases where the user is logged in but cannot post due to permissions (with tooltip explaining)... otherwise, show the login box?

**Comment by notbakaneko** [comment]
Clicking the reply button when at the end of the thread moves the focus to the reply box and stickies it, so I don't think disabling the button is an option. Maybe a more visible visual cue?

**Comment by peppy** [comment]
Probably check in with @arflyte as to how he sees this being handled.

**Comment by arflyte** [comment]
![9a951c9c0d](https://user-images.githubusercontent.com/3632750/41457483-c42340c8-70be-11e8-9d44-3fccf8cc4c49.png)

Clicking the button with open the login box. At the end of the thread, provide a link to the login box.
