### ISSUE TITLE
Add colors so that text won't get confusing (at least in poll)

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#2892]
Might changing

![chrome_2018-04-02_16-16-02](https://user-images.githubusercontent.com/32525896/38201051-19778b36-3697-11e8-8506-1b25447278dd.png)

to

![chrome_2018-04-02_16-55-52](https://user-images.githubusercontent.com/32525896/38201055-1d29b74a-3697-11e8-9cbe-4569536818f9.png)

I actually took a bad color here, it's not easy to see on that dark background. Something light-gray would be good or just having the font not bold I guess

**Comment by RockRoller01** [comment]
This should be closed, it is already done

![image](https://github.com/ppy/osu-web/assets/35633093/ad0e7868-62b3-418a-ab43-105fa61c9f02)

**Comment by Joehuu** [comment]
Seems a little subtle, but closing for now.
