### ISSUE TITLE
When there is a timestamp at the start of a post in General (All difficulties), it should warn the player where they are posting

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2900]
Almost no discussions that belong in General (All difficulties) start with a timestamp.
I accidentally posted a whole mod in the "General (all diffs) section again when I should have been posting in the timeline. This has happened on a number of occasions because there is no warning.

If there is a timestamp at the start of a post and the user isn't posting in the timeline panel, it should warn them that timestamps generally belong in the timeline, similar to the "someone else posted an issue at this time" thing
This would be really helpful to avoid posting mods in the wrong tab

Mockup:
![screen shot 2018-04-04 at 10 33 52 am](https://user-images.githubusercontent.com/30382015/38285675-ef073cd0-37f3-11e8-92ac-dfe47792f731.jpg)

**Comment by Xinnoh** [comment]
Someone suggested doing this which also works
https://benedictator.s-ul.eu/M6vI0Sgm

**Comment by notbakaneko** [comment]
Something like this? https://www.dropbox.com/s/digq4764i6h5824/Untitled.mov

**Comment by Xinnoh** [comment]
yes
