### ISSUE TITLE
Disqualifying a v2 map via v1 bugs the nominations

### ISSUE THREAD

**Issue by Raidencio** [ppy/osu-web#2905]
The map appears as it has 2 nominations but there is no "Disqualify" button available, so it is safe to assume that it's disqualified

map in question: https://osu.ppy.sh/beatmapsets/720081/discussion/1578829/general

**Comment by Xinnoh** [comment]
why was it disqualified in v1

**Comment by Raidencio** [comment]
because the mapper linked the v1 site and also the qat member is retarded

**Comment by Xinnoh** [comment]
Don't think this needs fixing, it's unlikely something like this will happen again + v1 is disappearing. It's easily fixable by just posting a problem to reset nominations (which has been done)

**Comment by Raidencio** [comment]
ok

**Comment by Raidencio** [comment]
reopening because now the nomination button is gone lol

**Comment by Xinnoh** [comment]
there is no nomination button when the mapper uploads a set marked as wip

**Comment by peppy** [comment]
This should be ok, right?
