### ISSUE TITLE
No "hover text" for Twitter and Facebook buttons in main drop-down menu

### ISSUE THREAD

**Issue by arkaderd** [ppy/osu-web#2908]
https://osu.ppy.sh/home

In the main drop-down menu of the new osu!'s site's layout, when you hover your cursor over the support button, it will display text directly above the button
![screenshot 6](https://user-images.githubusercontent.com/17171599/38348019-260f16c0-3854-11e8-8f16-094c1e052236.png)

However this is not the case with the two other buttons for both Twitter and Facebook. The two do not display any "hover text" when the cursor is put over them
![screenshot 7](https://user-images.githubusercontent.com/17171599/38348024-2d2391f2-3854-11e8-98d5-80bf1340ab21.png)
![screenshot 8](https://user-images.githubusercontent.com/17171599/38348026-2eebd774-3854-11e8-8316-f06bb59a2f37.png)

Not 100% sure if intentional or not, given that these are widely recognized platforms. Could add the text "support us on (Twitter)/(Facebook)"

**Comment by nanaya** [comment]
And then the whole thing is no more :dancer:
