### ISSUE TITLE
Getting symmetry in friendslist

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#2914]
I think by having the supporter tag heart symbol in an other place wouldn't look "that" messy.

![chrome_2018-04-05_16-52-30](https://user-images.githubusercontent.com/32525896/38373598-e98bcbd2-38f1-11e8-8495-4edef37bb0e0.png)

How about putting flag, friends button thingy, message button in a row (as it actually is) and the supporter symbol right after the name or something like that? Just to have some more symmetry.

**Comment by Fabricio20** [comment]
I would move the supporter badge after all the default buttons, since names can get big but the buttons are always default for everyone.

**Comment by Lyawi** [comment]
oh, yeah. makes sense to me

**Comment by TPGPL** [comment]
will be closed by #4232 ?

**Comment by roansong** [comment]
I believe this can be closed.
