### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#2916]
The new header is great but since then I think there are still things which could get changed:

![2018-04-05_17-54-19](https://user-images.githubusercontent.com/32525896/38377100-6d7abad6-38fa-11e8-83e9-219ee3309db3.gif)

- The osu! symbol and avatar circle is pretty close to the border. When you hover over the osu! symbol, it's already touching it and doesn't look good. This could get improved by moving everything in it a bit higher to the actual center.
- Flags look pixelated (?)
- Border around buttons look a bit of improvised. Are they needed?

**Comment by peppy** [comment]
The header is supposed to extend down into the page, which covers your first point.

If flags are blurry please bring it up in a separate issue.

Borders are part of the design, yes.
