### ISSUE TITLE
Add legacy support for forum kudosu display

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#2917]
Extremely similar to https://github.com/ppy/osu-web/issues/2814
This should be added so that future users can understand the context of what was going on in an older v1 thread, per post, and what was deemed worthy of kudosu. 
In the future if you looked at a thread, you'd have no idea who got kudosu or how much (1 or 2), even though the links to forum mods will still display on and effect a modder's kudosu history.

Since there's like, 10 years of history for this, should be done somehow.
possibly also a text message similar to what peppy said in the other issue.

**Comment by peppy** [comment]
Not sure we need this.
