### ISSUE TITLE
Blocked user list no longer accessible

### ISSUE THREAD

**Issue by Numailia** [ppy/osu-web#2920]
With the new friends listing page, there is no way to find or manage which users you blocked/ignore. on the old site this used to be accessible from settings > Friends/Foes, but now this link just redirects to the friend listing and doesn't show foes at all.

**Comment by peppy** [comment]
We haven't finalised how user blocking is going to work, but this definitely needs some kind of presence on the new site.

**Comment by nanaya** [comment]
It's been added to settings page.
