### ISSUE TITLE
Tooltip Broken on Edge

### ISSUE THREAD

**Issue by AncuL001** [ppy/osu-web#2926]
![applicationframehost_2018-04-06_15-56-16](https://user-images.githubusercontent.com/16044057/38412715-2f154cba-39b4-11e8-8f92-e105c2398bb1.png)
this doesn't happen when you are on the default y "position" of the page
![2018-04-06_16-06-04](https://user-images.githubusercontent.com/16044057/38412872-732b45f8-39b4-11e8-9619-68c8cd5ce328.png)

**Comment by AncuL001** [comment]
edge

**Comment by AncuL001** [comment]
![image](https://user-images.githubusercontent.com/16044057/38453360-995a2562-3a7e-11e8-8595-fa5d9047d9c4.png)
this also occurs in many parts of the forum, i just found out

**Comment by nanaya** [comment]
Seem to be only on edge.

**Comment by notbakaneko** [comment]
appears to be broken on Safari too
