### ISSUE TITLE
search bar without going to other page?

### ISSUE THREAD

**Issue by AncuL001** [ppy/osu-web#2927]
![image](https://user-images.githubusercontent.com/16044057/38413706-a65d0838-39b6-11e8-9d59-5110b54b38a8.png)
it'd be better if we can type things without going to other page (https://osu.ppy.sh/home/search)
https://i.imgur.com/xXY2PD5.png

also i have an idea to have a selection (all, beatmaps, players, forum, wiki) directly on this search bar as well

**Comment by peppy** [comment]
This is how it used to be, and how it will eventually be. Please wait to see the rest of the new design implemented.
