### ISSUE TITLE
Long URL links break when editting forum posts

### ISSUE THREAD

**Issue by TheMoMan** [ppy/osu-web#2930]
Sometimes when posting a URL, it will automatically get shortened using a "..." though the link will still work. However, when editting that post, it will edit from the shortened link which makes it forget the original link.

Example of this happening is [this thread](https://osu.ppy.sh/community/forums/posts/6566829) where something like 

https://osu.ppy.sh/beatmapsets/708763/discussion/-/generalAll#/184711

gets shortened to 

https://osu.ppy.sh/beatmapsets/708763/d ... ll#/184711 

where when editted, the link just becomes 

https://osu.ppy.sh/beatmapsets/708763/d

which leads to nowhere.

**Comment by nanaya** [comment]
Editing problem has been fixed. Short vs long is a matter of preference and anyone who want to shorten it can put it on a label on it instead of plain link, I think?
