### ISSUE TITLE
Missing migrations for osu_badges

### ISSUE THREAD

**Issue by LiquidPL** [ppy/osu-web#2933]
![image](https://user-images.githubusercontent.com/991831/38433184-36c5764a-39ca-11e8-9bf8-9c80e4755e07.png)

😕

**Comment by peppy** [comment]
Why are there not tests which cover this and catch it?

**Comment by LiquidPL** [comment]
Dunno, I always assumed that other devs have like the full database and sometimes forget to add a table to migrations.

Just grab the schema for me and I'll add it.

**Comment by LiquidPL** [comment]
So can I have that table schema?

**Comment by notbakaneko** [comment]
```
CREATE TABLE `osu_badges` (
  `user_id` mediumint(8) unsigned NOT NULL,
  `image` varchar(255) NOT NULL,
  `description` varchar(255) NOT NULL,
  `awarded` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`user_id`,`image`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;
```

**Comment by nanaya** [comment]
Added in #2952.
