### ISSUE TITLE
Tooltips displaying star rating does not consistently work

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#2936]
(in discussion drop down list for switching difficulites, as far as I've found)
More specifically, it seems to sometimes stop working after changing difficulties. And sometimes it stops working for a few difficulties, sometimes it stops for all of them.

🤷‍♀️

Video: https://www.youtube.com/watch?v=CYQJ1wYgSYk

**Comment by Joehuu** [comment]
Tooltips were removed and shows inline now, closing:
![image](https://user-images.githubusercontent.com/35318437/164968301-46543e9e-cbce-46f8-a282-1706e0c1aec3.png)
