### ISSUE TITLE
Forum main page's width is broken on Mobile

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#2937]
![](https://puu.sh/zY2eo/1882d0da44.png)

**Comment by peppy** [comment]
Please state phone OS/browser version

**Comment by peppy** [comment]
Also what part is broken here?

**Comment by TPGPL** [comment]
Android 7.0, Chrome 65.0.3325.109

**Comment by TPGPL** [comment]
U can see on the right side of the photo, the width is bigger than the layout

**Comment by flashwave** [comment]
this also happens in firefox 59.0.2 on windows, so it's not just mobile
![image](https://user-images.githubusercontent.com/5001057/38456933-535ef248-3a8a-11e8-996f-b4e50f7a3c6f.png)
