### ISSUE TITLE
Forum Thread Map Note Mods Must Be Clickable 

### ISSUE THREAD

**Issue by rhalp10** [ppy/osu-web#2939]
Hi, I notice this part on the new site that the notes cannot be click unlike on the old site you can click the note suggestions.
**OLD** 
![image](https://user-images.githubusercontent.com/13925864/38456245-21579fe0-3ab5-11e8-84e1-85c18891ee26.png)

**NEW**
![image](https://user-images.githubusercontent.com/13925864/38456240-1346a9b4-3ab5-11e8-93cc-223ca1098c29.png)

-----------
Maybe you should add <a>Clickable Link</a>  `osu://edit/'notes'`
` <a class="osu-timecode" href="osu://edit/00:20:539 (20539|2,20711|1) ">00:20:539 (20539|2,20711|1) </a>
`

**Comment by peppy** [comment]
We aren't adding backwards compatibility for the modding system for the time being.
