### ISSUE TITLE
First Place Ranks count

### ISSUE THREAD

**Issue by Toybickler** [ppy/osu-web#2941]
Would it be too troublesome to add a small metric that shows how many #1s you have since the new website only expands by 20 instead of 50 now.

https://i.imgur.com/AFPqPOX.png

Something like "First Place Ranks (362)" or something similar.

___________________________________________________________________________________________________________
Also I'm not sure why it still shows the map score instead of PP.

**Comment by peppy** [comment]
Hopefully this is a simple change (I think we are already retrieving the full result set anyway?).

Note the standardising of showing pp where available too.
