### ISSUE TITLE
[spoiler] BBCode broke

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#2943]
![chrome_2018-04-08_16-43-41](https://user-images.githubusercontent.com/32525896/38468860-075a2a76-3b4c-11e8-8ce9-0ae9c65a3a73.png)

Setting it from the old site seems to work and gets shown on the new page too, but setting it from the new site looks like this and gets shown broken on the old page aswell.

**Comment by BJPGameVideosITA** [comment]
can confirm,
![bbcode](https://user-images.githubusercontent.com/25528039/38628923-e43c1e1e-3db2-11e8-97d4-a12fc1476601.png)
doesn't work for supporters nor staff members either...

**Comment by Lyawi** [comment]
@BJPGameVideosITA: your comment is about [profile], actually not sure what you're talking about now..

**Comment by peppy** [comment]
Please provide more information. I have no idea what you're saying. How's it supposed to look?

**Comment by Lyawi** [comment]
@peppy 

Done from the new site:
![chrome_2018-04-12_09-42-53](https://user-images.githubusercontent.com/32525896/38663185-784291a0-3e36-11e8-85c2-b8b8958822bd.png)

Done from the old site (and how it's supposed to look):
![chrome_2018-04-12_09-44-04](https://user-images.githubusercontent.com/32525896/38663208-85df55e6-3e36-11e8-9633-db64828b962f.png)
![chrome_2018-04-12_09-45-00](https://user-images.githubusercontent.com/32525896/38663217-895d4d22-3e36-11e8-8d3e-edd4c7ed3eb4.png)
