### ISSUE TITLE
[Forum] Space Below Quote Is Too Far Away?

### ISSUE THREAD

**Issue by AncuL001** [ppy/osu-web#2947]
![image](https://user-images.githubusercontent.com/16044057/38474632-7665bf46-3bcb-11e8-860b-66be93bbabbc.png)
isn't the space a bit too big? it is imo but idk for everyone else

**Comment by Lyawi** [comment]
Thought the same, but it doesn't bother me too much

**Comment by AncuL001** [comment]
it's kinda annoying especially with posts with a lot of quotes but small amount of text in each quotes

**Comment by BJPGameVideosITA** [comment]
yeah, like when you want to reply to every single part of a message quoting small lines instead of the whole user's message and then reply to everything because in that last way you should do a point/dashed list every time you write something..

**Comment by peppy** [comment]
Tend to agree. Calling @arflyte.

**Comment by arflyte** [comment]
Must've missed it. Reduce it by half.
