### ISSUE TITLE
Behavior of mod rankings on beatmap score pages 

### ISSUE THREAD

**Issue by this1neguy** [ppy/osu-web#2950]
(pardon my inability to come up with a good descriptive title for this issue)
The expected behavior when I click the HD ranking button for a map would be to see HD-only plays for that particular map, but instead it shows all plays involving HD (inclusive of HDHR, HDNF, etc etc) [as shown here](https://i.imgur.com/LixUe7K.png). Perhaps include a functionality such as the osu!plus extension offers for old beatmap pages where you can click the icon for [HD-only plays](https://i.imgur.com/M34yqwz.png) and [add in other mods](https://i.imgur.com/BsqF4tW.png) by clicking them as well (even support the options together by [clicking one or the other of the icons twice](https://i.imgur.com/LJqaFbM.png))?

**Comment by peppy** [comment]
Tracking in #4674.
