### ISSUE TITLE
[Feature Request] Implement the use of service workers

### ISSUE THREAD

**Issue by LumpBloom7** [ppy/osu-web#2955]
A service worker when implemented correctly may improve page load times since important assets are cached.

A service worker can also open up the possibility of serving certain pages even while offline, eg. News feed posts, recent beatmaps, user profiles, etc.

Alongside that, a push notification system may also be added so users can receive notifications for the news feed or any bookmarked forum threads, maybe even beatmaps releases. Of course a choice should be given to users so they can choose what kind of notifications they may want to receive(or disable it entirely).

**Comment by peppy** [comment]
We already use workers for some workflows, though admittedly not everywhere it should be.

Are you prepared to look at moving more tasks to workers?

**Comment by LumpBloom7** [comment]
Was it? I remember not seeing any in the list of service workers in Chrome and Firefox, maybe it's just me being dumb.

I would like to help, but my web coding skills are far behind my software coding skills(and that wasn't any good to begin with).

I'll try to clone the repo see where I can help when I have the time and the patience to figure out what is what.

**Comment by peppy** [comment]
I was talking about server-side. I'm not sure we have much use for client-side. If you have a specific user case then please bring that up specifically in another PR.

Also I hear browser compatibility isn't that good yet.
