### ISSUE TITLE
Danish localisation issues

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#2960]
Reported on discord:

- In the rankings section charts gets translated to diagrammer which is technically correct but is different from what is meant here. It means a chart like economic charts or population chats. Suggested change: change this to "baner" this translates to "maps" and i think this will be a lot better.
- Fræmhævede artister (Fetured artist) fits but when you go to the page its title is "udvalgte artister" which translates to chosen artist. I would keep this as fræmhævede artister to make it less confusing.
- In the description of the fetured artist page there are a few issues main being translating "tracks" to "spor". Spor means a track but like a trafic lane/railroad. Change "spor" to "sange" since that translates to "songs" and makes more sence.
- A programming mistake was made on the fetured artist page in danish. Instead of telling the amount of songs the artist has it says ":tæl sange" which translated is "count songs" might want to fix that.

**Comment by tailsdk** [comment]
I have made translations on the parts that are very misleading to start of will need to make a longer edit fixing all translations on the other sites as well.

**Comment by tailsdk** [comment]
This issue should be fixed with the new changes

**Comment by tailsdk** [comment]
This issue is fixed
