### ISSUE TITLE
Forum Search filters

### ISSUE THREAD

**Issue by BJPGameVideosITA** [ppy/osu-web#2968]
It would be nice to have search filters in the new site meaning that you could search a username to view posts, threads, only links, images, etc...
Thanks; BJP!

**Comment by peppy** [comment]
You can already search forum posts for a specific user from https://osu.ppy.sh/home/search?mode=forum_post. We don't plan on adding image/link filters.

**Comment by BJPGameVideosITA** [comment]
Thanks anyway ;)
even if the posts search has no Threads category for users' posts it's still quite a good feature!
