### ISSUE TITLE
Value on the support osu! page is a bit unclear.

### ISSUE THREAD

**Issue by VenixOSU** [ppy/osu-web#2969]
![](https://venix.s-ul.eu/9Trppjcp)
Seems kinda messy for me, what about using "USD" or just "$" instead to make it more clear.

**Comment by BJPGameVideosITA** [comment]
Using only $ is not actually "real" 'cause the difference in nominal value between US$ and CA$ and for the what about "USD" as you can see other sites have this behaviour aswell:
[https://www.ebay.ca](url) - search for anything (it's not CA$ but C $ but is almost the same..)
[www.aliexpress.com/](url) - also search for anything (this has even US $ in their products' price even when visiting other country sites like me that I'm in Italy visiting it.aliexpress.com/ I still see prices in USD)

**Comment by VenixOSU** [comment]
So maybe space US$12.00 to get US $12.00, would look cleaner I think.

**Comment by peppy** [comment]
https://en.m.wikipedia.org/wiki/Template:Currency
