### ISSUE TITLE
New Site Sizes

### ISSUE THREAD

**Issue by BJPGameVideosITA** [ppy/osu-web#2970]
When on new site and using [size] to modify your text scale and use for example the "Small" size, when you like to use that font height again without using something else before it won't work at all because it remembers your last used scale and won't let you use that anymore unless using another before 'cause it thinks you're still in the "Small" size box so it thinks that doesn't make sense to use Small inside Small (even when you're outside the size box.

**Comment by Xinnoh** [comment]
Please write your issue legibly, I can't understand what is being asked

**Comment by BJPGameVideosITA** [comment]
I mean that if you want to make only two portions of the post with Small size you can't select Small again without selecting (and deleting) anything else before because it thinks it's still in Small:
[https://youtu.be/u-mFfk4iq58](url)

**Comment by BJPGameVideosITA** [comment]
Thank you so much guys. now it works perfectly!
Hope it helped, BJP.
See ya.
