### ISSUE TITLE
Rename 'Rank Status' sorting to 'Categories'

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#2990]
First of all, `Any`, `... & ...`, `Favourites`, and `My Maps` are not statuses at all. WIP is not there, but is on the `Pending` category.
Even ppy thought the name of RankStatus in lazer needs changing.
> RankStatus was never intended to be categories.
Call it BeatmapSearchCategory

![](https://puu.sh/A1C5H/04ff2ea5bd.png)

**Comment by nekodex** [comment]
Those sections/filters were directly ported from the old site... I'm thinking that entire area needs a redesign.

**Comment by Joehuu** [comment]
Duplicate of #3367. Worded in a different way, but this section will change from this issue.

**Comment by peppy** [comment]
"Approved" should be removed. Pending should probably be renamed to "Pending & WIP"
