### ISSUE TITLE
Reply and Resolve button is the wrong size

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#2993]
![screen shot 2018-04-13 at 10 23 24 am](https://user-images.githubusercontent.com/30382015/38713659-dceeb18c-3f04-11e8-95da-0b2d2ab13d61.png)

after clicking reply
![screen shot 2018-04-13 at 10 23 45 am](https://user-images.githubusercontent.com/30382015/38713660-dd1e44ce-3f04-11e8-88ad-85871c46e6b2.png)

**Comment by peppy** [comment]
Just in case, what browser are you seeing this on?

**Comment by Xinnoh** [comment]
chrome, bug appeared without grammarly enabled too
