### ISSUE TITLE
Usergroup descriptions are displayed wrong

### ISSUE THREAD

**Issue by Nath789** [ppy/osu-web#2999]
The forum home's subtitle is displayed instead of the usergroup descriptions.

**Global Moderation Team**
![image](https://user-images.githubusercontent.com/5668486/38725670-a2b098a6-3f3a-11e8-82ca-e1d1a823863a.png)

**Support Team Redux**
![image](https://user-images.githubusercontent.com/5668486/38725627-86ee5068-3f3a-11e8-8e3e-07a863e0e987.png)

**Comment by Nath789** [comment]
Oops never mind. Caused by the dark theme. *Stares at Flan*

**Comment by Flanster** [comment]
My bad, had no idea the element was used in other pages. Will update the style.
