### ISSUE TITLE
Add an option to choose how dark userpage covers are

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#3011]
There's currently a darkening filter on all userpage covers. The darker colour is good for not standing too out from the other information, but it's kinda limiting on the depth/contrast we can see.

The best solution is to have an option to choose how much of a darkening filter is applied to your profile picture. Covers that have a dark colour scheme would look much nicer if there wasn't an additional pointless darkening filter

**Comment by peppy** [comment]
Closing for now
