### ISSUE TITLE
Creating empty map submissions bug

### ISSUE THREAD

**Issue by Smowokeman** [ppy/osu-web#3013]
I was trying to upload a map and got the and aerror message that my Tags where too long https://puu.sh/A2Y6K/3637ae722d.png. I tried adjusting it a couple of times till it went through and then i noticed this on my profile https://puu.sh/A39kV/1c5b44ee23.png (see the "(not title)" submissions). 
I didn't make much out of it until i looked this up https://puu.sh/A398k/a771697b3a.png . As you can see there a 3 shadow maps which come up when i search for my name. (they dont appear the new website doe)

i dont know if i shoudl be worried but, yeah just wanted to mention it.

**Comment by peppy** [comment]
Closing as wont-fix. This is an issue with how BSS interacts with ES and will be eventually fixed when BSS is migrated to newer code.
