### ISSUE TITLE
If you jump to the end of a thread, accessing the top menu is impossible

### ISSUE THREAD

**Issue by Okorin** [ppy/osu-web#3016]
go to any thread with over 25 (or whatever many it loads up at once) posts or something and then jump to the end, try to access your profile over the top menu.

The top menu will hide once you've scrolled up and see the UI to click on it it goes away making space for more posts to load

example thread to replicate these steps: https://osu.ppy.sh/community/forums/topics/719568?n=198

This is very frustrating because you can't even use the user interface until you've scrolled back up to post 1

**Comment by Okorin** [comment]
oh wait you can access it but by hovering the osu! logo

i didnt even get that idea until i explicitly tried to make the menu appear after being frustrated 
idk if this is the best way to handle it

**Comment by Lyawi** [comment]
To be honest, I wanted to report this too but haven't done this because I noticed it later then too... pretty sure this could confuse or tilt other people in the same way

**Comment by arflyte** [comment]
![navigation-bar---mini](https://user-images.githubusercontent.com/3632750/38865256-32c227e4-4278-11e8-8586-e1f95824e659.jpg)

A smaller version of the navigation bar, always attached to the top.

**Comment by TPGPL** [comment]
should be closed

**Comment by peppy** [comment]
Resolved via #3809.
