### ISSUE TITLE
Certain previous usernames not displayed

### ISSUE THREAD

**Issue by E223** [ppy/osu-web#3019]
Specific users are missing some or all of their previous usernames.

Ex:
[Flanster](https://osu.ppy.sh/users/447818) - Missing all previous usernames
[Toy](https://osu.ppy.sh/users/2757689) - Missing "[Toy]"

**Comment by peppy** [comment]
Said users probably made changes before we were tracking changes. I'll look at migrating these across.

**Comment by peppy** [comment]
I fixed these two cases. Seems isolated enough (I couldn't find a huge number of users which had legacy name changes applied). If further cases come up please add them in this issue or email me at pe@ppy.sh to have things fixed up.
