### ISSUE TITLE
Remove solid grey fill for transparent profile pictures.

### ISSUE THREAD

**Issue by mynasu** [ppy/osu-web#3027]
![image](https://i.imgur.com/E1d0KdD.png)

![image](https://user-images.githubusercontent.com/32518209/38892197-8c2bdde4-4254-11e8-816f-c9e75e02b0e4.png)

The completely solid grey doesn't work well at all with the rest of the design elements used on the website.

Something along this line would fit a lot 
better in my opinion:  

![image](https://i.imgur.com/aMxx0l5.png)

**Comment by arflyte** [comment]
I think this was mentioned before, and the answer is still the same: Transparent avatars are not suitable for the website as there are many other areas where the frame of the avatar is part of an important design for the page.
