### ISSUE TITLE
The ` character doesn't take any space

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#3040]
the screenshot has a lot of `
![screen shot 2018-04-19 at 9 03 21 pm](https://user-images.githubusercontent.com/30382015/38993076-2b873d68-4415-11e8-9497-265b2e255268.png)

**Comment by shortthu** [comment]
Look like only modding discussions and search have this bug

**Comment by MegaApplePi** [comment]
It's a font issue with Exo 2, I think the author intended the gravemark to be used like this:
![image](https://user-images.githubusercontent.com/14264992/38994391-e22a583a-43ab-11e8-98a0-132e79d6c06b.png)

**Comment by Xinnoh** [comment]
this was fixed by the referenced issue above

**Comment by TPGPL** [comment]
should be opened as not fixed

**Comment by Xinnoh** [comment]
o, it's fixed on modding discussion so I thought it was solved
![screen shot 2018-11-04 at 7 18 13 pm](https://user-images.githubusercontent.com/30382015/47963377-72140200-e066-11e8-8a2f-2c6bb8617d3e.png)
![screen shot 2018-11-04 at 7 18 36 pm](https://user-images.githubusercontent.com/30382015/47963378-72140200-e066-11e8-99a3-f93cee8aa874.png)

**Comment by Joehuu** [comment]
Can't reproduce.
