### ISSUE TITLE
All Recent Plays (24h) show 0pp

### ISSUE THREAD

**Issue by E223** [ppy/osu-web#3045]
With the exception of loved and qualified maps, which still show "-"

![Image of Recent Plays Section](https://i.imgur.com/IH5WCc9.png)

**Comment by peppy** [comment]
Missing something int he transformer?

**Comment by nanaya** [comment]
the scores table doesn’t contain pp whoops

**Comment by peppy** [comment]
We can probably join against the table which does and show where possible.

**Comment by notbakaneko** [comment]
Is this still happening? From the code, `0pp`s should always be showing up as `-` unless those `0`s weren't actually 0

**Comment by peppy** [comment]
What was the issue here? no common primary key between `scores` and `scores_high`?

**Comment by nanaya** [comment]
yes

**Comment by notbakaneko** [comment]
the 0s should have been fixed by #3047

**Comment by peppy** [comment]
```
`high_score_id` bigint(20) unsigned DEFAULT NULL
```

is now present in all (non-high) scores tables. will require a migration.
