### ISSUE TITLE
Beatmaps Listing does not show when a map was ranked/qualified

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#3055]
Old website does...
this is very good/important information for quickly telling how old a map is

**Comment by peppy** [comment]
Is this addressed in the new beatmap panel design?

**Comment by peppy** [comment]
@arflyte

**Comment by arflyte** [comment]
![Figma_200214-122440](https://user-images.githubusercontent.com/3632750/74498848-44825d80-4f25-11ea-86e7-ede588bfeb2d.png)

it's part of the new beatmap card design.

**Comment by NoffyNoffeh** [comment]
Was fixed with new beatmap card design
