### ISSUE TITLE
Save multiplayer match history (mp links) forever

### ISSUE THREAD

**Issue by DigitalHypno** [ppy/osu-web#3060]
Supposedly there was an update in mid February that added the ability to "keep match history forever automatically"

![](https://i.imgur.com/sbORehn.png)

However, match history links still expire after 1 month. https://osu.ppy.sh/community/matches/40738514 Here is an example of a match history link from 5 weeks ago; it is no longer available.

![](https://i.imgur.com/8avGy2S.png)

Was there an error with that update or are these links still supposed to expire after 1 month?

**Comment by WalterToro** [comment]
@DigitalHypno that update was for keeping the multiplayer results of matches done in the tournament server, matches done in main bancho are still being deleted after one month, still can be a feature but looking at the vast amount of multiplayer matches every day, i dont think _every mp result_ can be saved.
Something can be worked i think.

**Comment by peppy** [comment]
I'll look into the feasibility of this.

**Comment by peppy** [comment]
I've increase overall retention to 6 months and added a rule for tournament naming structure to keep matches indefinitely.
