### ISSUE TITLE
[Supporter AD] The AD box is not at center and too high

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-web#3062]
![image](https://user-images.githubusercontent.com/18349191/39090490-6e85771a-4613-11e8-9716-1e61c9b9280d.png)
![image](https://user-images.githubusercontent.com/18349191/39090500-9289a7a8-4613-11e8-966b-c6d93f6a5b35.png)

**Comment by peppy** [comment]
We should probably centre it in the mean time.
