### ISSUE TITLE
Performance points not appearing in Recent Plays (24h)

### ISSUE THREAD

**Issue by Trosk** [ppy/osu-web#3063]
The recent scores in `Recent Plays (24h)` will always show a `-` instead of the correct amount of PP, even when the maps are ranked. 

It also always says `Only ranked beatmaps give out pp.` when you hover the cursor over it.

![chrome_2018-04-22_11-56-54](https://user-images.githubusercontent.com/15179452/39093763-169cfd4a-4625-11e8-83a1-cbf3669ee5a0.png)

Edit: Related to #3045 ?

**Comment by tomatohentai** [comment]
Same thing's happening to me, except it seems like it only started after I played (but not finished) an unranked map. Before that it would just say 0pp. I don't really have a way to prove it was caused by playing an unranked map, though, this is just going off of what I sort of remember happening.
