### ISSUE TITLE
Add ability to disable topic cover per forum

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3064]
Handle "thread headers" (or however you want to call them) like signatures. For example, in the subforum "Help" newer people use them to show their screenshots of their issue, which is pretty hard to see (just like in https://osu.ppy.sh/community/forums/topics/735139 and other)
You also could have an option to enable/disable the header when creating your thread maybe? Just a thought.

**Comment by nekodex** [comment]
The "thread headers" are already optional? You can make topics without them...

**Comment by peppy** [comment]
I think this is saying it should be disable-able per forum (ie. for the help forum, where it doesn't really make sense to add "flair" to your post, and people are misusing it to upload screenshots they expect viewers to be able to see, only having them cropped and gradiented).

**Comment by Lyawi** [comment]
this is still an issue especially with help threads https://osu.ppy.sh/community/forums/topics/1764830?n=1
