### ISSUE TITLE
Mark sets that have an .osb as having a storyboard with the sb icon

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#3066]
Considering this is already with searching for .mp4 or .mov files for the video icon, I don't see why this can't be done for sets that have storyboards. Would be really handy since storyboards are far more interesting to look at from a mapper's perspective

There are some maps that have storyboards without an osb file, but they're really uncommon
eg https://osu.ppy.sh/beatmapsets/733211/#osu

**Comment by Joehuu** [comment]
The storyboard filter works now, but the beatmap mentioned in the description doesn't seem to be reading with a storyboard. Also, the referenced issue still needs to be fixed.

**Comment by Xinnoh** [comment]
Being able to detect storyboards for maps that don't use the .osb is too large of a scope for little result. Just detecting if there's a .osb will work perfectly for 99% of maps since storyboards only using the .osu is really uncommon.

Just needs something to identify videos separate from storyboards and it should be fine, may be an issue with the current design since some sets have both storyboard and video

**Comment by peppy** [comment]
Marking this as done. We won't be supporting .osu storyboard detection just yet, but it is planned for a future BSS revision.

**Comment by peppy** [comment]
Fixed. The current processing was best-effort, and as such some of the less popular beatmaps have not received processing (based on what is locally cached).

**Comment by VINXIS** [comment]
https://osu.ppy.sh/s/480298
https://osu.ppy.sh/s/764481
Found 2 maps that have .osb files and sprites and stuff (and the first one also being a mapset more on the popular side) but weren't marked as having an sb while I was collecting maps with sbs for [MCA](https://osu.ppy.sh/community/forums/topics/734377), should maps that have sbs but aren't marked be listed here/somewhere?
