### ISSUE TITLE
Qualified listing needs a sorting option reflecting the qualified queue

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#3072]
Beatmap Qualified Listing order no longer reflects the queue, because it is not directly related to the date it was most recently qualified now, due to the changes to how qualified works for v2 maps

This can be extremely confusing as it will make it look like a map has a week to rank or the same as those around it, even if it has fewer days left.
There is now nothing indicating on the listing how close a qualified map is to being ranked.

If it is added, this should be the default sorting for the qualified section.

**Comment by peppy** [comment]
Ah yep, this was an oversight. Will get it switched across.
