### ISSUE TITLE
Username history doesn't include all changes

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#3073]
on my own profile, for example: https://osu.ppy.sh/users/3666350

my name history goes
- One Mad Waffle
- Cl8n (supporter / free)
- cl8n (admin)
- zelda102 (paid)
- Cl8n (revert)
- clayton (paid)

so I would expect the history to show "One Mad Waffle, Cl8n, cl8n, zelda102". instead, the cl8n's are out-of-order and zelda102 isn't included at all

edit: I think it also may make more sense to display these names in reverse, with recent ones showing first. people are more likely to recognize recent names

**Comment by nanaya** [comment]
Reverted names are hidden.

**Comment by cl8n** [comment]
why? if anything, I'd want to hide that first name, lol

imo it should either be the user's choice what gets hidden or just don't hide anything except the automated "_old" stuff

**Comment by nanaya** [comment]
Mainly to hide inappropriate names.

**Comment by peppy** [comment]
You can contact accounts@ppy.sh if you would like a missing one restored.
