### ISSUE TITLE
listing country on profile twice is somewhat redundant

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#3075]
The "from" section is redundant with the flag, doesn't need to be there twice since you can hover over the flag to see the country name
![screen shot 2018-04-24 at 1 00 13 pm](https://user-images.githubusercontent.com/30382015/39167034-8083fd62-47bf-11e8-987b-d0c35d592afd.png)

**Comment by peppy** [comment]
@arflyte opinion?

**Comment by peppy** [comment]
We'll probably keep this for now. In the new design it's combined with other information and doesn't take up any extra vertical space.
