### ISSUE TITLE
90% view size in browser doesn't show diaeresis/tréma ( ¨ ) of ÄÖÜ

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3081]
*in forum. Other values seem to behave fine with this.

![chrome_2018-04-25_09-36-58](https://user-images.githubusercontent.com/32525896/39232264-04f0e968-486d-11e8-912e-6a3f483af728.png)

**Comment by peppy** [comment]
another exo issue? @arflyte

**Comment by nanaya** [comment]
The newer font (Torus) doesn't seem to have this problem.
