### ISSUE TITLE
Disallow double-posting on forum

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#31]
- Reply dialog should be visibly disabled with a message in its place telling user to edit last post if they want to add more content.
- A double post should be allowed after n days from original post (let's start with 3, but this is probably best a definable constant).

**[Bounty](https://goo.gl/nFdoyI) offered**: 60

**Comment by tewki** [comment]
Wouldn't a automated merge system be better user side wise?

Talking about merging the new post with the old one (Not making a new post then merging)

**Comment by peppy** [comment]
Automatic merging would probably work too. Not sure which feels better to a user. Most people would probably rethink/rephrase their last post if they were aware it was going to be merged automatically.

Having a link to enter edit mode in the last post from within the "can't-double-post" message is a must, though. Gotta make it accessible.

**Comment by Repflez** [comment]
I suggest going with disabling posting new replies in the thread if the last post was made by user and instead encourage it to edit their post. Editing it would bump the thread obviously.

**Comment by neico** [comment]
Bumping should only happen in interval's though, else people would abuse it to keep their favorite thread on top.

And I'm also for a auto-merge option, which each user can set on their own personal preference, something like:

Option: (checkbox) Enable auto-merge on double-post
Desc: Disabling this will disable the reply dialog as long as a reply would count as a double-post

**Comment by peppy** [comment]
No user-side options, please. We decide on what is best for the user for cases like this.

**Comment by dvcrn** [comment]
Are there any style mockups for disabled textareas and / or disabled buttons? 
I'm poking around with the code right now and ended up with 2 mockups

Just disabling the textarea and writing some text into it + hiding reply button:
![screen shot 2015-09-03 at 1 43 02 pm](https://cloud.githubusercontent.com/assets/688326/9650707/bd552f98-5241-11e5-991c-b4a9dba20bc2.png)

Like above but hiding the avatar as well. Feels more like a infobox by taking all control from the user
![screen shot 2015-09-03 at 1 42 23 pm](https://cloud.githubusercontent.com/assets/688326/9650701/a56d8a1a-5241-11e5-8bd1-3a2879217472.png)

Maybe giving the element that contains the text a smaller height and different color so it looks like a appended 'info/warning box'?

**Comment by arflyte** [comment]
Let's go with something like this 
![screen shot 2015-09-03 at 3 14 57 pm](https://cloud.githubusercontent.com/assets/3632750/9651687/c00ff206-524e-11e5-9a55-04e0122c6e85.png)

**Comment by nanaya** [comment]
let's not forget reply box is shown by default.

**Comment by peppy** [comment]
I'm assuming that notice replaces the reply box. Although it should probably read something more along the lines of "You have just posted in this thread! If you want to add more to your post, please <a href='#edit'>edit</a> your existing post!"

**Comment by nanaya** [comment]
I think it should be information (yellow? blue?) instead of alert (red).

**Comment by nanaya** [comment]
also need to think what to show when user click on reply link of a post.

**Comment by peppy** [comment]
yellow sounds good

**Comment by arflyte** [comment]
yeah, let's go with yellow.

**Comment by dvcrn** [comment]
@arflyte something like this? ![screen shot 2015-09-04 at 9 18 24 am](https://cloud.githubusercontent.com/assets/688326/9674015/38146b0a-52e6-11e5-90f5-61204cc65424.png)

**Comment by peppy** [comment]
The "edit your post" text should probably trigger edit mode for the user. The text doesn't look to be vertically centered, too. Other than that, looks fine.

**Comment by abraker95** [comment]
Going to just link this here: https://osu.ppy.sh/forum/t/354058

**Comment by peppy** [comment]
Increasing bounty to 60.

**Comment by Risers** [comment]
Claiming for 6 days

**Comment by Risers** [comment]
Double post should be allowed 3 days after last post or 3 days after editing last post?

**Comment by peppy** [comment]
3 days after last post sounds like the best option. also best to make it a config variable while you're there.

**Comment by Risers** [comment]
I've got 2 ideas how to do it. First: When somebody try to doublepost show a box with message (something like access denied error) and second remove message box and put there sth like "you just posted wait a bit or edit your last post"

**Comment by peppy** [comment]
removing the box is best, else the user will type a message and then be denied after putting in the work.

**Comment by ThePooN** [comment]
I believe it should be allowed if it's the guy who originally created the topic because he may provide useful updates, even if nobody else posted in the last 3 days. Forcing them to edit wouldn't notify those subscribed to the thread.

**Comment by Risers** [comment]
Will be done tomorrow

**Comment by Risers** [comment]
#424

**Comment by Risers** [comment]
I think that this issue may be closed

**Comment by peppy** [comment]
Thanks for pointing that out. Awarded you 60 boundy :+1:.
