### ISSUE TITLE
Make modding history somehow accessible from user profile

### ISSUE THREAD

**Issue by VenixOSU** [ppy/osu-web#3100]
That would be smarter I think since now we have to go to the discussion and then click on the button next to the username or add ``/modding`` to user profile page

**Comment by peppy** [comment]
The Kudosu! section needs a redesign for the new modding system. @arflyte have you done anything on this yet?

**Comment by peppy** [comment]
@arflyte @arflyte @arflyte @arflyte @arflyte @arflyte @arflyte @arflyte @arflyte @arflyte @arflyte

**Comment by peppy** [comment]
how do i even get this guy's attention 🙄 i've tried everything. should i just start posting designs for this stuff myself?

**Comment by notbakaneko** [comment]
added in #3937
