### ISSUE TITLE
Navigation bar loads too slow when scrolling fast.

### ISSUE THREAD

**Issue by VenixOSU** [ppy/osu-web#3101]
![](https://venix.s-ul.eu/gMNtepGT.gif)
Applies to almost every page.

**Comment by Lyawi** [comment]
Can relate and thought about reporting this too.

**Comment by shortthu** [comment]
Google Chrome, my current ver is 66.0.3359.139 64bit.
In Microsoft Edge (42.17134.1.0) it works fine.

**Comment by notbakaneko** [comment]
now the bar is always there (with different issues)
