### ISSUE TITLE
Change colour of modding history button depending on the discussion rang.

### ISSUE THREAD

**Issue by VenixOSU** [ppy/osu-web#3103]
Right now it's blue for everyone what looks nice with normal user colour, but looks kinda unpolished mixed with the colour of Nominator / QAT / Alumni / Mapper I think.
![](https://venix.s-ul.eu/Fz1LYrY4)
![](https://venix.s-ul.eu/DKBx5udb)
![](https://venix.s-ul.eu/6R2f8ms2)
![](https://venix.s-ul.eu/t4jehlmf)

**Comment by Lyawi** [comment]
I like it, though I recommend to use an other color instead of green since it's used for people of the GMT

**Comment by Joehuu** [comment]
Resolved with dark mode implementation (username always white, icon always gray).
