### ISSUE TITLE
Medals are showing up for modes you can't unlock them with

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#3109]
This medal requires you to FC [this map](https://osu.ppy.sh/beatmapsets/488238/) with DT. It appears on the medal tab for all modes, but only unlocks when done in standard mode. Doesn't make sense for a medal to appear in a mode you can't earn it with.

This applies to a few other achievements too

![screen shot 2018-04-28 at 12 59 51 pm](https://user-images.githubusercontent.com/30382015/39392181-0f17d400-4ae4-11e8-8f5b-2cb3f73ce103.png)
![screen shot 2018-04-28 at 1 00 12 pm](https://user-images.githubusercontent.com/30382015/39392183-1c904e3c-4ae4-11e8-9a88-6baed8c87c62.png)

**Comment by nanaya** [comment]
Missing mode column data setting in database?

**Comment by Ephemeralis** [comment]
This is functioning as intended. Not giving any further details to preserve the challenge of the medal. I suppose that's enough in and of itself.
