### ISSUE TITLE
Add Box Nest in Forums

### ISSUE THREAD

**Issue by ItsWilLad** [ppy/osu-web#3117]
It would be nice if we could Add a box into another box in osu!forums
So we can make a cleaner forum if we're gonna be adding a lots of text and images.
But I noticed it doesn't work
![ice_screenshot_20180501-141501](https://user-images.githubusercontent.com/38876324/39463411-7222b674-4d4a-11e8-9504-27138c1a4999.png)

Since My Forum was getting too long 
![ice_screenshot_20180501-142254](https://user-images.githubusercontent.com/38876324/39463543-27135188-4d4b-11e8-8434-e6cdf137c48f.png)
I was planning to make a Season Box :} My Season box is basically like an anime, 1 Season consists 10-20 episodes 

My Season Box consists 10 Parts which are these things
![ice_screenshot_20180501-142321](https://user-images.githubusercontent.com/38876324/39463560-392c6832-4d4b-11e8-9031-2a341ec681f7.png)
But since you still add a box inside a box, I'll be making 10 parts every forums

It would be great if a Box inside a Box would work ^-^

**Comment by Lyawi** [comment]
You're on the old page, the new page doesn't take so much place with boxes
![chrome_2018-05-01_08-36-28](https://user-images.githubusercontent.com/32525896/39463868-caeba4ee-4d1a-11e8-8030-20e9c22d45d2.png)
Putting a box into a box doesn't make sense and inconceivable to handle to me

**Comment by ItsWilLad** [comment]
I know lmao, but I think Adding a working box inside a box would be a nice feature if you're gonna make a really long forum
![ice_screenshot_20180501-161623](https://user-images.githubusercontent.com/38876324/39466378-1f2761c0-4d5b-11e8-848b-f6d2669f3e87.png)

**Comment by abraker95** [comment]
Isn't this possible now?

**Comment by nanaya** [comment]
Apparently so, somehow.
