### ISSUE TITLE
padding problems in some images

### ISSUE THREAD

**Issue by LinuxGamer** [ppy/osu-web#3121]
![image](https://user-images.githubusercontent.com/17398632/39501460-666b98c2-4d91-11e8-8d50-7c45053b51e4.png)
![image](https://user-images.githubusercontent.com/17398632/39501478-7bf0d252-4d91-11e8-8c8e-bd3c799690d4.png)

**Comment by peppy** [comment]
Could you please explain where this screenshot is taken (a full screenshot would help, rather than small crops)

**Comment by LinuxGamer** [comment]
it's in the profile icon

Em qua, 2 de mai de 2018 às 00:29, Dean Herbert <notifications@github.com>
escreveu:

**Comment by peppy** [comment]
What's the bottom screenshot? Why is only half of the avatar visible?

You are going to have to explain yourself.

**Comment by LinuxGamer** [comment]
it's the "profile settings" button avatar
![image](https://user-images.githubusercontent.com/17398632/39949714-f8e96940-5552-11e8-9579-528b3dfbf4ea.png)

It was in this place, but the glitch was already fixed.
 thanks for replying anyway

**Comment by LinuxGamer** [comment]
(you can still feel it a little while hovering over the image)

**Comment by peppy** [comment]
Closing as resolved?
