### ISSUE TITLE
Change "charts" to "spotlights" in rankings header dropdown

### ISSUE THREAD

**Issue by Toybickler** [ppy/osu-web#3128]
https://i.imgur.com/PmPNbOK.png

Charts have been renamed to Spotlights since January 2017, only seems right to correct it on the website as well.

**Comment by peppy** [comment]
Let's do this.

**Comment by Xinnoh** [comment]
Same for the titles on this page https://osu.ppy.sh/beatmaps/packs

**Comment by TPGPL** [comment]
gonna do that one
