### ISSUE TITLE
Quotation/prime (?) symbol break in text

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3132]
to be honest, I don't know how ´ and ` get called in English, so I searched around 

https://en.wikipedia.org/wiki/Quotation_mark
https://en.wikipedia.org/wiki/Prime_(symbol)
___
Actual issue:
![chrome_2018-05-04_19-52-54](https://user-images.githubusercontent.com/32525896/39643357-cbc0ef70-4fd4-11e8-94e6-29413c14b36d.png)
copying quotation marks look fine so actually idk how to call the ones from keyboard, but they break obviously (also prime?)

**Comment by peppy** [comment]
Font issue?

**Comment by shortthu** [comment]
Look like it's the same thing as #3040

**Comment by notbakaneko** [comment]
duplicate of #3040
