### ISSUE TITLE
No Birthday options in new profile settings.

### ISSUE THREAD

**Issue by tomdenty1** [ppy/osu-web#3149]
Also, trying to change this on the old website will result in the website saying 
"The name you entered is not a valid Jabber account name."
There are no options on the page for anything related to Jabber

**Comment by dorothy3242** [comment]
Duplicate of https://github.com/ppy/osu-web/issues/2175 ?

**Comment by MegaApplePi** [comment]
Did you set a value for Discord on the new site? If so, removing it on the new site then changing the settings on the old site fixes this problem.

**Comment by peppy** [comment]
Closing as duplicate.

**Comment by peppy** [comment]
I've fixed the old site to no longer error on updating profile settings.
