### ISSUE TITLE
modding v2 title/artist awkwardly high up

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#3159]
![image](https://user-images.githubusercontent.com/33286824/39849473-84265380-53da-11e8-9df8-770e89b9a860.png)

quite frankly, it looks very off.

I think it'd make a lot more sense if it were arranged something like this (shoddy editing aside)
![image](https://user-images.githubusercontent.com/33286824/39849818-2f092574-53dc-11e8-8f26-0c10303be790.png)
have the difficulty and user filter drop downs side by side, each taking half of what the current difficulty drop down does, title and artist where it used to be.

**Comment by peppy** [comment]
Your version looks more awkward to me.

**Comment by notbakaneko** [comment]
There's not enough space to cram everything into one line consistently without things getting chopped off.

**Comment by nekodex** [comment]
Difficulty names can get long... there's a reason the selector was placed up there 😉

![](https://puu.sh/AjuYp/f8eba8bc46.png)
![](https://puu.sh/AjuY7/3be94b306b.png)
![](https://puu.sh/AjuVI/bbb4a78926.png)
etc
