### ISSUE TITLE
Profile country/global ranking indicator text overlap on mobile (especially on small screens)

### ISSUE THREAD

**Issue by lunafreya** [ppy/osu-web#316]
![screenshot_2016-01-29-00-07-49](https://cloud.githubusercontent.com/assets/15260566/12650164/b1740330-c61c-11e5-9498-27c3e17032a2.png)

Some screens could also have the text overlap when viewed, especially on my Flare S3 Octa's small 720p screen.

**Comment by peppy** [comment]
@arflyte need a solution for this

**Comment by arflyte** [comment]
Will look into this.

**Comment by lunafreya** [comment]
Design got updated, closing this up.
