### ISSUE TITLE
Broken texts in Vietnamese localisation

### ISSUE THREAD

**Issue by shortthu** [ppy/osu-web#3169]
![](https://puu.sh/Ak3z6/06a73905e4.png)

Yes because Exo 2 doesn't support Vietnamese.

I was told to find a new one to use for the Vietnamese localisation but not sure how to choose so I'll leave that for the designer 😛

**Comment by arflyte** [comment]
I really have no idea on how to solve this. Would changing everything from Exo 2 to Noto Sans when Vietnamese is selected solve the problem?

**Comment by shortthu** [comment]
Yep it'd be good
