### ISSUE TITLE
Mod v2 issue with links

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#3176]
Maybe something to do with _  ?
![image](https://user-images.githubusercontent.com/33286824/39941664-47ea47ee-552b-11e8-8251-3cebf250d524.png)

turned into 
![image](https://user-images.githubusercontent.com/33286824/39941652-4136a19a-552b-11e8-8249-5a7e3759fc5b.png)

when posted

**Comment by nanaya** [comment]
Looks like the text replacement part replacing wrong text thanks to the two similar urls.

**Comment by dorothy3242** [comment]
You're right.. it shows up properly if the second url is removed or placed first- but it'll happen as long as the second one is after it any later in the post
![image](https://user-images.githubusercontent.com/33286824/39942611-f97e183a-552d-11e8-946f-0c46513a155f.png)
working properly by switching the order

![image](https://user-images.githubusercontent.com/33286824/39942628-08b2334a-552e-11e8-9abd-b246b07b1001.png)
still bugging even if the other one is far later in the message

weird bug 😕
