### ISSUE TITLE
String resource users['show']['age'] looks broken in Russian

### ISSUE THREAD

**Issue by andremacareno** [ppy/osu-web#3179]
Instead of being parsed as the plural one, it's just getting replaced variable placeholders.
https://github.com/ppy/osu-web/blob/1d824a499982a4590d870d6732bbe4c4a29c40aa/resources/lang/ru/users.php#L90

Note the string below with exactly the same formatting works fine.
https://github.com/ppy/osu-web/blob/1d824a499982a4590d870d6732bbe4c4a29c40aa/resources/lang/ru/users.php#L129
![screen shot 2018-05-12 at 15 40 32](https://user-images.githubusercontent.com/5407142/39957384-e76c7254-55fa-11e8-9829-ccbf77f7b3bd.png)

**Comment by Nekonyx** [comment]
Yep, this will be fixed in the next update.

**Comment by nanaya** [comment]
Seems fixed.
