### ISSUE TITLE
The last sane cached content should be used when github is inaccessible

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#3193]
Right now the site stops loading on any pages requesting from github, even if there is potentially usable stale data.

**Comment by notbakaneko** [comment]
Data can't be read from redis once the ttl expires, and the ttl of the news index is only 5 minutes

**Comment by notbakaneko** [comment]
The idea discussed previously is to save an extra copy of the index with an extra long ttl

**Comment by sr229** [comment]
How is caching implemented for GitHub parsing? We could probably do a workaround.

**Comment by sr229** [comment]
@notbakaneko A more plausible solution would be:

- Parse data
- If GitHub is accessible, delete from Redis, and fetch new cache.
- If GitHub is returning other than 200, do not fetch and use cache.

**Comment by peppy** [comment]
Keep in mind that would require a different mechanism for expiry.

**Comment by sr229** [comment]
What I had in mind was use a service to manually do this instead of setting the expiry automatically in cache. This seems the only way to do it AFAIK, unless there are other solutions.
