### ISSUE TITLE
Some html translations are escaped

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-web#3196]
![screenshot_chrome_20180514-235820](https://user-images.githubusercontent.com/18349191/40008859-f7744076-57d2-11e8-94e4-6ea4b75b7fca.png)

**Comment by nanaya** [comment]
Victim from changing `@lang` to `{{ }}` without checking the content.

So `@lang` doesn't do any escaping even though the documentation says to use it in place of `{{ }}`.
