### ISSUE TITLE
Change lightbox background opacity

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#32]
We've decided it looks better at ~80% rather than completely black.

**[Bounty](https://goo.gl/nFdoyI) offered**: 1

**Comment by nanaya** [comment]
looks a bit weird? or now? not sure why ┐(･_･)┌ 

![](http://puu.sh/jYdsM/703ea06c3a.jpg)

**Comment by TheHowl** [comment]
What about this?

![](http://y.zxq.co/cohcfu.png)

**Comment by peppy** [comment]
white border feels bad. also we still want the controls, as far as i'm aware.

**Comment by TheHowl** [comment]
Still there on mouse move.

![](http://y.zxq.co/brbeif.png)

**Comment by peppy** [comment]
I did this myself. Closing.
