### ISSUE TITLE
Add option to display beatmap metadata in original language

### ISSUE THREAD

**Issue by nekodex** [ppy/osu-web#3217]
Currently we're not displaying beatmap titles/etc in their original language. An account-wide setting should probably be added to allow users to toggle whichever they'd prefer.

**Comment by peppy** [comment]
Maybe we can get this one added? Should be pretty simple to do as the metadata already exists.

**Comment by huupoke12** [comment]
I think this shouldn't be closed yet, the metadata for Artist is still missing.

**Comment by peppy** [comment]
Can you explain what you mean?

**Comment by Joehuu** [comment]
The implementation only affects beatmap titles, but beatmap artists can also be shown in original language.

![chrome_UQTlQRxFQw](https://user-images.githubusercontent.com/35318437/88009396-413c6080-cac7-11ea-8c88-a4c9ef83a81c.png)

**Comment by peppy** [comment]
That's a huge oversight (ping @notbakaneko)

**Comment by notbakaneko** [comment]
I read this as only title for some reason 🤔
