### ISSUE TITLE
A lot of rendering time used to display website

### ISSUE THREAD

**Issue by Phippe** [ppy/osu-web#3229]
(Well, I've already opened a similar issue once concerning the leaderboard's performance on a slightly older device (namely an iPhone 5).)
I looked into the performance tab of the chrome dev tools and saw that there was a lot of rendering being done when you're scrolling, sometimes up to half the time:

![image](https://user-images.githubusercontent.com/34287258/40272272-1b23de74-5bab-11e8-8b5b-3a46d16a065a.png)
_Performance report of osu performance leaderboard_

While this probably isn't a problem on most PCs, it can cause lags on mobile devices (even on a newer iPhone 8 it wasn't completely smooth).

Here are some other reports to compare:

![image](https://user-images.githubusercontent.com/34287258/40272347-0bc200f4-5bac-11e8-91a5-1e815bd3a372.png)
_Beatmap listing_

![image](https://user-images.githubusercontent.com/34287258/40272875-717502ee-5bb5-11e8-83d1-ee833ad9f113.png)
_Profile_

![image](https://user-images.githubusercontent.com/34287258/40272900-1fdce892-5bb6-11e8-9387-72a5fc1f18ee.png)
_Homepage_

Only things like news articles or the wiki don't seem to use so much rendering time:

![image](https://user-images.githubusercontent.com/34287258/40272888-d8fd1d0c-5bb5-11e8-98ae-70b11b26c3c4.png)
_News article_

![image](https://user-images.githubusercontent.com/34287258/40272908-595b2fd4-5bb6-11e8-9cff-705777b9425f.png)
_Wiki_

My only questions are if you are aware of this and if you'd reconsider to optimize this a bit.

I'd gladly look into this myself, but as of right now I simply don't know enough about how this website is made up. This will also be my last issue on this topic even if you decide to leave it like that for now :)

Edit: Looking at the performance report in Chrome it seems that something causes the Layer Tree to update every time the user scrolls, even if they scroll to a part of the page they have already scrolled to earlier and which has therefore already been rendered once.

**Comment by nanaya** [comment]
Seems better now? New issue can be opened when there's specific outstanding slowness.
