### ISSUE TITLE
New nightcore@2x.png icon is the new easy@2x icon

### ISSUE THREAD

**Issue by NythilN1k0** [ppy/osu-web#327]
[https://github.com/ppy/osu-web/blob/master/public/images/badges/mods/nightcore%402x.png](url) Hopefully the title is self explanatory enough but, the new higher resolution nightcore icon is in fact, the @2x easy icon. Hopefully the proper icon can be uploaded.
![nightcore 2x](https://cloud.githubusercontent.com/assets/17037521/12771008/1ad86560-c9eb-11e5-9bb9-c27fdba133eb.png)

**Comment by nanaya** [comment]
fixed
