### ISSUE TITLE
Beatmap Search Function isn't as accurate as in Old Website

### ISSUE THREAD

**Issue by rodrigoelicer** [ppy/osu-web#3272]
Currently, if you search for a beatmap on the new website, it isn't showing as first element the strongest relation with the string given. What I mean is that it looks like matches with tags are as important or even more important than title, artist, source or mapper's name. Let me explain myself better with an example:

If for example you search for 'One Piece', the old website first shows all the beatmaps related to 'One Piece'. However, on the new website, the results are a complete a mess, showing results with no relation to that (tags having 'one' or 'piece' in it). Basicaly it should show results with direct relation to the search string, be it source, title, artist or mapper, after that should be a comparison with tags.

https://osu.ppy.sh/beatmapsets?q=one%20piece vs https://osu.ppy.sh/p/beatmaplist?q=one%20piece

**Comment by peppy** [comment]
Interestingly, https://osu.ppy.sh/beatmapsets?q=%22one%20piece%22 gives matching results to the old site.

Definitely looks like an area we can improve (prioritising exact matching over individual word matching).
