### ISSUE TITLE
Dates and times in ISO 8601 should be parsed in local time

### ISSUE THREAD

**Issue by MegaApplePi** [ppy/osu-web#3282]
Some discussion happened in \#osu-wiki a few months ago where we swapped from `DD. MMMM YYYY` to ISO 8601 for better parsing.

**Comment by MegaApplePi** [comment]
Sorry, I meant when a paragraph in the wiki goes something like this:
```
Yuzu is the osu!catch mascot that joined on 2014-06-22.
```
The `2014-06-22` should be parsed `June 21, 2014` (or whatever your client says is locale) to give:
```
Yuzu is the osu!catch mascot that joined on June 21, 2014.
```

Though the title had the word "time" in it, but some dates in the wiki don't have a time, just the date. Tournaments (and other articles that do use time) will have just to adapt to add in the timezone where needed.

**Comment by nanaya** [comment]
That doesn't sound right at least for date. Why don't just standardize a format for each language write it accordingly instead? Having something like "In 2014年06月21日 something happened." in an English article because the user locale is Japanese is just wrong.

**Comment by notbakaneko** [comment]
I don't agree that dates in wiki articles being parsed into client local times; like @nanaya said, it doesn't make sense for the article to be in one language and then the time to be in another. Dates and times should follow the language of the article.

**Comment by notbakaneko** [comment]
If there isn't any further input on this, we're going to close the issue.

**Comment by MegaApplePi** [comment]
Oh, forgot about this. The date/time itself should be parsed from the client's local time/timezone but use the article's language when writing it out.

**Comment by notbakaneko** [comment]
That makes no sense; wiki pages are per-language and not templates, dates should already be in the appropriate format

**Comment by MegaApplePi** [comment]
Alright sounds good.
