### ISSUE TITLE
Profile Picture update bug

### ISSUE THREAD

**Issue by Eoria** [ppy/osu-web#3283]
Updating profile picture that have transparent BG on it gave a black BG instead if we're updating it with new site.

![chrome_2018-05-29_11-15-07](https://user-images.githubusercontent.com/23649631/40637879-0daeae52-6332-11e8-9f46-264f68f85d01.png) 

With new site.
![chrome_2018-05-29_11-19-01](https://user-images.githubusercontent.com/23649631/40637921-3d657086-6332-11e8-9e40-3f4953b1a62c.png)

With the old one.

Original picture: 
![sophie](https://user-images.githubusercontent.com/23649631/40637915-343fb70a-6332-11e8-88d1-6962767d9da6.png)

**Comment by jacksonisiah** [comment]
this is intended behavior

**Comment by notbakaneko** [comment]
Transparency in profile images is not supported going forward.
see #1832, #2879, #1685
