### ISSUE TITLE
Add forum update polling

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3284]
![chrome_2018-05-29_18-54-21](https://user-images.githubusercontent.com/32525896/40673333-caf3e5ba-6371-11e8-87da-c7da38962e3e.png)

Would it be possible to let the site reload when clicking on this where my cursor is pointing on? (how is it called...?)
I used to click on this when "waiting" for replies. 

pretty low priority

**Comment by peppy** [comment]
Disagree; instead replies should be automatically polled for. This is planned eventually.

**Comment by nanaya** [comment]
Duplicate of #225.
