### ISSUE TITLE
Profile details are moving

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3291]
![](https://lya.s-ul.eu/2jslmxxL.gif)

Looking at the profile details on the right side, they're moving due to a longer line in `last seen`. Can this be fixed somehow?

Just noticed this when switching tabs (actually not sure why I had open the same two tabs lmao)

**Comment by peppy** [comment]
Thanks for reporting this.

This is a known issue, but there is some amount of redesign planned for this page so we are holding off fixing small issues like this for the time being.
