### ISSUE TITLE
Link colour on rows is not readable

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#3297]
![image](https://user-images.githubusercontent.com/191335/40847856-780890b0-65f8-11e8-88c3-da5fdb6a5eb4.png)

**Comment by TPGPL** [comment]
To what colour should it be changed?

**Comment by peppy** [comment]
That's why this issue exists.

**Comment by arflyte** [comment]
![2b3e4aab5f](https://user-images.githubusercontent.com/3632750/40958950-1c3ffb7a-68d6-11e8-997c-e744684aea66.png)

Invert the row colour on hover. Bold the name when hovered on name.
