### ISSUE TITLE
Certain post(s) cannot be deleted

### ISSUE THREAD

**Issue by Nath789** [ppy/osu-web#3298]
For example, [this post](https://osu.ppy.sh/community/forums/posts/6644112).
I also asked some moderators to try and the results are the same. Even when editing the content, it's still not possible. There could be more than we know.

**Comment by Flanster** [comment]
Managed to softdelete it now, could have been some hickup? Who knows man.

**Comment by peppy** [comment]
Yes, this has since been addressed. Was an issue at our end.
