### ISSUE TITLE
Recommended only shows one result

### ISSUE THREAD

**Issue by numbermaniac** [ppy/osu-web#3302]
If I'm on the beatmap search page on the old website (https://osu.ppy.sh/p/beatmaplist), then I click on "Recommended difficulty", it forcefully takes me to the new website at https://osu.ppy.sh/beatmapsets?c=recommended . It also sets the other two options to Any mode and Ranked & Approved, regardless of what they were on the old site.

For whatever reason it also only gives me one map when it redirects to the new site:

![screenshot_2018-06-02](https://user-images.githubusercontent.com/5206120/40872635-e6362c68-6694-11e8-93fe-b5ff6c63dc31.png)

**Comment by peppy** [comment]
This is intentional, apart from the recommended results only showing one result.
