### ISSUE TITLE
User rating should also be reset on disqualification

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#3303]
Along with scores being deleted, user rating should also be reset.

**Comment by Xinnoh** [comment]
I think it's better to not change this. 
- It quickly indicates if a map was qualified before
- It lets us know what the community thought of it before getting dqd
As long as user ratings are reset upon qualification then I don't think this is an issue

**Comment by celerih** [comment]
Currently in v1, the way UR resets work is UR is kept and shown when a map is disqualified, leaving an easy way to see that the map was previously qualified. Then, if/when the map gets requalified, it's there that the UR is reset. 

I think it would be best to transfer that over to v2
