### ISSUE TITLE
Add modding history page link somewhere on userpage.

### ISSUE THREAD

**Issue by Nao2she** [ppy/osu-web#3304]
Currently only way to access the page, which is very useful for keeping track of mods and stuff, is by going to a v2 thread then clicking the link there (which is very small but not really relevant).
Adding a direct link to that page under the kudosu section (or replacing kudosu section with it tbh) would be a better way to do things since atm people don't even know the page exists and it's a bit tedious to get to.

**Comment by dorothy3242** [comment]
Duplicate of https://github.com/ppy/osu-web/issues/3100

**Comment by peppy** [comment]
Closing as duplicate, thanks.
