### ISSUE TITLE
An  error in Simplified Chinese translation of the home page

### ISSUE THREAD

**Issue by JGChicken** [ppy/osu-web#3305]
![qq 20180603231853](https://user-images.githubusercontent.com/39881472/40888084-bb8e44f0-6784-11e8-94e2-ba8de1fa96b2.png)
It happens in the Simplified Chinese version of the page https://osu.ppy.sh/home, which i have mark in the screenshot.
The word "坠吼" is homophonic to the word "最好(good)", which is a popular meme among chinese social networks. But it is infact a word that make fun of a chinese chairman's accent, and is was banned by the government. Posts that used the word usually get deleted. If the main page of osu keep using this word, i'm pretty sure that it will become a target of the chinese Government Fire Wall in a short while. IPs will get banned and nobody inside the wall can get access to osu.ppy.sh

**Comment by JGChicken** [comment]
Please change the translation to “最好” or anything similar, not the one right now.The GFW act really fast (usually 2-3 days) and it gives out permanent bannd to the website and server.

**Comment by kj415j45** [comment]
Sorry for the trouble that my group member made. At first, we just use this translation in our group for fun. However, we don't know it will live so fast that we don't even have time to remove it before update translation files. I told him to directly remove the translation, he will do it as soon as possible. Thank you for your report.

很抱歉我的组员带来了这样的麻烦。一开始我们只是在群里说着玩的，但是我们没想到翻译文件更新这么快以至于我们都没来得及删除它。我已经通知他删除这个翻译了，他会尽快执行。感谢你的报道。

**Comment by benpigchu** [comment]
Please go to the related crowdin project for translation discussion.

Also this is not a real problem, since “坠吼” is not strongly relative to the vice chairman. Anyone can have a similar accents.

The translation may or may not change.

**Comment by iVanilla** [comment]
I'm Angry! 你们这样是不行的！识得唔识得啊？我今天是得罪了你们翻译组一下。

**Comment by peppy** [comment]
Let's keep it in good taste. I'd rather steer away from anything with a hint of political bias if possible.

**Comment by kj415j45** [comment]
Will be fixed by ppy/osu-web@9a077c070a3440b1dfec489db43388d4c1e339d0
Welcome to join our translate project: https://crowdin.com/project/osu-web
