### ISSUE TITLE
Make search similar to the old site

### ISSUE THREAD

**Issue by aticie** [ppy/osu-web#3310]
On the old home page, you can search users or beatmaps just by typing their names into the boxes and then hitting enter. It's very simple, however on the new site things are a bit complicated.

On the new site when you want to search something starting from the home page, you have to first go to https://osu.ppy.sh/home/search and then type what you want to search, and it returns you a page full of results with your query (https://osu.ppy.sh/home/search?mode=&query=peppy). If you want to visit a user's page, you must click on the user to go their page. That's extra 2 page requests than before.

Also if you click on beatmaps tab after you searched for something, it takes you to a whole different page (https://osu.ppy.sh/beatmapsets?q=peppy) not related with search page.

**Comment by peppy** [comment]
We're doing ongoing work on the design of the header. It's currently in a transition period.

**Comment by TPGPL** [comment]
should unassign

**Comment by TPGPL** [comment]
should be closed?

**Comment by peppy** [comment]
Has been implemented, yep!
