### ISSUE TITLE
Don't show birthday under 13 years old on profile page

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#3312]
This setting isn't yet fully completed in the new site, but it does show on your profile *(whether you set it weirdly or not)*.

https://osu.ppy.sh/users/4937439

I don't know what to do about fake birthdays, or real birthdays. Who knows? Well this user is obviously fake ^.

Ways to fix it: *(1 is the easiest, 2 should be the right way to execute)*
1. You can just hide it like on the old site *(under 13 years old)*.
2. You can make the birthday settings stricter, noting you have to be over 13. Adding a timer when you can change it, or a counter of how many times you can change it.

It can help or it can't. In the old site, you can change the birthday an infinite amount of times. Idk for existing users whose setting is `0 years old`, probably just delete that fake birthday.

Things to consider:
1. ~The [privacy policy](https://osu.ppy.sh/legal/privacy) is flawed. Doesn't show anything about birthdays. Don't even know if linking the `Children` section goes with birthdays(fake or not). Might be irrelevant.~
2. Leaving yourself at 13 years old at this time doesn't change the fact that you joined in 2012. [This user](https://osu.ppy.sh/users/1473890).

**Comment by peppy** [comment]
To be honest I'm not even sure how relevant storing birthdays is for our service. For the time being it should probably just be limited to only being an allowed input above a certain age.

Related to #2966, should be fixed before merge.

**Comment by notbakaneko** [comment]
unless we're actually using birthdates for some actual function, I don't think this is personal information that we should be storing.

**Comment by peppy** [comment]
The only use is to display age on profiles, currently. Not sure we even want to keep that.

**Comment by Joehuu** [comment]
Closing this then. No more birthdays.
