### ISSUE TITLE
Misleading and inconsistent unwatch icon

### ISSUE THREAD

**Issue by LeNitrous** [ppy/osu-web#3315]
This is the Unwatch button in the Beatmap Discussion page.
![image](https://user-images.githubusercontent.com/20495991/41025657-119e9b20-69a5-11e8-8a61-9c5f1df33aa8.png)

This the Unwatch icon in the Modding Watchlist page.
![image](https://user-images.githubusercontent.com/20495991/41025626-01fad0bc-69a5-11e8-9612-66e178eba33f.png)

This just looks really misleading since the first thing I had in mind is deleting it.

**Comment by peppy** [comment]
That is shocking. Let's standardise these.
