### ISSUE TITLE
Triangles inside buttons doesn't animate in Microsoft Edge

### ISSUE THREAD

**Issue by tetsureign** [ppy/osu-web#3321]
(and IE11)

https://puu.sh/AAG1R/6b358b6acf.mp4

I'm using version 42.17134.1.0, seems to happen on older builds too.

**Comment by shortthu** [comment]
I might be unclear this time. What I mean is the triangles doesn't have the /*move to the right* animation while hover (watch the video above for more info).

**Comment by nanaya** [comment]
That one is internet explorer/edge bug.
