### ISSUE TITLE
Github PRs are stuck with the fix(wrench) icon

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#3324]
Not all of them are fixes.
![](https://puu.sh/AB8Qe/bde0b1a195.png)

**Comment by peppy** [comment]
Probably needs label or text-based matching (ie. any PR that starts with "Add%" or "Implement%") to work.

**Comment by Joehuu** [comment]
Closing this since some system sorts them out now, and some manual tweaks can be used to change the icon and PR description anyway.
![edited](https://user-images.githubusercontent.com/35318437/41792503-ea438070-760d-11e8-8ce7-f17393576a1c.png)

**Comment by peppy** [comment]
This is not yet implemented.

**Comment by nanaya** [comment]
And not it is. Kind of.
