### ISSUE TITLE
Cutting Edge Changelog only displays "Bug fixes and minor improvements."

### ISSUE THREAD

**Issue by E223** [ppy/osu-web#3330]
Nyquill's most recent editor changes along with the "/" character trimming and beatmap modding links are nowhere to be found except the base Changelog page.
![](https://i.imgur.com/3EYayHq.png)
![](https://i.imgur.com/BdswELF.png)

Probably a separate issue, but Stable client changes are also appearing before they are actually usable in any release stream. 
![](https://i.imgur.com/e98FHtK.png)

**Comment by peppy** [comment]
This is how the changelog has always worked.

**Comment by E223** [comment]
My second image is from the old website. Which is what I'm using as a reference. Perhaps the title of this issue did not convey what I was trying to say well enough.

The new website's behavior has been consistent, however, what's the point of being able to click on Cutting Edge when the only thing displayed is "Bug Fixes and Minor Improvements"? Even while there have been significant changes made before being pushed to Stable.

**Comment by peppy** [comment]
We are working better handling of that part. The old website just fudges it right now, which we don't want to do on the new one.
