### ISSUE TITLE
Nominators and QAT should also be able to post notes

### ISSUE THREAD

**Issue by AyanokoRin** [ppy/osu-web#3340]
There are cases where they also need to post these instead of suggestions and praises, such as metadata references in the case the BN is also metadata helper or detailing changes after an IRC mod ( to avoid situations such as [this](https://osu.ppy.sh/beatmapsets/760407/discussion/-/generalAll#/307781) ).

**Comment by peppy** [comment]
I guess there's no harm in allowing this.

**Comment by dorothy3242** [comment]
The change appears to not be working, there is no note button available. 
I am aware that there is some time between PRs and it showing on the website, but it has been apparently been applied to the release fork for osu web since 4 hours ago.. so...

**Comment by nanaya** [comment]
Seems to work here? Was it actually released yesterday?
