### ISSUE TITLE
Beatmap Sample Play button

### ISSUE THREAD

**Issue by nktanh** [ppy/osu-web#3341]
- On Beatmap Listing or Search screen.
- Just a minor issue, I tend to mis-click the play button a lot using touchpad. So I suggest adding a padding to the button, maybe 5px~10px padding.

![ezgif com-crop](https://user-images.githubusercontent.com/9295088/41326752-bb54e288-6eea-11e8-9fbd-4546190b4f39.gif)

Thought?

**Comment by peppy** [comment]
Sounds good. There are likely quite a few more places we need to add such padding.
