### ISSUE TITLE
Let this black box show longer

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3343]
![2018-06-13_07-21-20](https://user-images.githubusercontent.com/32525896/41331704-a0c39d5c-6eda-11e8-80cf-0b63b7b4375e.gif)

So I wanted to read the whole title but due to the fact it's not my native language I needed some time and then it already disappeared
Can it last longer or until you move the cursor away?

**Comment by peppy** [comment]
It should probably not disappear.

**Comment by peppy** [comment]
Can we limit the fade out to mobile then?
