### ISSUE TITLE
Disable 'add friend' button instead of hiding it when a user hits their friend limit

### ISSUE THREAD

**Issue by VenixOSU** [ppy/osu-web#3346]
Pretty much self-explaining. Checked on serval user profiles. Tested on Microsoft edge with the same result.

**Comment by nekodex** [comment]
Works for me in Edge 42. Were you logged in? The button is hidden unless you're logged in. Do you have a link to a profile where this happens?

**Comment by VenixOSU** [comment]
I'm literally logged in, it happens on every user profile which is using the default avatar, like https://osu.ppy.sh/users/2628870 for example.
![](https://venix.s-ul.eu/ZKRBoGxq)

**Comment by nekodex** [comment]
Hrm, it looks like you've hit your friend limit which is causing the button to be hidden. We should probably change that to be less confusing. 😛

**Comment by VenixOSU** [comment]
Oh, that makes sense, was pretty sure it's working like on the old site.

**Comment by peppy** [comment]
The button should probably still be visible but in a disabled state, with a tooltip explaining why it's unavailable.
