### ISSUE TITLE
Add heart icon in recent category (payments)

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3356]
![chrome_2018-06-15_21-24-22](https://user-images.githubusercontent.com/32525896/41485918-b02428ac-70e2-11e8-8a47-bcc35dd3a70a.png)

Just a little suggestion, I think you can add a pink heart here for any payments. Without an icon it kinda looks weird

**Comment by peppy** [comment]
Looks like this was too hard to hit the milestone. Moving back to candidate issues (someone looking for an easy task could look into this).

**Comment by Lyawi** [comment]
what about adding an icon for beatmap submission/update too by the way? But idk which icons would fit to be honest, payments was simple

**Comment by KeziahMoselle** [comment]
This is being done in #8410

**Comment by peppy** [comment]
Will close this as it's being tracked by that task.
