### ISSUE TITLE
"Last seen 48 years ago"

### ISSUE THREAD

**Issue by AndyThePie** [ppy/osu-web#3357]
I apologize if this wastes your time in any way.

I was randomly looking at user pages when I randomly stumbled across a user who was "last seen 48 years ago." (specifically, [rlagmlrjjs0's](https://osu.ppy.sh/users/2123086) page.)

It's an empty user page, so it probably doesn't matter much, but I thought I'd point it out. 

Thanks for your time.

**Comment by peppy** [comment]
The old site displays "long gone" in such cases. We should probably add a similar sanity filter here too.

**Comment by nanaya** [comment]
Fixed in database.
