### ISSUE TITLE
Beatmaps Listing suddenly started to show the same songs

### ISSUE THREAD

**Issue by Wieku** [ppy/osu-web#3368]
I was looking for new osu! songs. I downloaded a few of them, then i switched browser tab to the other site. But when i came back, beatmaps listing was looking like this (scrolling over and over will load the same beatmaps):
![image](https://user-images.githubusercontent.com/5307179/41548674-f086dc44-7323-11e8-80ca-1329cf69ea63.png)

While writing this i just found that forcing scroll shows that other beatmaps are loaded, but they are overwritten just a while after:
https://img.wieku.me/18/2018-06-18%2018-28-06.mp4

**Comment by notbakaneko** [comment]
Was it already like this when you switched tabs, or did you have to do something else to make it happen?

**Comment by Wieku** [comment]
If i remember correctly, it happened when i started scrolling and loading new beatmaps after switching. Sorry i didn't mention that earlier.

**Comment by notbakaneko** [comment]
We've only had 2 reports of this and they're from around the same time. As it stands, this hasn't been reproducible without more info.

**Comment by peppy** [comment]
Reproduced this one. Will keep browser window open in case @notbakaneko wants to check into it further.

Was from a fresh page load (Cmd-R) and then basic scroll downwards only.

**Comment by notbakaneko** [comment]
React gets confused when it renders and sees a row with an already existing key, so will have to change how pagination is handled

**Comment by nanaya** [comment]
Filtering out duplicates after fetch, before updating state could work for temporary workaround?

**Comment by Wieku** [comment]
The issue still persist, was able to reproduce it while searching for a song and scrolling down slowly. It happens randomly:
![image](https://user-images.githubusercontent.com/5307179/57586293-46ca0e00-74f4-11e9-8585-eb3e16df9f8d.png)

Debug console is clear.
