### ISSUE TITLE
You should be able to bring up header+search filters when scrolled down in the beatmaps listing

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#3370]
Being lost in an endless scrolling abyss with no easy way to escape is not fun and extremely inconvenient. If someone many maps deep into scrolling down on the beatmap listing page, it is not user-friendly to have to scroll the entire way back up just to change the search term or filters, or go to a different page on the website.

There should either be a way to bring the search bar and filters up after scrolling down, or a jump to top button. Or both. Preferably both.

**Comment by arflyte** [comment]
Adapting beatmap search to the new mini navigation. Back to top button at bottom right.

![e46226ea95](https://user-images.githubusercontent.com/3632750/41641154-497d40fa-749f-11e8-9037-fdc99257c8c5.png)

**Comment by TPGPL** [comment]
should be closed

**Comment by peppy** [comment]
Resolved via #3809.
