### ISSUE TITLE
Issue with Qualification Timer after Disqualification

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#3399]
https://osu.ppy.sh/beatmapsets/703580
https://osu.ppy.sh/beatmapsets/762466

It seems that when a map is disqualified with less than a day remaining until rank, it may end up ranking in less than a day after re qualification - despite it being discussed that a map should always spend a minimum of one 24-hour day in the qualified section.

https://osu.ppy.sh/beatmapsets/749557
This map had a similar case, it was requalified around 8 hours ago (it is now disqualified again) but prior to being disqualified, it was listed as the second-next map in line to be ranked on the website, which would have  most likely taken less than a minimum 24 hours as well
![image](https://user-images.githubusercontent.com/33286824/41813712-03a9efee-7709-11e8-8329-27899fd792b5.png)

There should always be at least 24 hours in qualified for any mapset, or another system to prevent requalified maps going through too quickly.

**Comment by peppy** [comment]
Right, this has been reported a few times but it slipped my mind and we never addressed it. Will make sure this is fixed ASAP.
