### ISSUE TITLE
Profiles: Ability to re-order sections.

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#340]
Need to add drag and drop support to reorder sections in your own user profile. The order should be saved to database so it is used whenever viewing your profile (as yourself or someone else).

![](https://puu.sh/n1fmV/7b1613e3d0.png)

Each section should have a "hamburger" button that can be used to begin the drag. While being dragged, it should be very obvious that the section is being dragged, via display of a "ghost" box attached to the cursor (and the existing one dimmed out to show what is being moved.

Check out the "Sortable list with handles" example [here](http://farhadi.ir/projects/html5sortable/) for a sample implementation. Not necessarily promoting this plugin as the best choice; just one possibility.

![](https://puu.sh/n1fvC/6cc93716ea.gif)

Keep in mind the fixed top menu will also need to update. As an extra, you could also make the fixed menu draggable for easy reordering (have to see how it feels, though).

**[Bounty](https://goo.gl/nFdoyI) offered**: 150-250 depending on implementation quality.

**Comment by 0----0** [comment]
Giving this a try.  I'll let you know how it goes.

**Comment by CMS-Falcon** [comment]
Gonna take a crack at this as well. Probably won't have much till the weekend.

**Comment by peppy** [comment]
Congratulations to @LiquidPL for the great work on this feature. I'm giving 450 bounty (+200 from spec) due to the increased work required to get things working, along with additional tasks that were added along the way.
