### ISSUE TITLE
Things that should be on osu(in game) and osu web

### ISSUE THREAD

**Issue by caryllelol** [ppy/osu-web#3403]
for osu (in game) 

- group/ group chats

- a chat box that pops out when you receive a new message

- friend request icon (like on facebook where it shows you a list of people who friended you)

- notification thing (like on facebook where it shows you who favorited your map, watched your replay, commented on your replay/screenshot etc etc)

for the web

- profile comments

- a chatbox (just like the one in game)

- rep

- saved/favorite/ most watched replays

- saved/favorite screenshots

- friendslist

- list of followers/following

**Comment by caryllelol** [comment]
please noticeeeeeeeeeeeeeeee

**Comment by Lyawi** [comment]
osu-web is related to the website only, also list only one thing per issue. But before you do that use the search bar to know if someone else had your idea or things are existent already

have patience

**Comment by caryllelol** [comment]
no thats too much work. would be best to just list everything at once
