### ISSUE TITLE
Outdated terms and formatting suggestions on the main forums page

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#3406]
Should be easy to change, since it's just small fixes. Can't do it myself, since it's not exposed. Sorry if this is the wrong place, but it is part of the web and can't list things in a better place. 

This covers the front(main) page of the forums.

[Front page](https://osu.ppy.sh/community/forums):

![](https://puu.sh/ALh5a/22caea3031.png)
`maps` -> `beatmaps`

![](https://puu.sh/ALhhQ/5386e6ce8a.png)
`osu!` -> `osu!.` -- period in description
`Taiko` -> `osu!taiko`
`Catch the Beat` -> `osu!catch`

![](https://puu.sh/ALhiU/0b049435cd.png)
`customization` -> `customisation`

![](https://puu.sh/ALsXf/f18f3a5758.png)
`here` -> `here.`-- end with a period

![](https://puu.sh/ALt1o/c768f2672b.png)
`Ranked/Approved` -> `Ranked`
`approved` -> `ranked`

**Comment by peppy** [comment]
All fixed.
