### ISSUE TITLE
Wrong naming on osu!supporter product

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#3407]
https://osu.ppy.sh/store/products/208

The product is `osu!supporter tag` without a space. The description should also be referencing the product "osu!supporter" and not just "supporter".

This line:
> Supporter tags are non-recurring payments. If you buy one while you still have a supporter tag active, it will extend the duration it lasts.

Edit: Can't edit this too.

**Comment by peppy** [comment]
Both of these issues have now been resolved (database changes). Thanks for the attention-to-detail.
