### ISSUE TITLE
Implement supporter page design

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#343]
This bounty is for the complete implementation of the supporter page design. This one is a good task for people who don't want to involve themselves with the back-end, as it's mostly just css/template design.

- Each of the "why" and "what" items should be localisable and extensible (ie. we should be able to add more and change them easily).
- The triangles in the PSD are outdated. Please use the new triangle pattern as used elsewhere on the [live site](http://new.ppy.sh/forum).
- As there are no interactive components yet, this page can be created without react as a direct template.
- CSS should be clean and in line with existing formatting see the [BEM disussion here](https://github.com/ppy/osu-web/issues/53) I guess.

![](https://puu.sh/n1tSe/61ea403b2a.jpg)

PSD: https://www.dropbox.com/s/m5n3hxvnyfwxws9/osu%21next%20-%20Support%20Page%20C.psd?dl=0

**[Bounty](https://goo.gl/nFdoyI) offered**: 150-300 depending on implementation quality.

As always, ask if you have any questions, and feel free to jump on the [osu!dev slack](http://osu.ppy.sh/p/slack) for more real-time discussion.

**Comment by UnnoTed** [comment]
ill do it

**Comment by RagnarLaud** [comment]
I'm gonna give it a shot

**Comment by peppy** [comment]
Awarding the bounty here to @UnnoTed as his implementation is basically complete. Nice job :+1:.
