### ISSUE TITLE
Change how much pp is needed to auto restrict users

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#3434]
Unsure where exactly this belongs
Whenever someone full combos the ctb version of image material with hidden or hardrock ([this map](https://osu.ppy.sh/beatmapsets/432720)), the user is automatically restricted and needs to contact support. This has been an issue for a while and shouldn't really be a thing.

The value to auto restrict users should either be increased to 1750, which is how much an HDHR SS can get you.

In addition, it would also make sense to add mode specific checks to improve the accuracy of this filter. Some example auto restrict values:
Standard: 1250
Taiko: 1000
Catch: 1750
Mania: 1500

**Comment by peppy** [comment]
Thanks for pointing this out, but it's not related to osu-web project.
