### ISSUE TITLE
Have an upvote and a downvote option on forum posts.

### ISSUE THREAD

**Issue by Zozimoto** [ppy/osu-web#3441]
Basically like under the name a thumbs up and a thumbs down on a forum post, it can be any type of 
post, the OP or replies. There really isn't any awards for making good posts, all it is is a way to judge a post by quality.

On the website it would look like this: 
![yeah like this](https://i.imgur.com/3FKbHuC.png)
Green indicating that that was the option you chose (Green recolor (of the button) for upvote, red recolor (of the button, again) for downvote)
The numbers next to the upvote and downvote icons tell you how many times a post has been upvoted and downvoted. The numbers shown in the picture clearly and precisely predict the outcome of this Feature Request.
Those buttons will be there for every post (Includes OPs and replies, but I already mentioned that.)

Thanks for reading, or atleast trying to read it.

(i was told by flanster to post this here instead of the feature request subforum so here we are)

**Comment by peppy** [comment]
I'm not sure we will be using the forums for feature requests going forward as we move towards using Github for more of our workflow. Also don't see this being too useful outside of the feature requests forum.

**Comment by Zozimoto** [comment]
you could use it in basically every forum except for the Beatmap forums

**Comment by Flanster** [comment]
Not really sure what this contributes at all, we're not reddit..

**Comment by cl8n** [comment]
closing this one in favor of #7386, which seems to be the preferred alternative and can achieve the same thing.
