### ISSUE TITLE
When switching difficulties on mv2, it should automatically switch to the timeline tab

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#3442]
After switching difficulties in modding discussions, 99% of the time it's to write comments about a specific difficulty, but people still post their stuff in the all difficulties section.

When switching difficulties, it should automatically swap to the timeline tab. 
Even if someone intended to write in the general tab, it would warn them they don't have a timestamp.

This is imo the best solution to people writing stuff in the wrong tabs.

**Comment by peppy** [comment]
I think this definitely should be done.
