### ISSUE TITLE
"Historical" never hi-lights on profiles because you cannot scroll past the start of it.

### ISSUE THREAD

**Issue by nyquillerium** [ppy/osu-web#345]
![Issue](http://nyquill.s-ul.eu/HlPOKLGC)

This is about as far as I can get for me. Maybe give the list of beat-maps one extra item?

**Comment by peppy** [comment]
This needs an offset similar to what we're doing in forums (should become the active tab when above 50% height in your browser).

**Comment by peppy** [comment]
**[Bounty](https://goo.gl/nFdoyI) offered**: 30

**Comment by nyquillerium** [comment]
should this behavior apply to all tabs or just the last one?

**Comment by nyquillerium** [comment]
the addition of the rank history graph seems to have resolved this as a side effect

**Comment by peppy** [comment]
I wouldn't call this fixed with that commit alone.

![](https://puu.sh/n48aw/e5dfdbca81.png)

**Comment by nanaya** [comment]
updated the marker position
