### ISSUE TITLE
Posting cooldown message is misleading

### ISSUE THREAD

**Issue by Zozimoto** [ppy/osu-web#3450]
seems legit
![hm](https://i.imgur.com/y6kxXK2.png)

**Comment by sr229** [comment]
Please elaborate further your issue.

But the way I see it, it's also a UX improvement that needs to be done

**Comment by Zozimoto** [comment]
i personally don't think we can consider 7 hours ago "You just posted now."

**Comment by peppy** [comment]
Could you please link the thread so we can ascertain whether this was a bug or not?

To me it looks like incorrect timezone behaviour if their post was actually 7 hours ago.

**Comment by nekodex** [comment]
Pretty sure that's double-post protection. The notice/message should probably be updated to better reflect that.

**Comment by notbakaneko** [comment]
We could either change the current message which would probably make it more vague, or have a different message depending on when the last post was.
