### ISSUE TITLE
Restricted banner doesn't play well with new header design

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#3451]
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/191335/42167056-ccd7b4a6-7e47-11e8-8c82-135f3dd7957b.png">

**Comment by Paussse** [comment]
omg that's me! hi mom!

**Comment by arflyte** [comment]
![image](https://user-images.githubusercontent.com/3632750/42554225-05423a22-851f-11e8-85a1-327e747c6e7f.png)

Navbar colour turns red. Alert icon on avatar. Design only applies to areas with the new header design ie: Changelog.
