### ISSUE TITLE
[Possibly related to the API used in-game] Unsubmitted maps showing as ranked / Invalid score retrieval

### ISSUE THREAD

**Issue by Adrriii** [ppy/osu-web#3452]
Hi, this bug has occured on many occasions to me and other people in the past months (2-3 months)

I'm assuming the osu! client gets information from an API, osu-web being the closest thing I'm posting this issue here.

**The problem**

During the background check of beatmap status and scores, it sometimes happens that a bunch of maps are set to Ranked while they aren't (sometimes even being unsubmitted).

With the search parameters "status=r key=4" and "Rank achieved" grouping that I often use, I expect to get a few dozens of maps to be in the "No Rank Achieved" group. As you can see in this screen, there is a thousand and when I randomly click one and go to a ranking in order to force its update, it becomes unsubmitted : 
https://puu.sh/APDJh/834f971be1.png
https://puu.sh/APDKs/4e654c56ba.png

It also happened that some maps were showing as Ranked AND it showed an SS, but when updating it the SS was gone and it became unsubmitted/pending again.

**Troubleshooting**

This doesn't seem to be related with a poor connexion as it happened to me on 3 different networks (excellent, good and very bad)

I don't have a way of reproducing this bug as it seems to happen randomly. Restarting doesn't fix it, I have to wait a few hours before logging back and the background scan of the maps works again.

**Comment by Adrriii** [comment]
GIF to also show the problem

https://puu.sh/APEYK/63b47d1380.gif

**Comment by sr229** [comment]
@peppy Recommending we raise this to a critical bug - this affects multiple users.

**Comment by peppy** [comment]
This is not related to osu-web. Please post in the help forums.

**Comment by peppy** [comment]
FWIW I have tested this and everything seems to be working as expected.

**Comment by Adrriii** [comment]
Well it happened again today, posted in help forums ..
