### ISSUE TITLE
Don't place scores differently due to rank

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3453]
![chrome_2018-07-02_19-13-20](https://user-images.githubusercontent.com/32525896/42177165-0f6c043c-7e2c-11e8-888b-fb7e97293ef5.png)
/
![chrome_2018-07-02_19-18-41](https://user-images.githubusercontent.com/32525896/42177354-c28d7ab4-7e2c-11e8-86ea-67ef5861c44f.png)

They're placed down differently depending on the achieved rank.

**Comment by peppy** [comment]
You mean due to mods?

**Comment by Lyawi** [comment]
oh yeah
but the avatars?

**Comment by arflyte** [comment]
The score details and the rest should be left aligned next to a fixed sized player name area.

**Comment by notbakaneko** [comment]
keep in mind that the elements also can collapse in:
![image](https://user-images.githubusercontent.com/1694544/42490718-b7a4e2ba-844c-11e8-86d0-861dda0fa5a5.png)
![image](https://user-images.githubusercontent.com/1694544/42490735-cd72d5ac-844c-11e8-902e-f345bbd27957.png)
![image](https://user-images.githubusercontent.com/1694544/42490775-f3ad5d64-844c-11e8-9982-98ea8db44b0f.png)

**Comment by nanaya** [comment]
Duplicate of #2538.
