### ISSUE TITLE
Make it possible to resurrect and delete graveyarded beatmaps

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3459]
old:
![chrome_2018-07-05_21-00-05](https://user-images.githubusercontent.com/32525896/42342459-6faec0f2-8096-11e8-8cbb-9d5b8ef81240.png)

current:
![chrome_2018-07-05_21-00-50](https://user-images.githubusercontent.com/32525896/42342495-8b4e9436-8096-11e8-8f4f-35e59791f5c1.png)
I think you could add two buttons next to the download button, only the creator should be able to see them.

**Comment by Joehuu** [comment]
See #1793.

**Comment by notbakaneko** [comment]
Is this actually necessary outside of the client?

**Comment by peppy** [comment]
We may still want to expose deletion on the site, although O think it should be on the beatmap info page if anywhere.

Ungraveyarding is done from in-game but may need a message on the info page telling the user to submit to restore to pending status.

**Comment by notbakaneko** [comment]
actually, does this cover #3006 or is there more to #3006?

**Comment by peppy** [comment]
Yes, it should do.
