### ISSUE TITLE
Recent section should show more lines when clicking on "show more"

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3460]
![2018-07-05_21-06-10](https://user-images.githubusercontent.com/32525896/42342776-6222cd24-8097-11e8-8a05-521dcd5b1d57.gif)

It should really show more.

**Comment by dorothy3242** [comment]
![2018-07-05_15-13-05](https://user-images.githubusercontent.com/33286824/42343096-fd1b1ce6-8065-11e8-9853-debd0683b9cc.gif)
It can display a lot more when you click the button, you just don't have very much _recent_ history to display.
It only displays events from the last ~4 weeks.

**Comment by Lyawi** [comment]
my bad
