### ISSUE TITLE
New website does not display weighted percentage for top ranks

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#3467]
![image](https://user-images.githubusercontent.com/33286824/42400114-59fd02ac-813e-11e8-8792-f4e49680e3cc.png)

on the old website, it mentioned how much each score was weighted by for its pp value
![image](https://user-images.githubusercontent.com/33286824/42400130-65e4aa02-813e-11e8-9399-319ba4499ac3.png)

not having it is extremely misleading as the system of weighted pp already causes some confusion for those not familiar with it, omitting this information from being easily viewed just makes it even more obscure.

**Comment by peppy** [comment]
![image](https://user-images.githubusercontent.com/191335/42406269-0a47fa72-81df-11e8-9d8a-669b90dddf55.png)

**Comment by dorothy3242** [comment]
oops
