### ISSUE TITLE
Rank History graph shows incorrect information for some users

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#349]
![](https://puu.sh/n359y/78e2df13b9.png)

http://new.ppy.sh/u/7457788

- Scale is incorrect and less useful than the previous site.
- Data is being shown from before the user was ranked or even registered.

**Comment by peppy** [comment]
should probably be logarithmic y-axis too, else [this kind of thing](https://puu.sh/n35Cp/5452a0ed8e.png) happens.

**Comment by nanaya** [comment]
fixed
