### ISSUE TITLE
difficulty sorting on the mania tab for hybrid mapsets is mixed

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#3490]
https://osu.ppy.sh/beatmapsets/607014#mania/1282252
on this set, the osu converted difficulty is to the right of the mania one when you're on the mania tab because the convert is 7k and the mania is 4k.

https://osu.ppy.sh/beatmapsets/438839#mania/964130
on this set, the order is mixed and plopping the mania-specific difficulties in the _middle_ due to this behavior. 

This problem seems to be unique to osu hybrids involving the mania game mode.
 it seems to go osu convert (4k), mania (4k), osu convert (7k), mania (7k) and so on with that pattern. This mixed order of osu converts / mania specific difficulties can be confusing to look at, especially when compared to catch and taiko's cases, the osu converted difficulties are always leftmost on the listing.

It should be something like
osu (4k) convert, osu (7k convert), mania (4k), mania (7k), and so on, so that the converted difficulties will always be leftmost and the actual difficulties made for the mode will be consistently to the right of those.

The current system results in mania mode specific difficulties being positioned super inconsistently, which can make them a bit less noticeable on the mapset's information page.

**Comment by notbakaneko** [comment]
We're going to sort them according to converts, keys, difficulty with the converts going at the end
