### ISSUE TITLE
osu!status page design

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#35]
Trialling some larger bounties. This one involves implementing a design concept fully.

![](http://puu.sh/jYodW/1e03c465f6.png)

This is a **stand-alone** status page, which will be replacing http://stat.ppy.sh

Requirements:
- Make a blade template to match the attached page style.
- Follow existing styling naming standards.
- Reuse existing styles where possible.
- Write in a way that can easily have functionality hooked up at a later point (be consistent with class names, feel free to use place-holder foreach loops etc.)
- The red "active incidents" area at the top is only visible when there's an active incident.
- The world map is open to interpretation, but should have some form of interaction on hover of the visible player clusters.
- Graph will be using the styling that results from https://github.com/ppy/osu-web/issues/13, so you are welcome to add a placeholder (or use the latest available d3 version from that thread).
- This graph shows both online users and score submissions. The two number boxes below are clickable and will change the graph's mode.
- Any further visualisations added should also use d3.
- Should be animation on the "Uptime" pie displays that tween as you change tabs.

**[Bounty](https://goo.gl/nFdoyI) offered**: 350 (+150 for complete ready-to-connect React implementation with placeholder jsx datasource)

As per bounty guidelines, it is recommended that you claim this issue if you are serious about it.

If you are going to react it up, make sure to check out the profile page implementation for examples to follow.

Ask away for further clarifications.

PSD: http://puu.sh/jYocV/527581fc06.psd

**Comment by Pepperrika** [comment]
Nice work peppy

**Comment by TheHowl** [comment]
*flyte

**Comment by troke12** [comment]
is recent incidents update from twitter ?

**Comment by peppy** [comment]
The final source isn't important for now. This is purely getting the design in place. If you are going to add a datasource, and are doing so with react, you should just be supplying an array of test data.

**Comment by Tewki** [comment]
Peer 'it is recommended that you claim this issue if you are serious about it.', I'm quite interested and have started but had to go to work; Should go rather quick thanks to flexbox & the psd.

Also, instead of those red gradient borders around the active incidents wouldn't it fit more with a semi-light colored flat warning pattern or a flat color instead of giving the flat design depth.

**Comment by peppy** [comment]
i tend to agree that the gradients feel a bit out of place. @arflyte?

**Comment by arflyte** [comment]
Feel free to remove the gradients.

**Comment by Tewki** [comment]
Pretty much done with the design + layout + functionality, only got the graphs + charts left which tends to be the most horrible part.

Partly the map, cuz of the way d3/DataMaps clips the path you can't really rely on a svg pattern to make the circles out getting clipped everywhere which doesn't look as nice.

Currently also looking at [c3](http://c3js.org/) and other libraries that has the right licence + uses d3 to see if it's any better than using a pure sulution of d3 (It just generates the d3 chart) due to the little updates to the graph library issue.

Also did the gradients like ![so](http://i.imgur.com/9wOoxkY.png) But it would be nice if I could get the real header image as the current one is a merged layer and my crop doesn't look the best.

**Comment by peppy** [comment]
I'm all for looking at extension libraries on top of d3 (on its own, as you say, it can be a beast to tame).

I'll follow up with @arflyte for the header layer.

Gradient change looks okay. Should be able to change the yellow to red or green (to match the three statuses in the incident timeline) too :).

Looking forward to going through your implementation! Post early and we can give you more rapid feedback.

**Comment by arflyte** [comment]
![status-header](https://cloud.githubusercontent.com/assets/3632750/10276181/c14334fa-6b88-11e5-8c2b-bdb31d1db264.jpg)
![status-header 2x](https://cloud.githubusercontent.com/assets/3632750/10276182/c163c01c-6b88-11e5-8233-36b24011444d.jpg)

Here are the headers. Sorry for the late, kinda missed this.

**Comment by TheHowl** [comment]
As Tewki is out of the bounty maximum limit for completion, can I take over?

**Comment by peppy** [comment]
Go for it! No need to ask.

**Comment by Tewki** [comment]
Yea I've become rather inactive for the time and I'm missing my files due to a mess up with my laptop being lost in traveling, so given the old rewrite/prototype to Howl.

**Comment by troke12** [comment]
just a little suggestion on Uptime Charts
i would recommend this chart using [Chart.js](http://chartjs.org) 
![kmUs4iH](http://i.imgur.com/kmUs4iH.png)

**Comment by TheHowl** [comment]
>Any further visualisations added should also use d3.

**Comment by TheHowl** [comment]
Was wondering - as I am going to implement react on the page, shall I provide the user with some data already on the response (server renders the page and then user gets updated data through http request done by js), or shall I make it user-rendered since the beginning (like on the user profile)?

**Comment by peppy** [comment]
Why would you require a second round-trip just to display data? Just include it in the initial request. So much faster.

**Comment by peppy** [comment]
Increasing bounty on this to 350 (+150)

**Comment by UnnoTed** [comment]
i'll do it

**Comment by peppy** [comment]
There's some degree of work done with d3 in the profile (rank history) graph now, so make sure to check that out for the graph parts.

**Comment by LiquidPL** [comment]
@UnnoTed you still doing this?

**Comment by Andrehande** [comment]
This is very interesting!

**Comment by UnnoTed** [comment]
@LiquidPL yes

**Comment by peppy** [comment]
awarding 500 bounty to @UnnoTed for complete implementation. :high_brightness:
