### ISSUE TITLE
Rank History graph x-axis less useful?

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#350]
![](https://puu.sh/n35Cp/5452a0ed8e.png)

Personally I find the old style of "x days ago" much easier for my brain to parse. Opinions?

ping @arflyte too

**Comment by vowywowy** [comment]
I would agree, and I think the current new.ppy.sh x-axis looks too dense. Maybe have a tool tip on hover of "x-days ago" with the date its referencing?

**Comment by VeilStar** [comment]
I also find "x days ago" better than an actual date.

Also, wouldn't every 2 weeks or every month be a better interval than every week? It just feels rather cluttered with that short of an interval. I feel that a more precise timestamp in the tooltip as it is on the current/old website is the better option.

This isn't exactly related to this issue, but the vertical lines don't show up in Firefox, while they do in Chrome. Thought I'd mention that as well.

**Comment by peppy** [comment]
As another note (might as well keep  it in this issue), the padding to the left seems way too large:

![](https://puu.sh/n3ziY/06d6900f2c.png)

**Comment by nanaya** [comment]
Fixed in 3029ca098c122699299fca2564095f2d92f9f664.
