### ISSUE TITLE
Link to changelog page in osu-framework releases is broken

### ISSUE THREAD

**Issue by plankp** [ppy/osu-web#3512]
The latest osu-framework release (at the time) is [2018.712.0](https://github.com/ppy/osu-framework/releases/tag/2018.721.0).

If you try to click on the *osu! changelog page* link, it brings you *Page Missing*.

* Is there anyway to either log framework changes separately from osu?
* Or just redirect to the latest osu changes?
* Or remove the *Thanks for following along! This is a tagged release (2018.721.0). For more information check out the osu! changelog page and dev blog.* completely?

**Comment by peppy** [comment]
I've updated the link. This is a pretty rare occurrence so I think we'll just handle it manually for the time bveing.,

**Comment by plankp** [comment]
👍
