### ISSUE TITLE
Changelog - contributors' osu! profile linking doesn't work properly

### ISSUE THREAD

**Issue by HoutarouOreki** [ppy/osu-web#3516]
Noticed this when porting the page to the client and implementing "open contributor's osu! profile in-game" type of functionality. However after hovering over my GitHub name to test this, it turned out that the `user_url` given by the JSON file is wrong (and so are the other 2 osu-profile-related entries).
![image](https://user-images.githubusercontent.com/16261733/43172415-7caacd8c-8faf-11e8-8e4d-cca0890fef51.png)

Checked what for is it used on the web, since I only remembered changelog linking GitHub profiles, and so it renders these "tooltip profiles":
![image](https://user-images.githubusercontent.com/16261733/43172572-2f002bda-8fb0-11e8-97ce-5e7b6a1646be.png)
This is still not my profile.

I understand how it tries to work, but it just doesn't in common circumstances and should be removed. Unless we're somehow linking osu! with GitHub and then detecting if a given `github_user` has a linked profile here, but that's just expensive and not worth it.

**Comment by nanaya** [comment]
Probably because we just find matching github username with osu! when doing the initial import. Just tell what your osu! id is (or if you don't want to link to osu! id) and it'll be fixed.

**Comment by HoutarouOreki** [comment]
Just saw a faulty, naive default behaviour and thought I'd report it. If that's how it's supposed to work, you can close this issue.

**Comment by nanaya** [comment]
As I said, the link is manually created. If it's wrong, just report it. It's rows with github_id and user_id. No magic involved apart of the initial import to fill in data.

**Comment by nanaya** [comment]
I'm confused. So is that not your osu! id? What's your osu! id then? Or do you not want to link your github user with any osu! id instead?

**Comment by HoutarouOreki** [comment]
Easy, I just wanted to bring up, that the automatic (or manual, doesn't matter) linking has no magic way to work properly 100% of the time.

I don't really care about it linking to my profile (4185566)

**Comment by nanaya** [comment]
I've fixed it. I don't know what magic you're thinking of because there's no magic. Any further new github users/contributors don't get automatically linked to osu! id - it must be manually set.
