### ISSUE TITLE
osu!supporter doesn't expire

### ISSUE THREAD

**Issue by Cerebi** [ppy/osu-web#3527]
This refers to two different cases: one of a normal user who said his supporter should have expired yesterday and one from a global moderator (me)

I know that when someone becomes staff they get their supporter timer "frozen", so each day you can see the timer just adds one day, and so on.
The strange thing is that when the other day I came back to gmt I had my supporter already expired, yet I could use direct and all the features it entails. At first I thought this was strange, but it also made sense, because in the past you had to buy one month to make the timer run infinitely, so maybe with the new site things changed in that regard...

Until I saw someone in #osu "complain" their supporter should have expired yesterday.
What was interesting is that both his timer (from what he says) and my timer were saying the same thing: 
![supporter](https://i.imgur.com/hGJrdmf.png)

Now, a day passed and even though my timer should be "frozen", it changed into: 
![supporter2](https://i.imgur.com/nxkz6JE.png)
This was also what it showed me the first day I returned to gmt btw.

PS: the user in question was https://osu.ppy.sh/users/9280575 (his userpage says nothing about gifts or anything) and my profile https://osu.ppy.sh/users/2581696

**Comment by nekodex** [comment]
So it looks like the new site shows the expiration as being at the beginning of the day while the expiration actually happens at the end of the day... so the display is around ~24hours off.

The old site still handles the supporter tag expiration so the actual behaviour hasn't changed.

**Comment by Siirpaul** [comment]
I think i had something similar. I bought osu!supporter for 4months a long while ago and ended up having it for over a year I believe. or at least it felt like it was over a year, im not entirely sure on the exact time
