### ISSUE TITLE
Multiplay Match History parse mods error

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-web#3537]
![qq 20180730023048](https://user-images.githubusercontent.com/18349191/43369421-a1491974-93a0-11e8-9943-7d6cd1220682.png)

So much mod icons there (`4-8K TouchDevice PF AutoPilot SO FL HT Relax NC HR FadeIn HD EZ NF`). But iirc, I only use `4K Co-op FadeIn EZ HD NF EZ ...` (No free-mod).

[Match Link](https://osu.ppy.sh/community/matches/44600970)

**Comment by nanaya** [comment]
The row has mods of `16777215` ಠ_ಠ

I don't think it's something to be fixed in osu-web.

**Comment by peppy** [comment]
Column wasn't large enough to hold mania mods. Unfortunately this means some old data is going to be in a permanently incorrect state (we'll reset the mods to `none` in these cases). A fix has been deployed to resolve this going forward.
