### ISSUE TITLE
Graph point goes away after holding a few seconds

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3551]
![2018-08-01_16-06-52](https://user-images.githubusercontent.com/32525896/43526663-10c44afc-95a5-11e8-8bac-c40ff17c5b00.gif)

I don't think this is a big deal but not correct either (?)

**Comment by notbakaneko** [comment]
@nanaya was there a reason for setting the 3000ms timeout?

**Comment by nanaya** [comment]
For mobile, I think? Also this one requires the mouse to stay in one place for few seconds which is a bit harder to do.

**Comment by peppy** [comment]
That looks really weird and disconcerting.

**Comment by nanaya** [comment]
Fixed, I believe.
