### ISSUE TITLE
New thread preview is not obvious that it's a preview

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#3558]
![image](https://user-images.githubusercontent.com/33286824/43672297-1f3ec4f6-9779-11e8-8223-8b1d896a858a.png)
there's nothing really indicating that it is a preview, gave me a scare that I had accidentally posted the thread already without meaning to. This needs to be more clearly labelled.

**Comment by peppy** [comment]
Completely agree.

**Comment by arflyte** [comment]
![photoshop_180806-183031](https://user-images.githubusercontent.com/3632750/43709222-3780a874-99a7-11e8-838b-df8031b38c8f.png)

Post Preview will be in the same postbox to avoid redundant avatar section, separated with different background shade. Timestamp states "Post Preview".

Screenshot based on the newer forum design; adapt the design to the current forum design.
