### ISSUE TITLE
Quicklink to private messages on new forums

### ISSUE THREAD

**Issue by Okorin** [ppy/osu-web#3573]
I didn't find this anywhere as an issue so:
old page contained links to quickly pm someone about a forum post they made - at least i've been using this feature from time to time instead of going to someone's profile to click "send private message"

![example](https://i.imgur.com/JHJHpr0.png)

**Comment by Joehuu** [comment]
See #2741.

**Comment by Okorin** [comment]
eh, it's there but i didnt know hovering the user's avatar would show this 

it's admittedly not very obvious that it does this
