### ISSUE TITLE
Filter by user doesn't work well with user colours

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#3580]
iirc this was mentioned in discord but I can't find a web issue for it
users with colours are difficulty to read on the filter

![screen shot 2018-08-16 at 10 30 00 am](https://user-images.githubusercontent.com/30382015/44183884-73a4ec80-a13f-11e8-895a-2cb7e449d859.png)

**Comment by VenixOSU** [comment]
In addition to the provided screenshot, here's one with alumni colour
![](https://venix.s-ul.eu/TZhuPwoR)

**Comment by notbakaneko** [comment]
Can't say we didn't see this coming 🥇 

Since the discussion page is being updated to a different design and layout that doesn't involve dark text on dark background or a dropdown list, the most we'll probably be doing for now is dropping the user colours.
