### ISSUE TITLE
Letter rank counter appears to be broken again

### ISSUE THREAD

**Issue by osuLuna** [ppy/osu-web#3582]
My profile currently shows 9 XH ranks when I should have 200+. This might potentially be caused by issues processing multiple scores on the same difficulty of a map as I achieved 10 XH ranks within the last 24 hours but they were spread across only 9 difficulties (I got both HRDTFL and HDHRDTFL XHs on one of them) and all my XH ranks were achieved on difficulties that I had already nomod SS'd.
Furthermore, the rank counters seem to have some major inconsistencies lately. My displayed SS count changed from ~3.2k to ~3.7k and back to ~3.2k in the span of the last three days. You can confirm this via the cached data on osudaily.net, and I know it's not an issue with the site since I actually saw the numbers on my user page. My S count also randomly jumped from 561 to 624 even though I didn't submit any S ranks recently (at least none that I didn't immediately improve to SS), but unlike the SS count it didn't drop back down (just a change from 624 to 623, which makes sense since I upgraded an older S rank to SS yesterday).
I wish I could tell you which of these numbers are the actually correct ones, but unfortunately I have no clue. I just farm SS and don't really keep track of my progress beyond the thousands digit.
A similar thing has happened before but been resolved, so I'm not sure if the causes are related https://github.com/ppy/osu-web/issues/2140

**Comment by peppy** [comment]
Is this still an issue? Could you please link your profile?

**Comment by osuLuna** [comment]
It seems to have fixed itself, at least from what I can tell (my XH ranks returned to a believable number but again, I have no idea which numbers are exactly correct). If you want to look at some data that shows what happened, I suggest the osudaily stats. WWW's graph is especially erratic, probably due to the high number of scores he has (https://osudaily.net/profile.php?u=1011&m=0 go to "Graphs" and select "Notes").
