### ISSUE TITLE
unlocked achievement without completing the criteria

### ISSUE THREAD

**Issue by R0slaN** [ppy/osu-web#3586]
just unlocked "Overconfident" medal after maxing (1,000,000 score) Jinjin - pi [4K Beginner].
![capture2](https://user-images.githubusercontent.com/37221780/44294438-bf6ea780-a29f-11e8-9d32-3626971f255e.PNG)
my profile:
https://osu.ppy.sh/users/7538867
unlock criteria for Overconfident:
http://haitai.jp/overconfident/
map:
https://osu.ppy.sh/beatmapsets/519251/#mania/1103144

sorry if wrong repo btw, not sure where to submit if not here.

**Comment by peppy** [comment]
Looked into this but the underlying code looks correct... needs further investigation.

**Comment by peppy** [comment]
Should be resolved now. Thanks for pointing this out.
