### ISSUE TITLE
Show previous beatmap spotlight ranking on userpage

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#3598]
from discussion in #osu-spotlights

it would be cool if players could show off what rank they achieved in the last month/season's beatmap spotlights scoreboard, and it would encourage more people to play them. this should only be shown if they completed at least one difficulty from every spotlighted map (i.e. if they got the badge for participation)

edit: in addition, I think the 1st/2nd/3rd rankings should have some special style or background, so that it feels more like an award than a statistic

**Comment by peppy** [comment]
This is actually the direction that charts will be going regardless, so rest assured this will be a thing sooner or later.

**Comment by cl8n** [comment]
done via ranking badges for the playlist spotlights
