### ISSUE TITLE
Improve code blocks text in forum posts

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#3599]
The code blocks: [code][/code]

I think text in code blocks should have a similar style to what the text looks like when you edit a post. It's better if the technical information displayed is condensed instead of spread out. This way the text is less likely be subject to line wrapping and allows the person to look at more info at once.

**Comment by peppy** [comment]
I think this has been addressed with the new design? cc @nanaya

**Comment by nanaya** [comment]
Seems missing @arflyte

**Comment by arflyte** [comment]
Code blocks, notice and list designs updated in figma.

**Comment by notbakaneko** [comment]
#4983?
