### ISSUE TITLE
Let wiki articles set a different fallback language

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#3603]
there are very few cases where articles aren't written in English as the original language, so the English article (if it exists) should be marked as the translation in those cases, not the original

the example that came up in osu-wiki is an article for a region-specific tournament written in the native language, which hasn't been translated to English yet

**Comment by nanaya** [comment]
Not sure if fallback to non-English is useful. An Indonesian speaker getting a Polish fallback page would just be confused.

**Comment by cl8n** [comment]
yeah that's true. they would still have the note saying that Indonesian doesn't exist, and Polish is the default for this article, though

also, the current wiki assumes that English is always up-to-date, but in this case it wouldn't be. it's not possible to mark English as outdated (or have it not exist) at the moment

would your suggestion just be to 404 for other locales then? I really doubt the example I mentioned in OP will get an English translation soon

**Comment by nanaya** [comment]
Can't you just put a simple description in English page with link to specific locale?

**Comment by peppy** [comment]
I'm all for always having an english stub page in such scenarios. I don't think we should add this logic.
