### ISSUE TITLE
Store stock levels for products with master products

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#361]
Products which have master products where the master product's stock is zero show "out of stock" when they shouldn't (see osu!keyboards [on the store](http://store.ppy.sh/store/listing) right now).

![](https://puu.sh/n8vaF/4335b7549f.png)
^ should not show "out of stock" because

![](https://puu.sh/n8vbX/fd70f36b84.png)
^ many varieties are still in stock

The stock check at this level should check all varieties and not show "out of stock" if any are still available.

**[Bounty](https://goo.gl/nFdoyI) offered**: 20

As always, ask if you have any questions, and feel free to jump on the [osu!dev slack](http://osu.ppy.sh/p/slack) for more real-time discussion.

**Comment by nanaya** [comment]
this seems to work https://0paste.com/8252-64835e9f.txt

*goes back to chart

**Comment by peppy** [comment]
wanna PR that?

**Comment by peppy** [comment]
Resolved by https://github.com/ppy/osu-web/pull/363.
