### ISSUE TITLE
Loved maps do not appear under "All" tab in searches

### ISSUE THREAD

**Issue by Toybickler** [ppy/osu-web#3620]
https://i.imgur.com/YGCBkOz.png vs. https://i.imgur.com/C9nXRv0.png

This map with the same keywords will only appear when looking specifically under the "Loved" tab, and not under the "All" tab. 

Same issue on the new site, but easier to visualize with the old.

**Comment by notbakaneko** [comment]
aay what?

![image](https://user-images.githubusercontent.com/1694544/44965716-0e8c2c00-af72-11e8-8e4a-83558011dfd4.png)

**Comment by Toybickler** [comment]
oh WOOPS,

it's an old site issue, I was just braindead when checking the new site

**Comment by peppy** [comment]
Has been fixed on `web-10`
