### ISSUE TITLE
Add a subtitle mark to wiki

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#3626]
should look something like
```
---
subtitle: "Community Tournaments"
---
```
and override the original subtitle
It could be pretty useful for translating the subtitles. It shouldn't change the original path to the index article.

**Comment by cl8n** [comment]
already exists https://github.com/ppy/osu-web/blob/master/app/Models/Wiki/Page.php#L285

**Comment by TPGPL** [comment]
does it change the index path though?
