### ISSUE TITLE
Header on the store page of osu!supporter tag is unreadable

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#3629]
![](https://puu.sh/BpHAC/0119cd468c.jpg)

https://osu.ppy.sh/store/products/208

should either change the font color or the background image

**Comment by notbakaneko** [comment]
![image](https://user-images.githubusercontent.com/1694544/45176807-1850b080-b24c-11e8-9241-86283147a02e.png)
The text on mine sure looks more readable than yours

**Comment by TPGPL** [comment]
Firefox Quantum 61.0.2

**Comment by peppy** [comment]
Do we remove this text from every page?
