### ISSUE TITLE
Strange line on profile page

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-web#3640]
![image](https://user-images.githubusercontent.com/18349191/45222988-92367780-b2e8-11e8-9b07-c32cac055a57.png)
![image](https://user-images.githubusercontent.com/18349191/45223001-9cf10c80-b2e8-11e8-86a3-8918b506d3e5.png)
![image](https://user-images.githubusercontent.com/18349191/45223029-af6b4600-b2e8-11e8-9cd4-f776e0e0fb55.png)
this line only appear when following or friends

Browser: Chrome 69.0.3497.81 (64bit)
Resolution: 1920x1080 (125%)

**Comment by peppy** [comment]
I *believe* this line is coloured based on the user group, but not too sure.

**Comment by Lyawi** [comment]
@peppy i think he was talking about the line below texts and friends button, which doesnt appear on the last screenshot

**Comment by WalterToro** [comment]
Yes is based on the usergroup, last screenshot is black due to deadbeat being an alumni.

![](https://walter.s-ul.eu/gYtHcuwZ.png)

**Comment by kj415j45** [comment]
Re: https://github.com/ppy/osu-web/issues/3640#issuecomment-419736204

yep, what i mean is the line under the friends button

**Comment by peppy** [comment]
Could you please provide a screenshot of the whole page then? It's hard to grasp what is happening when you focus mostly on the part which you're not trying to explain.

**Comment by kj415j45** [comment]
![image](https://user-images.githubusercontent.com/18349191/45277117-cbddcd00-b4f8-11e8-8495-2ab3d74b5f61.png)
![image](https://user-images.githubusercontent.com/18349191/45277133-eca62280-b4f8-11e8-8ec9-c546851e002b.png)
![image](https://user-images.githubusercontent.com/18349191/45277146-fe87c580-b4f8-11e8-8149-2258f8050cc2.png)

the red arrow point to the strange line
