### ISSUE TITLE
Local setup issues (SQL tables not found, etc)

### ISSUE THREAD

**Issue by Hughp135** [ppy/osu-web#365]
Hi, noob question here (hope this is the right place to ask) but after using vagrant up I am unable to view some parts of the site due to the tables not being found (i.e. 'osu_genres' table not found). The following screenshot is from /beatmaps. Other pages like user profiles are working.

<img width="700" alt="screen shot 2016-02-15 at 13 25 32" src="https://cloud.githubusercontent.com/assets/12624925/13049954/3e79101c-d3e8-11e5-976b-67327edfc2af.png">

I've checked out the master branch but can't see any migrations or other sql statements that create this table. Please forgive me if I'm missing something obvious or if I'm in the wrong branch.

Any help would be appreciated. Thanks :)

**Comment by Bobo1239** [comment]
For now you can just add
```
--
-- Table structure for table `osu_genres`
--

DROP TABLE IF EXISTS `osu_genres`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `osu_genres` (
  `genre_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`genre_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
/*!40101 SET character_set_client = @saved_cs_client */;
```
to `db-osu-structure.sql` and repopulate the DB or execute it directly. (e.g. over [Adminer](https://www.adminer.org/))

**Comment by peppy** [comment]
Here's the full data:

```
CREATE TABLE osu_genres
(
    genre_id SMALLINT(5) UNSIGNED PRIMARY KEY NOT NULL,
    name VARCHAR(200) NOT NULL
);

INSERT INTO osu.osu_genres (genre_id, name) VALUES (0, 'Any');
INSERT INTO osu.osu_genres (genre_id, name) VALUES (1, 'Unspecified');
INSERT INTO osu.osu_genres (genre_id, name) VALUES (2, 'Video Game');
INSERT INTO osu.osu_genres (genre_id, name) VALUES (3, 'Anime');
INSERT INTO osu.osu_genres (genre_id, name) VALUES (4, 'Rock');
INSERT INTO osu.osu_genres (genre_id, name) VALUES (5, 'Pop');
INSERT INTO osu.osu_genres (genre_id, name) VALUES (6, 'Other');
INSERT INTO osu.osu_genres (genre_id, name) VALUES (7, 'Novelty');
INSERT INTO osu.osu_genres (genre_id, name) VALUES (9, 'Hip Hop');
INSERT INTO osu.osu_genres (genre_id, name) VALUES (10, 'Electronic');
```

**Comment by Hughp135** [comment]
Thanks.

**Comment by Hughp135** [comment]
P.S. Shouldn't the structure sql file be updated so that other people don't have this issue in the future? Want me to add it in?
