### ISSUE TITLE
Switching gamemodes on a beatmap page should stay on the same difficulty

### ISSUE THREAD

**Issue by GrilledCheeese** [ppy/osu-web#3652]
Currently when switching gamemodes on the beatmap page it goes to the highest difficulty like so:
From this difficulty (Normal):
![normal](https://i.gyazo.com/3d19893ee058ff097f4b534d0d0f06c5.png)
To the highest difficulty (gary's Insane):
![garyisinsane](https://i.gyazo.com/aa14d90bfa9f0f2c65b8c5355f0e9895.png)
Also when opening the beatmap page from within the game I'd like it to open the gamemode I'm in so it opens the leaderboard that I want to see and not have to first switch gamemodes, then click the appriopriate difficulty to see the leaderboard I wanted. If possible, thank you.

**Comment by nanaya** [comment]
Apparently this has been implemented.
