### ISSUE TITLE
Comment System: Restrict view of deleted comments

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#3659]
Seems kind of weird that anyone can see that comments were deleted, when in the forums and modding discussions deleted posts can not be seen by regular users at all.
![image](https://user-images.githubusercontent.com/33286824/45389361-bbf1e600-b5e9-11e8-84ce-3e5a511b86c7.png)
![image](https://user-images.githubusercontent.com/33286824/45389539-36bb0100-b5ea-11e8-94d2-fae826a210fd.png)

I think it'd make more sense to make it so only osu! moderators , qat, gmt, admins, etc can see them, and that deleted comments be completely hidden from regular users.

**Comment by peppy** [comment]
Completely agree. It’s pointless and a huge waste of space.

In the one case it’s required (when there’s non-deleted replies to a deleted comment) it should not take up the same space as a normal comment would.

**Comment by nanaya** [comment]
It's more compact now.

**Comment by cl8n** [comment]
why not just hide them entirely though (besides when they have replies, as peppy mentioned)? they don't provide any information to normal users

**Comment by nanaya** [comment]
It messes the reply counter and may cause show more link to just disappear after clicking.
