### ISSUE TITLE
When reaching 1000 follower, the count goes 1

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3669]
https://twitter.com/Zetera_sm/status/1040152795410845702

**Comment by kj415j45** [comment]
![image](https://user-images.githubusercontent.com/18349191/45501010-a5e35180-b7b2-11e8-8686-47214d60ba7b.png)
it looks fine to me. It was 1000, add me => 1001

**Comment by Lyawi** [comment]
![unknown](https://user-images.githubusercontent.com/32525896/45502573-a533c680-b784-11e8-9c14-69c5290f9eb7.png)
still 1. might be related to brower version?

i've got Chrome, version 69.0.3497.92

**Comment by GSculerlor** [comment]
Working fine on Chrome 69.0.3497.92
![screenshot](https://gsculerlor.s-ul.eu/NCkH8AYO)

**Comment by GrilledCheeese** [comment]
I don't know how to check chrome version, but I got 1
![image proof](https://i.gyazo.com/6b5dd819f6d0e5114e24588f3a9b8f1e.png)
Even after I updated my chrome, it looks a lot fancier now, but I still have 1: (version Versie 69.0.3497.92)
![upgraded chrome](https://i.gyazo.com/3d24a281abecc061b4c7eb4741217809.png)
Also in firefox:
![firefox screenshot](https://i.gyazo.com/189ce6b8c0ce542fb4b3567c559867cc.png)

**Comment by GSculerlor** [comment]
Looks like just by changing web's language it make this issues appear just like @GrilledCheeese says.
I try to change from Bahasa Indonesia to Nederlands and it changed from 1000 to 1

**Comment by Lyawi** [comment]
yeah, it's only problematic with 1000 btw. At 1001 it's showing normal.

So at least no browser issue?! I've just checked all translations and French, Japanese, Turkish, Korean, Russian, Thai, Vietnamese, both Chinese show 1000 too. **All others (English as well) don't.**
