### ISSUE TITLE
"you have posted on this topic" indicator and "list of x's posts on a topic" function

### ISSUE THREAD

**Issue by AncuL001** [ppy/osu-web#3679]
the first one is already on the old forum, and is pretty useful especially on modding queues
![image](https://user-images.githubusercontent.com/16044057/45596617-a6fdc400-b9e8-11e8-910f-ee05a50cd577.png)

the second one is not, but it's a useful bonus on modding queues so we don't accidentally requested the same beatmap twice.
actually we already have something similar (https://osu.ppy.sh/home/search?mode=forum_post), but it requires you to have a query, which isn't really used much and is kinda far from what i request

**Comment by dorothy3242** [comment]
The second half of this issue is already mentioned in https://github.com/ppy/osu-web/issues/3059

**Comment by nanaya** [comment]
Duplicates as mentioned above.
