### ISSUE TITLE
"New comment" textarea size is hard to notice

### ISSUE THREAD

**Issue by GSculerlor** [ppy/osu-web#3680]
Make it different between textarea color and the outer div background to make it easier to notice the area size

![comment section example](https://gsculerlor.s-ul.eu/ZJt9fbqu)
![dark comment section example](https://gsculerlor.s-ul.eu/OyOXyC5R)

**Comment by arflyte** [comment]
![photoshop_180918-184555](https://user-images.githubusercontent.com/3632750/45679247-2fa86b80-bb73-11e8-8d77-b9a81d31dffe.png)

**Comment by TPGPL** [comment]
how should it look like in the new site design?

**Comment by TPGPL** [comment]
should be closed
