### ISSUE TITLE
Add a way for GMT/QAT to edit forum polls

### ISSUE THREAD

**Issue by osuMao** [ppy/osu-web#3681]
There currently is no way to edit a poll after posting so that if you'd want to change something (e.g. a typo or add another option) you'd have to repost it completely.

I'd recommend to just add an Edit/Delete button like for posts that opens the poll creation window and depending on the change, editing should probably reset the poll.

**Comment by TPGPL** [comment]
duplicate of #1711 ?

**Comment by osuMao** [comment]
Oh yeah, I had looked through it last week but probably missed it.
