### ISSUE TITLE
Add an ability for the mapset creator and QATs to set Genre/Language

### ISSUE THREAD

**Issue by osuMao** [ppy/osu-web#3682]
As there is currently no way to see Genre/Language on the new site, this issue probably needs to be addressed first: https://github.com/ppy/osu-web/issues/2751 

Additionally to this feature, there needs to be the ability to set genre and language but contrary to the old site, mappers should be able to set them themselves in order to improve the searching process for pending and graveyarded maps.

Moreover, mappers should not be able to change these settings after the mapset is **qualified**. From thereon only QATs should be able to change it in order to avoid abuse.

**Comment by cl8n** [comment]
not sure how to fit this one in visually, I was going to tack on a pencil button similar to descriptions for each of genre/language but there's not enough room for it
![chrome_2019-03-18_21-30-55](https://user-images.githubusercontent.com/9954349/54580433-482ffc00-49c5-11e9-8f72-07d99772c5ac.png)

**Comment by FlyingStefan** [comment]
I do not really like to give regular mappers the ability to set the genre and language for their maps. It didn't work out so well with the BNG and I have even less faith into regular mappers.

**Comment by cl8n** [comment]
mappers are allowed to set their own metadata until qualified, I don't see how this is anything more than an extension of metadata

**Comment by FlyingStefan** [comment]
Unlike genre and language, a map does not get qualified with obvious false metadata. It is very different to each other.

**Comment by cl8n** [comment]
so just don't qualify maps with incorrect genre/language, or have someone set those properly during qualified

I think the point of this change isn't specifically for the ranked section anyway, it's just so people can properly label their maps without bugging QAT

**Comment by Loctav** [comment]
I'd like to re-bump this issue because currently we have currently over a hundred Ranked beatmap sets where nobody has ever specified the language or genre at all. (see https://osu.ppy.sh/beatmapsets?g=1&l=1&s=ranked)

**Comment by hypercyte** [comment]
Wouldn't it be helpful to allow BNs to change the language/tags too like Noffy suggested?

It'd be good if the mapper forgot to set them before we qualify the map for example !
