### ISSUE TITLE
Disqualifications do not show a preview in the events listing

### ISSUE THREAD

**Issue by osuMao** [ppy/osu-web#3686]
Disqualifications currently just say `[no preview]` on the `/event` page.

![ss 2018-09-16 at 07 39 40](https://user-images.githubusercontent.com/41975558/45599249-7b7ad980-b9e8-11e8-83c8-79751c70150a.jpg)

This should be changed into actually showing the disqualification post's content:
![ss 2018-09-16 at 07 42 13](https://user-images.githubusercontent.com/41975558/45599264-b54be000-b9e8-11e8-8bd7-b8282a8749a5.png)

![ss 2018-09-16 at 07 43 31](https://user-images.githubusercontent.com/41975558/45599269-d6143580-b9e8-11e8-9b4a-1683bf44b378.jpg)

**Comment by nanaya** [comment]
Fixed in #5963.
