### ISSUE TITLE
Add up/downvotes to comments section

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#3688]
Comment sections are more or less first come first serve now, it is imo a bit too chaotic. Adding back upvotes would help bring more relevant comments to the top

**Comment by GSculerlor** [comment]
Related with #3627 I think

**Comment by Xinnoh** [comment]
searched but didn't find a dupe issue, thought I was missing something
probably best to close then since it's already on the list
wouldn't make sense to have an issue open for just one of those and not the others
