### ISSUE TITLE
Setup issue with Elasticsearch

### ISSUE THREAD

**Issue by Hughp135** [ppy/osu-web#369]
I'm having an issue with getting beatmap listing to work, specifically with the elasticsearch provider.

I noticed that the function call to searchES() in the BeatmapSet model was returning an empty array, so I tried dumping the results of the elasticsearch error:

BeatmapSet.php

<img width="510" alt="screen shot 2016-02-16 at 11 36 00" src="https://cloud.githubusercontent.com/assets/12624925/13075219/8104d808-d4a1-11e5-8333-06960f39056e.png">

This gives:

<img width="480" alt="screen shot 2016-02-16 at 11 01 07" src="https://cloud.githubusercontent.com/assets/12624925/13075228/881b9a82-d4a1-11e5-8596-28bde6281293.png">

The full error message (returning $results) gives:

<img width="1028" alt="screen shot 2016-02-16 at 11 21 02" src="https://cloud.githubusercontent.com/assets/12624925/13075391/bcb2f00a-d4a2-11e5-9a85-cabe3b8cf89f.png">

Looks like it's trying to perform a get request to localhost:9200/osu/beatmaps/_search. Is there meant to be an ES server running on this port or something? I haven't used ES before so I'm a bit confused about this... Any pointers would be appreciated.

**Comment by nanaya** [comment]
It sure does. You need load some... stuff... to elasticsearch. You need to install it... and the elasticsearch-jdbc plugin.

Unfortunately I don't even remember how to do it but there's this script which may give some hint.

```
#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
bin=${DIR}/../bin
lib=${DIR}/../lib

echo '
{
  "type":"jdbc",
  "jdbc":{
    "fetchsize":1000,
    "max_retries":3,
    "url":"jdbc:mysql://${mysql_host}:3306/osu",
    "user":"${mysql_user}",
    "password":"${mysql_password}",
    "sql":"select s.beatmapset_id as _id, s.user_id, s.artist, s.artist, s.artist_unicode, s.title, s.title_unicode, s.creator, s.source, s.tags, s.video, s.storyboard, s.epilepsy, s.bpm, s.approved, s.approved_date, s.submit_date, s.last_update, s.rating, s.offset, s.genre_id, s.language_id, s.star_priority, s.filename, s.filesize, s.filesize_novideo, s.favourite_count, s.download_disabled, s.play_count, s.thread_id, s.difficulty_names, b.beatmap_id, b.version, b.total_length, b.hit_length, b.countTotal, b.countNormal, b.countSlider, b.countSpinner, b.diff_drain, b.diff_size, b.diff_overall, b.diff_approach, b.playmode, b.approved, b.difficultyrating, b.playcount, b.passcount FROM osu_beatmapsets s     JOIN osu_beatmaps b USING (beatmapset_id)     WHERE active = 1 AND orphaned = 0",
    "index":"osu",
    "type":"beatmaps"
  }
}
' | java \
    -cp "${lib}/*" \
    -Dlog4j.configurationFile=${bin}/log4j2.xml \
    org.xbib.tools.Runner \
    org.xbib.tools.JDBCImporter
```

**Comment by Hughp135** [comment]
Thanks for the reply nanaya. Definitely clears things up :)

On looking through it a bit more, I was wondering why this provider is even being used? Could queries not simply be done using laravel's query builder?

Does using ES have any benefits over the query builder? e.g.

```
return Beatmapset::where([ $params ])
    ->skip($offset)
    ->take($results_per_page)
    ->orderBy('submit_date','desc')
    ->get();

```

**Comment by peppy** [comment]
ES gives us much better index coverage of beatmap data. If we were to rely on MySQL, we would have to basically index every column, and would still not get the same level of performance.

It also provides fulltext search that is miles better than anything MySQL can offer.

**Comment by Hughp135** [comment]
Ah right fair enough. I guess that makes sense with the amount of beatmaps that will need to be searchable through!

**Comment by Hughp135** [comment]
Well I kinda failed getting it installed since I'm on mac atm and there isn't a package for elasticsearch-jdbc for mac as far as I can see.

Might give it another go when I get home, or perhaps just use alternative functions for testing stuff locally.

**Comment by peppy** [comment]
I mean depends on what you are testing, but you CAN easily replace the ES return with database lookups without much effort. Searching won't be so simple, but if you just want beatmaps in the listing then...

**Comment by Hughp135** [comment]
Well if I could get ES working then I could potentially help with additional controller methods etc if needed.

But firstly I just wanted to populate the site with some data so I could get started on some of the minor frontend issues etc. Any chance of getting a database export like you mentioned earlier?

**Comment by Hughp135** [comment]
well believe it or not, I actually got this working inside the virtualbox VM. I've even added some code to the bootstrap.sh file to automate the setup of the elasticsearch server.

Now the only issue I'm having is that to index the SQL database I have to manually run the script that @nanaya posted. Any pointers on how to automate it so that this won't need to be manually done to load new entries to the db?

# install java & elasticsearch
    sudo apt-get install openjdk-7-jre-headless -y

    # install elasticsearch
    wget https://download.elasticsearch.org/elasticsearch/release/org/elasticsearch/distribution/deb/elasticsearch/2.2.0/elasticsearch-2.2.0.deb
    sudo dpkg -i elasticsearch-2.2.0.deb
    sudo update-rc.d elasticsearch defaults

    # install unzip
    sudo apt-get install unzip

    wget http://xbib.org/repository/org/xbib/elasticsearch/importer/elasticsearch-jdbc/2.2.0.0/elasticsearch-jdbc-2.2.0.0-dist.zip

    unzip elasticsearch-jdbc-2.2.0.0-dist.zip

    cd elasticsearch-jdbc-2.2.0.0/bin

    cp /vagrant/conf/jdbcexec.sh jdbcexec.sh

    bash jdbcexec.sh

    sudo service elasticsearch start

**Comment by peppy** [comment]
Good job getting things working. Setup seems a bit rough (might be best to not run every 15 seconds but just populate once on build/deploy) but at least we have something for new users to work with.

**Comment by Sakisan** [comment]
Another way to index the beatmaps is by using logstash. 
Using logstash is very simple: download it and run this command:

`logstash-2.2.2/bin/logstash -f osuweb-beatmaps.conf`

my osuweb-beatmaps.conf
```
input {
    jdbc {
        jdbc_connection_string => "jdbc:mysql://172.17.0.2:3306/osu?user=osuweb"
        jdbc_user => "osuweb"
        jdbc_driver_library => "/home/deepin/Projects/logstash/mysql-connector-java-5.1.36.jar"
        jdbc_driver_class => "com.mysql.jdbc.Driver"
        statement => "select s.beatmapset_id, s.user_id, s.artist, s.artist, s.artist_unicode, s.title, s.title_unicode, s.creator, s.source, s.tags, s.video, s.storyboard, s.epilepsy, s.bpm, s.approved, s.approved_date, s.submit_date, s.last_update, s.rating, s.offset, s.genre_id, s.language_id, s.star_priority, s.filename, s.filesize, s.filesize_novideo, s.favourite_count, s.download_disabled, s.play_count, s.thread_id, s.difficulty_names, b.beatmap_id, b.version, b.total_length, b.hit_length, b.countTotal, b.countNormal, b.countSlider, b.countSpinner, b.diff_drain, b.diff_size, b.diff_overall, b.diff_approach, b.playmode, b.approved, b.difficultyrating, b.playcount, b.passcount FROM osu_beatmapsets s     JOIN osu_beatmaps b USING (beatmapset_id)     WHERE active = 1 AND orphaned = 0"  
        jdbc_validate_connection => true
    }       
}
output {
    elasticsearch {
        index => "osu"
        document_type => "beatmaps"
        document_id => "%{beatmapset_id}"
    }       
}
```
- Don't forget to put the correct ip for the database connection
- and the path to mysql-connector-java-5.1.36.jar (which you need to download first)


I'm running elastic search in a docker image so I also needed to change the environment variable in [project-root]/.env:
`ES_HOST=172.17.0.1:9200`

**Comment by nekodex** [comment]
There has been support added for falling back to database queries when elasticsearch is not configured now, closing this issue.
