### ISSUE TITLE
Some areas of restricted users' profiles display incorrectly

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#3694]
Likely due to shared filtering logic, restricted users are unable to see certain portions of their profile as expected.

**Comment by veke66** [comment]
Just wanted to bump this, as it is something really irritating, especially now that the site switcher button is gone (I could circumvent the issue by switching to the old website) and I really hope you can do something about it.

Also while we're here, restricted users' personal best pp plays are not getting updated on their profile (which, again, can be circumvented by going to the old website, but seeing how it's on its way to deprecation, I'd rather that be fixed too)
