### ISSUE TITLE
Wiki page template

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#37]
wiki page template

Trialling some larger bounties. This one involves implementing a design concept fully.

![](http://puu.sh/jZ30d/43955f5186.png)

This is the wiki page template, which will be housing wiki articles currently found at http://osu.ppy.sh/wiki/

Requirements:
- Make a blade template to match the attached page style.
- Follow existing styling naming standards.
- Reuse existing styles where possible.
- The left menu should have a closed and open state (both shown in the template).
- The left menu should follow the screen when scrolling, so it is always openable using a single click.

**[Bounty](https://goo.gl/nFdoyI) offered**: 50

As per bounty guidelines, it is recommended that you claim this issue if you are serious about it.

Ask away for further clarifications.

PSD: http://puu.sh/jZ359/b67cf63589.psd

**Comment by abalabahaha** [comment]
What about on smaller screens? Would the sticky menu be taking up too much space?

**Comment by peppy** [comment]
The mobile design of the menu has not yet been finalised, so it's fine to just hide it when on a portable device (not sure it's that useful in this case anyway).

**Comment by Repflez** [comment]
The "Current events" (it's just another article on the wiki) and "Related changes" (lists changes in pages it links and such) links may go.
Special pages link could be removed since it's only a hub for certain pages on the current wiki or could be reworked to be an actual listing of pages that help editors but that's another story.
Do we need a printable version of an article? "Permanent link" may go too but it may help when linking a specific revision of an article...

**Comment by peppy** [comment]
I believe we are going to have options like "edit current page" etc. in that menu, so it will definitely have a place going forward. I agree that a lot of the items there at the moment can be removed.

**Comment by MasterBugPatch** [comment]
@peppy So for this bounty, it's just the programming of design correct? We don't actually have to have program in the Wiki part? For example I can just program the design with lorem ipsum as text?

**Comment by peppy** [comment]
Correct. This is just for the base template and menu functionality. I'd recommend using the text in the PSD so you can ensure you get as close to the mock-up as possible.

**Comment by MasterBugPatch** [comment]
Okay, I'd like to claim this then for the 10 days.

**Comment by peppy** [comment]
`bounty / 10` so 5 days for this. and sure, best of luck.

**Comment by MasterBugPatch** [comment]
@peppy Thanks, I'll keep you updated also.

**Comment by MasterBugPatch** [comment]
@peppy In the PSD, the wiki is under community? But actually, it's under help. Can I continue under help or should I reprogram it to community?

**Comment by peppy** [comment]
i think help is correct. @arflyte just doesn't update the header when he makes these :sleeping:.

**Comment by MasterBugPatch** [comment]
Alright, help it is ^.^, thanks.

**Comment by MasterBugPatch** [comment]
@arflyte @peppy On the Wiki-Navigation, Are the ( = ) buttons,icons or are they linked somewhere?

**Comment by MasterBugPatch** [comment]
Nevermind. I figured out how to create them myself by surrounding a fa icon in a circle.

**Comment by MasterBugPatch** [comment]
Finished
https://github.com/ppy/osu-web/pull/60

**Comment by TPGPL** [comment]
close this issue

**Comment by TPGPL** [comment]
@peppy Why isn't this issue closed?

**Comment by MasterBugPatch** [comment]
@TPGPL @nanaya wants me to make changes to the CSS to follow BEM, I should probably get to it soon.

**Comment by LiquidPL** [comment]
@TPGPL you probably shouldn't mention peppy in every comment you make, i'm sure he goes through them anyways.

**Comment by TPGPL** [comment]
@LiquidPL ok, thanks for the tip.

**Comment by cl8n** [comment]
Has the design for this changed at all? I see it's been quite a while since anybody was working on this...

**Comment by MasterBugPatch** [comment]
@cl8n Yeah it's done basically, just needs a few syntax changes

**Comment by MasterBugPatch** [comment]
@cl8n I haven't got to it yet because I'm lazy

**Comment by nanaya** [comment]
Kind of done.
