### ISSUE TITLE
Maps not showing in MP links

### ISSUE THREAD

**Issue by Negaosu** [ppy/osu-web#3702]
For just about every MP link recently - maps are not showing after they are completed.
Here's an example from a 1v1 that just finished: https://osu.ppy.sh/community/matches/46110648
https://i.imgur.com/LcAJQEc.png

**Comment by SpartanPlume** [comment]
After testing with the api v1, I can see that the problem is that the `scores` array is empty in this mp link. 

The problem seems to have been fixed (or fixed itself, I don't know) for now though, tried with normal lobbies and tournament lobbies (1 player only).

**Comment by peppy** [comment]
I was looking for this report today and couldn't find it anywhere. I saw this while I was away from my PC and fixed it when I arrived back, but couldn't report it as resolved.

It has indeed been resolved now; thanks for the report.
