### ISSUE TITLE
Friends list in one view

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3704]
Could it be toggleable between seeing your friends in a long list or one view on https://osu.ppy.sh/home/friends ? Like having a button above the headline or in settings how you would like to see them

Same exists on old site:
https://osu.ppy.sh/p/friends (long)
https://osu.ppy.sh/forum/ucp.php (one view)

I think people (including me) prefer the second since you don't have to scroll a lot. Won't be a valid reason but yeah, people (including me here again) often look at their friends list for whatever reasons *cough*

**Comment by peppy** [comment]
Backburner, but might be something worth considering.

**Comment by cl8n** [comment]
this page also performs pretty poorly for me (probably because of how many cards are loading in?), I can make my browser freeze for a few seconds by scrolling down to the bottom

on Chrome 69.0.3497.100 on two different computers, if that's relevant

**Comment by Joehuu** [comment]
Should be considered on redesign in #4232.

**Comment by Lyawi** [comment]
lemme bump this quickly, i did a poorly image to imagine 

![hello](https://user-images.githubusercontent.com/32525896/63432370-51643f80-c421-11e9-8f34-b14c94f7e2ad.png)

there are "buttons" to choose between first list and the second above the list so everyone could decide what they want to look at

current friendlist looks cool, but its not worth scrolling it all down to look for someone's name (i know search function exist but this isnt the same) or uh..just looking at them? that's why i said "in one view"
please also add the mutual thing behind the names so you could directly see it

**Comment by nekodex** [comment]
As a compromise, how do you feel about changing list view to something like this? Is this compact enough for you?

![](https://puu.sh/E83Du/ac000f5596.png)

**Comment by cl8n** [comment]
if the idea is to get the whole list on one page, you could probably drop the country, supporter badge and online status to save a lot of space

**Comment by peppy** [comment]
What is the use case for wanting "everything on one page"?

**Comment by Lyawi** [comment]
@peppy the new friendslist doesn't have any use for me anymore because its just big. i used to click my friend's profiles there and having a view of seeing who mutualed me and who doesn't

**Comment by peppy** [comment]
See the above screenshot. Is this compact enough for you?

**Comment by Lyawi** [comment]
yes lol

**Comment by Lyawi** [comment]
wait i didnt know this exists already: https://osu.ppy.sh/home/friends?view=list

it looks fine, should just be showing if mutual or not

**Comment by cl8n** [comment]
another reason people liked the super compact list from the old site is because you could easily share or display the list with mutual statuses showing. it's really common to see screenshots of friends lists on userpages and Twitter pins, and I have a feeling that removing this view (when the old site becomes unavailable) will just make people mad or something

**Comment by Joehuu** [comment]
Resolved in https://github.com/ppy/osu-web/pull/5813.
