### ISSUE TITLE
Display Drain time

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#3705]
The new website does not display the drain time of a beatmap.
![image](https://user-images.githubusercontent.com/33286824/45923081-19b7e500-beaa-11e8-920a-8104d17a1aa3.png)
![image](https://user-images.githubusercontent.com/33286824/45923083-20465c80-beaa-11e8-9381-a77d91beff5d.png)

considering there is a fairly large number of rules in the ranking criteria relating to drain time, hiding this kind of sucks, because that means when the old website is gone drain time would need to often be calculated manually for maps with breaks to see if they meet the requirements for this or that.

**Comment by peppy** [comment]
If not as its own always-visible stat, it should be in the tooltip.
