### ISSUE TITLE
Comment section in forums: Preview doesn't show when having a big image in it

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3710]
![unknown](https://user-images.githubusercontent.com/32525896/46060801-b5747a00-c164-11e8-9d7d-acf504f29c3a.png)

If it's important, actual image of the comment: https://cdn.discordapp.com/attachments/462682926107197450/494243960068374541/image0.jpg

Without the link of the image, I was able to see the preview, so my guess is it's because the image is big

**Comment by nanaya** [comment]
Not sure what exactly "preview doesn't show" mean here but typing that and clicking preview works on current site so I guess it's fixed now.
