### ISSUE TITLE
Users should not be allowed to reply to deleted comments

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#3713]
![screen shot 2018-09-26 at 9 01 00 pm](https://user-images.githubusercontent.com/30382015/46081536-4da74900-c1cf-11e8-8022-65a055d10302.png)

https://osu.ppy.sh/home/news/2018-09-24-bn-applications-autumn-cycle-2018

deleted comments shouldn't show up at all tbh

**Comment by nanaya** [comment]
Hiding deleted comment will either hide all the replies or disable deleting comment with replies.
