### ISSUE TITLE
Unable to log in and log out

### ISSUE THREAD

**Issue by SpartanPlume** [ppy/osu-web#3715]
When I try to log in on the website (osu.ppy.sh), it either loads for an eternity or shows an error `An unexpected error occured` (or something similar since it was written in French). When I try to log out, it loads for an eternity too.

However, I was able to log in and log out on the old website (old.ppy.sh).

I tried with Firefox and Google Chrome, same problem with both.

**Comment by notbakaneko** [comment]
There was an issue with a previous deploy; this should be resolved now
