### ISSUE TITLE
All old website map pages views are broken

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#3716]
![image](https://user-images.githubusercontent.com/33286824/46160416-ad920400-c250-11e8-8d08-8ade762d7cf3.png)

![image](https://user-images.githubusercontent.com/33286824/46160658-5a6c8100-c251-11e8-9512-34c527a3a4b9.png)

![image](https://user-images.githubusercontent.com/33286824/46160442-bd114d00-c250-11e8-92b0-ec68409f5670.png)
While the old website is nearing the end of its life, having such terribly broken web pages just looks.. uhm, bad for the game, imo

idk where else to report this, i know this github mostly for the new website but uhm.. yeah

**Comment by peppy** [comment]
Thanks for the report. Will look into this one.

**Comment by celerih** [comment]
Additionally, [profile][/profile] links are all broken, showing /u/username instead of linking anything and beatmap descriptions using them seem to have disappeared on old site https://old.ppy.sh/s/789095

**Comment by peppy** [comment]
Thanks for the additional report. Both should now be fixed.

**Comment by celerih** [comment]
There's still a few extra things, userpages are no longer showing on old site, and [size][/size] doesn't change anything.

**Comment by peppy** [comment]
These two issues should also be resolved.
