### ISSUE TITLE
The news page could look nicer with banners

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#3719]
https://osu.ppy.sh/home/news
The current page for news is pretty simple with just text

Making it look more like the [contests page](https://osu.ppy.sh/community/contests) by adding banners, a tag, and loading more articles per page would look a bit nicer

**Comment by arflyte** [comment]
Already working rough draft on it, but I haven't had the time to finish it yet. It's far from completion.

![photoshop_180928-155127](https://user-images.githubusercontent.com/3632750/46192560-7a29a500-c336-11e8-8ebf-7a76ecf81609.png)
![photoshop_180928-155145](https://user-images.githubusercontent.com/3632750/46192562-7bf36880-c336-11e8-9671-470c2edf7b92.png)
![photoshop_180928-155145](https://user-images.githubusercontent.com/3632750/46192691-e2788680-c336-11e8-9872-58f90e712ba3.png)

**Comment by TPGPL** [comment]
Is there a reason news are located in the community/player category?

**Comment by TPGPL** [comment]
should be closed

**Comment by Xinnoh** [comment]
ok
