### ISSUE TITLE
Reprocessing of thumbnails of older maps or manual editing/reprocessing of thumbnails/headers on old submitted maps

### ISSUE THREAD

**Issue by Smowokeman** [ppy/osu-web#3730]
Going through my catalog of maps i have a lot of older (and some newer ones in the last year) which dont have a thumbnail or header (all of them were uploaded with a background).
I have had a couple of people who were wondering if i deleted the BG of my now 2+year old maps without uploading only to have to tell them that that is not the case. 
I am not the only one affected by this as a lot of older classic maps suffer from the same thumbnailless fate or different visual bugs which make their header glitch-y

In particular this one https://osu.ppy.sh/beatmapsets/656040#osu/1390114 doesnt have a thumbnail but shows a header, which is especially wierd https://puu.sh/BCthM/53604e92d4.png. 

even if i wanted to revive and resubmit them so a thumbnail/header is reprocessed i would need to do that 22+ times myself, for which i dont have the slots for as i am actively mapping (And i wouldnt like reviving the dead for this). 
On the old site all of these maps show an image so this must be a problem on the new site. 

My profile for reference https://osu.ppy.sh/users/2140676everything including https://puu.sh/BCtlB/9c6ea6ef9d.png and further below.

**Comment by peppy** [comment]
@nekodex let's look at getting a process in place to verify all existing beatmap assets and doing a reprocess via an artisan command or similar.

**Comment by nekodex** [comment]
I ran a reprocess of these last week, they should be fine now.

If anyone notices any more beatmap image issues, please report them in issue #3729.
