### ISSUE TITLE
Links in pms + forum posts are not automatically becoming clickable

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#3737]
old-web issue again

![image](https://user-images.githubusercontent.com/33286824/46270522-df87bc80-c515-11e8-83b6-a864cbaaec9c.png)

when posting messages in private messages or on the forums, links will not automatically become clickable urls. Posting to the forums using the new website is working fine, and if you edit a post made on the old forum using the new forum the link will fix itself to be clickable as it should. This is mainly an issue for the PM system since that's old web only still.

**Comment by peppy** [comment]
Tested and confirmed this has since been fixed.
