### ISSUE TITLE
You can write comments on unranked beatmaps

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3761]
https://osu.ppy.sh/beatmapsets/682356#taiko/1793145

when we had the other system it wasn't like that. also when in unranked state, people mostly said something via hype/praise in mv2

is it intention now?

**Comment by cl8n** [comment]
yep, it's a recent change https://github.com/ppy/osu-web/pull/3756

**Comment by Lyawi** [comment]
hmm... it's already hard to get hypes imo, this will make it even harder.

well
