### ISSUE TITLE
Years should not round up at 0.5

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#3762]
https://osu.ppy.sh/beatmapsets/584128
This was updated 1 year and 7 months ago, it shows as graved two years ago on my profile as it rounds up at 0.5
Rounding up years should not be a thing

![screen shot 2018-10-07 at 4 48 51 pm](https://user-images.githubusercontent.com/30382015/46580101-e3a16600-ca50-11e8-9e28-5c8e5e55a62a.png)

**Comment by peppy** [comment]
Yeah, the rounding of timeago functions seem very weird at the moment.

**Comment by nanaya** [comment]
From what I can tell the library only supports showing single unit number.

**Comment by cl8n** [comment]
maybe just floor years then? I feel like that's what OP wanted instead

**Comment by LiquidPL** [comment]
Well then it goes completely in a different way, it'd look weird if you had a 1y11m map displayed as "1 year ago".

**Comment by notbakaneko** [comment]
What we want is probably something along the lines of https://date-fns.org/docs/distanceInWords
 which appears to be the only javascript library that actually supports this properly with i18n?

Neither moment not timeago support approximate distance, and none of their plugins that do seem to do localization properly.
