### ISSUE TITLE
User's age missing on profile

### ISSUE THREAD

**Issue by IceDynamix** [ppy/osu-web#3764]
A feature that's missing on the new page is the current age. Whenever you want to check someone's age on the profile (given that they choose to show it) one has to switch to the old page to do so.

**Comment by IceDynamix** [comment]
Ignore this if you want to stick to https://github.com/ppy/osu-web/issues/3312

**Comment by LiquidPL** [comment]
This is intentional.

#3432

**Comment by IceDynamix** [comment]
Alright then. Consider this as closed.
