### ISSUE TITLE
Add message above comment system on unranked beatmaps (about hypes)

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3766]
here i am again to bother with this topic

![unknown](https://user-images.githubusercontent.com/32525896/46622993-837ff200-cb2c-11e8-9888-a37e39d3fab5.png)

**Comment by peppy** [comment]
@arflyte can you come up with ah design for this on the new beatmap info page design? something which reads along the lines of "hype this map if you enjoyed playing it to help it progress to ranked status!"

**Comment by arflyte** [comment]
![photoshop_181009-144211](https://user-images.githubusercontent.com/3632750/46648804-9a2c5480-cbd1-11e8-9793-80f2d7d8d0f4.png)

Added hype area before Ranking.
