### ISSUE TITLE
Display star rating in Feature Request forum listing

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#3768]

**Comment by dorothy3242** [comment]
Duplicate of https://github.com/ppy/osu-web/issues/1173

**Comment by TPGPL** [comment]
i think voting on feature request is something *different* than displaying the stat on forum listing

**Comment by dorothy3242** [comment]
yes, except it explicitly is mentioned in the opener "display current star priority at a minimum"...

**Comment by peppy** [comment]
Closing as duplicate of #1173.
