### ISSUE TITLE
Improve Featured Artist beatmap visibility

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#3777]
Beatmapsets that use Featured Artist works should by their very nature, be of greater visibility to the general user than ordinary tracks. They're licensed content.

At the moment, there are no obvious markers that denote a track as inherently belonging to a Featured Artist game wise - they appear on both the website and the client as indistinguishable from normal beatmaps outside of perhaps the inclusion of 'featured artist' in their tags.

To fix this, I suggest:

- Add a new field to beatmapsets that allows them to be linked to an artist id.
- Create a design addition for Featured Artist listings that allows them to display ranked beatmaps linked to their artist's id.
- Add an element to the beatmapset listing page that clearly denotes a linked set as belonging to a particular Featured Artist's body of works, complete with a linkback to their FA listing
- Add a category to beatmap search that purely returns linked Featured Artist beatmaps - possibly with a special border or other visual marker to make them 'stand out' from ordinary content
- Consider exposing a feed of newly linked Featured Artist beatmaps for possible inclusion in stable/lazer as a 'feed' of licensed content

**Comment by ShiiTsuin** [comment]
Wasn't sure whether to make a new Issue/Proposal but I wanted to add another suggestion for improving FA beatmap visibility;

- Add a 'New Ranked Featured Artist Beatmaps' (or similarly named) section on the home page to go alongside 'New Ranked Beatmaps' and 'Popular Beatmaps' (or maybe replace the latter?).
