### ISSUE TITLE
Tie tournament-related store purchases into supplied dates

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#3778]
So as to avoid situations where some idiot forgets to turn off profile banner purchases once a tournament has actually finished, a custom field should be added to the store db that prevents items from appearing for sale outside of a given date range.

This date range could be pulled from a linked tournament_id table, though an additional field for "final week" will likely need to be added to the tournaments table to support this particular use case.

**Comment by LiquidPL** [comment]
What do you mean exactly by the 'final week' field? Doesn't banner sale end exactly on tournament end usually?

**Comment by Ephemeralis** [comment]
it doesn't, no. the purchases are turned off before the grand final matches conclude, though we may stop doing that going forward, not sure if we ever came to a decision on that
