### ISSUE TITLE
Profile section changes should add #anchor to URL

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#378]
For instance, clicking on the "Medals" section should generate a URL like `http://new.ppy.sh/u/2#medals` which can be linked to other users (or bookmarked).

**[Bounty](https://goo.gl/nFdoyI) offered**: 40

As always, ask if you have any questions, and feel free to jump on the [osu!dev slack](http://osu.ppy.sh/p/slack) for more real-time discussion.

**Comment by LiquidPL** [comment]
should this also happen when user scrolls to the section on his own?

**Comment by peppy** [comment]
hmm, i don't think it needs to. anyone else have opinions on this?

**Comment by Bobo1239** [comment]
Imo, it should only happen when clicking on the section button.

**Comment by CMS-Falcon** [comment]
Should have this done very soon.

**Comment by shavitush** [comment]
Does it need to be dynamic or static and just for the current available sections?

**Comment by peppy** [comment]
Completed by @nanaya. @CMS-Falcon check out the solution for the kind of implementation we were looking for. Notice how it is not duplicating any logic which will cause headaches down the road when we add/reorders/remove sections.
