### ISSUE TITLE
Docker - connection timeout while building yarn

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#3788]
Happened to me at least three times in a row

**update 1:** seems that Google Public DNS is failing for some reason while Cloudflare DNS is working fine

**Comment by nanaya** [comment]
Need the error log.

**Comment by TPGPL** [comment]
what happens when i build the containers for the first time even after resetting the docker to defaults

![](https://puu.sh/BJscT/88d72f3f8f.png)

after gracefully stopping docker, a new folder is made in the osu-web repo 

![](https://puu.sh/BJsfU/bf8f010065.png)

logs: https://pastebin.com/7KF8975f

**Comment by nanaya** [comment]
That looks like network problem.

**Comment by TPGPL** [comment]
No idea the network works normally

**Comment by nanaya** [comment]
Have you tried again? Is it producing same error?

**Comment by TPGPL** [comment]
Im gonna try today again, but i dont think it will work

**Comment by TPGPL** [comment]
still erroring on latest master branch, logs: https://pastebin.com/5EUq8R8U

**Comment by nanaya** [comment]
can you download the file in your browser? https://registry.yarnpkg.com/lodash/-/lodash-4.17.4.tgz

**Comment by TPGPL** [comment]
not a problem at all

![image](https://user-images.githubusercontent.com/19843905/46959909-7cf9f900-d09d-11e8-8743-5048acd30f0f.png)

**Comment by sr229** [comment]
@TPGPL you either encountered two cases:

- Your connection is unstable
- yarnpkg might be experiencing high load during when it happened.


These are all edge cases but retrying should work IMO

**Comment by TPGPL** [comment]
@sr229 pretty sure my connection is stable as i started docker two times while watching some streams on Twitch and there were no lags nor buffering in the meanwhile

**Comment by sr229** [comment]
Weird. I'm getting successful transactions in my end. Probably edge-case

**Comment by sr229** [comment]
Issue now logged at yarnpkg. Recommend you coordinate over there.

**Comment by sr229** [comment]
Triage update: Seems even switching Resolvers does not rectify the issue.

**Comment by sr229** [comment]
Triage update: Timeouts still happen but the install proceeds properly now.

**Comment by sr229** [comment]
Triage complete: Triaged it to Google Public DNS failing to resolve yarnpkg properly - which causes @TPGPL 's builds to fail. Recommending this to be closed.
