### ISSUE TITLE
Anchor links to featured artist listings don't work with turbolinks

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#3795]
Clicking a link to, for example, https://osu.ppy.sh/beatmaps/artists/12#album-54 will not correctly arrive at the anchor point (but instead some random offset). This only happens when arriving from another page (a news article in this case) and is likely an issue with turbolinks/react.

**Comment by nanaya** [comment]
Most likely caused by browser went to the anchor location first, then followed by react mounting the components, pushing the view down.

**Comment by notbakaneko** [comment]
seems to be working now
