### ISSUE TITLE
new threads without comments have Re:

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3813]
![unknown](https://user-images.githubusercontent.com/32525896/47069232-aecea500-d1ee-11e8-9909-5aa9da88af95.png)

https://osu.ppy.sh/community/forums/topics/817537?start=unread
I made a comment, which means **now** the Re: is okay, but before it wasn't

By the way, I think my issue #3605 could be related to this...?

**Comment by nanaya** [comment]
Yeah it's same problem.
