### ISSUE TITLE
Consider raising the filesize limit for art contest entries

### ISSUE THREAD

**Issue by LiquidPL** [ppy/osu-web#3816]
Currently it is at 4MB, which I believe might be not enough for lossless PNGs (especially at the suggested 2732x1536 resolution).

**Comment by peppy** [comment]
Post-contest we shrink all images to 1mb anyway. If you're able to learn image compression and tailor your image to be of that size, it would save us a portion of effort. If not, at very least learn how to use web export (you're likely saving colour profiles or extra metadata if your image is that large).

Lossless PNGs are not required.
