### ISSUE TITLE
Bounty: General enquiries, feedback and questions

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#382]
There are still hundreds of pages and features remaining to be implemented in this new system. Do you have something in particular that interests you? Do you have a new idea which you'd like to help us make official, rather than an external site?

Reply in here with any questions, feedback or requests regarding bounty. We may be able to provide completed mock-up designs and specifications for implementation, as well as give you a rough idea of how much bounty completing a task would be worth.

I really want to get as many hands on this project as possible, so any feedback is much appreciated.

Useful links:
- [Bounty system](https://goo.gl/nFdoyI) general information and running totals.
- [Open issues](https://github.com/ppy/osu-web/issues?q=is%3Aissue+is%3Aopen+label%3Abounty) with bounty.
- [osu!dev public slack](http://osu.ppy.sh/p/slack) for more real-time discussion.

**Comment by LiquidPL** [comment]
After looking at #251, I think I might attempt doing the beatmap details, or the signup process+user preferences.

Actually, why not both?

**Comment by peppy** [comment]
We actually want to get the new modding system complete ASAP. Are you interested in looking at that instead as a priority? Else I'll outline the sections you just mentioned as bounties.

**Comment by LiquidPL** [comment]
can do

**Comment by Nicarim** [comment]
https://github.com/ppy/osu-web/pull/326 how about this?

**Comment by LiquidPL** [comment]
@peppy now that I'm (mostly) done with the slack page, could you give me a quick rundown on the modding system?

**Comment by Nugamus420** [comment]
I really want a key press counter for osu!mania as it was not the original osu!

It should not be to hard to get in but i'll help if it's to hard :)
