### ISSUE TITLE
Ability to only see voted entries in contests

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#3820]
There might be a ton of votes and entries (like right now), and I can accidentally vote one and not know it. Also I have to go through all the entries to see what I voted which is hard.
![votes_section](https://user-images.githubusercontent.com/35318437/47185846-87a5cf80-d2e3-11e8-8130-3ecbac038b8e.png)
^ maybe pressing this will show the voted entries.

**Comment by Lyawi** [comment]
or hovering about one vote will show up as tooltip (if its called like that?) above or below, and when clicking on it it scrolls to the actual picture with some highlight around it

(if its worth it)

**Comment by Joehuu** [comment]
Gonna supersede this with https://github.com/ppy/osu-web/issues/7099, as it gained more traction right after it was posted.
