### ISSUE TITLE
Redirect country urls

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3823]
https://osu.ppy.sh/community/forums/topics/818500?start=unread

**Comment by peppy** [comment]
Could you please explain in detail where you expect this to be added, possibly with screenshots. A forum thread link alone is not a valid github issue on its own.

**Comment by Lyawi** [comment]
In country ranking on old site we got countries up to 237 (https://osu.ppy.sh/p/countryranking?p=countryranking&s=3&o=1&page=5). 
New site only has 150 and +2 another "weird" countries, which aren't listed on old site. (https://osu.ppy.sh/rankings/osu/country?page=3#scores and page 4)

Now someone made a thread about this and pretty much said they haven't got a listing for their country on the new site, because it seems to be missing. When it's missing, it redirects to https://osu.ppy.sh/rankings/osu/performance automatically.

**Comment by nanaya** [comment]
This has been fixed (also the title is quite confusing).
