### ISSUE TITLE
[spoiler] doesn't work on old web

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#3828]
![image](https://user-images.githubusercontent.com/33286824/47272905-2b98b080-d55a-11e8-9581-14fbbda42791.png)

it just displays like there is no [spoiler]

**Comment by Celektus** [comment]
Does the old site still matter?

**Comment by dorothy3242** [comment]
so long as it still exists i'd say yes

**Comment by Joehuu** [comment]
Can be closed as the old site does not pertain here.

**Comment by peppy** [comment]
Does not matter. Use the new site if it affects you.
