### ISSUE TITLE
Open timestamp result in "invalid format"

### ISSUE THREAD

**Issue by Kagu-chan** [ppy/osu-web#3837]
When clicking on a timestamp in a modding `osu://edit/00:42:553 (42553|1)` i get the message "invalid format"

What would be the right format? Or is this a issue in the client?

`osu://edit/00:20:184 (20184|2,20805|1)`

**Comment by nanaya** [comment]
Probably same as #3191.

**Comment by peppy** [comment]
@Kagu-chan Could you provide a link to a beatmap where this occurs (if you can still remember where)?

**Comment by peppy** [comment]
Fixed in latest CE.
