### ISSUE TITLE
Dragging links into client isn't working on new website as it does on old

### ISSUE THREAD

**Issue by DMills94** [ppy/osu-web#3844]
Old Website: 
![2018-10-31_12-53-30](https://user-images.githubusercontent.com/31848108/47789558-c0469f80-dd0c-11e8-8de8-a6637b8db430.gif)

New Website:
![2018-10-31_12-52-36](https://user-images.githubusercontent.com/31848108/47789620-ef5d1100-dd0c-11e8-9c76-b42119fb40eb.gif)

Preferred action: Dragging beatmap/beatmap set links into the game downloads/goes to the map

**Comment by DMills94** [comment]
I expect this is actually a client thing, and likely to be fixed in Lazer?

**Comment by peppy** [comment]
Fixed in cutting edge.

**Comment by omkelderman** [comment]
small nitpick:
* https://osu.ppy.sh/beatmapsets/320118#osu/714001 goes to the right diff
* https://osu.ppy.sh/beatmapsets/320118/#osu/714001 does not (it behaves as if the link was https://osu.ppy.sh/beatmapsets/320118)

same for clicking links in ingame chat btw

**Comment by peppy** [comment]
What is generating the second link?

**Comment by omkelderman** [comment]
redirect after going to /b/<number>

**Comment by peppy** [comment]
The nitpick should be fixed now (fixed discrepancy in URLs).
