### ISSUE TITLE
Slight extra margin on contracted tab bar

### ISSUE THREAD

**Issue by pine5508** [ppy/osu-web#3845]
The newly updated 'smaller' tab bar have slight issue.

![image](https://user-images.githubusercontent.com/33368542/47825791-5e0c8f80-dd4a-11e8-8431-902d9b947ff3.png)

![image](https://user-images.githubusercontent.com/33368542/47825802-6c5aab80-dd4a-11e8-8425-8d742499fffb.png)

As you can see, there are some mysterious white lines and margins.
It's not a huge problem, but it hurts osu webpage's perfect design 😢

**Comment by notbakaneko** [comment]
are you zoomed in?

**Comment by pine5508** [comment]
Nope, it's a FHD monitor scaled 125% (on Windows global setting).
