### ISSUE TITLE
[docker] php exits with code 1

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#3851]
logs: https://pastebin.com/ScnJ2nfX

`standard_init_linux.go:190: exec user process caused "no such file or directory"` seems to make trouble, but changing line-ending auto conversion for git didnt solve the problem

**Comment by sr229** [comment]
Which container process is this erroring out? I think this might be the  FPM container.

**Comment by TPGPL** [comment]
Its erroring from php_1 container

**Comment by sr229** [comment]
Diagnosed from incorrect Line Endings during checkout. PR #3856 will now solve this.

**Comment by TPGPL** [comment]
Although the line ending problem is solved, php still doesn't want to cooperate and stops working while building osu-web, mostly because of MySQL

logs: https://pastebin.com/wewAi8yh

**Comment by TPGPL** [comment]
For some reason on second build after resetting the database, and after an hour of waiting php migrated successfully and it started working
