### ISSUE TITLE
Add API scopes

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#3857]
at the very least I think it'd make sense to have:
- reading private data (e.g. friends list)
- writing data (e.g. sending chat messages)
- identifying (only `/api/v2/me`)

just so that I don't have to let the user blindly trust that my app doesn't do something it shouldn't (though fwiw, I think a more extensive set of scopes would be a lot better)

I can look into adding this myself if it's not a dev priority, but I figure someone else should decide which scopes exist

**Comment by peppy** [comment]
This is definitely required, especially as users are beginning to use oauth as a means of identifying users.

**Comment by peppy** [comment]
@cl8n if you’re able to look at this that would be great. looks like we likely won’t fit it in until next week at best.

**Comment by notbakaneko** [comment]
We have support for adding scopes now, new additional scopes should have new issues opened instead of this one.
