### ISSUE TITLE
Some users score gets nullified therefore illegible to enter into Spotlights ranking

### ISSUE THREAD

**Issue by Shadowthegod** [ppy/osu-web#3869]
Some user, no matter how many maps they played from the Spotlighted maps, reported that they can't enter into the Spotlights ranking due to their scores are being reset to zero. 

Kronos: [1](https://i.imgur.com/9AT2QW1.jpg) and [2](https://i.imgur.com/wt42nan.jpg)
and one other user
EthanTC: [First play](https://osu.ppy.sh/ss/12088544) and [second play](https://osu.ppy.sh/ss/12088556)

I asked them to try different computer and different network but they had the same issue, so I guess it is something account related.

**Comment by peppy** [comment]
Please have these uses to contact me via email. I'll look into it for them (pe@ppy.sh).

**Comment by didcreetsadgoku500** [comment]
I emailed you on November 14, but received no confirmation of the email going through. Email used was didcreetsadgoku500@gmail.com

**Comment by peppy** [comment]
yep, it’s on my todo list
