### ISSUE TITLE
Testing improvements

### ISSUE THREAD

**Issue by LiquidPL** [ppy/osu-web#388]
Right now, all we test is PHP. I think that we should add support for testing the JavaScript, notably the React components.

I wanted to start some discussion on choice of the framework. After some searching, I found those:
- [Karma](http://karma-runner.github.io), which is only a test runner by itself, and can run in tandem with [Mocha](http://mochajs.org/) or [Jasmine](http://jasmine.github.io/) (and many others i guess),
- [Jest](http://facebook.github.io/jest/), made by the React guys, and also runs on top of Jasmine.

What are your thoughts? Maybe we should use something else?

On a side note, we also should start tracking test coverage.

**Comment by notbakaneko** [comment]
We definitely need more js-side testing and it really needs to be separable into logic-only (no view output) parts.

**Comment by notbakaneko** [comment]
Bumping this up the priority list as refactoring and reviewing client-side changes without any repeatable logic tests is kind of irritating and time consuming.

**Comment by notbakaneko** [comment]
using karma+jasmine going forward #4556
