### ISSUE TITLE
"Unauthorized" page returns HTTP/1.1 200

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#3884]
should be 401

looks like it happens here https://github.com/ppy/osu-web/blob/ef8964813fa1d30e97cde9f0e7e117649b5cd9f4/app/Exceptions/Handler.php#L121-L128

**Comment by nanaya** [comment]
Because 401 will cause browser to show their generic login modal box.

**Comment by cl8n** [comment]
welp, TIL
