### ISSUE TITLE
Chat messages disappear after a week

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#3885]
pishi sent me a message testing the system on the 8th, it was there until yesterday when it disappeared
that or something else deleted it, which also shouldn't happen for private messaging

![screen shot 2018-11-15 at 12 07 30 pm](https://user-images.githubusercontent.com/30382015/48529671-10a62b80-e8cf-11e8-9a2d-fa79b659f491.png)

**Comment by peppy** [comment]
This has been fixed. They will now remain for one month. Going forward we will likely extend this as we update the underlying infrastructure.
