### ISSUE TITLE
OAuth authorization page should show who you're logged in as

### ISSUE THREAD

**Issue by notbakaneko** [ppy/osu-web#3889]

**Comment by arflyte** [comment]
need design specs lol.

**Comment by peppy** [comment]
![image](https://user-images.githubusercontent.com/191335/52385311-4caeee00-2ac4-11e9-813e-2a8f67395d30.png)

This is what it currently looks like

**Comment by arflyte** [comment]
Where is this displayed?

**Comment by arflyte** [comment]
![oauth](https://user-images.githubusercontent.com/3632750/52612906-06e09400-2ecf-11e9-9233-7e39c55d54b0.jpg)


https://www.figma.com/file/WcImnI0fAf0lPxyBEKMQxgl7/Web-OAuth-Authorisation-Page?node-id=0%3A1

**Comment by TPGPL** [comment]
should be closed?

**Comment by peppy** [comment]
I believe this implementation is completed, yes.
