### ISSUE TITLE
Can't create new forum topics as non-admin user

### ISSUE THREAD

**Issue by Hughp135** [ppy/osu-web#389]
EDIT: 
I think it's trying to load some forum permissions from the DB but this hasn't been set, so the check fails if you are not an admin. Is there a special field somewhere in the database for forum-specific permissions?

#Forum/Authorize.php
<img width="973" alt="screen shot 2016-02-22 at 17 09 23" src="https://cloud.githubusercontent.com/assets/12624925/13225941/1a18be9e-d987-11e5-9337-e41a3464b230.png">

**Comment by nanaya** [comment]
I don't even know how it calls the `Controller->canPost(Forum, '94')` because the code (`TopicsController.php:59`) says `$this->canPost($forum, null)`. Did you modify the code or something?

**Comment by Hughp135** [comment]
Yeah, I did actually change it to test if it would fix it, and forgot to change it back before posting the error.

It however still gives this error when not an admin:

<img width="1069" alt="screen shot 2016-02-22 at 16 58 46" src="https://cloud.githubusercontent.com/assets/12624925/13225663/b034ef30-d985-11e5-9332-afbcc7ab8f5d.png">
