### ISSUE TITLE
Whitespace on short wiki pages

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#3891]
Current: https://osu.ppy.sh/help/wiki/Twitter

Before the pinned header (which I think is the problem): https://web.archive.org/web/20181029192604/https://osu.ppy.sh/help/wiki/Twitter

![](https://puu.sh/C2ALR/37be660c85.gif)

**Comment by nanaya** [comment]
`wiki-toc`'s `height` probably should be `max-height` instead.
