### ISSUE TITLE
Viewing new forum topics gives an error

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#3893]
I'm not sure what the correlation is but it seems to happen only on posts newer than ~an hour ago? (as of the time of making this issue)

Example: https://osu.ppy.sh/community/forums/topics/831279

**Comment by peppy** [comment]
Seems to be working here now. Plesse confirm it’s still broken.

**Comment by cl8n** [comment]
works on my end now, too. this was one of the codes from when it failed earlier `439dd72ed37e4b6a968406c185f8fd9b`

**Comment by peppy** [comment]
Thanks, we’ll invetigate
