### ISSUE TITLE
Quick Question

### ISSUE THREAD

**Issue by MasterBugPatch** [ppy/osu-web#39]
How would I go about making a user supporter from the Vagarant SSH?

**Comment by peppy** [comment]
set `osu_subscriber = 1` for your user in phpbb_users

**Comment by MasterBugPatch** [comment]
Hm, would I do that directly from the hhvm artisan just using normal Select Table etc etc?

**Comment by peppy** [comment]
if you want to use artisan tinker:

```
$me = App\Models\User::where("username", "yourusername")->first();
$me->osu_subscriber = true;
$me->save();
```

**Comment by MasterBugPatch** [comment]
Gracias ^.^

**Comment by Tewki** [comment]
Or if you wanna go via sql,
`mysql -u osuweb osu`
`update phpbb_users set osu_subscriber = 1 where username = 'yourusername';
`

**Comment by MasterBugPatch** [comment]
That ones great too, thanks. @Tewki
