### ISSUE TITLE
Use "top" comment sorting as default

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#3905]

**Comment by peppy** [comment]
Are you sure this is what we want? Recent is also a potential best choice here, which is why it was left as recent for now.

**Comment by VINXIS** [comment]
I think top would be much better considering most people want to see what's the most upvoted usually instead, as well as the fact that disqus also did it before and that was really nice

**Comment by Ephemeralis** [comment]
While questionable in terms of actual viewing merit, most upvoted view by default is sort of expected behavior for any kind of comment system these days.

**Comment by peppy** [comment]
Does expected make it correct? I don’t like to blindly follow suit. FOr things like beatmaps, it will cause 100% memes to raise to the top – is this what we want?

**Comment by Kagetsu24** [comment]
fwiw,  i think that as far as beatmaps are concerned, the comment section has always been something informal and aimed towards a more casual audience. if you were looking for non-meme comments/serious stuff,  you'd probably be better off reading the beatmap discussion rather than comments.

**Comment by VINXIS** [comment]
ohh Ya thats a good idea actually

**Comment by VINXIS** [comment]
is this still planned to happen

**Comment by cl8n** [comment]
probably as part of #4434
