### ISSUE TITLE
Disable textbox instead of not sending messages while muted

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#3913]
![image](https://user-images.githubusercontent.com/19843905/48916642-5f316800-ee83-11e8-9887-3258cf49a53e.png)
![image](https://user-images.githubusercontent.com/19843905/48916652-65bfdf80-ee83-11e8-847a-1936c454ceb0.png)

**Comment by nanaya** [comment]
Pretty sure this has been implemented a while back.
