### ISSUE TITLE
Add russian language to beatmaps categories

### ISSUE THREAD

**Issue by Shmiklak** [ppy/osu-web#3915]
The number of maps with Russian lyrics increases everyday, it's already more than 80 maps in the ranked and qualified sections, while they don't have any specific group. French songs have a group though their amount is much lower what is weird. It was also mentioned in the "Feature request" thread https://osu.ppy.sh/community/forums/topics/762484?start=6881183

**Comment by Lyawi** [comment]
#3376

**Comment by TPGPL** [comment]
should be closed as duplicate
