### ISSUE TITLE
Comment entry area is confusing

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#3916]
![img_0033](https://user-images.githubusercontent.com/191335/48926628-1fb25c80-ef13-11e8-888e-551ad29f714c.jpeg)

Every time I go to make a comment, I click on this text rather than the larger one. It feels like the natural plce to click due to the colours of the text,

**Comment by arflyte** [comment]
will update the comment box's design to make it a lot more obvious.

**Comment by arflyte** [comment]
![photoshop_181228-124102](https://user-images.githubusercontent.com/3632750/50501752-e767e600-0a9d-11e9-9dea-6ceaa082b709.png)

Should be more obvious now

**Comment by peppy** [comment]
Let's get this in asap

**Comment by nanaya** [comment]
doesn't quite work for editing/replying comment.

![](https://s.myconan.net/2019-01/firefox_2019-01-15_20-09-32.png)
