### ISSUE TITLE
Update insecure node dependencies

### ISSUE THREAD

**Issue by loverthehater** [ppy/osu-web#3929]
A couple of dependencies you have leave the chance for [XSS](https://www.npmjs.com/advisories/328), [regex DoS](https://www.npmjs.com/advisories/532), and [prototype pollution](https://www.npmjs.com/advisories/577) attacks. Am I missing something or is an update in order?

(Found vulnerabilities via [this thing](https://david-dm.org/ppy/osu-web))

**Comment by notbakaneko** [comment]
None of these seem applicable to our usage of the libraries;
- we don't use lodash serverside
- moment is not used to parse user-provided strings
- there's a jquery prefilter applied on cross-domain requests similar to patched versions of jquery
