### ISSUE TITLE
Add ability to lock beatmap comments

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#3935]
as in, the comments on the info page, **not** the modding discussion page
because sometimes they can become terribly in need of a lock just like forum threads, seems like a basic need for moderating

**Comment by peppy** [comment]
Do you have an example of a case where this would be required? We tend to avoid this kind of locking if opssible.

**Comment by MillhioreF** [comment]
Bumping because we have [a heavily politically charged comments section now](https://osu.ppy.sh/beatmapsets/1044124) which is equally bad either to moderate or to not moderate and is just going to breed hostility by allowing further comments.

**Comment by peppy** [comment]
locking should not be used in such cases. disruptive users should be restricted or silenced. comments should not be locked.

closing as not-requried.

**Comment by Pachiru** [comment]
That's what we did on a guy once for a similar reason, and we got harshly blamed on Reddit

**Comment by WalterToro** [comment]
> disruptive users should be restricted or silenced

Sorry to say, this issue started because one user was restricted so it doesnt help at all doing it, just contributes adding more fuel to the fire, beatmap (and probably all types of) comments pages being locked helps to moderate those without constantly removing new inflamatory posts.

**Comment by peppy** [comment]
the posts should not have been removed in the first place, in the above case. they have all been restored.
