### ISSUE TITLE
Docker deploy has undefined Lang

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-web#3939]
Getting `ReferenceError: Lang is not defined[Learn More]` in a docker deploy, causing some pages (user profiles, beatmap listing) to not load.

**Comment by nanaya** [comment]
The `yarn` instance needs to wait until `php` instance generates the language js file. I suspect it's easier to change the structure so one is php-fpm and the other is dependency installer (php, js) + assets builder.

**Comment by nanaya** [comment]
Superseded by #4297 as there's more change recently to language assets generation.
