### ISSUE TITLE
User page has no character limit

### ISSUE THREAD

**Issue by Nath789** [ppy/osu-web#3943]
Just as the title says, editing user pages have no character limit.
I tried saving my user page with over 250,000 characters, an error occured but still the contents are saved. After that, my profile is totally inaccessible, just a blank page appears either in old and new. The only way to remove it is by using the moderation tools.

Adding a character limit (e.g. 60,000 like in the old site) will avoid this issue.

**Comment by abraker95** [comment]
What please no. I won't be able to post my scores stats in my profile: https://osu.ppy.sh/users/4635891

I keep track of all my scores on there so that my friends know what they need to beat me.

**Comment by omkelderman** [comment]
I guess some character limit is fair, you dont wanna be able to base64 your entire movie collection and paste it in there as "backup" :wink: 

Now depending on how this is going, if a somewhat insanely large character limit is implemented, I guess some kind of lazy loading system could be a thing where not everything of the user page is loaded until you scroll down.

Just a random thought tho, personally I don't really care and I doubt I'll ever go over that 60k limit

**Comment by abraker95** [comment]
![image](https://user-images.githubusercontent.com/4358724/49680357-95650f00-fa61-11e8-93a6-45642ddceafd.png)

I cry
