### ISSUE TITLE
Header fading out

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#3951]
or more of the line i am pointing on here (idk how to call it):
![1w6ucjz](https://user-images.githubusercontent.com/32525896/49639949-8a33c400-fa0c-11e8-8183-2b400499172c.png)

would look better imo! especially because like everything header-related is fading out too

**Comment by GSculerlor** [comment]
Related to #3877, I guess

**Comment by nanaya** [comment]
No change for now.
