### ISSUE TITLE
Emphasis group colour on user profile

### ISSUE THREAD

**Issue by VenixOSU** [ppy/osu-web#3953]
Just a suggestion but coloured usergroups like GMT, QAT or BNG with just a white title on the new version of user profile look quite empty imo. I think it would look better with group colour emphasized some way.
![](https://venix.s-ul.eu/us2OvfB6)
![](https://venix.s-ul.eu/h8cXJd9n)

**Comment by cl8n** [comment]
as mentioned in Discord, this is important because some users don't have the title of their primary group (ex. Ascendance uses "Elite Mapper" instead of "Beatmap Nominator")
