### ISSUE TITLE
Ranking graph in new profile page doesn't show last 90 days

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu-web#3954]
![wat](https://user-images.githubusercontent.com/27222621/49641501-9752b200-fa10-11e8-87a7-85e9a9beece6.png)

Shouldn't this show the last 3 months (aka 90 days?). It was 90 on the old page, then 89 on the new page (previous design) and now it's 88. Somehow each revision loses a day.

~~Also is the right anchored tooltip intended?~~

**Comment by peppy** [comment]
We can only show 89 at most, I believe. The tooltip may just be incorrect.

**Comment by nanaya** [comment]
"now" is the 1st day so 88 days ago is the 89th day.

**Comment by Aergwyn** [comment]
True, with "now" it adds up to 90.
Would it be possible to extend the previous data by the amount below 90?

**Comment by peppy** [comment]
This should be resolved.
