### ISSUE TITLE
Grade icons in Recent section are barely discernible

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu-web#3956]
![wat](https://user-images.githubusercontent.com/27222621/49642321-ffa29300-fa12-11e8-9f01-08e6c13fd4e3.png)

You can guess the grade by colour but S vs S+ is impossible to see. Even in "Recent plays" or "Ranks" with bigger icons S vs S+ is hard to see.
Some colours like green or yellow make it a bit hard to see the white text on it.

**Comment by notbakaneko** [comment]
We can definitely make them bigger; the flip side is that then there'll be people saying it's too big and takes up too much space

**Comment by Aergwyn** [comment]
I never suggested to make them bigger. I only commented that making them bigger will probably never help after I saw the attempted fix. Though I agree with your point about the size.

**Comment by peppy** [comment]
@arflyte

**Comment by Joehuu** [comment]
Instead of the small `+` to differentiate hidden/flashlight mod plays, can the design have the silver color scheme like the old design?

**Comment by arflyte** [comment]
That's a direct export of the original files. Will design a tiny version of it.

**Comment by arflyte** [comment]
![a_mini](https://user-images.githubusercontent.com/3632750/50503532-01f48c00-0aab-11e9-8b81-c594c1a2af94.png)
![b_mini](https://user-images.githubusercontent.com/3632750/50503533-01f48c00-0aab-11e9-93f5-e94608acf15b.png)
![c_mini](https://user-images.githubusercontent.com/3632750/50503534-01f48c00-0aab-11e9-8f59-fd885bbb85db.png)
![f_mini](https://user-images.githubusercontent.com/3632750/50503535-01f48c00-0aab-11e9-9ffb-03d36016444e.png)
![s_mini](https://user-images.githubusercontent.com/3632750/50503536-01f48c00-0aab-11e9-9ea7-2bf4a32892b8.png)
![s _mini](https://user-images.githubusercontent.com/3632750/50503537-028d2280-0aab-11e9-9cd4-01b5b6d6f939.png)
![ss_mini](https://user-images.githubusercontent.com/3632750/50503538-028d2280-0aab-11e9-8e98-fd77d032c68a.png)
![ss _mini](https://user-images.githubusercontent.com/3632750/50503539-028d2280-0aab-11e9-97c1-884e79a14b36.png)
![a_mini 2x](https://user-images.githubusercontent.com/3632750/50503543-05881300-0aab-11e9-90bf-27be9da560b6.png)
![b_mini 2x](https://user-images.githubusercontent.com/3632750/50503544-0620a980-0aab-11e9-9c67-364c9fc8224b.png)
![c_mini 2x](https://user-images.githubusercontent.com/3632750/50503545-0620a980-0aab-11e9-8560-94b6f747817a.png)
![f_mini 2x](https://user-images.githubusercontent.com/3632750/50503546-0620a980-0aab-11e9-9473-99e30573cb06.png)
![s_mini 2x](https://user-images.githubusercontent.com/3632750/50503547-0620a980-0aab-11e9-8918-c371bc941962.png)
![s _mini 2x](https://user-images.githubusercontent.com/3632750/50503548-0620a980-0aab-11e9-894d-088d64da90e6.png)
![ss_mini 2x](https://user-images.githubusercontent.com/3632750/50503549-06b94000-0aab-11e9-82aa-fcf338d20f90.png)
![ss _mini 2x](https://user-images.githubusercontent.com/3632750/50503550-06b94000-0aab-11e9-8ce2-a3630b17cf3d.png)

Designed tiny versions for the score grades.

**Comment by TPGPL** [comment]
should be unassigned?
