### ISSUE TITLE
(Beatmap Panels) From two columns per row maximum to three or more columns per row depending on screen width

### ISSUE THREAD

**Issue by lunafreya** [ppy/osu-web#396]
Currently, the maximum number of beatmap panels per row is two regardless of screen width. This is why some users think the beatmap panels are "too wide" on 16:9 or 21:9 screens. Why not have three or more beatmap panels (depending on screen width)?

Example:
* Three or four beatmap panels per row on 16:9 screens
* Four or five beatmap panels per row on 21:9 screens

**Comment by VeilStar** [comment]
It's currently at 3 panels per row unless the width is less than 1350px (minus padding) from what I can tell...? I'd don't think having more than 3 is a great idea as you'd have little space for the song title (and artists).
