### ISSUE TITLE
Beatmaps section on profiles is too bright

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#3960]
Since the profile is now a darker theme, the beatmaps section is almost blindingly bright compared to the other parts. Using gray or changing colour theme follows suit better.

also new profiles <3

**Comment by peppy** [comment]
A redesign of these panels is already planned (and design phase is completed), but didn't make this particular pass.

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu-web/pull/5691.
