### ISSUE TITLE
Change show more of profiles best performance list to show more to 25, 50, 100 top plays

### ISSUE THREAD

**Issue by Karthyz** [ppy/osu-web#3965]
If I remember correctly the old website used to show 50 top plays as default and show up to 100 when showing more, it made seeing milestones like all top 50 / 100 plays above x pp quite easy. I think 5, 25, 50 and 100 makes more sense than the 5, 25, 45, 65, 85, 100 it is now. If you're clicking that button more than twice you're probably wanting to see everything anyway and it would allow you to easily see at a glance what your 25th, 50th and 100th top performance plays are.

**Comment by Joehuu** [comment]
It is now 5, 55, and 100, so closing.
