### ISSUE TITLE
profile: remember last setting for collapsed/expanded ranking info

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#3967]
not much point if you have to click it every single time you visit someone's profile to collapse the ranking area
![image](https://user-images.githubusercontent.com/33286824/49676319-427e5e00-fa47-11e8-843e-45d711e1d02e.png)

**Comment by arflyte** [comment]
Set it to remember visitor's setting.

**Comment by peppy** [comment]
@arflyte across all profiles?
