### ISSUE TITLE
Inbox Icon still redirects to old page

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu-web#3968]
![wat](https://user-images.githubusercontent.com/27222621/49685704-6645b080-fae8-11e8-9905-71a83f7c5291.png)

Now that the new system appears to be open to the public this shouldn't link to the old page.

**Comment by peppy** [comment]
For this to be updated, the count of new messages needs to be correctly reflecting the new system, which it isn’t currently. We’ve discussed making this happen but it’s not a straight-forward change.

**Comment by TPGPL** [comment]
should be closed

**Comment by Aergwyn** [comment]
Indeed.
