### ISSUE TITLE
Upper bar in profile page is doubled

### ISSUE THREAD

**Issue by ticotaco72** [ppy/osu-web#3974]
![2018-12-09 2](https://user-images.githubusercontent.com/32620809/49701530-e6097300-fbed-11e8-9910-875a159dfdf7.png)
it doesn't look well and isn't easy to use 'cause when you coever upper bar then you can't click on lower until you go down too much e. g. when you go with your mouse too high trying to click it 'cause it covers with contecst menu all the lower bar

**Comment by arflyte** [comment]
still looking into this issue.
