### ISSUE TITLE
Restriction bar overlaps OWC banners on user profiles

### ISSUE THREAD

**Issue by czapek1337** [ppy/osu-web#3975]
![image](https://user-images.githubusercontent.com/32851089/49701824-785f4600-fbf1-11e8-9d5b-def7a385ef89.png)

**Comment by cyanidee** [comment]
@peppy unban me

**Comment by spook0** [comment]
https://www.youtube.com/watch?v=1dCD3EyPK-0

**Comment by Joehuu** [comment]
I don't think this happens anymore since the banner is below the avatar now.
