### ISSUE TITLE
Fixed profile tabs stuck at top of screen

### ISSUE THREAD

**Issue by kevinwlau** [ppy/osu-web#398]
On a user profile page, when you click one of the sections on the horizontal navigation, it scrolls down to the section and fixes the horizontal nav to the top of the screen.

When you scroll back up, the nav bar is still stuck there.
![screenshot 2016-02-25 00 14 24](https://cloud.githubusercontent.com/assets/689163/13311556/0dfafe0e-db55-11e5-8565-23c39b3568c5.png)

**Comment by kevinwlau** [comment]
This also occurs when you scroll down past the nav bar and refresh the page.

Additionally, the nav bar items don't show active state when scrolled to the corresponding section of the profile.

**Comment by nanaya** [comment]
try updating the source and rebuilding the assets
