### ISSUE TITLE
Text color change proposals on profile page

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#3989]
Stat numbers should be white not blue. It looks like something is linked.
![](https://puu.sh/CfIkB/2ba0cbb039.png)

Website links should be blue. I can't see the linkable text.
![](https://puu.sh/CfIkH/83b8d922fe.png)

**Comment by peppy** [comment]
I've brought this ujp multiple times in previous designs, yet we're still here.

**Comment by arflyte** [comment]
Change the stat numbers to white, and keep it bolded.

**Comment by TobiasLeander** [comment]
Green would also look pretty neat since the new profile page is going for some green kind of look. 
`color: #08fba0;` 
![green text](https://user-images.githubusercontent.com/26700331/50670462-0e597700-0fcc-11e9-89b9-876218a8d405.png)

**Comment by arflyte** [comment]
![chrome_190104-174237](https://user-images.githubusercontent.com/3632750/50679756-2c64bd00-1048-11e9-8364-2766d8cad156.png)

Update to the extra details. Keep the Stat colour to white for now. I'll revise the colours again once I go through with every section.
