### ISSUE TITLE
Stop store.ppy.sh being used for non-store routes

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#399]
![](https://puu.sh/nkFy5/c33ee9cfa8.png)

This needs to be fixed (and vice-versa).

**[Bounty](https://goo.gl/nFdoyI) offered**: 30

As always, ask if you have any questions, and feel free to jump on the [osu!dev slack](http://osu.ppy.sh/p/slack) for more real-time discussion.

**Comment by lunafreya** [comment]
You mean replacing the osu(new).ppy.sh/store hyperlink in the new osu!web header's store link with that of store.ppy.sh?

**Comment by LiquidPL** [comment]
I guess, also with redirecting to new.ppy.sh if someone uses a store link

**Comment by LiquidPL** [comment]
@peppy will this be a problem if I move the store admin to store.ppy.sh/admin?

**Comment by LiquidPL** [comment]
generally i think that if it is under a separate domain then the /store 'folder' is unnecessary

**Comment by nekodex** [comment]
We discussed this again and have decided to instead phase out store.ppy.sh and just have the store reside on the main site.
