### ISSUE TITLE
Move profile information to the upper part of the profile information

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#3997]
![](https://user-images.githubusercontent.com/19843905/49817644-17f71280-fd71-11e8-877b-d699d96ac46b.png)

there's no reason to keep it down there and it's hard to read as it is set horizontally

**Comment by peppy** [comment]
WHat happens when the window isn't full width? Keep in mind the design is fluid.

**Comment by arflyte** [comment]
Space above is reserved to accommodate long nicknames, former nicknames and for other important future details such as teams and team member next to the flag.

**Comment by Joehuu** [comment]
Can be closed as it's not happening.
