### ISSUE TITLE
profile-tournament-banner class width size unadjusted

### ISSUE THREAD

**Issue by VINXIS** [ppy/osu-web#4005]
Current profile page banners look like they haven't been adjusted to the new design, was expecting something like this:
![expected](https://imbouttaheadout.s-ul.eu/Om1z2UME)

However currently, it looks like this (which was the width of it in the previous profile design):
![actual](https://imbouttaheadout.s-ul.eu/MIxfKZDz)

[(Width: 100% on the profile-tournament-banner class was what i did for the expected img)](https://imbouttaheadout.s-ul.eu/fIGq1z62)

**Comment by nanaya** [comment]
That'd cover any profile image one has.

**Comment by VINXIS** [comment]
thats true, but the current one kind of does already that as well already and looks off-putting with the width size, maybe a different position for it?

**Comment by peppy** [comment]
It could probably be moved up a bit to better center it vertically?

**Comment by Joehuu** [comment]
Fixed with new design.

<img width="1034" alt="Screenshot 2022-11-08 at 8 30 11 PM" src="https://user-images.githubusercontent.com/35318437/200738965-0b47f21b-7d5e-4527-8722-592c37eb2235.png">
