### ISSUE TITLE
The Mix Manifest doesn't exist

### ISSUE THREAD

**Issue by AlexzanDev** [ppy/osu-web#4014]
Hi, from some days I'm trying to setup the website on a VM with Ubuntu 16.04, and I got into a lot of non osu-web related problems that I managed to fix. Now, for some reason, when I try to get into the website on local IP, a screen appears, telling me that The Mix Manifest doesn't exist.
Just to specify, the mentioned file actually exist. I don't really know what to do now. Any tips? To clarify, I used the first method in the setup, the "Experienced Developers" one.

Screenshot:
 [https://imgur.com/a/69qZRcm](url)

**Comment by nanaya** [comment]
Did the assets compile correctly?

**Comment by AlexzanDev** [comment]
@nanaya Yes, they did

**Comment by nanaya** [comment]
Does the file `public/mix-manifest.json` exist? And is it accessible by the php process?

**Comment by AlexzanDev** [comment]
> 
> 
> Does the file `public/mix-manifest.json` exist? And is it accessible by the php process?

I restored the snapshot before doing the build.sh and I discovered the problem. Node-saas isn't supported with Nodejs 11, so I installed Node 8 and now everything works. Thanks for your time :)
