### ISSUE TITLE
Remove one "show replies" button on map comments

### ISSUE THREAD

**Issue by AncuL001** [ppy/osu-web#4018]
![test](https://i.imgur.com/xn6HZAH.png)

i suppose we only need one of these

**Comment by nanaya** [comment]
One is to collapse, the other is to load.

**Comment by Kagetsu24** [comment]
i agree with this too, the Replies(x) thing isn't of much use since you have the collapse arrow at the right side of the comment anyway.

**Comment by arflyte** [comment]
Let's remove the Reply[+] button for now. I'll look into different ways to show the reply count.

**Comment by nanaya** [comment]
The "show replies" button has been removed when there's no replies loaded.
