### ISSUE TITLE
Allow mappers to mark which difficulties are not for ranking

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#4028]
Mappers often include various difficulties that are mixed in with the set that they don't intend to push for ranked for various reasons. Have an option mappers can tick that would show a message on the modding discussion page saying "The mapper has marked this difficulty not for ranked" or something along those lines. While the mapper can post a note in General (This difficulty) tab saying the diff is not for ranked, I believe allowing an explicit option to do so as well as special highlighting of the message will allow mappers and modders communicate the status of difficulties more efficiently.

**Comment by cl8n** [comment]
can you give an example of when this would be used? all that's coming to mind for me is hitsound diffs but those are pretty clearly marked as such already. overall I feel like this is a kind of random / oddly-specific marking to support on the website, but maybe it's okay if this is really common or something...

**Comment by abraker95** [comment]
Other than hitsound diffs I don't think it is actually that common.

I actually don't remember the circumstances that made make this issue. I think I made this because I ran into some kind of annoyance when either browsing the pending section or looking for maps to mod. Either way, I am reading it again and not sure what actual problem this is trying to solve.

**Comment by cl8n** [comment]
closing then, I also showed this one to Hivie (NAT) and they said it doesn't seem worth it to add this just for hitsound diff, which is the only real use case any of us could think of.
