### ISSUE TITLE
NotSupportedError: The media resource indicated by the src attribute or assigned media provider object was not suitable.

### ISSUE THREAD

**Issue by IDNatte** [ppy/osu-web#4029]
firefox browser bugging me and kind of annoying tho i don't know why but i cant play sound when i want to downloading my beatmap, also i don't have any idea where to report so i just posting in here. if there someone know where i should report this please tell me.

this is the source why it can't be played but i didn't have any idea how to fix it.
![shiet](https://user-images.githubusercontent.com/35636456/50423480-d72eeb80-0890-11e9-933b-5515123a9389.PNG)

**Comment by IDNatte** [comment]
sorry if i late noticing this threat, here my OS info and browser info

**Windows version : windows 10 version 1803 (OS Build 17134.706)**
**Browser : Firefox Quantum 66.0.3 64 bit**

**Comment by notbakaneko** [comment]
does it still not work for you?

**Comment by IDNatte** [comment]
nope, still the same... although the error NotSupportedError is missing. did it has something to do with this error ??

![a](https://user-images.githubusercontent.com/35636456/56720492-90d19680-6775-11e9-9f8c-716cc20168e6.PNG)

**Comment by cl8n** [comment]
yeah this will be fixed by #4378

**Comment by IDNatte** [comment]
gotcha, i'll close this issue for the moment.

**Comment by notbakaneko** [comment]
@IDNatte can you go directly to that url and see if there are any certificate errors?

**Comment by IDNatte** [comment]
@notbakaneko i didn't get any certificate error, but from what i know this error 

`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://b.ppy.sh/preview/725612.mp3. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing)`

in browser console, i guess it has something to do with server side, or maybe this is the result of firefox feature about tightening the security and some incompatible / not supported javascript library for media source. for browser other than firefox, even for edge latest version in my computer nothing wrong about audio play, in my case it's ms edge  `Microsoft Edge 42.17134.1.0` ms html version `Microsoft EdgeHTML 17.17134`.

**Comment by nanaya** [comment]
Do you have any extensions installed? Can you check if the browser can play audio in [this page](https://e.myconan.net/audiotest.html)?

**Comment by IDNatte** [comment]
nope i can't tho...
this the error

![ss2](https://user-images.githubusercontent.com/35636456/56734254-e5d0d500-6794-11e9-8126-a1acaa463f53.PNG)

**Comment by nanaya** [comment]
Can you take screenshot of the inspector tab?

**Comment by IDNatte** [comment]
here the inspector tab.

![ss3](https://user-images.githubusercontent.com/35636456/56735089-14e84600-6797-11e9-9f6e-548c77d935ab.png)

**Comment by nanaya** [comment]
Your extension/plugin is modifying the page, causing error. It's supposed to look like this (note the lack of some of the attributes):

![](https://s.myconan.net/2019-04/firefox_2019-04-25_21-27-00.png)

**Comment by IDNatte** [comment]
owh i see that... the causing the error...

okay i'll try removing my extension, and then try to opening it agai...
i'll close this issue for the moment tho... thanks for the work arround...
