### ISSUE TITLE
Slack invitation page

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#404]
This bounty is creating a slack invitation page to replace the [old one](https://osu.ppy.sh/p/slack). It allows our system to send out email invites for people who want to join the public slack network.

![](https://puu.sh/nkR8c/4f877df549.png)

Requirements:
- This doesn't require a react implementation.
- Should try to match the old conditions in the code below.
- Implement active and inactive states as per psd.
- Show the accepted state after the button has been pressed.
- SLACK_TOKEN should be provided in the env file.

PSD: https://www.dropbox.com/s/4hg1fr2z3fsl8uo/osu%21next%20-%20Slack.psd?dl=0

Here's the old code for reference:
```
$alreadyHasAccount = $conn->queryOne("SELECT COUNT(*) FROM osu_slack_users WHERE user_id = $localUserId") == 0;

$canInvite = true;
$canInvite &= $conn->queryOne("SELECT SUM(playcount) FROM osu_user_beatmap_playcount WHERE user_id = $localUserId") > 100;
$canInvite &= $alreadyHasAccount;
$canInvite &= $user->data['user_type'] != 1 && $user->data['user_warnings'] == 0;
$canInvite &= $conn->queryOne("SELECT COUNT(*) FROM osu_user_banhistory WHERE user_id = $localUserId AND timestamp > DATE_SUB(NOW(), INTERVAL 28 DAY) AND ban_status in (2)") == 0;

$agree = $_REQUEST['agree'] == '1';

$smarty->assign('canInvite', $canInvite);
$smarty->assign('alreadyHasAccount', $alreadyHasAccount);
$smarty->assign('agree', $agree);

if ($agree && $canInvite)
{
	file_get_contents("https://osu-public.slack.com/api/users.admin.invite?email={$user->data[user_email]}&token={SLACK_TOKEN}&set_active=true");
}
```

**[Bounty](https://goo.gl/nFdoyI) offered**: 100-150 depending on implementation quality.

As always, ask if you have any questions, and feel free to jump on the [osu!dev slack](http://osu.ppy.sh/p/slack) for more real-time discussion.

**Comment by LiquidPL** [comment]
i'll try to tackle this. expect something before sunday

**Comment by peppy** [comment]
Just as a note, keep in mind all PSDs we provide are @2x, so make sure to div2 any pixel values you take from it.

**Comment by LiquidPL** [comment]
How should be the images positioned? Do they have to be padded as they are on the psd, or is it ok if they are centered?

**Comment by peppy** [comment]
You can just include it as once big image containing the left and right portions if that makes it easier (then centre that image).

**Comment by LiquidPL** [comment]
```
$alreadyHasAccount = $conn->queryOne("SELECT COUNT(*) FROM osu_slack_users WHERE user_id = $localUserId") == 0;
```

What's that table? I don't see it in the schema.

**Comment by peppy** [comment]
```
CREATE TABLE osu_slack_users
(
    slack_id VARCHAR(50) PRIMARY KEY NOT NULL,
    user_id INT(11) NOT NULL,
    created_at TIMESTAMP DEFAULT 'CURRENT_TIMESTAMP' NOT NULL
);
CREATE INDEX user_id ON osu_slack_users (user_id);
```

**Comment by peppy** [comment]
Entries are inserted there by a separate script which runs on a schedule and checks/matchers signed-up slack users (using a slack outgoing webhook).

**Comment by peppy** [comment]
Awarding 120 for completion of this to @LiquidPL
