### ISSUE TITLE
Kudosu tab doesnt get highlighted when account standing is a thing

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#4048]
![an63od2](https://user-images.githubusercontent.com/32525896/50545559-dcd15c00-0c17-11e9-9382-ad149515b776.gif)

scroll down until account standing
https://osu.ppy.sh/users/5149551

doesn't happen on profiles without account standing

**Comment by Lyawi** [comment]
> as the page is too short to trigger the highlight.

so it just needs to be longer on profile? when its "long enough" ?

**Comment by nanaya** [comment]
Somewhere around first third of the screen and not the very bottom of the page.

**Comment by nanaya** [comment]
Closing issue as there's no getting around this. It is even more visible on tall display where multiple sections can be shown at once at which point the highlight makes even less sense.
