### ISSUE TITLE
Site not loading properly on Microsoft Edge

### ISSUE THREAD

**Issue by bieel1503** [ppy/osu-web#4051]
Sometimes when reloading, the site doesn't load properly. This also happen when multiple tabs of beatmaps are opened in a short time.

Video: https://youtu.be/FZsKGwkMTNE

EDIT: I downloaded Chrome for testing and it does not reproduce.

**Comment by GamezombieCZ** [comment]
I also ha similar problem. (using Edge or Firefox)
It's true I have lot's of tabs opened in Firefox, but only one tab is web of Osu!.
If I'm trying in Edge it's same even with one tab.
In Chrome there isn't any problem like that.
Maybe this will help a little with fixing the issue.

**Comment by nanaya** [comment]
This shouldn't happen anymore (or at least less often). Please inform if still happening.
