### ISSUE TITLE
Add button to redirect to beatmap page on discussion page

### ISSUE THREAD

**Issue by GSculerlor** [ppy/osu-web#4063]
![example](https://gsculerlor.s-ul.eu/mmD8VJSW)

Something like that, maybe? Cause placing it on title is hard to notice + no feedback to user if we hover it over the title that indicate it redirect us to beatmap page if we click on it

**Comment by Celektus** [comment]
You can currently just click on the song title and it'll redirect you to the beatmap listing

**Comment by peppy** [comment]
This is not immediately obvious. It feels like this should probably use a tab system similar to user profiles, to get back and forth.

![image](https://user-images.githubusercontent.com/191335/50758219-ed7f7300-12a4-11e9-9286-33cfd7d9a247.png)


@arflyte ?

**Comment by arflyte** [comment]
![photoshop_190107-193228](https://user-images.githubusercontent.com/3632750/50763415-1149b580-12b3-11e9-8fda-1fb45a09101d.png)

It's in the new design. We can temporarily add that button for the current design while we work on the new beatmap pages.
