### ISSUE TITLE
Admin Tools

### ISSUE THREAD

**Issue by arflyte** [ppy/osu-web#4067]
Here are the controls for admins tools. The button floats on top of the old/new switcher. It's only visible when the user's cursor hovers around the area. Yes, it's hidden. Admins must know the location of the button to make it visible.

![photoshop_190107-153358](https://user-images.githubusercontent.com/3632750/50752539-fe72b900-1291-11e9-9ab4-c52f1a6af70d.png)
Expanded

![photoshop_190107-153446](https://user-images.githubusercontent.com/3632750/50752540-ff0b4f80-1291-11e9-903a-c8784d07eab7.png)
Default

![photoshop_190107-153459](https://user-images.githubusercontent.com/3632750/50752542-ffa3e600-1291-11e9-9494-2ad4277271e1.png)
Zoomed in

**Comment by nanaya** [comment]
Already done.
