### ISSUE TITLE
Updating images in the osu! wiki do not update/cache in osu-web

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#4091]
Happens on images that are replaced (i.e. new image, same file name).

Happened on https://github.com/ppy/osu-wiki/pull/1883/files with the hack, and https://github.com/ppy/osu-wiki/pull/1956/files where the problem takes place on:

https://osu.ppy.sh/help/wiki/Mascots/#-yuzu

Should be this: https://github.com/ppy/osu-wiki/blob/master/wiki/Mascots/en.md#-yuzu

Edit: It has been a day since. The supposed time was 2 hours.

**Comment by peppy** [comment]
This is intended behaviour. You can fix this by adding a query string on the end of the image.

`image.jpg` -> `image.jpg?20190101`

**Comment by Joehuu** [comment]
So a month has passed since I last checked, and the said image updated itself.

Is this also intended behavior? I'll put it in https://github.com/ppy/osu-wiki#file-caching.

And this also applies to the news banner updates. They are still outdated as of now.

**Comment by peppy** [comment]
Yes, cloudflare caches hold for up to one month. Again, the filename should be changed with a suffix if the image content has changed.
