### ISSUE TITLE
Osu!Supporter Purchase Issue

### ISSUE THREAD

**Issue by Kamyyosu** [ppy/osu-web#4094]
So I could not be able to purchase an osu!Supporter Tag because in the process of checking out the order of one, it cancels my order because I have a previous order that was not continued.But I only have one order in my cart and was that was added just recently.I also had a problem before when I had two orders for Supporter Tags in my cart and couldn't purchase one so I had to wait until the orders were removed.They were just removed recently so I decided to buy one.But the same problem still occurs.

**Comment by peppy** [comment]
Could you please include your username and order id if you have one?

**Comment by Kamyyosu** [comment]
Username: Kamyy
Order ID: 425632

**Comment by notbakaneko** [comment]
Whatever you're using to pay is being rejected by Paypal.
Paypal doesn't provide us any information on why it's rejected, so I suggest contacting osu! support and/or Paypal.
