### ISSUE TITLE
Line break isn't styled in news articles

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#4095]
![15cae847-c7f3-423a-b9ce-f9788552377d](https://user-images.githubusercontent.com/191335/51112104-aadc0e80-1841-11e9-9456-b76c2b7e25d7.jpeg)

Feels out of place when everything else is styled purple.

**Comment by arflyte** [comment]
Change the bar colour to #ebb8fe

**Comment by nanaya** [comment]
Fixed in current PR.
