### ISSUE TITLE
Ability to see a list of comments made by user on maps

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#4112]
With Disqus you were able to see the list of comments you have made on beatmaps, but that is now gone. So I suggest adding it as a link in the user's profile page in a similar way you can see the list of forum posts a user has made. Something like "Contributed ### forum posts and ### map comments":

![](https://i.imgur.com/wJRnZPN.png)

**Comment by dorothy3242** [comment]
I'd like to add this feature would be beneficial for moderation as well. This should be a higher priority than backlog.
Right now if we (NAT or GMT) receive a report of a user posting something offensive on beatmap comments, there is not a good way to check if they have made similar offending posts on other maps.
