### ISSUE TITLE
Inconsistency between beatmap fav count and tooltips

### ISSUE THREAD

**Issue by GSculerlor** [ppy/osu-web#4114]
Example: 
https://osu.ppy.sh/beatmapsets/439917 and https://osu.ppy.sh/beatmapsets/710979
![Example](https://gsculerlor.s-ul.eu/d6Bfe2yR)
![Second example](https://gsculerlor.s-ul.eu/LAUT0nXe)

**Comment by Joehuu** [comment]
Duplicate of #1815.
