### ISSUE TITLE
Left arrow input is broken on the forums

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#4116]
Edit: For navigating though the forums.

**Comment by peppy** [comment]
Can you explain what you expect it to do?

**Comment by cl8n** [comment]
if you mean for scrolling through the posts on a topic, both the left and right arrow keys are working fine for me. latest stable chrome

**Comment by Joehuu** [comment]
What cl8n said.

Using Windows 10, Chrome Latest, 1680x1050. Also right arrow key scrolls 2 posts.
