### ISSUE TITLE
Poor scrolling performance on profile page when anchor URL is updated

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#412]
Windows 10 / Chrome (stable): When scrolling on the profile page and arriving in a new section, the URL is updated with the appropriate anchor. This causes a noticeable pause in chrome rendering. Does not happen when jumping to a section and is directly related to when the URL changes.

**[Bounty](https://goo.gl/nFdoyI) offered**: 80

As always, ask if you have any questions, and feel free to jump on the [osu!dev slack](http://osu.ppy.sh/p/slack) for more real-time discussion.

**Comment by nanaya** [comment]
I think it's sped up a bit but can certainly use further improvements.

**Comment by peppy** [comment]
Should reference the relevant issue in your commits.
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by peppy** [comment]
Feels 100% fixed here fwiw.
