### ISSUE TITLE
Wrong acc displayed on spotlights 

### ISSUE THREAD

**Issue by Squaretrix** [ppy/osu-web#4130]
https://osu.ppy.sh/rankings/osu/charts

Maxe191 has a 104% Accuracy 
[01/25/19 |  8 PM UTC]

Screenshot: http://de.tinypic.com/r/2ding3o/9

_EDIT:_ Maxe191 has a 123% Acc now
[01/31/19 | 6 PM UTC]

Screenshot: http://de.tinypic.com/r/119s47d/9

**Comment by cl8n** [comment]
it seems like scores are being counted twice or something; Toy mentioned how Maxe191's scores add up to a lot less than his displayed ranked score on the chart

**Comment by peppy** [comment]
I've been looking into this but am still unable to find the root cause. I will likely run a reprocess on all scores to fix once, and see if it happens again.

**Comment by peppy** [comment]
Thanks for the further investigation. I'll keep this thread updated as I find more.

Technical:
`accuracy_total` is being inflated while `accuracy_count` is 100% correct.

**Comment by peppy** [comment]
This has since been fixed.
