### ISSUE TITLE
Multiplayer match history breaks when a user does not have a country

### ISSUE THREAD

**Issue by E223** [ppy/osu-web#4134]
Originally, I was going to use [this match](https://osu.ppy.sh/community/matches/49170971) as an example, but the player in question that was missing a country has since received a country (and now the page works). Not sure if there are many more examples just laying around.

I do have these pictures however:
![1](https://i.imgur.com/eknO1bw.png)
![2](https://i.imgur.com/WpoVhf0.png)

**Comment by peppy** [comment]
Generally we guarantee all users have a country code, so this should not occur. Please re-open if you find a csae of this happening again.

**Comment by WalterToro** [comment]
Well, this happened again when looking at another recently created user

![](https://walter.s-ul.eu/0QIEofuk.png)

This user was in [this](https://osu.ppy.sh/community/matches/49271134) particular room and gave this error on console 

![](https://walter.s-ul.eu/h6ZHqn8G.png)

**Comment by cl8n** [comment]
this one can close too

**Comment by notbakaneko** [comment]
fixed in #4356
