### ISSUE TITLE
Text on news (frontpage) entries may be hard to read 

### ISSUE THREAD

**Issue by Aergwyn** [ppy/osu-web#4135]
![wat](https://user-images.githubusercontent.com/27222621/51823268-3c865a00-22df-11e9-9c28-66fc021fe866.png)
The text should have some outline, shadow or general background for the text areas to prevent awkward or impossible reading quality.

![wat](https://user-images.githubusercontent.com/27222621/51823371-7fe0c880-22df-11e9-8dd0-1fe0d22613d9.png)
This may also be valid for the headers on the news entries themselves.

**Comment by peppy** [comment]
I don't find any of these offensive (also the text there *does* already have a shadow).

**Comment by Aergwyn** [comment]
On the first image the right is awkward (bottom line). If there would be any brighter image it would only get worse.

**Comment by peppy** [comment]
Thos are already pure white. Also going forward text is not going to be included in the header desgigns.

**Comment by Aergwyn** [comment]
Alright, then I guess it is a momentary potential for awkwardness which will disappear in the near future.
