### ISSUE TITLE
Make signature less highlighted

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#4143]
![untrj6r](https://user-images.githubusercontent.com/32525896/52137469-e56be680-264a-11e9-8a77-6847485241f5.png)

signature font seems thicker and darker to me, which makes me look first at the signature and then the actual post

actually, i think we could have it greyed out all a bit until you hover over the signature to view the colors

in this case we maybe could get to see signatures in forums like Help again? >.>

**Comment by peppy** [comment]
I agree the signatures are currently too prominent. The gray background doesn't help (too much contrast with the post) I think.

**Comment by arflyte** [comment]
Change the background to even lighter gray #f5f5f5 with #eeeeee top-border. Will make the sig less prominent in the new design.
