### ISSUE TITLE
Move news post titles below the cover image

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#4144]
A lot of the news post covers already have text in them (usually including the title), so it looks a little odd to have the title text there again and overlaying it
![screenshot_20190203_160707](https://user-images.githubusercontent.com/9954349/52184875-ed07c880-27cd-11e9-88b0-7f72a93770ce.png)
![screenshot_20190203_160944](https://user-images.githubusercontent.com/9954349/52184898-22acb180-27ce-11e9-8795-146d97373cfd.png)

I think the home dashboard's view makes the news posts easier to read, though it looks like the author is missing there
![screenshot_20190203_161206](https://user-images.githubusercontent.com/9954349/52184935-77e8c300-27ce-11e9-9921-e6ea9a26e296.png)

**Comment by GSculerlor** [comment]
Yeah, probably this is good approach to solve problem like this ![News title problem on mobile](https://cdn.discordapp.com/attachments/558959115083448371/567382533797314600/Screenshot_20190415-190747.png)

**Comment by cl8n** [comment]
@arflyte do you have an opinion on this, a bunch of new banners (that I assume you helped design) already include text

**Comment by peppy** [comment]
@ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE @ARFLYTE

**Comment by arflyte** [comment]
in the new design, the title will appear under the cover image. we can move the current title out of the cover for now.

**Comment by cl8n** [comment]
done in #5709
