### ISSUE TITLE
News article font size is larger than anything else anywhere

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#4158]

**Comment by cl8n** [comment]
![screenshot_20190204-080847](https://user-images.githubusercontent.com/9954349/52220623-300c7f00-2854-11e9-8840-aaa55521afa5.png)
may or may not be related, the increased margins on this page + large font size make the mobile view a little inefficient to read on

**Comment by arflyte** [comment]
Reduce the content font size to 14. Reduce the padding, leave only 10 px for mobile.

**Comment by notbakaneko** [comment]
10px in total from the edge, or 10px plus everything in between?

**Comment by peppy** [comment]
@arflyte

**Comment by arflyte** [comment]
Total from the edge.
