### ISSUE TITLE
Emails not being sent for Qualified maps

### ISSUE THREAD

**Issue by VINXIS** [ppy/osu-web#4167]
I'm not sure if I'm the only one, but I ranked about 3-4 sets these past few weeks which had mods while qualified, and I had received 0 emails regarding these pending issues... while they were subjective issues for the most part that I may or may not have agreed with, I still had no idea that people modded the map while it was qualified because i didn't receive any emails

The BPM issue in https://osu.ppy.sh/beatmapsets/545931/discussion/-/generalAll/pending is an actual issue that would need to be fixed, however I didn't know this was posted until Chaoslitz told me about it this morning a few hours ago. The map was going to be qualified in less than a day or so and the post was made days ago

I checked my spam filter and everything and got no emails at all. When the map was disqualified previously though, I did receive an email regarding activity on my map. Same with my currently pending maps that are not in qualified yet.

**Comment by notbakaneko** [comment]
Is this still in issue? Submitting a beatmap now should enable watching by default.

**Comment by VINXIS** [comment]
no seems fine now, seemed like more of a 1 time thing
