### ISSUE TITLE
Discord username tooltip disappears immediately on copy

### ISSUE THREAD

**Issue by phosphene47** [ppy/osu-web#4169]
"Click to copy" tooltip appears on hover. On click, it changes to "Copied to clipboard!" for an instant then disappears.

<img width="193" alt="2019-02-07 19 46 48" src="https://user-images.githubusercontent.com/27663662/52399783-56ab0e00-2b11-11e9-8c9f-1c0327126f5c.png">

Safari 12.0.2

**Comment by peppy** [comment]
Are you saying it disappears too fast?

**Comment by phosphene47** [comment]
Yes, but it's more like *instantly*.

https://streamable.com/gd0oj

**Comment by notbakaneko** [comment]
this seems to have been fixed at some point?
