### ISSUE TITLE
Post highlight doesn't wrap around user color stripes

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#4184]
![chrome_2019-02-15_11-38-06](https://user-images.githubusercontent.com/9954349/52880289-6b416480-3116-11e9-94b5-3f5528678b6e.png)
I think the outline should go around the stripe on the left

**Comment by peppy** [comment]
Corner radius/padding also seems a bit weird in that screenshot.

**Comment by arflyte** [comment]
Looking into this

**Comment by TPGPL** [comment]
fixed probably?
