### ISSUE TITLE
Website and Client/Ingame Leaderboards Inconsistent

### ISSUE THREAD

**Issue by Magnus-Cosmos** [ppy/osu-web#4190]
I'm guessing this is a similar issue to #2724

On https://osu.ppy.sh/b/1520642
With the website, we see https://i.imgur.com/5TNaUpb.png
Ingame, we see https://i.imgur.com/HkT1e1C.jpg and https://i.imgur.com/Ce5vH5Q.jpg
The client displays PlayLeo as 1st, and Kevinii333 as 50th, which is consistent with the old website
But new website/api displays https://i.imgur.com/Rkldo70.png, where kevin3333g is 1st, and Duskyui is 50th, and PlayLeo is 2nd, while Kevinii333 is 55th

It seems like some players are randomly disappearing on the ingame leaderboard, not sure what would be causing this

**Comment by notbakaneko** [comment]
kevin3333g was the first player to set the score, the First Place Ranks on the user profiles also reflect this (it's on kevin3333g's profile, not PlayLeo's); this looks like a bug in the old site's sorting. The client currently seems to get the leaderboard from the old site, so the ordering there would have the same bug.

**Comment by Magnus-Cosmos** [comment]
Solved via #5920
