### ISSUE TITLE
Localized shortened large number

### ISSUE THREAD

**Issue by grindelwaldos** [ppy/osu-web#4192]
Short scale uses powers of 1 000, long scale uses powers of 1 000 000
In most English-speaking countries the short scale is used.
In most of Europe and South America, for example, the long scale is used.
Use this as reference: https://en.wikipedia.org/wiki/Long_and_short_scales#Current_usage
Number vs. Short scale vs. long scale
10^3 thousand thousand
10^6 million million(mln)
10^9 billion milliard(mld)
10^12 trilllion billion(bln)
10^15 quadrillion billiard(bld)
I'd suggest using abbreviations(in brackets),

**Comment by grindelwaldos** [comment]
Where can I file further translation suggestions? Is there any specific format you'd prefer? These will mostly refer to Polish-English translation, which I currently study at University of Gdańsk

**Comment by ticotaco72** [comment]
maybe here https://crowdin.com/project/osu-web but if it isn't created by humanizer or something similar

**Comment by nanaya** [comment]
Yes it's a known issue. It's currently not localized at all.
