### ISSUE TITLE
Brazil default language is wrong

### ISSUE THREAD

**Issue by InitialDet** [ppy/osu-web#4194]
The default language for brazil is set as "Português", thats the portugal version.

The correct one is "Português (Brasil)".

We have the same problem in the client too (wrong language as default)

![image](https://user-images.githubusercontent.com/13919114/53139397-4743b000-3568-11e9-9cae-d75461df935c.png)

**Comment by nanaya** [comment]
The language selector should be updated to something smarter. Maybe this [negotiation package](https://packagist.org/packages/willdurand/negotiation)?
