### ISSUE TITLE
Header and profile BG design

### ISSUE THREAD

**Issue by Methosss** [ppy/osu-web#4201]
please change header design, and profile background design, that gradiednds looks very bad
![image](https://user-images.githubusercontent.com/32804020/53175119-a1398980-35eb-11e9-8522-e81ed532dfe6.png)

please make more space for BG and make it equal width to the rest of the page
![image](https://user-images.githubusercontent.com/32804020/53175406-2886fd00-35ec-11e9-9189-0d5a6c6e138a.png)
or make to BG will fill first part of the page like this:
![image](https://user-images.githubusercontent.com/32804020/53176016-7fd99d00-35ed-11e9-9e7d-b3f8adbe1ffb.png)

**Comment by Lyawi** [comment]
i dont like that part too.. Stefan improvised: https://osu.ppy.sh/users/626907

**Comment by Methosss** [comment]
there's header gradient, left & right gradient and shadow gradient on pic i tired too to improvise with that, but i have not enough space for picture, and this shadow gradient making it looking bad

**Comment by Shadowthegod** [comment]
Mine looks different from those 👀 
![](https://kurokami.s-ul.eu/9lkFX2ib.png)

**Comment by Methosss** [comment]
you have a smaller monitor and / or resolution

**Comment by Shadowthegod** [comment]
1920x1080 17"

**Comment by Methosss** [comment]
try LCrtl + scroll and set zoom to 100% 🤔 

i think that will be the best way to make it's look better:
![image](https://user-images.githubusercontent.com/32804020/53178007-5884cf00-35f1-11e9-9a6b-6cc573d14fb5.png)

**Comment by Shadowthegod** [comment]
Ah, nvm. I found the "issue", it was not the zoom but a custom script which overwrote the default one. I thought I disabled those 🤔 Anyway, yeah, it looks horrible with that gradient and overextended length.

**Comment by Flanster** [comment]
I've improvised a gradient overlay with the dark theme i'm maintaining
![](https://flan.s-ul.eu/6TGzb9Pi.png)

Replacing `background-image` linear-gradient on `.header-v3__overlay:before` with

![](https://flan.s-ul.eu/bZOcj0ZQ.png)

**Comment by peppy** [comment]
that actually looks really good. @arflyte comments?

**Comment by arflyte** [comment]
Oh interesting. But need to test with various type of background; especially busy and simple bright, and busy and simple dark.

**Comment by nanaya** [comment]
The extra overlay itself (top to bottom) has been removed for a while now and the upcoming cover design won't have any kind of overlay at all.
