### ISSUE TITLE
Profile page game modes are getting wrapped to a new line on small width screens

### ISSUE THREAD

**Issue by ghost** [ppy/osu-web#4203]
intended
![image](https://user-images.githubusercontent.com/32551223/53286324-21d3c380-376d-11e9-9897-0ab1c8c98ed3.png)

small width
![image](https://user-images.githubusercontent.com/32551223/53286330-33b56680-376d-11e9-8ec9-4a81bc27a711.png)

I am using chrome's dev tools to make the width smaller, but it happens also on my phone browser

Suggestion: change the game modes text to icons on smaller screens
![image](https://user-images.githubusercontent.com/32551223/53286421-7fb4db00-376e-11e9-8a66-56e1d39e63a4.png)

**Comment by peppy** [comment]
what phone are you using?

**Comment by FajsiEx** [comment]
Lenovo P2 (res 1080 x 1920)
also tested it on Samsung galaxy S5 (res 1920 x 1080)

**Comment by Shadowthegod** [comment]
Same on Huawei Honor 8 which is also FHD

**Comment by Joehuu** [comment]
> Suggestion: change the game modes text to icons on smaller screens

Fulfilled no matter the screen size, closing as resolved.
