### ISSUE TITLE
Add ability to delete chats

### ISSUE THREAD

**Issue by GrilledCheeese** [ppy/osu-web#4204]
If I send someone a message and I don't tell them about it in a 3rd party they will never read it because they will never know about it unless they're checking the chat themselves.
Also there's no way to delete chats even if the chat is empty and you haven't even sent anything the person is still in the list because you pressed the chat button.

**Comment by peppy** [comment]
We are actively working on a notification system. Ability to leave conversations is something that will come a bit later. @nekodex can probably provide more context on this.

**Comment by nekodex** [comment]
The chat doesn't get created until _after_ you actually send a message. Currently the site just keeps the new chat visible for convenience sake (i.e. if until you attempt to send a message to another user or refresh the site without the `?sendto=` in the url anymore, it will disappear).

**Comment by nekodex** [comment]
Removing the 'notifications' part of this issue as #4461 has added notifications.

**Comment by TPGPL** [comment]
done?

**Comment by peppy** [comment]
Closed by #4494.
