### ISSUE TITLE
More cover options will be available in the future not available just icon checkmark

### ISSUE THREAD

**Issue by XIDigbyKun** [ppy/osu-web#4205]
![screenshot 8](https://user-images.githubusercontent.com/47943587/53299639-8b3bfb00-386f-11e9-9d3b-0b8d6ae7510b.png)

**Comment by peppy** [comment]
What browser are you using here?

**Comment by GSculerlor** [comment]
From the screenshot it's should be Microsoft Edge, but can't reproduce it on my Edge (42.17134.1.0)
![something](https://gsculerlor.s-ul.eu/BiiwGoYA)

**Comment by nanaya** [comment]
Seems fine on Edge 44.
