### ISSUE TITLE
Uploading maps with too long of metadata causes no map thread to be made

### ISSUE THREAD

**Issue by Takekii** [ppy/osu-web#4206]
As the titles says, having the artist and title field too long causes no thread to be made, usually when this happens the upload fails for the file path being too long. However it appears there are some instances were you are allowed to upload, causing this issue to happen. This also makes it so that you cant revive the map if it ever gets graveyarded.

**Comment by cl8n** [comment]
needs to be fixed at the old site's BSS endpoint I think

nwolf is trying to update their map for project loved and having problems, seems related to this issue https://osu.ppy.sh/beatmapsets/772836

**Comment by peppy** [comment]
It is resolved by shortening the metadata client side, right?

**Comment by cl8n** [comment]
they said they tried that already, so I think the last sentence of OP here may be true

**Comment by peppy** [comment]
This should since be resolved. Truncation is automatically applied now.
