### ISSUE TITLE
Year in profile page graphs isn't shown correctly (italian)

### ISSUE THREAD

**Issue by Nobyx** [ppy/osu-web#4208]
Localization issue: years are displayed as "182018", but I can't find the right string on Crowdin

![screen shot 2019-02-25 at 14 03 36](https://user-images.githubusercontent.com/9320677/53339570-0ef4f680-3907-11e9-93e4-b3ccb5fd6174.png)

Edit: Found it and suggested a translation.

**Comment by nanaya** [comment]
Thanks, should be fixed once it's deployed.
