### ISSUE TITLE
Remove option to upvote while logged out

### ISSUE THREAD

**Issue by jacksonisiah** [ppy/osu-web#4209]
![image](https://user-images.githubusercontent.com/34609781/53349601-5c786000-3915-11e9-9793-58ef44c919df.png)

no need for an error if there's no option ¯(°_o)/¯

**Comment by cl8n** [comment]
showing the upvote button while logged out was probably an oversight

**Comment by jacksonisiah** [comment]
good point, i'll update the issue.

**Comment by nanaya** [comment]
Weird, the message should look like this:

![](https://s.myconan.net/2019-02/firefox_2019-02-26_12-26-15.png)

Is that from dev env?

**Comment by jacksonisiah** [comment]
just browsing the normal site logged out, I can't seem to reproduce it again.
