### ISSUE TITLE
Investigate using swoole as an application server

### ISSUE THREAD

**Issue by notbakaneko** [ppy/osu-web#4212]
[Swoole](https://www.swoole.co.uk/)

The interest in using swoole are:

1. Minimize or remove the overhead of repeatedly booting Laravel on every request, which is quite significant.
2. Make use of reflection and various techniques to make changes at runtime and have them persist across requests; being able to generate code paths based on declarations instead of having to constantly reevaluate values.

To enable running on Swoole, we will be using the `laravel-swoole` package.

When running with Swoole, instead of creating and booting a new application on every request, the application is only created and booted once per worker, with the application instance reused across requests.

Due to the booting only happening once, previous assumptions about the lifetime of static variables, singletons and resolved objects are now broken and require changes to work correctly. laravel-swoole takes care of most of the resetting required per request, but we still have to make some additions and modifications.

Because code running with Swoole is persistent across requests, it would open up the possibility of reflection and generating optimized property accessors at runtime (since there is a sizeable performance hit from Laravel’s model attribute casting), which would be preferable to:
- manually writing optimized accessors
- doing code generation to generate accessors and then either bootstrapping onto the model somehow

# Cursory results
Benchmarks are run with:
- debug off
- no debug extensions
- php-fpm set to 64 workers
- swoole set to 16 workers (matching the fpm worker count slows swoole down)
- swoole hot reloading disabled
- Opcache enabled

Benchmarks achieve 100% saturation of CPU utilization on all cores.

_Notes on Opcache_
Code loaded by a swoole worker is not unloaded, so opcache doesn’t have any meaningful effect for swoole.

We picked 2 endpoints to test against
1. `/home`
minimal DB access, mostly generating a page.
2. `beatmapsets/search` (json response)
frequently accessed, makes use of collections of the same models, repeated accesses of the same properties on the same model across different parts of the request.

When running laravel-swoole, requests to /home has about 21% higher performance; this is should be expected as we expect the overhead of booting the application on every request to be skipped.

php-fpm | laravel-swoole | speedup  
-- | -- | -- 
807.39 | 979.44 | 1.2131

(Results are in requests per second)

However, when running against beatmapset search using various result page sizes:

Results per page | php-fpm | laravel-swoole | speedup  
-- | -- | -- | -- 
1 | 600.88 | 1,311.76 | 2.1831
10 | 446.58 | 628.95 | 1.4084
25 | 306.16 | 353.56 | 1.1548
50 | 198.91 | 200.15 | 1.0062
100 | 114.29 | 105.22 | 0.9207
150 | 81.87 | 72.84 | 0.8898

With smaller page sizes where the framework’s boot overhead would constitute a larger proportion of a request, laravel-swoole is significantly faster - but when the page size increases, the speed up decreases; as expected; until it starts actually performing slower than php-fpm. 

Given that php code in both cases are still executed by Zend, we would expect that for increasing page sizes where the framework boot would take up a smaller proportion of the request execution, both php-fpm and laravel-swoole would trend towards the same limit; however, this isn’t the case when measured, suggesting there is an additional overhead introduced by using Swoole.

_Note_
As a quick experiment, serializing and deserializing the results into a variable (no elasticsearch, database or redis query to get the search results) and using the response from the deserialized variable displays the same tendency as above; Swoole has an overhead even if no querying has to be performed. Additionally, running the query but always returning an empty array as a response also showed the same behaviour, so the overhead is not likely to be related to response serialization.

Given that,
- Using laravel-swoole breaks existing assumptions for the application-request lifecycle, requiring fixes to the existing code base to support it;
- The typical response page size is 50;
- There is negligible performance benefit at the default page size;
- There is an apparent increasing overhead when using laravel-swoole;
It does not seem to be beneficial to adopting laravel-swoole for this particular scenario.

A comparison of the total number of results served (request/sec * page size):

Results per page | php-fpm | laravel-swoole
-- | -- | --
1 | 601 | 1,312
10 | 4,466 | 6,290
25 | 7,654 | 8,839
50 | 9,945 | 10,007
100 | 11,429 | 10,522
150 | 12,280 | 10,926

The results in this post use a machine of the same spec and similar environment as production; database, elasticsearch and redis are local, so there is no variance of network latency to them. Benchmarks run on my dev machine have Swoole always being faster, but we’re not running the site off my macbook 🍎

**Comment by nanaya** [comment]
and then we switched to laravel octane
