### ISSUE TITLE
GitHub button on the osu! wiki blocks title on mobile

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#4215]
![screenshot_20190227-101046](https://user-images.githubusercontent.com/35318437/53512716-551d9780-3a78-11e9-8b8e-9fcacfd20ee7.png)

**Comment by gary-kim** [comment]
I'll take a look at this. Could the button just be moved up when being viewed on mobile?

**Comment by peppy** [comment]
seems like a fair solution, yes
