### ISSUE TITLE
Friends List Page

### ISSUE THREAD

**Issue by arflyte** [ppy/osu-web#4232]
- [x] Convert user card to React
- [x] New user card
- [x] New listing format
- [x] New page format
- [ ] Extra card formats?

related issues
- #2463
- #1851

---

Here's the new friends page; comes with 4 different views.

The top bar groups the active status. Clicking Prev 50 or Next 50, slides the entire list instead of refreshing it in place.

The list tile shows the player's avatar, country flag, usertype colour (non-supporter blue, supporter pink, dev pink and so on), online status and online status colour.

Everything still requires polish, but the basic layout are there. User card designs are not final.

https://www.figma.com/file/l8dHiOeoeGKwaoJYc6h0I7/Web-Friends?node-id=0%3A1

![friend listing list](https://user-images.githubusercontent.com/3632750/53724334-ff4c5380-3eac-11e9-81ed-790da1397cc5.jpg)

**Comment by Aergwyn** [comment]
Are topics like #3774 in the scope of this new design?

**Comment by notbakaneko** [comment]
is that a new pager style? ಠ_ಠ

**Comment by nekodex** [comment]
Are the user cover images being used here different aspect-ratio to the ones we already have generated? (i.e. Do we need to batch process a new size of user covers?)

**Comment by arflyte** [comment]
The max width is 250px for 1x.

**Comment by nekodex** [comment]
Note that we don't generate alternate user cover versions yet, only for beatmap covers. So this will need to be considered.

**Comment by Ztumpie905509** [comment]
I think there could also be a list of followers. (A button to toggle from Mutuals and Followers ?)

It is quite hard to find who actually just followed me without any notifications.

**Comment by cl8n** [comment]
I think the list view could include a column for notes, that would solve #4398 for groups and #3774 for friends list

**Comment by cl8n** [comment]
the avatar-only view seems sort of useless since avatars alone aren't identifying (people change them all the time and half are just random anime girl of the month)

I think some kind of super small card would be better, like 
![53724334-ff4c5380-3eac-11e9-81ed-790da1397cc5](https://user-images.githubusercontent.com/9954349/57172389-066fdf00-6dd4-11e9-9ea5-c15bb03f8c5f.png) (spacing/sizes are all wrong but the idea is there)

**Comment by peppy** [comment]
Agree that avatar-only is a bit pointless (unless it's a zero effort implementation).
