### ISSUE TITLE
Reporting users via beatmap page gives "Not Found" error

### ISSUE THREAD

**Issue by GrilledCheeese** [ppy/osu-web#4238]
Maybe its because I already reported him via the user page or maybe it's bugged anyways.
But I can't seem to report scores or there's an unnecessary error popping up:
![image](https://user-images.githubusercontent.com/34809632/53880889-7d763a80-4012-11e9-8f0d-adc171406792.png)

**Comment by notbakaneko** [comment]
A link to the actual page where this happens would be more useful

**Comment by cl8n** [comment]
https://osu.ppy.sh/beatmapsets/811822#mania/1703135
