### ISSUE TITLE
Account Standing shows incorrect details when a user's silence will expire

### ISSUE THREAD

**Issue by Nath789** [ppy/osu-web#4239]
In minutes:
![image](https://user-images.githubusercontent.com/5668486/53890243-cbb32a00-4062-11e9-88f0-16d5d9f80c44.png)

In days:
![image](https://user-images.githubusercontent.com/5668486/53890797-db7f3e00-4063-11e9-877f-8e05fa6a130a.png)

**Comment by peppy** [comment]
Your local system time is likely wrong.

**Comment by Joehuu** [comment]
I thought it was the grammar (it's really bad atm i.e. "will" | "ago").

**Comment by peppy** [comment]
yes, it's because the users clock is wrong.

**Comment by Nath789** [comment]
My system time is just right

![image](https://user-images.githubusercontent.com/5668486/53932189-6fd4b980-40d3-11e9-826d-ab632b657397.png)

**Comment by tybug** [comment]
I can reproduce the issue as well. Curiously, when I scroll down to "account standing", it briefly shows "3 days from now" but changes to "3 days ago" afterwards.

**Comment by Nath789** [comment]
nvm. dark theme was at fault. Flan!
