### ISSUE TITLE
Some scores are not being displayed in the "Ranks" section.

### ISSUE THREAD

**Issue by Trosk** [ppy/osu-web#4244]
As the title mentions, in some cases, scores that should appear in Top Ranks are not displayed properly on the new web, while they are visible on the old web. 

This also causes the scores to show 0pp on the new web's beatmap rankings 
![applicationframehost_2019-03-08_11-54-31](https://user-images.githubusercontent.com/15179452/54024857-20f15780-4199-11e9-92ba-bf1c0cc59373.png)

Some examples of scores that appear on old web, but not on new web:
- https://osu.ppy.sh/u/4633427 237pp score on https://osu.ppy.sh/b/1848803
- https://osu.ppy.sh/u/10652263 308pp score on https://osu.ppy.sh/b/801158
- https://osu.ppy.sh/u/6735738 368pp score on https://osu.ppy.sh/b/519080
- https://osu.ppy.sh/u/12088456 160pp score on https://osu.ppy.sh/b/1854204

**Comment by notbakaneko** [comment]
The users listed already have had the score display fixed; the scores not occasionally not showing up is currently an issue with the order pp gets updated.
