### ISSUE TITLE
Keep direct links for Beatmap Packs on new website

### ISSUE THREAD

**Issue by FlyingStefan** [ppy/osu-web#4246]
At the moment you can post a link directly from a beatmap pack from the old website design, the format is 
`https://osu.ppy.sh/p/packlist/?n=<letter><number>#<letter><number>` and is a pretty handy feature, it's not that much used, yet I work a lot with that.

This however is not possible for the new forum design, and I would love if this could be kept. The current URL on the new website is `https://osu.ppy.sh/beatmaps/packs<letter><number>` which is pretty easy to use it but doesn't seem to work.

**Comment by peppy** [comment]
This should be possible.
