### ISSUE TITLE
Display Maps by Hypes Sort Option

### ISSUE THREAD

**Issue by downpour-osu** [ppy/osu-web#4258]
Just like the old forum, I'd like some way of looking at maps by Hypes the same way we used to be able to sort by Star Priority OR choose to ignore it. I don't understand why this disappeared on the new site, it was a feature I liked using a lot.

**Comment by Xinnoh** [comment]
sort by nominations is sort by hype

**Comment by peppy** [comment]
I guess this is fine to close?
