### ISSUE TITLE
Do not count posts in the Introduction subforum.

### ISSUE THREAD

**Issue by Flanster** [ppy/osu-web#4263]
This is a suggestion to possibly counter the issue of people spamming introduction threads to farm postcount with similar to identical looking formatting. Has been a low-key problem for years.

**Comment by FlyingStefan** [comment]
If you ask me I'd put the purpose of this subforum into question. As the community increases rapidly I think the idea to introduce yourself to the community doesn't work that well anymore as it used to be 7-8 years ago IMO. 

Might suggest to cease the service of this subforum too but that is just a wild idea probably no-one is going to agree with me. At least the post count for this forum should be disabled, for reasons stated above.

**Comment by Lyawi** [comment]
hey, i agree with you stefan (´･ω･`) its usually full of "hi im new and a weeb, pls mutual me" anyway, thats not really an introduction, nobody takes it serious so why would we need it still?

**Comment by Flanster** [comment]
@FlyingStefan Of course, I've said that before. The place is quite low in activity and it's like some seperate offtopic entity. If removing it alltogether is a wild idea to you, making it a sub of OT is an also an idea. Some forums use offtopic for introductions.

**Comment by cl8n** [comment]
either remove or sub under OT sounds good to me
maybe this thread should be moved somewhere else first https://osu.ppy.sh/community/forums/topics/156928 ?

**Comment by abraker95** [comment]
The whole point of it is to just say hello, beyond which would be considered off-topic and subject to a lock. So each user, according to the thread's purpose is to create a thread there once and never again. This creates an environment in which threads keep on coming and going, an environment in which no thread would have any value but to the person who created it. Nothing in that subforum is something that the community can engage in but with the user that introduction thread is for.

I am for archiving it.

**Comment by Flanster** [comment]
Yeah, forum structure has barely changed over the years while the community has. I did consider the idea for locking threads after lets say 48-72 hours or longer. Theres plenty of ideas on the table.

**Comment by peppy** [comment]
i agree that it doesn't really have a place any longer. chat is probably a better place to introduce yourself these days. archiving may be the best path forward.

**Comment by peppy** [comment]
I've turned off post count but leaving the forum as i think it's a nice means of human connection and has history.
