### ISSUE TITLE
Images with relative URLs in wiki are not proxying properly

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#4264]
seems to have regressed with #4121, and as far as I can tell it only applies to image links starting with `./` on the page. the images are accessible from their direct URL, but the proxy links 404

examples: all but first image in https://osu.ppy.sh/help/wiki/Multi, all images in https://osu.ppy.sh/help/wiki/Replay

**Comment by peppy** [comment]
Closed via #4267.
