### ISSUE TITLE
Global column in ranking pages moves from one page to another [WEB]

### ISSUE THREAD

**Issue by xasuma** [ppy/osu-web#4265]
If you look at a few countries like https://osu.ppy.sh/rankings/osu/score?country=RU or https://osu.ppy.sh/rankings/osu/score?country=FI as examples, you'll see that the "global" score ranking is wrong. 

Also, something interesting with https://osu.ppy.sh/rankings/osu/score?country=US in particular is that this page doesn't even show "global" rank at all. 

Thanks for your time.

**Comment by cl8n** [comment]
is this fixed? if not can you screenshot the issue, I'm not seeing anything wrong on these pages

**Comment by xasuma** [comment]
Back when I posted this the pages above had an extra column with the global rank, in addition to the country rank. But it looks like that column has been removed since. So there is nothing wrong now since the information I spoke about is no longer there.

**Comment by xasuma** [comment]
I figured out the issue and how to get there. As an example: 
 You have to follow the following links : Go to any rankings page > click on "country" > click on any country . At this point you will be taken into the pp leaderboard of that country, and it will try to load the "global" column as seen here: https://puu.sh/DAvyP/65311972af.png . If you wait for that column to load, and then click on the "score" hyperlink  the column will not be there on the score leaderboard page. But if you don't let the page load that 'global' column, and click "score" before it's loaded, it will load the same data for the pp page onto the score page instead: https://puu.sh/DAvBp/40d3915b70.png   (note that the global numbers are the same on both pictures), one pic is from pp leaderboard, and the other one is score. 

This is just an example, seems like I can replicate this behavior anytime the 'global' column doesn't have enough time to load and I click another link before its done loading. As seen here, picture with random globals from another page: https://puu.sh/DAvwM/b168f9fb22.png . 

Kind of confusing but I tried my best to explain it.

**Comment by Magnus-Cosmos** [comment]
I noticed a similar glitch happens when you click on a country flag on the global pp leaderboard before the country ranks loaded, results in an extra column: https://i.imgur.com/FYZJlnp.png

**Comment by qcl12345** [comment]
Country ranks aren't normally displayed on the overall performance rankings, and global ranks aren't normally displayed on the country ranking pages. This is a feature (and bug) with the popular "osuplus" user extension, not the site itself.

**Comment by xasuma** [comment]
Thank you qcl12345, I tested it and you are correct. That column comes from osuplus.
