### ISSUE TITLE
Use beatmap approval status (instead of beatmapset) to show beatmap info

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#4266]
I brought this up in 2016 but was told to revert my change https://github.com/ppy/osu-web/pull/878#discussion_r91829218

came up in discussion again because Project Loved is starting to exclude more difficulties from their Loved nominations (mostly in osu!mania, where for example a whole keymode may be excluded if it's not really the focus of the mapset), and the only way to tell if a single map isn't actually Loved is if the scoreboard is empty

...which is also misleading, because it shouldn't act as if there is a scoreboard in the first place

for example, this map is not Loved, but just about nothing on the page would lead you to assume that https://osu.ppy.sh/beatmapsets/714729#fruits/1879175

**Comment by peppy** [comment]
Bumping in priority, this is a huge oversight.
