### ISSUE TITLE
Forum reply button cut off in mobile

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#4270]
Android 5.0, Firefox 62.0b13 and Chrome 68.0.3440.85
Reply button on the bottom right is cut off, which makes it slightly more difficulty to tap, especially when having a protective cover over the phone that has a raised edge.

![](https://i.imgur.com/8GleV9I.png)

**Comment by notbakaneko** [comment]
This is a known issue https://github.com/ppy/osu-web/issues/2138#issuecomment-460536581
