### ISSUE TITLE
There is no way to close a forum reply in mobile when in horizontal orientation

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#4271]
Android 5.0, Chrome 68.0.3440.85
There is no button allowing to close the reply box. The only workaround is to press the back button to go to the previous page, and then go forward back to the page. You can also flip it back to vertical, but there can be cases where a user's device is set to be in the horizontal orientation constantly.

![](https://i.imgur.com/PaPQWjG.png)

**Comment by notbakaneko** [comment]
This is a known issue https://github.com/ppy/osu-web/issues/2138#issuecomment-460536581
