### ISSUE TITLE
Store: 404 when selecting mocha as mascot for "let's play with" t-shirt

### ISSUE THREAD

**Issue by Slayer95** [ppy/osu-web#4272]
Steps:
1. Go to https://osu.ppy.sh/store/products/35
2. Find the form for selecting MASCOT and SIZE.
3. Select mocha in MASCOT.
4. Be redirected to https://osu.ppy.sh/store/products/267, missing content.

**Comment by peppy** [comment]
Has been fixed. Thanks for pointing out!
