### ISSUE TITLE
Forum reply box on mobile catch-all issue

### ISSUE THREAD

**Issue by notbakaneko** [ppy/osu-web#4273]
This is a catch-all summary issue for all the issues with the forum reply box (originally https://github.com/ppy/osu-web/issues/2138#issuecomment-460536581):

Replying while on a mobile device seems pretty broken in general with different combinations of:
- not being able to unpin the reply box because the button doesn't fit on the screen. #4270
- on-screen keyboard can cause the page to only use the top half of the screen.
- pinned reply box can block entire view. #4271
- unpinning causes the reply box to be deselected which makes the on-screen keyboard go away (and then tapping in the reply box causes it to get pinned and the on-screen keyboard comes up and pushes everything up and we go into a loop of fail) #2138

**Comment by nanaya** [comment]
The latest design update should fix all of the problems listed here.

(reply toolbar button not being visible is conveniently not listed here)

**Comment by peppy** [comment]
Should this be closed in that case?

**Comment by nanaya** [comment]
Fixed with the update mentioned earlier (by making the reply box full screen on mobile).
