### ISSUE TITLE
Bugging SVG-heartbeat

### ISSUE THREAD

**Issue by JankoGoo** [ppy/osu-web#4283]
Just look at the tweet, that seemed to drop through.

It's starting to creep me out more and more...

https://twitter.com/GamingWithJanko/status/1107890660600963072'

Please fix that.

Info:
Device: HUAWEI P8 lite
App: Google Chrome

**Comment by peppy** [comment]
Which version of google chrome are you using here (also is it up-to-date)?

**Comment by JankoGoo** [comment]
![image](https://user-images.githubusercontent.com/48768314/55109893-1d395c80-50d7-11e9-8a09-c7423fdc2bab.png)

**Comment by JankoGoo** [comment]
I hope that helps.

**Comment by JankoGoo** [comment]
It's as up-to-date, as it can be.

**Comment by JankoGoo** [comment]
Uhh... I guess the mobile tag would be appropriate here too, since it happened on my mobile web browser.

However... How's the progress going so far?

**Comment by notbakaneko** [comment]
This seems to be specific to the GPU used by the P8 Lite and the devices using the same GPU; closing this unless it can be reproduced on something else.

Unity and Chromium have frequent issues with this chipset

**Comment by JankoGoo** [comment]
It works properly for several seconds, before it starts to bug up like that.
