### ISSUE TITLE
Difficulty icons in beatmap listing do not match beatmap page's icons

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#4288]
I filtered the beatmap listing by the mania gamemode and graveyard, and sorted by favorites. Here is a couple examples:

This says it has a mania diff, but there is non:
![](https://i.imgur.com/KO4fxY2.png)
![](https://i.imgur.com/WEuP2Oc.png)

Same thing. Only here I noticed that the mapper's names don't match up (not sure if to put it as a separate issue). Leads me to believe this has to do with caching:
![](https://i.imgur.com/UL96VVA.png)
![](https://i.imgur.com/J2bJKIo.png)

It also happens on these maps, and not exclusive to mania. 
There are too many diffs for a screenshot: 
![](https://i.imgur.com/oeO9smw.png)
Map Link: https://osu.ppy.sh/beatmapsets/840009

![](https://i.imgur.com/tUTaCJa.png)
Map Link: https://osu.ppy.sh/beatmapsets/316625#osu/706566

**Comment by celerih** [comment]
The mania diffs are there, you need to click the osu!mania tab at the top of the page

**Comment by abraker95** [comment]
Oh ok. Still learning the new interface.
Tho why are are std diffs still showing up after clicking the gamemode tabs?

![](https://i.imgur.com/kVOPI6F.png)

**Comment by celerih** [comment]
Because std diffs can convert into mania, so they are still showed. Meanwhile, mania cannot convert into std so on the std tab the diffs are not shown

**Comment by abraker95** [comment]
I see. Confusing, but makes sense. 
Original issue doesn't exist. Closing.
