### ISSUE TITLE
Thread covers and their misusage

### ISSUE THREAD

**Issue by Flanster** [ppy/osu-web#4289]
Right, so I want to share my thoughts regarding thread covers. The feature has been around for a while now and from what I've seen, if anyone ever uploaded one, its random, has nothing to do with the thread's topic and ends up getting removed. While this is wasting server space (we're talking about images 2000px large, MBs in size), we're compressing avatars to JPEGs to save KBs. Something is amiss here. Could potentially limit this feature to supporters or the team only, since I see this viable for events/official stuff, not someone making a thread in the Help subforum, uploading an anime wallpaper as a cover just because they can.

**Comment by cl8n** [comment]
maybe disable them on a per-forum basis if it's a problem?

I feel like if space were a huge concern this would've already been addressed though

**Comment by abraker95** [comment]
>While this is wasting server space (we're talking about images 2000px large, MBs in size), we're compressing avatars to JPEGs to save KBs. Something is amiss here.

I think this should be the highlight. Something doesn't add up.

**Comment by peppy** [comment]
Can you provide some examples of misuse? I agree it should probably be limited to specific forums if anything. Also covers should be getting compressed; if they aren't that is a bug.

**Comment by Flanster** [comment]
Ah good, they are getting compressed and very well from 5MB to 120kb and cropped to 2000x400. Thats good then space wise. As for examples: when I find something since I do remove them afterall.

**Comment by camellirite** [comment]
one example would be my modding queue: https://osu.ppy.sh/community/forums/topics/827776. I used to have a blue avatar and had a nice theme but I changed it since then, I think that's considered misuse. there's nothing given to say what it's used for so I assume most would think it's used to make the forum threads look more pretty. 

I'd say just give it to specific team members or whatever since they're the only ones who knows the intended use for them.

**Comment by Lyawi** [comment]
also #3064

**Comment by E223** [comment]
Here is a recent example in Help that doesn't make much sense: https://osu.ppy.sh/community/forums/topics/888989

**Comment by peppy** [comment]
help is a good example where it should probably be disabled for non-admins.

**Comment by Flanster** [comment]
Yup.
![](https://flan.s-ul.eu/RJyMZirz.png)

**Comment by peppy** [comment]
Let's get a flag added in april milestone for disallowing cover setting (for non-admins) in specific forums. Just a flag in `phpbb_forums` should do.
