### ISSUE TITLE
Set minimum account time to vote in forum polls

### ISSUE THREAD

**Issue by WalterToro** [ppy/osu-web#4291]
On simple words, you can do multiaccount abuse to vote on polls due to the site not having an minimum account time set to vote on those, this after the abuse that has been uncovered on the project love polls of people multiaccounting repeatedly to get a map loved or not (in this case, voting on [this poll](https://osu.ppy.sh/community/forums/topics/885957)), I propose that you need to have a 1 month old account to vote on forum polls so this issue is at least mitigated.

**Comment by peppy** [comment]
@nanaya we already have the minimum playcount rules for forum posting, right? can that be applied here? (alternatively, the same conditions we use for contest voting)
