### ISSUE TITLE
Slidercount on beatmaps overlap the semi-transparent background

### ISSUE THREAD

**Issue by oSumAtrIX** [ppy/osu-web#4300]
Image Preview:
[https://i.imgur.com/e5BWqBx.png](https://i.imgur.com/e5BWqBx.png)

Beatmap:
[https://osu.ppy.sh/beatmapsets/29157#osu/156352](https://osu.ppy.sh/beatmapsets/29157#osu/156352)

**Comment by Joehuu** [comment]
Duplicate of #1879.
