### ISSUE TITLE
Bug Report: Source map error on Profile page

### ISSUE THREAD

**Issue by Snowleopard-osu** [ppy/osu-web#4307]
Noticed that the Recent section of my profile page didn't appear to be updating with a recent Ranked song I had placed a new rank on.  Developement console points out 2 source map errors, unsure if related to Recent section, but here is the output:

```
Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (2094080 px). Occurrences of will-change over the budget will be ignored. osu

Source map error: request failed with status 404
Resource URL: https://osu.ppy.sh/js/app.js?id=d5faf0c2b23615de2d1c
Source Map URL: app.js.map[Learn More]

Source map error: request failed with status 404
Resource URL: https://osu.ppy.sh/js/react/profile-page.js?id=60fd62cf4adcc45674b9
Source Map URL: profile-page.js.map[Learn More]
```
Issue occured on Firefox 66.0.1 (64-bit)

Screenshot:
![image](https://user-images.githubusercontent.com/49334335/55666325-da802e80-5812-11e9-8f7d-d896742ceeb4.png)

**Comment by notbakaneko** [comment]
Browsers don't try to load source maps until dev tools are opened, and source maps are not available on production.
