### ISSUE TITLE
Default beatmap search should probably include loved category

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#4314]
Feels a bit weird that it doesn't, as it doesn't really mention anywhere that it's being filtered down and looks like it's just failing to match.

![image](https://user-images.githubusercontent.com/191335/55767762-31a52e00-5ab5-11e9-922e-2974f2eb2f24.png)

![image](https://user-images.githubusercontent.com/191335/55767782-441f6780-5ab5-11e9-9352-d787883187c7.png)

**Comment by notbakaneko** [comment]
It's also weird if it's included in the default search and then doesn't show up in the more results listing since the UI only allows selecting a single category

**Comment by peppy** [comment]
The default should probably be a group category called "Has Leaderboard" to resolve this. Ranked / Qualified / Loved could all be other selectable choices.
