### ISSUE TITLE
Add beatmap packs sorting

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#4321]
Add an ability to sort beatmap packs alphabetically, by author and date

**Comment by peppy** [comment]
Not sure if this is a direction we want to go, nor if it would be used by many. Can you explain where this requirement came from?

**Comment by TPGPL** [comment]
I thought it might be useful as for example Anime Packs arent available on the same page and you have to search for them

**Comment by cl8n** [comment]
I think this is covered by https://github.com/ppy/osu-web/issues/4247 then, if they're grouped I would expect anime to be one of the groups under themed

**Comment by TPGPL** [comment]
think so
