### ISSUE TITLE
Multiplayer match not loading content

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#4322]
https://osu.ppy.sh/community/matches/50870003

There's definitely database entries for this match, but it doesn't show anything when visiting the site.

**Comment by cl8n** [comment]
seems like yet another case of invalid/missing user country

**Comment by WalterToro** [comment]
Probably duplicated of #4134

**Comment by nanaya** [comment]
Yeah, specifically user Nycous (id 14247194).
