### ISSUE TITLE
Change username priority in the profile URL

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#4333]
https://osu.ppy.sh/users/2837500
https://osu.ppy.sh/users/888

For example you can't access user with ID 888 by entering the URL, because there's an user with the nickname `888`

Solution: Increase priority of user ID over user nickname while searching by URL

**Comment by cl8n** [comment]
this is already how it works, there just is no 888 (I think?)

example:
https://osu.ppy.sh/users/410
https://osu.ppy.sh/users/2884569

**Comment by TPGPL** [comment]
oh my bad then
