### ISSUE TITLE
Don't show notifications for forum threads set to not show notifications

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#4334]
![image](https://user-images.githubusercontent.com/33286824/56081649-9fb36300-5ddd-11e9-9d60-f758cb958406.png)
It's really bothersome to get spammed in the web notifications about threads where the notifications are set to be _off_

I assume it's because this option is still just for email notifications as it has been before, but now it's confusing, misleading, and there doesn't appear to be a way to turn website notifications off for bookmarked threads.

**Comment by dorothy3242** [comment]
![image](https://user-images.githubusercontent.com/33286824/56224194-2dd95480-603d-11e9-848a-2907d3d4887d.png)
still happening

**Comment by peppy** [comment]
May be due to the deploy process failing for the last few days.

**Comment by dorothy3242** [comment]
This is still happening and it doesn't appear (to me) to be the deploy process as I checked and later commits merged into web-release are definitely working, but this is not.
