### ISSUE TITLE
Freshly downloaded Beatmaps need updates

### ISSUE THREAD

**Issue by FlyingStefan** [ppy/osu-web#4335]
Been a thing for very long time and I don't really know if that belongs here so please excuse me if I made something wrong. The beatmaps in this list provide at least one difficulty that requires an update before they're listed as ranked in-game. That happens to few of them that are downloaded directly from the listing (beatmap packs are getting fixed currently to offer fixed versions immediately.)

Ni-Ni - 1,2,3,4, 007 [Wipeout Series] (http://osu.ppy.sh/s/3) - "-Breezin-" requires update.
Maeken Trance Project - Koi no Maiahi (http://osu.ppy.sh/s/32) - all difficulties require update.
Caramell - Caramelldansen (http://osu.ppy.sh/s/42) - difficulty requires update.
The Chemical Brothers - Galvanize (http://osu.ppy.sh/s/62) - difficulty requires update.
Sukima Switch - Zenryoku Shounen (http://osu.ppy.sh/s/83) - Insane difficulty is missing, 'Original Insane' difficulty exists instead.
South Park - Let's Fighting Love! (http://osu.ppy.sh/s/124) - "Easy" requires update.
tiger YAMATO - tiger yamato (http://osu.ppy.sh/s/146) - "Hard" requires update.
Katrina & The Waves - I'm Walking On Sunshine (http://osu.ppy.sh/s/157) - difficulty requires update.
SEAMO - Mata Ai Mashou (http://osu.ppy.sh/s/167) - difficulty requires update.
The Pillows - All The Way To The Edge Of This World (http://osu.ppy.sh/s/215) - "Hard" requires update.
Gummibar - Gummy Bear Song (http://osu.ppy.sh/s/913) - completely broken download but can technically be played.
AA-Chino - Mighty Buddy (http://osu.ppy.sh/s/703) - all difficulties require update.
KOTOKO - Daily-daily Dream (http://osu.ppy.sh/s/14295) - "yongtw123's Ojou-sama" appears as unranked but requires an update. Has no music.
ROOKiEZ is PUNK'D - IN MY WORLD -TV SIZE OPENING VER.-
(https://osu.ppy.sh/beatmapsets/170650) - all difficulties require update.
ISHIDA YOKO - COLORFUL BOX (https://osu.ppy.sh/beatmapsets/245906) - "Easy" and "Insane" require update.
Akatin - sugoi Fukkireta wwwww (https://osu.ppy.sh/beatmapsets/324792) - "Under Orion" requires update.
Raujika - Lost Imagination (https://osu.ppy.sh/beatmapsets/328691) - all difficulties require update.
cYsmix - Manic (https://osu.ppy.sh/beatmapsets/362460) - "Insane" requires update.

more to add

**Comment by peppy** [comment]
I thought we already fixed this once..

**Comment by cl8n** [comment]
Killer - Zui Qing Feng (https://osu.ppy.sh/beatmapsets/238692) requires updates for both diffs

**Comment by Joehuu** [comment]
Fixed, see https://github.com/ppy/osu/issues/25078#issuecomment-1790107365.
