### ISSUE TITLE
Join date on forum posts is aligned wrong

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#435]
Shouldn't be bottom anchored.

![](https://puu.sh/nMWVx/3029801280.png)

**Comment by nanaya** [comment]
this should go to @arflyte since that's how he designed it ¯\\\_(ツ)_/¯

**Comment by suzumotoHikari** [comment]
Note: You can ignore this reply if this is against on the flyte's design.
Also, i am newbie on this kind of development especially coding less. :)

On the file `forum-post.less` on the line 284, on `&__info-panel-extra`, i just changed the value of `justify-content` to `initial`. Rather, removing the `justify-content` might work as well.

Also, you can remove it. As a probe, i had an image below showing the output.
Before i changed the `justify-content` value to `initial`: http://puu.sh/pEowt/3e41469534.PNG
I changed the `justify-content` value to `initial`: http://puu.sh/pEoyv/961b58c0c9.PNG
