### ISSUE TITLE
Notification for comment replies

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#4355]
1.) replies to your own comments should send you notifications by default. (maybe be disable-able). helps to continue a conversation.

2.) option to watch the comment sections for specific beatmaps and news articles. maybe could be done using a bookmark feature like forum threads, or a watch feature like beatmap discussions. then any comments posted on the watched beatmap/news article will send you notifications.

reasoning for b: as a mapper i want to know when people comment on stuff without having to manually check every map i have on a regular basis. please make my dreams come true. let me watch the comments for beatmaps. thank you have a nice day

**Comment by nanaya** [comment]
Updating title as the other part is done.
