### ISSUE TITLE
Collapsed beatmap difficulties should be hoverable when there is only one of a single mode

### ISSUE THREAD

**Issue by Poyo-SSB** [ppy/osu-web#4362]
![image](https://user-images.githubusercontent.com/1782081/56465435-b6475480-63b1-11e9-8799-db4b3e582bde.png)

[This beatmap](https://osu.ppy.sh/beatmapsets/447151) has several difficulties across multiple modes, and thus the icons are collapsed. I would expect that hovering over the osu!standard icon would show information for the corresponding difficulty because it represents only a single difficulty, but it doesn't.

**Comment by Joehuu** [comment]
May be resolved with #2632.

**Comment by Joehuu** [comment]
Has since been resolved with the new design.
