### ISSUE TITLE
Nothing showing up on beatmap page or profile

### ISSUE THREAD

**Issue by BrainMiner** [ppy/osu-web#4369]
When i try to go on any beatmap or on my profile (or anyone's) It just simply shows a blank screen with only the background there. Any help?
![Screenshot_1](https://user-images.githubusercontent.com/49865550/56496681-4c829400-64f2-11e9-943d-5b9cc0d308ce.png)

**Comment by notbakaneko** [comment]
what browser are you using?

**Comment by BrainMiner** [comment]
Chrome

**Comment by notbakaneko** [comment]
Is it still missing?

**Comment by BrainMiner** [comment]
Still nothing there @notbakaneko

**Comment by notbakaneko** [comment]
@BrainMiner can you send an email to baka@nekonyan.net so we can communicate on this directly?

**Comment by BrainMiner** [comment]
Got it, I'll email you as soon as possible

**Comment by notbakaneko** [comment]
This was resolved
