### ISSUE TITLE
set bookmark with mail in help forum automatically

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#4379]
some people ask for help, we are trying our best and they disappear forever, probably not used to forums and never finding their thread again. if we comment they could get poked with an email + notif in forum at least. someone new who is not familiar with forums probably wont set the subscription. 

besides this, even if you just commented a thread to help someone it would be nice if its automatically bookmarked too. atm we are used to check the threads all the time if they replied to us, but it could be simpler in the future (getting a notif?)..

**Comment by E223** [comment]
I think your proposal in #4332 would be a much better way of achieving what you want with this proposal. With that, one could "poke" the person that posted the topic, which would in turn notify them. 

I disagree with automatically bookmarking threads in Help. While it might be useful for people that post and then forget about their post, people who comment in these threads _generally_ tend to be slightly more knowledgeable about the site's functionalities, and can opt-in to receiving notifications for replies if they choose to. If anything, this should be a toggleable setting in my opinion.

**Comment by Lyawi** [comment]
hmm, toggleable sounds ok to me, i wanna follow threads i replied to, without setting that bookmark all the time. an email all the time is kinda annoying, but i can live with it for now. if its toggleable, maybe it should affect the whole forum instead of help only then, tbh

**Comment by peppy** [comment]
I think this is a pretty good idea as a forced default for help threads.

**Comment by Flanster** [comment]
#4332 is already plenty as mentioned above, they can get a notification from **quoting their reply** and/or **mentioning their name**. Autobookmarking everything sounds bothersome.

**Comment by cl8n** [comment]
I would say the opposite Flanster, because why would you post a thread if you didn't want to read the replies to it (on any forum, not just Help)? I don't think I've ever posted a thread without bookmarking it immediately after, can you explain why that would be a bothersome feature

**Comment by Lyawi** [comment]
in some cases you dont even quote if its only one question, and especially if youre replying to this thread the first time. lets take https://osu.ppy.sh/community/forums/topics/899476?start=7057436 as a example. i can understand the notifs could bother people that use the forums, but i do too and i would find it helpful. if its toggleable it should be a thing? and only then. just my opinion

**Comment by Flanster** [comment]
> I would say the opposite Flanster, because why would you post a thread if you didn't want to read the replies to it (on any forum, not just Help)? I don't think I've ever posted a thread without bookmarking it immediately after, can you explain why that would be a bothersome feature

Because I do the opposite, I've barely needed to bookmark anything as I can keep track of it.

**Comment by Lyawi** [comment]
the only thing i assume that could get annoying is getting spammed via email. in one hand it could be useful for newbies, in the other hand its annoying for people that use the forums regularly. in this case @mentions make sense again (they should get added anyway)

ahhh. 😫

**Comment by cl8n** [comment]
you only receive one email per thread (until you read it again)

**Comment by cl8n** [comment]
can be closed ^
