### ISSUE TITLE
Add a way to view read notifications

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#4390]
new notifs can be bold, already clicked ones could be regular

would showing all notifications require another page?

**Comment by peppy** [comment]
Are you saying you want to manually clear notifications, rather than have it occur on clicking them?

**Comment by Lyawi** [comment]
just having a notification history - new notifications could be **bold** until you clicked on them. atm they just disappear from the notif box after you clicked on them :(

**Comment by peppy** [comment]
I believe notification history is coming... @nanaya @arflyte ?

**Comment by cl8n** [comment]
I think this should be higher priority, especially considering the new modding notifications for BN/NAT

**Comment by nanaya** [comment]
Resolved by #5449.
