### ISSUE TITLE
Don't show "last seen" on user card when user is online

### ISSUE THREAD

**Issue by VenixOSU** [ppy/osu-web#4397]
![image](https://user-images.githubusercontent.com/30481900/57042662-a78c5780-6c65-11e9-8bfc-c9a8043bf401.png)
looks quite confusing to me, would make more sense to hide it when user is online, I think.

**Comment by peppy** [comment]
Agree

**Comment by 5unf10wer** [comment]
i think this should be applied to the profile page as well
please just show on their profile page that they are online
