### ISSUE TITLE
Group listings need additional information per user displayed

### ISSUE THREAD

**Issue by Loctav** [ppy/osu-web#4398]
Right now, the current group listings only show the a plain list of the current group's members.

What is missing is a way to include necessary information to each group member, which could vary from group to group, e.g.:
* The Beatmap Nominators will require the information whether or not they are a Nominator on trial (on probation) or a full Nominator and what game modes they are responsible for
* Nominator Administrators (formerly Quality Assurance Team) will need to a display to show their responsible game modes
* (optional) Global Moderators could benefit from a field where they could show all their spoken languages

The way of implementation could be a free input note field or actual static selectors dependent on the group, but I'll leave this choice to somebody else, obviously.

**Comment by peppy** [comment]
This should definitely be considered to be part of the friends list implementation, as it should 101% use the same page design and code.

**Comment by Joehuu** [comment]
Seems to be all implemented instead the "optional" one. Listing spoken languages can benefit all user groups, though.

**Comment by peppy** [comment]
Think it's safe to close this. I doubt we'll add spoken language any time soon.

**Comment by Joehuu** [comment]
Maybe adding it as a profile setting to not over complicate the groups page? Still want to remove the listing of users in the group wiki pages (e.g. https://osu.ppy.sh/help/wiki/People/The_Team/Beatmap_Nominators#team-members).

Or just require group members to list their languages in their me! tab instead? But still, both proposals require an extra step to view individual profiles just to get their languages.
