### ISSUE TITLE
Dusk tests time out sometimes

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#4403]
I don't know why/how but you can see in #4393 one of the route tests timed out, then all tests passed when running again with no changes

**Comment by notbakaneko** [comment]
Travis does that; it's probably not an issue unless it keeps recurring too often

**Comment by peppy** [comment]
Can we not add a retry step?

**Comment by notbakaneko** [comment]
that just adds false passes and adds more uncertainty into the results of the test suite. Visible random failures are better than masking potential failures.

**Comment by peppy** [comment]
That's fine if this is implying there's an actual issue (is there?). If not the test procedure should probably be amended so it doesn't confuse contributors.

**Comment by peppy** [comment]
Same thing? https://travis-ci.org/ppy/osu-web/jobs/530568334

**Comment by nanaya** [comment]
Haven't seen this issue anymore for a long time now.
