### ISSUE TITLE
show only one previous name

### ISSUE THREAD

**Issue by tsunamisittich** [ppy/osu-web#4406]
whats the reason all old names get shown now? people usually got their reasons why they changed it, for example: 
- embarrassing name made in the past 
![tAjHMU9](https://user-images.githubusercontent.com/32525896/57195187-0dbbf780-6f50-11e9-8d16-f1145f11aef0.png)
- transgender reasons (they dont really wanna get reminded)
- "fresh new start" in the game, when past wasnt really nice

people usually dont care about the old names from others, please dont show them. if you are still interested to know you can ask the person in private chat?
theyre also expensive, people dont change their names that often that it needs a whole list

showing latest name seems enough.. maybe also only for a short time (1-2 months)?

**Comment by dorothy3242** [comment]
old names can be removed from the history by contacting osu! support.
Some people do name change multiple times but want to be recognizable by the old names, which is why showing all names by default is beneficial.

**Comment by Loctav** [comment]
People can request to have their previous names removed by contacting the osu! support, I think? However, for the sake of transparency, hiding all previous names doesn't seem wise and it also assures that content created under an old name still gets properly attributed to the correct person, as the previous aliases are known to everybody.

**Comment by Lyawi** [comment]
lol. people/someone told me the support wont remove older names.... idk who it was. sorry then!

**Comment by InvisibleSymbol** [comment]
How about letting users hide their old name after a time span (let's say 180 days)? Having the option would be nice. Nobody knows my old names, and they are just annoying to have on my profile.

**Comment by TPGPL** [comment]
there could be an option in settings giving an ability to hide proper nicknames

**Comment by Lyawi** [comment]
> there could be an option in settings giving an ability to hide proper nicknames

this sounds great. we wouldnt need to contact the support, we wouldnt need to have a time limit, we can decide ourself which names should be visible (if any)

**Comment by peppy** [comment]
It's so you can find people across username changes. It's also the reason username changes exist (I wouldn't allow them if there was no easy way to track backwards through changes).
