### ISSUE TITLE
UK World Cup Supporter Banners Don't Show on New Site

### ISSUE THREAD

**Issue by ControlPro2** [ppy/osu-web#4407]
Although the World Cup Supporter Banners do work on the old site, they don't seem to be working for me on the new site. I paid for the UK Supporter Banner to be specific.

![Screen Shot 2019-05-05 at 15 03 24](https://user-images.githubusercontent.com/40320474/57195417-0bef3580-6f4a-11e9-9520-d5c741710167.png)
![Screen Shot 2019-05-05 at 15 03 29](https://user-images.githubusercontent.com/40320474/57195421-190c2480-6f4a-11e9-803a-101497a6e3d9.png)

Looking at the link on the new website, it looks like the link to preview the image says 'GB' instead of 'UK' lol. 
Link on the website: https://assets.ppy.sh/tournament-banners/official/twc2019/profile/supporter_GB.jpg
Correct link: https://assets.ppy.sh/tournament-banners/official/twc2019/profile/supporter_UK.jpg

**Comment by peppy** [comment]
Resolved, thanks.
