### ISSUE TITLE
Featured Artist beatmap pack category

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#4408]
rather than splitting featured artist packs between the "theme" and "artist/album" categories, for the future it'd be a good idea to add an additional "featured artist" map pack category.

This is because as the mappers' guild and featured artist projects grow, there's gonna be lots more of these packs, and splitting them between the already existing categories is potentially confusing.
![image](https://user-images.githubusercontent.com/33286824/57204126-9607c000-6f83-11e9-8cd1-e7e9f909f1e8.png)
![image](https://user-images.githubusercontent.com/33286824/57204130-9d2ece00-6f83-11e9-9854-91766a6ea4d6.png)
Like it already is a bit confusing cause just 2 packs are in a different category from the rest.

This would also be fantastic because then we can look into setting up packs that'd cover all ranked maps of licensed featured artist songs, even outside of those tied to medals. It'd serve as a good way organize, find, and dl featured artist maps using the current system until https://github.com/ppy/osu-web/issues/3777 sees implementation.

edit: also i do believe this requires old web implementation so i hope ppy reads this

**Comment by FlyingStefan** [comment]
Please make this happen. ID could be F (like how we have T for theme and A for artist)

**Comment by peppy** [comment]
cc @Ephemeralis

**Comment by Ephemeralis** [comment]
Would fully support this, especially if it's listed as the primary view when opening the beatmap packs page on both web-10 and osu-web for the first time.

Changing pack suffix like Stefan mentioned sounds like it'd work pretty well.

**Comment by dorothy3242** [comment]
Any chance of this happening sometime soon? It'd be good QOL now that there's 20+ associated packs and medals spread throughout the theme and artist sections :o
