### ISSUE TITLE
Probation BNs cannot post in Beatmap Management 

### ISSUE THREAD

**Issue by celerih** [ppy/osu-web#4414]
This forum https://osu.ppy.sh/forum/115 exists for general BN discussions and such. But since the split with the new usergroup, https://osu.ppy.sh/groups/32 some members are not able to reply to threads. This has been confirmed by 2 probation BNs

**Comment by Cynplytholowazy** [comment]
Screenshot here: https://cdn.discordapp.com/attachments/316154420591067136/575691572297859086/unknown.png

**Comment by peppy** [comment]
Please check and confirm it's working now (prefer you check on new forums).

**Comment by celerih** [comment]
Just checked with a probation bn and they were able to post (checked on new forums). Thanks for the fix
