### ISSUE TITLE
F as score-rank icon if you have rank D ingame

### ISSUE THREAD

**Issue by Emy** [ppy/osu-web#4420]
I recently noticed that the score-rank for rank D maps doesn't match with the rank that's displayed on the website. I don't know if this is intentional or not and I also couldn't find any information about it.

![wrong-score-rank-icon](https://user-images.githubusercontent.com/2758573/57381347-03e20080-71ab-11e9-9472-cc2550f5e862.PNG)

I tracked down the potential issue and found this to probably be the culprit of the mismatched score icon:

https://github.com/ppy/osu-web/blob/master/resources/assets/less/bem/score-rank-v2.less#L44

If this is indeed a bug I'd like to submit a pull request in which I change the score to display the D now and include the F icon for the css `class  score-rank-v2--F` like the others above.

**Comment by peppy** [comment]
@arflyte state intention
