### ISSUE TITLE
Profiles showing different Rank than Perfomance Ranking Table

### ISSUE THREAD

**Issue by noelli** [ppy/osu-web#4428]
Hey there,
i don't know if this is a known bug, but at least my search here showed nothing.

If i look into the Performance Ranking everything seems fine.
But as soon as i look into the Profiles of the Top-Ranks they are Different, and not only somewhat shifted, but sometimes duplicates.

Here is a Comparison between Profile and Ranking-List Display as of five minutes ago:

List-Rank | Name            | PP        | Profile-Rank 
---------- | ---------------|---------|---------------
`#1`           | Klug               | 15.559 | `#2`
`#2`           | WalkingTuna | 15.496 | `#2`
`#3`           | idke               | 15.410 |  `#4`
`#4`           | Mathi            | 15.055 |  `#4`

The PP difference is quite obvious, also PP-Values in Profiles and Listing match, so i'm wondering what might cause this issue?

**Comment by peppy** [comment]
This is probably due to caching for different systems. When showing results in a list, more accurate ranks can be used, while when showing ranks of individual users, a cached value must be used (it is computationally expensive otherwise).

This should recover within hours (maximum 1 day).
