### ISSUE TITLE
Weird notification title truncation

### ISSUE THREAD

**Issue by GSculerlor** [ppy/osu-web#4442]
![Expanded](https://gsculerlor.s-ul.eu/T3NSU0Rm)
![Collapsed](https://gsculerlor.s-ul.eu/baauzXaC)

Not sure this is intended or not, cause looks like it's only take the last line

**Comment by nanaya** [comment]
Which browser is that?

**Comment by GSculerlor** [comment]
Chrome 74.0.3729.131

**Comment by GSculerlor** [comment]
![gif](https://gsculerlor.s-ul.eu/unP7spjG)

Quick check not sure this is correct or not, but probably it truncate the text until it found `|` character

**Comment by nanaya** [comment]
Please check again with latest update. Also are you using some kind of custom user styles?

**Comment by GSculerlor** [comment]
Fixed with latest notification update. And I'm not using custom style (I don't even know there is one)
