### ISSUE TITLE
Show current difficulty in navigation bar in Modding v2

### ISSUE THREAD

**Issue by Kibbleru** [ppy/osu-web#4443]
So, sometimes when you click a modding v2 link (say to check a report) you will get linked directly to the post, and you have to scroll up to check which difficulty the post is referring to.

Can we add the difficulty into the navigation bar or something?

<img>https://i.imgur.com/wny6rWE.png</img>

**Comment by cl8n** [comment]
or maybe replace "This difficulty" with the name of it

**Comment by Kibbleru** [comment]
That's a great idea actually

**Comment by arflyte** [comment]
New design modding page changes will include ways to change the current difficulty with ease.

**Comment by cl8n** [comment]
the new design doesn't indicate which blocks should stay pinned when scrolling down, or if/how their styles would change. it doesn't seem like this issue was addressed

**Comment by peppy** [comment]
@arflyte can you advise on this one? do we have the new designs in figma showing how this will work?

**Comment by arflyte** [comment]
![Figma_210713-195408](https://user-images.githubusercontent.com/3632750/125440141-eb48823d-70b2-4aa8-8a7a-70ddd6341135.png)
This sticks to the top

**Comment by nanaya** [comment]
The original issue has been resolved ("this difficulty" changed to the name)
