### ISSUE TITLE
Add OP indicator in forums

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#4447]
of course we got used to it now without a star, its still ok to handle without... but especially in help forums its sometimes confusing when someone else is replying with their other issue. To get a better view a little star could already help out.

just for imagination, my edit skills arent good
![nzwr6vA](https://user-images.githubusercontent.com/32525896/57606402-183a4a80-7569-11e9-8146-5e654212d384.png)

**Comment by Flanster** [comment]
You mean an OP indicator? I've seen this before on other forums
![](https://flan.s-ul.eu/52BOaQUi.png)

Can be implemented in a similar manner.

**Comment by tsunamisittich** [comment]
ah ive only seen it as a star showing up 😂

**Comment by arflyte** [comment]
Topic Starter indicator for New Forum Design 
![Photoshop_190517-120020](https://user-images.githubusercontent.com/3632750/57900349-72098000-789b-11e9-80c4-e2ed5fac22c5.png)

Topic Starter indicator for Current Forum Design 
![Photoshop_190517-120037](https://user-images.githubusercontent.com/3632750/57900352-73d34380-789b-11e9-9ddd-ce068428019b.png)

**Comment by TPGPL** [comment]
should unassign?
