### ISSUE TITLE
Best Performance Visual Bug on Profile Page

### ISSUE THREAD

**Issue by KSSidll** [ppy/osu-web#4455]
![Przechwytywanie](https://user-images.githubusercontent.com/43550531/57795321-f649ef00-7745-11e9-8878-4143f09b7306.PNG)
![Przechwytywanie1](https://user-images.githubusercontent.com/43550531/57795350-04980b00-7746-11e9-92ad-25a6b7c641ec.PNG)

As can be seen Foreground Eclipse - From Under Cover play is missing on new page

What happened before bug was observed
1. Played the map..

2.  Couldn't see the pp worth of the play on page that shows up when you finish map ( exactly as happens when the score is lower than best play on same mods ) - play was visible on Recent Plays tab but it didn't show how much the play was worth

3.  12 minutes later ( just after playing next map ) got the pp and the play was updated on Recent Plays tab. Now insted of  ' - ' you could see actual worth of the play
But it seems as if Best Performance wasn't updated and the play wasn't visible nor is after 24 hours

Edit : I forgot to write that Show More button is also missing

That's all I noticed..  Can't help more than that but I hope that this info helps

**Comment by Joehuu** [comment]
Can be closed as this is resolved and also not an `osu-web` issue.

**Comment by KSSidll** [comment]
Thank you for reminding me about it
