### ISSUE TITLE
[Modding] Need a general section per-difficulty

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#447]
As people have pointed out in feedback, we need the ability to post "general" non-timestamped comments on a per-difficulty level.

**Comment by nanaya** [comment]
the backend is relatively easy

**Comment by Ephemeralis** [comment]
This probably needs to go in before we can swap over fully. It's a very requested feature from the people testing the system.

**Comment by Ephemeralis** [comment]
This exists as of a few weeks ago.
