### ISSUE TITLE
Search (and redirect) for users via previous usernames

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#4471]
Until somebody else claims a username, old usernames should easily redirect to the user who had them previously.
For example, if you put /users/oldname , it should redirect to /users/newname , or if you put oldname in the user search, newname should be a result. (maybe with something added to the user card, like was: oldname in small font to make clear why they are a result)

This would be to make finding users even after they change names easier.
It is especially relevant when looking at maps who say "GD by blah" but you can't find who blah is, because the mapper didn't link the userpage by id number, and blah changed their name!

URL redirects should be so long as nobody else takes the old nickname. The search results should be permanent except for cases where support manually removes names from a user's name history.

**Comment by peppy** [comment]
I swear we discussed making this happen (and already had an issue for it)... but I can't find it.

Completely agree this should be a thing, though.

**Comment by dorothy3242** [comment]
May be thinking of https://github.com/ppy/osu-web/issues/4050 which is part of the same problem (old profile links breaking after rename) but not as comprehensive
