### ISSUE TITLE
osu!mania number of key website search

### ISSUE THREAD

**Issue by Killertom63** [ppy/osu-web#4472]
On the website you have a lot of search options, but not one for how many keys on osu!mania. 

I only play 4k, and I assume there's a lot of people who only play 5k, 6k, 7k, etc. So would be nice if we could have a search that you could say "Only show beatmaps that have 4k" for osu!mania on the website.

I spend longer looking for 4k songs at this point than actually playing songs haha.

Thanks guys
<3 Tom

**Comment by Meandres** [comment]
Hi there.
I'd like to help with this issue. Thing is, if I trust the file presented here : [https://github.com/ppy/osu-api/wiki] the JSON file returned by the API doesn't contains informations regarding the number of keys of the map. I tried to look at the files from this repo to see whether or not this information was actually stored somewhere or not, but couldn't find anyting that seemed interesting.
But the game (at least stable, havn't tried with lazer) displays this information when browsing mania maps. So i'm really confused. 

Can someone hint me to where I could find relevant files of informations ?

**Comment by peppy** [comment]
I don't believe it is stored for converts, but Circle Size can be used for this purpose otherwise (`osu_beatmaps.diff_size`)

**Comment by notbakaneko** [comment]
https://github.com/ppy/osu-web/pull/7300
