### ISSUE TITLE
First join event is not logged in tournament matches

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#4474]
for example this match doesn't show that "death grips" joined at the very beginning https://osu.ppy.sh/community/matches/51943346

**Comment by peppy** [comment]
Are you seeing this on a regular basis (ie. is it always missing one join event at the beginning)? Was this during a peak time where it could have been a bancho-side issue?

**Comment by cl8n** [comment]
I think it might be that the first join is never being logged, based on these other games held at the same LAN event (not 100% sure that the unlogged join was always the first player, but that seems likely)

https://osu.ppy.sh/community/matches/51945087
https://osu.ppy.sh/community/matches/51943219
https://osu.ppy.sh/community/matches/51947819
https://osu.ppy.sh/community/matches/51945563
https://osu.ppy.sh/community/matches/51944566

**Comment by peppy** [comment]
This is an edge case where the event was never actually sent because it assumed the person to creator the match was the person to join it (thus making it redundant, since a "created" line is already there).

I've fixed this at bancho's end for tournament matches. Should be deployed later today.
