### ISSUE TITLE
[Modding] Make post type buttons clickable

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#448]
Should be able to click these:

![](https://puu.sh/ofllN/d4392c35e2.png)

to change the post type in my opinion. If a timestamp hasn't been entered by the user, put a placeholder 00:00:000 for them.

**Comment by Ephemeralis** [comment]
I believe this is defunct as this element no longer appears to exist in the current iteration of beatmap discussions, having since been replaced with the timeline/general/general (all diffs) switch above the comment feed.
