### ISSUE TITLE
Modding Watchlist issue

### ISSUE THREAD

**Issue by Muy4** [ppy/osu-web#4488]
譜面を更新するたびにmodding watchlistに追加していたはずの譜面がwatchlistから除去されてしまいます
my map links disappears from watch list when update a map. 

更新前:
before update
https://puu.sh/Dw1Vt.png 
https://puu.sh/Dw1VK.png 

更新後:
after update
https://puu.sh/Dw1Yt.png 
https://puu.sh/Dw1YA.png

SSに載せた譜面以外にも他の譜面でも試しましたが同じ症状のようです
I have tried on other pending/wip maps
but happened same issue.

could you help me? thanks
https://osu.ppy.sh/community/forums/topics/911457

**Comment by peppy** [comment]
What version of osu! (client) are you using to upload the beatmap?

**Comment by Muy4** [comment]
I have tried on current Stable, beta and Cutting Edge
but happens this issue on all of versions.

**Comment by peppy** [comment]
Can you check the the checkbox is ticked in the BSS window?
![image](https://user-images.githubusercontent.com/191335/58234891-9d4c0d80-7d7a-11e9-89cc-714f25b74653.png)

**Comment by Muy4** [comment]
oh... actually it works!
thanks for the help :)

**Comment by peppy** [comment]
That's weird though, since it should reflect the correct state. I'll look into this further.

**Comment by peppy** [comment]
I've fixed this in the latest cutting edge build.
