### ISSUE TITLE
weird design at top pp play list (version of vertical website)

### ISSUE THREAD

**Issue by FlashlightXi** [ppy/osu-web#4490]
スクリーンショット | screenshot:
https://gyazo.com/8b57059026fa2cd440e057bf50e19e4a

問題 | problem:

文字が書かれている部分の背景が四角になっています。変だと思いませんか？
Background of this text became to square, I think it is weird.

消すか、角に丸みを付けたほうがいいと思います。
Delete this background or make this background rounded.

（雑な英語ですみません）

**Comment by nanaya** [comment]
That certainly looks like custom user styles. Please report that to whoever made that theme instead.

**Comment by FlashlightXi** [comment]
oops, sorry.
that was https://osu.ppy.sh/community/forums/topics/802445
