### ISSUE TITLE
Multiplayer match history links are brute-forceable

### ISSUE THREAD

**Issue by Trigonoculus** [ppy/osu-web#4491]
### Issue
Because multiplayer match history links are chronologically ordered, a dedicated user could easily abuse the osu! api to search for particular lobbies that have match data which are beneficial to them, particularly involving tournament play. I have been made aware that someone actually wrote a script in node/js to automate this.

### How this works from my understanding
Assuming that I am a player in a tournament, I can take beatmap IDs [from the mappool] or user IDs [of an opposing team member] and input it to the script. The script, when run, then finds me multiplayer matches which the map is played / the player is participating In, which gives me data to utilise (which maps are the opponents bad at? Pick that map!), resulting in me getting a slight advantage in my match against the opponents.)

### Impact
This has been an issue for a long time, however it has been recently popularised to some extent, people using it in team-based community tournaments. As players practice together before matches, a MP link is generated for their practice lobby. Those MP links are being easily found by opponents, using it to strategise their matches and revolving picks around maps that the opponents are bad at.

This *could* also happen during official tournaments too, as teams also practice on Bancho.

### Possible solutions
1. **Add a limit to how fast you can query for multiplayer lobbies using the API**
One issue with this is that if you know the start time of the lobby, you can just keep reducing the x in multiplayer/matches/xxxxxxx until you find what you are looking for.

2. **Private match history links**
For example, you could private multiplayer matches that you created using the "!mp make" command, to prevent abuse. Not sure how tedious that is from a development standpoint.

Not sure how much of this is actually an issue, but I am curious to hear the osu! team's thoughts on this. Please do not hesitate to ask if you have any questions, I am sure that there is people who are willing to chime in about this issue.

**Comment by peppy** [comment]
passworded matches should probably require a password to view (or logged in as a participant of the match).

**Comment by Negaosu** [comment]
> passworded matches should probably require a password to view (or logged in as a participant of the match).

either option could be cool, not sure how long either would take to code but the second one sounds cool because there'd be no way for the password to get leaked/only team members would be able to see the mp page no matter what

**Comment by DMills94** [comment]
Adding a password protection for just the browser page doesn't solve the issue as people can use the API to get match history. 

Unless you made passworded MP id's invisible to the API which doesn't seem a valid solution (as this would remove ALL passworded lobbies, you could perhaps create a way to privatise the MP link from inside the lobby (eg. !mp private) perhaps?

A lot of tournaments publicise their MP links in results for other people to manually view the match, this is just a slower way of doing what Trig has originally mentioned. But using it to find practice lobbies like for OWC does seem kinda bad

**Comment by abraker95** [comment]
The actual tournaments are passworded, so they would be affected by this too. That's an issue because their mp links are provided in the tournament wiki pages.

**Comment by Negaosu** [comment]
> The actual tournaments are passworded, so they would be affected by this too. That's an issue because their mp links are provided in the tournament wiki pages.

Wouldn't it be possible to just make passwording/privating/whatever optional in such a way that tournament matches don't have to be private, but practice lobbies that people make are able to be privated?
