### ISSUE TITLE
User card doesn't show anything about user group

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#4499]
![image](https://user-images.githubusercontent.com/191335/58362474-48bba600-7ed2-11e9-850e-df0ca2dcd16d.png)

I feel like there should be a way of confirming if a user is a dev or moderator as it is useful context. Probably should show title.

**Comment by VenixOSU** [comment]
Maybe I just don't get you, but isn't it same as https://github.com/ppy/osu-web/issues/4392?

**Comment by peppy** [comment]
Thanks, closing as duplicate.
