### ISSUE TITLE
User card/menu design

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#45]
Trialling some larger bounties. This one involves implementing a design concept fully.

![](http://puu.sh/jZttw/0d4f5faa35.png)

This is the user card and menu, which will appear when you click your avatar/username at the top-right of any page.

Requirements:
- Implement design with interaction logic (should appear and dim page when avatar is clicked).
- No need to actually connect up the data source; we need to do some further work for this.
- Follow existing styling naming standards.
- Reuse existing styles where possible.

**[Bounty](https://goo.gl/nFdoyI) offered**: 60

As per bounty guidelines, it is recommended that you claim this issue if you are serious about it.

Ask away for further clarifications.

PSD: http://puu.sh/jZtBI/2a69c21449.psd

**Comment by ThePooN** [comment]
Interesting. I may try to do it if I find enough time.

**Comment by claudiodekker** [comment]
Sign me up for this one, I don't care about the bounty.

**Comment by peppy** [comment]
On a semi-related note: I understand many people do not want financial compensation. That's why we are offering unique rewards (flare for your profiles etc.) which are only available by accumulating bounty. If I was you I'd start saving :).

**Comment by claudiodekker** [comment]
Alright, fair enough. Count me in, then.

**Comment by PieInOblivion** [comment]
This can be done in very simple JS, I'll see what I can throw together in my spare moments. (I understand you want it completed, not a half finished one)

**Comment by PieInOblivion** [comment]
[Re-Adding Comment]
I'll give it a shot. But question, when you say "No need to actually connect up the data source", why?
"we need to do some further work for this.", it would just be so simple to 'Get <a> text inside div 'nav-user-bar'' then paste that at the end of link "http://jizz.ppy.sh/u/" but JUST load the index.html and take the information from that. I don't see the need for another data source.

I recognize that my view is of no importance what so ever, I'm just babbling on wondering why, and I find it comforting to understand these sorts of things, especially coming from someone working on this project. So, if I may ask, why a different data source?

**Comment by peppy** [comment]
You might want to check the pull request above, where @claudiodekker has already submitted a completed implementation for this!

**Comment by peppy** [comment]
Increasing bounty to 100 due to the final complexity of the implementation and awarding to @claudiodekker. Thanks for your contributions! We still need to hook up the implementation before pushing out to the release branch, but that should happen this week.
