### ISSUE TITLE
Everything turns opaque to show background triangles randomly.

### ISSUE THREAD

**Issue by Hubza** [ppy/osu-web#4500]
Randomly while using the website i've had this happen to me, from using the search to beatmaps to user profiles, it happens all the time, and the more i interact with said page (until refresh) it gets worse.

https://i.imgur.com/PS9Hp6j.png this is the only image i have

I have no idea

**Comment by nanaya** [comment]
Is it with firefox? Is it with the latest version? Also make sure the graphics driver is up to date as well.

**Comment by Hubza** [comment]
Graphics Driver & Browser is up to date. - Its with Firefox, yes.

**Comment by Hubza** [comment]
https://i.imgur.com/uJqhiLD.png Happened again, this time it was after clicking on a profile and clicking back before the profile could load, going back to the beatmap page i was on and then everything broke

**Comment by peppy** [comment]
Is this still relevant? The design has since changed.
