### ISSUE TITLE
Add ability to click someones name in chat to go to their profile (web chat)

### ISSUE THREAD

**Issue by GrilledCheeese** [ppy/osu-web#4501]
I'd like the "Talking with username" to be clickable to go to their profile, either in a new tab or in the same tab.
random example of what i'm talking about:
[image](https://i.gyazo.com/6299e14155bfb94d19c99b7629a2f90c.png)
link to the chat:
https://osu.ppy.sh/community/chat

**Comment by peppy** [comment]
sounds logical. right now it's hard to get to a profile if the user has not yet replied.
