### ISSUE TITLE
Beatmapset discussion upvotes/downvotes should be shown on mouseover

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#4503]
Currently, accountability for beatmapset discussion upvotes/downvotes exists only in several buried modding activity displays, making them largely invisible to most users. 

This has created a scene where someone's direct accountability for artificially inflating another user's kudosu value is hidden, allowing for abuse scenarios to occur.

A simple solution to this is to display a mouseover list of users who have upvoted/downvoted a particular issue when hovering over either the upvote or downvote button for a few seconds. Usernames and profile links will suffice.

**Comment by dorothy3242** [comment]
Duplicate of https://github.com/ppy/osu-web/issues/1747 ? Aside from the inclusion of downvotes.

**Comment by peppy** [comment]
@arflyte probably need a design for showing this? something similar to the users-who-favourited-beatmap display maybe (hover only)

**Comment by JBHyperion** [comment]
Just wanted to bring forward from the duplicate issue #4504 that it might be helpful to filter suggestions by who up/downvoted, in a similar way to how we can filter suggestions by poster using https://hyperion.s-ul.eu/hix4uINF

I think the hover-over idea that currently works for beatmap favourites is a great idea, but something more large-scale that covers the whole discussion at once would be good to have also.
