### ISSUE TITLE
D-rank icons are barely visible

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#4515]
![](https://puu.sh/Dy7xx/606dbde061.png)

it's hard to see the text on the D-rank icons

**Comment by peppy** [comment]
I think we could probably change the hues of A (too bright) and D (hard to read text).

**Comment by arflyte** [comment]
![Figma_190528-113217](https://user-images.githubusercontent.com/3632750/58446620-4e1c2900-813c-11e9-8ae4-5d852d00941f.png)

**Comment by peppy** [comment]
Looking much better
