### ISSUE TITLE
Tournament banners blurry

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#4516]
normal:
![image](https://user-images.githubusercontent.com/191335/58446867-5e80d380-813d-11e9-83ec-1d6b080273e1.png)
hovered:
![image](https://user-images.githubusercontent.com/191335/58446871-60e32d80-813d-11e9-97c3-ef5b7ed25d31.png)

both are shocking.

[example user](https://osu.ppy.sh/users/9314998)

**Comment by nekodex** [comment]
Partially fixed by #4564 (for other people's profiles). A proper fix is forthcoming (that involves moving the spinner elsewhere)

**Comment by peppy** [comment]
Was the proper fix implemented already?

**Comment by notbakaneko** [comment]
It's blurry if you use safari and view it on your own profile; the spinner needs to be moved out of the header background to anywhere else that won't overlap with the banner. An option that was discussed was to move the spinner to the image selection itself where the checkmarks currently are

**Comment by peppy** [comment]
I guess that's a no, then. Should we leave this in the June milestone? Is it more effort than it's worth to fix?

**Comment by peppy** [comment]
Moving out of milestone as it is now limited in scope and only affects safari.

**Comment by nanaya** [comment]
Can use an update on this :thinking: it probably has been fixed thanks to the (not-so) recent header change.

**Comment by peppy** [comment]
Tested on retina and non, looks fixed 👍
