### ISSUE TITLE
Downloading beatmap issue

### ISSUE THREAD

**Issue by FAMossu** [ppy/osu-web#4518]
Whole discussion in this map
https://osu.ppy.sh/beatmapsets/852093/discussion/-/generalAll#/991204

So, I'm not entirely sure what's the cause of this issue but for some reason when downloading the .osz it (speculating that it might be a server-side issue when it was updated?) but when downloaded the .osz is only 419kb and triggers the corrupt/incomplete message in the client.

Tried extracting the .osz in the failed folder and I got this message: https://mystic.s-ul.eu/o7eWbGVS
the resulting extraction produced the two .osu files, a 388kb audio file that lasts only 15 seconds, and nothing else. I think the audio file itself is the issue but I'm not entirely sure what's wrong since I could download it just fine before it was qualified

Should probably be looked at just to see what's going on so it can be fixed. I tried downloading it multiple times and got the same issue, plus (even though it's a terrible source) the comments indicate that others are having issues as well.

**Comment by peppy** [comment]
Has the creator tried deleting their local submissioncache and resubmitting?

**Comment by FAMossu** [comment]
well even they trying it now, they can't 
the map is in qualified status at the moment
it's alternative methods solving this?

**Comment by peppy** [comment]
I've disqualified the beatmap. They can try again now.

**Comment by riunosk** [comment]
my osu folder doesn't have Data folder inside and i can't delete my local submission cache if i have any

**Comment by FAMossu** [comment]
it's actually hidden folder

**Comment by peppy** [comment]
All good?

**Comment by FAMossu** [comment]
fixed now
thank you!
