### ISSUE TITLE
Ability to edit posts

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#452]
as per title. not sure if they should be able to change the resolved state, though.

**Comment by nanaya** [comment]
missing the design :dancer: Or techincally I can just improvise one

**Comment by nanaya** [comment]
normal state

![](https://puu.sh/ofubq/fa1f4ef903.jpg)

on hover

![](https://puu.sh/ofuaM/6e1266e49d.jpg)

on hover for first post

![](http://puu.sh/ofuh3/cad038eb37.jpg)

editing & hovering

![](https://puu.sh/ofucA/1934956c93.png)

editing & mouse somewhere else

![](https://puu.sh/ofud6/d0e9f44a05.png)

hi @arflyte :dancer:
