### ISSUE TITLE
Add A Margin

### ISSUE THREAD

**Issue by hanafi121** [ppy/osu-web#4528]
It seems like this 
![tttt](https://user-images.githubusercontent.com/31497538/58669240-b13cd400-8365-11e9-9c7a-d3ac562fd4e1.JPG)

use padding if possible

**Comment by peppy** [comment]
What browser is this?

**Comment by hanafi121** [comment]
Google Chrome Version 74.0.3729.169

**Comment by nekodex** [comment]
I think this graph is being changed in the new design? ping @arflyte

**Comment by hanafi121** [comment]
in my opinion , beatmap status like "ranked" moved in bottom of title and stat are selected move upper

**Comment by nanaya** [comment]
Besides this being redesigned, the current one is already as intended.
