### ISSUE TITLE
Resolved state should be attached to each post

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#453]
Consider in a long thread, with the current implementation we won't know who is responsible for resolving/unresolving issues. In a case where disagreements are occurring, it will be unclear if there was contention in the resolved state throughout the discussion, which is probably something we want to see.

Should be visible on posts with a coloured bar @arflyte provide design plz.

**Comment by nanaya** [comment]
![](https://puu.sh/oguav/945d3470c3.jpg)

Hi @arflyte design plsthx
