### ISSUE TITLE
Link "Report a Qualified beatmap here!" on modding discussions

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#4536]
Finding this extremely important thread is completely unintuitive. It is currently located in a forum which currently has no function besides this thread. There is no indication on modding discussions or qualified maps it exists. You have to know where it is to know where it is.

It previously made sense because if you're reporting a qualified map, you're looking at a thread in the ranked maps subforum, then linking it in the report thread which is also in the ranked beatmaps subforum. With modding discussions this design is no longer true.

Easy fix:
On qualified beatmapsets, link to the thread in an obvious place on the modding discussions page.

**"Have an issue with this beatmap? Report it here! [Link]"**
Clicking the link would take you to the thread.
Ideally, it should also automatically fill in a beatmap link in a user's forum post to make the process easier.

**Comment by peppy** [comment]
Sounds like an important one to get addressed.

**Comment by notbakaneko** [comment]
This really should be using the existing method of reporting problems/disqualifying modding discussions, instead of a forum thread with posts that...link back to the issue in modding discussions?

**Comment by nanaya** [comment]
Maybe a listing of qualified maps with open issue so it's easier to check?

**Comment by dorothy3242** [comment]
bakeneko - The existing method of reporting maps /is/ the forum thread. Linking the forum thread would be using the current system? Unless I'm misunderstanding something.

nanaya - Listing of maps with open issues has the problem of hardly anyone can resolve issues on qualified maps, so qualified maps would basically end up permanently in this category until rank or dq. It could work if there's some way to mark them as checked/fine, so it'd be easier to focus on double checking maps that need attention. Otherwise it could get messy as there would be a lack of visible distinguished types of states. 

overall I guess changing the system other than originally suggested could use NAT and other community input too to make sure the solutions work for what's needed. My initial suggestion is just based off what seems simplest (I may be wrong) to improve on for now.

**Comment by nanaya** [comment]
>hardly anyone can resolve issues on qualified maps

Unless I'm missing something the only person who can't resolve issues on qualified maps is the map owner...? The reporter and moderators can still close them...?

**Comment by peppy** [comment]
Is this actually still relevant? Can't anyone report on the modding discussions page as mentioned above?

**Comment by dorothy3242** [comment]
Maybe not what the issue originally proposed but there needs to be something that
- makes reported maps visible in one place 
- ^ ideally alongside a summary of the problem that the reporter would submit
- keeps it intuitive to report maps for issues (easy to know the option exists)

**Comment by peppy** [comment]
Okay, so on further discussion it seems like this is the result of a missing feature in the modding discussion system that has never been requested. The forum thread looks like a manual workaround which shouldn't exist in the first place.

Let's fix this in a better way via #4784.
