### ISSUE TITLE
Allow double posting in the "Report a Qualified beatmap here!" thread

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#4537]
When filing beatmap reports, it is more organised to make one post per beatmapset. This makes it clearer when there are multiple different maps being reported, instead of potentially mistaking two reports of two separate maps for one long report.

Issue is, you can't double-post in this thread on the new website easily. You can on the old forum. This is discouraging to users checking a larger amount of qualified maps and reporting multiple. While disallowing double-posting  makes sense for most of the forums, it does not in this use case.

**It should be allowed to double-post on the new website in this thread for any user.**

**Comment by cl8n** [comment]
this doesn't seem hard to solve without double posting though, just use formatting to make it clear (spoilerboxes for details about each report if they're long? headers for each map ... idk)

**Comment by peppy** [comment]
I guess, but sounds very low priority. I'd sooner just move the reporting system away from the forum.

**Comment by Cynplytholowazy** [comment]
May want to have this fixed first before moving it away from the forum since there is some bot that works on each post of report and editing may cause reports being missed by beatmap nominators.

**Comment by cl8n** [comment]
are there any other topics that'd want this functionality permanently? if not, this should be pretty easy to add provided everyone's okay with having some temporary code around. could have the topics set with a dead phpbb property (`topic_bumped`?) so there's no worry about clean-up later

#4784 is in the September milestone but it doesn't look like anyone has started on it

**Comment by abraker95** [comment]
mafia subforum suffers from the lack of this.

**Comment by dorothy3242** [comment]
The issue opened is no longer relevant with the changes in the modding discussion report system pushed out. 

If there needs to be more discussion about having double posting in certain subforums, it'd be more appropriate to open a different issue for that.
