### ISSUE TITLE
Different beatmap leaderboards on homepage

### ISSUE THREAD

**Issue by mindmaster107** [ppy/osu-web#4542]
As generally discussed during the saturation of the top 5 most played "Popular Beatmaps" with farmy maps, there is some discussion to replace it with something else entierly.

While I don't agree with replacing it, having only one leaderboard to show off maps, apart from those newly ranked feels wrong, considering there is no inbetween.

A possible middle ground leaderboard is "Hottest Beatmaps", with the idea name and concept stolen from reddit. Each map would have its playcount logarithmed, and divided by time ranked, and would be put on the leaderboard to provide maps BOTH recently ranked and played.

This won't actually "fix" the concerns with "farmy" maps being unfairly promoted, but the point here is to not have a stagnant leaderboard, and have a natural way to cycle through maps.

**Comment by peppy** [comment]
This has been factored into the next redesign of the dashboard page. We will start introducing spotlights and other sources.

**Comment by nanaya** [comment]
Should be replaced with highest rated of ranked beatmaps within last month.
