### ISSUE TITLE
Suggested difficulty doesn't work for hybrids

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#4545]
When searching by suggested difficulty for taiko/mania/catch (I can't test osu since i'm unranked lol), it will include hybrid maps that also meet the star rating requirement.

eg: My suggested difficulty is 6.89* in ctb (way too high but that's another issue), these maps will show up in my results
https://osu.ppy.sh/beatmapsets/819149
Standard mode: 6.74*, Catch: 5.43*
https://osu.ppy.sh/beatmapsets/703957
Standard mode: 7.05*, Catch: 4.16*

edit: When the standard diffs are converted to ctb, they are still only around 5* which shouldn't show up

**Comment by notbakaneko** [comment]
memo: change index format to store diffs per mode instead of together
