### ISSUE TITLE
Future time scheduled events are wrongly written as "in X ago"

### ISSUE THREAD

**Issue by Zyfarok** [ppy/osu-web#4571]
For future events (like "X will be able to speak again in Y ago." in the screen provided here), the syntax is grammatically incorrect.

![image](https://user-images.githubusercontent.com/10669609/59471161-8ad56900-8e3a-11e9-9ca6-99aa94d0e77b.png)
The "ago" word should only be used for past events and not future ones. (while the "in" should be used for future events, but it was "hard-coded" here)

I guess you should probably implement the "in" as part of the function while you add the condition for the "ago", since you'll always (I think ?) want to either have a "in" or a "ago" in any case in function of the sign of the duration. (that would be good for scheduled events so that they are still displayed right after they happened, as long as it's not in a sentence where you'd also have to change the verb tense)
Otherwise you could also simply remove the "ago" and hard-code it when it's a past event instead like you do with the "in"...

P.S.:  English is not my main language, so correct me if I'm wrong.

**Comment by qcl12345** [comment]
Your local system time is probably incorrect. 

![](https://i.imgur.com/qEttvRC.png)

**Comment by Zyfarok** [comment]
My local system time is totally fine, but actually I missed something : it switches between "from now" and "ago" without reasons... When I load the page it displays "from now" and then switches to "ago", and then sometimes switches again later...

I would guess that there's two different scripts that tries to re-evaluate those duration value every now and then and that they actually both want to modify that value.

Environment : Firefox 67.0.2 on Archlinux (KDE).

**Comment by notbakaneko** [comment]
Some custom user styles are known to cause this

**Comment by Zyfarok** [comment]
Ok, sorry for bothering you guys, and thanks for your answer.
In my case, It's actually caused by "osuplus" in case you wanna know (https://github.com/limjeck/osuplus).
Gonna report that to him.
