### ISSUE TITLE
Screenshots uploaded to web not working

### ISSUE THREAD

**Issue by TobiasLeander** [ppy/osu-web#4584]
screenshots uploaded via **shift + 12** to the web currently isn't working and gives a white screen, gave it an hour before reporting and didn't see anything on osu! status.
![chrome_2019-06-18_23-55-30](https://user-images.githubusercontent.com/26700331/59722717-b08cb480-9224-11e9-8632-b2b4ab827493.png)

**Comment by TobiasLeander** [comment]
Seems to have been fixed now.

**Comment by peppy** [comment]
Thanks for reporting. I just resolved this.
