### ISSUE TITLE
Misspelling & Forgotten translation Japanese 

### ISSUE THREAD

**Issue by FlashlightXi** [ppy/osu-web#4592]
1. https://gyazo.com/fd5ede27cd3356558e223274b4caea64
4日後日 is wrong, 4日後 is right.
(also 後今から should be あと[後])

2. https://gyazo.com/bea63cb6fa085514d271f2ab4092db28
this pageを参照。 should be このページを参照。

**Comment by nanaya** [comment]
This is done through [crowdin](https://crowdin.com/project/osu-web). I've updated the lines though it may take a while before it's applied.
