### ISSUE TITLE
Replays of some top scores are not found only when downloading from API

### ISSUE THREAD

**Issue by naoey** [ppy/osu-web#4599]
The replay files of top plays on many maps return a 404 when requesting them through the API.

Example score:
```
https://osu.ppy.sh/scores/osu/2773395092/download
https://osu.ppy.sh/api/v2/scores/osu/2773395092/download
```

The first URL used on the website retrieves the replay successfully, but attempting to download it from the API returns a 404 with JSON containing an empty "error" key:
```json
{
    "error": ""
}
```

I haven't been able to identify any patterns to this behaviour. I came across many cases where top few plays on the leaderboard fail to download the replay and a few scores in between download successfully.

**Comment by notbakaneko** [comment]
Is it always the same score that fails?

**Comment by naoey** [comment]
Yes it’s always the same that succeed/fail.

**Comment by peppy** [comment]
Could you please try these again?

**Comment by naoey** [comment]
Tried about 6 different replays that were previously failing, they are working now 👍

**Comment by peppy** [comment]
Thanks! Was a permissions issue with the API deployment of `osu-web`.
