### ISSUE TITLE
Pulling only 1 commit?

### ISSUE THREAD

**Issue by MasterBugPatch** [ppy/osu-web#46]
For the last 45 minutes I've been trying to pull request just one commit, followed a lot of guides but just can't seem to get it.

This is my fork of osu-web: https://github.com/MasterBugPatch/osu-web

I'm trying to pull request only 4294e8258e927e646176ad991a44bb7d87000125 to here.

Anybody can guide me on how I would go about doing that?

**Comment by peppy** [comment]
You need to put it on its own branch first.

**Comment by MasterBugPatch** [comment]
@peppy I have tried putting it on one branch, cherry-picking, then forcing an update. I must be missing something or just not doing it right.

**Comment by TheHowl** [comment]
```
git checkout master
git branch MasterBugPatch/profile-preview
git checkout MasterBugPatch/profile-preview
git revert fdc8f1c2ae648852432603e8ef62956cbb4a9274 # Reverts the commit in your fork that you do not want to pull
git push origin MasterBugPatch/profile-preview
```

The commit you don't want to pull into the repo should be reverted, and you can do the pull request of that commit.

If you do not want to have those "merge remote tracking..." commits, then next time you do `git pull` remember to do `git pull --rebase`, or set it to always use rebase:

```
git config branch.autosetuprebase always
```

**Comment by MasterBugPatch** [comment]
@TheHowl I had a bunch of problems trying to do that, it was saying I wasn't merged up with the main branch, and more. So I just deleted the whole fork, then reforked it, commited the changes I wanted. Now I'll do that thing you said would not create commits for updating the fork, thanks ^.^, very helpful!
