### ISSUE TITLE
Being able to rate a beatmap on the website

### ISSUE THREAD

**Issue by Monsquid** [ppy/osu-web#4601]
Hello, 

It would be cool if we were able to rate a beatmap directly on the website, and not only on the pass screen.

![68747470733a2f2f692e6962622e636f2f4274764e5043632f436170747572652e706e67](https://user-images.githubusercontent.com/5892122/60303010-9db96480-9935-11e9-8fd7-b4e1f2f7c9f0.png)

It's not a big feature but I'm sure that more people would use this rating system if it was also available on the website (on the beatmap scores page). 

Thanks

**Comment by camellirite** [comment]
Sounds like a good idea as long as there's a check that ensures the users has passed one of the difficulties already.

Or maybe it's only on the pass screen because that's when the map has just finished and it's fresh in the player's mind. Could go either way

**Comment by peppy** [comment]
In an effort to reduce scope of the site, this will not be made available. That said, it should become easier to rate beatmaps in lazer.
