### ISSUE TITLE
Decreased visibility and quality font on Chrome

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#4616]
I noticed the font differs according to the browser you are using. Here are some examples (Chrome is left and Firefox is right):

![image](https://user-images.githubusercontent.com/19843905/60590275-dfb23280-9d9b-11e9-8f66-f01285153006.png)

![image](https://user-images.githubusercontent.com/19843905/60590390-26a02800-9d9c-11e9-9082-3b5a254ec541.png)

*tested on Chrome 75.0.3770.100 and Firefox Quantum 67.0.4*

**Comment by notbakaneko** [comment]
What OS are you using, and do you have any user styles installed?

**Comment by TPGPL** [comment]
Windows 10 and I think I have no user styles installed

**Comment by peppy** [comment]
Do you have cleartype forced off?

**Comment by TPGPL** [comment]
I checked and turning off cleartype and font smoothing doesn't fix it

**Comment by TPGPL** [comment]
it... fixed itself i guess?

![image](https://user-images.githubusercontent.com/19843905/65250290-a31de980-daf5-11e9-9660-35c2df65d5c8.png)
