### ISSUE TITLE
My map lost all hypes when I changed the files

### ISSUE THREAD

**Issue by Forsaiken** [ppy/osu-web#4617]
My map lost 8 hypes and I don't know why. 
I think that when I changed the files of my map, the hypes was gone, I just removed the background and put another. After this my hypes disappear. 

Map: https://osu.ppy.sh/beatmapsets/330827#osu/733041 

and please return my hypes.

I don't have screenshots of the 8 hypes, but I think I got the 8 hypes when the system has converted

**Comment by peppy** [comment]
Hey! Maps brought across from the old system can have incorrect hype counts in some cases. This is to be expected, please get some new people to hype your map!

**Comment by Forsaiken** [comment]
@peppy this happened yearsteday.

**Comment by peppy** [comment]
Yes, because you never got hype votes on the new system.
