### ISSUE TITLE
Chat Web Client does not make you clickable in the client-side

### ISSUE THREAD

**Issue by sr229** [ppy/osu-web#4629]
With the help of a few users, we determined that you are somehow "invisible" to the client users when you are using the web chat client to chat to a room. This causes confusion for some who wants to check who they are, friend, etc.

This persists in current version of Web Chat.

**Comment by peppy** [comment]
I can't understand this issue. Specifically the title (it reads very badly) and what a "client user" is, what a "web chat client" is etc.

**Comment by qcl12345** [comment]
I believe this is referring to the fact that users who chat through the [website](https://osu.ppy.sh/community/chat) (or lazer for that matter) are not viewable from the stable client, and thus their name can't be clicked on in game to bring up their usercard.

**Comment by peppy** [comment]
That doesn't really help explain things. There's currently no integration between the new and old PM system.

**Comment by sr229** [comment]
What @qcl12345 said, seems that anyone who uses the chat system in-website can not be viewed through stable @peppy

**Comment by nanaya** [comment]
Closing this as it's unclear. Please provide more details and screenshots and reproduction steps of the problem.
