### ISSUE TITLE
Failed To run docker

### ISSUE THREAD

**Issue by afichemist** [ppy/osu-web#4635]
![Screenshot from 2019-07-10 14-39-54](https://user-images.githubusercontent.com/52690797/60950143-c9b6eb80-a320-11e9-90e7-b384a7b4e5ba.png)
its like in terminal

**Comment by notbakaneko** [comment]
you need to have a `UID` set in your environment. https://github.com/ppy/osu-web/blob/master/SETUP.md#3-using-docker
