### ISSUE TITLE
Expose API for comments on beatmapsets and changelogs

### ISSUE THREAD

**Issue by iiSaLMaN** [ppy/osu-web#4638]
Apparently, we can't access the comments via api requests (which is needed for lazer to add comment section support)

**Comment by notbakaneko** [comment]
Does lazer support deserializing json if the objects are sideloaded instead of embedded? e.g.
```json
{
  "comments": {
    "id": 1,
    "user_id": 1
  },
  "users": {
    "id": 1
  }
}
```
instead of
```json
{
  "id": 1,
  "user_id": 1,
  "user": {
    "id": 1
  }
}
```

**Comment by peppy** [comment]
should there be an array specification in the prior example (suggested by plurals)?

**Comment by notbakaneko** [comment]
oh yeah, these are supposed to be arrays

**Comment by peppy** [comment]
should be fine in that case
