### ISSUE TITLE
Points of Failure graph is broken for converts

### ISSUE THREAD

**Issue by stanriders** [ppy/osu-web#4641]
**Example map**: https://osu.ppy.sh/beatmapsets/956802#taiko/2006992

**Screenshot**: 
![image](https://user-images.githubusercontent.com/8269193/61050799-79a75a00-a3f0-11e9-88d6-7f44da7615c8.png)

**Comment by LiquidPL** [comment]
Also noticed that the success rate is the same as of the original standard beatmap. Do we store playcounts/passcounts/points of failure for converts?

**Comment by peppy** [comment]
We do not store success rates per mode/ruleset currently.

**Comment by nanaya** [comment]
The chart rendering has been fixed in #6595 and others and success rates data is for all applicable modes including converts.
