### ISSUE TITLE
Expose genre_id and language_id in beatmapset to API

### ISSUE THREAD

**Issue by stanriders** [ppy/osu-web#4642]
https://github.com/ppy/osu/pull/5334

**Comment by notbakaneko** [comment]
is there an issue getting them from `genre.id` and `language.id`?

**Comment by peppy** [comment]
That should be fine. Are other details also going to be included (like display names?)

**Comment by notbakaneko** [comment]
`genre` and `language` have a `{ id, name }` format but they're not included in any response that includes beatmapset other than the main `beatmapset/{beatmapset_id}` resource where they're already included.

**Comment by LiquidPL** [comment]
I think this one is fine. Should it be closed, or do we need to add genre/language to other responses too?

**Comment by notbakaneko** [comment]
reopen if ppy/osu#5334 gets updated
