### ISSUE TITLE
Cannot change font size in post due to dropdown automatically closing in Firefox

### ISSUE THREAD

**Issue by VeilStar** [ppy/osu-web#465]
Title. Using Firefox 45.0.2. Doesn't happen in Chrome.

**Comment by nanaya** [comment]
I... don't know ;_; All I figured out is it works if I disable the custom tooltip.

**Comment by VeilStar** [comment]
Looks like the font size dropdown closes if the left mouse button isn't being held down outside of the font size box (over which you can hover for the tooltip to be visible). Not sure if that's useful info though.

**Comment by nanaya** [comment]
magically fixed in latest firefox.
