### ISSUE TITLE
New color scheme in site causes very hard to read texts

### ISSUE THREAD

**Issue by Cynplytholowazy** [ppy/osu-web#4653]
Referring to the recent change in color scheme, there are a lot of parts that has very hard to read texts due to extremely similar text colors. This could impact the readability of certain texts, especially to those who have visual impairments, or those devices that has problems with color display.

Examples include:
![Screenshot_2019-07-12-18-07-19-548_org mozilla fennec_aurora](https://user-images.githubusercontent.com/31384149/61120621-f9f0bc80-a4cf-11e9-910b-32fbae47d249.png)
1) the username color for beatmap nominators
2) Post dates

![image](https://user-images.githubusercontent.com/31384149/61125777-4c84a580-a4dd-11e9-99a3-c1fe4a1d5676.png)
Lots of people are complaining about this too and this is on the main page, the ranked dates.

Also another thing to mention is the background color and the text color being similar (like the main page with blue bg color and blue text and modding page with purple text and purple by color) would severely decrease the readability of the texts for those who have visual impairment on particular colors.

**Comment by Furozzu** [comment]
i would suggest to make beatmap nominator color more brighter. ex: ![Screenshot_2019-07-12-18-46-21-034_com discord](https://user-images.githubusercontent.com/29659076/61127192-bf3f5200-a4d8-11e9-9d0c-1365f73d4b36.png)

![Screenshot_2019-07-12-18-44-27-924_com discord](https://user-images.githubusercontent.com/29659076/61127267-02012a00-a4d9-11e9-8b25-825cc46f93b0.png)
it seems good at dark theme, maybe need slightly more darker to fit with old web design, but idk

**Comment by TPGPL** [comment]
Went through probably most of the pages and compiled all hard to read texts below:

1. Timestamps on beatmaps in the home page

![image](https://user-images.githubusercontent.com/19843905/61129087-f2231f00-a4b3-11e9-8e88-6b7676e7b383.png)

2. Copyright sign

![image](https://user-images.githubusercontent.com/19843905/61129096-fb13f080-a4b3-11e9-968f-e92cab7e5c15.png)

3. Disabled Post button

![image](https://user-images.githubusercontent.com/19843905/61129150-0a933980-a4b4-11e9-87d1-98dd2c2e1b84.png)

4. Timestamp (and manage buttons?) of comments

![image](https://user-images.githubusercontent.com/19843905/61129179-1979ec00-a4b4-11e9-9e93-d9ec4b395ff1.png)

5. Changelog user count

![image](https://user-images.githubusercontent.com/19843905/61129202-2b5b8f00-a4b4-11e9-9ebd-c3d083a2c05e.png)

6. Changelog description has same colour as the change

![image](https://user-images.githubusercontent.com/19843905/61129272-5219c580-a4b4-11e9-8422-38edbf2a04e4.png)

7. `0` count in beatmap scoreboards

![image](https://user-images.githubusercontent.com/19843905/61129339-7d041980-a4b4-11e9-978e-0a0375c02dcf.png)

8.  Table headers (e.g. `max combo`, `total score`)

![image](https://user-images.githubusercontent.com/19843905/61129363-88efdb80-a4b4-11e9-9918-a13aa699b585.png)

9.  FA song count

![image](https://user-images.githubusercontent.com/19843905/61129407-9f963280-a4b4-11e9-99c3-4159f1799397.png)

10. Most of the track list on FA artist page

![image](https://user-images.githubusercontent.com/19843905/61129433-b177d580-a4b4-11e9-9514-d4a03b8645bb.png)

11. Stats on rankings page

![image](https://user-images.githubusercontent.com/19843905/61129470-c5233c00-a4b4-11e9-8680-9e1f4e51ae92.png)

12. Contest ending date and type
![image](https://user-images.githubusercontent.com/19843905/61129501-d4a28500-a4b4-11e9-9895-f0c60cef3455.png)

13. Tournament registration date (and user count?)

![image](https://user-images.githubusercontent.com/19843905/61129545-ec7a0900-a4b4-11e9-8df7-ea5dd2c33b14.png)

14. Settings text box labels

![image](https://user-images.githubusercontent.com/19843905/61129621-10d5e580-a4b5-11e9-98b1-4773f5659aa1.png)

15. Timestamp on best performance plays

![image](https://user-images.githubusercontent.com/19843905/61129806-7fb33e80-a4b5-11e9-8a06-8eba5dad9a2e.png)

**Comment by Cynplytholowazy** [comment]
There are a couple issue in modding thread area too but I'm on mobile can't really do much so I asked TPGPL to help me list them out for me.

**Comment by cl8n** [comment]
disabled links in the paginator of https://osu.ppy.sh/beatmapsets/events are even worse
![ccbcde](https://user-images.githubusercontent.com/9954349/61341971-71d72380-a7fd-11e9-918f-fc801c166efd.png)
![87dec8](https://user-images.githubusercontent.com/9954349/61341972-726fba00-a7fd-11e9-8955-47b95eeb19ea.png)
