### ISSUE TITLE
Add droplet misses for osu!catch

### ISSUE THREAD

**Issue by Larakagi** [ppy/osu-web#4655]
As this tweet follows https://twitter.com/osuChatie/status/1148100198335438849, this feature explains how much droplets you've missed in order to rate accurasy. While this has been implemented on the old site for some reason it doesn't appear on the new site. I've seen the same report as in candidate issue https://github.com/ppy/osu-web/issues/2385 but I don't know if it was ignored or not. I think it would be better just to add this counter to the new site thus osu!catch players would know exactly how many droplets they've missed.

**Comment by peppy** [comment]
need to come up with a way to make this fit in the layout. "droplets missed" is too long. open to suggestions.

**Comment by Cynplytholowazy** [comment]
Drp. Miss?
