### ISSUE TITLE
Beatmap Info Page

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#466]
This bounty is for the new beatmap details page.

![](http://puu.sh/nPzv6/8fdd6dfe0c.png)

### Difficulty Selector

![](http://puu.sh/nPAkW/c987dad24f.png)

This is the mode and difficulty selector. 

The tabs are for the modes. It’s red when selected and gray if the mode is not available.

The buttons are the available difficulties, represented by difficulty level.

The title of the difficulty is stated under the buttons.

### Mapper Details and Downloads

![](http://puu.sh/nPAg0/740d73961b.png)

Area for mapper details. Submit and ranked date stated here.

osu!direct button will download the via the game client. Download button will download the map as a normal file.

There’s an checkbox if the user wants to download the map without video.

### Map Details

![](http://puu.sh/nPAPg/9ccd73c4f7.png)

Star chart in the middle. CS, SD, AR, OD and HP represents, Circle Size, Star Difficulty, Approach Rate, Overall Difficulty, and HP Drain.

Upper right is the standard map details. Lower left is music details.

![](http://puu.sh/nPB08/edf76e20ae.png)

It’s the same as the new profile page.

## Success Rate Chart

![](http://puu.sh/nPBBf/67aa5a4640.png)

## Scoreboard

![](http://puu.sh/nPBBY/e36f41645e.png)

Tabs changes the ranking mode. Please ignore the Mods:All.

Player ranked #1 displayed in a box with result details.

Rank list of #2—#50 listed under the #1 box. Grey highlights when hovered.

This time around, we'll be providing technical information required for implementation as we go, rather than fleshing this out in the initial post itself. Please show interest and we will work through it in this issue or in #osu-web on [slack](https://new.ppy.sh/community/slack)

Do note that @LiquidPL showed interest in this bounty, so he has priority on it should he still be wishing to take it up.

**[Bounty](https://goo.gl/nFdoyI) offered**: 500 upwards, depending on implementation quality.

**Comment by LiquidPL** [comment]
Actually almost done with that, the only thing left is to plug the scoreboard to the backend, so the tabs actually do something ¯\_(ツ)_/¯.

Having that in mind, could you tell me how can I retrieve the user's friend list? (I asked you several times on slack but you didn't respond)

**Comment by peppy** [comment]
Friends is retrieved from the phpbb_zebra table for now.

```CREATE TABLE phpbb_zebra
(
    user_id MEDIUMINT(8) UNSIGNED DEFAULT '0' NOT NULL,
    zebra_id MEDIUMINT(8) UNSIGNED DEFAULT '0' NOT NULL,
    friend TINYINT(1) UNSIGNED DEFAULT '0' NOT NULL,
    foe TINYINT(1) UNSIGNED DEFAULT '0' NOT NULL,
    CONSTRAINT `PRIMARY` PRIMARY KEY (user_id, zebra_id)
);
CREATE INDEX zebra_id ON phpbb_zebra (zebra_id);```

```SELECT zebra_id as user_id FROM phpbb_zebra WHERE user_id = {$us} AND friend = 1```

**Comment by peppy** [comment]
Rewarding 750 bounty to @LiquidPL for compeltion of this page :fireworks::fire::fire_engine::scream_cat:
