### ISSUE TITLE
Add the ability to join channels in Chat

### ISSUE THREAD

**Issue by Cynplytholowazy** [ppy/osu-web#4661]
Recently noticed you can chat in osu! channels like #osu #taiko etc. through Chat. Is it possible to add the ability to add channels into the chat list like how the osu! client allows you to do?

Something like this:
![image](https://cdn.discordapp.com/attachments/532945248121257984/599208251636056066/6d01.png)

**Comment by peppy** [comment]
This is the eventual goal, yes.
