### ISSUE TITLE
UserPage navbar not updated

### ISSUE THREAD

**Issue by Nyroux** [ppy/osu-web#4663]
the dropdown menu in the navbar has not been updated on the user page 

userpage :
![aie](https://user-images.githubusercontent.com/33320665/61146392-703df080-a4c9-11e9-8a2c-7ed1e33fb954.png)

new one : 
![goodone](https://user-images.githubusercontent.com/33320665/61146404-77fd9500-a4c9-11e9-9bb6-c26b52da94c0.png)

**Comment by peppy** [comment]
This is a gradual rollout, and requires the page's header also be updated to the newer version.

**Comment by notbakaneko** [comment]
It's the other way around, the navbar on the user page is the new one

**Comment by peppy** [comment]
Can probably close this issue for now.
