### ISSUE TITLE
Many elements on modding discussions need to be color schemed

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#4664]
Bright green and dull pink do Not go together here and it clashes big time
these elements should be added to the color scheming system or made more fitting colors to the pink coloration of the modding discussions pages
![image](https://user-images.githubusercontent.com/33286824/61163818-a3d74580-a4de-11e9-8fff-896f563a7921.png)
![image](https://user-images.githubusercontent.com/33286824/61163825-b5b8e880-a4de-11e9-92b7-b4f80e129a4d.png)
![image](https://user-images.githubusercontent.com/33286824/61163840-d41ee400-a4de-11e9-91fc-0b3e012f5245.png)

**Comment by TPGPL** [comment]
probably should be closed as the colours have been changed and it looks rather good
