### ISSUE TITLE
I didn't get a pp :'(

### ISSUE THREAD

**Issue by Ey2s** [ppy/osu-web#4666]
![12](https://user-images.githubusercontent.com/52864608/61174927-209f1800-a5e2-11e9-9a7d-b6d893580f10.PNG)
![13](https://user-images.githubusercontent.com/52864608/61174928-21d04500-a5e2-11e9-96c1-aea29c1635d3.PNG)
![15](https://user-images.githubusercontent.com/52864608/61174929-23017200-a5e2-11e9-9fd4-6bbd8e21f21b.PNG)

It's not a high score, but I think it's very unfair that other users don't get a normal pp. I hope this is fixed as soon as possible, xD.

**Comment by Joehuu** [comment]
Seems to be fixed. Can be closed.

**Comment by Magnus-Cosmos** [comment]
Doesn't seem to be fixed, I'm checking the event feed and still 0pp for every score I'm seeing

**Comment by TPGPL** [comment]
no point in keeping this issue open as the problem is already tracked

https://twitter.com/osustatus/status/1150136496017379328
