### ISSUE TITLE
Count Scorev2 toward playtime and playcount

### ISSUE THREAD

**Issue by downpour-osu** [ppy/osu-web#4667]
See title. There's basically no reason for this to still not count toward playtime and playcount, it's been in the game for forever. I understand not making the scores submit, but you're still playing the game!

**Comment by Magnus-Cosmos** [comment]
There's no way for the server to count playtime/playcount for a play if it doesn't submit
Also, you can use your same argument for any unranked mod/map

**Comment by peppy** [comment]
This will be fixed with lazer, as we will more liberally count play time with better heuristics.
