### ISSUE TITLE
100 50 and miss count not dimmed for friend highlighted score on map leaderboards 

### ISSUE THREAD

**Issue by Cynplytholowazy** [ppy/osu-web#4669]
Not very sure if intended but 100, 50 and miss count are not dimmed for friend highlighted score on map leaderboards.

![Screenshot_2019-07-14-19-25-17-732_org mozilla fennec_aurora](https://user-images.githubusercontent.com/31384149/61182976-b7fd7d00-a66d-11e9-8508-b020cd8c8c6e.png)

Also happens to users' own scores.

![Screenshot_2019-07-14-19-30-25-319_org mozilla fennec_aurora](https://user-images.githubusercontent.com/31384149/61182985-e418fe00-a66d-11e9-8f48-950f73992e8f.png)

I think the behaviour should be like the will only be turned white when the score is being hovered by the cursor?

**Comment by peppy** [comment]
Looks like an oversight.
