### ISSUE TITLE
Extra padding on the Friend things's 3 dot button overlay

### ISSUE THREAD

**Issue by AqilCont** [ppy/osu-web#4671]
![image](https://user-images.githubusercontent.com/32044067/61246117-1bde7f00-a71c-11e9-983f-ae613a8919f0.png)

**Issue:** When clicking on the 3 dot button on the friend thing, I think there is extra, unnecessary padding. Not really a big issue, I know, but just thought that I should address.

(sorry for saying thing... I just forgot what its called)

**Comment by peppy** [comment]
Can you point out which padding you believe is unnecessary?

**Comment by arflyte** [comment]
I'm not sure which padding you're referring to? if you're referring to the menu, it's there so that touch users can click it easily.

**Comment by Joehuu** [comment]
Closing as the design is intentional.
