### ISSUE TITLE
Difficult icon colour are different. (New Site and Old Site)

### ISSUE THREAD

**Issue by akba558** [ppy/osu-web#4677]
New Site:
![errere44](https://user-images.githubusercontent.com/52974182/61317078-db265900-a834-11e9-87e1-4e0233165d70.PNG)

![222](https://user-images.githubusercontent.com/52974182/61317088-deb9e000-a834-11e9-9208-5c45369fd166.PNG)

![2322](https://user-images.githubusercontent.com/52974182/61317513-b41c5700-a835-11e9-8b26-ba7835e43a7e.PNG)

Old Site:
![323121](https://user-images.githubusercontent.com/52974182/61317104-e8434800-a834-11e9-8c51-07595714362b.PNG)

![333](https://user-images.githubusercontent.com/52974182/61317113-ebd6cf00-a834-11e9-88fd-2466e96e7d2b.PNG)

![sww](https://user-images.githubusercontent.com/52974182/61317539-bda5bf00-a835-11e9-8a3e-494954b47d9e.PNG)

**Comment by InvisibleSymbol** [comment]
Pretty sure this is related to https://github.com/ppy/osu-web/pull/4181 and how it's not implemented/changed on the old page.

**Comment by Cynplytholowazy** [comment]
The old site uses the old star rating scheme to label the difficulty icon for each difficulty, listed as below:
0★ - 1.49★: Easy  
1.5★ - 2.24★: Normal  
2.25★ - 3.74★: Hard  
3.75★ - 5.25★: Insane  
5.25★+ : Expert

Whereas the new site uses the amended scheme:
 Easy: 0.0★–1.99★
 Normal: 2.0★–2.69★
 Hard: 2.7★–3.99★
 Insane: 4.0★–5.29★
 Expert: 5.3★–6.49★
 Expert+: >6.5★

When the new difficulty icon scheme is introduced, the old site is already depreciated. This is the reason why the old site and the new site may have different icon color in the same difficulty.

This issue can be closed.

**Comment by peppy** [comment]
The old site will not be updated with new functionality.

**Comment by akba558** [comment]
Thanks giving information.
