### ISSUE TITLE
Search maps by creator

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu-web#4681]
Add searching by creator function in beatmaps listing, because sometimes it finds you something completely different from what you wanted to see: https://i.imgur.com/5toaSEs.png

**Comment by Cynplytholowazy** [comment]
The relevance filter searches for artist, song title first before creator and tags. I believe if someone wants to search for maps by a particular creator they could simply go to their user page for that.

**Comment by peppy** [comment]
unless we start to add the ability to prefix search terms with a target search field, this seems a bit out of scope. i agree that visiting a user page would be a better approach when searching for a specific creator.
