### ISSUE TITLE
[docker] osu! page is timing out after successful build

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#4682]
![image](https://user-images.githubusercontent.com/19843905/61393180-b4adff80-a8c0-11e9-97f8-0f8507b49f2a.png)

I get this error whenever i try to connect to the localhost:8080 with osu! page.

```nginx_1          | 2019/07/17 16:27:14 [error] 6#6: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: <data>, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://<data>:9000", host: "localhost:8080"```

php is working fine: 
![image](https://user-images.githubusercontent.com/19843905/61393380-1ff7d180-a8c1-11e9-9e5b-97f8fa15b7aa.png)

and so is yarn: 
![image](https://user-images.githubusercontent.com/19843905/61393397-271edf80-a8c1-11e9-989a-d7e8d029df12.png)

another errors:
```php_1            | [17-Jul-2019 16:38:45] WARNING: [pool www] child 105 said into stderr: "NOTICE: PHP message: PHP Fata
l error:  Maximum execution time of 30 seconds exceeded in /data/osuweb/vendor/symfony/translation/Translator.php on lin
e 32"
php_1            | <ip> -  17/Jul/2019:16:26:14 +0000 "GET /index.php" 500
php_1            | [17-Jul-2019 16:39:17] WARNING: [pool www] child 105 said into stderr: "NOTICE: PHP message: PHP Fata
l error:  Maximum execution time of 30 seconds exceeded in /data/osuweb/vendor/laravel/framework/src/Illuminate/Foundati
on/Exceptions/Handler.php on line 35"```

**Comment by notbakaneko** [comment]
post the whole log, not tiny snippets and screenshots.

**Comment by notbakaneko** [comment]
also look in `storage/logs/laravel.log` for any errors

**Comment by TPGPL** [comment]
docker suddenly started working and it's fine now; will reopen if the issue happens again

**Comment by TPGPL** [comment]
happening again, this time it started timing out after making changes in the code and trying to reload the page

logs:
[powershell](https://gist.github.com/TPGPL/3fafc584b988969e6416c4ab38881a5c)
[laravel.log](https://github.com/ppy/osu-web/files/3481586/laravel.log)

**Comment by notbakaneko** [comment]
This looks more like a docker windows network issue

**Comment by TPGPL** [comment]
tried reinstalling docker and hyper-v but it didn't solve the problem

logs:
[powershell](https://gist.github.com/TPGPL/8c99ecde78c0cffa16c626d3cebe5b89)
[laravel.log](https://github.com/ppy/osu-web/files/3555474/laravel.log)

looks like the machine is blocking on nginx and maintaining web requests, as it fails to stop the containers for about an hour; same thing happened when i tried to access exec php shell - shell didn't load and nginx stopped working completely

**Comment by peppy** [comment]
Is this still relevant?

**Comment by nanaya** [comment]
Feel free to comment if still happens.
