### ISSUE TITLE
Add tooltips with full group name where abbreviations are used for display

### ISSUE THREAD

**Issue by venix12** [ppy/osu-web#4690]
It doesn't seem to be taking too much place while it used to be that way and it would be more clear I think.

**Comment by nekodex** [comment]
This was intentionally shortened - those badges are going to be used in many more places other than just the modding page. Those other places won't have as much free space as the modding section currently does.

Might be worth looking at adding a tooltip instead?

**Comment by VenixOSU** [comment]
If that's the case, yeah I think adding the tooltips with full usergroup names would be nice.

**Comment by peppy** [comment]
@nanaya is this still a thing?

**Comment by nanaya** [comment]
Yes, part of the moving group system to database
