### ISSUE TITLE
Wrong /legal/ route colour

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#4692]
Currently /legal/ path uses the same colour as /home/, although it uses osu!wiki which uses a different colour palette than /home/,

**Comment by peppy** [comment]
I think this may actually be more correct as it is, based on the route's home. @nekodex thoughts? I'm guessing this was intentionally done this way?

**Comment by nekodex** [comment]
![](https://puu.sh/DWETb/494389bfaa.png)

**Comment by peppy** [comment]
Let's leave it as-is.
