### ISSUE TITLE
Hide deleted comments on the comments listing page

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#4695]
otherwise it will look like that 
![image](https://user-images.githubusercontent.com/19843905/61540001-fe235980-aa3c-11e9-8dc7-c753ef64c81e.png)

**Comment by LiquidPL** [comment]
Should it also include some toggle to show deleted comments anyway (say, for moderators), or is it fine as is?

**Comment by peppy** [comment]
If it's a simple addition it's best we have it, but I'm not sure how necessary it is for moderation.

**Comment by E223** [comment]
A toggle already exists on the actual beatmap/news/changelog page FWIW. 
![](https://death.s-ul.eu/dkZRrT0b.png)

I don't know any moderators who actually use this listing page though.  If more functionality is ever added to this page (e.g. search/filtering) I'm sure a toggle would be nice to have for moderation purposes. For now I don't think people care.

**Comment by FlyingStefan** [comment]
It's not urgent but would be still be a good feature for moderators to have a clearer sight of comment sections.
