### ISSUE TITLE
Decrease distance between username and badge on modding discussions

### ISSUE THREAD

**Issue by venix12** [ppy/osu-web#4696]
Pretty minor thing, but I think it would give a better look if distance between username and the badge would be a little smaller;
current:
![](https://venix2.s-ul.eu/eZmUaEFQ)
proposed:
![](https://venix2.s-ul.eu/1tcY1mBW)

**Comment by peppy** [comment]
@arflyte

**Comment by arflyte** [comment]
Yeah, make it smaller for now.
