### ISSUE TITLE
Many badges blend in to the new profile design

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#4713]
![image](https://user-images.githubusercontent.com/33286824/61816140-b96f3800-ae19-11e9-9744-8e1e4205eb4e.png)
![image](https://user-images.githubusercontent.com/33286824/61816049-8d53b700-ae19-11e9-8e43-abb171da8cae.png)
![image](https://user-images.githubusercontent.com/33286824/61816113-aeb4a300-ae19-11e9-85a7-292520034f9e.png)

(these screenshots are just a few examples)

As a lot of badges were designed based off the assumption of being displayed on the old website (bright backgrounds) quite a few end up blending a lot on the new website dark themeness. While text etc is often still readable, the badges are really less noticeable overall and that sucks when they're supposed to be for cool achievements the user has earned.

Maybe all badges could have a medium-brightness outline on the profile design to help them stand out a bit more, or some other design.

**Comment by arflyte** [comment]
All content in the new site design will have a brighter background compared to the current one.

**Comment by Joehuu** [comment]
Closing as the background is brighter now:
![image](https://github.com/ppy/osu-web/assets/35318437/5f5344a4-e7aa-43ef-a47e-230384d121c1)
