### ISSUE TITLE
download_disabled_url is wrong for some maps

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#4721]
on https://osu.ppy.sh/beatmapsets/91217 , the "more information" link is https://gist.githubusercontent.com/a8700ac65256ded285b8/raw, but it should be https://gist.githubusercontent.com/peppy/a8700ac65256ded285b8/raw

other maps from this time probably have the same problem, I'm guessing github changed the gist raw URLs at some point

**Comment by peppy** [comment]
Thanks for pointing this out. Should be fixed.
