### ISSUE TITLE
Google Chrome internal website search does not fully work

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#4728]
If you type in osu.ppy.sh in the google chrome url/search bar then hit space, it gives you the option to search the website using its own search quickly.

However, if you actually try to do this, you get taken to osu's search page without your search term actually there.
![2019-07-26_16-08-55](https://user-images.githubusercontent.com/33286824/61978685-f1b07b00-afbf-11e9-82f7-17717dca4120.gif)

Doing the google chrome quick search should already fill out your search term once you are taken to osu's search page.

**Comment by notbakaneko** [comment]
Chrome adds this automatically based on a heuristic, there isn't anything in osu-web that provides omnibox support

**Comment by peppy** [comment]
Is this safe to close as not-our-issue?

**Comment by cl8n** [comment]
you can add support for it explicitly, I just told noffy she should try adding this herself because all that's needed is https://developer.mozilla.org/en-US/docs/Web/OpenSearch

**Comment by muekoeff** [comment]
Sample OpenSearch-file which can be referenced by inserting `<link rel="search" type="application/opensearchdescription+xml" href="/path/to/opensearch.xml" title="osu! beatmap listing" />` into `<head>`:

```
<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/" xmlns:moz="http://www.mozilla.org/2006/browser/search/">
	<ShortName>osu! beatmap listing</ShortName>
	<Description>osu! beatmap listing</Description>
	<Url method="get" template="https://osu.ppy.sh/beatmapsets?q={searchTerms}" type="text/html">
	</Url>
	<Image height="16" type="Image/x-icon" width="16">https://osu.ppy.sh/favicon.ico</Image>
	<moz:SearchForm>https://osu.ppy.sh/beatmapsets</moz:SearchForm>
</OpenSearchDescription>
```

**Comment by LittleEndu** [comment]
Shouldn't something like ``https://osu.ppy.sh/home/search?query={searchTerms}`` be used instead?
