### ISSUE TITLE
Create an "I want this!" store button for out-of-stock items

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#473]
We regularly run out of stock, but there is no way for users to be informed when we replenish stock for specific items. This task involves adding a button which displays on all out of stock items. It should be a toggle state, with text "Notify me when available!" becoming "You will be notified when stock arrives!".

On clicking, the user_id and product_id pair should be stored to a table.

**[Bounty](https://goo.gl/nFdoyI) offered**: 50-150 depending on implementation quality.

As always, ask if you have any questions, and feel free to jump on the [osu!dev slack](http://osu.ppy.sh/p/slack) for more real-time discussion.

**Comment by LiquidPL** [comment]
So this handles only adding the 'notify me' button, and you'll handle notifying by yourself, am I correct?

**Comment by peppy** [comment]
It's a pretty rare case and we don't have an admin interface for stock at the moment, so yes, that's correct.

**Comment by LiquidPL** [comment]
Alright then, I can try doing it.

**Comment by arflyte** [comment]
The design of the button should be the same as "Add to Cart" for now, as the new standardised button is not finalised yet.

**Comment by arflyte** [comment]
![response](https://cloud.githubusercontent.com/assets/3632750/14629507/2aab76a6-0642-11e6-836b-c3f43bb69df7.jpg)

The response should look like this.

**Comment by LiquidPL** [comment]
[![](http://i.imgur.com/WxrtA2v.png)](https://github.com/ppy/osu-web/blob/master/app/Http/routes.php#L101)

can I break this down into separate routes?

**Comment by LiquidPL** [comment]
@arflyte can I get the actual font sizes for that?
