### ISSUE TITLE
Add a volume control button on the Featured Artist page

### ISSUE THREAD

**Issue by Pachiru** [ppy/osu-web#4739]
It would be nice to have a button to control the volume on the Featured Artist webpage, on the bottom of the page, kinda like Soundcloud does on their website, since when you preview a song, the sound is pretty high and there is no way to manage the volume, unless using the Windows volume panel, which is quite inconvenient. 

Thanks!

**Comment by nekodex** [comment]
FWIW previews are playing back at 45% volume atm... is your browser volume pretty loud in general?

**Comment by tailsdk** [comment]
I think having the option would still be nice since it might be too loud or too low on others. I don't think having the ability to tune the volume would hurt it would just make it more convinient.

**Comment by peppy** [comment]
@tailsdk are you experiencing them being too loud or soft?

**Comment by MBomb-osu** [comment]
I experience it being too loud personally, it's the only thing I ever have to change my volume mixer down for (but then I have to turn it back up when using anything else e.g. youtube).

**Comment by peppy** [comment]
It still feels too loud here too, comparing to iTunes on macOS. I think we need to drop the volume down further (and maybe figure out what the actual correct setting is, since other sites seem to get it more correct).
