### ISSUE TITLE
Add Date to Achievement Popup

### ISSUE THREAD

**Issue by arflyte** [ppy/osu-web#474]
Something, like, this.

![osu next - achievement details hover](https://cloud.githubusercontent.com/assets/3632750/14662263/7c4e684e-06ef-11e6-9add-8e6361ff2a03.png)

Reduce the space between the title and description, and add the date (19px, #999) at the bottom.

**Comment by peppy** [comment]
**[Bounty](https://goo.gl/nFdoyI) offered**: 20

As always, ask if you have any questions, and feel free to jump on the [osu!dev slack](http://osu.ppy.sh/p/slack) for more real-time discussion.
