### ISSUE TITLE
[friends list] User card doesnt disappear from the list on unfriend

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#4743]
Friend's user card should automatically disappear after unfriending

**Comment by qcl12345** [comment]
I kind of like the way it is right now actually. If you somehow manage to click the remove button by accident, or if you remove someone and then immediately change your mind, you don't need to go all the way to that person's profile to add them back.

**Comment by Joehuu** [comment]
GitHub's follow system still shows the user after unfollow.

Twitter's follow system has a popup for confirmation, but still shows the user after unfollow.

**Comment by notbakaneko** [comment]
It itentionally does not disappear so accidental unfriending can be easily undone; it's also annoying when everything moves from the card being removed.
