### ISSUE TITLE
New Typeface for Content

### ISSUE THREAD

**Issue by arflyte** [ppy/osu-web#475]
Testing new typeface for content for readibility, [Noto Sans](https://www.google.com/fonts#ChoosePlace:select/Collection:Noto+Sans:400,700,700italic,400italic).

@nanaya can you help me out with these?

![ss 2016-04-20 at 03 58 49](https://cloud.githubusercontent.com/assets/3632750/14665949/9e7586ba-0711-11e6-8392-b40eb915d096.png)

**Comment by TPGPL** [comment]
Close this issue cuz it's done.

**Comment by lunafreya** [comment]
Uh... You forgot to close that issue, @arflyte.

**Comment by nanaya** [comment]
Whee.
