### ISSUE TITLE
API v2 Wiki request

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu-web#4755]
We need an API v2 request to get raw markdown pages of wiki. (Will be used in osu-side)

**Comment by kj415j45** [comment]
I think it is not a good idea since we host it on github. it would be easier to fetch from github side. through `https://github.com/ppy/osu-wiki/raw/master/{path/to/lang.md}`

**Comment by EVAST9919** [comment]
Thanks, works as expected aswell

**Comment by peppy** [comment]
Keep in mind using github for retrieval may hit rate limits, and we may still want an endpoint to ensure availability even if github is not available to the end-user (consider cases it is blocked by their country or ISP).

**Comment by notbakaneko** [comment]
are wiki requests going to be made by unauthenticated users?

**Comment by EVAST9919** [comment]
@peppy ?

**Comment by peppy** [comment]
Let's go with yes.
