### ISSUE TITLE
Make nominators visible on discussion after ranked

### ISSUE THREAD

**Issue by xenallio** [ppy/osu-web#4779]
Once a map is ranked, the nominators names dissapear from discussion page. This data would be usefull for both general information or keep track of poor nominations. idk if bns can see it, but I would like to be able to put a blame on someone.

**Comment by cl8n** [comment]
you can view the History tab of modding discussions to find the latest nominators

**Comment by peppy** [comment]
@arflyte is this something that may have changed with your latest design?

**Comment by xenallio** [comment]
claiton is right, this info is still accessible, but still going to keep issue open to ask if this is worth to let it be more visible

**Comment by arflyte** [comment]
Not in the design at the moment, but can easily be added.

**Comment by peppy** [comment]
have confirmed that this is always present in the next design iteration.
