### ISSUE TITLE
Add RC to "help" dropdown

### ISSUE THREAD

**Issue by xenallio** [ppy/osu-web#4791]
Ranking Criteria is essential for mapping and can provide a basic guide for new mappers. However the only way to find it is by google, from forum guides or by chaining links in the wiki.

Would strap RC right in the "help" dropdown at the top of eachpages (or under "beatmaps"?) to make at least more accessible.

**Comment by Joehuu** [comment]
I would go with `beatmaps`. It has the correct context there.

**Comment by peppy** [comment]
If anything, shouldn't it be on the BSS popup in-game or similar? There are already some help links there, have you checked whether it's already present?

**Comment by nl-tatatat** [comment]
I was going to post another proposal, but I saw this. The ranking criteria isnt visible or accessible enough on the web. It should be in one of the main dropdown menus, not tucked away in the wiki.

**Comment by peppy** [comment]
The wiki is not considered "tucked away". It's the location for all help information. As above, this is already in the BSS popup. Going to close this for now.
