### ISSUE TITLE
Unable to get country rankings using via API

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu-web#4794]
I'm trying to implement api for rankings in osu!, but here's a problem: it works fine for scores and performance, but country returns `null`. And error was Internal server error.
Request I was using: `https://osu.ppy.sh/api/v2/rankings/osu/country`

**Comment by EVAST9919** [comment]
Still doesn't work after https://github.com/ppy/osu-web/pull/4813 being merged

**Comment by nekodex** [comment]
Because it's not deployed yet.

**Comment by EVAST9919** [comment]
yep, it works now, my bad

**Comment by EVAST9919** [comment]
Seems like it's broken again for some reason. Now I have the same issue.

**Comment by peppy** [comment]
Please reopen issues if they return.

**Comment by notbakaneko** [comment]
What's the actual error message?

**Comment by EVAST9919** [comment]
Internal server error
