### ISSUE TITLE
Bounty platform suggestion

### ISSUE THREAD

**Issue by jhdcruz** [ppy/osu-web#4806]
> For those interested, we love to reward quality contributions via bounties, paid out via paypal or osu! supporter tags. Don't hesitate to request a bounty for your work on this project.

-----

There is also a **bounty hunting platform** for issues that needs attention _(high-priority)_ to suggestions _(something like, ex: `proposal` or `feature-suggestion`)_.

**[Issuehunt.io](https://issuehunt.io/)** - An issue-based bounty platform for open source projects. They use `Paypal` for withdrawals, and has alternatives like `Transferwise` and `SWIFT`. Have a look at their [FAQ](https://spectrum.chat/issuehunt/general/faq-summary~6a4aa913-92f8-4ad8-bf85-1f35ca25319c), it includes almost all answers to the questions that you might ask.

**[Gitcoin.co](https://gitcoin.co/)** - This one is an interesting one (for me at least 😂). Get paid in crypto for freelance jobs, building features, and solving bug bounties! Work with top open source projects and get paid out fast.

**As far as I know**, they also allow pay out on paypal, but not quite sure yet.
Look at their **[Kudos](https://gitcoin.co/kudos/)**, it's kind of interesting actually, it's some kind of badge for contributors.

**Comment by peppy** [comment]
we are not doing crypto nor are we using an external service. we used to use bountysource but it was crap. others likely are too.

if you want to support osu! development please buy supporter. if you want to prioritise issues then please add a reaction on the issue's OP or similar.
