### ISSUE TITLE
Timestamps for beatmap modding aren't wrapping properly

### ISSUE THREAD

**Issue by venix12** [ppy/osu-web#4817]
![](https://venix2.s-ul.eu/dNQ4ZZeS)
timestamps shouldn't wrap that way i believe

**Comment by peppy** [comment]
Where are you seeing this?

**Comment by nekodex** [comment]
That's the beatmap modding section

**Comment by nanaya** [comment]
Considering some timestamps may have long notes marker, it might actually be desirable.

**Comment by peppy** [comment]
can wrapping be preferred until it becomes no longer feasible?

**Comment by nanaya** [comment]
This has been accidentally fixed when review was added.
