### ISSUE TITLE
Torus shouldn't be used with italics

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#4824]
I'm assuming this is the plan already, just mentioning since the new forum page overrides the usercards' fonts but keeps the italics on the name

![67cb0d](https://user-images.githubusercontent.com/9954349/63677326-92ea4700-c7a1-11e9-98ff-facbc37f71ab.png)

**Comment by arflyte** [comment]
No italics for anything that uses Torus. Only content will use italics, and content uses a different font.

**Comment by peppy** [comment]
Still not fixed, still looking bad, including cut-off text:

![image](https://user-images.githubusercontent.com/191335/70210425-efcca480-1775-11ea-9c24-ba1432613291.png)
