### ISSUE TITLE
Multiple "Latest Post" unnecessary on forum listing 

### ISSUE THREAD

**Issue by qcl12345** [ppy/osu-web#4828]
To be clear I'm referring to the text at the top of each subforum here:
![](https://i.imgur.com/omnFRQM.png)

The text is bold(er) and it is the first line, so your eye is immediately drawn to it while it provides nearly useless information (especially after you've read it 20 times on the same page or have used the forum more than 1 time ever). Although the title itself is pink, that content is far more important and should be more noticeable in my opinion.

I'd suggest just removing the "Latest Post" text entirely. It does not take long to deduce what exactly those posts are based on the timestamp of the reply. Anyone who has used a forum before can also guess what that is because the layout for most forums are the same in this regard.

If having that is an absolute necessity, I'd suggest either listing it once somewhere for the entire column, or again, making it less noticeable in some way.

**Comment by arflyte** [comment]
The 'latest post' stays for now. I imagined there will be peeps who'd be confused without it.

**Comment by Lyawi** [comment]
Can I bump this, because it's really not needed, especially when the "Re:" exists 

Also no clue why it's like a headline in bold font

**Comment by Flanster** [comment]
Not to mention the presence of a timestamp implies it is the last post in said forum. Can you provide actual feedback this was needed in the first place?

**Comment by arflyte** [comment]
![Figma_191121-120941](https://user-images.githubusercontent.com/3632750/69300889-d4cb4200-0c57-11ea-9b46-b012734d13c4.png)
