### ISSUE TITLE
Add usergroup indication on last reply name

### ISSUE THREAD

**Issue by qcl12345** [ppy/osu-web#4829]
![](https://i.imgur.com/1BBCkhs.png)
In the image above, user group is indicated next to the name of the user that created the topic, but on the last reply it is nowhere to be found.

This was something that offered a bit of variety when scanning through posts on the forums on the old iterations of the designs. And sometimes looking for moderator posts is helpful. I think it would be nice to add this back (not sure if it was removed intentionally or forgotten).

**Comment by Dontmakemeeatyou** [comment]
Do agree it's hard to differentiate without the color differences of past iterations. Would honestly prefer just coloring the usernames, instead of using colored circles next to said names.

**Comment by VenixOSU** [comment]
Yeah, agree here, coloured usernames feel just more readable and clear, at least for me.

**Comment by Lyawi** [comment]
noticed this and feels really weird
