### ISSUE TITLE
Topic icons not vertically centered on feature request forum

### ISSUE THREAD

**Issue by qcl12345** [ppy/osu-web#4835]
![](https://i.imgur.com/ZcYfnGz.png)

Very noticeably off-center on the [feature requests](https://osu.ppy.sh/community/forums/4) forum. Likely due to the "star priorities" line increasing the height of the row (typically it is only posts and views).

These icons are also not centered on mobile (for all subforums), but I'm not sure if that is intentional. Looks kind of weird:
![](https://i.imgur.com/GnP8ao9.png)

**Comment by arflyte** [comment]
everything should be vertically aligned like other subforums
