### ISSUE TITLE
Noto Sans for non-Latin characters

### ISSUE THREAD

**Issue by lunafreya** [ppy/osu-web#485]
Why not have a font for the other languages? Especially when you see CJK characters. (i.e. primary font is Exo 2, secondary font is Noto Sans w/ all variants)

**Comment by nanaya** [comment]
Yeah, there was a joke about "please download 500 MB worth of fonts to view the site".

**Comment by lunafreya** [comment]
You can see the whole website with Exo 2 because of a font import mechanism! That can be done the same with Noto Sans!

**Comment by nanaya** [comment]
yeah... and the browser will download the font... in the background... so it can be rendered...

Not sure if anyone will appreciate loading a site causing a half gigabyte download of font in the background without notice.

**Comment by roupkk** [comment]
You can use css: [unicode-range](https://developer.mozilla.org/en/docs/Web/CSS/@font-face/unicode-range)
> If the page doesn't use any character in this range, the font is not downloaded; if it uses at least one, the whole font is downloaded.

Chunking fonts by frequency can help.
In case of korean, total size of Noto Sans KR is about 150MB.
But if you only support commonly used characters, that can be reduced into about 3MB or less (+95% coverage).

But not sure worth it. :confused:

**Comment by lunafreya** [comment]
@roupkk LGTM

**Comment by roupkk** [comment]
@lunafreya Inconsistent font rendering could be bad for UX.
Many sites use system fonts or well known fonts which might be cached from other site.
Focusing too much on font rendering could be overkill, IMHO.
