### ISSUE TITLE
Correct Æther Realm's placement in the Featured Artist catalogue

### ISSUE THREAD

**Issue by Nivalyx** [ppy/osu-web#4875]
as it stands (due to the character "Æ", which is derived from Ae) the band Aether Realm is being located in the very end of the Featured Artist Catalogue while they would fit more to be classified after *namirin and before antiPLUR i suppose :

![image](https://user-images.githubusercontent.com/36564236/64051375-14c4e080-cba5-11e9-8c56-313cb26287da.png)

i'm not sure whether this is an intended behavior or not tho, but right now it feels kind of weird for me to see an artist that is supposed to be alphabetically classified under "A" being listed in the very end...

**Comment by Greydus** [comment]
That's how unicode is structured, you can check [here](https://www.ssec.wisc.edu/~tomw/java/unicode.html) for a list unicode characters, just a warning, it might take a while to finish loading

**Comment by peppy** [comment]
For now I think this is fine.
