### ISSUE TITLE
Beatmapset factories don't work as intended

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#4887]
accessing beatmapsets generated by factories result in blank pages 

![image](https://user-images.githubusercontent.com/19843905/64178116-26d2a780-ce61-11e9-9491-7d2d5113226f.png)

[logs](https://gist.github.com/TPGPL/9f738b1c695d4b8a92053a09316a4577)

**Comment by cl8n** [comment]
looks like you made a beatmapset with no beatmaps, you need at least one beatmap for this page to work

**Comment by TPGPL** [comment]
if thats the problem then couldnt there be an array merge with Beatmap factory available?

**Comment by cl8n** [comment]
it's sometimes useful to make a Beatmapset without making new Beatmaps, so you shouldn't modify the factory definition for either of them

to make `x` beatmapsets with `y` beatmaps each:

```php
$beatmapsets = factory(App\Models\Beatmapset::class, x)
    ->create()
    ->each(function ($set) {
        $set->beatmaps()->saveMany(
            factory(App\Models\Beatmap::class, y)->make()
        );
    });
```

if you're only using these to get some example data to work with, you should use the seeders instead (https://github.com/ppy/osu-web/blob/master/SETUP.md#reset-the-database--seeding-sample-data)

**Comment by notbakaneko** [comment]
Beatmapset page shows sets of Beatmap info.
Beatmapset factory does not create Beatmaps.
Beatmapset page cannot show Beatmap info if there are no Beatmaps in the set.
