### ISSUE TITLE
Unable to get Spotlights rankings via API

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu-web#4898]
Similar to https://github.com/ppy/osu-web/issues/4794. Same internal server error.

**Comment by nekodex** [comment]
It's not an internal server error, it's returning HTML instead of JSON.

**Comment by notbakaneko** [comment]
is there a related lazer issue for all the rankings api stuff?

**Comment by peppy** [comment]
No issue as it hasn't been implemented yet.

**Comment by notbakaneko** [comment]
Is there an issue for implementing it? This would get more attention if there actually was.
