### ISSUE TITLE
Add a mod icon for Mirror

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-web#4909]
Mirror was added to lazer without any icon design. However, when it comes to stable version and has mod leaderboards, it should have a design for web.

Match used <Mirror>: https://osu.ppy.sh/community/matches/54664344

**Comment by peppy** [comment]
@arflyte

**Comment by arflyte** [comment]
Need more information on what the mod does.

**Comment by EVAST9919** [comment]
It's the mania mod that mirrors all the columns. Like 1,2,3,4 to 4,3,2,1.

**Comment by arflyte** [comment]
Got it. I'll think of something.

**Comment by arflyte** [comment]
![Mirror](https://user-images.githubusercontent.com/3632750/64755240-6ab26480-d565-11e9-8852-8be5af2d0a2d.png)

How's this?

**Comment by nanaya** [comment]
Added in #4939.

**Comment by arflyte** [comment]
![mod_mirror](https://user-images.githubusercontent.com/3632750/65298938-62cb7380-dba8-11e9-8be5-ef53e5bcbe39.png)
![mod_mirror@2x](https://user-images.githubusercontent.com/3632750/65298939-63640a00-dba8-11e9-8c21-2ac7b37fd804.png)

[Mirror.svg.zip](https://github.com/ppy/osu-web/files/3634161/Mirror.svg.zip)

Colour update.
