### ISSUE TITLE
Incorrect tooltip on some badges

### ISSUE THREAD

**Issue by willyosu** [ppy/osu-web#4910]
On [Dungeon's profile](https://osu.ppy.sh/users/461720) should say "osu! World Cup 3" or similar instead of "osu! World Cup 2013" since the tournament took place in 2012.
![image](https://user-images.githubusercontent.com/11691902/64472400-cf1b9100-d12b-11e9-8fe7-d5cb82f82d20.png)
and on [KRZY's profile](https://osu.ppy.sh/users/114017), same thing but with "osu! World Cup 2" which happened in 2011 and not 2012.
![image](https://user-images.githubusercontent.com/11691902/64472424-2883c000-d12c-11e9-9803-ff77a142baa8.png)

Not sure if there's any other incorrect ones like this but I'll edit if I find any.

**Comment by peppy** [comment]
Will look into this.

**Comment by peppy** [comment]
I've updated these to read better.
