### ISSUE TITLE
Disable the option to create new threads in Completed Projects

### ISSUE THREAD

**Issue by FlyingStefan** [ppy/osu-web#4921]
There's no reason to create new threads for the completed projects subforum. I'd also like to disable new posts but I guess people would still want to comment there.

Also prevents one or another person to request beatmaps.

**Comment by peppy** [comment]
Please confirm this is not fixed.

**Comment by FlyingStefan** [comment]
It remains for regular users and moderators to be available creating new threads. Took a screenshot from mine and a regular user it is still possible.

![IMG_20190911_071040](https://user-images.githubusercontent.com/35871017/64669898-81709280-d463-11e9-85ed-bcd8b86e6562.png)
![Screenshot_20190911-071117](https://user-images.githubusercontent.com/35871017/64669901-846b8300-d463-11e9-87cc-0a5415163a39.png)

**Comment by peppy** [comment]
Please check once more

**Comment by FlyingStefan** [comment]
Still unchanged, I've made sure to check desktop version but it's still possible

**Comment by peppy** [comment]
We've confirmed it's disabled here. Is this because you are a moderator?

**Comment by FlyingStefan** [comment]
I'm indeed a moderator. If it's disabled for everyone except moderators that's good enough.
