### ISSUE TITLE
Don't mix wiki and web changes in changelogs

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#4923]
it doesn't make a lot of sense to mix these together because you end up with logs like this https://osu.ppy.sh/home/changelog/web/2019.909.0 , where you'd think the "Tournament" section is going to have some changes to the website contests system but it's actually just wiki updates

my suggestion is to either split wiki into its own changelog stream, or ignore all tags from the wiki and keep them grouped under the "Wiki" category only

**Comment by peppy** [comment]
I don't mind this too much. Maybe grouping all under "wiki" is best for now. Will do this going forward.
