### ISSUE TITLE
Developer and GMT user groups cleanup

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#4924]
there are a lot of users in these groups that don't make a lot of sense or should probably be removed since they're so inactive

dev:
- "fly a kite" looks like some testing account that was never deleted
- inactive: echo, mm201, marcin, blaizer, daru, rbrat3(?), thevileone(?)
- nyquill should be added

gmt:
- osu!team shouldn't be here if it's already in dev
- do these people ever act as moderators? (and if not, do they need to be in this group anymore? it's misleading to show them here): nyquill, happystick, zallius, millhioref, smoogipoo, peppy
- inactive: mm201, marcin, p3n

**Comment by cl8n** [comment]
oh also there are people with titles that imply they're part of groups still, but aren't. the one I remember is intermezzo https://osu.ppy.sh/users/136842 with osu!dev + ppy color, there might be more but im not sure

and I guess this whole issue is just for @peppy

**Comment by peppy** [comment]
Have updated these with some changes. Remaining inactives should probably be moved to alumni, will look into that in the near future.

**Comment by cl8n** [comment]
are u still planning to do this @peppy 

@osuChaos is updating the GMT wiki page, and has basically the same complaint as me https://github.com/ppy/osu-wiki/pull/2847#issuecomment-558444528 . if people aren't involved with regular moderation / GMT work, they probably shouldn't be listed here

**Comment by peppy** [comment]
i'm fine with that happening. probably more chance of getting @Ephemeralis to go through and make the changes, rather than me.

**Comment by Ephemeralis** [comment]
I've pulled HappyStick, mm201 and Nyquill out since they're definitively less active/engaged these days, and moved them to the alumni. This is all a bit ceremonial since they can readd themselves at any time, but whatever.

Spoke to clayton about using superscript addendum on the GMT page for the rest that I'm not willing to really touch, unless I get absolute confirmation that they don't need the privileges anymore.

**Comment by peppy** [comment]
I'm fine with being removed from GMT (along with other devs) if that's best for clarity, fwiw @Ephemeralis.

**Comment by Ephemeralis** [comment]
I've cleared peppy and smoog out of the group as per of the above.
