### ISSUE TITLE
Poll results visuals are incorrect for localisations

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#4944]
***EDIT: Looks like the visuals are broken ONLY for localisation***

Results currently look like this:

![image](https://user-images.githubusercontent.com/19843905/64876850-6747d780-d650-11e9-97d0-80fce4a4dcda.png)

I think it's kinda wrong as the bars don't indicate anything and the winning option highlight doesn't always appear. Should probably adjust bar length to percentage and add proper highlighting for winning option

example poll: **https://osu.ppy.sh/community/forums/topics/121491**

**Comment by notbakaneko** [comment]
![image](https://user-images.githubusercontent.com/1694544/64879980-240e5880-d692-11e9-8af9-d232c4e4b165.png)
?_?

**Comment by TPGPL** [comment]
![image](https://user-images.githubusercontent.com/19843905/64880245-045a3e80-d658-11e9-8a21-1b69ff5fece7.png)

🤷‍♂ console is clear, chrome version is 76.0.3809.132

**Comment by Aergwyn** [comment]
Looks fine for me on Chrome Version 76.0.3809.132 (Official Build) (64-bit)

**Comment by TPGPL** [comment]
oh, looks like the poll results are broken on localisations but fine on English version for some reason? 

es: 

![image](https://user-images.githubusercontent.com/19843905/64880333-3cfa1800-d658-11e9-9e5d-78c17acd7891.png)

en:

![image](https://user-images.githubusercontent.com/19843905/64880350-497e7080-d658-11e9-9f26-28c27c7686ae.png)

**Comment by VenixOSU** [comment]
Yeah, it's some bug I believe, tried on other languages as well and same thing happens.

**Comment by notbakaneko** [comment]
I think it's when the delimiter is `,` instead of `.` since other languages are fine when they use `.`
