### ISSUE TITLE
Some letters look weird on dark forum badges.

### ISSUE THREAD

**Issue by venix12** [ppy/osu-web#4947]
M
![](https://venix2.s-ul.eu/nVdmAMM7)
![](https://venix2.s-ul.eu/EMFuD6Co)
V
![](https://venix2.s-ul.eu/NPcp9pFB)
A (one pixel longer)
![](https://venix2.s-ul.eu/fazNrdGS)
![](https://venix2.s-ul.eu/rqh4iWI5)

Seems like it's related to font size, increasing it a little would fix it.

**Comment by peppy** [comment]
What browser / operating system?

**Comment by Dontmakemeeatyou** [comment]
> What browser / operating system?

I'm also experiencing this behaviour. 
Chrome with 100% Zoom (Default)
Windows 7

Going to 110% seems to scale the font better

**Comment by notbakaneko** [comment]
screen resolution as well

**Comment by Dontmakemeeatyou** [comment]
> screen resolution as well

I thought I included that but I guess I didn't.

1920x1080

**Comment by venix12** [comment]
For me it's Windows 10 1920x1080 and chrome 76.0.3809.132

**Comment by notbakaneko** [comment]
The anti-aliasing (hinting?) on Inter seems weird at smaller font sizes especially at lower dpi:

retina display:
![image](https://user-images.githubusercontent.com/1694544/65016823-286f9580-d960-11e9-817f-3133ceb09609.png)

non-retina:
![image](https://user-images.githubusercontent.com/1694544/65016718-eb0b0800-d95f-11e9-8f36-2fedc692f0ea.png)

The 2 `R`s look different and bleed in different directions

**Comment by peppy** [comment]
Can reproduce, windows, chrome, default settings 100% zoom.

**Comment by nanaya** [comment]
Fixed in #5664 by using master copy of the fonts instead of converted ones.
