### ISSUE TITLE
Use full (or shortened) group names on forum badges.

### ISSUE THREAD

**Issue by venix12** [ppy/osu-web#4948]
Seems like there's a place to use more descriptive names on forum;
![](https://venix2.s-ul.eu/ajOHybT9) ![](https://venix2.s-ul.eu/di3a0lNk) ![](https://venix2.s-ul.eu/rVqGUG3j)
There's enough place to put "Global Moderator", "Nomination Assessement", "Nominator", "Developer" etc. I believe.

**Comment by Dontmakemeeatyou** [comment]
This design also removes any custom set titles so users like I, who are GMT but should have "Support Team", just show as "GMT".

I also believe full titles would be better for users to easily understand user roles instead of shoving a million acronyms in their face.

**Comment by cl8n** [comment]
> Or at least, have user title badges link to the wiki page about them? If you are fully set on using these.

#3706 !

**Comment by peppy** [comment]
Closing in favour of #3706, which is a more likely implementation.

**Comment by venix12** [comment]
Well, that wasn't really my point. I think https://github.com/ppy/osu-web/issues/3706 is a nice solution, but mostly for modding discussions where there seems to be no place to use full group name. On forum there's a lot of place so I think it would be nice to make use of it.
