### ISSUE TITLE
Forum footer bar overflow on mobile

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#4949]
![image](https://user-images.githubusercontent.com/19843905/64895420-cb809080-d67c-11e9-82e6-6fc426db4474.png)

Samsung Galaxy S5 as set device, but clips on most devices

**Comment by peppy** [comment]
You can try turning your device around as a temoprary solution.

**Comment by gagahpangeran** [comment]
Maybe temporary solution for this right now is change the bottom toolbar become scrollable.

![2020-08-01 10-32](https://user-images.githubusercontent.com/4964985/89093234-9db25080-d3e2-11ea-8829-c389133fec56.gif)

Related #5373

**Comment by nanaya** [comment]
Reopening because the temp fix broke other thing.

**Comment by nanaya** [comment]
A proper mobile menu is probably better. I don't see finished design from @arflyte though.

**Comment by arflyte** [comment]
That's one tiny screen ;__;

Maybe use an ellipsis to reveal bookmark, search and reply?

**Comment by nanaya** [comment]
It still needs design. Also there's moderator tools and thread lock status. The bookmark button is actually a menu which contains three options.

**Comment by arflyte** [comment]
Aite, on it.

**Comment by arflyte** [comment]
Actually... we can just reassign the buttons.

Just put all of the option in the moderator tools (renamed to Forum tools). Status lock changes to reply if it's not locked. I think everything is pretty much there in the design?

![Figma_200929-134328](https://user-images.githubusercontent.com/3632750/94513613-22daaa00-025a-11eb-9cbd-cb693f270ed0.png)
