### ISSUE TITLE
Enable the option to create new threads in Work in Progress

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#4950]
https://osu.ppy.sh/forum/119
This subforum has existed for quite some time now, but its still locked. Death and I asked multiple times (including on github) for it to be unlocked. I made a new issue after seeing #4921 which is basically the same thing but enabling instead of disabling.
I assume this also should just be a small change like for 4921.

Would love to finally be able to utilise this forum

**Comment by FlyingStefan** [comment]
Yep, noticed when I just tried to move a completed project to its respective forum I was unable to choose it so I sorta locked out myself from this forum and organize things there.

**Comment by peppy** [comment]
This should now be fixed. Please confirm and close.

**Comment by RockRoller01** [comment]
Thank you very much. Its finally working.
