### ISSUE TITLE
Add user's country flag to mobile forum post info

### ISSUE THREAD

**Issue by E223** [ppy/osu-web#4951]
Not sure why the flag was removed from the post info on the left side of the post content, it looks like it would fit? From what I can tell the bar on the left is 45px wide while the flags are 30px. 

Sometimes it's relevant to see what country someone is from and since you can't pull up a user card on mobile, it gets slightly annoying to need to click on people's profiles to get that information. Especially because navigating between pages or new tabs on mobile is more annoying than desktop in and of itself.

![](https://cdn.discordapp.com/attachments/202196734393319425/622274087577845771/SmartSelect_20190913-203451_Chrome.jpg)

**Comment by peppy** [comment]
@arflyte any reason this was removed when there's space for it?

**Comment by arflyte** [comment]
Ah, I must have forgotten to put it back when I was trying out the layouts. I'll put the flag back in.
