### ISSUE TITLE
Scroll position doesn't get reset when clicking on a new thread or subforum

### ISSUE THREAD

**Issue by E223** [ppy/osu-web#4952]
If you click on a thread, scroll down a bit, then go back and click on a completely new thread, you automatically get scrolled to the position you were in on the previous thread. It should probably reset instead.

I think the same thing applies to listing pages as well. If you scroll all the way down on https://osu.ppy.sh/community/forums and click on the "[Other Languages](https://osu.ppy.sh/community/forums/18)" subforum you end up scrolled down on that page as well.

In case that wording is confusing, the only way I've found to illustrate this is with a picture of the window.scrollY value in the console.
![](https://death.s-ul.eu/ZPV4IGbV.png) 
1. Navigated to https://osu.ppy.sh/community/forums/topics/923908 and scrolled down a bit
2. Clicked on the breadcrumb item to go back to https://osu.ppy.sh/community/forums/7
3. Navigated to https://osu.ppy.sh/community/forums/topics/766952 (a thread I've never visited before) and was automatically scrolled to the same position as I was in the other thread.

**Comment by nanaya** [comment]
I can't seem to reproduce this. It doesn't help the console output provided above isn't what should normally happen as our navigation doesn't produce "Navigated to \<url\>" as it doesn't use browser native navigation.

**Comment by E223** [comment]
I believe I refreshed the page to get the "Navigated to..." to appear in order to show what pages I was on. I can't seem to reproduce this anymore either though, so I'll close this issue.
