### ISSUE TITLE
Modding discussions user filter missing usergroup indication

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#4954]
![image](https://user-images.githubusercontent.com/33286824/64909388-5f804580-d6d9-11e9-9c47-97d9987ffdfe.png)

previously, users with usercolors were also colored on this dropdown. This made it easier to find BN or NAT posts in a thread. For some reason this feature has disappeared ( ? I can't find the reason why anywhere ? ).

This should really keep the usernames colored, or add the badges next to them to make it clearly identifiable.

**Comment by Joehuu** [comment]
Here: https://github.com/ppy/osu-web/issues/3580

**Comment by dorothy3242** [comment]
That was when it was removed originally, then it was added back (with better colors), now it's gone again.

**Comment by venix12** [comment]
yeah, same on the forum listing, possibly related to https://github.com/ppy/osu-web/pull/4913?
