### ISSUE TITLE
Discord Integration

### ISSUE THREAD

**Issue by Malavolence** [ppy/osu-web#4955]
![Screenshot_228](https://user-images.githubusercontent.com/55348410/64925191-47014f80-d7ed-11e9-868c-257fc0c1807c.png)

A way to just see the discord user's osu! IGN and Rank

for the love of god don't make others see our PP

**Comment by jorolf** [comment]
This is up to discord to integrate and not up to osu!.

![connections](https://user-images.githubusercontent.com/12570757/64925265-24236b00-d7ee-11e9-8bb3-6a6bf0e30058.png)
See how this is a set list with services that you probably don't even use? It's very unlikely that discord will integrate this considering that there are no other games in that list (except league of legends). 

(And osu! is rather small compared to other candidates for integration)
