### ISSUE TITLE
Scaling Issues on Firefox

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#4968]
The thread listing scales perfectly on chrome when I zoom, but chrome only has zoom levels that are increments of 25. Firefox however has increments of 10 and when I scale to 130% (and some zoom levels above 200) I start to see these pink lines on the thread listing. 
![firefox_dHQtCQoo1n](https://user-images.githubusercontent.com/35633093/65042954-4508cf00-d95a-11e9-9b09-8852959cf2ce.png)

**Comment by RockRoller01** [comment]
Addition to this: I have the same problem on mobile aswell, If I use the osu site on desktop mode.

**Comment by afichemist** [comment]
I Found it. Its Issue for rendering browser. in some cases,you must ,scroll up and down to re-render this.is normally.
and scaling will be breaks the design and browser render
