### ISSUE TITLE
Quoting a post with shortened links returns <a> of the link.

### ISSUE THREAD

**Issue by Nath789** [ppy/osu-web#498]
It only happens on links that has been shortened.
e.g. [t/408517](https://osu.ppy.sh/forum/t/408517) or [/p/4815096](https://osu.ppy.sh/forum/p/4815096)

Simply use the quote button on a post with a that kind URL to reproduce.

![cap](https://cloud.githubusercontent.com/assets/5668486/15145009/b4091dd2-16e5-11e6-9c84-f94d0874f130.JPG)

**Comment by Nath789** [comment]
Updated information, it only happens on shortened links.

**Comment by nanaya** [comment]
Seems fixed.
