### ISSUE TITLE
Posts in mod only subforums not searchable

### ISSUE THREAD

**Issue by E223** [ppy/osu-web#4982]
Posts/threads in any mod only subforums are not searchable or vieawable in people's post histories by moderators. This makes it incredibly difficult to find things there.

**Comment by Ephemeralis** [comment]
This has cost me hours of time today when trying to compile something that relies heavily on historical information. Searching by hand is an absolute pain in the dick.

**Comment by peppy** [comment]
Can this be easily turned on @nanaya? Do we require storing more data to ES?

**Comment by nanaya** [comment]
Currently search assumes everything in elasticsearch is publicly searchable so adding support for this involves changing indexer to index everything, update search to exclude/include forums based on the user permission, and finally reindex everything.

**Comment by notbakaneko** [comment]
`enable_indexing` needs to be enabled on the forum, assuming permissions have been set correctly

**Comment by nanaya** [comment]
Oh, so the filter is already there.

**Comment by peppy** [comment]
I've added the missing forums to indexing. Should be available in a few hours.

**Comment by E223** [comment]
Was https://osu.ppy.sh/community/forums/3 added as well? Seems like that is still not searchable and it's the main subforum I created the issue for in the first place.

**Comment by peppy** [comment]
It was not added. What's the purpose of searching the abandoned wasteland?

**Comment by E223** [comment]
For keeping track of user history. In the same way that it's useful to see deleted forum posts (https://github.com/ppy/osu-web/issues/5978), modding discussions, or comments. 

I guess it's not so much that I care about it being "searchable" per se, but rather I'd like to just be able to see it in someone's post history in general. If that is possible without actually making the entire forum searchable, I'd be fine with that as well.

**Comment by peppy** [comment]
This is for very old cases right? Because these days we don't use that forum?

**Comment by E223** [comment]
It's still used quite a bit.

In theory I believe it could be phased out, but at the moment deleting the first post of the thread will not actually remove the thread, it just makes the second post show up as the first and thread stays visible. So the only way to remove an entire thread is to move it there. I thought there was an issue open for that, but after searching just now it seems like there isn't...
