### ISSUE TITLE
No-mod leaderboard should include SD and PF

### ISSUE THREAD

**Issue by Sleepteiner** [ppy/osu-web#4994]
On the old site, the nomod leaderboard also listed scores with SD and PF. This is great since it actually shows all scores that don't use any mods that change the difficulty of the map, since SD and PF are basically just condition-based auto-retryers. The new site doesn't do this anymore which means that everyone who has put a lot of time into SD and PF scores won't find their scores on the leaderboard that they could be competitive on. This also makes those scores a lot harder for other people to find compared to the old site. Yes, you could go through and check the SD and PF leaderboards individually for most maps, even though that is an inconvenience, however, on some maps with tons of plays, there are so many SD/PF scores with other mods included that the SD/PF only scores can't be found on the new site at all.

**Comment by peppy** [comment]
Should be considered when #4674 is implemented.

**Comment by cl8n** [comment]
this wasn't addressed in #4674 

also, if this is added I think Mirror should be included. it's nothing more than a preference
