### ISSUE TITLE
osu! brand page

### ISSUE THREAD

**Issue by LeaPhant** [ppy/osu-web#4996]
Having an official brand page would be nice. This should include the osu! logo and the official color palette with maybe some design guidelines on how to use them similar to how other companies are doing it.

![image](https://user-images.githubusercontent.com/14080165/65392374-93600880-dd74-11e9-8137-804db1551917.png)

This might help in making contributions to osu! and related third-party projects look less divided and closer to the original design.

References:
https://www.twitch.tv/p/brand/
https://www.youtube.com/about/brand-resources/
https://whatsappbrand.com/

**Comment by peppy** [comment]
We already have a brand guidelines document since flyte likes making that kinda thing. It's been a private thing until now, but I see no reason we can't publish it if it's not a super-high-effort task. @arflyte

**Comment by arflyte** [comment]
[osu! Identity Guidelines.pdf](https://github.com/ppy/osu-web/files/3644973/osu.Identity.Guidelines.pdf)

Above is the current guideline we have; covering mostly on logo usage. Pending for a major revision on typography, colour palette and general style guide. The newly revised guideline will be made available on Figma.

**Comment by aerouk** [comment]
Is Exo 2 likely to remain the primary font face considering the recent change to the font used on the forums?

**Comment by arflyte** [comment]
Exo 2 will phase out.

**Comment by Coppertine** [comment]
Don't forget the design pack that the pdf is refferencing and forcing you to use

**Comment by arflyte** [comment]
https://drive.google.com/file/d/1TmUot5nu49p71icz4u3G68njLAQOeQrG/view?usp=sharing

Here's the package.

**Comment by WalterToro** [comment]
@arflyte some notes after looking at the guidelines
- Colours
	- +1 +2 color codes are the same on pink and purple
	- -1 color codes are the same on light blue and yellow
- Game Mode Badge
	- Game mode text is mixed, should be taiko, catch and mania (in order)

**Comment by arflyte** [comment]
Use the guideline attached above, not the one included in the package. The package is pretty old and hasn't been updated for quite some time since it's only been used internally.

We're no longer using the colour swatch too. The only thing that's still valid in the guidelines is the logo usage.

**Comment by peppy** [comment]
Closing this as it is now available on the wiki and should continue to be expanded there.
