### ISSUE TITLE
Enable 'Move to' permission for threads to moderators

### ISSUE THREAD

**Issue by FlyingStefan** [ppy/osu-web#4999]
With the change in https://github.com/ppy/osu-web/issues/4921 it locked the whole Completed Projects  subforum in Beatmap Projects and therefore makes it impossible to moderators to move threads into Completed Projects. (to sort things out)

Add the permission to moderators to move threads in Completed Projects.

**Comment by peppy** [comment]
I'm 99% sure this would have been fixed by now. If not, please let me know.
