### ISSUE TITLE
pp not shown in user profiles

### ISSUE THREAD

**Issue by Shavitush** [ppy/osu-web#5]
I may be blind, but probably not;
pp is not shown in user profiles

I guess this is very easy to implement as it exists in the old site.

Attached a page capture of rrtyui's user profile as an example.
![enkcato](https://cloud.githubusercontent.com/assets/3672466/9545870/517be6f4-4d96-11e5-918f-f99a0fc4f753.png)

**Comment by peppy** [comment]
This site is still a WIP.
