### ISSUE TITLE
Show group name on mobile group listing

### ISSUE THREAD

**Issue by venix12** [ppy/osu-web#5000]
![Capture+_2019-09-23-11-35-31](https://user-images.githubusercontent.com/30481900/65415717-8edc3400-ddf6-11e9-961f-dee84dc6402a.png)
user group name is missing, in this case there's no way to enforce it's osu!dev group

**Comment by TPGPL** [comment]
![image](https://user-images.githubusercontent.com/19843905/71427645-1453d680-26bb-11ea-8f06-31e9f7825452.png)

should be closed
