### ISSUE TITLE
Spoiler boxes showing "SPOILER" before any text

### ISSUE THREAD

**Issue by Minion24** [ppy/osu-web#5008]
spoiler boxes show the text "SPOILER" before any other text, even if those aren't supposed to
![Screenshot_203](https://user-images.githubusercontent.com/38690901/65518733-0d170400-dee5-11e9-81d2-f09070bc99a1.png)

**Comment by peppy** [comment]
I don't think it's supposed to say that, right?

**Comment by arflyte** [comment]
Remove the word spoiler. Completely forgotten that some used it for non-spoilery content.
