### ISSUE TITLE
New Change Log Page

### ISSUE THREAD

**Issue by arflyte** [ppy/osu-web#501]
![](http://puu.sh/oNLFw/5b54e95e6c.png)
Design mockup for Change Logs page at @2x. Ignore the old style header.
## Change Logs Summary

![](http://puu.sh/oNLGL/07be8aa358.jpg)
Release stream buttons. The latest Stable version is on top, 2 buttons wide while the rest are at the bottom. Each button shows the current online users using the stream's build.

When clicked, button is highlighted with border of it's label colour (blue for latest stable, green for old stable, orange for test builds, red for the super experimental build), and the background cover changes.

The cover background image changes according to selected release stream. Illustrations will be provided in the future, use temporary placeholder image for now.

![](http://puu.sh/oNLI8/d2d1697d44.png)
Graph shows the build propagation for the past 7 days. The colour of the graph follows according to the build label colours. Additional details appear on hover.
## Change Logs Descriptions

![](http://puu.sh/oNLJp/56b23e163d.png)
Date, followed by build number.

Change type icon (fix or add) followed by contributor name and change details.

Shows builds for the latest 4 builds for each release stream.

**[Bounty](https://goo.gl/nFdoyI) offered**: 500+ depending on implementation quality.

As always, ask if you have any questions, and feel free to jump on the [osu!dev slack](http://osu.ppy.sh/p/slack) for more real-time discussion.

**Comment by peppy** [comment]
One someone has shown interest in this, we will provide database table structure and sample data for the changelog entries and build history graph/display.

**Comment by LiquidPL** [comment]
is there any set way how should those buttons arrange when on mobile? also, what image/gradient/whatever is under those buttons?

**Comment by arflyte** [comment]
Featured/Important fix should be on top of other lesser fix. Like this:

![](http://puu.sh/oNNoZ/14eb4a8269.png)

**Comment by UnnoTed** [comment]
i'll do it

**Comment by peppy** [comment]
How's things going?

**Comment by UnnoTed** [comment]
Preview: https://youtu.be/5rgTKWevd7U

Things left to do:
- [ ] Fix the chart info-box not being in the same place as the mouse (caused by viewBox).
- [ ] Add the featured/important fix to be on top.
- [ ] db stuff

**Comment by TPGPL** [comment]
How's the work going?

**Comment by lunafreya** [comment]
Any progress on this so far? I think we must have forgotten about this.

**Comment by peppy** [comment]
I believe @LiquidPL has made some progress on this.

**Comment by UnnoTed** [comment]
I didn't finish it, but here is the code: https://github.com/UnnoTed/osu-web/commit/0eb9ccf2a744df9ed30c7fee807664cd1c539b2f
feel free to use it, if it's still useful...

I wont be able to continue as i'm working 50+ hours weekly now, sorry :confused:

**Comment by LiquidPL** [comment]
should this page be able to retrieve data for older builds (like in `https://osu.ppy.sh/p/changelog?v=<build_id>`), or *only* the four newest ones?

**Comment by peppy** [comment]
any build should be accessible

**Comment by lunafreya** [comment]
The currently presented version of the new changelog page design does not explicitly display what exactly has changed for either the client or the website. Or should we ask @arflyte to look into this one more?
