### ISSUE TITLE
Boxes in osu! profiles don't show the intended effect but show SPOILER

### ISSUE THREAD

**Issue by chika-osu** [ppy/osu-web#5011]
![ACE1BC9E-0C24-40E2-B7B7-97184BEC72B9](https://user-images.githubusercontent.com/34539452/65575712-0d75d480-dfa3-11e9-82b3-449435f75da5.jpeg)

The intended effect for boxes is not spoilers. A lot of user's profiles were massively ruined due to the change - addition of "SPOILER" for box labels (which was not intended). Please fix soon.

**Comment by peppy** [comment]
Already fixed via #5009.
