### ISSUE TITLE
Make it easier to access the friends page on mobile

### ISSUE THREAD

**Issue by InvisibleSymbol** [ppy/osu-web#5018]
Currently it is necessary to be on the homepage to access your friends page:

![](https://i.fiery.me/9uyO.gif)

Loading two pages instead of one can be extremely annoying, especially on a slow connection. I suggest to add an extra section in the drop-down for user related actions, which can normally be accessed on the desktop site [using your profile pic](https://i.fiery.me/AT3d.png).

This is the implementation I have in my mind _(please note that this is a simple html edit, **I haven't coded anything**)_:

![](https://i.fiery.me/chJp.gif)

**Comment by arflyte** [comment]
![Profile](https://user-images.githubusercontent.com/3632750/65858690-8d37e080-e3a1-11e9-88d0-90dc0e408e5d.png)

There's a new header for mobile which will fix this. Temporarily, we can implement that Profile item in the menu.

**Comment by InvisibleSymbol** [comment]
The issue is back with the new design

**Comment by nanaya** [comment]
Tap on your avatar maybe? It has same menu as the one on desktop.

**Comment by InvisibleSymbol** [comment]
Oh it does show up, my bad. Will take a bit to adapt to the new design I guess.
