### ISSUE TITLE
Add “All time highest rank” feature aside of current rank

### ISSUE THREAD

**Issue by CaptainTristana** [ppy/osu-web#5032]
Got this idea while playing Clash Royale, basically when you’re hitting a rank that is your all time high, there will be a record of your rank even if you decay into oblivion. Gives the player a sense of pride and accomplishment.
Basically Cookiezi would have rank 17 and (highest rank: 1) 
A scrub like me would finally show off that I once belonged to the 3 digits club too (inb4 peppy was actually rank 1)

**Comment by peppy** [comment]
We've been recording this for some time now, with the intention of eventually displaying it.
