### ISSUE TITLE
Sort Featured Artist albums by most recent

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#5046]
New albums added to Featured Artist listings display at the bottom of the album/collection sidebar, which is generally counter-intuitive, as many people tend to favor more recent releases.

Changing the default sorting on this to favor newer albums first (ergo, at the top of the sidebar) would be ideal for most use cases.

In addition, perhaps consider a 'promoted' flag for artist_albums which always pins them as the topmost entry in the list, maybe with a special highlighting. This would be useful to highlight concurrent or 'special' releases, such as the recent thing with KOAN Sound and now BilliumMoto's new albums.

**Comment by TPGPL** [comment]
could be connected with adding *actual* sorting ability
