### ISSUE TITLE
Improvements to US and Liberian flags

### ISSUE THREAD

**Issue by Rocker-r** [ppy/osu-web#505]
Someone brought this up on the osu! subreddit, so I made up improved versions of the US and Liberian flags. However, I've never used git before, so I have no idea how to create a pull request for these improved flags. 

![us](https://cloud.githubusercontent.com/assets/19335796/15234104/18db6ba6-187c-11e6-98e2-0c00b241acab.png)
![lr](https://cloud.githubusercontent.com/assets/19335796/15234107/2188f502-187c-11e6-874b-efcf11d05ef4.png)

**Comment by kschamplin19** [comment]
See the [flags](https://github.com/ppy/osu-web/tree/master/public/images/flags) folder for the list of all the flags. I would [fork](https://help.github.com/articles/fork-a-repo/), then [branch](https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/), and after you have made your changes make a [pull request](https://help.github.com/articles/using-pull-requests/).

**Comment by Rocker-r** [comment]
Thanks for the help, created the pull request

**Comment by arflyte** [comment]
The USA flag have already been updated by increasing the number of stars, but the number of stripes remained in order to keep it simple. The flags are not accurate representations but a simplified representation of the actual flag designs.
