### ISSUE TITLE
Provide access to private chat via message box on new site

### ISSUE THREAD

**Issue by nicholauscjj** [ppy/osu-web#5063]
![img1](https://user-images.githubusercontent.com/36277652/66260248-5705c100-e7e6-11e9-8362-29499157273d.png)
Image 1. Definition of the message box is the one in the red square.

Considering new chat notification is sent from the message box, it would make more sense (also by intuition) if there's a way to also approach chat via message box. Alternatively, show past chat picked from the most recent.

The similar usage of "message box" to access private chat can be seen on various platforms, notably social media.

![image](https://user-images.githubusercontent.com/36277652/66260393-49e9d180-e7e8-11e9-96e7-653765d46d15.png)
Image 2. Example of the usage of "message box" icon to redirect to private chat on (a) web twitter, low-width; (b) Instagram

**Comment by peppy** [comment]
We really do need this. It is way too hidden currently.

**Comment by arflyte** [comment]
Looking into it; chat notifications weren't in mind back then as it has a different notification.

**Comment by afichemist** [comment]
@peppy it's something make message notification on database for displaying new chat?

**Comment by afichemist** [comment]
ok , I will try this

**Comment by Joehuu** [comment]
Button added in https://github.com/ppy/osu-web/pull/5765 and notifications window added in https://github.com/ppy/osu-web/pull/6803.
