### ISSUE TITLE
Mods used not showing on user profile top ranks (mobile)

### ISSUE THREAD

**Issue by Allxzh** [ppy/osu-web#5074]
Haven't tested anything else but atleast on my iphone 6s while using google chrome none of the mods used on top ranks show up.

**Comment by afichemist** [comment]
Can you give some screenshot?

**Comment by Allxzh** [comment]
![EGRifKiWkAAjYVA](https://user-images.githubusercontent.com/27788159/66357061-b4784a00-e96d-11e9-9ec2-f1f2618043fd.jpg)

this is wubwoofwolfs userpage, his top play is HDHR and remote control is HDDT but it doesn't show anything

**Comment by nanaya** [comment]
Which ios version is that?

**Comment by afichemist** [comment]
Its effect to another platform in mobile mode @nanaya . I Have tried for this.

**Comment by nanaya** [comment]
It seems fine on my phone...

![Screenshot_20191008-113312](https://user-images.githubusercontent.com/276295/66362942-83286a00-e9bf-11e9-8b59-15e5debbc36f.png)

**Comment by nanaya** [comment]
Seems fine on ios 13.2 as well.

**Comment by afichemist** [comment]
![Screenshot from 2019-10-08 09-35-48](https://user-images.githubusercontent.com/52690797/66363065-29b83f00-e9af-11e9-9c58-1ee520ebe461.png)
![Screenshot from 2019-10-08 09-36-11](https://user-images.githubusercontent.com/52690797/66363067-29b83f00-e9af-11e9-82d9-23b71c8dc67e.png)
in mobile and desktop mode

**Comment by afichemist** [comment]
I Think , its affected by resolution support

**Comment by nanaya** [comment]
hmm, that's weird

![](https://s.myconan.net/2019-10/firefox_2019-10-08_11-40-08.png)

**Comment by afichemist** [comment]
yes, I think so. hmm but, Flex is only support in newest browser,right?

**Comment by nanaya** [comment]
No, flexbox support has been in firefox since over 4 years ago. Which version is your firefox?

**Comment by afichemist** [comment]
ya,saya di firefox.69.0.1 ,dan anehnya,support saat desktop.
yes,I am in firefox , version 69.0.1 , and it's supported in desktop

**Comment by afichemist** [comment]
giliran di rotasi bisa @nanaya di tombol rotation

**Comment by peppy** [comment]
Please use english.

**Comment by nanaya** [comment]
try reloading and wait a few minutes and see if it loads.

**Comment by afichemist** [comment]
try to clearing cache in browser,some browser store old CSS before update.

**Comment by Phippe** [comment]
iPhone 5 using iOS 10.3.4, mods are visible for me

**Comment by nanaya** [comment]
In addition to this looked like a connection issue, mods display styling has been changed since to be a bit simpler.
