### ISSUE TITLE
Cannot report users

### ISSUE THREAD

**Issue by GrilledCheeese** [ppy/osu-web#5076]
Screenshot of the problem:
![image](https://user-images.githubusercontent.com/34809632/66355881-331eb880-e969-11e9-86e0-a2c068943e53.png)

Profile in question:
https://osu.ppy.sh/users/15240006/mania

Getting it also on other players, maybe its just a recent bug or im doing something wrong?
![image](https://user-images.githubusercontent.com/34809632/66356482-59ddee80-e96b-11e9-81c1-337f07eb0796.png)
Profile:
https://osu.ppy.sh/users/10674189

**Comment by peppy** [comment]
Likely regression.

**Comment by peppy** [comment]
Should be resolved (nginx misconfiguration).
