### ISSUE TITLE
difficulty icons should not consider invisible star rating

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#5080]
currently difficulty icons will consider the rating of a map beyond the 100ths decimal place

this means that in edge cases, maps that are supposedly the exact same SR will have different difficulty icons
examples:
https://osu.ppy.sh/beatmapsets/129299#osu/342711 I icon insane (4.00*)
https://osu.ppy.sh/beatmapsets/359191#osu/789818 H icon LV. 8 (4.00*)
https://osu.ppy.sh/beatmapsets/664182#osu/1673578 H icon Insane (4.00*)

https://osu.ppy.sh/beatmapsets/61207#osu/182774 N icon Hard (2.70*)
https://osu.ppy.sh/beatmapsets/50924#osu/161630 H icon Advanced (2.70*)
https://osu.ppy.sh/beatmapsets/62991#osu/186451 N icon Hard (2.70*)
https://osu.ppy.sh/beatmapsets/93958#osu/266534 H icon Hard (2.70*)

this inconsistency makes it additionally ambiguous where the boundaries of icons are supposed to be

also, imo, 2.70 exactly should be H icon, and 4.00 exactly should be I icon, because currently the majority of maps that currently display 2.70* and 4.00* display with H and I icons respectively.

applies to other difficulty icon boundaries as well.

**Comment by peppy** [comment]
Sounds correct.
