### ISSUE TITLE
Scores are not aligned properly with some names on mobile

### ISSUE THREAD

**Issue by Chiyozel** [ppy/osu-web#509]
![misscores](http://i.chiyozel.com/zZiIgGYZ)

Giving attention to ranks 36, 37, 40, 46, 49

**Comment by LiquidPL** [comment]
I guess this needs a separate design mostly because of stuff actually not fitting in such small width. 

Will you try to design something yourselves or should I come up with something on my own?

@peppy any thoughts?

**Comment by peppy** [comment]
start hiding more elements as they can't be displayed? ie. remove the least important stuff (#rank probably)

**Comment by peppy** [comment]
Also the size of the rank letters looks wrong..

**Comment by notbakaneko** [comment]
can anyone else see the image?

**Comment by LiquidPL** [comment]
image is dead yes

also, im 95% sure that this is related to the old beatmap info design

problem with scores right now is that not everything fits in one row in small widths; would probably require us to split stuff in two rows 🤔

**Comment by LiquidPL** [comment]
![](https://user-images.githubusercontent.com/991831/29195020-ab260630-7e2c-11e7-8dfb-083099987dd3.png)

Including a screenshot from the current production build (chrome devtools unfortunately, my Nexus 5X works fine apart from not displaying usernames, I don't really have any more actual devices to test with). Generally, given a small enough screen width, stuff will start expanding outside of the main container.

**Comment by notbakaneko** [comment]
just eyeballing, but I think it should fit if the left padding/margin isn't there
