### ISSUE TITLE
Loggng in via in topic reply feature

### ISSUE THREAD

**Issue by Sulker** [ppy/osu-web#51]
Was thinking of a feature which will make you being able to login when replying to a topic if not logged in.(If scrolled all the way down to the bottom of a thread). I was thinking of hopefully clicking a guest avat box in the reply prompt would open the login prompt to login and continue where we was last positioned
![2015-09-04_23-39-16](https://cloud.githubusercontent.com/assets/14132792/9697525/c5cfb9b8-535e-11e5-8124-9999666cad46.png)

Would be possibly easier to login if scrolled all the way to the bottom without access the to the top header (without clicking the fast scroll button I guess)

**Comment by MasterBugPatch** [comment]
Or, we could just set the profile picture to the guest image. Then when they press post and it pops up a login dialog, do you think that would be efficient too?

**Comment by claudiodekker** [comment]
This should be possible, since we could trigger the login using the post-button.

Basically, the way the login works is via AJAX, and when triggered, it keeps the triggering element in mind, clicking it after logging in. The way to trigger this is by adding the *js-login-required--click* class.

**Comment by nanaya** [comment]
Login link is always visible now and I think is good enough for this issue. Add comment if you think otherwise.
