### ISSUE TITLE
Cannot praise directly with suggestions nearby

### ISSUE THREAD

**Issue by Okorin** [ppy/osu-web#5105]
So if you intend to write a praise and link a timestamp where suggestions and issues are nearby you first have to confirm that "none of the posts address my concern" before praising whatever you wanted to praise

![img](https://i.imgur.com/C4zKqmT.png)

I dont think that makes a whole lot of sense because you didn't have a concern to begin with in that case

**Comment by nanaya** [comment]
For starter, there's no way of telling whether it'll be an issue or praise post.

And then maybe check if someone praised the same timestamp and add more comment to it instead?

**Comment by Naxesss** [comment]
Should probably only disable the Suggestion and Problem buttons in these cases.

![image](https://i.imgur.com/qd2TrJY.png)
