### ISSUE TITLE
Profile links with username appends ? to the end of url when loaded

### ISSUE THREAD

**Issue by tybug** [ppy/osu-web#5106]
Going to https://osu.ppy.sh/users/chocomint results in a url in the form of https://osu.ppy.sh/users/124493?. Going to https://osu.ppy.sh/users/124493 does not have this same issue.

**Comment by nanaya** [comment]
Weird behaviour by laravel. Wait how laravel/framework#30280 goes and then act accordingly.

**Comment by peppy** [comment]
Do we wait for the next laravel release now? Or make a temporary fix?

**Comment by nanaya** [comment]
Unless it's urgent I'd wait until next laravel release. Shouldn't take more than two weeks. Otherwise temporary fix it.

**Comment by peppy** [comment]
Let's just wait for it.
