### ISSUE TITLE
Swap "move to" and "hide deleted posts" button.

### ISSUE THREAD

**Issue by ghost** [ppy/osu-web#5107]
Every time I want to move a thread to another subforum I keep hitting the "hide deleted posts" button thats in its place. Swap them please.

![](https://flan.s-ul.eu/PgIV2DEk.png)

**Comment by peppy** [comment]
i don't understand why swapping the order is more logic or will fix this. also your buttons are different shapes, are you sure this isn't a browser plugin?

**Comment by E223** [comment]
Does it even make sense to move? I think we just need to get used to it. Also might be weird to swap them on forums with the additional tagging controls like Help/Feature Requests.

**Comment by peppy** [comment]
The bigger issue i see here is that the "hide deleted" is an icon that looks like "delete".

**Comment by peppy** [comment]
These have since been moved around. The "hide deleted" still looks like "delete" but alas, no one has complained recently so let's call this resolved?
