### ISSUE TITLE
Add operation result to beatmap favourite API endpoint

### ISSUE THREAD

**Issue by bdach** [ppy/osu-web#5108]
While reviewing ppy/osu#6416 I realised that the lack of the actual operation result in the response returned by the beatmap (un)favourite endpoint added in #5031 could potentially cause desync issues if the consumer assumes that the operation succeeded every time.

The count returned does not help here (could have changed through other API consumers anyway), so having the actual operation result (whether the beatmap has been added to or removed from favourites) would make consuming the endpoint more reliable.

**Comment by nanaya** [comment]
Looking at change in the client, shouldn't it just remember what the action being requested is? Success response from API means the request - favoriting or unfavoriting - succeeded...

**Comment by smoogipoo** [comment]
Suppose the beatmap is not favourited, but is visible in the client (along with the button). The user then clicks the favourite button on web, and then clicks the button in the client. How should the client know what state the button should be in?

**Comment by nanaya** [comment]
It'll be whatever the last request is. Favoriting a favorited beatmap (or the other way) is (mostly) a noop.

**Comment by peppy** [comment]
I guess if we're not interested in absolute correctness then the above information is enough. There's still potential for a race condition if the user has changed the state on two different clients, but the more correct way to resolve that may be to retrieve the full beatmap info again? Not sure.

**Comment by bdach** [comment]
Alright, going to close as something to be handled client-side.
