### ISSUE TITLE
All nominators get notifications when a problem is posted in a qualified map

### ISSUE THREAD

**Issue by Raidencio** [ppy/osu-web#5129]
Is this intended? Not every nominator is doing post-qualification work, it also notifies every single BN, other modes included, which is most of the times irrelevant. 

https://i.imgur.com/JjaFYS8.png

map in question:
https://osu.ppy.sh/beatmapsets/641775/discussion/1360771/timeline#/1218430

**Comment by venix12** [comment]
Would be nice to have an ability to disable those notifications I think.

**Comment by JBHyperion** [comment]
Should be an opt-in option as Raiden has said, ideally based on a Nominator's preferred game mode(s).

**Comment by peppy** [comment]
The first step was to add them, then we will dial them back to be usable to nominators. For those that these are useful for: are they in a good state with the current implementation?

**Comment by dorothy3242** [comment]
There also really should be a listing of all maps with open problems, currently you can remove a notification then forget about the map, with no good way to refind it.

**Comment by pimpG** [comment]
the notifications should not be removed automatically after you click them once, some kind of notification log would be great, and just differ read and unread notifications somehow.

**Comment by cl8n** [comment]
#4390 is probably what you're looking for

**Comment by pimpG** [comment]
yes

**Comment by peppy** [comment]
once this is added, it can govern whether disqualification is allowed by the BN or not.

implementation could be a new column in phpbb_user_group (nullable varchar with CSV or int) containing the valid modes.

**Comment by notbakaneko** [comment]
#5172 - added per-mode problem/disqualification notification options
#4390 - issue for read notifications
