### ISSUE TITLE
Convert difficulties should always be visible on beatmap pages

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#513]
Right now there's no way to see scores for convert difficulties (osu! standard maps played using a non-standard mode). They should be displayed in the difficulties list (possibly at half opacity) along with the native difficulties for other mode, should they exist.

bounty: 50-100

**Comment by LiquidPL** [comment]
should the converts be displayed after normal diffs, or can they be mixed up?

**Comment by peppy** [comment]
i feel like they should be before, personally (because osu! generally precedes other modes).

**Comment by peppy** [comment]
Awarding 80 bounty for this. :+1:
