### ISSUE TITLE
Auto recognition of osu related urls

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#5133]
In the old forums the urls were automatically recognized and shortened. The lack of recognition also makes the forum url parsing think the colon is part of this url `https://osu.ppy.sh/community/forums/posts/7244062:`, for example. So I'm forced to wrap urls in [url=...][/url] tags which bloats the bbcode content, and is very inconvenient.

**Comment by peppy** [comment]
Is the main issue here that the colon is included?

**Comment by abraker95** [comment]
Yes
