### ISSUE TITLE
Add the option to mods to pin/highlight comments

### ISSUE THREAD

**Issue by WalterToro** [ppy/osu-web#5138]
Pin/highlight comments (whatever you wanna call it) was on disqus and helped mods to give a short note, redirect people to other places as needed, etc. So it can be helpful for mods to give a notice about whats happening in a comment section for everyone to look at.

**Comment by peppy** [comment]
Should be admin only. Useful for change logs too.

**Comment by LiquidPL** [comment]
Gonna do this one.
