### ISSUE TITLE
"Show more" notifications is unintuitive

### ISSUE THREAD

**Issue by notbakaneko** [ppy/osu-web#5145]
- clicking "show more" doesn't indicate anything is happening
- notifications are grouped, but the "show more" button isn't - it's not clear what was updated

**Comment by nanaya** [comment]
I think I've already mentioned about the update performed not quite obvious :smiley:

**Comment by arflyte** [comment]
looked into notification designs few days ago. will finalise the fix soon.

**Comment by notbakaneko** [comment]
Grouping and loading of notifications was completely changed #5449
