### ISSUE TITLE
Clear all notifications doesn't clear all notifications

### ISSUE THREAD

**Issue by notbakaneko** [ppy/osu-web#5146]
Clicking clear all to clear all notifications of a group only clears the notifications loaded instead of all of them.
It should clear all; alternatively, it should clear the loaded ones and provide an option to clear all.

**Comment by nekodex** [comment]
It should be made obvious that this is what's going to happen - either by having the notification counts next to 'clear all' showing the total count and not just the displayed count (potentially related to #5145) or via some popup ala gmail when you delete based on a filter.

**Comment by nanaya** [comment]
Also note we don't currently return full count of each types anywhere.

**Comment by notbakaneko** [comment]
also changed in #5449
