### ISSUE TITLE
Embedded images in mp3 files

### ISSUE THREAD

**Issue by Striderin** [ppy/osu-web#5156]
I suggest an addition to the ranking criteria, that makes people strip unneeded embedded data from their audio files. Mp3 files can have embedded images, which is completely useless filler data for osu maps.
One can easily strip away images from the audio file with ffmpeg.

**Comment by dorothy3242** [comment]
Hi! This git-hub is meant for issues or suggestions for the website itself. To make a Ranking Criteria proposal, please see this forum:
https://osu.ppy.sh/community/forums/87

**Comment by TPGPL** [comment]
should be closed
