### ISSUE TITLE
Discussion links on old maps are broken

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#5161]
The "discussion" link on the information page of forum modding maps will link you to https://osu.ppy.sh/forum/t/##### which brings up this page since the old forums are turned off 
![image](https://user-images.githubusercontent.com/33286824/67355447-46af4f00-f525-11e9-83d4-12acd0523191.png)

should be fixed to link to the new forums instead (I'm surprised this isn't an automatic redirect?)

**Comment by peppy** [comment]
Should be fixed now.
