### ISSUE TITLE
"Hype" and "Report" buttons on beatmap information page are not the same size

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#5166]
![image](https://user-images.githubusercontent.com/33286824/67443108-85024800-f5d1-11e9-9c40-b8e8a60ed518.png)
Hype beatmap is just slightly thinner than Report beatmap, the result looks unpolished.

**Comment by nanaya** [comment]
Shouldn't be a problem anymore after moving all the buttons to the bottom area in #5857.

**Comment by venix12** [comment]
still a thing since it's beatmapset page, not the discussion
