### ISSUE TITLE
People who can DQ shouldn't see reporting info on beatmap info page

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#5167]
![image](https://user-images.githubusercontent.com/33286824/67443247-08239e00-f5d2-11e9-85e0-82ce7cb89efd.png)
I can't report beatmaps (only disqualify) and I am part of the team mentioned, so seeing this message on the info page doesn't make any sense. This has confused a few BNs into thinking that they should still be able to report maps since they could see the option mentioned here.

Those who can disqualify should have an alternate message,
"If you find an issue with this beatmap, please disqualify it here." and put a "Disqualify Beatmap"  button instead of "Report Problem"

**Comment by peppy** [comment]
As it's just messaging, I don't think this is super-high priority, but definitely can be fixed as time allows.
