### ISSUE TITLE
Check resolution on submitted entries in art contests

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#5175]
It would be very helpful to be able to set a desired width and height for art contests, as Fan Art ones in particular have stringent resolution requirements which often confuse discarded entrants during voting phase.

Perhaps adding such checks to the JSON field that handles landscaping and best-of toggles would be best here.

**Comment by Ephemeralis** [comment]
Just nudging this back up a bit - something like 90% of all entries that get bounced back are due to not meeting strict resolution requirements.

Checking this at upload would help negate a lot of frustration for entrants who often get distressed as to why their entry hasn't made the cut. I've got script contingencies to handle this, but we probably lose about 3-4 otherwise decent entries each contest due to this stuff.

**Comment by peppy** [comment]
Still low priority compared to other tasks. As a temporary solution, you could check the entries a couple of days before the deadline with your script and let people know.

**Comment by Ephemeralis** [comment]
The checking a few days before is already the case, for what it's worth!

**Comment by Ephemeralis** [comment]
Addressed in #9243.
