### ISSUE TITLE
Nominators shouldn't receive notifications on disqualified beatmaps

### ISSUE THREAD

**Issue by rorre** [ppy/osu-web#5184]
Currently, disqualifying a map notifs the entire BNG, as shown in this image below.
![IMG_20191026_053231](https://user-images.githubusercontent.com/6541445/67608448-7030da80-f7b2-11e9-8ced-43a14497066c.jpg)
[Discussion linked](https://osu.ppy.sh/beatmapsets/1002819/discussion/-/generalAll#/1232171)

This should not ping entire BNG because it is no longer qualified and its pretty useless to notif as its most likely not going to have a huge discussion, just the mapper needs to fix something.

This also against the idea of "reporting qualified beatmap" as it is no longer qualified, and its no longer a report because its already disqualified. Disqualification happens mostly due to issues that already present that needs to be fixed before continuing to be in qualified/ranked, so there is no need to ping the BNG again once its disqualified.

**Comment by peppy** [comment]
Settings are coming to turn off these notifications if you don’t want to see them.

**Comment by notbakaneko** [comment]
#5907 adds an option to enable/disable notifications for beatmap modding as a whole, but given this issue, it sounds like splitting the option up into more types would be better?

**Comment by nanaya** [comment]
Check #5916 for a bit more discussions.

**Comment by nanaya** [comment]
Option added in #5907.
