### ISSUE TITLE
Allow Bundled Maps in Most Played 24 Hours Again

### ISSUE THREAD

**Issue by VINXIS** [ppy/osu-web#5185]
Since the issue that people had years ago of bundled maps being only a couple or so beatmaps, and would always be dominating the most played section is gone now, I would vouch for allowing them back in most played since it's definitely fair game now that the nature of bundled maps have changed and everything (unless they already are allowed in the most played section). 

Just to be clear, referring to this area:
![image](https://user-images.githubusercontent.com/18523454/67628030-92fbd700-f824-11e9-8468-7c1f77f574e3.png)
![image](https://user-images.githubusercontent.com/18523454/67628032-98592180-f824-11e9-99e6-230d66f50fbc.png)

**Comment by peppy** [comment]
We are actually reworking most played algorithm to avoid stagnant display. Will continue tracking here https://github.com/ppy/osu-web/issues/2730
