### ISSUE TITLE
Wiki subtext is flyte design wank

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#5188]
![image](https://user-images.githubusercontent.com/191335/67637411-c66e5c80-f91d-11e9-8814-642667cb68c4.png)

this should be changed to something that isn't wank.

@arflyte please stop using wank in your designs because people will implement and merge them at face value.

**Comment by tybug** [comment]
I personally thought the text in question was humorous, but understandably not ideal depending on how official/formal the osu!wiki is meant to be. A couple suggestions:

* "anything you need to know about osu!"
* "the answers to your questions lie within"
* "enlightenment on all things osu!"

**Comment by peppy** [comment]
i like the third 3. or just something mentioning that it's community curated resources

"A wealth of community curated resources to guide you in your osu! journey"

**Comment by arflyte** [comment]
...I was actually pretty serious with that subtext lol.

**Comment by TPGPL** [comment]
should be closed as the subtitle is no more with the new header design?

![image](https://user-images.githubusercontent.com/19843905/71325375-203d6e00-24ec-11ea-9803-c3cdab8ab9b8.png)
