### ISSUE TITLE
2FA for authentication

### ISSUE THREAD

**Issue by solehudin-baharsah** [ppy/osu-web#5197]
good afternoon
I have a suggestion for two-factor authentication (2FA) to make it easier for osu players! and prevent the sale of accounts and any of rule-breaking rather than receiving a verification code.
I ask for your attention so that this can be realized
as for the cons of this, can give a reason
thank you

**Comment by LiquidPL** [comment]
Duplicate of #5163.

**Comment by solehudin-baharsah** [comment]
I Am sorry for this. but is avail now

**Comment by STCapricorn** [comment]
Duplicate of #5163

**Comment by solehudin-baharsah** [comment]
@LiquidPL but  2FA authentication can replace email verification for changing password?

**Comment by solehudin-baharsah** [comment]
2FA I mean is similar to Google authentication
Barcode scan or type Token and done!

**Comment by solehudin-baharsah** [comment]
I Am sorry for my bad english.
