### ISSUE TITLE
Unexpected API response

### ISSUE THREAD

**Issue by hallowatcher** [ppy/osu-web#5223]
Hey!

I run the pickem site over at https://pickem.hwchr.com and I believe it has been blacklisted from making API requests to the osu page.

Every time someone tries to log in, 2 requests are done - one to `https://osu.ppy.sh/api/v2/me` and one to `https://osu.ppy.sh/api/v2/friends`

When this happens, the console just spits out Internal server error because I believe the promise is being rejected.

![image](https://user-images.githubusercontent.com/6265839/68073234-29347d80-fd8e-11e9-96e2-dcfbb09897a0.png)

I think it is worth looking into on your side.

The IP when pinging pickem.hwchr.com is `207.154.192.33`

Here's the OAUTH client information:

```
{
    "id": 22,
    "name": "pickem",
    "password_client": false,
    "personal_access_client": false,
    "scopes": null,
    "user_id": 1874761,
    "redirect": "https://pickem.second-circle.net/api/auth/callback",
    "secret": ""
}
```

note that `https://pickem.second-circle.net` is an alias for `https://pickem.hwchr.com`

**Comment by cl8n** [comment]
500 on your end means you need to look into it, log the responses from osu! and catch the promise / log the errors there too

**Comment by hallowatcher** [comment]
alright, i'll do that and report back

**Comment by hallowatcher** [comment]
everything seems to be working normally after I created this since the traffic isn't as much as when it launched

it can be closed for now
