### ISSUE TITLE
Prevent 'autoplay' in [youtube] BBCode tag

### ISSUE THREAD

**Issue by E223** [ppy/osu-web#5224]
There is a little sentence that tells people not to do this in the official game [rules](https://osu.ppy.sh/help/wiki/Rules), but it's probably better if it wasn't even possible to do at all.
> Don't post advertisements, referral links or any other annoying or intrusive content... **Autoloading or autoplaying content/embeds falls within this rule as well.**

I believe it is also possible to set a YouTube video to autoplay and then effectively hide the player itself using some of the other parameters, basically making it impossible (or really difficult) to stop the video from playing. So, maybe no extra parameters should be allowed.

**Comment by peppy** [comment]
I thought we were already doing this?
