### ISSUE TITLE
Allow guest access to comments API

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu-web#5225]
Currently it's not possible to get comments via API in you are not logged in.

**Comment by bdach** [comment]
Are you sure? Seems to be working for me when I test with postman, and I'm pretty sure I didn't do anything to authenticate:
![image](https://user-images.githubusercontent.com/20418176/68087303-ca860700-fe54-11e9-9800-a938f90cb489.png)

**Comment by EVAST9919** [comment]
> Are you sure? Seems to be working for me when I test with postman, and I'm pretty sure I didn't do anything to authenticate:
> ![image](https://user-images.githubusercontent.com/20418176/68087303-ca860700-fe54-11e9-9800-a938f90cb489.png)

`try to use osu.ppy.sh/api/v2/comments...`

**Comment by bdach** [comment]
Ok, sorry, you're correct, the `api/v2` comments endpoint does require basic auth.
