### ISSUE TITLE
The user's latest medal is cut off on the bottom

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu-web#5233]
The most recent medal of a user looks cut off on the bottom:
(Probably similar to https://github.com/ppy/osu-web/issues/562, but in a different area)

![Medals](https://user-images.githubusercontent.com/43073074/68119736-c238d500-ff03-11e9-96c9-750f4a796686.png)

**Comment by bdach** [comment]
Looks like the actual exported asset is lacking a drop shadow in comparison to the others, which contributes to this, but additionally I think line-height is interfering a little bit, at least on Firefox 71.0b6 ([see video](https://streamable.com/ufav0) - notice how the image position drops slightly downwards before setting `line-height: 1;`).

**Comment by Ephemeralis** [comment]
The exported assets lacking a drop shadow is an intentional choice from the designer (flyte) on the past set. I originally thought the fact that the newer exports being significantly larger (193x210 vs 110x119 for 1x) might factor in here, but it doesn't appear to make a difference via inspect element.

**Comment by Naxesss** [comment]
Looks like there's some shenanigans going on with line-height causing the flex to try to accommodate for it. Setting `line-height: initial` to `.page-extra__recent-medals` seems to fix it.

![image](https://i.imgur.com/Yjr1uz7.png)

However the lack of a drop shadow makes the new design larger than the old ones which looks a bit odd.

**Comment by peppy** [comment]
I've fixed this one.
