### ISSUE TITLE
Gifs as profile picture

### ISSUE THREAD

**Issue by CykaZero** [ppy/osu-web#5235]
Would be really cool to have gifs as profile pictures! Maybe a supporter-only feature? Like with discord nitro

**Comment by venix12** [comment]
It's already a thing I believe?

**Comment by Xinnoh** [comment]
it is
must be uploaded as a .png file and not have "gif" in the title because the site automatically rejects gifs, but it technically works.

**Comment by nanaya** [comment]
> must be uploaded as a .png file and not have "gif" in the title because the site automatically rejects gifs, but it technically works.

Which part are we talking about? I just checked using gif for both avatar and profile header and they work just fine?

**Comment by Xinnoh** [comment]
o, rules probably changed for the new site.
for the old site it was like that.

**Comment by Xinnoh** [comment]
uh i tried setting a gif as my profile, doesn't seem to work on the new website.
seems to be a bit picky with what it accepts and it's really unclear?
image 1 does not work, image 2 does work, I went through the same compression process for both of them.
![animate](https://user-images.githubusercontent.com/30382015/68988717-91ed1280-07f0-11ea-82ec-743a6b63b075.png)
![sandy_yey](https://user-images.githubusercontent.com/30382015/68988718-93b6d600-07f0-11ea-94a3-9db090180062.png)

**Comment by nanaya** [comment]
There's 100kB limit. Anything over that will be converted.
