### ISSUE TITLE
Rankings chart endpoint is missing hit_accuracy

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu-web#5252]
![Screenshot_3](https://user-images.githubusercontent.com/22874522/68300950-ecc79100-00af-11ea-95a6-9e3f920120bb.png)

**Comment by cl8n** [comment]
charts don't store those values, this seems correct

**Comment by EVAST9919** [comment]
Looks like web uses `accuracy` instead of `hit_accuracy`, which is not included in API response anyway

**Comment by peppy** [comment]
So the main issue here is missing accuracy, correct?

**Comment by EVAST9919** [comment]
Well, yes. But not every property in `UserStatistics` is nullable, so it might require some refactoring osu-wise
