### ISSUE TITLE
Ranked Beatmaps (Archived) Subtitle

### ISSUE THREAD

**Issue by roansong** [ppy/osu-web#5261]
https://osu.ppy.sh/community/forums/14
Currently the subtitle is 

> Ranked beatmap threads reside in here. Archived for prosperity.

Typically "posterity" would be used instead of "prosperity". I'm curious if this is the intended meaning or if there is an inside joke related to this? Ranked beatmaps do provide **p**ros**p**erity after all.

**Comment by peppy** [comment]
Resolved, thanks.

**Comment by roansong** [comment]
@peppy the subtitle has been updated to "prosterity" instead of "posterity" - now I'm really not sure if that's a typo or an amalgamation of the two

**Comment by peppy** [comment]
Fixed again, moving too fast.
