### ISSUE TITLE
number of friends on profile is incorrect

### ISSUE THREAD

**Issue by cub01d** [ppy/osu-web#5262]
![image](https://user-images.githubusercontent.com/1859568/68466096-913cf680-01c8-11ea-9676-035c0201f659.png)

![image](https://user-images.githubusercontent.com/1859568/68466045-7c606300-01c8-11ea-9f32-b54b29952462.png)

I'm pretty sure I only have 1 friend, not sure why it's showing up as 3 in the other view.

**Comment by LiquidPL** [comment]
The first number is the amount of your followers (as in users that have friended you).

**Comment by nekodex** [comment]
The tooltip on the profile page should probably say 'followers' instead of 'friends' to make this less confusing
