### ISSUE TITLE
Some ranked beatmaps doesn't show up when searching

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu-web#5266]
This bug is only happens on the new website.
When I search for "Euphorium" or "Dored", this map (https://osu.ppy.sh/beatmapsets/779047) doesn't show up in the search result. This bug also affects osu!lazer's osu!direct searching (but not osu!stable's osu!direct).
Another affected beatmap is https://osu.ppy.sh/beatmapsets/740862

**Comment by peppy** [comment]
Checking on these beatmaps, they are intentionally excluded from the search index for one or more reason (matching an ignored term). This is intended behaviour.

**Comment by cl8n** [comment]
if these are hidden without any notice I feel like there should be an account setting to show (potentially) nsfw results?

**Comment by peppy** [comment]
This is a system level list maintained for compliance reasons, not NSFW. Hope that makes it understandable.
