### ISSUE TITLE
Reduce size of licence header

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#5267]
While AGPLv3 recommends adding the full text as we are doing to every file it is overly cumbersome. This is luckily only a recommendation.

![image](https://user-images.githubusercontent.com/191335/68518632-24ad1f00-02d0-11ea-89b3-0f3f62350028.png)

A minimal licence header - in line with our licence headers in other projects - is enough to satisfy their minimum criteria.

Proposal:

```
// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the GNU Affero General Public License v3.0.
// See the LICENCE file in the repository root for full licence text.
```

**Comment by notbakaneko** [comment]
How do I upvote issues

**Comment by Bryanpedini** [comment]
> How do I upvote issues

It's simple, fellow:
- notice the blue emojy on the top bar of the first message
- click on it
- click the thumb up icon
- done, congrats

### PS:
###### I'm not paid enough to teach kids how to use the internet.........
###### GitHub, this is for you: add a "suicide_me" emojy face to append to useless idiotic messages
