### ISSUE TITLE
Latest Post preview missing in Resolved Issues subforum

### ISSUE THREAD

**Issue by E223** [ppy/osu-web#5289]
For the past few days the "Latest Post" preview has been blank for the [Resolved Issues](https://osu.ppy.sh/community/forums/29) subforum.
![](https://death.s-ul.eu/eeOHRsCg.png)

Might be related to threads that get automatically moved when they are tagged in the main Help forum because I believe it fixes itself temporarily when someone posts in Resolved Issues or a thread is moved into there manually.

**Comment by peppy** [comment]
As suspected, this is likely a `web-10` component. Honestly not sure I will fix this, as it's going to be a treasure hunt deep into phpbb.

**Comment by peppy** [comment]
Has this happened recently?

**Comment by peppy** [comment]
Going to close for now.

**Comment by E223** [comment]
Forgot this was still open. It seems to have been resolved at some point.
