### ISSUE TITLE
Gulp Watch not working

### ISSUE THREAD

**Issue by kschamplin19** [ppy/osu-web#529]
This has been discussed for a while, but no real solution has been sought. At first, it seemed to be a limitation of the vagrant user, and gulp could not watch **all** the files (why it needs to do this is beyond me). This could be fixed with a simple command that raised the limit of watched files in the filesystem. However, that caused more errors later on (but it did work for a little bit). The root of the error, as far as I can tell, is the .version command, because it introduces a race condition (explained [here](https://github.com/laravel/elixir/issues/126#issuecomment-157761804)). I don't know enough about elixir to solve this, but any solutions I have tried did not solve it.

**Comment by nekodex** [comment]
This seems to be a vagrant issue, not an osu-web issue. We no longer support or recommend vagrant, so we suggest looking at an alternative setup.
