### ISSUE TITLE
Latency with user actions on mobile

### ISSUE THREAD

**Issue by ghost** [ppy/osu-web#530]
I am using Firefox on Android. Most of the elements on the website have up to about 3 second latency until they respond to user actions. For example, tapping on the achievments in the profile can take up to 3 seconds for the description to show up. Same with the menu in the top right corner and many other stuff.

**Comment by nanaya** [comment]
Which phone/tablet/etc are you using? Have you tried with Chrome?

**Comment by abraker95** [comment]
I am using the S5 phone.

Just tried chrome, it's a lot more responsive there (only slight latency).

**Comment by nanaya** [comment]
I don't think it's specific to mobile, just the site being generally slow (and worse on firefox android)  :dancer:
