### ISSUE TITLE
If an email verification is required when using OAuth, it breaks the redirect back to the site

### ISSUE THREAD

**Issue by Coppertine** [ppy/osu-web#5308]
Title is self explanitory

But after logging into mappersguild using the Oauth method, it required me a verification
https://cdn.discordapp.com/attachments/551236835045670927/646828747927978026/unknown.png

After that is completed I got this message and didn't get redirected to mappersguild
![image](https://user-images.githubusercontent.com/37494321/69281158-8ad06500-0c33-11ea-9389-d955e7b1a6d7.png)

**Comment by nanaya** [comment]
Did you check the original page? At the moment, the verification link doesn't do any redirect after opening it.

**Comment by nanaya** [comment]
It's as intended as per previous reply.
