### ISSUE TITLE
Horizontal line on the middle of profile page cover image

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#5311]
![](https://puu.sh/EGY2D/f3c4d8d623.png)

Wasn't like that before. Range is https://web.archive.org/web/20190613092747/https://osu.ppy.sh/users/124493 to https://web.archive.org/web/20190722212946/https://osu.ppy.sh/users/124493

**Comment by peppy** [comment]
Can you confirm this on multiple browsers?

**Comment by Joehuu** [comment]
Yes, chrome and edge.

**Comment by notbakaneko** [comment]
It's caused by a change to the gradient to make the text more readable when the user profile image is a similar colour as the text.
The gradient used to be dark -> transparent, but it's now dark->transparent->dark which causes the 'line' in the middle

**Comment by peppy** [comment]
@arflyte see above, this looks bad as-is.

**Comment by arflyte** [comment]
Looking into a quick fix.

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu-web/issues/4201 (made before gradient change). Closing as this issue was seeking a revert, but the previous gradient didn't work too.
