### ISSUE TITLE
Change logic for popular beatmaps on frontpage to increase natural variety and prevent congestion

### ISSUE THREAD

**Issue by Striderin** [ppy/osu-web#5317]
First of all, I wish there was proper documentation (at least more easily findable) for how the popular beatmaps section even works. Based on observation, I assume it works the following way: it lists the beatmaps ranked within the last month, sorted by how many favorites they have in total.

However, this means that we're almost guaranteed to see the same map on top of the list for an entire month. And now we have an edge-case scenario where a loved beatmap was ranked (Ghost Rule), and thus it defaulted to being the top position because it already had 2k+ favorites when it was ranked.

So, I suggest implementing the following change:
Change the logic such that maps are sorted by how many *new* favorites a beatmap has gotten within a certain time period (I personally think a shorter time like a week - or even just 24 hours - would be better in order to allow greater variety in the section and prevent congestion by giants). There could then still be a hard 1-month cutoff for which maps are even tracked and considered. This way there would be a more natural shift in the list, as really popular beatmaps would stay at the top for a while, but then gradually shift downwards instead of suddenly disappearing from one day to the other. I think this would be much more representative of what a recently "popular beatmap" is.

Implementation suggestion:
It would require the implementation of a way to keep track of what count as "new" favorites. Putting time-stamps on favorites could work. Doing this could also allow for something cool like making new favorites show up in a player's "Recent" profile timeline alongside the usual stuff. Then it could also become part of the API somehow.

**Comment by Striderin** [comment]
Additionally, I suggest changing the name of the list to "Recently popular beatmaps" to more properly describe it.

**Comment by peppy** [comment]
Definitely think this is a step forward, and kind of what we planned. Will require database / logic changes, though.
