### ISSUE TITLE
File MD5 from the api appears to differ from osu files extracted from downloaded osz; possibly caused by stale downloads

### ISSUE THREAD

**Issue by Eugenio-Bruno** [ppy/osu-web#5327]
Here's something the API (v1) returns:

```
{"beatmapset_id":"420","beatmap_id":"2041", ... "file_md5":"eebf77f343e3106c88710986153d3588", ...},
```

If you download this beatmap from [here](https://osu.ppy.sh/beatmapsets/420#osu/2041), open it with osu, and take the md5 of the resulting file:

```
>>> print(hashlib.md5(open("E:\\nobackup\\OsuSongs\\420 Nintendo - Here We Go!\\Nintendo - Here We Go! (eyup) [Hard].osu", "rb").read()).hexdigest())

3863f6ad53e3139d876c084cd16ff758
```

So the MD5 is different. If you then go into the client and search for this map, you'll notice that even though you *just* downloaded it, it asks you to update the map to the newest version to see the leaderboard. If you go ahead and update, then the md5 is actually the same a what originally returned by the api:

```
>>> print(hashlib.md5(open("E:\\nobackup\\OsuSongs\\420 Nintendo - Here We Go!\\Nintendo - Here We Go! (eyup) [Hard].osu", "rb").read()).hexdigest())

eebf77f343e3106c88710986153d3588
```

This might be caused by maps that have been updated, but the download servers serve the *old* version of the map.

This does not happen with every map.

**Comment by peppy** [comment]
This is correct. Some osz contain outdated osz files. This isn't an API issue and will eventually be fixed (it's on my list).
