### ISSUE TITLE
Cook Islands missing flag

### ISSUE THREAD

**Issue by xenallio** [ppy/osu-web#5330]
Cook Islands is missing their flags on new website and is currently a '?'.

old site : https://osu.ppy.sh/p/pp?c=CK
new site : https://osu.ppy.sh/rankings/osu/performance?country=CK
forum topic (I think that's what he means) : https://osu.ppy.sh/community/forums/topics/988871

**Comment by peppy** [comment]
As there's only three users, it may make more sense to remove this as a recognised country.
