### ISSUE TITLE
Chat message notifications need better handling

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#5351]
Every private message I receive in-game also gives a notification on the website despite the fact I am actively replying to them in-game, which is very spammy and redundant.
![image](https://user-images.githubusercontent.com/33286824/69833587-dae69300-1202-11ea-8e96-c460f389a0d5.png)
![image](https://user-images.githubusercontent.com/33286824/69833620-16815d00-1203-11ea-99d6-ca5baf0747e8.png)

on top of that, the website clearly knows i'm sending responses because my messages show when i open the website chat
![image](https://user-images.githubusercontent.com/33286824/69833616-0ff2e580-1203-11ea-84cf-f6479134cc52.png)

Notifications for a chat should be erased if the user receiving the notification has responded to to solve this issue. This way messages you have not responded to would still leave website notifications as a reminder, but ones that you've responded to don't have pointless extra notifications on the web.

**Comment by peppy** [comment]
See https://github.com/ppy/osu-web/issues/4896.

**Comment by qcl12345** [comment]
I don't think #4896 actually addresses this issue with its current working though. 

Unless having chat opened in game will automatically mark messages read on the website, you would still need to go and explicitly open the website to mark the notifications read to get them to disappear, which is really annoying.

**Comment by peppy** [comment]
It's a prereq to adding in-game support.
