### ISSUE TITLE
Signing in on mobile is unintuitive

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-web#5353]
The menu bar just shows a blank avatar:

![image](https://user-images.githubusercontent.com/1329837/69841002-e092b600-12a0-11ea-85ae-284dfe05564d.png)

The dropdown menu doesn't have any option to sign in:

![image](https://user-images.githubusercontent.com/1329837/69841014-edafa500-12a0-11ea-92ec-70c54fcd6d34.png)

And even worse, the `> profile` subsection of the menu lists items without even being logged in:

![image](https://user-images.githubusercontent.com/1329837/69841025-fd2eee00-12a0-11ea-97b8-330fc3f467b3.png)

**Comment by nanaya** [comment]
how about this? @arflyte 

![](https://s.myconan.net/2020-08/firefox_2020-08-04_20-44-44.png)

**Comment by arflyte** [comment]
Yeah, "sign in/register" should be okay for now, although I can't imagine anyone registering on mobile tho.
