### ISSUE TITLE
Tilde (~) symbol doesn't display correctly on modding discussion

### ISSUE THREAD

**Issue by Baron9876** [ppy/osu-web#5355]
When applying or leaving mods on a discussion I commonly use "~" to signify around that value however recently it doesn't [display as intended](https://i.imgur.com/PHJfvz5.png). Zooming out or in to the webpage makes the symbol appear [correctly](https://i.imgur.com/mWx52AE.png). Haven't experienced this anywhere else on the site.

**Comment by notbakaneko** [comment]
what browser and zoom level are you using?

**Comment by notbakaneko** [comment]
actually, this appears to be an issue in `Open Sans`

**Comment by Joehuu** [comment]
Open Sans is not used anymore. Can be closed.
