### ISSUE TITLE
[Question] Why doesn't "generate-localizations.js" use fs to make the directory?

### ISSUE THREAD

**Issue by GingkathFox** [ppy/osu-web#5358]
Line: https://github.com/ppy/osu-web/blob/5b413ac15f9383c442409c502fbb2d111ae171e4/generate-localizations.js#L73

`fs` has `fs.mkdirSync`, why not use that instead of requiring a second module?

**Comment by cl8n** [comment]
mkdirp also makes any parent directories that are missing

**Comment by GingkathFox** [comment]
```
fs.mkdir('/tmp/a/apple', { recursive: true }, (err) => {
  if (err) throw err;
});
```
> The optional options argument can be an integer specifying mode (permission and sticky bits), or an object with a mode property and a recursive property indicating whether parent folders should be created. Calling fs.mkdir() when path is a directory that exists results in an error only when recursive is false.

**Comment by notbakaneko** [comment]
because `recursive: true` is a `node.js 10.12+` feature and we weren't running 10.12+ at the time.

**Comment by GingkathFox** [comment]
oh, ok. Opening a pull request then.
