### ISSUE TITLE
Strange empty wiki search result

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#5366]
the last result here is empty, and the link's casing doesn't match anything on the wiki. I'm not sure what causes this
![52788b](https://user-images.githubusercontent.com/9954349/70043704-c9d8b180-1575-11ea-8653-b26c6925e83f.png)

https://osu.ppy.sh/home/search?mode=wiki_page&query=mp7k

**Comment by notbakaneko** [comment]
looks like the redirect being indexed and searchable when it shouldn't be

**Comment by cl8n** [comment]
this is a much better example https://osu.ppy.sh/home/search?mode=wiki_page&query=main%20page . looks like the problem is more than redirects
