### ISSUE TITLE
Comments endpoint returns empty "user_votes" even if it not suppose to be empty

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu-web#5378]
Example:
web (pretty obvious I have voted comments):
![Screenshot_1](https://user-images.githubusercontent.com/22874522/70228399-5c8b7300-1765-11ea-806d-4b7ddc5ac470.png)
api response:
![Screenshot_2](https://user-images.githubusercontent.com/22874522/70228465-72993380-1765-11ea-87bf-bdb7164e20f3.png)

**Comment by notbakaneko** [comment]
show the whole response, not a tiny screenshot snippet of it

**Comment by EVAST9919** [comment]
> Show the whole response, not a tiny screenshot snippet of it; also include the request params.

Request params: `commentable_type=beatmapset&commentable_id=41823`
Response: [Response.txt](https://github.com/ppy/osu-web/files/4000014/Response.txt)

**Comment by notbakaneko** [comment]
It looks like you're not sending the request as an authenticated user; `user_votes` is always empty for unauthenticated requests

**Comment by EVAST9919** [comment]
I'm using client API request and this issue wasn't a thing before comments became a guest request (I guess)
