### ISSUE TITLE
Messages go through the website when "don't receive messages from non friends" is ticked

### ISSUE THREAD

**Issue by Karthyz** [ppy/osu-web#5379]
I'm assuming this is the case since my inbox has been flooded on the website since the chat update / offline messages was implemented. I guess they're not being blocked anymore and are just being treated as an offline message instead?

I think being able to receive messages sent through the website from non friends is useful, just not when sent from in game as the vast majority of ones sent in game are just spam.

**Comment by notbakaneko** [comment]
you want to be able to receive messages from non-friends on the website but not in game?

**Comment by peppy** [comment]
Right now the web apis are bypassing the user's in-game setting (not persisted to database) to block PMs from non-friends.

Not sure how/if this can be resolved, but needs to be discussed. @Karthyz for now we recommend you the the "block" setting on your [settings page](https://osu.ppy.sh/home/account/edit).

**Comment by Karthyz** [comment]
> you want to be able to receive messages from non-friends on the website but not in game?

I'd prefer if it were as it was before where you can receive messages sent FROM the website (by non friends) but not from in game.


> Not sure how/if this can be resolved, but needs to be discussed. @Karthyz for now we recommend you the the "block" setting on your [settings page](https://osu.ppy.sh/home/account/edit).

Thanks, didn't know this existed. It's a means to stop the spam.

**Comment by nanaya** [comment]
I think this has been fixed client-side? @peppy

**Comment by peppy** [comment]
Client and server are now synchronised, should be fixed.
