### ISSUE TITLE
Notifications for issues on qualified beatmaps are not working

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#5380]
I have notifications enabled for all modes, but have only been receiving disqualification notifications in osu!taiko beatmaps for the past couple of weeks. This obviously isn't right, as standard beatmaps get disqualified on a much more regular basis. 

I do not know right now what's causing it, but other users apparently have not been receiving these notifications recently as well. This is a serious issue because this means beatmaps that should be sending notifications when issues are posted may be having their issues go unnoticed.

**Comment by nanaya** [comment]
@dorothy3242 can you check if it's still a problem?

**Comment by dorothy3242** [comment]
Reports are showing up now for posted problems on all modes of beatmaps made by regular users which is a good thing. It seems disqualification notifications are still working inconsistently though. For example I was notified of this mania map being disqualified earlier https://osu.ppy.sh/beatmapsets/923321/discussion#/1301239 but not this https://osu.ppy.sh/beatmapsets/1045019/discussion#/1301450 standard map being disqualified later today.

**Comment by nanaya** [comment]
@dorothy3242 can you confirm again?

**Comment by dorothy3242** [comment]
Appears to be working by comparing notifications and https://osu.ppy.sh/beatmapsets/beatmap-discussions?user=&beatmapset_status=qualified&message_types%5B%5D=problem&only_unresolved=on for the past two weeks.
I'll reopen if issues reoccur.
