### ISSUE TITLE
Removing in-game chat notifications that pops up on the new website

### ISSUE THREAD

**Issue by frukoyurdakul** [ppy/osu-web#5381]
While it seems to be a good idea to be able to chat with somebody directly from the website, for users who don't want to receive notifications such as me, it would be better to put an option to the "Settings" page under "Notifications" tab, about disabling them. After talking to somebody in game and actually reading the messages,  seeing 100 notifications about it doesn't seem to make sense that much.

It would be better to mark those as read and not show on the website, or put an option to receive in-game chat texts as notifications.

**Comment by cl8n** [comment]
#4896 , in-game notifications will be marked as read

**Comment by peppy** [comment]
There is currently work in progress to fix this. Will continue tracking on #4896.
