### ISSUE TITLE
New and old website sort plays differently

### ISSUE THREAD

**Issue by mangomizer** [ppy/osu-web#5382]
![image](https://user-images.githubusercontent.com/30021847/70286335-b8381980-17c2-11ea-8c96-0a4f6e74b54f.png)
![image](https://user-images.githubusercontent.com/30021847/70286318-a5254980-17c2-11ea-8ec0-11d762ca4578.png)

My top 2 plays are both worth 499.484pp. Their order is different depending on the website though. I have no idea what's causing the issue, only that there is an issue.

**Comment by mangomizer** [comment]
Just realised this is the case for 4th, 5th and 6th plays, which are all worth 499.449.
Order on new website: atomosphere -> more one night -> berry go
Order on old website: atomosphere -> berry go -> more one night

**Comment by peppy** [comment]
I'm not sure what is that stuff on the old website, but it looks to be an extension. We do not support this, sorry.

**Comment by mangomizer** [comment]
OK I reuploaded the screenshots without the osuplus extension, the order is still mixed up regardless.

Profile Link: https://osu.ppy.sh/u/1893718

**Comment by peppy** [comment]
Which ordering do you expect?

**Comment by mangomizer** [comment]
I mean 2 weeks ago I would've answered "just use a calculator to calculate the next 3 dp and then work it out from there". However, I recognise the chance of this happening is already extremely low, it's just common here because I have like 56 499pp plays lol.

Some person on reddit just told me that the ordering on the old website is sorted by score set date and the new website by beatmap id. Personally I can't see a reason to have one over the other. Maybe you should make a poll for it?

Originally, I would have logically assumed it would be alphabetically sorted, but then the old website does "artist - song name" while the new website does "song name by artist", so which do you prioritise first? Parameters such as SR/acc/mod combinations seem way too arbitrary to consider as well.

**Comment by peppy** [comment]
It should be date, not beatmap ID. so that would mean the new site is likely ordering incorrectly.

**Comment by mangomizer** [comment]
Is there any reason why old scores go on top? score ID wise it makes sense because sort by ascending, but surely it makes more sense for recent plays to "beat" older plays?

**Comment by peppy** [comment]
Generally that's not how any leaderboards work in osu!. Would be a paradigm shift to do so.

**Comment by mangomizer** [comment]
Ah, that makes a lot more sense actually
