### ISSUE TITLE
Show Mapper badge in beatmap comments section

### ISSUE THREAD

**Issue by smileyhead** [ppy/osu-web#5390]
Just a little something to help the mapper stand out a bit in the comments sections of their own maps.

**Concept:**

![image](https://user-images.githubusercontent.com/15932372/70471076-c8a30980-1acc-11ea-8bbd-68d8164bc293.png)

**Comment by peppy** [comment]
Should be a simple but effective one

**Comment by arflyte** [comment]
![Figma_200309-182122](https://user-images.githubusercontent.com/3632750/76199217-d171bb80-6232-11ea-9ba1-94e22692b9e9.png)

inverted, to not be confused with usergroup tag. L1 colour, B5 text.
