### ISSUE TITLE
Beatmap comments cannot handle Zalgo text overflow

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#5398]
![](https://puu.sh/EOde5/db85c9e3a5.png)

Source map in question: https://osu.ppy.sh/beatmapsets/1077085#osu/2253921

**Comment by peppy** [comment]
This character range should be blacklisted / automatically removed.

**Comment by bdach** [comment]
I'm not sure that is a viable route to go down. "Zalgo text" is essentially just spamming valid character modifiers. I'd have to look, but some languages might natively depend on those to display diacritics, which then will lead to these users being unable to use their alphabet fully (I'd suspect something like Vietnamese might be an especially bad example of this).

Perhaps Unicode normalisation can get rid of invalid combinations and keep those ones that make sense, by merging ASCII chars and modifiers into single valid Unicode code points. Not sure.

**Comment by InvisibleSymbol** [comment]
fyi this should be handled everywhere, not just in the beatmap comments.
Example: ![](https://i.fiery.me/INXz0.png)
