### ISSUE TITLE
Invalid link on https://osu.ppy.sh/beatmaps/artists/23

### ISSUE THREAD

**Issue by geotim90** [ppy/osu-web#5408]
Under "RECORD3-TRANCE", the "Holy Winter #3" download link does not URL encode the `#` character. It currently links to `https://assets.ppy.sh/artists/23/osz/Cranky%20-%20Holy%20Winter%20#3.osz` (does not work) instead of `https://assets.ppy.sh/artists/23/osz/Cranky%20-%20Holy%20Winter%20%233.osz` (works)

**Comment by geotim90** [comment]
Same issue with `https://assets.ppy.sh/artists/23/osz/Cranky%20-%20Phantom%20Pianist%20-session%20#1.osz` on the same page, which should be `https://assets.ppy.sh/artists/23/osz/Cranky%20-%20Phantom%20Pianist%20-session%20%231.osz` instead.

**Comment by Ephemeralis** [comment]
This has been fixed, thanks for pointing it out! All links should function correctly and the rest of the library was checked for similar issues with none found.
