### ISSUE TITLE
BBCode sublists shouldn't have smaller font

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#5412]
lists within lists have 0.85em size, that's just an odd design choice imo. sublists usually do not change the font size

**Comment by peppy** [comment]
Can you include a screenshot for reference?

**Comment by cl8n** [comment]
![861698](https://user-images.githubusercontent.com/9954349/70895882-94d05400-1fa4-11ea-9ae3-679901f2729a.png)
put example of block quotes too since they do a similar thing
