### ISSUE TITLE
Avatar change results in an "Unknown error occurred"

### ISSUE THREAD

**Issue by luthienelentari** [ppy/osu-web#5414]
I tried changing my profile picture and Error keeps on occuring, the picture meets all the requirements for uploading what is happening xD

Here is the picture im  trying to uploading and the error 
![avatar-13549](https://user-images.githubusercontent.com/58868580/70841346-d4057600-1de7-11ea-9f30-9ccceaf41033.jpg)
![9742aa0edf8f36dcc1b4eddef153cc56](https://user-images.githubusercontent.com/58868580/70841349-d5cf3980-1de7-11ea-84f2-ccc51e64d27c.png)

**Comment by notbakaneko** [comment]
This looks like it was caused by a network issue with the image store
