### ISSUE TITLE
Why can't it calculate star rating

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-web#5442]
This map has had no star rating for a whiiile why can't it calculate the star rating?

https://osu.ppy.sh/beatmapsets/682489#mania/1443309

**Comment by nanaya** [comment]
Looks like it needs some recalculation or something.

**Comment by smoogipoo** [comment]
Closing as resolved with the recent mania recalc.

**Comment by WinterIsPretty** [comment]
Thank you for implementing this you guys are awesome. I've recently found out how good you and peppy are at coding by doing a ton of calculations using the API and star rating calculations.

Basically, I went through a lot of osu!'s code so I can understand it more.

Like I used the API to convert a player's top 100 into star rating using their pp and score and then converting it to old pp to see the leaderboard with old pp of the top 1000 players.

ok goodbye have a nice day
