### ISSUE TITLE
Feature request: Receiving notifications after getting a mod on a beatmap

### ISSUE THREAD

**Issue by frukoyurdakul** [ppy/osu-web#5446]
Well, the title sums up it all.

Receiving notifications after getting a mod on a beatmap would be pretty useful, since notification panel is used for a lot of things I think it can be used for that as well. Getting mail notifications is something else, but notifications from the website itself could work a lot better since most of us mappers occasionally visit the website.

From my point of view, we can receive notifications for

1. New posts,
2. Resolved posts from modder themselves (in case mapper does not agree and the modder after agrees with what mapper said in the end)
3. Re-opened posts.

**Comment by peppy** [comment]
This is already a thing. Could you please try pressing the "watch" button on the beatmap you're interested in? It should default to on for your own beatmaps:

![image](https://user-images.githubusercontent.com/191335/71430231-f2d00a80-270d-11ea-8c69-463f4f993bbf.png)

**Comment by nl-tatatat** [comment]
It only defaults to on if you choose to get email notifications while uploading the map (which defaults to off)

**Comment by peppy** [comment]
I guess this default should be changed then. Seems like a bad choice right now.

**Comment by nl-tatatat** [comment]
any progress on this? It seems like every mapper should be notified of suggestions on their beatmaps, unless they explicitly don't want them.

**Comment by peppy** [comment]
@notbakaneko @nanaya can we prioritise this one? seems like a pretty important / easy qol fix

**Comment by peppy** [comment]
I've changed the default in the next `osu-stable` release as mentioned above.
