### ISSUE TITLE
owc banner has a black border

### ISSUE THREAD

**Issue by InvisibleSymbol** [ppy/osu-web#5463]
![](https://i.fiery.me/3scmM.png)
and
![](https://i.fiery.me/UUQZj.png)
Raw file:
![](https://assets.ppy.sh/tournament-banners/official/owc2019/profile/winner_US.jpg)

Example profile: https://osu.ppy.sh/users/13506780
image: https://assets.ppy.sh/tournament-banners/official/owc2019/profile/winner_US.jpg
<sub><sup>again no userscripts</sub></sup>

**Comment by peppy** [comment]
Thanks for pointing out. Should be fixed now.
