### ISSUE TITLE
Ability to view chat history

### ISSUE THREAD

**Issue by Endaris** [ppy/osu-web#5473]
Right now the online chat only has a history of the last 50 messages. Any messages beyond that are lost and can no longer be retrieved which makes it impossible to look up the content of any prior conversations. This is a major disadvantage compared to both ingame chat and former forum PMs.
There should be an option to enable logging that saves the chat-logs clientside and also displays from clientside.

Ideally there would also be the possibility to synchronise the webchat-logs with the gameclient-logs so that your Logs-folder once again becomes the place to look for any prior private chat logs instead of having to check multiple places.
Right now you can be in the funny situation that you chat via website with someone while the client is open and the client only logs the other person's messages which is really meh.

**Comment by peppy** [comment]
viewing history is planned. it's stored but the web UI doesn't support it yet.
