### ISSUE TITLE
user badges should be above player stats and followers on new site

### ISSUE THREAD

**Issue by pimpG** [ppy/osu-web#5476]
![pimpBNv2](https://user-images.githubusercontent.com/31360512/71700911-3c22f880-2da5-11ea-8be4-009b60db45e5.PNG)

similar to how it looks on the old site

![pimpBN](https://user-images.githubusercontent.com/31360512/71700995-b2bff600-2da5-11ea-82df-acb288fce2af.PNG)

would look a lot better

**Comment by peppy** [comment]
They used to be above I think? Not sure why they moved but I agree it looks wrong.

@arflyte

**Comment by arflyte** [comment]
![Figma_200103-133709](https://user-images.githubusercontent.com/3632750/71707614-3cb3a180-2e2e-11ea-8655-61f04828c1e5.png)

in the new design, not the current one. will try to fix the current one.

**Comment by nanaya** [comment]
updated. (although some people seem to prefer the less prominent position)
