### ISSUE TITLE
include multiple download mirrors for packs

### ISSUE THREAD

**Issue by FlyingStefan** [ppy/osu-web#5477]
It has been removed with #2235 but it was also requested by the people at the same time to have an alternative to Mediafire and having now MEGA as platform to download packs would require this support back. Additionally now that I have noticed some packs from Mediafire got recently unavailable and had to be reuploaded.

I understand it's a bit inconvenient to come up with that but I didn't know this has been intentionally removed with the new website.

**Comment by peppy** [comment]
I would actually prefer we just move everything to mega, or host them ourselves. Mediafire is a pretty shoddy service.

**Comment by FlyingStefan** [comment]
If you can provide around 200gb of room for all packs (and upcoming packs in the next months) I'd be more than happy to move them.

**Comment by peppy** [comment]
The idea behind hosting them elsewhere was that there was added redundancy was osu! to ever explode into flames. I think there may still be value in having that level of redundancy.

Would mega work as a solution? I'm happy to pay for an account there to provide ample space for hosting. At least it is ad-free.

**Comment by FlyingStefan** [comment]
Mega is a great idea! Thanks to the generosity of the osu!dan project a plan of 4TB could be paid out for the Mega account so for now it's fine.

And I'll gladly accept your offer once the current plan runs out.

**Comment by peppy** [comment]
Let me know if anything needs to be done from our end.

**Comment by nanaya** [comment]
So what's the plan with this? Is it still relevant or single place as of current is fine?

**Comment by FlyingStefan** [comment]
this is actually good timing, because the MEGA subscription is about to run out very soon and I'd require some assistance for that. 

Also, regarding alternative download mirror: I have set up a mediafire mirror with all beatmap packs till october 2020 and this should be added into the description of the beatmap pack page, in case people prefer this platform for whatever reason or have problems to use MEGA: https://app.mediafire.com/t01qat9p8m4wc

**Comment by peppy** [comment]
@FlyingStefan is it fine to close this issue based on switching to mega for hosting here?

**Comment by Joehuu** [comment]
Packs are now hosted directly, closing.
