### ISSUE TITLE
Last pages of the comments listing don't have any comments

### ISSUE THREAD

**Issue by InvisibleSymbol** [ppy/osu-web#5481]
It says that [15935](https://osu.ppy.sh/comments?page=15935) is the last page while it's actually [15042](https://osu.ppy.sh/comments?page=15042) (atm at least)

---
Video: https://streamable.com/k4f3l
Url: https://osu.ppy.sh/comments

**Comment by peppy** [comment]
We probably shouldn't allow going that far back in pagination in the first place.
