### ISSUE TITLE
Add icons in the userpage for Specific BNs

### ISSUE THREAD

**Issue by DaxMasterix** [ppy/osu-web#5484]
If this request was already made, I'm sorry. I didn't find a search bar in the Feature Request Forum.

As the title says, I think it would fit well to have specific icons for the BN members. I example the idea in the images.

With This, new mappers could find Specific BNs by just searching their respective userpages, Avoiding possible misunderstandings.
![crissa example](https://user-images.githubusercontent.com/59589377/71862981-347f8e80-30da-11ea-8eae-b53ad93b4665.png)
![critical star example](https://user-images.githubusercontent.com/59589377/71862982-35182500-30da-11ea-89d4-35641ea8c7e6.png)
![daxs example](https://user-images.githubusercontent.com/59589377/71862983-35182500-30da-11ea-961d-dc06c28d9592.png)
![vulkin example](https://user-images.githubusercontent.com/59589377/71862984-35182500-30da-11ea-819d-79488ad05c76.png)

**Comment by peppy** [comment]
If this was to be added, it should probably be in the group name (same line and same colour).

**Comment by arflyte** [comment]
Hmm, very new idea to me. I'll add this to the user page and card designs.

**Comment by DaxMasterix** [comment]
Hey that's cool! Thanks you!

**Comment by nl-tatatat** [comment]
I think this is a terrific idea. BNs of non osu! gamemodes regularly receive requests for osu! because all BNs look the same. 

The only problem with only changing the group name is the case of multi-gamemode BNs.

**Comment by DaxMasterix** [comment]
That wouldn't change the Name. Just add some icons according to their respective speciality on their userpage.

**Comment by nl-tatatat** [comment]
Is there some reason this design proposal wasnt used instead of https://github.com/ppy/osu-web/pull/5701 ? This proposal does a much better job at conveying what gamemode the user is a nominator for, which has been a long standing issue on osu-web (since forever?)

**Comment by cl8n** [comment]
5701 was solving a different problem, this issue is still valid

the reason this isn't straightforward is that data of BNs belonging to certain game modes isn't available on the site at all for now, when that's added it could also be used for group pages and nomination permissions

**Comment by nl-tatatat** [comment]
That data isn't available at all? It seems like pretty important data to have. Having it could enable other features like greying out the nomination button on mapsets of gamemodes you aren't qualified to nominate. Or greying out the nomination button if its already been nominated by a probation bn, and you are also a probation bn.

Anyways, until this or a similar feature is implemented, people will continue to get confused about what gamemode(s) nominators are involved in. What a shame.

**Comment by peppy** [comment]
This issue is open because we are working to fix this issue. "what a shame" response are not required since we are working to fix the issue.

**Comment by nl-tatatat** [comment]
Oh, nice

**Comment by c-sig** [comment]
> the reason this isn't straightforward is that data of BNs belonging to certain game modes isn't available on the site at all for now, when that's added it could also be used for group pages and nomination permissions

Just bumping because I'd like for this issue to be more noticed. Wouldn't data from https://bn.mappersguild.com/ for determining which game modes BNs belong to be sufficient for this? Or maybe getting the same data the same way the BN site gets it would be okay for this, _unless they're all manually inputted._  

I'd also like to give a piece of a design idea because this was mainly the reason how I found this thread.
![image](https://user-images.githubusercontent.com/61018516/93665030-dfd44600-faa5-11ea-9b47-8f766e923064.png)

**Comment by c-sig** [comment]
shouldn't this issue be closed?

**Comment by peppy** [comment]
Closed via https://github.com/ppy/osu-web/pull/6747.
