### ISSUE TITLE
Search doesn't work for guests

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#5488]
Probably should, at least for the wiki. If not, it should prompt the user to login, rather than silently returning no results.

![2020-01-08_16-18-14](https://user-images.githubusercontent.com/191335/71958009-94894880-3232-11ea-9035-2ce946804c36.gif)

**Comment by nanaya** [comment]
That quick search isn't going to search wiki anyway...

**Comment by peppy** [comment]
Yeah, I realised that after logging in. It's a bit of a pity a guest can't search the wiki, even from the wiki home page. Could we change it there, at least?

**Comment by notbakaneko** [comment]
closing this since guests can now search the wiki and quick search prompts for login instead of doing nothing

**Comment by notbakaneko** [comment]
whoops; close after #5541 is merged
