### ISSUE TITLE
Highlighted stream on livestream page should be an embedded player

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#549]
Right now it's a huge ugly thumbnail.

**[Bounty](https://goo.gl/nFdoyI) offered**: 20-50 depending on implementation quality.

Feel free to reply in this thread should you have any questions.

**Comment by normundy** [comment]
Would we want an embedded player like the players on MyAnimeList that "pop" out (Ex: under 'Most Popular Promotional Videos')? 
http://myanimelist.net/

**Comment by peppy** [comment]
No, it should be playing when you arrived at the page, in place of the over-sized thumbnail that is currently being shown there.

**Comment by normundy** [comment]
So the embedded players should look something like this?

![osuweb_549_1](https://cloud.githubusercontent.com/assets/10818718/15701559/cdef0896-278f-11e6-97e9-9eb754cd8a9e.png)

My mock-up significantly slows down the page, may need to consider some sort of pagination. Note that the stream details such as the views and status are all included in the player already. Do we want to keep the same layout like how this is currently shown in production (with the views on the top right and the status on the bottom)?

Docs on embedding Twitch streams: https://github.com/justintv/Twitch-API/blob/master/embed-video.md

**Comment by nanaya** [comment]
I thought it's just for highlighted one?

**Comment by LiquidPL** [comment]
wouldn't those have actually the same purpose as what we have currently? as in, opening the twitch page? also, as nanana mentioned, it is to be only for the first, big one.

**Comment by normundy** [comment]
Oh oops. Feeling dumb here. What do you mean by the highlighted one or first big one? 
http://new.ppy.sh/community/live

**Comment by LiquidPL** [comment]
https://puu.sh/pcsv4/0b047a7177.jpg

**Comment by VeilStar** [comment]
http://puu.sh/pcv4e/a48efb3e00.jpg if you want a bit of a better preview

A stream can be promoted/featured/highlighted and will then appear as shown on the screenshot.

**Comment by normundy** [comment]
Ah I see, I had my development on master. Thanks for the images

**Comment by peppy** [comment]
Also keep in mind that the design here is slightly outdated (the whole page design) and implemented incorrectly (everything is @2x from what it should be).

I believe @arflyte will have a bounty today for fixing that up to the newer version.

**Comment by Nicarim** [comment]
:( that hurts

**Comment by peppy** [comment]
This makes up part of the bounty at https://github.com/ppy/osu-web/issues/549, but can be implemented separately if it happens first.

**Comment by nanaya** [comment]
p.sure this is done (as part of #560).

**Comment by nanaya** [comment]
Sure is done.
