### ISSUE TITLE
Update background video on home page

### ISSUE THREAD

**Issue by Squiddu** [ppy/osu-web#5496]
The current home page video is using an outdated version of lazer (and it's REALLY outdated. It uses numbers!).
Here's a screenshot of it:
![chicken](https://user-images.githubusercontent.com/55364481/72104568-bbf71880-32f9-11ea-9c32-7431c21e2cf0.png)

**Comment by peppy** [comment]
I think it still gets the point across. If you're up for making a new one (it needs to be a perfect loop) we'd definitely consider switching it out, though.

**Comment by Luxiono** [comment]
For clarification (if can be found, what's the song used?

**Comment by peppy** [comment]
It doesn't really matter which map. Using one of the bundled or otherwise would be fine.

**Comment by Joehuu** [comment]
Has since been updated, see https://github.com/ppy/osu-web/issues/10275.
