### ISSUE TITLE
Creating user: Fatal error

### ISSUE THREAD

**Issue by miguelmartin75** [ppy/osu-web#55]
The following command fails for when I try to create a user:

```bash
hhvm artisan tinker
```

It throws a run-time error (for me using vagrant on OS X 10.10.4 via the install on the web [vagrant 1.7.4]), which is the following:

```
Fatal error: unexpected St13runtime_error: locale::facet::_S_create_c_locale name not valid
```

**Comment by Tewki** [comment]
`sudo dpkg-reconfigure locales && sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8`

**Comment by miguelmartin75** [comment]
Looks like this is a common error with [HHVM](http://laravel.io/forum/08-28-2014-hhvm-instead-of-php-laravel-composer-installation-error). The solution is to simply do the following:

```
sudo printf "%s\n%s" LC_CTYPE=en_US.UTF-8 LC_ALL="en_US.UTF-8" >> /etc/default/locale
```

Exit ssh and re-enter it via `vagrant ssh`. 

Alternatively if that doesn't work, this might:

```
sudo echo export export LC_ALL=C >> /etc/default/locale
```

**Comment by miguelmartin75** [comment]
Thanks for the alternative solution @Tewki.
