### ISSUE TITLE
User Preferences

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#550]
This is an open-ended task to add user preferences to the system. We have a design for this (and I think it was partly implemented) so ask if you are wanting to take this one. It will likely require consultation directly with us on an on-going basis, so let us know if you are interested in helping here and we'll talk it through.

This will involve tasks like:
- Change avatar
- Change profile details
- Change email or password
- Change signature

**[Bounty](https://goo.gl/nFdoyI) offered**: 500-1500 depending on implementation quality.

Feel free to reply in this thread should you have any questions.

**Comment by normundy** [comment]
I am interested in helping in helping with these features. Maybe I can start out with implementing one of them for now like the 'Change avatar' feature. Thinking of working on this after #549

**Comment by Hughp135** [comment]
I'd definitely like to help out with this, from what I gather we will new to add new routes and controller methods for each the required functions plus any new tables required for storing profile data?

These all seem pretty doable

**Comment by LiquidPL** [comment]
profile tables are here already from the old website, you just need to add models, routes and controller methods for editing it within the new site, and then make the frontend.

**Comment by ren-** [comment]
I'm up for it, please let me know what's currently available from the front end.

**Comment by RedbackThomson** [comment]
If flyte has not posted a PSD with the design, then there is no current front end design.

**Comment by ren-** [comment]
@peppy Can this be split into 2 bounties? One for the frontend the other for the backend? 
I can do the backend, but I'd need someone to do the rest.

**Comment by LiquidPL** [comment]
i guess you should consult this with whoever is doing the issue right now

@normundy ping ping

**Comment by IrateGod** [comment]
I am not that great at designing front-end, but I may well be able to help with the back-end.

@peppy are there any updates on this issue so far? As @ren- stated I would want to ask if this could be split up into the two tasks mentioned above.

**Comment by peppy** [comment]
you're free to work on portions. i'm not splitting this up just yet because we don't have completed designs

**Comment by Risers** [comment]
Is anybody doing this?
And have we got completed designs?

**Comment by Risers** [comment]
I'll do this

**Comment by nanaya** [comment]
[Jobs done](https://www.youtube.com/watch?v=5r06heQ5HsI).
