### ISSUE TITLE
Allow using API to get seasonal backgrounds

### ISSUE THREAD

**Issue by mcendu** [ppy/osu-web#5501]
**Proposed design:**
```diff
--- a/routes/web.php
+++ b/routes/web.php
@@ -418,3 +418,6 @@
         Route::get('users/{user}/{mode?}', 'UsersController@show');
+
+        Route::resource('contests', 'ContestsController', [ 'only' => 'index' ]);
+        # More contest related stuff...
     });
 })
```

**Comment by notbakaneko** [comment]
What's the use-case for this?

**Comment by mcendu** [comment]
This is for allowing retrieval of seasonal backgrounds.

**Comment by peppy** [comment]
It probably needs to be a custom endpoint specifically with that purpose.

**Comment by nanaya** [comment]
So what is the use case of this issue? Is it seasonal background for client? (and is it why it's in a milestone?)
