### ISSUE TITLE
Headers take too much space on mobile

### ISSUE THREAD

**Issue by stanriders** [ppy/osu-web#5503]
`profile . info`, mode selectors and search take way too much space on mobile. They also seem to be spaced differently everywhere.  

I propose removing `page . info` header altogether since it's redundant on mobile, making mode selectors into a dropdown (or at least shrink them to fit on one line) and making search a button somewhere in the header.

**Screenshots:**  
![photo_2020-01-14_15-17-13](https://user-images.githubusercontent.com/8269193/72343996-47e5b780-36e1-11ea-90e4-325411152560.jpg)
![photo_2020-01-14_15-17-14](https://user-images.githubusercontent.com/8269193/72343997-4916e480-36e1-11ea-809a-2f9897095be5.jpg)

**Comment by peppy** [comment]
@arflyte do we already have a direction for fixing this?

**Comment by arflyte** [comment]
![Mobile Index](https://user-images.githubusercontent.com/3632750/72405735-45489800-379d-11ea-8020-b7909f3be9d4.png)

Yeah, already looked into it. It's still a work in progress.

**Comment by nl-tatatat** [comment]
I don't think having the gamemode selector be in a seperate tab system seems like a good idea... its just introducing hassle and extra steps to the browsing experience. They can easily fit on one line if there is just less spacing between the gamemodes imo.
