### ISSUE TITLE
BBCode [notice] bug

### ISSUE THREAD

**Issue by Serizawa-Haruki** [ppy/osu-web#5505]
When using multiple consecutive [notice], it is not possible to add empty lines between them. The borders will always touch, even if you use enter a couple of times. It looks like this:
https://cdn.discordapp.com/attachments/528985001891725323/666987218593775626/unknown.png

By coincidence, I discovered that this doesn't happen when using [centre] around the [notice], but it doesn't solve the problem if you want the text to be aligned on the left border. You can see it in this screenshot:
https://cdn.discordapp.com/attachments/528985001891725323/666987993386582026/unknown.png

**Comment by DarkStoorM** [comment]
Almost posted a duplicate, whew.
I noticed you can (for now) place empty tags between your [notice] (...) [/notice]
```
[...]
[notice][/notice]
[b][/b]
[notice][/notice]
[b][/b]
```
results in:
![image](https://user-images.githubusercontent.com/7021295/73582111-16643e80-448c-11ea-8222-a3d892df4abc.png)

It forces a new line:
![image](https://user-images.githubusercontent.com/7021295/73582174-56c3bc80-448c-11ea-9fbc-e6eaae6d2aec.png)
