### ISSUE TITLE
Beatmap links shouldn't open in a new window/tab

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#552]
Right now they do, when clicked from the listing page.

**Comment by nanaya** [comment]
with current search page, I don't recommend opening in same page because going back to search page result in something... undefined (try clicking modder name for example, and/or scrolling down several pages).

**Comment by peppy** [comment]
can that just be fixed in this PR too? ;)

**Comment by nanaya** [comment]
Maybe update the title/description? :P (also it's pretty difficult from what I can tell)

**Comment by MrSurvivor** [comment]
I'm kind of torn on this xD
Part of me really wants the open in a new tab so I can just press twenty beatmaps at once
But the other part remembers there's a download button if you hover over the map...
