### ISSUE TITLE
Inconsistent page titles and navigation

### ISSUE THREAD

**Issue by nanaya** [ppy/osu-web#5531]
Section/subsection naming seem a bit inconsistent. For example everything in forum says "community - forum" but for contests it says "contests - listing/<name>" despite both forum and contests are under "community". Similar situation with home's dashboard and news. Etc.

Additionally mobile title is rather confusing in some areas. You can't put long title in it though - being mobile and can only be one line. Changing it to always show section(?) name might be enough because the page title is usually in navigation links.

And as can probably be guessed from the sheet, everything is currently manually defined :dancer: 

- decide what to put as section and subsection
  - also consider #5529
- decide what to put in mobile title
- add some logic to browser tab title?
- (optional) maybe fix some of the urls as well. For example https://osu.ppy.sh/beatmapsets/beatmap-discussions is kind of weird

[List of pages](https://docs.google.com/spreadsheets/d/1zcOheJwaxAER5xf82hhNBe83KMLcqFlCAaCPMbP4Xpk/edit?usp=sharing).

**Comment by peppy** [comment]
On further discussion, let's start with a conformity pass on the nav / section / subsection and move any case where we are relying on the subsection to instead be displayed inline on the page (cases like featured artist).

**Comment by nanaya** [comment]
Mostly fixed by #5640.
