### ISSUE TITLE
osu! Front Page

### ISSUE THREAD

**Issue by arflyte** [ppy/osu-web#554]
![](http://puu.sh/pbjlL/5273245bcb.jpg)
Front page when users not signed in. It features huge image carousel that fades between 3-5 images, with large call to action lines. Artworks will be provided by illustrators and will change according to events or seasons. Clicking some of the images will take to different pages.

Design is not finalised, and all the image snippets here are at 2x unless mentioned otherwise.

### Navigation

![](http://puu.sh/pbhTC/4571ae2c71.jpg)
Button has pink highlight on hover. No dropdowns. Directs them straight to the main page of each section.

![](http://puu.sh/pbi5C/a4dd23431e.jpg)
Would be nice if the osu!cookie bounces on hover, like the game client. Solid white ring expands and fades out on each bounce.

![](http://puu.sh/pbhMg/61436dbe3c.jpg)
The login and sign up should work and look like the new forum's, for now. The design will be updated in the future.

### Cover

![](http://puu.sh/pbhNE/f922cb74a7.jpg)
Large download button, automatically suggested based on their OS. "for Windows" only for now. I'm not sure about other OSes. Button design not finalised.

![](http://puu.sh/pbicM/415f73181a.jpg)
Online user graph for the past 24 hours. Image at 1x. 

![](http://puu.sh/pbilJ/75d2cca972.jpg)
Peak marked by circle, with description aligned at 45 degrees on the right. Description should be on the left side if there's no space on the right side.

![](http://puu.sh/pbiqT/5c0077481c.jpg)
Uh.. self-explanatory?

### Footer

![](http://puu.sh/pbisA/2fa5028f8a.jpg)
Placeholder rounded boxes with drop shadow for seasonal features. Images will be provided by the designer for each feature. Snippet at 1x.

![](http://puu.sh/pbiBY/152cc1e9ae.png)
Footer. Snippet at 1x.

**Comment by arflyte** [comment]
![](http://puu.sh/pbnGR/8e05f27e44.jpg)

When the online users link are clicked.

**Comment by peppy** [comment]
**[Bounty](https://goo.gl/nFdoyI) offered**: 200-1000 depending on implementation quality.

Feel free to reply in this thread should you have any questions.

**Comment by peppy** [comment]
also "free-to-play" should totally be "free-to-win" ;)

**Comment by lunafreya** [comment]
Also, "productivity killer" should be "rhythm clicker".

**Comment by reesebiz** [comment]
Me and @RedbackThomson is interested in working on this! Are there resources/PSD available for the current version somewhere?

**Comment by peppy** [comment]
@arflyte i can't find the psd for this. please provide.

**Comment by peppy** [comment]
I think this is the right PSD?

https://puu.sh/pg3Q4/d217f4536d.psd

**Comment by reesebiz** [comment]
Yep that's the one. Thanks!

**Comment by RedbackThomson** [comment]
What did you envision for the login and sign-up buttons? If they're logged in, they shouldn't even be able to access this page? Or an avatar like the normal header?

**Comment by peppy** [comment]
the page is only accessible when not logged in.

**Comment by RedbackThomson** [comment]
Should the buttons redirect to a permanent login/sign-up page, then?

**Comment by reesebiz** [comment]
So I saw mentioned that the design is at @2x. I made the page to be half of what it looks like in the design so far: http://puu.sh/piklJ/01becc0382.jpg

I'm wondering is the site supposed to look that small? It feels a lot smaller compared to the rest of the pages on the site. I saw a LESS ".at2x" function for making background images bigger for retina devices but I don't know if there's anything else I should be knowing about.

**Comment by peppy** [comment]
That looks correct, although if it makes the styling easier you're welcome to make it stretch to the same width as every other page does right now. We plan on adding (user-customisable) width limitations at some point, at which point the home page will be limited to the width you have there.

@2x images should work magically as long as you use the at2x and get the filenames right.

**Comment by reesebiz** [comment]
Ok I will make it match the other pages with so far. The design is really nice it should be in everyone's faces :P

Also is there a planned mobile design or am I going to wing it? Everything is laid out pretty simple I can make it collapse easily.

**Comment by peppy** [comment]
Do your best with the "mobile" part. The menus should probably be done sharing how the full site's menu system works when collapsed (but with only the single tier.

**Comment by odihominem** [comment]
I'm working on osu! logo animation on hover. I came up with this: http://codepen.io/mxnd/pen/beVdrG/
What do you guys think?

**Comment by Ameobea** [comment]
@odihominem that's pretty amazing; 10/10 stuff

**Comment by peppy** [comment]
Reminds me of the swf version we used to have. I don't think we will use such an animation on the new site though (it doesn't fit with our style going forward).

**Comment by reesebiz** [comment]
@peppy what do you mean by style? Like the image he used? Or the way he built the animation? Or the animation wasn't close enough compared to how the logo is in the game?

**Comment by peppy** [comment]
Oh I guess flyte actually asked for this.

Well it doesn't behave how it should - the exploding part should be behind the logo and a white ring (as per flyte's specs). As it is it just looks messy (the pink mixing with the white border etc.)

Also the initial inwards part is too gradual if you're trying to match how it is in-game.

**Comment by RaidMax** [comment]
Here's my take at the logo
[](http://codepen.io/anon/pen/WxQdLP)

**Comment by Ameobea** [comment]
@RaidMax Another beautiful piece of work!

**Comment by peppy** [comment]
Close to what I'd hope for :). @RaidMax's first try is probably a good place to start.

**Comment by RaidMax** [comment]
@peppy 
Now that I'm free, I can make it identical to the in-game menu animation, if that's what you're looking for. Also steady beat or varied?

**Comment by peppy** [comment]
steady is fine

**Comment by RaidMax** [comment]
@peppy 
Something closer to the in-game menu: http://codepen.io/anon/pen/yJYqeo

**Comment by peppy** [comment]
i'm still partial to http://codepen.io/anon/pen/WxQdLP (your first attempt). feels the best

**Comment by kschamplin19** [comment]
imo I prefer the latest one he made, because it is very flat like the rest of the page design. I notice that in the menu, it instantly (or almost instantly) snaps to big size before fading to small. Prevents it from looking jittery. Also the wake needs re-timing, to expand when the circle is at its smallest. IDK, just my two cents.

**Comment by RaidMax** [comment]
Here's a final version that combines the timing and "feel" of the first with the smooth glow.
http://codepen.io/anon/pen/wWKZBr. Hopefully you guys can use one of my iterations as a base.

**Comment by RedbackThomson** [comment]
How long should the time span of the online users graph be?

**Comment by peppy** [comment]
24 hours seems best!

**Comment by peppy** [comment]
@RaidMax  I think that feels fine for now!

**Comment by TPGPL** [comment]
@reesebiz How's the work going?

**Comment by reesebiz** [comment]
@TPGPL Mostly done. Just finishing up some things and making some fixes before we make a PR

**Comment by reesebiz** [comment]
@ppy @arflyte For the online users graph: What do you guys think about having functionality to show the number of players online during a certain period of time on hover? 

By default the graph would show the peak users amount always, but on hover the circle would move to the x-coordinates of the mouse on the graph and show the users online at that point of time.

It would remove the "Peak," part of the text and possibly could show the date too.

**Comment by peppy** [comment]
There's a status page to get more detail. Personally I don't think it should be something we offer here.

**Comment by arflyte** [comment]
I'm fine with showing the number of players online on hover. We'll try usability after implementation. Remove it if it feels weird.

**Comment by TPGPL** [comment]
maybe the number should be in the box near the cursor?

**Comment by peppy** [comment]
Awarding 1000 bounty for this to @RedbackThomson :+1:.
