### ISSUE TITLE
Botswana not showing up on country list despite active player

### ISSUE THREAD

**Issue by roansong** [ppy/osu-web#5542]
This user is the #1 player in Botswana (has been for ages): https://osu.ppy.sh/users/9321462
Clicking on the BW flag links to https://osu.ppy.sh/rankings/osu/performance?country=BW but not filter is applied.

**Comment by roansong** [comment]
Botswana is not listed on the country page at all, in fact

**Comment by peppy** [comment]
We only show countries with enough players to matter.

**Comment by roansong** [comment]
Antarctica, Central African Republic, Liberia, and Eritrea should probably be removed then

**Comment by peppy** [comment]
Please open another issue and we will consider that.
