### ISSUE TITLE
Consider removal of countries with too few players from the leaderboards

### ISSUE THREAD

**Issue by roansong** [ppy/osu-web#5543]
Currently there are countries with few to no active users showing up on the leaderboards.
E.g. [Liberia](https://osu.ppy.sh/rankings/osu/performance?country=LR) and [Eritrea](https://osu.ppy.sh/rankings/osu/performance?country=ER) show 1 active user each. Clicking on either of these countries displays no users.

Some countries with at least one active user (e.g. [Botswana](https://osu.ppy.sh/users/9321462) (see #5542) do not show up on the leaderboards at all.

Should countries with active players below a certain threshold be removed?

Possibly related discussion: #3823 and #4561

**Comment by myangelaku** [comment]
I don't think that any countries should be entirely removed from the country leaderboards, but if they are going to, there should at least be some way to still view the country's leaderboards, for example through the direct link (country code in URL)

**Comment by peppy** [comment]
The two countries mentioned in this issue are now hidden from the list. We can revisit this if there are any other which need adjustment (we can flag individual countries to not show up as required).
