### ISSUE TITLE
"Unknown error occured." when posting in forums

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#5552]
Happens randomly whenever anyone posts something. It's a running joke now: https://osu.ppy.sh/community/forums/topics/1015432. Takes another try or two to for it to post

**Comment by peppy** [comment]
How reliably can you make this happen? I've never seen it happen. If you can reproduce it reliably, keep your browser network inspector open and try and log some details of what the response is on failure.

**Comment by peppy** [comment]
@nanaya can you think of a reason this would happen?

**Comment by cl8n** [comment]
the response is 500 with `{"error": null}`, not very helpful. I was able to replay the request from devtools and successfully post a reply, so it seems pretty random from client's perspective

**Comment by abraker95** [comment]
I can't make this reliably happen, but it happens often enough to be annoying.

**Comment by peppy** [comment]
We've pushed out a hopeful fix for this. Please report back how things go now.

**Comment by abraker95** [comment]
I made 16 posts since and haven't gotten the error yet

**Comment by peppy** [comment]
Tentatively going to close this for now. Please comment if you notice it happening again!
