### ISSUE TITLE
Notifications "show more" button should show more

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#5558]
Generally when a user is going to click this, they are expected to continue clicking it until they see all their notifications. It would therefore be a better UX to show about 500 each click to reduce the number of clicks required.

Assigning to @nanaya as discussed earlier today. Feel free to reassign if required.

**Comment by nanaya** [comment]
Should re-confirm if still needed with the new update...

**Comment by peppy** [comment]
I think it's fine now.
