### ISSUE TITLE
Loved mania map has no leaderboard

### ISSUE THREAD

**Issue by jxu** [ppy/osu-web#5560]
Shows up in-game but cannot submit scores. 
https://osu.ppy.sh/beatmapsets/764649#mania/1751616

**Comment by cl8n** [comment]
it's not loved, only the standard diffs are. good example for #4266

**Comment by jxu** [comment]
iirc it has a scoreboard in game

**Comment by cl8n** [comment]
we removed that diff from loved a few hours after the whole set was loved, i guess the old scores still show up in-game

**Comment by peppy** [comment]
This should be fixed now.
