### ISSUE TITLE
Beatmap showing played maps with "unplayed" filter

### ISSUE THREAD

**Issue by Kodaijin** [ppy/osu-web#5561]
Problem details: Supporter account, searching for new beatmaps @ https://osu.ppy.sh/beatmapsets shows played beatmaps.

Video or screenshot showing the problem: https://i.imgur.com/AQicm57.png

Notes: This is repeatable across various browsers. 

osu! version: Stable 20200118.2

**Comment by nanaya** [comment]
It looks like this part isn't doing the expected thing. Filtering out by beatmapset id works. There might also be a correct way to filter out by existence of array element.

https://github.com/ppy/osu-web/blob/c5d2ac9a314bc601c0fdbbce6cfb81a926044b34/app/Libraries/Search/BeatmapsetSearch.php#L161-L163

**Comment by notbakaneko** [comment]
It's because the inverse of a `nested: { filter: ... }` query isn't `nested: { must_not: ... }` but actually `must_not: { nested: ... }` 😖
