### ISSUE TITLE
Exiting BSS before fully finished creates ghost difficulties

### ISSUE THREAD

**Issue by Pennek** [ppy/osu-web#5564]
Uploading diffs ingame but exiting before upload is fully finished creates ghost difficulties on beatmap info page and beatmap discussions.

First noticed on: https://osu.ppy.sh/beatmapsets/1084483
Able to recreate somewhat consistenly for pending/wip beatmaps: https://osu.ppy.sh/beatmapsets/1081411

Images of bug: https://i.imgur.com/gQE8UN6.jpg https://i.imgur.com/QEEiwmf.jpg

**Comment by Pennek** [comment]
hmm, tried again on https://osu.ppy.sh/beatmapsets/1081411 . Seems to be more difficult than expected to reproduce. what I've been doing up until now is clicking the x-button on the BSS prompt and spamming 'escape' to return to the song selection screen. It works maybe 30% of the time

**Comment by peppy** [comment]
This is generally normal behaviour. Can you confirm they are cleaned up on next submission?

**Comment by Pennek** [comment]
Can confirm
