### ISSUE TITLE
Arabic is ready to be implemented to the website!

### ISSUE THREAD

**Issue by greevak** [ppy/osu-web#5569]
Hey!-

Ibrahim younis aka Greevy or Greev.

Am an active english to arabic translator on CROWDIN - Osu!Translation project. (By peppy).
AR project link: https://crowdin.com/project/osu-web/ar#

As of me finishing the work and adding new translations every while to the project, Arabic language in Osu! project seems to be completely done and ready to implement it to the site. it looks fit for the job and very professional.

If you think the words need to be approved then i will say that's unfortunate because i can't get anyone to approve them, but if you can give me the ability to do so, i will be really happy to help and make sure of all words. Also i will be glad to make sure of the translations every while.

Email: ibrahimahmaed3@gmail.com Osu!username: greevy

Thanks for checking this article/issue.

**Comment by greevak** [comment]
Good to mention that it was readyabout 8 months ago. I keep it updated, So all translations are being checked every while to keep everything at its best.

**Comment by peppy** [comment]
Thanks for the heads up, I will look at getting this out this week.
