### ISSUE TITLE
Beatmap Details Page, Redesigned

### ISSUE THREAD

**Issue by arflyte** [ppy/osu-web#559]
![](http://puu.sh/pctKG/a114e17def.png)

New design for the beatmap page. Designs not final but ready for implementation. All of these image snippets are at 2x, unless mentioned.

## Cover and Main Information
![](http://puu.sh/pcwEf/0eaa51630f.jpg)
Cover is beatmap's background. 50%-70% gradient black overlay on the cover for visibility. Will be fine tuned in the future. All the text except in the beatmap details box, has drop shadows. Snippet at 1x.

Song preview when cover is clicked. Song preview function will be finalised in the future.

### Mode and Difficulty Selector

![](http://puu.sh/pctQ6/213fd8730a.jpg)

Available modes are available in white, 50% opacity if not available. Selected mode has a 50% black background.

Underneath the modes are the list of available difficulties for selected mode. Line break at 10. Selected difficulty has a 50% black background.

Difficulty title, play count and favourites are displayed under the difficulty list. By default it shows the selected difficulty; it will display other difficulty's info when hovered.

Star Difficulty only appears on hover.

### Main Information
![](http://puu.sh/pcubS/38b9b8dc37.jpg)
Song title (Semi Bold) followed by song artist (Medium).

### Mapper Info
![](http://puu.sh/pcuft/debe74f2e5.jpg)
Mapper avatar, and name; followed by map submission date and ranked date. Mapper name italicised, date is bolded.

### Download buttons
![](http://puu.sh/pcuik/bc6f45ed84.jpg)
Buttons to download the maps. A dialog box will appear if a non-supporter clicked osu!direct, promoting supporter functions.

## Beatmap Details
![](http://puu.sh/pcutA/fd3f5e607b.jpg)
3 boxes, black 50% opacity. Seperated by 2px. All of the texts inside this area has no drop shadows.

### Basic Stats
![](http://puu.sh/pcuv3/d55adcc7b6.jpg)
Length, Tempo, Node count and Slider count.

### Advanced Stats
![](http://puu.sh/pcuyC/ea487551c2.jpg)
Extra information showing the Circle Size, HP Drain, Accuracy, Approach Rate and Star Difficulty. The order is not finalised and will be updated in the future.

All the bars are white 50% opacity. Filled with white, except Star Difficulty which is orange. Resize transitions when different difficulty is selected.

The values on the right are centered.

### User Rating
![](http://puu.sh/pcuEf/eb3c2fcf0a.jpg)
Identical to the current website, displaying the rating spread of the map. Rating spread chart is solid blue for every value.

## Extra Information
![](http://puu.sh/pcuIF/5ae4506d2f.png)
Image snippet at 1x. Displaying additional info. Box height is fixed. The description is scrollable inside the box if it's taller than the box. Tags are clickable. Hide extra tags if it's taller the height limit to discourage mappers spamming tags.

Success rate function is identical to the current site. Point of Failure graph is attached to the bottom of the extra info box.

### Ranking Chart Filter
![](http://puu.sh/pcuSN/312a55f669.png)
User will be able to change the list to show global results, player's country results or results between their friends.

By default all the mod filters are enabled. Toggled by clicking it. If enabled, list will only show games with at least one of the mods used. Results without any mods will be displayed at all time.

If you think there's a better way for the filters, do suggest.

The list will show the top 50. Grey highlight on hover (in the future, a quick info panel will appear http://puu.sh/pcxCx/76bd9eea21.jpg)

### Best Result / Player Best
![](http://puu.sh/pcvUq/c4868ed918.png)
Best result or player's best appears as a box, within the list.
Snippet at 1x. Gold border for #1 result, none for player best.

Best result is shown on top of the list. If the player best is within 50, result is shown within the list (eg: between #7 and #9 with the player best is #8). If the player's best is beyond 50, it's shown at the bottom of the list at #50.

#### Player
![](http://puu.sh/pcx58/bf9bc2622c.jpg)
Rank number #1 should be in gold, vertically center aligned between the blue guide lines. Player avatar with usual drop shadow. Italicised bold player name on top of player's country flag and team flag.

#### Score Details
![](http://puu.sh/pcxfm/1b5b04ca4c.png)
Mods used are displayed. All the scores details are italicised, additional bold for score.

X/Y/Z is a placeholder for 300/100/50. Will be updated when I can come up with the better way to represent them.

Relative time when the score was achieved is displayed under the scores.

**Comment by peppy** [comment]
**[Bounty](https://goo.gl/nFdoyI) offered**: 400-1000 depending on implementation quality.

Feel free to reply in this thread should you have any questions.

**Comment by Cyanogenoid** [comment]
A suggestion for the ranking chart filter:
I think the most flexible system for the filters uses three states for each mod icon rather than two: *don't care*, *enabled*, and *disabled*.

 - *don't care* means that all plays, regardless of whether they use this mod or not, are shown.
 - *enabled* means that the plays shown must have this mod enabled
 - *disabled* means that the plays shown must have this mod disabled.
 
*don't care* is the default state for all mod filters, as this way, no plays are filtered out.
An example of this three state system for mod filtering can be seen in the table here: https://github.com/Cyanogenoid/osu-modspecific-rank/tree/master/results#mod-leaderboards

The filters can cycle through the three states when clicked, i.e. *don't care* comes first, then *enabled*, then *disabled*, then back to *don't care*. *don't care* could be represented with the mod icon at lower opacity, *enabled* with the icon at full opacity, and *disabled* with a cross on top of the icon. Of course, if anyone has better ideas for how to represent this, feel free to comment.

**Comment by LiquidPL** [comment]
how are we going to handle converts in this one?

**Comment by LiquidPL** [comment]
grabbing this one as soon as flyte gives me updated designs

**Comment by LiquidPL** [comment]
this is a test comment

**Comment by arflyte** [comment]
![](https://cloud.githubusercontent.com/assets/3632750/16187416/2a9565ec-370b-11e6-9e85-3fea9804e175.png)

New design update to conform to the new navigation bars.

![](http://puu.sh/pzdI1/0090d51773.png)
Sub-navigation bar to switch game modes. Top left of the cover only displays available difficulty for selected mode.

**Comment by TPGPL** [comment]
new navigation bars look bad tbh

**Comment by TPGPL** [comment]
shouldn't the darkgrey background of new navigation bars be map's background?

**Comment by TPGPL** [comment]
@arflyte what about legend for Points of Failure?

**Comment by LiquidPL** [comment]
>Basic Stats
>![](https://camo.githubusercontent.com/3a8327810327d8a4de95edbd06b990537d7df114/687474703a2f2f7075752e73682f70637576332f643535616463633762362e6a7067) 
>Length, Tempo, Node count and Slider count

@arflyte may I ask you where do those icons come from (the first one is in fontawesome, but not sure about the rest)

**Comment by arflyte** [comment]
[BDI - Accuracy.pdf](https://github.com/ppy/osu-web/files/386166/BDI.-.Accuracy.pdf)
[BDI - Approach Rate.pdf](https://github.com/ppy/osu-web/files/386167/BDI.-.Approach.Rate.pdf)
[BDI - BPM.pdf](https://github.com/ppy/osu-web/files/386164/BDI.-.BPM.pdf)
[BDI - Circles.pdf](https://github.com/ppy/osu-web/files/386163/BDI.-.Circles.pdf)
[BDI - HP Drain.pdf](https://github.com/ppy/osu-web/files/386162/BDI.-.HP.Drain.pdf)
[BDI - Length.pdf](https://github.com/ppy/osu-web/files/386165/BDI.-.Length.pdf)
[BDI - Overall Difficulty.pdf](https://github.com/ppy/osu-web/files/386171/BDI.-.Overall.Difficulty.pdf)
[BDI - Size.pdf](https://github.com/ppy/osu-web/files/386168/BDI.-.Size.pdf)
[BDI - Sliders.pdf](https://github.com/ppy/osu-web/files/386170/BDI.-.Sliders.pdf)
[BDI - Spinners.pdf](https://github.com/ppy/osu-web/files/386169/BDI.-.Spinners.pdf)

Here's them files.
