### ISSUE TITLE
Database connections should fallback

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#5597]
If a slave database is not available, the site should use master. It isn't currently.

**Comment by nanaya** [comment]
Duplicate of #5115? And maybe use mysql router instead of hacking php to do this manually?

**Comment by peppy** [comment]
I think it would be good to have something (even "hacky") in our code base for the time being. I've had serious performance and reliability issues with proxy setups in the past and don't foresee giving it another try for a couple of weeks at least.

Will close in favour of the other 2019(!) milestoned issue.
