### ISSUE TITLE
negative unread messages

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu-web#5598]
i dont know how to reproduce this. i dont really remember what i was doing so i cant give step by step instructions.

**NOTE:** im using the [osuplus extension](https://osu.ppy.sh/community/forums/topics/408541). i ave no idea if this could cause any compatibility issues.

**Screenshots:**
![chrome_ACvwPCcv6A](https://user-images.githubusercontent.com/43358824/73969203-46439400-491b-11ea-9590-6efcbaed8d00.png)
![chrome_ACQ83DrLUN](https://user-images.githubusercontent.com/43358824/73969219-4d6aa200-491b-11ea-8496-ebc05abacfe4.png)

**Comment by peppy** [comment]
does it resolve on refresh?

**Comment by mouzedrift** [comment]
yes

**Comment by GrilledCheeese** [comment]
I right clicked the new message to open in new tab, then I pressed the X to remove the notifications, making them 0, then in the new tab it did 0 - new messages:
![screenshot](https://i.imgur.com/XsZzgl5.png)
It gets fixed after sending a message back

**Comment by notbakaneko** [comment]
@GrilledCheeese was it a chat notification?

**Comment by stanriders** [comment]
You can also open chat in two new tabs, first you switch to will have 0 notifications, second will have negative. It resolves on refresh

**Comment by GrilledCheeese** [comment]
> @GrilledCheeese was it a chat notification?

Yes
