### ISSUE TITLE
base62_encode minor bug

### ISSUE THREAD

**Issue by miguelmartin75** [ppy/osu-web#56]
The [`base62_encode`](https://github.com/ppy/osu-web/blob/master/app/helpers.php#L280-L294) function has a very small bug in it, but I thought I'd mention it. If you call `base62_encode(0);` it will return an empty string, and I assume that is not what you want. A simple fix is to use a do-while loop instead of a while loop, like so:

```php
function base62_encode($input)
{
    $numbers = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ';
    $base = strlen($numbers);

    $output = '';
    $remaining = $input;

    do
    {
        $output = $numbers[($remaining % $base)].$output;
        $remaining = floor($remaining / $base);
    } while ($remaining > 0);

    return $output;
}
```

**Comment by nanaya** [comment]
good catch, thanks.
