### ISSUE TITLE
Missing User-Group-Badge Icon on Quick Search

### ISSUE THREAD

**Issue by Em0nky** [ppy/osu-web#5607]
Such as BN or ppy etc. Other users experiencing issue as well. Refreshing does not fix.

**Screenshots:**
![missingppy](https://user-images.githubusercontent.com/60788724/74045439-bfce9700-499a-11ea-9ecc-1e2bc10a7ef6.png)
![missingbn](https://user-images.githubusercontent.com/60788724/74045441-bfce9700-499a-11ea-817d-e945038eb5f0.png)

**Comment by Ephemeralis** [comment]
![](https://puu.sh/F8910/6aee0a63c7.png)

User (1421452) was recently awarded an Elite Nominator badge, which includes a custom title, and this appears to have broken the BN shortform bubble display on search as shown above.

This appears to be caused by custom ranks set via ASS.

**Comment by venix12** [comment]
seems like it's related to #5507, would attemt to fix it, but i don't have an environment set up, also @Ephemeralis the badge is based on usergroup, not custom title.
