### ISSUE TITLE
Country Cape Verde has bug on rank global's country

### ISSUE THREAD

**Issue by DevilPedrow** [ppy/osu-web#5610]
Hello,
I wanted to see the ratings in the country Cape Verde.
But the site simply goes back to the start of the global ranking.
As if Cape Verde did not exist on osu!
I'll leave a photo for your to understand what's going on:
http://prntscr.com/qxesvx (Cape Verde)
http://prntscr.com/qxetde

**Comment by notbakaneko** [comment]
There's currently no country ranking for Cape Verde, so it just redirects back to the main list
related: #3823 #4561

**Comment by peppy** [comment]
Would be great if we can not link in these cases.

**Comment by alolanraichulive** [comment]
closing for now on.

**Comment by nanaya** [comment]
Fixed in #9660.
