### ISSUE TITLE
Comments endpoint don't include deleted comments with some requests

### ISSUE THREAD

**Issue by EVAST9919** [ppy/osu-web#5611]
I'm talking about `comments?parent_id={id}` endpoint.
Good example: https://osu.ppy.sh/comments?parent_id=776359, in which you can see that deleted comment isn't included in the `CommentBundle`, but included here: https://osu.ppy.sh/comments/776359

**Comment by notbakaneko** [comment]
Deleted comments currently only show if they're listed as part of post/beatmap/whatever they're commenting on. They're not visible in the comments listing #4695 even if the count is visible.

**Comment by EVAST9919** [comment]
Hmm, I could've just use the second request, but seems like it return not every comment for very long trees (see https://osu.ppy.sh/comments/258, in which it rrtyui's comment has 149 replies, but loaded only 50)

**Comment by nanaya** [comment]
add `commentable_id` and `commentable_type` to the request parameters

**Comment by EVAST9919** [comment]
@nanaya thank you!
