### ISSUE TITLE
Add user title on forum

### ISSUE THREAD

**Issue by venix12** [ppy/osu-web#5612]
Seems like it would work nicely, especially for people with some kind of custom title, would mix great with usergroup badges informing about usergroup so it's not confusing, some examples of how i see it in mind, would be probably pretty much straightforward to implement if deemed fitting:

![](https://venix2.s-ul.eu/5eKquaW5) ![](https://venix2.s-ul.eu/eX7zankX)

It's probably also to note it would have a good informing role for support team

**Comment by peppy** [comment]
I don't see why this can't be present. @arflyte opinions?

**Comment by arflyte** [comment]
yeah, that sounds good. we can go with that.
