### ISSUE TITLE
Getting chat notification in web when connected via IRC

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#5616]
I don't believe this is intended behavior since this doesn't happen when I am have the game open

refering to these
![](https://i.imgur.com/dDiAD1Z.png)

**Comment by venix12** [comment]
I'm not really sure if this is possible, at the moment it probably gets information about read messages from some osu! client endpoint, which couldn't be used via pure IRC. (as long as it could not be done via some kind of chatbot or something)

**Comment by peppy** [comment]
irc isn't really core functionality and we don't really have plans of fixing this flow, sorry!
