### ISSUE TITLE
"Best Performance" Section not displaying top 100 plays after rollback.

### ISSUE THREAD

**Issue by amberkowalski** [ppy/osu-web#5619]
[Link to account where this behavior is displayed](https://osu.ppy.sh/users/11888158)
![image](https://user-images.githubusercontent.com/4877041/74350172-53c9a580-4d83-11ea-8f04-eff3724b037a.png)
The owner of the linked account was previously restricted (and upon unrestriction, had all their plays removed) and has since set more than 1 unique play on bancho. However, the "Best Performance" section of the profile only shows one play. This is the same issue reported in #3701, which had been reported as fixed.

**Comment by peppy** [comment]
Please report such issues to accounts@ppy.sh, not github. The user in question should contact us, not someone else.
