### ISSUE TITLE
Allow name history to be set to either public or private

### ISSUE THREAD

**Issue by huuishuu** [ppy/osu-web#5629]
Based on a post on /r/osugame [here](https://old.reddit.com/r/osugame/comments/f30pol/whats_the_point_of_this_message_if_people_can/), an idea a user has had was to allow us to hide our previous usernames on the website.

With the [top comment](https://old.reddit.com/r/osugame/comments/f30pol/whats_the_point_of_this_message_if_people_can/fhfutpp/) getting upvoted more than the original post itself, it's a safe bet this would be a decent quality-of-life addition to the new website for many.

It was suggested by someone to open an issue about this on Reddit but the OP never did so I guess I'll fill in for them.

**Comment by venix12** [comment]
Seems like it was discussed in #4406 already?

**Comment by huuishuu** [comment]
> 
> 
> Seems like it was discussed in #4406 already?

That was more so about removing it entirely from their profiles plus makes the user deal with it via osu! support. Should be something togglable on the site itself, at least that's what I think.

**Comment by venix12** [comment]
https://github.com/ppy/osu-web/issues/4406#issuecomment-489439059 that seems to be a reason why it's not a thing and probably shouldn't be, though

**Comment by huuishuu** [comment]
> 
> 
> [#4406 (comment)](https://github.com/ppy/osu-web/issues/4406#issuecomment-489439059) that seems to be a reason why it's not a thing and probably shouldn't be, though

I'm of the opinion that it should be up to the user whether they *want* to be tracked across username changes. Though that too has its own flaws. Still, I'm sure some middle-ground can be reached, like still being able to access someone's profile through an old username but it just doesn't display publicly. Just a quick idea I had floating in my head.

**Comment by cl8n** [comment]
also related is that reverted names are private, with no way to make them public again. the username I used to play tournaments with isn't shown on my profile at all, and that's probably how most people would recognize me =(

**Comment by peppy** [comment]
Hiding username history breaks osu! rules of keeping consistent history.

We can probably fix the revert case - usually reverts are used after only hours or days.
