### ISSUE TITLE
Add additional row of hearts to user profiles to represent supporter tags gifted to others

### ISSUE THREAD

**Issue by Romi969** [ppy/osu-web#5632]
For example they could be golden or red [like here](https://imgur.com/a/Ox1ZENs)

**Comment by peppy** [comment]
Is this intended to display on the person that gifted the tag to someone else?

**Comment by Romi969** [comment]
It could be for the person that gifted the tags.

**Comment by notbakaneko** [comment]
ok, that makes more sense then, I thought it made no sense to show gifted tags received

**Comment by arflyte** [comment]
![Figma_200313-125216](https://user-images.githubusercontent.com/3632750/76588102-7e954e00-6529-11ea-8adb-6ddfe2ce6b99.png)
Something like this? Hand handing out heart.

**Comment by arflyte** [comment]
![Figma_200313-134557](https://user-images.githubusercontent.com/3632750/76590602-06328b00-6531-11ea-9796-7c901cf74b54.png)
or something like this.

**Comment by cl8n** [comment]
this came up in the user card discussion https://github.com/ppy/osu-design/discussions/1#discussioncomment-11225987 , leaning toward *not* including this there, but maybe it'd still be relevant enough to show on the full profile page in some way.

**Comment by peppy** [comment]
Let's not do this.
