### ISSUE TITLE
Multiple issues with pinned comments

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#5634]
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/191335/74598136-4546fb00-50af-11ea-9e47-67d997ca87ce.png">

- Pinned comment should show above the composition box
- Pinned comment shouldn't show twice
- Should probably be highlighted (lighter background?) in some way to define it as a pinned, separate from the comments below
- Can't reply to pinned comments from the pin directly.

**Comment by peppy** [comment]
arbitrary highlights so that this actually gets seen

@arflyte @arflyte @arflyte @arflyte @arflyte @arflyte @arflyte @arflyte @arflyte @arflyte @arflyte @arflyte

**Comment by arflyte** [comment]
Lol. I'll look into it today.
