### ISSUE TITLE
Subscribing to mapper

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#5635]
There are many mappers that make great maps. Wouldn't it be great if you could be notified when they submit a new map?

I imagine there would be a page where you can manage your subscription for each mapper. You would be able to filter subscriptions by gamemode, star rating, CS (or keymode), OD, AR, and map length so you could receive notification for the types of maps you want. I don't know if filters should be global or per subscription.

**Comment by peppy** [comment]
Let's look at getting this in in a simple way (similar to forum thread subscriptions is fine, with a button on profiles to subscribe).
