### ISSUE TITLE
osu! web-chat text when starting a new conversation should be updated.

### ISSUE THREAD

**Issue by TobiasLeander** [ppy/osu-web#5641]
![chat text](https://user-images.githubusercontent.com/26700331/74672827-5a568380-51ae-11ea-914e-e5659a14fe9c.png)
When writing to people from the osu! web-chat you now also receive the messages on osu! which makes the claim that only osu!lazer or people on the new chat gets the message wrong.

**Comment by peppy** [comment]
Yep, this can be removed now.
