### ISSUE TITLE
Timeshift multiplayer rooms should return the list of participants

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-web#5647]
Currently only `participants_count` is returned, which means that osu!lazer's doing a subrequest for the leaderboard to retrieve the actual participants in the room (e.g. to display their avatars).

This is not enough since you can have e.g. 3 participants but 0 scores on the leaderboard.

**Comment by peppy** [comment]
I think we probably want to be doing a request in room selection, not getting participants in the main lobby request (to reduce the initial load/poll size).

Should probably be an explicitly get room info request though.
