### ISSUE TITLE
Accuracy styles are inconsistent on beatmap leaderboards

### ISSUE THREAD

**Issue by mouzedrift** [ppy/osu-web#5654]
![chrome_jNHNgDffe9](https://user-images.githubusercontent.com/43358824/74922848-20fd5e00-53d0-11ea-8e8d-d31291da9cfb.png)

The scores on the top show 100% accuracy while the other scores on the small leaderboard show 100.00% instead, is this intended?

**Beatmap:** https://osu.ppy.sh/beatmapsets/163112#osu/397536

**Comment by peppy** [comment]
@arflyte

**Comment by arflyte** [comment]
Hmm, must've missed it. Do players prefer it with the extra decimals or without?

**Comment by venix12** [comment]
i think it makes more sense with extra decimals, there's huge difference betwen let's say 99.10 and 99.95

**Comment by arflyte** [comment]
then let's add the extra decimals to the top.

**Comment by nanaya** [comment]
It's already showing decimal points for non-whole numbers though 

![](https://s.myconan.net/2020-03/firefox_2020-03-02_15-40-10.png)

https://osu.ppy.sh/beatmapsets/1007427#osu/2108552

**Comment by TheWildTree** [comment]
we've had this exact issue lazer side (ppy/osu#7763), ended up adding the decimal places to whole numbers too for the sake of consistency.
