### ISSUE TITLE
Navigation bar doesn't open on portrait

### ISSUE THREAD

**Issue by Cynplytholowazy** [ppy/osu-web#5655]
Navigation bar doesn't open on portrait mode. Confirmed in opera mobile / chrome / safari
Opera
![IMG_20200220_182847](https://user-images.githubusercontent.com/31384149/74925836-e61b1a80-540f-11ea-9297-dab839671a83.jpg)
Chrome
![image0](https://user-images.githubusercontent.com/31384149/74925848-eb786500-540f-11ea-9556-aef7e7e493a7.png)
Safari
![image0-1](https://user-images.githubusercontent.com/31384149/74925874-f6cb9080-540f-11ea-84d7-5615e2b1cb3a.png)

**Comment by notbakaneko** [comment]
should be fixed now
