### ISSUE TITLE
Picking a different reason for reporting on the site makes the dark overlay disapear.

### ISSUE THREAD

**Issue by TobiasLeander** [ppy/osu-web#5656]
![bad 1](https://user-images.githubusercontent.com/26700331/74958866-e31d2b80-5409-11ea-87a1-cb5b0af2efda.png)
![bad 2](https://user-images.githubusercontent.com/26700331/74958869-e57f8580-5409-11ea-93f5-ad21aec75060.png)

**Comment by notbakaneko** [comment]
looks like this bit from the new mobile navigation clearing any `Blackout` even if it wasn't set by it https://github.com/ppy/osu-web/blob/b0296b4b4e01aa5b1aa2c9fa93932918348c0b4c/resources/assets/coffee/_classes/nav2.coffee#L62-L63
