### ISSUE TITLE
Remove forum title display when badge is also present

### ISSUE THREAD

**Issue by Pachiru** [ppy/osu-web#5657]
For usergroups like BN, NAT and GMT (idk about Dev), it kinda look redundant to have twice the titles, like this > https://i.imgur.com/mdhRViG.png

The only way it could be really useful would be for people that have specific titles like "Elite Mapper" or else

**Comment by celerih** [comment]
Agree that it's redundant to have both, imo easiest solution is to have coloured user titles instead of both titles and that coloured thingie under it

**Comment by venix12** [comment]
well imo it's alright as-is tbh? it works fine for sake of consistency (with how it used to be so title on both user page and forum) and you can see what it goes for in one look as well.

**Comment by WalterToro** [comment]
I think there are 2 options:
- If the user title is the group default title (for example, "Global Moderator" for GMT) the user title shouldnt appear and the user group badge should be the only thing there (example, "Support Team" users should have both the user title and the user group badge).
- Put the usertitle inside the user group badge and recolor this with the user group team color.

**Comment by peppy** [comment]
Yeah, let's not show the title when the badge exists.

**Comment by nanaya** [comment]
There's no relation between badge and forum title so we either need to add such data or hide the title if any badge exists at all regardless whether they're related or not.

Or just remove the ranks/titles which are already represented by the badge.

**Comment by dorothy3242** [comment]
I'd think it'd be unfair to people that have a title like "Elite Mapper" AND have a usergroup to just remove titles for anyone with a usergroup badge.

So having some way to say (for example) "this user has BN fprum badge **and** BN title, hide the BN title" would be best.

**Comment by cl8n** [comment]
that's what nanaya means by "already represented by the badge"

if you choose to remove the ranks/titles, don't forget to show the usergroup badge somewhere on user profiles

**Comment by Ephemeralis** [comment]
I'm not entirely sure that reducing the visibility of the titles afforded to our community volunteers by 70-80% for the sake of design/logical consistency is the right approach to take here, especially when readability is impacted.

It might seem minor, but not only does the change outlined in #5701 significantly reduce the overall ability for users to discern what team presence *is* at a glance (Global Moderation Team is reduced to a green "GMT" splotch, the acronym for which could be easily misinterpreted as something related to timezone for new/uninvested users), but it also does extraordinarily little to engender good will from people who are sinking hundreds of hours of their lives into maintaining the social side of our project by directly limiting sometimes the sole accolade or marker of their contribution.

**Comment by peppy** [comment]
so just to clarify, you'd prefer both are displayed?

**Comment by Ephemeralis** [comment]
Yes. It is practically tradition, besides.

**Comment by peppy** [comment]
Okay, reverting and closing issue as invalid.
