### ISSUE TITLE
drop down menu isn't working in mobile

### ISSUE THREAD

**Issue by Furozzu** [ppy/osu-web#5658]
hi, this is my first time using github so sorry if i make some mistakes

so, as seen at title, there's some issue at dropdown menu, it can't show anything. there some screenshoot showing this problem

![IMG_20200221_004506](https://user-images.githubusercontent.com/29659076/74963341-23999b00-5444-11ea-889e-5820cf7b7c13.jpg)

![IMG_20200221_005051](https://user-images.githubusercontent.com/29659076/74963404-3f9d3c80-5444-11ea-9ab5-16aab2fb3b06.jpg)

i hope this can fixed soon since i tend to use mobile to open osu alot

**Comment by peppy** [comment]
Similar issue to https://github.com/ppy/osu-web/issues/5655 which was apparently fixed somehow without changes at our end. I can't reproduce this, so maybe a caching thing? @notbakaneko

**Comment by notbakaneko** [comment]
it's a caching issue

**Comment by peppy** [comment]
@Furozzu please try refreshing the page a few times and report back if it's fixed.

**Comment by Furozzu** [comment]
ok its fixed, thanks dev team
