### ISSUE TITLE
Update English flag

### ISSUE THREAD

**Issue by Luxiono** [ppy/osu-web#5660]
Update the English flag to use both the UK and US flag. Here is a rough version of it. (Keep in mind it looks pretty bad):
![GB](https://user-images.githubusercontent.com/55364481/74997615-79f6e180-5424-11ea-8300-c6d2a761f107.png)
I don't want to make this a pull request until I improve the image, but changing the image shouldn't have any affects, as it has the same file name.

**Comment by Luxiono** [comment]
![GB](https://user-images.githubusercontent.com/55364481/74997872-2e910300-5425-11ea-9c0e-2e2920b16d06.png)
Updated version, rounding a corner I forgot.

**Comment by notbakaneko** [comment]
We're not changing flags
