### ISSUE TITLE
Format links on website chat

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#5669]
in-game formatting links as [link text] will display the text as a clickable hyperlink.
this isn't true of the website, which makes that formatting look a lot more messy, especially for /np'd maps

Image examples:
website chat:
![image](https://user-images.githubusercontent.com/33286824/75099616-a419e200-5591-11ea-9262-d9ade84c1dcd.png)

vs in-game:
![image](https://user-images.githubusercontent.com/33286824/75099621-ab40f000-5591-11ea-9a5c-0385054e4e53.png)

On the website, links should be able to use the same formatting and behavior as in-game to bring the two platforms closer together.

**Comment by cl8n** [comment]
wiki links too, they show up as the raw text (`[[Page]]`) on web

**Comment by nanaya** [comment]
This has been implemented.
