### ISSUE TITLE
Quick Ubuntu development setup script is outdated

### ISSUE THREAD

**Issue by Tetriando** [ppy/osu-web#5672]
I just planned to start contributing and set up fresh Ubuntu VM. After using priovided bootstrap.sh it seems that php is outdated there. I will try to increment it, retry and provide adequate PR for that.

![image](https://user-images.githubusercontent.com/1027662/75114965-d17e9280-565a-11ea-8b5c-9ba406b69e81.png)

**Comment by venix12** [comment]
why not use docker though

**Comment by Tetriando** [comment]
> why not use docker though

Sure, that's also one of the options.

Maybe this issue is about something more like for example deciding on officially supported setup options mentioned in README

**Comment by bdach** [comment]
IMO if it's in the docs, the script should be supported and updated. If it's deemed to be unsustainable to maintain it due to the amount of work required, then it should be removed from the repo and the docs altogether.

**Comment by peppy** [comment]
I would still propose *only supporting docker* officially and leaving other setups up to the user.

**Comment by Tetriando** [comment]
> I would still propose _only supporting docker_ officially and leaving other setups up to the user.

In that case I will adjust docs and remove outdated scripts from the project
