### ISSUE TITLE
Online user count is not shown for lazer on changelog page

### ISSUE THREAD

**Issue by jai-x** [ppy/osu-web#5675]
Unsure if this is intended for now:

<img width="641" alt="Screenshot 2020-02-25 at 14 05 21" src="https://user-images.githubusercontent.com/8362491/75254508-5c38cc00-57d8-11ea-86ed-7d3bb3620f51.png">

**Comment by peppy** [comment]
there is no such data yet.

**Comment by hrfarmer** [comment]
I noticed that the osu status page shows the number of people online on lazer now, is it possible to add the number of people on lazer to the changelog now?

**Comment by peppy** [comment]
Not quite, but getting closer.
