### ISSUE TITLE
Legacy beatmaps which have Unicode characters don't show correctly

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu-web#5678]
Examples:
https://osu.ppy.sh/beatmapsets/93
https://osu.ppy.sh/beatmapsets/104
https://osu.ppy.sh/beatmapsets/106

The legacy beatmaps which don't have separate fields for Unicode Title and Unicode Artist in the .osu files, so the Title and Artist is filled with Unicode characters (and they don't have Romanized fields).
The downloaded .osz files also have wrongly encoded filenames.

**Comment by peppy** [comment]
I fixed these and a few others I found along the way. Please post again if you find any more.

**Comment by huupoke12** [comment]
The beatmap https://osu.ppy.sh/beatmapsets/63240 actually don't have a display issue, but it's using an Unicode title for the Title field, and non-Unicode title for the TitleUnicode field.
``` .osu
Title:TSU·BA·SA (TV Size)
TitleUnicode:TSU.BA.SA (TV Size)
```
