### ISSUE TITLE
Weird white dots on beatmap panels

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#5679]
![image](https://user-images.githubusercontent.com/191335/75316102-c2d8eb00-58a7-11ea-88ba-0ce3ab2971fd.png)

Not sure what these are but @arflyte has confirmed it's not intentional.

**Comment by notbakaneko** [comment]
which map is this?

**Comment by notbakaneko** [comment]
Safari?

**Comment by peppy** [comment]
All maps with no thumbnail, and yes, safari :|.

**Comment by notbakaneko** [comment]
This seems to happening if the element doesn't have exactly the same `border-radius` for all corners

**Comment by notbakaneko** [comment]
reproducible test case: https://jsfiddle.net/notbakaneko/dn32o7v8/
seems specific to newer versions of Webkit?

![image](https://user-images.githubusercontent.com/1694544/75413744-be750680-5969-11ea-9e71-08cb2dad7758.png)

**Comment by peppy** [comment]
is it worth reporting to webkit or is there already an issue for it?

**Comment by peppy** [comment]
Based on lack of response just going to assume this is not worth following up on and will learn to live with it.
