### ISSUE TITLE
Beatmap pages should show accurate dates for their data

### ISSUE THREAD

**Issue by underscorePendere** [ppy/osu-web#5682]
Dropping in from replies on [this tweet](https://twitter.com/Typobad/status/1232787599238062083), I personally think the change in the beatmap description is better to be changed back to its old functionality.

While on user profiles it's alright to have less accurate time indicators shown for account creation and last login, for beatmaps these dates have a lot more meaning to them. The date of a beatmap, when combined with the beatmap creator's name, can sometimes quickly give a player information about the map they are playing. Within a year's time a mapper's style or skill in mapping can change a lot, when you see the difference between perhaps a early [2010 Happy30 map](https://osu.ppy.sh/beatmapsets/13223#osu/53554) and [one from just a few months later](https://osu.ppy.sh/beatmapsets/17670#osu/62963) a player might recognize them as probably not being similar due to the experience a mapper can gain between this time.

To tl;dr: the dates between profiles and beatmap descriptions serve different purposes which I think are important enough to keep in mind, this being inconsistent between pages isn't bad (as long as stuff on the same page is the same) if it means giving more important information to the user from the start (as opposed to having to hover over the "x time ago" to see the accurate date.)

**Comment by nanaya** [comment]
This got proposal label but it's also added to milestone. Are we reverting the change...? @peppy

**Comment by peppy** [comment]
Yeah I milestoned it so it would get a decision made sooner rather than later. @arflyte agreed to reverting it, but on the flip side I haven't heard many people complaining about it recently.

Personally I do agree that TimeAgo format gets pretty obnoxious at x years ago (with rounding imprecision). Maybe we could take a halfway point and start showing the absolute date after 4 weeks? Or maybe that is worse UX due to it changing depending on which page you view?

**Comment by Aquaaaa** [comment]
i want my accurate dates back. what's the point of submitting a map on someone's birthday if it isn't visible on the map page...

**Comment by peppy** [comment]
it is visible in the same way every other date is visible on the site / game (via tooltip). this is not a valid point. if you want to wish someone for their birthday please include it in the storyboard or description.

**Comment by Mordredosu** [comment]
making it exact again after 4 weeks sounds good

**Comment by NevarrenF** [comment]
After 4 weeks does sounds good as a halfway point
