### ISSUE TITLE
Reply function automatically reopens a closed issue

### ISSUE THREAD

**Issue by Raidencio** [ppy/osu-web#5692]
Link to the issue: https://osu.ppy.sh/beatmapsets/800102/discussion/-/generalAll#/1421172

it's causing quite a ruckus and needed GMT intervention

**Comment by Raidencio** [comment]
it seems to have been resolved? please confirm

**Comment by ekisu** [comment]
https://github.com/ppy/osu-web/blob/ed359c12f2911541cf24de057c9ee8f9dd70c424/resources/assets/coffee/react/beatmap-discussions/new-reply.coffee#L170-L177

Seems like when you just press Enter, it keeps the `resolved` state as it was before posting, so if someone resolves the issue when another person is writing a reply, and that person didn't refresh the page to the new `resolved` state, it will just rollback to the old state.
