### ISSUE TITLE
"Friends" buttons are not the same height

### ISSUE THREAD

**Issue by IvanovVN** [ppy/osu-web#5713]
For some reason they are not equal to each other. So when you switch between your page and someone else's the content below this buttons is "jumping".

_Your profile_:
![image](https://user-images.githubusercontent.com/41357019/76057370-0c6eb780-5fc5-11ea-8549-f39467755691.png)

_Friend's profile_:
![image](https://user-images.githubusercontent.com/41357019/76057387-1f818780-5fc5-11ea-9112-ba13aac3104a.png)

_Someone else's profile_:
![image](https://user-images.githubusercontent.com/41357019/76057440-43dd6400-5fc5-11ea-8eba-193a7dd6c9a6.png)

**Comment by peppy** [comment]
Should be a 5 minute fix, hopefully.
