### ISSUE TITLE
bold and small torus looks too cramped in popular beatmaps

### ISSUE THREAD

**Issue by venix12** [ppy/osu-web#5718]
changing ``font-weight`` to 400 would keep the emphasis and look better i believe
![](https://venix2.s-ul.eu/KrLedG4O) ![](https://venix2.s-ul.eu/Q0hw77Sa)

(is possibly a thing on other places as well, haven't found them at the moment though)

**Comment by Joehuu** [comment]
Fixed in https://github.com/ppy/osu-web/pull/5720.
