### ISSUE TITLE
Featured Artists listing should use regular font-weight

### ISSUE THREAD

**Issue by venix12** [ppy/osu-web#5719]
![](https://venix2.s-ul.eu/Vd6PNZwW) 
![](https://venix2.s-ul.eu/qY8xLWNd)

``300`` looks quite distracted and not really comfortable to read, would suggest going for regular ``400`` to improve readability, it would also make it consistent with forum posts/userpages.

(same goes for beatmap packs most likely)

**Comment by peppy** [comment]
@arflyte

**Comment by arflyte** [comment]
Must've missed this one. All content should be in Regular 400.
