### ISSUE TITLE
Inconsistent font in Vietnamese

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu-web#5721]
For the other language which Torus doesn't support, it fallbacks fine to the system installed font (such as CJK). But with Vietnamese, only some characters are being fallbacked, leading to this:

![image](https://user-images.githubusercontent.com/16283764/76079185-bc005580-5fd6-11ea-9cae-b2695d871e67.png)

**Comment by peppy** [comment]
@arflyte suggestions?

**Comment by arflyte** [comment]
Yikes, I thought it already had all the glyphs. I'll look into this today.
