### ISSUE TITLE
Star rating color problem on mouseover

### ISSUE THREAD

**Issue by Flashbangy** [ppy/osu-web#5724]
There is a problem with the font color on the diff's inheriting the black color when the mouseover box is also black. Its very hard to see the number on a TN pannel laptop screen on full brightness.

Maybe making the color of the star rating number white or light gray would be a good option?
You can see the blue and pink ones just fine if this makes sense.

![unknown](https://user-images.githubusercontent.com/44573779/76085778-01ab2700-5fb3-11ea-8d3a-e355fcde0bc1.png) ![chrome_2020-03-06_14-02-00](https://user-images.githubusercontent.com/44573779/76085839-1687ba80-5fb3-11ea-9e52-e888b280f3c4.png)

**Comment by peppy** [comment]
This has already been resolved. Please refresh.
