### ISSUE TITLE
Changelog url on Api v2 docs goes to localhost by default

### ISSUE THREAD

**Issue by DMills94** [ppy/osu-web#5727]
https://docs.ppy.sh/#changelog

Think this is the right repo for this? Apologies if not

**Comment by aspriddell** [comment]
It's not just the changelog url - it's across the entire documentation (see the examples down the side). 

Not too critical but will need updating at some point (maybe when more scopes are exposed and the documentation is more complete?)

**Comment by notbakaneko** [comment]
Should be correct now
