### ISSUE TITLE
Nomination status bar should cover full width if there is no nominate button

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#5728]
For non-BNs, the nom status bar is never full width, as they can't see the nomination button.
![Screen Shot 2020-03-07 at 2 27 07 PM](https://user-images.githubusercontent.com/30382015/76154416-c5e68f00-6090-11ea-97cb-2d1b93348859.png)

Should also apply to BNs and similar usergroups if looking at their own maps

same as #1977 but that was 2 years ago and was fixed, probably just a regression

**Comment by cl8n** [comment]
gets weirder when you have buttons that don't fit in line with either of hype or nomination
![image](https://user-images.githubusercontent.com/9954349/76154758-bc602580-6096-11ea-9203-13e71d73a9cb.png)

**Comment by nanaya** [comment]
The buttons are a bit out of control so I'm thinking of moving the whole buttons to bottom instead.

Hi @arflyte please check this.

Current:
![](https://s.myconan.net/2020-03/firefox_2020-03-31_19-58-33.png)

Proposed (not sure if the buttons should have same width or not):
![](https://s.myconan.net/2020-03/firefox_2020-03-31_19-58-00.png)

**Comment by arflyte** [comment]
Yeap, look alright to me. Let's go with it.
