### ISSUE TITLE
Display multiple usergroup-badges in profile for users in multiple usergroups

### ISSUE THREAD

**Issue by Kuron-kun** [ppy/osu-web#5739]
![uwu](https://user-images.githubusercontent.com/23140655/76237695-724d8000-620d-11ea-88d4-e41d4d4cf46a.png)

people who belong to multiple usergroups should have their badges in profile.

since you can basically have a single user title, and some titles/groups have priority over others, having multiple usergroup badges would help identifying the user's roles.

**Comment by venix12** [comment]
that's in plans iirc?

**Comment by peppy** [comment]
With the way we structure user group permissions, I believe this is redundant. If we did this we'd have to start hiding specific combinations. @Ephemeralis thoughts?

**Comment by venix12** [comment]
well, you could technically add ``displayed`` (or whatever name you want) column to user groups pivot table and loop through``true`` ones for display only

**Comment by peppy** [comment]
That's not what I mean. It would be a precedence thing.

**Comment by Ephemeralis** [comment]
Some groups are not necessarily exclusive, someone can be a BN and basically any other titled usergroup simultaneously. NAT can also be GMT (and vice versa), but they also are essentially BN de facto, so they wouldn't double up on NAT-BN either.

The only real case of exclusivity is that someone cannot be an Alumni and either a GMT or NAT at the same time, they lose ALM status until their next extended absence from the team. This is usually reflected in usergroup changes upon return though, so is probably a non-factor.

I think there's definitely an argument for having multiple badges indicate usergroup belonging as above. Previously, the only way this was tracked was either by having mismatched colours with titles (aka, a GMT/NAT would have a green username w/ NAT title) or by a wiki page made by someone actually tallying who belonged to multiple groups simultaneously.

**Comment by Hiviexd** [comment]
so are there any updates on this proposal?
I get that this feature seems redundant in certain cases (like giving a NAT the BN badge), but at least it would clear up some confusion regarding GMT being BNs

examples of such individuals:
https://osu.ppy.sh/users/2239480
https://osu.ppy.sh/users/394326
https://osu.ppy.sh/users/626907

**Comment by peppy** [comment]
I guess we should just implement this and fix individual cases.
