### ISSUE TITLE
[false alert] Unknown database 'osu_chat'  when trying to migrate

### ISSUE THREAD

**Issue by Akuba-** [ppy/osu-web#574]
When I run "artisan migrate" or "artisan migrate:refresh" I always get this error:
  [PDOException]                                    
  SQLSTATE[HY000] [1049] Unknown database 'osu_chat'

Cannot fix this myself since I do not know the fieldnames/types of this table.

**Comment by nanaya** [comment]
it is usually recommended to read the error message when diagnosing a problem.

**Comment by Akuba-** [comment]
... oh ... database.

I thougt it was a table for some reason :s.

**Comment by TPGPL** [comment]
close this issue
