### ISSUE TITLE
Group names are missing from group pages

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#5740]
i.e. 
https://osu.ppy.sh/groups/4
https://osu.ppy.sh/groups/7
https://osu.ppy.sh/groups/28
https://osu.ppy.sh/groups/32

are all just labelled as "unknown" where the title of the group would be listed previously.
may apply to other groups as well

may be a weird side effect of the changes from the following issue: https://github.com/ppy/osu-web/issues/5657

**Comment by peppy** [comment]
Looks like a regression.
