### ISSUE TITLE
Landing background video causes severe lagging on low-end hardware

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu-web#5747]
The landing video causes my phone severe lagging on my (low-end) phone when I'm not logged in. It is unable to do anything without severe lagging until logging in.

**Comment by peppy** [comment]
What phone are you using?

**Comment by huupoke12** [comment]
Nokia 3. The browser I'm using is Firefox.
I have also tested on a Chromium-based browser and did not have this issue. Maybe it's a Firefox bug which it doesn't have Hardware video acceleration.

**Comment by peppy** [comment]
We've tested going back quite far with hardware and the video works fine. I'm going to close this as a browser-specific issue.
