### ISSUE TITLE
Torus doesn't support Cyrillic script

### ISSUE THREAD

**Issue by IvanovVN** [ppy/osu-web#5749]
So combination of _Latin & Cyrillic scripts_ or _Numbers & Cyrillic script_ makes texts kinda weird or messy. I don't really know what you can do with it. :I

_Russian:_
![image](https://user-images.githubusercontent.com/41357019/76312270-66051800-631e-11ea-8e44-fa597f49ea89.png)

_Byelorussian:_
![image](https://user-images.githubusercontent.com/41357019/76312388-afedfe00-631e-11ea-853a-e1083af20038.png)

_Bulgarian:_
![image](https://user-images.githubusercontent.com/41357019/76312527-00fdf200-631f-11ea-81d1-ac5cf59b347f.png)

_Ukrainian:_
![image](https://user-images.githubusercontent.com/41357019/76312693-4f12f580-631f-11ea-877f-80e628a61140.png)

These are just the examples. The problems are similar in principle.

**Comment by peppy** [comment]
We've [changed the font fallback order](https://github.com/ppy/osu-web/pull/5784) to alleviate this issue. Hopefully things look better for you now.
