### ISSUE TITLE
Where is the 'view' function defined?

### ISSUE THREAD

**Issue by miterosan** [ppy/osu-web#577]
Where is the 'view' function defined?
http://puu.sh/pjf5R/57b0365da0.png

and also where does 'users.show' come from / gets defined?

**Comment by LiquidPL** [comment]
`view` comes from laravel itself, so its not written by us.

As for `users.show`, check `resources/views/users/show.blade.php`.

**Comment by miterosan** [comment]
oh okay, thanks

**Comment by normundy** [comment]
Going through this series can help 

https://laracasts.com/series/laravel-5-from-scratch

**Comment by miterosan** [comment]
Okay I'll look into that too

**Comment by miterosan** [comment]
@LiquidPL is there somewhere a place where i can ask you questions (programming related) to you?

**Comment by peppy** [comment]
You can join our semi-public discord network and chat in the osu-web channel.

https://discord.gg/013KEJ9ERBQU595KN
