### ISSUE TITLE
Remove white box including a saved text in chat

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#5777]
The white box with a text you wrote in the past isn't needed in the chat, you probably won't write this another time 
Can we remove this somehow? It only shows when you click on the text bar

![zOYSCPC](https://user-images.githubusercontent.com/32525896/76681499-bcf73f80-65f3-11ea-90da-2555cffa530c.png)
_please don't mind the text_

**Comment by notbakaneko** [comment]
disabled in #5772
