### ISSUE TITLE
Load infos of profile page on demand instead of on page load

### ISSUE THREAD

**Issue by ghost** [ppy/osu-web#578]
I am currently changing that profile pages stop loading things like allscores... in inital page load.
Instead the infos should be loaded seperate and on demand only. 

I do it over a GET command.

t: section of the profile like allScores or allScoresBest
offset: offset of the info
limit: limit of the requested info
http://puu.sh/pjkba/5a006f7a90.png

Are there some opinions about this?
- [x]  inital implementation
- [x]  limiting results
- [x]  adding offset
- [ ]  implement it into the current webpage

**Comment by peppy** [comment]
make it happen
