### ISSUE TITLE
What is thd standart pass and username for mysql?

### ISSUE THREAD

**Issue by miterosan** [ppy/osu-web#58]
What is the standart pass and username for mysql?

**Comment by Tewki** [comment]
osu and no password

**Comment by nanaya** [comment]
I think it's `osuweb`...

**Comment by miterosan** [comment]
thank you two!

**Comment by TheHowl** [comment]
you can also login as root. there's still no password even if you login 
as root, so `vagrant ssh` and then `mysql -u root` should do it
