### ISSUE TITLE
Jul 2013 set of news posts has incorrect links

### ISSUE THREAD

**Issue by STCapricorn** [ppy/osu-web#5801]
at news post [The Revival](https://osu.ppy.sh/home/news/2013-07-31-the-revival), the "Newer post" button points to [Clicking Styles](https://osu.ppy.sh/home/news/2013-07-31-clicking-styles), and vice versa for the "Older post" button at Clicking Styles.

note that this is only a problem with the Jul 2013 set; the rest point to other posts correctly, including [osu!test build now more usable](https://osu.ppy.sh/home/news/2013-08-08-osutest-build-now-more-usable); the first of the Aug 2013 set

**Comment by STCapricorn** [comment]
actually, the posts in between also have the same problem; "Newer post" and "Older post" point to Clicking Styles and The Revival respectively.

**Comment by notbakaneko** [comment]
All the posts in July 2013 have the same date for some reason

**Comment by peppy** [comment]
Unfortunately it's also what twitter shows, and I can't find any better source. Someone may need to do some archive.org digging to solve this.

![image](https://user-images.githubusercontent.com/191335/77223975-a711ed80-6ba4-11ea-8405-ed96ac2a848f.png)

Closing in favour of https://github.com/ppy/osu-wiki/issues/3346.
