### ISSUE TITLE
"show more" button for top plays list doesn't show

### ISSUE THREAD

**Issue by pavlukivan** [ppy/osu-web#5804]
![](https://i.imgur.com/naE3XwE.png)

On the top: "best performance", no "show more" button    
On the bottom: "first place ranks", there is a "show more" button

**Comment by peppy** [comment]
It looks to be showing correctly for me. Please include the user whose profile you are seeing this issue on.

**Comment by pavlukivan** [comment]
https://osu.ppy.sh/users/7160196

**Comment by pavlukivan** [comment]
indeed, it works correctly on my own profile

**Comment by pavlukivan** [comment]
it actually happens on pc as well

**Comment by peppy** [comment]
Fixed.
