### ISSUE TITLE
news index has strange behavior when there aren't many posts in current year

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#5805]
- sidebar looks really empty for a news front page
- the main view loads 12 posts regardless, so some will be from the previous year, which doesn't match the sidebar
- "show more" probably doesn't work because it tries to load posts from current year

**Comment by peppy** [comment]
@arflyte 

might be better to show previous x months?

**Comment by arflyte** [comment]
true. let's show the previous 2 months for January, Feb and March.
