### ISSUE TITLE
Docker setup is not working

### ISSUE THREAD

**Issue by taylankasap** [ppy/osu-web#5809]
Steps:
1. `$ export UID`
2. `$ docker-compose up`

Error:
![image](https://user-images.githubusercontent.com/4192479/77245148-7f1a9c80-6c2d-11ea-93ad-787c71cb1d53.png)

Sometimes there is a different error but I can't reproduce this reliably:
![image](https://user-images.githubusercontent.com/4192479/77245176-b0936800-6c2d-11ea-8b47-96490dd6277a.png)

There is also this line getting spammed at the end of terminal, is this in any way related?
```
notification-server_1  | OAuth public key hasn't been created. Sleeping for 5 seconds before starting again...
```

Trying to troubleshoot:
- Accessing localhost:8080 redirects to localhost:8080/home so php is working.
- I logged in to mysql container and `mysql.user` table doesn't have `osuweb` user
- In mysql container db_setup.sh and db_user.sql exists inside /docker-entrypoint-initdb.d
- Looks like db_user.sql is not running for some reason. (Changing the `database` volume name also doesn't work, but I'm not sure if it was supposed to work in the first place.)

**Comment by taylankasap** [comment]
Oh, I forgot to mention my system.

Windows 10 Version 2004 build 19041.153
Docker Desktop Version 2.2.2.0 (43066) | Channel: edge | Engine: 19.03.5 | Compose: 1.25.4
I'm using WSL2 if it is important.

Note that I've been using Docker for a while now and so far it worked without problems with both my projects and other open source projects.

**Comment by peppy** [comment]
The mysql "unknown method" part makes it seem like you are running an old version of mysql, somehow. Do you have other docker containers running on the same PC?

**Comment by taylankasap** [comment]
I have other mysql containers - that use 5.7 - but they are not running at the same time if that's what you're asking. But shouldn't changing db volume name create a fresh volume for that mysql container on the host? Would they even conflict?

Also when I log in to osu db container and check out mysql users/databases I don't see anything from my other containers.

**Comment by taylankasap** [comment]
By the way:
```
$ docker-compose exec db mysql --version
mysql  Ver 8.0.19 for Linux on x86_64 (MySQL Community Server - GPL)
```

**Comment by taylankasap** [comment]
I have changed the project name (by adding `COMPOSE_PROJECT_NAME=osu-web-taylan-test-1` to .env file) so I can test from fresh and I noticed it gives this error on my very first `docker-compose up`. If I run it again then it goes back to the errors I mentioned in my first comment.

I can reliably get this error if I change my project name to something unique:

```
db_1                   | 2020-03-22 10:13:45+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.19-1debian10 started.
db_1                   | 2020-03-22 10:13:45+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
db_1                   | 2020-03-22 10:13:45+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.19-1debian10 started.
db_1                   | 2020-03-22 10:13:45+00:00 [Note] [Entrypoint]: Initializing database files
db_1                   | 2020-03-22T10:13:45.679305Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.
db_1                   | 2020-03-22T10:13:45.679361Z 0 [System] [MY-013169] [Server] /usr/sbin/mysqld (mysqld 8.0.19) initializing of server in progress as process 42
db_1                   | 2020-03-22T10:13:47.935360Z 5 [Warning] [MY-010453] [Server] root@localhost is created with an empty password ! Please consider switching off the --initialize-insecure option.
db_1                   | 2020-03-22 10:13:50+00:00 [Note] [Entrypoint]: Database files initialized
db_1                   | 2020-03-22 10:13:50+00:00 [Note] [Entrypoint]: Starting temporary server
db_1                   | 2020-03-22T10:13:51.030792Z 0 [Warning] [MY-011070] [Server] 'Disabling symbolic links using --skip-symbolic-links (or equivalent) is the default. Consider not using this option as it' is deprecated and will be removed in a future release.
db_1                   | 2020-03-22T10:13:51.030900Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.19) starting as process 92
db_1                   | 2020-03-22T10:13:51.510694Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
db_1                   | 2020-03-22T10:13:51.513957Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
db_1                   | 2020-03-22T10:13:51.529906Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.19'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MySQL Community Server - GPL.
db_1                   | 2020-03-22 10:13:51+00:00 [Note] [Entrypoint]: Temporary server started.
db_1                   | 2020-03-22T10:13:51.616634Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Socket: '/var/run/mysqld/mysqlx.sock'
db_1                   | Warning: Unable to load '/usr/share/zoneinfo/iso3166.tab' as time zone. Skipping it.
db_1                   | Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
db_1                   | Warning: Unable to load '/usr/share/zoneinfo/zone.tab' as time zone. Skipping it.
db_1                   | Warning: Unable to load '/usr/share/zoneinfo/zone1970.tab' as time zone. Skipping it.
db_1                   |
db_1                   | 2020-03-22 10:13:53+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/db_setup.sh
db_1                   |
db_1                   | /usr/local/bin/docker-entrypoint.sh: line 192: $1: unbound variable
db_1                   | 2020-03-22 10:13:53+00:00 [Note] [Entrypoint]: /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/db_user.sql
osu-web-taylan-test-1_db_1 exited with code 1
```

**Comment by taylankasap** [comment]
After some hours of troubleshooting I've found out running `db_user.sql` before `db_setup.sh` (renaming db_user.sql to a_db_user.sql **inside** the container) fixes the issue.

I still don't know the reason though. Any ideas?
