### ISSUE TITLE
Track missing + wrong name in Featured Artist page

### ISSUE THREAD

**Issue by TamamoNoMae13** [ppy/osu-web#5816]
https://osu.ppy.sh/beatmaps/artists/23
In album RECORD5-SPEED: missing 1 track named "Flugel"
And the track with "Han" name is supposed to be "Hanaarashi".

**Comment by peppy** [comment]
cc @Ephemeralis

**Comment by TamamoNoMae13** [comment]
![image](https://user-images.githubusercontent.com/50830861/79415050-44ffa900-7fe7-11ea-9aa2-1801ac16ca79.png)
Missing "Flugel", img taken from: http://felinegroove.shop-pro.jp/?pid=90783431

**Comment by Ephemeralis** [comment]
Flugel turned out to be nearly impossible to time with the person responsible for timing things back then. I'll see if that's still the case now, but it was an absolute clusterfuck from memory.

The Hanaarashi change has been applied, though!

**Comment by peppy** [comment]
Closing this for now I guess.

**Comment by peppy** [comment]
@Ephemeralis I wouldn't be against that track being made available *without* timing as an exception. I'm sure there's someone out there willing to put in the effort.

**Comment by Ephemeralis** [comment]
pishi's taking a stab at it, if he can't manage it then we can shove it up as an untimed osz, I guess.

**Comment by Ephemeralis** [comment]
Flugel's now available from Cranky's FA listing thanks to the extraordinary efforts of pishifat. Please shed a single tear for his loss.

![](https://puu.sh/FB6Qr/de3c0c4f8c.png)
