### ISSUE TITLE
Site doesn't handle sessions properly

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#5822]
Recently the site started logging me out for no reason after the browser tab was closed. I checked the web sessions section in account settings and it looked like this:

![image](https://user-images.githubusercontent.com/19843905/77595968-f6388500-6efa-11ea-994a-3508992388e7.png)

All those sessions are from the same IP address and browser, which means the site doesn't handle sessions correctly anymore.

**Comment by peppy** [comment]
This means you have changed your browser/PC privacy sessions and are destroying your cookies.
