### ISSUE TITLE
Brick user listing improvements

### ISSUE THREAD

**Issue by venix12** [ppy/osu-web#5823]
after looking on and collecting some opinions about new brick user listing, some ideas on how to improve it came to my mind: 
- show friend button even if a person isn't your mutual, wouldn't take a lot of place and would be kinda useful i believe, it would also make non-mutual users much easier visible if you've got a lot of friends
- make bricks even smaller, seems like it wouldn't hurt design much, however it would be nice to see entire friend list at one glance, the comparison below:

**Currently:**
![](https://venix2.s-ul.eu/VxUMdZHO)
**After changes:**
![](https://venix2.s-ul.eu/rJtKK2ek)
(changed ``height`` of ``user-card-brick`` to 25px, and ``font-size`` of ``user-card-brick__username`` to 13px - ``font-size--normal-2``)

**Comment by peppy** [comment]
@arflyte

**Comment by arflyte** [comment]
Wouldn't that be too busy? Unless the brick version is solely meant for screenshot purposes, then yeah.

**Comment by arflyte** [comment]
Did some test. Yeah, let's go with 25px height, 13px font. But remove the mutual icon, and use a pink border like the old site instead.
