### ISSUE TITLE
where is the this.setstate()?

### ISSUE THREAD

**Issue by miterosan** [ppy/osu-web#583]
In the file "\osu-web\resources\assets\coffee\react\profile-page\historical.coffee"
line 31 is a invoke for the @setState function. (this.setState(..., ..., ...) )

But where is the difinition of the function?

**Comment by LiquidPL** [comment]
1. First, it's `setState`, not `getState`.
2. Check https://facebook.github.io/react/docs/component-api.html.
3. Get on that Discord server peppy mentioned earlier and ask questions there.

**Comment by miterosan** [comment]
thank you!
