### ISSUE TITLE
auth/authorize returns 400 after user authentication

### ISSUE THREAD

**Issue by UncleGoogle** [ppy/osu-web#5832]
I've followed API v2 documentation instruction: https://osu.ppy.sh/docs/index.html#authorize-users-for-your-application
and created API access with client_id=929 and url=https://gog-galaxy-osu.net/redirect

I want to redirect user via oauth/authorize to got code which can be exchanged to refresh token:
http://osu.ppy.sh/oauth/authorize?client_id=929&redirect_uri=https://gog-galaxy-osu.net/redirect&scope=identify,friends.read,users.read

After inserting credentials and email verification code I got this:
https://i.gyazo.com/827085245423615baad14e0a81be9f2a.mp4

"
layout.errors.400.error
The authorization grant type is not supported by the authorization server.
layout.errors.400.description
"

Expected:
- redirect to `https://gog-galaxy-osu.net/redirect`

**Comment by MoeLava** [comment]
You also need `response_type=code` in your query parameters, the documentation doesn't seem to mention this however
Also, seperate your scopes with spaces or `+`

**Comment by UncleGoogle** [comment]
@MoeLava 
Thanks, it works!

I'm leaving the issue opened until docs are updated. Are docs in this repo? I do not see

**Comment by robinknaapen** [comment]
It is in the docs though.

`POST http://osu.ppy.sh/oauth/token`

Parameters:
- code: the code you received

**Comment by peppy** [comment]
Yes, docs are generated from this repo via `php artisan apidoc:generate`

The documentation in question is at
https://github.com/ppy/osu-web/blob/e8eda3fd9e129ea61fc1fda23fc859ea579c4310/resources/views/vendor/apidoc/partials/info.blade.php

cc @notbakaneko
