### ISSUE TITLE
[Question] Client secret vs desktop app

### ISSUE THREAD

**Issue by UncleGoogle** [ppy/osu-web#5833]
Hey,

I'm creating plugin which follows this API: https://galaxy-integrations-python-api.readthedocs.io/en/latest/galaxy.api.html#galaxy.api.plugin.Plugin.authenticate

The Galaxy Client app can show browser windows for authentication purposes on plugin request. It returns back to plugin code redirect url (with params) and cookies.

The question is: can I embed client_secret into plugin code just to be able to exchange returning `code` to `refresh_token` on client site? Or should I create a server designed for only one thing: exchanging user's `code` to `refresh_token` and then passing it via another redirect_url to the Galaxy plugin code? (the second way means for me much more hassle and work I've never did before)

I've already seen deskop clients that uses oauth2 with client_secret beining embeded into codebase. Then of course they leak, but looks like nobody cares. For example epic launcher client_secret here:
https://github.com/FriendsOfGalaxy/galaxy-integration-epic/blob/master/src/http_client.py#L33

Is it a risk for osu, for the app or for the user? What kind of risk if the user has to explicitly authenticate there? Someone may create an app for 'bad things' (chat access?) and then publish it under the name of my app, right?

**Comment by bdach** [comment]
[Result of 5 minutes of googling.](https://tools.ietf.org/html/rfc6819#section-4.1.1)

Neglecting security because "nobody cares" is not a good approach to ever take.

**Comment by peppy** [comment]
embedding the key means that anyone can perform actions as you, leading to your account potentially being responsible should something go wrong. please do things correctly.

**Comment by UncleGoogle** [comment]
Ok, thanks for your answers.
