### ISSUE TITLE
multiplayer history endpoint missing data

### ISSUE THREAD

**Issue by Blade12629** [ppy/osu-web#5837]
I'm not quite sure what causes or what the reason for this is but as it looks like matches that have a "show more" button on their stat page have incomplete data on the history endpoint (https://osu.ppy.sh/community/matches/mpid/history).

what's missing as far as i can tell is everything that's hidden until you press "show more" at the top of the page (https://osu.ppy.sh/community/matches/mpid)

you can see this on these 2 multiplayer matches:
https://osu.ppy.sh/community/matches/58122135
https://osu.ppy.sh/community/matches/58122135/history

https://osu.ppy.sh/community/matches/59735607
https://osu.ppy.sh/community/matches/59735607/history

for reference this is a link that contains all data:
https://osu.ppy.sh/community/matches/59754965
https://osu.ppy.sh/community/matches/59754965/history

**Comment by notbakaneko** [comment]
history shows the most recent 100(?) events by default, just like the page; this is as expected.
