### ISSUE TITLE
Won't update when I get a difficulty from the download, not created.

### ISSUE THREAD

**Issue by bowlingfan** [ppy/osu-web#5839]
I was trying to update my map https://osu.ppy.sh/beatmapsets/1135779#osu/2372028, but it kept not updating Freimox vs bowlingfan's Hard, I think after the difficulty download was put into the song folder, it wont update.

https://streamable.com/uzyxc

**Comment by bowlingfan** [comment]
I dont understand why I have to use a copied version of the diff when I get that error.

**Comment by peppy** [comment]
This isn't the right repository for this, but I'm willing to investigate this if you provide enough detail. Please upload your local copy of the beatmap folder which causes this issue.

Also please delete or move that folder away, then download from scratch and confirm whether it will upload or not.

**Comment by peppy** [comment]
Going to close this due to wrong repo, but feel free to reply with further information.
