### ISSUE TITLE
Beatmap discussion events only go back 5 days

### ISSUE THREAD

**Issue by Naxesss** [ppy/osu-web#5842]
Seems this page (as an example)
https://osu.ppy.sh/beatmapsets/beatmap-discussions?page=501
shows the exact same contents as any page greater, for example
https://osu.ppy.sh/beatmapsets/beatmap-discussions?page=502

Changing filtering settings reveal that this always stops while showing "about 5 days ago".
This worked fine 10 days ago fwiw.

**Comment by peppy** [comment]
This is intentional as people were using this page in a way that was cause infrastructure performance issues. If you have a need to go further back please provide reasoning.

**Comment by Naxesss** [comment]
I'm attempting to log all beatmapset events from the beginning of 2020, and have done so respecting ratelimits for a few weeks, but took the program down 10 days ago to focus on other things temporarily. Now I'd like to fill in the gap so that the database contains complete information since 2020, continuing where I left off 10 days ago.

Collecting this information is most notably for the purpose of Beatmap Nominator evaluation, to collect mods of both aspiring modders and BNs over the past 3 months. Other reasons include statistical analysis, for example of how modding has developed in popularity over time, as a measure of success for systems the Nomination Assessment Team are trialing.

**Comment by peppy** [comment]
You were probably causing the issue then. Please contact us *before* spidering pages in the future as these pages are not meant to be accessed via such autoamtions (API endpoints would be created for that instead).

**Comment by Naxesss** [comment]
Does this mean I should wait for these API endpoints to be created before continuing? I did ask Ephemeral at the end of december last year about spidering these pages, and have in the past contacted support for advice on acceptable rate limits. I can definitely slow down the requests tenfold without much harm to what I'm doing; should be less invasive on infrastructure performance that way.

**Comment by peppy** [comment]
The whole lookup needs to be rethought if it is to be used in such a way. Web pages are made to be viewed by normal people in a normal way. Please open a separate issue stating what you need and we'll add it to the list.

**Comment by Naxesss** [comment]
I actually already have an issue open for this since 2 years ago here https://github.com/ppy/osu-web/issues/4042, which has the API tag. As you can see I've been trying to set this up for quite a while since the switch to modding discussions, without much of an opportunity to gather this information until recently when these routes were opened.

**Comment by Ephemeralis** [comment]
For what it's worth the data Naxess is spidering is pretty critical to modding activity overviews on the BN website services. It isn't some pet vanity project or whatever.

**Comment by peppy** [comment]
that means nothing if they are doing it incorrectly and taking down the servers
