### ISSUE TITLE
Add multiplayer matches title

### ISSUE THREAD

**Issue by ThePooN** [ppy/osu-web#5849]
Multiplayer matches title are nowhere to be found on the new site.

On the old website, multiplayer matches title used to be displayed at the top of the page, and in the page title.

It would be nice to also add the match title to the page `<title>`. I used to use my browser history to find some multiplayer matches, which is nearly impossible now, since I can only refer to the players & played maps.

**Comment by peppy** [comment]
seems like a definite oversight
