### ISSUE TITLE
Setting map genre and language to Any should not be possible

### ISSUE THREAD

**Issue by Darius-Wattimena** [ppy/osu-web#5850]
Currently you can add the genre and language to a mapset if you are the owner of the set or have permissions.
Although there is currently no check if you selected the Any option in the dropdown, which results you being able to set the following: 

![](https://puu.sh/FrpoG/275371dbee.png)

**Comment by dorothy3242** [comment]
would there be a way to retrieve a list of all beatmaps that currently have "any" genre set or automatically set them to unspecified other so that existing cases can be fixed? there's no way to search for them currently.

**Comment by peppy** [comment]
I'll provide a list once the fix is in.

**Comment by cl8n** [comment]
@peppy could you do the same for language now, I just caught one that had Any set https://osu.ppy.sh/beatmapsets/456463/discussion/-/events

**Comment by peppy** [comment]
All done (49 maps were in the wrong state, mostly graveyarded).
