### ISSUE TITLE
Adding "Metal" as a genre in the new genre selection list

### ISSUE THREAD

**Issue by frukoyurdakul** [ppy/osu-web#5851]
With the most recent change of the mappers being able to pick their own genres for their beatmaps, I believe the genres that can be picked should be extended as well.

I'm going to speak for osu!Taiko here, not really sure about what the main mode has currently, but taiko probably has at least 10 times more "metal" songs / maps as opposed to "rock" songs, as a genre. They might be similar but I believe they are still misrepresented.

Backing up with this new change I'm requesting that "Metal" should be added to the selectable genres on the beatmap page, solely because they exist while count is high, and more than rock at this point.

**Comment by TheDefaultGuy** [comment]
Agreed.

**Comment by frukoyurdakul** [comment]
Well I guess I can close this one by myself since there is another issue opened. https://github.com/ppy/osu-web/issues/5852
