### ISSUE TITLE
Better or no rounding for silence timer on bullet list

### ISSUE THREAD

**Issue by KatouMegumi-osu** [ppy/osu-web#5859]
![1ez](https://user-images.githubusercontent.com/30472780/78177361-75880480-7477-11ea-8c85-9ef2f0dd1dfb.png)
One place it says the silence is only one hour, and one hour is past. Silence is still active because APPARENTLY it was originally 90 minute silence, but the site rounds it as one hour, which is rather confusing,

**Comment by peppy** [comment]
Similar to https://github.com/ppy/osu-web/issues/5682#issuecomment-607478685. I think we should be customising the "time ago" display to be more accurate and more absolute for some cases.
