### ISSUE TITLE
phpunit on local container fails for every `assertViewIs('users.verify')`

### ISSUE THREAD

**Issue by taylankasap** [ppy/osu-web#5860]
There are 7 failures in total but all of them are same so here is the first one:

```
1) Tests\Controllers\BeatmapDiscussionPostsControllerTest::testPostStoreNewDiscussion
The response is not a view.

/data/osuweb/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:925
/data/osuweb/vendor/laravel/framework/src/Illuminate/Foundation/Testing/TestResponse.php:835
/data/osuweb/tests/Controllers/BeatmapDiscussionPostsControllerTest.php:59
```

The problem is, `original` property of the response is a `string` instead of `View` object and I don't know why. String's content is correct, it's the content of users.verify template.

If I use `$this->withoutExceptionHandling()` in the test, error changes to:
```
App\Exceptions\VerificationRequiredException: Please verify to proceed.
```
which is expected as far as I can tell.

Test command I use: `docker-compose exec php bin/phpunit -d memory_limit=-1 --filter=BeatmapDiscussionPostsControllerTest::testPostStoreNewDiscussion$`

I couldn't figure this out but if you direct me in the right direction I can fix and open PR.

**Comment by taylankasap** [comment]
To reproduce:
```
git clone git@github.com:ppy/osu-web.git osu-web-phpunit-test # Unique directory name so the volumes, network etc. will be fresh
cd osu-web-phpunit-test
export UID
docker-compose up # Wait until the end
docker-compose exec php bin/phpunit -d memory_limit=-1 --filter=BeatmapDiscussionPostsControllerTest::testPostStoreNewDiscussion$
```

**Comment by nanaya** [comment]
Should be fixed with the new docker.
