### ISSUE TITLE
Username to ID redirect of /api/v2/users/{username} redirects to a non-API endpoint

### ISSUE THREAD

**Issue by nekodex** [ppy/osu-web#5868]
![Screen Shot 2020-04-03 at 11 03 02 am](https://user-images.githubusercontent.com/272140/78316514-d5c39700-759a-11ea-842e-98bab119c163.png)

Not sure if we want the redirect to even happen with the API? If so, it should at least redirect to the relevant API path instead of the non-API one.

**Comment by peppy** [comment]
In APIv1 people would expect this to return the matching user. Not sure if we want to mix the two in v2, but if not we should have a separate endpoint for searching for users.

**Comment by aticie** [comment]
Any updates on this? I'm looking forward to it.

**Comment by peppy** [comment]
Let's get this fixed, seems like an oversight.
