### ISSUE TITLE
Getting 400 on oauth/token

### ISSUE THREAD

**Issue by UncleGoogle** [ppy/osu-web#5872]
Hello, after I've obtained code from redirect url params during authorization, I'm trying to exchange code to refresh_token based on docs: https://osu.ppy.sh/docs/index.html#authorize-users-for-your-application:

```python
def do_auth(code):
    params = {
        'grant_type': 'authorization_code',
        'code': code,
        'client_id': CLIENT_ID,
        'client_secret': CLIENT_SECRET,
        'redirect_uri': THIS_HOST + '/redirect_osu'
    }
    url = 'http://osu.ppy.sh/oauth/token'
    response = requests.post(url, params=params)
```

but I got this:
```
layout.errors.400.error

The authorization grant type is not supported by the authorization server.

layout.errors.400.description
```

Is there anything I'am doing wrong?

**Comment by peppy** [comment]
Did you not already resolve this via https://github.com/ppy/osu-web/issues/5832? Could you provide more detail?

**Comment by UncleGoogle** [comment]
No, the previous issue was about http://osu.ppy.sh/oauth/authorize and this is a next step, after my app is authorized by used and I want to exchange `code` to tokens via http://osu.ppy.sh/oauth/token

**Comment by UncleGoogle** [comment]
Reproduction steps:

0. create oauth client:
https://i.gyazo.com/ff136a27de15e53242dfa58fb8626fd8.png
get `client_id` and `redirect_uri` (`redirect_uri` may be imaginary for test purposes)

1. authorize this client for example:
https://osu.ppy.sh/oauth/authorize?response_type=code&client_id=929&redirect_uri=https://galaxy-osu/auth&scope=identify

changing `client_id` and `redirect_uri` of course.

2. copy `code` from url where we land after authentication

3. exchange `code` manually using `client_secret` from step 0:
![5e46fc19e73913750e8afdb6a69b19f9](https://user-images.githubusercontent.com/12197825/78499036-87ef9000-774e-11ea-9a74-3d835925203b.png)

Result:
Html with error description:
```
layout.errors.400.error

The authorization grant type is not supported by the authorization server.

layout.errors.400.description
```

**Comment by notbakaneko** [comment]
send the parameters in the body of the request, not as query parameters of the url

**Comment by UncleGoogle** [comment]
Oh, thanks, passing json in body works.

Why body, not params like http://osu.ppy.sh/oauth/authorize, nor headers, like many oauth examples?

**Comment by peppy** [comment]
@UncleGoogle you could handle that second redirect pattern from your end. That should be your responsibility.
