### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by SpartanPlume** [ppy/osu-web#5881]
## Problem

When I try to use the search button, the popup to write the text in appears, I write any number of character in it and then the popup disappears and the search button too.

This problem appears both in Firefox and Chromium.

I used the search button within the last week (not sure when exactly but I think it was on Sunday), and it was still working fine.

## How to reproduce

- Click the search button from any page (while logged in)
- Type any number of character

**Comment by SpartanPlume** [comment]
After some more testing, it still works sometimes, but even when it works, if I type some more characters, it can still disappear (along with the search button). So maybe the assumption that it was still working on Sunday is false.

**Comment by peppy** [comment]
This was intentional. I had to turn it off due to load, while we investigated.
