### ISSUE TITLE
Mapper Isn't Automatically on Watch Mode for Their Own Beatmap Discussions / Comments

### ISSUE THREAD

**Issue by VINXIS** [ppy/osu-web#5891]
I believe this may be a bug since this issue exists https://github.com/ppy/osu-web/issues/2190, but currently I and other mappers have to press watch on both comments and the beatmap discussion, would be nice if it was automatically done so we don't have to do it every time we submit a map

**Comment by inix1257** [comment]
![image](https://user-images.githubusercontent.com/39195410/78845497-a0f48b80-7a43-11ea-9fb8-bf52757f0b5a.png)
there is already an option for this but seems like it's not working at all

**Comment by peppy** [comment]
There's a setting in osu! during beatmap submission "notify on reply". Have you made sure you have it checked?

**Comment by VINXIS** [comment]
I didn't check / notice when i uploaded my latest beatmap, but I thought that was automatically enabled since forever

**Comment by peppy** [comment]
It's enabled by default, but if you change it it will remember your setting.

**Comment by VINXIS** [comment]
uploaded a new beatmap and apparently it was not ticked, after ticking it did automatically put me on watch for beatmap discussions but not for comments

**Comment by peppy** [comment]
Right, comments are a completely separate thing. @nanaya what's the procedure for me to add a comments watch?

**Comment by nanaya** [comment]
Probably need to make an endpoint to properly propagate it to notification websocket (also for the discussion watch).

In the meantime
```sql
INSERT INTO follows (user_id, notifiable_type, notifiable_id, subtype, created_at, updated_at)
VALUES (?, 'beatmapset', ?, 'comment', now(), now());
```

**Comment by peppy** [comment]
I guess those would only be required for currently open websocket sessions? Probably relatively low priority if so.

**Comment by peppy** [comment]
Comment subscription has been added. It should take effect from the next time you submit any beatmap with that checkbox checked in BSS.
