### ISSUE TITLE
User's avatars are being randomly deleted

### ISSUE THREAD

**Issue by willyosu** [ppy/osu-web#5892]
Avatars of random users are being removed for seemingly no reason. It's happened to me 3 times in the past two weeks, my avatars just keep getting deleted. ([profile](https://osu.ppy.sh/users/3521482))
![image](https://user-images.githubusercontent.com/11691902/78868684-5528ee80-7a11-11ea-8980-9873beae938d.png)
It's not an infraction on my account like I first thought, it's just something on server side that keeps removing people's avatars. Here's some other users from Twitter who have apparently had the same experience:
![image](https://user-images.githubusercontent.com/11691902/78868905-b05ae100-7a11-11ea-8e21-ad0b33a66946.png)
Don't know any other UIDs of who it's happened to but if you need a larger sample I can ask around.

**Comment by peppy** [comment]
They are not being "deleted" but just badly cached. I'm looking into the issue but don't have any leads yet. For instance, check again and your avatar will now be back (I cleared server-side cache).

**Comment by peppy** [comment]
I've applied some further fixes (I hope) for this. Will leave this issue open for now because I'm not confident it's 100% fixed. Please report back if you have it happen again.

**Comment by willyosu** [comment]
It seems like it's fine now on the new website but anything grabbing the avatar via api (a.ppy.sh) like the game is still not displaying.

[Website:](https://osu.ppy.sh/users/3521482)
![image](https://user-images.githubusercontent.com/11691902/79403511-1dfc9500-7f5d-11ea-865b-138153f06f5a.png)

In-game:
![image](https://user-images.githubusercontent.com/11691902/79403312-8bf48c80-7f5c-11ea-9612-31ecca85578e.png)

[Third party using API (osuskills.com):](http://osuskills.com/user/Willy)
![image](https://user-images.githubusercontent.com/11691902/79403477-058c7a80-7f5d-11ea-9707-a10a107c3923.png)

**Comment by peppy** [comment]
It's probably being cached in those usages.

**Comment by peppy** [comment]
I'm going to close this for now. Please comment if you encounter the same issue.

**Comment by willyosu** [comment]
It stopped happening for a while but just happened to me again today.

**Comment by peppy** [comment]
I still see your avatar. Could you confirm in a porn mode browser that it's actually missing and not a once-off retrieval failure?

**Comment by willyosu** [comment]
Nevermind, you're right it's back now.
