### ISSUE TITLE
Decommissioning the osu! iPhone subforum entirely

### ISSUE THREAD

**Issue by Flanster** [ppy/osu-web#5893]
As with osu!droid's subforum (https://github.com/ppy/osu-web/issues/4311) the iPhone subforum aswell seems to be a lingering ghost where people sometimes post their stable client issues in its Bug Reports section instead of the Help subforum as it seems to confuse people. Project is long dead so I don't think theres any support to be provided there?

**Comment by peppy** [comment]
Has been decommissioned.

**Comment by E223** [comment]
Users still seem to be able to view and post in https://osu.ppy.sh/community/forums/50, which is a subforum of the iPhone subforum. 

Ex: https://osu.ppy.sh/community/forums/topics/998504

**Comment by Flanster** [comment]
People are still posting there, either rename this subforum to something not confusing or waste it please.
