### ISSUE TITLE
Playcount should be replaced with Hype on Pending map's info pages

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#5894]
On beatmap cards for wip+pending maps, the hype count can be found where playcount would be on ranked maps.
![image](https://user-images.githubusercontent.com/33286824/78950319-6539e000-7a9c-11ea-9915-017a02f35e3e.png)

But on the info page, playcount is displayed and not hype, despite playcount being an irrelevant metric on wip+pending maps, as the majority of the time their playcount would be 0.
![image](https://user-images.githubusercontent.com/33286824/78950376-94505180-7a9c-11ea-8976-9edc4e97e254.png)

The only case where wip+pending maps would have plays is if they are disqualified or unloved, but this shouldn't be relevant as that playcount would be reset regardless if those maps were to get leaderboards again.

**Comment by peppy** [comment]
I think this should be okay? @arflyte are you okay with that area being contextual?

**Comment by arflyte** [comment]
yeah, sounds good. i'll keep this in mind for the new cards.

**Comment by dorothy3242** [comment]
The original issue is a bit outdated since playcount exists now, and it looks like the beatmap cards got updated to account for maps having playcount now
maybe the information could be displayed in the order of

playcount-favorites-hype-nominations

this would be similar to the order on the cards and keep the placement of information consistent no matter which category the map is in.

**Comment by cl8n** [comment]
hype is already shown in the hype train below the map info, and those stats are ordered with favs last since the hover thing goes out to the right

**Comment by dorothy3242** [comment]
ok :)
