### ISSUE TITLE
Label 18+ content with a “explicit” mark

### ISSUE THREAD

**Issue by 3mplify** [ppy/osu-web#5902]
Add the ability to identify "18+" content (more likely "13+" since we don't allow 18+ on osu! in the first place)

**Comment by Kashouryo** [comment]
I partially agree with this idea. However, allowing explicit content to show in some countries (e.g. China) can cause a firewall ban. To prevent such disaster from happening, we might also have a forced, IP based explicit content filter.

**Comment by Snowmander** [comment]
I disagree with a forced IP filter. Caving in to a government’s censorship policy sets terrible precedent for other nations to influence and censor a website’s content at will.

Reddit hosts adult content and is not banned anywhere except China (afaik).

**Comment by peppy** [comment]
I'm removing the attached document link because that's not how github works. Please fill out the issues description. Also please end discussion about censorship etc. – this would be a labeling / warning feature only if implemented.

**Comment by cl8n** [comment]
this would be really helpful for retroactively moderating ranked/loved maps without nuking their leaderboards-- today there is drama about https://osu.ppy.sh/beatmapsets/418412 being unloved after years due to nsfw lyrics, you can see everyone being disappointed in map comments and on twitter and reddit. whoever decided to remove this also just Streisand effect -ed this back into the spotlight when the intention was to not promote it via the loved category anymore.

**Comment by Ephemeralis** [comment]
Agree fully with clayton here. Some sort of flag to prevent searching and display a warning on the webpage but allow the beatmap to remain intact is the best way of handling old "precedent" cases where things have slipped through the cracks without destroying history and work that might've developed around these sets.

I don't see this warning being used often in a modern sense (unless the song content rules are changed) but it would be very useful for things like Border of Extacy and the bunch of 2009-2011 era maps that had... questionable song choices.

**Comment by lolxdhi1** [comment]
I agree with this as well.
It would be useful to have these warnings on maps that have disturbing themes as well as nsfw maps (like ztrout's visit to the proctologist for example)

**Comment by alolanraichulive** [comment]
we will remove beatmaps that are 18+ because it violates our community guidelines, then we will make a 18+ beatmap not available for download.
