### ISSUE TITLE
Notification grouping for medal is not quite right

### ISSUE THREAD

**Issue by nanaya** [ppy/osu-web#5905]
- it probably shouldn't be grouped (it wasn't grouped before the refactor iirc)
- if we're keeping it grouped, it will need some fixing:
  - better group title and icon
  - add missing group url
  - fix small medal icon

![](https://s.myconan.net/2020-04/firefox_2020-04-13_13-34-25.png)

**Comment by peppy** [comment]
I think non-grouped is best for medals, since they are kinda important?

**Comment by notbakaneko** [comment]
Ungrouping turns out to be quite a bit more complicated than initially thought; achievement notifications are queried under one group and unrolling them manually or separately starts leading to the confusing pagination from before.
