### ISSUE TITLE
Certain beatmap pack medals don't work when doing them in mania

### ISSUE THREAD

**Issue by GrilledCheeese** [ppy/osu-web#5908]
My current medals on my **mania** profile:
![image](https://user-images.githubusercontent.com/34809632/79130892-fa441e00-7da7-11ea-862e-5e682531d4f1.png)
I barely play osu standard or any other gamemodes, which is why I assume all of the medals I have currently are done with mania scores. I already completed all maps of Mappers' Guild Pack IV in **mania** , so I thought I could just redo one map to unlock it just like I did with the new winter spotlight medal:
![image](https://user-images.githubusercontent.com/34809632/79131135-5f980f00-7da8-11ea-8b41-24ac90f99095.png)
But then it turns out that none of the circles light up when redoing them in mania, but one of them did when I played it in osu standard:
![image](https://user-images.githubusercontent.com/34809632/79131201-835b5500-7da8-11ea-947f-904906f0adc3.png)
![image](https://user-images.githubusercontent.com/34809632/79131301-ad147c00-7da8-11ea-897a-ac5a2da4ead7.png)
Me submitting mania scores for maps in the Mappers' Guild Pack IV:
![image](https://user-images.githubusercontent.com/34809632/79131556-15635d80-7da9-11ea-8fbc-d2cf7158f94c.png)
If you need me to check any other medals just let me know

**Comment by peppy** [comment]
You need to pass pack medals in the original game mode now. Converts no longer work.

**Comment by GrilledCheeese** [comment]
Will the standard only medal packs be removed from the other gamemode user profiles to only show them on the osu standard page? To prevent future confusion

**Comment by peppy** [comment]
Possibly.
