### ISSUE TITLE
Replay download links from off-site no longer work

### ISSUE THREAD

**Issue by tybug** [ppy/osu-web#5913]
Clicking a replay download link (eg https://osu.ppy.sh/scores/osu/2797309065/download) from anywhere that isn't the osu! site will redirect you to the beatmap page but not download it. 

I'm guessing this was caused by #5906 - just noticed it this morning.

**Comment by peppy** [comment]
This is intentional, yes. Could you explain which site is doing this and why it needs to? We are dropping support for this due to people batch downloading where it was not the intention.

**Comment by tybug** [comment]
Replays are linked pretty often over at https://reddit.com/r/osureport/. When I (for instance) see discussion on a player I'd like to weigh in on, the first thing I do is download the replay in question so I can open it in a separate application made specifically for viewing replays, which allows for more detail and ease of viewing than ingame.

If the replay is in the user's top 100 plays,  I can go to their userpage and download it. But It could be in position 76, requiring me to click "show more" twice on their userpage, locating the play in question, and clicking a hamburger menu to actually get the download link. More time consuming than clicking a link.

The replay might also very well be outside of the user's top 100 replays (and the top 50 of the beatmap), meaning I simply can't download it at all without the link. I could get the replay data from the api and reconstruct the .osr given the username, time of play, etc but that seems like an over-constructed (and overly programmatic) solution to what should be a simple issue.

**Comment by peppy** [comment]
For replays we do have a new score display page coming which will address this.
