### ISSUE TITLE
Svalbard and Jan Mayen Country Rankings cannot be accessed

### ISSUE THREAD

**Issue by Dawnsday** [ppy/osu-web#5914]
trying to access the Svalbard and Jan Mayen country rankings doesnt work and just showcases the top 50 globally (Maybe an issue with a tiny userbase? Could be worth just merging this with it's actual country)

https://osu.ppy.sh/rankings/osu/performance?country=SJ

https://osu.ppy.sh/users/2735631 can try to access it from this users country

**Comment by venix12** [comment]
https://github.com/ppy/osu-web/issues/5542#issuecomment-578413248 could apply here i guess

**Comment by Dawnsday** [comment]
Ah makes sense, figured it was something to do with a tiny userbase but couldn't find another country to test with. Makes sense.
