### ISSUE TITLE
Secondary sorting along side "Relevance" in beatmap listing

### ISSUE THREAD

**Issue by xenallio** [ppy/osu-web#5930]
Instead of the fixed favorite count usage from https://github.com/ppy/osu-web/issues/5681 allow a secondary parameter, or make relevance always on if there is something in the search bar and just use whatever is selected in the "sort by".

This would offer more flexibility, such as seeking for the most recently updated or highest difficulty from a popular song in graveyard.

**Comment by peppy** [comment]
you can already choose a sort.

the weighting of favourites is just one component of relevance.
