### ISSUE TITLE
Moderation commands sent from the web chat have no effect

### ISSUE THREAD

**Issue by TicClick** [ppy/osu-web#5932]
I've tried making Banchobot respond to `!faq lines` in a public channel, to no avail -- the contents were sent to me privately instead, as if I was a regular user. I suspect it's the same for other commands.

**Comment by peppy** [comment]
Will be fixed in next bancho restart.

**Comment by TicClick** [comment]
I'd like to reopen it, because Bancho still sends you the output of `!faq` commands privately. The following are screenshots of osu! chat and my IRC client that prove this:
- https://tc.s-ul.eu/dhrwGCRX.png
- https://tc.s-ul.eu/Xzn6PBCN.png

Note that silence commands do not show up and work as intented.

**Comment by TicClick** [comment]
@peppy I don't know if it's intended, but it's back to square one:
- `!faq <topic>` sent from the web chat does nothing, I don't even receive a private message from the bot anymore;
- the silence command sent from the web chat has no effect and is visible to everyone (I've asked Noffy to confirm), which is a regression.
