### ISSUE TITLE
category for ranked featured artist maps

### ISSUE THREAD

**Issue by genericthing** [ppy/osu-web#5938]
the idea here is that ranked featured artist maps should be put into their own category to make such maps easier to find, featured artist maps that have the featured artist not revealed yet will stay in ranked until the featured artist is announced

if a featured artist is announced, all mapsets that are licensed and relevant to the featured artist (including mapsets from before the featured artist) will be moved to the category

**Comment by dorothy3242** [comment]
Duplicate of https://github.com/ppy/osu-web/issues/3777

**Comment by genericthing** [comment]
will close this then
