### ISSUE TITLE
Grant type refresh_token

### ISSUE THREAD

**Issue by UncleGoogle** [ppy/osu-web#5939]
> Only the Authorization Code Grant type is currently supported for public use.

https://osu.ppy.sh/docs/index.html#authentication

Any ETA for providing refresh_token grant type? Access token is only 24h

**Comment by aspriddell** [comment]
It already exists. Pass `refresh_token` as the grant type and the token under `refresh_token`

**Comment by peppy** [comment]
It's even mentioned in documentation.

**Comment by UncleGoogle** [comment]
@aspriddell thanks, but to which endpoint?

I've got 400 from with POST to https://osu.ppy.sh/oauth/token having in body:
```json
{
	"refresh_token": "***",
	"grant_type": "refresh_token"
}
```

and application/json Content-Type header

> It's even mentioned in documentation.

@peppy where?

**Comment by aspriddell** [comment]
It should be `application/x-www-form-urlencoded`, not `application/json` but the same endpoint (if I remember correctly)

**Comment by UncleGoogle** [comment]
Still 400
https://i.gyazo.com/cfc362635adbd48e2747e4cf9e1501d6.png

**Comment by UncleGoogle** [comment]
Ok, I've got this adding `client_secret` and `client_id`. Thanks for help!

Docs should be updated. There is text:
```
grant_type | string | This must always be authorization_code
```
