### ISSUE TITLE
Stop autoplaying the next song on literally everything

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#5940]
I wanted to see what a map was on the BSS and a completely unrelated song that I had no interest in was shoved into my ears once it finished.
It is good for newsposts, but please don't use it on the beatmap listing.

**Comment by peppy** [comment]
maybe as a setting. personally i like the way it works right now.

**Comment by cl8n** [comment]
other pages have multiple unrelated areas where audio can be played and it doesn't make sense to autoplay through it all

- audio in a forum post autoplays into audio in a later post
- audio on userpages autoplays into favorite beatmaps
- multiple audio within a forum post may be unrelated too, depends how poster used it

all of these are related to user content, but I think it would be just as confusing if two 'official' tracks in unrelated spots of a page autoplayed into each other (not sure if that case exists on the site rn)

**Comment by penguin2233** [comment]
audio also plays if the beatmap is offscreen, was trying on my userpage and the audio player kept playing something I could not see

**Comment by peppy** [comment]
Should definitely be limited to sections for pages like user profile.
