### ISSUE TITLE
usernames with multiple consecutive spaces get compressed

### ISSUE THREAD

**Issue by InvisibleSymbol** [ppy/osu-web#5942]
some examples: 
- https://osu.ppy.sh/users/723190 `-     -` shows up as `- -`
- https://osu.ppy.sh/users/1537821 `Bad   Apple` shows up as `Bad Apple`
- https://osu.ppy.sh/users/325462 `Bad  apple` shows up as `Bad apple`

Now these names can't be created anymore, but since they still exist I think they should be fixed.
Especially confusing when searching for "Bad Apple"
![](https://i.fiery.me/KxBmm.png)

**Comment by peppy** [comment]
should be a simple fix, i'd hope

**Comment by nanaya** [comment]
In html, multiple spaces are usually collapsed into one so one of the way to fix this will involve finding where usernames are rendered and escaping them there.

**Comment by peppy** [comment]
The alternative would be to nuke these users, if they are inactive.

**Comment by lmnyx** [comment]
Simplest fix is to add `white-space: pre;` I guess
![fix preview](https://user-images.githubusercontent.com/13962537/82520654-25a3f080-9b3e-11ea-9a90-985c2edcc08f.png)
