### ISSUE TITLE
Report Score on Recent Plays (24h) doesn't work

### ISSUE THREAD

**Issue by GrilledCheeese** [ppy/osu-web#5951]
![image](https://user-images.githubusercontent.com/34809632/80255351-04ee9500-867d-11ea-953c-9dbe1d83e06e.png)
It works on Best Performances and First Place Ranks, but not on Recent Plays (24h)

**Comment by nanaya** [comment]
@peppy should people be able to report those scores considering the scores only last for around a day?

**Comment by peppy** [comment]
They have a high score ID linked in the case they are available for longer, right? Maybe just those cases for now..
