### ISSUE TITLE
No note when replying to user blocking messages from non-friends

### ISSUE THREAD

**Issue by E223** [ppy/osu-web#5954]
If a user is blocking messages from people not on their friends list (or has you blocked?) and messages you first, the note that normally appears under their name explaining why you can't message them does not appear. So when you go to reply, all of your messages fail/403 with no explanation and you are left wondering why that is the case. For example:
![](https://i.imgur.com/ykox04y.png)  

Typically you would see something like this:
![](https://i.imgur.com/uwDFOY4.png)

**Comment by peppy** [comment]
It's quite common for players to have this setting on, so at least we should provide a decent error message on send (but hopefully the info page as shown above).
