### ISSUE TITLE
Request: Being able to add tags after ranked status

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#5959]
Mappers change their username too! Could we make it possible to allow BN/NAT(?) add the new username in the tags by the mapper's request? So that if I type in the name "R**a**ytoly" I would also be able to find his older maps when he still had the name "R**h**ytoly". 

With this it also needs to show the new name in the listing otherwise we won't find all maps at once.
Rhytoly: https://osu.ppy.sh/beatmapsets?q=rhytoly
Raytoly: https://osu.ppy.sh/beatmapsets?q=raytoly

**Comment by venix12** [comment]
Changing website tags is possible for certain usergroups on the old website, I believe it will eventually be a thing on the new one, but that's relatively low priority I guess.

**Comment by peppy** [comment]
Usernames should not be in tags in the first place. This will be addresses eventually by a collab system.
