### ISSUE TITLE
Song and Artist name in original language in the beatmap info page

### ISSUE THREAD

**Issue by huupoke12** [ppy/osu-web#5967]
I think it is necessary to show the original language metadata in the beatmap info page. This seems to be related to https://github.com/ppy/osu-web/issues/3217 but I think the beatmap info page should always provide original info and sources.

**Comment by peppy** [comment]
We do really need this, along with a setting to toggle it like in-game.

**Comment by Joehuu** [comment]
> I think the beatmap info page should always provide original info and sources.

> setting to toggle it like in-game

A toggle counteracts the “always provide original info and sources”, so this is a duplicate of https://github.com/ppy/osu-web/issues/3217.

**Comment by peppy** [comment]
Closing as duplicate of #3127.
