### ISSUE TITLE
Mod badge inconsistencies

### ISSUE THREAD

**Issue by oamaok** [ppy/osu-web#597]
Easy and NoFail: The drop shadow is lighter and more blurred compared to the rest.
1K: One pixel shorter in height than the others.

Only checked the 2x versions.

**Comment by arflyte** [comment]
Will look into it.

**Comment by nekodex** [comment]
@arflyte is this issue still relevant?

**Comment by arflyte** [comment]
it will be fixed when everything is re-exported.

**Comment by peppy** [comment]
These have since been re-exported and redesigned multiple times, and thus should be resolved.
