### ISSUE TITLE
Bot group accounts should not release usernames ever

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#5970]
These accounts are not marked as "active" due to the user not logging in. Therefore there should be an exception disallowing username release. Should probably be an env variable with group ids similar to other checks (we'd probably include team groups in here too).

**Comment by notbakaneko** [comment]
Anything currently with a `group_id != 2` is not available.

**Comment by nanaya** [comment]
It only checks default group though. Probably should be extended to check the full group ids. Although then the question is should it be a whitelist (only user in base group ("registered") and doesn't belong to other groups) or a blacklist (belongs in specific groups)

**Comment by peppy** [comment]
whitelist may actually be easier to manage

**Comment by notbakaneko** [comment]
For some reason `User::isBot` only uses the default group_id 🤔 
`return $this->group_id === app('groups')->byIdentifier('bot')->getKey();`

**Comment by nanaya** [comment]
Yeah that's because there are some bots that's not really bot (normal user with "bot" running using same user id).
