### ISSUE TITLE
Multiple scores on a map with the same mod combination [apiv1]

### ISSUE THREAD

**Issue by doughn0** [ppy/osu-web#5977]
In rare occasions a player might have 2 or more scores on a beatmap with a given mod combination according to the api. These are usually both the same score, but the score_id is shifted by one, but they might be completely different scores as well. If the user sets a new highscore everything returns to normal.

Example calls:
[https://osu.ppy.sh/api/get_scores?b=753769&u=9074986&m=3&mods=64](https://osu.ppy.sh/api/get_scores?b=753769&u=9074986&m=3&mods=64)
Completely different scores. Response in resp2.json in case the user sets a score.

[https://osu.ppy.sh/api/get_scores?b=262377&u=6659363&m=3](https://osu.ppy.sh/api/get_scores?b=262377&u=6659363&m=3)
Same score, score_id shifted by one. Response in resp1.json.

[resp.zip](https://github.com/ppy/osu-web/files/4561651/resp.zip)

**Comment by peppy** [comment]
This should now be fixed. Thanks for pointing it out.
