### ISSUE TITLE
Show deleted forum posts in user's post history

### ISSUE THREAD

**Issue by E223** [ppy/osu-web#5978]
GMT/NAT should be able to see deleted forum posts in a user's post history as it is useful for moderation. 

Perhaps they should also be shown on the [search page](https://osu.ppy.sh/home/search?mode=forum_post) (similar to how it's done for modding posts), though I don't how many moderators would actually need that.

This is also similar to #4982, but I'm not sure how similar the fixes are.

**Comment by abraker95** [comment]
I think it's best to limit this to posts deleted by GMT/NAT instead of users themselves.

**Comment by E223** [comment]
> I think it's best to limit this to posts deleted by GMT/NAT instead of users themselves.
It ultimately shouldn't end up making a difference.

**Comment by abraker95** [comment]
Can this be bumped up in priority? It's hard to gather material about users when the offending content is unsearchable. This would also apply to posts in the abandoned wasteland - At the very least make posts created in the last 6 months searchable if there is a reason against making the subforum searchable.
