### ISSUE TITLE
Scrolling bars for tags list on website

### ISSUE THREAD

**Issue by Pachiru** [ppy/osu-web#5983]
Adding a scrolling bar on the website when the tags length are so high that they appear off-screen like this
Here is a screenshot of the issue https://i.imgur.com/3L8viYq.png

**Comment by peppy** [comment]
@arflyte want to advise about this (cases where tags overflow the provided area)

**Comment by arflyte** [comment]
didn't imagine that the tags would overflow. i assume this is not a common case? We can add a small scrollbar to the entire column for now.

I'll update the new design to handle huge tag list.

**Comment by peppy** [comment]
It looks like they are being arbitrarily truncated right now. But probably not in a way that works correctly with the contained design. Can we change this to return more tags and truncate at a css level or something as a temporary solution?

**Comment by arflyte** [comment]
yeah, we can. currently, it's not fully utilising the space I think. and if it still overflows, we can add a small scrollbar to the tag column.

**Comment by Joehuu** [comment]
Resolved in https://github.com/ppy/osu-web/pull/10030.
