### ISSUE TITLE
indented markdown tables aren't being parsed correctly

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#5985]
at least I think it's the indentation here. see table in https://osu.ppy.sh/help/wiki/Tournaments/TWC/2020#stage-instructions , the headers are there but the content is shifted to the right. it probably thinks the spaces at the beginning are table cells

**Comment by gagahpangeran** [comment]
Maybe this issue because osu-web is using league/commonmark version 1.1.2, it looks correct with version 1.3.0 [here](https://johnmacfarlane.net/babelmark2/?text=%60%60+%60+%60%60). I'm not sure about that.
