### ISSUE TITLE
i.ppy.sh serving 404 "Request loop failure" for some users

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#5990]
there's a lot of people in #osu-wiki just now that said they can't view <https://i.ppy.sh/6a8df3762c81b9afc6377c26c723774d1bd8f1c8/68747470733a2f2f6f73752e7070792e73682f68656c702f77696b692f7368617265642f646966662f686172642d6d2e706e67> , which is the cached resource for <https://osu.ppy.sh/help/wiki/shared/diff/hard-m.png>

you can see it used on <https://osu.ppy.sh/help/wiki/Ranking_Criteria/osu!mania>

I'm not having any problems viewing this image, but I've seen similar 404s previously. they solve themselves after some time but this is probably worth looking into, we've had 3 different images reported for this at osu-wiki

**Comment by peppy** [comment]
The error mentioned is a camo error, but checking the source I can't imagine how it would have happened. Generally occurs when there's a loop (the image requested is at `i.ppy.sh`).

**Comment by alolanraichulive** [comment]
change the title to "i.ppy.sh serving 404 "not found" for some users".

**Comment by Joehuu** [comment]
Closing this for now until it happens again.
