### ISSUE TITLE
Duplicate condition in nomination button showing logic

### ISSUE THREAD

**Issue by mcendu** [ppy/osu-web#5996]
https://github.com/ppy/osu-web/blob/b0d30ea0149504977277c1cfce6be300ec1ad396/resources/assets/coffee/react/beatmap-discussions/nominations.coffee#L410

Note that `mapCanBeNominated` showed up twice, with the latter one preventing BNs from nominating a qualified map which is allowed by the former.

**Comment by nanaya** [comment]
There's another one for disqualifyButton. I must've missed them when cleaning up the render logic.
