### ISSUE TITLE
Add more filters to beatmap search

### ISSUE THREAD

**Issue by lmnyx** [ppy/osu-web#5998]
Add to beatmap search form more filters such as:
* OD, CS, AR, HP
* BPM
* Length
* Streams, jumps? (very useful btw)
And also maybe give an option to choose star rating, because recommended diff isn't right in most cases.

**Comment by Nivalyx** [comment]
iirc there's already http://osusearch.com/ in which you are able to search for a beatmap with specific OD/CS/AR/HP/BPM/Length/Star Rating range 

i'm not really sure how could a map be algorithmically filtered by "streams" and "jumps" tho in the other hand, from what i've seen people who were categorizing maps into different categories based on their playing niches (for example mappoolers) are doing so manually by playing them one by one and sorting them into different Collections in-game or by any other means :(

**Comment by lmnyx** [comment]
Yeah, I know about osusearch, but their website kind of have bugs (when AR is displayed as 0 for example). 
I don't really know either how to recognize streams or jumps, but maybe somehow on spacing between hitcircles or premade patterns?

**Comment by peppy** [comment]
Would be nice to see the easy pieces of this added, in a similar fashion to what is available in stable/lazer

Reference:
https://github.com/ppy/osu/blob/428065ff43ee0ee73304eeeaa04238476c051184/osu.Game/Screens/Select/FilterQueryParser.cs#L37-L76

**Comment by CS7BCantrell** [comment]
@Nivalyx I tried to go to http://osusearch.com/ and it said that it was no longer supported is there no longer a way to search by AR/OD/CS/HP/BPM/Length/Star Rating?

**Comment by cl8n** [comment]
they don't support direct downloads anymore but you can still use it to search

**Comment by peppy** [comment]
Probably should look to get this in, even if it's just the text version mentioned in https://github.com/ppy/osu-web/issues/5998#issuecomment-636759009. Star rating is an important one if that serves as a pointer for where to start with implementation.

**Comment by Fvern** [comment]
probably known but keys= _needs_ to be a filter as 4/7k mania are practically different gamemodes from a player's perspective.
