### ISSUE TITLE
php7.2 mcrypt is deprecated

### ISSUE THREAD

**Issue by lmnyx** [ppy/osu-web#6012]
mcrypt in php 7.2 was discontinued and there is no install candidates for php7.2-mcrypt.
As well setup quick-guide says PHP 7.2 and extensions for him needed but php's Dockerfile still uses php7-*.

**Comment by notbakaneko** [comment]
alpine `php7-mcrypt` is an alias of `php7-pecl-mcrypt` and installs the pecl extension
