### ISSUE TITLE
Floating navigation in user profile and beatmap discussion page can use better design

### ISSUE THREAD

**Issue by lmnyx** [ppy/osu-web#6018]
![image](https://user-images.githubusercontent.com/13962537/82125191-ce102880-97bd-11ea-9dd8-82c66a805ef4.png)

**Comment by nanaya** [comment]
Can use more detail on what exactly is being reported here.

**Comment by lmnyx** [comment]
I'm saying about that div block which uses 100% of page width and looks awful.

**Comment by nanaya** [comment]
But that's the design and I don't think you're supposed to view the page with screen that wide (under normal zoom). @arflyte

**Comment by lmnyx** [comment]
Yeah, but even with normal zoom or on wide screen it's looks kinda ugly. It can be same size as others but when you scroll and it sticks to the top make it shrink (?)

**Comment by peppy** [comment]
does indeed look a bit silly @arflyte

**Comment by arflyte** [comment]
yeap. that does look silly. i'll look into it.

**Comment by arflyte** [comment]
https://www.figma.com/file/ORt8Z970eMqEdgHCXarYXS/Profile-Navigation?node-id=0%3A1

Navigation box appears like one of the cards but with B4 bg instead of B5. H1 line on top of the navigation box. Behaves the same way when scrolling; it sticks to the top.
