### ISSUE TITLE
Allow users to customise display title

### ISSUE THREAD

**Issue by Xinnoh** [ppy/osu-web#6023]
Since we are giving control to users over their beatmap metadata, I think it would be a good idea to allow control over the display title. It's currently a feature only gmt/qah members can use on the old site, it sets the colour of the title and when it appears when playing a map. By default, it appears at the start of the map and the text is white.

It used to be pretty popular to customise, but stopped being a thing because you had to go out of your way to contact a qat/gmt in order to set it.

Where it is set
![Screen Shot 2020-05-18 at 1 01 45 AM](https://user-images.githubusercontent.com/30382015/82188791-43a1f480-98a3-11ea-8b5f-11c34471a64f.png)

What it looks like when set to blue + a later offset (the text with (TV Size) in it)
![screenshot015](https://user-images.githubusercontent.com/30382015/82189155-cb87fe80-98a3-11ea-82b8-f0173b6f214f.jpg)

**Comment by peppy** [comment]
If anything, I believe this will be deprecated (potentially not displayed in lazer). This should be done via storyboards these days.
