### ISSUE TITLE
Non-ASCII characters in difficulties' names

### ISSUE THREAD

**Issue by TamamoNoMae13** [ppy/osu-web#6024]
Mentioned before in https://github.com/ppy/osu-stable-issues/issues/445

But I've also found in these maps:
[/s/1](https://osu.ppy.sh/beatmapsets/1)
[/s/93](https://osu.ppy.sh/beatmapsets/93)
[/s/106](https://osu.ppy.sh/beatmapsets/106)
The 3 above are maps that got their name edited on the web, but not the *.osu inside the packages.

[/s/63240](https://osu.ppy.sh/beatmapsets/63240)
[/b/725139](https://osu.ppy.sh/beatmapsets/326608#osu/725139)
[/b/996177](https://osu.ppy.sh/beatmapsets/465330#taiko/996177)
[/b/1360912](https://osu.ppy.sh/beatmapsets/641854#osu/1360912)
[/b/2223893](https://osu.ppy.sh/beatmapsets/857638#osu/2223893)
2 difficulties in [/s/928561](https://osu.ppy.sh/beatmapsets/928561)
[/b/2020385](https://osu.ppy.sh/beatmapsets/965125#osu/2020385) (mentioned in [osu-stable-issues#445](https://github.com/ppy/osu-stable-issues/issues/445))
[/s/1236902](https://osu.ppy.sh/beatmapsets/1236902#osu/2573886)
Those are maps with special characters like `‡`, `†`, ...

And also plenty of diffs using Left/Right Single Quotation Mark (`‘` and `’`) or Acute accent `´`, etc instead of Apostrophe `'` for something like "Someone's Insane";
Or Left/Right Double Quotation Mark (`“` and `”`) instead of Quotation Mark `"`

List:
[/b/350283](https://osu.ppy.sh/beatmapsets/140189#mania/350283)
[/b/433737](https://osu.ppy.sh/beatmapsets/180175#mania/433737)
[/b/1100690](https://osu.ppy.sh/beatmapsets/374328#taiko/1100690)
6 out of 8 diffs in [/s/524546](https://osu.ppy.sh/beatmapsets/524546)
[/b/1296825](https://osu.ppy.sh/beatmapsets/614764#fruits/1296825)
This diff's name also uses Horizontal Ellipsis `…` instead of 3 normal period/full stop/dot `...` 
[/b/1513093](https://osu.ppy.sh/beatmapsets/673290#osu/1513093)
[/b/1630856](https://osu.ppy.sh/beatmapsets/776165#taiko/1630856)
[/b/1770695](https://osu.ppy.sh/beatmapsets/846636#osu/1770695)

There are also some BG/SB pictures, and *.osb as well, but those won't affect osu! processing the beatmaps, just that some BG or SB sprites may not show up. (They're mostly from mapsets with 4digits ID or older)

If you downloaded them long ago, it preserved the character, and osu! processes normally.
But atm, idk why, when downloading those beatmaps, when opening the *.osz with WinRAR/7-zip/Ark/... those characters become something like "ü". It isn't the archiving programs bug, because even if I didn't open them with those, when I dropped the *.osz in, the game give me error notifications for those diffs.

**Comment by TamamoNoMae13** [comment]
Plus, if anyone having these beatmaps before, when non-ASCII didn't get auto-convert and work normally.
Atm, if one accidentally select these (either via choosing or F2-ing), the whole beatmaps database got reprocessed.

**Comment by TamamoNoMae13** [comment]
Updated some maps by editing the original post.

**Comment by TamamoNoMae13** [comment]
After doing some checks to reproduce this, it's seem like, it'd depend on the user Windows locale if the bugs would happen or not.

![image](https://user-images.githubusercontent.com/50830861/147845831-4ac9ed70-2709-4fef-aeea-902e0cf1c009.png)
If I set it as Japanese with no UTF-8 support, the *.osu files would be normal.

As of now, I ticked the Beta, it is:
![image](https://user-images.githubusercontent.com/50830861/147845849-13eff9eb-4ba3-4126-aa92-289be53adbd1.png)

If I set the locale to English US/UK like a regular person would do, it would happen like that too.

**Comment by peppy** [comment]
We have already changed the way this works to ensure newer beatmaps are not ranked with unicode characters, for what it's worth. That happened years ago.

Can you confirm that your issue here is only seen when turning on the "Beta" feature?

**Comment by TamamoNoMae13** [comment]
![image](https://user-images.githubusercontent.com/50830861/147898589-c79c392c-cdb8-4402-83ca-12e2ac013e7e.png)
So, the game functions normally now, unlike a year ago in my original issue messages, but the resulting `*.osu` is still like that, if I extracted via other archiving programs (so it's not your end).

If I drag-and-drop, it would still show the cross char.
![image](https://user-images.githubusercontent.com/50830861/147898746-cb598f1b-b1bc-47c4-9f4d-664036e2dae9.png)

A year ago, those diffs don't appear in song select, and if you scrolling down to the utmost bottom, you'll see some map entries with blank metadata (showned as "/"), and when clicked on any of them, the whole map db got processed again.
And at that time, I don't use Beta UTF8 yet. The archiving program showed the ★, and other chars correctly. The resulting files in Songs folder when importing via drag-n-drop also has correct filename, just that the game don't recognize them.
I did a workaround by renaming those files, then F5, and it works again.

At that time I don't even know osz is a zip with its extension renamed yet, so I don't think I'd do anything like not drag-n-drop into the game.

These are records from what I do in JPese locale (with Beta UTF-8 ticked), I will try other locales now.

**Comment by peppy** [comment]
Yes, well, this is a bit out-of-scope in that case. You may want to try other archive applications (maybe 7zip?) to see if they better handle unicode on your system. The fact is that the zip format has very lacking specifications for encodings and we do our best to make it work for our use case.

**Comment by TamamoNoMae13** [comment]
That is 7-zip xD.
7-zip in US locale changes those char to `ü`, whilst Beta (both US and JPese) changes to a rhombus with ? inside.
JPese (w/o Beta) works fine.

Well, I think I should close this. The game works fine now even with ridiculous chars appear.
