### ISSUE TITLE
Change order of icons on user card

### ISSUE THREAD

**Issue by InvisibleSymbol** [ppy/osu-web#6030]
It's weird and confusing that the friends icon changes position between users. 
In this case, if you only look real quick, it almost looks like I'm a mutual with peppy, since the supporter icon has a similar color to mutals. Making it so the friends icon is always the first one fixes this.
|Before|![](https://i.imgur.com/jH0F527.png)|
|-------|-----|
|After|![](https://i.imgur.com/3RC04Mg.png)|

I didn't find an issue about this, but it might have been my keywords.

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu-web/issues/2914. Has been a problem since the old design.

**Comment by peppy** [comment]
Closing as duplicate for the time being.
