### ISSUE TITLE
Web chat is missing messages sometimes

### ISSUE THREAD

**Issue by GrilledCheeese** [ppy/osu-web#6040]
Not sure how to reproduce it but I can give an example, since my private messages are sent to my discord dms I can see messages I would otherwise miss:
![image](https://user-images.githubusercontent.com/34809632/82676548-e1504780-9c46-11ea-9470-e38cfa019747.png)
And in-game the message showed as well:
![image](https://user-images.githubusercontent.com/34809632/82676668-0e9cf580-9c47-11ea-902e-4da752fbe4c5.png)
The message "and how does combo work" isn't shown in web chat
Edit: I see the ":(" isn't in there either

**Comment by peppy** [comment]
This can happen if bancho is not having a good time (logging may be bypassed to save on database overhead at high load times). Eventually it will no longer be an issue as bancho is phased out of existence, but I will take a look and see if we can make an exception for this.

**Comment by peppy** [comment]
This has since been mostly resolved through bancho refactors over the last 6 months. It should be very rare for message to not be logged these days.
