### ISSUE TITLE
Hide "default beatmap download type (with video or not)" if user is not/has never been a supporter

### ISSUE THREAD

**Issue by mcendu** [ppy/osu-web#6045]
This is because this option is completely not useful to non-supporters as they are unable to access osu!direct on stable.

**Comment by lmnyx** [comment]
I think this should stay as its now, but renamed to `preferable`/disabled state for non-supporters.
Its really annoying when you cannot change a specific setting when you miss some privileges, but had/going to.

**Comment by nanaya** [comment]
Is it about the options in account settings page? The osu!direct option is not shown if you're not a supporter and there are still two options remaining without that (video/no video).

**Comment by mcendu** [comment]
yep

**Comment by lmnyx** [comment]
Ohh, that's what you meant. Then thats not an issue. This isn't supporter-only thing.
Look:
![example without](https://user-images.githubusercontent.com/13962537/83252946-90e86500-a1c5-11ea-8d32-6855ac2d23c7.png)
![example with](https://user-images.githubusercontent.com/13962537/83252984-a3fb3500-a1c5-11ea-9951-001bc1fe5148.png)

**Comment by mcendu** [comment]
forgot the download button on the card. close
