### ISSUE TITLE
Unclear what the colors in the score detail page wheel represent

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#6047]
I am guessing the outer edge with the green-blue gradient is score. No idea with the inner colors are supposed to represent. They seem to match the colors indicated by the accuracy key on the left, but I do not know what they relate to.

![](https://i.imgur.com/gtzbBPd.png)

**Comment by bdach** [comment]
The whole dial represents accuracy, mirroring the new lazer results screen. The inner ring is supposed to represent the accuracy required to achieve a particular rank.

Admittedly however it might be a bit unclear as the accuracy percentage does not seem to be shown anywhere on the page currently.

**Comment by cl8n** [comment]
I think it'd be clear enough if ranks had a direct correlation with accuracy, but they don't...

**Comment by peppy** [comment]
they may in a future iteration. for now it's just visual fun, don't read into it too far
