### ISSUE TITLE
Incorrect whitespace applied to short comments under a clipped comment

### ISSUE THREAD

**Issue by bdach** [ppy/osu-web#6054]
The comment clipping feature introduced in #6008 applies clipping to child comments of a clipped comment, which is not necessarily valid. See the following example:

![image](https://user-images.githubusercontent.com/20418176/82831117-d819e180-9eb7-11ea-84a7-cf6866bc76c6.png)

After expanding the parent comment, the child comments actually shrink back in size:

![image](https://user-images.githubusercontent.com/20418176/82831153-e9fb8480-9eb7-11ea-8ca9-e87fc098ed52.png)

This is due to the `.comment-clip` class being applied to the top-level `div` which then propagates to children that don't need to be clipped.

Source comment is [here](https://osu.ppy.sh/comments/1108011).
Reproduced on both Firefox 77.0b9 and Chrome 81.0.4044.138, Windows 10.

**Comment by Phippe** [comment]
Seems kinda related ([this](https://osu.ppy.sh/comments/1081831) comment for reference): Child comments won't extend when clicking on "read more" unless the parent comment is already extended. You need to be on mobile in order to see a "read more" button (will cover this in a seperate issue).
