### ISSUE TITLE
Add link to score page of your own play from beatmap info page

### ISSUE THREAD

**Issue by Phippe** [ppy/osu-web#6068]
There's currently no way to get to the score page of one of your plays if it isn't on the leaderboard of the map or one of your top/recent plays.

I'd suggest to just make the large boxes clickable with a link to the score page:
![grafik](https://user-images.githubusercontent.com/34287258/83194705-5c2ecc00-a139-11ea-9988-b9b24b56a7bc.png)

**Comment by peppy** [comment]
I really feel like even individual rows should be clickable, rather than a tiny menu.

**Comment by peppy** [comment]
@arflyte advise on both of above

**Comment by arflyte** [comment]
Hmm, we can add another tab just for personal scores. And I agree that we should make the rows clickable.
