### ISSUE TITLE
Add API endpoints for viewing and posting on the forum

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#6072]
I'm currently scraping the normal website to automate things for project loved https://osu.ppy.sh/community/forums/120 and I think abraker does the same to get statistics about Off-Topic (?)

would be nice if this could be done via API.

**Comment by abraker95** [comment]
Methods and data:

- **Getting thread info**
thread id
subforum id
timestamp
user
title
status (open, locked, inaccessible, non existent)
list of post ids

- **Getting post info**
post id
thread id
timestamp
user
content
edited?

- **Editing your own post**

**Comment by Ephemeralis** [comment]
Could we get this considered for addition in the short-term? I've finished a bunch of internal logging improvements for GMT-removed content and the absence of any API endpoints to return forum post data means I'll have to write a scraper to do this properly, which sort of blows.

Even just the get-related methods abraker mentioned above would be excellent.

**Comment by peppy** [comment]
Are you asking for special admin routes? Currently API routes generally don't get permissions to view deleted posts and such, which sounds like what you are asking for.

**Comment by Ephemeralis** [comment]
No, just accessing forum posts in general via API. No admin routes or anything special needed.

Like, retrieving post content via post_id, fetching threads with a list of post_id, really basic stuff like that. As far as I can tell, it doesn't exist currently, or the documentation doesn't list it if it does.

**Comment by peppy** [comment]
Might be nice to get the bare basics in for this if it's a quick one.

**Comment by nanaya** [comment]
Are post actions (topic create, edit (title), reply, and post edit) needed as well or just topic/posts listing is enough?

**Comment by abraker95** [comment]
I'll need post editing

**Comment by cl8n** [comment]
> Are post actions (topic create, edit (title), reply, and post edit) needed as well or just topic/posts listing is enough?

I'm doing basically everything you can do on the normal website so I'd need it all-- the only write action I think is missing from above PR is creating forum topic cover, thnx for working on this!

I saw that the `chat.write` scope can only be given from a bot account's client, will the same be true for `forum.write` ?
