### ISSUE TITLE
Group badges don't wrap properly on mobile

### ISSUE THREAD

**Issue by E223** [ppy/osu-web#6074]
User page:
![](https://i.imgur.com/OV3lIuP.png)
![](https://i.imgur.com/cXC805X.png)

Search (seems to mainly be an issue with 3+ badges unless you have a really small device):
![](https://i.imgur.com/QeRZy6T.png)

**Comment by lmnyx** [comment]
Yeah, reproducible. Issue with https://github.com/ppy/osu-web/pull/6013
![example](https://user-images.githubusercontent.com/13962537/83328426-5e5d6b80-a29c-11ea-868b-e7c1257534d9.png)

**Comment by nanaya** [comment]
hi @arflyte

**Comment by arflyte** [comment]
Damn, group tag hoarders. I'll look into this. Maybe we can make them stacked like mod icons or something. I dunno, I'll figure something now.

**Comment by lmnyx** [comment]
Maybe add `+` block near and make it like dropdown or make them animated so they will change every, for example, 2-3s? Just first thoughts.

**Comment by arflyte** [comment]
![Figma_200602-181943](https://user-images.githubusercontent.com/3632750/83503200-b050fc00-a4fd-11ea-8c1b-8c5e46e26604.png)

Only display one group badge, and the rest reduce it to a coloured dot. Reduce the padding between items to 2px.

For user info panel, slightly reduce the size of the avatar.

**Comment by notbakaneko** [comment]
Narrow screens already can barely fit a short username, supporter icon and single badge, let alone a flag; I don't know how wanting to show all the group badges / icons should even be considered a good idea.

sort of related since the icons can't fit either #6517

**Comment by notbakaneko** [comment]
Also, quick search results remain after navigation; someone can always select a search result to see the full details of the user and then reopen quick search and pick a different user; cramming everything in seems completely unnecessary.

**Comment by peppy** [comment]
showing just one is fine IMO
