### ISSUE TITLE
Mania maps with keycount more than 10 (a.k.a. Co-op) are displayed as 10k

### ISSUE THREAD

**Issue by mcendu** [ppy/osu-web#6075]
~~[This map (cs 8 + coop) kinda demonstrates the issue.](https://osu.ppy.sh/beatmapsets/1181312#mania/2463158)~~ These keymodes are unrankable, so not very important.

**Comment by nanaya** [comment]
It looks like the linked map is now 7K. At any rate, the keycount display is taken directly from beatmap metadata itself so if it's showing wrong keycount then the data itself is wrong? :shrug: 

Either that or there's additional metadata I'm missing here.

**Comment by mcendu** [comment]
> 
> 
> It looks like the linked map is now 7K. At any rate, the keycount display is taken directly from beatmap metadata itself so if it's showing wrong keycount then the data itself is wrong? 🤷
> 
> Either that or there's additional metadata I'm missing here.

Original map is 16K. Replaced with an std map, got a few mods, then graveyarded.

**Comment by nanaya** [comment]
It looks like the database says 10 keys (`diff_size` column) for those maps. For example [this one](https://osu.ppy.sh/beatmapsets/912527#mania/1906244). @peppy should know more about this mismatch.

**Comment by peppy** [comment]
@smoogipoo before i look into this, i think you may already know the answer to this one?

**Comment by smoogipoo** [comment]
Stable's diffcalc is just old enough that it doesn't know about the coop mod and still caps CS at 10. If there's no other BSS process that parses the beatmap and sets `osu_beatmaps.diff_size` correctly before diffcalc, then this is going to be challenging to fix (either new stable calculator build with deprecated toolchain or wait for lazer's diffcalc).

**Comment by peppy** [comment]
Will be looking to deploy the lazer mania diffcalc backend next week, which should resolve this.

**Comment by smoogipoo** [comment]
Closing as resolved, see:
- https://osu.ppy.sh/beatmapsets/912527#mania/1906244
- https://osu.ppy.sh/beatmapsets?q=keys%3E10&s=any
