### ISSUE TITLE
Increase paragraph/issue limit for modding reviews

### ISSUE THREAD

**Issue by venix12** [ppy/osu-web#6083]
At the moment it is set to 10, which is a pretty small value (especially considering paragraphs count into it)

**Comment by Ephemeralis** [comment]
100 would be considerably more reasonable as an upper limit, and even then that might still be too little for some fringe cases.

**Comment by hypercyte** [comment]
Agree with eph, majority of mods will go beyond just 1-2 points per difficulty.

People may want to keep their reviews clean by using blank lines (which each count as their own paragraph) to organise things too.

**Comment by Loctav** [comment]
I don't even know why there is a limit to begin with. Is there a reason why it is capped? 100 seems also reasonably low if you consider beatmaps that have more than 2 difficulties. Hitting 20 suggestions across 5 difficulties doesn't seem overly much, especially if you add General issues to it, too, so 100 is also pretty low. I'd rather abolish the cap entirely.

**Comment by venix12** [comment]
Guess the limit is to avoid database overload? After all, each issue from the review is stored as a single entry in issues database iirc.

**Comment by Loctav** [comment]
But I could still write over a 100 suggestions without using the review feature and I am not capped there either. I don't like speculating about why it even exists, however it's existence makes no sense from a modder's point of view.

**Comment by venix12** [comment]
Yeah, it's right, somebody could abuse it when there was no limit though; would honestly go for a healthy limit (probably even over 100), maybe based on difficulty count as well?

Posting 1000 issues separately is kinda different from posting them literally at once, if you spam those quickly, you will get an error after a few anyways.

**Comment by peppy** [comment]
The limit has been increased to 40. Over 40 sounds like you are not productively reviewing. Similar issues should be grouped rather than spamming and overwhelming the mapper.

Please give this a try and we'll discuss in a few weeks if this is not high enough (with examples).
