### ISSUE TITLE
Deleted discussions in reviews should be clear to moderators

### ISSUE THREAD

**Issue by pishifat** [ppy/osu-web#6088]
normal discussions differentiate between visible/deleted posts for moderators:
![](https://i.imgur.com/TGOY4oI.png)

"hype" is the deleted post in the review below

normal users see this:
![](https://i.imgur.com/xHMa1Vn.png)

moderators see this:
![](https://i.imgur.com/nTPd0qc.png)
there should be an indicator that "hype" is deleted for moderators

**Comment by peppy** [comment]
@arflyte how should deleted posts look to admins? are we fading them like elsewhere?

**Comment by arflyte** [comment]
yeah, make it faded too.
