### ISSUE TITLE
Navigation is a long bar in beatmap discussions

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#6089]
That doesn't look right, and is possibly unintended

![](https://i.imgur.com/VApBC5B.png)

**Comment by bdach** [comment]
#6018 is a similar design issue.

**Comment by peppy** [comment]
May be a duplicate. Already milestoned and high priority.

@arflyte bumping yet again because nothing has happened.

**Comment by arflyte** [comment]
already looking into it.

**Comment by nanaya** [comment]
Combining with #6018 as they both are more or less the same thing.
