### ISSUE TITLE
In modding review, autocorrect mobile keyboards may duplicate text, make text input weird, and make the entire modding page blank.

### ISSUE THREAD

**Issue by Cynplytholowazy** [ppy/osu-web#6097]
Autocorrect mobile keyboards may duplicate text, make text input weird, and make the entire modding page blank. This issue will occur when using Google Keyboard for Android. Other similar autocorrect keyboards may be affected by these too.

I am using the Chinese Pinyin variant of Google Keyboard in the below videos attached. This is reproducible with Gboard - the Google Keyboard.

[Video: Weird text input when editing in-between numbers.](https://cdn.discordapp.com/attachments/423292757038071809/716920546151104554/Screenrecorder-2020-06-01-15-42-27-492.mp4)

[Video: Any kind of keyboard input mid-text will cause texts to duplicate.](https://cdn.discordapp.com/attachments/451253981616930816/717362463485591582/Screenrecorder-2020-06-01-15-52-33-312.mp4)

[Video: Holding backspace will cause the page disappear.](https://cdn.discordapp.com/attachments/451253981616930816/717358555153301604/Screenrecorder-2020-06-02-20-46-09-386.mp4)

**Comment by notbakaneko** [comment]
The main issue appears to be the way Android keyboards handle input events for browsers making it problematic for React and WYSIWYG editors.
https://github.com/ianstormtaylor/slate/search?q=android+input&type=Issues

**Comment by notbakaneko** [comment]
Also general IME bugs https://github.com/ianstormtaylor/slate/search?q=IME&type=issues

**Comment by peppy** [comment]
Will bump this up in priority due to multiple people hitting it.
