### ISSUE TITLE
Skin System

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#61]
For Marcin

Pages:
- Skin listing page. Should allow users to view all public skins (and also all of their own skins).
- Skin information page. What you get when you click a listing entry. Gives you options to clone the skin (make your own copy of it to further modify), download, watch preview videos etc.
- Skin creation page. Choose skin name, description, preview image, upload skin elements.

Things to consider:
- Skins should be versioned. A creator should be able to easily add a new version of a skin based on the previous one.
- Users should be able to set private or public for a skin, and also decide whether others are allowed to use their elements in further skins.
- When creating a skin from scratch, a user will be able to upload an element of choose from a listing of all elements from skins which have allowed use of individual elements.
- Eventually we'll want all the skin.ini settings also modifiable via a web interface.

**Comment by PieInOblivion** [comment]
I think it could be nice that when a user visits a skins download page that it's thumbnail or preview picture be a server generated one. This preview image would be consistent across all skins (But will show the selected skin instead) and I think could look quite nice.

Eg: http://puu.sh/k2Utb.png
The red line is just to split the two and show how both are the same but with different skins.

**Comment by peppy** [comment]
This is planned, yes.

**Comment by Nicarim** [comment]
That was planned before, yeah,

pon., 7 wrz 2015, 12:57 PieInOblivion użytkownik <notifications@github.com>
napisał:

**Comment by PieInOblivion** [comment]
May I ask what's missing? perhaps I could contribute?

**Comment by Nicarim** [comment]
@PieInOblivion nothing is done yet, it's just a draft until I pick it up (probably tomorrow)

**Comment by PieInOblivion** [comment]
If any assistance or errors are found or needed, I'll attempt best I can to help.

**Comment by pixeldesu** [comment]
> Skins should be versioned.

I think this would be solved the easiest way with giving the users another variable in the `skin.ini` called `SkinVersion` or `Revision` or something alike. This then could be combined with...

> Eventually we'll want all the skin.ini settings also modifiable via a web interface.

...so people can just upload the new elements and change this _on-the-fly_, if they (for example) forget to change the version number in the skin.

**Comment by peppy** [comment]
Versioning is most definitely planned to be part of the system.

**Comment by PieInOblivion** [comment]
Am I correct in saying that if no VersionNumber is given, the client or server (when uploading) will auto assign one?

**Comment by Nicarim** [comment]
db01b8fe86c7e169f7582189762aad69dfe54738
Please check if I forgot about something.
Also there I'm not sure how should elements that have more than one frame (are animation) should be handled, any ideas?

**Comment by PieInOblivion** [comment]
So eg: 'scorebar-colour-0' to 'scorebar-colour-10'
I would take it simple and just use the first 'Frame' of the animation and display that on the preview.
- OR -
Generate a GIF, detecting/counting how many frames there are max of any animation, and create the GIF accordingly. Perhaps with a limit of 'XXX' frames in the GIF in case someone trolls and creates a purposefully long animation to use lots of bandwidth.

**Comment by ameliaikeda** [comment]
@PieInOblivion bandwidth isn't really an issue for that to be honest. Just make the gif the same overall length in seconds.

**Comment by Nicarim** [comment]
@ameliaikeda @PieInOblivion in old version of that site, there was javascript in place that iterated over every frame in <img> tag so it looked like it was animation.

**Comment by TobySchoon** [comment]
I think this is a great idea! You could also put your own item / photo in for other people to use. But it would have to be cropped. But otherwise, if you wanted me to, i would be glad to put photos in for when the project is done!

**Comment by notbakaneko** [comment]
This is planned to be handled in the game client.

**Comment by lunafreya** [comment]
@notbakaneko Uhh... You should have to tell @peppy first; he was going to put up a dedicated skin section in the new osu!web.

**Comment by peppy** [comment]
We discussed this IRL. There will be a listing/information page but this issue is outdated and inaccurate for the time being.

**Comment by catb0x** [comment]
@peppy is this still planned?

**Comment by peppy** [comment]
As long as issues are open, then issues are open.

**Comment by ilyaxuwu** [comment]
where is the exactly skin system? @peppy

**Comment by Joehuu** [comment]
@ilyaxuwu moved to https://github.com/ppy/osu/discussions/17759. Please upvote!
