### ISSUE TITLE
Modding reviews: allow newline within a single issue/paragraph using shift+enter

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#6111]
When posting individual discussions, it is possible to use shift+enter to add newlines within a post, like so:
![image](https://user-images.githubusercontent.com/33286824/83680402-ed28fb80-a5ae-11ea-8610-8f5ead7d2cc6.png)

but on modding reviews, this is not the case. It should be the case for consistency and convenience! 
![image](https://user-images.githubusercontent.com/33286824/83680246-b81ca900-a5ae-11ea-8342-4e75ad05ca33.png)

allowing for newlines within a post is a very useful formatting tool. 

allowing shift+enter to create a newline should apply within paragraphs as well, as forcing every newline to count as a seperate paragraph is more restrictive for those who prefer to format using list formatting instead of large walls of text. Especially with the current limit of 40 paragraphs+issues per review.

**Comment by nanaya** [comment]
Adding newlines in embed is now possible and at current 100 blocks limit it should fine for main review post itself.

I still think paragraph blocks shouldn't be counted toward that limit though (or at least counted differently).
