### ISSUE TITLE
Config option to enable anonymous beatmap listing searches

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-web#6121]
Originally mentioned in https://github.com/ppy/osu-web/issues/5924

I'd really like a way to enable anonymous beatmap listing searches for my deploys. This used to be possible once-upon-a-time via changing `app/Libraries/Search/BeatmapsetSearchRequestParams.php`, but that technique doesn't seem to work anymore :(

**Comment by peppy** [comment]
Just to better understand, what's the issue with creating a user and logging in using it (with username/password a or similar)?

**Comment by smoogipoo** [comment]
Because this isn't just for me to use locally - it's for people on the discord #difficulty channels, for people that post it on twitter, on reddit, in other discord servers, etc.

**Comment by peppy** [comment]
As a workaround, could you just make one account for people to use when logging in? Or does verification or the likes get in the way?

**Comment by smoogipoo** [comment]
Seems to work. My concern was mostly that it's hidden away, but I'll take it as a temporary workaround.
