### ISSUE TITLE
Reviews need to be better included in modding discussions filters

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#6122]
Right now, if you apply the pending filter on the modding discussions page, there will never be any reviews displayed. This is true even if all the issues in the review are still open. Having it missing from the filtered view can lead to review-formatted modding posts being missed entirely if a mapper is used to applying mods by applying the pending filter and seeing what's left.

the review should display under any filter the posts it contains satisfy, for example if a review contains a praise, a resolved issue, and a pending issue, it would then display for all 3 filters. If it has a praise and just one other post that's an open issue, it would display for the praise and pending filters. So on and so forth.

**Comment by peppy** [comment]
Not sure if this is high priority, remove from milestone if it's not deemed as such.
