### ISSUE TITLE
beatmap search "pending & wip" category is often including graveyarded maps

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#6127]
![image](https://user-images.githubusercontent.com/33286824/83877729-0a71dd00-a709-11ea-9686-40e83be0cf95.png)

5/6 maps in this first page of search results are graveyarded on this pending & wip categorized search.

This obviously isn't right, and has been occurring recently under all search terms. It has always been that _very recently_ (within a day) graveyarded maps tend to show up in the "pending & wip" category, but lately maps as old as 50-60 days since their last update have still been showing up in the category, making it effectively useless, because half the results will be **graveyarded**, not pending, not wip.

For example: I often use pending map searches to find maps to push for ranked, so it's really inconvenient website features are not functioning properly ): .

**Comment by peppy** [comment]
Sounds like we aren't correctly updating indexing results when a beatmap changes state. I'll take a look into this.

**Comment by peppy** [comment]
This should be resolved.
