### ISSUE TITLE
Navigation Header Design Update, Part 1

### ISSUE THREAD

**Issue by arflyte** [ppy/osu-web#613]
![](http://puu.sh/pz9qx/f48b74f827.png)

Design update to replace the current top navigation bar to improve usability and standardise designs. All image snippets at 2x unless mentioned otherwise.
### Pulsing osu!cookie

![](http://puu.sh/pAo4x/2e30882e3e.png)

The osu!cookie should pulse on hover. Suggest something nice, fun and not overly done.
#### Title Bar

![](http://puu.sh/pAo8J/aaa26ab3db.png)

Displays the page section title, not the page title (the page title should be within the cover). The title should appear something like this: "rankings > chart". The angle-right's opacity is 50%. All title should be in small caps.

There's a new orange bar under page section title now to suggest interaction. Not finalised; requires live testing for usability test.

The orange bar will only disappear when the profile quick info panel is used or quick search results is displayed.
#### Nav Box

![](http://puu.sh/pz9u8/a10c50ea47.png)
This is the new main navigation panel, or Nav Box. Image snippet at 1x.

This box will be used for main navigation, player quick info panel and quick search result panel (designs available for main navigation only for now.)

The navigation panel appears on top of everything except the osu!cookie and user avatar. It doesn't push the page content down.

It appears when hovered on the entire navigation bar. On tablets, when clicked on the page title (hence the orange bar). The animation is a quick slide down of the dark grey box, with the contents fading in before the box animation is completed. The entire animation should take less than 300ms (will be finalised later), hopefully doesn't set aging computers on fire.

Main item at #999 grey.

![](http://puu.sh/pzaEb/cf6acdd74c.png)

Item goes bold and white when hovered, orange bar marker on top. Orange sub items fades in. Suggest fade animation (something less than 100ms). Sub item goes bold and white on hover with barely visible chevron-right on the left.
## Part 2

Part 2 will be on Profile Quick Info Panel. Soon.

**Comment by arflyte** [comment]
![](http://puu.sh/pL9rh/14689a1afd.png)

New language settings added to the navigation bar. The item and the bar is purple. 

The flags represents the language's origin (or where it's used as the official language), something pretty common in multi-language manuals. This might be changed in the future too accommodate more languages in the future.

**Comment by nekodex** [comment]
This has been done.
