### ISSUE TITLE
incorrect star rating displayed after updating beatmap

### ISSUE THREAD

**Issue by 02Naitsirk** [ppy/osu-web#6132]
after updating a beatmap and going to the beatmap page, it's somewhat likely that the star ratings will be incorrect. the old star ratings (before the angle changes/speed changes) will be shown instead of the new ones. a simple refresh fixes this.

video: https://streamable.com/e2v4hu

**Comment by peppy** [comment]
What do you mean by "a simple refresh"?

**Comment by 02Naitsirk** [comment]
> What do you mean by "a simple refresh"?

reloading/refreshing the page fixes the issue (the correct star ratings show up).

**Comment by peppy** [comment]
this doesn't sound like a problem then, maybe you just refreshed too fast?

**Comment by 02Naitsirk** [comment]
> this doesn't sound like a problem then, maybe you just refreshed too fast?

what? im pretty confused now, it is definitely a bug (very minor but still). the wrong star ratings go away only if the page is reloaded. i dont know what you mean by i refreshed too fast, how exactly would that cause the problem? 

if i wasnt clear: when you update a map and the game says it is updated, then you click on the option to go to the beatmap page, there is a chance that the star ratings are wrong (i said chance, because i dont think it happens every time u update). the star ratings shown is what the old sr system would calculate. this will happen even if the update to the beatmap did not change sr.

ill give an example using my map shown in the video. my map was 5.55* before i updated it. the star ratings in-game and on the site matched. then i made a really minor change (the map was still 5.55* in-game after my changes.) i uploaded my map, and clicked the option to go to the beatmap page. however, the site displayed a much different star rating (5.41*), which is what the sr would have been in the old sr system. i got confused and i refreshed the page, and then the site displayed the correct sr (5.55*). that is the bug.

**Comment by peppy** [comment]
calculating the difficulty is done asynchronously. it can take seconds or minutes to complete. this is normal.

**Comment by peppy** [comment]
Closing as working-as-intended.
