### ISSUE TITLE
Chat doesn't hide messages of silenced users

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#6133]
![image](https://user-images.githubusercontent.com/19843905/83979776-162ff000-a911-11ea-8e4c-d874c28f582f.png)

![image](https://user-images.githubusercontent.com/19843905/83979793-234cdf00-a911-11ea-803e-7d4c3e575652.png)

User has been muted, but his messages weren't removed from the chat

**Comment by notbakaneko** [comment]
Muting doesn't make messages suddenly disappear especially if it's just going to expire.

**Comment by peppy** [comment]
We probably need to address this somehow. Have to figure the best way to approach it (maybe bancho should fire a specific endpoint on silence?)

**Comment by nanaya** [comment]
What is the expected result here? Permanently remove all of the silenced user's messages? Or hide the messages for however long their silence is and then make them visible again afterwards?

**Comment by peppy** [comment]
They shouldn't return afterwards.
