### ISSUE TITLE
long map title on match history overflows

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#6135]
![image](https://user-images.githubusercontent.com/9954349/83990264-e0cdd700-a8fd-11ea-9afe-b8f0d332971d.png)
should probably do the ellipses thing at the end

**Comment by gagahpangeran** [comment]
I want to fix this issue.

Looks like I only need remove these lines
https://github.com/ppy/osu-web/blob/033a075dd11e67f15deadcf5dcd016711e169c7c/resources/assets/less/bem/mp-history-game.less#L67-L69

I only check it from browser dev tools right now. I'll check it again after I finish the setup and make sure nothing is broken.
