### ISSUE TITLE
Message notification shows 1 message, but 0 in it?

### ISSUE THREAD

**Issue by lmnyx** [ppy/osu-web#6144]
![image](https://user-images.githubusercontent.com/13962537/84072180-37174480-a9e8-11ea-9661-162d3a4cccd5.png)
Really don't know how that happened, but thats been for a while like that

**Comment by notbakaneko** [comment]
Do you have a left over unread chat notification?

**Comment by lmnyx** [comment]
I don't really know, I read the messages once and cleared them all and for a week or two I see that notification about message is left, but when I look into it there is no messages

**Comment by notbakaneko** [comment]
Do you still have an unread chat notification here?
![Untitled](https://user-images.githubusercontent.com/1694544/84116958-c4e84380-aa6b-11ea-8427-3603e98cc98f.png)

A channel or conversation getting closed doesn't automatically mark it as read.

**Comment by lmnyx** [comment]
Oh. Yes, I had. Thanks.
