### ISSUE TITLE
Player Main Page, Part 1

### ISSUE THREAD

**Issue by arflyte** [ppy/osu-web#615]
![](http://puu.sh/pAt5d/3676a05051.png)

This is the new design for player main page when they're signed in. Players will be able to check the news update, friends page, team member page, messaging, account settings and maybe more. **Designs not final** but ready for implementation.

For now, only the news page is designed.

_This design is meant for desktop and tablet. Mobile view is still a work in progress._
### Header

![](http://puu.sh/pAt8x/bc98e9dfa4.png)

Image snippet at 1x.

Player profile cover, 50% height, vertically center aligned. It says "Hello" if the player logs in regularly, "Welcome back" if player haven't logged in the last 7 days. Maybe "We missed you" if the player didn't logged in for months for the fun of it.

On the right is the online players stats. The graph displays the number of all online players in the last 24 hours.
### News Article

![](http://puu.sh/pAtwA/a3c36c3789.png)

The latest 3 news will display the article's cover images. While the cover image for news article can be in any size, cover box is 860*260 (at 2x) and the image should be resized to fit it.

![](http://puu.sh/pAtDW/e25cd4e38c.png)

Other news are listed in a single box, up to 10 articles. There will be a "more news" button to open a list of old articles.
### Recommended Beatmaps

![](http://puu.sh/pAtRu/e75d4db4b9.png)

On the right column are the recommended beatmaps, promoting newly approved beatmaps and the week's popular beatmaps.
## Other sections

Design pages for other sections are coming. Soon.

**Comment by TPGPL** [comment]
►The dark background looks bad with the triangle background (mixing white and black isn't good)
►Navigation bars should have thinner underline and the first char should be uppercase
►Pink font doesn't look nice on grey background

**Comment by iamanai** [comment]
Just a personal opinion, but it would look way more uniform and streamlined if everything (except the main header bar, which will extend all the way across) were the same width. I get what you're trying to do here, but it just doesn't appeal to me. Besides the widths, everything looks splendid!

**Comment by kschamplin19** [comment]
that design choice is everywhere on the site.

**Comment by iamanai** [comment]
Yeah, I know. I'm saying I think it ought to be changed site-wide.

**Comment by RedbackThomson** [comment]
@reesebiz and I are keen to work on this after we finish the landing. Just reply if/when the changes are made with the PSD and we can hit it asap.

**Comment by reesebiz** [comment]
@arflyte @peppy Where can we find the psd at?

**Comment by kschamplin19** [comment]
Will this update the team page design as well? I'd like to do it now rather than later.

**Comment by marii-osu** [comment]
For new approved/week's popular beatmaps, the black triangles on the right should be easier to see; maybe change the color to white/yellow?

**Comment by kschamplin19** [comment]
if no one is gonna do this I'll step up to the plate if I can get the psd

**Comment by nekodex** [comment]
@arflyte ping

**Comment by arflyte** [comment]
@kschamplin19 heya, pm me on discord and i'll give you the psd files. ^_^/

**Comment by reesebiz** [comment]
@kschamplin19 We're still working on this, but took kind of an extended break :P

Just an update we haven't died or anything. I'll post an update on our status this weekend

**Comment by reesebiz** [comment]
It's mostly just been on me doing the HTML/CSS. I'll hand off the programming bits to Redback to hook up when i'm done!

**Comment by nekodex** [comment]
This has been done.
