### ISSUE TITLE
Old beatmaps are incorrectly shown as having 0 sliders 

### ISSUE THREAD

**Issue by KevKjef** [ppy/osu-web#6158]
The issue is explained in the title.

The object count says the map has no sliders while it most definetely does.
![Disco prince](https://user-images.githubusercontent.com/64087607/84354976-1f93b380-abc2-11ea-8b8a-0733236c45cb.PNG)

I found out about this issue when xasuma made a list of all no-slider maps for me.
I looked at this list and found it odd that there were so many old low-id beatmaps on this list.
Since it only happens to these really old maps I think it may be an issue with old file formats, but I can't say for certain.

Here is the list of maps which are shown as having 0-sliders, despite having multiple.
Note: this issue is apparent on all difficulties on maps with multiple.
https://osu.ppy.sh/beatmapsets/1#osu/75
https://osu.ppy.sh/beatmapsets/16#osu/119
https://osu.ppy.sh/beatmapsets/18#osu/80
https://osu.ppy.sh/beatmapsets/23#osu/86
https://osu.ppy.sh/beatmapsets/25#osu/165
https://osu.ppy.sh/beatmapsets/27#osu/121
https://osu.ppy.sh/beatmapsets/28#osu/188
https://osu.ppy.sh/beatmapsets/30#osu/101
https://osu.ppy.sh/beatmapsets/31#osu/100
https://osu.ppy.sh/beatmapsets/32#osu/102
https://osu.ppy.sh/beatmapsets/35#osu/110
https://osu.ppy.sh/beatmapsets/36#osu/220
https://osu.ppy.sh/beatmapsets/38#osu/116
https://osu.ppy.sh/beatmapsets/39#osu/170
https://osu.ppy.sh/beatmapsets/40#osu/145
https://osu.ppy.sh/beatmapsets/41#osu/120
https://osu.ppy.sh/beatmapsets/43#osu/123
https://osu.ppy.sh/beatmapsets/44#osu/124
https://osu.ppy.sh/beatmapsets/45#osu/126
https://osu.ppy.sh/beatmapsets/46#osu/127
https://osu.ppy.sh/beatmapsets/47#osu/131
https://osu.ppy.sh/beatmapsets/48#osu/132
https://osu.ppy.sh/beatmapsets/49#osu/133
https://osu.ppy.sh/beatmapsets/50#osu/134
https://osu.ppy.sh/beatmapsets/51#osu/153
https://osu.ppy.sh/beatmapsets/52#osu/137
https://osu.ppy.sh/beatmapsets/54#osu/141
https://osu.ppy.sh/beatmapsets/55#osu/162
https://osu.ppy.sh/beatmapsets/56#osu/164
https://osu.ppy.sh/beatmapsets/57#osu/144
https://osu.ppy.sh/beatmapsets/58#osu/146
https://osu.ppy.sh/beatmapsets/59#osu/147
https://osu.ppy.sh/beatmapsets/60#osu/148
https://osu.ppy.sh/beatmapsets/62#osu/200
https://osu.ppy.sh/beatmapsets/64#osu/195
https://osu.ppy.sh/beatmapsets/65#osu/155
https://osu.ppy.sh/beatmapsets/66#osu/178
https://osu.ppy.sh/beatmapsets/67#osu/160
https://osu.ppy.sh/beatmapsets/72#osu/166
https://osu.ppy.sh/beatmapsets/73#osu/167
https://osu.ppy.sh/beatmapsets/74#osu/171
https://osu.ppy.sh/beatmapsets/75#osu/275
https://osu.ppy.sh/beatmapsets/76#osu/172
https://osu.ppy.sh/beatmapsets/77#osu/175
https://osu.ppy.sh/beatmapsets/78#osu/177
https://osu.ppy.sh/beatmapsets/79#osu/187
https://osu.ppy.sh/beatmapsets/80#osu/180
https://osu.ppy.sh/beatmapsets/82#osu/186
https://osu.ppy.sh/beatmapsets/83#osu/189
https://osu.ppy.sh/beatmapsets/84#osu/324
https://osu.ppy.sh/beatmapsets/85#osu/193
https://osu.ppy.sh/beatmapsets/86#osu/194
https://osu.ppy.sh/beatmapsets/87#osu/196
https://osu.ppy.sh/beatmapsets/88#osu/198
https://osu.ppy.sh/beatmapsets/90#osu/203
https://osu.ppy.sh/beatmapsets/91#osu/204
https://osu.ppy.sh/beatmapsets/93#osu/209
https://osu.ppy.sh/beatmapsets/94#osu/210
https://osu.ppy.sh/beatmapsets/95#osu/212
https://osu.ppy.sh/beatmapsets/96#osu/213
https://osu.ppy.sh/beatmapsets/97#osu/216
https://osu.ppy.sh/beatmapsets/98#osu/218
https://osu.ppy.sh/beatmapsets/100#osu/221
https://osu.ppy.sh/beatmapsets/101#osu/227
https://osu.ppy.sh/beatmapsets/102#osu/223
https://osu.ppy.sh/beatmapsets/104#osu/228
https://osu.ppy.sh/beatmapsets/106#osu/232
https://osu.ppy.sh/beatmapsets/107#osu/233
https://osu.ppy.sh/beatmapsets/108#osu/235
https://osu.ppy.sh/beatmapsets/110#osu/242
https://osu.ppy.sh/beatmapsets/114#osu/249
https://osu.ppy.sh/beatmapsets/116#osu/255
https://osu.ppy.sh/beatmapsets/117#osu/256
https://osu.ppy.sh/beatmapsets/118#osu/257
https://osu.ppy.sh/beatmapsets/120#osu/272
https://osu.ppy.sh/beatmapsets/122#osu/269
https://osu.ppy.sh/beatmapsets/125#osu/279
https://osu.ppy.sh/beatmapsets/127#osu/284
https://osu.ppy.sh/beatmapsets/128#osu/285
https://osu.ppy.sh/beatmapsets/129#osu/287
https://osu.ppy.sh/beatmapsets/130#osu/289
https://osu.ppy.sh/beatmapsets/131#osu/291
https://osu.ppy.sh/beatmapsets/132#osu/293
https://osu.ppy.sh/beatmapsets/133#osu/297
https://osu.ppy.sh/beatmapsets/134#osu/299
https://osu.ppy.sh/beatmapsets/135#osu/321
https://osu.ppy.sh/beatmapsets/136#osu/306
https://osu.ppy.sh/beatmapsets/137#osu/308
https://osu.ppy.sh/beatmapsets/138#osu/309
https://osu.ppy.sh/beatmapsets/139#osu/310
https://osu.ppy.sh/beatmapsets/140#osu/312
https://osu.ppy.sh/beatmapsets/141#osu/313
https://osu.ppy.sh/beatmapsets/142#osu/318
https://osu.ppy.sh/beatmapsets/145#osu/329
https://osu.ppy.sh/beatmapsets/147#osu/332
https://osu.ppy.sh/beatmapsets/149#osu/334
https://osu.ppy.sh/beatmapsets/150#osu/335
https://osu.ppy.sh/beatmapsets/151#osu/337
https://osu.ppy.sh/beatmapsets/152#osu/340
https://osu.ppy.sh/beatmapsets/153#osu/342
https://osu.ppy.sh/beatmapsets/154#osu/346
https://osu.ppy.sh/beatmapsets/156#osu/349
https://osu.ppy.sh/beatmapsets/158#osu/353
https://osu.ppy.sh/beatmapsets/159#osu/356
https://osu.ppy.sh/beatmapsets/162#osu/365
https://osu.ppy.sh/beatmapsets/163#osu/367
https://osu.ppy.sh/beatmapsets/167#osu/398
https://osu.ppy.sh/beatmapsets/168#osu/417
https://osu.ppy.sh/beatmapsets/169#osu/419
https://osu.ppy.sh/beatmapsets/166#osu/421
https://osu.ppy.sh/beatmapsets/170#osu/424
https://osu.ppy.sh/beatmapsets/171#osu/427
https://osu.ppy.sh/beatmapsets/33#osu/339
https://osu.ppy.sh/beatmapsets/201#osu/614
https://osu.ppy.sh/beatmapsets/203#osu/625
https://osu.ppy.sh/beatmapsets/212#osu/2029

You can also find these maps on the file I got from xasuma:
[No sliders.xlsx](https://github.com/ppy/osu-web/files/4763285/No.sliders.xlsx)
Please note that there are maps on this list that do have 0-sliders (as that is what the list was made for) even among the list of incorrect old ones.

**Comment by Magnus-Cosmos** [comment]
I made a list for this about 2 years ago with the correct values: https://docs.google.com/spreadsheets/d/1qjo1XoUn1z2M2MEJ4ZA1fJFhIkossAAtkTk2uzA-UiM

There should be a total of 185 maps (all before 2008) where the slider/spinner count shows 0 on website/api when it isn't ingame

**Comment by peppy** [comment]
@Magnus-Cosmos what was the process you used to make the sheet?

**Comment by Magnus-Cosmos** [comment]
The original sheet was made manually by checking inagme using osu! stable. Since it was a while ago, I decided to recheck the values and add two new sheets that are made using two different beatmap parsers (https://github.com/llllllllll/slider and https://github.com/Magnus-Cosmos/bparser-js).

Also it seems like the first 4 mania mapsets also have this issue which I added to the sheets.

**Comment by peppy** [comment]
Thanks a lot. I've updated all the values. Closing this issue, please let me know if you find any discrepancies.
