### ISSUE TITLE
Forum Thread Design Update

### ISSUE THREAD

**Issue by arflyte** [ppy/osu-web#616]
![](http://puu.sh/pAvnh/ad3574feca.png)

New design update to conform to the latest design standards.

![](http://puu.sh/pAvoE/1e98b0ef8c.png)

The new sub-navigation bar that used on other pages as section tabs, is used as breadcrumb bar in the forums.

Tab colour follows the forum section colour. Pink is used in the example.

![](http://puu.sh/pAvrU/ab98a355cf.png)

Thread title design updated to Exo 2 Semi-Bold Italic 30px (1x).

![](http://puu.sh/pAvuE/4f43709c32.png)

New total post count box.

**Comment by nanaya** [comment]
Done ┐(･_･)┌
