### ISSUE TITLE
Green checkmark on leaderboards to indicate that a replay has been verified by osu!'s anticheat / Manual replay verification

### ISSUE THREAD

**Issue by cometblazer** [ppy/osu-web#6178]
Note: This is a proposal and is *probably* best suited to be under the "beatmap-listing" area.

This was a hybrid set of two ideas, but since they're both related to each other, I thought I'd suggest a proposal for them both.

In a newer era of osu!, a user's plays are getting more and more difficult to gauge the legitimacy of on the player's end. This includes both replays AND liveplays (which, contrary to what people think, *are* definitely editable in programs like Vegas and Premiere Pro, and this *has* been done before).

This proposal attempts to ease the stress of the issue, with a subtle but noticeable green checkmark next to replays/user scores in leaderboards on-site. Optionally, this idea could also be implemented in the Lazer client itself, but I'll leave that for another time.

Simply put, this green checkmark is an indicator that the replay has passed every check and test run by osu!'s AC, *without* compromising anything related to how those check(s) and test(s) work. There would also be one other icon for the sake of completion, which is a yellow exclamation (!) mark. This would indicate the replay/score on which it is placed in the leaderboards is pending verification *by* those check(s) and test(s).

To build onto this idea, I can also suggest a (slightly more ambitious) page on-site that users may visit to upload replays manually, as well. Each user would be rate-limited to 2-5 replays a minute (arbitrary figure, adjust as needed) to avoid abuse. These replays would be added into a queue list for processing, and when the user's replay(s) are processed, it would return either the same green checkmark, or a red "X" if any check(s) or test(s) fail.

Feedback on something like this would be appreciated, as I'm trying to become more active in the GitHub repos for osu! itself. Thanks :)

**Comment by peppy** [comment]
Scores are not displayed until they "pass" checks.
