### ISSUE TITLE
Can't look at certain parts of the ranking graph on specific profiles

### ISSUE THREAD

**Issue by KevKjef** [ppy/osu-web#6179]
Trying to look at certain days on the ranking graph(s) of certain user isn't possible. Your 'dot' snaps to the closest part of the graph you can look at.
![graph1](https://user-images.githubusercontent.com/64087607/84588496-3afff800-ae28-11ea-8a85-01607ea69e05.PNG)
![graph2](https://user-images.githubusercontent.com/64087607/84588497-3b988e80-ae28-11ea-863b-187906b1c1c2.PNG)
The pictures above show which part of the graph your 'dot' snaps onto.
It is not possible to look at the graph between 9-29 days ago and between 45-53 days ago
This happens on -Shyna-'s profile (https://osu.ppy.sh/users/7504653/fruits) and occurs on the graphs of all modes. their are two of these 'gaps' in catch and mania and one in both standard and taiko.
This issue might have something to do with players who just got unrestricted, which can mess up their graph.
This is the only profile I know of, which has this issue, but other players said they experience(d) the same thing on different profiles.

**Comment by peppy** [comment]
This is intentional and correct. The data for the specified period is missing.
