### ISSUE TITLE
Map preview on beatmap page

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#6181]
Currently it's not possible to know the contents of the map without downloading and checking it out in osu!. If you are looking for specific maps or just something interesting, it's inconvenient to have to mass download maps to check them out only to then delete most of them. This is especially true if you are looking for something good in the graveyard listings. This also applies to rank or loved if you do not know what to expect going in.

**Comment by peppy** [comment]
You mean a visual preview? I don't foresee this being a thing on the web (ever) but may be a thing in lazer.

**Comment by abraker95** [comment]
Yea, a visual preview. Since there is a browser extension does this I figured it shouldn't be too much if there was official support for this. So it's better to request this on osu!lazer issues then?

**Comment by lmnyx** [comment]
I don't thing it could fit the web very well. There is not much place where you can place it **nicely**.

**Comment by peppy** [comment]
if the browser extension author is willing to package it in a way we can use I guess it could be considered. Otherwise I'd recommend continuing to use the browser extension if it's already working for you.

**Comment by abraker95** [comment]
Maybe have buttons allowing to change between description and preview.

A very rough edit:

![](https://i.imgur.com/PJilulC.png)
