### ISSUE TITLE
Last active/last seen option.

### ISSUE THREAD

**Issue by jorgen779** [ppy/osu-web#6182]
An option to update "last seen/last active" status only when the osu game client is open, so that opening the osu webpage doesn't update it.

**Comment by peppy** [comment]
Accessing the website is interacting with the game. I'm not sure why it shouldn't count.

**Comment by jorgen779** [comment]
I don't see checking scoreboards, checking new map releases or just opening the site in general for less than a minute as enough interaction to warrant an update to it (going from my own usage). Things that would be enough interaction would be posting on forum threads, modding and using the new chat feature.

**Comment by peppy** [comment]
Could you please state the use case? You don't want others to know you are checking scores?

**Comment by jorgen779** [comment]
The way the old site functioned with the last active feature, I used to use it to measure the gaps between session, this was useful for trying to be more consistent in playing and improving in osu, the other niche is seeing if people who quit or play infrequently are actually playing the game or just had the site open.

**Comment by peppy** [comment]
You can check last play date by looking at the play graph. The old site also records last active when navigating the site, FWIW.

I don't think this is something we want, especially as the game and site get more and more integrated with each other.
