### ISSUE TITLE
ScoreV2 plays are not shown as +Scorev2 in recent plays

### ISSUE THREAD

**Issue by KevKjef** [ppy/osu-web#6186]
Not fully sure if this belongs here, but playing a (ranked) map with ScoreV2 submits the score (as of sometime ago).
Because of this your score(s) will also show up under your recent plays, however there is no icon to indicate the score was using ScoreV2.

Here you can see two scores I submitted with ScoreV2 on a short map to illustrate this:
![screenshot135](https://user-images.githubusercontent.com/64087607/84656467-061c9f80-af13-11ea-8938-138d3e427d12.jpg)
And here you can see how my recent plays have no indication that this would be a ScoreV2 play, besides the play not being worth any PP (but there can be a different reason for this):
![recentsv2](https://user-images.githubusercontent.com/64087607/84656472-09b02680-af13-11ea-8d3b-046ceb3c88a3.PNG)
Because there is no indication of ScoreV2, it can be easy to confuse these scores with 'normal' scores.

Something else to mention, related to ScoreV2 plays submitting, is that there is no icon for ScoreV2.
![Scorev2missingicon](https://user-images.githubusercontent.com/64087607/84656910-c0140b80-af13-11ea-8267-24d048c7844d.PNG)
If someone has osuplus installed and looks at recent, the mods you played with are 'bumped' one icon to the left (as seen in the picture above).

It would be nice if a ScoreV2 icon could be added, both to make the recent plays section less confusing and fill up the missing texture.

**Comment by peppy** [comment]
This is a limitation with storage of mods currently. I hope to eventually resolve this but it may take a bit longer due to the nature of database migration.

**Comment by aticie** [comment]
Any updates on this?

**Comment by nanaya** [comment]
It looks like the main thing that's missing is the icon design. Apparently there's a whole set of new design for it? Not sure if done though.

**Comment by peppy** [comment]
if it's just the icon, let's come up with something temporary and get it displaying. @arflyte can we just whack "sv2" or just "v2" in one of the old mod icons to get this ball rolling?

**Comment by arflyte** [comment]
yeah, let's go with "v2".

**Comment by peppy** [comment]
Are you able to provide the graphic? :)

**Comment by arflyte** [comment]
Wait I thought we already had the "v2" mod graphic. I'll get to it.

**Comment by aticie** [comment]
> It looks like the main thing that's missing is the icon design. Apparently there's a whole set of new design for it? Not sure if done though.

Also, the API won't return v2 scores. Tried with these endpoints:

https://osu.ppy.sh/docs/index.html#get-user-scores
https://github.com/ppy/osu-api/wiki#apiget_user_recent

Neither returns v2 scores. As a side effect, submitted v2 scores aren't being shown on the website as well. 

![image](https://user-images.githubusercontent.com/25616662/111622935-d4669b00-87fa-11eb-839b-0e9d645d1ed4.png)

**Comment by nanaya** [comment]
Probably this https://github.com/ppy/osu-stable-issues/issues/559

**Comment by peppy** [comment]
@aticie please open an issue on the linked repository and reference this one. i'm not sure if we will get it fixed in the near future (as it's just adding more variables to the mix while we are trying to move forward with large infrastructure changes) but having this documented would be beneficial.

**Comment by aticie** [comment]
![image](https://user-images.githubusercontent.com/25616662/111748210-48f41500-88a1-11eb-9025-41c4542850e9.png)

**Comment by peppy** [comment]
I was proposing making a *new* issue. The one you linked was already resolved (if you read closely my response was one which was the result of reverting a previous change).

**Comment by peppy** [comment]
Is this.. still waiting on an icon?

**Comment by nanaya** [comment]
hi @arflyte please export the icon somewhere

**Comment by arflyte** [comment]
Gah, I missed this. The mod situation was and is still a lil bit messy now because it's in the middle of a design transition. I'll sort this out today first priority.

**Comment by arflyte** [comment]
@nanaya uploaded to the repo. It might be tiny slightly off a bit, but we'll go with it for now. Different versions of photoshops exports in a weird funky way.

I need to look into the whole mod icon situation in-depth again.

**Comment by nanaya** [comment]
@arflyte it seems to be missing drop shadow
