### ISSUE TITLE
Inconsistent image for "wisp x" medal across web and client

### ISSUE THREAD

**Issue by ChromaBlast** [ppy/osu-web#6188]
![image](https://user-images.githubusercontent.com/47886244/84679285-0758c700-af29-11ea-8930-7a82adee6010.png)

Not much else to say except what's in the title.

**Comment by peppy** [comment]
@Ephemeralis leaving this in your capable hands

**Comment by Ephemeralis** [comment]
This was fixed a long while ago, never saw this until just now.
