### ISSUE TITLE
Locked accounts still appear in search results

### ISSUE THREAD

**Issue by KevKjef** [ppy/osu-web#6192]
Recently (I believe within last week) the pretty well known (presumed) multiaccounts Vernas and SkyDuDu got locked/restricted (I don't fully know/understand the difference)
While I don't know if there are different 'stages' of being locked/restricted I am confused as to why you are able to find these accounts in your search results, especially when they don't have a viewable profile anymore.
![vernas](https://user-images.githubusercontent.com/64087607/84765394-77218d00-afcf-11ea-8c9f-7175b25ee5f5.PNG)
![skydudu](https://user-images.githubusercontent.com/64087607/84765396-77ba2380-afcf-11ea-90f4-f4b67925e180.PNG)
The searches are shown above and clearly show them appearing in the list.
SkyDuDu's case is also quite odd since it even says 'user not found' above the results.
Clicking on their profiles, brings you to the usual 'user not found' page.

A couple days ago --kozima also got restricted/locked (most likely on the same day as Vernas and SkyDuDu?)
![kozima](https://user-images.githubusercontent.com/64087607/84766433-172be600-afd1-11ea-97e0-69deb7a0c251.PNG)
His account also shows up in search results as can be seen above.
Presumably there are more accounts like this that show similar behaviour, even though they don't have a viewable userpage, but these are the ones I am aware of.

Whatever the case is for these specific accounts, I don't see why these 'locked' accounts show up in your search results, especially since they don't have a visitable userpage anymore which I believe, means they are restricted/banned (or at least deemed a multiaccount/guilty of other things) and therefore should not be viewable amongst search results.

Either way, restricted/banned/locked users you friended before don't show up in your friends list anymore (as far as I am aware), so why would they show up here?

**Comment by lmnyx** [comment]
This isn't specific, for reason I don't know restricted users is showing in the search.
![E](https://user-images.githubusercontent.com/13962537/84771312-a4336700-aff2-11ea-8353-a5403ea7d8ab.png)

**Comment by KevKjef** [comment]
interesting, I tested it out with some banned/restricted players myself, but didn't get any search result for them. (venlas, -exdark, voyager of 1969 are the ones I tested)

**Comment by lmnyx** [comment]
I guess free'd names of banned users isn't in this list 
![r](https://user-images.githubusercontent.com/13962537/84772121-ef01ae80-aff3-11ea-9191-33160d8d04cd.png)

**Comment by Helen0903** [comment]
[shouldiblamecaching.com](https://shouldiblamecaching.com) 

I'm imagining the results are cached client-side or server-side (or most likely both)
Are there any cases of accounts that were restricted a long time ago that still show up?
And also if you clear your browser cache does that change anything?

I'm not too knowledgeable on the specifics of the osu website, but it's not much of a stretch to imagine search results are cached

**Comment by KevKjef** [comment]
That doesn't seem to be the case, voyager of 1969 is in use aswell as god_old_1 (who is also restricted/banned)
Also caching doesn't seem to matter.
I checked by using edge, which I have never used (so no cache) and they still show up in the search results

**Comment by lmnyx** [comment]
>  Are there any cases of accounts that were restricted a long time ago that still show up?
Yes. [GYZE - HONESTY](https://osu.ppy.sh/users/16982692) account is from Jul 2019 from [Beastroll's stream](https://www.youtube.com/watch?v=hsDILrDyNHU).

**Comment by lmnyx** [comment]
But to be honest, there is really not **all** showing up, like *Nara*, *burstlimit* (very old ones, 4 yrs iirc) I tried. Their name is still taken, but they're not showing up in the search.

**Comment by Helen0903** [comment]
Alyce & El vi Britannia don't show up (& are restricted)

Perhaps it has to do with

**Comment by peppy** [comment]
Should be resolved within the next hour. A permanent fix has also been deployed.
