### ISSUE TITLE
Translation dependent on gender

### ISSUE THREAD

**Issue by Phippe** [ppy/osu-web#6193]
[This translation](https://crowdin.com/translate/osu-web/16/en#10666) is dependent on the gender of ":type" in some languages. Using multiple demonstrative pronouns (like "dieser/dieses :type") looks bad. The simplest solution would be to just make this snippet translatable for each of the 3 cases for ":type".

**Comment by peppy** [comment]
Your link does not work. Also please state the language which is problematic in this case.

**Comment by lmnyx** [comment]
In [Russian](https://crowdin.com/translate/osu-web/16/en-ru#10666) translation of this node there is also an issue:
When using the "problem" and "praise" `this` should be "'эта", but with "suggestion" it'll be "это".
