### ISSUE TITLE
Option in beatmap sorting: Show only maps X* star rating

### ISSUE THREAD

**Issue by Yukari0** [ppy/osu-web#6194]
Maybe my new idea is hard to implement, but I want to try offer it.
Near the sorting, could be add a drop-down menu with the numbers of stars from 0 to 10. When player select this number, only those maps with X difficulty will be shown. For example, players who are just starting to play 5* maps will be much more comfortable and easier to find maps on which they can training and earn pp.

**Comment by cl8n** [comment]
already described in #5998 a bit

in the meantime you might be able to make use of the recommended filter https://osu.ppy.sh/beatmapsets?c=recommended , but sometimes it's not very accurate...
