### ISSUE TITLE
Navigation Header Design Update, Part 2: Quick Search

### ISSUE THREAD

**Issue by arflyte** [ppy/osu-web#620]
![](http://puu.sh/pJQW4/11e5c48a21.png)

Quick Search Panel, which is part of the new main navigation bar.

![](http://puu.sh/pJR2E/bcf17d0938.png)

The orange bar that underlined the page section title is now underlining the search box. The search box will go darker once activated.

The first 4 results are displayed in the box.

The result type (player, beatmap, etc) is displayed underneath the player result. Left-chevron appears on the right when hovered.

The fifth item will take the user to the search result page.

**Comment by nanaya** [comment]
the mythical search result page :+1:

**Comment by lunafreya** [comment]
Should we have to close this one already? A more better search has been implemented (#1259 plus some improvements).

**Comment by nanaya** [comment]
Indeed.
