### ISSUE TITLE
Degrading web chat performance when many chats open

### ISSUE THREAD

**Issue by Adrriii** [ppy/osu-web#6200]
Hi, since my account is also used as an irc-bot, I get messaged a lot. These messages can also end up in osu-web for some reason, and I have a decent amount (around 500).

While I imagine some might have considerably more, I'm still experiencing great performance issues with that amount of open discussions.

I will link to a video that I upload on the discord osu-web channel.

Here is the link : https://cdn.discordapp.com/attachments/188630616286167041/722810946447212554/kpTsxBUjTD.mp4

**Comment by notbakaneko** [comment]
@Adrriii are you using either Chrome or Edge?

**Comment by Adrriii** [comment]
This was on google chrome
I forgot to write my system details, sorry about that. Windows 10 as well. Hardware acceleration disabled on the browser.
