### ISSUE TITLE
Add a clear distinction for filter headers

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#6201]
![image](https://user-images.githubusercontent.com/19843905/84960900-3d51a300-b103-11ea-8a4e-44f23f88b18d.png)

Currently the filter headers `Variant` and `Show` blend into other filter options and it's not obvious which one is not the option.

**Comment by arflyte** [comment]
Still working on it. Working on Search headers which will be related to it.

**Comment by arflyte** [comment]
![Figma_200623-082849](https://user-images.githubusercontent.com/3632750/85344826-b9951d80-b52b-11ea-8633-600be7576333.png)

New filters, based on new beatmap filter designs.

**Comment by lmnyx** [comment]
Would be useful if it could be collapsed, because it looks just massive for me

**Comment by peppy** [comment]
Agree that it is quite big. Actual page content will be only about 25% of the screen on certain aspect ratio devices, which feels pretty weird.

**Comment by arflyte** [comment]
![Figma_200624-034527](https://user-images.githubusercontent.com/3632750/85444380-3af0bc80-b5cd-11ea-9d69-f975986f8417.png)

Tried a different layout, slightly different than beatmap filters (might need to update that one too). Less tall and compact.

**Comment by Gabixel** [comment]
So I guess that the filter in the beatmap discussions page needs a similar re-design:

![discussion](https://user-images.githubusercontent.com/43073074/85848799-156cda00-b7aa-11ea-8142-f835f12d99fb.png)

There's also this one in the friends page, but it's slightly different:

![friends](https://user-images.githubusercontent.com/43073074/85849234-e73bca00-b7aa-11ea-8b7c-150d43b49c51.png)

**Comment by gagahpangeran** [comment]
> ![Figma_200624-034527](https://user-images.githubusercontent.com/3632750/85444380-3af0bc80-b5cd-11ea-9d69-f975986f8417.png)
> 
> Tried a different layout, slightly different than beatmap filters (might need to update that one too). Less tall and compact.

I interested to implement this. Is this the final design?

**Comment by peppy** [comment]
I think that is a safe assumption

**Comment by notbakaneko** [comment]
@gagahpangeran are you working on this?

**Comment by gagahpangeran** [comment]
@notbakaneko still wip in my local, because I'm not sure If I should only change like the design (have a little hack) or modified the `Sort` component entirely (change the title position to top and the sort item at bottom). The last one will change all of `Sort` component in other page.
