### ISSUE TITLE
Disqualification/nomination reset message display does not shorten discussion post URLs

### ISSUE THREAD

**Issue by mcendu** [ppy/osu-web#6202]
Didn't screenshot that so giving the example in text.
The URL form overflows the screen on mobile devices.

Comment:
> DQ to fix #1645432 ...

DQ message:
> DQ to fix https://osu.ppy.sh/beatmapsets/1124745/discussion/-/generalAll#/1645432 ...

**Comment by notbakaneko** [comment]
I think this was fixed in one of the parser updates.
