### ISSUE TITLE
Buy supporter slider can lead to confusion on the end user

### ISSUE THREAD

**Issue by insomnyawolf** [ppy/osu-web#6206]
When buying supporter, you can move the slider and add more money without changing the month number like in the following image.

![image](https://user-images.githubusercontent.com/18150917/85044600-23a96d80-b18e-11ea-9de7-7272eb383b2f.png)

Some of my friends actually bought supporter without knowing that and paid some extra fore it by accident.

I would propose to add a warning or a higher visible message that warn you about that so the users that want to give some extra money still can do it but the ones that doesn't want/can pay the extra money would be able to notice it easier, something like this:

![image](https://user-images.githubusercontent.com/18150917/85045986-10979d00-b190-11ea-9323-9d2b55ef697c.png)

**Comment by Helen0903** [comment]
If there's no increase in time between $4 and $7, I'd suggest to just have the slider snap to months of supporter rather than monetary units.

Maybe add an extra box or slider, where you can choose to donate more on top of the supporter cost? This way people can't really accidentally pay more than necessary, but can still donate more if they want to

**Comment by insomnyawolf** [comment]
I think in the same way but i have hear it's the intended behavior:
```That’s intended, you can pay however much or little you want between each bracket```
that's why i suggest the warning instead

**Comment by peppy** [comment]
This is intended. Pay whatever you want. The months is a bonus.

**Comment by insomnyawolf** [comment]
You should be warning the users anyways

**Comment by peppy** [comment]
Thanks for your opinion. If someone is offended to the point they are offended they can contact me at pe@ppy.sh and request a refund.

Supporting the game is not intended to be a subscription.
