### ISSUE TITLE
Add medals for 9 and 10 star pass and FC

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#6208]
in osu!standard there are already 9\* FCs, and [Merami almost got a 10\* FC yesterday](https://www.reddit.com/r/osugame/comments/hb2czq/merami_the_oral_cigarettes_mou_ii_kai_rain_hdnc/)

**Comment by nMM456** [comment]
I also want to propose an SS medal being added for each star range. I made a quick example of what a medal could look like in paint.
![osu-skill-fc-7@2x](https://user-images.githubusercontent.com/20979830/85090680-b8729200-b1b3-11ea-87aa-72fd6e80c86d.png)

**Comment by Ephemeralis** [comment]
Four new medals are now live, reflecting 9/10* passes and FCs respectively.

Anyone who's qualified for one of these medals in the past will need to do it again in order to attain the medal.
