### ISSUE TITLE
Navigation Header Design Update, Part 3: Quick Profile

### ISSUE THREAD

**Issue by arflyte** [ppy/osu-web#621]
## Quick Profile

This is the new Quick Profile panel is which part of the new Main Navigation bar. It's accessible via clicking the player's name or avatar. Wipe transition from the right (will be detailed in the future).

![](http://puu.sh/pJWmo/c28342bb88.png)

The page section title yellow underline now underlines the player's name. Yellow border on player's avatar.

The navbox is split into 3 sections: from the right, quick shortcuts, player's basic details, and spaaaaaace. The background of the navbox is the player's cover with black overlay at 50% opacity.

The quick shortcut is pretty self-explanatory. The background is solid #222. List of items in orange and bolded white with right-chevron on the left when hovered.

Player details area. Player's name followed by player's achievements title, country flag and team's banner. Underneath all that is the online status for friends and teammates. The background is black 50% opacity.

Clicking the player name will take the user to their public profile page (player's title not clickable for now). Clicking the online users will take them to their friend's page or team page.

The content and design of this area is not final.

![](http://puu.sh/pJSND/a84f15ef7a.png)
### Login

![](http://puu.sh/pJW1Q/9083361438.png)

This is how the quick profile looks like when user's not logged in, with generic purple avatar.

![](http://puu.sh/pJVZY/e7ab64780c.png)

Title on the top, followed by instruction text (ignore the placeholder for now).

2 input boxes for user's email address (it will work if player's name used) and password.

![](http://puu.sh/pJXti/a568a56b3a.png)

The instruction text displays error if there's an error.
### Register

![](http://puu.sh/pJW2O/22935e6dfe.png)

Next to the login section is the registration section, that simply takes the user to the registration page if they do not have an account. There will be no "quick and fast" registration. Please ignore the place holder texts.

**Comment by iamanai** [comment]
I know next to nothing about PHP or even how osu-web functions (I've been trying to figure it out, but to no avail). Is there still some way I could help move this project forward?

**Comment by nekodex** [comment]
I believe this is mostly done now, the only things missing are Friends+Teams info.

**Comment by TPGPL** [comment]
should be closed probably as the design for the header changed

**Comment by peppy** [comment]
Yep, closing this for now.
