### ISSUE TITLE
country rank without supporter

### ISSUE THREAD

**Issue by MyAzr** [ppy/osu-web#6213]
Suppose someone buys a supporter to view a place in the country. BUT, why when he can go to the Web site to look at the top score and see where he is in the country.
![Opera-2020-06-20-144915-osu-ppy-sh](https://user-images.githubusercontent.com/67195203/85203399-65bde500-b32f-11ea-8f2c-5c81174072e9.png)

**Comment by MyAzr** [comment]
https://osu.ppy.sh/community/forums/topics/1091799?start=7521546

**Comment by Mia0013** [comment]
Supporter gives access to the country's leaderboards on maps, not just the rank on the map.

**Comment by MyAzr** [comment]
> Supporter gives access to the country's leaderboards on maps, not just the rank on the map.

I mean u can see country rank without supporter

**Comment by peppy** [comment]
This is intentional.

**Comment by Mia0013** [comment]
I don't see how it is a problem, supporter gives more functionality than just the rank either way.

**Comment by MyAzr** [comment]
> This is intentional.

Oh. Ok
