### ISSUE TITLE
Text after a spoiler box spam won't draw.

### ISSUE THREAD

**Issue by superyor** [ppy/osu-web#6217]
When spamming the spoiler box alot of times, any text after it won't be drawn.
I found this bug in [my own forum game](https://osu.ppy.sh/community/forums/topics/1081168?start=unread), it's a game where the people have to create the longest quote chain, some people spammed boxes to troll and then we/I found this bug.
After 5 minutes of testing, I found out it was the boxes.

Here's an example BBCode:
`[box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][box=][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box][/box]
Hey! You won't be able to see this!`

It looks like this:
![Image of the bug](https://i.imgur.com/ZjslPWC.png)

I tested it on my profile in the "Me!" section, it work's there aswell.
As it seems, it only happens after a specific amount of boxes, I don't know after how many though.

**Comment by lmnyx** [comment]
Looks like #5987

**Comment by nanaya** [comment]
It hit the default nesting limit in library used. Unless there's a legitimate use for it I don't see this needs changing.

**Comment by cl8n** [comment]
I think it should at least fail to post, instead of silently deleting part of it

**Comment by peppy** [comment]
Agree it should probably hard fail if that's something we can easily do.

**Comment by nanaya** [comment]
I don't see the library emitting warning or anything on that.

**Comment by peppy** [comment]
In that case let's just close this one. It seems like a super super edge case (where the user is likely trying to abuse the formatting elements).
