### ISSUE TITLE
Pinnable timeshift rooms

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-web#6226]
With the upcoming spotlights, it would be nice to have the ability to pin timeshift rooms to the top of the listing. This should probably just be a database flag that's returned via the `/rooms` endpoint.

**Comment by peppy** [comment]
Rather than just a pin flag, should probably be a category, with initial categories being (Normal, Tournament, Pinned).

I'd foresee us having tabs for each in the client, and probably a separate request per category fetch.

**Comment by notbakaneko** [comment]
Room can only be in one category at a time, right?

**Comment by peppy** [comment]
Yep, sounds fine for now.

**Comment by smoogipoo** [comment]
To start off they could one category. Maybe later it'd be nice to have a sort of grid of "tags" instead that you can choose a subset  of, similar to super mario maker?

![image](https://user-images.githubusercontent.com/1329837/86587944-a53e2f80-bfc5-11ea-9b0d-f448d7165e95.png)

**Comment by peppy** [comment]
I don't think that's the goal here. It should be specifically used for system defined types. They should not collide (ie. you don't have a [spotlight] [tournament]).

Tagging can be done via a tag or title field.
