### ISSUE TITLE
Kudosu ranking page on the new website

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#6228]
https://osu.ppy.sh/p/kudosu

This page exists and has yet to be ported to the new website in any form, it's quite cool to look at and can give modders a small goal to be proud of as an overall sign of their experience/progress. It would be a loss to see it go away entirely when the old site is decommissioned, and it could do well to have a new website page with some additions. The issue it currently has is that it is not very dynamic.

This page would be most useful with monthly and weekly leaderboards, in addition to an all-time one like the current page. Weekly could possibly be the default. Besides being a cool thing for modders to check out, this would be very useful for mappers as well - it could allow them to find out what modders are currently active in the community, giving them some idea of potential people to reach out to for feedback! Having weekly/monthly options would be much more dynamic than just one all-time ranking as well.

Since it's a rankings page, the design could be done similarly to the performance ranking page, just with the appropriate columns.

**Comment by peppy** [comment]
The whole kudosu system is planned to get a rework (you can see many issues vaguely tracking this [here](https://github.com/ppy/osu-web/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+kudosu)). Whether a leaderboard will come with it has yet to be decided, but the leaderboard as it currently exists definitely won't be coming across.

**Comment by peppy** [comment]
Apparently this is something people want to see, but in its original state it's mostly a static page. Would be interested in more insight as to why it should be transferred across, or any changes (such as making it based on only the last month) to make it more dynamic.
