### ISSUE TITLE
Web incorrect star rating display after beatmap update

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#6234]
may be related to https://github.com/ppy/osu-web/issues/6132 

A user reported to me that https://osu.ppy.sh/beatmapsets/1173976#osu/2477122 before updating this map, in-game and on website the star ratings matched. After updating, the website star ratings changed to incorrect values - even though the in-game ones had not changed at all.

these values are at time of writing, which is 30 minutes since the map update. (edit: it's still like this after over 6 hours)
in-game: 2.18-3.1-4.32-5.45
website : 2.16-2.98-4.26-4.98

the discrepancy is minor on the Normal Hard and Insane difficulties, but significant for the Expert to the point it has the wrong color of difficulty icon.

Even if this is done asynchronously, the expected behavior on a user's end would be for the star ratings to stay at what it was on the previous update until the calculation is finished and the star rating is updated correctly, **not** to change to something incorrect for half an hour or more. 

So please take a look at 
-> not changing the displayed SR on the website at all until the calculations are **done**. Why should it change to something incorrect in the meantime? This only confuses users updating their maps.
-> Put a small notice on the beatmap page that the SR is recalculating after the update, so people know this is the case.

**Comment by peppy** [comment]
Thanks for reporting this! It turns out that with some infrastructure changes, the newer difficulty calculator was running too fast, being overwritten by legacy values. This has been resolved now.

**Comment by yeetodorito69420** [comment]
peppy, it's still happening in update b20210920

**Comment by peppy** [comment]
Please provide full details and logs and screenshots of what you are seeing.
