### ISSUE TITLE
Web is not correctly parsing visible unicode metadata on recently updated beatmaps

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#6245]
In the past day, mapsets uploaded or updated with unicode metadata in their source or tags does not have it correctly parsed on the website. This was working correctly up until now, and the maps have nothing unusual with their unicode metadata either. It appears to be entirely a website-end issue

This appears to be an issue for: the source field, and unicode characters at the beginning of the tags field.  Unicode tags in the middle or end of the tags field are parsing correctly, such as https://osu.ppy.sh/beatmapsets/1167283#taiko/2434856 .

Examples of maps with the issue:
https://osu.ppy.sh/beatmapsets/1201879#osu/2503124 Visible in the first tags.
https://osu.ppy.sh/beatmapsets/1186095#osu/2472187 Visible in the first tags.
https://osu.ppy.sh/beatmapsets/1142363#osu/2385733 Visible in the source field. For this specific case, you can also see ranked maps where the same source field is parsed correctly such as https://osu.ppy.sh/beatmapsets/781509 
https://osu.ppy.sh/beatmapsets/1109617#osu/2318822 Visible in the source field. 

The beatmaps themselves are not affected and will be correctly displayed/parsed in-game and in their files, confirming this to be specifically a web issue.

**Comment by peppy** [comment]
Please try updating again now.

**Comment by hypercyte** [comment]
Just updated [my map](https://osu.ppy.sh/beatmapsets/1201879#osu/2503124) and it's fixed now! 👍

**Comment by peppy** [comment]
Thanks

**Comment by dorothy3242** [comment]
This is really weird, hypercyte's map was fixed on update but other people are still having the problem with maps updated _just now_

https://osu.ppy.sh/beatmapsets/1200493#taiko/2499995

**Comment by peppy** [comment]
yes, disqualify to fix.
