### ISSUE TITLE
Tidy up page metadata for better discord display

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#6251]
Two points:

- Currently there is a huge empty space in page preview titles (not sure why this happens):

![image](https://user-images.githubusercontent.com/191335/86206707-f904df00-bba7-11ea-852b-baf4e36a142d.png)

- User links' preview text sounds really bad and doesn't really help with clarity:

![image](https://user-images.githubusercontent.com/191335/86206741-0c17af00-bba8-11ea-8d7d-0952b823ae79.png)

Proposal: change to match beatmaps page (`osu! » users » egg and cheese`)

**Comment by Repflez** [comment]
The extra whitespace is caused by 4aa0c7e8ffba1a5a08ec475a5ec6b5bf190a0b76, fwiw:
![image](https://user-images.githubusercontent.com/659133/86211095-03d15c80-bb33-11ea-8795-cc3d68f564ea.png)
