### ISSUE TITLE
Middle mouse btn into New reply window

### ISSUE THREAD

**Issue by B0und** [ppy/osu-web#6256]
When I press middle mouse button inside New reply window and move mouse up/down a bit, the reply window gets stuck and covers half of the forum view. Reloading the page with f5 doesnt solve the problem.
Im using firefox 78.0.1 if that matters.

**Comment by nanaya** [comment]
Middle clicking text box focuses it (and thus triggers the sticking of reply box). Considering that's the default behavior in many places, not allowing autoscroll when middle clicking text box instead seems to make more sense?

**Comment by nanaya** [comment]
Not sure if want to change default browser behavior so closing this unless there's some good reason to override this.
