### ISSUE TITLE
Problem with recent 4k Mania Leaderboard

### ISSUE THREAD

**Issue by xKibitz** [ppy/osu-web#6257]
Hi, this may seem like a minor issue but as a competitive player this affects me quite a little.

So firstly, I am currently rank 644 with 8993 TOTAL PP. However it shows that I am rank #172 on the 4K leaderboard. However when I go to the 4k leaderboards, it shows that I only have 8914PP. I have never played more than 1 star on 7k so this is very confusing to me when I should actually be #154 on the leaderboard. I will provide some screenshots down below. Hope the issue will be fixed :D.

Profile + Rank: 
![image](https://user-images.githubusercontent.com/67725177/86316954-48b7d900-bc82-11ea-841f-8a1d1a836e82.png)

Fake Rank On 4K Leaderboard:
![image](https://user-images.githubusercontent.com/67725177/86316990-61c08a00-bc82-11ea-9726-d61c70585bb9.png)

Thank You,
Kibitz

**Comment by peppy** [comment]
I've checked your totals and they are correct. The difference you point to is that the key specific charts do *not include converts*. Hopefully this is understandable!

**Comment by xKibitz** [comment]
Sorry but I have to ask, what map do I lose over 80 Raw PP from?? Please tell me as this limits me by a huge amount.

**Comment by peppy** [comment]
Some mania beatmaps were automatically "converted" from osu! ruleset. Any plays on these beatmaps are not included towards your total. Only beatmaps of [osu!mania difficulty category](https://osu.ppy.sh/beatmapsets?m=3) are included in the 4k/7k totals.

**Comment by xKibitz** [comment]
I don't believe i earned 80 Raw PP from playing converted maps, because all I do when playing converts are farming SS etc. Is there really no way to check how i lose that PP? Sorry for annoying you with this trivial matter btw.

**Comment by nanaya** [comment]
btw you can also view your 4k pp by hovering the total pp on your profile page

![](https://s.myconan.net/2020-07/firefox_2020-07-03_15-32-21.png)

**Comment by xKibitz** [comment]
> btw you can also view your 4k pp by hovering the total pp on your profile page
> 
> ![](https://camo.githubusercontent.com/bf6ce2e97755ed00e0d55e28bffda2d54b8fcf5a/68747470733a2f2f732e6d79636f6e616e2e6e65742f323032302d30372f66697265666f785f323032302d30372d30335f31352d33322d32312e706e67)

yes i'm aware of that but my question is why it is 8915 instead of 8993 when i only play 4k

**Comment by peppy** [comment]
You have.

```
| beatmap_id | pp       |
|------------|----------|
| 1413113    | 104.579  |
| 1994839    |  95.7318 |
| 1101627    |  83.2137 |
| 1092970    |  80.7752 |
| 1385532    |  73.1997 |
| 808983     |  73.0246 |
| 391204     |  72.6111 |
| 1733039    |  70.5997 |
| 1733039    |  70.523  |
| 1733039    |  69.6244 |
```

```
non-weighted sum of pp from converts

| sum(pp)           |
|-------------------|
| 68863.83686825633 |
```
