### ISSUE TITLE
Search breaks when searching for a user's post

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#6261]
Replication steps:

1. Go to [search page to search through Serraionga's posts](https://osu.ppy.sh/users/5176679/posts?query=spaghetti&forum_id=) 
2. It breaks when searching for anything, but let's use "test"
3. Tick the "include subforums" check mark and hit search
4. You get the following error:
![](https://i.imgur.com/AO19BsP.png)

**Comment by lmnyx** [comment]
I guess fixed already? Doesn't happen to me.

**Comment by abraker95** [comment]
Yup, doesn't happen anymore. Closing.
