### ISSUE TITLE
User's should be able to search for wiki articles without signing in

### ISSUE THREAD

**Issue by paper-toaster** [ppy/osu-web#6265]
**After attempting to bring up this discussion in the #osu-wiki Discord channel, I was told to open an issue here.**

Being a lowly wiki janitor and stub writer, I tend to search for stubs and pages for linking quite a bit. And because I keep my cookies off most of the time, I end up attempting to search for an article on the wiki without being signed in. And I've begun to wonder why it's neccessary to require user's to sign in to an osu! account in order to search for articles.

The fact that you are *required* to have, and be signed into, an osu! account to be able search for articles makes no sense considering that you can already view the articles signed out if you have the link to them. And as a huge supporter of online communities, this choice seems very counter intuitive and would probably discourage researchers and newcomers from actually getting into/learning more about osu!, which wikis are kinda supposed to do.

Thus I am opening this issue to see some sort of discussion spring up, and to try to get an answer to this question, if not remove the requirement entirely.

**Comment by peppy** [comment]
https://osu.ppy.sh/help/wiki/Main_Page i can search without being logged in?

**Comment by paper-toaster** [comment]
@peppy the main page works fine, but from the home page, it requires you to be signed in. And it's reasonable to assume that most newcomers/researchers would search from this page

**Comment by peppy** [comment]
This is being changed in #6266. Should clear things up.
