### ISSUE TITLE
Spotlight display page should pull from timeshift lobbies

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#6270]
Future spotlights look to be using timeshift.

Continuing from https://github.com/ppy/osu-web/issues/6226, the charts display page needs to show spotlights coming from the new sources. The display should be exactly how the [current charts/spotlights page](https://osu.ppy.sh/rankings/osu/charts) is, with the dropdown being sourced from the pinned/categorised timeshift rooms.

Any data not available from timeshift (ie. rank counts) can be omitted.

Fine to implement as a v2 page or however is easiest.

**Comment by nanaya** [comment]
Added in #6279.
