### ISSUE TITLE
Do not send/store messages from banchobot

### ISSUE THREAD

**Issue by lmnyx** [ppy/osu-web#6276]
![e](https://user-images.githubusercontent.com/13962537/86811265-24e7ff00-c097-11ea-9aae-89a4cd68436b.png)

**Comment by peppy** [comment]
They will get cleared when you read them, or dismiss them.

**Comment by lmnyx** [comment]
i mean don't send at all on the web
![i](https://user-images.githubusercontent.com/13962537/86817339-57e1c100-c09e-11ea-8f5f-3b8af3cf88c5.png)

**Comment by peppy** [comment]
the intention is for the web to reflect chat 1:1. bancho commands should still be usable.
