### ISSUE TITLE
Allow longer Beatmap title prefix searches

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#6284]
https://osu.ppy.sh/beatmapsets?q=dadadadada should match https://osu.ppy.sh/beatmapsets/350076#fruits/771879

We should be wildcard searching each search word to some degree.

**Comment by notbakaneko** [comment]
This was already added #4294

It's currently limited to a maximum run length of 8 characters per term for performance and index size reasons.
`https://osu.ppy.sh/beatmapsets?q=dadadada` will work but `https://osu.ppy.sh/beatmapsets?q=dadadadada` will not.

**Comment by peppy** [comment]
how does it affect performance if the term is longer?

**Comment by notbakaneko** [comment]
It's mostly going to be size and the associated costs of a larger index.

Although, it may not actually be too much on an issue here, since there's additional tokenization already being applied that generally removes the less useful edge_ngrams from being stored.

**Comment by gagahpangeran** [comment]
This issue still persist :/

![image](https://user-images.githubusercontent.com/4964985/89613435-680edb00-d8ac-11ea-8254-3fa28467774c.png)

**Comment by notbakaneko** [comment]
It's fixed now
