### ISSUE TITLE
Old changelog entries are unavailable

### ISSUE THREAD

**Issue by Pennek** [ppy/osu-web#6292]
As part of writing osu!wiki articles, I am searching through the changelog for feature implementation dates and similar stuff. Since the old changelog has been nuked, it is impossible to see entries prior to [this release](https://osu.ppy.sh/home/changelog/cuttingedge/-26) (August 2014).

If we could bring entries from the old changelog back in some form (either as a temporary or updated solution) it would make my work a whole lot easier

**Comment by cl8n** [comment]
idk what happened to the years in between but the oldest changelogs were done via forum https://osu.ppy.sh/community/forums/topics/15

**Comment by Pennek** [comment]
To my understanding, from 2010 and onward they were published via an RSS-feed to the old changelog listing which has now been nuked

**Comment by peppy** [comment]
the link above doesn't seem to work for me. can you include a screenshot of the "oldest build" yore seeing?

**Comment by Pennek** [comment]
Screenshot: 
![image](https://user-images.githubusercontent.com/20502902/87213085-92f42680-c322-11ea-955a-8990eba8c1a7.png)

**Comment by peppy** [comment]
What was the last build you got to which wasn't "weird"?

**Comment by Pennek** [comment]
Cutting Edge 20140903
https://osu.ppy.sh/home/changelog/cuttingedge/20140903

**Comment by peppy** [comment]
Can't guarantee when but I will look into this at some point.

**Comment by pishifat** [comment]
as a temporary solution, here's [a pdf of changelogs from august 2008 to may 2017](https://github.com/ppy/osu-web/files/4915516/changelog.pdf)

**Comment by peppy** [comment]
Out of curiosity where did you source that from? May help figure the issue.

**Comment by pishifat** [comment]
i had it saved from a while ago so can't help there :(

**Comment by CrazyCSIW6** [comment]
[changelog.txt](https://github.com/ppy/osu-web/files/7270768/changelog.txt)
Changelog containing entries from July 4th, 2007 to November 6th, 2008.

**Comment by CrazyCSIW6** [comment]
Changelog text document containing entries from September 16th, 2007 (beta release) to November 7th, 2008 (shortly after osu!catch was added).
Hopefully with this and the PDF combined all of the changelog entries can be restored.
[changelog-rls.txt](https://github.com/ppy/osu-web/files/7270807/changelog-rls.txt)

**Comment by peppy** [comment]
@CrazyCSIW6 please stop posting in this thread.

**Comment by peppy** [comment]
Very late reply here, but this should now be fixed. I've gone through and mangled all available data in the database to be displayed back to `build_id` 1. Note that most of the new data is in either cutting edge (around half a years worth) or stable-fallback (2 years worth).

Comments also seem to be preserved, so that's cool.
