### ISSUE TITLE
New spotlight leader board (seemingly) randomly changes leader board position of users with identical score

### ISSUE THREAD

**Issue by KinglingOS** [ppy/osu-web#6293]
When two players have identical scores, they change leader board place seemingly randomly. Not sure why this happens.

[Here](https://imgur.com/gallery/vjSwylP) is an imgur album showing me and idealism changing leaderboard position, despite neither of us setting a score.

Afaik there is no lazer version/log for this.

**Comment by peppy** [comment]
To fix this, we need a score_updated_at storage in the room totals.
