### ISSUE TITLE
Timeshift lobby leaderboards can not be accessed in their entirety.

### ISSUE THREAD

**Issue by Loctav** [ppy/osu-web#6294]
Right now, web interface, in-game interface and API calls only return the top 50 leaderboard items of a timeshift multiplayer lobby. Same goes for individual map leaderboards within a timeshift lobby (only the top 50 items on a playlist beatmap can be retrieved at most).

I have been told that there should be some kind of pagination, but neither the web interface nor the in-game interface offers that. Accessing the scores via the API neither allows me to retrieve more than 50 scores per timeshift lobby or beatmap via pagination methods, because there is currently no documented way on how to even "turn over" the pages.

Accessing this information in its entirety is crucial to calculate the Seasonal Leaderboards for Beatmap Spotlights. Ideally, this information is made available via the osu! API.

**Comment by nanaya** [comment]
For api `/rooms/{room}/leaderboard` endpoint, there's `page` parameter.
