### ISSUE TITLE
wiki section link only scrolls down when opened in a new tab

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#6295]
the "Captain's Pick" link in the first bullet at the bottom of [this page](https://osu.ppy.sh/help/wiki/People/The_Team/Project_Loved_Team#trivia) only works right if I open it in a new tab. if I open in same tab, the "History of Loved" page opens but my view doesn't scroll down to see the linked section. using Chrome v83.0.4103.116 on Windows 10

this is the only link I've seen behave like this so I feel like it's something to do with the characters being used

**Comment by gagahpangeran** [comment]
Can confirm on firefox 79 developer ver and firefox android 68.10.1.

After some observation, if you turn off javascript in your browser, it behaves as usual.
