### ISSUE TITLE
Setting the Category In Beatmap Listing to "Any" or "Favourites" only allows user to sort by Ranked Date, not Updated Date

### ISSUE THREAD

**Issue by Hydria** [ppy/osu-web#6307]
Whilst having search limited to "Ranked" makes sense for "Has Leaderboard", "Ranked", "Qualified", and "Loved" categories, considering that "Any" and "Favourites" also contain unranked maps, limiting the search to Ranked Date stops the user from seeing the true order of all map updates and forces priority of ranked maps on top, so should be changed to "Updated" similar to Pending/Graveyard categories.
![BeFfNra](https://user-images.githubusercontent.com/13346079/87451162-66c4f800-c5f7-11ea-94f5-f010b30e6c66.png)
![m7krI9Q](https://user-images.githubusercontent.com/13346079/87451173-6a587f00-c5f7-11ea-9526-c2d660110236.png)
![0PS61MJ](https://user-images.githubusercontent.com/13346079/87451177-6d536f80-c5f7-11ea-9ac7-3283baa63f88.png)

**Comment by peppy** [comment]
Are you saying that even though you favourited a WIP map, it won't show up in your favourites?

**Comment by Hydria** [comment]
My bad, I've edited the original post now, though the main concern still stands where a user cannot see a recently updated map sitting in pending without scrolling through all ranked/qualified/loved maps first for Any / Favourites categories.

**Comment by peppy** [comment]
So really we should be showing the "Updated" sort mode in such cases, not "Ranked". Or maybe both where it applies/

**Comment by Hydria** [comment]
Both works and allows for more flexible searching for the user.
