### ISSUE TITLE
Searching for beatmaps using client_credentials ignores query params

### ISSUE THREAD

**Issue by aspriddell** [ppy/osu-web#6314]
When using the new `client_credentials` grant, a request to `/api/v2/beatmapsets/search?q=adamas` will return the same result as `/api/v2/beatmapsets/`. Using a normal user authenticated token works normally. (links below are screenshots)

[Using a `client_credentials` token (returns the "frontpage" response)](https://user-images.githubusercontent.com/10289119/87533588-c0c3cd00-c68c-11ea-9639-2d4a5a3efc1e.png)
[Using a `authentication_code` token (returns the expected search results)](https://user-images.githubusercontent.com/10289119/87533536-ac7fd000-c68c-11ea-9cae-62acb187e009.png)

**Comment by notbakaneko** [comment]
Guest users cannot search.
Requests using `client_credentials` are explicitly considered guest users.

**Comment by aspriddell** [comment]
Ah, fair enough. Might be worth noting in the documentation  (when it's updated next) for other people facing the same issue.

**Comment by nanaya** [comment]
Should probably make exception for api access

**Comment by peppy** [comment]
Definitely should be an exception. For checks which only require `is_authenticated` client grant should still work.
