### ISSUE TITLE
Dates are shortened in too many places

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-web#6315]
![image](https://user-images.githubusercontent.com/1329837/87560107-0f598180-c6f6-11ea-8714-59d92a1bd0d0.png)

![image](https://user-images.githubusercontent.com/1329837/87560129-154f6280-c6f6-11ea-9237-8744c2533f14.png)

![image](https://user-images.githubusercontent.com/1329837/87560153-1bddda00-c6f6-11ea-9f99-df506b715bd4.png)

![image](https://user-images.githubusercontent.com/1329837/87560198-2ac48c80-c6f6-11ea-8b2f-940f6cd50341.png)

![image](https://user-images.githubusercontent.com/1329837/87560435-64959300-c6f6-11ea-8436-e87b0ebb970e.png)

Etc...

**Comment by notbakaneko** [comment]
already fixed in #6312
