### ISSUE TITLE
Old web links with trailing slash don't redirect to new web

### ISSUE THREAD

**Issue by VeilStar** [ppy/osu-web#6316]
I'm not sure if this is something that should be supported since the slash would indicate the start of a new path, however, I noticed a fair few of my old forum posts containing a link to a different forum post have a trailing slash in said links, and it would be nice if these links would still work and redirect you properly, as they used to work fine on the old web, and I'm sure a fair few old forum posts suffer from the same issue.

I believe Firefox used to automatically append a slash at the end of every URL in the address bar, causing this to be an issue in some of my posts. I may be mistaken though.

Example of a post containing an link from the old website with a trailing slash:
https://osu.ppy.sh/community/forums/topics/368463?start=4518567

Clicking on said link and going to https://osu.ppy.sh/forum/t/358282/ shows an error from the old web:
> The page you were looking for can't be found...
> or something went seriously wrong!

While going to https://osu.ppy.sh/forum/t/358282 redirects you to https://osu.ppy.sh/community/forums/topics/358282.

Edit: Maybe this is better left for #1051?

**Comment by VeilStar** [comment]
I just found out that old forum links containing /start=<number> at the end such as https://osu.ppy.sh/forum/t/261443/start=0 don't work either.

Additionally, old beatmap links with a trailing slash such as http://osu.ppy.sh/b/131564/ do work and redirect you.

I'm not sure if this issue is specific to old forum topic and post links containing anything after the topic or post ID rather than an issue caused by a trailing slash now, so the title and description of this issue may be somewhat inaccurate.

**Comment by peppy** [comment]
Fixed, thanks.
