### ISSUE TITLE
forum threads aren't marked as read after posting

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#6321]
it doesn't matter 99.9% of the time because OP is redirected to their post after they make it, which then does mark it as read. I notice this when I make the posts on [Project Loved forum](https://osu.ppy.sh/community/forums/120) with a program that doesn't follow the redirect

just something to consider for when there is an actual API for making forum posts I guess.

**Comment by peppy** [comment]
Should be an easy fix.

**Comment by notbakaneko** [comment]
I'm against the notion that sending a post should mark anything as read, _especially_ when used as an API or not done from the site itself; it's the viewing of the thread that should be the condition for being considered as read.

**Comment by cl8n** [comment]
sorry I think my wording was misleading. I only meant for new topics, since there are no other posts to read besides the one OP made

**Comment by notbakaneko** [comment]
You mean when creating a new topic, the topic won't be unread for the creator?
That makes more sense, then.

**Comment by peppy** [comment]
>You mean when creating a new topic, the topic won't be unread for the creator?

*will* be unread, right?

**Comment by notbakaneko** [comment]
This is asking for forum topics to be have already been marked as read (so, not unread) for the creator when they're created, ...right? 🤔
