### ISSUE TITLE
Project Loved usergroup can add maps to Loved, but not remove them

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#6327]
Currently, someone with database access needs to hop in and unlove maps if they need to be removed from the category for whatever reason.

Adding a simple button to beatmap discussions that allows them to unlove Loved maps upon request would be ideal.

**Comment by peppy** [comment]
I'm not sure we should make the process of removing that accessible. Is it such a common thing?

**Comment by cl8n** [comment]
we let loved mappers request to have their maps removed, so it does happen more than something like unrank. I made the added button in #6760 usable for project loved group cuz i dont think it's very "accessible" given the group is only 3 people and rarely changes, but I can change that to admin only if u want
