### ISSUE TITLE
Scores (in recent scores for instance) should include the "perfect" / "full combo" flag

### ISSUE THREAD

**Issue by stanriders** [ppy/osu-web#6329]
Would be very useful for player's recent scores

**Comment by peppy** [comment]
Could you explain where you are seeing this? We can't help with your issues if you aren't providing minimal details.

**Comment by stanriders** [comment]
https://osu.ppy.sh/api/v2/users/6447454/scores/recent
`beatmap` part doesnt have `max_combo`

**Comment by notbakaneko** [comment]
Max combo can be retrieved from the beatmap instead; API's function isn't to include everything in the same response.

**Comment by stanriders** [comment]
Is it that much effort to add? Considering its present in other endpoints' short beatmap struct

**Comment by peppy** [comment]
If anything we should be providing less information in the beatmap. There should probably be a "perfect" flag is that's not already there, which signifies full combo or not.

**Comment by stanriders** [comment]
That would work too i guess. Max combo would be more informative, but perfect is better than nothing.

**Comment by notbakaneko** [comment]
`perfect` is already part of the score response
