### ISSUE TITLE
Add api endpoint for retrieving player's score on a beatmap

### ISSUE THREAD

**Issue by stanriders** [ppy/osu-web#6330]

**Comment by notbakaneko** [comment]
should be available since #6826

**Comment by stanriders** [comment]
Pretty sure it's not unless i'm missing something

**Comment by notbakaneko** [comment]
`/scores/{mode}/{scoreId}`?

**Comment by stanriders** [comment]
Is it possible to specify beatmap and player name/id there? I'm looking for an endpoint similar to V1's [/api/get_scores](https://github.com/ppy/osu-api/wiki#apiget_scores)

**Comment by peppy** [comment]
@notbakaneko do we have something that matches? ie. the ability to get a user's score for a specific beatmap?

**Comment by nanaya** [comment]
Should this return the all highest scores for the selected beatmap (in case of multiple high scores due to mods etc) or just the highest one?

**Comment by stanriders** [comment]
Ideally it should have some kind of mods param, but having all high scores would work too
