### ISSUE TITLE
You should get a notification when someone replies to your comment under a map

### ISSUE THREAD

**Issue by Thymue** [ppy/osu-web#6333]

**Comment by peppy** [comment]
Was there a reason for closing this?

**Comment by lmnyx** [comment]
Isn't there a "Watch" button in beatmap comments?

**Comment by peppy** [comment]
That's for all comments. I believe the issue is in relation to *always* getting notifications for replies to your own comments, which I can strongly agree with.

Anyways, duplicate of https://github.com/ppy/osu-web/issues/4355, which I have bumped in priority.

**Comment by Thymue** [comment]
I closed it because I found the duplicate afterwards, sorry.
