### ISSUE TITLE
Unable to send old forum PMs in some cases

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#6334]
In the NAT, we send Beatmap Nominator application and evaluation feedback via forum PMs presently, due to a lack of any alternative at the present for sending longer messages with BCC functionality.

Sometimes however, I find myself totally unable to send forum PMs to specific users.
Previously, the PMs ate a message I sent to hypercyte http://osu.ppy.sh/users/hypercyte. We both have a "ghost PM"
![image](https://user-images.githubusercontent.com/33286824/87856124-d3d3d880-c8ea-11ea-9fae-e1626406429d.png)
where my outbox count is higher than what's there, and he is stuck with "1 private message on-hold because of a full folder".

Today I've found myself completely unable to send a message to Fall https://osu.ppy.sh/users/4800816 on the website about their passing probation. My messages do not appear in my sent our outbox folder, and they receive this message instead:
![image](https://user-images.githubusercontent.com/33286824/87856176-4d6bc680-c8eb-11ea-8053-92d4cfdbc07e.png)
Despite the fact their inbox is clearly nowhere near full.
All PMs I send to them now end up in this state, rendering it impossible for me to forum PM them.

For both hypercyte and Fall, they are unable to release the initial bugged message. They ARE able to release other messages, but not the first ones.

This bug has only started occuring in the past few weeks. I'm not sure why this would happen, as to my knowledge no old-website changes have been happening - but it's definitely an issue that impedes on basic tasks NAT need to do.

edit: now this happened to me messaging Seto Kousuke https://osu.ppy.sh/users/2857314  too, send help, my forum pms are dying with every other pm i send...

edit edit: Fall is now unable to receive forum PMs from any user, but hypercyte is.

**Comment by hypercyte** [comment]
also worth mentioning the messages that did get "released" didn't actually appear, they kinda just vanished

**Comment by iiyosomu** [comment]
Yes, I am able to release the on-hold messages but despite that they just dissapear anyways and I'm left with 1 on-hold message stuck in the abyss so hopefully finding a solution soon would be appreciated.

**Comment by yaspo** [comment]
Can confirm having just experienced this same issue, I have 3 pms marked in my outbox but only 2 showing - neither of which is the one I just sent to Fall.
![](https://i.imgur.com/05fBydy.png)

Sending a pm to a BN applicant right after did work however, pushing the amount of pms my outbox marks to 4 and showing 3 in my outbox listing. Note that this pm and the previous one have the same people in BCC so it's likely not due to that.
![](https://i.imgur.com/rRrjQTU.png)

**Comment by SetoKou** [comment]
also having the same issue with ghost pms, other users are able to send me new messages, but it still shows this message even though there's nothing there and clicking ''Release all on-hold messages'' does nothing
![image](https://user-images.githubusercontent.com/40137854/87857331-587b2280-c8fc-11ea-905b-192400710b33.png)

**Comment by peppy** [comment]
Have you tried using the new chat system instead? PMs are going to be decommissioned in the coming future and as such likely won't receive fixes for issues like this.

**Comment by cl8n** [comment]
never fixed, but these are fully deprecated now so can close issue.
