### ISSUE TITLE
Comment section always sorted as "Recent" no matter how I change.

### ISSUE THREAD

**Issue by UraomoteError** [ppy/osu-web#6337]
Self-explanatory title. I was wondering if there's an own solution for it or it has been a bug recently.

**Comment by gagahpangeran** [comment]
On which page this happened?

I can change the sort to top or old.

**Comment by Joehuu** [comment]
He meant that the sort is not saved anymore (i.e. in a beatmap page, sort comments to top, and refreshing will make it go back to recent).

**Comment by gagahpangeran** [comment]
After some observation, looks like https://github.com/ppy/osu-web/commit/d71851e6964a53d848532bd69c4b89ee6292727d logic changes is wrong.
