### ISSUE TITLE
Initial Setup

### ISSUE THREAD

**Issue by BossOfGames** [ppy/osu-web#634]
Hey all,

I am trying to setup the web environment but I am running into issues on the forum side of things. How does one get the forum to work properly within the testing environment (Vagrant)?

**Comment by BossOfGames** [comment]
More specifically, I am getting this error:

`QueryException in Connection.php line 713:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'osu.phpbb_acl_options' doesn't exist (SQL: select `auth_option_id` from `phpbb_acl_options` where `auth_option` = f_post limit 1)`

**Comment by kschamplin19** [comment]
See #605.

**Comment by BossOfGames** [comment]
So how exactly do I add these missing tables referenced in #605?
