### ISSUE TITLE
Add number of remaining votes when looking at contest entry in lightbox view

### ISSUE THREAD

**Issue by Phippe** [ppy/osu-web#6355]
When viewing all the entries, I usually cycle through all of them in lightbox view. Seeing the number of remaining votes would help to decide whether an entry should receive a vote or rather not. It could look something like this:

<img src="https://user-images.githubusercontent.com/34287258/88182297-4f59c080-cc30-11ea-8a99-1a58638f1a4e.jpg" />

**Comment by peppy** [comment]
Would definitely be nice to have. Maybe we can re-use the "remaining paragraphs" control @nekodex recently added?
