### ISSUE TITLE
Use cases for creating/sending chat PMs through API

### ISSUE THREAD

**Issue by pishifat** [ppy/osu-web#6359]
forum pms are being used to send automatically generated info-heavy messages (BN evaluations/reports and individual feedback for monthly beatmapping contests), which can total around 100 pms a month. project loved also sends similar template forum pms but i'm not sure if they'd use this feature

manually sending these with new chat involves sending a few messages in a row because of length limits or sending a link to the full content of the message

https://osu.ppy.sh/docs/index.html?javascript#create-new-pm this seems like a doable way to handle these situations

**Comment by notbakaneko** [comment]
who or what is going to be sending these PMs?

**Comment by pishifat** [comment]
i assumed it would be sent by the user behind the authorization token, which would be me for monthly beatmapping contest cases and anyone in the NAT usergroup for BN evaluations/reports

**Comment by notbakaneko** [comment]
In other words, there's always going to some user interaction before they're sent?

**Comment by peppy** [comment]
I think adding this is fine for bot users exclusively (if that's not already the case).

**Comment by notbakaneko** [comment]
bots having special permissions for API is not a thing we have.

**Comment by peppy** [comment]
We'll probably need that going forward, since bots will eventually be using the API instead of the IRC gateway to interact with chat and other systems.
