### ISSUE TITLE
Top menu should link to old site for incomplete areas

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#636]
In preparation for making the forum portion of osu-web live, the top menu should link to the old site where necessary.

The old site's domain should be an env/config setting. Ask if any specifics are unclear.

**Comment by BossOfGames** [comment]
I will be happy to do it. I do not know which file to edit though. I have been searching the blade files and hit dead ends.

**Comment by peppy** [comment]
awarding 40 bounty for this to @TPGPL 👍
