### ISSUE TITLE
Fonts for CJK languages (and Thai) are inconsistent with lazer

### ISSUE THREAD

**Issue by STCapricorn** [ppy/osu-web#6360]
in lazer, CJK languages use the font Noto Sans, while web uses whatever the viewing device has as backup (Hiragino Sans, Meiryo, Microsoft YaHei). this results in an inconsistent viewing experience for those using the new "show beatmap metadata in original language" option on the website.

i also found that the website uses Inter for Cyrillic metadata, while lazer uses Noto Sans. (has to do with the font fallbacks)

**Comment by nanaya** [comment]
Non latin alphabet intentionally doesn't have specific web font to avoid having to download some MB of file just to view a web page.
