### ISSUE TITLE
Client authentication failed

### ISSUE THREAD

**Issue by Enitoni** [ppy/osu-web#6370]
Hi again. I had OAuth2 working just fine a few days ago, but today when I needed to authenticate my account again to test something, I get this error
  
![image](https://user-images.githubusercontent.com/5295397/88595158-cb09a200-d062-11ea-87c7-6b99a6734270.png)

I tried resetting the secret, clearing cookies, re-logging. I also had my friend try on his machine. Nothing has helped. 
How do I resolve this?

**Comment by peppy** [comment]
what page is that? what's your username? give us something to work with.

**Comment by Enitoni** [comment]
Oops, sorry!

My username is "Enitoni". This is the page for authenticating via oauth. The exact URL is
`https://osu.ppy.sh/oauth/authorize?client_id=1677&redirect_uri=http%3A%2F%2Flocalhost%3A9000%2Fauth&scope=identify&response_type=code`

Last time, this would give me a screen that allowed me to authenticate my account to my app via OAuth2.

**Comment by nanaya** [comment]
Your redirect uri is wrong.

**Comment by Enitoni** [comment]
I seem to be making all kinds of silly mistakes. Thank you, and sorry for the bother.
