### ISSUE TITLE
Text in chatbox should not be shared across every channel

### ISSUE THREAD

**Issue by Trigonoculus** [ppy/osu-web#6372]
## Current behavior
![Screen-Recording-2020-07-28-11-43-17](https://user-images.githubusercontent.com/20501245/88620218-a85da480-d0c7-11ea-8a95-e41a88147a68.gif)

This happens to both channels and PMs.

## Expected behavior
Text in chatbox should be confined to a single chat that it was typed in. The reasoning is that, for instance, if you are chatting in a PM with someone and accidentally presses send while switching chat tabs, private information may inadvertently be made public.

**Comment by peppy** [comment]
At very least, deleting the content should be added. If we can persist per channel, that would obviously be better.
