### ISSUE TITLE
pending map seems to have playcount

### ISSUE THREAD

**Issue by Apollo-P** [ppy/osu-web#6373]
can't reproduce adding to the playcount, this map has never been qualified so it's very strange that it has playcount. not sure how

map: https://osu.ppy.sh/beatmapsets/1194122#osu/2487840

**Comment by peppy** [comment]
See https://github.com/ppy/osu-web/issues/3359

**Comment by Apollo-P** [comment]
this is a really nice addition! at the moment I can't get it to work on cutting edge, but I have spotted an issue (which I think you may be aware of already)

all unranked maps w/ playcount that I could find seem to have the exact same playcount, and I highly doubt that in the period that this was working, exactly 9 players played every single one of these maps and literally no other? can provide examples

**Comment by peppy** [comment]
Both are intentional.
