### ISSUE TITLE
Add sorting by plays for unranked mapsets in search

### ISSUE THREAD

**Issue by MzudemO** [ppy/osu-web#6375]
Since those sets now have playcount associated with them that option would be really handy in the site search 

That option is available for sets with leaderboards:
![chrome_9XJXP8u69P](https://user-images.githubusercontent.com/23505804/88676346-3ea3c180-d0ec-11ea-8155-0615b5a1041b.png)

but doesn't exist for Pending & WIP or Graveyard maps:
![chrome_KkjpWUWuuI](https://user-images.githubusercontent.com/23505804/88676486-685ce880-d0ec-11ea-969d-e5ac9fe8fd95.png)

**Comment by peppy** [comment]
Should be a super simple one.
