### ISSUE TITLE
Email digest usability issues

### ISSUE THREAD

**Issue by Shmiklak** [ppy/osu-web#6402]
![-1vsxtl](https://user-images.githubusercontent.com/20987315/89076805-6a4bd380-d39a-11ea-9196-02060cd7cb1d.jpg)

As shown on the picture I've received the digest 15 times within a few hours even though I was browsing the website and was online in the game. 

One of the possible reasons of such behaviour might be sending digest everytime somebody makes a post in the followed thread no matter if you've checked the thread already or not. As far as I remember in before you wouldn't receive the same message for the same thread untill you actually check the new posts which was definitely comfortable, rather than getting email for each post. 

No matter such behaviour of digest is intended or not, I think letting people choose whether they want to receive old fashioned email notifications instead of new digest as an additional feature in the settings would be great. 

As an addition to this issue the website push notifications which are enabled by default in profile settings don't seem to be implemented as in my understanding push means browser push notifications. In case you call the website notifications like this, I'd suggest to rename it to "Website push" or whatever more specific.

**Comment by peppy** [comment]
As an update, digests now send less often, and also will not repeatedly send for the same topic.

Further changes are incoming so I'll leave this open to track the issue to completion.

**Comment by Shmiklak** [comment]
![image](https://user-images.githubusercontent.com/20987315/90338681-c2264380-e004-11ea-930b-901ffd3b3d40.png)
it still keeps sending email notifications for the same topics even though i haven't checked them yet.

**Comment by peppy** [comment]
@notbakaneko can you check in on this?

**Comment by nanaya** [comment]
The update to digest has only been merged recently. It should be fixed now.

**Comment by peppy** [comment]
safe to close the issue?

**Comment by peppy** [comment]
Going to close for now. Please comment if you still find usability issues going forward.
