### ISSUE TITLE
Make the navigation bar on user profiles sticky on the bottom.

### ISSUE THREAD

**Issue by iptq** [ppy/osu-web#6405]
Right now one of the biggest blockers for me using the new site is navigation on user pages. On the old site, you can choose the section to navigate to immediately but on the new site, the cover photo is large and requires me to scroll before reaching the navigation bar (the me! Recent Ranks Beatmaps Historical kudosu! Medals bar).

It would be nice to sticky this bar to the bottom of the screen when the page first loads, the same way it sticks to the top of the screen as you scroll down the page. This way navigation bar is always visible on the screen and navigation to any part of the page is always very simple.

(Another alternative ofc being placing the navigation bar at the top or left but that's a larger change and just stickying it is way less intrusive to the current design)

Rough example:
![image](https://user-images.githubusercontent.com/1700346/89113324-ee678f00-d45e-11ea-9ded-68d5298d02e2.png)

**Comment by peppy** [comment]
@arflyte can you confirm this direction? not sure if the user page is even the latest design right now so also confirm that.

**Comment by arflyte** [comment]
Interesting input. We can stick the navigation to the bottom for now. This is not the latest design, but I'll keep in mind about making the navigation tabs very accessible.
