### ISSUE TITLE
All beatmaps of set ID 356821 seem to have wrong computed checksum

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu-web#6407]
According to my understanding, beatmap checksums are MD5 hashes computed based on the content of the `.osu` file, which is correct checking with every single beatmap, but the beatmaps of [set ID 356821](https://osu.ppy.sh/beatmapsets/356821#osu/785097), all checksums provided by them (via room querying API request) do not match with what they were expected to be, here's a table showing off the provided checksums and the expected checksums:
| Beatmap ID | Checksums provided by room querying request | Expected checksum (MD5 hash of `.osu` file content) |
|:------------:|:-----------------------------------------------:|:------------------------------------------------------:|
| ￼￼ [785647](https://osu.ppy.sh/beatmapsets/356821#osu/785647)       | `a7d69648d156e3fabfe7a114d4923ec2`           | `ff6eae3c20117ab22582a91c8a6909e4` |
| [805928](https://osu.ppy.sh/beatmapsets/356821#osu/805928) | `101df9e333e6658a12ce049c51c1155a` | `19eaea902e2c9457185495009c18f0d1` |
| [788121](https://osu.ppy.sh/beatmapsets/356821#osu/788121) | `562c9f40170ad70fec028e2cbf0c7257` | `18a29a9d145841a9de835df8791401eb` |
| [794551](https://osu.ppy.sh/beatmapsets/356821#osu/794551) | `2d109e2f495139975f94ec80f802ab1e` | `66caf0a8745e5550b116aa45f28add6a` |
| [785097](https://osu.ppy.sh/beatmapsets/356821#osu/785097) | `2dbef102555c14ccaf3f175e517287cc` | `30d73e9b9b5ffc980f1af44d30e7a6c8` |

This issue causes these beatmaps to be unplayable in multiplayer rooms osu!lazer-side due to the checksum mismatches above.

**Comment by peppy** [comment]
The .osu files inside the .osz don't match the latest versions provided by the server (you can check these via `https://osu.ppy.sh/osu/<beatmap_id>`.

from osz:
```
❯ md5sum *.osu
18a29a9d145841a9de835df8791401eb  Kano - Stella-rium (Moeka) [Anais' Hard].osu
19eaea902e2c9457185495009c18f0d1  Kano - Stella-rium (Moeka) [Collab Normal].osu
ff6eae3c20117ab22582a91c8a6909e4  Kano - Stella-rium (Moeka) [Easy].osu
66caf0a8745e5550b116aa45f28add6a  Kano - Stella-rium (Moeka) [Sekai's Insane].osu
30d73e9b9b5ffc980f1af44d30e7a6c8  Kano - Stella-rium (Moeka) [Starlight].osu
```

from osu:
```
❯ md5sum *.osu
562c9f40170ad70fec028e2cbf0c7257  Kano - Stella-rium (Moeka) [Anais' Hard].osu
101df9e333e6658a12ce049c51c1155a  Kano - Stella-rium (Moeka) [Collab Normal].osu
a7d69648d156e3fabfe7a114d4923ec2  Kano - Stella-rium (Moeka) [Easy].osu
2d109e2f495139975f94ec80f802ab1e  Kano - Stella-rium (Moeka) [Sekai's Insane].osu
2dbef102555c14ccaf3f175e517287cc  Kano - Stella-rium (Moeka) [Starlight].osu
```

We'll push a fix for the outdated osz to fix this instance.

**Comment by Ephemeralis** [comment]
This is fixed.
