### ISSUE TITLE
upvoting banchobot posts should not award kudosu.

### ISSUE THREAD

**Issue by pimpG** [ppy/osu-web#6408]
in the past, users upvoted banchobot posts to the point where bancho would appear in the kudosu ranking and i had to deny them manually so the bot would at least be removed from the top 50, but bancho makes new posts every day so it could become a tiring task to deny the posts if people decide to abuse it again.

make it so banchobot deny it's own post's kudosu from now on? (i assume bancho have the ability to do that since it can already reset nominations?)

**Comment by peppy** [comment]
Upvoting should just be hidden on banchobot (or all bot acounts, for simplicity).
