### ISSUE TITLE
alternating page results in beatmap events removes user filter when it's used

### ISSUE THREAD

**Issue by pimpG** [ppy/osu-web#6409]
as title says
https://osu.ppy.sh/beatmapsets/events?user=pimp&min_date=&max_date=

if i try to click on page 2 it will redirect me to this link https://osu.ppy.sh/beatmapsets/events?limit=20&page=2#events which is basically page 2 without user filter. it was supposed to show me this result https://osu.ppy.sh/beatmapsets/events?user=pimp&page=2&min_date=&max_date=

**Comment by gagahpangeran** [comment]
Maybe this is the cause

https://github.com/ppy/osu-web/blob/e6a4ad6425c45afc3780ef67c1f5320d720833a4/app/Libraries/ModdingHistoryEventsBundle.php#L63

I'm not sure why the param `user` is unsetted, will investigate later.
