### ISSUE TITLE
Storyboard flag is not displayed correctly on website

### ISSUE THREAD

**Issue by Calvariaa** [ppy/osu-web#6410]
https://osu.ppy.sh/beatmapsets/1110686
This beatmapset with *.osb file in it and works fine, but the storyboard flag is not displayed on the website.

I dont know why but same problem happens in this ranked map：
https://osu.ppy.sh/beatmapsets/957917

**plz fix this**

**Comment by Alleyne-Angel** [comment]
Same problem with my another mapset https://osu.ppy.sh/beatmapsets/1040744.

**Comment by peppy** [comment]
Your map has two storyboard files, for what it's worth. You should fix that.

I've made fixes to make sure this doesn't happen going forward and also fixed the listed beatmaps.
