### ISSUE TITLE
Markdown parsing issue in table

### ISSUE THREAD

**Issue by MegaApplePi** [ppy/osu-web#6411]
From https://github.com/ppy/osu-wiki/pull/3033

![](https://user-images.githubusercontent.com/14264992/72487248-07666680-37d3-11ea-8567-9383246e6743.png)

The rendering of this table cell in the [shortcut key reference article](https://osu.ppy.sh/help/wiki/Shortcut_key_reference#play-mode) is broken. It appears fine in [GitHub](https://github.com/ppy/osu-wiki/blob/master/wiki/Shortcut_key_reference/en.md#play-mode) though, fwiw.

**Comment by gagahpangeran** [comment]
Maybe this issue because osu-web is using league/commonmark ver 1.1.2. It looks correct with version 1.3.0 [here](https://johnmacfarlane.net/babelmark2/?text=%60%60+%60+%60%60).
