### ISSUE TITLE
Exact matches on user search are not always on the top 

### ISSUE THREAD

**Issue by InvisibleSymbol** [ppy/osu-web#6416]
Exact matches should be the first result but it somehow doesn't always work
For example if you search for "btmc" the first one is incorrect:
![](https://i.imgur.com/5jyANOx.png)

And more importantly if you search for "merami" he will somehow be the last result:
![](https://i.imgur.com/OZVgFVy.png)

**Comment by gagahpangeran** [comment]
As I know one of the reason of this because last time Merami's name is reverted by support. You can check the search for other player's name that get revert like Sotarks or RyuK.

**Comment by peppy** [comment]
This should be resolved now, thanks for pointing out!
