### ISSUE TITLE
allow downvoting on beatmap discussions

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#6421]
as a normal user you can upvote whatever you want but not downvote anything. to show that you disagree with a post, you need to comment and explain why, but you can't change the downvote counter-- so even suggestions that are widely considered nonconstructive end with up/down counts like 15/1 or something

my concern is that people who agree with the discussion can show their support without contributing any comments, yet people who disagree need to write a comment *and* don't have their disagreement shown in the up/down counts. I think the requirements to vote up or down should be the same, to get a less misleading view of people who agree and disagree

also, if it was built like this to prevent KD abuse, votes that don't come from the mapper or BNs could just not count toward KD

**Comment by cl8n** [comment]
turns out this is very similar to #4628 and I didn't read far enough. /me runs

**Comment by notbakaneko** [comment]
this should be moved into #4628
