### ISSUE TITLE
Improvements to changelog webhook handling

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#6423]
Will help alleviate some manual process at my end.

- We use labels with prefixes now. They don't look nice for display so should be converted for category display

area:gameplay -> Gameplay
area:user interface -> User Interface
anything:Title Case -> Title Case
Performance -> Performance

- Any PR in the category "Dependencies" should be marked as `private` (is a dependabot PR).

**Comment by nanaya** [comment]
> area:user interface -> User Interface

Do you mean `area:user-interface`?

**Comment by peppy** [comment]
yeah, i think we do always have dashes, but best support spaces as well
