### ISSUE TITLE
beatmap `countTotal` sometimes doesn't match sum of object counts

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#6426]
it happens on a lot of maps I checked so I think there's either a problem with the processor or I'm misunderstanding what `countTotal` means.

for example on https://osu.ppy.sh/beatmaps/137121:
```json
"count_circles": 693,
"count_sliders": 212,
"count_spinners": 2,
"count_total": 1123,
```
693+212+2 = 907. `count_total` is 216 higher than that and I don't know where it's coming from. i thought it might be including slider ends/ticks/repeats but none of those add to 216

**Comment by peppy** [comment]
![image](https://user-images.githubusercontent.com/191335/89271010-1af5f380-d677-11ea-83b7-689ce8baa6e7.png)

Looks like it may be for one of the old star algorithms? I'm not sure why we expose it anywhere, it's not accurate.

**Comment by peppy** [comment]
In further discussion this just shouldn't be exposed via the API.
