### ISSUE TITLE
Display pass/fail chart for pending+graveyarded beatmaps

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#6432]
Currently on pending and graveyarded beatmaps, the section will just say "unranked beatmap"
![image](https://user-images.githubusercontent.com/33286824/89304942-09dbc100-d63c-11ea-89be-e68589ba185c.png)

This information should be displayed now as plays are tracked for pending and unranked maps. 

It's also important to make this section functional, as presently per-difficulty playcount is not accessible on the webpage without this panel.
![image](https://user-images.githubusercontent.com/33286824/89305106-38f23280-d63c-11ea-91c4-0b255887a9b2.png)

Having per-difficulty playcount visible would be beneficial for programs like loved to see which difficulties in a set are actually being played.

**Comment by peppy** [comment]
I believe this data is already being filled in, so there's no reason not to display it.
