### ISSUE TITLE
Keep getting error 400 when trying to do client credentials grant

### ISSUE THREAD

**Issue by reigenatk** [ppy/osu-web#6440]
Hello, I was following the instructions in the image below and have verified that all my info is correct, but I keep getting error 400 so it must mean I'm still inputting something wrong. Does anyone know what?

![image](https://user-images.githubusercontent.com/69275171/89469086-5d363800-d73e-11ea-9da9-f8c0f5c95aa2.png)

Here's my request, I'm trying to use Postman.

![image](https://user-images.githubusercontent.com/69275171/89469264-b1d9b300-d73e-11ea-858d-0bb74bfab8d3.png)

Thanks!

**Comment by cl8n** [comment]
I think you need to send the parameters in the body with `application/x-www-form-urlencoded`

**Comment by reigenatk** [comment]
Thanks, that worked. Now I am getting 401 when I try to make a request with the access-token...

**Comment by gagahpangeran** [comment]
The auth token must be in header, not parameter field

**Comment by reigenatk** [comment]
Sorry if I'm wrong, but isnt the auth token being sent in the header as indicated by -H?

**Comment by qcl12345** [comment]
Remove the curly braces around your token in the request

**Comment by gagahpangeran** [comment]
You use postman, so you can input the auth token in 'Authorization' tab and select 'Bearer Token'.

![image](https://user-images.githubusercontent.com/4964985/89594927-67ab1b80-d87d-11ea-95a9-6dde18de2101.png)


Or in 'Headers' tab.

![image](https://user-images.githubusercontent.com/4964985/89594899-56faa580-d87d-11ea-8cf6-df5e7dbb5eed.png)

**Comment by reigenatk** [comment]
Thanks so much guys! It works. I was doing OAuth2 instead of bearer token. Time to get started on my project :D
