### ISSUE TITLE
beatmap listing sorted by playcount isn't always in order

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#6442]
it's most apparent in pending, where just a few pages down the maps don't seem to be in order of playcount at all. maybe related to how often the es index gets updated

**Comment by peppy** [comment]
I don't believe it is ever getting updated by playcount (there's no update schedule for it any more).

**Comment by nanaya** [comment]
The endpoint has been added. All that's left is for the score processor or something related to hit it every now and then with list of beatmap ids. @peppy

**Comment by peppy** [comment]
I've added reindexing support via the existing submission code in a bit of a temporary way, but should be enough to keep these relative up-to-date 👍 .
