### ISSUE TITLE
Artist name is not truncated in beatmapset card

### ISSUE THREAD

**Issue by gagahpangeran** [ppy/osu-web#6443]
This happen on mobile.

![image](https://user-images.githubusercontent.com/4964985/89499678-9d52f480-d7ea-11ea-9774-0c6f5fe76d19.png)

**Comment by notbakaneko** [comment]
I think this is intentional and pushes the title up.

**Comment by gagahpangeran** [comment]
Another example

![image](https://user-images.githubusercontent.com/4964985/89613051-86c0a200-d8ab-11ea-8057-ec78f25c1da5.png)
