### ISSUE TITLE
Searching phrases including colons don't work properly

### ISSUE THREAD

**Issue by ciiii0001** [ppy/osu-web#6446]
Let's say we want so search Re:TrymenT (https://osu.ppy.sh/beatmapsets?m=0&q=re%3Atryment). First results are songs titled "re-blahblah" but not what we want.
![re](https://user-images.githubusercontent.com/66686071/89574034-19d2eb00-d85e-11ea-81c9-032c0285b978.PNG)

Removing the colon in the search phrase (https://osu.ppy.sh/beatmapsets?m=0&q=retryment) gives correct results.
![tryment](https://user-images.githubusercontent.com/66686071/89574039-1ccddb80-d85e-11ea-8591-3c2a1ac0aca3.PNG)

(edit: idk if removing colon working is caused by the tags but the issue exists anyway)

**Comment by nanaya** [comment]
weirdly enough it seems to work now. I wonder if it's related to prefix length update.

![](https://s.myconan.net/2020-08/firefox_2020-08-24_13-42-46.png)

**Comment by notbakaneko** [comment]
Prefix length update probably allowed it to match up to a certain extent since it has different tokenization rules; will have to investigate a bit more so be it it can be considered fixed 🤔 

But tokenization rules for the title should probably be changed anyway

**Comment by notbakaneko** [comment]
It seems like this is now working by coincidence and not the way it should be working.
The actual problem is the `es_query_escape_with_caveats` function which ends up breaking `Re:TrymenT` into `Re` and `Tryment` so it never actually matched the title.

**Comment by nanaya** [comment]
So the question is should `:` be considered a word separator or not.

**Comment by nanaya** [comment]
And do we still need that `es_query_escape_with_caveats` function considering we're using `simple_query_string` which has fewer functionality and doesn't seem to need escaping?

**Comment by peppy** [comment]
I'd say there's probably very few cases punctuation should be considered a word separator for titles. They are usually used in weird ways that normal punctuation wouldn't be.
