### ISSUE TITLE
New medal is cropped in user page

### ISSUE THREAD

**Issue by gagahpangeran** [ppy/osu-web#6458]
![image](https://user-images.githubusercontent.com/4964985/89710171-cf12b980-d9aa-11ea-9fdb-8ca9ae9e56ae.png)

**Comment by bdach** [comment]
Probably another case of a difference in the process of exporting the assets between old and new medals (see discussion in #5233 wherein this happened once previously).

**Comment by gagahpangeran** [comment]
Yeah, I think the lack of drop shadow makes it little bit taller in height ratio and causing overflow at the bottom.

**Comment by Ephemeralis** [comment]
This is fixed on our end and should update whenever the cache does its thing.

**Comment by peppy** [comment]
Have purged caches.
