### ISSUE TITLE
Deleting first paragraph in mod review is difficult

### ISSUE THREAD

**Issue by pishifat** [ppy/osu-web#6460]
if a paragraph is the first part of a mod review, the only way to delete it is by pressing backspace at the beginning of the next issue (shown [here](https://www.dropbox.com/s/djhsasbpldzxofx/cmJiVEofAx.mp4?dl=0)). there should be a better way to do this?

**Comment by nekodex** [comment]
You can also click in the blank paragraph and hit delete (not backspace).

I'm guessing the issue here is more that hitting backspace doesn't do anything inside of the first paragraph/issue of a review?

**Comment by pishifat** [comment]
didn't try delete oops
but yeah, ive been using backspace to remove other paragraphs so i expected it to work in this case too
