### ISSUE TITLE
topic watch/bookmark button is broken

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#6461]
when you hover over the button, its color changes but the menu doesn't open. confirmed with a few other people, this started happening recently

no errors in console so maybe it's a style issue. I'm on latest chrome/windows

**Comment by gagahpangeran** [comment]
Weird, looks like regressed by #6420

**Comment by notbakaneko** [comment]
You can't use `overflow` have elements outside the bounds of the container (which is what the bookmarks menu is)

**Comment by nanaya** [comment]
Closing as the change which broke this has been undone.
