### ISSUE TITLE
Add the possibility to resize image in forums

### ISSUE THREAD

**Issue by Corne2Plum3** [ppy/osu-web#6464]
We can not resize images in forums (according to this thread https://osu.ppy.sh/community/forums/topics/1122923), and it's not very pratical when we want to post an image or add a image in the signature but the image it's too huge...

It's possible too add in the BBCode of forums a tag who resize images? Like this for exemple:
`[resize={width}x{height}]{URL of the image}[/resize]`
or better:
`[img={width}x{height}]{URL of the image}[/img]`
Thanks. An active user in forums

**Comment by peppy** [comment]
Please do this to the image itself. Resizing in the way mentioned causes the original images to be higher resolution than required which leads to high bandwidth usage and bad browser downscaling artifacts.
