### ISSUE TITLE
empty pages on country ranking

### ISSUE THREAD

**Issue by LMNYX** [ppy/osu-web#6469]
![void](https://user-images.githubusercontent.com/13962537/89982517-5902a100-dc8f-11ea-8e09-5b9f475cc6bf.png)

**Comment by myangelaku** [comment]
Why was this closed? It still happens, for example on [the Luxembourg rankings](https://osu.ppy.sh/rankings/osu/performance?country=LU&page=96#scores)...

**Comment by Albionthegreat** [comment]
It appears this issue is back. [link to page in image](https://osu.ppy.sh/rankings/taiko/performance?country=GP&page=3#scores)

![image](https://github.com/ppy/osu-web/assets/74660626/9761445c-8fb9-4d75-9efd-76f752541a7b)

**Comment by LMNYX** [comment]
Is this pushed to the prod? Because I still see it happening :skull:
