### ISSUE TITLE
Truncate forum post username

### ISSUE THREAD

**Issue by lmnyx** [ppy/osu-web#6470]
![e](https://user-images.githubusercontent.com/13962537/89984096-4178e780-dc92-11ea-8977-7b97117d0d62.png)

**Comment by solitairecreations** [comment]
I made a pull request that fixed this issue. For some reason I can't manually link this issue to it (probably intentional, maybe I'm just dumb)

[Link to pull request](https://github.com/ppy/osu-web/pull/6479)

**Comment by lmnyx** [comment]
@solitairecreations You need to add `Resolves #6470` to the main post of pr

**Comment by solitairecreations** [comment]
Ah, thanks!
