### ISSUE TITLE
Can't see all 100 user top plays, only on the new website.

### ISSUE THREAD

**Issue by veke66** [ppy/osu-web#6474]
So basically I was unrestricted about a month ago and have noticed a weird issue, where I can only click "Show More" under my top plays only once, thus being able to only see my 55 top pp plays (https://osu.ppy.sh/users/8908387). BUT, if I go to to the old website (https://old.ppy.sh/u/8908387), the issue does not occur and I can see all my 100 top pp plays (I even counted them to make sure).

At first I thought it was some issue with me not having full top plays list, but now that I have reached 100, it most definitely isn't that.

In another user's case (https://osu.ppy.sh/users/11888158), you can only see their top 4 pp plays, whilst on the old website (https://old.ppy.sh/u/11888158) they have all 100. I assume they also have been unrestricted and some other people suggested this might be the culprit too.

Sorry if this has already been submitted, I tried searching, but couldn't find anything relating to this.

**Comment by notbakaneko** [comment]
They should be there nw
