### ISSUE TITLE
Modding panel layout issues

### ISSUE THREAD

**Issue by Shmiklak** [ppy/osu-web#6475]
The textarea for the mod posts becomes too wide and runs out of the actual form box in case the mod itself is huge

https://i.imgur.com/KLddwWS.png

Not like a big issue, yet it makes modding beatmap uncomfortable when you need to explain your point in details and it was fine in before until some recent updates (like a day or two ago)

**Comment by gagahpangeran** [comment]
Duplicate of #6447
