### ISSUE TITLE
Add Ban History to the new page

### ISSUE THREAD

**Issue by Lolihunter1337** [ppy/osu-web#6484]
The old osu! site has https://osu.ppy.sh/p/bans which shows the amount of players banned per month. would be nice to have that back

**Comment by alolanraichulive** [comment]
Provided for transparency. Don't become a statistic, please.

**Comment by alolanraichulive** [comment]
That might be cool if peppy added it to the new theme of the osu! website.

**Comment by cl8n** [comment]
seems like it could be an entry on status.ppy.sh? I can't imagine it fitting into anywhere on the osu website.

**Comment by peppy** [comment]
I've added a graph on status.ppy.sh. I don't think this will come back on osu-web (but web-10 will remain visible for the foreseeable future).
