### ISSUE TITLE
OAuth dialog-form obscured by __header-overlay

### ISSUE THREAD

**Issue by Naxesss** [ppy/osu-web#6487]
![](https://i.imgur.com/epXiPEz.png)

This element prevents mouse input, for example when trying to click "Authorise", and darkens the dialog.
Deleting `<div class="dialog-form__header-overlay"></div>` seen in the image seems to solve this.

See https://osu.ppy.sh/oauth/authorize?client_id=1595&redirect_uri=https%3A%2F%2Faiess.tk%2Fcallback&response_type=code&state=

(Latest version of Chrome)

**Comment by peppy** [comment]
Thanks for pointing this out! Will rollback the build for now (we were aware there may be remaining issues with a recent performance improvement change that was made).

**Comment by nanaya** [comment]
Resolved by #6492.
