### ISSUE TITLE
The word "Beatmap" In Thai Translation is very inconsistence

### ISSUE THREAD

**Issue by C0NS03L** [ppy/osu-web#6488]
![Problem 1](https://user-images.githubusercontent.com/58496201/90306458-aa14ce00-def7-11ea-97d5-05082c6739b9.png)
![Problem 2](https://user-images.githubusercontent.com/58496201/90306459-ad0fbe80-def7-11ea-90ac-0daac2a292ec.png)
![Problem 3](https://user-images.githubusercontent.com/58496201/90306460-ae40eb80-def7-11ea-8d55-bfa627025dce.png)
Its super inconsistence 
1st one uses: บีตแมป, แมพ
2nd one uses: บีทแมพ, Beatmaps
3rd one uses: Beatmap

Plus the second one contains wrong translation that can cause misunderstanding
The translator translate "Loved beatmap" into "Beatmaps ที่ชื่นชอบ" which means "Favorited Beatmap"

**Comment by C0NS03L** [comment]
I replaced most of the Beatmap in crowdin to "บีทแมพ" since it seems the most correct

**Comment by notbakaneko** [comment]
These should be fixed on crowdin https://crowdin.com/translate/osu-web/47/en-th#1421
