### ISSUE TITLE
Chat API Scope

### ISSUE THREAD

**Issue by iWeeti** [ppy/osu-web#6489]
I'm trying to make a chatbot into the game as my own account.
I'm sending `GET /api/v2/chat/channels` with a token I got from `POST /oauth/token` with public scope,
but it gives me `{'error': 'Invalid scope(s) provided.'}`.
What is the scope I should be using to get a token that can do those? Is there even a one?

![bot account image](https://reeee.me/EcGB)

**Comment by qcl12345** [comment]
There are currently no publicly available scopes for any of the chat endpoints. See https://github.com/ppy/osu-web/issues/6359. 

Chat on the stable client can currently be connected to via [IRC](https://en.wikipedia.org/wiki/Internet_Relay_Chat), which is what most (all?) of the current chat bots are using. https://osu.ppy.sh/p/irc

**Comment by iWeeti** [comment]
Alright, thanks!
