### ISSUE TITLE
Huge lag in friends dashboard page

### ISSUE THREAD

**Issue by MkGuh** [ppy/osu-web#6490]
I have over 270 added people in my friendlist, and whenever I open the friends page in https://osu.ppy.sh/home/friends the website gets extremely laggy and I can't really do much in it.

I am using brick view and didn't test with other views yet. 

I think this happens because the website tries to load each user animated banner at the same time, and this doesn't really seem to work in an optimized way :3c

My friendlist for reference: https://mkguh.s-ul.eu/yfVKpSik.png

**Comment by nanaya** [comment]
See if it's better now.

**Comment by MkGuh** [comment]
Yes, now it's much more responsive. I'll close it as it seems to have been fixed.

Thank you very much for that!
