### ISSUE TITLE
Option to see banned user'a maps

### ISSUE THREAD

**Issue by Onto3ma** [ppy/osu-web#6491]
Basically how this system would work is there profile won't show there rank , and there score's , most played maps , you get the idea but you'll be able to see a little bar or something that show's there submitted , ranked , WIP , graveyarded and loved maps , if not add an option in the beatmap listing tab that say's "sort by user" since searching up there username doesn't show some of there maps especially the older or less popular maps

**Comment by Onto3ma** [comment]
user's*

**Comment by peppy** [comment]
They show up in the listing. You can search by username.
