### ISSUE TITLE
Display a list of existing languages in osu!wiki articles

### ISSUE THREAD

**Issue by Kotoki1337** [ppy/osu-web#6493]
Example:
![image](https://user-images.githubusercontent.com/35394151/90360277-e8dc8c80-e08d-11ea-883c-201e537bfe4a.png)

osu!wiki will only display the current web language. Some people have more than two languages, showing all available languages suitable for people to choose their suitable third language, and also helping translators to compare.

**Comment by heagan01** [comment]
so can I contribute by adding my translations + the list of current language??

**Comment by Lalo611** [comment]
Other example:
![image](https://user-images.githubusercontent.com/69506035/93778252-0f956200-fbfc-11ea-94e6-7df0334bc608.png)
idk if it suits what you want @Kotoki1337

**Comment by Kotoki1337** [comment]
> Other example:
> 
> ![image](https://user-images.githubusercontent.com/69506035/93778252-0f956200-fbfc-11ea-94e6-7df0334bc608.png)
> 
> idk if it suits what you want @Kotoki1337 
> 
> 

I think the country flag is more intuitive

**Comment by Lalo611** [comment]
Oh, okay. I know absolutely nothing about PHP but I like your idea

**Comment by Kotoki1337** [comment]
> Oh, okay. I know absolutely nothing about PHP but I like your idea

Yea yea just a suggestion

**Comment by troke12** [comment]
woah, that would be nice
example from me:
![ss](https://cdn.discordapp.com/attachments/408950289962369025/757619317951955108/unknown.png)

**Comment by peppy** [comment]
Would be quite nice to have this, I think the proposed location is fine but @arflyte please confirm and provide direction.

**Comment by nanaya** [comment]
hi @arflyte some kind of response would be nice

**Comment by arflyte** [comment]
Sorry, I have absolutely nothing on this for now. I'll try to come up with something before the day's end.

**Comment by arflyte** [comment]
![Figma_201001-131601](https://user-images.githubusercontent.com/3632750/94767887-be018a00-03e8-11eb-8544-5b8eb05f3451.png)

![Figma_201001-132342](https://user-images.githubusercontent.com/3632750/94768142-7c251380-03e9-11eb-99dc-bb562cf4e657.png)

Bit late. I tried making flag display but I think it's overwhelming the header unless it's really tiny (the current flag design is not suitable for tiny sizes). I prefer a dropdown list so we don't have to face an overflowing flag problem in the future.

If you guys still prefer flag display, use the second option.

**Comment by Kotoki1337** [comment]
> ![Figma_201001-131601](https://user-images.githubusercontent.com/3632750/94767887-be018a00-03e8-11eb-8544-5b8eb05f3451.png)
> 
> ![Figma_201001-132342](https://user-images.githubusercontent.com/3632750/94768142-7c251380-03e9-11eb-99dc-bb562cf4e657.png)
> 
> Bit late. I tried making flag display but I think it's overwhelming the header unless it's really tiny (the current flag design is not suitable for tiny sizes). I prefer a dropdown list so we don't have to face an overflowing flag problem in the future.
> 
> If you guys still prefer flag display, use the second option.

If there is no suitable place, dropdown list is indeed a good choice
