### ISSUE TITLE
Landing page hyperlinks not working

### ISSUE THREAD

**Issue by PubWorld** [ppy/osu-web#6502]
The hyperlinks on the landing page https://osu.ppy.sh/home are not working (not clickable but elements are present).
The mobile version of the page seems fine.

I have done some digging inspecting the page elements and apparently the z-index (currently set to auto) is causing the hyperlinks to be behind another element on the page. This may or may not have something to do with the recent changes to position: relative. Unfortunately I was not able to find the possible cause in the recent commit history.

The Hyperlink elements have the class `landing-nav__link` assigned. Manually changing the z-index to 0 moves them into the foreground and the functionality is restored.

Tested on Chrome, Firefox and Edge - The issue is present in all browsers.

**Comment by peppy** [comment]
Which hyperlinks specifically are you talking about?

**Comment by peppy** [comment]
Found them, only when not logged in:

![image](https://user-images.githubusercontent.com/191335/90408322-a72a0100-e0e2-11ea-83bb-8fc7e7f00a54.png)

**Comment by PubWorld** [comment]
All hyperlinks - navigation (home, beatmaps...), sign in, and at bottom General, Help & Community , Legal & Status
