### ISSUE TITLE
Userprofile stretching to full width

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#6505]
![](https://cdn.discordapp.com/attachments/591696564578156575/744941315673948340/unknown.png)

Userprofiles stretch to full width and dont stop at a max width of 1000px, this doesn't have anything to do with big images in userpages since it even happens without one.

Not the only user experiencing this, talked to some others who also get this.

Edit: it doesn't seem to always happened, reloaded the userprofile a few times and it only happens on ~70% of reloads.

**Comment by gagahpangeran** [comment]
It's caching issue, should be fixed now.

![image](https://user-images.githubusercontent.com/4964985/90415290-169bf280-e0db-11ea-903b-b9d45294d2c9.png)

**Comment by notbakaneko** [comment]
should be fixed
