### ISSUE TITLE
User list view is broken in mobile

### ISSUE THREAD

**Issue by gagahpangeran** [ppy/osu-web#6517]
In mobile it's broken because of long username and supporter tag. Example : https://osu.ppy.sh/groups/4?view=list

![image](https://user-images.githubusercontent.com/4964985/90662245-521cf500-e272-11ea-9da0-765f017b5900.png)

**Comment by arflyte** [comment]
Hmm, the supporter tags are definitely taking up a lot of space. Maybe we can remove the supporter tags in mobile view for now. If the name still can't fit, we'll use ellipsis. I don't think we need the online status on mobile too.

**Comment by notbakaneko** [comment]
If anything, at 320px I think we should be losing the flag and have a more discreet online indicator

**Comment by arflyte** [comment]
I did think of removing the flags, but I felt that we should leave it there to differentiate users with similar names (I think). Online indicator can definitely be reduced to something else, like a single bar if we wanna keep it.

**Comment by notbakaneko** [comment]
In light of there now being _more icons than ever_ on the card, I think most of the icons, if not all, should disappear in list view on narrow screens. @arflyte 
320px wide can only realistically fit: avatar, flag, long name, _one_ icon, menu button.

**Comment by arflyte** [comment]
Let's just remove the supporter tags.

**Comment by notbakaneko** [comment]
that's not going to help because group badges and notification icons also exist 
![image](https://user-images.githubusercontent.com/1694544/113978333-cd253100-987e-11eb-95cd-3adcf0030d05.png)

**Comment by arflyte** [comment]
I mean, the ones that should remain would be avatar, flag, name and menu button. Not even sure if the group should stay.

**Comment by peppy** [comment]
For the user list, the mutual icon is quite important, so we *probably* want that to stay where it is.

If we are making changes local to the user list display and not globally, the flag can probably go as well. And the supporter icon.

**Comment by arflyte** [comment]
Yeah, thinking about it, it's probably okay to remove the flag.

**Comment by notbakaneko** [comment]
A bit squishy 🤔 

320px wide:
![image](https://user-images.githubusercontent.com/1694544/134461085-68a60954-bc53-4d22-a13c-6bae0fde6b3d.png)

375px: 
![image](https://user-images.githubusercontent.com/1694544/134461230-9c064569-1771-449f-b231-0e671f1edfed.png)
