### ISSUE TITLE
Score calculation problem when lagging at the end of beatmap

### ISSUE THREAD

**Issue by heagan01** [ppy/osu-web#6518]
When I play beatmaps, I tend to lag, but when I lag on the last part of the map, It shows a notification saying: "Score calculation failed". But when I lag at the beginning / the middle of the map, it doesn't show the notification

**Comment by peppy** [comment]
Please follow this guide to attempt to fix your lag issues https://osu.ppy.sh/help/wiki/Performance_Troubleshooting
