### ISSUE TITLE
More consistent backspace/delete behavior on discussion review editor

### ISSUE THREAD

**Issue by nanaya** [ppy/osu-web#6520]
Currently, both delete and backspace behave differently depending on the current and adjacent blocks

### backspace
previous | current | result
---|---|---
empty | empty | deletes current block
empty | filled | deletes previous block &larr; :question: 
filled | empty | deletes current block
filled | filled | deletes current block, moves current text to previous &larr;  :question:  
none (current is first) | empty | deletes current block

### delete
current | next | result
---|---|---
empty | empty | deletes current block
empty | filled | deletes current block
filled | empty | deletes next block &larr;  :question: 
filled | filled | deletes next block, moves next text to current &larr;  :question: 
empty | none (current is last) | deletes current block

I think at least when current is empty, both backspace and delete should delete current block. I'm not sure about filled/filled, backspace's empty/filled, and delete's filled/empty situation though.

**Comment by nekodex** [comment]
related: #6460

**Comment by notbakaneko** [comment]
Honestly, I'd expect delete to always remove whatever is in front of the cursor and backspace to always remove what's behind it, and both to delete the current selection.

At the moment, if the current line is an empty paragraph, it removes the paragraph and moves into the next block - if it's not an empty paragraph, it collapses the next block into the paragraph, however, if it's not a paragraph (but still empty), it always collapses the next block into it; I think this difference makes it unintuitive w.r.t to the cursor.

If deleting in an empty block should remove the block, then I'd expect pressing delete at the end of the block should not be collapsing the next block into it - in this case the block is treated as a visual enclosure and both backspace and delete should remove the current block, only if it is empty, and not remove any adjacent blocks. Paragraphs don't have the same visual encapsulation so this wouldn't apply to them.

Right now it seems like the behaviour is all over the place making it uncertain what pressing either key is supposed to do in context.

**Comment by nanaya** [comment]
Deleting and backspacing current empty block have been fixed to behave as expected. The rest are a bit of lower priority and I think it's fine at the moment. Anyone who find this behaviour confusing can comment on this or open a new issue.
