### ISSUE TITLE
Unexpected pp is awarded on some taiko beatmaps

### ISSUE THREAD

**Issue by pavlukivan** [ppy/osu-web#6522]
https://osu.ppy.sh/b/2495119

top 1 score from Peaceful with HD, 53 100s and 3 misses has less pp than Consified's score with NM 2 misses and 67 100s. Usually Taiko pp doesn't account for combo - it seems that wasn't the case for at least this score for whatever reason. At the very least it should be recalculated. Correct values can be calculated with https://mon.im/taikopp/ (it works, but doesn't account for double rounding on both api and osu! site)

**Comment by smoogipoo** [comment]
As it turns out, this has been the case for all maps newer than 2018. There's already a PR on osu-performance to address this (https://github.com/ppy/osu-performance/pull/117), but I'm waiting until the SR changes get in along-side it, which should happen either this month or the next.

**Comment by pavlukivan** [comment]
so it happened because of switching to lazer pp calc?

**Comment by smoogipoo** [comment]
No, it happened because of a change to stable in 2018 which fixed the combo not being populated server side.

**Comment by pavlukivan** [comment]
...this is the first time the issue happened though

**Comment by pavlukivan** [comment]
also the pp values on this map https://osu.ppy.sh/b/2565627 seem to match, so I don't think it's an issue with more than one map/score

**Comment by smoogipoo** [comment]
Thanks. I've checked the stable difficulty calculator again and it does seem to not write the max combo, so your assessment that this is coming from lazer is correct.

We're still going to wait for the upcoming changes anyway to avoid reprocessing multiple times.

**Comment by smoogipoo** [comment]
Just to clarify a bit further. This issue has since been fixed, it's only a few beatmaps that were affected.

**Comment by pavlukivan** [comment]
Can you at least recalculate the map I linked in the first post?

**Comment by peppy** [comment]
It will be done as part of the batch recalculation. I'm not sure what the hurry is. Everyone is still on a level playing field.
