### ISSUE TITLE
Email notification bugging

### ISSUE THREAD

**Issue by UmaruPChan** [ppy/osu-web#6531]
So i have a problem about Email notification where the email from osu! keep coming to my inbox, i already disable it on my account settings but the email keeps coming in

Please fix

**Comment by peppy** [comment]
Can you take a screenshot of the emails you are receiving, and your settings page?

**Comment by UmaruPChan** [comment]
![Screenshot_2020-08-20-17-36-10-500_com android chrome](https://user-images.githubusercontent.com/50126684/90870352-0c743f80-e3cc-11ea-943d-54fab5df4b5f.png)

**Comment by nanaya** [comment]
What notification are you getting?

**Comment by UmaruPChan** [comment]
I guess it's beatmap email notification?
i got this email right after i switch off all email notification on account settings

![Screenshot_2020-08-21-16-43-41-433_com google android gm](https://user-images.githubusercontent.com/50126684/90871557-d6d05600-e3cd-11ea-9d31-1dd455102809.png)

**Comment by nanaya** [comment]
That says yesterday, are you still getting more since?

**Comment by UmaruPChan** [comment]
yeah it's yesterday, and now i think it's fixed because i didn't get any email from osu again
