### ISSUE TITLE
Don't register deleted scores in players' recent tab

### ISSUE THREAD

**Issue by TechnoZamb** [ppy/osu-web#6533]
I'm just kind of tired of seeing popular scores sniped by hackers in popular player's profiles (for example chocomint gets sniped on freedom dive multiple times a day according to recent). Make it so if a score is deleted then the "player lost #1" message is also deleted.

**Comment by nanaya** [comment]
This requires recording score id which generates the event and then removing the event when the score is deleted.

Neither of which are done through osu-web, I think.

**Comment by peppy** [comment]
Hmm, I see. Will look into this from my end (can probably nuke the event rows quite easily when a delete is triggered).

**Comment by peppy** [comment]
This has been resolved via changes to our internal tooling.
