### ISSUE TITLE
Mapsets with .ogg as audio source preview's don't work

### ISSUE THREAD

**Issue by NevarrenF** [ppy/osu-web#6535]
Basically if a map uses a .ogg as the audio source the preview point does not work on the site. 
Example: https://osu.ppy.sh/beatmapsets/1236584#osu/2570400 and  https://osu.ppy.sh/beatmapsets/1240989#osu/2579955

**Comment by nanaya** [comment]
The preview isn't in expected place (`b/preview/:id.mp3`) and changing the extension to `.ogg` doesn't help :shrug:

**Comment by Phippe** [comment]
Might be related to #5955, although apart from _Holy Orders_, all the songs listed there are `.mp3`.

**Comment by peppy** [comment]
These two beatmaps are fixed now. Any others will need to be manually fixed. A resubmission via BSS will also fix existing uploads if they are not yet ranked.

Please leave set IDs if you would like specific beatmaps reprocessed in the mean time. We will do a batch pass on every map in the near future.
