### ISSUE TITLE
Multiplayer rooms should provide an RNG seed

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-web#6536]
Relates to https://github.com/ppy/osu/issues/9967

Should probably be on a playlist item level, which the client could use to seed various things (e.g. the random mod in mania).

**Comment by nanaya** [comment]
If it doesn't need to be truly random, there's playlist item id (or some combination of static data like id, room, beatmap, and creation time) :thinking:

**Comment by smoogipoo** [comment]
Yeah, I think playlist item id works.
