### ISSUE TITLE
Multiplayer leaderboard should also return the user's score

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-web#6540]
E.g. `/rooms/27188/leaderboard` should return the top 50 + the user's own aggregate score in the room.

**Comment by nanaya** [comment]
It looks like there's currently no way to add that because it returns an array. Appending/prepending user own score to that array would be just weird.

**Comment by smoogipoo** [comment]
Yeah, it'd be a bit of a breaking change, not sure how bad that is though (I think loctav's the only one other than lazer hitting that API, and even then I'm not sure he is instead of per-playlist-item API)?

**Comment by notbakaneko** [comment]
we're going to eventually have to stop returning lists as plain top-level arrays, anyway, to add cursors and other metadata.
