### ISSUE TITLE
Beatmap set APIv2 endpoint can return uneven fail/exit counts

### ISSUE THREAD

**Issue by bdach** [ppy/osu-web#6543]
Detected lazer-side at ppy/osu#9937.

Hitting `https://osu.ppy.sh/api/v2/beatmapsets/1205458` from lazer returns the [following response](https://gist.github.com/bdach/73cb6d790e53a7b588f0961c50506185). The point of note here is `beatmaps[0].failtimes`, which has a `fail` array property of length 100, but no corresponding `exit` property of the same length. Note that the converts are fine.

Unsure if it's an actual issue or if it's by design as the endpoint in question seems to be undocumented but it might be worth investigating. I'll probably add a guard for this lazer-side but I'm not quite sure how this response is to be interpreted generally (seems that if missing, zeroes should be assumed?)

**Comment by nanaya** [comment]
Web doesn't do anything with the data. It returns whatever stored in database as is and web doesn't create those data.

**Comment by bdach** [comment]
Alright, fair enough. Not sure whether to direct this somewhere else but clearly here isn't the right place. Thanks.

**Comment by nanaya** [comment]
Also the ones with missing exit just means they're missing from database.

**Comment by nanaya** [comment]
Looking again, the title is confusing. It implies the count might differ but it's impossible (the code always builds array of length 100). Either there's an array or there's none. (again, if both are always needed, it could be done - those will be just all zeros)

**Comment by bdach** [comment]
Also true. Couldn't find a better phrasing for the title.
