### ISSUE TITLE
The game doesn't work

### ISSUE THREAD

**Issue by Layla-Lux** [ppy/osu-web#6548]
Umm I have a bit of a problem I tried to install osu on both my tablet and phone the installation went fine but everytime I try to open it's just a black screen then it closes by itself idk what happend if someone has a solution please tell me!!!

**Comment by peppy** [comment]
You're in the wrong place.

osu! (pc): https://osu.ppy.sh/community/forums/5
mobile: either lazer or some unofficial build.
