### ISSUE TITLE
Delete and Nominate Buttons shouldn't be right next to one another

### ISSUE THREAD

**Issue by Okorin** [ppy/osu-web#6550]
If you have the BN and GMT/NAT Usergroup, nominating a map will look like this:
![example](https://i.imgur.com/dEwC0T2.png)

both the nominate button and delete button will ask the user whether or not they're sure of what they're doing. This is all fine, but the messages and buttons are so similar and close together that it's basically an accident just waiting to happen (wanted to nominate a map? Whoops, it's gone)

Can you swap this button's position with the "Lock discussion" button which is far less destructive if misfired?

**Comment by peppy** [comment]
The buttons aren't even different colours. What a fucked up UX.

Let's make this top priority to fix.

**Comment by cl8n** [comment]
would be nice if Love button can get different color too, since you need to contact admin to "undo" that if you mess up

![image](https://user-images.githubusercontent.com/9954349/91216336-9f61f200-e6ca-11ea-85c8-07afb6961327.png)
