### ISSUE TITLE
Mail forwarding on unread messages treated same as private messages

### ISSUE THREAD

**Issue by polygonalenippel** [ppy/osu-web#6551]
I haven't played in many years but it looks like the line between BBS private messages and IRC messages got blurred.
So if an unread message on bancho is not read within a few hours, it gets forwarded by mail as if it were exactly the same as a private message (2015 era osu).

As a matter of fact I can turn off the mails, but this simultaneously stops forwarding private messages, which is insane.

Which mentally challenged developer thought this was a good idea? Are you weebs this serotonin deprived and lonely you crave attention from 8 digits spamming invites in #lobby? Did any of you coincidentally read up on a course of modern advertising, thinking spamming a personal mailbox is the best way to seek user attention?

I suggest to bring back the old behavior, thereby considering them as two separate means of communication and including an option whether to forward stale bancho messages to mail.

**Comment by polygonalenippel** [comment]
Alright I was angry when I posted this, but my point still stands. Please reconsider the notifications.

**Comment by cl8n** [comment]
what you want is emails for the forum pms (old site) but no emails for chat/IRC, right?

on https://old.ppy.sh/forum/ucp.php?i=prefs&mode=personal, select "Yes" for "Notify me on new private messages:"
on https://osu.ppy.sh/home/account/edit, uncheck the "mail" box for "private chat messages"

**Comment by polygonalenippel** [comment]
@cl8n Thank you, this was exactly what I was looking for.
