### ISSUE TITLE
only 4 of top 100 plays showing

### ISSUE THREAD

**Issue by aesien** [ppy/osu-web#6552]
this only applies to me (and a few others, according to people i have spoken to, although i do not know the profiles). on the website, only 4 of my top 100 plays are showing and i do not have a "show more" option either, as shown in the image below. you can also check [my osu! profile](https://osu.ppy.sh/users/11922986) to see the exact issue yourselves. 
![_](https://user-images.githubusercontent.com/55908282/91255047-baf3e980-e718-11ea-8672-30bbd27e254f.PNG)

**Comment by tybug** [comment]
same problem as https://github.com/ppy/osu-web/issues/6474 I think, which doesn't seem to have been fixed? the [user linked there](https://osu.ppy.sh/users/8908387) only has 3 top plays showing on the new site

**Comment by peppy** [comment]
Should be fixed. Is a caching issue with previously restricted users.
