### ISSUE TITLE
Audio player is present on every thread

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#6557]
I am using a stylesheet that makes bottom bar transparent and noticed the audio player is present on every thread, hidden behind the bottom bar.

![](https://i.imgur.com/nemQw5Y.png)

If you inspect element and remove the bar you can clearly see it

![](https://i.imgur.com/DpbU4B6.png)

**Comment by nanaya** [comment]
Yeah, that is by design. If you know of better way feel free to PR it but otherwise it's just as intended.
