### ISSUE TITLE
Beatmap page data display issues (for lack of a better title)

### ISSUE THREAD

**Issue by tilda** [ppy/osu-web#6570]
GIF that shows bug in action:
![YHlqgGOK6P](https://user-images.githubusercontent.com/8301262/91612312-c1fe4000-e942-11ea-8748-7221a4a33c2b.gif)

I used [my own beatmap](https://osu.ppy.sh/beatmapsets/1221830#osu/2541504) but this should be reproducible on other sets as well.

Steps to reproduce:

1. Click on another difficulty in the set that has no data available (as of this issue's filing it would be the Normal difficulty on my set)
2. Go to a difficulty that *does* have data available (Extra diff on my set has some)
3. Notice failure points don't show at all (if you refresh the page on the Extra diff, it should show again)

I'm on Microsoft Edge, version 84.0.522.63.

Please let me know if more information is needed, thanks!

**Comment by peppy** [comment]
Result of the recent changes to this area maybe?
