### ISSUE TITLE
User Profile Best Performance section's weighted percentages are not shown for turkish language

### ISSUE THREAD

**Issue by Eroo36** [ppy/osu-web#6573]
![chrome_VixtnNuIUv](https://user-images.githubusercontent.com/13486466/91663650-e862dd80-eaf2-11ea-8ca8-d19e962a9edb.png)

Tried on other browsers just to be sure

**Comment by Gabixel** [comment]
I guess the problem is [in the translation itself](https://crowdin.com/translate/osu-web/47/en-tr#1934): (the _percentage_ variable is missing)
![image](https://user-images.githubusercontent.com/43073074/91663894-dc275200-eaeb-11ea-80ca-876520c05016.png)

**Comment by Gabixel** [comment]
@Eroo36 do you think this translation is correct? (":percentage" becomes the percentage value when viewed from the website: for example, "ağırlıklı: 96%")
![image](https://user-images.githubusercontent.com/43073074/91663976-58219a00-eaec-11ea-9911-80325625ffab.png)

**Comment by Eroo36** [comment]
well "ağırlıklı yüzde %96" would make more sense in my opinion cause 'ağırlıklı' is by itself is not really weighted more like weight.

**Comment by zeusminus** [comment]
> well "ağırlıklı yüzde %96" would make more sense in my opinion cause 'ağırlıklı' is by itself is not really weighted more like weight. But should be also okay with the way you said.

I think the correct order should be ":percentage ağırlıklı" instead, since the percentage here is supposed to project how much weighted the score is.

**Comment by Eroo36** [comment]
> > well "ağırlıklı yüzde %96" would make more sense in my opinion cause 'ağırlıklı' is by itself is not really weighted more like weight. But should be also okay with the way you said.
> 
> I think the correct order should be ":percentage ağırlıklı" instead, since the percentage here is supposed to project how much weighted the score is.

yep posted accordingly on crowdin
