### ISSUE TITLE
Chat notifications do not update on website.

### ISSUE THREAD

**Issue by iiyosomu** [ppy/osu-web#6590]
So for some reason the chat notifications stay on 0 the whole time next to the chat icon, and in the past couple months I have missed requests from people that i would've otherwise seen.

I'm not sure if I'm the only one with this issue but i don't want notification alerts, only the number to update when there is a new message in-game so this just makes that useless unless i check it 24/7 which i don't have time for.

Hopefully there is a fix for this.

**Comment by iiyosomu** [comment]
apparently I forgot push notifications exist, my apologies

**Comment by peppy** [comment]
Ah yes, if you turn off push they will not show up in the chat display. Maybe a weird UX but that's how it is for now.
