### ISSUE TITLE
Add Indonesian language in the beatmap search

### ISSUE THREAD

**Issue by heagan01** [ppy/osu-web#6598]
In the beatmap listing tab please add the Indonesian language in the language tab

**Comment by peppy** [comment]
Are there actually enough beatmaps to warrant this?

**Comment by heagan01** [comment]
How many beatmaps is actually necessary for the warrant?

**Comment by bdach** [comment]
#5852 is relevant here (or even a duplicate). A tagging system like one proposed at the end of that thread would render this sort of request no longer necessary going forward.

**Comment by heagan01** [comment]
Ok, thank you for your help

**Comment by peppy** [comment]
Will close this one for now.
