### ISSUE TITLE
400 Bad Request on oauth/token

### ISSUE THREAD

**Issue by shivaco** [ppy/osu-web#6602]
When attempting to use both [Authorization Code](https://osu.ppy.sh/docs/index.html#authorization-code-grant) and [Client Credentials](https://osu.ppy.sh/docs/index.html#client-credentials-grant) grants, I keep receiving a 400 Bad Request error with no additional traceback/information.

Client ID and secret when sent in query parameters are copied as-is from the [account settings page](https://osu.ppy.sh/home/account/edit#oauth). `scope` is set to `public`, and `grant_type` is set to `client_credentials`, as explicitly stated in [the documentation](https://user-images.githubusercontent.com/22858781/92275069-3b33ff00-ef10-11ea-868c-fe017d47caae.png).

The same response is sent regardless of any of the query parameters OR headers:
```html
<html>

<head>
	<title>400 Bad Request</title>
</head>

<body>
	<center>
		<h1>400 Bad Request</h1>
	</center>
	<hr>
	<center>cloudflare</center>
</body>

</html>
```

**Comment by peppy** [comment]
have you checked these two?

https://github.com/ppy/osu-web/issues/6440
https://github.com/ppy/osu-web/issues/5872

**Comment by shivaco** [comment]
Interestingly, I'm still getting the same response.
![image](https://user-images.githubusercontent.com/22858781/92277930-eabfa000-ef15-11ea-94dd-11536d5d532b.png)

**Comment by peppy** [comment]
Very weird. Also doubly weird that you're getting back html. Are you sure you are specifying the content type as json in the headers?

```
      'Accept': 'application/json',
      'Content-Type': 'application/json'
```

**Comment by shivaco** [comment]
Postman seems rather weird when it comes to sending JSON in the request body, I believe.

I just sent a manual request with Python's `aiohttp` module and got a proper response. In any case, my case is solved and I am closing this issue. Thank you very much!
![image](https://user-images.githubusercontent.com/22858781/92279334-e3e65c80-ef18-11ea-87b0-3ce44d7ae7d7.png)
