### ISSUE TITLE
Request Button to delete all of the notifications history

### ISSUE THREAD

**Issue by troke12** [ppy/osu-web#6621]
is that possible to delete all of the notification history?

**Comment by peppy** [comment]
There's a button for this. Please confirm this works, and if not, what you are expecting and what is not happening.

![image](https://user-images.githubusercontent.com/191335/92683477-ee1bb700-f36d-11ea-9f4c-e63a662398eb.png)

**Comment by troke12** [comment]
it's only clear on that, not clear in this section : 
<details>
<summary>Screenshot</summary>

![ss](https://cdn.discordapp.com/attachments/701452257102921738/753480409928433665/unknown.png)

</deatils>

**Comment by peppy** [comment]
So basically you're looking for a way to only show unread notifications on that page? Maybe a checkbox to hide read notifications would work?

**Comment by peppy** [comment]
On further discussion, but course of action may be:

- Change button `Clear all` -> `Mark all read`
- Add buttons to notification history page `Mark all read` `Clear all read` or thereabouts.

**Comment by troke12** [comment]
i would like to clear the history, but i think it's okay to add a checkbox for hide read notifications

**Comment by troke12** [comment]
also the ranges of notifications history should be shorter, it's 50 change to 25 maybe? looks like to much for me
