### ISSUE TITLE
Sorting by playcount for Pending/WIP/Graveyard has inconsistent results

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#6629]
Initially it will appear fine, but the further down you go, the more inaccurate sorting by playcount is for these categories. For instance I scrolled down around 3 screens and it starts looking like this->
![image](https://user-images.githubusercontent.com/33286824/92768283-e22bf700-f365-11ea-83de-a691fd41f282.png)
In the above screenshot, Doraemon and Shine are sorted below Amazing Break, despite having 14k plays while Amazing Break has 13k

this happens in differing amounts as you go down
![image](https://user-images.githubusercontent.com/33286824/92768434-04be1000-f366-11ea-8b1a-63696722b156.png)
Circles is sorted 2 maps lower than it should be, while the positions of the bottom two in this screenshot are flip-flopped

this issue gets even more prelevant in specific searches where playcounts are overall low or maps have no playcount, such as in this screenshot of maps from my "my maps" filter, where the playcount sorting is way off
![image](https://user-images.githubusercontent.com/33286824/92768927-79914a00-f366-11ea-9821-18ec3dbef4b4.png)

Additional example with a "vocaloid" search where after the first few results, the sorting gets messier
![image](https://user-images.githubusercontent.com/33286824/92769625-2b307b00-f367-11ea-8bed-ba6103ec3ec7.png)

It doesn't seem like this feature is fully working as it should at the moment and could be optimized for better accuracy.

**Comment by cl8n** [comment]
duplicate of #6442

**Comment by dorothy3242** [comment]
gasp how did i miss this
