### ISSUE TITLE
Recent scores counter disappears when theres atleast 1 score

### ISSUE THREAD

**Issue by lmnyx** [ppy/osu-web#6633]
![e](https://user-images.githubusercontent.com/13962537/93001472-9dac8100-f548-11ea-8592-3c818d62ef10.png)
![e](https://user-images.githubusercontent.com/13962537/93001474-a604bc00-f548-11ea-8cd3-f91303d58436.png)

**Comment by cl8n** [comment]
this is intentional, it's supposed to tell you there are no recent plays, I think I'd rather it show an actual message or just hide the section entirely though

**Comment by lmnyx** [comment]
Then it's pretty unconsistent usage, because for example in beatmaps section of profile even when theres >0 maps it still shows number.
![exm](https://user-images.githubusercontent.com/13962537/94040300-31e8d480-fde2-11ea-95d5-9c0cdecde3f2.png)

**Comment by peppy** [comment]
I'm thinking it should either always or never be there?

**Comment by lmnyx** [comment]
I think if it always will be here it will be useful, you don't need to go deep scrolling to understand that there's a lot of items i.e.
