### ISSUE TITLE
User card can't find users who renamed

### ISSUE THREAD

**Issue by pishifat** [ppy/osu-web#6637]
https://osu.ppy.sh/users/Byakugan249 this link will show
![](https://i.imgur.com/wg8zmVO.png)

but loading it will go to the correct user: https://osu.ppy.sh/users/660484

**Comment by Gabixel** [comment]
This is "intentional" (or a limitation), I think. The [osu! BBCode wiki page](https://osu.ppy.sh/help/wiki/BBCode#profile) says:
> Usage of this button is **heavily discouraged**! The problem with using this tag is that user names can be changed once after obtaining an [osu!supporter tag](https://osu.ppy.sh/help/wiki/osu!supporter). And once they do, the link will fail.
> 
> It is recommended to use [URL](https://osu.ppy.sh/help/wiki/BBCode#url) instead (using the user's id number).

**Comment by peppy** [comment]
We can probably fix user cards via a better lookup.
