### ISSUE TITLE
backgrounds of brick user cards are distracting

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#6647]
probably more of a personal nitpick if anything but posting here to see if anyone else feels the same way. the brick user cards show user banners in the background, but they're so small that I can barely tell what any of them are, and it ends up looking more like random colors that make the text stand out less for no reason

[with background (current)](https://user-images.githubusercontent.com/9954349/93160957-58ae5900-f6c6-11ea-90c2-a750ec25ccb1.png) vs [without background](https://user-images.githubusercontent.com/9954349/93160966-5f3cd080-f6c6-11ea-8244-3d7133339c0c.png)

I find that without the backgrounds it's a bit easier to visually parse a large list. it would also make the page load faster without all of the images

**Comment by peppy** [comment]
I think without is better. Especially since they are loading quite large versions of the images currently (we don't generate any small enough for usage in these bricks).
