### ISSUE TITLE
List ranked maps for each song in the featured artist listing

### ISSUE THREAD

**Issue by iptq** [ppy/osu-web#6656]
This would be useful for discovering maps for certain songs, as well as finding songs that don't have ranked maps for mapping. The mappers' guild database should have this information, but I don't know where that lives or whether or not it's available to the web-facing app in the osu-web repo.

![image](https://user-images.githubusercontent.com/1700346/93283954-19186780-f7c1-11ea-8e5d-68b190efb31c.png)

**Comment by cl8n** [comment]
this is one of the bullet points in #3777

**Comment by iptq** [comment]
Dammit I can't read
