### ISSUE TITLE
Audio Player shows zero as total length

### ISSUE THREAD

**Issue by Gabixel** [ppy/osu-web#6659]
Audio players seem to show `0:00` as their total length:

![Zero length total](https://user-images.githubusercontent.com/43073074/93335454-c40f3c80-f826-11ea-8e28-d13451b1e129.png)
---
And the correct total value appears when you start the track:

![Updated length total](https://user-images.githubusercontent.com/43073074/93335582-fae55280-f826-11ea-914e-3ee58a1950c1.png)

**Comment by peppy** [comment]
This is because your browser is choosing not to load the audio files ahead of time so it can't know the length of the track. We don't have this metadata anywhere and adding it may be more effort than it's worth.

**Comment by nanaya** [comment]
The default can probably be set to `-:--` (or something in that effect)
