### ISSUE TITLE
Qualified Queue position is not kept on maps previously qualified >7 days

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#6661]
An example would be this beatmap: https://osu.ppy.sh/beatmapsets/1246982#osu/2591930

It was initially qualified September 5th, disqualified September 14th after 9 days in qualified. 
It was requalified September 16th, and is now estimated to rank September **19th**.

On getting requalified, it should have had around ~1 day more in qualified, as it was previously the 5th map in line to be Ranked. However it instead is getting another **3 full days** in qualified. It seems this is because it went back to being on it's "6 days so far in the queue" position instead of giving it a regular ~24 hours more in qualified.

I assume this is because however the queuing is written in these cases did not account much for maps going over typical queue time? It certainly doesn't seem right.

As qualified is currently on 9-10 days average for standard maps right now, this should be looked at as this map will likely not be the last case like this.

**Comment by cl8n** [comment]
seems intended, a map can only skip up to 6 days of queue time to make sure it has at least 1 day of waiting before ranked, if there's already a bunch of maps queued before 6 days ago it'll be waiting behind them too. if you set the queue time further back than 6 days on purpose to put it in the same position as before, there's a chance that if some other maps are DQd you'd get this map ranked in <1 day

bumping overdue maps out of the way for a re-qualified one seems kinda odd to me anyway

**Comment by dorothy3242** [comment]
I think clayton's explanation makes sense as to why it is how it is now so I'm gonna close this
