### ISSUE TITLE
Bug in the hungarian version of the "scores" page

### ISSUE THREAD

**Issue by farkasma** [ppy/osu-web#6669]
So probably something got messed up during translation, but I'm not sure. Basically the part where the song artists name would go now reads "mapped by [x player]" and it always says x player, so that's why I'm suspicious about the translation going wrong.
Here's a screencap about the thing.
![Képernyőkép 2020-09-17 165233](https://user-images.githubusercontent.com/33036336/93488057-3a36a080-f906-11ea-84a7-f8b3ac0489ac.png)

**Comment by nanaya** [comment]
Someone with Hungarian knowledge should fix it directly [in crowdin](https://crowdin.com/translate/osu-web/302/en-hu?filter=basic&value=0#10634).

**Comment by farkasma** [comment]
I submitted a different translation, that I think is correct, now it just needs upvotes.

**Comment by nanaya** [comment]
You may want to check the translation for "Played by" as well (see my comment in there)

https://crowdin.com/translate/osu-web/302/en-hu?filter=basic&value=0#10636

**Comment by farkasma** [comment]
I might start crawling through the translations again... Thanks for the heads up!

**Comment by nanaya** [comment]
Thanks!
