### ISSUE TITLE
Comments box is focused on loading news page

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#6670]
May be iPadOS specific, can't reproduce on iPhone.

![ezgif com-optimize](https://user-images.githubusercontent.com/191335/93491317-87d1fe00-f944-11ea-883c-96e966cc0f29.gif)

**Comment by notbakaneko** [comment]
Appears to be iOS-related when a hardware keyboard is connected and something has previously activated keyboard input.
It also happens on phones if a hardware keyboard is connected
- it will still happen if the keyboard is disconnected until something is done to reset the input for safari.
- it doesn't happen if the keyboard is just connected without typing anything into it.
