### ISSUE TITLE
allow option to show beatmaps that have been taken down in beatmap listing in user settings

### ISSUE THREAD

**Issue by igontusuwu** [ppy/osu-web#6674]
the idea here is to be able to access scores and info on taken down beatmaps without having to go a longer route to find said scores on a taken down beatmap

this should be a option so that you don't have to see taken down beatmaps clutter the listing

**Comment by peppy** [comment]
If you're asking to find them via searching, then this is by design. One of the reasons for removal is that an artist does not want their name to be listed. We delist it intentionally based on this feedback.

This is non-negotiable.
