### ISSUE TITLE
Beatmap Page doesn't display anything

### ISSUE THREAD

**Issue by c-sig** [ppy/osu-web#6677]
The beatmap page just looks like this:
![image](https://user-images.githubusercontent.com/61018516/93665980-2bd6b900-faad-11ea-9824-b854511d047c.png)

I am still able to download the whole mapset but anything about the said mapset isn't represented at all on the page.

Another instance is https://osu.ppy.sh/beatmapsets/910378#osu/2524978

The only thing I did to reproduce this was uploading a map with the same metadata on https://osu.ppy.sh/beatmapsets/1213183#osu/2525002 where the original map got its page broken directly after. Although I'm not sure if this was correlation or causation.

**Comment by aspriddell** [comment]
fwiw the map in the screenshot (https://osu.ppy.sh/beatmapsets/1212251#osu/2606260) is listed on the mapper's page as graveyarded, whereas it's marked as WIP on the map info page:

![image](https://user-images.githubusercontent.com/10289119/93685485-a8669900-faa7-11ea-8c5f-3e54da20ae83.png)

**Comment by peppy** [comment]
Have fixed this. Please re-submit the beatmaps if they are intended to exist.
