### ISSUE TITLE
osu!taiko hardest map haven't been updated to use the new sr

### ISSUE THREAD

**Issue by lolxdhi1** [ppy/osu-web#6679]
When I went to check the highest sr maps, I saw that the maps were organised using the old sr system, even though the sr shown was the new one. This ended up in the top 5 hardest maps according to the current highest sr maps list being 8.29*, 8.72*, 9.46*, 9.37* and 8.14* 

Another problem that I have witnessed during my examinations is that maps 3 and 4 in the list (holy bitch and genjuro's ng+) haven't had their sr recalculated using the new sr system.

**Comment by peppy** [comment]
please include URLs to the beatmaps.

**Comment by lolxdhi1** [comment]
ok, here they are
https://osu.ppy.sh/beatmapsets/1037726
https://osu.ppy.sh/beatmapsets/1249951
https://osu.ppy.sh/beatmapsets/1236758
https://osu.ppy.sh/beatmapsets/833092
https://osu.ppy.sh/beatmapsets/1057894

**Comment by peppy** [comment]
https://osu.ppy.sh/beatmapsets/1037726#taiko/2169457 the first in your list is listed as 8.14*, which matches the new star rating calcualtion. What are you expecting in this case?

**Comment by peppy** [comment]
I've re-run the processor and the above look correct now. Can you confirm?

**Comment by lolxdhi1** [comment]
Yes
