### ISSUE TITLE
Add 'new sort' by in BN pages by game mode they're nominated

### ISSUE THREAD

**Issue by 1210al** [ppy/osu-web#6681]
I referred to this page : https://osu.ppy.sh/groups/28

It would be helpful in my opinion especially with new mappers when they searched bn for nominated.

**Comment by Nivalyx** [comment]
you can look up for bns by their status and game modes already through this site : [bn.mappersguild.com](http://bn.mappersguild.com/)

**Comment by peppy** [comment]
Going to milestone this as generally part of https://github.com/ppy/osu-web/issues/6688 and related issues.

**Comment by nanaya** [comment]
Not sure how this and #6688 are related...?

**Comment by peppy** [comment]
Meant #6689 sorry. The general concept of per-ruleset BNs (and adding group/system support for them(
