### ISSUE TITLE
Purpose of Recaptcha (on every single login)

### ISSUE THREAD

**Issue by Endaris** [ppy/osu-web#6685]
Today I was met with a recaptcha on login for the first time and I'm a bit puzzled why it was added in the first place and also by the way it greets on every single login.

I'm not much of a web person but from what I read about recaptcha is that it calculates some kind of threat level based on whether I have a google account, a sufficient amount of google cookies and whether my browser behaviour is human based on what they collected through me browsing on websites that have recaptcha enabled and then decides whether you need to do a captcha check to proceed or not.
Furthermore I read that Google recommends to enable recaptcha on the entire website to improve the accuracy of the threat level estimation.
Personally I'm rather concerned by this from a privacy standpoint. I'm avoiding data collection where it is reasonably possible to do so and recaptcha popping up on osu! has me quite disturbed to say the least. Apart from the game content itself the fact that osu! has been independent and didn't have any kind of data grabs for 3rd parties (none I was aware of anyway) was always one of the major reasons to never second guess my decision to support osu! ever since I started to do so. The existence of similar services not feeding directly into google does not make me happier about this either although I lack the background to tell whether they're viable alternatives or not.
Additionally I'm personally a bit unsure whether the data collection by recaptcha needs to/should be included in osu!'s Privacy Policy as I haven't seen it there yet.

That much for my general thoughts about recaptcha.
To be fair I really wonder why it was added in the first place. Account protection? Don't think so, we already have 2FA for that. Or is there an actual bot problem on osu? If so, is it really necessary to force a recaptcha on every single login for people who like to browse osu! in private tabs (aka no google cookies = high enough threat level to have the captcha popping every single time)? I have seen that there is a some config value called 'captcha.threshold' by searching the codebase and based on my current experience it is most likely set to 0.

Sorry for this very general issue but I feel concerned about this and I couldn't find any considerations about the addition of captchas, neither in the repository nor in the #osu-web channel so I would greatly appreciate an informative reply about the scope of recaptcha on the website in terms of data collection, the motivation for adding it and whether requiring people like me to do a captcha for every login is really intended.

**Comment by jacksonisiah** [comment]
As for why they were added, see [peppy's thread on twitter](https://twitter.com/ppy/status/1306206497907470337?s=20) 

I can agree with your thoughts on Recaptcha itself, there are some different ones (such as [hcaptcha]( https://www.hcaptcha.com/)).

**Comment by peppy** [comment]
It is present when we need it. I am not about to announce every time we are combatting an issue that requires it.

If you dislike it to the point of not wishing to interact with the site, then please come back another day. I'm sorry but we do not have the bandwidth to get involved in political issues like this.

Also note that we have google analytics on every page until last month and no one complained for 13 years.
