### ISSUE TITLE
It's possible to break the review editor by removing un-editable sections within an embed

### ISSUE THREAD

**Issue by nekodex** [ppy/osu-web#6687]
In a chromium-based browser, it's possible to place the cursor inside of the stripe div (which has `contentEditable=false`), which on its own is harmless (albeit confusing) as typing moves the cursor to the correct position before inserting text. 

However when part of a selection, it's possible to cut (but not delete?) away the stripe div (even though it shouldn't be editable)... and upon subsequent input, Slate gets confused as to where to place text and explodes.

Example:
![contenteditable](https://user-images.githubusercontent.com/272140/94260096-828b3980-ff6a-11ea-98ac-65d0024db593.gif)

Seems related to these chromium bugs (and likely others):
https://bugs.chromium.org/p/chromium/issues/detail?id=688015
https://bugs.chromium.org/p/chromium/issues/detail?id=991399

I'm not sure if this is fixable without changing how embeds behave, two options are:
- reimplementing as [voids](https://docs.slatejs.org/concepts/02-nodes#voids) - at the cost of embed edits not going into the global editor-level undo/redo history and not being able to navigate outside the embed with arrow keys

or

- not having `contentEditable=true` set at a parental level - which also breaks arrow-key navigation between embeds/paragraphs

Neither of those options are particularly great, and there's no guarantee that other `contentEditable` issues won't rear their head with those fixes (there's _a lot_ of `contentEditable` related bugs in the chromium bug tracker)

... so I'm just going to make this issue to track it for now and hope that not too many users stumble upon this edge case.

**Comment by notbakaneko** [comment]
I think this was some what fixed during one the updates made to update slate
