### ISSUE TITLE
Contest page Cleartype font issue with Firefox

### ISSUE THREAD

**Issue by Akuba-** [ppy/osu-web#669]
The font on the contest page is barely readable using Firefox with enabled Cleartype on Windows:
[Cleartype enabled](http://up.akuba.eu/2016-07/31125430.png)
If I disable Cleartype it is readable again:
[Cleartype disabled](http://up.akuba.eu/2016-07/31130449.png)

I only have this issue with Firefox, Chrome looks fine, whether Cleartype enabled or not:
[Chrome](http://up.akuba.eu/2016-07/31130722.png)

**Comment by peppy** [comment]
I believe this should be fixed now. Please close if so.
