### ISSUE TITLE
Api documentation should mentation how you can filter leaderboards by country

### ISSUE THREAD

**Issue by InvisibleSymbol** [ppy/osu-web#6692]
https://osu.ppy.sh/docs/index.html#get-ranking doesn't mention anywhere that you can use the `country` parameter to filter by Country.

**Comment by Joehuu** [comment]
It does link [RankingType](https://osu.ppy.sh/docs/index.html#rankingtype) which has it, or am I missing something?

![image](https://user-images.githubusercontent.com/35318437/94368236-e19a9c80-0097-11eb-9f02-5e713f96e3bb.png)

![image](https://user-images.githubusercontent.com/35318437/94368158-a6986900-0097-11eb-8376-a3a4b2c16a23.png)

**Comment by InvisibleSymbol** [comment]
The ranking type "country" is [the list of countries by rank](https://osu.ppy.sh/rankings/osu/country) (for example us #1, ru #2). 
The parameter instead shows [the ranking of a country](https://osu.ppy.sh/rankings/osu/performance?country=JP), for example the top players of japan.
