### ISSUE TITLE
Set a max height for api responses in documentation page

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#6712]
https://osu.ppy.sh/docs/index.html#apiv2changelog takes up >50% of the page's size, and you have to scroll through all response before going to the next section. Setting a max width and having to scroll within could be a resolution.

**Comment by nanaya** [comment]
For now you can use the navigation panel on left side.

**Comment by tybug** [comment]
this might be able to be closed now that the changelog response on the docs sidebar has been massively reduced in size?

**Comment by Joehuu** [comment]
Yeah, can be closed now.
