### ISSUE TITLE
Multiaccounting are not allowed in osu!

### ISSUE THREAD

**Issue by alolanmeowth** [ppy/osu-web#6722]
Hey guys, Alolan Meowth here. Just to tell you a multiaccounting warning.
If this is your first account, don't EVER make a account ever again. It is a violation of the osu! rules.
Are you **username**? osu! has a policy of **one account per person**! Please be aware that creating more than one account per person may result in **permanent deactivation of all accounts**. If you forgot your password, then press "I have forgotten my password!"
Pressing "This new account isn't for me" will be like **NOTHING**.
If you scroll down to the page that says "Account Standing", it will say "Username's account is not in good standing :(" If you get 9 strikes, your account will be permanently banned if you continue to break the rules. Please make sure to follow the community rules! Note that infringements will disappear after four weeks of good behavior. If you see this, you are silenced for per an hour. The reason is: spamming a user [BanchoBot protection], Innapropiate conversation in #mode, multi-account creation/abuse. Username can't speak for another hour. The multi-account will be banned FOREVER. Bye!

**Comment by bdach** [comment]
This is already [explained on the wiki](https://osu.ppy.sh/help/wiki/Help_Centre/Account_Restrictions) [in multiple places](https://osu.ppy.sh/help/wiki/Rules). This issue tracker is not the place to issue such warnings, as it's used by the developers of the osu! website itself.
