### ISSUE TITLE
Can't zoom in contest fanart entries when clicking on them

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#6723]
Left clicking them should show a slideshow, but nothing happens and you can now see the link on the bottom left of the window.

![zKab7j27B8](https://user-images.githubusercontent.com/35318437/94980402-30a06180-04de-11eb-8f46-8ad47ed80d12.png)

**Comment by peppy** [comment]
I've hotfixed this but it does need a proper fix.
