### ISSUE TITLE
Account verification isn't required to send chat messages

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#6726]
It likely should be.

**Comment by nanaya** [comment]
Notifications may contain private messages as well. Should that require verification? (in which case we'll be requiring verification for everyone on login)

**Comment by peppy** [comment]
The important part is write operations. Notifications should be fine.

**Comment by notbakaneko** [comment]
#6688 is also going to need to be addressed otherwise the play count requirement is going to be pointless
