### ISSUE TITLE
Old Loved maps did not get moved to ModdingV2

### ISSUE THREAD

**Issue by huuishuu** [ppy/osu-web#6732]
Recently [Paradigm Shift by Avena](https://osu.ppy.sh/beatmapsets/432589) was removed from Loved as the mapper seeks to pursue Ranked status. However, seeing as the map was added to Loved before the migration to ModdingV2 - [the map still uses legacy forum posts](https://osu.ppy.sh/community/forums/topics/434079) and doesn't have a ModdingV2 thread (clicking "Discussion" on the map pages takes you to the linked forum thread). [This makes it impossible to "hype" the map](https://i.imgur.com/lsxLrUu.png), which is required for maps to be eligible for nomination.

The problem seems to stem from the fact that old Loved maps (pre-2018) are treated the same as Ranked maps and weren't migrated over to ModdingV2 which could pose a problem if a situation like this arises in the future where a mapper wants to remove their map from Loved and go for Ranked instead.

**Comment by dorothy3242** [comment]
In these cases I'm fairly sure all the mapper needs to do is ask Ephemeral to enable modding v2 on the map manually, though I agree it would be better if there was a more intuitive way this could be handled such as giving that switch power to the mapper.

**Comment by cl8n** [comment]
I was going to suggest that an added "unlove" button could move it to mv2 as well, but I guess you wouldn't be able to get to the loved buttons without mv2...

**Comment by huuishuu** [comment]
It skipped my mind entirely that this issue also prevents us from even re-adding this map to Loved in the future at all since the "Love" button is only available on mv2. Good catch.

**Comment by peppy** [comment]
Please contact myself or someone on the team and we'll fix these as necessary.
