### ISSUE TITLE
putting whatever you want in [profile] bbcode tag is allowed and return 400 bad request

### ISSUE THREAD

**Issue by lmnyx** [ppy/osu-web#6737]
![e](https://user-images.githubusercontent.com/13962537/95255250-83f61500-083a-11eb-862b-63b8db188bb7.png)
leaving also possibility for xss
upd : if put just dotes returns 403

**Comment by lmnyx** [comment]
Found possible XSS workaround: `data-user-id` is not encoding characters in profile tag

<details>
 <summary>How works & how found</summary>

This is how usually profile tag looks in HTML
![first](https://user-images.githubusercontent.com/13962537/95257500-d97ff100-083d-11eb-8e9f-44c4e4afe1fa.png)
Then by changing inner of tag to `"` i found that href is encoding symbols so its impossible to do it here, but data-user-id doesn't encode
![sec](https://user-images.githubusercontent.com/13962537/95257574-f288a200-083d-11eb-992a-7b0011727902.png)
And if we look at it closer we will find out that it uses `'`
![thr](https://user-images.githubusercontent.com/13962537/95257676-1ba93280-083e-11eb-89a2-c0aeaf15a374.png)
Now I just change the thing to `'>`
![fr](https://user-images.githubusercontent.com/13962537/95257732-34b1e380-083e-11eb-88fd-5b843c807b9a.png)
tada
![e](https://user-images.githubusercontent.com/13962537/95257758-3d0a1e80-083e-11eb-9ec0-97f8e7ae0be7.png)
</details>

**Comment by bdach** [comment]
if this indeed is an XSS vulnerability it is very irresponsible to disclose it on a public issue tracker in such a manner.

**Comment by lmnyx** [comment]
Really needed to think about that before, truly. I'll delete the second message. My bad
