### ISSUE TITLE
Wrong combo is marked as Perfect

### ISSUE THREAD

**Issue by Wieku** [ppy/osu-web#6752]
I don't know if it's a client or web issue, but I assume it's a web one.

There is a map: https://osu.ppy.sh/beatmapsets/103862#osu/275266

Perfect in the osu-stable client gives you 484 combo (tested with Auto as well), but according to web page and api Perfect combo is 483:
![image](https://user-images.githubusercontent.com/5307179/95579162-6a6ced00-0a35-11eb-8900-17717828a035.png)
![image](https://user-images.githubusercontent.com/5307179/95579075-3abde500-0a35-11eb-8d82-8c6ad3d900e7.png)
![image](https://user-images.githubusercontent.com/5307179/95579092-490c0100-0a35-11eb-9f83-7aa691618ad7.png)

I know there is an osu-stable issue that gives extra combo when audio offset is not 0, but my offset was 0.

**Comment by nanaya** [comment]
That map is recorded as having 483 max combo in the database. Something with difficulty processor? @peppy 

(that said, the pages probably should be updated to check `perfect` attribute instead)

**Comment by peppy** [comment]
@smoogipoo can you take a look at this? i recall we may have not been propagating new max combo updates to database, but not sure if that's the reason this is wrong.

**Comment by smoogipoo** [comment]
@peppy Something seems wrong with that beatmap. The .osu from updating the beatmap (and via `https://osu.ppy.sh/osu/{id}`) does not match the .osu in the .osz. This also leads to the "update beatmap" button in song select never going away no matter how much you click it.

**Comment by alolanraichulive** [comment]
this should be resolved in a hour. the beatmap is glitchy on the website when Nikliu reached 22nd place

**Comment by Ephemeralis** [comment]
This should be fixed now.
