### ISSUE TITLE
Why does mania not have anyone ranked #14??

### ISSUE THREAD

**Issue by edgy01** [ppy/osu-web#6759]
I looked at the rank leaderboard and its looks fine but when you check there profiles you can see no one at rank #14
![Screenshot (1)](https://user-images.githubusercontent.com/72818059/95894899-ca2a0780-0d57-11eb-8e6c-8f0e12c2b026.png)
![Screenshot (2)](https://user-images.githubusercontent.com/72818059/95894902-cb5b3480-0d57-11eb-81c3-4a24c1b79b50.png)
![Screenshot (3)](https://user-images.githubusercontent.com/72818059/95894907-cc8c6180-0d57-11eb-9fed-c34cebf98b00.png)

**Comment by edgy01** [comment]
when you press #14 on the leaderboard it shows the 15th player

**Comment by edgy01** [comment]
Wait why are there two people ranked 29?
![Screenshot (4)](https://user-images.githubusercontent.com/72818059/95895574-e0849300-0d58-11eb-89f2-8d89b996a048.png)
![Screenshot (5)](https://user-images.githubusercontent.com/72818059/95895585-e2e6ed00-0d58-11eb-9649-e3bc055d862c.png)

**Comment by zeusminus** [comment]
"Global Ranking" section on userpages are usually known to be inaccurate in general for some reason. Referring to the leaderboards for a more accurate ranking information works, as far as I can tell.

**Comment by notbakaneko** [comment]
Global rank on the user profile is a snapshot and it's possible for multiple players to have the same rank at the times when their respective ranks were calculated. The 'rank' on the leaderboard is just sorting the list of scores already of the page which isn't feasible for user profiles.
