### ISSUE TITLE
Quotes overlap text on different browsers in mobile in osu supporter

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-web#6766]
I was browsing osu and I wanted to see how much supporter I have and I was reading that quote from dean herbert right below peppy and noticed that the quote overlapped the last words

![20201015_070121](https://user-images.githubusercontent.com/52920930/96121171-4c7c0e00-0eb5-11eb-89ec-f6044b95c797.jpg)

**Comment by notbakaneko** [comment]
What browser and version?

**Comment by WinterIsPretty** [comment]
On my samsung s7 phone in samsung internet specifically

**Comment by alolanraichulive** [comment]
Try

**Comment by alolanraichulive** [comment]
Try choosing another browser.

**Comment by WinterIsPretty** [comment]
LMAO what
