### ISSUE TITLE
Leaderboard lines accuracy, playcount, pp and ranks wrongly

### ISSUE THREAD

**Issue by AetherianFI** [ppy/osu-web#6767]
Leaderboard lines accuracy, playcount, pp and ranks wrongly. Notice how E.g. Whitecat's 21 460 is under accuracy (Tarkkuus in finnish) when it's supposed to be under playcount (Pelikerrat). And accuracy number is just in the middle.
![image](https://user-images.githubusercontent.com/72926305/96130899-3005c300-0f01-11eb-9c69-ad01b0262600.png)
I use Chrome Version 86.0.4240.75 (64-bit)

**Comment by Joehuu** [comment]
You may be using osuplus, see https://github.com/ppy/osu-web/issues/4265.
