### ISSUE TITLE
Including checksum of Beatmap object on api v2

### ISSUE THREAD

**Issue by ilsubyeega** [ppy/osu-web#6777]
[this code hides the 'checksum' attribute](https://github.com/ppy/osu-web/blob/2d5561aca34b3ad71f7524e3a4a5633b3b6863a3/app/Models/Beatmap.php#L62).
I think if this attribute is included in Beatmap object from api v2, services such as beatmap mirrors will be able to check for updates without using api v1.

**Comment by peppy** [comment]
sounds fine to add back.
