### ISSUE TITLE
Make api/v2/scores/ available via public scope API

### ISSUE THREAD

**Issue by ShaddyDC** [ppy/osu-web#6781]
I'm looking to get, for a given score id, both the score metadata as well as the replay data via the api. I can do the latter over the old api, but the former will likely [not be implemented there](https://github.com/ppy/osu-api/issues/304). 
The api endpoint [`api/v2/scores/{mode}/{score}/download`](https://osu.ppy.sh/docs/index.html#apiv2scoresmodescoredownload) looks very promising, but using it with `public` scope results in the error `Invalid scope(s) provided.` for me, similar to #6055, so I assume it is currently not accessible with any scope.

**Comment by nanaya** [comment]
This will also need to be rate limited.
