### ISSUE TITLE
In beatmapset search, sorting by plays does not work properly

### ISSUE THREAD

**Issue by Magnus-Cosmos** [ppy/osu-web#6795]
When trying to filter beatmapsets by playcount, I noticed beatmaps were often out of order, where some with higher playcount were sorted after maps with lower playcount
![broken playcount sorting](https://user-images.githubusercontent.com/39173355/96688914-b67e3280-134f-11eb-94cd-db152b5d1456.PNG)
In this image the map with 5,055,786 plays is after 3 maps with less playcount, and similarly the map with 5,103,470 playcount is after a map with 5,102,082 playcount

I also checked on the old site and it has the same issue

**Comment by nanaya** [comment]
Duplicate of #6442.

**Comment by Magnus-Cosmos** [comment]
Oops I should've checked for previous issues, sorry for the duplicate.
