### ISSUE TITLE
Name change rules are not displayed on purchase page

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#6797]
There's a few extra name change rules listed under the [Help Center category of the same name](https://osu.ppy.sh/help/wiki/Help_Centre#name-changes) which detail a few niche cases where we might revert or deny a name-change the system ordinarily accepts.

Currently, this is not visible on the username change page (https://osu.ppy.sh/store/products/32). An easy fix to this would be to change the bold text at the bottom to the following:

```Note that we reserve the right to revert name changes if they are made in bad faith (ie. impersonating another user or brand, changing with an intent to cause confusion), or otherwise violate the rules laid out in [this article](https://osu.ppy.sh/help/wiki/Help_Centre#name-changes). Please make sure you read this carefully before purchasing!```

**Comment by nanaya** [comment]
The description is stored in database. Someone just need to update the entry.

**Comment by peppy** [comment]
I've updated this for you (even though I think you could do this already yourself).
