### ISSUE TITLE
Some content diseappears with a loooooong quote chain...

### ISSUE THREAD

**Issue by Corne2Plum3** [ppy/osu-web#6804]
When you quote a post and the next user quote the post above, like this:
![Capture3](https://user-images.githubusercontent.com/57914482/96937256-05e76e80-14c8-11eb-941f-c123fcbd3a43.PNG)
If the quote chain is too long some content of the post diseappears...
It's happened here: https://osu.ppy.sh/community/forums/topics/474971?n=744

I don't know at what level this bug start (around 500 maybe?).
This is only a visual bug, it's just the post isn't displayed correctly.

**Comment by abraker95** [comment]
That thread was nothing but spam

**Comment by nanaya** [comment]
Yes that is intentional.
