### ISSUE TITLE
Remove web chat update polling

### ISSUE THREAD

**Issue by notbakaneko** [ppy/osu-web#6805]
Chat message and channel updates currently happen by polling `/chat/updates`; the overhead on this is fairly high even if there are no updates. These should be pushed over via the websocket server instead.

**Comment by peppy** [comment]
This is mostly resolved now? @notbakaneko

**Comment by notbakaneko** [comment]
Update polling has been removed #8121

Handling silences and restrictions over websockets should probably have its own issue.
