### ISSUE TITLE
chatting with new line actually not deleted or not showing the new line.

### ISSUE THREAD

**Issue by ilsubyeega** [ppy/osu-web#6806]
I don't think a new line should come out.

To Reproduce:
1. open notepad
2. spam new line on a notepad
3. paste to input
4. the new line not shows on the website, but the client (both osu!lazer and osu!stable) shows the new line.

[Video](https://youtu.be/19umbdy7bak)

**Comment by peppy** [comment]
probably should be trimming newlines for chat.
