### ISSUE TITLE
Featured artist beatmap template link is broken

### ISSUE THREAD

**Issue by qBuen0** [ppy/osu-web#6810]
https://osu.ppy.sh/beatmaps/artists/90
The 5th song(Yume ni Sayonara*) is not working.

"404 not found
Code: NoSuchKey
Message: The specified key does not exist.
Key: artists/90/osz/Numtack05 - Yume ni Sayonara.osz2020
RequestId: 58785E174B8D9E22
HostId: V+Ch2fjKCWDb16NmEccS2Yhat8jNsiJXaYNU4+BsTvkc1ceZREpVqPZwQk7fRXcDlr6hKPA+8Jk=
"

**Comment by peppy** [comment]
This has been fixed.
