### ISSUE TITLE
Error when requesting for a Client Credentials token

### ISSUE THREAD

**Issue by bemxio** [ppy/osu-web#6822]
When I tried to get an "guest user" token, I got a response:
`{"error":"The authorization grant type is not supported by the authorization server."}`
I tried parsing normal URL parameters and body parameters, but it didn't work.

**Comment by peppy** [comment]
what is a guest user token?

**Comment by bemxio** [comment]
sorry for a late reply, i meant Client Credentials token.

**Comment by peppy** [comment]
Could you please provide more information? preferably the full code you're using.

**Comment by bemxio** [comment]
i make a POST request with `requests` Python library with a URL and good parameters as written in [osu! docs](https://osu.ppy.sh/docs/index.html#client-credentials-grant), but when the code completes the request, I get the JSON response mentioned above. also, again sorry for a late reply, i dont get notifications from github.

**Comment by bemxio** [comment]
ok nvm, i didnt do the request with a POST type, anyways thanks for help
