### ISSUE TITLE
Removal of old notifications

### ISSUE THREAD

**Issue by nanaya** [ppy/osu-web#6824]
At current rate of around 8 notifications/second some kind of cleanup should be in order.

- partition the tables by date and drop accordingly
  - make sure nothing explodes if UserNotification is missing the corresponding Notification
  - figure out how to not break frontend when someone tries loading deleted notification (is it even worth it?)
- or alternatively, run a job every some interval which gracefully deletes some amount of notifications
  - the amount should be slightly higher than the rate above which would be about ~30k notifications if run every hour
- some other alternative?

Dropping even just `user_notifications` table rows down to something more manageable would be a good start. It would allow adding index to that table which is needed for removal of orphan notification (used to be part of #6762).

**Comment by peppy** [comment]
I'm ready to add partition deletion as soon as the confirmation that it won't break anything web-side is received.

**Comment by nanaya** [comment]
This has mostly been done.
