### ISSUE TITLE
Clicking a score row to open in new tab (middle click or ctrl-click) doesn't behave as expected

### ISSUE THREAD

**Issue by tybug** [ppy/osu-web#6829]
when holding the command key on macos and clicking any row in the highscores of any beatmap ([example for convenience](https://osu.ppy.sh/beatmapsets/409164#osu/892780)), the score does not open in a new tab as expected but instead loads in the current tab.

Occurs in both safari and chrome.

**Comment by peppy** [comment]
Also middle click doesn't work.
