### ISSUE TITLE
osu!mania ranking criteria's link is broken in the english general ranking criteria

### ISSUE THREAD

**Issue by pimpG** [ppy/osu-web#6830]
https://osu.ppy.sh/help/wiki/Ranking_Criteria

"For game mode-specific ranking criteria, see: osu!, osu!taiko, osu!catch, and osu!mania"

the link doesn't behave like the other three mode specific links, it only works if i hover the mouse around the botton right of the first letter of the link.

according to zeusminus , it's not an issue with the wiki code but something in osu-web https://github.com/ppy/osu-wiki/issues/4384

happens on chrome and edge, didn't tested on other browsers.

**Comment by dorothy3242** [comment]
seems to be an issue on the beatmap nominators page too, links aren't clickable wherever the dropdown would appear. So this seems to be a wiki-wide issue with the website.
![2020-10-29_19-22-42](https://user-images.githubusercontent.com/33286824/97642705-37a68b00-1a1c-11eb-9ed2-b41ba09be2c5.gif)
