### ISSUE TITLE
Download without Video option doesn't filter .m4v format

### ISSUE THREAD

**Issue by hikizisa** [ppy/osu-web#6835]
some mapsets with video are always downloaded with video even if user choose to download without video

https://osu.ppy.sh/beatmapsets/1227803#osu/2553775
https://osu.ppy.sh/beatmapsets/1230699#osu/2558573
https://osu.ppy.sh/beatmapsets/1273875#osu/2653961
https://osu.ppy.sh/beatmapsets/660752#osu/1615502

and it seems like those mapsets contain .m4v formatted video.
it is recognized as a video format in osu client or apparently even in osu-web since download without video option is shown, but somehow download without video doesn't filter it out

**Comment by peppy** [comment]
I've fixed this and the maps listed. Note that this will only apply on next cache purge for maps that weren't listed above (may take days or months depending on map popularity).
