### ISSUE TITLE
Language dropdown prevents links from being clicked even when hidden

### ISSUE THREAD

**Issue by yaspo** [ppy/osu-web#6836]
![example](https://i.imgur.com/OWkV6t0.png)
When visiting [this page](https://osu.ppy.sh/help/wiki/People/The_Team/Nomination_Assessment_Team), I was unable to click the link "Beatmap Nominators" nor hover it. The link "Global Moderation Team" worked partially: when hovering and clicking on "Global" nothing happened, while "Moderation Team" worked just fine. When using inspect element (see image above) I found that the language dropdown blocks these clicks.
Tested on both Firefox and Chrome and got the same results.

**Comment by dorothy3242** [comment]
Same issue as https://github.com/ppy/osu-web/issues/6830 . Not sure here if the fix in that thread didn't work or if it's just not live yet.

**Comment by zeusminus** [comment]
I think #6833 was supposed to fix this. My best guess would be PRs taking a while to go live.

**Comment by peppy** [comment]
Closing as duplicate. Will deploy tomorrow.
