### ISSUE TITLE
Email verification issue.

### ISSUE THREAD

**Issue by Master-chan** [ppy/osu-web#6841]
Hello, I couldn't find any open issues on this matter so I decided to create a new one.
I'm using same browser accessing osu website from the same IP address every day without logging in from other locations. Can I not be required to do email verification literally every time I want to change my avatar, add a friend or use web messenger?

**Comment by peppy** [comment]
Verification is only required once per session. Are you logging out or deleting cookies?

**Comment by Master-chan** [comment]
No, I'm not logging out and I'm visiting the site daily.

**Comment by peppy** [comment]
I would suggest clearing all your browser sessions from your settings page and logging in from scratch. Your browser may be in a weird state.

Verification is only required once per pc, per session.

**Comment by Master-chan** [comment]
If this is where web sessions are listed in settings then my browser can be indeed in a weird state:
![изображение](https://user-images.githubusercontent.com/1059861/97826436-62763500-1ce3-11eb-99e0-be8e93e36c64.png)

I'm using Firefox 82 with addons like NoScript and uBlock disabled on osu site. Is there anything I can do?

**Comment by peppy** [comment]
As I said, follow the instructions I provided.

Log out, then log back in. Your session should correctly show after this.

**Comment by Master-chan** [comment]
Alright, thank you. I logged out and back in, did email verification and session is now showing in settings. Should I continue this issue or create a new one in case of problems?
