### ISSUE TITLE
Add ability to query details for multiple users in a single API request

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#6842]
The osu! client needs to be able to quickly retrieve details for a subset of users that are to be displayed on screen (via a list of `user_id`s). This is relatively high priority as we need to use it for the spectator UI.

**Comment by nanaya** [comment]
How much details are needed here? Is [UserCompact](https://osu.ppy.sh/docs/index.html#usercompact) enough? (maybe with `cover`, `country`, `groups` to match card?)

**Comment by peppy** [comment]
I think so, yes.
