### ISSUE TITLE
username blocks input on user card

### ISSUE THREAD

**Issue by tybug** [ppy/osu-web#6844]
on scores and friend lists (and probably everywhere user cards are used), the area to the right of the username is not clickable / hyperlinked. Might be intended behavior but it was certainly surprising when I found I couldn't click there to go to the user.

example: https://osu.ppy.sh/scores/osu/2797309065, clicking anywhere in the highlighted area doesn't go to the user's page

![image](https://user-images.githubusercontent.com/31628143/97936183-c121ca00-1d48-11eb-8992-af216836c635.png)

**Comment by notbakaneko** [comment]
The block with the username has `pointer-events: auto` to allow the tooltip shown then the name is truncated to work, which makes the entire block un-clickable as a link.
