### ISSUE TITLE
buttons like osu direct not doing anything to osu

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-web#6845]
For a few months, the osu direct button wasn't working. I don't know if this is because it doesn't recognize my osu, but it doesn't do anything anymore when I press the button. Another example is when modding a map I cannot click on timestamps either.

I did, in fact, download osu again and re-install chrome, and I don't know why it won't open osu

Yes, I have supporter if you thought it was because of that

**Comment by peppy** [comment]
This is not a web issue. It means your PC associations are not working. It could mean your browser is running as a different user (incorrect UAC elevation) or that something on your system is stopping the communication from occurring (could be a browser privacy settings even).

**Comment by WinterIsPretty** [comment]
how do I fix this
