### ISSUE TITLE
Ability to instantly graveyard own beatmaps before 30 days

### ISSUE THREAD

**Issue by greevak** [ppy/osu-web#6850]
So much of what to say, It seem to be a little of annoying that i have to wait for 30 days before being able to delete a beatmap, 

And for the summary, so go on with other mappers i asked about this thing,
and the majority of them seem to show agreement on this one specific argument.

I will try to put that in a better way,
I do understand that osu! warns you before uploading a map, But the quota is so low for non osu! supporters. (4 beatmaps),
And sometimes when a player/mapper wants to upload a new map he has to wait for the pending ones to be graveyarded.

One thing that can really improve everything is adding a button to "Instantly graveyard" a map.
Therefore when it's graveyarded, I can delete it aswell, or keep it for other players to play/work on.
And i will also have space to upload my newer/ improved maps.

Thanks for your time, I hope this request will be worked out in a proper way.

**Comment by peppy** [comment]
The 30 day cooldown is there intentionally so people don't abuse the upload process.
