### ISSUE TITLE
Mapset with 2 simultaneous nominations is not qualified

### ISSUE THREAD

**Issue by Naxesss** [ppy/osu-web#6857]
https://osu.ppy.sh/beatmapsets/1250431/discussion/-/events has 2 nominations but is not qualified, probably caused by the nominators nominating at almost the exact same time

![](https://i.imgur.com/KitNVUO.png)

Note that it's missing the qualify event, unlike e.g.

![](https://i.imgur.com/E6H43nm.png)

**Comment by peppy** [comment]
The weird part is, on a quick check this code actually looks to be correctly transactioned..

`osu_beatmapsets` for this beatmap:
![image](https://user-images.githubusercontent.com/191335/98457940-f4dc7400-21ce-11eb-9b2d-88a239794cd9.png)

**Comment by nanaya** [comment]
Due to several other things can also trigger updating nominations count, it's possible that when the problem occurs the nominations count is still at 1.
