### ISSUE TITLE
pm's in-game to web chat taking 10+ hours to show up

### ISSUE THREAD

**Issue by TobiasLeander** [ppy/osu-web#6858]
When sending a private message to someone in-game the message will take up to 10 hours to show up in the web-chat on the osu! site this is the case for everyone at the moment and not just me.

**Comment by peppy** [comment]
Thanks for the report. Investigating a performance regression `osu-web` side that is causing this.

**Comment by peppy** [comment]
I've rolled back the release for now, and the queue is catching up. It should be back in real-time within a few hours (can be monitored via https://p.datadoghq.com/sb/irf3GA-339e24efc792fbe37106391d62032cdf).

Will close this issue for now.
