### ISSUE TITLE
No way to view all of a user's comments

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#6859]
There is currently no route that exposes all of a person's comments in a single view.

This is useful for a few reasons:

- It allows users to see a brief glance of someone's comment history, allowing them to follow up on further points of interest
- It allows moderators to do the above, but for the purpose of mass-handling problematic/abusive users

**Comment by dorothy3242** [comment]
Duplicate of https://github.com/ppy/osu-web/issues/4112 ? 

That has a related PR open too

**Comment by Ephemeralis** [comment]
Looks like it.
