### ISSUE TITLE
Error: "mysql: unrecognized service"

### ISSUE THREAD

**Issue by iamanai** [ppy/osu-web#687]
I am attempting to deploy the project using the instructions in the readme file, but vagrant stops with the message, "The SSH command responded with a non-zero exit status." Upon reading the log to find out what went wrong, it seems that vagrant cannot access "mysql".

What am I doing wrong? The full output is provided below.

> D:\Files\Caleb\Development\Web\osu-web\vagrant>vagrant up
> Bringing machine 'default' up with 'virtualbox' provider...
> ==> default: Box 'ubuntu/trusty32' could not be found. Attempting to find and install...
>     default: Box Provider: virtualbox
>     default: Box Version: >= 0
> ==> default: Loading metadata for box 'ubuntu/trusty32'
>     default: URL: https://atlas.hashicorp.com/ubuntu/trusty32
> ==> default: Adding box 'ubuntu/trusty32' (v20160802.0.1) for provider: virtualbox
>     default: Downloading: https://atlas.hashicorp.com/ubuntu/boxes/trusty32/versions/20160802.0.1/providers/virtualbox.box
>     default: Progress: 100% (Rate: 10.7M/s, Estimated time remaining: --:--:--)
> ==> default: Successfully added box 'ubuntu/trusty32' (v20160802.0.1) for 'virtualbox'!
> ==> default: Importing base box 'ubuntu/trusty32'...
> ==> default: Matching MAC address for NAT networking...
> ==> default: Checking if box 'ubuntu/trusty32' is up to date...
> ==> default: Setting the name of the VM: osu!web
> ==> default: Clearing any previously set forwarded ports...
> ==> default: Clearing any previously set network interfaces...
> ==> default: Preparing network interfaces based on configuration...
>     default: Adapter 1: nat
> ==> default: Forwarding ports...
>     default: 80 (guest) => 8080 (host) (adapter 1)
>     default: 8000 (guest) => 8081 (host) (adapter 1)
>     default: 3306 (guest) => 3366 (host) (adapter 1)
>     default: 22 (guest) => 2222 (host) (adapter 1)
> ==> default: Running 'pre-boot' VM customizations...
> ==> default: Booting VM...
> ==> default: Waiting for machine to boot. This may take a few minutes...
>     default: SSH address: 127.0.0.1:2222
>     default: SSH username: vagrant
>     default: SSH auth method: private key
>     default: Warning: Remote connection disconnect. Retrying...
>     default:
>     default: Vagrant insecure key detected. Vagrant will automatically replace
>     default: this with a newly generated keypair for better security.
>     default:
>     default: Inserting generated public key within guest...
>     default: Removing insecure key from the guest if it's present...
>     default: Key inserted! Disconnecting and reconnecting using new SSH key...
> ==> default: Machine booted and ready!
> ==> default: Checking for guest additions in VM...
>     default: The guest additions on this VM do not match the installed version of
>     default: VirtualBox! In most cases this is fine, but in rare cases it can
>     default: prevent things such as shared folders from working properly. If you see
>     default: shared folder errors, please make sure the guest additions within the
>     default: virtual machine match the version of VirtualBox you have installed on
>     default: your host and reload your VM.
>     default:
>     default: Guest Additions Version: 4.3.36
>     default: VirtualBox Version: 5.0
> ==> default: Mounting shared folders...
>     default: /vagrant => D:/Files/Caleb/Development/Web/osu-web/vagrant
>     default: /data/osu!web => D:/Files/Caleb/Development/Web/osu-web
> ==> default: Running provisioner: shell...
>     default: Running: inline script
> ==> default: stdin: is not a tty
> ==> default: I am provisioning...
> ==> default: Setting up php, nginx, mysql
> ==> default: /tmp/vagrant-shell: ./bootstrap.sh: /bin/sh^M: bad interpreter: No such file or directory
> ==> default: Bind mounting node_modules
> ==> default: setup osu!web stuff
> ==> default: /tmp/vagrant-shell: line 19: mysql: command not found
> ==> default: sudo: unable to execute ./build.sh: No such file or directory
> ==> default: Running provisioner: shell...
>     default: Running: inline script
> ==> default: stdin: is not a tty
> ==> default: mysql: unrecognized service
> The SSH command responded with a non-zero exit status. Vagrant
> assumes that this means the command failed. The output for this command
> should be in the log above. Please read the output to determine what
> went wrong.

**Comment by cl8n** [comment]
Try changing `mysql-server-5.7` to `mysql-community-server` on line 26 of bootstrap.sh--- if that doesn't fix everything, try re-saving the three .sh files with LF line endings rather than CRLF. I had to do both of these things before vagrant got up correctly.

**Comment by iamanai** [comment]
Changing line 26 did nothing. How would you go about changing the line endings?

**Comment by iamanai** [comment]
Doing both of those things did not solve the issue.

**Comment by peppy** [comment]
are you vagrant `destroy; vagrant up;`ing after the changes?

**Comment by iamanai** [comment]
No I was not. I'll try that now.

**Comment by iamanai** [comment]
Well, that worked, but now attempting to load the website comes up with 

> PDOException in Connector.php line 55:
SQLSTATE[HY000] [1049] Unknown database 'osu'

Sorry for all the questions - I am horrendously inexperienced when it comes to web development. Why would the osu database be missing?

**Comment by iamanai** [comment]
Well, the initial problem is solved, so I'm closing this issue. Thanks!
