### ISSUE TITLE
Block overlay doesn't block side panels

### ISSUE THREAD

**Issue by InvisibleSymbol** [ppy/osu-web#6873]
![](https://i.imgur.com/gGPoat1.png)

**Comment by nanaya** [comment]
What side panels are you talking about?

The scrollbar is permanent to prevent the header from moving around when navigating between pages.

**Comment by InvisibleSymbol** [comment]
I'm talking about these side panels
![](https://i.imgur.com/bcMERfo.png)
It looks broken, I assume they are meant to be black aswell
This looks way better
![](https://i.imgur.com/fqHAEAx.png)

**Comment by nanaya** [comment]
Those aren't part of the content and frankly speaking no one should look at that page long enough to care about that
