### ISSUE TITLE
Outdated hybrid nomination checks

### ISSUE THREAD

**Issue by Naxesss** [ppy/osu-web#6875]
After the change to require 2 BNs for each mode in a mapset, it should now be possible for at most 1 probation BN and at least 1 full BN to nominate their mode. However it seems the restrictions on the site still assume all must be full.

Context: On https://osu.ppy.sh/beatmapsets/1154158, a probationary osu! nominator ([Een Persoon](https://osu.ppy.sh/users/10959501)) received this, while a full osu!taiko nominator ([realy0_](https://osu.ppy.sh/users/8863359)) had nominated:
![](https://cdn.discordapp.com/attachments/655483404065833001/777286189496533042/unknown.png)

Could temporarily lift the web restrictions on this, and then update these as part of / following https://github.com/ppy/osu-web/pull/6832.

**Comment by peppy** [comment]
is it correct thinking that #6832 will resolve this? if so, it's best to just wait for it as it should be days off...

**Comment by Naxesss** [comment]
it seems to lift the restrictions, looking at https://github.com/ppy/osu-web/pull/6832/files#diff-2bca393c48498440e3ec8981703e0fc984db144b74a51456c40e5418fb793f70L590-L599

so it does resolve the specific case that raised this issue, but there should probably be checks to ensure a full bn is always involved with each mode (so 2 probation bns can't qualify a map together), I'll retitle the issue to make that more clear

**Comment by nekodex** [comment]
#6832 does exactly that - it both allows probationary BNs to nominate hybrids and also adds the requirement for at least one full BN nomination per game mode
