### ISSUE TITLE
Downloading beatmapsets using osu!api v2

### ISSUE THREAD

**Issue by Naxesss** [ppy/osu-web#6876]
Seems to be unfinished currently:
![](https://i.imgur.com/9rI3D2Q.png)

Planned use case is a program that automatically checks newly qualified beatmapsets (usually between 10 to 16 per day) for issues through https://github.com/Naxesss/MapsetVerifier, and then reports any to BNs/NAT; thereby eliminating a large portion of possible unrank reasons.

**Comment by peppy** [comment]
Should be fine to allow this scope (via the api key authorised user only, similar to other cases like this).

**Comment by notbakaneko** [comment]
This should be in now #6826
