### ISSUE TITLE
Problem with getting OAuth key

### ISSUE THREAD

**Issue by Cruxial0** [ppy/osu-web#6877]
Having problems obtaining a key through Client Credentials Grant.
Using Postman and passing in all parameters stated in the docs.

![image](https://user-images.githubusercontent.com/25249091/99193355-c0415d00-2778-11eb-8eaa-fa03cb9b95b1.png)

**Comment by peppy** [comment]
Please see https://github.com/ppy/osu-web/issues/6602

**Comment by Cruxial0** [comment]
Passing in the values to the body instead of params indeed worked. Closing the ticket now.
Thanks for the help!
