### ISSUE TITLE
No feedback when trying to upvote own comment

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#6878]
It's impossible to upvote your own comment, so it should be visually different than others or have feedback when hovering it.

![00BjRgfYHK](https://user-images.githubusercontent.com/35318437/99216738-41095480-278b-11eb-9f61-41f964c1718f.gif)

**Comment by peppy** [comment]
Should probably have a different background colour (or none at all) @arflyte please advise.

**Comment by arflyte** [comment]
I'd suggest removing the bg for own posts.
