### ISSUE TITLE
Unknown database 'osu'

### ISSUE THREAD

**Issue by iamanai** [ppy/osu-web#688]
Ugh... I'm attempting just to set up the VMs and things as explained in the readme file, but have run into numerous issues. First it didn't think mysql existed, then it couldn't ssh into the VM, and now I'm running into a "SQLSTATE[HY000] [1049] Unknown database 'osu'" error every time I try to perform an ssh action or open the page using localhost.

I feel so clueless... Curse me and my inexperience with web development!

Does anyone know how to get it actually running?

**Comment by ThePooN** [comment]
You should execute the `bin/db_setup` script.

**Comment by iamanai** [comment]
And how do I do that? Going through both regular command prompt and the ssh client does nothing (sorry again for my complete noobishness. I'm trying!)

**Comment by ThePooN** [comment]
You should `vagrant ssh`, then `cd /data/osu\!web/bin` and `./db_setup`.

**Comment by iamanai** [comment]
Doing that produced a 'no such file or directory' error. I changed the line endings to LF and it spat out "ERROR 1698 (28000): Access denied for user 'root'@'localhost'"

**Comment by ThePooN** [comment]
Seems like root permissions are needed. Try `sudo ./db_setup` instead.

**Comment by iamanai** [comment]
Yay, that worked, but now I'm getting ANOTHER error when attempting to load the page or do anything else. This is just fantastic.

> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'osu.osu_banchostats' doesn't exist (SQL: select * from `osu_banchostats` where `date` >= 2016-08-10 03:19:45 and banchostats_id mod 10 = 0)

**Comment by ThePooN** [comment]
You should read the README.

You should generate assets, reset and seed the db to get the website working.

**Comment by iamanai** [comment]
My bad, I was trying to create the user first because that was the next item on the readme. I did the first part of asset generation just fine, but when I got to "./node_modules/.bin/gulp", it threw a "no such file or directory" at me. Should I just seed the database anyway?

**Comment by ThePooN** [comment]
Try doing `npm install` in the osu!web folder and generate assets again.

**Comment by ThePooN** [comment]
You should eventually generate a user, but after seeding the database.

**Comment by iamanai** [comment]
> [PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1217 Cannot delete or update a parent row: a foreign key constraint fails

**Comment by iamanai** [comment]
The whole log of the asset creation?

**Comment by iamanai** [comment]
Because that's the whole log upon seeding the databse.

**Comment by ThePooN** [comment]
Open a mysql shell `sudo mysql -u root` and issue:
```DROP DATABASE osu
DROP DATABASE osu_chat
DROP DATABASE osu_store```

Then, try to migrate and seed again.

**Comment by iamanai** [comment]
So doing that caused me to get back to the original "Unknown database 'osu'" error, so I backtracked and redid everything again and it worked this time. Now upon loading the page it gives me this:

> ErrorException in helpers.php line 352:
File css/app.css not defined in asset manifest. (View: /data/osu!web/resources/views/layout/metadata.blade.php) (View: /data/osu!web/resources/views/layout/metadata.blade.php) (View: /data/osu!web/resources/views/layout/metadata.blade.php)

I looked through the log and found that during the database seed, it printed this to the log:

> Fetching Version Source Files...
   - public/css/app.css <-- Not Found
   - public/js/app.js
   - public/js/react/profile-page.js
   - public/js/react/beatmaps.js
   - public/js/react/slack-page.js
   - public/js/react/status-page.js
   - public/js/react/beatmap-discussions.js
   - public/js/react/beatmapset-page.js
   - public/js/react/artist-page.js
   - public/js/react/contest-page.js

So that file is missing.

**Comment by ThePooN** [comment]
You should generate assets I believe.

**Comment by iamanai** [comment]
I did that. The log from the asset generation has some errors in it as well.

**Comment by ThePooN** [comment]
Why not paste them?

**Comment by iamanai** [comment]
It's very, VERY long. Do you want it anyway?

**Comment by ThePooN** [comment]
attach a file

**Comment by iamanai** [comment]
[asset generation.txt](https://github.com/ppy/osu-web/files/412515/asset.generation.txt)
[database seeding.txt](https://github.com/ppy/osu-web/files/412516/database.seeding.txt)

**Comment by iamanai** [comment]
Wow oops, in my comment before, I meant to say "during the asset generation" not "during the database seed".

**Comment by nekodex** [comment]
It looks like the build script may have not run properly - try `vagrant ssh`, then run `./build.sh` from the osu!web directory. Hopefully after that you can regenerate the assets.

**Comment by nanaya** [comment]
something to do with git converting line endings to windows' format and confuses bash/sh.

**Comment by iamanai** [comment]
THAT WORKED! Thanks a million! Now I can finally start poking around and figuring things out!

**Comment by thomastanck** [comment]
@iamanai Could you write up a guide of how to set this up from scratch? I'm having a lot of trouble setting it up as well, and reading this was a bit confusing (and it still doesn't work) :c

**Comment by thomastanck** [comment]
@iamanai Any updates?
