### ISSUE TITLE
Request about Access for GET "/rooms" endpoint

### ISSUE THREAD

**Issue by WilczekCK** [ppy/osu-web#6882]
Hello,
Is it possible to get an access for that endpoint (POST "/rooms") ?
https://osu.ppy.sh/docs/index.html#apiv2rooms

I'm making a script for a website which will list all of the actual(live) and previous tournaments, their scores, players, maps played etc.
Of course I made several other scripts with that API, so I'm familiar how it works.

But, i tried to connect that route , I got the 403 HTTP error, so I'm unauthorized using client credentials grant (the one without redirection, because any user won't have to log-in)

I talked with peppy and he told me that I need to request to make that route public (or get access)
Is it possible?

Username in game is the same as in github ;)

//Edit
Would be good if /get scores would be available too.
https://osu.ppy.sh/docs/index.html?javascript#get-scores

Greetings

**Comment by peppy** [comment]
Just to confirm, you are interested in interacting with the timeshift system?

**Comment by nanaya** [comment]
Listing endpoint is `GET`. Endpoint `POST /rooms` isn't supposed to be used by anything but lazer client.

Also I just checked it's already accessible using public token :raised_eyebrow:

**Comment by WilczekCK** [comment]
But GET /rooms is just for single room, I asked about for all of the online/active multiplayers lobbies.

**Comment by venix12** [comment]
yes, it's possible via ``GET /rooms``, make sure you have public scope
