### ISSUE TITLE
Overlays are always (faintly) visible

### ISSUE THREAD

**Issue by lh-deux** [ppy/osu-web#6883]
The loading animation is always visible in the middle of the screen, on Firefox 82.0.3.
This also affects the rank pop-up when hovering the rank graph and moving the cursor out of it. (top left of graph in the second image)

![](https://user-images.githubusercontent.com/41867600/99525328-f3166b80-2999-11eb-94b1-79a10cda07a2.png)
![](https://user-images.githubusercontent.com/41867600/99525770-949dbd00-299a-11eb-89e2-629ada8b4ce9.png)

**Comment by peppy** [comment]
Wow, that's really dodge.

**Comment by notbakaneko** [comment]
I can't reproduce this on Chrome, Firefox or Safari on MacOS

**Comment by lh-deux** [comment]
I tried to reproduce it without extensions, the problem comes from uBlock, not the site itself.
