### ISSUE TITLE
Profile pages won't render when user's country rank is null

### ISSUE THREAD

**Issue by MillhioreF** [ppy/osu-web#689]
https://new.ppy.sh/u/2107443#mania

As can be seen at https://osu.ppy.sh/u/2107443 , the user doesn't have a flag by their country ranking (next to their performance ranking). Either the tables need to be resynced, or a fallback case needs to be added to the website so the page still renders if this is broken (or both?)

**Comment by cl8n** [comment]
Why do their flags not match on the old site (under username vs next to performance ranking)? I'm confused as to what's actually going on here

**Comment by MillhioreF** [comment]
It's got to be something wrong with the tables. I've seen one or two other users with the same problem, but only ever in mania mode, so it may be some sort of failed template migration?

**Comment by nanaya** [comment]
is it still a problem? At least the linked user seems to be fixed.

**Comment by MillhioreF** [comment]
The linked user's flag is correct now somehow, and I can't find any other users with the problem at the moment, so maybe it resolved itself in the db. Will reopen this issue if I see it happen again.
