### ISSUE TITLE
Reporting Abuse article should be displayed under 'help' header

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#6890]
[A highly upvoted comment](https://osu.ppy.sh/comments/1320799) from the recent abuse-related newspost made by peppy makes a good point - we should probably include a link to the abuse reporting article under the help header for extra visibility.

```https://osu.ppy.sh/help/wiki/Reporting_Bad_Behaviour/Abuse```

**Comment by peppy** [comment]
can probably fit underneath "rules" in help menu.

**Comment by nekodex** [comment]
What should the link read? Just "report abuse" or something?

**Comment by peppy** [comment]
if it fits, that sounds fine
