### ISSUE TITLE
osu!Taiko sorting by difficulty: not sorted

### ISSUE THREAD

**Issue by h571566** [ppy/osu-web#6893]
Using the sorting function on the website doesn't list taiko beatmaps in the correct order by star rating. In the screenshot it seems like it is fine after the first two maps, but it's not^^ It goes down to 6*, then back up to 8* etc.
![Capture5376925](https://user-images.githubusercontent.com/31436527/99796535-f5a9ca00-2b2d-11eb-804a-f768edb12534.PNG)

**Comment by notbakaneko** [comment]
The diffs used for sorting are currently outdated

**Comment by notbakaneko** [comment]
Thanks for reporting this, they should be correct now.
