### ISSUE TITLE
last login date randomly set back to multiple weeks ago

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#6894]
[my profile](https://osu.ppy.sh/users/3666350) says "last seen 21 days ago" (`2020-10-30T21:39:14+00:00`) as of creating this issue, but I was logged into the website and playing the game as recent as a few days ago, you can see that on my recent activity. it jumped to 21 days either yesterday or today because I remember visiting my profile (while logged out) earlier and seeing 1 or 2 days ago

I've heard about other people having similar issues, but it's hard to track down details since nobody remembers exactly what they were doing weeks ago, and the exact incorrect last login date is usually lost after they use the site or game again. one of my friends remembers having his login date set to as high as "2 months ago"

this is probably an issue with old web bc the only time osu-web updates `user_lastvisit` is on page visits. I dug around phpbb and the only nonobvious update to it I could find was in `session_gc()`, I didn't research further than this because idk if it'd even be applicable to osu's version of phpbb

so lastly here is what I can remember about my login history, unfortunately it's still pretty vague:

- I was actively using my account in-game and on website until a few days ago. i logged out of all sessions
- I last used the old website weeks ago to read and send forum PMs, no idea if it was exactly 21 days ago though. I did *not* sign out from the old website and those sessions may still be active (I'm purposely avoiding checking it to keep this incorrect state in case it's helpful)
- the correct last login date was shown until either yesterday or today, when it jumped to "21 days"

edit: logged in again so the bug's gone, hopefully all the relevant timestamps are in this issue

**Comment by peppy** [comment]
super weird. there's three systems that update that date right now, so gonna require a bit of detective work. to be sure, does it update if you login to bancho as normal?

**Comment by cl8n** [comment]
yeah, it always updates correctly on logins (old site, new site, and client) in my experience

**Comment by peppy** [comment]
I'm going to tentatively close this one as there haven't been any more reports and I still don't have much idea of how this could have happened.
