### ISSUE TITLE
3 differing sources about limitations on pending beatmap submission count with osu!supporter

### ISSUE THREAD

**Issue by klmix** [ppy/osu-web#6895]
Source 1: https://osu.ppy.sh/home/support
( normal support main page)

> How many **non-ranked beatmaps** you can have at once is calculated from a base value plus an additional bonus for each ranked beatmap you currently have (up to a limit).
>Normally this is 4 plus 1 per ranked beatmap (up to 2). With supporter, this increases to  **8 plus 1 per ranked beatmap (up to 4)**. 

That would be up to 12 total NON-RANKED beatmaps, i.e. I would assume including graveyard maps.

Source 2: https://osu.ppy.sh/help/wiki/Submission#limitations
(english osu wiki about limitations of Beatmap submissions)
> Users without osu!supporter can have 4 pending beatmaps plus 1 per ranked beatmap (up to 2). With osu!supporter, this increases to **8 pending beatmaps plus 1 per ranked beatmap (up to 12) for a total of 20.**

That would be up to 20 pending beatmaps, i.e. without graveyard maps.

Source 3: https://osu.ppy.sh/help/wiki/osu%21supporter?locale=de#vorteile-als-osu!supporter
(German wiki page about Benefits of osu!support)

> (original) Erhöht die Beatmap Submission Anzahl (**bis zu acht Beatmaps** ingesamt im Pending gleichzeitig)
 (translation by me) Rises the amount of Beatmap Submissions (**up to 8 Beatmaps** in **Pending** at the same time)

That would be up to 8 pending beatmaps, i.e. without graveyard maps.

**Comment by dorothy3242** [comment]
Source 2 is the correct one, so it's source 1 that needs to be fixed.

Source 3 would be a wiki issue.

**Comment by peppy** [comment]
welp. i changed source 1 because someone said it was wrong. it used to read correct. have fixed.

**Comment by klmix** [comment]
Please also consider changing "non-ranked beatmaps" to "pending beatmaps" like it is written on the osu!wiki. It was very unclear to me that non-ranked beatmaps is NOT including graveyard beatmaps.
