### ISSUE TITLE
Created maps not appearing on the website

### ISSUE THREAD

**Issue by aMolybdenum** [ppy/osu-web#6898]
I have mapped several maps and have always been able to look at them by going Website>Beatmaps>Listing>My Maps but since probably yesterday or today I have not been able to see my maps, and am greeted with "...nope, nothing found." They still appear on my profile and if i search for them, just not with this route.

**Comment by marcostudios** [comment]
I have to say that also "Favourites" is blank and i have a lot of favourites on my profile.
