### ISSUE TITLE
API route for community/matches/:id scrapping

### ISSUE THREAD

**Issue by WilczekCK** [ppy/osu-web#6906]
Hi,
Would be grateful if you would create route for scrapping results from that page:
https://osu.ppy.sh/community/matches/60883767
or extend the GET /rooms/:id route to get the ID for the community match page.

If it's hard to understand, please try to make  **GET /rooms/1** request and then, try to find it on website.
https://osu.ppy.sh/community/matches/1 - it does not work, even when I provide the "channel_id" value https://prnt.sc/vptqlq

It's important for script that is nearly done, I mentioned it in another issue, right here:
https://github.com/ppy/osu-web/issues/6882

thanks

**Comment by peppy** [comment]
Could you explain what you mean by the "hard to understand" id lookup? What would you expect to see with `/matches/1`?

**Comment by notbakaneko** [comment]
Timeshift rooms `/rooms/:id` and matches have nothing to do with the ones under `/community/matches`

**Comment by WilczekCK** [comment]
Okay I undestand, but is there any possibility to get an ID from **GET /rooms/1** to paste in into the https://osu.ppy.sh/community/matches/:id ?

**Comment by nanaya** [comment]
`/matches/` is for stable multi. Are we going to support this in new api? @peppy

**Comment by peppy** [comment]
Yeah, probably best to have an endpoint for that until we combine the systems.
