### ISSUE TITLE
API docs should list the scopes of each endpoint

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#6911]
A recurring theme is people trying to use endpoints which aren't publicly exposed. This should be listed clearly in the documentation.

Also all existing api endpoints which aren't public should be considered candidates to be made public. We are going to keep getting these requests and it's easier to just expose preemptively where feasible:

https://github.com/ppy/osu-web/issues/6882
https://github.com/ppy/osu-web/issues/4042
https://github.com/ppy/osu-web/issues/6906
https://github.com/ppy/osu-web/issues/6876
https://github.com/ppy/osu-web/issues/6422
https://github.com/ppy/osu-web/issues/6330
https://github.com/ppy/osu-web/issues/6073
https://github.com/ppy/osu-web/issues/2162
(some of these may already be fulfilled)

**Comment by nanaya** [comment]
Is this PR just for API endpoint scope docs or for tracking giving public scope for those endpoints as well?

**Comment by nanaya** [comment]
Scopes in docs have been added by #6968.

**Comment by nanaya** [comment]
Oh so that's why I kept this issue open (list of endpoints to be made public?).

**Comment by notbakaneko** [comment]
These have been added except #6073 which should be tracked in its own issue.
