### ISSUE TITLE
Play history recording into future month

### ISSUE THREAD

**Issue by NafeeJ** [ppy/osu-web#6916]
The time of the following image for me is November 30, 2020, 7:32 pm EST

![play history error](https://user-images.githubusercontent.com/33550260/100681859-ba37a880-3342-11eb-9a26-6ad8953de509.jpg)

I have 2 plays in December when it isn't December for me. I don't know how scores are submitted but I'm guessing this is a time zone problem.

**Comment by Nivalyx** [comment]
your hunch is correct, this is due to the server records your statistics in the international UTC (GMT +0) timing standard

considering that 7:32 PM EST (GMT -5) = 0:32 AM UTC (GMT +0), the server therefore recognizes that the play is being done in Dec 1st instead of Nov 30th

**Comment by peppy** [comment]
This can't really be avoided due to how these statistics are aggregated. I don't think it's a huge deal.
