### ISSUE TITLE
Removing inappropriate backgrounds from currently ranked maps

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#6933]
The following sets have been flagged by members of the GMT, NAT and broader community as needing to have their backgrounds deleted/replaced:

https://osu.ppy.sh/beatmapsets/22252#osu/110771
https://osu.ppy.sh/beatmapsets/228790#osu/562333
https://osu.ppy.sh/beatmapsets/618290#osu/1303380
https://osu.ppy.sh/beatmapsets/667862#osu/1413067
https://osu.ppy.sh/beatmapsets/392207#osu/855762
https://osu.ppy.sh/beatmapsets/446027#osu/958038
https://osu.ppy.sh/beatmapsets/690556#osu/1479927

Posting this here at peppy's request so he can use specialized tools to do this.

**Comment by Coppertine** [comment]
I might have to disagree with https://osu.ppy.sh/beatmapsets/667862#osu/1413067 as the background used is one of the official images used for the game and is even shown on steam (with the majority of the image) used as the thumbnail.

**Comment by twoonetwoseven** [comment]
> 
> 
> I might have to disagree with https://osu.ppy.sh/beatmapsets/667862#osu/1413067 as the background used is one of the official images used for the game and is even shown on steam (with the majority of the image) used as the thumbnail.

I feel like even though it is official content for the game it does not fit osu's current VCC and should still be removed.

**Comment by peppy** [comment]
it is not an "official" image. please show us where this is seen as "official" so we can correct this.

**Comment by dorothy3242** [comment]
I think they mean official promo art for the video game the song is from, and said game is rated pegi12 for reference. Not as in being for osu

**Comment by peppy** [comment]
This is not relevant to this thread. Locking.

**Comment by peppy** [comment]
@Ephemeralis can we mark these as explicit and move on?

**Comment by Ephemeralis** [comment]
I've flagged a few as explicit (even though this isn't really what the explicit marker is for), but https://osu.ppy.sh/beatmapsets/446027 definitely needs to be removed directly.

**Comment by peppy** [comment]
Thanks much
