### ISSUE TITLE
Add the Serbian language to the crowdin osu-web project

### ISSUE THREAD

**Issue by twoonetwoseven** [ppy/osu-web#6967]
I would like to get started on the Serbian translation of the game however there isn't an option to choose from on the [crowdin](https://crowdin.com/project/osu-web) site.
Also it might be worth mentioning that the translations would be done in [Serbian Cyrillic](https://en.wikipedia.org/wiki/Serbian_Cyrillic_alphabet), not Latin.
I also sent a message on the crowdin website however I don't know if that inbox is monitored so I figured it'd be best to post on here.

**Comment by peppy** [comment]
I've added the language on crowdin.
