### ISSUE TITLE
Migrate from TSlint to ESlint

### ISSUE THREAD

**Issue by notbakaneko** [ppy/osu-web#6974]
TSLint has been deprecated for a while and stopped accepting updates since Dec 1st.
Apparently, ESLint can do annotations on Github Actions via `setup-node` and since we've just moved our entire CI to Github actions #6959, now is a good time as any to look at switching

**Comment by nanaya** [comment]
I'll start slowly fixing the errors one by one every now and then.

**Comment by nanaya** [comment]
done in #8003
