### ISSUE TITLE
previous specs of the .osu file format should be available

### ISSUE THREAD

**Issue by tybug** [ppy/osu-web#6976]
There should be some developer guidance on the difference between different versions of the `.osu` file format. For instance, https://osu.ppy.sh/beatmapsets/78#osu/177 (.osu v3) is missing many attributes required by [the current (v14) spec](https://osu.ppy.sh/wiki/en/osu%21_File_Formats/Osu_%28file_format%29). `AudioLeadIn`, `PreviewTime`, and `Countdown` are just a few examples. Without trial and error there is no way to tell what attributes were required by a past beatmap version, and therefore no reliable way to parse them.

**Comment by notbakaneko** [comment]
I think this should be opened in [osu-wiki](https://github.com/ppy/osu-wiki/issues)?

**Comment by tybug** [comment]
apologies, you're right. Should you transfer it or should I close and reopen?

**Comment by peppy** [comment]
Documenting all the intricacies of legacy versions is not a priority for the team (although you may find someone in the community willing to do this, not sure).

Developers should use (or consume) the osu! source code, which is available at https://github.com/ppy/osu. This includes legacy parsing support.

Feel free to open an issue on the wiki repo if you think it's something which should exist there.
