### ISSUE TITLE
Currently you can't change your osu! profile banner after you're supporter has expired. This wouldn't be a problem but me! is changeable after supporter has expired. 

### ISSUE THREAD

**Issue by Strik4r** [ppy/osu-web#6986]
It seems really random that you can't change your profile banner but can change me! after supporter has expired. I would love to see a change to keep it consistent. 
![image](https://user-images.githubusercontent.com/76068680/102261550-aeadbb00-3ec6-11eb-86f6-f3ea1a75da6c.png)

**Comment by peppy** [comment]
This is intended behaviour.
