### ISSUE TITLE
Opening users forum posts while being unauthorized shows nothing

### ISSUE THREAD

**Issue by lmnyx** [ppy/osu-web#7011]
![a](https://user-images.githubusercontent.com/13962537/102734155-f5853000-4360-11eb-9366-d642d760405c.png)
I guess it should say that you need to be authorized to view that, because the counter  displays that posts exist

**Comment by peppy** [comment]
What do you mean by "unauthorised"? Are you not logged in?

**Comment by venix12** [comment]
Yes, that's the case. Should it display the forum posts or redirect to the login screen?

**Comment by lmnyx** [comment]
> 
> 
> What do you mean by "unauthorised"? Are you not logged in?
Yes, that's what I meant

**Comment by peppy** [comment]
Bumping this in to a milestone; pretty weird behaviour.
