### ISSUE TITLE
assets urls in config are unused and should proabably be removed

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#7026]
https://github.com/ppy/osu-web/blob/c0cf70631844c545ea8f939f38413d2dbfd45b73/config/osu.php#L24-L27

seem to no longer be used anywhere. might be a good time to go through and purge any others we don't use any more.

**Comment by nanaya** [comment]
Those are still used to generate thumbnail url for contest.

https://github.com/ppy/osu-web/blob/da1666fd354579b07c87de13b8e9c1bd14b91360/app/helpers.php#L1641-L1646

**Comment by peppy** [comment]
Sneaky as hell. That said, will the assets url ever differ from the s3 one?
