### ISSUE TITLE
Typo on store page

### ISSUE THREAD

**Issue by Phippe** [ppy/osu-web#7036]
There's a second "funds" in front of "any reserved funds" in the English text: https://crowdin.com/translate/osu-web/43/en-de#11020

**Comment by Joehuu** [comment]
You can make a pull request to remove the first "funds" if you're willing to:

https://github.com/ppy/osu-web/blob/a01ef6a8597a65fa53cfd39c5ed65c195e664616/resources/lang/en/store.php#L73
