### ISSUE TITLE
Beatmap page displays ∞ BPM with 2021 BPM.

### ISSUE THREAD

**Issue by Corne2Plum3** [ppy/osu-web#7044]
So I created a map with a song with **2021 BPM**. He have only 1 timing point who set the BPM.
I published the map and the bratmap page displays "∞" BPM instead of the correct BPM value.

![anotherosuwebbug](https://user-images.githubusercontent.com/57914482/103801340-e6cf9600-504d-11eb-9233-5ea2c89bebe8.PNG)

The map: https://osu.ppy.sh/beatmapsets/1341512#osu/2778829

Note: the song is **REALLY** 2021 BPM and dividing the BPM may kill the fun of this song.

**Comment by venix12** [comment]
what's the problem with it, though? at the moment, everything above 1000BPM displays infinite mark, it doesn't really change anything with beatmap i believe.

**Comment by peppy** [comment]
This is intentional.
