### ISSUE TITLE
Add difficulty name to nav bar in modding discussions

### ISSUE THREAD

**Issue by Kibbleru** [ppy/osu-web#7052]
Basically instead of having it as General(This difficulty) it would be great if it showed the difficulty name instead.
Might be a simple change but it would be really useful since u often want to know which difficulty you are on without scrolling up to the top.

![image](https://i.imgur.com/zFnFJ8h.png)

--
Unrelated but i'm sure it's been mentioned already, pls add download link to modding discussions page.

**Comment by peppy** [comment]
Is this a simple one to change? If so it may be a good change to get in.

**Comment by nanaya** [comment]
The requested specific change should be easy.

I think ideally the tab should be first divided into "All difficulties" (Reviews, General (all), History) and "Selected difficulties" (General, Timeline) sections. Or some other way to make it clear whether the tab applies for selected difficulty or for all difficulties.

**Comment by notbakaneko** [comment]
I think these tabs and the filters on top should be combined somehow, or at least be made more accessible - the info box in between them seems less useful when doing discussions?

**Comment by Kibbleru** [comment]
Would be nice, but not too necessary yet. If it's a quick change, having what I proposed implemented would be really helpful.

**Comment by peppy** [comment]
Are we already on the latest version of the design for this page, or one behind? Wondering if this has already been resolved at the design in end in some way..

**Comment by nanaya** [comment]
The tabs are similar in newer design
