### ISSUE TITLE
API: beatmapsets search doesn't show explicit maps

### ISSUE THREAD

**Issue by sometimeszzzzzzz** [ppy/osu-web#7053]
Not sure if this was intended or not but explicit maps don't show up in https://osu.ppy.sh/api/v2/beatmapsets/search/ when using client credentials.

**Comment by venix12** [comment]
You need to add ``nsfw=true`` parameter to the url, for example ``https://osu.ppy.sh/api/v2/beatmapsets/search?nsfw=true``.

**Comment by Magnus-Cosmos** [comment]
https://github.com/ppy/osu-web/blob/1e59b56ee57e4347e1f31b99cfcb871f1ccc850b/app/Libraries/Search/BeatmapsetSearchRequestParams.php#L77-L79
The nsfw parameter only works if there is the user is not null (i.e. client credentials will not work because there is no user)

**Comment by venix12** [comment]
i tested this on my oauth2 environment and seemed to work, though? pretty sure it'd work when you have a proper oauth2 workflow set up.

**Comment by sometimeszzzzzzz** [comment]
Don't know if I'm doing something wrong, but explicit maps still don't show up for me when using client credentials
Using postman:

https://user-images.githubusercontent.com/52870410/104368858-a6a76200-54ea-11eb-8f6c-15d16373e21d.mp4

**Comment by bdach** [comment]
the change in the PR above needs to be deployed to production still, which I believe hasn't happened yet.
