### ISSUE TITLE
Changing ruleset should not change the selected difficulty

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-web#7058]
After selecting a difficulty on a beatmap page, changing the ruleset will always reset your selection to the top difficulty in the new ruleset.

The difficulty should only change when either:
1. The page loads for the first time.
2. The difficulty doesn't exist in the new ruleset (e.g. changing from osu!mania to osu!).

https://drive.google.com/file/d/1kNwf9jPB-S79QtG0FSnV7cZUVVrGQIfB/view?usp=sharing

**Comment by nanaya** [comment]
I have vague memory it was intentionally changed to the current behavior. Something along the line viewing proper difficulty when changing mode instead of converted.

**Comment by smoogipoo** [comment]
Personally I'd expect the OP to still be the case even in that scenario, based on my thinking that the amount of cases you want to view a ruleset other than your default being the exception. It's also the way lazer, stable, and osu-web-10 operate.
