### ISSUE TITLE
Recommended difficulty doesn't apply on loading a beatmap from the listing

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#7059]
The selected beatmap should be the recommended one (via https://github.com/ppy/osu-web/blob/ce1db2df867d564e4ee082a3f2e01cf032987394/app/Models/User.php#L1690-L1698), on entering the beatmap info page from the listing

**Comment by nanaya** [comment]
Hmm, this will require querying all four stats table when getting user data :thinking:

**Comment by smoogipoo** [comment]
This should also have an option. For example most people viewing Freedom Dive are likely to see the `Another` diff which is probably not what people always want when randomly viewing beatmaps.

**Comment by peppy** [comment]
They can just click the one they care about in that rare case? I'm against adding an option unless there is a need for it.
