### ISSUE TITLE
Beatmap page: Top score does not show mods

### ISSUE THREAD

**Issue by kevinwlau** [ppy/osu-web#706]
The #1 score on the beatmap page scoreboard card does not show what mods were used.

![image](https://cloud.githubusercontent.com/assets/689163/17792862/063165ca-6569-11e6-811c-6b38b5b8e97f.png)

**Comment by ColdVolcano** [comment]
Have you seen #559 ?

**Comment by kevinwlau** [comment]
Oh, no I didn't see the redesign.
