### ISSUE TITLE
osu! direct category for subscribed mappers.

### ISSUE THREAD

**Issue by Nyanaro** [ppy/osu-web#7081]
Fairly self explanatory. It would be really nice if subscribed mappers would get their own osu! direct listing. This would make subscribing to mappers a lot more practical and interactive, and also make it easier to download all maps from a mapper, and not just the most recent ones.

This could of course also be expanded to the website's beatmap listing.

**Comment by nanaya** [comment]
You can already download all maps from a mapper by going to their profile page.

**Comment by smoogipoo** [comment]
@nanaya It's easier to filter by a category and get an aggregate listing of all beatmaps that you have and haven't downloaded, than to individually go through all the mappers. It's similar to the "Subscriptions" category on YouTube (I'm not going to go through 300 subscribed creators to see if they have any new videos up).

**Comment by nanaya** [comment]
I'm only covering this part:

> and also make it easier to download all maps from a mapper
