### ISSUE TITLE
Add "Genre" and "Language" on BeatmapSetCompact (API)

### ISSUE THREAD

**Issue by Cristian-Sknz** [ppy/osu-web#7086]
I used API V1, I started using V2 a little while ago. One difference I noticed, was that beatmap requests (v1) always returned genre_id and language_id.
> _api/get_beatmaps_
```json
"genre_id": "10",
"language_id": "3",
```
In v2 these values ​​can only be obtained by requesting BeatmapSet.
> _api/v2/beatmapsets/_
```json
"genre": {
  "id": 10,
  "name": "Electronic"
},
"language": {
  "id": 3,
  "name": "Japonês"
},
  ```

**Comment by notbakaneko** [comment]
`language` and `genre` are defined on `Beatmapset`, not `Beatmap`; get it from the beatmapset.

**Comment by Cristian-Sknz** [comment]
I would have to make 2 requests just to receive this information.

**Comment by peppy** [comment]
Can you explain how you are querying with only beatmap_id available? We usually have both available wherever one is.

**Comment by Cristian-Sknz** [comment]
> Can you explain how you are querying with only beatmap_id available? We usually have both available wherever one is.

When I make requests to `/beatmaps/{beatmap}`, these values ​​are not available, they are only available when making another request to `/beatmapsets/{beatmapset}`
