### ISSUE TITLE
php-fpm fails to start on first initialization

### ISSUE THREAD

**Issue by roupkk** [ppy/osu-web#709]
When I run `vagrant up` for the first time, starting php7.0-fpm always fails, resulting 502 bad gateway. So I should manually start fpm.

I guess fpm socket does not created yet when calling [this line](https://github.com/ppy/osu-web/blob/master/vagrant/Vagrantfile#L64) first time.

provisioning script result:

<pre>
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default:  * Stopping MySQL Community Server 5.7.14
==> default: .
==> default: .
==> default: .
==> default:  * MySQL Community Server 5.7.14 is stopped
==> default:  * Re-starting MySQL Community Server 5.7.14
==> default: .
==> default: .
==> default:  * MySQL Community Server 5.7.14 is started
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
<b>==> default:  * Restarting PHP 7.0 FastCGI Process Manager php-fpm7.0
==> default:    ...fail!</b>
==> default: Running provisioner: shell...
    default: Running: inline script
==> default: stdin: is not a tty
==> default:  * Restarting nginx nginx
==> default:    ...done.
</pre>

log file at: `/var/log/php7.0-fpm.log`

```
[20-Aug-2016 05:19:18] ERROR: unable to bind listening socket for address '/run/php/php7.0-fpm.sock': No such file or directory (2)
[20-Aug-2016 05:19:18] ERROR: FPM initialization failed
[20-Aug-2016 05:22:56] ERROR: unable to bind listening socket for address '/run/php/php7.0-fpm.sock': No such file or directory (2)
[20-Aug-2016 05:22:56] ERROR: FPM initialization failed
```
# 

I suggest that check status first, if not running(exit code:3), then start or just restart as previously.

``` ruby
  config.vm.provision "shell", inline: "sudo service php7.0-fpm status; if [ $? == 3 ]; then sudo service php7.0-fpm start; else sudo service php7.0-fpm restart; fi", run: "always"
```

**Comment by peppy** [comment]
We've dropped official vagrant support, but do feel free to PR this change if it's still an issue at your end (we will keep vagrant configuration files in the project for now).
