### ISSUE TITLE
Suggestion: change "Beatmap Mapper" in "MAP" tooltip to "Beatmap Creator"

### ISSUE THREAD

**Issue by tilda** [ppy/osu-web#7097]
IMO the current wording is a bit confusing, "Beatmap Creator" would make more sense.

**Comment by tilda** [comment]
For reference, I mean this tooltip: 
![image](https://user-images.githubusercontent.com/8301262/105347382-72980500-5bac-11eb-98a9-d42051e88aca.png)

**Comment by iptq** [comment]
wtf it me

**Comment by peppy** [comment]
Seems like a good improvement. It would also be great to come up with a better TLA if anyone can think of one.

**Comment by iptq** [comment]
Would it be possible to just have "Mapper" spelled out entirely? Not sure if this conflicts with other designs in different areas

**Comment by Joehuu** [comment]
The comments section already does it. Should also have the same color, see reason in https://github.com/ppy/osu-web/issues/5390#issuecomment-596417893.

![chrome_SkgKWs94Ez](https://user-images.githubusercontent.com/35318437/107136865-d106f800-68bb-11eb-8cfe-fc598abaafbd.jpg)
