### ISSUE TITLE
Filter community choice listing to voted maps only

### ISSUE THREAD

**Issue by iptq** [ppy/osu-web#7099]
many people want to share how they voted in community choice, but the default view shows all maps a user has played without an option to filter it

![image](https://user-images.githubusercontent.com/1700346/105348655-92492080-5be0-11eb-897c-facf9da3ba6f.png)

which means people just end up distributing code to copy-paste into the console

![image](https://user-images.githubusercontent.com/1700346/105348791-bd337480-5be0-11eb-9c3f-019be3e98f43.png)

this (1) doesn't work on mobile, (2) isn't very safe, so could we consider adding a button to just hide the maps that the user hasn't voted for?

**Comment by iptq** [comment]
i could try my hand at implementing this if there's a consensus on the design, i had set up the codebase earlier but wasn't sure what to do :P

**Comment by nanaya** [comment]
Maybe a toggle to the left of "votes" in header area? @arflyte ?

**Comment by arflyte** [comment]
Either we put the toggle, or just push up all the voted maps.

**Comment by iptq** [comment]
My opinion here is pushing up the voted maps without a warning would be kinda confusing if you're scrolled halfway down the list and the map you just picked disappears. An explicit toggle button would be what users are kinda "looking for" so I think it would be a better choice.

**Comment by BlastTheKidd** [comment]
I agree! A togglable sorting option would be a better ux.
