### ISSUE TITLE
In osu!，The China flag is wrong

### ISSUE THREAD

**Issue by timi137137** [ppy/osu-web#7104]
The China flag is wrong,The stars are not at the right Angle.In China, this kind of thing can lead to the game being banned.
Hope to modify!

**Comment by bdach** [comment]
Duplicate - see https://github.com/ppy/osu-web/issues/3760#issuecomment-428825836

**Comment by timi137137** [comment]
i know,but pls modify

**Comment by timi137137** [comment]
you can see 1 years ago

**Comment by peppy** [comment]
We will continue tracking in the other issue. If you can help by providing design updates we can potentially make the change happen faster.
