### ISSUE TITLE
Name changing messes up user search.

### ISSUE THREAD

**Issue by Len-Github** [ppy/osu-web#7122]
I changed my name a few months ago yet people cannot find me through https://osu.ppy.sh/home/search using my current name, it still forces people to type my old name in order to find me. 
![image](https://user-images.githubusercontent.com/78104241/106036380-53d2ca80-60e6-11eb-929c-39046d02d808.png)
![image](https://user-images.githubusercontent.com/78104241/106036392-57fee800-60e6-11eb-9fd3-d5695ad6b92c.png)
Image for example:

**Comment by peppy** [comment]
@Len-Github thanks for the report. we're making a fix for this going forward, and have also started a rebuild of the index. your username should become searchable within the next few hours. do note that as there are spaces in your name there's no guarantee how well it'll appear in search results.

**Comment by Len-Github** [comment]
Thank you peppy!
