### ISSUE TITLE
Difficulty seeing if you've upvoted a comment on mobile

### ISSUE THREAD

**Issue by Purplegaze** [ppy/osu-web#7130]
![Screenshot_20210128-184804_Chrome](https://user-images.githubusercontent.com/25409695/106212819-6823cf80-6199-11eb-8d9b-fd74be2bd078.jpg)
Bottom one is upvoted and top one isn't, and the colour is almost the same, which makes it hard to tell with just a few small characters that change colour. Would make more sense design-wise to use a bright green for comments the user has upvoted to match the colour used on the desktop site.

**Comment by peppy** [comment]
@arflyte any reason we aren't using the standard pill design here?

**Comment by arflyte** [comment]
Probably forgot to match the mobile design as we update the desktop site. It should follow the desktop design.
