### ISSUE TITLE
Copy pasting texts which include new lines automatically split them into new suggestions in modding reviews

### ISSUE THREAD

**Issue by yotm-osu** [ppy/osu-web#7141]
This happens both in other text editor and texts in reviews.
Keeping new lines would be what is expected.
<img src="https://puu.sh/HbXUH/4f5952d5ac.png" style="zoom:50%;" />
<img src="https://puu.sh/HbY0U/edf519e7c4.png" style="zoom:50%;" />

**Comment by peppy** [comment]
Seems like it should be pasted into one issue as a default, for sure.
