### ISSUE TITLE
Local user statistics should be returned with a playlist room request

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#7148]
A call to `/api/v2/rooms/<room_id>` should return some statistics about the local user for display purposes. Currently the one I'm interested in is attempt count as calculated below:

https://github.com/ppy/osu-web/blob/3169b33ccc4c540be5f20136393ad5f00d635ff9/app/Models/Multiplayer/Room.php#L342

More may come as we build on the system. We also need attempt count per playlist item in the near future, so adding that as well may be a good measure.

**Comment by nanaya** [comment]
Apparently that attempt count check already checks per playlist item, it's just the number is uniformly set by the room :thinking: 

A room with 10 max attempts setting and 5 playlist items means 50 max attempts overall; 10 for each playlist items.

**Comment by peppy** [comment]
Hmm, it should be checking the total plays across all items.
