### ISSUE TITLE
Option to Delete Account

### ISSUE THREAD

**Issue by SethFalco** [ppy/osu-web#7151]
It appears to me that osu! doesn't have a feature baked into the web UI to delete ones account.

If someone has found they aren't fond of the game, it makes sense they should be able to delete their account, this could be because:
* It just doesn't have to be there
* To remove personal information such as:
  * Email address
  * Location
  * Username (if it references a real name)

> As a user you have the right to migrate, update or delete your personal information...
>
> If you are covered by the European Union, you have the option of deleting your account from our service. Please note that this is currently a manual process and may take several days to complete (contact us to file a request).

In other words, this has been in the privacy policy since 2018, namely the "this is currently a manual process". It would be nice if this could shift from a manual to autonomous process?

**Comment by peppy** [comment]
The overhead of making it an automatic process is probably going to end up higher for us. Due to people attempting to return to the game after deleting their account. By keeping it manual we add higher bars to screwing yourself over for life.

**Comment by peppy** [comment]
On consulting with the support team, the throughput isn't high enough to consider automation for now. We may reconsider it at a future date.
