### ISSUE TITLE
suggestion for osu! (a really useful option)

### ISSUE THREAD

**Issue by Kuganee** [ppy/osu-web#7154]
It would be extremely appreciated if you added the option "remove corrupted beatmap". 
having downloaded a 58gb pack of beatmap, several hundreds are corrupted in different ways, either the music doesn't play and we can't click on the circles, or the beatmap starts very well but in the middle of it the problem mentioned above occurs, or the beatmap is cut as soon as we launch it, so it would be really appreciated to have an option to remove the corrupted beatmap as soon as possible.

**Comment by bdach** [comment]
This seems like the wrong place to post this. This repository is for the website only, not the game client itself.

Also I'm not sure where the "58gb" beatmap pack is coming from, but it's surely unofficial and this is really your problem at that point. Would recommend to download beatmaps only from trusted and supported sources, like the official beatmap packs, the website, or osu!direct in game.
