### ISSUE TITLE
Archived web chats are being sorted in reverse chronological order

### ISSUE THREAD

**Issue by Uberzolik** [ppy/osu-web#7175]
Already opened chats are displaying in reverse order, meaning all recent messages I've received are now at the very bottom of the chat list. This is especially troublesome as a BN, given I cannot find any of the recent messages due to the sheer amount of messages I have received and left open in new chat. 

Newly opened chats do move to the top as intended, but once they're "archived" again they're sent back to the very bottom.

I made a recording where I open a recent chat and then refresh the page, to demonstrate the behavior:

https://user-images.githubusercontent.com/12388394/107062518-2528b400-67b8-11eb-9b6a-18c8fd128a46.mp4

**Comment by notbakaneko** [comment]
This is likely a result of the optimization in #7146; channels that haven't received any new messages since it was deployed will have `last_message_id` of `null` causing their order in the list to be unknown - selecting the channel loads the messages allowing the client to infer its order.

**Comment by iptq** [comment]
Would it be possible to run an indexing task or to perform the old expensive query over just the `last_message_id`s that contain a value of `null`? Theoretically this number should get smaller and smaller over time. Otherwise people will need to open every single chat to reobtain the original order.

**Comment by notbakaneko** [comment]
We'll probably run a job that backfills in the missing ids
