### ISSUE TITLE
API users route not returning user object while providing username

### ISSUE THREAD

**Issue by Syudagye** [ppy/osu-web#7176]
I needed to use the osu!api for one of my projects, and I faced this problem:
Sending a `get` request to the api route `/users/{ userId }` didn't returned the user object, but html code instead.

For example, executing this :
`$ curl -H "Authorization: Bearer [TOKEN]" https://osu.ppy.sh/api/v2/users/Syudagye`
returned:
```
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url='https://osu.ppy.sh/api/v2/users/11205353'" />

        <title>Redirecting to https://osu.ppy.sh/api/v2/users/11205353</title>
    </head>
    <body>
        Redirecting to <a href="https://osu.ppy.sh/api/v2/users/11205353">https://osu.ppy.sh/api/v2/users/11205353</a>.
    </body>
</html>
```
Executing it with the user id works just fine :
`$ curl -H "Authorization: Bearer [TOKEN]" https://osu.ppy.sh/api/v2/users/11205353` return a user object

Looking at the code i found [here](https://github.com/ppy/osu-web/blob/38efd618b9334160161a0d3e3163a0d6cc53beec/app/Http/Controllers/UsersController.php#L488) that it checks is the id is the real id or not, and then checks if it is an api request, but seems to redirect it as if it is a normal request from the website.
So I was wondering if there is something i'm doing wrong or is it just not implemented that way.

**Comment by Joehuu** [comment]
Try adding `-L`.

Ref: https://curl.se/docs/manpage.html#-L

**Comment by iptq** [comment]
Per the [docs](https://osu.ppy.sh/docs/#get-user) the user id must be the numerical id of the user. AFAIK the best way to lookup user data by ID is the old api: https://github.com/ppy/osu-api/wiki#apiget_user.

To avoid HTML output breaking your code, you should be checking the return status of the response _before_ parsing the body, and only parsing the body if the response you received is a 200.

**Comment by Syudagye** [comment]
> Try adding `-L`.
> 
> Ref: https://curl.se/docs/manpage.html#-L

Thanks that fixed it, now I'll try to implement that.
