### ISSUE TITLE
Unavailable usernames show as a free name change in API response

### ISSUE THREAD

**Issue by tilda** [ppy/osu-web#7177]
This isn't really important - but figured I'd write here just in case.

Here's a API response from me looking up `Vaxei` on the Player Name Change section of the store:
```js
{
  "username":"Vaxei",
  "available":false,
  "message":"Username is already in use!",
  "cost":0,
  "costString":"free!" // wow, free?!
}
```

and here's me looking up an actual username I could use on the same page:
```js
// for the record, i wouldn't actually name change to this
{
  "username":"AwesomeName92",
  "available":true,
  "message":"Username 'AwesomeName92' is available!",
  "cost":8,
  "costString":"US$8.00" // ... turns out i do not have another free name change
} 
```

The difference between those 2 is the data for the pricing (which should probably be consistent).

Ways this could be tackled from a initial thought:
- Don't include `cost` and `costString` at all if the username is unavailable (could possibly cause errors on FE and would require more changes than 2nd solution)
- If above isn't feasible, perhaps just make `costString` blank to avoid possible confusion? (probably the most ideal one out of the 2 here)

(Sidenote: I spent way too long writing this)

**Comment by notbakaneko** [comment]
It doesn't matter; the endpoint is not meant to be used by anything other than the page itself, it's not to be called directly
