### ISSUE TITLE
Links in Beatmap Discussion page should open in new tab

### ISSUE THREAD

**Issue by MaxKruse** [ppy/osu-web#7179]
Hello,

as of today, when click any external links in a beatmap discussion page, such as https://osu.ppy.sh/beatmapsets/1039618/discussion/2246149/timeline#/2147666 all links are opened in the same tab by default. This is unintuitive and should be done with a new tab.

target="_blank" would be the only change needed, so not a lot of work...

**Comment by peppy** [comment]
Given that the discussions page is one you're meant to stay on unless explicitly navigating away to a different area of the site, this makes sense.
