### ISSUE TITLE
Suggestion: Subscription to mappers by Tags

### ISSUE THREAD

**Issue by PaRaDogi** [ppy/osu-web#7183]
Hello, i think the new subscribe feature is great to get informed about you favorite mappers maps being uploaded or ranked. I think what would be cool to add is notification for all maps the mapper is featured in by tags. 
Like guest diffcultys, hitsounds etc....
you could see you favorite mapper have a ranked guest diffculty show in you notification wich not only helps the person subscribing to the mapper but also to the host of the set get also recognized.

**Comment by peppy** [comment]
#4750
