### ISSUE TITLE
Ruleset statistics returned by /v2/users/?ids[]=<id> are not easily deserializable lazer-side

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu-web#7197]
Currently `statistics_{osu/taiko/...}` properties from `/v2/users/?ids[]=<id>` are added directly to the main user JSON object:
```json
{
    "users": [
        {
            "id": 14210502,
            "statistics_fruits": {
                 ...
            },
            "statistics_mania": {
                 ...
            },
            "statistics_osu": {
                 ...
            },
            "statistics_taiko": {
                 ...
            },
        ...
        }
    ]
}
```

Which makes deserializing this lazer-side complicated than usual, as it is not simply determinable what the property names are, without writing extra logic to get all properties that start with "statistics_" and parse them properly.

Therefore I request making these statistics be contained in a single property called `all_statistics` or otherwise, that makes deserializing this lazer-side pretty straightforward, given how the deserializer used there does its job:
```json
{
    "users": [
        {
            "id": 14210502,
            "all_statistics": {
                "fruits": {
                    ...
                },
                "mania": {
                    ...
                },
                "osu": {
                    ...
                },
                "taiko": {
                    ...
                },
            }
        ...
        }
    ]
}
```

**Comment by peppy** [comment]
Also keep in mind that we will likely be adding more rulesets in the future, so this lends itself to being easier to populate more items in.
