### ISSUE TITLE
std/mania map is treated as two separate sets

### ISSUE THREAD

**Issue by jxu** [ppy/osu-web#7199]
I had a map with std and mania diffs I tried to add different map bgs for.
After I did a map refresh in-game with F5, the game treats them as different sets, even though they should be the same set?
And they don't show up at all online https://osu.ppy.sh/beatmapsets/1354180#osu/2837463 

maybe i'm missing something obvious?

mania map:
```
[Metadata]
Title:Battle! Roaming Legendary Pokemon
TitleUnicode:Battle! Roaming Legendary Pokemon
Artist:Junichi Masuda
ArtistUnicode:Junichi Masuda
Creator:qwr
Version:qwr's Tornadus
Source:Pokemon: Black/White
Tags:game freak musketeer trio nintendo Irreversible cheesiest
BeatmapID:2803116
BeatmapSetID:1354180
```

std map:
```
[Metadata]
Title:Battle! Roaming Legendary Pokemon
TitleUnicode:Battle! Roaming Legendary Pokemon
Artist:Junichi Masuda
ArtistUnicode:Junichi Masuda
Creator:qwr
Version:qwr's Thundurus
Source:Pokemon: Black/White
Tags:game freak musketeer trio nintendo Irreversible cheesiest
BeatmapID:2837463
BeatmapSetID:1354180
```

[1354180 Junichi Masuda - Battle! Roaming Legendary Pokemon.zip](https://github.com/ppy/osu-web/files/5968814/1354180.Junichi.Masuda.-.Battle.Roaming.Legendary.Pokemon.zip)

**Comment by jxu** [comment]
I tried deleting my submission cache and that treats the maps as the same collection.
However sometimes when updating, I get the error "The request was aborted: Could not create SSL/TLS secure channel.

**Comment by peppy** [comment]
Can presume this is fixed then? SSL/TLS issues are something on your PC, not osu!.

**Comment by jxu** [comment]
Also osu always says my backgrounds are unused, do you want to delete them, even though each diff should have a different bg.
