### ISSUE TITLE
Official MIME types

### ISSUE THREAD

**Issue by fmang** [ppy/osu-web#7202]
As far as I know, there are no officially defined MIME types for the file formats osu! uses.

Looking for related issues, I found https://github.com/ppy/osu/issues/1030, which is related to what I'm trying to do: desktop integration. It is not specific to osu!lazer though, and applies to osu!stable.

The MIME type is the main metadata browsers and file explorers use when identifying a file to provide a default application to open the file with. Many applications became tolerant and are okay with falling back on the file extension, but some won't. Beside, some environments require a MIME type when registering an extension.

For optimal cross-platform support, the osu! website should send a specific MIME type along with downloadable files, and every osu! installer should register that MIME with the extension.

I have a few ideas:

- application/x-osu-beatmap for .osu
- application/x-osu-storyboard for .osb
- application/x-osu-skin for .osk
- application/x-osu-replay for .osr
- application/x-osu-archive for .osz

It is not central to the game's development, but I believe it's a quick win for desktop integration.

The best place to document this is probably https://osu.ppy.sh/help/wiki/osu!_File_Formats

**Comment by peppy** [comment]
Moving this across to osu-web so we can action on it better. It seems like this may be a good direction forward to better support some browsers which disagree with our `application/download` specification for beatmaps and other files.

Not sure if changes are required in osu-web or just legacy systems.

**Comment by nanaya** [comment]
I think the only osu file served directly by osu-web is replay files? The rest should be done by whatever actually serving the file.

FWIW it's currently set to `application/octet-stream` which is the generic type for download files. I've never heard about `application/download` before.

https://tools.ietf.org/html/rfc1521

````
    application -- some other kind of data, typically
         either uninterpreted binary data or information to
         be processed by a mail-based application.  The
         primary subtype, "octet-stream", is to be used in
         the case of uninterpreted binary data, in which
         case the simplest recommended action is to offer
         to write the information into a file for the user.
````

**Comment by peppy** [comment]
For beatmap downloads (the main issue here) we specify three content types. I'm not even sure if this is valid (so only the last one is probably being applied?):

```php
header("Content-Type: application/force-download");
header("Content-Type: application/octet-stream");
header("Content-Type: application/download");
header("Content-Transfer-Encoding: binary");
header("Content-Length: " . filesize($localFilename));
header("X-Accel-Buffering: yes");
header("X-Accel-Redirect: /{$localFilename}");
header("Content-Disposition: attachment;filename=\"$serveFilename\";");
```

As a first step I guess switching to `octet-stream` may be an improvement? But maybe at that point making the jump to a custom one is more beneficial?

**Comment by nanaya** [comment]
Either php or nginx or something else strips it out to just the last header as [it's generally not allowed to have multiple headers of same field name](https://tools.ietf.org/html/rfc7230#section-3.2.2).

A well behaved client should generally able to handle unknown type (handled as if it's `application/octet-stream`). `x-` prefix should be fine to be used for custom types. If feeling official, [may also get our own vnd-prefixed type](https://www.iana.org/assignments/media-types/media-types.xhtml). I don't know how that works though.

**Comment by nanaya** [comment]
Apparently firefox (and maybe other browsers?) inhibit weird behavior if nonstandard mime type (`application/download` in this case) used for different type of files.

For example this seemingly innocent download dialog:

![](https://s.myconan.net/2021-02/firefox_2021-02-15_22-46-56.png)

If as per the screenshot, set to open with WMP and "do this automatically..." is checked, any further downloads with similar server-returned mime type (`application/download` in this case), even with different extension, will also automatically be opened with WMP.

This doesn't happen with `application/octet-stream` as far as I can tell.

(the actual behavior is slightly more complex)

**Comment by peppy** [comment]
I've updated the beatmap mirrors to serve as `application/x-osu-archive`. Will keep this issue open to track the remaining cases (`.osu` being the main one, I guess).

**Comment by peppy** [comment]
Going to try and finalise this specification before we get too far in adding usages of it. One discrepancy is `osu-archive` and `osu-skin` – both of these cases are achives but one is a beatmap and one is a skin, so it doesn't make sense that the `archive` term is dropped for the skin case.

I propose we use:

```csharp
osu application/x-osu-beatmap
osb application/x-osu-storyboard
osr application/x-osu-replay
osz application/x-osu-beatmap-archive
osk application/x-osu-skin-archive
```

**Comment by peppy** [comment]
I've updated all the usages of this in lazer. Will push out a `web-10` change to serve beatmaps as `x-osu-beatmap-archive` instead of `x-osu-archive` after the next lazer release (as to not break compatibility completely).

**Comment by peppy** [comment]
Going to close this issue as we have decided on the mime types. Please leave a comment if you happen to find somewhere where they are not being served correctly. ( @nanaya we may need to update the nginx configuration to correctly handle featured artist beatmap downloads? )
