### ISSUE TITLE
Can't distinguish issue types on modding pages on mobile

### ISSUE THREAD

**Issue by iptq** [ppy/osu-web#7207]
Here's an example: what's usually on the side is not visible at all on mobile, so when I get a new notification about my map I can't tell whether it's a problem, suggestion, praise, or hype except by reading the text and guessing.

![Screenshot_20210212-080140.png](https://user-images.githubusercontent.com/1700346/107777521-8c8aba80-6d08-11eb-93c7-10a7e4f431af.png)

If it helps, firefox on Pixel 3xl

**Comment by notbakaneko** [comment]
I could have sworn there was a matching colour-coded bar before 🤔

**Comment by Hiviexd** [comment]
Any update on this? 2 years later and it's still a major inconvenience to check mods on mobile

**Comment by notbakaneko** [comment]
I could have sworn I had a branch with this added 🤔
