### ISSUE TITLE
Security Idea: Ability to see recent sessions and end them

### ISSUE THREAD

**Issue by Nath789** [ppy/osu-web#721]
To keep track our activities, I think it's necessary to add a place where we can see our web sessions, showing details (e.g. country) where we logged in and able to end these sessions (excluding the current) that are not familiar to us. Another security measure along with the current verification system.

**Comment by sr229** [comment]
By you mean "ending sessions" like Revoking future access to your account on that particular machine/location/IP?

**Comment by Seventth** [comment]
Most likely Nathanael is probably referring to the addition of two things

A location on the new site (probably on the new vers. of the User CP or (work in process) home page that contains a list of successful or unsuccessful logins on the website which contains  eco-location as well as the IP address/System OS of where the access was done and the ability to end those login session by a button. Though I do probably recommend also an email being sent to the email registered of the web login in question

I agree this probably could be a second wall for user verfication.

**Comment by sr229** [comment]
I agree with this motive IMHO since this has been used by alot of websites
