### ISSUE TITLE
Score difference in Playlist Lobbies

### ISSUE THREAD

**Issue by goldey1308** [ppy/osu-web#7217]
The score on a Playlist's leaderboard is not the same as the sum of the individual scores. Score differences vary.
![score-difference](https://user-images.githubusercontent.com/26635047/108062446-1795e880-705a-11eb-885d-3fadae94a040.png)

**Comment by nanaya** [comment]
I just checked the database directly and the spotlight mentioned above ([assuming this one](https://osu.ppy.sh/multiplayer/rooms/46680)) seems to have all the total score matches with their respective high scores.

Please specify more details on how you processed the data.

**Comment by nanaya** [comment]
No update on this, assuming reporter made mistake on their calculation.
