### ISSUE TITLE
Exclude hype posts from user filter list in modding discussions

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#7241]
Trying to find the filter option for specific modders on highly hyped maps is downright painful, there's gotta be a better way. Like typing one in and it autocompletes to whatever uses posted on the map?
![2021-02-20_16-53-28](https://user-images.githubusercontent.com/33286824/108609489-3965d700-739c-11eb-9094-bddc25e3c1d4.gif)

**Comment by peppy** [comment]
That list is getting so long that it probably shouldn't even be showing all users.. maybe sorted by amount of participation from each user and be limited to the top 5 or 10, along with a search field at the top?

**Comment by dorothy3242** [comment]
That or potentially make it modders only and exclude users who only hyped the map? Most big cases like this is just from hypes

**Comment by peppy** [comment]
Oh, that makes sense actually. We can probably get that change made very easily, and it should alleviate the majority of the issue.
