### ISSUE TITLE
Deleted Threads trying to load "show more" forever

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#7247]
If a thread is deleted it tries to load stuff via "show more" infinetly
![85e2FukaD8](https://user-images.githubusercontent.com/35633093/108850113-43c5e200-75e3-11eb-88f8-e563c07ac599.gif)

**Comment by nanaya** [comment]
Delete process has been updated and this shouldn't happen again. Behavior for current problematic topics should be fixed by #7225.
