### ISSUE TITLE
Clicking chat button on profile does not direct to user's chat

### ISSUE THREAD

**Issue by dorothy3242** [ppy/osu-web#7249]
It seems this has broken recently. The link still gets formatted as https://osu.ppy.sh/community/chat?sendto=USERID but it opens to the #osu chat instead of their dm. This has made it wonky to open new dms via the website.

For example
![image](https://user-images.githubusercontent.com/33286824/108922171-a9769600-7604-11eb-90cc-4354f02789b5.png)

takes me to 

![image](https://user-images.githubusercontent.com/33286824/108922227-bbf0cf80-7604-11eb-97c6-6ca9bb5cbdde.png)

their chat is not available on the left side at this point either
it will only work after refreshing the page

**Comment by nanaya** [comment]
Looks like once chat is initialized, it doesn't accept new states when the page is accessed again
