### ISSUE TITLE
"Show Deleted" behaviour on comments

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#7254]
The amount of deleted posts is only visible while "show deleted" is **not** selected. This should probably be also shown while "show deleted" is enabled, so that one wont need to change and therefore reload the setting if they want to know the count for whatever reason.

In addition to this, users that are not moderators can see the count of deleted posts and use the "show deleted" setting, but it doesnt shown them anything really besides who the user was. This probably shouldnt be a thing, since thats not really something users should know.
![](https://cdn.discordapp.com/attachments/276296389519081472/814194869567488080/unknown.png)

**Comment by notbakaneko** [comment]
This is currently intentional as deleting a comment with threaded replies would otherwise leave a dangling thread tracking onto nothing

**Comment by peppy** [comment]
So basically, the "show deleted" option shouldn't be available to non-moderators.

**Comment by RockRoller01** [comment]
@peppy that and that it should probabyl always display the amount of deleted posts and not just while you are not looking at them
