### ISSUE TITLE
Change elasticsearch alias creation order

### ISSUE THREAD

**Issue by nanaya** [ppy/osu-web#7256]
Creating new index currently potentially leave outdated data in the new index because how the indexing works:

1. create new index
2. index data to new index
3. add new index to alias
4. remove old indexes

`2` takes a while and any updates happened during the process will go to the old index.

A better process would be:

1. create new index
2. update alias, set new index as writing index
3. index data to the alias
4. remove old indexes

Unless we're short on disk space this should also remove the need for inplace indexing? :thinking:

**Comment by peppy** [comment]
How does this work? Would there be two aliases, one for writing and one for reading? Or is the "writing index" thing you mentioned some built-in elasticsearch behaviour?

**Comment by nanaya** [comment]
one alias can point to multiple indexes. One of them can be marked as writing index.

**Comment by notbakaneko** [comment]
Having multiple indexes in the same alias while reindexing is going to result in duplicate search results (and if a DB query is needed after, less results that there should be); marking a writeable index in an alias is usually for rolling over things like time-series data into new indexes.

**Comment by nanaya** [comment]
Hmm, I guess the only way to not potentially end up with outdated index entry is by creating separate alias for writing and reading then.

**Comment by peppy** [comment]
It does sound like a good path forward I think... should simplify the schema migration process quite a bit (although the current one *has* been pretty resilient until now).

**Comment by nanaya** [comment]
closing as the originally proposed  idea doesn't work and I can't find better way to do it
