### ISSUE TITLE
Revived mapset notification for mapping subscribers

### ISSUE THREAD

**Issue by Apis035** [ppy/osu-web#7276]
When someone revived a mapset from graveyard it gives a notification to their mapping subscribers. So the subscribe feature has more function than just noticing about new maps from the mapper.

**Comment by peppy** [comment]
Sounds like a good addition.

**Comment by Apis035** [comment]
I just realized that I never see this feature in action. Recently a user that I subscribed revived a map, and I didn't get notification about it.

Haven't asked this with others if they ever see the revived mapset notification, so maybe it was just me.

**Comment by peppy** [comment]
Tested, doesn't seem to be working.

**Comment by nanaya** [comment]
This needs the backend which deals with beatmap revival to hit the new endpoint created in the related pr... (similar to new beatmap notification - just replace `broadcast-new` with `broadcast-revive` iirc)

**Comment by peppy** [comment]
Thanks, have added this.
