### ISSUE TITLE
Forum Posts unable to jump to last post

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#7278]
Got no clue why, (but from what I have heard it may have to do with deleted posts), but some forum threads are unable to skip to the end. It seems to only happen with posts that have more than 20 posts, aka ones where you need to load more. If you hit the button it tries to load but you stay on post #1.

Here is one: https://osu.ppy.sh/community/forums/topics/793342?n=53

**Comment by nanaya** [comment]
The thread has wrong topic count.

The topic controller should probably also be updated to handle case when `n` is larger than posts count. And maybe change the link to specify "latest" or something like that instead of post number.

**Comment by notbakaneko** [comment]
Post position doesn't include deleted posts.
