### ISSUE TITLE
Add the ability to toggle favourite from a beatmap's card

### ISSUE THREAD

**Issue by Zander100** [ppy/osu-web#7286]
Hello everyone,
my idea would be to be able to favourite beatmaps by having next to the small downlaod button in the website also a heart button, that when clicked favourites the beatmap or removes the favourite from the beatmap.

Basically a heart symbol maybe that is empty when not favourited and is full when favourited.

I came up with this idea after wanting to remove some favourites I have on maps and by wanting to remove them I always have to click on the beatmap and then remove the favourite. With this I can just quickly do it from my osu! page removing the favourites directly.
Or when searching for beatmaps you can just quickly add a favourite if you enjoyed it etc.

I hope you all like my idea! I also hope it will be implemented to the website!

Kind regards <3

**Comment by peppy** [comment]
@nanaya i don't suppose this is already implemented in the new cards as one of the buttons in the right area? or if there's potentially room to add it?

**Comment by nanaya** [comment]
Added on new card
