### ISSUE TITLE
Beatmap audio preview asks for verification

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-web#7295]
I'm trying to listen to a single beatmap, and the song is a little quiet, so I tap the volume, and it asks me to verify my account. I don't know how frequent this is though the most I can say is every day. Changing audio volume shouldn't ask for my verification. I think you are better off refreshing the website than verifying your account again.

**Comment by WinterIsPretty** [comment]
it asks for verification yet still keeps the volume where you set it at if you refresh the website so this doesn't make any sense

**Comment by peppy** [comment]
Could you please make a video showing this happening?

**Comment by Joehuu** [comment]
https://user-images.githubusercontent.com/35318437/110562993-671e8000-80ff-11eb-8239-1fb6a5dd364e.mp4

**Comment by peppy** [comment]
This probably shouldn't need verification, even though it's an account setting (because it's such an unimportant one).

**Comment by notbakaneko** [comment]
It doesn't normally require verification, this verification is part of the `USER_POST_ACTION_VERIFICATION` env setting

**Comment by peppy** [comment]
Should we be turning that off?

**Comment by nanaya** [comment]
Unless verification is required for all modifying actions (forum post, favoriting beatmap, changing audio volume settings, etc), it should be off.

If we're going to always require that then we should remove the option and go with whitelisting approach instead, listing which operations don't require user verification.

**Comment by peppy** [comment]
So just to confirm, this is because we are storing the volume level to the database session, rather than browser session? Not sure if that is correct behaviour (wouldn't you think that volume is per-PC rather than per account?)

**Comment by nanaya** [comment]
yes it's currently stored per account. There's no "per-pc" for web pages but otherwise that may make sense? Although the setting will be reset whenever they log out in that case. There are also two other settings on that audio control - mute and "auto play next"

**Comment by peppy** [comment]
Maybe fine to store all of those in local storage, not sure. The other option is just to let this be as an edge case which most users aren't going to hit.

**Comment by nanaya** [comment]
Has been fixed by #9674 and #4596
