### ISSUE TITLE
API UserBeatmapScores endpoint to include score for each mod combination

### ISSUE THREAD

**Issue by MaxOhn** [ppy/osu-web#7301]
The API v1 endpoint `/api/get_scores?b={map}&u={user}` currently returns the top score of the user on the map *for each mod combination*.
In API v2 I believe `/beatmaps/{map}/scores/users/{user}` is the closest thing to that, but it returns only the very top score of the user on the map.

I'm kinda missing that feature on the new API, any chance of adding that back in or is it deliberately omitted?

**Comment by peppy** [comment]
I don't believe it was deliberately removed.

**Comment by minhducsun2002** [comment]
Any updates on this? It has been almost a year I believe.

**Comment by peppy** [comment]
Will bring this up in priority. Not sure if we have a similar request existing yet.
