### ISSUE TITLE
DMCA'd map still downloadable

### ISSUE THREAD

**Issue by cihe13375** [ppy/osu-web#7307]
https://osu.ppy.sh/beatmapsets/60136#osu/181509
This map is DMCA'd (like many other a_hisa maps, and not visible in search lists) but the download seems working perfectly (with mp3, video and bg) and score submission is also fine. What's happening here?
![图片](https://user-images.githubusercontent.com/33959010/111028167-f09bbe00-842f-11eb-8ca1-39b31b58d0b3.png)

**Comment by peppy** [comment]
Will look into this, but this is not an osu-web issue (for future correspondence, email works best for things like this).
