### ISSUE TITLE
Certain scores incorrectly displaying pp values as "processing"

### ISSUE THREAD

**Issue by E223** [ppy/osu-web#7308]
Currently, mania scores in some cases can be worth exactly 0pp. I believe this is causing them to indefinitely show their pp value as "still being calculated" in the recent plays section of user profiles, score pages, beatmap listings, etc.

A bunch of example scores affected by this can be found on [this map](https://osu.ppy.sh/beatmapsets/1071024#mania/2241878) with the "No Fail" mod selected (though it should be noted this can occur without No Fail as well).

**Comment by peppy** [comment]
Would be good to get some attention on this one. Hopefully just an incorrect `=== 0` that needs to be fixed.
