### ISSUE TITLE
0pp scores are displayed as a warning symbol

### ISSUE THREAD

**Issue by mcendu** [ppy/osu-web#7309]
![image](https://user-images.githubusercontent.com/43639171/111064368-adeceb00-84ee-11eb-8071-3c9bc6af516b.png)

**Comment by frenzibyte** [comment]
Sounds like a duplicate of https://github.com/ppy/osu-web/issues/7308?

**Comment by mcendu** [comment]
The above screenshot is from an std profile, btw
