### ISSUE TITLE
Make commenting/upvoting permission only unlocked after a fixed amount of time to prevent spam

### ISSUE THREAD

**Issue by iptq** [ppy/osu-web#7311]
Lots of fresh multiaccts are being made to promote or upvote political stances, and although multiaccts are not allowed, detecting them takes time and the effects of their comments are immediately obvious. People should not be abusing multiaccts to get their points across, they should be doing it on their main.

Many platforms like Discord have a mechanic that doesn't allow commenting until your account is X minutes old. Having commenting and upvoting become "unlocked" after some time would mitigate this problem in the future and make it so heated situations aren't made unnecessarily harder on moderators by a bunch of people multiaccounting as well.

**Comment by peppy** [comment]
First of all, I have no idea what you're talking about here. We already have systems in place to handle new accounts, spam, etc. and I am not aware of "fresh multiaccts" you are talking about.

This is not the correct place to report this, though. If you are seeing abuse of the system, please contact accounts@ppy.sh.
