### ISSUE TITLE
Featured Artist might need its own usergroup

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#7312]
As shown with [VINXIS](https://osu.ppy.sh/users/4323406), Featured Artists can sometimes be well integrated members of the community who might have other usergroups/titles.

Presently, Featured Artist is set via a custom rank, which overwrites usergroup titles and *inherits their colours*. This creates situations as seen [here](https://puu.sh/HpgKK/266479463a.png), which aren't particularly helpful to lay users who might not be familiar with what the colours mean.

Featured Artists should have their own usergroup with an acronym and little badge, possibly a music note icon from font awesome or something like it. That way, we can safely categorize Featured Artist users into multiple usergroups without causing peculiar overlaps or necessitating the need for custom titles/ranks.

**Comment by peppy** [comment]
Do you need anything to make this happen? I'm fine with migrating them away from the custom titles (since we were really trying to stop using that...). Not sure about the music note, but `FA` should work fine?

**Comment by Ephemeralis** [comment]
Need a usergroup made and a colour for it - will probably need flyte's input on what that should be to avoid turning profiles into an episode of art attack.

If you make the actual group, I can handle the rest. Still think you should consider some sort of icon for FA, though!

**Comment by peppy** [comment]
I've added a new group for this purpose (`id=35`). Let me know if anything else is required.

**Comment by Ephemeralis** [comment]
Added all applicable people to the group and set the group with colour ```00FFFF``` tentatively, and the identifier ```featured_artist```.
