### ISSUE TITLE
osu! medal - "I can see the top" (top 50k) awarded incorrectly

### ISSUE THREAD

**Issue by CoolDudeGD** [ppy/osu-web#7318]
![image](https://user-images.githubusercontent.com/70100054/111271876-ebd04780-8685-11eb-86f4-11ae004e7947.png)
![image](https://user-images.githubusercontent.com/70100054/111271909-f8ed3680-8685-11eb-82fb-7201ade9ea39.png)

These photos are under the osu! tap (not ctb)

I think I got this award by playing catch the beat and passing 50k ranks playing a catch the beat specific map, while in osu! standard mode. Not sure if this only happened to me or happens to others as well. Also note that the award for passing 50k did not appear in game on the final end screen. You can check out my profile in the link below to see for yourself.

https://osu.ppy.sh/users/17007603

**Comment by peppy** [comment]
This is intended behaviour. The medal is achievable in any game mode.
