### ISSUE TITLE
Missing implicit response_type grant

### ISSUE THREAD

**Issue by Itsyuka** [ppy/osu-web#7323]
The oauth is missing a very good type for a secure flow for any client side applications.

https://laravel.com/docs/6.x/passport#implicit-grant-tokens

**Comment by tybug** [comment]
[oauth.net's implicit grant article](https://oauth.net/2/grant-types/implicit/) has the following to say:

> Public clients such as native apps and JavaScript apps should now use the authorization code flow with the PKCE extension instead.

there's a few related issues for PKCE: #7004, #5879

**Comment by Itsyuka** [comment]
Disregard, because I went full stupid :). Thanks for reminding me
