### ISSUE TITLE
-1 Notifications in browser

### ISSUE THREAD

**Issue by FaKeDIs** [ppy/osu-web#7324]
It's nothing game breaking or something like that but it is definitely a bug so i just want to make it known.
it happened when i open the browser to download some maps after chatting with a friend.
(This was like 4 days ago, so I dont know if it's already fixed)

https://i.imgur.com/T6JjP1d.png
https://i.imgur.com/aLX6i6Q.png

**Comment by peppy** [comment]
@FaKeDIs was this just a once-off thing? on refreshing did it resolve itself?

**Comment by Allisonhash** [comment]
> @FaKeDIs was this just a once-off thing? on refreshing did it resolve itself?

yes, it always resolves itself. it is honestly just a bug that happens from times to times with people (i have seen it happen plenty of times on twitter) but it's nothing to worry about.

**Comment by peppy** [comment]
If this does resolve itself, we should probably just fix this at a visual level then? Make sure the display is always zero or higher.

**Comment by miyucode** [comment]
i have the same bug now :/
i reload the page but it's not working

https://imgur.com/a/VJ8x3Tf
