### ISSUE TITLE
Missing beatmap management options

### ISSUE THREAD

**Issue by TheMoMan** [ppy/osu-web#7326]
Basically this from the old site: ![image](https://user-images.githubusercontent.com/6444058/111512237-70cf6580-8747-11eb-9f7d-e40ad88174e7.png)

Moderators are still unable to edit a beatmap's online offset, title text, and tags on the new website. This could be added either to the existing metadata management panel (where genre, language, and explicit tags are set), or in a seperate panel hidden from regular users.

While we're at it it may also be worth allowing regular users to edit the title text on their own beatmaps, with similar permissions to setting genre and language tags (regular users can only edit for their own unranked maps, BNs can edit for any unranked map, moderators can edit for any map in any state).

**Comment by dorothy3242** [comment]
This was previously brought up in https://github.com/ppy/osu-web/issues/2395

We now have genre controls added, but still no way of editing online tags or offset. peppy did mention title text would be removed in the future. 

Is title text something the community wants to stay around? It'd expand to a lazer issue to add that if so. And even if it is added shouldn't that be as an in-game feature, it being web-editable only was always really weird.

peppy mentioned in the last issue moving online offset elsewhere, but I'm struggling to imagine where it could go, as making its own page wouldn't work without other things to add to it for instance.

**Comment by TheMoMan** [comment]
Wasn't aware title text was going to be deprecated, I'm probably one of very few people who actually care about it, but I guess I wouldn't miss it either.

I don't think another page is really necessary, just a button that opens up another modal/pop-up thing, or even an extension to the existing modal.

![image](https://puu.sh/Hq1mI/56501f84a5.jpg)
![image](https://puu.sh/Hq1uD/425e66babc.jpg)

**Comment by peppy** [comment]
As this is one of the *very* few admin pieces still remaining on the old site, I think we should try and get this moved over ASAP. Design and implementation doesn't need to be perfect as long as the functionality is there (a limited subset of users are able to access this in the first place).

**Comment by venix12** [comment]
I could try to implement that, who should be able to access that btw? Used to be NAT only Iirc but same was the case for genres which are now editable for both GMT and NAT.

**Comment by notbakaneko** [comment]
just use the existing `BeatmapsetMetadataEdit` permission

**Comment by venix12** [comment]
not sure if regular users should be able to change offset or online tags on their maps, though

**Comment by nanaya** [comment]
The check is slightly more involved than that. Owner can only change them when in wip/graveyard/pending (and not yet nominated).

**Comment by peppy** [comment]
hmm, on revisiting this, neither of those fields are probably needed in current times.

how often do we make use of post-rank timing or tag changes? i would like think thing never. will check in the database but it'd be handy to know if these *are actually needed*.

seems like something we'd un-rank for.

**Comment by Okorin** [comment]
unranking for that seems spicy. 

the way the setting (online offset / tags) is used is usually by moderators (NAT/GMT) to fix the offset on maps that have already been ranked, especially offset things are sometimes only brought to attention years after the fact

if it gets pointed out in qualified, the map gets disqualified for either of these.

**Comment by peppy** [comment]
Is it safe to say that tags are not ever changes, at least?

**Comment by Okorin** [comment]
In fringe cases i remember adding a username to tags who contributed to the beatmap but didn't get credited (map was ranked for months already). Also is kind-of-neat to use for people who namechanged and request their current username being added to old maps / their old username being added to newer maps (old usernames are technically not required to be present for ranking so people can leave them out)

It's just generally nice to have for searching - unless it doesn't work on the new website i haven't done this in a while... 

Those are the usecases i can think of where having that still makes sense, mostly attribution things or adding more search terms to maps that are from like 2010 and only have 1 tag or so.

**Comment by peppy** [comment]
So I think we don't need to add back tag editing (until the whole BSS system is refreshed/update) but we do need online offset in some way.

- shouldn't be editable by users (or if it is, it should be reset on qualify / ranked, if that's easier to implement)
- should be logged somewhere when changed (is that already the case for these metadata settings? i'd hope so)

**Comment by NoffyNoffeh** [comment]
> * (is that already the case for these metadata settings? i'd hope so)

yes, that is the case for the other meta settings so far.

**Comment by venix12** [comment]
> The check is slightly more involved than that. Owner can only change them when in wip/graveyard/pending (and not yet nominated).

the point is, why would regular users mess with it even if it's not nominated? seems potentially confusing for people (like having 2 different options for setting offset - bss and web, not knowing web one isn't really affecting actual in game offset and should in practice be used only for loved/ranked beatmaps in some edge cases)
