### ISSUE TITLE
Report beatmaps from beatmap page

### ISSUE THREAD

**Issue by pishifat** [ppy/osu-web#7327]
covering reports for stolen or nsfw content. this can be handled using a similar format to user or score web reports

**Comment by dorothy3242** [comment]
could also be able to report miscellaneous things for ranked maps like 

incorrect genre/language
missing gder or other important tags
needing online offset

+unset difficulty icons if https://github.com/ppy/osu-web/issues/3917 is implemented

**Comment by peppy** [comment]
Is this one we can add quite simply using the existing reporting system? If so, let's get it in.

**Comment by venix12** [comment]
i can work on this one, no idea where to put the report button though, next to favourite button perhaps?

**Comment by peppy** [comment]
Sounds fine, but please make sure to make it similar to the user profile implementation (where it's hidden behind the pop-out/dropdown menu).
