### ISSUE TITLE
Create nomination activity section on modding info page

### ISSUE THREAD

**Issue by pishifat** [ppy/osu-web#7329]
referring to this page: https://osu.ppy.sh/users/3178418/modding though maybe it's more fitting elsewhere

concise BN activity is useful for knowing things like how active and how well a user's nominations are performing. [this](https://osu.ppy.sh/beatmapsets/events?user=3178418&types%5B%5D=nominate&types%5B%5D=qualify&types%5B%5D=rank&types%5B%5D=love&types%5B%5D=nomination_reset&types%5B%5D=disqualify&min_date=&max_date=) covers most of a BN's activity, but there's no way to see when a user's nomination is reset or disqualified (which are some of the most important stats)

a nice addition would be a new subsection on the modding page for BN/NAT called "Nomination activity" including events filtered to the link above + their nomination's resets and disqualifications

**Comment by peppy** [comment]
So this would basically just be a "recent activity" but for modding, yeah? If this is something we can realise easily, it seems like we should get it in using the existing design for the recent activity of the normal profile.

**Comment by nanaya** [comment]
I don't think such data is currently recorded (whose nomination being reset/disqualified).

This will probably need a new... thing which I'm not sure what yet because one of the ways involves storing something that's multi valued and indexable for the disqualification/reset row (to list current nominators) but there's no such thing in mysql (it'd be gin-indexed array for postgres).

**Comment by peppy** [comment]
So it might be best to just record to `osu_events` (or a similar concept) as its own feed?

**Comment by nanaya** [comment]
Apparently mysql finally added support for array lookup in 8.0.17

**Comment by notbakaneko** [comment]
what kind of info are we looking for here?
- which users' nominations where reset by a disqualification?
- who reset a user's nomination?
etc

**Comment by TheMoMan** [comment]
On the [BN site](https://bn.mappersguild.com/home) we currently record unique nominations (only shows a mapset once if the user has nominated it more than once), which of those nominations were reset and for what reason, and which maps they have reset the nomination of.

![image](https://user-images.githubusercontent.com/6444058/121358963-ee5fd780-c92a-11eb-8d54-4296c196b136.png)

NAT currently use this information to evaluate the performance of a BN, and one of the key values we look at is how many of their nominations are being reset for significant reasons compared to how many they nominate. Seeing the nominated map's host is useful for checking if a BN is nominating for a large variety of people or just for a small group.

Regular users could use this to determine which BNs they could contact based on the maps they nominate.
