### ISSUE TITLE
Don't consider beatmapsets with no storyboard elements as storyboarded

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu-web#7330]
[Silentroom - NULCTRL](https://osu.ppy.sh/beatmapsets/917159#osu/2163542) for example has a .osb file, but it only contains a single video event. Videos can be defined in .osb files, but they are arguably not part of a storyboard.

When searching for storyboards I always have to check if they actually have a storyboard when they're also shown as having a video. This may be non-trivial to implement but would be good as something to eventually have.

![image](https://user-images.githubusercontent.com/36758269/111567445-4ad5af80-879f-11eb-8423-dac026076171.png)

**Comment by peppy** [comment]
What would you consider the cut-off for something being considered "storyboarded"?

**Comment by Walavouchey** [comment]
Storyboards consist of sprites and animations in the [Event] sections of the .osu files and .osb file.

In other words, any occurence of `Sprite` or `Animation` (that are not commented out) in the .osb or .osu files under the `[Event]` markers should cause the beatmapset to be considered storyboarded.

Whether the sprites are ever visible or the storyboard is malformed probably isn't of any concern and should be considered categorically as storyboarded anyway.

**Comment by Walavouchey** [comment]
Variables in the file might need to be processed as well since they may obscure the occurrence of `Sprite` or `Animation` in the file.

**Comment by peppy** [comment]
I've fixed this in legacy BSS for now, searching for `Sprite` or `Animation` keywords. It makes sense to do it there for now as I'm going to use the code there as a basis for the new version.
