### ISSUE TITLE
User profile graphs cut - half of the graph is hidden

### ISSUE THREAD

**Issue by HowWillWeRIP** [ppy/osu-web#7332]
No idea how long I have this issue, but if I first open up a user profile, the graphs are fked up and can't see them properly:
![image](https://user-images.githubusercontent.com/79837625/111622705-c8bea880-87e9-11eb-90b8-e7a179165852.png)

![image](https://user-images.githubusercontent.com/79837625/111622759-daa04b80-87e9-11eb-9568-d722449751d6.png)

Then, if I put my web browser to smaller, and then back to full size it will reset and will be good again:
![image](https://user-images.githubusercontent.com/79837625/111622950-176c4280-87ea-11eb-9888-70f33370bc92.png)

![image](https://user-images.githubusercontent.com/79837625/111622992-20f5aa80-87ea-11eb-92fb-a41011bb745f.png)

but it lasts for 5 minutes, or till I do something in the website, then it hides them again in this weird way.
I am using Google Chrome on Windows 10, asked others but noone had this issue afaik.

**Comment by nanaya** [comment]
Have you tried with extensions disabled?

**Comment by nanaya** [comment]
lack of detail after a year and I don't remember ever seeing it myself
