### ISSUE TITLE
Reset button in me! should probably have a confirmation + be coloured red

### ISSUE THREAD

**Issue by Purplegaze** [ppy/osu-web#7343]
I'm always afraid I'm going to click this instead of "Preview" whenever I'm trying to make big changes to my userpage. Considering it clears all your changes without giving you a chance to undo, I think it should visually look different and have some sort of confirmation once you press it (or be removed entirely, because just refreshing the page and opening up me! again has the same result)

![](https://cdn.discordapp.com/attachments/247078580381679627/822759042665283584/unknown.png)

**Comment by peppy** [comment]
I think just removing it is fine. If a user wants to start over, they can hit the "cancel" button.

**Comment by nanaya** [comment]
Removed.
