### ISSUE TITLE
Deleted modding posts say edited [deleted user] (Bug?)

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#7345]
It's really confusing and weird, seems like a bug

![image](https://user-images.githubusercontent.com/33286824/111876903-22a0a900-8977-11eb-88f0-f1ad64e326cc.png)
this post was by Jerry, deleted by Jerry, but says it was also edited by [deleted user] and as a moderator I have no idea what that is supposed to mean. It seems to be showing on any post deleted by the poster.

**Comment by nanaya** [comment]
Which page are you seeing this?
