### ISSUE TITLE
Images in someone's me! below the initially visible scrolled area only load when the entire webpage is scrolled

### ISSUE THREAD

**Issue by Purplegaze** [ppy/osu-web#7350]
When userpages have images in them that are low enough that you have to scroll to see them, they don't load until the scrollbar for the entire webpage is used (not the scrollbar for just the userpage)

Video showing what I mean: https://www.youtube.com/watch?v=8KT39_SzGCA

This also affects mobile in the same way.

**Comment by notbakaneko** [comment]
My guess is the current image lazy loading library being used (`layzr.js`) only works on the main document or window scrolling and not any scrollable containers.

**Comment by nanaya** [comment]
This probably has been fixed with recent change to use browser native lazy loading
