### ISSUE TITLE
Api endpoint /api/v2/rooms/:id new user info

### ISSUE THREAD

**Issue by WilczekCK** [ppy/osu-web#7357]
Hello,
I just want to post an idea, which in my humble opinion, should be inserted in that route.

What I mean, is the "Team" information while playing the 'Team VS' multiplayer.
While this mode is turned on, then information received about player, should include the information to which team he belongs.

Also, I wanted to ask, does the 'event' object received from that scope does have any documentation?
I'm not sure, if "other" means the change of beatmap only?
<img width="286" alt="obraz" src="https://user-images.githubusercontent.com/25286189/111979832-d5067680-8b05-11eb-9caa-4ba214943456.png">

Best Regards

**Comment by peppy** [comment]
Are you sure you're looking in the right place? The API endpoint you're using is the newer version of multiplayer which is only live in lazer. We haven't implemented team VS there yet, which is why this data doesn't yet exist.

**Comment by WilczekCK** [comment]
Okay, but it takes the multiplayer rooms from the stable osu! (not lazer) too, so it looks like the information is missing, even if this endpoint is made for osu!lazer or am I wrong?

**Comment by ilsubyeega** [comment]
> Okay, but it takes the multiplayer rooms from the stable osu! (not lazer) too, so it looks like the information is missing, even if this endpoint is made for osu!lazer or am I wrong?

[api/v2/matches/{match}](https://osu.ppy.sh/docs/#apiv2matchesmatch) would valid.
`https://osu.ppy.sh/community/matches/78801200`
![image](https://user-images.githubusercontent.com/37479424/112136172-fc4a6a00-8c11-11eb-907e-feefb5f864a2.png)

**Comment by WilczekCK** [comment]
> [api/v2/matches/{match}](https://osu.ppy.sh/docs/#apiv2matchesmatch) would valid.
> `https://osu.ppy.sh/community/matches/78801200`


Yes, my bad - it would be the best case to valid it.
So, the information is missing - but I noticed something, the team color for users is visible only for event 'other', when the map is finished.
<img width="312" alt="obraz" src="https://user-images.githubusercontent.com/25286189/112145758-0d2bb900-8bdb-11eb-8d5a-19d543de702a.png">

So, it's possible to assign players to team, but only when map is finished - It's okay for me, but you have to discuss, if this information should be attach for users object.

**Comment by ilsubyeega** [comment]
If you are going to say the `user` object should have a team attribute?
I think it should not happen since team could be changeable, and I think the database saves team with a score (there is a team column at osu_mp.game_scores) + (no real-time team members information at the database, not sure at this)

**Comment by WilczekCK** [comment]
It's okay how it's working now for me, I did not notice earlier the **scores.match.team** attribute which tells the team of user.
I through that 'user' object has (or should have) the real-time informations from the MP, like for example team attribute - but If it would be the only real-time attribute, then it's not worth the efford.

Feel free to close this issue, if you do not want to include that :)
