### ISSUE TITLE
New article header is not wrapper correctly on mobile layouts

### ISSUE THREAD

**Issue by FAMossu** [ppy/osu-web#7359]
![](https://cdn.discordapp.com/attachments/218677502141399041/823584616559411230/IMG_20210322_225101.jpg)

this also impacts the orientation phone display.

Phone: Redmi 9C, 720x1600 pixels

**Comment by eugenekotovx** [comment]
Hi! I think main trouble in css-property "flex: none;". Can you assignment to me this issue?

**Comment by peppy** [comment]
You're welcome to attempt a fix and submit a PR (we generally don't assign issues this small, and I don't believe we *can* even assign to users outside of the organisation).
