### ISSUE TITLE
Laravel 5.3 Migration

### ISSUE THREAD

**Issue by BossOfGames** [ppy/osu-web#736]
Hey Everyone,

I am building a Laravel 5.3 application right now and I am loving the new feature set and cleanliness that comes with the new framework and layout. Notable features include a driver based notification system (email update regarding leaderboards and friends plays), realtime event broadcasting support (get notified live when viewing the site of things going on in the game (friends playing maps)), and a built-in OAuth2 server (for the osu!api).

I was wondering if there were any plans on migrating to 5.3 in the near future. If nobody else wants to do it, I will be happy to in my spare time.

**Comment by peppy** [comment]
No one has started work on this. If you are interested in helping out, you're most welcome to give it a shot! I can get behind that with a bounty payment as well, if that's something that interests you.

**Comment by BossOfGames** [comment]
The bounty is interesting... Challenge Accepted! Just a heads up, there is a slight change in the Laravel directory structure from 5.2 to 5.3 so I don't know if that will play nice with this GitHub when you accept my pull request (routes are now in it's own folder on the project root and the app directory was cleaned up).

**Comment by peppy** [comment]
This has been completed by @nanaya in #799, with a small portion remaining (OAuth Passport migration) in #808.
