### ISSUE TITLE
Token delete request over API doesn't delete the token

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#7363]
I get a 204 from `DELETE https://osu.ppy.sh/api/v2/oauth/tokens/current` but it doesn't seem like this token is actually getting revoked. I can still see it in my account settings, ~~and I can get the same token back from `/oauth/authorize`~~ (total misunderstanding on this part, it was just that I could re-auth wiht no prompt and get a different token)

**Comment by notbakaneko** [comment]
Which client are you seeing this issue on?

**Comment by cl8n** [comment]
I think I misunderstood how this is supposed to work. I thought that "revoking a token" was the same as revoking an "authorized client" in account settings, so was confused when I deleted the former but the latter stayed. deleting token does work cuz I can't delete it twice (get 401 on second try)

in case this is still relevant, token was for user ID 3666350 on client ID 7

**Comment by peppy** [comment]
Does this need better documentation? Or was it just a lapse of understanding?

**Comment by cl8n** [comment]
my misunderstanding and the docs for deleting token are fine, I'll open a new issue about the account settings UI that confused me
