### ISSUE TITLE
Beatmap mode filter for beatmap discussions page

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#7364]
https://osu.ppy.sh/beatmapsets/discussions this page

This is the best way to view all open issues on qualified maps, but currently lacks any mode indicators or filters. This page would be much more useful with such filters present and better enable BN oversight on current qualified issues outside of report notifications.

There should be a way to filter by the posted on beatmap's mode.

**Comment by peppy** [comment]
Should be a pretty easy one to add. Out of curiosity, is this page accessible from somewhere? Or is it a hidden page that was originally intended for moderation?

**Comment by NoffyNoffeh** [comment]
Dunno how to access it besides the direct link, don't think it was meant as a hidden one for moderation either though. Feels more like it was forgotten about before it could be fully visible/implemented?

I think having qualified somehow link to here would be helpful to make issues on the maps more visible. Some people prefer overviews over individual notifications.

**Comment by nanaya** [comment]
Set doesn't have "mode" so this filter won't show "general (all difficulties)" discussions.

**Comment by peppy** [comment]
That's a bit of a weird one. If it was to be used for the aforementioned cases (where nominators wanted to filter down to the modes they care about) you'd hope for it to also include all general (all) discussions. But definitely doesn't make sense in terms of the filter.

Maybe this can be implemented as five checkboxes, the last being "general issues"?

```
[ ] osu!  [ ] osu!taiko [ ] osu!catch [ ] osu!mania [ ] general issues
```

**Comment by nanaya** [comment]
Well it's kind of possible to filter discussion for either "beatmap of specific mode" or "all difficulties which beatmapset contain beatmap of specific mode".

The query will be a bit long though :eyes:
