### ISSUE TITLE
Add API method to revoke an authorization code and all tokens obtained from it

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#7365]
an equivalent of the "revoke access" button here

![image](https://user-images.githubusercontent.com/9954349/112272966-0718f500-8c3a-11eb-8747-39c325a054d6.png)

is what I'm looking for, because I want to implement a log-out button on a website. currently, best I can do is revoke the token it keeps (this is what I confused for authcode in #7363), but for all the user knows I could just use the same authorization code they gave me the first time and get another token. they haven't truly "logged out" until they go to their account settings and revoke my client themselves

**Comment by peppy** [comment]
The issue I can see with this is that the user can't be sure that you've actually revoked access when you say you have. Is there precedent for this kind of flow on other APIs? Personally I've never used a third party service where that service itself offers the ability to revoke privileges from the OAuth source..

**Comment by notbakaneko** [comment]
This makes no sense to me; with authcode grants, the user is granting permissions to a 3rd party via a token - there's no way the user can verify the claims of the 3rd party that the permissions granted have been revoked without checking on the authorization server itself.

**Comment by cl8n** [comment]
I see. I probably should have done some review of how security practices work via oauth before posting these issues, sorry for the noise
