### ISSUE TITLE
Bancho chat filters do not apply to messages sent via osu-web chat/lazer

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#7375]
Bancho-level filters (used extensively for basic chat moderation) currently do not apply to chat sent via osu-web. Similarly, the same applies to chat sent via osu!lazer, likely because they share the same frontend (?).

**Comment by peppy** [comment]
We should probably give this some priority. Should be a relatively simple implementation with a database table and string replacement at point of ingesting messages.
