### ISSUE TITLE
artist_unicode and title_unicode are null on old beatmaps

### ISSUE THREAD

**Issue by acrylic-style** [ppy/osu-web#7380]
I did `JSON.parse(document.getElementById('json-beatmapset').textContent)` in browser's developer console, and I just noticed that the artist_unicode and title_unicode are null, while other (newer) beatmaps has the value (usually same value as non-unicode property)
Beatmap URL: https://osu.ppy.sh/beatmapsets/34348#osu/111680
I think it's just because it's an old map (submitted in 2011), but I think it shouldn't be null and should show the same value as a non-Unicode one instead (just like any other maps).

For reference: https://osu.ppy.sh/beatmapsets/1348446#osu/2792231
This map has non-null artist_unicode and title_unicode.

**Comment by peppy** [comment]
Not sure. I guess non-null may make more sense? Right now it matches what is in the `.osu` file, so I'm hesitant to change it but if that's the preferred result we can consider it.

**Comment by acrylic-style** [comment]
Ah, I see. I think a non-null value makes more sense than just a null value because third-party applications may use the Unicode value without fallback with non-Unicode title/artist because most maps have non-null Unicode title/artist.
Third-party application developers are (usually) not aware that the artist_unicode, title_unicode are actually nullable unless they see the null value directly by viewing the old beatmap page.

**Comment by peppy** [comment]
I guess the question is do we make this change at the database or just at an API level. Latter may be the better choice.

**Comment by acrylic-style** [comment]
Yeah, I think it's better to do it at an API level if possible.
