### ISSUE TITLE
searching docs freezes in beginning of search

### ISSUE THREAD

**Issue by tybug** [ppy/osu-web#7382]
https://user-images.githubusercontent.com/31628143/112732543-f950c180-8f10-11eb-8b9a-1a13d5a602cd.mov

macOS 10.5.16
Chrome Version 89.0.4389.90 (Official Build) (x86_64)

the docs look like they're generated by a third party library? If so and if this is an issue on their side and not osu!'s, let me know where to follow up with them instead.

**Comment by notbakaneko** [comment]
I guess this is why just about everyone disables search in slate 🤔

**Comment by notbakaneko** [comment]
After a bit more investigating, this appears to be a problem with Lunr.js; Documentarian uses a very old version of Lunr, so this may or may not have been fixed in in the current version of Lunr, which may not work with Documentarian, which hasn't seen any notable updates in a long time.

**Comment by tybug** [comment]
seems to be fixed now
