### ISSUE TITLE
[Mobile] Special characters aren't properly escaped in author name on beatmap listing on user profile Most Played Beatmaps

### ISSUE THREAD

**Issue by Susko3** [ppy/osu-web#7384]
This escape bug is only present on Most Played Beatmaps category, all other categories display the artist name fine.

Happens on both Chrome and Firefox. If I switch to the Desktop site (via three dot menu in browser), the artist name is displayed normally 

Example:

On [my user profile](https://osu.ppy.sh/users/18945305), it is written as `by CircusP &amp; Eyeris`

Further down, there is also `by u&#39;s`

![Screenshot_2021-03-28-12-06-23-41_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/16479013/112748851-e0064e80-8fbe-11eb-85c6-7ec822b068da.jpg)

**Comment by peppy** [comment]
Can reproduce.

**Comment by bdach** [comment]
Seems as if there's a bit of an inconsistency in how the artist name is treated on different layouts:

https://github.com/ppy/osu-web/blob/465f8cc3276458aca4dfb5447efbb3b0d6a021d1/resources/assets/coffee/react/profile-page/beatmap-playcount.coffee#L39-L41

https://github.com/ppy/osu-web/blob/465f8cc3276458aca4dfb5447efbb3b0d6a021d1/resources/assets/coffee/react/profile-page/beatmap-playcount.coffee#L44-L52

Note the escape in the latter case. No idea where that came from, though.
