### ISSUE TITLE
Soundcloud embeds on forums

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#7385]
Youtube has `[youtube]...[/youtube]` bbcode tags, so soundcloud would be `[soundcloud]...[/soundcloud]`.  Unlike youtube, I dont think soundcloud has ids so I'm thinking full link would be used instead.

**Comment by peppy** [comment]
What's the use case for this? Soundcloud as a service is pretty shoddy (64-96kbit) so I'd recommend using youtube for all intents and purposes.

**Comment by abraker95** [comment]
Two benefits from this
- It makes sharing music on forums more convenient
- It saves data on mobile

This is definitely not for pointing mappers toward the track they should use for their maps, or anything to do with mapping for that matter. Quality might be shoddy, but the point is not to have an experience listening to music, rather have a convenient way share music through forum content. Think like "share music you like" kind of threads. People can then find better quality source if they do happen to like it. Usually you can find the same music on youtube, but sometimes not. A huge plus tho is that it can save a lot of data on mobile compared to youtube video.

**Comment by peppy** [comment]
I'd rather not support the soundcloud service as I think it's crap, sorry.
