### ISSUE TITLE
User avatar URL is returned as relative path for guests

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#7390]
In API responses, the avatar URL is usually returned as an absolute url:

`https://a.ppy.sh/9958822?1615128896.jpeg`

But for guests (I guess whenever a user doesn't have an avatar set), it's returned as a relative URL:

`/images/layout/avatar-guest.png`

This is a bit confusing, so I'd propose we change this to also/always be a full absolute URI.

As pointed out in https://github.com/ppy/osu/pull/12204#discussion_r602893245.

**Comment by ilsubyeega** [comment]
https://github.com/ppy/osu-web/blob/master/app/Traits/UserAvatar.php#L28
would fix this line with 
```
return config('osu.urls.base').config('osu.avatar.default');
``` (combining base URL and default avatars URL)
