### ISSUE TITLE
Show changes in rank on leaderboards

### ISSUE THREAD

**Issue by Vaf167** [ppy/osu-web#7391]
Hi there. The Issue I'll be proposing is one I've been thinking of lately. Across the gamemodes, leaderboards are constantly changing. In some, they have a certain country dominating in the rankings like japan in taiko for example or standard where the top 100 is having new players every week. As a solution not only for leaderboards but for profiles I suggest the following:
Implement an arrow system. Something like FIFA's performance arrows. This arrows would be used both in profiles and leaderboards to reflect a player's growth in the past 7 days globally. When entering to their profile it would also show their growth countrywise. This would help not only tournament players to get more info faster but also players who just like looking at new players in the leaderboards making it a lot easier to grasp information. I made 2 examples out of taiko with wikipedia's arrows. These can be changed. I had 3 type of arrows:
Neutral
Positive
Negative
Neutral can have a +0 or just nothing that's up to whoever decides to implement this feature. 
Last but not least, It would probably look better if the arrows were placed next to the rank in the same column to make it more aesthetic. However, a small place should be added to fit it.
![GITHUB TEMPLATE PROFILE](https://user-images.githubusercontent.com/46717907/112837675-8d866a00-9072-11eb-83a5-98634ae8eef9.png)
![GITHUB TEMPLATE](https://user-images.githubusercontent.com/46717907/112837725-9bd48600-9072-11eb-9c5d-0e3071738150.png)

**Comment by vexhy** [comment]
oh wow yea, i do really think this is a great idea especially in top leaderboards!

and yes i agree that if you positioned the arrows next to the actual rank the player has (in the leaderboard, the profile looks cool c:) would make it more intuitive and nicer!

**Comment by peppy** [comment]
This actually used to be a thing but was removed for some reason (would need to dig to find out why, but either due to performance concerns or people not caring enough for it).

**Comment by Vaf167** [comment]
> This actually used to be a thing but was removed for some reason (would need to dig to find out why, but either due to performance concerns or people not caring enough for it).

I knew it was a thing in the past but don't really know why it got removed. I think it would be really useful if it doesn't bring any problems to the performance of the web

**Comment by trollocat** [comment]
This would be amazing to have again, maybe could be implemented to the top 50 only or top 100 if it causes too much performance issues

**Comment by cl8n** [comment]
tried this one, I can't decide on how long ago the rank should be compared to though. 7 days sounds fine to me, but worth noting it makes the top of the leaderboards look pretty stagnant because it takes so much time to pass other players at that level. I don't know if it's important.

<details><summary>7 days vs. 28 days</summary>

![image](https://github.com/ppy/osu-web/assets/9954349/c2e2b170-f038-4a9b-acb5-c3b4e32f7a4a) ![image](https://github.com/ppy/osu-web/assets/9954349/8c6f2d48-d8c6-4604-9de3-f9b19a83ed5e)

</details>

also, country rank changes and variant rank (i.e. 4k & 7k) changes aren't currently tracked and so that would be a lot more effort to get working than just global

**Comment by cl8n** [comment]
I'll finish and PR this one after few other things I'm following up on, hopefully this week or next. it's only going to be for global leaderboard changes as explained above

**Comment by peppy** [comment]
I think 28 days would be fine.
