### ISSUE TITLE
Allow restricted accounts to upvote/downvote comments

### ISSUE THREAD

**Issue by Allisonhash** [ppy/osu-web#7394]
As of right now, there is a message "Can't do that while restricted." when trying to upvote comments. It seems fair, but I was wondering that if restricted accounts are allowed to favourite beatmaps and a few other actions, and the fact that upvotes are anonymous, could banned users maybe also be able to upvote comments? 

Or they could at least remove upvotes from already upvoted comments, which is also not possible to do once restricted.

**Comment by peppy** [comment]
Out of scope sorry. Restrictions limit all publicly visible write actions and that isn't going to change any time soon.
