### ISSUE TITLE
Notify users with non-friend dms blocked when messaging a BN

### ISSUE THREAD

**Issue by MzudemO** [ppy/osu-web#7395]
Surely someone has made an issue for this before but I couldn't find anything so here goes. Apologies if I missed something.

Nomination requests over the osu chat are quite common. Users will message BNs and usually expect a reply (deny or acceptance). Especially in the acceptance case they really want to be able to read the answer.

Current Behavior:
User A is blocking dms from non friends
User A messages User B asking for a nomination (or advice, or whatever)
User B receives the message and wants to accept their request but cannot reply because they aren't friended
User A has no way of knowing there was a reply

Proposal: 
Notify users when messaging someone that can't message them back, similar to the message you get right now when replying to someone that you can't message.
Either only for certain user groups (BN, NAT, GMT...) but I think it could make sense for all users.
![chrome_ReDChb9KK4](https://user-images.githubusercontent.com/23505804/113051524-59ac6100-91a6-11eb-9ba7-26be621067be.png)

"You have messaged this user, but they can't reply to you. You might be blocking private messages from users not on your friends list."

**Comment by peppy** [comment]
I think the best way forward is to disallow messaging people that can't reply to you. It doesn't make sense as it stands.

**Comment by Hiviexd** [comment]
any chance this could be bumped up in priority? almost a year later and BNs/other people are still being bothered by this

**Comment by peppy** [comment]
@notbakaneko can you take a look at this one? disabling sending messages to someone when they can't reply to you due to your settings (with a tooltip/hover message or otherwise explaining how to resolve the issue).

**Comment by notbakaneko** [comment]
yeah, I was going to look into this, already
