### ISSUE TITLE
Add cors headers to API endpoints to allow client-side fetch requests

### ISSUE THREAD

**Issue by VanWeapon** [ppy/osu-web#7400]
The osu V2 API doesn't have CORS headers in the response which means client-side apps cannot make calls to the endpoints for fetching data. 
E.g, the following code doesn't run in a browser
```javascript
function getUser(userID) {
    return fetch(`https://osu.ppy.sh/api/v2/users/${userID}/osu`)
    .then(response => response.json())
    .then(data => data)
    .catch(err => console.error(err));

}
getUser(4504101).then(data => console.log(data));
```
Expect to get the user data for WhiteCat, but instead get an error:
```
Access to fetch at 'https://osu.ppy.sh/api/v2/users/4504101/osu' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

When testing with a dummy API like numbersapi, the response works as expected:
```javascript
function getNumberTrivia(number) {
    return fetch(`http://numbersapi.com/${number}/trivia `)
    .then(response => response.text())
    .then(data => data)
    .catch(err => console.error(err));

}
getNumberTrivia(17).then(data => console.log(data));
```
Outputs:
`17 is the maximum number of strokes of a Chinese radical.`

Use case: A web application using a framework such as React does not need to have an active server to run, it can be served as a static site. This means that all logic is run from JavaScript code executing within the browser enviroment, and thus is subject to the anti-client side CORS rules that are default on web servers. 

If the lack of CORS is intentional, all good, but I couldn't find an answer one way or another hence posting this issue.

**Comment by bdach** [comment]
Enabling CORS is not something that is done willy-nilly. It is a serious security consideration.

I believe the official stance is that you should create a proxying server component, with appropriate response caching.

**Comment by peppy** [comment]
How would this even work? We don't have a public client API.

**Comment by VanWeapon** [comment]
> Enabling CORS is not something that is done willy-nilly. It is a serious security consideration.
> 
> I believe the official stance is that you should create a proxying server component, with appropriate response caching.

I figured as much, thanks for the response
