### ISSUE TITLE
Can't view general tab on map

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#7409]
Before I disqualified the map, everything was working fine.

https://osu.ppy.sh/beatmapsets/1390855/discussion/-/generalAll#/2252461

Soon after I disqualified it for a minor issue, the general tab became inaccessible unless a filter is applied. This made it impossible to view and resolve issues. The general tab only became accessible again once I deleted the linked post via the poster's profile. 

It's still impossible for moderators to view the general tab if they have the "show deleted discussions" check box enabled.

This post was up for days without causing issues, so we are not sure what triggered the page-breaking behavior.

**Comment by nanaya** [comment]
What does the console say? (press F12 on page with error and switch to console tab)

**Comment by NoffyNoffeh** [comment]
![image](https://user-images.githubusercontent.com/33286824/113440604-c13afa00-93ba-11eb-8c13-93dd530aac85.png)

**Comment by NoffyNoffeh** [comment]
Reports say it works on mobile devices, but not desktop. I was also able to view the post on their profile page without issue prior to deleting it.

**Comment by nanaya** [comment]
Weird if it's something recent because it looks like the error come from change quite a while back.

**Comment by nanaya** [comment]
Oh it's a new reply which caused the error.

**Comment by NoffyNoffeh** [comment]
Oh I see. I had no way of seeing that since I only knew "all users posts can show besides yudragens" and the profile history doesn't show a post's replies. Reports told me it happened around when the map was updated after being disqualified.

Will the bug be fixed, or is there a way to know what reply to delete.
