### ISSUE TITLE
Show who deleted the comment for moderators

### ISSUE THREAD

**Issue by venix12** [ppy/osu-web#7412]
Unlike beatmap discussions, at the moment, moderators can't see who deleted the comment, think it would be helpful to display it, it's already stored in the database (``deleted_by_id`` on ``comments``) and is likely a quick thing to code.

**Comment by peppy** [comment]
Just to confirm, you're wanting to know if the user or another moderator was responsible for deleting the comment?

**Comment by venix12** [comment]
that's the use case i believe, yes
