### ISSUE TITLE
Prompt user whether they really want to navigate away from page if they are editing forum BBcode

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#7415]
I was editing a lengthy post, making formatting all pretty. I accidently clicked on this and now all changes are lost. 

![](https://i.imgur.com/XWW6RTJ.png)

In fact it happens for any link you press. There should be a confirmation prompting the user if they really want to navigate away from page.

**Comment by peppy** [comment]
This seems like a pretty critical one.
