### ISSUE TITLE
Include a notice about abuse@ppy.sh in user profile report

### ISSUE THREAD

**Issue by venix12** [ppy/osu-web#7416]
I believe it would make sense to put some link to report abuse article there as sometimes it feels like people would sometimes use a regular report instead of mailing abuse@ppy.sh (not aware of its existance).

**Comment by peppy** [comment]
Honestly not sure we need even more throughout on the abuse email. The idea of abuse is to give people a means of reporting when they aren't willing to use standard channels. If they are already placing a report via profile report buttons that's already enough, IMHO.

**Comment by Ephemeralis** [comment]
Agree with peppy on this one. Abuse email throughput should be reserved for issues of the highest priority, not a general-response email for misbehavior. If we did do something like this, it should point towards support@ppy.sh and allow the people handling that to forward cases of concern on for the abuse executive to handle.
