### ISSUE TITLE
Assistance in Ukrainian localization

### ISSUE THREAD

**Issue by PichuGames** [ppy/osu-web#7432]
Hello, peppy. I'm an osu!player like Pichu Games. I'm an ordinary guy from Ukraine, who wants to help a game with Ukrainian localization. Even if you do not approve my request, I will not be upset. If anything, I offer help with Ukrainian localization.

**Comment by notbakaneko** [comment]
localization for osu-web are done via Crowdin https://crowdin.com/project/osu-web/uk

**Comment by PichuGames** [comment]
Thanks

**Comment by PichuGames** [comment]
I want to make an amendment. I wanted to help with the Ukrainian localization not on the site but in the osmium game

**Comment by peppy** [comment]
The game is feature and localisation locked. Please wait for lazer, where the localisation will also happen on the crowdin project.
