### ISSUE TITLE
On the download page, link to Lutris

### ISSUE THREAD

**Issue by cainy-a** [ppy/osu-web#7435]
On Linux, by far the best way to get osu! (stable not lazer) running is through Lutris, a games launcher and installer.

It may help Linux users wanting to play osu! to link to https://lutris.net/games/osu/ similar to how there is a link to osu!wine on MacOS.

**Comment by peppy** [comment]
We'll be updating that page to linux to lazer soon, so this is unnecessary!

**Comment by cainy-a** [comment]
Ah ok
