### ISSUE TITLE
Old Chat messages not loading properly

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#7446]
If you open a chat again that you previously have closed it will look as if it doesnt load any messages and just display a blank area. If you refresh the page the messages appear.

**Comment by notbakaneko** [comment]
How are you reopening the chat?

**Comment by RockRoller01** [comment]
via https://osu.ppy.sh/home/messages/users/user-id

I just made sure that it doesnt just affect chats that havent been loaded in some time. Closed a chat and reopened it again and it happened
