### ISSUE TITLE
Allow repositioning of thumbnail in the new beatmap cards

### ISSUE THREAD

**Issue by Nivalyx** [ppy/osu-web#7449]
saw this tweet earlier which is kind of gaining traction as i wrote this issue post : http://twitter.com/iljaaz/status/1380512392099024901

in short some of the thumbnails that are being auto-generated by the new beatmap cards aren't highlighting the background properly. in some cases they would end up in a super awkward crop of the bg image as follows :

![image](https://user-images.githubusercontent.com/36564236/114188687-95e47c00-9973-11eb-818d-060423b2d454.png)

![image](https://user-images.githubusercontent.com/36564236/114192901-350b7280-9978-11eb-85c3-4aadf8341d72.png)

![image](https://user-images.githubusercontent.com/36564236/114188479-646bb080-9973-11eb-88fc-c432ad1fee93.png)

---

edit : i've just been told that apparently some of the cuts can end up being *very* visually explicit indeed http://twitter.com/Ryuusei_Aika/status/1380517124230184963 D:

**Comment by LeNitrous** [comment]
similar to https://github.com/ppy/osu-web/issues/1709

**Comment by Nivalyx** [comment]
@LeNitrous don't think it's the same issue tho since this issue concerns about the new Beamapset Card system that was just being launched literally on the [Beatmap Listing](http://osu.ppy.sh/beatmapsets) page around ten minutes ago or so (https://github.com/ppy/osu-web/pull/7422)

while that https://github.com/ppy/osu-web/issues/1709 that you mentioned is more about repositioning the thumbnail on the individual beatmapset page (https://osu.ppy.sh/beatmapsets/xxxxx)

**Comment by peppy** [comment]
We've made some improvements to the cover display which should alleviate the majority of concerns. Will continue to track the repositioning of header crop in https://github.com/ppy/osu-web/issues/1709.
