### ISSUE TITLE
New beatmap cards go off layout on user profile

### ISSUE THREAD

**Issue by venix12** [ppy/osu-web#7450]
![](https://i.imgur.com/CROEboH.png)

**Comment by eenpersoon64** [comment]
somewhat related: big hybrid sets go off bound to the right
![image](https://user-images.githubusercontent.com/37511342/114191481-bfd67800-994c-11eb-8482-af373abc2be5.png)

**Comment by NoffyNoffeh** [comment]
Please open a separate issue for that

**Comment by revelsix** [comment]
I think the examples from [this thread](https://twitter.com/Francis_Edits/status/1380515568130924544) show this bug off the best 
![image](https://user-images.githubusercontent.com/45189851/114195388-6bb49f00-991e-11eb-85ae-227f4fac7a60.png)
