### ISSUE TITLE
Add date format options on new beatmap cards

### ISSUE THREAD

**Issue by Rekunan** [ppy/osu-web#7453]
Maybe not full customization but at least have an option to switch between `DD/MM/YYYY` and `MM/DD/YYYY`

![image](https://user-images.githubusercontent.com/24501632/114189969-68b2b200-9910-11eb-8cbe-2ef42bc2e103.png)

**Comment by Purplegaze** [comment]
would greatly appreciate YYYY-MM-DD option as well for us ISO-8601 enjoyers

**Comment by NoffyNoffeh** [comment]
I think just writing it out like it is everywhere else on the site to avoid mm/dd and dd/mm shenanigans would be more effective

**Comment by peppy** [comment]
It should follow existing standards. Not sure how this was overlooked, or what the weird checkmark is next to it.

**Comment by nanaya** [comment]
It already follows the corresponding standard (as can clearly be seen in japanese/korean/chinese locale).

**Comment by NoffyNoffeh** [comment]
The current website standard is that everywhere with dates write out the month instead of using the number
![image](https://user-images.githubusercontent.com/33286824/114197873-c7802780-9920-11eb-9989-651aebc66694.png)
![image](https://user-images.githubusercontent.com/33286824/114197909-d23abc80-9920-11eb-9b50-0c436f0acc58.png)
![image](https://user-images.githubusercontent.com/33286824/114198033-e383c900-9920-11eb-8518-5b9716f7bb18.png)

**Comment by peppy** [comment]
@nanaya is this an issue with the user having incorrect region set in that case? or is the formatting limited to one-per-language and therefore DD/MM is the same everywhere?

**Comment by nanaya** [comment]
The formatting is one per language. For English, date and time format follows British English.

It's shown as number just so it can be slightly shorter.

**Comment by peppy** [comment]
An unfortunate huge oversight as the majority audience are americans that read dates incorrectly. Probably best to expand to the larger format for now.

**Comment by nanaya** [comment]
There supposed to be a tooltip for full date but apparently I forgot a rather important css for it.

**Comment by peppy** [comment]
A tooltip doesn't fix 50%+ of the audience saying "the dates look wrong".

**Comment by NoffyNoffeh** [comment]
Fix looks to be very clear and works well, this can probably be closed.
