### ISSUE TITLE
Seperate crop for left thumbnail on Beatmap Cards

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#7456]
I think this would be a better way if selectable crops isn't on the cards (literally) right now

right now the left thumbnails are a crop of a crop, meaning it ends up being a very small portion of the background, and in most cases it's hard to tell what you're looking at.

Instead, it should be its own crop from the whole background 

I'll use this map as an example:
https://osu.ppy.sh/beatmapsets/955671

![image](https://user-images.githubusercontent.com/33286824/114193383-753d0780-991c-11eb-9fbc-bd092f245334.png)

**Comment by Ephemeralis** [comment]
To cite another (very) prominent example:

![](https://puu.sh/HwMov/30a96348bd.png)

Some degree of adjustment to the algorithm is going to be necessary here, be it as the OP suggests or via other means. Without manual cropping options afforded to mappers, there's no other realistic outcome that doesn't involve either kicking the can down the road with algorithm updates or reworking our content review procedures to prevent these kinds of situations, the latter being something that patently _nobody_ wants to go through on any side.

**Comment by nanaya** [comment]
Also remember that having two different crops means twice the images to be downloaded.

**Comment by peppy** [comment]
I brought this up during the design process as something that looked stupid. Not sure why we are showing the same image twice next to each other. @arflyte is there some design logic behind it?

**Comment by Ephemeralis** [comment]
Is it not possible to supply some sort of horizontal offset that determines what part of the card image is displayed which the mapper or the NAT can set via beatmapset admin panel? That should allow the crop to be fixed without generating a second card.

**Comment by peppy** [comment]
@Ephemeralis there's another issue for that but no. that's not how anything works and not how it would be implemented.

**Comment by peppy** [comment]
Locking as this doesn't need outside input without a response from @arflyte. It can easily be fixed by changing the displayed region or redesigning the card to not duplicate the same display, but does not need discussion at this point.

**Comment by peppy** [comment]
Mostly resolved via #7469. Opened #7470 to track the remaining task.
