### ISSUE TITLE
Expand abbreviated numbers on cards on desktop

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#7458]
The current ones can be confusing as a play icon and "4m" text can be misread as "this beatmap plays for four minutes"

![image](https://user-images.githubusercontent.com/33286824/114196151-1cbb3980-991f-11eb-9bb8-075d6558aff3.png)

Instead we could fully write out the numbers for playcount and favorites, like this:

![image](https://user-images.githubusercontent.com/33286824/114196473-6572f280-991f-11eb-8126-dd9b9acdc1b6.png)

There is more than enough space present to do so comfortably, even for maps with 10m+ plays

Here's some examples with ridiculously large placeholder numbers to show that it still works even if maps achieve such huge numbers in the future, courtesy of vinxis:
![image](https://user-images.githubusercontent.com/33286824/114196820-b84caa00-991f-11eb-88c3-36741f56ba25.png)
![image](https://user-images.githubusercontent.com/33286824/114197080-ffd33600-991f-11eb-9306-866cc5940d09.png)

Mobile layout can stay the same as it is now for space efficiency

**Comment by peppy** [comment]
The card sizes are dynamic. You are testing with the largest size in the above screenshots. Please remove the screenshots or test properly.

**Comment by NoffyNoffeh** [comment]
vinxis will post with the smaller versions in a bit

it's not as jank on mobile because the numbers are already displayed to begin with, so you only need to hover once to see the full thing instead of hover inside of a hover

**Comment by peppy** [comment]
Edited opening post to remove unrelated issues.

**Comment by VINXIS** [comment]
![image](https://cdn.discordapp.com/attachments/821508004682924082/830100497733779466/unknown.png)

Smallest res with 2 columns for beatmaps (900 width)

favs can stay shortened but play icon and date being expanded seem like it can be doable though the 2015 does cross over with 100,000,000

**Comment by nanaya** [comment]
The smallest res is the one in user profile page, btw.

**Comment by NoffyNoffeh** [comment]
Dang. Didn't realize before that the search listing and profiles use different margins (why???)

Well in that case if there's no way to make full full numbers fit, some decimal places as described in https://github.com/ppy/osu-web/issues/7460 would help clarify it too. Like 1 decimal place shown.

The minutes / millions thing would also be less confusing with seeing stuff like 1.2m or 1.5m since that's more clearly different from the likes of 1:15 or 1:30

**Comment by nanaya** [comment]
> Dang. Didn't realize before that the search listing and profiles use different margins (why???)

The one in profile page is the site-wide default margin (which I've made uniform recently mainly for profile page so it's slightly wider than before in #7313). The beatmap listing one is the exception.
