### ISSUE TITLE
Pending color on the new beatmaps card feels somehow bland

### ISSUE THREAD

**Issue by venix12** [ppy/osu-web#7463]
![](https://i.imgur.com/n2ewq2X.png)
![](https://i.imgur.com/tOkoOfy.png)

for comparison - wip and ranked and loved feel much more colorful, feel like making this yellow more alive would look nicer

**Comment by Hiviexd** [comment]
bright yellow is already used by qualified tho, making pending color brighter would make it and qualified even more similar than what we currently have.

![image](https://user-images.githubusercontent.com/62819481/114277977-79a11780-9a25-11eb-841e-24809d6a689f.png)
]

**Comment by venix12** [comment]
didn't really notice that, maybe it would make sense to use completely different colour for qualified and pending then (since they are kinda close to being identical)
