### ISSUE TITLE
Solo score submission endpoint returns different mod setting types

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-web#7477]
Endpoint: `PUT /api/v2/beatmaps/{beatmap_id}/solo/scores/{score_id}`

## 1. Without mod settings
Request:
```
{
    "mods": [
        {
            "acronym": "DT",
            "settings": {}
        }
    ]
}
```
Response:
```
{
    "mods": [
        {
            "acronym": "DT",
            "settings": []
        }
    ]
}
```

## 2. With mod settings
Request:
```
{
    "mods": [
        {
            "acronym": "DT",
            "settings": {
                "speed_change": 1.6
            }
        }
    ]
}
```
Response:
```
{
    "mods": [
        {
            "acronym": "DT",
            "settings": {
                "speed_change": 1.6
            }
        }
    ]
}
```

Note the response is a `[]` type in case (1), but a `{}` type in case (2). This is causing deserialisation failures in the client.

**Comment by peppy** [comment]
Is this specifc to the `solo` submission endpoint, or does it also apply to `multiplayer`?

**Comment by smoogipoo** [comment]
It looks to be just `solo`. `multiplayer` is fine.
