### ISSUE TITLE
Modding reviews are unusably bugged in cases of using timestamps on general tab

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#7481]
Reported by numerous people. This is feature breaking and many people are quitting using reviews because they simply can't use reviews with this bug.

In some cases, trying to post a review will render an error, then the review tab will become inaccessible. The review tab will only be viewable for that user again if they log out, and their review will not post.

This is triggered by using timestamps on the general tab for problem or suggestion stamps. There are many reasons timestamps would be used on the general tab such as
- In error when drafting the review and forgetting to set a difficulty
- Pointing out issues that apply to all difficulties at that time
- Storyboard mods
- timing issues 
- etc

I've made a video recreating the issue which can be seen here:
https://www.youtube.com/watch?v=UW_VlWA3zBM

I used https://osu.ppy.sh/beatmapsets/1419424/discussion/-/reviews this map as my test subject (since it's mine)

**Comment by peppy** [comment]
For reference, how long has this been an issue / reported before it was reported here?

If it's long enough that people are "stopping using the feature" then there is something seriously wrong with how things are happening, so please look to solve that.

**Comment by NoffyNoffeh** [comment]
When I looked into it, earliest I saw it mentioned was earlier this week, but it's unclear how long it's been a thing since it would appear random on their end without clear cause. I couldn't find earlier discussion about it, but I don't see any recent changes that would make this a newer bug either.

As for it turning people away, I think that would be a pretty immediate thing since it resulted in literally sending mods that took who knows how long into some nether.

I saw someone mention there was a similar issue for it already that went nowhere but I couldn't find anything like that, but it may have dissuaded others from posting themselves when it previously came up this week.

**Comment by peppy** [comment]
So this is just one user with one report? You said "many people" in your original post. Is that just the "bandwagon" or "cancel" stuff people do these days?

Also, you said "go into the nether" but in your video (and when I attempt to reproduce) nothing is lost. There is an error message and the user can then choose to copy the content out or wait until the issue is resolved.

**Comment by NoffyNoffeh** [comment]
No, someone initially brought it up, which led to multiple other people posting about the same issue with evidence backing that up later too when seeing it wasn't just an issue on there end.

The impression was that the mod was lost, because at the end of the video it goes to the blank page where they can't see anything on the review tab, and the review was not posted. It wouldn't be clear to them the issue would be resolved soon or if it was, if their draft would still be there.

**Comment by peppy** [comment]
Okay. In the future please reconsider how you phrase issues, not including unnecessary details like "users quitting" etc. when it's something that has only just come up. If users are going to quit over something like that in 5 minutes without reporting the issue further they can do so.

We don't need that as part of reports on github, *unless* this is actually something that has been happening and affecting users over a period of time.
