### ISSUE TITLE
Search by loved date

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#7483]
With https://github.com/ppy/osu-web/pull/7358/ we got the functionality to search for maps based off when they were created or ranked. 

But at the moment, this functionality is missing for the loved category, and trying to use a `ranked` search on it doesn't work either. Would be good and make more sense that this category has the same date search features as the other ones do, as people looking at them would often expect the same search features present.

**Comment by peppy** [comment]
`ranked` should work (at least from a database perspective).

**Comment by NoffyNoffeh** [comment]
Unfortunately it currently does not 
![image](https://user-images.githubusercontent.com/33286824/114643208-39e76380-9ca3-11eb-9136-b59653e7e24d.png)


If the feature is added I think both loved or ranked should work for syntax just so the user doesn't need to think too hard about it.
