### ISSUE TITLE
Beatmap cards' hover data barely visible for certain languages

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#7491]
Can be tested with [this map](https://osu.ppy.sh/beatmapsets?q=1165141) on Polish localisation

![image](https://user-images.githubusercontent.com/19843905/114916257-e43ac480-9e24-11eb-9cc1-0f395f252077.png)

Because of a long beatmap title, the explicit mark is wrapped to the next line, causing the beatmap data shown on hover to be barely visible

**Comment by notbakaneko** [comment]
Text for badges really should not be that long.
