### ISSUE TITLE
Always show play & favourites count on beatmap cards

### ISSUE THREAD

**Issue by rjoken** [ppy/osu-web#7511]
![Example gif showing issue](https://i.imgur.com/bVEUBQE.gif)

I don't see why this information is only visible on hover with the new beatmap card design. Before this change I would often use this info when looking at a large amount of pending/graved beatmaps in the search to see which maps had more favourites, in order to weed out maps that were more likely of a lower quality. Now, I have to manually move my cursor over every beatmap card in order to do this.

The space where this information appears is otherwise blank, so I don't see the issue with making this always display.

**Comment by peppy** [comment]
It's hidden to give breathing room. A larger version of the card is already planned which always shows this information, but I have no idea how close that is to being a thing. @arflyte is it worth just showing this in the mean time?

**Comment by arflyte** [comment]
I have a feeling that people are going to rage if we remove it at a later time. I believe it's best to wait for the larger card; the design's done.
