### ISSUE TITLE
Client credentials grant API endpoint returns HTTP 404 for GET requests.

### ISSUE THREAD

**Issue by Master-chan** [ppy/osu-web#7516]
It should probably return 405 Method Not Allowed instead to clarify mistake on user's end.

**Comment by peppy** [comment]
Not sure if this is a simple one to implement (seems like something that laravel itself may need to provide support for?) but I know I've run into this at least once and it'd be super useful to get back a response that isn't 404.

**Comment by nanaya** [comment]
The topic title seems wrong

```
$ http --json post https://osu.ppy.sh/oauth/token
HTTP/1.1 400 Bad Request
CF-Cache-Status: DYNAMIC
```

**Comment by Master-chan** [comment]
Fixed the title. Seems that java default http client doesn't properly follow some standards.
