### ISSUE TITLE
New (lazer-first) mods and settings don't display on recent scores

### ISSUE THREAD

**Issue by STCapricorn** [ppy/osu-web#7521]
not sure where i should put this, but it seems self-explanatory.

tested with no other mods and with hidden. autopilot doesn't have the same problem.

edit: happens with the new lazer-specific mods as well (classic, wind up, grow tested)

![osu_2021-04-23_06-11-37](https://user-images.githubusercontent.com/7162510/115796222-abd65000-a3fb-11eb-80cc-696fbbfbb5cb.jpg)

![osu_2021-04-23_06-16-29](https://user-images.githubusercontent.com/7162510/115796228-b0026d80-a3fb-11eb-92e6-3873066fcf17.jpg)

![image](https://user-images.githubusercontent.com/7162510/115796628-5d758100-a3fc-11eb-87ed-a31dd30137ad.png)

**Comment by wowcake** [comment]
Also happens with Difficulty Adjust mod.

**Comment by peppy** [comment]
This is intended.

**Comment by peppy** [comment]
Will keep this open to track the issue as I can see more users potentially reporting it.

**Comment by nanaya** [comment]
This isn't resolvable without first switching to new score table.

**Comment by nanaya** [comment]
Removing priority label for now as it just distracts from other immediate issues.

**Comment by nanaya** [comment]
Closing this in favour of #10471 since it's more general.
