### ISSUE TITLE
Lodash Vulnerabilities

### ISSUE THREAD

**Issue by Arlangue** [ppy/osu-web#7523]
Go check those Lodash vulnerabilities https://snyk.io/vuln/npm:lodash?lh=4.17.20
You should update your Lodash package to be safe.
This is important!

**Comment by peppy** [comment]
Unless you have a very specific example of how this would affect us, it's likely quite low priority, as this is only run on client side logic. It will likely get updated with the next dependencies bump.

**Comment by notbakaneko** [comment]
we're already on `4.17.21`, this is just spam

**Comment by peppy** [comment]
Makes sense. I thought I remember this already being handled via a github vulnerability report.
