### ISSUE TITLE
Requesting user data by username from APIv2 is slow because of redirect.

### ISSUE THREAD

**Issue by Master-chan** [ppy/osu-web#7527]
APIv2 requests by username are redirected to userId. This results in total request time being 900ms on average, compared to 350ms on APIv1. While I don't think it is critical, ~2.5x time difference for one request is pretty big.

**Comment by peppy** [comment]
I think we should be avoiding redirect in an API call in general. It also adds server overhead due to it doubling the requests / lookups.
