### ISSUE TITLE
Verification request disappearing after refreshing the website

### ISSUE THREAD

**Issue by goebeldamian** [ppy/osu-web#7540]
While scrolling through the beatmaps section on the website, sometimes I got a pop-up with a verification request. Pop-up disappears after refreshing the website and I am able to scroll freely without providing the verification code.

**Comment by peppy** [comment]
Seems very weird and worth investigation.

**Comment by nanaya** [comment]
Looks like a duplicate of #7295.

**Comment by peppy** [comment]
Basically, the OP here must have triggered an action like favouriting a beatmap, which caused the verification popup. May have been an accidental click. Scrolling alone should not encounter this issue.
