### ISSUE TITLE
Index needs to be added to `solo_scores`

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#7547]
Has been done server-side, but adding a migration needs to be done.

**Comment by junaidtariq48** [comment]
@peppy  i can see in migration there is already some columns got index. which field you want to index in `solo_scores`

**Comment by peppy** [comment]
Oh sorry, somehow missed that. There should be an index on `user_id`.

**Comment by nanaya** [comment]
Apparently the index already exists and prod now has two indexes on `user_id` :thinking:

**Comment by peppy** [comment]
very confused at this point.
