### ISSUE TITLE
Audio previews are cached for many days before updating with beatmap updates

### ISSUE THREAD

**Issue by VINXIS** [ppy/osu-web#7554]
https://osu.ppy.sh/beatmapsets/1415465#osu/2917229

Mapper states they updated the audio preview 4 days ago but they still hear the old audio

From https://b.ppy.sh/preview/1415465.mp3 
The mapper currently hears this: https://cdn.discordapp.com/attachments/357216522919477249/838881450258464798/1415465.mp3

The intended preview (which I also hear) is to be this: https://cdn.discordapp.com/attachments/357216522919477249/838880537635979264/1415465.mp3

Not sure if it was intentional for caching to last this long for some users such as the mapper themselves, if it was it seems to be lasting too long for some users but again not sure

**Comment by peppy** [comment]
This is an intentional change to reduce costs. We probably need to setup a cache refresh endpoint like we have for avatars, but not sure how that's looking (@ThePooN)

**Comment by ThePooN** [comment]
@peppy s3-nginx-proxy cache busting has been implemented long ago, so you can implement that on your end now. or implement the Cloudflare cache purge API request since that will be solely used post-R2 migration, and is still half-effective with s3-nginx-proxy.

**Comment by peppy** [comment]
I've added cloudflare purge support here (for both audio previews and old-style-thumbnails).
