### ISSUE TITLE
Add a "nominated beatmaps" section in the "beatmaps" tab on user profiles

### ISSUE THREAD

**Issue by VINXIS** [ppy/osu-web#7555]
Would be nice if users that are/were BNs/NATs/QATs/BATs/MATs/e.t.c could have a section on the user profile showcasing the beatmaps they have/had nominated for ranked/approval

Something like this would be cool
![](https://i.imgur.com/Nc8YOCz.png)

Kind of ties in with https://github.com/ppy/osu-web/issues/7329 though that one is moreso for NATs/management while this is moreso just to showcase stuff nominated

**Comment by peppy** [comment]
Seems like a cool addition. Should be pretty simple to add this in, presuming the underlying data is indexed in some way already.

**Comment by AJT127** [comment]
What was the status on this? It would be cool so a bit sad that it just died

**Comment by peppy** [comment]
It's up to someone to implement. I think this might be something a non-team member may be able to give a try since it should be mostly about adding a new section with slightly different criteria.

**Comment by Sebola3461** [comment]
It will include ranked beatmaps too? Or just qualified beatmaps?

**Comment by VINXIS** [comment]
Definitely should have ranked beatmaps

**Comment by Sebola3461** [comment]
ok, thank you. Me and @hiviexd will add this feature.

**Comment by Sebola3461** [comment]
One more thing, what we do with "Ranked Beatmaps" section?

**Comment by VINXIS** [comment]
It should stay the same

Just to be clear my request feature was mainly focused on (ex)BNs/NATs/QATs/MATs etc where the beatmaps they have nominated, so for example on my page it would show all the maps I have pressed the Nominate button on.

It should have 0 overlap for almost any user this applies to between Ranked Beatmaps and Nominated Beatmaps

**Comment by Sebola3461** [comment]
yea i got noticed now

**Comment by Hiviexd** [comment]
so basically it should be all maps from this page https://osu.ppy.sh/beatmapsets/events?user=14102976&types%5B%5D=nominate&min_date=&max_date= excluding duplicates, right?

**Comment by VINXIS** [comment]
yea

**Comment by AJT127** [comment]
i personally would also want to know that info
but if not then u could just call the section "Ranked Nominations" and have ranked only

**Comment by VINXIS** [comment]
Dunno i feel like showing https://osu.ppy.sh/beatmapsets/1193555 under Hobbes2's page for example is kinda ehhh but adding it or not doesnt really matter to me PERsonally

**Comment by AJT127** [comment]
ok that was a good counterargument i suppose since he purposely elected to not be involved with the map anymore so it'd be kinda unfair to attach it to his name so i agree with u now
