### ISSUE TITLE
Website UI change for Beatmap Descriptions 

### ISSUE THREAD

**Issue by CIubber** [ppy/osu-web#7559]
A common trend among mappers is to include a bunch of info such as GD names, map banners and artist info in the Beatmap Description box however I feel it isn't pronounced enough as of current and is frankly far too small to fit the amount of info that some mappers want to include. It would probably fit much better if the meta data section (red) was moved up onto the beatmaps BG panel and the description be widened, or the whole bottom bar be further extended down to allow more room for the description box (blue)
![image_2021-05-06_204616](https://user-images.githubusercontent.com/83761758/117286103-1e3f3980-aeac-11eb-8576-f3189a831b0e.png)

**Comment by peppy** [comment]
There is already a design refresh incoming which addresses this:

![20210507 134132 (Figma)](https://user-images.githubusercontent.com/191335/117398766-f696b280-af39-11eb-9edd-b87b30af287a.png)
