### ISSUE TITLE
Some pp values from before recalculation for player -ZooM- (https://osu.ppy.sh/users/7728757)

### ISSUE THREAD

**Issue by stanrunge** [ppy/osu-web#7560]
Some of the top plays of player -ZooM- (player ID: 7728757) appear to not have been processed correctly by the recent pp recalculations, or if they have, then they at least don't appear like they should on the website. For instance, their top play (Simarik) has 771pp when it should be worth 707pp (like what ChocoPafe got on the same map with the same mods with the same combo (full combo) and with the same accuracy). 
![image](https://user-images.githubusercontent.com/65637274/117304913-8bd47100-ae7e-11eb-9ec8-9b7a0b5a8407.png)
<img width="931" alt="Screenshot 2021-05-06 at 3 20 55 PM" src="https://user-images.githubusercontent.com/65637274/117305120-bfaf9680-ae7e-11eb-8623-05aa9d9dd8d4.png">

Some other plays like their 3rd top play, Imagination +DTHDHR, or their 6th top play, Horrible Kids +DTHDHR, also show pp values from before the latest pp recalculation.

**Comment by peppy** [comment]
Thanks for your report. These will gradually be amended over time as more users play or as we continue processing the billions of scores in the background.
