### ISSUE TITLE
South Sudan is missing from the rankings

### ISSUE THREAD

**Issue by myangelaku** [ppy/osu-web#7562]
https://github.com/ppy/osu-web/blob/master/database/seeds/ModelSeeders/CountrySeeder.php#L44

While "countries"/territories such as Antarctica are included, South Sudan seems to be missing. This is probably because [it is a relatively new country that split from Sudan in 2011](https://www.iso.org/obp/ui/#iso:code:3166:SS).
Moreover, I figured that it already appears in [the code of lazer](https://github.com/ppy/osu/blob/master/osu.Game.Tournament/Resources/countries.json)

**Comment by Joehuu** [comment]
See https://github.com/ppy/osu-web/issues/5542#issuecomment-578413248.

**Comment by myangelaku** [comment]
> 
> 
> See [#5542 (comment)](https://github.com/ppy/osu-web/issues/5542#issuecomment-578413248).

In that case, **one single player** in [Guinea-Bisseau](https://osu.ppy.sh/rankings/osu/performance?country=GW) (a country in West Africa) equals "enough to matter"?

**Comment by Joehuu** [comment]
There is an issue open for that: https://github.com/ppy/osu-web/issues/5543.
