### ISSUE TITLE
Purpose of `user_pending` on `phpbb_user_group`

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#7565]
I'm wondering why there are checks against `user_pending` throughout the app, when (as far as I can tell) all group memberships have it unset. I understand the column itself comes from phpbb but is it actually used anywhere? if not, I want to remove all of the unneeded logic

**Comment by peppy** [comment]
It's there for safety until we completely retire phpbb (aka turn off old.ppy.sh).

**Comment by peppy** [comment]
Going to close this for now; I don't think we need a tracking issue for it. @cl8n let me know if you need anything else answered.
