### ISSUE TITLE
Allow deletion of maps if pending/wip

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#7566]
Right now people can delete their maps only if it's graveyarded. I had couple requests from others to delete maps either due to duplicate/accidental upload or for other reasons because of this. [This thread](https://osu.ppy.sh/community/forums/topics/1311754) makes me believe this behavior might have been an oversight.

**Comment by peppy** [comment]
The current behaviour is intended to stop upload abuse. If there is a copyright issue please contact copyright@ppy.ah.
