### ISSUE TITLE
"Show Voted" filter on contest page breaking gallery view

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#7584]
The "show voted" filter seems to break the contest gallery view. Console spits out "Uncaught TypeError: l is undefined"

![image](https://user-images.githubusercontent.com/35633093/117864091-b5cdcf00-b294-11eb-9b28-5317223306cb.png)

Steps to reproduce:
- load the page, e.g. https://osu.ppy.sh/community/contests/125
- check show voted
- try to click on an image to show the gallery

Browser: Firefox 88.0.1 

Sometimes the gallery view opens and you can navigate using arrow keys, however the moment you click anywhere the same error appears

**Comment by venix12** [comment]
I'm using google chrome and getting a little different error but stil.
![](https://i.imgur.com/Sj9C9lI.png)
