### ISSUE TITLE
Markdown parser improvements

### ISSUE THREAD

**Issue by nanaya** [ppy/osu-web#7586]
- [ ] upgrade to latest commonmark library
  - API change is involved
- [ ] both `html` and `indexable` should use same list of parsers/extensions
  - `indexable` is currently missing AttributesExtension when it should be used
    - probably need to add additional renderer for that? Or not?
  - and it always uses `StyleBlock` even when it shouldn't
- [ ] move `OsuMarkdownProcessor` to extension so it can be registered last and be sure to be the last thing to be run
  - mainly to remove the need for `(new AttributesExtension())->register($env)` hack

**Comment by cl8n** [comment]
i can do these today
