### ISSUE TITLE
Add support for `grave` `escapes` in changelog titles

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#7594]
We've been doing this a lot more since github now supports this natively (see https://osu.ppy.sh/home/changelog/lazer/2021.514.0).

Styling could be something similar to how github does it - a rounded gray background around the phrase.

**Comment by cl8n** [comment]
do you want to allow all inline markdown too or just code?

**Comment by peppy** [comment]
no, this would be the only case. it's fine to do simple parsing rather than full markdown if that's easier to implement.
