### ISSUE TITLE
Fix the registration issue please

### ISSUE THREAD

**Issue by chase12345678-jpg** [ppy/osu-web#7595]
I don’t know if you just stopped letting people register. But I’ve been playing osu!lazer for over a year. All I want to do is make an account but everytime I try to it just says “something happened and we’re not sure what”

**Comment by bdach** [comment]
I can guarantee you that the issue won't be fixed if you refuse to provide any pertinent details whatsoever to diagnose the problem.

Please open an issue over at https://github.com/ppy/osu/, and follow the issue template therein. In particular please make sure to attach the log files after trying to register (do not restart the game between trying and uploading logs, or the logs will be discarded).

**Comment by chase12345678-jpg** [comment]
you might get impatient due to the fact that I've never done something like this before. I but it's happening to a lot of people and has been for a long time idk it may be because I'm on a school laptop and others are too. 

2021-05-13 19:33:01 [verbose]: Request to https://osu.ppy.sh/users failed with System.Net.WebException: NotFound.
2021-05-13 19:33:01 [verbose]: Response was: 404 not found
