### ISSUE TITLE
Show music source when hovering

### ISSUE THREAD

**Issue by isweethero** [ppy/osu-web#7599]
Music source has always been shown when hovering over a beatmap card.
![image](https://user-images.githubusercontent.com/38861963/118312373-9d91c600-b4c7-11eb-83f3-b3087fe0b7d7.png)
Now it's gone.
![image](https://user-images.githubusercontent.com/38861963/118312468-c914b080-b4c7-11eb-85be-73e884c76f74.png)

It's good to show that the music is not originally from osu.
And i miss this.

**Comment by peppy** [comment]
It's coming back in the near future with a larger card option. This should arrive within a week or two and is already tracked elsewhere.
