### ISSUE TITLE
Allow set host to resolve pending issues along with difficulty owner

### ISSUE THREAD

**Issue by Shmiklak** [ppy/osu-web#7601]
As for the last updates we are now able to choose difficulty creators on our sets, which makes set host unable to resolve pending issues on their difficulty which might lead to some issues when changes to difficulty should be done by hosting mapper (like some technical stuff or hitsounding) or in case the guest mapper allowed set host to apply mods for them. My suggestion is to keep host mappers ability to resolve issues as addition to guest mappers.

**Comment by MzudemO** [comment]
Can't you just change owner to yourself, resolve, then change back?

**Comment by Shmiklak** [comment]
This would require too many actions and feels as a wrong way to perform actions which could be easily implemented
