### ISSUE TITLE
Consider switching audio previews to ogg preset 0

### ISSUE THREAD

**Issue by Kyuunex** [ppy/osu-web#7608]
Currently, previews are mono mp3 files with a bitrate of 64 kbps, and 22 kHz sample rate. 
I recommend switching to ogg preset 0 that yields 64 kbps audio but it can also take in full 44 kHz sample rate and stereo and still sounds much much better than mp3, even if mp3 was also stereo and 44 kHz, while taking about the same amount of disk space.

For comparison, bellow I attached a zip file (GitHub wouldn't let me upload them otherwise) that contains the same segment of the song in both ogg and mp3. ogg is just a tiny bit bigger but that can be compensated by shaving off last one second if desired.
[comparison.zip](https://github.com/ppy/osu-web/files/6488766/comparison.zip)

**Comment by peppy** [comment]
https://caniuse.com/?search=ogg

**Comment by nanaya** [comment]
it's 2021 so maybe opus instead if anything https://caniuse.com/?search=opus

**Comment by Kyuunex** [comment]
last i checked, osu-stable can't play opus, so idk how it will work with osu!direct

**Comment by peppy** [comment]
Already tracked via https://github.com/ppy/osu-web/issues/6459 as well.

**Comment by AuracleTech** [comment]
Wait you closed #6459 mentioning this one.
I believe we lost an issue, either this one or #6459
