### ISSUE TITLE
Can not view profile modding tab

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#7617]
It was working earlier this week so likely some recent update to the page broke it. It won't load for any profile that I've checked. I've checked for BN, NAT, and regular user's pages. All are the same.
![image](https://user-images.githubusercontent.com/33286824/118537796-63b8fd80-b71b-11eb-8aa0-3e3acf283cc7.png)

Not sure what other info I'd need to add but let me know and I'll grab it as needed.

**Comment by Gabixel** [comment]
I never check that page, but I just tried to load it and I can confirm that it doesn't show anything.
The browser's console returns an error about an undefined id:

![console](https://user-images.githubusercontent.com/43073074/118538538-9cbe9580-b74e-11eb-9d95-41d18e17ac2d.png)

**Comment by Respektive** [comment]
just wanna add that it seems to work for users with no recent events or discussions, for example WhiteCats modding tab loads.
