### ISSUE TITLE
Monthly nomination cap per Beatmap Nominator

### ISSUE THREAD

**Issue by yaspo** [ppy/osu-web#7621]
Following internal discussion within NAT, we'd like to request a cap to how many mapsets a Beatmap Nominator (BN) can nominate within one month. This cap needs to be at 75 over 90. This can either be rolling or based on months of the year. It should only count unique nominations; BNs should be able to re-nominate a map of which they had their nomination reset without it counting to the cap.

Reasoning:
When a BN's activity trends towards 1 nomination per day they'll spend little time per nomination, and are consistently observed to make bigger mistakes more frequently due to dropping the quality of their work accordingly. From our experience with evaluations, 75 is the cut-off point that separates BNs with high activity and BNs that are "spamming" nominations. The majority of BNs never or rarely reach 75 nominations within 90 days making this a lenient sanity measure for things growing to unhealthy proportions. This is similar to the daily nomination cap.

This is something that isn't reasonably dealt with through regular evaluations. Larger volumes tend to skew performance metrics to look more positive as it will be difficult to track nominations and act on them at the same rate a spamming BN is nominating. Doing an in depth evaluation at larger volumes is too resource-intensive to be cost-effective.

Edit: updated the cap from 20 per month to 75 over 90 days

Edit 2: Implementation on hold to save Dev time and work out uncertainties. We'll try this out with policy over implementation first, so BN rule + simple tracking. Will make a new post if/when ready to implement

**Comment by lassem22** [comment]
"When a BN's activity trends towards 1 nomination per day they'll spend little time per nomination, and are consistently observed to make bigger mistakes more frequently due to dropping the quality of their work accordingly," 
This is generalizing things way too much, if you have a the time and motivation you could easily hit 1+ quality nominations a day given you can find enough maps. 
Properly checking a map can take anywhere from 10 minutes up to multiple hours, but in most cases you could assume around an hour on average.
Adding a cap here doesn't address the actual issue (low nomination quality, bad checks), that is something that has to be dealt with on a per-nominator basis. 
This change does nothing besides capping the number of "bad nominations" someone can do to 20 a month which is still way too many "bad nominations" in the first place.

**Comment by cl8n** [comment]
> Adding a cap here doesn't address the actual issue (low nomination quality, bad checks), that is something that has to be dealt with on a per-nominator basis.
> This change does nothing besides capping the number of "bad nominations" someone can do to 20 a month which is still way too many "bad nominations" in the first place.

if I'm not understanding this wrong, this is not trying to only cap "bad nominations", but let NAT effectively evaluate super-active BNs in the first place. @yaspo makes it sound like NAT does not currently have the resources to do proper evals in these cases, so they *cannot* "address the actual issue" by dealing with nominations individually

> This is generalizing things way too much, if you have a the time and motivation you could easily hit 1+ quality nominations a day given you can find enough maps.

this is meant to be a generalization based on observation, it's said in the thing you quoted... taking OP's words as-is, this is supposed to be "lenient", so if you can show it's strict in some way then that would be reason to increase the limit or drop this proposal altogether.

to me this feels like a natural extension of daily nomination limits, OP outlines what check out as valid concerns for nomination assessment, and it also checks out that BNs rarely hit >20/mo anyway, so I'm kinda surprised ppl have latched onto negative opinion of this so quickly.

if not by a simple cap like this, it sounds like NAT is in need of better tools or more helping hands to handle eval cases where 1 BN makes a ton of nominations

**Comment by MzudemO** [comment]
How does this factor in with BNs now self-managing and self-evaluating? I was under the impression that that was meant to solve the lack of resources for evaluation in NAT.

There have been cases in the past where BNs were kicked for too many nominations and little/poor modding of those. What changed since then that that process isn't sufficient anymore? This change seems like a knee-jerk reaction to a single case, which I'm not convinced even exhibits the "lack of quality" you want to avoid with this rule.

**Comment by Negaosu** [comment]
If you're going to do a cap, at least make it something more reasonable like 30-40 (~1 per day on average). However I disagree with the addition of a cap in the first place, it's perfectly possible to do well over 20 nominations per month whilst rechecking each nomination extremely thoroughly and having no major issues occur, and introducing a cap (at least this low), just makes it so certain BNs have to stall on their requests for no good reason whilst they are performing well overall, and I don't consider the NAT needing to evaluate them being a good enough reason to do this.

**Comment by yaspo** [comment]
Hi, what a day.

Updated to be 75 over a 90 day period, or a 25 average. This is based on the following statistic which measures "peak" activity for the highest performing BNs in this 90 day timeframe.

| user     | nominations | date       |
|----------|-------------|------------|
| Sonnyc   | 51          | 2021-01-19 |
| Hivie    | 52          | 2021-04-27 |
| eiri-    | 53          | 2020-08-22 |
| ikin5050 | 54          | 2021-03-09 |
| Lasse    | 56          | 2020-09-03 |
| Smoke    | 57          | 2020-08-21 |
| Raiden   | 60          | 2020-11-02 |
| Agatsu   | 71          | 2020-12-31 |
| Vulkin   | 96          | 2020-04-11 |
| Cheri    | 115         | 2021-05-16 |
| Gamelan4 | 125         | 2020-05-29 |
| Capu     | 128         | 2020-05-17 |
	
so, this covers "spamming" more in the spirit of the daily cap.

to clarify some stuff:

Essentially, each evaluator spot-checks 3 random maps for each bn during their evaluation, or 3x3 = 9 total maps. There's no real way to get around the manual and rather robotic nature of this task; it's essentially QAH on ranked maps. So, it's best kept at a minimum, there's a limit to how much time most want to spend on tasks that are inherently not super enjoyable. Keeping it a minimum also means not literally all our energy goes into maintenance (even though that's kindof what it's been like).

This number 9 gives a good gist for what most BNs nominate. But the higher the total number of evaluations get, the less relevant those 9 maps get. To maintain an actually reasonable idea of someone who's at say .. 120 nominations, you'd probably want to check a quarter to a third of their nominations. This translates into at least 30 mapsets to check. No matter how you assign this, 3 maps x 10 evals, 10 maps x 3 evals, 5 maps x 6 evals, etc. , it'll always be a silly amount of manpower investment for one single BN. This, especially so when both applications and current BNs are evaluated continuously.

At 75 max the number 9 can be a niche compromise, or potentially be increased to 4x4, which is a more acceptable tradeof. 

Why can't we use Trial NAT for this? Well, mainly the aim with this project is to shift/distribute the workload and not to simultaneously increase it. Have people check more maps and it stops being a small, approachable task. Throw more people at single BN's evaluation and it becomes increasingly difficult to coordinate in a timely fashion. Just imagine 10 people disagreeing about whether or not a BN should be probationed lol.

As for whether or not it's possible, we more-so just lowballed it too much. The idea remains the same, but extending it to 3 months and increasing it a little should show which kind of cases it addresses. It's correct that this doesn't magically fix map quality throughout the ranked section on its own .. but that was never the point.

Otherwise we'll continue treating BNs on a case by case basis as we always have, this is just a necessary sanity limit so these systems don't become unapproachable for the hands of human volunteers.

**Comment by peppy** [comment]
Is it safe to say that a conclusion or stalemate was arrived at here and we can close this issue for the time being?

**Comment by yaspo** [comment]
Can be closed, we've added this to our rules section instead
