### ISSUE TITLE
Add multiaccounting as a user report option

### ISSUE THREAD

**Issue by venix12** [ppy/osu-web#7626]
Currently, a lot of people are reporting for multiaccounts with reason "other", which is kinda spammy on #web-reports listing, would make sense to have a custom option for that and have it in separate channel that's not visible to mods (see like cheating reports) as they are not responsible for handling those cases.

**Comment by OsuHoutaro** [comment]
would help as well for newer players that speedrun the rules that multi-accounting is bannable

**Comment by cl8n** [comment]
should multiaccount reports go to the same endpoint as cheating? or a new one?

**Comment by peppy** [comment]
same is fine
