### ISSUE TITLE
Add descriptions on group pages

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#7640]
I don't remember when it was, but group pages used to have short descriptions about their purpose. not sure why that was removed. having a description on-page can help ppl learn about it quickly

currently this isn't very important since there aren't prominent links to the group listings in the first place (if you're on the page, you likely already know what the group is), but after #6936 it would have good use.

**Comment by notbakaneko** [comment]
The groups page was updated to match the user listing of the friends page, which didn't include any design for the description; this appears to have been a [known issue](https://github.com/ppy/osu-web/pull/4412) that fell away 🤔 

Preferably, they should also link to the wiki; https://osu.ppy.sh/wiki/en/People/The_Team#user-groups
