### ISSUE TITLE
Image quality on new larger beatmap cards

### ISSUE THREAD

**Issue by Rekunan** [ppy/osu-web#7649]
When looking at the images (thumbnails?) on the larger beatmap cards, they have a lower quality when comparing against the smaller version.
Smaller:
![image](https://user-images.githubusercontent.com/24501632/119504370-822d8300-bd31-11eb-83bb-4c4113aed5cc.png)
Larger:
![image](https://user-images.githubusercontent.com/24501632/119504410-8eb1db80-bd31-11eb-891b-210164613dd9.png)

**Comment by peppy** [comment]
This is a known issue and will improve over time as we regenerate thumbnails for the new size.

**Comment by peppy** [comment]
These have now been completely regenerated and should look pretty great.
