### ISSUE TITLE
When selecting mods on a beatmap, have it change the CS,HP,AR etc appropriately

### ISSUE THREAD

**Issue by nlynnerup** [ppy/osu-web#7675]
**What**
When you're on the website and you select a beatmap it should be possible to see how the CS,HP,OD,AR,SR gets affected by the mods selected.

**Why**
Wouldn't it be nice to see what changes when you select mods, without having to be ingame?

Thanks : > )

**Comment by peppy** [comment]
Don't think this is a worthwhile use of development time when it's already visible in-game.
