### ISSUE TITLE
Notifications not dismissing when using Middle Click

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#7687]
It seems as if comments from watched comments sections do not dismiss once one takes a look at them

![07f1xJpPwZ](https://user-images.githubusercontent.com/35633093/120643281-405db480-c476-11eb-8705-2ca5a37d3b67.gif)

**Comment by peppy** [comment]
Can you confirm whether they dismiss if you try from the notification panel, rather than the history page?

**Comment by nanaya** [comment]
It's because middle clicking bypasses browser click event...

**Comment by peppy** [comment]
Nice catch. I guess there's no real way around this?

**Comment by nanaya** [comment]
It does trigger mouseup/mousedown but the whole notification section doesn't currently properly support middle clicking to begin with (only certain area can be middle clicked).
