### ISSUE TITLE
Beatmap search functionality in API

### ISSUE THREAD

**Issue by eclipsevtuber** [ppy/osu-web#7716]
I want to be able to search the API for beatmaps using a query, exactly like how I can on the actual beatmap site, and return a list of json blocks with basic data on the beatmaps, or just like download links. Is this already supported/possible?

**Comment by eclipsevtuber** [comment]
I've seen that someone was able to make their own search engine for osu, but I have yet to figure out how to actually do it myself.

**Comment by gagahpangeran** [comment]
You can use this endpoint

```
https://osu.ppy.sh/api/v2/beatmapsets/search/{filters}
```

There is [no documentation for the filter yet](https://osu.ppy.sh/docs/#beatmapsetssearchfilters), but it's the same as query parameter for filter in https://osu.ppy.sh/beatmapsets
