### ISSUE TITLE
How to search API for beatmapsets by query

### ISSUE THREAD

**Issue by eclipsevtuber** [ppy/osu-web#7718]
The search function is completely undocumented (/beatmapsets/search/{filters?}), but I've been getting a response when I make a request. The problem I'm having is that it isn't actually giving me anything I searched for, instead just spitting out the same beatmapset every time. How am I supposed to do this, exactly?

**Comment by gagahpangeran** [comment]
[As I wrote before](https://github.com/ppy/osu-web/issues/7716) the filter is the same as filter query param in https://osu.ppy.sh/beatmapsets

**Comment by eclipsevtuber** [comment]
> [As I wrote before](https://github.com/ppy/osu-web/issues/7716) the filter is the same as filter query param in https://osu.ppy.sh/beatmapsets

I didn't see the response- my bad
