### ISSUE TITLE
Bad performence

### ISSUE THREAD

**Issue by HoutarouOreki** [ppy/osu-web#772]
I decided to let know that there's an issue like this for me as it's kinda annoying.
## **System**
- Windows 10
- Intel Pentium Dual Core 3GHz
- Nvidia GT 240 512mb
- 2gb ram 
## **Details**

On the old website after clicking a link to my profile it always took about one second for the page to load and be usable. By usable I mean that it's smoothly scrollable and the browser doesn't lag. For the new page it takes about 8 seconds for the profile page to be half-usable. When scrolling down the page continues to load and the scroll itself is not smooth even after the page is fully loaded. What I also noticed is that the game's performance is affected when the page is turned on in the browser in the background. This also happened with the old YouTube player and some other heavy websites, but it doesn't happen with the current osu! website. 
- The problem applies not only to profile pages but it's 1.5x more impactful on these.

**Comment by peppy** [comment]
Which page are you testing on?

**Comment by HoutarouOreki** [comment]
I was describing profile pages mainly but the problem's been present on new.ppy.sh in general. Though now I think I either was delusional or you guys did something about it, because I don't really get this problem anymore.. 
The only change on my end is overclocking from 3ghz to about 3.4ghz but I don't think it could be because of this that the new page is responsive now.

**Comment by HoutarouOreki** [comment]
Closing as this was probably just something on my side.
