### ISSUE TITLE
Live Stream Page buttons should have a tooltip/different icons

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#7722]
https://osu.ppy.sh/community/livestreams
![image](https://user-images.githubusercontent.com/35633093/121752434-663b2700-cb10-11eb-96c1-92c0ae4b2aa1.png)
![image](https://user-images.githubusercontent.com/35633093/121752449-6c310800-cb10-11eb-9e22-fc6f5b5174fd.png)

Clicking thumbs up opens that stream in big, while thumbs down closes it again, bringing you back to the overview. These are not really obvious and should have either a tooltip or a different icon

**Comment by cl8n** [comment]
not directly related to issue, but in case you didn't know this is a moderator function which pins the stream for anyone visiting that page.

**Comment by peppy** [comment]
It should probably have a confirmation step since this issue makes it apparent that people with permissions may be promoting a stream without even realising it..
