### ISSUE TITLE
Discussion Posts should have icon tooltips

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#7730]
Its not really obvious what heart, speaker, note and so on mean to someone that isnt used to the modding system.. would be quite helpful to have tooltips on the icons

**Comment by cl8n** [comment]
icons for praise, note, problem, and resolve seem very clear to me. suggestion is just a circle but at least the color and post contents tell you what it is. hype isn't clear but it's not like a tooltip that says "Hype" does anything to explain it either

I see no harm in adding this but I also can't see how it would help new modders 🤔

**Comment by RockRoller01** [comment]
Only really talking from own experience and have been mixing up mainly hypes and praises, as they both usually contain meaningless comments, while one of them is important to the system and one is not.

Just one of those many "nice to have, not a problem to do and will maybe help someone" features
