### ISSUE TITLE
Character limits for praise/hypes

### ISSUE THREAD

**Issue by VINXIS** [ppy/osu-web#7731]
Compared to suggestions and problems hypes and praises don't need much to be said for those posts so it would be a good idea to create some form of a low character limit (even like 120 chars/twitter level) for them to reduce any potential cause of what anyone may consider as "spamming" of whatever degree

**Comment by VINXIS** [comment]
Can also include line limit as well

**Comment by cl8n** [comment]
abraker and I were looking through praise/hype messages and found that the longest not-spam posts were ~200 characters / a few sentences
I think 250 limit sounds good, also just round number with timeline limit (750). not sure if line limit is necessary

**Comment by peppy** [comment]
Is there something that spurred this? Are people spamming long text regularly?

**Comment by VINXIS** [comment]
They are regularly posted. A conflict of interest is definitely emerging so this is just a proposal more than anything.

It's become sort of a "tradition" per se by many people who regularly use beatmap discussion pages to regularly post some form of text of what can also be usually considered as "funny" when posting a praise/hype by mappers/modders/BNG/NAT, which global moderators are tending to notice lately because they can be considered under spam/unrelated to the beatmap/e.t.c. Depends on what is wanted most here but the proposal stems from what the global moderators have noticed

**Comment by Ephemeralis** [comment]
It might sound trivial, but it is becoming a point of contention between people who want to use praises/hypes as essentially shitpost celebrations and people (usually moderators) who view them as spam or unwanted content. Given both praises and hypes are meant to be positive expressions, moderating them tends to result in people responding rather poorly to the people performing it, even if those posts are breaking the rules.

For context, a recent top contributing BN resigned after receiving a 1h silence for posting a small piece of ASCII art on a praise made to a low traffic map.

In my view, it would be better for the community's health (and to promote engagement) to allow these expressions with a reasonable cap and perhaps some form of sorting toggle to quickly hide them if their spam becomes too much. The closest thing I can think of is equating them to nico nico comments.

**Comment by peppy** [comment]
Who is behind the moderation? They should generally only be moderated on report, so are people reporting these comments? If so, is it the mappers reporting? That shows that we should likely be taking action if so, since the mappers are the ones supposed to be benefitting from the praise section.

That said, if anything I think the discussion system SHOULD be moderated and i have NO idea how you equal it to "nico nico" comments which is basically shit thrown at a wall. Should that kind of stuff be put on the beatmap comments instead of the discussion/mod system?

**Comment by peppy** [comment]
To reiterate: The whole premise of the praise system was for the same level of thought to be put in as ANY OTHER area of the discussion system. If this is not maintained it may as well be nuked.

**Comment by Okorin** [comment]
dunno what you're saying here - posting feedback is inherently different from saying 'i like this! cool', posting a thumbsup or whatever for the person who made the map

whatever you post in praises rarely is subject to debate / discussion anyhow so i'm not sure i follow your point apart from saying shitposting should be moderated

**Comment by VINXIS** [comment]
Uh also just to clarify, the unrelated/"spammy" nature of some of those posts usually are taken as positive reception by the mapper(s) and people coming in to the beatmap discussion page

**Comment by Ephemeralis** [comment]
It's probably a toss-up either way for praises in terms of meaningful feedback & shitposting, but I've never seen hypes be anything but spam/shitposts for the most part since they're essentially mandatory. Splitting hypes out somewhere else might be worth investigating.

**Comment by peppy** [comment]
Hypes should probably not even get the ability to comment to be honest. That will likely reduce the spam.

**Comment by Ephemeralis** [comment]
Definitely.

I get what you're angling for with praises and that does happen sometimes, but often just the act of someone leaving a praise to begin with even with nonsense feedback or nothing meaningful included in the comment is taken as support of the mapper and their work from a social perspective, so I hold some concerns that trying to moderate them too much might be hurting more than it helps. Shitpost culture is hard to explain in contexts like this.

**Comment by SecreOsu** [comment]
removing the ability for hypes to comment would remove a lot of community interaction between random players and the mapper

overall I think that limiting character limits for hypes/praises is definitely not the way to go. If you really want to limit characters, do it on hypes, but praises can actually have use in them as some modders use them to tell mappers' what parts they like about the map (shocking right, people use the system for its intended purpose)

imo GMT are overstepping their bounds on a lot of message removals lately, spam isn't just 3-4 lines of a meme, spam is unwanted multiple message shitdumps. When BNs nominate my map and put some funny message, as a mapper i personally enjoy it almost every time. The messages should only be removed when the mapper requests it or if it is SUPER excessive/insulting towards other people (think full page messages or personal insults)

**Comment by peppy** [comment]
This conversation stops here without examples. @Ephemeralis please investigate whether this is one person on the team using the page i said we shouldn't need/have (system-wide comment listing) for this exact reason.

We should be operating based on reports. Not this level of enforcement.

I think this is a team issue, not a system one.

**Comment by Ephemeralis** [comment]
We'll try dealing with this from a team perspective first. Recent pushes to address moderation in modding spaces should help fix this without needing code first.
