### ISSUE TITLE
Character limit on private messages should be adjusted for GMT/NAT members

### ISSUE THREAD

**Issue by zeusminus** [ppy/osu-web#7732]
The current character limit, which seems to be 449 for the time being, disables the GMT/NAT members from utilizing better and extensive message templates distributed to the regular users for moderation-related reasons. 

I think it would be better to escalate it to a higher number (750-1000 chars) or lift it for GMT/NAT members altogether.

**Comment by NoffyNoffeh** [comment]
Most of this use case is already covered in issue https://github.com/ppy/osu-web/issues/6404

**Comment by RockRoller01** [comment]
@NoffyNoffeh #6404 seems like a good final solution for this, however as the comments state there are currently still issues preventing it from being implemented, namely "Chat currently needs a decent bit of work that isn't just bolting more things onto it, at the moment". 
This issue kinda just is a bandage solution till "decent bit of work" is done

**Comment by cl8n** [comment]
IRC standard doesn't allow commands over 512 characters. but regardless, usage of chat messages in osu (always displayed as one wrapped line, intended to be very short, barely any useful formatting) would not suit "extensive message templates" well.

until #6404 can be considered, break long messages into multiple smaller ones
