### ISSUE TITLE
Update user profile recent play beatmap links from ?m=3 to ?mode=mania

### ISSUE THREAD

**Issue by GrilledCheeese** [ppy/osu-web#7739]
Current links look like this:
https://osu.ppy.sh/b/2509953?m=3
And they link to the standard version if it's a convert instead of the converted gamemode
Proper links look like this:
https://osu.ppy.sh/beatmaps/2509953?mode=mania
It works the same for taiko and catch the beat convert beatmap links in Recent on user profiles

**Comment by gagahpangeran** [comment]
Is this the 'Recent Plays (24h)' in **Historical** section or the exact **Recent** section?

**Comment by Joehuu** [comment]
It's the exact recent section.

<img width="633" alt="Screen Shot 2021-06-14 at 10 25 51 PM" src="https://user-images.githubusercontent.com/35318437/121997611-7bf25b80-cd5f-11eb-8fdc-32df75698f1e.png">

**Comment by gagahpangeran** [comment]
Looks like all of the links (including the user links) in those section in all modes is using old url schema.

Looking at [this event model](https://github.com/ppy/osu-web/blob/master/app/Models/Event.php), I'm afraid to touch that file to make some changes.

**Comment by nanaya** [comment]
just add the handler for `m` parameter in `BeatmapsController#show`
