### ISSUE TITLE
Display a pop-up message with the rules when making a thread or post for the first time

### ISSUE THREAD

**Issue by Corne2Plum3** [ppy/osu-web#7742]
Because there are to many people who don't respect the rules (maybe they didn't read them), I suggest to show a message like below, so people can"t say "I dIn'T kNoW...", and I'm sure it would reduce the amount of necroposts and useless threads.
Because each forum have his own rules, I think it's important to show the specific rules of the subforum.

![popup](https://user-images.githubusercontent.com/57914482/121879993-c519bf80-cd0d-11eb-9fe7-b7cb5166af7a.png)
_(Sorry for the bad grammar...)_

The user have to check the checkbox at the bottom (possible when you reach the end of the message) and then press continue to post a comment or a thread.

**Comment by RockRoller01** [comment]
Duplicate, see #4090
