### ISSUE TITLE
Expand featured artist listing pages

### ISSUE THREAD

**Issue by mrowswares** [ppy/osu-web#7743]
Just a proposal so I'll keep it brief, it would be nice to be able to browse through the featured artist songs catalog on a song-by-song basis rather than categorized by artists

The first use case that comes to mind personally is filtering for genres, BPM and length.

**Comment by peppy** [comment]
This is already covered by many issues, the most prominent being https://github.com/ppy/osu-web/issues/1804

Please search before posting: https://github.com/ppy/osu-web/issues?q=is%3Aissue+is%3Aopen++featured+artist.
