### ISSUE TITLE
Capitalization of the lowercase `i` should use `İ` in Turkish locales

### ISSUE THREAD

**Issue by zeusminus** [ppy/osu-web#7747]
As the title suggests, this is a fairly minute issue albeit a critical one in my eyes. From what I've observed, certain strings on Crowdin are delivered in their lowercase or sentence-case forms, which are rendered as full uppercase characters on the website. As a result of this process, the letter `i` becomes `I`. However, in Turkish, the uppercase form of `i` is written as `İ` so as not to conflict with the letter `I`, which is the uppercase version of `ı`. Phonetically, these two letters are completely different from each other, and using them interchangeably occasionally leads to different semantic interpretations.

For the time being, the only solution to this issue is seeking such strings and fully capitalize them on Crowdin manually, which is a tedious thing to do and probably isn't a viable solution in the long term. Therefore, just as the localization preparations are gradually coming to an end for osu!lazer, I wanted to create this issue to see if there's any possibility to get it resolved once and for all.

**Comment by peppy** [comment]
Can you give some examples of where you are seeing this?

**Comment by nanaya** [comment]
In page with problematic content, check if running this command in console (F12) fixes it

    document.querySelector('html').lang = 'tr'

**Comment by zeusminus** [comment]
> Can you give some examples of where you are seeing this?

Most prominently on the beatmap pages where the status of the beatmap is indicated (ranked, loved, qualified, etc.)
![](https://zeu.s-ul.eu/AQnomAaq.png) 
*Translation: Ranked* / Intended: `DERECELİ`

![](https://zeu.s-ul.eu/oEWrHLEV.png)
*Translation: Loved* / Intended: `SEVİLEN`

And obviously their beatmap card versions
![](https://zeu.s-ul.eu/nYiSGifg.png)
*Translation: Qualified* / Intended: `NİTELİKLİ`

They also seem to appear on the contest voting page, where it says "show voted"
![](https://zeu.s-ul.eu/Dip1xHuv.png)
*Translation: Show Voted* / Intended: `OY VERİLENLERİ GÖSTER`

In addition to these, the navigation buttons located on the performance/forum pages ("prev" and "next") used to be shown the way I pointed out, but I fixed them by changing them on Crowdin as all capitalized.

> In page with problematic content, check if running this command in console (F12) fixes it

It didn't change anything for the better.

**Comment by gagahpangeran** [comment]
> In page with problematic content, check if running this command in console (F12) fixes it
> 
> ```
> document.querySelector('html').lang = 'tr'
> ```

This change the letter.

**Before**

![image](https://user-images.githubusercontent.com/4964985/122084696-41a2c000-ce2c-11eb-9f2a-486d26e13ccb.png)

**After**

![image](https://user-images.githubusercontent.com/4964985/122084625-3059b380-ce2c-11eb-8f00-c6e10506b7c7.png)

But it's kinda bad in torus font.

**Comment by bdach** [comment]
I think this must be somehow browser-specific. Setting `lang="tr"` on the root html element works in Firefox 89 but not Chrome 91. Unsure why this would be the case, as MDN claims chrome should both [support `lang`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/lang) and [use that for `text-transform`](https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform).

**Comment by nanaya** [comment]
I think it's just chrome doesn't rerender immediately compared to firefox.
