### ISSUE TITLE
Profile page doesn't match its preview

### ISSUE THREAD

**Issue by Hexality** [ppy/osu-web#7771]
Noticed today when I was rearranging my profile that there's a glitch that may happen when one of the images is dynamically updated (svg), where the dynamic image will shift itself up after saving all changes. This doesn't happen in the "Preview" mode, only when saving 
How its looking: (how it looks after saving)
![image](https://user-images.githubusercontent.com/17398632/122840785-2ecb3800-d2d1-11eb-88b0-f81e13e671c7.png)

How it should look like: (How it shows up in the preview mode)
![image](https://user-images.githubusercontent.com/17398632/122840750-21ae4900-d2d1-11eb-9e21-2e4fe0e45135.png)

**Comment by cl8n** [comment]
can you paste the bbcode used here?

**Comment by Hexality** [comment]
sure
`[img]https://i.imgur.com/JZUe9qS.png[/img][url=https://discord.gg/CKNAftY][img]https://internals.hexality.cf/api/422274807732633604?animated=true&theme=light&borderRadius=0&showNothing=false&bg=ffffff&type=vertical&hideDiscrim=false[/img][/url][url=https://twitch.tv/hexalitylp][img]https://i.imgur.com/L7e1sbL.png[/img][/url][url=https://youtube.com/hexality][img]https://i.imgur.com/WkIVjAP.png[/img][/url][url=https://twitter.com/HexalityM][img]https://i.imgur.com/vptjBRm.png[/img][/url][url=https://github.com/hexality][img]https://i.imgur.com/kxQF4yD.png[/img][/url]`

**Comment by peppy** [comment]
This is likely an issue with whatever is sending the image not sending the correct directions. We cache dimensions so they need to not ever change.

**Comment by Hexality** [comment]
the thing is, as you can see it shows correctly in the preview mode, so I don't think the problem is actually in my end.

**Comment by Hexality** [comment]
https://user-images.githubusercontent.com/17398632/122861255-84b1d700-d2f5-11eb-88fb-d452a2f04860.mp4

**Comment by nanaya** [comment]
Slight rendering difference aside, the misaligned image is 218px tall while the rest of are 210px.

**Comment by Hexality** [comment]
yeah but that's not the issue, the 2018 is rendering up no down, the anchor is on the top not bottom afaik :/, also I tried the same size before changing to 210px, it got bigger even in the preview mode.

**Comment by Hexality** [comment]
the remote image has a like 8px of blank space btw cause its a renderer issue on my side, but the thing is that its happening only when saving, if it was on my end, it would be out-of-alignment even in the preview mode.

**Comment by nanaya** [comment]
as I said before, preview and actual render are currently slightly different. Have you confirmed it's still unaligned when saved or was it just from preview?

**Comment by Hexality** [comment]
it was unaligned after saving, not in the preview, I shown it in the video.

**Comment by nanaya** [comment]
the video you're showing is the one with 210px/218px mismatch, right? How about the uniform 218px one?

**Comment by Hexality** [comment]
let me show you what happens with only 2 images 
(preview)
![image](https://user-images.githubusercontent.com/17398632/122862689-e8d59a80-d2f7-11eb-851f-27abe5633193.png)

(after saving)
![image](https://user-images.githubusercontent.com/17398632/122862763-060a6900-d2f8-11eb-8daa-b2b7ae652856.png)

**Comment by Hexality** [comment]
using a 218px image

**Comment by nanaya** [comment]
By 218px I mean the 210px actual image with 8px blank just like the middle image, not the full image resized to 218px.

Also the other problem is the middle image is svg so it broke the preview in some ways.

**Comment by Hexality** [comment]
yeah so that's the problem, the svg thing. about the image with blank space, doing it right now as a workaround fn.

**Comment by nanaya** [comment]
Digging a bit more, the main difference is image in preview is top-aligned while the actual render is middle-aligned.

**Comment by nanaya** [comment]
Also remember that images are cached so any changes won't be shown until the cache expires.
