### ISSUE TITLE
Multiplayer match history sometimes shows wrong accuracy for catch the beat.

### ISSUE THREAD

**Issue by iptq** [ppy/osu-web#7778]
![image](https://user-images.githubusercontent.com/1700346/123054134-2f93c500-d3ca-11eb-8db6-07541c4c7eaa.png)
match history link: https://osu.ppy.sh/community/matches/86106125

In this image, all 387x scores are full combos with the top score being an SS, but the accuracy is shown incorrectly in the match history as 56.15%. The same happens for the rest of the match, where accuracy is reported to be much lower than it actually is, probably from the 100s/50s being counted as penalties to the accuracy like in standard instead of contributing 100% as it does in catch.

[@eggo_sad on twitter](https://twitter.com/eggo_sad/status/1407575703390867456) suggests that it happens when the "main mode" is set to standard. (possibly related: all of the players in the match are primarily standard players and have the default mode on the website set to standard)

**Comment by nanaya** [comment]
Nothing in the stored data indicates they're catch scores so they're all counted as standard. Even just looking at that screenshot it looks like it's standard game. @ppy ? Is the `play_mode` column in `games` table is for something else and beatmap ruleset should be checked directly instead for the actual ruleset?

**Comment by peppy** [comment]
This sounds like a bancho-side issue if anything. I'll take a look into it.

**Comment by iptq** [comment]
Yea, seems to be pretty rare. I just went back to double check the CWC match histories and they don't seem to exhibit this so possibly just a result of standard players playing catch maps.

Haven't tried reproducing it yet but I can try again tomorrow / later this week

**Comment by peppy** [comment]
I've found the cause of this (a bit of a race condition client-side) and should be releasing a fix in an upcoming cutting edge build.
