### ISSUE TITLE
Spanish localisation quality is poor

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#778]
Several users have reported issues with the Spanish localisation and its overall quality. It likely needs another pass by a native Spanish speaker. Trosk volunteered to do this over our internal slack, but any additional eyes are always welcome.

Localisation files:
https://github.com/ppy/osu-web/tree/2c0cc235b29a4823d35176895890da213744153d/resources/lang/es

**Comment by LiquidPL** [comment]
FYT, I discussed with peppy about setting up a crowdsourced translation system, so we might use that in the future, but I'm not sure what is the progress on that.

**Comment by nekodex** [comment]
The quality of a lot of the translations are not where we'd like them to be yet. If you have a better translation or specific problems with the translations, please make a pull request with the relevant changes.
