### ISSUE TITLE
Text decoration on image links in discussion history

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#7782]
Not a big problem really, just kinda odd to have that short pink line on hovers, which comes from the anchors containing the images, which doesnt match the image size 
![grafik](https://user-images.githubusercontent.com/35633093/123127281-69a4ab80-d44a-11eb-86c7-c1fde1003abf.png)
![grafik](https://user-images.githubusercontent.com/35633093/123127306-6f9a8c80-d44a-11eb-9d8e-cd17a83809dd.png)

**Comment by notbakaneko** [comment]
Are you using any extensions or user stylesheets?

**Comment by RockRoller01** [comment]
Yes I am but I have no stylesheets that should affect this..

Went and tried to confirm and now its gone.. guess my browser decided to do a funny? 🤷

**Comment by nanaya** [comment]
And that's why you should post the link when reporting problem. It's a problem on this page https://osu.ppy.sh/beatmapsets/discussions/posts

**Comment by RockRoller01** [comment]
As you can see by the pink coloring of my screenshot, this happened on user profiles modding tab to me, where I now wasnt able to reproduce it (till now I didnt even know the page you linked existed). To be exact, it was on this profile (tho I think I als otried it on others?) https://osu.ppy.sh/users/2474015/modding

**Comment by nanaya** [comment]
It can't be that page unless you have stylesheet which modifies that section as the distance between reply icon and the post is way further apart for that page.

**Comment by nanaya** [comment]
Actually the linked page I linked is just a general version of https://osu.ppy.sh/users/2474015/modding/posts which probably what you were on
