### ISSUE TITLE
OD filter doesn't work

### ISSUE THREAD

**Issue by Molly-Sandera** [ppy/osu-web#7783]
![Screenshot_2021-06-23-20-23-50-217_com android chrome](https://user-images.githubusercontent.com/63004223/123133751-1e49c780-d461-11eb-936c-b0f9e37e5e0a.jpg)
![Screenshot_2021-06-23-20-23-58-972_com android chrome](https://user-images.githubusercontent.com/63004223/123133770-24d83f00-d461-11eb-8930-5967e448bc4a.jpg)
![Screenshot_2021-06-23-20-24-05-620_com android chrome](https://user-images.githubusercontent.com/63004223/123133784-273a9900-d461-11eb-8ff6-1de06502cb5a.jpg)
Web map filters in general works,but not this specific one, unless I'm missing the specific keyword?

**Comment by peppy** [comment]
We cannot work with screenshots.
Please provide actual links or solid details along with your report (ie. show a specific search criteria returning an incorrect beatmap, via the URL).

**Comment by Molly-Sandera** [comment]
Sorry about the screenshots, i will now send actual links. This should show that instead of looking for maps with accuracy of certain criteria, it returns the maps with the keywords OD and the number specified on them. https://osu.ppy.sh/beatmapsets?q=Ar%3E8%20od%3C6
https://osu.ppy.sh/beatmapsets?q=Ar%3E8%20od%3C7
https://osu.ppy.sh/beatmapsets?q=Ar%3E8%20od%3C8
https://osu.ppy.sh/beatmapsets?q=Cs%3E6%20od%3C8

**Comment by peppy** [comment]
Right. So we may want to exclude keywords that are consumed as filter criteria from the full text search altogether.

**Comment by nanaya** [comment]
the syntax isn't even right (missing `:` or `=`). And `od` isn't supported at the moment.

**Comment by Molly-Sandera** [comment]
> Right. So we may want to exclude keywords that are consumed as filter criteria from the full text search altogether.

And do it's job as a filter, which is the main issue, as it's not doing that at the moment

**Comment by Molly-Sandera** [comment]
> ~the syntax isn't even right (missing `:` or `=`).~ nvm I remembered it wrong. `od` isn't supported at the moment.

I see. The article announcing the web filters mentioned od, though, unless I'm remembering it wrong

**Comment by nanaya** [comment]
The initial implementation was referencing lazer which doesn't seem to have it either. Also I don't know where that attribute is stored (if at all).

**Comment by Molly-Sandera** [comment]
> The initial implementation was referencing lazer which doesn't seem to have it either. Also I don't know where that attribute is stored (if at all).

I figured it would be based on lazer, which is why i mentioned if the name of that attribute is different in web/lazer, as I'm not very familiar with lazer. OD is called Accuracy in Web

**Comment by gagahpangeran** [comment]
It's `diff_overall` in `Beatmap` model.
