### ISSUE TITLE
api docs takes a significant amount of time to load

### ISSUE THREAD

**Issue by tybug** [ppy/osu-web#7785]
Just visit https://osu.ppy.sh/docs/index.html and notice that the sidebar on the left doesn't load for 5-10 seconds. Potentially more noticeable is visiting an anchored url (https://osu.ppy.sh/docs/index.html#client-credentials-grant) and noticing that the docs don't jump to that anchor for 5-10 seconds.

chrome Version 91.0.4472.114 (Official Build) (x86_64)

discussion on discord: https://discord.com/channels/188630481301012481/188630616286167041/852231762927157300

https://user-images.githubusercontent.com/31628143/123177864-133c6a80-d454-11eb-9946-13d0c7ed8bd1.mov

**Comment by peppy** [comment]
Not sure if this is already being tracked somewhere, but may be resolved via https://github.com/ppy/osu-web/pull/7774, which intends to reduce the size of the sample responses in the documentation (which should help with performance on ceratain browsers).

cc @cl8n

**Comment by cl8n** [comment]
I didn't look into it very far, just noticed that the sample response lengths correlated to initial render time, and documented the longest one to see what would happen. in local testing it did help a significant amount

I'm not very experienced in profiling or optimizing for browser performance so I don't have more specifics than that ¯\\\_(ツ)\_/¯

**Comment by tybug** [comment]
This has been greatly improved in the most recent deploy, no doubt due thanks to #7774 as above. It still takes 2-3 seconds to load but that's at least tolerable compared to before. Will leave the decision on whether to close to others.

**Comment by peppy** [comment]
Let's close this for now. Seems to be much better.
