### ISSUE TITLE
Forum posts should show who deleted it

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#7786]
Comments and beatmapdiscussion already show this.. forum posts probably should as well.

This also would be a step towards replacing quickmod logs

**Comment by gagahpangeran** [comment]
From what I see in [Post Model](https://github.com/ppy/osu-web/blob/a9129e5ea83c4f4e44dceb0ebf0b67b8723871d4/app/Models/Forum/Post.php), there was never any record of forum post's deleter. So, if this is implemented, the past deleted post would have no information about who deleted it.

**Comment by venix12** [comment]
They are logged along with other forum moderation events in the [Logs](https://github.com/ppy/osu-web/blob/master/app/Models/Log.php). Considering how the whole phpbb workflow is structured it would possibly make sense to add ability to display the forum post logs for the mods? (aka quickmod logs but on the new website)

**Comment by RockRoller01** [comment]
Quickmod (at least currently) doesnt show which comment was deleted tho, not to mention it would be an extra page to open and cross reference when you want to check something.

**Comment by gagahpangeran** [comment]
> They are logged along with other forum moderation events in the [Logs](https://github.com/ppy/osu-web/blob/master/app/Models/Log.php). Considering how the whole phpbb workflow is structured it would possibly make sense to add ability to display the forum post logs for the mods instead? (aka quickmod logs but on the new website)

Actually this logs are viewable in admin page (and maybe accessible for admin user only, idk).

This is some example of this logs page in my local osu-web.

![Screenshot from 2021-06-24 10-36-37](https://user-images.githubusercontent.com/4964985/123199351-e716fd00-d4d8-11eb-9d49-43c304b451a7.png)

**Comment by venix12** [comment]
Yes, this is admin-only.

**Comment by venix12** [comment]
For what it's worth, I'm willing to work on importing the quickmod thing to the new website if deemed a way to go.

**Comment by RockRoller01** [comment]
I thnk that requires an answer from @peppy
