### ISSUE TITLE
Google links to random language version of wiki articles

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#7787]
When I search for a wiki page via google to share with someone, I end up sharing some stupid localisation version of it.

Not sure was the best fix for this is but it needs to be addressed somehow.

![20210624 103623 (Safari app)](https://user-images.githubusercontent.com/191335/123189065-1b3dee00-d4d8-11eb-8d38-0d3a0513a63b.gif)

**Comment by nanaya** [comment]
Seems useful

https://developers.google.com/search/docs/advanced/crawling/localized-versions
