### ISSUE TITLE
Add more information under Beatmapset Object in API

### ISSUE THREAD

**Issue by Ztumpie905509** [ppy/osu-web#7794]
Currently it only allow searching for one specific beatmap by `GET /beatmaps/{beatmap}` , while we cannot obtain any other information about other difficulties in the set.

Maybe adding an array of `beatmapID` of the other diff under the `Beatmapset` object can help developers to also obtain information of different difficulties under the same set.

**Comment by cl8n** [comment]
seems like you're searching for a beatmapset rather than a single beatmap. use `/beatmapsets/{beatmapset ID}`, or if you only have a beatmap ID, `/beatmapsets/lookup?beatmap_id={beatmap ID}`

**Comment by tybug** [comment]
Will `/beatmapsets/lookup?beatmap_id={beatmap ID}` give us what we want here though? It still returns a `Beatmap` object with its beatmapset attribute having no beatmaps (that is, `beatmap.beatmapset.beatmap` is null). So I'm not sure how you could retrieve other difficulties of the beatmapset using /lookup when you only have the beatmap id.

**Comment by cl8n** [comment]
> It still returns a `Beatmap` object with its beatmapset attribute having no beatmaps

it returns Beatmapset (this is for beatmap***set*** lookup route)

**Comment by tybug** [comment]
Aha, right. Forgot /beatmapsets/lookup existed.
