### ISSUE TITLE
Preview Point Not Setting

### ISSUE THREAD

**Issue by WestOtterman** [ppy/osu-web#7810]
Problem details: I recently posted my first beatmap, but once I check the page after submitting it I couldn’t hear the audio on the website. When I press the button to hear a sample of the song nothing plays, but if I actually download and play the map it works just fine. I've tried setting the preview point and updating the map multiple times, but nothing is seeming to work. How can I fix this?
Beatmap: https://osu.ppy.sh/beatmapsets/1505411#mania/3083699

**Comment by peppy** [comment]
![20210629 175901 (Finder)](https://user-images.githubusercontent.com/191335/123768872-b03f4d80-d903-11eb-8b4b-4ba683166120.png)

Your mp3 is broken in some way. Please fix it or seek help on the forum.

**Comment by WestOtterman** [comment]
> ![20210629 175901 (Finder)](https://user-images.githubusercontent.com/191335/123768872-b03f4d80-d903-11eb-8b4b-4ba683166120.png)
> 
> Your mp3 is broken in some way. Please fix it or seek help on the forum.

Ok, I see. Thank you for pointing that out. I've been trying to find a way to fix the audio file, but I can't find a solution to this problem anywhere. Could you point me to a guide?

**Comment by peppy** [comment]
Easiest solution would be to reencode it using any encoder that can read it successfully.

**Comment by nanaya** [comment]
that file is aac encoded in mp4 container...
