### ISSUE TITLE
Screenshots not uploading?

### ISSUE THREAD

**Issue by PaperSaysNo** [ppy/osu-web#7812]
when i do shift+f12 it just gives me a white page that doesn't load

![](https://cdn.discordapp.com/attachments/381986789252136960/859518213132910612/unknown.png)

**Comment by cl8n** [comment]
I can reproduce this by logging in and immediately taking screenshot before login finishes

**Comment by peppy** [comment]
Currently fixing this one, should be working again within 30 minutes or so.

**Comment by peppy** [comment]
Should be working again. Thanks for the report!
