### ISSUE TITLE
The ability to self-lock one's own account

### ISSUE THREAD

**Issue by RenovaDeus** [ppy/osu-web#7813]
Inspired somewhat haphazardly by [this Reddit thread here](https://www.reddit.com/r/osugame/comments/oa908a/my_take_on_the_restriction_system/).

I saw the thread this morning, and there doesn't seem to have been a GitHub feature request suggesting it yet, so I thought I'd make one. Also, this expands to a wee bit more than just `osu-web`, but I figured `osu-web` is (probably) the most appropriate repo to make this request in.

osu! has obeyed the GDPR laws of the European Union where need be, but one of the semi-relevant things I've heard over the years (there is *some* clamor for it) is the ability for people to voluntarily delete their account in the same manner as people from the EU. In other words, they would prefer EU law be universally applied to all users of the platform, regardless of whether their native country is actually *in* the European Union.

While I'm not a huge fan of this (I think to be frank that too many people are overly trigger-happy, and would not be able to judge the ramifications of deleting their own account adequately on a dime), I do believe there is a middle ground in everything that can be discussed. In this scenario, that translates to individuals locking their own accounts via the on-site profile options (alternatively, it could also be requested via emailing osu@ppy.sh or support@ppy.sh; whichever is preferable).

The most straightforward way to do this would be to create a new "account state" (I forget what it's called, it's an ID number in SQL databases and I'm not a programmer) that would effectively take someone off of the global PP rankings, but keep their scores public on maps and have their profile be publicly visible (with a grey lock or some symbol next to their name indicating the account is locked). I'm entirely unaware if this is valid in this use-case, considering how complex osu! is from frontend to backend, but there are surely other ways this request can be brought to life.

Is the size of this request within reason?

**Comment by venix12** [comment]
Well according to [the wiki](https://osu.ppy.sh/wiki/en/Help_Centre/Account#can-i-delete-my-account?), you don't need to be an EU citizen to request an account deletion?
![](https://i.imgur.com/Pds07vO.png)

**Comment by Sylurial** [comment]
As a disclaimer, I have not read GDPR-related content on the wiki for many revisions. Perhaps it's changed since I last viewed it, but I still do think that having a "midway point" (letting users disable their account rather than delete it on-the-fly) is something to approach, for several reasons (the previously mentioned trigger-happiness/lack of broader understanding, curbing addiction to the game where needed from person to person, avoiding having other people login to your account to change your password to something you don't know, which would be classified as multi-accounting, etc).

Obviously there would need to be a cooldown before you could email Support again requesting access to the account you would be disabling (at present, 45 days, or half of a 3 month cooldown, seems like a good place to start).

**Comment by peppy** [comment]
We've considered this in the past but the demand is low and as such it's a low priority.

**Comment by Blooshing** [comment]
Couldn't this be closed or at least circumvented through having the user reset their account's password through the "forgot password" or "change password" as is described in the wiki:
<img width="750" alt="Screen Shot 2022-08-17 at 11 12 35 AM" src="https://user-images.githubusercontent.com/90729492/185176605-c1dd3c37-4fdd-4ffc-b08e-7597a78464f1.png">

not really sure having a button/option without the many steps to actually lock the account would be beneficial or even desired as many young players may not know the full extent of what they are asking and could just be more hassle than is now.

**Comment by peppy** [comment]
Yep let's close for now.

For anyone wanting the instructions that may arrive at this issue, please refer to https://osu.ppy.sh/wiki/en/Help_centre/Account#account-lock
