### ISSUE TITLE
Mode tags on groups suffer in readability

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#7826]
Due to low size and thick lines for their size, the mode icons used for some usergroups (BN, NAT, Loved) are very difficult to read. It can be very difficult to tell modes apart at a glance.

![image](https://user-images.githubusercontent.com/33286824/124313575-0946f580-db3f-11eb-8fc7-31a9a1e266b0.png)
![image](https://user-images.githubusercontent.com/33286824/124313586-0e0ba980-db3f-11eb-8ea4-5294eef36259.png)
![image](https://user-images.githubusercontent.com/33286824/124313600-1237c700-db3f-11eb-8fc0-f2751f4d896f.png)
![image](https://user-images.githubusercontent.com/33286824/124313627-19f76b80-db3f-11eb-86e3-a557c1ed3555.png)

catch is the least affected by this issue, but taiko can be difficult to tell apart from mania or osu! as the lines are so thick compared to the size it is hard to see any details.

I use a 1920x1080 monitor with browser set to window size

you have to zoom in a LOT for the details of the mode badges to be clearer though

![image](https://user-images.githubusercontent.com/33286824/124313898-8a05f180-db3f-11eb-9682-0894d923f986.png)
![image](https://user-images.githubusercontent.com/33286824/124313914-8ffbd280-db3f-11eb-98db-ea4b81c05051.png)

It looks like the font weight for these badges is set very high for the group label to be bold, but this is negatively affecting the mode icons. If possible, the font weight should be set lower for just the mode icons and set similarly to where they're used in other parts of the website, such as beatmap cards where they are much more readable.

**Comment by peppy** [comment]
@NoffyNoffeh how are things looking now? the font has since been changed to a bolder weighting, so if that's enough to resolve this for you then the issue can be closed.

**Comment by NoffyNoffeh** [comment]
Looks good.
