### ISSUE TITLE
The ranking status in preview should show the ranking status of the ruleset

### ISSUE THREAD

**Issue by PercyDan54** [ppy/osu-web#7832]
![image](https://user-images.githubusercontent.com/50285552/124531335-dd7a8700-de40-11eb-951b-26661f2977d1.png)
As you can see, I'm filtering with "Has leaderboard" and ruleset osu!
And this map shows as loved

But when you click it you find out the osu! beatmap is WIP
The loved one is in osu!catch, which we probably don't want to see
![image](https://user-images.githubusercontent.com/50285552/124531432-14e93380-de41-11eb-9625-768f7412dea3.png)
![image](https://user-images.githubusercontent.com/50285552/124531448-1ca8d800-de41-11eb-990f-04d3a9093c3e.png)

https://osu.ppy.sh/beatmapsets/89139#osu/361955

**Comment by peppy** [comment]
This is a very rare case, so unless this can be done with negligible overhead I'd just let it be.

**Comment by nanaya** [comment]
I haven't tested it but querying by difficulty status instead of beatmap status should be possible assuming they're correctly reindexed ([relevant function](https://github.com/ppy/osu-web/blob/8354000fa81f4d3421a187f7d7e90e6b5163c3cc/app/Libraries/Search/BeatmapsetSearch.php#L286)).
