### ISSUE TITLE
Nickname length expand offer

### ISSUE THREAD

**Issue by danilyer228** [ppy/osu-web#7839]
https://github.com/ppy/osu-web/blob/9de00a0b874c56893d98261d558d78d76259d81b/app/Libraries/UsernameValidation.php#L59

Can we expand it to 16-20? I don't see this as a problem to do that.

![image](https://user-images.githubusercontent.com/33658320/124760574-8dcbb680-df39-11eb-9256-4c131c2b9b33.png)

**Comment by peppy** [comment]
The length is intentionally limited to allow usernames to display in the game and web.

If it wasn't, you will become DeliciousPancak... anyway.
