### ISSUE TITLE
Approved beatmap shows wrong key count for mania convert

### ISSUE THREAD

**Issue by GrilledCheeese** [ppy/osu-web#7846]
https://osu.ppy.sh/beatmapsets/4651#mania/24733
Beatmap shows as 5 key on the website:
![image](https://user-images.githubusercontent.com/34809632/125003846-6ae3f400-e058-11eb-8f59-7c5df4e36a82.png)
But is actually a 6 key map:
![image](https://user-images.githubusercontent.com/34809632/125003767-3bcd8280-e058-11eb-80ba-27f988160904.png)

**Comment by peppy** [comment]
If this is only occurring on that beatmap, it's likely to do with very old beatmaps using a different algorithm to decide how it converts. Can you confirm this isn't a common issue but one you found only on this beatmap?

**Comment by GrilledCheeese** [comment]
I found 8 others after a brief search using status=a keys=6 in-game all showing 5k on the website, but are 6k in-game:
https://osu.ppy.sh/beatmapsets/20237#mania/72402
https://osu.ppy.sh/beatmapsets/972#mania/9007
https://osu.ppy.sh/beatmapsets/7828#mania/32997
https://osu.ppy.sh/beatmapsets/4081#mania/23933
https://osu.ppy.sh/beatmapsets/26932#mania/94945
https://osu.ppy.sh/beatmapsets/26932#mania/94942
https://osu.ppy.sh/beatmapsets/26932#mania/90785
https://osu.ppy.sh/beatmapsets/26769#mania/91156

**Comment by smoogipoo** [comment]
Circling back to this, I believe this is an osu-web issue and I missed the point being converted beatmaps.

Mania has some logic for converting circle size to number of columns: https://github.com/ppy/osu/blob/6bbc23c831cd73bf126b31edb0bb4fa729f947d1/osu.Game.Rulesets.Mania/Beatmaps/ManiaBeatmapConverter.cs#L59-L69

I think it's easiest to fix this directly in osu-web - counts can be taken from the `osu_beatmaps` table. Note that this only applies to converted beatmaps - for osu!mania beatmaps just read the CS directly as it's currently done.
