### ISSUE TITLE
Differentiate between finished scores and unfinished scores in the "recent plays" section when submitting a play from lazer

### ISSUE THREAD

**Issue by minasminas** [ppy/osu-web#7847]
If I play a beatmap and fail or restart the beatmap, the score will still show on the "recent plays" section on my profile.
I wasn't quite sure where to post this, because I don't know if this is an osu-web or a lazer issue. I hope this is the right place for this.

**Comment by frenzibyte** [comment]
Intentional, [that's how osu! works](https://github.com/ppy/osu/issues/13775#issuecomment-873717104).

**Comment by minasminas** [comment]
I know that, Stable also submits scores when not finishing a map (I think). But is it really intended to also show in the recent plays section if not finished? I think it should at least show somehow if the score is a finished one or not, because it seems pretty confusing not knowing that.

Anyway, that is my own opinion and if this is **really** intentional, just ignore this and feel free to close the issue.

**Comment by frenzibyte** [comment]
It should definitely fall within the "recent plays" section, since you *have* played this. Differentiating between finished scores and unfinished scores is another thing that's irrelevant from the OP, but I guess the title can be edited to track that instead.

**Comment by minasminas** [comment]
I somehow get that, I'm just questioning some things about this. Let's say I play a beatmap and there is a very hard section at the beginning, so I restart the map 5-10 times (or more) to pass that section. It just spams the recent plays section with meaningless scores, but if that is something that is wanted from the devs, I just accept it. I might just change the topic of this issue.

**Comment by peppy** [comment]
Should be hidden, is missing `passed` flag support for the temporary legacy insertion.

Will depend on https://github.com/ppy/osu-web/pull/7809.

**Comment by minasminas** [comment]
Welp, should have just searched for 3 more Minutes and could have found that myself. Thanks for clarification.
