### ISSUE TITLE
Missing Pending Beatmaps and Graveyarded Beatmaps on user's profile

### ISSUE THREAD

**Issue by shortthu** [ppy/osu-web#785]
![image](https://cloud.githubusercontent.com/assets/22362633/19507813/6be2958a-95ff-11e6-87a0-8d6fd2e41667.png)
like this image, I have 2 pending beatmaps but it doesn't showed

**Comment by nekodex** [comment]
We'd want to add "Pending Beatmaps" grouped with "Ranked & Approved" under a new "My/User's Beatmaps" section (and have "Favourite Beatmaps" by itself in a section).

Graveyarded beatmaps shouldn't be displayed as prominently (they have essentially been abandoned after all). We'll need to give this some further design thought, but we can just display them alongside pending/ranked&approved for now.
