### ISSUE TITLE
Rank graph occasionally doesn't display, no dim when opening a menu in Mobile web

### ISSUE THREAD

**Issue by wowcake** [ppy/osu-web#7859]
Recently today, there's an issue of rank graph sometimes showing, and sometimes not. Alongside with there is no dim applied when opening the menu/searching

Could confirm this happening with other people aswell.

(for reference) Graph not showing:
![IMG_20210713_203612](https://user-images.githubusercontent.com/76740201/125462572-f62d6fb6-2b0f-4126-9a92-0324e826b9a8.jpg)
No dim in the background:
![IMG_20210713_203620](https://user-images.githubusercontent.com/76740201/125462589-015deeaf-e583-40ec-b10d-085c6c0c1be6.jpg)

**Comment by peppy** [comment]
Fixes for both of these issues are currently being deployed.
