### ISSUE TITLE
Allow usage of chat updates endpoint

### ISSUE THREAD

**Issue by venix12** [ppy/osu-web#7862]
Would be nice to be able to use it (possibly chat bots only?) instead of using some tricky message tracking solutions. Would also make tracking chat much more practical (see, for example, currently modreation tools index ingested messages by plain username which can be problematic in many cases).

**Comment by peppy** [comment]
The plan is that chat would be moved to websockets before having any more users hitting the existing endpoint. It's the largest performance drain on the infrastructure right now.

I'm not sure on the state of that effort.
