### ISSUE TITLE
[Feature request] Hide soft keyboard when pressing enter in search fields

### ISSUE THREAD

**Issue by Susko3** [ppy/osu-web#7866]
This is mostly a feature request for the mobile website, but is equally as applicable for desktop users on touchscreen devices using a on-screen keyboard.

When searching for beatmaps on the mobile website, it's annoying to have to manually close the soft keyboard by using the Android back gesture. My expectation is that the keyboard should close when I press enter, and in every other app and website, pressing enter closes it. But on search boxes on osu!web, this doesn't happen. The keyboard stays open after pressing enter.

Tested search boxes include:
- the search overlay accessed by the search icon
- the one on https://osu.ppy.sh/home/search
- the one on https://osu.ppy.sh/beatmapsets

I suggest to close the soft keyboard when pressing the enter key in those search boxes. (If this behavior is unwanted on desktop platforms, I'm okay with it being only on the mobile web.)

[This example](https://codepen.io/Siphalor/pen/JWdqyj) works fine on my Android device on both Chrome and Firefox.

(I don't have the required knowledge on how to implement this on osu-web, so that's why I'm making a feature request.)

**Comment by peppy** [comment]
Can confirm that this also happens on iOS. We should probably be removing focus from the search box on "enter" press to resolve this.
