### ISSUE TITLE
Empty (non-null) passwords return incorrect has_password value

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-web#7890]
This method should also return `false` if `password` is an empty (but non-null) string:
https://github.com/ppy/osu-web/blob/b7897d88451041666b7430f12817f1501078c8fc/app/Transformers/Multiplayer/RoomTransformer.php#L37

**Comment by nanaya** [comment]
Is it being set separately from osu-web? I think osu-web side turn all empty strings for password into null.

**Comment by smoogipoo** [comment]
Yeah, this would be set by osu-server-spectator. So we should be setting it null for this case? I can work with that.

**Comment by peppy** [comment]
I think it's best to handle this here, as an empty password doesn't make sense no matter how you think about it.
