### ISSUE TITLE
Error when jumping from general search to beatmaps search

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-web#7895]
Re-produce step:
1. Go to [general search page](https://osu.ppy.sh/home/search) or click search button on the top navbar.
2. Search with any keywords that have result in "Beatmap" tab. e.g. `abyss`.
3. Click on "Beatmap" tab or "More Beatmap search result".
4. Error: `Cursor parameters do not match sort parameters.`

**Comment by notbakaneko** [comment]
This should be fixed when #7896 is deployed
