### ISSUE TITLE
Error while searching for a beatmap

### ISSUE THREAD

**Issue by goebeldamian** [ppy/osu-web#7900]
I've encountered the following error:
![search error](https://user-images.githubusercontent.com/45130534/126355677-90ad0eb8-3e2d-4e66-bb4c-d9a92c0477eb.gif)

Sometimes it doesn't search for the desired beatmaps as well (not like in the GIF above).

**Comment by kj415j45** [comment]
Duplicated with #7895 .

**Comment by notbakaneko** [comment]
This should be fixed when #7896 is deployed
