### ISSUE TITLE
Circular outline does not match with given grade

### ISSUE THREAD

**Issue by mobilex1122** [ppy/osu-web#7911]
Some maps have different grade shown with the outline than with the letter itself. I found it in Something Good '08 (Radio Edit) by Utah Saints. https://osu.ppy.sh/beatmapsets/456463#osu/978213

![osubug001](https://user-images.githubusercontent.com/60009551/126626531-f5c1b3fa-2bb1-4f55-a454-61601ffbbb9e.png)

**Comment by gagahpangeran** [comment]
See #6047

**Comment by mobilex1122** [comment]
ou I see. I'm sorry.
