### ISSUE TITLE
Any new languages being added soon over at Crowdin? 

### ISSUE THREAD

**Issue by saieeshb** [ppy/osu-web#7916]
Hello, I would like to ask if there are more languages being added for localisation over at Crowdin.

I would love to translate into Hindi, and Telugu.

Thank you!

**Comment by peppy** [comment]
I can most definitely add these languages, but do note that we don't add languages to the site itself (ie. actually deploying the translations) until they are close to 100% complete. As there hasn't been a demand for either of these languages in the last 10+ years, I can't guarantee there will be others to help you or review the translations, so it's debatable whether it's worth the effort.

But if you're adamant about wanting to give it a shot then I can definitely add the languages and see how things go from there. Please confirm intentions and I'll look into it.

**Comment by saieeshb** [comment]
I see, since there isn't any demand, I would rather spend this time learn learning code to help contribute to the lazer project. Thanks for the notice peppy. 👍
