### ISSUE TITLE
osu!web chat in Android refused to scroll down when typing.

### ISSUE THREAD

**Issue by Aikyuu-Chan** [ppy/osu-web#7918]
https://user-images.githubusercontent.com/79167465/126791802-4b99f71f-c04a-48a6-957b-b0dfb16d0260.mp4

**Comment by gagahpangeran** [comment]
Looks like this also happen in desktop.

![Screenshot from 2021-08-02 14-58-09](https://user-images.githubusercontent.com/4964985/127825107-58b65d04-651b-4e09-ac30-c796a899ddbe.png)

Simple refresh on the chat page fixes this.

![Screenshot from 2021-08-02 14-58-25](https://user-images.githubusercontent.com/4964985/127825172-dc7c07b4-e74d-4903-8ea8-551e5aef0d8c.png)

**Comment by notbakaneko** [comment]
This problem appears specific to Firefox
