### ISSUE TITLE
Country name incorrect on website

### ISSUE THREAD

**Issue by oLagger** [ppy/osu-web#7919]
Greetings, my osu! username is [Fouad](https://osu.ppy.sh/users/10190936/osu)
My [country](https://osu.ppy.sh/rankings/osu/performance?country=PS) is labelled as "Palestine, state of" on the osu! website (specifically on players' profiles) which isn't really correct.
![image](https://user-images.githubusercontent.com/41295683/126832607-410dcd7f-0dbe-4d49-8814-ac05d51a5a3b.png)

As the osu! Palestinian community we request to change the name "Palestine, state of" to either one of these choices:

- "Palestine" (preferred)
- "State of Palestine"

If this kind of change is even possible, please notify me with any further requirements that I would have to do from my end (or from the rest of the players in the country)

Thank you very kindly

**Comment by zeusminus** [comment]
osu!web follows ISO-3166 standards for country naming, [according to which](https://www.iso.org/obp/ui/#iso:code:3166:PS) Palestine is represented as "Palestine, State of", hence your country was labelled that way.

Personally speaking, I would also prefer "Palestine" or "State of Palestine" over the other, but I imagine we would be required to change the country naming standards altogether. I'm not sure if there had been exceptions to the said standards, either, but I haven't encountered any, so the name's most likely to stay.

**Comment by saieeshb** [comment]
Do we only use the "Short name, lower case"? Because it also shows the full name as "the State of Palestine" So I'm confused if we can't use the full name.
![image](https://user-images.githubusercontent.com/66863579/126858907-4a749b29-e722-44ef-a341-45ae2a096399.png)

**Comment by peppy** [comment]
I'm not against changing this, but if we do so we should also be changing all the other similar instances:

Tanzania, United Republic of 
Congo, The Democratic Republic of the
Micronesia, Federated States of
Iran, Islamic Republic of
Korea, Democratic People's Republic of

**Comment by saieeshb** [comment]
Yes, I agree. It would make more sense to change all the instances to keep things uniform throughout the website.

**Comment by peppy** [comment]
I've updated all of the above country names to reverse the display order.

**Comment by oLagger** [comment]
Thank you
