### ISSUE TITLE
Yarn installation failing during vagrant provisioning

### ISSUE THREAD

**Issue by ivan94** [ppy/osu-web#792]
When I tried to set up my vagrant machine, during the provision while executing the build.sh script, npm failed installing yarn, due to lack of permisisions. Adding sudo to the command seemed to solved the issue.

Is this a known issue? 

I'm using virtualbox if that have any relevance.

**Comment by Mathisca** [comment]
I have the same issue, this is the error log : http://pastebin.com/RbzxdDDy

**Comment by nanaya** [comment]
Fixed by #818.
