### ISSUE TITLE
Uploading a map from the stable client breaks the "[profile]" BBCode tag

### ISSUE THREAD

**Issue by tel3** [ppy/osu-web#7920]
Hello,

First time opening an issue, so excuse me if I expressed myself badly.

Symptoms: uploading the map from the client breaks the "[profile]" BBCode tag, forcing to re-edit the description of the map from the site. After editing the description on the website everything goes back to normal, but considering that I have to edit the description a bit, it's not really a one-click fix. The rest of the tags were unaffected. In the meantime I'll use the proper [url] tag, but I think this is something that is worth bringing up, maybe some other tags are also a bit broken in a similar way when uploading the map from the client.

The description code for reference:

`[heading]Our Collab with [profile=597957]riffy[/profile][/heading]
[notice][list]
[*] [img]https://i.ppy.sh/0483e62636e2df983031f1020036ed7829bff61b/68747470733a2f2f6f73752e7070792e73682f77696b692f696d616765732f7368617265642f646966662f656173792d6f2e706e67[/img] Our Soft Party by [profile=6684556]Myahkey[/profile] and [profile=597957]riffy[/profile] (WIP)
[*] [img]https://i.ppy.sh/d4261c141ed067af961d4702981d66f6d9f3cab5/68747470733a2f2f6f73752e7070792e73682f77696b692f696d616765732f7368617265642f646966662f6e6f726d616c2d6f2e706e67[/img] Our Average Party by [profile=6684556]Myahkey[/profile] and [profile=597957]riffy[/profile] (WIP)
[*] [img]https://i.ppy.sh/0abeecca5e337a64ae8511bddbe73c2c3a305a04/68747470733a2f2f6f73752e7070792e73682f77696b692f696d616765732f7368617265642f646966662f686172642d6f2e706e67[/img] Our Hard Party by [profile=6684556]Myahkey[/profile] and [profile=597957]riffy[/profile] (WIP)
[*] [img]https://i.ppy.sh/5025b33c13836974b62eb6f7895ea749ac8586dc/68747470733a2f2f6f73752e7070792e73682f77696b692f696d616765732f7368617265642f646966662f696e73616e652d6f2e706e67[/img] Our Insane Party by [profile=6684556]Myahkey[/profile] and [profile=597957]riffy[/profile] (WIP)
[*] [img]https://i.ppy.sh/18f822ec64303d554c9dcb2d39cd251a7cf3e76c/68747470733a2f2f6f73752e7070792e73682f77696b692f696d616765732f7368617265642f646966662f6578706572742d6f2e706e67[/img] Our Communist Party by [profile=6684556]Myahkey[/profile] and [profile=597957]riffy[/profile][/list][/notice]
[list]
[*]Hitsounds by [profile=6684556]Myahkey[/profile]
[*]BG by [url=https://everythingburns.com]Tom Burns[/url]
[/list]`

The mapset for reference: https://osu.ppy.sh/beatmapsets/1529472#osu/3128581

Tested on: latest osu!stable, latest Firefox and latest Edge. 

Also sorry for accidentally closing the issue, not much experience working with issues on GitHub.

**Comment by NoffyNoffeh** [comment]
Duplicate of https://github.com/ppy/osu-web/issues/7051

**Comment by tel3** [comment]
Couldn't find it via search, so I'm closing this then, thanks!
