### ISSUE TITLE
Missing rate change info for recent Doubletime/Halftime scores

### ISSUE THREAD

**Issue by crownys** [ppy/osu-web#7921]
In lazer, rate changes can be viewed by hovering over the mods:
![explorer_idgiIWgrv3](https://user-images.githubusercontent.com/87690762/126891417-dd438cdb-2c81-41af-bfe4-99118041ba8d.png)

This is missing from the website. I play a lot of modified doubletime/halftime and many times it looks like I am playing maps on doubletime far above my skill level - adding this to the website could potentially clear up any confusion to random onlookers. Having some sort of visual cue outside of the mouseover menu that the rates have been modified could also help.

**Comment by peppy** [comment]
Being tracked via https://github.com/ppy/osu-web/issues/7521.
