### ISSUE TITLE
beatmapset event page in Dutch translation doesn't substitute links properly

### ISSUE THREAD

**Issue by eenpersoon64** [ppy/osu-web#7927]
in Dutch translation, some places where there should be a link to the relevant discussion post/user instead show "discussie" and "gebruiker" respectively (which fyi are correct translations of "discussion" and "user" respectively as well)

using https://osu.ppy.sh/beatmapsets/1242733/discussion/-/events as reference:
underlined some parts where the substitution is broken. nomination events seem to work fine though, even after the addition of the (osu!) mode marker thing
![image](https://user-images.githubusercontent.com/37511342/127112554-ab4162ac-a7cd-4eda-bb36-24307c47fa44.png)

comparison image English:
![image](https://user-images.githubusercontent.com/37511342/127112692-f465f6f1-8161-4313-a3b5-439b96de21fd.png)

**Comment by nanaya** [comment]
Whoever did the translation missed this "QA Issues" part

![](https://s.myconan.net/2021-07/chrome_2021-07-27_16-25-11.png)

**Comment by peppy** [comment]
@eenpersoon64 as mentioned, this needs a fix on the crowdin side. you can find information on how to contribute a fix in the project readme.
