### ISSUE TITLE
Issues with new twemoji sourced country flags

### ISSUE THREAD

**Issue by Kotoki1337** [ppy/osu-web#7928]
the Switzerland and Nepal are not normal size in twemoji
![image](https://user-images.githubusercontent.com/35394151/127120123-9a2398d5-32cb-4c09-ac1e-d8d53b6720d9.png)
![image](https://user-images.githubusercontent.com/35394151/127120133-ececd0ec-19bf-440d-9dd4-8183a04f8242.png)

And looks some regions have no flag in twemoji
![image](https://user-images.githubusercontent.com/35394151/127121189-23b219c9-f11d-428c-a31c-8b06009f3c2a.png)
![image](https://user-images.githubusercontent.com/35394151/127121239-ab30a83a-583f-435c-9f27-af2632d5f455.png)

Maybe need a little modification to keep it consistent?

<details>
  <summary>Resolved</summary>

- #7929
    twemoji's flags don't seem to match the current size resulting in some countries' flags being cutted

    ![image](https://user-images.githubusercontent.com/35394151/127119251-34d6f0d2-1334-45fc-ab18-a300be09f965.png)
    ![image](https://user-images.githubusercontent.com/35394151/127119262-53cb4f7d-014b-4845-bfa8-c98ffde3eb31.png)
    ![image](https://user-images.githubusercontent.com/35394151/127119943-aaef07d9-7b30-48ee-969a-44e51438a19b.png)![image](https://user-images.githubusercontent.com/35394151/127119764-eb9196fd-2c91-4a53-84d0-a45b2c6a6ef9.png)

</details>

**Comment by Kotoki1337** [comment]
Btw the Switzerland and Nepal are not normal size in twemoji
![image](https://user-images.githubusercontent.com/35394151/127120123-9a2398d5-32cb-4c09-ac1e-d8d53b6720d9.png)
![image](https://user-images.githubusercontent.com/35394151/127120133-ececd0ec-19bf-440d-9dd4-8183a04f8242.png)

Maybe need a little modification to keep it consistent?

**Comment by Kotoki1337** [comment]
And looks some regions have no flag, mixing with old designs to solve this issue?
![image](https://user-images.githubusercontent.com/35394151/127121189-23b219c9-f11d-428c-a31c-8b06009f3c2a.png)
![image](https://user-images.githubusercontent.com/35394151/127121239-ab30a83a-583f-435c-9f27-af2632d5f455.png)

**Comment by peppy** [comment]
Please combine all your posts into one post and stop posting additional posts.

**Comment by nanaya** [comment]
I'll add a default fallback flags for missing ones although I don't think APAC has its own flag. Please direct missing country flags issues to https://github.com/twitter/twemoji/issues/265
