### ISSUE TITLE
Qualified Beatmap Problem shows maps that aren't qualified

### ISSUE THREAD

**Issue by mcendu** [ppy/osu-web#7930]
![image](https://user-images.githubusercontent.com/43639171/127148968-4d35aa70-4513-4f48-a275-0be72ffb9291.png)

The map has no history of being qualified at time of posting.

Link to issue: https://osu.ppy.sh/beatmapsets/1444121/discussion/2970635/timeline#/2499838

**Comment by NoffyNoffeh** [comment]
It seems to be flagging whenever a post is reopened on any map. This started in the last 12 hours and already blew up my notifications...
