### ISSUE TITLE
Add triangles to beatmap page buttons.

### ISSUE THREAD

**Issue by Sebola3461** [ppy/osu-web#7934]
Its beautiful and make sense.

its simple too:

### Change
```
.btn-osu-big--beatmapset-header {
    min-width: 120px;
    height: 45px;
    margin: 0 5px 5px 0;
    background-image: url(/assets/images/button.16de7c2c.svg);
    background-size: 175%;
    background-position: 50%;
    transition: cubic-bezier(0, 0, 0.05, 1.18) 150ms;
}

.btn-osu-big--beatmapset-header-square {
    width: 45px;
    height: 45px;
    margin: 0 5px 5px 0;
    background-image: url(/assets/images/button.16de7c2c.svg);
    background-size: 400%;
    background-position: 50%;
    transition: cubic-bezier(0, 0, 0.05, 1.18) 150ms;
}
```

and

```
--bg-hover: hsl(200deg 70% 60%);
```

### Add
```
a.btn-osu-big.btn-osu-big--beatmapset-header:hover {
    background-position-y: 40%;
}
```

## Result
![image](https://user-images.githubusercontent.com/62405013/127220734-ca55aa4d-98db-4865-89e3-d8397339e652.png)

**Comment by gagahpangeran** [comment]
There's already [new design for beatmap page](https://www.figma.com/file/HDSXf4LPPV7hnD5wrWYG4jix/Web%2FBeatmap-Info?node-id=0%3A1) and also [opened PR](https://github.com/ppy/osu-web/pull/7899) that.

**Comment by Sebola3461** [comment]
> There's already [new design for beatmap page](https://www.figma.com/file/HDSXf4LPPV7hnD5wrWYG4jix/Web%2FBeatmap-Info?node-id=0%3A1) and also [opened PR](https://github.com/ppy/osu-web/pull/7899) that.

I hadn't noticed that post of yours, I'll close this issue.
