### ISSUE TITLE
Problem stamp on unqualified map notifying as Qualified Beatmap Problem

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#7942]
Map:
https://osu.ppy.sh/beatmapsets/1513466/discussion/-/timeline#/2505524

This map has never been nominated, but the linked post showed up in notifications as a qualified beatmap problem

![image](https://user-images.githubusercontent.com/33286824/127411260-75a65b59-9543-4124-81eb-57aa29ced567.png)

May be related to https://github.com/ppy/osu-web/issues/7930 ? 

I'm not sure what the exact cause is in this case, since it isn't happening for every problem stamp just this one so far today.

Edit: Another case: https://osu.ppy.sh/beatmapsets/1518112/discussion/-/generalAll#/2505976

**Comment by nanaya** [comment]
I missed that review uses its own logic for sending notification for problem on qualified maps.
