### ISSUE TITLE
Checkboxes sometimes don't load properly

### ISSUE THREAD

**Issue by Magnus-Cosmos** [ppy/osu-web#7952]
In account settings the checkboxes don't load properly (making them unselectable), had to reload the page several times for them to load properly:
![broken checkbox](https://user-images.githubusercontent.com/39173355/127721124-5f17f762-523c-4499-ad2a-9820723014c5.gif)
Tested on chrome and firefox.

**Comment by RockRoller01** [comment]
I recently had this happen as well on the search, but wasnt able to reproduce it and therefore didnt file an issue

**Comment by peppy** [comment]
Did you happen to check your browser's error console when this happens?

**Comment by RockRoller01** [comment]
I did but didn't see anything. Also using firefox (v 90.something)

**Comment by RockRoller01** [comment]
Just went back and tried it again and getting this consistently with no error messages

![image](https://user-images.githubusercontent.com/35633093/127728972-9d9006f5-d830-4006-a802-af73e523720a.png)

Also getting this on e.g. account settings

Tried navigating there as well as opening it directly in a new tab and both things lead to this

**Comment by nanaya** [comment]
it looks like octane persists view variables in some cases ಠ_ಠ reverting back for now
