### ISSUE TITLE
Country rank on score page disappeared

### ISSUE THREAD

**Issue by MaxTechnics** [ppy/osu-web#7957]
Supporter or not, normally you can see the country rank on any /scores page. (Intentional as mentioned in #6213)
However, it is no longer visible, is this an intentional removal? Or a bug.
Example: 
![image](https://user-images.githubusercontent.com/58440941/127788743-80ce6a34-b9c2-4c5a-9711-9369eea300ac.png)

**Comment by venix12** [comment]
seems to be intended as of #7879.

**Comment by peppy** [comment]
As mentioned, this was indeed intended. It may return in the future, but requires significant infrastructure work to happen (and is not a priority currently).
