### ISSUE TITLE
Add new parameter to room table and creation API request

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#7962]
We are expanding osu!(lazer) to offer Team VS next, for multiplayer games. This will only be supported for realtime rooms. In order to allow this to happen, a new parameter should be added to `/rooms POST` endpoint:

`type { playlists, headtohead, teamvs }`

Should also be added to `multiplayer_rooms` as an `enum` type I guess.

Note that we will probably want to reconsider how the existing `category` type is used. I believe the `realtime` setting should not need to exist with this new type enum. It may be that we want to have "spotlighted" realtime rooms in the future, so probably fine to leave it existing for that purpose.

One could alternatively argue that we could add these new types to the existing `category` enum, and if that's deemed as a better direction then it can likely still work.

So either we would end up with option 1:

```csharp
category { normal, spotlight } // realtime is removed either immediately or as a second step
type {playlists, headtohead, teamvs }
```

or option 2:

```csharp
category { normal, spotlight, realtimevs, realtimeteamvs } // not sure about naming
```

This is semi high priority as it's a blocker for making initial game creation work (currently the type is only able to be changed post-creation). @nanaya @notbakaneko @smoogipoo

**Comment by smoogipoo** [comment]
I'd prefer option 1, since option 2 looks weird with both normal and realtimeX members.

**Comment by peppy** [comment]
Also when implementing this, it would be preferrable that a request for `realtime` category should set its type to `headtohead` if not specified (ie. the invalid type combination of "realtime / playlists" should not be allowed). This will allow for backwards compatibility.
