### ISSUE TITLE
Potential issue due to localization file change

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-web#7964]
PR #7937 made some changes on original localization files (en), but did not update the other localization files. As a result, the changes do not reflect in Crowdin.
For example, in Crowdin, [string `layout.menu.beatmaps.index` => "`beatmap listing`" still shows "`listing`" in Simplified Chinese](https://crowdin.com/translate/osu-web/32/en-zhcn#852). (Crowdin's issue maybe?)
![image](https://user-images.githubusercontent.com/18349191/127991325-6574d26f-635e-4a5d-8d73-ba257f215fe4.png)

Besides, there's a [break change](https://github.com/ppy/osu-web/pull/7937/files#diff-4e0c426e5ce208b5d07e3497db6f77beb821c9374c1cda2defc6299c22876302L130-R130) in that PR.
```diff
-            '_' => 'knowledge base',
+            '_' => 'wiki',
```
Though they have a similar meaning, this may lead to confused in some way.

**Comment by nanaya** [comment]
Base files just haven't been updated. The "knowledge base" rename (and others in `page_title`) should have been applied to all translations.

**Comment by peppy** [comment]
I've reuploaded the source strings and it seems to be resolved now, @kj415j45 can you please confirm?

![20210804 122239 (Safari)](https://user-images.githubusercontent.com/191335/128117155-f57ea872-167d-446f-8ec4-44badacf184f.png)

**Comment by kj415j45** [comment]
yep, confirmed that source strings are up-to-date now. but what I'm concerned is that shall we purge current translation?

**Comment by peppy** [comment]
We intentionally did not. I think they can be updated as required.
