### ISSUE TITLE
The upvote button on beatmap info pages is broken

### ISSUE THREAD

**Issue by Nivalyx** [ppy/osu-web#7969]
(dunno how to title the issue properly orz ;~;)

Talked about in #osu-web earlier. The most recent osu-web tag (2021.804.0) seems to broke the upvote button on beatmap info pages, as seen in the following :

![image](https://user-images.githubusercontent.com/36564236/128109811-a285212f-dc16-4a7a-9718-7a558638372c.png)

The issue seems to only be specific to beatmap info pages tho fwiw, as the comment section on other pages (i.e. news/changelog) doesn't seem to be affected.

**Comment by gagahpangeran** [comment]
Probably regressed by #7924 and forgot to change these lines.

https://github.com/ppy/osu-web/blob/aaad1121a8aedcfadc365fb24f46f707f756a77a/resources/assets/coffee/react/_components/comment.coffee#L404-L405
