### ISSUE TITLE
Multiplayer/playlist room indexing requests should return recent participants

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-web#7972]
Flyte's new designs list recent participants in the lounge before the room is selected/entered:
![image](https://user-images.githubusercontent.com/1329837/128186949-ebc94855-fd7e-4915-8176-4bcfa3452b3e.png)

But recent participants are currently only returned in `RoomsController.show()`:
https://github.com/ppy/osu-web/blob/f51a514e911e08b75e31bb1f10179adaa93e5cb9/app/Http/Controllers/Multiplayer/RoomsController.php#L110-L124

And not in `RoomsController.index()`:
https://github.com/ppy/osu-web/blob/f51a514e911e08b75e31bb1f10179adaa93e5cb9/app/Http/Controllers/Multiplayer/RoomsController.php#L29-L34

**Comment by peppy** [comment]
Should also probably take this opportunity to return the total participant count, yeah? It looks like you only need the most recent 8 + a count for the display.

**Comment by smoogipoo** [comment]
Yeah, I agree.

**Comment by nanaya** [comment]
@peppy current response already includes participant count it seems?

**Comment by peppy** [comment]
Had a feeling that was the case

**Comment by smoogipoo** [comment]
Perfect, forgot about that one :D
