### ISSUE TITLE
Giftable name changes

### ISSUE THREAD

**Issue by TicClick** [ppy/osu-web#7975]
https://osu.ppy.sh/store/products/32

to expand, there have been several times when I wished I could supply other person with a name change without sharing my personal details, and I've also seen others struggling with the same issue.

of course there is always a possibility of the other party rejecting the gift (or not using it after, err, unwrapping), but oh well, I guess that's something a benefactor can live with.

**Comment by gagahpangeran** [comment]
Maybe it can be some kind of voucher? (Something like #6130 proposal)

**Comment by peppy** [comment]
I believe this would only be feasible via a gift card system, yeah. Probably fine to track at #6130 (please 👍 the opening post to show your support).
