### ISSUE TITLE
BN List needs to be updated.

### ISSUE THREAD

**Issue by dreammmest** [ppy/osu-web#7976]
The Probationary Beatmap Nominators list needs to be updated for every gamemode in the BN list: https://osu.ppy.sh/wiki/en/People/The_Team/Beatmap_Nominators

**Comment by RockRoller01** [comment]
This list is regularly updated, but this happens manually, so some things may be slightly out of date. If you require an accurate list please refer to the respective usergroup page (which you can get to by clicking on a BNs BN badge)
