### ISSUE TITLE
One single profile's country rating is way too low

### ISSUE THREAD

**Issue by ItsJustSomeDude** [ppy/osu-web#7982]
The country rating listed on osu!web and inside osu!lazer for this profile is way too low.  The global ranking appears right, at around 2,000,000, but it says it is 64 in the United States for osu! and rank 19 in the US for osu!catch.  These are totally incorrect.

The profile in question: [https://osu.ppy.sh/users/24481070](https://osu.ppy.sh/users/24481070)

It shows the same thing if the profile is accessed from Private browsing and not, logged in and not.

The country ranking page does not list the account in the rank that is shown on the profile page.  [https://osu.ppy.sh/rankings/osu/performance](https://osu.ppy.sh/rankings/osu/performance)

I primarily play on lazer, but I think that is mostly unrelated.

(I considered just emailing this in, but while it is an issue with my account, it really seems to be an osu!web bug.  If I should just email the account support address, let me know.)

**Comment by peppy** [comment]
Thanks for the report. This should be resolved now.
