### ISSUE TITLE
Separate user plays history graphs for finished and unfinished plays

### ISSUE THREAD

**Issue by nicolas-sanz** [ppy/osu-web#7987]
When you play a map the moment it starts it counts as a play and it gets recorded but there is no difference in terms of what is a play based on whether you finish the map or not so for example someone retry spamming would accumulate many plays whether they end up even finishing the map or not so it would be useful on your play history starting from when implemented a new separate graph that only counts finished plays. I say only once implemented because I don't think it is possible to somehow gain previous number of plays data due to how it is counted unless every map score achieved is looked at and counted up but this would take a long time to do.

**Comment by peppy** [comment]
Please use “play time” for tracking your actual play time. History is supposed to track total retries and plays.

**Comment by nicolas-sanz** [comment]
Thank you for reading and sorry to make it unclear but I did actually mean number of plays not play time. The suggestion was to have the history graph to show excluding retires.
