### ISSUE TITLE
Beatmap info description has no bottom margin

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu-web#7994]
Current live:
![2021-08-11 22_27_33-Settings](https://user-images.githubusercontent.com/11320483/129090924-e7b0cdd5-3aa0-4a86-9d53-4ec3ee0df564.png)

Manually added `margin-bottom: 20px`
![2021-08-11 22_28_33-Settings](https://user-images.githubusercontent.com/11320483/129091000-b42076e0-af49-468e-879a-f7a484395f2f.png)

**Comment by RockRoller01** [comment]
This entire site is currently getting a rework (#7899)

**Comment by peppy** [comment]
Safe to say this is fixed in the newer design, so going to close this for now.
