### ISSUE TITLE
Web star rating different from in game star rating on diffs updated after the latest osu update 

### ISSUE THREAD

**Issue by foealke** [ppy/osu-web#7998]
Might be related to [#6234](https://github.com/ppy/osu-web/issues/6234)

The star rating on osu website of diffs updated after the latest game update (https://osu.ppy.sh/beatmapsets/1458865#osu/3006443) 
differs from the in game star rating.

The problem still occurred after several hours of waiting, so I am pretty sure the difficulty calculations were already over.

**Comment by peppy** [comment]
web is correct. this has been the case since the recent recalculation. the game will eventually somehow be updated to match.
