### ISSUE TITLE
Userpage's new width can break userpage graphics

### ISSUE THREAD

**Issue by UncleClapton** [ppy/osu-web#8]
This might end up being one of those "oh well we're stuck with it" things, but maybe something can be done about it. The new me! tabs on profiles have a smaller width than their old-web counterparts, causing split-image userpage header graphics to break.

Some images for reference:

Old Userpages:
![old userpage example](http://puu.sh/jRL18/e60ef71813.png)
New me! tab:
![New userpage example](http://puu.sh/jRL01/7c527d744a.png)

This affects the desktop version and the mobile version at certain widths. I have had them appear correctly at some elongated widths in mobile mode, but this should be expected due to it's dynamic width.

To give credit, Sulker on the osu!dev slack found this, and I investigated it further with him. We found one possible solution was to expand the profiles out by 100px on desktop, but this does not fix the issues on mobile.

**Comment by Nicarim** [comment]
In my opinion that's no issue - it's simply new layout, you have to accomodate widths to it, and these images are loosing sense given profile picture background is already a thing. (I can see popular websites buttons being added too, if really needed)

**Comment by UncleClapton** [comment]
I suppose the best solution would be to add website buttons which would completely eliminate the need for banners like these in the first place.

This is very rough, but maybe buttons like this?
![website button sugguestion](http://puu.sh/jROr4/e8db88c21b.png)

**Comment by TheHowl** [comment]
Real ugly. I think a dropdown with "links" or something on the profile would be much better

On 28 August 2015 20:30:19 CEST, UncleClapton <notifications@github.com> wrote:
>I suppose the best solution would be to add website buttons which would
>completely eliminate the need for banners like these in the first
>place.
>
>This is very rough, but maybe buttons like this?
>![website button sugguestion](http://puu.sh/jROr4/e8db88c21b.png)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ppy/osu-web/issues/8#issuecomment-135854757

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by UncleClapton** [comment]
A dropdown might be space consuming for just one link, but would work. Additionally users could just add images to act as buttons to their me! tabs / userpages if something integrated won't work.

(also that was a 5 minute draft, it aint supposed to look pretty :stuck_out_tongue_closed_eyes:)

**Comment by TheHowl** [comment]
Perhaps put a dropdown only if there are 2+ links, and just put a button at its place if it's just one :P

On 28 August 2015 21:00:21 CEST, UncleClapton <notifications@github.com> wrote:
>A dropdown might be space consuming for just one link, but would work.
>Additionally users could just add images to act as buttons to their me!
>tabs / userpages if something integrated won't work.
>
>(also that was a 5 minute draft, it aint supposed to look pretty
>:stuck_out_tongue_closed_eyes:)
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ppy/osu-web/issues/8#issuecomment-135860941

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by peppy** [comment]
We'll likely add youtube and other links to the profile system, going forward.

**Comment by lunafreya** [comment]
It's been half a year since last update for this issue. Should we revisit and examine this so that we can finally close this one?

**Comment by nekodex** [comment]
With the latest user page redesign, this issue seems resolved. Closing.
