### ISSUE TITLE
`No comments yet` disclaimer not showing if there's a pinned comment

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#8007]
comment section with a single (pinned) comment:

![image](https://user-images.githubusercontent.com/19843905/129453332-ea7cebd9-50a2-49a6-90d2-d5c9b8c284cf.png)

comment section without any comments:

![image](https://user-images.githubusercontent.com/19843905/129453353-edeb14c9-013c-42d8-b0b1-99601774f669.png)

**Comment by bdach** [comment]
For what it's worth I don't think it makes sense to show "no comments" if there *is* a comment, even if it's a pinned one?

**Comment by TPGPL** [comment]
yeah though i think it looks kinda wrong with how it is right now

**Comment by smoogipoo** [comment]
@arflyte please provide insight into whether this is intended, or if "no comments" should still show up if there's a pinned comment.

**Comment by arflyte** [comment]
Yeah, we shouldn't show 'No comments yet' if there are pinned comments.

**Comment by smoogipoo** [comment]
Closing as intended.

**Comment by nanaya** [comment]
Does it not look weird though being just an empty section?

**Comment by peppy** [comment]
It definitely does look weird and has actually thrown me off once or twice. Not sure on how it should look though.

**Comment by arflyte** [comment]
Another alternative is to make it show "No other comments yet" or something along the tline.

**Comment by peppy** [comment]
Might work better. Let's keep this open for now.

**Comment by nanaya** [comment]
Fixed in #10218.
