### ISSUE TITLE
osu!api v2 - Getting all modes ranks 

### ISSUE THREAD

**Issue by 10YAR** [ppy/osu-web#8020]
Hello,

I'm writing this issue because of a problem I have on the osu!api v2, my webpage takes 2 seconds to show, and it's due to the fact that I'm doing 4 curls in order to get each modes ranks of a user : 

` $user = curl($osuApiUser . "/osu", null, $fallbackToken);`
` $mania = curl($osuApiUse . "/mania", null, $fallbackToken);`
` $taiko = curl($osuApiUser . "/taiko", null, $fallbackToken);`
` $ctb = curl($osuApiUser . "/fruits", null, $fallbackToken);`
 
 I'd like to know if there's a better way to get ranks of all modes. If not, is it possible to add a "all_gamemodes" option in the api ?

Thanks!

**Comment by frenzibyte** [comment]
You can get ranks of all mods by querying `osu.ppy.sh/api/v2/users?ids[]={user_id}`, which would include all gamemodes/rulesets and the user's statistics for each (`statistics_rulesets`).

However, there was a [proposal osu!lazer-side](https://github.com/ppy/osu/issues/12898) about a feature which can only be possible to implement by either including the `statistics_rulesets` object in the `api/v2/user/{user_id}` endpoint, or requerying using the user compact endpoint to get that object.

I'm interested in hearing whether it'll be feasible to include the full `statistics_rulesets` object in the `api/v2/user/{user_id}` endpoint, as that'll be useful to determine the user's rank without having to requery.

**Comment by 10YAR** [comment]
Seems like it doesn't work

I requested this URL : https://osu.ppy.sh/api/v2/users?ids[]=2892140

And i'm getting this error :
array(1) {
  ["error"]=>
  string(26) "Invalid scope(s) provided."
}

While I have these scopes : 
![image](https://user-images.githubusercontent.com/76828073/129747992-9240c3b8-0f8b-4b0f-a206-4aa9b74c1709.png)

**Comment by 10YAR** [comment]
I see, so there are no ways to get all gamemodes right now ?

**Comment by peppy** [comment]
I think these days we are already querying this data regardless, and it could potentially just be included in the transformer?

**Comment by nanaya** [comment]
Those are from different table for each modes and only the relevant one is queried.

**Comment by peppy** [comment]
Ah, I was thinking of lazer getting all of these for difficulty recommendations. It turns out [we also just query four times](https://github.com/ppy/osu/blob/6be41e497a2a9556ac4fc8334e9a5bc90fe4193a/osu.Game/Beatmaps/DifficultyRecommender.cs#L85-L97)).

Going to close this for now I think.
