### ISSUE TITLE
Why do application tokens expire so quickly?

### ISSUE THREAD

**Issue by kaname-png** [ppy/osu-web#8023]
I have generated a token with the endpoint [https://osu.ppy.sh/oauth/token](https://osu.ppy.sh/docs/index.html?javascript#client-credentials-grant), but I see that its expiration is in 1 day, this is very little, to be an application token, what can I do to not have to be generating a token every day and configure it in my code?

**Comment by nanaya** [comment]
There's no application token for client grant because creating new token only involves one request call. Apps using client grant aren't expected to be configured using the token itself but using client id/secret and generates the token whenever needed/expired.

**Comment by kaname-png** [comment]
Will there be no problem generating a new token every day?

**Comment by nanaya** [comment]
yes it's fine
