### ISSUE TITLE
Add toggle for showing username before

### ISSUE THREAD

**Issue by yansaan** [ppy/osu-web#8028]
Make settings for hidden "formerly known as" so that vtubers can play osu without creating a new account.

![Screenshot_20210819-173837748-piclsay.jpg](https://user-images.githubusercontent.com/21020026/130055595-ae49bded-5b9f-4de7-8e44-b06d3de42fcf.jpg)

![Screenshot_20210819-173837748-picsay.jpg](https://user-images.githubusercontent.com/21020026/130055624-7cd37a10-28fb-4564-a480-912736ec6847.jpg)

**Comment by gagahpangeran** [comment]
As I know you can request to remove it to support if the previous username contains your sensitive data (e.g. real name).
