### ISSUE TITLE
Report beatmap & user button messed up on mobile

### ISSUE THREAD

**Issue by mousesalt** [ppy/osu-web#8029]
just noticed it's out of mobile layer portrait

browser: chrome latest version
os: android 10

![Screenshot_2021-08-19-21-49-43-011_com.android.chrome.jpg](https://user-images.githubusercontent.com/39128490/130090684-7dcdf414-819d-45d1-ba74-44e8a57d9890.jpg)

**Comment by gagahpangeran** [comment]
This issue also happen in user profile page.

![Screen Shot 2021-08-20 at 21 58 02](https://user-images.githubusercontent.com/4964985/130092028-5c011730-7a31-47d7-ac75-927302a43a1a.png)

IMO, menu should have some kind of heuristic to adjust its position when showed.

**Comment by mousesalt** [comment]
this is may not priority but it's worth fixing..

**Comment by peppy** [comment]
I think this somehow slipped under the radar. Bumping up in priority.
