### ISSUE TITLE
Why is this endpoint not working?

### ISSUE THREAD

**Issue by kaname-png** [ppy/osu-web#8032]
I am using my authentication token as well.
And I am putting the url as it is in the documentation.

> URL = https://osu.ppy.sh/api/v2/beatmaps/lookup?checksum=qui&filename=doloribus&id=dolorum

![image](https://user-images.githubusercontent.com/56084970/129941980-0a17715e-f234-4f63-9532-2d298ea1f67e.png)

**Comment by nanaya** [comment]
Maybe try looking up something that actually exists instead
