### ISSUE TITLE
Feature to make your Country private.

### ISSUE THREAD

**Issue by realtriz** [ppy/osu-web#8033]
Picked from a post here https://osu.ppy.sh/community/forums/topics/1236711?n=1

Many people in the osu! community doesn't want to share their country names and such. Not having a feature to turn your country private is pretty >/

So, peppy, could you please implement said feature or try working on it in the near future?

**Comment by peppy** [comment]
This would be a huge amount of effort, and would take away from several game systems. Won't consider unless there's an actual large percentage of users wanting this.

**Comment by SolsticeSpectrum** [comment]
> This would be a huge amount of effort, and would take away from several game systems. Won't consider unless there's an actual large percentage of users wanting this.

I would appreciate this. Something like this should be an opt-in feature, not necessity especially these days when more and more people care about online privacy.

**Comment by cl8n** [comment]
I'm going to close this because a more recent response from peppy reads pretty definitive (https://github.com/ppy/osu/discussions/28120#discussioncomment-9370935):
> Removing country from user profiles is not something we are considering for osu!. You are welcome to use a VPN if it's that important to you.
