### ISSUE TITLE
osu! wiki: headings don't appear in search results (not indexed?)

### ISSUE THREAD

**Issue by TicClick** [ppy/osu-web#8038]
- example page: [`Help Centre/Client`](https://github.com/ppy/osu-wiki/blob/master/wiki/Help_Centre/Client/en.md#allowing-a-program-through-kaspersky-internet-security)
- searching for `Kaspersky`: [query](https://osu.ppy.sh/home/search?mode=wiki_page&query=Kaspersky) | [0 results](https://user-images.githubusercontent.com/4686101/130238265-647d4844-6f36-45b7-aafc-adbbd41f8483.png)
- searching for `Kaspersky's`: [query](https://osu.ppy.sh/home/search?mode=wiki_page&query=Kaspersky%27s) | [1 result](https://user-images.githubusercontent.com/4686101/130238613-ef12a136-e569-4c37-a22b-f4678174a852.png), as expected

I've tested other unique phrases or words that only occur in headings, like `font styles` ([query](https://osu.ppy.sh/home/search?mode=wiki_page&query=font%20styles)) or `McAfee` ([query](https://osu.ppy.sh/home/search?mode=wiki_page&query=McAfee)), and also couldn't find the exact pages. the issue is not limited to the help centre articles (for example, try `Bad Authentication Token`, and [IRC](https://github.com/ppy/osu-wiki/blob/master/wiki/Internet_Relay_Chat/en.md#im-receiving-the-error-bad-authentication-token) doesn't show up)

**Comment by notbakaneko** [comment]
Section headers currently aren't part of the search index due to them generally adding noise to the results without providing much context of their match, particularly with common words or when repeating part of the content.

For the current issue, `Kaspersky` and `McAfee` really should be matching `Kaspersky's` and `McAfee's` as well

**Comment by TicClick** [comment]
in other words, it works under the assumption that every header is duplicated somewhere in the article, which is not always true. I don't know how many people search for exact headings or their parts, but this may potenyially rob them of useful results.

regarding missing context, you can use Wikipedia as an example of properly highlighting that it's a match on section name: [query](https://en.wikipedia.org/w/index.php?search=%22Specifications+%28C-17A%29%22&title=Special:Search&profile=advanced&fulltext=1&ns0=1) | [results](https://user-images.githubusercontent.com/4686101/130277170-45a65ace-f105-4fb6-9dd5-a895e065bc81.png)

**Comment by peppy** [comment]
I'd say in the majority case that anything in the header that is important enough would usually be repeated somewhere in the following text. That said, not sure they need to be excluded from indexing. What does the "noise" look like that led to this decision?
