### ISSUE TITLE
Remove link from a deleted map, on "recent" profile area 

### ISSUE THREAD

**Issue by Sebola3461** [ppy/osu-web#8044]
![image](https://user-images.githubusercontent.com/62405013/130342552-105865ea-e824-44d9-9069-15e22d8dd316.png)
![image](https://user-images.githubusercontent.com/62405013/130342561-fcade928-6b09-4942-8e53-e0bd176d429e.png)

**Comment by nanaya** [comment]
With moderators being able to view deleted beatmaps the link could be useful 🤔

**Comment by Sebola3461** [comment]
> With moderators being able to view deleted beatmaps the link could be useful 🤔

we can limit it to moderators maybe?
