### ISSUE TITLE
Star rating on website and in game is different in several cases

### ISSUE THREAD

**Issue by troyph** [ppy/osu-web#8048]
https://osu.ppy.sh/beatmapsets/444335#osu/954692 (6.04 in-game, 5.95 on website)
https://osu.ppy.sh/beatmapsets/372851#osu/816600 (6.05 in-game,  6.01 on website)
https://osu.ppy.sh/beatmapsets/325158#osu/735272 (6.08 in-game,  6.01 on website)
and probably more

**Comment by nanaya** [comment]
Check #7998.
