### ISSUE TITLE
osu! wiki: {#custom-identifier} syntax doesn't support unicode characters

### ISSUE THREAD

**Issue by TicClick** [ppy/osu-web#8057]
- context: #7258
- [my attempt](https://github.com/ppy/osu-wiki/commit/395f2bd976f7016986534d60d5a940854f545bba), which I [have to rollback](https://github.com/ppy/osu-wiki/pull/6013), because `{#russian-identifier}`s follow the headings and [become a part of them](https://user-images.githubusercontent.com/4686101/130970106-9a0c5abb-dcfb-41bb-8d81-8f24bc2bf50d.png) instead

**Comment by nanaya** [comment]
it's a limitation of the upstream library and the workaround seems good enough so I'm closing this
