### ISSUE TITLE
Add Kazakh language

### ISSUE THREAD

**Issue by Elnurk** [ppy/osu-web#8060]
I would like to translate osu to kazakh language, but osu! site does not support it

**Comment by Elnurk** [comment]
Should I just wait before Kazakh language will be added to crowdin or I need to make request?

**Comment by peppy** [comment]
It will only be added if we see quite a bit of support for it. Reasoning being that we haven't had any requests for this in over ten years so far.

**Comment by artex212** [comment]
kazakhstan vperde!!!!!

**Comment by artex212** [comment]
I would like to see Kazakh language added as well

**Comment by ace1ng** [comment]
I would like the Kazakh language to be in osu!

**Comment by nanaya** [comment]
It's been added to crowdin. Feel free to notify me once the translation for web ("master" directory) reaches 100%.
