### ISSUE TITLE
Countries within the UK should have seperate leaderboards/flags

### ISSUE THREAD

**Issue by rennk** [ppy/osu-web#8064]
This is far fetched but please hear me out. The UK population consists of about 70 million people. 60 million of which are from England (**86%**), 5 million from Scotland (**7%**) , 2 million from Northern Ireland (**2.8%**) and 3 million from Wales (**4.3%**). There are no places in the world like the UK, which contain individual countries that are all grouped under one banner (at least I couldn't find an example of one). I believe that having a way to distinguish what part of the UK you are from would allow for the players from these places to find a better sense of community. It would also be interesting to have a separate leaderboard for each country inside of the UK. Places like Palau have their own leaderboard although less than 100 players from Palau exist and their population is only around 20,000. If this change was implemented then I think keeping the whole of the UK competing in OWC and such, similar how the Olympics handle this issue would be the correct approach. This would be a great service to those who are not from England as many of us feel not only unrepresented, but also misrepresented by the British flag. 
Thanks a lot.

**Comment by mcendu** [comment]
At least here in China, there isn't many that regard UK as a collection of countries; most of us treat it as a single entity in most cases instead.

~~And is Northern Ireland GB or IE.~~

**Comment by peppy** [comment]
For reference, this is carries over from https://github.com/ppy/osu/discussions/14500.

**Comment by rjoken** [comment]
Can you show us the flag that will be used for Northern Ireland?

**Comment by rennk** [comment]
As of now Northern Ireland does not have an "official flag" apart from the Union Jack, however the flag used along with the Union Jack there is called the Ulster Banner
(https://upload.wikimedia.org/wikipedia/commons/4/43/Flag_of_Northern_Ireland_%281953%E2%80%931972%29.svg) 
or sometimes Saint Patrick's Saltire 
(https://upload.wikimedia.org/wikipedia/commons/thumb/8/81/Saint_Patrick%27s_Saltire.svg/1200px-Saint_Patrick%27s_Saltire.svg.png)

I didn't actually know that Northern Ireland doesn't have an official flag so I apologise for including it in the proposal. Having said that the other countries mentioned do have official flags, so I hope you can make something of that. Thanks a lot.

**Comment by rennk** [comment]
> At least here in China, there isn't many that regard UK as a collection of countries; most of us treat it as a single entity in most cases instead.
> 
> ~And is Northern Ireland GB or IE.~

That's odd to hear as we are very much not the same.

It's all a bit confusing and rather contradictory if you do some searching, none of the 4 parts of the UK have their own country codes. Technically speaking It is neither GB or IE and is actually called NI (however NI is owned by Nicaragua). It shouldn't be GB as that refers to England, Scotland, Wales and their associated islands, and it wouldn't be IE as that is for the Republic of Ireland. Although it is grammatically wrong, Northern Ireland is referred to as GB, as the GB code is the ISO 3166–1 standard for the UK. Confusing but whatever.

**Comment by gagahpangeran** [comment]
Just to confirm, have you already discuss about this proposal with UK community in general?

**Comment by peppy** [comment]
I'm going to go ahead and close this. Twemoji does not support these flags and we are not having multiple countries using the same flags.
