### ISSUE TITLE
Beatmap display issue on site after updating different mapset of same song/metadata

### ISSUE THREAD

**Issue by Hiicantpk** [ppy/osu-web#8067]
After updating my WIP set (https://osu.ppy.sh/beatmapsets/1558315#taiko/3190985), my previous mapset of the same song (https://osu.ppy.sh/beatmapsets/903760#taiko/3190983) displays four empty osu!standard difficulties with no diffnames on the beatmap info page. However, upon downloading the set either through standard downloading or direct, the original two difficulties that were with the previous set are successfully imported into the game (albeit showing "Not submitted" when set to show global rankings)

There were not any difficulties added or removed from this old set, and I did not even have it downloaded at the time of adding the two difficulties to the new set, so not entirely sure what happened. Attached are screenshots of the beatmap card on my profile, as well as the listing on the osu!direct screen
![on site](https://user-images.githubusercontent.com/89744458/131260028-6954469e-74b2-417c-bc9f-949887f5542c.png)
![in direct](https://user-images.githubusercontent.com/89744458/131260029-773a2f75-0e05-47aa-a7af-a4752207d296.png)

**Comment by peppy** [comment]
Generally this isn't a supported scenario. I can fix up your beatmaps, but please let me know your goal here. The previous version is graveyarded - shall we just delete it?

**Comment by Hiicantpk** [comment]
The previous version has my two contest entries from two beatmapping contests I entered. The new set is a full taiko only set being pushed for ranked

**Comment by peppy** [comment]
can you just rename the old one via resubmission? can i do this for you? the answer here is to disambiguate the two beatmaps in some way.

**Comment by hhuujjiitfou** [comment]
can i join to

**Comment by Hiicantpk** [comment]
The old mapset has different diff names from the current set ("Another" and "Inner Oni (OFBC#1 Ver.)", compared to currently "Futsuu", "Necro's Oni",  "Inner Oni", and "Necro's Outer Oni"). I guess worse case I can slightly change the metadata on the contest set to prevent future issues (like adding a . to the title or something, since metadata won't matter for a graveyard set anyways)

**Comment by Hiicantpk** [comment]
added a . to the title of the other set to prevent future conflicts
