### ISSUE TITLE
Transparency on beatmap report button

### ISSUE THREAD

**Issue by Apis035** [ppy/osu-web#8068]
(actually the 3 dots button that displays the report button)

This button appearance doesn't goes along with others around it. Beatmap information, ranked/pending/graveyard status above, and difficulty list on the top all have transparent background box. This button should have transparency too to have same appearance as others.

- or -

Make it have same style as other 3 buttons on the left, something like this:
![image](https://user-images.githubusercontent.com/53115851/131333345-8b97c988-940b-45ef-84a9-eb343d95134b.png)

**Comment by peppy** [comment]
Do you mean the colour? If so, please wait for the redesign of this page (currently in progress at #7899) which should bring things back into a consistent visual style.
