### ISSUE TITLE
Featured artists songs shouldn't be listed as new if they were already featured under another featured artist

### ISSUE THREAD

**Issue by LittleEndu** [ppy/osu-web#8077]
[T & Sugah](https://osu.ppy.sh/beatmaps/artists/188) has few songs (like "No More" and "Walk On Air") that are listed as new but are actually from [High Tea Music](https://osu.ppy.sh/beatmaps/artists/26) albums already featured before. Don't know if new featured artist design counts for such songs but the current one doesn't seem to.

**Comment by peppy** [comment]
We list new for any artists with new tracks.
