### ISSUE TITLE
osu! wiki: support inline country flags

### ISSUE THREAD

**Issue by TicClick** [ppy/osu-web#8083]
quote from https://github.com/ppy/osu-wiki/issues/6017:

> While osu-web has moved over to using twemoji for flags, the wiki still relies on using the old pastel designs. The problem here is that they still contain many of the mistakes that are mentioned in [ppy/osu-web#3760](https://github.com/ppy/osu-web/issues/3760). While some of them are not easily spotted due to the small nature of the flags, there are still some obvious errors, as in the case of [Albania [`AL`]](https://github.com/ppy/osu-wiki/blob/master/wiki/shared/flag/AL.gif?rgh-link-date=2021-08-25T22%3A52%3A36Z) [(correct design)](https://commons.wikimedia.org/wiki/File:Flag_of_Albania.svg) and [Trinidad and Tobago [`TT`]](https://github.com/ppy/osu-wiki/blob/master/wiki/shared/flag/TT.gif?rgh-link-date=2021-08-25T22%3A52%3A36Z) [(correct design)](https://commons.wikimedia.org/wiki/File:Flag_of_Trinidad_and_Tobago.svg).
> 
> I'm not sure what the best solution to this problem would be, maybe there is some easy way to use with twemoji, but my familiarity with using it is next to nothing. Hopefully, it isn't as big of an issue to fix as I worry it could be.

twemoji flags were added in ppy/osu-web#7875. if this is implemented on the website rather than the wiki itself, we could throw away a lot of [manually copied, carried, and pasted flag references](https://github.com/ppy/osu-wiki/issues/328), ([example](https://github.com/ppy/osu-wiki/blob/master/wiki/Tournaments/OWC/2020/en.md?plain=1#L570-L618))

**Comment by TicClick** [comment]
my thoughts (a necessary preface: I don't know jack about PHP, but wanted to take a stab at the issue):

possible implementations:
- a regular Markdown figure with a special dummy URL `![](AU)` handled in [`Models/Wiki/Image.php`](https://github.com/ppy/osu-web/blob/2b5beb4388340fb17d0abaf0757b5a4bd38a0144/app/Models/Wiki/Image.php#L26)
- a custom tag used like `{{AU}}` handled during the document parsing in [`Libraries/Markdown/Osu/DocumentProcessor.php`](https://github.com/ppy/osu-web/blob/2b5beb4388340fb17d0abaf0757b5a4bd38a0144/app/Libraries/Markdown/Osu/DocumentProcessor.php#L85)

the custom tag is worse because you have to maintain it by yourself and port into osu!, but at the same time it's easier from an editor's perspective.

it would be appreciated if both approaches picked up country names automatically and used them as title text. as of now, there's a large list of country flags with localized names of the countries, and you need to copy the URLs manually. on the website, there are user profile flags, but I don't know what they use as source of data for the titles, and it's probably English only anyway _(should we even care about localization here?)_

**Comment by peppy** [comment]
Definitely need a custom tag for this. Should be easily feasible considering how many other tags have been added recently.

**Comment by notbakaneko** [comment]
After some fiddling, the syntax for this will be
`::{ flag="CC" }::`
where `::` is the custom inline container syntax which should be supported by Markdig and `{ }` is the commonmark attribute extension syntax.

**Comment by Walavouchey** [comment]
wonderful. i love this syntax. made a quick [test](https://github.com/Walavouchey/osu-wiki/blob/e305dd2977dc35d97ad29110e4d9892844dc45c2/wiki/Tournaments/OWC/2021/en.md?plain=1) to see how it would look in a tournament article

this'll ofc break github previews, making editing potentially a little more unintuitive and delaying any feedback until ci checks, but some of the workflow can potentially be improved upon in the future

![image](https://user-images.githubusercontent.com/36758269/151365869-981e0cbb-d1fa-491b-adb3-043c4798b300.png)

![image](https://user-images.githubusercontent.com/36758269/151370622-33b7820e-6d8c-4f0e-8bcb-644227268551.png)
