### ISSUE TITLE
Some featured artist not indexed if the featured artist listing lists multiple aliases for the same artist

### ISSUE THREAD

**Issue by Cynplytholowazy** [ppy/osu-web#8084]
Here's a couple of example

![image](https://user-images.githubusercontent.com/31384149/132080307-33769077-a5df-485d-8beb-43042f0f235d.png)
![image](https://user-images.githubusercontent.com/31384149/132080334-fe9d9d2f-44e7-47ec-b10c-723895815562.png)

Think it has to do with the listing having multiple aliases at the same time:
![image](https://user-images.githubusercontent.com/31384149/132080344-78534976-61a8-4ba7-9e28-9e185a211ec9.png)
![image](https://user-images.githubusercontent.com/31384149/132080349-b28dbd10-e662-42af-8528-b35c0280ceb9.png)

**Comment by peppy** [comment]
The initial associations of featured artists are not yet completed. Please check back in a week or so.

**Comment by peppy** [comment]
Closing in favour of #8111 (forgot this issue exists and we don't need two).
