### ISSUE TITLE
Limit beatmap reports to pending and graveyard maps only

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#8093]
Ranked and loved maps go through a process in which issues severe enough to be reported should be caught, with the NAT and Loved captains made aware respectively. Besides that, GMT are getting a lot of false positives from people that simply don't like the map they played and it feels like spam at this point.

**Comment by Nivalyx** [comment]
Yeah I'm seconding this, the amount of "I want to report this beatmap as `UnwantedContent` as I don't like the map" that we're getting over the days is... kind of alarming rn

From what I've seen most (if not all) of the valid reports that concern Ranked beatmaps are either coming from http://bn.mappersguild.com/reports or directly from an user to a reputable member of the mapping community (esp. NATs) anyway, so yeah 🐇

**Comment by peppy** [comment]
Sounds fine.
