### ISSUE TITLE
Add max_combo to default includes for Beatmap

### ISSUE THREAD

**Issue by Magnus-Cosmos** [ppy/osu-web#8101]
I think `max_combo` is an important attribute of a beatmap and would be nice to always have it available when dealing with a beatmap. Use cases for me would be mainly [`UsersController@scores`](https://github.com/ppy/osu-web/blob/e3f614a701bbeeb845020777100025c14434f132/app/Http/Controllers/UsersController.php#L719-L739) and [`BeatmapsController@scores`](https://github.com/ppy/osu-web/blob/e3f614a701bbeeb845020777100025c14434f132/app/Http/Controllers/BeatmapsController.php#L68-L116) since those don't include it. I want to display how far away scores are from FC and currently it requires doing an additional request for every beatmap.

**Comment by notbakaneko** [comment]
`max_combo` should be fetched from the Beatmap or Beatmapset endpoints.

**Comment by peppy** [comment]
In the future we are changing the structure of the score object to include (probably?) enough detail to determine max combo, as it is going to be required for osu-web display as well (with lazer-style-scoring).

Until that point, @notbakaneko's response is valid - request the beatmap and cache the result. Or use the data from data.ppy.sh and process the max combo locally using osu-tools.
