### ISSUE TITLE
Beatmap discussion text box position no longer fixed when pinned

### ISSUE THREAD

**Issue by apollo-dw** [ppy/osu-web#8102]
![b82wYVDXMj](https://user-images.githubusercontent.com/83023433/132675054-925f3279-bdcf-4c1d-a34d-64464ec0403a.gif)

Doesn't seem like intended behaviour?

**Comment by nanaya** [comment]
Which part of it is not fixed position?

**Comment by notbakaneko** [comment]
you're unpinning it and it unpins...as expected?

**Comment by apollo-dw** [comment]
The text box container, very specifically `beatmap-discussion-new-float--pinned`. I understand the behaviour of the toggle to be making a "note" post stay pinned at the top of modding discussions, not pinning the container to the screen.

**Comment by apollo-dw** [comment]
I was wrong on this one - apologies!
