### ISSUE TITLE
Ranked map's banner not showing

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#8112]
This map: https://osu.ppy.sh/beatmapsets/1149112

Map's background is visible when opened in osu!

**Comment by Nivalyx** [comment]
Attempting to open http://assets.ppy.sh/beatmaps/1149112/covers/cover.jpg yields in an error, seems like a server-side caching issue of some sort it seems?

**Comment by peppy** [comment]
Thanks for the report. This has been fixed.
