### ISSUE TITLE
Handle API requests with a language different from web preferred

### ISSUE THREAD

**Issue by frenzibyte** [ppy/osu-web#8113]
Continuation to ppy/osu#14662.

Currently osu!lazer's preferred language setting is decoupled from web and therefore any error responses from web would appear in the language selected web-side rather than lazer-side.

While coupling the client and web's language setting is one way to resolve this, going for an alternative way might be an easier solution in the interim (and perhaps better).

One proposal was to use the `Accept-Language` HTTP header, but, looking at osu!web now, I assume from [this code](https://github.com/ppy/osu-web/blob/04e0f42aebde3e12f8e3eef9bbe855925d2b8b49/app/Http/Middleware/SetLocale.php#L17-L46) that the `Accept-Language` is actually already considered but only when the user isn't signed in to the website, as a fallback locale provided by the browser, and therefore it can't actually be used as a solution.

Another way would be to provide the localisation key (e.g. `beatmapsets.panel.empty`) next to the message in the response, for osu!lazer to parse and display in the locally selected language, but I'm not sure if it's feasible to get the key, however.

**Comment by peppy** [comment]
Why can't it be a solution? We own the osu-web project and can make changes to how that works. Or we can update (and sync) the user's language on game startup. This is done with other settings in stable.

**Comment by frenzibyte** [comment]
> > and therefore it can't actually be used as a solution.
> 
> 
> 
> Why can't it be a solution?
> 
> 
> 
> We own the osu-web project and can make changes to how that works. I guess that is your proposal here?

If osu-web could be changed so that Accept-Language becomes prioritised over the web-side preferred locale then that'll make thing easy.

But, if I recall correctly, browsers attach their configured locale in `Accept-Language`, so the browser-wide locale would always take priority over osu-web locale setting in that case, which would not be wanted.

**Comment by peppy** [comment]
It would of course be API only, if implemented.
