### ISSUE TITLE
Maps in the 4.5* -- 6* range are hard to differentiate under the current spectrum

### ISSUE THREAD

**Issue by mcendu** [ppy/osu-web#8118]
Forwarding discussion of the relevant part from #7955.

@Purplegaze's comment:

> Currently, when you look at the gradient at a glance, the range between 4.5-6 stars appears to blend in far more slowly than the ranges below and above it.
> The difference in colour between 4.8* and 5.4* appears much smaller than the difference between 6.6* and 7.2*:
> ![image](https://user-images.githubusercontent.com/25409695/129385102-b966ea5e-bd0f-4284-9360-84eebf7b8cc9.png)
> 
> This is problematic for display because **4.5-6.5 stars is the most common range where multiple difficulties of similar levels are present** in larger mapsets involving multiple levels of Expert difficulties. (examples: [large set](https://osu.ppy.sh/beatmapsets/972812#osu/2317620), [very large set](https://osu.ppy.sh/beatmapsets/972025#osu/2077771))
> 
> I propose removing the harsh jump at 8* and using the extra space in the spectrum to spread the points back a bit, so the rainbow looks smoother:
> 
> ```typescript
>   .domain([0.1, 1.5, 2, 2.5, 3.3, 4.2, 4.9, 5.8, 6.7, 7.7, 9])
>   .clamp(true)
>   .range(['#F5FAFF', '#4FC0FF', '#4FFFD5', '#7CFF4F', '#F6F05C', '#FF8068', '#FF4E6F', '#C645B8', '#6563DE', '#18158E', '#000000'])
> ```
> 
> ```typescript
>   return rating >= 9 ? '#000000' : rating < 0.1 ? '#AAAAAA' : difficultyColourSpectrum(rating);
> ```
> 
> ![difficulty](https://user-images.githubusercontent.com/25409695/129406762-a16b51d3-873d-4ea7-8855-77de7125038e.png)
> (Edit: Extended the dark purple part as I accidentally made it dim overly quickly in the first version of the image due to the darker endpoint colour over the same distance)
> 
> I haven't seen one stated anywhere, but if there's a specific reason there has to be a harsh jump at 8*, the end of the last point can be cut off at a slightly lighter colour there too.

See also @Corne2Plum3's [comment](https://github.com/ppy/osu-web/issues/7955#issuecomment-917722060).

I think that associating Insane with orange is not a sound idea, as it looks too similar to the red color for Expert. Instead, I suggest that Insane be associated with red and Expert with magenta or pink. This can help for example making 4.5* distinguishable from 5*, and can also smoothen the transition in 6* -- 7*.

My suggestion, combined with parts of other suggestions from the original issue, looks like this:

![suggestion spectrum](https://user-images.githubusercontent.com/43639171/133385652-9119027e-42bd-4400-8c96-d1b8af626318.png)

The current one:

![current spectrum](https://user-images.githubusercontent.com/43639171/133386013-d2db2e41-26cc-46b4-9411-4c87654a4460.png)

In code:

```typescript
const difficultyColourSpectrum = d3.scaleLinear<string>()
  .domain([0, 1.25, 2, 2.5, 3.25, 4.5, 6, 7, 8, 9])
  .clamp(true)
  .range(['#4290FB', '#4FC0FF', '#4FFFD5', '#7CFF4F', '#F6F05C', '#FF3C71', '#D14FEC', '#6563DE', '#18158E', '#000000'])
  .interpolate(d3.interpolateRgb.gamma(2.2));
```
```typescript
  return rating < 0.1 ? '#AAAAAA' : difficultyColourSpectrum(rating);
```

**Comment by Purplegaze** [comment]
I already accounted for this in my original suggestion and made this distinction between Insane = red and Expert = purple, and I think this alteration brings the Insane region a bit too far while at the same time removing the distinction between low and high Expert.

Examining the individual ranges themselves shows that your suggestion's insane range looks like It encompasses many more colours than the other ranges:
![merged](https://user-images.githubusercontent.com/25409695/133425609-8b5d84f2-7cf9-4ac5-83e6-c9dac1f8b751.png)
Mine on the left, yours on the right. Note how on the version on the right, the Insane range goes from orange to bright pink without much room for red whereas mine uses the reddish orange point that you removed to add more smoothness to the range in line with how the other ranges look.

My suggestion for reference:
![f1s](https://user-images.githubusercontent.com/25409695/133425438-746d301c-ddb8-4375-bbcf-eaa86f6e746e.png)
```
  .domain([0.1, 1.25, 2, 2.5, 3.3, 4.2, 4.9, 5.8, 6.7, 7.7, 9])
  .clamp(true)
  .range(['#4290FB', '#4FC0FF', '#4FFFD5', '#7CFF4F', '#F6F05C', '#FF8068', '#FF4E6F', '#C645B8', '#6563DE', '#18158E', '#000000'])
```

```
return rating >= 9 ? '#000000' : rating < 0.1 ? '#AAAAAA' : difficultyColourSpectrum(rating);
```

**Comment by NoffyNoffeh** [comment]
Based off the general support and agreement in 7955 and peppy's comment here: https://github.com/ppy/osu-web/issues/7955#issuecomment-948258609 would it be possible for this to be implemented soon? 

Looks to me like Purplegaze's suggestion is a solid and finalized version of the gradient with the idea of moving down purple that was agreed on.

From what I can tell the technical part is worked out and looks solid and just needs a PR from someone who knows where it'd go in the osu-web code?

**Comment by peppy** [comment]
A PR would be a good next step, yep.

**Comment by cl8n** [comment]
is https://github.com/ppy/osu-web/issues/8118#issuecomment-919939836 the "final" version?
