### ISSUE TITLE
/beatmapsets/search returns cursor with _id attribute (is this intended?)

### ISSUE THREAD

**Issue by Sheepposu** [ppy/osu-web#8122]
The cursor returned from /beatmapsets/search has an _id attribute, but in order to query the next page of search results I have to use "page=2" in the url query rather than "_id=1556076". Am I doing something wrong or is the cursor supposed to return page rather than _id?

**Comment by frenzibyte** [comment]
Just to make sure, are you specifying `_id=1556076` or `cursor[_id]=1556076`? you're supposed to do the latter.

**Comment by Sheepposu** [comment]
> Just to make sure, are you specifying `_id=1556076` or `cursor[_id]=1556076`? you're supposed to do the latter.

when I tried to do the latter I got an error from Python:
`requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://osu.ppy.sh/api/v2/beatmapsets/search?sort=ranked&m=osu&cursor%5B_id%5D=_id`
so I tried just _id which didn't cause an error but it didn't grab the next page. So I tried page and that worked. I didn't really experiment much with trying to get rid of the error though.

**Comment by tybug** [comment]
You must supply all cursor parameters to the query, not just `_id`. In this case you also need an `approved_date`. Te cursor object you received previously should have had this attribute, all you need to do is forward it to the next api call.

**Comment by Sheepposu** [comment]
> You must supply all cursor parameters to the query, not just `_id`. In this case you also need an `approved_date`. The cursor object you received previously should have had this attribute, all you need to do is forward it to the next api call.

Ok I'll try this when I get back to playing around with it. I had no idea the cursor had such an attribute.

**Comment by nanaya** [comment]
Cursor parameter is not supposed to be built manually. It should forward the one from previous result as is.

**Comment by Sheepposu** [comment]
> Cursor parameter is not supposed to be built manually. You should forward the one from previous result as is.
> 
> If you think you need to know what should go inside cursor parameter, you're doing it wrong.

The way I had my objects built unloaded the data (in this case `'cursor': {'approved_date': '1596234279000', '_id': '1189904'}`) into class attributes, such as cursor._id, since this is what I did with all the other objects. Though now I realize I can just supply `{'approved_date': '1596234279000', '_id': '1189904'}` to the request function as query parameters.
Thanks for the help!

**Comment by nanaya** [comment]
Uh, that would only work if it's posting request as json (shouldn't be done for a get request). Otherwise use whatever query builder function after parsing the content.

For example in php
```php
http_build_query(['cursor' => $parsedCursorFromPreviousResult, ... other parameters ...])
```

or jquery
```javascript
$.param({ cursor: parsedCursorFromPreviousResult, ... other parameters ... })
```
