### ISSUE TITLE
Changes to the report system

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#8123]
Recent talks inside the GMT regarding our response rate to web-reports have lead to the following 2 suggestions for the report system:

-   **All score reports should be routed to the cheating endpoint.** Currently only ones marked as "cheating" land on the support teams feed and ones marked as "other" land in our. There is not really any use case for "other" for score reports, they always are cheating reports.
-   **Reports should not have an empty reason/description.** Many reports, especially user profile ones, come in wihtout any context and no obvious case. Having context would make it easier to figure out whats going on.

iirc @venix12 he would implement these if there are no issues with these suggestions

**Comment by peppy** [comment]
I'm fine with all these suggestions.
