### ISSUE TITLE
Featured Artist mark is removed after updating a map

### ISSUE THREAD

**Issue by osuZiRoX** [ppy/osu-web#8134]
Whenever you update a Pending (or potentially WIP) mapset that has the Featured Artist tag on the site, the tag gets removed. Just saw it happen with this mapset: https://osu.ppy.sh/beatmapsets/1554250#fruits/3175484

I didn't record a video or something, but it should be easy to replicate.

**Comment by peppy** [comment]
This has been resolved now, thanks for pointing out.
