### ISSUE TITLE
osu-web api /users/{id}/beatmapsets/{status} returns 403

### ISSUE THREAD

**Issue by Sebola3461** [ppy/osu-web#8136]
My request code: 

```js
get("https://osu.ppy.sh/api/v2/users/{user_id}/beatmapsets/ranked", {
        headers: {
            "Content-Type": "application/json",
            "Accept": "application/json",
            "Authorization": `Bearer ${auth_token}` // OAuth "auth_token"
        }
    }).then(response => { return response.json() }).catch(e => {
        res.send(e)
})
```

response: 
```json
{
  "message": "Request failed with status code 403",
  "name": "Error"
 }
  ```

**Comment by tybug** [comment]
Are you sure your auth token is valid? If you are using the client credentials grant and generated this token more than 24 hours ago, it will be expired and invalid and you will need to generate a new one.

**Comment by Sebola3461** [comment]
Yes, the token is valid. If not, the response code would be 401.

**Comment by tybug** [comment]
right, my bad. Did you make sure to include the `public` scope when authenticating? That endpoint needs the `public` scope.

**Comment by Sebola3461** [comment]
yes.
![image](https://user-images.githubusercontent.com/62405013/133910236-cd0c6c61-a8c6-4113-949f-1717cb3b51d3.png)

**Comment by nanaya** [comment]
what's the error message?

**Comment by Sebola3461** [comment]
> what's the error message?

https://github.com/ppy/osu-web/issues/8136#issue-1000141227

**Comment by ilsubyeega** [comment]
> Yes, the token is valid. If not, the response code would be 401.
> 
> request with invalid token:
> ![image](https://user-images.githubusercontent.com/62405013/133910061-497edab9-7990-436d-b8f6-3543e4bd7712.png)

if the token is wrong the response seems to be like this:
```json
{
  "authentication": "basic"
}
```,
I'm guessing the response from your web server is the exception?

**Comment by nanaya** [comment]
> > what's the error message?
> 
> [#8136 (comment)](https://github.com/ppy/osu-web/issues/8136#issue-1000141227)

As mentioned above, that's not the response returned by osu-web. Please check the original response.

**Comment by Sebola3461** [comment]
I generated the token again and this time it worked, I have no idea why. Because the previous token had just been generated.
