### ISSUE TITLE
Beatmap discussion text box no character limit

### ISSUE THREAD

**Issue by MANi-kun** [ppy/osu-web#8139]
So u don't have any limit on the number of characters u can type out in this box which leads to ugly situations like this one.
![image](https://user-images.githubusercontent.com/80633810/134156893-bbc370d0-b536-42d8-b6b6-c7c54610a444.png)
![image](https://user-images.githubusercontent.com/80633810/134156919-5878354d-04f9-46dd-adc4-dc1cbb026961.png)
Limit it to like maybe like 250 characters?

**Comment by nanaya** [comment]
So there was this #3831...

**Comment by peppy** [comment]
Yeah, I'm tempted to just leave as is and handle these cases via reporting them. Let's close this one and revisit if it ever becomes a widespread problem (doubt it).
