### ISSUE TITLE
Suggestion: Show less medals on profile to save space

### ISSUE THREAD

**Issue by FayneAldan** [ppy/osu-web#814]
Since there's so many Hush-Hush medals being added lately, I think that on profiles the obtained medals should show before the other medals and only obtained medals should be shown on others' profiles. Also, when viewing your own profile, there should be a button that says "Show Unobtained Medals" instead of showing them all regularly.

**Comment by peppy** [comment]
I tend to agree and had something along those lines in mind.

Assigning flyte for further feedback.

**Comment by FayneAldan** [comment]
Maybe all profiles could just show the obtained badges, and we would have a dedicated page on the site that lists all the badges with their descriptions (similar to the achievements page on the wiki), and if the user is logged in the page would have a check mark for each owned badge (probably in the corner of the badge icon).
Also, the layout for the page could probably just match the badge announcement in the Halloween news post, but with sections for each category.

**Comment by FayneAldan** [comment]
With that idea, there should also be an option on the page to switch between a grid layout (the current layout on profiles) and a list layout, so that users (achievement hunters in particular) can see all the badges at a single glance.

**Comment by arflyte** [comment]
I'll look into this.

**Comment by peppy** [comment]
Closing in favour of #1962 (half of this issue was resolved, as unachieved medals are only visible on own profile now).
