### ISSUE TITLE
suggestion to add a toggle to only display marked featured artist songs

### ISSUE THREAD

**Issue by h3oCharles** [ppy/osu-web#8146]
i know there's a gold button in the maps listing that shows maps only with that tag, but how about having that enabled by default?
maybe have that as a toggle in user settings

not sure how this would affect song selects in-game tho

**Comment by peppy** [comment]
I don't get it. Are you asking to save your default search preferences? Would bookmarking the page work?

**Comment by peppy** [comment]
Is that's what you're after, this could be considered a duplicate of https://github.com/ppy/osu-web/issues/4750.

**Comment by h3oCharles** [comment]
seems like a duplicate
