### ISSUE TITLE
combine api v2 lookup-beatmap and get-beatmap

### ISSUE THREAD

**Issue by tybug** [ppy/osu-web#8148]
the usages of [get beatmap](https://osu.ppy.sh/docs/index.html#get-beatmap) seem to be a subset of the usages of [lookup beatmap](https://osu.ppy.sh/docs/index.html#lookup-beatmap), since lookup beatmap can also take a beatmap id (in addition to other parameters) and they both have the same return type.

**Comment by nanaya** [comment]
get beatmap endpoint does a bit more on non-api side so it can't be removed.
