### ISSUE TITLE
Chat disappearing

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#8157]
![image](https://user-images.githubusercontent.com/35633093/135183880-b2b26698-cd36-4d35-8442-12d926b53583.png)

Started doing this today. The chat just disappears.. sometimes it happens right on page load, sometimes it takes a while. Would record a short video, but thats quite hard considering that this thing happens sorta at random. There are no error messages in the console when this happens. Confirmed with a friend that this isnt just happening to me

**Comment by nanaya** [comment]
When there's new silence but no new message, presence array is empty...
