### ISSUE TITLE
How about adding a badge for OSU! in the README?

### ISSUE THREAD

**Issue by aleen42** [ppy/osu-web#816]
![osu](https://rawgit.com/aleen42/badges/master/src/osu.svg)

Hello, considering about using a new badge for `OSU!` in any repositories of `ppy`, which can be a awesome representation. The badge is powered by my projects: [**badges**](https://github.com/aleen42/badges).

**Comment by NeoAdonis** [comment]
Not the most necessary of things, but I must admit it might not be a bad idea for this and other projects related with osu!

However, it's "osu!", not "OSU!". Former is a rhythm game, latter is the acronym of a state university.

**Comment by peppy** [comment]
also the logo looks like poop and is outdated and aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
