### ISSUE TITLE
[url][/url] bbcode breaks if the link contains square brackets

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#8163]
The following code:
```
[url=https://osumod.com/[Akito]/request]test[/url]
```
results in this:
![](https://i.imgur.com/0Io7GvL.png)

**Comment by aidswidjaja** [comment]
Use HTML encoding

`[url=https://osumod.com/%5BAkito%5D/request]test[/url]`

**Comment by cl8n** [comment]
well there's no way to tell whether you meant
`[url=https://osumod.com/[Akito] /request]test [/url]` or
`[url=https://osumod.com/[Akito]/request] test [/url]`.

I think the current behavior is easiest to understand, also changing it would mean potentially breaking older posts. it works the same way in phpBB. like post above says u can encode brackets to include them in links
