### ISSUE TITLE
Recent score endpoint returns incorrect lazer scores

### ISSUE THREAD

**Issue by stanriders** [ppy/osu-web#8166]
Example: 
![image](https://user-images.githubusercontent.com/8269193/135465492-661f8f85-1cdf-4156-9fcd-022e89035bf6.png)

Actual score: 
![image](https://user-images.githubusercontent.com/8269193/135465607-65adb774-a6fe-45a5-97b1-311f229e4051.png)

Accuracy and statistics seem to be missing

**Comment by peppy** [comment]
Do these show correctly on your profile?

**Comment by stanriders** [comment]
Nope
![image](https://user-images.githubusercontent.com/8269193/135484348-15101943-3a29-4d37-965b-cd2c567a3438.png)

Apiv1 seems to be returning the same data 
![image](https://user-images.githubusercontent.com/8269193/135484446-a70b2870-20d3-4fc1-90b8-c9abf959428d.png)

**Comment by peppy** [comment]
This is going to be a regression from https://github.com/ppy/osu-web/pull/8120 cc @nanaya
