### ISSUE TITLE
API user endpoint should return basic user information for restricted users

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#8172]
Ran into this in a project with a friend, where the forum endpoint returns the user id of the author (which is not visible on the website), but which you then cant lookup the name of (which is visible on the website) with the /users/ endpoint.

Would have expected to get at least some basic information for restricted users, which is visible on the website anyways, just with the is_restricted flag set to true, rather than getting nothing

**Comment by peppy** [comment]
Restricted users are intended to not exist until restrictions are lifted. Having them completely hidden is intended.
