### ISSUE TITLE
Change the "support osu!" and "osu!store" button colours

### ISSUE THREAD

**Issue by XetThe** [ppy/osu-web#8174]
i noticed the "support osu!" button changed colours a bit and i thought that the pink colour in the "osu!store" button fits better with the "support osu!" button.

i made a little edit just to see how it would look like.
![image](https://user-images.githubusercontent.com/87451413/135683895-f0301984-0aea-4764-a168-ebeed9963af8.png)
this is the current one (obviously)
![Untitled-1](https://user-images.githubusercontent.com/87451413/135683976-6a74cdfb-2acc-40ad-980e-e31e8394e07b.png)
and this is how it would look like.

(also the store button is 1px taller than the rest)

**Comment by gagahpangeran** [comment]
This colour was changed using new updated colour, see #8105

**Comment by peppy** [comment]
@arflyte highlighting for consideration

**Comment by arflyte** [comment]
O-orange? Feels weird. While I agree 'support osu!' feel better with pink, I think the store can go with purple.

**Comment by nanaya** [comment]
I think it's to match with osu store colour being orange...

**Comment by arflyte** [comment]
Hmm yeah, alright. Let's go with orange.

**Comment by baharsah** [comment]
imho, the store button is more eye-catching if using green color but more darken
