### ISSUE TITLE
Missing beatmap header image on website

### ISSUE THREAD

**Issue by Celektus** [ppy/osu-web#8175]
On [this recently uploaded map of mine](https://osu.ppy.sh/beatmapsets/1592605#osu/3252661), there's no image being displayed on the website even though it has (and always had) a normal background image with no odd resolution, file size or anything like that.

[Beatmap page](https://puu.sh/IfCMz.png)
[User page](https://puu.sh/IfCML.png)
[Beatmap listing](https://puu.sh/IfCOt.png)
[In-game](https://puu.sh/IfCMW.jpg)

**Comment by peppy** [comment]
@Celektus did you figure out what the issue was?

**Comment by Celektus** [comment]
Yea, I posted in the help forum as well and the GMT Death told me that the issue was caused by irregular characters in the BGs filename https://osu.ppy.sh/community/forums/topics/1433031
