### ISSUE TITLE
Add Ranked score section on user profil

### ISSUE THREAD

**Issue by Biokax** [ppy/osu-web#8180]
Hey,
related to the forum post I made here : 
https://osu.ppy.sh/community/forums/topics/1433320?n=1

I have been in the last osu meeting and peppy told about getting pinned score on user profile and its really great for player that just don't play osu for only pp, but want to have fun and share some scores on Their profiles even if it doesn't give pp.

I think that making something even better for peoples like score farmers who have thousands of good score in the game could be cool and I have some ideas on how to doing it :

- Have the possibility to change the curent **Rank graph** to something like **Ranked score graph** who doesn't show a curve going down on the profile for users who play 4 hours per day for years just because they don't farm pp. They playing the game and having a graph on profile who show that player loose ranks be like the player don't really play the game for now and I think osu insn't just for pp and the user profile need to show what they are doing, the number of recent play in the month does not show what the player do in game.

- Making **player title** more common for peoples that are really invested in the game. Here the idea is also for score farmers but it can be made for others "type" of players if we want. For example someone who have more that 1000SS+ on his profile can have a title like "SS+ God", etc.. I found that the score farmer leaderboard is currently underrated by the time players need to invest to the game to have these scores, maybe a title given for the top 100 score farmers players can be nice too.

The global idea is to have users that are not interested in the pp farm having a profile that doesn't just show pp and bring a new kind of content for showing that they are very active in the game.

**Comment by peppy** [comment]
> * Have the possibility to change the curent **Rank graph** to something like **Ranked score graph** who doesn't show a curve going down on the profile for users who play 4 hours per day for years just because they don't farm pp. They playing the game and having a graph on profile who show that player loose ranks be like the player don't really play the game for now and I think osu insn't just for pp and the user profile need to show what they are doing, the number of recent play in the month does not show what the player do in game.

Just use the play count graph

> * Making **player title** more common for peoples that are really invested in the game. Here the idea is also for score farmers but it can be made for others "type" of players if we want. For example someone who have more that 1000SS+ on his profile can have a title like "SS+ God", etc.. I found that the score farmer leaderboard is currently underrated by the time players need to invest to the game to have these scores, maybe a title given for the top 100 score farmers players can be nice too.

There are medals for this. We don't do titles for things like this.

> The global idea is to have users that are not interested in the pp farm having a profile that doesn't just show pp and bring a new kind of content for showing that they are very active in the game.

We are going to add new competitive means to the game. "Farming" score is not one of them. It's not competitive because it's just equal to time put into the game. You can group your epenis in the medals section (and potentially request new medals to cover this play style), but that's about as far as I'm interested in integrating it.
