### ISSUE TITLE
Moddingv2 Live Testing

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#819]
Listing issues with moddingv2 as observed during the current [live test](http://new.ppy.sh/beatmapsets/485376/discussion#:null)

**CRITICAL:**
None.

Bugs/high prio:
- [ ] Praise style feedback shouldn't show the resolved box
- [ ] Praise feedback by default, should not be visible on the timeline until toggled on to avoid clutter.
- [x] Filter toggles do not appropriately toggle the visibility of non-applicable posts on the mod timeline itself
- [x] Resolving mod posts does not actually set them as resolved.
- [x] Beatmap discussions are currently not linked from applicable maps in the new [beatmapset view](http://new.ppy.sh/beatmapsets/485376#osu/1035104). This is a fairly big issue as it orphans modding discussions from the rest of the new website from a usability perspective.
- [x] Head title is currently "Beatmap Discussions" - too nondescript and should be at the very least, a line detailing the current beatmap in question. ```beatmap / discussion / Streetlight Manifesto - A Moment of Violence by pishifat``` for example

Design:
- [ ] Difficulties within the dropdown listing should have a number right-aligned that displays the number of outstanding issues or total issues
- [x] No download link/BSS link from the discussions page itself. Mild inconvenience for new users attempting to engage with the discussion directly from the page.
- [x] Black gradient over beatmap header is missing
- [x] Upvote/downvote buttons that haven't been used by the user to actually vote are monochrome and need to be distinctly coloured based on values. Non-zero values could be coloured and the "selected" state colour changed to something else
- [x] Tightly clustered mods form [fat, ugly blobs](http://puu.sh/s2DkV/103a4b6470.png) on the timeline. Likely needs some sort of scaling "zoom" view on the timeline for very close mods.
- [x] Single-gamemode beatmap sets should not have to [go through two dropdown clicks](https://puu.sh/s2Dot/bddc700609.webm) to change difficulties
- [x] Difficulties within the gamemode set views are [not sorted at all](http://puu.sh/s2DmA/077bea86f3.png) - should be sorted by star rating ascending
- [x] [General and Timeline view toggles](http://puu.sh/s2Dlr/9702504190.png) are too nondescript and easily missed. Button style backing would make them much more visible and intuitively clickable

Feature requests:
- [ ] A global view showing an aggregate timeline across all difficulties with current non-resolved issues should be added
- [ ] Downvotes/upvotes need to have username lists attached to them [a la disqus](http://puu.sh/s2DSa/3ec64925fb.jpg) in order to better identify where the approval/disapproval is coming from
- [ ] Highlighting/outlined for "experienced" or "acclaimed" mods (BN/QAT/high upvote or high kudosu etc)
- [ ] User/role based toggles to filter out all other mods/praises from other users to replicate old forum post mod styles
- [ ] Posting new issues on identical timelines to existing issues should give the poster a notification and scroll to the existing issue in order to prevent doubleposting or unintentionally resurrecting resolved issues
- [ ] Updated/new input should raise a notification in the browser window
- [x] A ">>" button on lower difficulty levels to ascend to the next difficulty of the same gamemode would greatly increase user quality of life for quickly browsing between difficulties when working from lowest-to-high
- [x] Page header bar should inherit a cropped shot of the map's background by default
- [x] "Night mode" should be added to allow for colour inversion of major background elements for better low-light reading
- [x] Timeline elements need some sort of "ghost" padding that makes them clickable from further than just [the sole pixels in which they are drawn](https://puu.sh/s2DqB/a9808482ba.webm), perhaps same width as the icon beneath them

Concerns:

How will kudosu be awarded using this new system? For X number of upvoted and resolved issues?

Design and "power" paradigm between modders and mappers regarding the "Resolve" functionality needs to be explained in greater detail. 
- Do the modders resolve the issues they've raised after the mapper fixes them? 
- In the event that a mod change is ignored by the mapper due to non-feasibility or noncompliance, how is this handled by the system?

**Comment by Ephemeralis** [comment]
Any progress in resolving the "marking as resolved" issue? Kind of important to making the system actually usable.

**Comment by Ephemeralis** [comment]
The updated design and view is generally much cleaner and less esoteric than the old view, which is fantastic. The issue of the discussions view itself being orphaned from the beatmapset view is becoming a pretty big deal and needs to be addressed, as the system's pretty much in a state now where we can start using it for most things.

Critical stuff needs to be fixed ASAP though.

**Comment by peppy** [comment]
@Ephemeralis is this up to date? it doesn't look like it

**Comment by Ephemeralis** [comment]
Closing as existing problems have been ported to individual issues within the milestone and the bulk of the issues revealed during the live test have since been fixed.
