### ISSUE TITLE
API incorrect cursor example for /forum/topics/{topic}

### ISSUE THREAD

**Issue by RoanH** [ppy/osu-web#8191]
When reading the documentation for getting forum topics and posts: https://osu.ppy.sh/docs/index.html?bash#get-topic-and-posts

The example cursor response is shown as:
![image](https://user-images.githubusercontent.com/8530896/136292113-0f756c39-27d3-41bd-8457-6345880fcec4.png)

However, when trying to use this endpoint the cursor was returned as:
![image](https://user-images.githubusercontent.com/8530896/136292192-2b4fd114-41b7-4ba3-bf42-6dbf42e53e1e.png)

Presumably the name was changed from `post_id` to `id` at some point. I tried to find the file in this repository that would need to be updated to reflect this change, but didn't have much luck. If someone tells me which file to change I'll make a pull request, though that's probably not very efficient.

**Comment by RoanH** [comment]
Thanks! I'll make a pull request right now.

**Comment by nanaya** [comment]
While the example could be better, there's no incorrect cursor example. It's not supposed to be handled manually by api consumers.
