### ISSUE TITLE
Display Player's Guest Difficulties in the User page

### ISSUE THREAD

**Issue by nicholauscjj** [ppy/osu-web#8196]
With the addition of setting "Difficulty Owner", or better known as "Guest Difficulty", it would be better if all their guest diff to be displayed under their respective mapper. This will not entirely cover the pre-moddingv2.0 maps, so the mapper has to do it themselves (unfortunately).

![image](https://user-images.githubusercontent.com/36277652/136359770-d913cad4-c43b-4a6d-980a-808bce7d4d9b.png)
Figure 1. Current state of Beatmaps part of the user page

![image](https://user-images.githubusercontent.com/36277652/136359942-f4a01eb7-b51e-48ee-8af2-ac05eaf5dfd6.png)
Figure 2. Proposed state of Beatmaps part of the user page. Notice that there's "Guest Difficulty" subpart, although I only rename it from existing layout. It can be inserted anywhere, though.

**Comment by cl8n** [comment]
you can use `artisan tinker` to manually update models (e.g. `Beatmap::find($beatmapId)->update(['user_id' => $userId]);`) or make new models using the provided factories

can also use the menu provided on the beatmap page to update creators

**Comment by Diduhless** [comment]
What if the host of a beatmap
set falsely adds someone as a gder into their set? This should require some sort of confirmation system to prevent this new feature from being abused

I also believe there should be an option where you can remove yourself as the guest difficulty creator from the set (only if it's not ranked) in case you don't want to display some of your pending guest difficulties for the same reason as you being able to delete your graveyarded maps in your profile

**Comment by cl8n** [comment]
@Diduhless open a separate issue for each of those, they're both problems with the existing gd settings and not this proposed display. can be worked on independently too

**Comment by Milkitic** [comment]
Here is my proposal: For accuracy of statistics I think we need a solution for old ranked beatmaps which hasn't been marked as guest difficulty. Anyway it's another topic

**Comment by Hiviexd** [comment]
should be solved by addressing https://github.com/ppy/osu-web/issues/8243 alongside the current issue

**Comment by nanaya** [comment]
Instead of having all this "guest difficulty" badge thing, can it be just a new section which lists all non-wip/graveyard guest diff maps?

**Comment by peppy** [comment]
I think that's fine as a starting point. Should probably be beneath "Ranked Beatmaps" and called "Ranked Beatmaps (with guest difficulty)"

**Comment by Hiviexd** [comment]
thoughts on "Ranked Guest Difficulties" as a category name? looks cleaner and less cluttered imo

**Comment by TalhaAbid** [comment]
oh wow I forgot about this, I'll maybe fix my issues this week unless someone else wants to do it.

**Comment by peppy** [comment]
> thoughts on "Ranked Guest Difficulties" as a category name? looks cleaner and less cluttered imo

I don't really agree with this as it implies that the difficulties are actually listed themselves in some way, which isn't the case. The listing is literally going to show the set containing the difficulty but in now way highlight which difficulty that is.
