### ISSUE TITLE
Passing a ranked map with D shows as F on the new site

### ISSUE THREAD

**Issue by Jeremiidesu** [ppy/osu-web#820]
I just passed a map with D ranking
![Ingame showing D](http://puu.sh/s2P2U/37e31730d1.png)
And the website shows as F
![new website showing F](http://puu.sh/s2Pel/e40fb72a88.png)

**Comment by Lunar-Dust** [comment]
It seems like this has to do with misnamed files, but I'm not positive about this

**Comment by Lunar-Dust** [comment]
https://github.com/ppy/osu-web/blob/master/resources/assets/less/bem/badge-rank.less#L44
This seems to be the issue

**Comment by TPGPL** [comment]
I think there is no icon for D for the moment,

**Comment by Jeremiidesu** [comment]
There used to be one before they changed these icons tho

**Comment by peppy** [comment]
D is now F
