### ISSUE TITLE
osu forums get request issue

### ISSUE THREAD

**Issue by SeaSaltSmiles** [ppy/osu-web#8227]
Been working on my osu discord bot and wanted to add a command where it will return the titles of the most recent posts in the tournaments forum topic. Looking at the api documentation it doesn't seem possible at the moment. 
[You can see the whole code [here](https://replit.com/@SeaSaltSmiles/Osa-Bot#main.py)]

The URL **/forums/topics/55** leads me to [this post](https://osu.ppy.sh/community/forums/topics/55?n=1) and not [here](https://osu.ppy.sh/community/forums/55) but just **forums/55** (as it shows in the tournaments link) the code prints the error {'error': 'Invalid url or incorrect request method.'}

Is there a way to get the data from the tournaments forum? Hopfully this makes sense.

```
def tournament_updates():
  token = get_token()

  headers = {
    'Content-Type': 'application/json', 
    'Accept': 'application/json', 
    'Authorization': f'Bearer {token}'
  }

  params = {
  }

  response = requests.get(f'{API_URL}/forums/55', params=params, headers=headers)

  json_data = json.loads(response.text)
  print(json_data)

tournament_updates()
```

**Comment by gagahpangeran** [comment]
#7440 #7486
