### ISSUE TITLE
api v2 doesn't have anything about supporter only features

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-web#8230]
I really want to get the top score on mod-specific leaderboards, and although I have supporter myself it won't let me because I need to have supporter. Shouldn't my own client use my supporter? Also to get a user code I need to make a website but I'm using apps script to get osu info to put on my google sheets.

If there is a different way, the api document doesn't have anything about supporter and for the features that require supporter, they have to text "TODO" next to them

![image](https://user-images.githubusercontent.com/52920930/137605030-ef2e92d2-cee3-4ad6-9f9e-957892272198.png)

**Comment by peppy** [comment]
These features cannot be used via the API. The reason they are supporter only is to limit server load, and as such they can’t be exposed for automated querying.

**Comment by WinterIsPretty** [comment]
I wanted to get the average of the top 100 of every ranked map in osu!mania with no mod and double time, if I order it from the most score to least score, my theory is you will see the maps that are in order of difficulty with more accuracy than the star rating. Is there anyway I can do this or is it impossible to do currently. 

My goal is to see some sort of trends in the order that the maps are displayed to help with the star rating calc of osu!mania. I believe the pp calc is pretty good but the star rating is not.
