### ISSUE TITLE
api v2 client_credentials grant type doesnt works.

### ISSUE THREAD

**Issue by Sebola3461** [ppy/osu-web#8231]
I recently tried to generate a token for my account, but for some reason the server returns an html file from the login page with a paragraph that says:
![image](https://user-images.githubusercontent.com/62405013/137652756-be70fa39-39df-477a-9137-d054f6aefcc8.png)

#### My code (its the example code)
```js
const url = new URL(
    "https://osu.ppy.sh/oauth/token"
);

let body = {
    "client_id": my client id,
    "client_secret": "my client secret",
    "grant_type": "client_credentials",
    "scope": "public"
}

fetch(url, {
    method: "POST",
    body: JSON.stringify(body),
}).then(response => {return response.text()}).then(r => { console.log(r)})
```

**Comment by peppy** [comment]
Is this missing a `Content-Type` spec?

**Comment by notbakaneko** [comment]
`content-type` needs to specify it's json

```js
await fetch(url, {
    method: "POST",
    body: JSON.stringify(body),
    headers: {
      'Content-Type': 'application/json'
    },
}).then(response => response.json())
```

I could have sworn it used to default to json, though 🤔

**Comment by peppy** [comment]
That may be the case, but the user here has copied the example code we provide verbatim and it doesn't seem to work, so there's definitely something missing here.
