### ISSUE TITLE
Specified char/int limit on Discord users for a User model.

### ISSUE THREAD

**Issue by goverfl0w** [ppy/osu-web#8232]
https://github.com/ppy/osu-web/blob/ef432c11719fd1207bec5f9194b04f0033bdf02c/app/Models/User.php#L216

Is it intentional that `37` is the specified limit if a Discord username is a max of `32` char and a 4 digit discriminator ID?

**Comment by notbakaneko** [comment]
32 + 1 + 4 = 37
