### ISSUE TITLE
Inconsistent profile details across profile tabs

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#8241]
Seems weird to me that info shows friends, subscribers and rank information, while modding doesnt show subscribers and multiplayer shows none of the three.

![image](https://user-images.githubusercontent.com/35633093/137981519-22766cdb-4f01-4bee-8e1d-86a2c6cfbcec.png)
![image](https://user-images.githubusercontent.com/35633093/137981536-bb6c753c-1bb9-4257-b8b4-be57156e210d.png)
![image](https://user-images.githubusercontent.com/35633093/137981554-d2713f1d-3666-4fa5-aa2e-779a57f40b4a.png)

**Comment by venix12** [comment]
personally think it's okay and logical that modding displays the mapping related stats, not sure about multiplayer though :thinking:

**Comment by cl8n** [comment]
he's talking about the bar on the bottom of these screenshots, not the top-right stats

**Comment by nanaya** [comment]
This should've been fixed.
