### ISSUE TITLE
Update design of download page

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#8246]
The current download page feels too weeb, dated, and doesn't have anywhere to put the lazer download link.

It should be redesigned to match closer to the modern/flat/technical look we have elsewhere. As it stands a lot of people probably get there and close their browser window immediately.

**Comment by breaddevv** [comment]
Following along from the image above (image edited, I'm unsure on working with laravel, apologies) my main thought was to have 2 choices between the downloads. There could be more details added on, explaining in short what osu!stable is, and what osu!lazer is, like the features possibly? However from the basic changes, it would fill in the area on the right side of the 'let's get you started' area and gives lazer it's own section. Apologies for the different font too, I couldn't find the correct font.

![image](https://user-images.githubusercontent.com/94323077/190883167-fb7492cc-75f0-4c6f-90ac-0a1b60dcdbf1.png)

**Comment by peppy** [comment]
@breaddevv apart from the font you used being the old one, I think that looks like a good start. But in addition, there needs to be a table or further text to explain the differences between the two versions (and what is missing on lazer still).

**Comment by breaddevv** [comment]
I'll take a look later on when I'm free, trying to compile a decent list of features on Lazer and think I got a good list so far 👍

**Comment by breaddevv** [comment]
I managed to add some form of table to show some features, can definitely be expanded if required. I've added in only one cross icon in the table purely to see whether it would be better with/without one. Like discussed earlier in Twitch chat, the table is just placeholders for now. 
![osudownload2](https://user-images.githubusercontent.com/94323077/196757552-ccdbd02a-c462-4e38-b4bf-1f7313bde25b.png)

I also have a secondary version that contains the 'what is lazer?' video underneath the table, which might be an idea to further explain what lazer is, without them needing to search for the video themselves or learn about it other ways, instead it's just on the page for them. Could be an idea to have text above the video such as 'Learn more about osu!lazer:' too?
![osudownload3](https://user-images.githubusercontent.com/94323077/196758324-b9c93cbb-4d56-40bd-be27-2bebeb7fc8f5.png)

**Comment by frenzibyte** [comment]
Would put "open source" at the last since it's the least for a normal osu! player to care for, and include more important and enticing features (multiplayer spectator, in-game web pages, overhauled default skin, new HUD components e.g. PP counter, etc.)

**Comment by breaddevv** [comment]
Yeah I agree, at the moment they're just placeholders. Asked peppy earlier on if I should bother putting any key features in or not and came to the conclusion it was better to not focus on that too much. Mainly just for visual presentation I guess. Can be changed if needed though!

**Comment by nanaya** [comment]
can the page at least be page like other pages instead of making it a very big "header"? Guides etc can be styled like user profile's sections I suppose.

**Comment by breaddevv** [comment]
Yeah I understand what you mean. I guess the 'so what's the difference' could probably move somewhere else, since it does look a bit bulky along with the video, but I'm unsure it would work being in the installation guide section. Unless a new section were to be made?

**Comment by nanaya** [comment]
I mean the whole thing, including the section with download buttons. Especially without any custom background I don't see why it still needs to be in the header bg area. The current one is leftover from very old design iirc.

![](https://s.myconan.tk/2022-10/firefox_2022-10-20_18-52-32.png)

**Comment by breaddevv** [comment]
I could be wrong but I think that was just from removing the background element that made it weeb-ish, and was planned to have something else behind it? Unsure. But yeah I understand. I'll take a look

**Comment by breaddevv** [comment]
I've adjusted it a little more to make it look more like user page sections, unsure whether it was specific to just the guides or the whole page, but it can be adjusted if that's not correct, and overall made it look like the other pages (I hope). I feel like the colour of the sections could also be adjusted a little? I couldn't find a better colour, so any suggestions are great haha

![osudownload5](https://user-images.githubusercontent.com/94323077/197050601-d0f71428-9d60-481f-a24d-71020caf6b7b.png)

**Comment by peppy** [comment]
The table is still not fitting with the design at all.

@arflyte you still have no interest in participating in this thread?

any other designers out there that can help match the style? should we just leave this to nanaya/bakaneko during implementation?

**Comment by arflyte** [comment]
Uhh, sorry I didn't get any notification for some weird reason D:

Since this is the download page, it can have a fancier design like the supporter page: https://osu.ppy.sh/home/support . Don't use profile page section designs; it's not suitable for this case. I think the current download page is fine; we can just remove the weeb element, add lazer stuff, and a simple explanation on lazer.

The table is.. uh, no go. Use https://osu.ppy.sh/rankings/osu/performance as a reference for tables.
