### ISSUE TITLE
Able to download beatmaps while not signed in

### ISSUE THREAD

**Issue by jtvjan** [ppy/osu-web#825]
On new.ppy.sh, I am able to download beatmaps without being signed in. This shouldn't be possible. osu.ppy.sh does disable downloading without being signed in correctly.

![img_2905](https://cloud.githubusercontent.com/assets/9449583/19959219/5a849b9c-a1a5-11e6-82f1-8bac79e4e4d3.PNG)

**Comment by LiquidPL** [comment]
this is because you have an open session on `osu.ppy.sh`, if you log out from there, then you won't be able to download anymore

**Comment by jtvjan** [comment]
Hmm… yeah, that works. Maybe this should be reflected in the UI? So this should disappear if new.ppy.sh is the default. (as you don't have 2 separate cookies)

**Comment by LiquidPL** [comment]
hiding the download buttons for guests will have to suffice for now. we'll probably make it so that downloading is dependent on new website login somewhere around the time it will replace the old site.

**Comment by nekodex** [comment]
This was fixed in #794, closing issue~
