### ISSUE TITLE
Posts in AW show in post history

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#8251]
was made aware of this by a user, apparently this post, which is in AW is visible in the search history, and even after deletion it still shows up. Not sure if this is a one off case or not, but would be bad if it wasnt a one off case considering that AW has been a thread trashbin for over a decade

https://osu.ppy.sh/community/forums/topics/1240898

**Comment by peppy** [comment]
We've tested with new threads and this doesn't occur. This is probably an edge case of a thread which was moved using the old website's management tools.

I'll run an full reindex, which will fix this specific case.
