### ISSUE TITLE
Split modding queue subforum by gamemode

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#8256]
Like how gameplay and rankings subforum is split up. Seems like a quick and easy thing to do and will greatly benefit non standard gamemodes.

**Comment by Ephemeralis** [comment]
There's definite support for this, one per game mode. Can make the forums at any time and the GMT can handle moving things across.

**Comment by peppy** [comment]
Subforums have been added: https://osu.ppy.sh/community/forums/60
