### ISSUE TITLE
Notifications to modders about unresolved mods with replies

### ISSUE THREAD

**Issue by kongehund** [ppy/osu-web#8258]
I suggest to make it default for users to receive notifications when their mods are replied to but not marked as resolved. Sometimes a mapper might ask for clarification about a mod, but if the modder receives no notification about this, I think the modder is less likely to respond.
Example: https://osu.ppy.sh/beatmapsets/1506042/discussion/3085024/timeline#/2667379/7312429

**Comment by peppy** [comment]
Don't we already send notifications for these replies?

**Comment by notbakaneko** [comment]
Notifications for modding posts are sent to users watching the beatmap - notifications specifically for replies are only on comments.

**Comment by peppy** [comment]
Aha, definitely seems like something we want then.
