### ISSUE TITLE
DnB Featured Artist tracks shouldn't have their genres defaulted to "Electronic"

### ISSUE THREAD

**Issue by Nivalyx** [ppy/osu-web#8264]
noticed this issue through this one tweet that i saw earlier : http://twitter.com/KharazOW/status/1453000733788344328

![image](https://user-images.githubusercontent.com/36564236/138919069-b3668710-05ad-4f57-88e1-a637141cd7c9.png)

---

as it stands osu! has managed to secure quite a bunch of DnB/DnB-oriented artists in the Featured Artist listing, such as [Lexurus](http://osu.ppy.sh/beatmaps/artists/208), [T & Sugah](http://osu.ppy.sh/beatmaps/artists/188), [Andromedik](http://osu.ppy.sh/beatmaps/artists/177), and [Fred V & Grafix](http://osu.ppy.sh/beatmaps/artists/180) just to name a few.

however, most (if not all) of these artists' tracks are being defaulted to "Electronic" instead of "Drum & Bass", which caused the [Drum & Bass listing in the new FA track search page](http://osu.ppy.sh/beatmaps/artists/tracks?genre=Drum%20%26%20Bass&is_default_sort=true&sort=update_desc) to be heavily under-represented/under-populated as follows :

![image](https://user-images.githubusercontent.com/36564236/138918856-29f45fef-776a-4852-887e-96b6efd25bfd.png)

*(...yeah atm Billain is the only artist that is considered as "DnB" even although Billain's tracks are arguably much much much closer to [Neurofunk](http://osu.ppy.sh/beatmaps/artists/tracks?genre=Neurofunk&is_default_sort=true&sort=update_desc) than they are DnB)*

**Comment by cl8n** [comment]
all of the mentioned cases have been fixed so I'm closing this one. further general improvements to tagging FA genres probably are going to start depending on #9506
