### ISSUE TITLE
Beatmap cover is not loaded

### ISSUE THREAD

**Issue by gagahpangeran** [ppy/osu-web#8284]
https://osu.ppy.sh/beatmapsets/1294981#osu/2792145

The cover of the beatmap above is not loaded for me and also there are other comment about it from other user in that beatmap page.

Can't check what the status code when requesting the cover image because I'm on mobile now.

**Comment by peppy** [comment]
I've regenerated the covers, they are displaying now.

**Comment by Hiviexd** [comment]
more maps got broken right after changing their status (in this case, moving them to Loved)

https://osu.ppy.sh/beatmapsets/858742
https://osu.ppy.sh/beatmapsets/781356

**Comment by cl8n** [comment]
I can't reproduce any of these, all the oszs are working fine with osu-web and scthumber at `master`

**Comment by peppy** [comment]
I noticed a few S3 resolution failures overnight, which may have been related. Let me know if it happens again after that specific action.
