### ISSUE TITLE
Difficulty names with multiple consecutive spaces get compressed

### ISSUE THREAD

**Issue by quat1024** [ppy/osu-web#8288]
Related: #5942

This is visible on the recently ranked beatmap [Toby Fox - Dialtone](https://osu.ppy.sh/beatmapsets/1584926#osu/3237398). The second difficulty is named

    HARD                                     !!

with 37 spaces after the word `HARD`. It appears correctly in osu!stable and lazer, but displays as simply "HARD !!" in various locations on the website.

![image](https://user-images.githubusercontent.com/2068021/140238573-1a93e2b4-07e6-4e70-aa89-86c631e6faed.png)
![image](https://user-images.githubusercontent.com/2068021/140238740-fff94b8c-2ca4-47ed-9d3b-edd882b89d4c.png)
![image](https://user-images.githubusercontent.com/2068021/140238818-80626691-b78e-4a78-8ef6-c13537e36059.png)

## Possible fix

Setting `white-space: pre-wrap;` causes the difficulty name to appear correctly, at least on the main difficulty page (i haven't tried other locations). `white-space: pre` also works, but doesn't introduce line breaks for really really long diff names.

Might be kind of a pain because difficulty names can appear on the website in lots of contexts though.

![image](https://user-images.githubusercontent.com/2068021/140250437-744e1338-cd94-47d1-9a56-10e9c87ddd4d.png)

**Comment by nanaya** [comment]
No plan to display such names on web that the moment.
