### ISSUE TITLE
osu mania rankings bug

### ISSUE THREAD

**Issue by WinterIsPretty** [ppy/osu-web#8299]
what

![image](https://user-images.githubusercontent.com/52920930/140525662-b03a3619-df61-4b16-ac74-354e3a69a462.png)

I go to my country rankings and this shows up, very confusing

[my profile](https://osu.ppy.sh/users/12645448)

**Comment by GSculerlor** [comment]
pretty sure it's not a bug. the rank that is displayed on your profile is your overall rank, and when you hover it, it'll show your 4K _only_ rank and 7K _only_ rank. You can check it [here](https://osu.ppy.sh/rankings/mania/performance?variant=4k&country=US) and [here](https://osu.ppy.sh/rankings/mania/performance?variant=7k&country=US)

**Comment by cl8n** [comment]
what part of it are you finding confusing?

**Comment by WinterIsPretty** [comment]
How can your 4k rank be higher number than your country rank. I have no 7k scores on my profile whatsoever but my 4k rank is higher than my overall rank which is pure 4k maps because I barely play 7k.

**Comment by Helen0903** [comment]
Imagine if someone is very slightly above you in 4k scores, but far far below you in 7k scores. You'll be above them overall, since you are much better on average, but they'll be above you in 4k.
Considering you're ~#400 in the US for 7k, it's probably just that someone hasn't played as much 7k as you.

**Comment by WinterIsPretty** [comment]
I know what is happening, I have a lot of bonus points and bonus points don't account for key modes so my rank is higher because my pp is inflated with bonus pp
