### ISSUE TITLE
Non-ranked plays are not getting score submission tokens

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#8301]
Even for non-ranked beatmaps, the score token / submission endpoints should still work. Currently tokens will 404 when a non-`scoreable` beatmap is targeted, which is incorrect.

Probably need a new scope for this, as `scoreable` has uses elsewhere.

As discussed in https://github.com/ppy/osu/discussions/15502.

**Comment by nanaya** [comment]
what's the correct allowed maps? Everything that's `active`?

**Comment by peppy** [comment]
Sounds correct, yep. If you need to give it a new scope, something like "increases-statistics" could work. These days, all beatmaps will increase common user statistics. The main differences from scoreable are:

- Don't award PP
- Don't have leaderboards
- Don't award (most) medals, exceptions being things like progression (hit count / play count)
