### ISSUE TITLE
add a 5+ year BN/NAT badge

### ISSUE THREAD

**Issue by Hiviexd** [ppy/osu-web#8302]
Currently, we have 5 users who are eligible for this kind of badge, and it wouldn't make sense not to reward their longstanding dedication with an upgrade to their current BN/NAT badge:

Deif: 7y NAT
jonathanlfj, Gero: 7y BN
Mao: 6y NAT
neonat: 6y BN
(dates have been checked using https://bn.mappersguild.com/users )

Since it would be a potential hassle to make a 6y/7y badge due to design limitations, having a +5y badge would be much more convenient, easier to make, and future-proof.

**Comment by Joehuu** [comment]
This has been resolved.
