### ISSUE TITLE
Beatmap review feature freezing

### ISSUE THREAD

**Issue by StarCastler** [ppy/osu-web#8312]
Attempting to create a review is currently pretty broken.

Choosing either the diff select or post type:
![review-example](https://user-images.githubusercontent.com/44957149/140982579-e4d820fe-5071-49f8-bce3-fb1526879fe1.PNG)
bricks the interface, preventing any progress without reloading the entire page.

What I got from console log seems to indicate a failed resizing of the box:
![review-errorlog](https://user-images.githubusercontent.com/44957149/140982908-75455857-6253-401e-a24d-d8c070dfda88.PNG)

Would be very helpful if this could be addressed as I frequently utilize reviews in the modding process.

**Comment by Negaosu** [comment]
agree!

**Comment by peppy** [comment]
Can reproduced this, will attempt a rollback.

**Comment by peppy** [comment]
I've rolled back one release and things are working again. Apologies for that!

**Comment by Negaosu** [comment]
Ty
