### ISSUE TITLE
Error 500 when updating avatars

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-web#8318]
![image](https://user-images.githubusercontent.com/1329837/141101903-65300c50-cd49-4894-bef3-ce9dd339fb83.png)
![image](https://user-images.githubusercontent.com/1329837/141101929-5221fee3-0bce-463a-a6ee-33c23c80f67b.png)

**Comment by peppy** [comment]
This was due to some DO maintenance which hit the avatar server, please try again.

**Comment by smoogipoo** [comment]
Looks fixed.
