### ISSUE TITLE
can't see source field in beatmaps listing

### ISSUE THREAD

**Issue by rust2** [ppy/osu-web#8320]
idk how to describe problem in words so i post a screenshot. is it fixable?
in mobile version it looks little different (6 rows vs 5 rows in desktop)

pic: https://i.ibb.co/F3Nb42f/image.png
pic 175% scaled: https://i.ibb.co/23fvwWV/image.png

or this is normal behavior?

**Comment by nanaya** [comment]
yes. Switch to larger card size to see them.

**Comment by rust2** [comment]
why then?

**Comment by peppy** [comment]
Is there a reason you can't use the larger cards?

**Comment by rust2** [comment]
if you mean i can use 175% scaling then 1 card takes half of a screen which is very uncomfortable

**Comment by nanaya** [comment]
click the highlighted button to switch to larger card size

![](https://s.myconan.net/2021-11/firefox_2021-11-12_23-25-09.png)

**Comment by rust2** [comment]
ok sry

**Comment by peppy** [comment]
You might be able to get away with changing browser zoom, but that's currently how we're making things work.

Going to close this issue for now.
