### ISSUE TITLE
Link in profile score recalculation notice breaks sometimes

### ISSUE THREAD

**Issue by nbvdkamp** [ppy/osu-web#8328]
The notice added in #8324 works most of the time:
![image](https://user-images.githubusercontent.com/15140758/141338121-029aedf3-24fe-4589-bcf9-f3ac2a56115b.png)
But sometimes  on reloading the page, seemingly randomly there's an extra bracket in the markdown:
![image](https://user-images.githubusercontent.com/15140758/141338245-3423356a-c2cf-4534-b0fc-ee361aaec5f1.png)

I guess the environment variable is set incorrectly somewhere?

**Comment by peppy** [comment]
Thanks for the report. Was due to a bad deploy on one server. I've fixed this.
