### ISSUE TITLE
country_code of UserCompact can be null in api v2

### ISSUE THREAD

**Issue by MaxOhn** [ppy/osu-web#8337]
Querying api v2 endpoints containing user data for users such as [kashiUwU](https://osu.ppy.sh/users/26197460) return responses where `country_code` is `null`.
The [documentation](https://osu.ppy.sh/docs/index.html#usercompact) currently describes it as `string` i.e. non-null so that should probably be marked as `string?`.
Unless the lack of a country code is a deeper underlying issue which can be fixed instead.

**Comment by cl8n** [comment]
think it'd make sense to embrace `null` where there are currently invalid countries or magic defaults like `XX` or `__`. it communicates the meaning better to api consumers

**Comment by peppy** [comment]
I think this has been resolved now? @nanaya

**Comment by nanaya** [comment]
yeah it should be fine now
