### ISSUE TITLE
Verification

### ISSUE THREAD

**Issue by Sulker** [ppy/osu-web#834]
Versification on the new site seems to not work at all. Request a lot of code to be resent and didn't received one. 

There also the suggestion of hopefully the verification screen popping up while in the middle of uploading a user-page image on your profile as it's not responsive enough because currently right now it doesn't change the picture and doesn't notify you why.

-edit- 
Email is correct. Get verification codes from old site. New osu!site is the only problem.

**Comment by peppy** [comment]
This should be fixed now; email queue got stuck.
