### ISSUE TITLE
`null` country should show the missing flag on user profile

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#8342]
right now it shows nothing. example https://osu.ppy.sh/users/26197460

**Comment by peppy** [comment]
At a database level this user has an empty acronym, which seems weird. Usually if we can't determine one it's set to `XX`.

**Comment by peppy** [comment]
We've fixed this at a database level and also at a code level for all future cases (see https://github.com/ppy/osu-web/pull/8422).
