### ISSUE TITLE
Updating a map didn't result in a nomination reset

### ISSUE THREAD

**Issue by AJT127** [ppy/osu-web#8343]
I nominated a map last night (16 Nov)
![image](https://user-images.githubusercontent.com/43456830/142252907-18cfe6b8-2c05-4988-a571-a37ef2b0f195.png)

I then (today, 17 Nov) told YokesPai to update the map to fix something, and after he updated it my nomination wasn't reset by BanchoBot 
![image](https://user-images.githubusercontent.com/43456830/142253085-0fe03654-3f32-4b41-8eef-11a3e93d49ed.png)
(in retrospect I could've included the time on this image so you'll just have to trust me)
Aistre then nominated it and it was qualified, and I never had to renominate it after the update.

Is this intentional? Seems like it was a bug, but I'm not really sure how it happened or if I will be able to reproduce it soon so I just thought I'd bring attention to it.

**Comment by NoffyNoffeh** [comment]
Adding additional information here

Beatmap:
https://osu.ppy.sh/beatmapsets/1525457/discussion/-/generalAll

Update time from YoakesPai's profile:
![image](https://user-images.githubusercontent.com/33286824/142253508-1cdc0c96-4dcd-4520-a05b-0669dc3df0da.png)

It looks like banchobot didn't post on this map at all for whatever reason.

**Comment by peppy** [comment]
Probably worth investigation of the database paper trail to see if we can figure how this occurred.

**Comment by nanaya** [comment]
There's no banchobot post at all for that beatmapset. Either something happened with it and it never hit the endpoint or something failed when trying to create the post.

**Comment by peppy** [comment]
Sounds like we may need to change the ordering or retry LIO requests or something. Will investigate from my end.

**Comment by peppy** [comment]
I've looked into this and the only thing I can guess is that the request from old web to new web failed. I've added retry logic to hopefully make this more resilient going forward. Will close this issue for now, but let me know if you see this happen again in the future.
