### ISSUE TITLE
Background not showing on web

### ISSUE THREAD

**Issue by AJT127** [ppy/osu-web#8344]
Sometimes, either with an update, or seemingly randomly, the background file for a map ceases to show on the website.
One example would be https://osu.ppy.sh/beatmapsets/1343171#taiko/2782105 which is now ranked and doesn't show:
![image](https://user-images.githubusercontent.com/43456830/142256610-ad9838de-5284-4dde-bca1-655ccb4e49b7.png)

A second example would be https://osu.ppy.sh/beatmapsets/1525457#osu/3121051, which YokesPai managed to fix by updating the map again today (even though it actually didn't fix by updating when he tried last night) 
![image](https://user-images.githubusercontent.com/43456830/142256739-42b56ea2-2b5e-46f3-ae67-689048f0ee42.png)
![image](https://user-images.githubusercontent.com/43456830/142256774-b5f3ef4a-01f8-479b-881f-427d7fa05cc7.png)

Not really sure what causes this so just thought I'd drop everything I know here. It may or may not be relevant that a different bug also occured on the 2nd example map: https://github.com/ppy/osu-web/issues/8343

**Comment by peppy** [comment]
Are there more than just two cases of this?

**Comment by TicClick** [comment]
there was also https://osu.ppy.sh/community/forums/topics/1456830 ~2w ago, but the mapper said that it had resolved on its own

**Comment by Hiviexd** [comment]
probably related to https://github.com/ppy/osu-web/issues/8284 ?

**Comment by peppy** [comment]
We're tracking this problem, something going on with asset retrieval at our end. In the mean time, you can resolve it by submitting once more.

**Comment by bad-mapper** [comment]
another example of the issue: 
https://osu.ppy.sh/beatmapsets/1630025#mania/3327659

**Comment by peppy** [comment]
> another example of the issue: https://osu.ppy.sh/beatmapsets/1630025#mania/3327659
> 
> tried to fix by updating twice, no success

The image in your beatmap is a bitmap, renamed as a jpeg. Please make it a jpeg instead.

**Comment by peppy** [comment]
We've figured the cause of this issue, so it shouldn't happen again. Going to close the thread for now, but don't hesitate to reply if you come across another case of it happening.

**Comment by bad-mapper** [comment]
> The image in your beatmap is a bitmap, renamed as a jpeg. Please make it a jpeg instead.
It somehow got fixed, what I did:
Change extension to .jpeg, update -> didn't help
Change filename, update-> didn't help (I repeated this step 3 times)
Change filename again, edit image a bit, change resolution (aspect ratio 16:9), update -> it helped

I changed image resolution yesterday and it didn't help, but it wasn't 16:9 aspect ratio. Though I have a few maps uploaded that don't have bg in 16:9 aspect ratio and they never failed to show.

**Comment by peppy** [comment]
dude. it was a bitmap. it needs to be a jpeg. renaming a file doesn't change the file's type.
