### ISSUE TITLE
Proposal: modifying how the "Other" field functions

### ISSUE THREAD

**Issue by Negaosu** [ppy/osu-web#8345]
Just a random showerthought that I had, rather low priority but might not be too hard to implement so I thought I'd gather thoughts.

Currently, if the language or genre of a song does not fall under the pre-listed website options, "Other" must be used. What I'm proposing is that, once you click other, a second dropdown appears, which has a much larger library of languages (I presume you could borrow the list from somewhere, similar to how job application sites would have the full list) from which you could select the precise language. 

I feel like this would be quite beneficial and provide the same respect to all languages instead of "Other"-ing the less common ones. (Whilst not the main point, it might also have a byproduct of people being encouraged to map songs from their native languages or more uncommon languages, which I think would be cool for variety.)

**Comment by Negaosu** [comment]
Sidenote: This might be able to be applied to Genre as well, but I'd imagine that might be harder since the "list" would be harder to define since there are lots of genres and new ones are being pioneered constantly. It might end up also being a good idea though if done properly, since there are some genres (Hyperpop, Baroque, etc.) that get mapped but have to be moved under their umbrella genre/the closest genre to it, or just "Other". 

(also can someone add the proposal label idk how)

**Comment by MzudemO** [comment]
I don't think website genre label will encourage people to map languages more or anything. Languages and genres more specific than the presets are already used in tags and decently searchable through that. I doubt there's much of a benefit to this change.

I believe the better way to make genres and languages work is with tags as more complex objects carrying metadata information. This way you could have tags like language:Other language:Esperanto genre:Metal genre:Doom Metal etc. Unfortunately this is completely incompatible with the .osu file format so I doubt it'll happen.

**Comment by Negaosu** [comment]
That wasn't really part of the main reason. Neither was searchability to be honest, but it would indeed help that: you could be able to click on the language on the site like you can with other languages, and every non-common language wouldn't be linked under "Other" (Now it's arguable whether this is a plus or a minus considering some people might specifically wanting to be looking for uncommon genres/languages and this may deprive them of that tag, so that's something to think about).

That aside, I don't really see why _not_ to do this - it would just be making those languages work in the same way that all the rest do. It isn't exactly pressing or urgent, though.

**Comment by Negaosu** [comment]
Ok apparently a similar proposal exists: https://github.com/ppy/osu-web/issues/8345
