### ISSUE TITLE
User search sometimes misses results

### ISSUE THREAD

**Issue by Wieku** [ppy/osu-web#8360]
I tried to find a similar issue, but couldn't find one.

![image](https://user-images.githubusercontent.com/5307179/142867056-19b9fcca-14dc-4ee1-b924-63a83a25b076.png)

As a second result we get WubWoofWolfM8 and WubWoofWolf is at the 3rd page:

![image](https://user-images.githubusercontent.com/5307179/142868015-f08bf4be-de13-4a2e-ad25-4f0a12bf1d81.png)

Although this is probably #2156

Here I get no results:
![image](https://user-images.githubusercontent.com/5307179/142867120-307fab7b-489e-4872-bcd8-9d207b700f6f.png)

Searching for `wubwoofwol` returns only 1 person but misses other "wubwoofwol*":
![image](https://user-images.githubusercontent.com/5307179/142867152-1cddc69e-74de-4e96-aa8f-0d93d1a7fb43.png)

When I search for `wubwoofwolf` I get him properly as expected:
![image](https://user-images.githubusercontent.com/5307179/142867209-72a6eab1-4532-44a6-9d37-2b9c2d632903.png)

but:
![image](https://user-images.githubusercontent.com/5307179/142867227-04daa3df-7be1-4c31-90f5-bbad4b88d962.png)

WubWoofWolfM8 (mentioned under the 1st screenshot) is missing here.

it's also missing when searching for `wubwoofwolfm`
![image](https://user-images.githubusercontent.com/5307179/142868968-1cf04875-9ea9-469d-a9c4-8e855827f90e.png)

**Comment by peppy** [comment]
What is the perceived issue here? All the results match your search.

**Comment by Wieku** [comment]
I think number of screenshots is overwhelming so:
- `WubWoofWolfM8` is searchable by `WubWoof` , but not by `WubWoofWolf` or `WubWoofWolfM`
- Searching by `WubWoofWo` yields no results
- Searching `WubWoofWol` returns only 1 user

**Comment by peppy** [comment]
Definitely looks broken.

**Comment by peppy** [comment]
Scary that we didn't notice it for a year if that's the case o_O. I'm running reindexing now.

**Comment by Wieku** [comment]
Seems to be working now:
![image](https://user-images.githubusercontent.com/5307179/142912036-f7209fb3-ce7b-4448-be28-75edad331b83.png)
![image](https://user-images.githubusercontent.com/5307179/142912060-a8aeb3e3-dbbb-417a-a330-3b61835f564a.png)
![image](https://user-images.githubusercontent.com/5307179/142912172-9d35f40a-db8e-4b78-8277-bff7987f9bc5.png)
![image](https://user-images.githubusercontent.com/5307179/142912104-8dcd4a19-76e3-4867-a098-9c692ea6e2b1.png)

**Comment by peppy** [comment]
Good to hear. Indexing completed some time ago.

**Comment by cl8n** [comment]
a friend just sent me lots of examples of user searches giving really poor results, like this:

(notice screenshot is on page 2!)
![](https://user-images.githubusercontent.com/9954349/151920040-67d0a330-5718-4488-b0c2-d518be379249.png)

no idea how this happens or if it's related to the reason this was originally an issue. you can search most popular players' names with just a few characters removed and get results that put them well below other players that have less closely matching names. we tried lots of combinations of lots of names but couldn't find any real trend, the results were overall just not good
