### ISSUE TITLE
Star rating based medals do not work with Flashlight mod

### ISSUE THREAD

**Issue by MBmasher** [ppy/osu-web#8361]
With the recent osu!std rework, Flashlight now affects Star rating. However players have not been able to get the Star Rating based pass medals with Flashlight plays. (FC medals not tested yet as far as I know)

**Comment by peppy** [comment]
That's by design, and how the medals have been implemented.

**Comment by MBmasher** [comment]
Could you please elaborate on that further?

**Comment by peppy** [comment]
They have never adjusted with mods. If you'd like to make that a *proposal* then that's a different story, and would require discussion around what they are supposed to mean in the first place.

**Comment by MBmasher** [comment]
They do adjust with mods such as DoubleTime and HardRock however?

**Comment by peppy** [comment]
Will have to double-check, I may be overlooking something. The original intention was that they shouldn't, to my knowledge.

**Comment by Wieku** [comment]
Wanted to point the same, people were getting 8* (or 9* don't remember) pass medals by playing Hidamari no Uta maps with DT

**Comment by peppy** [comment]
Seems like this may actually be an issue, will investigate.

**Comment by peppy** [comment]
This should be resolved now.

**Comment by Purplegaze** [comment]
Can you clarify: does this mean that playing maps that hit certain star ratings with DT and HR no longer award those pass and FC medals?
