### ISSUE TITLE
Global Ranking number missing bottom padding in user profiles

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-web#8370]
Nov 22:
![image](https://user-images.githubusercontent.com/1329837/143431237-4a330977-6fcc-4817-952a-25d81a65a13c.png)

Current:
![image](https://user-images.githubusercontent.com/1329837/143431274-2457ee32-a779-403e-811e-bfd5dad23917.png)

This has been pointed out to me privately, but has also been mentioned in the public pp discord server so I assume it's bothering multiple people.

**Comment by nanaya** [comment]
it's been moved in new design. Check if it's still too far down in there.

**Comment by smoogipoo** [comment]
The new design is completely different, not sure what I should compare there because they're not stacked.

I've added comparison screenshots to the OP.

**Comment by smoogipoo** [comment]
![image](https://user-images.githubusercontent.com/1329837/143431542-6bb36d02-3182-4df2-87b7-fcac0870ddf1.png)

This is one of the designs in https://www.figma.com/file/YIVQm9d6pvOemHsdjq6j9w/Web%2FProfile-Page-Proposal, which matches the Nov 22 version, but that's the old design.

This is the new design:
![image](https://user-images.githubusercontent.com/1329837/143431786-dcc17576-c446-4d50-ab57-ba78a762764d.png)

**Comment by nanaya** [comment]
> The new design is completely different, not sure what I should compare there because they're not stacked.
> 
> I've added comparison screenshots to the OP.

oh I thought you meant the position on the page itself. There seems to be a typo in the class name in recent update.
