### ISSUE TITLE
Text in Skype area on profile in old and new osu!web

### ISSUE THREAD

**Issue by Xayanide** [ppy/osu-web#8375]
### Recap
As we know it, Skype has been removed from the new osu! website in every profile and cannot be seen.
It has been removed in [Account Settings](https://osu.ppy.sh/home/account/edit) as well.
Removed by 
[#1286](https://github.com/ppy/osu-web/issues/1286)
[#7259](https://github.com/ppy/osu-web/issues/7259)

 ### Issue
Those who had filled up text in the Skype area from the old osu! website back then remains in their profiles when looking them up using the https://old.ppy.sh/ website.
 
E.g. New osu!web, value in Skype cannot be seen.
https://osu.ppy.sh/users/2295078
https://osu.ppy.sh/users/2103927

E.g. Old osu!web, value in Skype can be seen.
https://old.ppy.sh/u/2295078
https://old.ppy.sh/u/2103927
 
And they cannot remove it anymore since going to the Account Settings in the old osu! website takes you directly to the [new one](https://osu.ppy.sh/home/account/edit).
 
I think there is a possibility that the text in the Skype area in the osu! profiles still remain in the new osu! website but just cannot be seen therefore when you use the old osu! website, it shows the value inside of the Skype area if there is one. 
 
Remove Skype from both old and new osu! website completely.

This minor issue is a low priority because barely anyone goes to old.ppy.sh nowadays.

**Comment by peppy** [comment]
Looks to be an oversight. I'll remove it from the old web, even though that thing is going away soon.
