### ISSUE TITLE
Registered players counter on the home page is not up to date

### ISSUE THREAD

**Issue by Aksumxd** [ppy/osu-web#8380]
Seems to have been frozen at 15,210,892 since late 2019 (according to the [wayback machine](https://web.archive.org/web/20191103215834/http://osu.ppy.sh/home)).

**Comment by peppy** [comment]
This is no longer updated, and not displayed on the new site.

**Comment by Aksumxd** [comment]
sorry, i might be misunderstanding but isn't this the same counter?
![](https://i.imgur.com/pPAnvlR.png)

**Comment by peppy** [comment]
it looks like it is. will look at either removing or making it work.
