### ISSUE TITLE
No permission to create a new topic in the new modqueue's sub-forum

### ISSUE THREAD

**Issue by hikikuman** [ppy/osu-web#8390]
Screenshot by DCT: https://imgur.com/xFxEXxh
Screenshot by Nathalia-: https://prnt.sc/213ggnb

I think the title of this issue is enough to explain🤔

**Comment by NoffyNoffeh** [comment]
They're not able to post in threads either, and get this message
![image](https://user-images.githubusercontent.com/33286824/144104864-f08d1234-d4a5-43b4-ae15-a9a327053790.png)

**Comment by peppy** [comment]
This should hopefully be resolved now. Could someone please test things out and confirm?

**Comment by Felipefams** [comment]
> This should hopefully be resolved now. Could someone please test things out and confirm?

![image](https://user-images.githubusercontent.com/86446935/144155486-108db152-ccdd-4b59-870d-78ca570a94ec.png)

it is working

**Comment by mcendu** [comment]
Worked
