### ISSUE TITLE
Web chat not showing new messages automatically

### ISSUE THREAD

**Issue by Nath789** [ppy/osu-web#8393]
The page is not showing new messages, making it out of sync with the in-game chat (even when switching channels or pm)
![image](https://user-images.githubusercontent.com/5668486/144163825-b4af7db5-206a-44e8-b990-2e24566d57b0.png)

Refreshing the page makes them appear, but it still doesn't update automatically

**Comment by peppy** [comment]
Keeping this open as it requires a bancho-side change as well.

**Comment by peppy** [comment]
This has ben resolved as of yesterday.
