### ISSUE TITLE
Graveyarded map has missing metadata and difficulty information

### ISSUE THREAD

**Issue by bdach** [ppy/osu-web#8406]
Originally spotted at https://github.com/ppy/osu/discussions/15908.

See the following beatmap set: https://osu.ppy.sh/beatmapsets/711461

Two difficulties on this beatmap set (https://osu.ppy.sh/beatmapsets/711461#osu/3104419 and https://osu.ppy.sh/beatmapsets/711461#osu/3104450) have no difficulty name, zero star rating, zero duration, no BPM/object count info and no difficulty information:

![2021-12-02-194120_988x340_scrot](https://user-images.githubusercontent.com/20418176/144483228-2c0b876d-d695-4c94-8095-f5f3f6e63332.png)

<details>

<summary>Extracted json for one of the offending beatmaps</summary>

```json
{
  "beatmapset_id": 711461,
  "difficulty_rating": 0,
  "id": 3104419,
  "mode": "osu",
  "status": "graveyard",
  "total_length": 0,
  "user_id": 10652548,
  "version": "",
  "accuracy": 0,
  "ar": 0,
  "bpm": null,
  "convert": false,
  "count_circles": 0,
  "count_sliders": 0,
  "count_spinners": 0,
  "cs": 0,
  "deleted_at": null,
  "drain": 0,
  "hit_length": 0,
  "is_scoreable": false,
  "last_updated": "2021-07-11T00:07:04+00:00",
  "mode_int": 0,
  "passcount": 0,
  "playcount": 0,
  "ranked": -2,
  "url": "https://osu.ppy.sh/beatmaps/3104419",
  "checksum": null,
  "failtimes": {
    "exit": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ],
    "fail": [
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0,
      0
    ]
  },
  "max_combo": null
}
```

</details>

Particularly of note is the  `null` bpm which is causing client-side parsing failures. Not sure whether that is something that should be handled client-side or an actual failure, which is why I'm opening this as an issue.

**Comment by respektive** [comment]
honestly might wanna handle that in the client just in case, because this actually locks the entire beatmap listing

**Comment by bdach** [comment]
@respektive thanks for your opinion, but i would rather want to hear the web team's opinion on the matter. as is the map is looking rather broken in web too.

**Comment by cl8n** [comment]
the doc type for `bpm` on `Beatmap` doesn't include null and there's no special handling of null anywhere, so it seems like an oversight

worth noting that until very recently (#8367) the API docs didn't mention bpm could be null either, so maybe that's how this issue made its way to the client.

**Comment by bdach** [comment]
Oh interesting, the case mentioned in that pull (https://osu.ppy.sh/beatmapsets/1113445/discussion#/2725011) seems to have the exact same thing going on.

Notably, upon inspection of `.osz` archives for both maps, it looks like the affected difficulties shouldn't even exist (my original case has 3 difficulties in the archive and 5 on web, case linked in this comment has 1 difficulty in archive and 2 on web).

**Comment by peppy** [comment]
I've made some database fixes to hopefully resolve this. How do things look now?

If this resolves it, I'll look at a more permanent solution.

**Comment by respektive** [comment]
Web looks good. Client-side the beatmap cards also load correctly now.

No more issues on my end.

**Comment by peppy** [comment]
Thanks for the confirmation. I'm going to need to rearrange things in BSS to avoid beatmaps don't get into this state, as it looks to be a thing which is happening on an ongoing basis.

**Comment by peppy** [comment]
I've deployed a permanent fix for this.
