### ISSUE TITLE
Add an icon statements for events in "recent"

### ISSUE THREAD

**Issue by Loreos7** [ppy/osu-web#8410]
For example, it may have this:

![image](https://user-images.githubusercontent.com/86934170/144582106-e3ef2a22-6bcc-4252-8a17-39475b89c850.png)

This is necessary to eliminate the "voids" in this graph

**Comment by peppy** [comment]
Definitely think this could benefit from icons.

**Comment by Hiviexd** [comment]
could also add a small heart one for supporter purchases/gifts

**Comment by KeziahMoselle** [comment]
Do we need custom icons for those, or we could use free to use icons library for this?

**Comment by peppy** [comment]
Are you looking to implement this? If there are suitable/matching fontawesome icons then using those for now is fine. We will replace or provide custom icons as required (or when they become available).
