### ISSUE TITLE
KINEMA106's FA listing features an album that contains no tracks

### ISSUE THREAD

**Issue by Nivalyx** [ppy/osu-web#8414]
not sure whether this is intentional or not but in the new fa (KINEMA106 / http://osu.ppy.sh/beatmaps/artists/222)'s listing there's an album that's being listed but has no licensed tracks in it :

![image](https://user-images.githubusercontent.com/36564236/144715096-85b24701-6b97-4fdd-acfa-432ee92a7cc7.png)

(i already pinged Ephemeral in the internal #mappers-guild channel but yeah i'm posting this here as well just in case)

**Comment by Ephemeralis** [comment]
fixed

**Comment by peppy** [comment]
Seems like this was an accidental addition (no tracks were forgotten in publishing the listing).
