### ISSUE TITLE
OAuth refresh_token grant type

### ISSUE THREAD

**Issue by bubrick** [ppy/osu-web#8416]
Are there plans to introduce `refresh_token` grant type in v2 api?
For now it's returned as a response to `authorization_code` request, but don't see any traces of its usage

**Comment by bubrick** [comment]
Thanks for your reply. I'm starting up with navigating to `https://osu.ppy.sh/oauth/authorize?client_id=xxx&redirect_uri=https://localhost:12345/callback&response_type=code&scope=public`, this redirects the request with authorization code to my local service. It then creates a request to replace code with access token, which is also successful. All goes well so far.

But then when I try to refresh the received `access_token` using `refresh_token` from the same response - I'm unable to do so. I've tried
```
curl -X POST "https://osu.ppy.sh/oauth/token" -H "Accept: application/json" -H "Content-Type: application/json" -d
 '{"client_id":%XXX%,"client_secret":"%SECRET%","refresh_token":"%REFRESH_TOKEN%","access_token":"%ACCESS_TOKEN%",
 "grant_type":"refresh_token"}'
```
same with `authorization_code` grant type and even without grant_type at all - every time get the following error
```
{"error":"unsupported_grant_type","error_description":"The authorization grant type is not supported by the
 authorization server.","hint":"Check that all required parameters have been provided","message":"The
  authorization grant type is not supported by the authorization server."}
```

I highly suspect that I'm missing something else and the error message is a bit misleading

**Comment by nanaya** [comment]
if that's the exact command used, in command prompt, then the data sent is malformed:

```
C:\Users\Edho\Downloads\curl-7.80.0-win64-mingw\bin>curl -X POST "https://on.nanaya.pro/oauth/token" -H "Accept: application/json" -H "Content-Type: application/json" -d '{"client_id":%XXX%,"client_secret":"%SECRET%","refresh_token":"%REFRE
SH_TOKEN%","access_token":"%ACCESS_TOKEN%", "grant_type":"refresh_token"}'
{"error":"unsupported_grant_type","error_description":"The authorization grant type is not supported by the authorization server.","hint":"Check that all required parameters have been provided","message":"The authorization grant type is not supported by the authorization server."}curl: (3) unmatched close brace/bracket in URL position 25:
grant_type:refresh_token}'
                        ^
```

Using double quote and escaping the double quotes inside work:

```
C:\Users\Edho\Downloads\curl-7.80.0-win64-mingw\bin>curl -X POST https://on.nanaya.pro/oauth/token -H "Accept: application/json" -H "Content-Type: application/json" -d "{\"client_id\":%XXX%,\"client_secret\":\"%SECRET%\",\"refresh_token\":\
"%REFRESH_TOKEN%\",\"access_token\":\"%ACCESS_TOKEN%\", \"grant_type\":\"refresh_token\"}"
{"token_type":"Bearer","expires_in":86400,"access_token":"eyJ0eXAiOiJKV1QiLCJhbG
```
