### ISSUE TITLE
Erroneous profile pp display after rebalance

### ISSUE THREAD

**Issue by Endaris** [ppy/osu-web#8419]
I was flagged an inactive player at the time of the pp rebalance.
I submitted scores again 2 days ago and got my rank readjusted then (not sure if this is relevant to the case in point but I'll mention it anyway).

On my profile there are some top scores that display pp values out of line in regular display as well as on mouseover and the weighted pp-value:

![grafik](https://user-images.githubusercontent.com/22120694/144951100-f4ae489c-eb05-40b5-8660-280f3e506146.png)

Additionally the list of my top plays is inconsistent with the list displayed by third-party tracking pages such as ameobea.me/osutrack where the map in the screenshot above does not show up in my top 100. The total pp number however is consistent with the official osu-web
[Link to my osu!-profile](https://osu.ppy.sh/users/392866)
[Ameobea osutrack profile for reference](https://ameobea.me/osutrack/user/Endaris/#content-other)

Crosschecking 2 inactive people on my friend list I did not find similar inconsistencies in display and I wasn't able to find relevant issues labeled with area:user-profile within the last month so I'm reporting this here (although I'm sad because apparently the zts Umineko marathon would barely drop out of my displayed top 100 as a result of a fix).

Even if this was due to a pending recalculation (which does not seem to make sense), I would expect the lowest scores to be properly sorted to the bottom but they aren't.

**Comment by peppy** [comment]
Please see the news post. It has information on this.

**Comment by Endaris** [comment]
The news post doesn't really have information on this or at least nothing that would make me assume that the hotfix-based recalculation isn't done yet, so I posted this on abraker's suggestion but I suppose in that case there's actually still recalculation running. Thanks.

**Comment by peppy** [comment]
The last step is ongoing over months. I guess that wasn't conveyed as well in the recent post compared to the previous one. It's not isolated to you and will be fixed as the passage of time passes.
