### ISSUE TITLE
Add check to limit playlist room duration

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#8426]
New options:

2 weeks
1 month (supporter only)
3 month (supporter only) <- not 100% sure about this but let's give it a try i guess

Reference: https://github.com/ppy/osu/discussions/14251

Would appreciate if this can be added as a relative priority, as the user in the linked thread would like to use it in January 2022.

**Comment by nanaya** [comment]
I don't actually see any limit imposed from osu-web side :thinking: 

There's a minimum of 30 minutes but no max limit check that I can find.

**Comment by peppy** [comment]
That's a touch scary. I guess we should be adding them in then :)

**Comment by ZeroPyrozen** [comment]
I would love to see monthly tournament playlist.
