### ISSUE TITLE
Add ability to sort comments

### ISSUE THREAD

**Issue by Rekunan** [ppy/osu-web#8434]
Sort by # of votes and posting date, specifically in `https://osu.ppy.sh/comments` and/or in
`https://osu.ppy.sh/comments?user_id=USERID`

**Comment by roansong** [comment]
The sort functionality already exists on the back-end, with "sort" being one of "top", "new" (the default), or "old". e.g. https://osu.ppy.sh/comments?sort=old. 

Are there existing designs for the UI for this?

**Comment by roansong** [comment]
Looks like there is an existing issue for this: https://github.com/ppy/osu-web/issues/4693

**Comment by peppy** [comment]
Closing as duplicate of #4693.
