### ISSUE TITLE
Replace an uninformative graph of online history in changelog

### ISSUE THREAD

**Issue by Loreos7** [ppy/osu-web#8437]
The current online graph should be redesigned: it does not carry 'correct' visual information. It is difficult to choose the osu version, to understand the online ratio (a logarithmic version of the graph is needed)
![ScreenShot_20211212133558](https://user-images.githubusercontent.com/86934170/145709208-9906d231-de13-4ee1-946f-5dec40af1f63.png)

For example, this can be done using the example of these graphs:
![ScreenShot_20211212133747](https://user-images.githubusercontent.com/86934170/145709253-0367a82a-d07e-4ec7-8de8-9a37829fa6d9.png)
![ScreenShot_20211212133756](https://user-images.githubusercontent.com/86934170/145709254-f378f832-6ebc-4797-b275-e4452c3a7def.png)

**Comment by peppy** [comment]
The graph here is intended to show relative usage of builds, not online user. Please visit https://osu.ppy.sh for that. Or use https://stat.ppy.sh or a third party site.
