### ISSUE TITLE
Playcount history was shifted one month to the past.

### ISSUE THREAD

**Issue by hostilew** [ppy/osu-web#8450]
Playcount history is displaying one month earlier than it should. https://osu.ppy.sh/users/6447454/osu Aetrna has playcount a month before he created his account. The same goes for every other profile I've checked including ryuk, kablaze and sakamata1. Playcount totals seem correct, just month that is wrong.

**Comment by nanaya** [comment]
looks like the chart didn't account for negative offset timezone shifting the date by one whole month from its reference point (first day's exact midnight utc)
