### ISSUE TITLE
Almost everything fails to load

### ISSUE THREAD

**Issue by RoanH** [ppy/osu-web#8461]
This has been a pretty common issue for me, but until now I never managed to capture enough information to file an issue. This time I saved a HAR for everything I managed to capture, however since it contains sensitive information I can't really upload it (though I can look up details in it). Still hoping I can capture everything from the initial page load to finish sometime.

Basically everything on the entire page fails to load (exact page isn't that important, I've seen this happen on both profile pages and forum threads, this time I clicked the link from osu-web issue 8434). Refreshing the page or loading a different page so far has always resolved the issue for me and the site remains functional for a few days after that before it happens again.
![page](https://user-images.githubusercontent.com/8530896/146976841-5eea0d2f-e84b-4c95-b4c5-7d02a0a8d510.png)

All the errors I managed to capture are shown below:
![console/network](https://user-images.githubusercontent.com/8530896/146991016-bbd6ddfa-ea41-430d-89e1-02188db8530a.png)

Browser: Firefox 95.0.2 (64-bit)

**Comment by peppy** [comment]
Please test using a different browser or connection. Those are not errors that can occur from our end, so it's going to be something like
- browser
- browser extension
- internet connection
- malware on your pc
