### ISSUE TITLE
Allow users to block/hide other users' comments

### ISSUE THREAD

**Issue by Niftys** [ppy/osu-web#8462]
I think that the comments sections of maps are long overdue for a block/hide function that allows users to prevent themselves from seeing comments from other users. Reporting doesn't work when there is outside context to the message or simply annoying individuals who aren't annoying enough for GMT to do anything, so a block/hide function would be great.

**Comment by peppy** [comment]
Should probably respect the existing user blocking system (sounds like it doesn't?)

**Comment by Niftys** [comment]
Thought about this last night, and yes, a better suggestion would be to extend the current user blocking system to comments sections, as that is the only place (I am aware) it doesn't apply.
