### ISSUE TITLE
Inconsistent label on game mode button on beatmap discussion page

### ISSUE THREAD

**Issue by Apis035** [ppy/osu-web#8470]
Here I have a beatmapset with 4 taiko difficulty and 3 mania difficulty.
![image](https://user-images.githubusercontent.com/53115851/147376227-700646cd-5c4b-475c-bea5-c7b14f984030.png)
There are 0 issue on the taiko set and 21 issues on mania set but the website shows numbers like above which is inconsistent.
The label should be either show only the total difficulty or total issues on that game mode, or even better if it shows both splitted.

**Comment by peppy** [comment]
Could you please link the beatmap for reference?

**Comment by Joehuu** [comment]
https://osu.ppy.sh/beatmapsets/1384875/discussion

**Comment by peppy** [comment]
Thanks, can confirm the issue.

Which number is most helpful to have here, since we need to choose one or the other?

**Comment by Apis035** [comment]
Issues number should be helpful to put there, to make it easier to notice which game mode that still have issues.

The difficulty dropdown list should be enough to see how many difficulties are there in that game mode. Or maybe the difficulty counter can be put inside the dropdown list like putting it in the left side of the down arrow icon.
