### ISSUE TITLE
Displaying loved #1's on userpage with a heart instead of a dash

### ISSUE THREAD

**Issue by uhuhuhh** [ppy/osu-web#8471]
Loved #1s look a bit weird on the userpage and it would look a lot better with just a heart rather than a dash, kinda like this:
before:
![loved_dash](https://user-images.githubusercontent.com/60112032/147512685-38cde18f-d05b-4661-9fce-fa7a41ab41d6.png)

after:
![loved_heart](https://user-images.githubusercontent.com/60112032/147512690-efb6d6a2-5554-4630-9f18-e7d9a128fd4a.png)

apart from the aesthetic side it would also allow to differenciate loved #1s from qualified #1s
edit: would be the same thing for pp display on recent scores etc

**Comment by peppy** [comment]
I can agree with this change.

**Comment by Walavouchey** [comment]
does the above pr close this?

**Comment by nanaya** [comment]
Indeed.
