### ISSUE TITLE
Featured Artist track search results is behind a month

### ISSUE THREAD

**Issue by Joehuu** [ppy/osu-web#8488]
When going to https://osu.ppy.sh/beatmaps/artists/tracks, the last track update was from KINEMA106, who was FA about a month ago.

Noticed when searching for freedom dive.

**Comment by peppy** [comment]
Seems like the reindex endpoint isn't correctly updating the new index (`index-beatmapset/{beatmapSetId}`)

cc @nanaya

**Comment by nanaya** [comment]
Artist track index doesn't have anything to do with beatmapset. And the timing for calling the #8489 isn't when updating beatmapset but when updating artist tables.

**Comment by peppy** [comment]
I generally do both in one go at the moment, which is the reason i mention it here. But yeah, I can add it to the new artist population script instead as it seems like a better home.

**Comment by peppy** [comment]
This has since been fixed.
