### ISSUE TITLE
api v2 Matches doesn't return beatmap ID/data from unsubmitted/deleted maps

### ISSUE THREAD

**Issue by HitomiChan-ch** [ppy/osu-web#8492]
I am currently making a stats sheets for tourney hosts/sheeters to use to quickly calculate qualifier results and other match statistics. I've run into a problem in my testing where if a deleted/unsubmitted map was played no map data would be returned in the match event. In api v1 this wasn't a problem as at least a beatmap ID was provided despite the map not actually existing. With the lack of map ID, it's impossible to automatically cross reference stuff in sheets without having to manually enter the non existent map ID. Dunno if a fix would fix all previous lobbies or not but it would be nice for unsubmitted maps to supply an ID or at least some sort of map info at least for future matches.

I'll provide some images of what I'm talking about in case things weren't clear (this is the match being used in my testing: [https://osu.ppy.sh/community/matches/92494239](https://osu.ppy.sh/community/matches/92494239))
![apiv1ss](https://user-images.githubusercontent.com/58704475/148652854-d1d7e920-55a1-4cb2-8809-5314698b9830.png)
![apiv2ss1](https://user-images.githubusercontent.com/58704475/148652857-0dbed47d-946f-4f7c-86d8-300ced4b7e42.png)
![apiv2ss2](https://user-images.githubusercontent.com/58704475/148652860-a08a2a5a-7a6d-4dc8-8828-b4c78a14bb4d.png)

**Comment by peppy** [comment]
Sounds like the data provided by v1 wasn't correct in the first place, right? What happened for unsubmitted beatmaps? Where are you implying the `beatmap_id` came from, and how would you like to see this fixed? Some kind of hash you can use to track the beatmap across multiple plays?

**Comment by HitomiChan-ch** [comment]
The match in question used a map that was then deleted after the tournament was over as it was a stat edit map with an approved upload from the original creator so what's returned from api v1 is correct. I had another case where a match had to be played with a local version of the map as the creator had deleted it mid tryouts and the sheets I was using at the time equipped with api v1 worked just fine. [https://osu.ppy.sh/community/matches/94838837](https://osu.ppy.sh/community/matches/94838837)

I presume what happens is that api v1 uses the local data for the map and api v2 does not? I think it'd make more than just my life easier if api v2 was able to include local map data if online data isn't available to still allow for automation with a map database.

**Comment by peppy** [comment]
Keep in mind that unsubmitted maps won't even have a local one. I'm not sure this is something which we will resolve before lazer multiplayer. And even there, right now unsubmitted beatmaps aren't supported (to avoid precisely this kind of scenario).

**Comment by HitomiChan-ch** [comment]
> Keep in mind that unsubmitted maps won't even have a local one

Take this map for example. It had been uploaded and a local ID was stored in the beatmap file. Later, it was deleted by the creator for whatever reason but the IDs stayed (saved it as a .txt because I couldn't upload the original)
[Silentroom - Lethaeus (BNY963) [Collab].txt](https://github.com/ppy/osu-web/files/7855002/Silentroom.-.Lethaeus.BNY963.Collab.txt)

You can also manually set a Beatmap ID and Beatmap Set ID in the map file locally and export the package with the preset IDs
[Uruha Rushia - (Not) Pettan  (metal song) (HitomiChan_) [in da kitchen].txt](https://github.com/ppy/osu-web/files/7855045/Uruha.Rushia.-.Not.Pettan.metal.song.HitomiChan_.in.da.kitchen.txt)

Regardless, understandable if there's no easy/immediate fix
