### ISSUE TITLE
SR Inconsistencies w/ Lazer

### ISSUE THREAD

**Issue by Rekunan** [ppy/osu-web#8493]
When comparing between the SR on the site and on Lazer, depending on the status of the map, the differences can range from 0.01 (https://osu.ppy.sh/beatmapsets/1164291#/2744118) to 1.1 (https://osu.ppy.sh/beatmapsets/1342866#/2781571) with extreme examples having 15.64 (https://osu.ppy.sh/beatmapsets/1274643#osu/2648514).
I've also noticed that many, if not all, of the bigger differences are on maps w/ no lb's while I've only seen low differences (most of which are 0 or 0.1 and are prob due to rounding errors) on maps w/ lb's.
Is this intentional? I was under the assumption that the web SR would use the same/similar calculation as the Lazer SR.

Some more examples (tho they're easy to find):
Ranked 0.01 diff: https://osu.ppy.sh/beatmapsets/63222#/188819
Ranked 0.06 diff: https://osu.ppy.sh/beatmapsets/376552#/824390
Approved 0.02 diff (the other 2 difficulties have 0.06 diff): https://osu.ppy.sh/beatmapsets/24388#osu/83975
Loved 0.03 diff: https://osu.ppy.sh/beatmapsets/811908#/2450838
Loved 0.07 diff: https://osu.ppy.sh/beatmapsets/327557#/924446
Pending 0.04 diff: https://osu.ppy.sh/beatmapsets/1312343#/2855311
WIP 0.12 diff: https://osu.ppy.sh/beatmapsets/1276314#/3388226
Graveyarded 0.36 diff: https://osu.ppy.sh/beatmapsets/1075008#/2249551
Graveyarded 0.51 diff: https://osu.ppy.sh/beatmapsets/1078340#/2256378

Should also note that you can view the web SR within Lazer by right-clicking the difficulty->details.

**Comment by respektive** [comment]
Probably related to https://github.com/ppy/osu/pull/15758, which got merged after the SR changes were deployed.

**Comment by Rekunan** [comment]
Maybe related in part, but def not the main cause since that's basically just a nerf despite many maps in Lazer getting buffed in SR.

**Comment by peppy** [comment]
lazer tracks newer changes than osu-web.
