### ISSUE TITLE
"Read More" link is covered by like button on mobile comments

### ISSUE THREAD

**Issue by InvisibleSymbol** [ppy/osu-web#8497]
This makes it very hard to press (only the corners work)

https://user-images.githubusercontent.com/34715248/148758904-4149a06e-f22c-4431-9b61-fd7db8e38922.mp4

**Comment by nanaya** [comment]
@InvisibleSymbol how did you find this initially? I can only reproduce this on chrome dev tool mobile mode. It seems to work fine on android chrome version 96.0.4664.104 and iphone safari (ios 15.1).

**Comment by InvisibleSymbol** [comment]
This is just how it behaves on my phone (and has been for quite a while, i remember experiencing this months ago).
Currently running Chrome 97.0.4692.70 on Android 11. My screen resolution is 1440 x 2880, if that matters.
