### ISSUE TITLE
Some World Cup winner titles are misleading

### ISSUE THREAD

**Issue by cl8n** [ppy/osu-web#8511]
minor thing that #8498 reminded me about,

titles like https://osu.ppy.sh/users/147623 already sound as if they're talking about a former rank 1, even though they're talking about OWC#1. I think they should be renamed for clarity, "OWC \<number/year\> Champion" or something?

**Comment by peppy** [comment]
cc @Ephemeralis

**Comment by Hiviexd** [comment]
resolved (with the discretion of world cup admins)
