### ISSUE TITLE
Favorites users of a beatmap not showing correctly

### ISSUE THREAD

**Issue by Ztumpie905509** [ppy/osu-web#8513]
This is my map, with 40 favorites in total
![image](https://user-images.githubusercontent.com/48085506/149653893-9c5c1a2e-01a9-4633-a302-a4dd8368e567.png)

Why does "+1 other!" exists when there is space for the 40th icon ?

Original thread: https://osu.ppy.sh/community/forums/topics/1503137?n=1

**Comment by Hiviexd** [comment]
most likely it's a restricted user that has favorited your map, their icon doesn't show up but they still count towards the map's favorite count

**Comment by Ztumpie905509** [comment]
If that is the case, I think if a restricted user is unable to interact with the community, their favorites could also be excluded since this is still an interaction by supporting this map in the community.
When their restriction is lifted, their favorites will be counted and shown.

**Comment by peppy** [comment]
We can't do that, it's too computationally intensive.

Going to close this for now.
