### ISSUE TITLE
Watched Replays Graph doesn't display correctly

### ISSUE THREAD

**Issue by Xotna** [ppy/osu-web#8515]
Found on this profile : https://osu.ppy.sh/users/17442279

It looks like the user has 0.5 replays watched in december 2020, when hovering over this month no value is displayed.
When counting the total number of watched replays (12 according to the graph, not counting the 0.5), it doesn't match the value displayed on his profile stats (10).
Also, and this is the case for every profile I checked so far, the months displayed when hovering don't correspond to the scale (1 month discrepancy).
![image](https://user-images.githubusercontent.com/97849339/149678132-bdb4e622-3458-4901-ac6f-592183a0829e.png)
The graph shows correctly on lazer client though.
![image](https://user-images.githubusercontent.com/97849339/149678214-3e5bffdf-8b2b-436c-9d45-30bb4cda103b.png)

**Comment by Karoo13** [comment]
I noticed this too, it also applies to monthly playcount history. missing data points name the previous month on hover, and consecutive missing data points will sometimes be omitted.
