### ISSUE TITLE
Site crashed on my map

### ISSUE THREAD

**Issue by Satoriohiko** [ppy/osu-web#8516]
I put map with Japanese difficulty name, then site crashed on my map. HELP. 
my account: https://osu.ppy.sh/users/12507295
my maps: https://osu.ppy.sh/beatmapsets/1676076 
https://osu.ppy.sh/beatmapsets/1676093
Please delete these maps forever. Thanx

**Comment by peppy** [comment]
It looks like you've already re-submitted the beatmap as a fresh submission. I've deleted the two failed ones for you.
