### ISSUE TITLE
Info about map is not displayed on the site, but in the game everything is fine with it.

### ISSUE THREAD

**Issue by Moltanicaa** [ppy/osu-web#8524]
https://osu.ppy.sh/beatmapsets/1636331
https://osu.ppy.sh/users/13354883 - map "Test - Test": in graveyard section

Previously, this was a difficulty for a completely different mapset, but I wanted to pull it out of there and load it myself, since there were some errors when loading that mapset. As a result, the map loaded, but the map page does not work. Map can be downloaded and it will start in the game.

**Comment by peppy** [comment]
Going to leave this open this time.

Not sure how you managed to get the beatmap into this state, but all difficulties have been deleted from the set. We can't really action on this apart from showing a better 404 error and waiting for the beatmap to enter the graveyard, I think.

**Comment by peppy** [comment]
@nanaya as discussed yesterday, this should 404 (all `osu_beatmaps` rows are `deleted_at!=NULL` while the `osu_beatmapset` row is `deleted_at=NULL`

**Comment by NoffyNoffeh** [comment]
Isn't it already in the graveyard?

**Comment by peppy** [comment]
Likely. Just commenting on users which get their beatmaps into this state and expect them to be immediately fixed/removed. Until we know how this state can be achieved, it could potentially be used as trying to work around the beatmap limit so we need more details on how to repro rather than taking system-wide remedial steps.

**Comment by kelinimo** [comment]
https://osu.ppy.sh/beatmapsets/1068471
Achieved this state by updating the map and canceling before it was completed. It used to display 4 0* difficulties, but about a month ago it just went blank.

**Comment by peppy** [comment]
@kelinimo thanks for the repro. are you able to still update the beatmap back into a good state at this point?

**Comment by kelinimo** [comment]
I do. It's still bugged after update and shows 4 0* https://osu.ppy.sh/beatmapsets/1068471#osu/3430191
