### ISSUE TITLE
PerformanceCalculator - The results of the calculation is not the same

### ISSUE THREAD

**Issue by timi137137** [ppy/osu-web#8526]
in website: https://osu.ppy.sh/scores/osu/4029061614 100pp
in osu-tools: 
![image](https://user-images.githubusercontent.com/36812439/150109329-f7242877-970d-4945-9090-066307198e59.png)
93.11pp

osu-tools build for 07a1518 commit,i sure command and file is latest

Looking forward to your early reply.

**Comment by peppy** [comment]
osu-tools features changes that haven't been deployed to production yet.
