### ISSUE TITLE
ApiV2 score lookups are missing max_combo in the beatmap object

### ISSUE THREAD

**Issue by respektive** [ppy/osu-web#8536]
`/beatmaps/{beatmap}/scores` or `/users/{user}/scores/{type}` (and probably every other score lookup, but not tested) are missing the max_combo of the beatmap. Whereas `/beatmaps/{beatmap}` does return the max_combo.

The score lookups already have every other stat one could think of, pretty weird that this is missing. 🤔

**Comment by nanaya** [comment]
@peppy is it safe to assume max combo don't vary between mods?

**Comment by peppy** [comment]
It can.. should be stored as a difficulty attribute against each ruleset already (in theory).

**Comment by nanaya** [comment]
Hm, there's nowhere to put non-base max_combo data at the moment

**Comment by nanaya** [comment]
Closing this in favor of #6572. I don't think adding max_combo to score data will be a thing.

**Comment by respektive** [comment]
Alright, guess i'll just have to do an extra api request then.
