### ISSUE TITLE
Adjusting the qualified queue

### ISSUE THREAD

**Issue by NoffyNoffeh** [ppy/osu-web#8547]
This was also discussed during the community meeting, so if there's something from that not mentioned here please add it as a reply.

Currently the qualified queue for the osu! game mode is making maps sit in qualified for around 2 weeks. 

**Problem**
There is multiple problems with this:
- Maps at over 6 days can only hold their place in the queue for up to 6 days. This means maps beyond this point that are disqualified could end up in qualified for 3 or 4 weeks instead of just 1 in total. 
- - This discourages people from making minor changes when maps pass the 6 day mark. Most maps would be disqualified before then anyways, as the norm is to check them when they're first qualified, or within the first week just like maps qualified when the queue isn't overflowing. 
- The queue is designed to help balance out incoming ranked maps. However, when it gets this bloated you would have to have a long dead period for any balancing to occur, which leads to the queue being more likely to grow than shrink when it hits this point.
- - It was at 9/10 days late December and earlier this month, but is now at 13/14 days for instance.

**Solutions**
- Raise the cap for osu!. Other modes are fine at 10 for now and rarely have that many qualified maps at a time.
- Implement a system that is naturally more flexible, instead of having to raise the hard cap each year as the community grows. Make it automatic so we can stop repeating this conversation every time
- - "like maybe increase the ranked maps per day by 1 when it reaches like 50-60, by 2 when it reaches 70, something like that" - Dada's idea
- - - Could adjust the numbers a bit, but I generally agree this is the best option. This would allow the ranked flow to stay mostly balanced without having a hard cap that leads to the Qualified queue increasing excessively in size.

- Could additionally let FA maps bypass the daily ranked cap - mentioned as an idea in the meeting
- - From what I can see, this would be good for the FA maps but rarely anyone else. This would also be weird for maps getting qualified prior to FA release, such as showcase maps. Would they get the full queue (2+ weeks), potentially delaying players getting to experience the new ranked map, or would they bypass the queue, spoiling the fact that it's FA?

_________

Thank you and I hope this issue can be addressed soon. If anyone has other ideas as well please do mention them in a comment.

**Comment by Walavouchey** [comment]
> Would they get the full queue (2+ weeks), potentially delaying players getting to experience the new ranked map, or would they bypass the queue, spoiling the fact that it's FA?

Wouldn't skipping the queue once the FA gets announced also be an option?

**Comment by peppy** [comment]
Just to make sure things are still flowing, I've increased the number per day to 12 across the board.

I agree we could potentially make this self governing (increase the number per day based on the queue length), but let's allow for a bit more time to discuss that and ensure it's feasible.

**Comment by peppy** [comment]
Going to close this for now. Please bump if we need future changes.

**Comment by Lyti4n** [comment]
Bumping this as the queue is currently the fullest it has ever been with a map just recently qualified estimated to be ranked in 12 days rather than the 7 its supposed to. There is no sign of this slowing down as 30 maps! have been qualified in std in the last 24hrs
