### ISSUE TITLE
Add an option to exclude the beatmap from being tagged with Featured Artist label

### ISSUE THREAD

**Issue by aryoadhi** [ppy/osu-web#8549]
Some beatmaps used a song that is a remix from existing song(s) on Featured Artist page. It would be a great idea to add an option to exclude it to avoid unintended behavior (would be great if 'exclude FA listing' is disabled by default), since not all song remixes are necessarily appropiate to be labelled with Featured Artist label on it.

For example, see [this beatmap](https://osu.ppy.sh/beatmapsets/1667108):

![image](https://user-images.githubusercontent.com/5029654/151272785-90b93b55-d5db-4d83-8823-cf4ca9f0a467.png)

The original source, "Pump It" is within [Getty's Featured Artist page](https://osu.ppy.sh/beatmaps/artists/128), but this particular remix is not.

**Comment by peppy** [comment]
I don't believe this will be added at a user level. We will either improve the rules to avoid remix inclusion, or create a blacklist if ever required. See https://github.com/ppy/osu-web/issues/8111 for more discussion.
