### ISSUE TITLE
The `You have blocked this user.` warning panel shouldn't be visually similar to the `Your account has been restricted!` alert

### ISSUE THREAD

**Issue by Nivalyx** [ppy/osu-web#8565]
saw this on [twitter](http://twitter.com/enri623/status/1486626659369242624) earlier :

![image](https://user-images.githubusercontent.com/36564236/151653295-1c5a3853-6266-4b87-b3b6-310d7cff58c2.png)

basically as it stands the `You have blocked this user.` warning panel looks rather similar visually to the `Your account has been restricted!` alert, which had apparently prompted some unwarranted scare/confusion to people along the way.

idk whether this is an intended behaviour or not but i feel like these two alerts can definitely be made to be more distinct towards each other tho, perhaps akin to what has been done previously in [#6550](http://github.com/ppy/osu-web/issues/6550)/[#6553](http://github.com/ppy/osu-web/pull/6553)

**Comment by peppy** [comment]
No normal user should be scared by this. Because restrictions are a very rare thing and most people have never seen that.

Viewing a blocked user profile is something people may be triggered by. Therefore the warning is intentionally visually loud.
