### ISSUE TITLE
Wrong title on a ranked mapset

### ISSUE THREAD

**Issue by Xotna** [ppy/osu-web#8598]
This ranked mapset https://osu.ppy.sh/beatmapsets/8487 is not "Parade" but "The Girl in Byakkoya" (see this mapset of the same song https://osu.ppy.sh/beatmapsets/770240). Not sure if this can be solved without changing the status of the mapset or if other ranked mapsets are misnamed, but I thought it was important enough to signal it.
Maybe it could be useful as well to check back the title + artist of old ranked maps in regard of this mistake ?

**Comment by Hiviexd** [comment]
can't really do anything about metadata mistakes in ranked maps, especially older ones, as they aren't worth an unrank and nuking countless of scores just for a title change

**Comment by cl8n** [comment]
> Not sure if this can be solved without changing the status of the mapset

unfortunately not at the moment, and there are currently no plans about future beatmap/metadata storage, so it's going to be a while before this is considered. moderators can change the online copy of Tags for now, which seems to have been done already for the map you linked

> or if other ranked mapsets are misnamed

there are lots :smiling_face_with_tear:

**Comment by Xotna** [comment]
Oh thanks for both your answers, well i guess now i know it can't be done for now ^^
Should I close the issue then ?
