### ISSUE TITLE
Error while accessing v2 API endpoints: "A required scope is missing"

### ISSUE THREAD

**Issue by CIRCULARKA** [ppy/osu-web#8601]
### Can't send the message to myself using ```https://osu.ppy.sh/api/v2/chat/new``` endpoint
 - Body
![image](https://user-images.githubusercontent.com/34581740/152685973-7f848c70-f5f1-441c-8b2f-ac2494c75062.png)
- ```Content-Type``` and ```Accept``` are ```application/json```
- Method: ```POST```
-  I am using Authorization Code Grant token
- Error:
![image](https://user-images.githubusercontent.com/34581740/152685918-feada15a-85c6-4aa2-8297-7ad4495c1115.png)
What am I doing wrong? Same error occurs with another endpoints too

**Comment by tybug** [comment]
Why are you sending the `scope` parameter in the body of the `/chat/new` request? You have to first authenticate with the api as described [in the docs](https://osu.ppy.sh/docs/index.html#authentication), and that's where you specify the `chat.write` scope.

**Comment by CIRCULARKA** [comment]
> Why are you sending the `scope` parameter in the body of the `/chat/new` request? You have to first authenticate with the api as described [in the docs](https://osu.ppy.sh/docs/index.html#authentication), and that's where you specify the `chat.write` scope.
Thanks. Idk, missed that part somehow
