### ISSUE TITLE
MWC7K Support Banner not appearing on profile's banner

### ISSUE THREAD

**Issue by wowcake** [ppy/osu-web#8621]
The MWC7K (https://osu.ppy.sh/store/products/864) image banner does not appear on profile's banner and instead appear as a blank image, Could also confirm happening on other people's side.
(for the record, it was the Indonesian MWC7K banner one)

![Screenshot_2022_0211_193434](https://user-images.githubusercontent.com/76740201/153592569-52657b6e-a44c-423c-b3ae-96f1ded13e1f.png)
(full profile, see top left)

![IMG_20220211_193642](https://user-images.githubusercontent.com/76740201/153592629-6c1e32f7-b4d7-4a97-8e76-eee85e93848b.png)
(where the mwc7k banner image should be)

**Comment by Ephemeralis** [comment]
I've fixed this on our end and it should spontaneously resolve shortly. Please highlight/DM me if it isn't resolved within 24 hours.

**Comment by peppy** [comment]
Has been resolved.
