### ISSUE TITLE
Filter beatmap search between WIP and Pending mapsets

### ISSUE THREAD

**Issue by apollo-dw** [ppy/osu-web#8623]
Beatmap search currently doesn't allow you to return only pending maps as WIP maps are also returned. As a BN who would be interested in going out of my way to find mapsets to push, not being able to filter out WIP maps proves to be a significant hinderence as many WIP maps aren't ready to be looked at, or not intended for ranked (memes, etc)

**Comment by AJT127** [comment]
seems like a good idea

**Comment by peppy** [comment]
It does feel weird that there's no way to do this. We originally grouped these together under the assumption that no one would want to view only one or the other, but this is a valid use case.

**Comment by cl8n** [comment]
https://osu.ppy.sh/beatmapsets?q=status%3Dpending&s=pending works in the meantime
