### ISSUE TITLE
Audio preview does not play in beatmap 981616

### ISSUE THREAD

**Issue by daud-ahn** [ppy/osu-web#8643]
Beatmap set https://osu.ppy.sh/beatmapsets/981616 doesn't have its audio preview, it doesn't play whether you play it form the page itself. or from search listing.

Provided the recording when reloading the webpage with console open, with comparison to a working page
https://user-images.githubusercontent.com/72173079/154492236-f8610abc-a3e9-4adb-b5a2-052debfc7eab.mp4

**Comment by peppy** [comment]
Thanks for making us aware. I've fixed this. Note that it may take a few hours to start working again due to multiple levels of caching.
