### ISSUE TITLE
Update country name for Czechia

### ISSUE THREAD

**Issue by i77xd** [ppy/osu-web#8650]
Hello,
player from Czechia here.

According to the [ISO-3166 standard](https://www.iso.org/obp/ui/#iso:code:3166:CZ), that I found out the website uses to label countries, Czech Republic's short country name is defined as `Czechia` while the osu!web still uses the full name `Czech Republic`. 
We adopted the short name in 2016 (should been in 1993 but failed) and prefer to be called that way (like French Republic is called France). So please update this.

Thank you

**Comment by peppy** [comment]
Can definitely make this change, but will wait for some more opinions as google seems to imply that not everyone has adopted the new name and a lot prefer the old.

**Comment by VaclavSulista** [comment]
Dear @Peppy, I am supporting the @i77xd  request. I am the Honorary Consul of Czechia in Switzerland.
Our foreign ministry is strongly supporting this case. 

Among others, Czechia is used by the [U.S. Department of State](https://www.state.gov/countries-areas/czechia/) , () and the CIA World Factbook and the European Union.
Czechia is also being used by the most important internet giants such as [Google](https://www.google.com/maps) and [Apple](https://www.apple.com/maps/). 
![Anmerkung 2019-09-17 155648](https://user-images.githubusercontent.com/104210032/164725350-b0e87c67-6441-41b1-83e5-76cec347ac1d.jpg)
![CIA Czechia](https://user-images.githubusercontent.com/104210032/164725352-f1e9af93-38ea-4b8d-aecf-efbfdbca54c8.jpg)
![Google maps](https://user-images.githubusercontent.com/104210032/164725353-8c5b521f-190c-4363-94bf-7e115e2bf6d5.jpg)
![iso detail](https://user-images.githubusercontent.com/104210032/164725354-f25dbb54-2067-458a-a55a-d691639957e3.jpg)
Czechia has been used in various indexes and country comparisons, for example, the World Population Data Sheet, 2019 World Population Prospects: Data Booklet, [Human Development Reports](https://hdr.undp.org/en/countries/profiles/CZE), European Demographic Data Sheet, World Happiness Report, Fragile States Index and many more.

Thank you very much

Best regards

Vaclav

**Comment by i77xd** [comment]
Another reasons to change the name:

- All czech sports associants including Czech Olympic Committee will use the short name Czechia by 2024 (Summer Olympics). Basketball, ice hockey, baseball, rugby, and football already adopted the name.

> On 28 April 2022, a conference of all sports associations was held under the patronage of the Foreign Ministry at the Czernin Palace. Following basketball, ice hockey, baseball, rugby, and association football, which started to use the short name, all remaining sports agreed to transition to the short name Czechia in the near future.

quoted from Wikipedia > [Source (article in czech language)](https://www.olympijskytym.cz/article/czechia-vs-czech-republic-co-budeme-nosit-na-dresech?fbclid=IwAR1V1xJMwOWZcgOJryfJ_POvBlcEGcXHmYvQKiYCSUAwP8GVRmn8MYTQats)

- The czech osu! community uses the short name. (!!!) > [reddit post (community meetup)](https://www.reddit.com/r/osugame/comments/uvfcvh/czechoslovak_osu_community_meetup_at_animefest_in/?utm_medium=android_app&utm_source=share)

There is no reason why to postpone this simple change more. Do we have to wait another 2, 4 or 6 years?

![image](https://user-images.githubusercontent.com/62654610/172664230-2514ddd9-2fe1-447e-8772-6cd33ca4b096.png)

**Comment by i77xd** [comment]
https://twitter.com/Kaplankook/status/1576283903123369984

**Comment by i77xd** [comment]
https://www.expats.cz/czech-news/article/czech-olympic-committee-opts-for-czechia-and-drops-czech-republic

**Comment by peppy** [comment]
Please refrain from posting consecutively. You can edit your previous posts to change it.
