### ISSUE TITLE
The "osu! Beatmaps" button is missing on Rabbit House's FA page (http://osu.ppy.sh/beatmaps/artists/242)

### ISSUE THREAD

**Issue by Nivalyx** [ppy/osu-web#8661]
noticed this while checking out Rabbit House (today's FA)'s page earlier (http://osu.ppy.sh/beatmaps/artists/242) -- the "osu! Beatmaps" button is missing from that page for some reason :

![image](https://user-images.githubusercontent.com/36564236/155345748-ca13c10a-69b3-4ed7-b3b8-f8126e71c4d1.png)

![image](https://user-images.githubusercontent.com/36564236/155346534-24d63a27-68d3-457e-9381-f846e6e46031.png)

**Comment by NoffyNoffeh** [comment]
From what I can tell, the button will appear once the ranked maps from their library are marked, based off previous artists that didn't have the button until a map got ranked. Looks like the FA marking needs to be run.

**Comment by peppy** [comment]
Was an oversight due to changed process at my end. Should be resolved now, thanks for making me aware.
