### ISSUE TITLE
Some plays in Best Performance are not ordered correctly

### ISSUE THREAD

**Issue by mangomizer** [ppy/osu-web#8663]
Some plays don't seem to be ordered properly. See Peaceful's profile: https://osu.ppy.sh/users/165027

![image](https://user-images.githubusercontent.com/30021847/155679848-4102972a-f10f-4143-8b6f-e7d6d9972e06.png)

**Comment by peppy** [comment]
Probably taiko specific. I'll re-run the processor over all users.

**Comment by peppy** [comment]
Reprocessing has finished and the case mentioned is now in order.
