### ISSUE TITLE
Blocking a user doesn't hide their forum posts

### ISSUE THREAD

**Issue by iSimpFor** [ppy/osu-web#8665]
if a person finds someone else annoying enough, they should be able to extend their block on the user to their forum threads, posts, and comments 

a gmt may not be fast enough to get to such a person who probably deserves said block to take action or it may go unnoticed so people can block said person in the meantime

the posts hidden from block will hide the post and display a message about the block, people quoting the person will display "quote hidden" on the blocked quotes(though this will only work if the people don't misspell the blocked's name, this could probably be case-insensitive)

there should also be an ability to type in the a person to block if you can't get access to the block button of that person

additionally, the person being blocked will be unable to see the blocker's posts(they will not be told who blocked them) and going to their profile will display a "user not found" page

**Comment by PercyDan54** [comment]
> additionally, the person being blocked will be unable to see the blocker's posts(they will not be told who blocked them) and going to their profile will display a "user not found" page

I disagree with this. Blocking shouldn't work like this, it will be easily abused.

**Comment by peppy** [comment]
Blocking will only ever work in one direction.
