### ISSUE TITLE
osu-api returns error

### ISSUE THREAD

**Issue by bluekytu** [ppy/osu-web#8668]
sending a request to the osu-api (v2) returns with content:
```
'{"authentication":"basic"}'
```
code: 
```
req = requests.get("https://osu.ppy.sh/api/v2/rankings/{mode}/{type}", params={"mode": "osu", "type": "performance", "response-type":"code"}, headers={"Authorization": "Bearer {{token}} ", 'Content-type':'application/json','Accept':"application/json"})
print(req.status_code)
```

I obtained the token from sending a request to /oauth/token as stated in the documentation:
```
verify = requests.post("https://osu.ppy.sh/oauth/token", data={"client_id": id, "client_secret": "secret", "grant_type": "client_credentials", "scope": "public", 'Content-type': 'application/json', 'Accept': 'application/json'})
myDict = simplejson.loads(verify._content)
access_token = myDict["access_token"]
```

Expected outcome should be code 200 with specified data.

Doing the same in javascript yields no result as there is simply no space to authorize. Headers do not accept Authorization as a legal header value and GET requests do not have bodies, so I am stuck.

I understand that the issue is caused by an invalid API KEY, but what I don't understand is how exactly is my API KEY invalid?

**Comment by notbakaneko** [comment]
`{{token}}` should be substituted with your `access_token` and there should be no space after it

**Comment by bluekytu** [comment]
@notbakaneko Yes, I do know that, I only replaced my actual token with 'token' as to not leak it

**Comment by nanaya** [comment]
just to make sure, it's the whole string `{{token}}` that needs to be replaced. In python it should be something like `f'Bearer {access_token}'` or in shell `"Bearer $TOKEN"`, not just the `token` part. `f'Bearer {{{{{access_token}}}}}'` (or `'Bearer {{thelongtokenstringgoeshere}}'` is incorrect.

Also `{mode}` and `{type}` in the url need to be replaced with actual parameter (see example on the right side of the docs).

And not related by content-type and accept goes in header, not parameter. And

> Doing the same in javascript yields no result as there is simply no space to authorize. Headers do not accept Authorization as a legal header value and GET requests do not have bodies, so I am stuck.

Browser fetch have restricted permission. nodejs fetch does support any headers. And query parameter goes in the url `https://thing.com/?like=this&and=this`. Use `URLSearchParams` to correctly build it although for your specific endpoint and parameters it's not even needed.

**Comment by bluekytu** [comment]
Thank you for the help, it did get fixed. I was using {{access_token}} (thought the token had to be inside parentheses) 

About ```related by content-type and accept goes in header, not parameter. ``` The request doesn't work if they're in the header, so I had to put them in the parameters. Changed code:
```
verify = requests.post("https://osu.ppy.sh/oauth/token", data={"client_id": 13011, "client_secret": "secret, "grant_type": "client_credentials", "scope": "public"}, headers={ 'Content-type': 'application/json', 'Accept': 'application/json'})
print(verify._content)

```
This is with content-type and accept going in header which yielded me this error message:

```
'{"error":"unsupported_grant_type","error_description":"The authorization grant type is not supported by the authorization server.","hint":"Check that all required parameters have been provided","message":"The authorization grant type is not supported by the authorization server."}'
```

Continuing with content-type and accept in the parameters work perfectly fine

**Comment by nanaya** [comment]
> This is with content-type and accept going in header which yielded me this error message:

`data` parameter is form-encoded by default. And by passing content type json header as well the request won't be in correct format. Check the library documentation.

> Continuing with content-type and accept in the parameters work perfectly fine

That's because the parameters are then ignored.

Oh and one last thing, `.json()` is a thing (although it'll throw error if the response isn't proper json).

**Comment by bluekytu** [comment]
Alright, thanks a lot!

I'll close this issue now
