### ISSUE TITLE
 Things I did on my first day playing osu don't count on my profile, but they show in my recent.

### ISSUE THREAD

**Issue by anjellalo** [ppy/osu-web#8670]
Things I did on my first day playing osu! don't count on my profile, but they show in my recent. For example I got an S rank, it shows in recent but not in best performances or the pf area that shows the number of whatever rank plays you've had. My play still shows on stuff like beatmap global ranking tho. Also some badges I got then don't show either, but I got notifs for them and they show only in Recent.

**Comment by nanaya** [comment]
Assuming the reporter has name username in osu!, it looks like they were looking at wrong mode (and then discovered it later considering there are pinned scores for the other mode).
