### ISSUE TITLE
About suggestions for new UI

### ISSUE THREAD

**Issue by wanjiaXG** [ppy/osu-web#8680]
If delete class "header-v4__bg"，does it look better？
![p1](https://user-images.githubusercontent.com/26690346/156314119-449491b8-3a35-4cfa-8c32-cfcb78f93eb6.png)
![p2](https://user-images.githubusercontent.com/26690346/156314129-f35d4d58-8f1f-4560-9472-246cddd17346.png)
![p3](https://user-images.githubusercontent.com/26690346/156314141-824e8e2e-b8b3-4e0a-ae59-aa605374fe40.png)

**Comment by peppy** [comment]
@arflyte has said that it's intended to be there, but should probably provide rationale here

**Comment by TheDomco** [comment]
I would make it optional if you can't straight up delete, can look odd depending on the image

**Comment by peppy** [comment]
Things like this are never to be made toggles. If it's removed then it will be removed completely. Still waiting on a @arflyte response, no need for further discussion.

**Comment by arflyte** [comment]
I acknowledge that it looks odd for certain images for now. Working on a fix now.

**Comment by Walavouchey** [comment]
I think it might make sense to hide the duplicate banner when the real banner is visible, and make it appear again when you scroll down past the banner

**Comment by nanaya** [comment]
It's been changed to be effectively a colored blob of the original cover.
