### ISSUE TITLE
User title, username and flag name are missing slight drop shadow

### ISSUE THREAD

**Issue by Hiviexd** [ppy/osu-web#8682]
old:
![image](https://user-images.githubusercontent.com/62819481/156328131-60b8d2ab-ac0c-458b-8740-5b63f6ab59f3.png)

new:
![image](https://user-images.githubusercontent.com/62819481/156328173-1e127fe7-617d-4230-aaef-73c09889d6b3.png)

new one feels too flat and is harder to read, and it gets notably worse the farther you look at it from

**Comment by Hiviexd** [comment]
took a deeper look and it seems that username and flag name used to use the same drop shadow too.

adding a `text-shadow: 0px 1px 1px black, 0px 1px 5px black;` to `.profile-info__title, .profile-info__name, .profile-info__flags` should make it look better and closer to the original.

old: 
![image](https://user-images.githubusercontent.com/62819481/156452996-e0e73907-f6fb-4b53-b425-a19a8c57c8b0.png)
current: 
![image](https://user-images.githubusercontent.com/62819481/156453044-2ce975bd-fc0a-495a-8bf0-b1996ced4e3a.png)
proposed: 
![image](https://user-images.githubusercontent.com/62819481/156453204-507a7289-41df-4003-9ec3-b31db06605a8.png)

**Comment by peppy** [comment]
Proposed is definitely way too harsh against the new colour background. Leave that to @arflyte to decide on.

**Comment by arflyte** [comment]
Yeah, adding shadows to it, and probably tweaking the group colours.
