### ISSUE TITLE
Total Kudosu Earned font size too small

### ISSUE THREAD

**Issue by MrChompysaur** [ppy/osu-web#8698]
After the recent osu profile updates, the font size of the Total Kudosu Earned is now tiny  
![chrome_Tp63YCxOmC](https://user-images.githubusercontent.com/80795706/156833213-9ef68d67-caf3-4f58-a750-0c6fb33477aa.png)
compared to before 
![chrome_Dl9Oln2O5Y](https://user-images.githubusercontent.com/80795706/156833215-9e05bea0-f38f-4142-8614-ca5de0982893.png)
 
Was this intentional?

**Comment by respektive** [comment]
This has been fixed earlier https://github.com/ppy/osu-web/pull/8697. Gotta wait for next release to see the changes on the website.
