### ISSUE TITLE
Lao People's Democratic Republic not appearing in Country Ranking selection 

### ISSUE THREAD

**Issue by dailac-boiii** [ppy/osu-web#8699]
Was looking around country rankings when I found out that Laos does not appear on the country rankings list. The page still exists as the screenshot show [Fig.1], but you cannot access it through the menu [Fig.2]

[Fig.1]
![643AFAD0-4CC6-42FA-B432-FB94D14BD627](https://user-images.githubusercontent.com/62544788/156863285-9d1bbfdf-25e3-42d3-9c5d-63dfdb895c1c.png)
[Fig.2] 
![72673814-3387-4C67-9267-29E2F55F2B24](https://user-images.githubusercontent.com/62544788/156863520-8288f755-9286-40d0-a466-602967b9fff8.jpeg)
Device info: [Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Mobile/15E148 Safari/604.1]

**Comment by peppy** [comment]
Countries with very few players intentionally don't show up in the main dropdown. We add these on a per case basis.

**Comment by dailac-boiii** [comment]
Then is it possible for Laos to be included? Cuba is also included in the list with much fewer players
