### ISSUE TITLE
Discussion replies are visible in Modding History if parent discussion is deleted

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#8700]
![image](https://user-images.githubusercontent.com/35633093/156886648-b1ab23e9-eebb-4f50-ac9d-e8d9ea3d0b5d.png)
![image](https://user-images.githubusercontent.com/35633093/156886665-ebf77120-7abb-4cce-af94-bf01d421cab1.png)

Really shouldn't be visible still. 

links:
https://osu.ppy.sh/users/15376632/modding/posts
https://osu.ppy.sh/beatmapsets/1487999/discussion/-/generalAll#/2928352

**Comment by nanaya** [comment]
Do we want to actually delete them or make it behave like comments with replies still visible instead?

**Comment by RockRoller01** [comment]
It makes no sense to have them still show up (same for comments, but thats another topic)

**Comment by nanaya** [comment]
Though it is being done by at least reddit for something that "makes no sense".

**Comment by RockRoller01** [comment]
I personally have no clue why reddit does it, it often just leads to confusing comment chains. In addition to this, at least in cases where moderation removes the parent comment, the entire chain gets nuked to prevent people still going on about the same topic.

**Comment by nanaya** [comment]
because that would give the thread starter power to delete others' post if they don't like it
