### ISSUE TITLE
Small gap between the profile navigation bar and the website navigation bar

### ISSUE THREAD

**Issue by lolxdhi1** [ppy/osu-web#8701]
As you can see in this screenshot, there seems to be a very small gap (I think it's only a couple of pixels) between these two bars
![han5zwe](https://user-images.githubusercontent.com/47082567/156887603-6d5c579d-381f-489e-80ea-f87f220deb20.png)

**Comment by peppy** [comment]
Which browser are you seeing this happen on? I can't reproduce on safari at least.

**Comment by nanaya** [comment]
It's this chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=1076036

**Comment by notbakaneko** [comment]
I was going to test a workaround since I get this issue on Chrome at 100% (and only at 100%) zoom too, but it's stopped happening on my dev environment 👀

**Comment by nanaya** [comment]
check if you've got tournament banner or other stuff further changing the height... (and it may be a lost cause for profiles with tournament banner)
