### ISSUE TITLE
Closed bracket in link format get carried over in web chat

### ISSUE THREAD

**Issue by ZeroPyrozen** [ppy/osu-web#8711]
The close bracket get treated as part of URL if the user or BanchoBot use `(Text)[Link]` format to create URL. For example, if the link in the chat formatted like this `(Mamat)[https://osu.ppy.sh/u/3031177]` it will show this in web chat:

(Mamat)\[https://osu.ppy.sh/u/3031177]

![BanchoBot Example](https://pyrozen.s-ul.eu/EqsHZv2Y)

Thus, if user click it will include close bracket in URL bar.

**Comment by peppy** [comment]
I'd say we want support for this kind of url formatting in the web chat interface. It's pretty common.
