### ISSUE TITLE
Pack problem

### ISSUE THREAD

**Issue by ILovedDonuts69** [ppy/osu-web#8720]
So basically I was mapping a pack as usual for mania just for fun, and I made another pack for another pack of song. After I uploaded it, the first pack I made is weird or glitched. Please help me, this couldn't get off my head.

The image of the error:
https://imgur.com/a/vCJxun9

And this is the pack:
[beatmapsets/1686237](https://osu.ppy.sh/beatmapsets/1686237)

**Comment by peppy** [comment]
It looks like your beatmap is, as suggested by the error, too large. Please open it using the editor file menu and reduce the filesize to something sane.
