### ISSUE TITLE
Sometimes failed scores don't add to total score value

### ISSUE THREAD

**Issue by respektive** [ppy/osu-web#8721]
A friend of mine (https://osu.ppy.sh/u/7635621) played [this map](https://osu.ppy.sh/beatmapsets/998836#osu/2089071) and failed near the end but didn't gain any score from it. 
Screenshot from a statistics tracker app showing that he gained play count and other stats (even level like what), but no total score:
![image](https://user-images.githubusercontent.com/22381687/158013536-f99ca46a-f608-4cd0-9118-4645a96d892c.png)

This is giving the rather strange behavior that the level value does not match up with the total score value.
His total score value of `688,751,458,864` should correspond to his level being `106.618`. Instead, because his level did increase, it is now at `106.628`. Higher than what it is supposed to be.

**Comment by peppy** [comment]
Some beatmaps with inflated score values intentionally don't give total score increments. This will likely change once we move to the newer scoring system.

**Comment by respektive** [comment]
Alright, that's good to know. I didn't know this was also the case for ranked maps. :smile:

**Comment by peppy** [comment]
It is a bit of a weird one, but I don't think it's the right time to consider changing it when there are other larger changes amidst.
