### ISSUE TITLE
[REQ] An option for dont download storyboard and/or beatmap hitsounds

### ISSUE THREAD

**Issue by Likver** [ppy/osu-web#8737]
Just like we can choose if we want to download or not a beatmap video background id like to see an option/button to download only the beatmap and its song, without the map hitsounds (if it has) and the storyboard (if it has)

Id like to see that since i dont even use skin hitsounds and i dont have so much storage space so i need to manually delete it, and same with storyboards, i dont use them so i need to delete .osb files and SB folders.

Ill wait for it :)

**Comment by peppy** [comment]
I'd consider upgrading your hard drive. The elements you mention are usually very small and sometimes integral to the beatmaps. I don't believe we will offer this as an option.
