### ISSUE TITLE
osu! wiki infoboxes bleed over to subsequent headings

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu-web#8743]
Recent [clean-up work of the osu!supporter wiki article](https://github.com/ppy/osu-wiki/pull/7057) caused a sudden realisation that infoboxes don't quite play nicely with other elements and themselves.

Infoboxes don't push subsequent headings down.

![unknown (1)](https://user-images.githubusercontent.com/36758269/159819266-26e139b6-0fc4-4ed2-9c6e-0b4d38faca50.png)

Multiple infoboxes after each other should stack vertically. Arranging them horizontally like this would never be desired. Granted, combining the images into the same infobox is the correct solution, so this can be considered more of an edge case that would be a non-issue if the main issue was fixed.

![unknown](https://user-images.githubusercontent.com/36758269/159818777-5fead775-7140-4fa7-a679-67ee510b9812.png)

**Comment by peppy** [comment]
Let's mark this high priority so we don't need to revert the wiki-side changes.
