### ISSUE TITLE
Pinned comment should be unpinned when deleted

### ISSUE THREAD

**Issue by leSupaV** [ppy/osu-web#8744]
Happened after website gave the mapper the ability to pin their own comments in their maps.

Essentially, when you post a comment in your own mapset and pin it, then delete that said comment from your mapset while it's still pinned, you will be unable to pin any other comments after that.

**Comment by AncuL001** [comment]
pretty good first issue imho

**Comment by RockRoller01** [comment]
If you check "show deleted" it shows the comment with an unpin button

**Comment by leSupaV** [comment]
we are not GMTs.

**Comment by zeusminus** [comment]
You do not need GMT perms to do that, afaik. It was tested by a non-GMT user a while ago.

![](https://media.discordapp.net/attachments/276296389519081472/952916181591937094/unknown.png)

**Comment by AncuL001** [comment]
https://user-images.githubusercontent.com/16044057/159917533-80ec24bd-e44a-4a67-b552-1c674c117835.mp4

i'm unable to confirm that

**Comment by AncuL001** [comment]
oops. i forgot "show delete" checklist exists

would be nice if deleted message is unpinned by default tho

**Comment by leSupaV** [comment]
yep, exactly so. would be better if it's unpinned by default.

**Comment by notbakaneko** [comment]
It should probably unpin when deleted; I don't see a reason for deleted comments to stay pinned 🤔

**Comment by RockRoller01** [comment]
Yea they should get unpinned, just pointing out that it currently *technically* is possible, just not a great usage experience
