### ISSUE TITLE
Beatmap audio preview has weird noises at the end of the preview when using Firefox

### ISSUE THREAD

**Issue by james2323123** [ppy/osu-web#8748]
The same noise appears at the end of every song preview.
I've also tried using Chrome, it does not have the same issue.
I also saw someone else with the same issue on the forum post I made.

forum post:
[https://osu.ppy.sh/community/forums/topics/1540732?n=1]()

Video or screenshot showing the problem:
[https://drive.google.com/file/d/1PtMMwC80PQl-Wr7eQkF55zE3lbgq-oc9/view?usp=sharing]()

**Comment by nanaya** [comment]
It sounds just like audio cut off at unfortunate time? Especially as there's no fade-out applied. At least [the preview](https://osu.ppy.sh/beatmapsets/1596423#taiko/3263127) in the linked video sounds the same in chrome (and other audio players).

@peppy did you confirm the problem?

**Comment by peppy** [comment]
I didn't check, no. This is standard sample clipping caused by trimming in the middle of a peak on the waveform, and quite expected. Let's track this as part of #6459. We could add a fade as part of the reprocessing so this doesn't occur.
