### ISSUE TITLE
New syntax for image map

### ISSUE THREAD

**Issue by nanaya** [ppy/osu-web#8751]
A way to support something that's like [html map](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/map) would be useful. It won't use that exact syntax (because it's not responsive) but just an image and a bunch of absolute-positioned links. It'll be limited to rectangular links since otherwise the syntax will be rather unwieldy.

Something like this for the syntax
```
[imagemap]
imageurl
x y width height url1 optionaltitle
x y width height url2 optionaltitle
[/imagemap]
```

The bbcode editor will have a button to open a map editor where image can be specified and then the links can be added. Or maybe a dedicated page where the specific syntax above can be copy pasted around.

This will remove the need for #2060 by removing the need to deal with sliced images.

**Comment by solstice23** [comment]
HTML map has multiple types of areas(poly, circle and rect) rather than only rectangles, which can make collabs more flexible and customizable. Maybe we can draw up new syntaxes for these different types of areas?

**Comment by nanaya** [comment]
As mentioned in the starting post, it's not going to use map element due to it not being responsive.

**Comment by nanaya** [comment]
I guess the button and help link are good enough "frontend" for now 👀
