### ISSUE TITLE
APIV2 /beatmaps/{beatmap}/attributes incorrect response for all modes

### ISSUE THREAD

**Issue by Sebola3461** [ppy/osu-web#8755]
## Correct reponse (taiko for example):
<html>
<body>

stamina_difficulty | float
-- | --
rhythm_difficulty | float
colour_difficulty | float
approach_rate | float
great_hit_window | float

</body>
</html>

## Current response

```json
{
	"attributes": {
		"mods": null,
		"skills": null,
		"starRating": 10.09000015258789,
		"maxCombo": 0
	}
}
```
Query Params
`?mods[]=dt&ruleset_id=1`

**Comment by peppy** [comment]
Could you explain what you mean by "correct response"? Where are you getting that from?

**Comment by peppy** [comment]
Could you please try again? It should match now.

**Comment by Sebola3461** [comment]
![image](https://user-images.githubusercontent.com/62405013/161300468-732b1cfa-ef94-4da4-9a14-e9eeeb44abbe.png)
max combo is wrong

**Comment by nanaya** [comment]
I wouldn't be surprised if the database based version only handles fetching star rating value 👀

**Comment by smoogipoo** [comment]
Indeed looks to be the case: https://github.com/ppy/osu-beatmap-difficulty-lookup-cache/blob/996c7fc0aae1c2ec969f579fe2a4360acfb71029/BeatmapDifficultyLookupCache/DifficultyCache.cs#L75

**Comment by peppy** [comment]
There was actually an issue and I had to roll back immediately, will reopen until it's fixed.

**Comment by peppy** [comment]
@respektive please test again now.

**Comment by respektive** [comment]
Tested multiple ranked and unranked maps and the response is the same as before. Each map only shows the `star_rating` and `"max_combo": 0`.

**Comment by peppy** [comment]
Please try once more, you tried too quickly 😅

**Comment by respektive** [comment]
Yeah, now it's working correctly :+1:

**Comment by Sebola3461** [comment]
![image](https://user-images.githubusercontent.com/62405013/163580835-3dc85063-020a-49f6-aafc-beeccbaa91c2.png)
Add mods will be nice

**Comment by smoogipoo** [comment]
@Sebola3461 Has been fixed in https://github.com/ppy/osu-web/pull/8814, will be part of the next deploy.
