### ISSUE TITLE
Recieving homepage when authenticating

### ISSUE THREAD

**Issue by GreenJuzzy** [ppy/osu-web#8781]
When I try to authenticate a user thru Authorization Code Grant, I just recieve the home page of https://osu.ppy.sh/. Here's my code

```javascript
app.get("/auth", async (req, res) => {
    if (!req.query.code) return res.redirect(`https://osu.ppy.sh/oauth/authorize?client_id=${osu.id}&redirect_uri=${encodeURIComponent(`http://localhost:3000/auth`)}&response_type=code`)

    var body = {
        "client_id": osu.id,
        "client_secret": osu.secret,
        "code": req.query.code,
        "grant_type": "authorization_code",
        "redirect_uri": encodeURIComponent("http://localhost:3000/")
    }


    var headers = {
        "Accept": "application/json",
        "Content-Type": "application/json",
    };


    var data = await call({ method: "POST", url: `https://osu.ppy.sh/oauth/token`, body: { body }, headers: { headers } }) // Body is JSON.stringify'd
    res.send(data)
})
```

**Comment by respektive** [comment]
You want to stringify the body (like your comment suggests). Also not 100% sure about this, but I don't think you wanna put the headers object into another pair of curly brackets(?)

```js
var data = await call({ method: "POST", url: `https://osu.ppy.sh/oauth/token`, body: JSON.stringify(body), headers: headers }) // Body is JSON.stringify'd
```

**Comment by GreenJuzzy** [comment]
> You want to stringify the body (like your comment suggests). Also not 100% sure about this, but I don't think you wanna put the headers object into another pair of curly brackets(?)
> 
> ```js
> var data = await call({ method: "POST", url: `https://osu.ppy.sh/oauth/token`, body: JSON.stringify(body), headers: headers }) // Body is JSON.stringify'd
> ```

Ah, forgot that i dont need brackets with the body and headers, but now im just getting { error: null } when authenticating?

**Comment by GreenJuzzy** [comment]
Heres my full code, still recieve `{ error: null }`  when trying to get an access token for the code.
https://pastebin.com/6xDWWwj0

**Comment by Sebola3461** [comment]
can you send the recived html code?
