### ISSUE TITLE
Colors are wrong

### ISSUE THREAD

**Issue by BuySharp** [ppy/osu-web#8786]
![image_2022-04-09_223918](https://user-images.githubusercontent.com/70163582/162598811-5fc5281f-0102-432b-ad57-32997c5b2d39.png)
Some of the flags colors are weirdly shaded, my profile looks black instead of white as well
![image_2022-04-09_231404](https://user-images.githubusercontent.com/70163582/162599752-26be7194-b329-43aa-94a3-64ecdcfb98fb.png)

**Comment by peppy** [comment]
This looks like your browser is not correctly rendering the page. What browser are you using? Can you try a different one?

**Comment by BuySharp** [comment]
I am using Opera GX. I used Chrome and it works, don't know the issue with Opera

**Comment by jacksonisiah** [comment]
Are you using the Opera GX dark/light mode feature? Extensions like that seem to break stuff a lot across many different browsers.

**Comment by BuySharp** [comment]
> Are you using the Opera GX dark/light mode feature? Extensions like that seem to break stuff a lot across many different browsers.

Changing from dark to light or vice versa doesn't seem to fix the issue. Factory resetting does however.
