### ISSUE TITLE
`/beatmaps/{beatmap}/scores` endpoint doesn't work with mods

### ISSUE THREAD

**Issue by respektive** [ppy/osu-web#8808]
When I try to receive the scores on a beatmap for a certain mod combination like `https://osu.ppy.sh/api/v2/beatmaps/75/scores?mods[]=DT` I receive an error, stating I need to be an osu!supporter, which I currently am.

```
{
    "error": "You must be an osu!supporter to use this feature."
}
```

**Comment by peppy** [comment]
How are you using the api? ie. what grant or client type?

**Comment by respektive** [comment]
I'm using Client Credentials Grant.

**Comment by peppy** [comment]
I'm not sure if this is intentional or not, but I can say that supporter filters are not supposed to be queries via the API. We don't have the throughput for that (and would require you to pay probably 10-100x the cost of supporter to allow infrastructure to keep up).

**Comment by respektive** [comment]
fwiw this endpoint is also available in APIv1 and has no limitations there, that's why I was thinking it should probably work on APIv2. I understand that some endpoints, that are supporter only, won't be available via API like it's already the case for country/friend rankings on a map.

**Comment by peppy** [comment]
Given the direction we'll be taking things (ie. this kind of query should not be supporter only once the new infrastructure comes online aka ES lookups for scores), it should be fine to fix this one to work.
