### ISSUE TITLE
oauth2: callback uri doesn't support flexible query params and multiple uris

### ISSUE THREAD

**Issue by EthanDevelops** [ppy/osu-web#8811]
re: osu-web & osu-api
hey! when registering for an oauth2 app on osu! you have to input a redirect uri as per the oauth2 specification. 
something that could be helpful is to allow developers to use "flexible" query parameters in these redirect uris. 
example: lets imagine i have an app and you can log into the app using your osu! account anywhere in the app. 
this app has ~30 pages. from a UX standpoint, its way better to log in to the app and pick up on the page you left off. some oauth2 services allow this by using "flexible" query params. for example, an acceptable redirect uri could be: https://example.com/auth/callback?return=/previous/page and the redirect uri inputted when creating the oauth app could be: https://example.com/callback?return=* (* in this case meaning a wildcard). another nice feature could be the ability to add multiple redirect uris so you could have one for development (http://localhost:8080/auth/callback) and one for production (https://example.com/auth/callback) and maybe even more.

**Comment by cl8n** [comment]
in my own apps I store the referring page's URL before redirecting the user to auth with osu, then in the callback handler I redirect them to that stored URL. idk if that's normal or recommended but it's been working for me

for different redirects in dev vs. production, you should use different API clients

**Comment by EthanDevelops** [comment]
> in my own apps I store the referring page's URL before redirecting the user to auth with osu, then in the callback handler I redirect them to that stored URL. idk if that's normal or recommended but it's been working for me
I looked into this, however, on larger websites this is very inefficient and wouldn’t really work.

> for different redirects in dev vs. production, you should use different API clients
Since the API is not very complex at the moment, this is viable, but as the API becomes more complex its easier to test with the same client, although this varies on personal preference mostly

**Comment by EthanDevelops** [comment]
I don't know where to put this and no one will probably notice it (or use it) but I made this small sort of janky dev env script to install dependencies required to develop osu!lazer (on an Intel Mac) https://github.com/EthanDevelops/osu-dev-starter/blob/main/mac.sh

**Comment by peppy** [comment]
@EthanDevelops we're willing to look into adding this, but only if it's a pretty common thing that is done by other large oauth APIs. You mentioned that you've seen this done elsewhere – could you please link to a few examples?

**Comment by nanaya** [comment]
Looking into it a bit this page recommends not allowing flexible query params but use state instead

> Per-Request Customization
>
> Often times a developer will think that they need to be able to use a different redirect URL on each authorization request, and will try to change the query string parameters per request. This is not the intended use of the redirect URL, and should not be allowed by the authorization server. The server should reject any authorization requests with redirect URLs that are not an exact match of a registered URL.
>
> If a client wishes to include request-specific data in the redirect URL, it can instead use the “state” parameter to store data that will be included after the user is redirected. It can either encode the data in the state parameter itself, or use the state parameter as a session ID to store the state on the server.
https://www.oauth.com/oauth2-servers/redirect-uris/redirect-uri-registration/#per-request

**Comment by peppy** [comment]
@EthanDevelops can you try using the state parameter as above? it seems like a good solution which you can implement and use right away if it works.

**Comment by EthanDevelops** [comment]
I’ll see if that works, thanks so much for the help. I was trying out state but it didn’t seem to work but I’ll try again.

Also re: this
> I don't know where to put this and no one will probably notice it (or use it) but I made this small sort of janky dev env script to install dependencies required to develop osu!lazer (on an Intel Mac) https://github.com/EthanDevelops/osu-dev-starter/blob/main/mac.sh

I believe I fixed the errors and I’m working on a universal version

**Comment by EthanDevelops** [comment]
You can run `curl https://raw.githubusercontent.com/EthanDevelops/osu-dev-starter/main/mac.sh | sudo sh` (Or just sh) to start it

**Comment by EthanDevelops** [comment]
Everything so far is automated except the installation of Visual Studio which the script guides you through, it does require sudo access unfortunately

**Comment by peppy** [comment]
I'm going to close this issue as the responses are a bit off-topic, and we've proposed a workable solution.
