### ISSUE TITLE
descend map favorite's order by user's follower

### ISSUE THREAD

**Issue by roelyschaap12** [ppy/osu-web#8820]
<img width="395" alt="image" src="https://user-images.githubusercontent.com/103881956/163982262-5b6cb7b0-24ba-493f-bda5-c544ae6368e8.png">

In the old osu! website, favorites where ordered in a descending by account age.
In the new osu! website it's ordered based on nothing, just most recent favorites. which I think is backwards for those who where used to the old osu! beatmap page design. 

I suggest to descend this order based on the new parameter which is the amount of followers people have.
People don't care about random names they want to see popular ones upfront see what figures are interested in their maps.
And no doubt this is really easy to implement as you've to edit only one query.

**Comment by peppy** [comment]
I can agree with this. Not sure how efficiently it can be done without adding indices, but should be fine to apply if it can be done.

**Comment by nanaya** [comment]
Follower count doesn't exist on the database. It is cached externally but no way to use it easily apart for single user.

**Comment by peppy** [comment]
How about sorting by `user_id` to give older users precedence to display first? Might be a good interim solution, not sure.

**Comment by nanaya** [comment]
That seems like giving older user inherently higher priority for being displayed on that popup. Not sure if newer users would appreciate that.

**Comment by AncuL001** [comment]
the old site does sort by `user_id`. i doubt anyone would notice about how it's sorted, let alone care

sorting by `user_id` theoretically reduces the amount of default avatars on the favorite list + (imo) older users are generally more important. otherwise there's not much reason to prefer one over another if we're not able to use more concrete number like follower/mapper subscriber count

**Comment by notbakaneko** [comment]
Sorting by `user_id` sounds like beatmap favourites will eventually turn into a list of largely the same users - as soon as a user with an older account favourites something, it'll push other users out.

**Comment by peppy** [comment]
Let's leave as is for now, I think it's fairest.
