### ISSUE TITLE
Beatmap Discussion button moved, Bad UX

### ISSUE THREAD

**Issue by dudehacker** [ppy/osu-web#8825]
in a beatmap page like https://osu.ppy.sh/beatmapsets/1745942#mania/3571324

![alt text](https://cdn.discordapp.com/attachments/951524313763287071/966159398651191316/unknown.png)

There used to be a Discussion button on right side of osu!direct , but now its gone and moved to info | discussion on top, and on mobile its even harder to find.

can we pls undo this change? its really annoying causing a lot of people to click the osu!direct button instead cuz it is the new button on most right

**Comment by peppy** [comment]
The new location is a much more logical place for it to exist, so I don't think it should be moved/added back.

Could you give it a few more weeks (your brain should gradually adapt to changes like this).
