### ISSUE TITLE
Guest Participation Beatmaps list should be displayed under Ranked maps list, not pending

### ISSUE THREAD

**Issue by Hiviexd** [ppy/osu-web#8828]
it would make more sense to display them under the Ranked list because the GD list only has your ranked GDs, and it doesn't make sense to have that under pending for that reason.

**Comment by leSupaV** [comment]
I second this, it's a bit confusing considering that we have the hierarchy of ranked->pending->graveyard based on importance, so technically, gds that are ranked should be below ranked

**Comment by peppy** [comment]
To confirm, you just mean changing the ordering, right?

**Comment by Hiviexd** [comment]
Yes, just the display order of the lists.

**Comment by peppy** [comment]
I think that's fine to change, makes more sense for now at least.

**Comment by peppy** [comment]
Let's put it after Loved, rather than ranked, as it can have both of these included.
