### ISSUE TITLE
Hide online offset option for qualified beatmaps from BNs

### ISSUE THREAD

**Issue by apollo-dw** [ppy/osu-web#8832]
There is no reason for BNs to have access to this.

1. They can only access this panel for qualified and pending beatmaps.
2. Standard procedure is to disqualify maps with incorrect offset according to [some official wiki source which I lost the link to]:
> Issues that can be mitigated through online offsets, tags or similar must still be disqualified.
3. Therefore there is no use case for BNs

**Comment by AJT127** [comment]
Yes, I'd also consider this to be urgent seeing as people are abusing it already

**Comment by Ephemeralis** [comment]
One BN just got restricted for abusing this to change the online offset on an active qualified map to 2000, for the record.

This definitely needs to be limited to NAT only.

**Comment by Nivalyx** [comment]
wrote this earlier on one of the internal discussion channels, thought i'd post this here as well for visibility as it's also related to the issue in a slightly wider scope :

---

regardless of the current events i feel like at the moment the current setting is more accessible than it should be either way tbh. i mean there's no case of such abuse (yet) but as the setting can be changed by literally anyone on their own maps i can feel like it's just a matter of time before someone used the setting to alter their maps for malicious purposes

((think about how the [Toy Boxxx](http://osu.ppy.sh/beatmapsets/1569748) tourney map drama back then is technically replicable w/ this setting for example))

**Comment by Walavouchey** [comment]
> Standard procedure is to disqualify maps with incorrect offset according to [some official wiki source which I lost the link to]

https://osu.ppy.sh/wiki/en/People/The_Team/Beatmap_Nominators/Rules#disqualification

![image](https://user-images.githubusercontent.com/36758269/164534691-a6c34dc2-b2ae-499d-b5c7-0e0ce4f091d4.png)

**Comment by AJT127** [comment]
> wrote this earlier on one of the internal discussion channels, thought i'd post this here as well for visibility as it's also related to the issue in a slightly wider scope :
> 
> (...) regardless of the current events i feel like at the moment the current setting is more accessible than it should be either way tbh. i mean there's no case of such abuse (yet) but -- as the setting can be changed by literally anyone on their own maps -- i feel like it's just a matter of time before someone used the setting to alter their maps for malicious purposes
> 
> (think about how the [Toy Boxxx](http://osu.ppy.sh/beatmapsets/1569748) tourney drama back then is technically replicable w/ this setting for example)

agree + i'm semi-convinced this was just an unintentional oversight (i hope) in the first place since all of these abuse scenarios are pretty obvious, but forgetting that regular users will be able to change this when you implement it seems like something that could've happened

**Comment by UberFazz** [comment]
users can already destroy their own maps by setting the offset to anything they want just by doing it in the editor, don't think that's a valid point. but seeing how much of a nuisance abusing this actually is (by BNs), id say i agree with restricting it to NAT/GMT only

**Comment by cl8n** [comment]
needs a separate permission altogether, this isn't the same as other `BeatmapsetMetadataEdit` options in that it's only used to correct mistakes in the map. don't need the permissions for owner or BN, and nobody should be able to use it outside of ranked/approved/loved

**Comment by peppy** [comment]
should be admin only. no discussion required.
