### ISSUE TITLE
Rankings rows are not rounded

### ISSUE THREAD

**Issue by respektive** [ppy/osu-web#8833]
I'm on Firefox 99.0.1 and the rows on the rankings pages are not rounded anymore. I also tried on Chromium and they look normal there. I checked with the style inspector and there is a `border-radius` set to 4px, but changing it doesn't do anything. However, it does work on other parts of the page like the pagination buttons. :thinking: 

![](https://pek.li/l3qu77.png)

**Comment by bdach** [comment]
related: https://bugzilla.mozilla.org/show_bug.cgi?id=706766
