### ISSUE TITLE
Mapper on beatmap info redirects to wrong user

### ISSUE THREAD

**Issue by respektive** [ppy/osu-web#8837]
The mapper of [this beatmap](https://osu.ppy.sh/beatmapsets/3#osu/91) has the **user_id** `141`. However, clicking on the mapper redirects you to the profile of a person with the **username** `141`.

![image](https://user-images.githubusercontent.com/22381687/164713738-9c935e76-f2f8-4701-9d7c-e083e12c13a4.png)

**Comment by peppy** [comment]
This is really weird. Did something regress with user links? I thought that IDs are always preferred to usernames for the new routing..

**Comment by nanaya** [comment]
the user is deleted and due to regression, the link is still created and it falls back to username look up (to be fixed by #8802 )

**Comment by nanaya** [comment]
Should be fixed on next release.
