### ISSUE TITLE
Allow mapper to edit difficulty owner after map is Ranked

### ISSUE THREAD

**Issue by MkGuh** [ppy/osu-web#8839]
This will be good to address a few issues with the new GDs on userpage feature.

**Comment by venix12** [comment]
GMT/NAT is able to do that already, can probably just poke one of them if really in need?

**Comment by RockRoller01** [comment]
I have the feeling that someone would start adding unrelated people to their diffs, since unlike qualified there no longer is someone double checking that no one does nonsense. So probably best to leave to NAT/GMT?

**Comment by MkGuh** [comment]
> I have the feeling that someone would start adding unrelated people to their diffs, since unlike qualified there no longer is someone double checking that no one does nonsense. So probably best to leave to NAT/GMT?

Just a quick note @venix12 @RockRoller01 @peppy , currently the users are able to edit their own beatmap descriptions, even after the map is Ranked for years, and I'd assume no one is checking those either, so wouldn't the GD thing maybe follow the same logic?

**Comment by peppy** [comment]
Beatmap descriptions should not be editable post-rank. We've had many cases of abuse there. I'll look into changing this.

**Comment by MkGuh** [comment]
> Beatmap descriptions should not be editable post-rank. We've had many cases of abuse there. I'll look into changing this.

Did not want to see this getting changed... It is a pretty useful feature. Maybe make it so the mapper can edit but it is only applied upon approval by a staff member?

**Comment by peppy** [comment]
If you have an edit to make that is required, you can contact a NAT or GMT member as with other things.
