### ISSUE TITLE
1000 Favorite maps limit

### ISSUE THREAD

**Issue by dudehacker** [ppy/osu-web#8840]
can you add a new supporter pack which increase the fav map count? I want add more maps to my fav, so if my SSD is destroyed i can get all the maps back.

normal user = 100 favs
supporter = 1000 favs

when i got to 1000 favs it gave me this error:
![alt text](https://cdn.discordapp.com/attachments/937473688180252712/961687901643624489/unknown.png)

**Comment by dudehacker** [comment]
but im mainly using it like bookmark. 

a use case is i found a map on phone, cant play it right now. but want play it later, so i add it to fav and when i have pc later i can easily find it and play.

**Comment by Nivalyx** [comment]
hmm if that's the case then i would also be inclined to agree with peppy i suppose, in a sense that "that's not really how favourites is intended to be used" -- sure enough you can use the favourite button to mark maps but... ultimately favourites aren't made to be bookmarks so yeah

that being said i'm all for increasing fav maps limit if there's an *adequate* reason to do so tho. it's just i feel like this reasoning isn't it

**Comment by dudehacker** [comment]
i also like a lot of maps, and i want mappers to know that so they feel encouraged to map more.
i dont think a map has the best map ever for you to consider that fav worthy? if that's the case shouldn't there be a simple like/bookmark button, or save your in game playlist to server? 

If i fav 1 map per day, after 3 years im will hit limit. and many people been playing osu for longer than that.
here's an example of another user with 926 fav soon to hit limit: https://osu.ppy.sh/users/9014584

i also have 5k+ bookmarks on pixiv, don't even need premium for that.

what is the intended use of favorites?
what do you consider a valid reason to increase the limit? 
does increasing limit create huge technical trouble? does it require a long period of time to develop? or huge cost increase?

1 issue with played maps is just cuz i played a map doesnt mean i like it, doesnt mean i want play it again later, its not a replacement for a bookmark/like system

**Comment by zkdkrkwhdk** [comment]
I agree with dudehacker.
I need more fav space too.

Old users could have this problem.
I don't understand why finite value like 100 or 1000 is ceiling.

As time goes by, the number of beatmaps will increase.
There's many good and impressive beatmap in osu for me.
I'll always check them as favorite beatmap.
Because pressing fav is also a way of showing respect and appreciation to me.

This problem should be reformed.

**Comment by Sun-osu** [comment]
I think many users agree with DH on this issue.

Actually, I'm not a big user of favorites, but I have more than 400 favorites.

As DH mentioned above, in a few years, I will reach the limit, and my favorite maps will increase.

I believe that for whatever reason this matter should be reformed

**Comment by Paran777** [comment]
Is there a reason why the 1000 Favorite Maps limit that is set for the user should not be lifted? For sites such as Pixiv, there are no additional restrictions. If it doesn't matter, please lift the restriction

**Comment by DenYiDesu** [comment]
I agree with DH.

I also don't know why the Favorite maps limit is small. I don't think it's a good idea to set a limit on your favorite and impressive maps.

**Comment by peppy** [comment]
See https://github.com/ppy/osu-web/issues/5510 for existing discussion.
