### ISSUE TITLE
Clicking a modding discussion reply notification brings you to the main post

### ISSUE THREAD

**Issue by apollo-dw** [ppy/osu-web#8843]
i remember this behaviour was correct at some point in the past - i'd expect it so that i don't have to scroll down to the reply

https://user-images.githubusercontent.com/83023433/164974770-74daeefd-13e9-4cc8-add8-fdc3e191c69d.mp4

**Comment by nanaya** [comment]
It has always been like that. It does make sense to link to the post though.
