### ISSUE TITLE
play history dates don't show correctly when translated to spanish

### ISSUE THREAD

**Issue by Gonzalo-Bruna** [ppy/osu-web#8845]
I think this might happen with other languages as well, I can't see the date at all in the play history section in user profiles, since the year is cut off

![image](https://user-images.githubusercontent.com/41755816/164983076-b756e0ad-81fc-4af6-a4e8-0509bd34ef5c.png)

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu-web/issues/6896

**Comment by Gonzalo-Bruna** [comment]
ah sorry, I couldn't find the issue.
