### ISSUE TITLE
Forum thread repeats posts

### ISSUE THREAD

**Issue by abraker95** [ppy/osu-web#8846]
I found a forum thread that has a set of posts repeated if you link directly to one of the posts. For example, [if you follow this post](https://osu.ppy.sh/community/forums/posts/7062759) and scroll around the thread, you would notice that at some point an older post will be placed after a newer post, and a bunch of posts would repeat. The point at which it repeats seems to vary based on the post being linked. This does not happen when using [a link to the thread](https://osu.ppy.sh/community/forums/topics/167932) instead.

**Comment by Walavouchey** [comment]
it does seem to add extra posts at some point when you scroll

https://user-images.githubusercontent.com/36758269/164992629-9c311a60-f790-441c-86db-c264db7f065a.mp4
