### ISSUE TITLE
Broken beatmap submission | Empty metadata and non-existent beatmap listing

### ISSUE THREAD

**Issue by Ja-syn** [ppy/osu-web#8847]
I uploaded a beatmap to my userpage thenceforth there was an error on the website. It shows as unsubmitted on the client and as said on the title there is no beatmap listing nor metadata. This is likely due to the difficulty name.

My profile: https://osu.ppy.sh/users/16777307

![e](https://user-images.githubusercontent.com/104329546/165001254-4dc4afe6-b68d-4d75-a592-021785daa271.png)

**Comment by peppy** [comment]
It looks like you have already had this resolved. Let us know if you have any further issues.

**Comment by Ja-syn** [comment]
It is still not resolved.

**Comment by peppy** [comment]
Where are you seeing this? I can't see either beatmap on your profile page.

**Comment by Ja-syn** [comment]
My username is Jasyn.

**Comment by peppy** [comment]
Thanks for updating the profile link to the correct user. I'll take a look into this.

**Comment by Ja-syn** [comment]
My bad, I also added on the original post the possible cause of this.

**Comment by peppy** [comment]
I've fixed these, please try submitting fresh.

**Comment by Ja-syn** [comment]
I resubmitted, yet the same happened.

**Comment by peppy** [comment]
Please attach the beatmap here (rename to .zip). It must be broken in some way.

**Comment by Ja-syn** [comment]
[Dante Red vs. Ericdoa - finale.zip](https://github.com/ppy/osu-web/files/8626280/Dante.Red.vs.Ericdoa.-.finale.zip)

**Comment by peppy** [comment]
Yes, I don't believe it will work. Please try a different one which uses english characters only.

**Comment by peppy** [comment]
Will close this for now.
