### ISSUE TITLE
When switching between difficulties, discussion page goes to General (All) instead of the timeline of said difficulty

### ISSUE THREAD

**Issue by Hiviexd** [ppy/osu-web#8857]
self-explanatory, this makes the modding process pretty counter-intuitive when switching between diffs, forcing you to switch AND select the timeline instead of just switching like before.
here's a demonstration:

https://user-images.githubusercontent.com/62819481/165444075-a9f532a0-beb4-40d6-91e1-f8493df26ab4.mp4

most likely an unintentional side-effect from #8853

**Comment by peppy** [comment]
Should fix this as a priority, seems like an annoying regression.

**Comment by nanaya** [comment]
Would keeping whatever currently selected tab make more sense?

**Comment by peppy** [comment]
Yeah, I think that's how it should work.

**Comment by nanaya** [comment]
There was request to make it always go to timeline when switching difficulties few years ago: #3442.

**Comment by peppy** [comment]
Good find, maybe we should respect that then..
