### ISSUE TITLE
Adding a new line in Review should not always defaulted to highest difficulty

### ISSUE THREAD

**Issue by EriosTahv** [ppy/osu-web#8860]
This is a rather annoying behavior because everytime a new line of suggestion/problem are added, I need to select the difficulty again and again. It should always stay to the last difficulty selected.
![firefox_2022-04-27_14-09-04](https://user-images.githubusercontent.com/17510971/165462946-1e425df3-7f22-4683-bb5e-b87d902d64e9.gif)

**Comment by nanaya** [comment]
if you press enter inside the box, a new box will be created with same difficulty.

**Comment by EriosTahv** [comment]
ah okay. also didnt know the selected diff page are also affected to the review.
