### ISSUE TITLE
Playback with some crackles

### ISSUE THREAD

**Issue by mateusmoov** [ppy/osu-web#8861]
Some days I noticed this happening
In the final seconds of the playback you can hear some crackles
This issue is only happening in Firefox

https://user-images.githubusercontent.com/49696764/165556404-aad76677-51b7-4ed0-8f7c-d60279baf234.mp4

.

**Comment by mousesalt** [comment]
occured to me as well, especially using earphone

**Comment by Nivalyx** [comment]
this has been reported before in http://github.com/ppy/osu-web/issues/8748, with the issue currently being tracked in http://github.com/ppy/osu-web/issues/6459 i think

**Comment by peppy** [comment]
The issue covered there is slightly different (involves one click at the end of the preview). The one in this thread seems like a firefox bug. I'd report to firefox, there's little we can do.

**Comment by Rekunan** [comment]
idk if this was in their latest update, but this issue on Firefox is reduced to just the one click at the end now

**Comment by mousesalt** [comment]
thie issue is fixed on my side
