### ISSUE TITLE
Mappacks changing color on completion

### ISSUE THREAD

**Issue by Chibu68** [ppy/osu-web#8864]
It's been mentioned before in request #2548, but it's been 4 years and I don't know if necroposting is appropriate as the issue seems to be abandoned, so I'm making a new issue. I think it would be cool if mappacks changed color upon completion, just like the clear circle. In my opinion, it would feel more rewarding to complete a mappack and it would become way easier to keep track of them. The images below are a suggestion as to what it could look like.
![image](https://user-images.githubusercontent.com/62471871/165720359-fd67c039-b09c-4591-a153-bb570775ae18.png)
![image](https://user-images.githubusercontent.com/62471871/165720387-aed97b16-a5df-4974-8128-d9750e5b156d.png)

**Comment by peppy** [comment]
Could you please make a post in the original thread. We prefer "necro-posting" to creating duplicate issues.
