### ISSUE TITLE
`/v2/users/{user}` is missing individual hit counts

### ISSUE THREAD

**Issue by respektive** [ppy/osu-web#8869]
The apiv1 endpoint shows hit counts for 300s/100s/50s, whereas the apiv2 only has the total amount of hits.

apiv1
![](https://pek.li/m0o3x8.png)
apiv2
![](https://pek.li/1hr1ga.png)

**Comment by nanaya** [comment]
How's this going to be handled for new scores? Does `count300` currently include `perfect`/`countgeki` for mania? (and `count100` for `good`/`countkatu`?)

**Comment by peppy** [comment]
Rather than matching the v1 spec, exposing all the new hit types (ie. after mapping legacy types to the new naming/structure) is fine.

**Comment by peppy** [comment]
Shouldn't mania perfects come from `geki` count?

https://github.com/ppy/osu/blob/aac2aa341cf879c66e7b802d6d9a2ce1d1c3e890/osu.Game/Scoring/Legacy/ScoreInfoExtensions.cs#L10-L29

**Comment by nanaya** [comment]
There's no such data in user stats table (`osu_user_stats` etc)...

**Comment by peppy** [comment]
Right, sorry. I was missing the fact that these are the user-level summary totals.

In that case I think the mapping is still fine, as it is best-effort (ie. it's fine if osu!mania `perfect`s are included in the `great` count).
