### ISSUE TITLE
Change "Đang chờ & WIP" to "Đang Chờ" in Vietnamese in osu!web

### ISSUE THREAD

**Issue by cuhoangdk** [ppy/osu-web#8870]
WIP mean "Chưa xong" in Vietnamese so fix this please

**Comment by Walavouchey** [comment]
you can change this at [osu!'s crowdin page](https://crowdin.com/project/osu-web). this is mentioned in the `README.md` file ([front page of the repository](https://github.com/ppy/osu-web))

**Comment by cuhoangdk** [comment]
i can't find it in clowdin page

**Comment by Walavouchey** [comment]
i've found it for you by copy-pasting "Đang chờ & WIP" into the search box (from the main page, select the language, click "Translate all" and then find the search box to the top left)

https://crowdin.com/translate/osu-web/all/en-vi?filter=basic&value=0#q=%C4%90ang%20ch%E1%BB%9D%20
