### ISSUE TITLE
Can't search with more than 2 commands in osu!web

### ISSUE THREAD

**Issue by cuhoangdk** [ppy/osu-web#8872]
I can't search 2 or more commands (ex: mode=o key=4 bpm=175) in osu!web but i can do it in Client
Can you fix this?

**Comment by bdach** [comment]
It's not about the count. `mode=o` is not a supported filter.

https://github.com/ppy/osu-web/blob/5e9efc2a3585e1a7e2a25330369d2e0250bc4f5a/app/Libraries/Search/BeatmapsetSearchRequestParams.php#L210-L225

By "client" I assume you mean stable, not lazer, correct? lazer also doesn't have this filter.

**Comment by cuhoangdk** [comment]
why don't you (or someone else) remove this in lazer and don't even add it in osu!web?
can you add this in next update?

**Comment by Walavouchey** [comment]
you can simply click on these buttons when searching, which works both on the website and in lazer

![image](https://user-images.githubusercontent.com/36758269/166236484-72ac7a0c-4ce9-4377-a9e1-1f0fe5578f97.png)

**Comment by cuhoangdk** [comment]
this can't search just converted map and not included the original mode map
