### ISSUE TITLE
image issue on comments section

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu-web#8883]
https://osu.ppy.sh/comments/2025758
https://osu.ppy.sh/comments?user_id=12012218

![chrome_6pVEl6aUG2](https://user-images.githubusercontent.com/21735205/167471224-6b7c8258-6c73-4480-bc1c-a33dbd708883.jpg)
![chrome_weDSBQJNlq](https://user-images.githubusercontent.com/21735205/167471229-8276e2f8-2078-4378-b072-19d031c65f0f.jpg)

**Comment by RockRoller01** [comment]
seems to potentially be a browser issue, i am on firefox and it shows just fine in both places for me
![image](https://user-images.githubusercontent.com/35633093/167485433-2c33d0ff-6408-4584-8cfc-a050d75527fa.png)
![image](https://user-images.githubusercontent.com/35633093/167485479-02effcd8-a6e4-4fe3-bd29-ae7bbe5b8f6c.png)

**Comment by notbakaneko** [comment]
This seems to be Blink/Chrome issue; it's fine on Safari as well.

**Comment by nanaya** [comment]
Being only on specific configuration aside, this isn't really a supported use case.
