### ISSUE TITLE
`/beatmaps/{beatmap}/scores` can only return 50 top scores

### ISSUE THREAD

**Issue by Wieku** [ppy/osu-web#8884]
In my case I need to get 51 scores to possibly filter out the score I already have on hand and still have top 50 plays.

APIv1 allowed retrieving up to top 100 scores using `limit` parameter:
`https://osu.ppy.sh/api/get_scores?k=x&b=3525928&limit=51`

But it seems that APIv2 equivalent doesn't have that parameter and always returns 50 scores if possible.

**Comment by peppy** [comment]
This is fine to add, with the default being 50.
