### ISSUE TITLE
Facebook link of IAHN's FA page is broken

### ISSUE THREAD

**Issue by burnerbunny** [ppy/osu-web#8885]
https://osu.ppy.sh/beatmaps/artists/3
https://www.facebook.com/jungmin.lee.52643821
seems like he ~~deleted his facebook page~~ changed his url
new url: https://www.facebook.com/I1AHN
![image](https://user-images.githubusercontent.com/96855131/167519517-02092886-6476-4731-852b-cd19c42039a4.png)

**Comment by peppy** [comment]
@Ephemeralis one for you.

**Comment by Ephemeralis** [comment]
I've nulled out the broken link for now instead of replacing it with the link above, since the profile doesn't appear to have any obvious linkback to his artist identity (if it's even the artist at all). Will reach out via email to confirm.
