### ISSUE TITLE
v2 endpoints return error

### ISSUE THREAD

**Issue by cyperdark** [ppy/osu-web#8886]
/beatmapsets/{beatmapset}/favourites
```json
{"error":"Invalid action"}
```
![image](https://user-images.githubusercontent.com/21735205/167541644-965bed64-c6c6-47a3-a0f1-1e63032d28a2.png)

/me/download-quota-check
```json
{"error":null}
```
![image](https://user-images.githubusercontent.com/21735205/167542172-1f5cf29a-5bf3-430b-abaa-c536584a607f.png)

/notifications/mark-read

returning empty string and notifications still unreaded
```json
""
```
![image](https://user-images.githubusercontent.com/21735205/167542383-16c6299d-abd0-4460-aa79-dc48432c8c34.png)

**Comment by nanaya** [comment]
what's the status code? also all those endpoints are lazer only

**Comment by cyperdark** [comment]
/beatmapsets/{beatmapset}/favourites
422

/me/download-quota-check
404

/notifications/mark-read
204

i know that they lazerr only, other endpoints return json data or mark as read (chat message)

**Comment by nanaya** [comment]
> /beatmapsets/{beatmapset}/favourites 422
> 

as per status and error message, invalid parameter was specified (or more like it's missing required parameter).

> /me/download-quota-check 404
> 

there's a bug here.

> /notifications/mark-read 204
> 

the parameter has been changed and documentation hasn't been updated to reflect it. The response is still 204 because that's all it returns.

**Comment by cyperdark** [comment]
oh  ``/beatmapsets/{beatmapset}/favourites`` should have ``action`` query parameter, i thought its was returning list of beatmap favourites but its favorite or unfavorite specified beatmap

**Comment by cyperdark** [comment]
``/me/download-quota-check`` working, and i fixed issue with ``/beatmapsets/{beatmapset}/favourites``
but ``/notifications/mark-read`` are not mark notification as readed
![image](https://user-images.githubusercontent.com/21735205/167971614-de619cf8-2401-482d-a5db-efe48094535f.png)

**Comment by nanaya** [comment]
> but `/notifications/mark-read` are not mark notification as readed 

I don't know what you're expecting trying the same parameter after I said

> the parameter has been changed and documentation hasn't been updated to reflect it

**Comment by cyperdark** [comment]
ah, sorry
