### ISSUE TITLE
A beatmap is still pending after 2 nominations

### ISSUE THREAD

**Issue by Hiviexd** [ppy/osu-web#8899]
map is single mode, so it's supposed to be qualified with 2 nominations
![image](https://user-images.githubusercontent.com/62819481/168469408-acd806b4-4169-499f-b47a-9aa62d7fb6a2.png)
![image](https://user-images.githubusercontent.com/62819481/168469411-19d7f05f-152b-4f53-a9c5-9c764375ded5.png)

map: https://osu.ppy.sh/beatmapsets/1749823#taiko/3579780

**Comment by Sebola3461** [comment]
bro

**Comment by nanaya** [comment]
There's slight database table problem.

@peppy the beatmapset table has `approvedby_id` as `mediumint` which is not enough for current user ids. It needs an update to match current user id type.

Also I noticed the nomination process isn't wrapped in transaction, resulting partial failure during nomination 🤔

**Comment by peppy** [comment]
I've applied a database fix to the table (should make a laravel migration to match it).

@nanaya are you able to fix the nomination in question? Or should we reset the status and have the nominators re-hit the button?

**Comment by nanaya** [comment]
I'll just rerun the qualification process.

**Comment by Hiviexd** [comment]
looks like it's fixed now, thank you for your attention
