### ISSUE TITLE
Incorrect name rendering

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#8912]
I have noticed a couple of times that the user [ - Nezuko - ] sometimes gets displayed as [--Nezuko-]
![image](https://user-images.githubusercontent.com/35633093/168659649-afe8ca76-544b-4949-9fc1-719930f7d99e.png)
![image](https://user-images.githubusercontent.com/35633093/168659669-c146e484-a3fc-4bd8-938f-fd78c7e39293.png)

Doesn't happen all the time

**Comment by nanaya** [comment]
Are you using some browser extension? Does it still happen with it disabled?

**Comment by RockRoller01** [comment]
I would love to test, but it only happens very rarely, so i cant just disable them to make it happen again. IIRC i havent just seen it go wrong on the forum but also userpage. Will try if i can replicate soon:tm:

**Comment by peppy** [comment]
Going to close this for now as there's absolutely no way I can see this happening from our end.

@RockRoller01 if it happens again, please save and provide the page source.

**Comment by RockRoller01** [comment]
Will do
