### ISSUE TITLE
broken beatmap link

### ISSUE THREAD

**Issue by supremeboi324** [ppy/osu-web#8917]
Hey,

I am trying to download this one map that I wanted to play real badly: https://osu.ppy.sh/beatmapsets/15006#osu/58359

But the link is broken for it for some reason, I am unable to get it. But when I try getting an osu simulation of the map, theres actually a simulation, meaning the map does exist. If you are able to fix this link, I would greatly appreciate it. I've been meaning to play this map for months, but I couldn't find out why I couldn't download it.

Thanks

**Comment by Nivalyx** [comment]
this is actually intended iirc. unlike ranked/loved/approved maps, graveyarded maps aren't meant to be "permanent" and according to [this thread](http://osu.ppy.sh/community/forums/topics/49310) "graveyarded maps which have not been updated in a long period of time will no longer be downloadable" :

![image](https://user-images.githubusercontent.com/36564236/168804411-01255d38-87b5-4b29-90d6-19376e4c37c4.png)
