### ISSUE TITLE
[Minor] "home/download" button css error

### ISSUE THREAD

**Issue by leonekmi** [ppy/osu-web#892]
### Minor issue
![Image](http://i.imgur.com/LvuXZeF.png)
As you see on the screen, the download button is out of his normal position.

**Comment by nicholastay** [comment]
Seems to be firefox specific - tested on my computer, correct alignment in chrome but misaligned on firefox. Will try to dig the css element

**Comment by Capuno** [comment]
#904

**Comment by nanaya** [comment]
Fixed.
