### ISSUE TITLE
Variable cost for throttle middleware

### ISSUE THREAD

**Issue by notbakaneko** [ppy/osu-web#8920]
The current `Throttle` middleware pretty much assigns a fixed cost per request; ideally, we'd want to be able to assign a variable cost per request or be able to selectively increment the throttle counter during the request for operations like batch queries.

**Comment by peppy** [comment]
Potentially related: https://github.com/ppy/osu-web/issues/8800 https://github.com/ppy/osu-web/issues/7351 https://github.com/ppy/osu-web/issues/6839
