### ISSUE TITLE
The "Spotlights" label should be coloured green to follow the colour scheme of the Rankings page

### ISSUE THREAD

**Issue by Nivalyx** [ppy/osu-web#8924]
this is more of a suggestion rather that an "issue" i reckon, but

![image](https://user-images.githubusercontent.com/36564236/169032746-a3f4df2a-6ddc-454d-8c0a-87c665bb4fac.png)

since the "Featured Artist" label is coloured blue (which matches the color of http://osu.ppy.sh/beatmaps and http://osu.ppy.sh/beatmaps/artists) shouldn't the "Spotlights" label be coloured green to match the color of http://osu.ppy.sh/rankings and http://osu.ppy.sh/rankings/osu/charts?

i feel like -- aside from the consistency aspect -- the pink colour should be reserved for tournament maps tho (if [#8436](http://github.com/ppy/osu-web/issues/8436) goes through) since tournaments are currently placed under http://osu.ppy.sh/community...

**Comment by venix12** [comment]
it was coloured pink to match lazer's spotlight marker

**Comment by peppy** [comment]
@arflyte thoughts on this one? i was also a bit startled by the pink being used here, but the lazer precedent did validate it in my mind.

**Comment by arflyte** [comment]
I don't remember about this lol. We can use green for spotlights from now on.

**Comment by peppy** [comment]
Are you saying green is a better choice, or that either/or is fine?

For reference, this is how the colour is currently used in lazer:

![osu! 2022-05-19 at 07 04 58](https://user-images.githubusercontent.com/191335/169231072-f8e12714-5589-4b4c-8d03-26f6bb7daf08.png)

**Comment by arflyte** [comment]
Yeah, if there's no objection, thinking of having Spotlights changed to green. Let's reserve pink for something else.
