### ISSUE TITLE
Add a way to assign spotlight tag 

### ISSUE THREAD

**Issue by venix12** [ppy/osu-web#8927]
got told to open an issue for this one 🤨 

Currently, assigning a spotlights tag requires manual re-indexing beatmapset, which isn't wanted from what i know. There should be a way to do it, either by on-site controls (similar to nsfw tag) or some kinda script.

Would be appreciated if i'd be able to assign it (or spotlights team in general?).

**Comment by peppy** [comment]
The reason I asked for an issue to be made is before adding UI controls to do this, I wanted to better understand the use case. From my understanding, spotlights are going to involve 10+ beatmaps being added in one go, and always as part of a larger release process.

If it makes more sense, we could implement this as an api endpoint and skip requiring the UI overhead. Or if it's something which is going to involve a manual switch from our end (ie. also flagging the playlists in lazer as spotlight), it can potentially be automated as part of that process.

**Comment by venix12** [comment]
Sounds about right probably, but keep in mind that we wanted to add the label to older spotlights (pre-lazer era) as well. (this probably could be done as a separate bulk insert, just as the first wave though, if you don't mind reindexing those afterwards again 🚶 )

**Comment by peppy** [comment]
Yeah, I can deal with that (you can attach a list of IDs to this issue when ready and I'll process them).

Will assign this to myself to track adding the automatic tagging to existing spotlight processing automation.

**Comment by Ephemeralis** [comment]
Latest batch of IDs (already set to ```spotlight = 1```):

```1507229,1344501,1257525,1473006,1671498,1004248,1524556,1591460,1262446,1581561,1118054,1549374,1283761,1331332,452051,1526077,1506936,1496486,1368447,1583701,1625860,857537,777109,601392,332623,1134081,1560368,782749,1665442,838465,1452883,1305627,1477789,228853,1647221,1561114```

**Comment by Ephemeralis** [comment]
Another batch of IDs (already set to ``spotlight=1``):

```1670776,1058659,1672934,1464050,795140,1557716,1060239,1197597,1715489,643492,1484214,1634301,1668744,1678197,1469387,1530955,1698611,1393508,880513,1176960,1244353,139525,1375156,1007778,1018035,1080025,668691,693381,531090,1359629,1152802,1604725,1722448,473736,1128753```

**Comment by Ephemeralis** [comment]
Yet another batch of IDs (also ```spotlight=1```):

```1564795,1602654,1405913,223092,503978,1567554,1347840,1601852,1605822,1587293,1622545,1629336,1469612,1228198,1631743,1581561,1573592,1606407,1560338,1636276,1511787,1543977,1361768,1517608,1633104,74671,1383242,1128596,1656541,1481796,1681210,1258120,923488,1310705,1489897,400078```

**Comment by Ephemeralis** [comment]
A big batch this time (```spotlight=1``` as usual):

```716193,1665328,1629444,995205,1351876,727333,1429536,704541,993369,455092,1403009,1236025,1729551,1724847,773708,777597,1786386,1631947,960656,1686741,1198383,1762601,1596364,1751193,1407228,1726306,1726063,1767410,1155202,1732016,1630732,1589361,1730764,1722957,1693010,1596423,887380,922835,838989,1460069,1621606,1391197,1090079,1744475,1557240,1599662,1110955,1109546,1467467,1635006,1621981,1554550,114741,1722551,166146,1726083,1566347,1061174,1150451,1267752,1683567,361643,1608837,1275180,1624402,1027900,733774,1281691,1738026,1272922,613792,1666003```

**Comment by Hiviexd** [comment]
Wouldn't it be more productive to make a simple UI for this and allow people in some sort of a spotlights usergroup to assign it?

This would also give spotlight team members more presence in the communty and would directly increase incentive and importance of the role (and might even help waith making people take it more seriously as a role)

Also this might be far-fetched but thoughts on adding a "Spotlighted by" text right under "Nominated by" in beatmap discussion? this would furthermore increase incentive like I mentioned earlier.

**Comment by peppy** [comment]
> Wouldn't it be more productive to make a simple UI for this and allow people in some sort of a spotlights usergroup to assign it?

I always choose the most efficient path, but due to the seldom request here, it is definitely not more productive.

> This would also give spotlight team members more presence in the communty and would directly increase incentive and importance of the role (and might even help waith making people take it more seriously as a role)
> 
> Also this might be far-fetched but thoughts on adding a "Spotlighted by" text right under "Nominated by" in beatmap discussion? this would furthermore increase incentive like I mentioned earlier.

I'm not against this but it requires dev time. If you're able to help that would be appreciated.

**Comment by venix12** [comment]
Eph is not around so need ``spotlight=1`` on those as well:

``1713947,554143,1638064,1765453,1650533,1439651,1048608,1575475,1659645,1802506,1355421,1775661,1770207,1616787,1519045,1414012,1763568,1828466,1816401,1597589,1764078,1689443,1769575,1774562,1770054,1704324,1810556,1838172,1568720,1304251,1672239,1641449,1721944,1741321``

**Comment by peppy** [comment]
Has been resolved with better internal tooling
