### ISSUE TITLE
Allow Project Loved members to edit genre/language on graved maps

### ISSUE THREAD

**Issue by Hiviexd** [ppy/osu-web#8938]
Currently, we can edit difficulty owners on loved and graved maps, but we can edit genre/language on loved maps only.

It would make more sense to make permissions consistent across both settings by allowing LVD group to edit genre/language on graved maps.

**Comment by Hiviexd** [comment]
Also, (slightly unrelated to this issue but I can edit it to extend to the thing that i'm about to mention) would you guys be okay with BNs being able to edit difficulty owners on pending and qualified maps? 
Seeing that they can already edit genre/language on pending and qualified maps, it would be better to achieve the same consistency I mentioned in the issue above.

**Comment by peppy** [comment]
I think it's fine to allow genre/language editing. I'm less sure about the guest mapper editing for BNs. It seems like something which would generally not be required. If required, please open a separate issue with rationale.
