### ISSUE TITLE
osu!mania "Perfect" score highlighting not accounting for higher values

### ISSUE THREAD

**Issue by plexiondev** [ppy/osu-web#8968]
after FC'ing a map in osu!mania i noticed that on the web-side, the max combo "perfect" green highlight does not account for numbers above the beatmap's max combo.

it is possible to achieve a higher combo due to longnotes and caused a bit of confusion, would make sense if combo above was highlighted as well. may just be me misunderstanding.

client (2* FC achievement):
![screenshot1340](https://user-images.githubusercontent.com/46572320/170739480-f3438ee8-351f-49b4-826c-cbed82323005.png)

web:
![image](https://user-images.githubusercontent.com/46572320/170739562-8c2c3e83-2d8c-4e0f-bf8b-12da0357b5c2.png)

**Comment by nanaya** [comment]
The highlight has got nothing to do with actual max combo value. It solely depends on the perfect attribute of the score. The value is false so it's not highlighted. Can probably use some check by @peppy

**Comment by Master-chan** [comment]
I got my 4* mania FC achievement for score with 1x miss so there might be some super convoluted logic involved.

**Comment by peppy** [comment]
I believe this may be fixed in the next difficulty calculator deploy (via https://github.com/ppy/osu-difficulty-calculator/pull/211), @smoogipoo can you confirm?

**Comment by smoogipoo** [comment]
Nah, combo is still going to be weird (because osu-stable's weird) and that DB value can't be relied upon for this case. How is that value currently calculated? I thought it was supposed to be if `count_miss = 0` for o!m?

**Comment by peppy** [comment]
The issue here is that the green highlight is using the `perfect` flag, which is set by the osu! client (stable). We'll need to check the conditions for `perfect` and whether it's not matching expectations.

**Comment by smoogipoo** [comment]
Right. So the condition for that flag in mania for stable is:
```csharp
if ((CurrentScore.CountMiss + CurrentScore.Count50 + CurrentScore.Count100) == 0 && ((float)CurrentScore.CountKatu / CurrentScore.TotalHits) < 0.1)
    CurrentScore.Perfect = true;
else
    CurrentScore.Perfect = false;
```
So if I'm reading that correctly, for a perfect score you need:
- No misses.
- No 50s.
- No 100s.
- Less than 10% 200s.

**Comment by peppy** [comment]
That's a very weird conditional. Wonder if there would be any opposition to simplifying...

**Comment by smoogipoo** [comment]
One thing to keep in mind is that stable is inconsistent in the way that it awards points. It's framerate-dependent - having a frame skip will take points away from you, as well as dependent on when you start holding - if you start holding _before_ the start time of the note then it should give you more combo according to my rudimentary check.  

There's some nuance when it comes to the early hit window and how that plays into all of this, but the gist of it is that it's inconsistent and the combo value can't really be relied upon. Even auto, played at different speeds (numbers 6-9 on CE), and I believe even the same speed, will differ between plays >_>

I personally wouldn't be opposed to using "no misses" as the single conditional for this particular value, but I recognise the other conditions are likely meant to represent a more BMS-like AAA scoring. Maybe that's something that should be left to something other than the "perfect" value though - perhaps having a way to display not just classic/standardised scoring but also "wife" or BMS scoring or whatever other people come up with, as a completely separate system.

**Comment by peppy** [comment]
I guess we've already changed it in lazer, so we can see how that goes over there.

Probably fine to close this issue as "behaving correctly"..?

**Comment by smoogipoo** [comment]
Lazer's even worse since it uses max combo >:D Closing this seems fine though.

**Comment by peppy** [comment]
@plexiondev see https://github.com/ppy/osu-web/issues/8968#issuecomment-1149530914 and https://github.com/ppy/osu-web/issues/8968#issuecomment-1149541311 for the rationale behind why this is actually correctly displayed.
