### ISSUE TITLE
Beatmaps attributed to the artist "a" or "A" are mistakenly tagged w/ the Featured Artist tag

### ISSUE THREAD

**Issue by Nivalyx** [ppy/osu-web#8975]
as found by accident (and reported internally in the #nat channel) earlier -- some examples :

- http://osu.ppy.sh/beatmapsets/210774#osu/495799
- http://osu.ppy.sh/beatmapsets/1472695#mania/3022847
- http://osu.ppy.sh/beatmapsets/302045#osu/677105
- http://osu.ppy.sh/beatmapsets/1668800#osu/3407989

![image](https://user-images.githubusercontent.com/36564236/171071963-3f43ff5d-ef32-4639-af6b-b0470f3bf44d.png)

upon clicking all the FA tags seem to redirect to http://osu.ppy.sh/beatmaps/artists/173 tho, so i suppose this has to do with the database confusing all of these w/ songs from the actual featured artist (`A?`)'s catalogue perhaps? idk...

**Comment by Nivalyx** [comment]
also for some reason i noticed that this error only occurs when the Title field is also 1 character long :

![image](https://user-images.githubusercontent.com/36564236/171073483-9a754a77-758e-47b1-b856-890fe8b4e395.png)

**Comment by peppy** [comment]
I've fixed this case. I'd call this very edge case as it only affects graveyarded beatmaps, but I did also make some improvements which resulted in a few new (correct) matches, in ranked and non-ranked.
