### ISSUE TITLE
Allow moderators to lock beatmap comments sections

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#8985]
Some beatmap comments sections get out of hand very quickly. In some cases, they can be saved by aggressive moderation, but in some circumstances that is simply not possible nor productive to the volume of incoming messages, the scope of the provoking situation, or any other myriad of reasons that crop up when handing a multinational community.

Beatmap comments sections need to have the same lock functionality as modding discussions and forum threads do - toggle it active and no new comments are permitted until it is toggled off.

**Comment by peppy** [comment]
As an update, we're currently discussing internally what kind of locking we would want here. It's likely going to be an admin-only action and will automatically undo after a specified time interval.

**Comment by peppy** [comment]
We will be requiring this as a priority (needs to be deployed this week).

It is fine to be admin-only if that makes it easier to implement. Eventually we may want the unlock portion to be automatic, but I can schedule that at my end for now.
