### ISSUE TITLE
`Announcement` are mistakenly written as `Annoucement` on certain places

### ISSUE THREAD

**Issue by Nivalyx** [ppy/osu-web#8987]
related to the recently implemented "Announcements" feature. here's one instance where it's being written incorrectly :

![image](https://user-images.githubusercontent.com/36564236/172057505-1a307903-7eaf-45b3-99f4-29e829e41ca4.png)

i looked at http://github.com/ppy/osu-web/pull/8747/files and apparently a lot of things (not just strings, but also variables) are being written/defined as `annoucement` in that pr for some reason... i'm not sure whether it's intended or not but i doubt that's the likely case here :(

**Comment by notbakaneko** [comment]
that should definitely be `announcement`
