### ISSUE TITLE
`Create Announcement` button not properly showing

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#8990]
As far as i understood, moderators and "announce" usergroup members should be able to send announcement messages, however the "create announcement" button did not show up for me until someone send me an announcement, eventho the data showed "can_chat_announce: true" for me as a GMT

**Comment by nanaya** [comment]
Fixed in #8991

**Comment by RockRoller01** [comment]
now that this is closed, is there any way yet to get rid of announcements or am i eternally stuck with this test channel
![image](https://user-images.githubusercontent.com/35633093/172373805-56a3d838-5794-48f7-9935-3323fecc8f4f.png)

**Comment by notbakaneko** [comment]
coming soon™️
