### ISSUE TITLE
Modding page erroneously assumes that there's an extra game mode (`beatmaps.mode`) on a mapset

### ISSUE THREAD

**Issue by Nivalyx** [ppy/osu-web#8993]
(Ryuusei Aika asked me to log this issue here for him)

As reported in the BN server just now. This beatmap --> http://osu.ppy.sh/beatmapsets/1335792 consists solely of osu! difficulties, and yet somehow the modding page assumes that the beatmap is a hybrid of two different game modes (`osu!` and the nonexistent `beatmaps.mode`) -- therefore preventing the beatmap from being pushed to Qualified due to its required amount of nomination.

Related screenshots :

![image](https://user-images.githubusercontent.com/36564236/172187379-cfcaa7ec-5073-463a-8799-0e5185d4941c.png)

![image](https://user-images.githubusercontent.com/36564236/172187400-b0d1b548-5a31-432a-8ee2-094d968b7f1d.png)

**Comment by notbakaneko** [comment]
Does it happen on other mapsets as well?

**Comment by nanaya** [comment]
The shortcut used to determine beatmap modes, `difficulty_names` column, has its value truncated due to too many difficulties and it's cut right at the separator between name and mode.

**Comment by Nivalyx** [comment]
hmm is it something that's fixable server-side, or should the mapper be reducing the number of difficulties in order to prevent this issue from happening for instance? @nanaya

**Comment by nanaya** [comment]
I'll need confirmation from @peppy on if this column can actually be relied on and work from there.

**Comment by Nivalyx** [comment]
ah, okay

**Comment by peppy** [comment]
I wish we had an upper limit set on difficulty count earlier on.

I'll look to add a limit and also fix this at a database level.

**Comment by peppy** [comment]
This should be fixed now, please confirm.

**Comment by StarCastler** [comment]
Looks fine on my end now, thanks

**Comment by cdwcgt** [comment]
this seen happened again in https://osu.ppy.sh/beatmapsets/1949343/discussion
