### ISSUE TITLE
Beatmap covers API endpoints return images of the old format for most non-recent graveyard maps

### ISSUE THREAD

**Issue by Zyfarok** [ppy/osu-web#8994]
The size of images returned by the beatmaps covers endpoints of the assets API seems to have changed a while ago (since May 26th 2021 with https://github.com/ppy/scthumber/pull/1 ?), but ___most___\* graveyard beatmaps that were not updated since then still have the old format.  
This includes the `card.jpg`, `card@2x.jpg`, `list.jpg` and `list@2x.jpg` images. (cover.jpg and slimcover.jpg did not change)

Graveyard maps are often used in tournaments, and the card/list image are used in osu-web, in lazer (?), and by third-parties applications like mappool sheets.  
Example of user favourite section where the graveyard maps have a blurrier look due to this :
![image](https://user-images.githubusercontent.com/10669609/172273470-10b05442-49c9-451e-aeb3-0622c5c53271.png)

Example graveyard map with the new format and image URLs :
https://osu.ppy.sh/beatmapsets/1558526
https://assets.ppy.sh/beatmaps/1558526/covers/card.jpg?1636360215
https://assets.ppy.sh/beatmaps/1558526/covers/list.jpg?1636360215
https://assets.ppy.sh/beatmaps/1558526/covers/card@2x.jpg?1636360215
https://assets.ppy.sh/beatmaps/1558526/covers/list@2x.jpg?1636360215
(ranked and loved beatmaps seem to all return this format)

Example graveyard map with the old format and image URLs :
https://osu.ppy.sh/beatmapsets/1235496
https://assets.ppy.sh/beatmaps/1235496/covers/card.jpg?1599939054
https://assets.ppy.sh/beatmaps/1235496/covers/list.jpg?1599939054
https://assets.ppy.sh/beatmaps/1235496/covers/card@2x.jpg?1599939054
https://assets.ppy.sh/beatmaps/1235496/covers/list@2x.jpg?1599939054

*: I said most because there seems to be a few exceptions like https://osu.ppy.sh/beatmapsets/1306572 (last updated 22 Nov 2020, yet has the new format)

Side-Note :  
Removing timestamp query parameter at the end of the URL seems to give the same result.  
What's the use of this timestamp query argument ? Retrieving old covers ?

**Comment by peppy** [comment]
That is because the beatmaps were graveyarded. The graveyard is for old beatmaps. We don't re-run processes on these.

**Comment by peppy** [comment]
I understand the use case. We may be able to slowly reprocess all beatmaps in the background. I'll add this to my bucket list.

**Comment by peppy** [comment]
I believe reprocessing of this finished a while back. Please let us know if you find any examples.

**Comment by Zyfarok** [comment]
> Please let us know if you find any examples.

The two example maps linked above are indeed fixed, but all the other graveyards maps in my favorite beat-map list still have the same issue:
https://osu.ppy.sh/beatmapsets/609865#mania/1287833 -> https://assets.ppy.sh/beatmaps/609865/covers/list@2x.jpg
https://osu.ppy.sh/beatmapsets/748815#osu/1577423 -> https://assets.ppy.sh/beatmaps/748815/covers/list@2x.jpg
https://osu.ppy.sh/beatmapsets/837257#osu/1753120 -> https://assets.ppy.sh/beatmaps/837257/covers/list@2x.jpg
https://osu.ppy.sh/beatmapsets/630247#osu/1330531 -> https://assets.ppy.sh/beatmaps/630247/covers/list@2x.jpg
https://osu.ppy.sh/beatmapsets/417749#osu/904530 -> https://assets.ppy.sh/beatmaps/417749/covers/list@2x.jpg

Was it supposed to have run on all graveyard beatmaps ?
