### ISSUE TITLE
seemingly incorrect genres on multiple featured artist tracks

### ISSUE THREAD

**Issue by Gamingzone123** [ppy/osu-web#8996]
i was going through the featured artists looking for something different to listen to and found many of the tracks are seemingly mislabelled (as electronic). Is electronic the default genre songs get assigned when not otherwise labelled?

a few examples:

Archspire's songs dont strike me as primarily electronic music, more some metal subgenre
https://osu.ppy.sh/beatmaps/artists/256

Many songs of Release Hallucination seem more heavy metal
https://osu.ppy.sh/beatmaps/artists/194

the main basis for my theory on electronic being the default genre is Symholic's (newest because its at the top??) album " X -Kaikou Seshi Souheki no Claymore -" being marked electronic despite its sound and almost all of the rest of their albums being marked as 'Rock'
https://osu.ppy.sh/beatmaps/artists/130

not all of Natsume Itsuki's songs seem electronic
https://osu.ppy.sh/beatmaps/artists/189

im sure there are more past the examples ive given and from my perspective, someone probably needs to sit down and manually set each songs genre while i know that would be extremely time consuming, but thats just my two cents in the (probably very low priority) matter so this is mainly here as notice

**Comment by peppy** [comment]
cc @Ephemeralis

**Comment by Ephemeralis** [comment]
This will be (mostly) fixed but the general intent on FA track genre classification is *heavily* stalled on https://github.com/ppy/osu-web/issues/5852 since any sweeping attempt to mass-categorize all tracks needs to just be more than a single genre assignment.

**Comment by Ephemeralis** [comment]
Listed examples in the issue are now fixed.
