### ISSUE TITLE
comment float container goes outside of comment page when upvote score is high

### ISSUE THREAD

**Issue by Dafiely-nyan** [ppy/osu-web#9009]
I think this doesnt look great neither intended when this score container goes outside of that area
![image](https://user-images.githubusercontent.com/105630731/173184043-ecb4a91e-51e6-42fa-8f22-59d1b33b46eb.png)

also same happens when you view comment by direct (permanent) link 
![image](https://user-images.githubusercontent.com/105630731/173184162-cfcf3991-66b4-4a77-9721-abc265c6e332.png)

https://osu.ppy.sh/comments/2266111

occurs on chrome and edge as well, im using 1920x1080 if it matters

**Comment by RockRoller01** [comment]
dupe of #7379
