### ISSUE TITLE
No audio sample on beatmap webpage

### ISSUE THREAD

**Issue by Qungopottomus** [ppy/osu-web#9016]
In the past the audio samples have worked fine. But recently, the samples stopped working. Nothing plays. I have tried moving the preview point, changing out the audio file, and reuploading. I thought maybe I had just uploaded one cursed map, but it happened again today. What can I do?

Map 1: https://osu.ppy.sh/beatmapsets/1775734#osu/3636201
Map 2: https://osu.ppy.sh/beatmapsets/1784649#osu/3655118

**Comment by peppy** [comment]
Your audio track is `AAC` renamed to `MP3`. Please don't do this.
