### ISSUE TITLE
Add profile infringement for tournament bans

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#9018]
Currently, tournament bans are tracked via internal notes which require support operators to manually disclose their status to tournament organizers (TOs) during screening. Out of an interest to not pass the responsibility of informing the general public of such a status to TOs, present practices involve informing the public via the osu! support twitter in a manner that can be easily construed as targeted.

Making active/permanent tournament ban status visible on user profiles as per the mockup below would help to alleviate this problem:

![](https://puu.sh/J5DoS/75038da94e.png)

This would allow TO's to make quicker staffing decisions when making on-the-fly replacements and would also negate some need for non-supported tournaments to request screening at all.

Adding this into internal tool workflow for standard restriction appeal returns (aka, for noting the typical 1 year tournament ban that accompanies most standard appeals) will also be helpful.

**Comment by nanaya** [comment]
Is this going to supersede #8676 or a separate/additional thing?

**Comment by Ephemeralis** [comment]
A user can fail screening and not be tournament banned, but tournament banned users will always fail screening, so likely an additional thing.
