### ISSUE TITLE
Beatmaps without a discussions page cannot be deleted

### ISSUE THREAD

**Issue by JBHyperion** [ppy/osu-web#9030]
The following beatmap: https://osu.ppy.sh/beatmapsets/1786972#osu/3660834 seems to have been uploaded without a discussions page being generated. Clicking the discussion tab at the top of the page redirects you to the beatmap thread instead: https://osu.ppy.sh/community/forums/topics/1595272

Attempting to force the website to load the discussions page (e.g. entering https://osu.ppy.sh/beatmapsets/1786972/discussion, https://osu.ppy.sh/beatmapsets/1786972/discussion/3660834/timeline, etc. as the URL) returns a "Page Missing - Sorry, but the page you requested isn't here!" error.

In previous cases of bugged submissions, the discussions page will generate, but not the thread - this just prevents the description from being edited and is usually resolved by a GMT/NAT deleting the map and having the user resubmit. However, this solution isn't possible in this case because the option to delete the beatmap is _on_ the discussion page, which can't be accessed. Deleting or moving the thread doesn't correspondingly delete the beatmap, so it's somewhat stuck there at the moment. The uploader also tried to reupload the map completely: https://osu.ppy.sh/beatmapsets/1786994#osu/3660917 - but the same issue occurred.

An option for moderators to delete beatmaps from the info page as well as the discussion page would be helpful, but as this is (hopefully) a one-off incident, it may be resolved more quickly at a database level?

**Comment by nanaya** [comment]
A new deploy should fix this. @peppy

**Comment by peppy** [comment]
Should be fixed now.

Although the first beatmaps was deleted.

**Comment by JBHyperion** [comment]
Seems to be fixed, discussion page is accessible and users have been able to leave Hype. First submission being deleted is fine and is how we would normally handle these cases anyway.

Thanks for the quick response!
