### ISSUE TITLE
Beatmap is incorrectly displayed as a guest participation map on profile

### ISSUE THREAD

**Issue by hburn7** [ppy/osu-web#9031]
There is a [beatmap](https://osu.ppy.sh/beatmapsets/765635#osu/1622225) that incorrectly shows as a "Guest Participation" beatmap on [my profile](https://osu.ppy.sh/users/8191845). This beatmap belongs to "Extra Stage" - but I could not find their profile. The original beatmap creator linked it to [this profile](https://osu.ppy.sh/users/Alex%20Kaulfild) which doesn't seem to exist.

I understand why this was linked to my profile, but I feel there should be a better way to validate guest participation - I'm not sure what the best solution is. I think this issue applies to all usernames that have spaces in the guest participation. i.e. the diff "I am very cool's Extra" may link to the user "cool" on the website.

<img width="472" alt="Screen Shot 2022-06-16 at 19 22 28" src="https://user-images.githubusercontent.com/38370573/174193997-307f85da-6c8f-4571-8bc0-e81f6a2ba60a.png">

**Comment by peppy** [comment]
Fixed.
