### ISSUE TITLE
Double posts in a beatmap discussion while network is not stable

### ISSUE THREAD

**Issue by Alleyne-Angel** [ppy/osu-web#9032]
I'm a Beatmap Nominator. These days I'm getting annoyed by this issue. I don't know how my network is going on. Sometimes it gets OK after loading animation, but the result is that my post gets doubled. There's also a case that the loading animation only lasts less than one second but still double post. Is there any possible way to change the post system? I'm not sure if this issue happens on comments, forums, and so on.

**Comment by peppy** [comment]
Approximately how often does this happen? Are you able to reproduce it to take diagnostics if we need them?

**Comment by Alleyne-Angel** [comment]
> Approximately how often does this happen? Are you able to reproduce it to take diagnostics if we need them?

Seems almost every time recently when I was trying to mod something. There should be double posts on a 4k normal diff - https://osu.ppy.sh/beatmapsets/1489889/discussion/3056735/timeline
idk know if it's available to see my deleted mods or other things

**Comment by peppy** [comment]
Are you able to open web inspector to the network tab and take a screenshot of the requests firing around the time you post? May be helpful in investigating further

**Comment by Alleyne-Angel** [comment]
![1](https://user-images.githubusercontent.com/67787327/174418889-7130f639-4779-4aa0-a82b-8a464d805957.png)
![2](https://user-images.githubusercontent.com/67787327/174418887-fa70b3c5-dbb4-4459-aafb-251102f73c95.png)
![e](https://user-images.githubusercontent.com/67787327/174418915-8ad6c9a9-b89b-47c1-a583-05f9928bce6d.png)

Seems it keeps requesting multi times

**Comment by notbakaneko** [comment]
The polling requests for updates is normal, I can only see one post request there.
The timing of the duplicate posts (they are slightly less than 1 minute apart) suggest it's not a duplication submission but something actually retrying the `POST` request, except we don't do anything that retries the request 🤔

**Comment by nanaya** [comment]
The post function probably shouldn't be aborting existing request and make another request but instead return immediately.

**Comment by peppy** [comment]
Was this resolved by https://github.com/ppy/osu-web/pull/9037?

**Comment by nanaya** [comment]
The provided screenshots doesn't indicate any duplicated post requests so it's not quite clear what's the problem here.

**Comment by peppy** [comment]
Could a plugin be involved? @Alleyne-Angel can you try with all plugins disabled, including any virus/security applications?

**Comment by Alleyne-Angel** [comment]
> Could a plugin be involved? @Alleyne-Angel can you try with all plugins disabled, including any virus/security applications?

Probably related to my VPN. But without VPN, many times I cannot connect to the server. 

And I can be sure that the VPN works well. Just my net is bad while there're many people suggesting me changing the other nets.

**Comment by peppy** [comment]
Does your VPN run as a web browser plugin? It might be triggering multiple requests without you knowing (which sounds pretty bad).

**Comment by Alleyne-Angel** [comment]
> Does your VPN run as a web browser plugin? It might be triggering multiple requests without you knowing (which sounds pretty bad).

(ah sorry I haven't receive any notification of this ;w; until cdwcgt told me) 
I use Clash for Windows, via setting the system proxy so I don't think there's any plugin since I never do that

But actually now there's no similar case happens on me after improving my network. The current speed is about 250 Mbps. I don't know how is the previous speed ;w;

**Comment by peppy** [comment]
Going to close this one for now.
