### ISSUE TITLE
Add an API endpoint for editing the me section

### ISSUE THREAD

**Issue by CyberGen49** [ppy/osu-web#9035]
As the title describes, I propose an API endpoint for editing the authenticated user's me section on their profile page, provided that they have osu!supporter. Allowing for the automation of me section edits could give users the opportunity to display ever-changing information on their profile page without the need to make edits manually.

To provide an example, suppose I have hundreds of osu gameplay clips I've saved throughout my time playing. I plan on automating the uploading of these clips to a YouTube channel (or my own website), and I think it could be cool to keep an updated list of recently uploaded video links on my osu profile page, for quick and easy access.

**Comment by peppy** [comment]
I don't think this should be the kind of thing we allow automation of, sorry.
