### ISSUE TITLE
When restricted, the Block/Unblock Dialog overlaps the user profile when you click Unblock

### ISSUE THREAD

**Issue by damaredayo** [ppy/osu-web#9036]
This can be found here:

![image](https://user-images.githubusercontent.com/28869766/174411625-e267ba13-7b01-4feb-97c3-9e5127d27b70.png)

Steps to reproduce
1. Be Restricted
2. Block a User
3. Click "Show Profile" on the dialog.

**Comment by nanaya** [comment]
yes, fixed by #9844.
