### ISSUE TITLE
Input characters are duplicated while using input methods in Review of Mapping Discussion

### ISSUE THREAD

**Issue by Alleyne-Angel** [ppy/osu-web#9051]
Yeah, almost all characters are duplicated in Review. I tried Chinese, Korean, and Japanese input methods, and seems it happens in all cases.

Sometimes when I'm trying to input something and press a key to confirm what I'm typing for, the screen gets black (nothing) | Chinese: Space | Japanese: Enter

I recorded a video: https://drive.google.com/file/d/1o-DBCHwEtnsZKYneh9dPX8iS9ECX5L19/view?usp=sharing

**Comment by nanaya** [comment]
I wouldn't be surprised if this is the same problem as #6097.

**Comment by Alleyne-Angel** [comment]
> I wouldn't be surprised if this is the same problem as #6097.

But here I didn't use anything to autocorrect, just normally using input methods

**Comment by notbakaneko** [comment]
This is the same issue as #6097, it's an issue with `slate`'s handling of IME input (which has somehow gotten...worse?)
