### ISSUE TITLE
api request beatmap difficulty attributes

### ISSUE THREAD

**Issue by StreamerYT** [ppy/osu-web#9054]
Why is my code not working and returns {error:null} ?
![image](https://user-images.githubusercontent.com/41978062/175222466-ee455cc8-2f22-45ed-a85f-2a1a93029ced.png)

**Comment by bdach** [comment]
This line looks suspicious in the endpoint in question:

https://github.com/ppy/osu-web/blob/3b8ba4024b5153db234d979b3f62320c11d85e58/app/Http/Controllers/BeatmapsController.php#L91

The other branch (that uses array) assigns to `$mods` instead:

https://github.com/ppy/osu-web/blob/3b8ba4024b5153db234d979b3f62320c11d85e58/app/Http/Controllers/BeatmapsController.php#L98

**Comment by E223** [comment]
That endpoint is expecting a beatmap id, but it's being provided a beatmap**set** id. Try using `3608801` in the URL instead, that's the beatmap id of the highest difficulty in that beatmapset.

**Comment by bdach** [comment]
Never mind, I misread source.

**Comment by StreamerYT** [comment]
Thanks for the help. Can you tell me why the star rating is different?
![image](https://user-images.githubusercontent.com/41978062/175229803-8baf9198-27df-4f7e-bccc-45cfbfecb63d.png)
![image](https://user-images.githubusercontent.com/41978062/175229852-15c597d8-669c-4173-ae63-fff7e4f9c829.png)
