### ISSUE TITLE
Database migration missing for table `osu_user_performance_change`

### ISSUE THREAD

**Issue by smoogipoo** [ppy/osu-web#9068]
Used in `osu-performance`.

**Comment by peppy** [comment]
```sql
***************************[ 1. row ]***************************
Table        | osu_user_performance_change
Create Table | CREATE TABLE `osu_user_performance_change` (
  `change_id` int unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int unsigned NOT NULL,
  `mode` tinyint NOT NULL,
  `beatmap_id` int NOT NULL,
  `performance_change` float NOT NULL,
  `rank` int DEFAULT NULL,
  `timestamp` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`change_id`,`mode`),
  KEY `osu_user_performance_change_user_id_index` (`user_id`)
) ENGINE=InnoDB AUTO_INCREMENT=229109696 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci ROW_FORMAT=DYNAMIC
/*!50100 PARTITION BY RANGE (`mode`)
(PARTITION p0 VALUES LESS THAN (1) ENGINE = InnoDB,
 PARTITION p1 VALUES LESS THAN (2) ENGINE = InnoDB,
 PARTITION p2 VALUES LESS THAN (3) ENGINE = InnoDB,
 PARTITION p3 VALUES LESS THAN (4) ENGINE = InnoDB) */
```

Of note, this table is never actually used. Not sure if populating it is required, and not sure if we'll use it in the future.

**Comment by cl8n** [comment]
it has such arbitrary conditions for being inserted into (via osu-performance) that I don't see how this could be useful, even just for historical purposes. I think it should be removed to solve this issue.

what was this table used for in the past?

**Comment by smoogipoo** [comment]
I think the reason this issue exists is because reprocessing PP via `osu-performance` for comparisons would sometimes trigger the condition and fail because the `data.ppy.sh` exports don't contain this table.

These days, I no longer use `osu-performance` to reprocess PP, so I don't think this is super relevant anymore.

**Comment by peppy** [comment]
Above is correct. The thinking was that we would show some insights into large pp changes on user profiles, but it never really happened.

**Comment by cl8n** [comment]
closing based on smoogi's comment then
