### ISSUE TITLE
"TheDreamGame" playlist appears in the list of official playlists

### ISSUE THREAD

**Issue by Flamiii** [ppy/osu-web#9077]
Under rankings > multiplayer, there's supposed to be a list which consists of all of the official playlists that have been run on osu!lazer. However, when I was scrolling through this list, I found a playlist which is not official and is just some random playlist that some inactive player made and I don't think that it's supposed to be there.

Playlist: https://osu.ppy.sh/multiplayer/rooms/74671

![image](https://user-images.githubusercontent.com/74088315/177017896-a248144b-c012-4901-941f-4bd38c371f80.png)

![image](https://user-images.githubusercontent.com/74088315/177017931-3d7d958f-56ae-47d0-adab-c7cd62a9ca77.png)

**Comment by peppy** [comment]
Fixed, thanks.
