### ISSUE TITLE
Store: Back button is shown with no history present

### ISSUE THREAD

**Issue by pixeldesu** [ppy/osu-web#91]
In the header of the osu!store, there's this back button...which, as you might think, should get you back to the frontpage of the store.

And well, it does, but only **if** you were on the frontpage before.

**If not**, the back button is still shown, but doesn't work as there is no history present you could jump back to.

Best way to reproducing this is visiting the store over [ppy's last blogpost](http://blog.ppy.sh/post/129362282513/20150918) (just click on "available" in the first list item)

Not really a big issue, it might just confuse people because it does nothing at that state.

**Comment by ameliaikeda** [comment]
This is a simple link to `javascript:history.back()`. Actually detecting if you can go back or not is [a bit of a tricky situation](https://stackoverflow.com/questions/3588315/how-to-check-if-the-user-can-go-back-in-browser-history-or-not) because browsers.

**Comment by nekodex** [comment]
Probably can just remove the back link/button altogether, not really needed with the header linking to the store top-page anyway?
