### ISSUE TITLE
The site loads very poorly. The download may take 2-5 minutes. Other sites are working fine.

### ISSUE THREAD

**Issue by StreamerYT** [ppy/osu-web#9101]

**Comment by peppy** [comment]
Where do you live? What internet connection do you have? Have you tried another browser?

**Comment by StreamerYT** [comment]
Russia. I logged out of my profile and everything loads much faster. But a delay of 5-10 seconds is still present. Edge & Chrome

**Comment by StreamerYT** [comment]
Strange. I turned on and off vpn warp and the site started loading normally.
