### ISSUE TITLE
Underscores don't work for spaces in `/users/{user}/{mode?}` username parameter

### ISSUE THREAD

**Issue by respektive** [ppy/osu-web#9113]
Noticed this when updating my discord bot to apiv2. In the apiv1 you are able to replace any spaces in usernames with `_` when doing a `get_user` request. This is no longer present in the apiv2. I always liked this and was wondering if it could come back. :thinking:

**Comment by peppy** [comment]
I don't see too much harm adding this back if it isn't going to break anything.
