### ISSUE TITLE
when returning to user page from beatmap page, wrong parameter are given

### ISSUE THREAD

**Issue by yuzupon1133** [ppy/osu-web#9114]
*notice: this was translated by DeepL*

open userpage (ex. [my user page](https://osu.ppy.sh/users/22136262)) and click the beatmap with least 2 diff from favrite beatmap,
next, make sure you have selected the highest diff for the beatmap you have chosen, then press the page back button,
then `#osu/beatmap_id` will be given to the url of the user page.

video: https://youtu.be/OC08V_Xjkwc

- worked with Microsoft Edge, Google Chrome
- no userscript available
- doesnt work without logging in to site

I think this bug is recently happened because it didnt happen until yesterday
is this my problem? does anyone else this working?

my user agent:
Microsoft Edge
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.114 Safari/537.36 Edg/103.0.1264.62`
Google Chrome
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36`

**Comment by peppy** [comment]
Can reproduce, seems like a regression.
