### ISSUE TITLE
Ensure `ended_at` is non-null in solo scores

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#9116]
We will be making this property non-null to simplify handling, the assumption being that all scores in the `solo_scores` table have been completed.

This may already be the case, but osu-web should ensure that scores aren't written to the `solo_scores` table with a `null` `ended_at` going forward. Feel free to close if this is already ensured.

**Comment by nanaya** [comment]
Current behavior is as follows:
- creating new score with data missing `ended_at` will throw error
- new scores from client are created with `ended_at` set to `now()`
- existing score in database, when missing `ended_at`, will be filled in with `created_at` from the table instead (and will throw error if null) (not actually saved the database)

**Comment by peppy** [comment]
Sounds like it's in a good state already 👍
