### ISSUE TITLE
Custom identifier syntax does not work for newspost

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#9118]
learned this with my recent newspost for the skinning contest, custom identifier doesnt work on the newspost but the accompanying wiki article.

newspost totally should support identifier syntax

**Comment by Walavouchey** [comment]
previous articles like the mappers' report have used html anchors to achieve the same effect, but the syntax should definitely be unified in order to also eventually support section highlighting (https://github.com/ppy/osu-web/issues/8976) in news posts
