### ISSUE TITLE
Incorrect link in Featured Artist label

### ISSUE THREAD

**Issue by JBHyperion** [ppy/osu-web#9131]
https://osu.ppy.sh/beatmapsets/1703527#taiko/3483886

Featured Artist label links to https://osu.ppy.sh/beatmaps/artists/tracks/4404 - which is on katagiri's Featured Artist listing, but it should direct the user to tokiwa's listing instead. I believe this should instead be tracks/5085?

This might have happened because https://osu.ppy.sh/beatmapsets/1605822#osu/3394505 this remix *is* on katagiri's FA listing (and is tagged correctly). I searched through tokiwa's other Ranked maps and they all seemed to be tagged correctly, so hopefully just an isolated case.

**Comment by Ephemeralis** [comment]
This has been fixed.
