### ISSUE TITLE
status.ppy.sh not loading correctly

### ISSUE THREAD

**Issue by EndyMc** [ppy/osu-web#9158]
Not sure if this belongs here, but as it stands right now. If I open status.ppy.sh on my phone (running Firefox on android) it loads as it should. But if I instead try to open the site on my computer (running Firefox on Windows 11) it just shows a black screen, and as far as I can see, nothing is logged to the console.

**Comment by cl8n** [comment]
same for me, though if i go to the url in the iframe i can view that page fine.
User agent `Mozilla/5.0 (X11; Linux x86_64; rv:103.0) Gecko/20100101 Firefox/103.0`

**Comment by EndyMc** [comment]
Upon further inspection, it seems that p.datadoghq.com is blocked by an extension I have installed, called Privacy Badger.
![bild](https://user-images.githubusercontent.com/82646131/182024839-c81d1edc-84eb-429a-81de-38140b0a10e2.png)

**Comment by peppy** [comment]
@cl8n can you confirm this is also the case for you?

**Comment by cl8n** [comment]
oh yeah I do have same extension. seems they block datadoghq.com and p.datadoghq.com by default
