### ISSUE TITLE
Map download link is broken

### ISSUE THREAD

**Issue by azazino3** [ppy/osu-web#9176]
Map download link is broken:
https://osu.ppy.sh/beatmapsets/17140#osu/154828
Both video and no-video downloads return:
"
Warning: sprintf(): Too few arguments in /var/www/html/S3.php on line 742
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/S3.php:742) in /var/www/html/d.php on line 109
"

**Comment by peppy** [comment]
I don't think we have a copy of this beatmap. It is graveyarded and was purged at some point.

I've marked it as unavailable.
