### ISSUE TITLE
When medals are highlighted, unearned medals are further darkened

### ISSUE THREAD

**Issue by yuzupon1133** [ppy/osu-web#9177]
![medal](https://user-images.githubusercontent.com/65931718/183638588-96f57ff9-9a52-4ca8-a7e8-339307067d57.gif)
In CSS, the properties of the `::section` for earned and unearned medals have [the same value](https://github.com/ppy/osu-web/blob/8d2b4a58e7c978291d6116cca99a69819e9ee32a/resources/assets/less/layout.less#L11).
I think it is due to [the opacity and filter](https://github.com/ppy/osu-web/blob/8d2b4a58e7c978291d6116cca99a69819e9ee32a/resources/assets/less/bem/badge-achievement.less#L54) in the `.badge-achievement--locked` class.

It's a personal thing, but it's unnatural and I would like to see it fixed.

**Comment by nanaya** [comment]
That's just how browser behaves with the styled image. What are you trying to do?

**Comment by yuzupon1133** [comment]
It is a copyable area (in this case, the medal name, not the image).
As I said earlier, it is unnutual when highlighted.

**Comment by nanaya** [comment]
From what I gather, this isn't trivially "fix"able (I don't think it's weird) as a lot of it comes from the browser itself. Highlighting itself doesn't even look the same between browsers. If you want to fix it then feel free to.

**Comment by yuzupon1133** [comment]
All selectable areas should have the same selection background color, but I close this because there is no point in obsessing over it.
