### ISSUE TITLE
New flag syntax doesn't reliably work in the newsposts

### ISSUE THREAD

**Issue by TicClick** [ppy/osu-web#9185]
(this might be a side effect)

- example post: https://osu.ppy.sh/home/news/2022-06-29-new-featured-artist-toromaru | https://github.com/ppy/osu-wiki/blob/11abde9d085551eacd57088bc50ff4a84f03bc3c/news/2022-06-29-new-featured-artist-toromaru.md
- what I see (Firefox and Safari): 
![image](https://user-images.githubusercontent.com/4686101/183887487-7de94101-1d75-445a-9295-44b4f8051cf1.png)
- what others *may* see: ![image](https://cdn.discordapp.com/attachments/218677502141399041/1006881837215399946/unknown.png)
- what we all should see: all flags mentioned in the `.md` file

in my console there are a few failed GET requests:

<details>
<summary>example request/response</summary>

## request

```
GET /7f1c9bb69e8a4c1e4f521ae6d24675c70b237b8f/68747470733a2f2f6f73752e7070792e73682f77696b692f696d616765732f7368617265642f666c61672f55532e676966 HTTP/2
Host: i.ppy.sh
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:103.0) Gecko/20100101 Firefox/103.0
Accept: image/avif,image/webp,*/*
Accept-Language: en,en-US;q=0.5
Accept-Encoding: gzip, deflate, br
DNT: 1
Alt-Used: i.ppy.sh
Connection: keep-alive
Referer: https://osu.ppy.sh/
Cookie: XSRF-TOKEN=(removed); osu_session=(removed); locale=en
Sec-Fetch-Dest: image
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-site
```

## response

```
HTTP/2 404 Not Found
date: Wed, 10 Aug 2022 11:13:43 GMT
content-type: text/plain; charset=utf-8
content-length: 10
content-security-policy: default-src 'none'; img-src data:; style-src 'unsafe-inline'
x-content-type-options: nosniff
x-xss-protection: 1; mode=block
cache-control: max-age=14400
cf-cache-status: EXPIRED
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
vary: Accept-Encoding
strict-transport-security: max-age=31536000; includeSubDomains; preload
server: cloudflare
cf-ray: 73884db43d0f2325-ZRH
alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400
X-Firefox-Spdy: h2
```

</details>

**Comment by Coppertine** [comment]
![image](https://user-images.githubusercontent.com/37494321/183888849-09a596da-8128-476a-a358-7bea2b1772fb.png)
Additional photo of what others see.

**Comment by TicClick** [comment]
^ the most recent announcement, https://osu.ppy.sh/home/news/2022-08-10-new-featured-artist-waterflame | https://github.com/ppy/osu-wiki/blob/11abde9d085551eacd57088bc50ff4a84f03bc3c/news/2022-08-10-new-featured-artist-waterflame.md

**Comment by nanaya** [comment]
News post missing images were because they weren't updated.

As for the `::::`, looks like the syntax isn't quite working right in table.

**Comment by notbakaneko** [comment]
That's because it's not enabled for news posts

**Comment by notbakaneko** [comment]
turns out this is probably a dupe of #9118
