### ISSUE TITLE
Missing https://assets.ppy.sh/tournament-banners/official/cwc2022/profile/winner_KR.jpg

### ISSUE THREAD

**Issue by marcostudios** [ppy/osu-web#9192]
As reported [here](https://osu.ppy.sh/community/forums/topics/1629262), the banner of supporting the winners of cwc2022 is missing ([404](https://assets.ppy.sh/tournament-banners/official/cwc2022/profile/winner_KR.jpg)).

Edit: It seems like something went wrong when _removing_ the banner

**Comment by peppy** [comment]
Looks to have never been uploaded

**Comment by Ephemeralis** [comment]
The asset has since been uploaded and no longer 404's. Should be safe to put back up with an env change.
