### ISSUE TITLE
Square brackets are not escaped in reports

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#9195]
![image](https://user-images.githubusercontent.com/35633093/184634431-28b0db22-477d-4cd6-905d-cf4f00485f1f.png)

Just saw this report and it seems like the square brackets arent escaped, causing markdown links to potentially break.

**Comment by nanaya** [comment]
I tried escaping it but it didn't do anything...

**Comment by notbakaneko** [comment]
discord does it's own escaping/unescaping as well 👀
