### ISSUE TITLE
Username change "0 more days" message

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#92]
As per [this report](https://osu.ppy.sh/forum/t/369681/start=0), username changes can show "0 more days" until available. Probably should show "1" in these cases.

Still waiting for more details to pinpoint when this occurs.

**Comment by peppy** [comment]
>>> App\Models\User::checkWhenUsernameAvailable('edelweiss');
	=> Carbon\Carbon {
	     +"date": "2015-09-24 13:57:23.000000",
	     +"timezone_type": 3,
	     +"timezone": "UTC",
	   }

**Comment by TheHowl** [comment]
wouldn't showing the remaining hours be better?

**Comment by peppy** [comment]
and minutes and seconds?
and be realtime?
yeah, that would be cool, i guess.
