### ISSUE TITLE
filtering date on the beatmap search web page in all status of maps

### ISSUE THREAD

**Issue by Adsicmes** [ppy/osu-web#9202]
I have only found that parameters like `ranked<2022` can filter map by date. But it only displayed maps in ranked, loved or approved status. I want to filter all maps with any date parameters. It will be a useful option.

**Comment by nanaya** [comment]
there's no option for search by updated but there's `created` filter (`created<2022` etc)

**Comment by Adsicmes** [comment]
If we will have any parameter to search last updated date?

**Comment by Swekka** [comment]
This is resolved with #10641
