### ISSUE TITLE
Add a setting to prevent previous names from being displayed

### ISSUE THREAD

**Issue by gkr-758** [ppy/osu-web#9229]
We have to contact accounts@ppy.sh to remove the previous name, but is there any way to temporarily remove it or make it appear again in the settings?
![image](https://user-images.githubusercontent.com/85799458/187082401-b564d776-3d9d-48b5-873e-b5e88ab51911.png)

**Comment by peppy** [comment]
There is not, please contact accounts@ppy.sh.
