### ISSUE TITLE
APIv2 OAuth does not work for a specific user

### ISSUE THREAD

**Issue by Sebola3461** [ppy/osu-web#9240]
This is so weird, i don't know why this happens with him. I'm the owner of [osu!modhub](https://osumodhub.xyz) and the user `14708449` can't be authenticated with OAuth

It returns this error:
![image](https://user-images.githubusercontent.com/62405013/187828602-e0bc8950-ee4e-4662-b894-223f10292dd3.png)

**Comment by notbakaneko** [comment]
In absence of other information, it looks like you're trying to reuse an already used authcode; Authorization codes are only valid once, requesting new tokens require new authorization codes.

**Comment by Sebola3461** [comment]
It's impossible. That code only runs after the user pass into your oauth page

**Comment by peppy** [comment]
Are you able to show the full process you're attempting in a video or listing the web requests in the flow? There are hundreds of people using the API so it definitely is working - something must be wrong in the process taken here.

**Comment by Sebola3461** [comment]
i will record the logs

**Comment by Sebola3461** [comment]
A video explaining the authentication flow: 
https://drive.google.com/file/d/1GarHfju17P0UU4nyI-JtfigUCaTmzH2P/view?usp=sharing

**Comment by Sebola3461** [comment]
More people with the same problem (in another client)
![image](https://user-images.githubusercontent.com/62405013/189447921-2b243d56-591e-45d7-ad61-519e42384764.png)

I've seen, the api doesn't returning the `authorization_code` for some reason

**Comment by nanaya** [comment]
Check if there's race condition which calls the validate osu token function multiple times. Last time I checked the oauth token for the user has already been generated. There might be a repeated call on that function on which any subsequent requests will fail as the auth code is one time use.

**Comment by Sebola3461** [comment]
I checked 2 times in a row, didn't found anything

**Comment by peppy** [comment]
We can't do anything with screenshots of code or browsers. Please provide a full network level log of what you're doing (using wireshark or otherwise). I'll close this issue for now but will reopen if said information is provided.
