### ISSUE TITLE
Contest system submission requirements

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#9243]
Currently, the contest system isn't set up to allow for sanity checking of submissions save for basic filename requirements linked to the contest type.

This poses a problem especially for fan art contests, which have extremely stringent image resolution requirements that have notoriously caused a great deal of problems for entrants who've exported their image incorrectly (sometimes by as few as a pixel or two). The processing scripts we use filter out these incorrect entries, but a manual pass is also needed for every fan art contest for obviously incorrect entries, since many users just upload random shit to a contest listing page if they are able to.

It would be ideal if there were ``extra_options`` available to enforce resolution requirements, like ``forced_height`` and ``forced_width``. A user attempting to upload something that does not fit the requirements would be informed clientside before the upload takes place.

**Comment by peppy** [comment]
Should be relatively easy to add this.
