### ISSUE TITLE
lazer scores incorrectly say "Only personal best scores award pp" and are not made distinct from stable scores

### ISSUE THREAD

**Issue by Non-Binary-Programmer** [ppy/osu-web#9245]
On the user profile, under the Recent Plays section, plays made in lazer will have a dash through the pp value that, when hovered, says "Only personal best scores award pp." This happens regardless of if a given score is a personal best or not. Additionally, it is impossible to tell at first glance whether a play was made in lazer or stable (unless it uses the mirror mod in standard, which also displays using the wrong icon). To fix both of these problems at once, I propose adding an icon similar to the heart displayed next to loved maps that, when hovered, says "lazer maps currently do not award pp" or something similar.

This discrepancy likely is the cause of #9219.

**Comment by peppy** [comment]
I don't see this as being a different issue from the other one.

Recent score show the PP that score got. This is intended to display on lazer and stable scores alike, as mentioned in the other issue. If it's not, there's a problem there as all lazer scores *DO* have pp values server-side and client-side.

**Comment by Non-Binary-Programmer** [comment]
The issue is that even if I were to play a map I had never played before, if I played on lazer, that play would still show as a dash and say that it wasn't a personal best.

**Comment by peppy** [comment]
Yes, I understand. But a valid pp value should show in that case, rather than this message. as per #9219.

We will investigate why that's not happening.
