### ISSUE TITLE
Add newly ranked beatmaps to `bss_process_queue`

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#9246]
Currently, the osu!(lazer) client is made aware of any changes in beatmaps statuses on startup. This happens via a mechanism that tracks `bss_process_queue`.

Right now, this doesn't correctly handle changes in ranked status (from qualified to ranked) as entries are not added at this boundary (tracking at https://github.com/ppy/osu/issues/19488). The easiest solution is to insert an entry during the qualified -> ranked operation.

```sql
INSERT INTO bss_process_queue (beatmapset_id) VALUES (1520317);
```

Default values for the table work fine.

**Comment by smoogipoo** [comment]
This will also fix diffcalc issues that crop up every now and then with maps that weren't recomputed during the full beatmap passes :+1:
