### ISSUE TITLE
Notification options for announcement

### ISSUE THREAD

**Issue by nanaya** [ppy/osu-web#9251]
This seems like something that should have email notification option...? And there's no way to disable push notification either.

**Comment by notbakaneko** [comment]
Announcements weren't supposed to have notification options because they were supposed to be important messages and not be turned off 🤔

**Comment by nanaya** [comment]
Also fwiw it's missing translation keys for email as well

**Comment by nanaya** [comment]
Still no option but now having both push and email always enabled seems good enough.
