### ISSUE TITLE
New #2 top with no according global rank change

### ISSUE THREAD

**Issue by Rekunan** [ppy/osu-web#9252]
My friend set a new #2 top yesterday and just recently realized that his global rank didn't change accordingly. His previous best on the map was around 170pp.

Profile: https://osu.ppy.sh/users/9946406
Score: https://osu.ppy.sh/scores/osu/4263790019

**Comment by peppy** [comment]
Global rank is not guaranteed to change. It requires that the next person above you has not improved, and is within range for it to actually increase.

If you think there's an actual issue, please provide more details.

**Comment by Rekunan** [comment]
It seemed weird at first, but what you said makes sense, esp since I just noticed it's only 13pp above his #3. Thank you!

**Comment by cl8n** [comment]
there are more reports of this recently
https://osu.ppy.sh/community/forums/topics/1643545
https://osu.ppy.sh/community/forums/topics/1643609

and the example in OP was supposed to change rank, you can see the update from #59k to #57k was caused by that score and it was just delayed

**Comment by peppy** [comment]
There was a slight delay overnight and I'm not sure why. Maybe related to moving pp processor to kubernetes, will investigate.

Things have since caught up.
