### ISSUE TITLE
Drag-and-Drop links not supported on Profile pages

### ISSUE THREAD

**Issue by megu-osu** [ppy/osu-web#9257]
Currently the osu! client supports dragging beatmap links into the game to either direct you to said map or open up the osu!direct panel.

This is available on a variety of URL formats, for example:
https://osu.ppy.sh/b/2923999
https://osu.ppy.sh/s/1376486
https://osu.ppy.sh/b/2923999?m=0
https://osu.ppy.sh/s/1376486?m=0
https://osu.ppy.sh/beatmapsets/1376486
https://osu.ppy.sh/beatmapsets/1376486#osu/2923999

However on profile pages, all beatmaps in Ranks and Historical tabs have this URL format:
https://osu.ppy.sh/beatmaps/2923999?mode=osu

When trying to drag-and-drop this link into osu!, it will be spat back out and your browser will open the URL, just like any other unsupported link. I believe this should be fixed by either changing the URL format to one that works or updating the game to support /beatmaps/ links, as this feature would be a major convenience for players that want to quickly navigate from a profile page directly to a beatmap.

**Comment by peppy** [comment]
Can these links be updated to use the `set/#osu/beatmap_id` standard?

**Comment by nanaya** [comment]
yeah, that seems possible
