### ISSUE TITLE
Add links to tournaments from profile badges

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#9276]
Had this request a few times

- Add new column in `osu_badges` (nullable) to put URL
- If URL present, clicking badge should redirect to URL

Should be a very simple implementation that we can make happen in 30 minutes (excluding filling in the data).

**Comment by RockRoller01** [comment]
Duplicate of #4211 which supposedly is already completed just never got used 🤷

**Comment by peppy** [comment]
face palm.

i completely missed it because it's got zero data.

cc @Ephemeralis
