### ISSUE TITLE
Count of upvotes for pinned comments is too big when count reaches 3 digits

### ISSUE THREAD

**Issue by 0x84f** [ppy/osu-web#9286]
You can see this here on the pinned comment:
[Post](https://osu.ppy.sh/home/news/2022-09-01-anniversay-art-voting)
![image](https://user-images.githubusercontent.com/24534022/190396530-7fd4633d-86aa-4204-9f44-cd0fc61f2db1.png)

**Comment by venix12** [comment]
probably duplicate of #7379

**Comment by 0x84f** [comment]
ye, closing
