### ISSUE TITLE
Beatmap info page freezes on iPhone 12 (iOS 16)

### ISSUE THREAD

**Issue by Shmiklak** [ppy/osu-web#9289]
Lately I've been experiencing problems accessing beatmap info page for any ranked set from my phone as the page instantly freezes after accessing it, while working perfectly fine with Pending or Graveyard sets. Similar issue was noticed on some wiki articles where the page contains lots of country flags, which might be the issue causing the crash. Embedding a video example of such behaviour, here I'm trying to access the modding panel on both maps, however in case of the first one the only thing I can do is completely close the tab as the whole page is frozen: https://youtube.com/shorts/EDEfyaIEptQ?feature=share

**Comment by notbakaneko** [comment]
should be better now #9291

**Comment by Shmiklak** [comment]
can confirm, it does actually work better for beatmap info page, still unable to view some wiki articles though (e.g. triangles contest)

**Comment by peppy** [comment]
@Shmiklak can you open a separate issue with a screenshot or video and URL of the page you're still having issues with please
