### ISSUE TITLE
unicode characters are entered twice in beatmap discuss review

### ISSUE THREAD

**Issue by cdwcgt** [ppy/osu-web#9294]
![image](https://user-images.githubusercontent.com/34775378/191061660-a0c4bcaa-37ab-4aa0-8b0d-35af2d230dcd.png)
Entering non-English characters (even symbols) here will be entered twice
![image](https://user-images.githubusercontent.com/34775378/191061870-bb67ef7c-964f-4e47-a270-2b0f63f70ecd.png)
after press enter
![image](https://user-images.githubusercontent.com/34775378/191061963-4497dcbf-aa3f-45a4-84d3-be19ad552460.png)

**Comment by peppy** [comment]
I cannot reproduce the issue.

Please state your browser / operating system

**Comment by notbakaneko** [comment]
This should be a duplicate of #6097
