### ISSUE TITLE
api/v2/users/1/scores/best? Doesn't Give Best Top Play

### ISSUE THREAD

**Issue by Anthoney3** [ppy/osu-web#9305]
The v2 api endpoint for obtaining a users best score play based on their top pp play seems to return results that are not the current best play no matter what players username I use to retrieve the records; or it shows the players second best for the most part as if it might not be updating. I've pasted a prettied JSON output of the call made for a friend of mine and when compared to his best play's pp,  its pulling the third best instead of his top 100% weighted play.

<img width="730" alt="image" src="https://user-images.githubusercontent.com/88722074/192165108-3d4fa85c-ee75-4d31-a000-b91127e08964.png">

Raw Output from endpoint (https://osu.ppy.sh/api/v2/users/21120079/scores/best?include_fails=1&mode=osu&limit=1&offset=1):

[
  {
    "accuracy": 0.9334554334554335,
    "best_id": 4271156762,
    "created_at": "2022-09-14T23:13:30+00:00",
    "id": 4271156762,
    "max_combo": 334,
    "mode": "osu",
    "mode_int": 0,
    "mods": [],
    "passed": true,
    "perfect": false,
    "pp": 82.6312,
    "rank": "S",
    "replay": false,
    "score": 2135606,
    "statistics": {
      "count_100": 26,
      "count_300": 246,
      "count_50": 1,
      "count_geki": 24,
      "count_katu": 17,
      "count_miss": 0
    },
    "type": "score_best_osu",
    "user_id": 21120079,
    "current_user_attributes": {
      "pin": null
    },
    "beatmap": {
      "beatmapset_id": 975620,
      "difficulty_rating": 4.64,
      "id": 2041972,
      "mode": "osu",
      "status": "ranked",
      "total_length": 77,
      "user_id": 5156153,
      "version": "Sweet",
      "accuracy": 8,
      "ar": 9,
      "bpm": 153.6,
      "convert": false,
      "count_circles": 207,
      "count_sliders": 65,
      "count_spinners": 1,
      "cs": 3.8,
      "deleted_at": null,
      "drain": 5.5,
      "hit_length": 63,
      "is_scoreable": true,
      "last_updated": "2019-07-04T16:46:59+00:00",
      "mode_int": 0,
      "passcount": 186120,
      "playcount": 1180287,
      "ranked": 1,
      "url": "https://osu.ppy.sh/beatmaps/2041972",
      "checksum": "f871a8cba6c50f19406cb35d4a9081f6"
    },
    "beatmapset": {
      "artist": "Alexandra Stan feat. Connect-R",
      "artist_unicode": "Alexandra Stan feat. Connect-R",
      "covers": {
        "cover": "https://assets.ppy.sh/beatmaps/975620/covers/cover.jpg?1650680911",
        "cover@2x": "https://assets.ppy.sh/beatmaps/975620/covers/cover@2x.jpg?1650680911",
        "card": "https://assets.ppy.sh/beatmaps/975620/covers/card.jpg?1650680911",
        "card@2x": "https://assets.ppy.sh/beatmaps/975620/covers/card@2x.jpg?1650680911",
        "list": "https://assets.ppy.sh/beatmaps/975620/covers/list.jpg?1650680911",
        "list@2x": "https://assets.ppy.sh/beatmaps/975620/covers/list@2x.jpg?1650680911",
        "slimcover": "https://assets.ppy.sh/beatmaps/975620/covers/slimcover.jpg?1650680911",
        "slimcover@2x": "https://assets.ppy.sh/beatmaps/975620/covers/slimcover@2x.jpg?1650680911"
      },
      "creator": "DeRandom Otaku",
      "favourite_count": 1238,
      "hype": null,
      "id": 975620,
      "nsfw": false,
      "offset": 0,
      "play_count": 3485493,
      "preview_url": "//b.ppy.sh/preview/975620.mp3",
      "source": "",
      "spotlight": false,
      "status": "ranked",
      "title": "Vanilla Chocolat (Sped Up Ver.)",
      "title_unicode": "Vanilla Chocolat (Sped Up Ver.)",
      "track_id": null,
      "user_id": 5156153,
      "video": false
    },
    "user": {
      "avatar_url": "https://a.ppy.sh/21120079?1662521345.jpeg",
      "country_code": "US",
      "default_group": "default",
      "id": 21120079,
      "is_active": true,
      "is_bot": false,
      "is_deleted": false,
      "is_online": false,
      "is_supporter": true,
      "last_visit": "2022-09-25T20:17:16+00:00",
      "pm_friends_only": false,
      "profile_colour": null,
      "username": "FlavorTown42069"
    },
    "weight": {
      "percentage": 95,
      "pp": 78.49964
    }
  }
]

**Comment by respektive** [comment]
It's giving you the 2nd best play instead of the 1st, because you have the set `offset=1`. It's not the 3rd best play like you said, you can compare the beatmap_ids.

**Comment by Anthoney3** [comment]
> It's giving you the 2nd best play instead of the 1st, because you have the set `offset=1`. It's not the 3rd best play like you said, you can compare the beatmap_ids.

Ah i see, so what offset should I be aiming for in order to get someone's top play? Offset 0?

**Comment by respektive** [comment]
> Ah i see, so what offset should I be aiming for in order to get someone's top play? Offset 0?

Offset 0, or removing the offset parameter completely.

**Comment by Anthoney3** [comment]
> > Ah i see, so what offset should I be aiming for in order to get someone's top play? Offset 0?
> 
> Offset 0, or removing the offset parameter completely.

Gotcha, Thank you for the assistance. I'll remove the issue.
