### ISSUE TITLE
Simplified Chinese support

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-web#931]
I want to add Simplified Chinese support in osu-web,
I know that I should put i18n files in `resources/lang/zh_cn`
But what should I do to add a language in index page?

**Comment by LiquidPL** [comment]
[here I think](https://github.com/ppy/osu-web/blob/master/config/app.php#L81)

**Comment by kj415j45** [comment]
![image](https://cloud.githubusercontent.com/assets/18349191/22350192/c827c152-e44d-11e6-82f5-c53dc9d5637e.png)
And what about here

**Comment by nanaya** [comment]
Just add finish the translation first, I'll add it later.

**Comment by nanaya** [comment]
If you want, update the meta at `app/Libraries/LocaleMeta.php`.

**Comment by kj415j45** [comment]
Thank you! :)
