### ISSUE TITLE
Cannot unfriend restricted user

### ISSUE THREAD

**Issue by wowcake** [ppy/osu-web#9329]
Currently, if a player gets restricted, they won't show up in the "Friends" tab dashboard (https://osu.ppy.sh/home/friends) and since you cannot visit their profile, you really can't do anything about it.

Since restricted person still count as your friend even after they got restricted, this uses up the friend slot, and you can't unfriend them since there's no way of doing so.

**Comment by nanaya** [comment]
Restricted users aren't counted for friends limit. If you observe otherwise, please provide more detail.
