### ISSUE TITLE
suggestion: add pop-up after selecting text in forum to paste quote automatically

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#9330]
![6fxWkpT](https://user-images.githubusercontent.com/32525896/193431103-8f6c012f-1670-42c4-ad7c-5d8d95b57835.png)

by clicking it, it will automatically insert the bbcode + selected text into the writing field, which would make it way easier to quote

**Comment by RockRoller01** [comment]
duplicate of #3496
