### ISSUE TITLE
Chat messages posted by silenced users are shown after web page refresh

### ISSUE THREAD

**Issue by TicClick** [ppy/osu-web#9334]
this has been present for a long time (maybe since the chat was implemented) and is usually self-evident: refresh the tab, and all messages pop back.

**Comment by nanaya** [comment]
Apparently the messages (on public channels) from that user for the past 1 hour or something should just be deleted from database when silence happens.

The current plan is for the bancho/mod command bot to just delete them from database directly as part of their user silencing process.

**Comment by peppy** [comment]
I've applied a solution for this (both bancho and ASS level).
