### ISSUE TITLE
Accessing a certain wiki article results in an error

### ISSUE THREAD

**Issue by TPGPL** [ppy/osu-web#9345]
as in title accessing https://osu.ppy.sh/wiki/en/Contests/M2P is not possible and results in an error

![](https://user-images.githubusercontent.com/19843905/194003770-63685399-1ba1-49a5-8fc8-b5534a642059.png)

The article on GitHub: https://github.com/ppy/osu-wiki/blob/master/wiki/Contests/M2P/en.md

**Comment by nanaya** [comment]
The one of the tags isn't a string (`m2p: taiko`) as also indicated by what github renders. Please put it in quote.

![](https://s.myconan.tk/2022-10/firefox_2022-10-05_16-28-06.png)

**Comment by TPGPL** [comment]
okay it works now, thanks
