### ISSUE TITLE
broken beatmapsets or something else.

### ISSUE THREAD

**Issue by StreamerYT** [ppy/osu-web#9346]
broken beatmapsets or something else.
HTTP 500/PHP Error

beatmapsets: 520,570,645,671,850,875,1022,1031,1125,1361,1556,1724,1949,2222,2430,2887,3081,3126,3263,3341,3369,3643,4021,4149,4151,4250,4298,4351,4413,4459,4473,4487,4506,4616,4654,4660,4661,4728,4904,4916,4962,5066,5067,5101,5146,5175,5187,5229,5243,5258,5268

Screenshot:
![image](https://user-images.githubusercontent.com/41978062/194066912-6f5db87d-6a3d-42db-b885-279fe8d64443.png)
![image](https://user-images.githubusercontent.com/41978062/194066998-2e95095f-9151-4228-9801-18c010442454.png)

**Comment by nanaya** [comment]
Banner informing this would be useful but in the meantime please don't bother reporting those old graveyarded maps.

> Due to the huge number of abandoned beatmaps, graveyarded maps which have not been updated in a long period of time will no longer be downloadable. If you need one for a specific reason, please post in this thread.

https://osu.ppy.sh/community/forums/topics/49310?n=1

**Comment by StreamerYT** [comment]
I'm sorry if I wrote something wrong. I do not know English, and I have to use a translator.

For such maps, this text is displayed.
![image](https://user-images.githubusercontent.com/41978062/195661155-afd9280a-7b30-49ab-a018-40cb2bc06fb5.png)

But for the 520 card and other cards, I don't see it.
![image](https://user-images.githubusercontent.com/41978062/195661293-96aab083-2456-40f3-9be3-c4a5e93b60ae.png)

It is also abnormal when an http 500 error or a php related error is issued.

**Comment by peppy** [comment]
How are you finding these beatmaps? If you are crawling the site and trying to download all beatmaps including graveyard, *please stop*. This kind of behaviour causes us to delete these beatmaps, as the retrieval cost gets very high if you do that.

**Comment by peppy** [comment]
I've fixed all the ones pointed out.

**Comment by peppy** [comment]
I've also fixed the error output to show an error page rather than erroring at the server-side.
