### ISSUE TITLE
Twitter button appears despite not having a twitter on profile

### ISSUE THREAD

**Issue by reo-the-enby** [ppy/osu-web#9353]
https://user-images.githubusercontent.com/81715029/194345733-e4b781f1-209a-43ad-8509-4f2fdc9a2c94.mp4

I looked at my profile and noticed just the @ symbol was appearing next to the twitter icon. It just takes me to the homepage of twitter. I don't have a twitter on my profile but even when the twitter box is clear it shows the @ symbol

**Comment by Walavouchey** [comment]
this was [reported earlier](https://github.com/ppy/osu-web/issues/9351) and [fixed already](https://github.com/ppy/osu-web/pull/9352) so you'll see the change on the next osu-web deploy
