### ISSUE TITLE
bpm selector on featured artists "track search" feels out of place

### ISSUE THREAD

**Issue by tybug** [ppy/osu-web#9357]
https://osu.ppy.sh/beatmaps/artists/tracks

the up/down arrows feel pretty out of place with general osu! design language (sharp corners, pretty bright white compared to the rest of the page):
<img width="239" alt="image" src="https://user-images.githubusercontent.com/31628143/194719624-d7f2c72c-f492-43b9-8d61-7978824bcb5f.png">

browser: chrome. Seems to be using the builtin browser widgets.

also checked on firefox, where the increment/decrementors appear even when the box isn't selected:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/31628143/194720046-148e3c2c-10b8-45b9-83d7-ee3f9d1fb9f8.png">

**Comment by peppy** [comment]
Not sure how easy it is to customise these. Could consider just removing altogether.
