### ISSUE TITLE
Beatmap page design choices

### ISSUE THREAD

**Issue by WorldSEnder** [ppy/osu-web#936]
There are a few things that I would like to see being cleared up a bit on the beatmap page.

- The user's top score, which most likely is one of the more interesting parts for him, is found at the bottom of the page. This not only breaks the flow that existed in the old page (user expectation) but I catch myself scrolling almost every time I visit a beatmap to see if I already have a score on it

- The button to Favourite the beatmap set has been removed or I am unable to spot it. Either way, I don't find it.

- The background image/banner is most of the time seriously cut because the current beatmaps have pretty quadratic images. A really good example is here: https://new.ppy.sh/beatmapsets/332532 where you see only a neck while the face is not visible

**Comment by peppy** [comment]
#1 addressed
#2 addressed
#3 we have an algorithm to decide the most "detailed" part of the background. in the case you mention the detail is not in the face, so it got cut off. eventually mappers may have a way to specify their own images for banner usage.
