### ISSUE TITLE
Inactive people do not get removed from individual key mania leaderboards

### ISSUE THREAD

**Issue by just7nz** [ppy/osu-web#9365]
After reworks, people that were inactive for 3 months or more get removed from global leaderboards, however, they stay in the mania 4k and 7k leaderboards, which in turn makes the 4k/7k rank in user profiles inaccurate.

https://osu.ppy.sh/rankings/mania/performance?variant=7k&page=3
See: MAAAAAAAAAAAAAS, [ Special ], Rio1-, Stink God

I've also been told restricted users are not removed from the rank number that is shown in the individual key rankings on the user profile, but I can neither confirm nor deny that.

**Comment by peppy** [comment]
Thanks for letting us know. I'll look into this one.

**Comment by peppy** [comment]
> After reworks, people that were inactive for 3 months or more get removed from global leaderboards, however, they stay in the mania 4k and 7k leaderboards, which in turn makes the 4k/7k rank in user profiles inaccurate.
> 
> https://osu.ppy.sh/rankings/mania/performance?variant=7k&page=3 See: MAAAAAAAAAAAAAS, [ Special ], Rio1-, Stink God
> 

Maybe there's a misunderstanding here? All users ranks around here look correct. The users there were not removed from leaderboards yet and are in an "inactive" state but still present and considered for rankings. Actual removed users will not show on that page.

> I've also been told restricted users are not removed from the rank number that is shown in the individual key rankings on the user profile, but I can neither confirm nor deny that.

I can confirm that restricted users are correctly handled as one would expect.

---

From my perspective everything looks to be working correctly, and would be in a sane state one day after any processing changes are applied. Could you please provide more specific detail showing the discrepancy if you still think there's an issue?

**Comment by Kasumiikun** [comment]
An example from my own profile (https://osu.ppy.sh/users/6177263/mania), might be related to what the original issue is reporting here
I show as 70th in the country ranking for 4K, whereas if you check leaderboards, I'm actually 59th.
There's a slight difference between my actual 4K rank being 4023 on the leaderboard and 4026 on my profile, but I think that's a non-issue.
The country ranking is really weird though.

**Comment by peppy** [comment]
Country rankings are *very* specific. This may just be a best-effort given how many filters need to be applied to make them happen. 

I'll investigate further.

**Comment by just7nz** [comment]
Quoting from the Star rating and Performance points  news post:
>Inactive users (anyone that has not played the game in 3 months) will be delisted.

That is correct with every single leaderboard (except catch at the time of writing this but yknow), there probably isn't a single person that has been inactive for a period longer than 3 months, however in the individual key leaderboards, there are users that were inactive for much longer than 3 months.
![chrome_h305KWot01](https://user-images.githubusercontent.com/61681644/196171386-91c20a7b-964f-48cd-90ba-4dd181b855cd.png)
![chrome_pJPc4d2vB0](https://user-images.githubusercontent.com/61681644/196171397-a54c737e-7cc3-4516-929b-1542d9b6245b.png)
(taken from [page 2 of 7k rankings](https://osu.ppy.sh/rankings/mania/performance?variant=7k&page=2))

>The users there were not removed from leaderboards yet and are in an "inactive" state but still present and considered for rankings.

Why are users in inactive state present and considered for rankings here, and nowhere else? The amount of time some users were inactive already is much more that the 3 months that were mentioned in news post. Is there even a longer period of time that has to pass until the user is completely delisted?

>can you show me a profile where the key rank looks obviously wrong

![chrome_AzjgQfSVIq](https://user-images.githubusercontent.com/61681644/196171749-660eb1b0-2fdc-4ffc-8fc1-8c19054667cb.png)
![chrome_NIdgT6YRtD](https://user-images.githubusercontent.com/61681644/196171768-5f89e9e7-918d-4899-92a6-a1f0ff03b202.png)
[my own profile](https://osu.ppy.sh/users/9949910)
https://osu.ppy.sh/rankings/mania/performance?variant=7k&page=22

**Comment by peppy** [comment]
Thanks for the more specific example!

**Comment by peppy** [comment]
I'm applying a fix imminently. The actual ranks should update within 24 hours. Will close this for now, but feel free to comment if you still see an issue.
