### ISSUE TITLE
Illegal trailing semicolon in Content-Disposition header field

### ISSUE THREAD

**Issue by popugasik** [ppy/osu-web#9371]
E.g. `https://osu.ppy.sh/beatmapsets/163112/download` redirects to another link (`https://bm6.ppy.sh/d/163112?...`) with invalid header field:

> Content-Disposition: attachment;filename="163112 Kuba Oms - My Love.osz";

Should be without `;` at the end.

Refer to [RFC 6266](https://datatracker.ietf.org/doc/html/rfc6266) or [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition).

**Comment by nanaya** [comment]
It's not handled by osu-web so there's nothing can be done here but I'd be interested why you care about this (and how you notice this). Did some program/browser refuse the header? At least firefox and chrome seem to handle it fine.

**Comment by popugasik** [comment]
I thought this issue goes here because of https://github.com/ppy/osu-web/issues/7202#issuecomment-778020745.

Some apps refuse to handle invalid headers and don't process filenames from headers (like at https://github.com/aria2/aria2/pull/391).

**Comment by peppy** [comment]
Are you seeing this on a browser?

If not, I don't think it is of concern to us.

**Comment by popugasik** [comment]
Modern browsers will accept this (may be with [warning]http://test.greenbytes.de/tech/tc2231/#attwithasciifilenamenqs?)

Sorry, I didn't check readme file and the word "web" mislead me. :sweat_smile: Is it osu-server related staff then? Where should I drop by?

**Comment by popugasik** [comment]
I think it would be nice to fix it. For example in case if someone would use alternative download manager add-on in their browsers. I actually discovered this issue while writing my own web-extension, and i can't do anything to solve it :slightly_smiling_face:

**Comment by peppy** [comment]
I've fixed it since I was working around similar code.
