### ISSUE TITLE
`/api/v2/beatmaps` seems to return `Beatmap`

### ISSUE THREAD

**Issue by tybug** [ppy/osu-web#9377]
[documentation for /beatmaps](https://osu.ppy.sh/docs/index.html#get-beatmaps) says that it returns `BeatmapCompact[]`, but it seems like it actually returns `Beatmap[]`:

```
GET https://osu.ppy.sh/api/v2/beatmaps?ids%5B%5D=221777
{
    "beatmaps": [
        {
            "beatmapset_id": 79498,
            "difficulty_rating": 5.82,
            "id": 221777,
            "mode": "osu",
            "status": "approved",
            "total_length": 386,
            "user_id": 1047883,
            "version": "Pretender",
            "accuracy": 8,
            "ar": 9,
            "bpm": 174,
            "convert": false,
            "count_circles": 854,
            "count_sliders": 593,
            "count_spinners": 3,
            "cs": 4,
            "deleted_at": null,
            "drain": 5,
            "hit_length": 364,
            "is_scoreable": true,
            "last_updated": "2014-05-18T17:22:23Z",
            "mode_int": 0,
            "passcount": 475211,
            "playcount": 6105120,
            "ranked": 2,
...
```

Not sure if this is unintentional, or the documentation is incorrect. fwiw, the equivalent endpoint for users (`/users`) does in fact return `UserCompact` and not `User`s.

**Comment by shinobu-uwu** [comment]
Yeah, it seems to be using the wrong transformer. Investigating the commit that added that route it appears to really be a mistake since the code conflicts with the PHPDoc. @nanaya can you confirm which type it should be returning?

https://github.com/ppy/osu-web/blob/08efa1a17ee471b0e8bda0b5fbc615dfda385e21/app/Http/Controllers/BeatmapsController.php#L29-L68

**Comment by nanaya** [comment]
Yes the documentation is slightly incorrect.
