### ISSUE TITLE
Subtopic links are broken only when visiting a single subforum

### ISSUE THREAD

**Issue by marcostudios** [ppy/osu-web#9382]
1. Visit a specific forum category (ex. General Discussion)
2. On top of the page hover to the "Other" link

![immagine](https://user-images.githubusercontent.com/5209299/196231703-8352a3fa-38fb-4e38-9a14-b4806f1be11f.png)

Result: https://osu.ppy.sh/community/forums#forum-11 instead of https://osu.ppy.sh/community/forums/11

**Comment by nanaya** [comment]
yes that is as expected as there shouldn't be anything but subforums in those forums.

**Comment by marcostudios** [comment]
Sorry, i meant not only in General Discussion/Other it was just an example. It also happens when you visit any specific subforum and on the top you click the Category (osu!/Beatmaps/Other/Language Specific).

**Comment by nanaya** [comment]
yes they're all the same.

**Comment by respektive** [comment]
Those forums have nothing in it, except the other sub-forums. The link should scroll you to the specific sub-forum on the main page though, is that not happening for you?

**Comment by respektive** [comment]
I don't think the link needs to go inside that forum, as there is nothing in it anyway. Seems fine to have the ability to also scroll to other forums easily as well.
