### ISSUE TITLE
User card design: brightness & gradient

### ISSUE THREAD

**Issue by VeilStar** [ppy/osu-web#94]
Creating this issue after [these 2 comments](http://blog.ppy.sh/post/129636272043/20150922#comment-2268002150) on blog.ppy.sh.

There's 2 things I would like to be changed about the user card design.

1. Removing the gradient on it.
The reason is simply that it feels out of place on the new osu!web, as there are no gradients used anywhere else on the website (to my knowledge).

2. Making the darkning overlay that is over the profile cover on the user card less strong.
Yes, there is white text right above it, so you probably still want it to be a bit darker so that the user can clearly see what you want to the user to see, however, as the page is already dimmed, and most of what isn't dimmed is pure white, it feels too dark.

Changing
`
transparent linear-gradient(to bottom, rgba(0, 0, 0, 0.5) 0px, rgba(0, 0, 0, 0.75) 100%) repeat scroll 0% 0%
`
to
`
transparent linear-gradient(to bottom, rgba(0, 0, 0, 0.35) 0px, rgba(0, 0, 0, 0.35) 100%) repeat scroll 0% 0%
`
is more or less what I think feels right.

Here's a comparison of the current user card and one where I quickly edited it to my liking, which is the idea I'm proposing here.

![osuwebusercard_01_current](https://cloud.githubusercontent.com/assets/14024130/10082577/b48a9eb0-62fa-11e5-8b1b-f88e0e2b1382.png)
![osuwebusercard_02_proposed](https://cloud.githubusercontent.com/assets/14024130/10082578/b490d0d2-62fa-11e5-9575-b7aa5caa604d.png)

**Comment by ameliaikeda** [comment]
You should probably take into account that black and grey are usually
whitewashed on crappy monitors, so maybe stick with the darker one since
it's easier to read.

**Comment by VeilStar** [comment]
I'd still like the gradient to be gone.
It could be darker than in the example I gave if readability becomes an issue.

Here's the same comparison with a pure white (RGB 255,255,255) profile cover as worst-case scenario.

![white_current](https://cloud.githubusercontent.com/assets/14024130/10149235/8ba4e802-6638-11e5-8827-cf909dcd70b9.png)

![white_proposed](https://cloud.githubusercontent.com/assets/14024130/10149236/8ba59c0c-6638-11e5-820f-2ba778a0b52e.png)

**Comment by RBRat3** [comment]
Did you take my settings out for a test drive?
transparent linear-gradient(to bottom, rgba(0, 0, 0, 0.1) 20%, rgba(0, 0, 0, 0.6) 100%) repeat scroll 0% 0%

**Comment by peppy** [comment]
@arflyte you okay with reducing or removing the gradient? i also feel like the current one is too dark.

**Comment by arflyte** [comment]
Yeah, I'm fine with removing the gradient.
