### ISSUE TITLE
Maybe somthing wrong happend

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-web#940]
here is my screenshot
![image](https://cloud.githubusercontent.com/assets/18349191/22455831/e6e5a4fe-e7c9-11e6-89c2-5cfff4f56be0.png)

And don't forget to solve my issue #931 ,I've waited for 5 days :(

**Comment by kj415j45** [comment]
And this maybe another error
![image](https://cloud.githubusercontent.com/assets/18349191/22455991/bb57ffac-e7ca-11e6-84dd-b3deef14048a.png)

↑ I've fix it in 3bf8ab6 :)↑

**Comment by kj415j45** [comment]
Don't forget to remove the DEBUG message @nanaya

**Comment by nanaya** [comment]
What DEBUG message?

**Comment by kj415j45** [comment]
like model_validation.forum.xxx

**Comment by nanaya** [comment]
that's not debug message. Just missing translation.

**Comment by kj415j45** [comment]
And please look the first screenshot,a strange translation key

**Comment by nanaya** [comment]
The translation key in translation file was just wrong.

**Comment by kj415j45** [comment]
OK,I've know :)
