### ISSUE TITLE
ApiV2, /beatmaps/{beatmap} returns {"error":null}, instead of a beatmap

### ISSUE THREAD

**Issue by WyvernX-YT** [ppy/osu-web#9403]
`Request<Long> GET_BEATMAPS = buildRequest("/beatmaps/{id}", RequestMethod.GET);`
`    public static HttpRequest buildRequest(Request<?> request, JsonObject data) {
        String access = data.get("access_token").getAsString();
        String url = request.getURL(data);
        return HttpRequest.newBuilder()
                .uri(URI.create(url))
                .header("Authorization", "Bearer " + access)
                .header("Content-Type", "application/json")
                .header("Accept", "application/json")
                .method(request.getMethod(), HttpRequest.BodyPublishers.noBody())
                .build();
    }
`

`
        HttpRequest request = RequestFactory.buildRequest(RequestFactory.GET_BEATMAPS, object.getJson());
        HttpResponse<String> response = api.getClient().send(request, HttpResponse.BodyHandlers.ofString());
`

this seems to return null instead of a beatmap

**Comment by WyvernX-YT** [comment]
And before you ask, I checked url, it is the exact same as the documentation, but returning null still

**Comment by nanaya** [comment]
what's the status code

**Comment by WyvernX-YT** [comment]
404.

**Comment by WyvernX-YT** [comment]
> what's the status code

Auth code is: 200

But the request status code is: 404

Im not really sure whats going on here, "not found"?

**Comment by nanaya** [comment]
well, maybe try accessing actually existing beatmap

**Comment by WyvernX-YT** [comment]
> well, maybe try accessing actually existing beatmap

Ive tried hundreds of existing beatmaps, same error.

**Comment by WyvernX-YT** [comment]
Ill try something for now we can close this, and see if the issue persists if so, I will reopen.

**Comment by WyvernX-YT** [comment]
> are you checking beatmap or beatmapset?

Beatmap, im using the second id, shown in a url.

**Comment by nanaya** [comment]
I don't know what language is that but maybe try hardcoding the url? `/beatmaps/123` - I assume the `/api/v2` prefix is automatically added?

**Comment by WyvernX-YT** [comment]
> I don't know what language is that but maybe try hardcoding the url? `/beatmaps/123` - I assume the `/api/v2` prefix is automatically added?

The url gets completed then debugged, the debugged url, is exactly the same format as it should be.

**Comment by nanaya** [comment]
what's one of the urls you tried with?

**Comment by WyvernX-YT** [comment]
> what's one of the urls you tried with?

https://osu.ppy.sh/api/v2/beatmaps/1786960

**Comment by nanaya** [comment]
Well I got the correct response here, so 🤷 As I mentioned above, have you tried with hardcoded url?

```
$ http get https://osu.ppy.sh/api/v2/beatmaps/1786960 Authorization:"Bearer $tok"
HTTP/1.1 200 OK
// ...other headers...

{
    "accuracy": 8.5,
    "ar": 8.3,
    "beatmapset": {
        "artist": "Tanizawa Tomofumi",
        "artist_unicode": "タニザワトモフミ",
        "availability": {
            "download_disabled": false,
            "more_information": null
        },
```

**Comment by WyvernX-YT** [comment]
> Well I got the correct response here, so 🤷 As I mentioned above, have you tried with hardcoded url?
> 
> ```
> $ http get https://osu.ppy.sh/api/v2/beatmaps/1786960 Authorization:"Bearer $tok"
> HTTP/1.1 200 OK
> // ...other headers...
> 
> {
>     "accuracy": 8.5,
>     "ar": 8.3,
>     "beatmapset": {
>         "artist": "Tanizawa Tomofumi",
>         "artist_unicode": "タニザワトモフミ",
>         "availability": {
>             "download_disabled": false,
>             "more_information": null
>         },
> ```

I will try with a hardcoded url right now.

**Comment by WyvernX-YT** [comment]
> Well I got the correct response here, so 🤷 As I mentioned above, have you tried with hardcoded url?
> 
> ```
> $ http get https://osu.ppy.sh/api/v2/beatmaps/1786960 Authorization:"Bearer $tok"
> HTTP/1.1 200 OK
> // ...other headers...
> 
> {
>     "accuracy": 8.5,
>     "ar": 8.3,
>     "beatmapset": {
>         "artist": "Tanizawa Tomofumi",
>         "artist_unicode": "タニザワトモフミ",
>         "availability": {
>             "download_disabled": false,
>             "more_information": null
>         },
> ```

Still returning null.

**Comment by nanaya** [comment]
As the url works with plain cli client and the full client code isn't available (or at least the full raw http request log), I don't think there's anything else can be done here. Or maybe if the problem can be reproduced with curl request.

**Comment by WyvernX-YT** [comment]
> As the url works with plain cli client and the full client code isn't available (or at least the full raw http request log), I don't think there's anything else can be done here. Or maybe if the problem can be reproduced with curl request.

Alright, ill try using a different method.

**Comment by nanaya** [comment]
Feel free to reopen/comment if the problem still happens with curl (or if there's full network request log available).
