### ISSUE TITLE
Replies on map discussion page duplicate themselves into the "Type Your Response Here" field

### ISSUE THREAD

**Issue by NevarrenF** [ppy/osu-web#9405]
So for about the last month or so I and a few other mappers have noticed that when you reply to a post sometimes that reply duplicates itself into the new response field.

![image](https://user-images.githubusercontent.com/62331647/197370130-4089bcb5-726f-4907-b6d4-bec008a2ff99.png)
![image](https://user-images.githubusercontent.com/62331647/197370136-462fc801-0488-4828-847e-1e55859bb49b.png)

here are the threads where it effects me personally.
https://osu.ppy.sh/beatmapsets/1821864/discussion
https://osu.ppy.sh/beatmapsets/1352410/discussion

Sorry I don't have much more info because it doesn't happen on every thread, my browser is Chrome.

**Comment by nanaya** [comment]
is this still happening?

**Comment by NevarrenF** [comment]
I personally haven't noticed it happening recently.

**Comment by nanaya** [comment]
Cool. Feel free to comment here or open a new one if happens again.
