### ISSUE TITLE
Some table columns still use fake utf8 datatype

### ISSUE THREAD

**Issue by nanaya** [ppy/osu-web#9412]
Caused various kinds of error.

Quick check on sentry there are at least unicode related errors on
- `osu_beatmaps.filename` (lookup by filename)
- `osu_user_reports.comment` (insert error due to emoji)
- `phpbb_poll_options.poll_option_text` (insert error due to emoji)

(also, it turned out username and email columns have been updated a while ago)

**Comment by peppy** [comment]
I've applied changes to these three cases. Fingers crossed they are the last.

**Comment by nanaya** [comment]
`osu_user_reports.comments` (I made a typo, it's not `comment`) and `phpbb_poll_options.poll_option_text` are still utf8mb3 it seems

**Comment by peppy** [comment]
Well that's amazing. Changing the `DEFAULT` when a column was using the default seems to implicitly update that column's specification to mb3...

**Comment by peppy** [comment]
Should be fixed correctly this time..
