### ISSUE TITLE
Language choose

### ISSUE THREAD

**Issue by kj415j45** [ppy/osu-web#942]
During I translate osu-web,I found a BUG(maybe it's feature XD)

If I haven't login,I can't change language :(
But if I login,I can change language :)

Maybe it'll be difficult for someone who first enter osu-web and doesn't understand english because he haven't have an account and login to change language(maybe)

**Comment by kj415j45** [comment]
And I think we should remove italic for chinese,because:
![image](https://cloud.githubusercontent.com/assets/18349191/22477778/6080d952-e822-11e6-91af-4d98200f05da.png)
it's so stupid XD

**Comment by benpigchu** [comment]
【the Chinese font should be a common sans-serif font rather than “宋体”】

**Comment by nanaya** [comment]
seems fixed
