### ISSUE TITLE
GET /rooms doesn't allow getting match data from classic matches

### ISSUE THREAD

**Issue by longnguyen2004** [ppy/osu-web#9454]
I'm trying to get the match data from https://osu.ppy.sh/community/matches/87538928. v1 returns the data properly, while v2 returns a 404. Does the v2 API only look for lazer matches, and not classic?

**Comment by cl8n** [comment]
there's GET /matches and GET /matches/{id} but they're not documented. response format isn't the same as v1 but it probably has what you're looking for

/rooms is for lazer multiplayer

**Comment by longnguyen2004** [comment]
It's way under the Undocumented sections in the doc. I guess I'll leave this issue open until they're documented?

**Comment by nanaya** [comment]
The docs is known to be underdocumented and there's no point having open issue for every single endpoints.
