### ISSUE TITLE
Unmarked osu! originals

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu-web#9457]
these are fa songs that were commissioned or specifically made for osu! (as listed in the [osu! originals](https://osu.ppy.sh/wiki/en/osu!_originals) wiki article), but aren't labelled on the fa listing for some reason.

- [onumi & Akira Complex - Ethereal Cyber Angel XV](https://osu.ppy.sh/beatmaps/artists/tracks?is_default_sort=true&sort=relevance_desc&query=%22ethereal%20cyber%20angel%20xv%22)
- [Frums - of Ambrosia](https://osu.ppy.sh/beatmaps/artists/68#album-814)
- [aa...hisuichazuke... - steganography](https://osu.ppy.sh/beatmaps/artists/tracks?is_default_sort=true&sort=relevance_desc&query=steganography)
- [II-L - Asteroid Field of DECAPLETS](https://osu.ppy.sh/beatmaps/artists/tracks?is_default_sort=true&query=decaplets&sort=relevance_desc&artist=ii-l)
- [SAMString - NUMA](https://osu.ppy.sh/beatmaps/artists/tracks?is_default_sort=true&sort=update_desc&artist=samstring&query=numa)
- [UNDEAD CORPORATION - The Throne](https://osu.ppy.sh/beatmaps/artists/tracks?artist=undead%20corporation&bpm%5Bgte%5D=220&bpm%5Blte%5D=220&is_default_sort=true&length%5Bgte%5D=394&length%5Blte%5D=394&query=the%20throne&sort=relevance_desc)
- [Rabbit House - Muspelheim](https://osu.ppy.sh/beatmaps/artists/tracks?artist=rabbit%20house&is_default_sort=true&query=muspelheim&sort=relevance_desc)
- [Camellia - OOPARTS](https://osu.ppy.sh/beatmaps/artists/tracks?is_default_sort=true&sort=update_desc&query=OOPARTS)

**Comment by peppy** [comment]
@Ephemeralis

**Comment by Ephemeralis** [comment]
These are now all properly set.

**Comment by Walavouchey** [comment]
@Ephemeralis 

- [DJ Raisei - T.R.AP.](https://osu.ppy.sh/beatmaps/artists/tracks?artist=DJ%20Raisei&query=T.R.A.P.)
- [seatrus - Querasis](https://osu.ppy.sh/beatmaps/artists/tracks?artist=seatrus&query=Querasis) (where are the other corsace originals that were made by featured artists)
- [SAMString - Crystalised Euphoria](https://osu.ppy.sh/beatmaps/artists/tracks?query=Crystalised%20Euphoria&artist=SAMString)
- [SAMString - Akarui Taiyo](https://osu.ppy.sh/beatmaps/artists/tracks?artist=SAMString&query=%22Akarui%20Taiyo%22)

**Comment by Ephemeralis** [comment]
The above are all now marked correctly.
