### ISSUE TITLE
Some beatmaps are missing the "Spotlight" label

### ISSUE THREAD

**Issue by tematikkp** [ppy/osu-web#9466]
Here are the beatmaps that have no "Spotlight" tag:
https://osu.ppy.sh/beatmapsets/1570536
https://osu.ppy.sh/beatmapsets/1373644
https://osu.ppy.sh/beatmapsets/1714190
https://osu.ppy.sh/beatmapsets/1774999
https://osu.ppy.sh/beatmapsets/1742131
https://osu.ppy.sh/beatmapsets/543917
https://osu.ppy.sh/beatmapsets/1593278
https://osu.ppy.sh/beatmapsets/1610294
https://osu.ppy.sh/beatmapsets/1611987
https://osu.ppy.sh/beatmapsets/1762719
https://osu.ppy.sh/beatmapsets/1453784
https://osu.ppy.sh/beatmapsets/1328323
https://osu.ppy.sh/beatmapsets/1646183
https://osu.ppy.sh/beatmapsets/1769222
https://osu.ppy.sh/beatmapsets/1687320
https://osu.ppy.sh/beatmapsets/1507426
https://osu.ppy.sh/beatmapsets/1678112
https://osu.ppy.sh/beatmapsets/978534
https://osu.ppy.sh/beatmapsets/1734128
https://osu.ppy.sh/beatmapsets/1774562
https://osu.ppy.sh/beatmapsets/1031588
https://osu.ppy.sh/beatmapsets/933984
https://osu.ppy.sh/beatmapsets/1592786
https://osu.ppy.sh/beatmapsets/1525823
https://osu.ppy.sh/beatmapsets/74274
https://osu.ppy.sh/beatmapsets/1734804
https://osu.ppy.sh/beatmapsets/506110
https://osu.ppy.sh/beatmapsets/1683802
https://osu.ppy.sh/beatmapsets/1435937
https://osu.ppy.sh/beatmapsets/1741009
https://osu.ppy.sh/beatmapsets/365716
https://osu.ppy.sh/beatmapsets/1683972
https://osu.ppy.sh/beatmapsets/1378488
https://osu.ppy.sh/beatmapsets/1326970
https://osu.ppy.sh/beatmapsets/1645306

I'm sorry if this is so many. These beatmaps appeared in the Summer 2022 Playlist C, but probably peppy forgot to add these.

**Comment by aceticke** [comment]
Aren't these currently in voting?

**Comment by peppy** [comment]
@Ephemeralis can you take a look at this one?

**Comment by Ephemeralis** [comment]
Checked in with Venix and have set spotlight flag for the following sets as pulled from the playlist system:

```1570536, 1373644, 1714190, 1774999, 1742131, 543917, 1593278, 1610294, 1611987, 1762719, 1453784, 1328323, 1646183, 1769222, 1715489, 1687320, 1507426, 1678112, 978534, 1734128, 1774562, 1031588, 933984, 1592786, 1525823, 74274, 1734804, 506110, 1683802, 1435937, 1741009, 365716, 1683972, 1378488, 1326970, 1645306```

This incorporates all but three sets listed in the main issue that apparently weren't supposed to qualify.
