### ISSUE TITLE
Add Triangles beatmap contest winner to bundled beatmap asset path

### ISSUE THREAD

**Issue by jai-x** [ppy/osu-web#9509]
Winner of the triangles beatmap contest is to have their beatmap bundled with osu!lazer.
For this, the beatmap `1841885 cYsmix - triangles.osz` file needs to be available at the path `https://assets.ppy.sh/client-resources/bundled/...` like the other bundled beatmaps.

Winner annoucement: https://osu.ppy.sh/home/news/2022-10-06-results-triangles
Beatmapset link: https://osu.ppy.sh/beatmapsets/1841885

**Comment by peppy** [comment]
I've uploaded this.
