### ISSUE TITLE
Prioritize osu!originals in Featured Artist track listing sort order

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#9519]
![](https://puu.sh/JrKD3/40954b3638.png)

This is a fairly minor cosmetic thing, but I feel like the logical expectation for sorting here is to have the osu!originals be first in the order and clustered together instead of spread out amongst the album/song grouping.

Expected order:
- New originals
- Existing originals
- New normal tracks
- Existing normal tracks

**Comment by nanaya** [comment]
The grouping (and sorting) starts from album so do you mean:

- Original albums (sorted by id desc)
  - tracks sorted by display_order
- New original tracks ("Songs" album)
  - tracks sorted by id desc
- Existing original tracks (or should they be combined with new original tracks?) ("Songs" album)
  - tracks sorted by id desc
- Normal albums (sorted by id desc)
  - tracks sorted by display_order
- New normal tracks ("Songs" album)
  - tracks sorted by id desc
- Existing normal tracks (or should they be combined with new normal tracks?) ("Songs" album)
  - tracks sorted by id desc

This assumes there's no album with mixed original and normal tracks in which case it'll be... split? combined and sorted along original albums area? How should the tracks inside be sorted?

For reference, current sorting is:
- Albums (sorted by id desc)
  - tracks sorted by <del>display_order</del> id asc (kind of)
- Tracks ("Songs" album)
  - tracks sorted by id desc

**Comment by Ephemeralis** [comment]
Oh, this is more geared towards changing the sorting _inside_ albums (including the Songs generic album) to always showing osu! originals first, to more or less the first thing you see is the osu! originals clustered together inside their appropriate albums. Otherwise, the way everything works now is fine.

If this is a royal pain in the balls to hash out, creating a per-track ``display_order`` similar to other implementations that can be used to sort them as needed might be a better approach, and originals can just be set this way manually via DB or during the addition process.

To help clarify what I mean, if display_order was added, originals would always have whatever display_order assignment which would make them appear at the top of a given album view compared to any other track inside the same album.

**Comment by nanaya** [comment]
well this part

> have the osu!originals be first in the order and clustered together instead of spread out amongst the album/song grouping

kind of saying something... different.

anyway, tracks in album are currently sorted by id ascending (oldest first) while in "songs" are id descending (newest first). Should those stay and just move originals to the top or flip the order for album tracks as well?

`display_order` can be made to always override both original and id orders.
