### ISSUE TITLE
Incorrect Forum Order in Forum Select Dropdown

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#9525]
![image](https://user-images.githubusercontent.com/35633093/202829676-4d58c7c0-23db-4662-b962-7d7139aef036.png)

For some reason the WIP and Remixed skins subforum display under Help and not Skinning. WIP used to be ordered correctly until recently, I suspect this happened when Remixed forum was added and WIP edited

**Comment by RockRoller01** [comment]
@peppy Im just going to highlight you as this probably is a job for you

**Comment by peppy** [comment]
I believe this should be resolved now, via black magic phpbb fuckery. Could you please confirm?

**Comment by RockRoller01** [comment]
can confirm, the black magic phpbb fuckery worked
