### ISSUE TITLE
osu! World Cup profile banners has horizontal gaps on profile pages other than the info page   

### ISSUE THREAD

**Issue by kesedihan** [ppy/osu-web#9531]
Main (info) page (/users/<userid>) :
![image](https://user-images.githubusercontent.com/57430190/203380294-9277c31c-b523-4f32-b2c0-efb022bda922.png)

The other pages (/users/<userid>/modding, /users/<userid>/playlists, /users/<userid>/realtime)

![image](https://user-images.githubusercontent.com/57430190/203380570-6edc5d04-f5e3-4967-8264-2194bedb40af.png)
![image](https://user-images.githubusercontent.com/57430190/203380722-f0b91522-c4fd-46c4-ac4d-23a38a070c31.png)
![image](https://user-images.githubusercontent.com/57430190/203380617-3b0e2a47-d9a6-4bb6-a3c8-0a0b3abe7a95.png)

**Comment by tematikkp** [comment]
I think that's intentional, along with the badges (?)
