### ISSUE TITLE
Mapper's username on web does not match in-game

### ISSUE THREAD

**Issue by TheRealStevie** [ppy/osu-web#9533]
[Echo](https://osu.ppy.sh/users/431)'s maps (at least the ranked ones) on web show the username as "Echo", but in-game (with exceptions [1](https://osu.ppy.sh/beatmapsets/3697#osu/22422), [2](https://osu.ppy.sh/beatmapsets/3339#osu/23170)) it shows as "Echo49".

[An example](https://osu.ppy.sh/beatmapsets/920#osu/6783) on web:
![Screenshot 2022-11-24 010131](https://user-images.githubusercontent.com/75444413/203593033-4cd0651c-6dbc-4414-a8a5-4f274f0a04f6.png)
![Screenshot 2022-11-24 010559](https://user-images.githubusercontent.com/75444413/203593659-12f266d2-a937-48f1-aac5-dbb69efe619a.png)

Same map in-game:
![Screenshot 2022-11-24 010218](https://user-images.githubusercontent.com/75444413/203593159-420a187d-8f67-4518-b79d-bb6680c8f591.png)

**Comment by WindowsMeosu** [comment]
2 things:
could be an old username
maybe an issue with an old version of the Beatmap Submission System

**Comment by loma-baldsson** [comment]
Fair point, but they should match regardless. There are some mappers who submit maps under another username (iljaaz and scubdomino are the first to come to mind) without getting their name changed, and the username still matches both in-game on the site.

**Comment by peppy** [comment]
That is correct.
