### ISSUE TITLE
ScoreV2 Causing weirdness with pass/fc medals. (mania)

### ISSUE THREAD

**Issue by chromb** [ppy/osu-web#9534]
Don't really know how to word this, but pass/fc medals are pretty free via mashing in mania due to changes in how judgements and 'columnlock' work. Don't know exactly what I should write here, but for reference here's a video of it in action:  

https://www.youtube.com/watch?v=uVGhw4uwqnk

**Comment by nanaya** [comment]
I don't think this issue belongs here. @peppy

**Comment by chromb** [comment]
gonna close this as it got resolved a long time ago, and I forgot i made this issue in the first place :P
