### ISSUE TITLE
The date is not shown in different languages. It seems to be only in English.

### ISSUE THREAD

**Issue by AndReyHentai** [ppy/osu-web#9536]
![image](https://user-images.githubusercontent.com/71509022/203713026-27e3c79c-f94f-44b5-8f4b-413b14e1e8d8.png)

![image](https://user-images.githubusercontent.com/71509022/203712941-8279d5cf-a786-4e36-a401-6ada972471f0.png)

**Comment by yuzupon1133** [comment]
![image](https://user-images.githubusercontent.com/65931718/203722709-6ae02ef6-4d07-4972-b4cd-7498dea4eed5.png)
and osu!direct button.

**Comment by peppy** [comment]
#9538

**Comment by notbakaneko** [comment]
Is fixed in #9538 (and also text missing translations like the `pp` column)
