### ISSUE TITLE
Add an option to change the account visibility.

### ISSUE THREAD

**Issue by glacc** [ppy/osu-web#9541]
When hiding the account, the user page, uploaded scores on leaderboard etc. will be not visible to others, just like a restricted account, but the account is not actually restricted. And this option has cooldown when change it everytime.

**Comment by agatemosu** [comment]
It would be like choosing if a certain profile tab can be seen only by you, your friends or everyone.

**Comment by peppy** [comment]
I don't foresee this happening..

**Comment by loma-baldsson** [comment]
i feel like this can be abused by cheaters to hide scores
