### ISSUE TITLE
Play

### ISSUE THREAD

**Issue by kziro** [ppy/osu-web#955]
Is there a website except [http://osu-web.com/](url) where I can see this script in action?

**Comment by LiquidPL** [comment]
Uh, i think you're a little mistaken here.

http://osu-web.com seems to be some sort of an implementation of the game in a browser, while this repository contains the new version of osu!'s official website.

([This](https://github.com/pictuga/osu-web) is what appears to be a repo for http://osu-web.com.)

**Comment by nanaya** [comment]
ಠ_ಠ
