### ISSUE TITLE
seprate beatmap packs in different areas for each gamemode 

### ISSUE THREAD

**Issue by mugiishiro** [ppy/osu-web#9551]
so basically that it's easier to search for beatmap packs without having to scroll through every other gamemode. could also be done for loved/ranked maps but the amount of loved is probably to low.

**Comment by WindowsMeosu** [comment]
isn't that what mode=osu!/taiko/ctb/mania and status=ranked/approved/loved/unranked is for?

**Comment by Joehuu** [comment]
Duplicate of https://github.com/ppy/osu-web/issues/4247
