### ISSUE TITLE
The Badge from a former BN doesn't go to the BN Wiki Page

### ISSUE THREAD

**Issue by mugiishiro** [ppy/osu-web#9556]
Active BN: see the profile of https://osu.ppy.sh/u/wafer Badge goes to the BN Wiki page
Former BN: see the profile of https://osu.ppy.sh/u/Delis Badge doesn't go anywhere

**Comment by RockRoller01** [comment]
@Ephemeralis thats a job for you I believe

**Comment by Ephemeralis** [comment]
These are now all batch fixed, for all BN badges (or should be at least).
