### ISSUE TITLE
Badge from the osu!stats developer has an incosistent title and doesn't lead to anywhere

### ISSUE THREAD

**Issue by mugiishiro** [ppy/osu-web#9563]
https://osu.ppy.sh/users/Piotrekol = creator of osu!stats
his badge has a inconsistent title compared to the other "osu!contributors"
and his badge also goes no were if you click on it.

a suggestion would also be that mulraf (osekai) and Badewanne3 (bathbot)
get their respectful badges for their contributions to osu

**Comment by RockRoller01** [comment]
@Ephemeralis more badge issues

**Comment by Ephemeralis** [comment]
This has been fixed.

For future reference, unless the badge title is very inaccurate or straight up wrong, we tend to preserve old contributor badges as-is in order to preserve history. Uniformity is less important in that regard.
