### ISSUE TITLE
Non existing gold S ranks 

### ISSUE THREAD

**Issue by Gilus420** [ppy/osu-web#9566]
Maybe my taiko profile isn't updated but I have the issue that there are some gold S on my osu profile which don't exist anymore.
I have 43 scores in total, all of them are SS but on the website it displays 4 silver SS 36 gold SS and 2 gold S, it displays 42 scores but I 
have 43 top plays for some reason, I honestly don't know what to do could someone help me pls?

**Comment by nanaya** [comment]
What's the user id/name? Is it still a problem?
