### ISSUE TITLE
Artist portrait on all featured artist pages looks broken

### ISSUE THREAD

**Issue by apollo-dw** [ppy/osu-web#9570]
![image](https://user-images.githubusercontent.com/83023433/204796785-6d6a5a00-228f-458e-b74f-2fe0b0c40856.png)

The portrait is overlapping the header components

**Comment by notbakaneko** [comment]
The overlap so it starts from the title bar instead of an empty space is intentional.

**Comment by Joehuu** [comment]
The design is getting changed anyway, see https://www.figma.com/file/bFBmdDhNuDBOCLyMTQYhQM/Featured-Artist?node-id=0%3A1:

<img width="569" alt="Screenshot 2022-11-30 at 8 09 31 PM" src="https://user-images.githubusercontent.com/35318437/204963733-fd2c8c37-7252-4022-95f7-ee835e8051cf.png">
