### ISSUE TITLE
Beatmap removal tweaks

### ISSUE THREAD

**Issue by Nukrid** [ppy/osu-web#9572]
The beatmap deletion command on ASS could use a few tweaks:

1 - BanchoBot is always the operator, it should probably be the person who uses the command, just like .s and .rm

2 - We don't have a copy of the background of the map, it would be VERY useful to have it, just like removing covers and avatars leave a logged copy. Inappropriate background removals are one of the most common ones, so it is very important.

3 - We could also make use of specifying reasons on the command, so it gets tracked better if the removal reason isn't really that obvious.

In case such reason can be appended on the support mail template, it would be very useful for the person to immediately know what was the cause behind it.

**Comment by TicClick** [comment]
for 2), can suggest attaching the whole beatmap as a catch-all solution (required for more involved cases)

**Comment by Nukrid** [comment]
Points 1 and 3 have been solved, point 2 now being tracked in [https://github.com/ppy/osu-web/issues/9594](url), will close it now.
