### ISSUE TITLE
Beatmap has (seemingly) 2 nominations from the same user

### ISSUE THREAD

**Issue by Hiviexd** [ppy/osu-web#9580]
![image](https://user-images.githubusercontent.com/62819481/205353057-e78e4e33-480d-4389-9001-085713fb6670.png)

https://osu.ppy.sh/beatmapsets/1768045/discussion?user=1561995

**Comment by aceticke** [comment]
something recent must've broken it, i checked this map's discussion recently and it only had one nomination (just said the user once)

**Comment by aceticke** [comment]
it's applying to all maps with only one nomination
