### ISSUE TITLE
Storyboarded maps can have icon not displayed on page due to incorrect file capitalisations.

### ISSUE THREAD

**Issue by Coppertine** [ppy/osu-web#9585]
This is a bit of a weird situation. 
But as seen on this map: https://osu.ppy.sh/beatmapsets/1851103#osu/3802734
the storyboard icon and status is not placed even though a .osb file is found in the set.
The main issue is that the capitalisation of both the .osu and .osb files (although read correctly by stable) are not the same for the side of the website.
![image](https://user-images.githubusercontent.com/37494321/205477514-e9564de1-e327-4ec8-924f-0f90668fe930.png)
(For above example, the .osu file should be `twenty one pilots - Heathens (Magnetude Bootleg) (funny) [Marathon].osu` as is what's part of the correct metadata of said beatmap)

I have given a [problem report to the beatmap](https://osu.ppy.sh/beatmapsets/1851103/discussion/-/generalAll#/3437948) as it is currently in the Qualified stage, however, I do like to notify the issue on the website in case this little edge-case should be fixed.

**Comment by Walavouchey** [comment]
in any other case where the filenames don't match up to before the difficulty name, stable just doesn't load the sb, which would've made this issue discoverable way before qualified.

looking at a [tangentially related lazer issue](https://github.com/ppy/osu/issues/1295), it might be intentional that filenames are treated case-insensitively everywhere, in which case this would need fixing on osu-web

**Comment by peppy** [comment]
This should be fixed by fixing the `osz` on the server, as it will cause issues elsewhere.

**Comment by Coppertine** [comment]
For the map used in this report, it was fixed before it was pushed to ranked after I made this issue.
I'm essentially seeing if osu-web would be able to check for osb files case-insenisively (same name of course) upon new uploads (old uploads would of course tons of problems)

**Comment by peppy** [comment]
No, it wouldn't/shouldn't. This needs to be fixed before rank, as it's an actual issue. It should NEVER happen unless the user has made manual changes. If it's not fixed, it will cause issues on certain file systems.
