### ISSUE TITLE
Soft beatmap deletion being available for moderators to see

### ISSUE THREAD

**Issue by Nukrid** [ppy/osu-web#9594]
New issue as solicited here #9572

This should tackle the point 2 made initially, which was availability for the background, but as Peppy said, it is just better to have it accessible to moderators to prevent beatmap duplication or other uploads being necessary.

The end goal is to have the contents accessible by moderators (GMT/NAT) after the deletion, with some kind of visibility or disclaimer being available for us to know it has in fact been deleted, so we don't confuse ourselves.

<s>I was also thinking that, with the page being available, we could also possibly be able to restore beatmaps that have been deleted by mistake (like what happened with a beatmap recently that got deleted by inappropriate background but it could just be changed, as it wasn't anything egregious) but that surely needs discussion beforehand.</s>

Edit: as talked with ppy now, not worth the effort of putting a restoration button, so only the visibility should be good.

**Comment by peppy** [comment]
I've added this to the roadmap.

@ppy/team-web this should be a pretty simple one – make beatmap pages (ie. https://osu.ppy.sh/beatmapsets/1872603#fruits/3853231) visible to moderators even when the beatmap is deleted, with a messages somewhere visible on the page letting them know that the beatmap is deleted. Something similar to restricted users would work fine. Doesn't need to be fancy.

**Comment by nanaya** [comment]
Is it about making beatmap page visible or not deleting beatmap cover? (or both?)

Also I assume this doesn't mean moderators can see deleted beatmap on visible beatmapset right?

**Comment by peppy** [comment]
> Is it about making beatmap page visible or not deleting beatmap cover? (or both?)

Covers are generally not deleted anymore (we've changed the process so that the beatmap itself is deleted, but the cover remains, except for excruciating circumstances. ~~I don't think osu-web has support for deleting the cover does it?~~

> Beatmap(set) deletion task currently immediately removes all covers for the beatmap(set).

Is this when a user chooses to delete their beatmap? If that's the case, then that's fine to continue deleting the background. The special case here is where a moderator soft deletes a beatmap pending discussion / response from the user, I believe. This is done via ASS.

> Also I assume this doesn't mean moderators can see deleted beatmap on visible beatmapset right?

That's an interesting one. I guess that's correct though, it would create too much noise.

So the conditional would have to be... 

```
if beatmapset deleted_at is not null and user is moderator
    display all beatmaps (even if beatmap.deleted_at is not null)
else
   no change from current implemementation
```

**Comment by nanaya** [comment]
> Is this when a user chooses to delete their beatmap? If that's the case, then that's fine to continue deleting the background. The special case here is where a moderator soft deletes a beatmap pending discussion / response from the user, I believe. This is done via ASS.

No the task I meant is for moderator deletion which includes the one done via bot (which hits the interop endpoint for actual deletion task). I don't think osu-web handles user deletion at the moment.

**Comment by peppy** [comment]
Right I see..

Graveyard only might be okay. Feels a bit weird still.

**Comment by RockRoller01** [comment]
> Graveyard only might be okay. Feels a bit weird still.

graveyard is one of the main places where this featured would be needed for moderators. Basically anywhere that doesn't have a leaderboard we might delete a beatmap

**Comment by nanaya** [comment]
So, no cover deletion? osu-web can't display/use background image in the osz archive directly.

**Comment by nanaya** [comment]
Added in #9845.
