### ISSUE TITLE
Featured Artist track title missing hover tooltip when truncated

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu-web#9600]
when hovering over the track title, you get a whole bunch of nothing

![image](https://user-images.githubusercontent.com/36758269/205999688-12d1003c-cc13-48ee-aa87-a0d581c7a749.png)

would be good if this had a tooltip like in other places

![image](https://user-images.githubusercontent.com/36758269/205999876-4a7d2506-f9a5-4716-9576-f56063a26f72.png)

**Comment by nanaya** [comment]
Well that's because the title in the first screenshot isn't truncated so there's no tooltip to be shown. The tooltip is there if it's actually truncated

![](https://s.myconan.tk/2022-12/firefox_2022-12-07_14-32-19.png)

**Comment by Walavouchey** [comment]
curious as to why the whole title can't be included, if it would be truncated properly anyway @Ephemeralis
