### ISSUE TITLE
GET `/v2/scores/{mode}/{score}/download` returns HTTP 401

### ISSUE THREAD

**Issue by mezodev0** [ppy/osu-web#9608]
When trying to call https://osu.ppy.sh/api/v2/scores/osu/2177560145/download, the api returns a HTTP 401. Is this intended?

**Comment by cl8n** [comment]
make sure you're calling the API the correct way & that other endpoints aren't giving the same error. also make sure your token has the `public` scope, for this endpoint. it's working fine for me

**Comment by tybug** [comment]
In addition to the above, ensure that you are authenticating with the Authorization Code grant, not the Client Credentials grant. The latter acts as a guest user and does not have permission to access the replay download endpint.

**Comment by mezodev0** [comment]
@tybug that was it, thanks.
