### ISSUE TITLE
Home page "highlights" section

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu-web#9614]
a while ago i saw [this tweet](https://twitter.com/exaiosu/status/1591631502823288832) concerning visibility of the world cup on the website. yes, current events are advertised in the main menu of stable, but it would indeed be nice for the same functionality to appear on the website.

designs for this have existed for [years](https://github.com/ppy/osu-web/issues/2394#issuecomment-365808656), but it has never been implemented for some reason, even though most of the home page design is up to date

current [figma design](https://www.figma.com/file/M2Nzhk2W1WahX8ssvIkpTD/Web%2FDashboard):

![Screenshot 2022-12-08 203429](https://user-images.githubusercontent.com/36758269/206538541-55bad03e-63c6-434f-b243-f4932eb95b98.png)

i suppose at minimum these would be clickable images that lead to the respective news post, contest or tournament page, or wiki article, assigned manually like the in-game main menu banner. seeing as the design implies multiple images (that probably switch between each other every few seconds), this would be a good upgrade from the single png on the client main menu, and help with the issue of concurrent events fighting for the main menu spotlight.

**Comment by RockRoller01** [comment]
this is probably also very useful to ease the issue of FA newsposts pushing other posts out of the spotlight too quickly ( #7685 )
