### ISSUE TITLE
"Show deleted" comments toggle shouldn't show for non-moderators

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#9615]

**Comment by RockRoller01** [comment]
To explain a bit more where this sudden issue is coming from: this spawned from the fact that comment replies are fully intact if the parent is deleted. I have commented about this in #8700 before, and its still an annoyance.

After a short discussion internally the following solution was agreed on:

Make children inaccessible (non replyable, dont show in search/comments list, no content if accessed via e.g. permalink as if it was deleted) if their parent (either direct or further up the chain) is deleted. To prevent the whole "commenters could silence others by deleting their own post" issue which was given as the reason in #8700 just make comments behave like discussion posts and forum threads. The parent can not be deleted by the poster if there are any replies.

(this also has the neat side effect of making the behaviour of deleted content more in line across the site)

**Comment by cl8n** [comment]
this feels like a downgrade... the person who would've previously deleted their comment would now just edit to nothing instead, if they want it gone. I don't see how this is an "annoyance" to begin with

**Comment by peppy** [comment]
Keep in mind that I made this issue because there's no easy way to delete a whole thread currently. So if it's changed to still display replies it won't solve the actual issue (see https://osu.ppy.sh/comments/2531769)

**Comment by nanaya** [comment]
that looks more like the individual comments should be deleted instead

**Comment by peppy** [comment]
Yeah, problem is there's hundreds and doing that manually is a bit of a chore (which is why this came up).

**Comment by nanaya** [comment]
A delete recursive button is probably better in this case.

**Comment by nanaya** [comment]
It's been removed (although the resulting behaviour is probably not quite what's wanted).
