### ISSUE TITLE
Spanish has an incorrect thousands separator

### ISSUE THREAD

**Issue by agatemosu** [ppy/osu-web#9625]
- unicode-org/cldr#2027

The thousands separator for Spanish should be a thin space, as in French.

**Comment by nanaya** [comment]
it's defined by the browser. We could hack the change in but you may better push for the change in [unicode standard](https://st.unicode.org/cldr-apps/v#/es/Symbols/) itself. [Related bug in chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=1207059). And it seems Windows is using the same formatting as well (do you guys just change it manually on every Windows installation?).

**Comment by nanaya** [comment]
From what I gather both have some level of usage with space being the current official rule but period is still in common use. Unless this is causing major confusion, following unicode as is seems like the best path forward for now.
