### ISSUE TITLE
Scaling did not change for Recommended Diffiuclty in osu!taiko

### ISSUE THREAD

**Issue by mangomizer** [ppy/osu-web#9626]
With the recent changes in osu!taiko resulting in a roughly 30-40% increase in pp for all users, the Recommended Difficulty did not change to reflect this and now I am being recommended 9* maps which is probably a little beyond my skill level.
![image](https://user-images.githubusercontent.com/30021847/206961283-7595519f-b369-4234-b300-97feb26dc943.png)

**Comment by cl8n** [comment]
are you able to recommend an alternative? for reference it's currently `pp^0.4 * 0.195`

**Comment by mangomizer** [comment]
No but @ppy/taiko-pp-commitee might be able to advise.

**Comment by vunyunt** [comment]
The PP scaling function currently is in a bit of a mess. From what I remember, the previous rescale was done by increasing the power to difficulty value, but there were a bunch of other changes too.

Once we get to reworking performance calculator, this scaling will probably be changed again. So a simpler solution would work for the time being. 

Seeing as how the previous change made a bigger difference in higher SR scores, it may be a good idea to reduce the power and increase the modifier instead, so as to curve the graph more. Here's a quick desmos graph to demonstrate: 
![image](https://user-images.githubusercontent.com/5846322/207000189-550778f8-900c-4168-b18c-ef0bba2bf686.png)
