### ISSUE TITLE
hovering on friends page component disables active highlighting 

### ISSUE THREAD

**Issue by tybug** [ppy/osu-web#9655]
https://osu.ppy.sh/home/friends

https://user-images.githubusercontent.com/31628143/208476564-539e26be-e85c-4de1-8dcb-12471a7617b1.mov

**Comment by nanaya** [comment]
That looks like by design so there's no duplicate highlights

**Comment by tybug** [comment]
wouldn't it be better to only disable the highlight when the cursor is actually over another option, like "online" or "offline"? All I can say is this was pretty jarring when I was moving my cursor around the page, since there's a lot of empty space to the right where it's not clear this is intentional.
