### ISSUE TITLE
Add Kazakhstan to country dropdown options

### ISSUE THREAD

**Issue by itotallygetthat** [ppy/osu-web#9658]
As per the comments in #8699 , the list of countries included in the country list dropdown on the website is set manually.  There are currently 122 countries in this list.

The number of osu! players in Kazakhstan has grown significantly in the last few years.  Some stats showing why Kazakhstan should be included in the main country dropdown now:
- over 100k accounts, easily within the top 50 countries
- 39th in country pp
- participated in OWC qualifiers in 2021 + 2022.  Possibly the only country that has recently participated in OWC recently that is not included in the country dropdown

Arguments could be made for also including Kyrgyzstan and Uzbekistan (currently 91th + 93th in country pp), but they are borderline as it seems that historically the cutoff is around top 100.

**Comment by nanaya** [comment]
This has been fixed.
