### ISSUE TITLE
"Error requesting access token using client_credentials grant type

### ISSUE THREAD

**Issue by DrowsyOsu** [ppy/osu-web#9663]
am encountering while trying to use the osu! API. I am attempting to request an access token using the "client_credentials" grant type, but I am receiving an error that says "unsupported_grant_type". The error message indicates that the authorization grant type "client_credentials" is not supported by the authorization server.

I am using the Python requests library to send a POST request to the /oauth/token endpoint with the required parameters. I have double-checked that I am sending all the required parameters in the correct format and that there are no spelling mistakes or typos. However, I am still encountering this error.

I am not sure what is causing this issue, Could you please provide some guidance on how to fix this error and successfully request an access token using the "client_credentials" grant type?

**Comment by DrowsyOsu** [comment]
https://i.cmyui.xyz/3GLlhpyDB17E0HOdmQE.png

**Comment by DrowsyOsu** [comment]
[https://i.cmyui.xyz/3GLlhpyDB17E0HOdmQE.png](url)

**Comment by DrowsyOsu** [comment]
![3GLlhpyDB17E0HOdmQE](https://user-images.githubusercontent.com/25093530/208870224-705bc20a-854c-4397-b044-70b7b9a96bc0.png)

**Comment by DrowsyOsu** [comment]
![X8a1qApg0wnqR9M](https://user-images.githubusercontent.com/25093530/208871042-b01fe588-e5da-4477-96f6-85c4d114ea78.png)
the error im getting

**Comment by DrowsyOsu** [comment]
{"error":"unsupported_grant_type","error_description":"The authorization grant type is not supported by the authorization server.","hint":"Check that all required parameters have been provided","message":"The authorization grant type is not supported by the authorization server."} 
response im getting

**Comment by nanaya** [comment]
The example in documentation is wrong. Parameters should be sent as form encoded as per oauth specification.

This shouldn't be a problem if you use oauth2 client library instead.
