### ISSUE TITLE
My lazer website profile doesn't show best performances for osu!std

### ISSUE THREAD

**Issue by Non-Binary-Programmer** [ppy/osu-web#9682]
See title. [Link to my profile.](https://lazer.ppy.sh/users/25480469)

This is total conjecture, but I think it may be because I have ranked +RX scores that can not be calculated due to the site still using classic pp/difficulty calculation. I believe this is the case because +RX scores from 6 days ago still show as calculating in the Recent Plays section, and my best performances for other rulesets show up fine.

**Comment by Non-Binary-Programmer** [comment]
Update: it works fine now, but the relax plays still haven't been calculated.

**Comment by Joehuu** [comment]
> relax plays still haven't been calculated

Intended for now, see https://github.com/ppy/osu/discussions/23396#discussioncomment-5823849.
