### ISSUE TITLE
Bugged Profile Page (lazer.ppy.sh)

### ISSUE THREAD

**Issue by memesnightmares** [ppy/osu-web#9686]
I'm not totally sure how to debug this, but here's the broken page: https://lazer.ppy.sh/users/14613516 (example error code `098bf7af363d4ac29bc6b9e116966961`) and here's some potentially related information:

- About 10 hours ago, there was no error, but my "Best performance" section listed 0 scores and scores set on lazer did not add to total PP on lazer.ppy.sh. See my report here: https://github.com/ppy/osu/discussions/21830
- Subsequently, I tried opening stable up and setting one score. That did not change anything, although it did give me rank on osu.ppy.sh again, because mine was reset.
- I primarily play on lazer and have for nearly two years. I have under 10 hours in stable. I use the AppImage build for linux.

**Comment by peppy** [comment]
Is it fixed now?

**Comment by memesnightmares** [comment]
Uhhhh sort-of? My "best performance" now says it includes 100 plays, but actually just lists 5? New plays that have PP (listed in Recent Plays section) do not show up there, and I have no idea how it selected those 5 to show, since I've been playing lazer for years. They might just be the top 5, I would believe that?

**Comment by nanaya** [comment]
it's only temporary workaround so the page doesn't straight out error

**Comment by Fatalution** [comment]
Kinda same issue [here](https://github.com/ppy/osu-web/issues/9684), but a bit more serious - my profile is outright empty, aside from showing my history of plays. Almost all stats are showing 0s.

I haven't played and set scores with stable, I do play on Lazer.

**Comment by memesnightmares** [comment]
Resolved on live lazer.ppy.sh. Still seeing pp being calculated based on stable max combo (including slider ends) rather than lazer max combo (no slider ends), but from my understanding that's a separate issue. Not sure if one is already open but I believe I saw a GH discussion on ppy/osu about it.

**Comment by peppy** [comment]
Thanks for the update. I've applied some fixes to the processing which should cover most of the cases of things not looking right.

As for the max combo calculation, we will track that at https://github.com/ppy/osu/issues/21815 (?) or please open an issue if that doesn't look to be tracking this case.
