### ISSUE TITLE
Wrong profile accuracy displayed on the main website after syncing with lazer

### ISSUE THREAD

**Issue by just7nz** [ppy/osu-web#9687]
Before yesterday, my profile accuracy was 97.48%. Yesterday I logged in to lazer and submitted a score to update profile stats, which changed my profile accuracy to 95.85 in lazer.ppy.sh, as it should, because mania's 300 judgement's accuracy got changed, however, that also changed the profile accuracy in the main website, and doesn't seem to update even after submitting a score on stable.

My profile: https://osu.ppy.sh/users/9949910

**Comment by peppy** [comment]
You will likely need to set a high score on stable for it to revert to the old number. Please try this.

**Comment by just7nz** [comment]
That worked.
