### ISSUE TITLE
(lazer.ppy.sh) classic badge not showing next to scores with it

### ISSUE THREAD

**Issue by SquishyMan1** [ppy/osu-web#9688]
In both Firefox and Chrome, the classic badge is not showing up on my profile next to scores that have the mod applicable to it. However, the badge has a tip that shows up when you hover over the area in which it should be. These tags appear just fine when viewing my profile from within the game itself though. 

Website version
<img width="969" alt="Screenshot 2022-12-28 at 9 57 52 AM" src="https://user-images.githubusercontent.com/67621489/209853327-c03f5bc3-f472-4e7e-bfb7-41f03b98d266.png">

In game version
<img width="1122" alt="Screenshot 2022-12-28 at 9 57 04 AM" src="https://user-images.githubusercontent.com/67621489/209853253-14004b69-5313-45d4-a571-d460b00cb06b.png">

**Comment by Corne2Plum3** [comment]
I have the same issue, It seems like there's already the space for the Classic Mod icon, but the icon is missing.

![same_issue](https://user-images.githubusercontent.com/57914482/210223892-f213ccb8-48dd-476d-ae6d-0771f14c5c98.png)

**Comment by Loreos7** [comment]
Every lazer-mod icon doesn't show up either.
![image](https://user-images.githubusercontent.com/86934170/211786137-e90b93ee-a108-497f-ae24-8cfcacf82010.png)
https://lazer.ppy.sh/scores/2165305061
