### ISSUE TITLE
(lazer.ppy.sh) Recent Plays (24h) goes way farther back

### ISSUE THREAD

**Issue by Theighlin** [ppy/osu-web#9689]
I checked a couple of profiles and all seem to behave like this

Screenshot from mrekk's profile
Last visible play is from 21 days ago, seems to cap at 100 like the best performance section?

![Screenshot_2022-12-28-21-58-07-86_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/53081750/209871493-02fd3682-dd41-4eb8-8a00-eaec5632be48.jpg)

**Comment by peppy** [comment]
This is correct for now. It will likely reduce in the future as we bring the score purging system online.

I don't think this needs a tracking issue unless this is creating some usability issue.
