### ISSUE TITLE
Add proper filtering and spam protection for Apiv2

### ISSUE THREAD

**Issue by MIHAIdavid22** [ppy/osu-web#9695]
**it appears that entire raids with bots are happening using Apiv2 directly or via a IRC botnet bridge between lazer/web chat as @WindowsMeosu theorizes, thus i would request that proper filtering and spam protection like in Bancho is added for Apiv2 since the current implementations do not seem to work that well.**

**here are a few examples of a bot raid in action:** 
edit: here is a gif version showing the raid in action
![firefox_2zjApgW1LZ](https://user-images.githubusercontent.com/20879176/210031625-b66782a9-28c7-48f6-bff4-5697926ef766.gif)
![firefox_6woNMAfnTK](https://user-images.githubusercontent.com/20879176/210027140-51bf7e83-6735-48e7-88d1-d6f38af6b243.png)
![firefox_UPDC7rU0ID](https://user-images.githubusercontent.com/20879176/210027155-96a2e85c-6eed-4209-afbe-51fda4d38ebf.png)
![firefox_y5riRE83wu](https://user-images.githubusercontent.com/20879176/210027161-27f235c4-bef6-486a-ac4f-16bf8a742e7e.png)

**Comment by peppy** [comment]
Thanks for the input but this is being tracked internally and this is not required.
