### ISSUE TITLE
Wrong tooltip text on the Edit button of the me! section

### ISSUE THREAD

**Issue by SchiavoAnto** [ppy/osu-web#9699]
The Edit button of the me! section displays a wrong tooltip, or rather, the same tooltip as the Edit profile page button.
![image](https://user-images.githubusercontent.com/63348037/210071053-a11279cc-01b1-4397-9a0b-adc78834d1f7.png)

**Comment by eoghanriley** [comment]
What should the tooltip say instead? The most obvious answer to me is Edit me!

**Comment by SchiavoAnto** [comment]
> What should the tooltip say instead? The most obvious answer to me is Edit me!

yes, I think it would be better.
