### ISSUE TITLE
Ranked map is missing its background preview

### ISSUE THREAD

**Issue by Hiviexd** [ppy/osu-web#9714]
https://osu.ppy.sh/beatmapsets/1884417#taiko/3879886

I've also heard claims that this affected some recent pending maps but I didn't really investigate that.

**Comment by Hiviexd** [comment]
any update on this? seems like it went unnoticed for such a simple fix

**Comment by Joehuu** [comment]
Seems to be back, closing for now.

![chrome_amlf1QPkHB](https://user-images.githubusercontent.com/35318437/211652254-dfdff73c-b153-452c-9198-6f4b7cf3fc69.png)
