### ISSUE TITLE
The authorization grant type is not supported by the authorization server.

### ISSUE THREAD

**Issue by owoPeef** [ppy/osu-web#9716]
When Im trying to get authorization_code with oauth, I always get the error "_The authorization grant type is not supported by the authorization server._".
PHP Data:
`array(
    "client_id" => $BANCHO_CLIENT_ID,
    "client_secret" => $BANCHO_SECRET_KEY,
    "code" => $code,
    "grant_type" => "authorization_code",
    "redirect_uri" => $BANCHO_REDIRECT_URI
);`
Headers:
`array(
    "Accept: application/json",
    "Content-Type: application/x-www-form-urlencoded"
);`

**Comment by nanaya** [comment]
The data is probably sent in wrong format. Alternatively try using existing oauth2 client library.

**Comment by nanaya** [comment]
Feel free to reopen/comment if still having problem.
