### ISSUE TITLE
Bugged/Impossible scores

### ISSUE THREAD

**Issue by C0D3-M4513R** [ppy/osu-web#9717]
These are some bugged scores I've noticed whilst playing. Might be wise to crawl scores again and compare the total amount of hits(300+100+50+miss) and the total amount of possible hits.

https://lazer.ppy.sh/scores/954414
https://lazer.ppy.sh/scores/10990198
https://lazer.ppy.sh/scores/954298
https://lazer.ppy.sh/scores/37649558

Initial post on discord: https://discord.com/channels/188630481301012481/188630652340404224/1060979568892198912

**Comment by Camillewz24340** [comment]
Ok that's kinda weird 🥲

**Comment by peppy** [comment]
Scores will be reset in the future.
