### ISSUE TITLE
difficulty list dropdown is broken and rendered useless on mobile web

### ISSUE THREAD

**Issue by leSupaV** [ppy/osu-web#9727]
the additional info in the difficulties dropdown is pretty much rendered useless on mobile as it just gets cut out
![Screenshot_20230110-231617_Samsung_Internet](https://user-images.githubusercontent.com/84695826/211605679-399000fc-1690-4867-9f29-5456e1efa3ad.jpg)

on another note, isn't it quite a bit too much to put additional info in the drop-downs when the actual mapper's name is on the discussion page itself?
![Screenshot 2023-01-10 231446](https://user-images.githubusercontent.com/84695826/211605713-49277d72-8b73-40d1-926c-6f165ecbfc21.png)
dropdown view on desktop

![Screenshot 2023-01-10 231501](https://user-images.githubusercontent.com/84695826/211605733-bbf1b4d3-cae9-462e-89c8-02b7c68145cb.png)
what you see right below the drop-down

**Comment by nanaya** [comment]
> the additional info in the difficulties dropdown is pretty much rendered useless on mobile as it just gets cut out

well that's unfortunate but it's still useful on slightly wider screen

> on another note, isn't it quite a bit too much to put additional info in the drop-downs when the actual mapper's name is on the discussion page itself?

but you have to actually select the map first instead of one quick look at the list

**Comment by leSupaV** [comment]
my point is that on mobile it really _is_ useless as it just gets cut out all of the time. perhaps paraphrasing the long test into something like (`username`)? cause as it stands rn, even if you'd intend to get a quick look at the list, it'll not work on mobile so i don't really get it man

**Comment by nanaya** [comment]
Continued in #9779.
