### ISSUE TITLE
Add individual difficulty ratings to the beatmap cards

### ISSUE THREAD

**Issue by ap-ple** [ppy/osu-web#9733]
I want to grab the difficulties directly from the beatmap cards on the website through the HTML; however, since they only display on hover, I've had to implement a workaround by grabbing the map link and requesting the difficulties from the API, which has proven to be much slower.

**Comment by nanaya** [comment]
I don't know what you're trying to do here but the beatmapsets api endpoint already return those. And if you're trying to access the beatmap data on page they're in `osuCore.dataStore.beatmapsetStore` (note that this is internal api and may change without warning)

**Comment by ap-ple** [comment]
This seems to be exactly what I was looking for. May I ask how to interact with the `osuCore.dataStore.beatmapsetStore` API to retrieve the difficulties on the page (is there a documentation I should look at)?

**Comment by nanaya** [comment]
As mentioned above, it's an internal api so you have to figure it on you own.

**Comment by ap-ple** [comment]
To clarify, this is a feature request; for the difficulties of each beatmap to be displayed on the beatmapset cards.
