### ISSUE TITLE
Searching a user with "_old" suffix is difficult

### ISSUE THREAD

**Issue by TheRealStevie** [ppy/osu-web#9742]
Let's say we want to search [Yes_old (ID:112302)](https://osu.ppy.sh/users/112302). On user search , entering "[yes](https://osu.ppy.sh/home/search?mode=user&query=yes)" or even with "[_old](https://osu.ppy.sh/home/search?mode=user&query=yes_old)"/"[ old](https://osu.ppy.sh/home/search?mode=user&query=yes%20old)" won't show the user we wanted to search. Even [entering a user ID](https://osu.ppy.sh/home/search?mode=user&query=112302) won't work which is odd. Note that on beatmap search, the user's beatmaps can be searched just by entering "[yes](https://osu.ppy.sh/beatmapsets?q=yes)" ([creator=yes](https://osu.ppy.sh/beatmapsets?q=creator%3Dyes)) or by [user ID](https://osu.ppy.sh/beatmapsets?q=112302).

![wa](https://user-images.githubusercontent.com/75444413/212448297-6ea2c5cf-07b4-4740-bc24-4e1647e22eec.png)

What I would expect to happen is that by searching with a username, the first result show a user who currently using its username, and the next results will be users who previously used it.

**Comment by peppy** [comment]
`_old` usernames are not intended to be searchable.
