### ISSUE TITLE
Forum post counter showing incorrectly in some users' profile.

### ISSUE THREAD

**Issue by tematikkp** [ppy/osu-web#9745]
For example:
![Westonini's profile showing 0 posts even though they posted thousands of posts](https://i.ibb.co/QbXk6n5/Screenshot-2023-01-15-193550.png)
A few people might have noticed this bug, though. Keep in mind that Westonini posted thousands, not 0, and was very active in the forums in the past. The same case as TheLegendaryHD, they posted hundreds of posts in the forum and in their profile, it says, "12 posts". This is a glitch in the website.

**Comment by venix12** [comment]
Some forums (e.g. off-topic) are not counted into the displayed number from what I know.

**Comment by tematikkp** [comment]
> Some forums (e.g. off-topic, introductions) are not counted into the displayed number.

Oh okay I never knew that before
