### ISSUE TITLE
Add guest difficulty information to beatmaps in the API

### ISSUE THREAD

**Issue by apollo-dw** [ppy/osu-web#9773]
Use case: I started running a [map rating & rating charts website](https://omdb.nyahh.net/) and I'd like to start individual difficulties with mappers, rather than entire mapsets. Recently, maps have gotten [guest difficulty support](https://i.imgur.com/ZSXiwsl.png) but this information is currently missing from the API response. Adding a `creator_id` field to the `Beatmap` object structure (which would either return guest, or the set host if no guest) would solve this completely, making my life 2000x easier.

**Comment by nanaya** [comment]
it's already there as `user_id`

**Comment by apollo-dw** [comment]
lesson learnt to read better
