### ISSUE TITLE
Remove "Delete Beatmap" button for moderators

### ISSUE THREAD

**Issue by RockRoller01** [ppy/osu-web#9774]
All removals should happen via the bot for logging purposes, there are 0 reasons why anyone should do it with the button. 
It already happened that people deleted things without using the bot, which lead to no logging.

**Comment by Okorin** [comment]
IDK if beatmaps have soft-deletes. 

If they do, alternative for the "no logging" issue would be enabling moderators to see those, especially if mapthreads are involved see https://github.com/ppy/osu-web/issues/9594

instead of disabling the button, alternatively just adding logging to said button would be a solution as well

**Comment by RockRoller01** [comment]
> instead of disabling the button, alternatively just adding logging to said button would be a solution as well
at that point the button is the same as the bot, and would need to report back to discord via webhook etc. i dont think its worth maintaining 2 separate systems for this (ASS and osu-web) but thats up to the devs to know

**Comment by venix12** [comment]
They literally both use the same workflow ([BeatmapsetDelete](https://github.com/ppy/osu-web/blob/master/app/Jobs/BeatmapsetDelete.php)  job).

**Comment by nanaya** [comment]
The mailing part is bot specific thing. It could technically be moved to web as well so all the bot needs to do would be just hitting the api...

**Comment by RockRoller01** [comment]
I don't think it matters much in the end which system is used, as long as it
- removes the map
- mails the user + silences
- logs to #content-moderation on discord

The point is that all existing systems must fulfill these criteria so people don't use the wrong one. Easiest one probably would be to let it all be handled by the bot considering that its doing all of that already and osu-web would need to paly catch-up
