### ISSUE TITLE
Report pop-up looks bad and unintuitive

### ISSUE THREAD

**Issue by Blooshing** [ppy/osu-web#9789]
Issue on latest Opera GX, chrome, but havent checked other browsers.

Asked in #osu-web and was told to go here :shrug:

Initially had an extension, then turned if off and both looked the same so no real extension issue on my hand.

![CyNbGOG](https://user-images.githubusercontent.com/90729492/214597923-7fe92450-ee7c-479c-9f73-7280e71c2665.png)

**Comment by marcostudios** [comment]
I have the same issue on latest Firefox 109 with and without enabled extensions and ms edge
