### ISSUE TITLE
Downloading beatmap takes me to error page

### ISSUE THREAD

**Issue by cfgexe** [ppy/osu-web#9792]
When I try to download https://osu.ppy.sh/beatmapsets/7777,
it takes me to an error page on the old website. What ever happened to this map?

**Comment by peppy** [comment]
This looks to be a beatmap which is not actually available due to automatic graveyard purging (something we used to do). The issue is that it hasn't been marked correctly. I'll look at running a batch process to mark any that should be marked as having no download but haven't been yet.

**Comment by peppy** [comment]
Will track via https://github.com/ppy/osu-web/issues/8939
