### ISSUE TITLE
Disallow all username changes to handles held by top players

### ISSUE THREAD

**Issue by Ephemeralis** [ppy/osu-web#9804]
As raised in an email to me recently, a specific, now-deceased top player's name is about to become available for name changes. This is an ongoing problem not just for deceased or inactive players, but also for any player who has been in the public eye by virtue of being at the top of the leaderboards.

An easy solution to fix this would be to add the usernames (including all previous ones) of any players from the top 100 via peak rank (in all game modes) to the disallowed usernames list a few times a year.

**Comment by notbakaneko** [comment]
Does this mean any username that's been in the top 100, at any time ever, gets reserved? @Ephemeralis @peppy

**Comment by peppy** [comment]
Yes, that's the hope.

**Comment by notbakaneko** [comment]
I forgot to mention whether it's supposed to include any username they've used in the past and not just the current one? 🤔
