### ISSUE TITLE
Wrong naming of Vietnam in store.

### ISSUE THREAD

**Issue by Blooshing** [ppy/osu-web#9806]
![cTQG5dM](https://user-images.githubusercontent.com/90729492/215352042-41faf597-dfb2-4e42-b53f-296badd39810.png)

Not super important but figured it should be fixed. The image shows that Vietnam is actually spelt out like Viet Nam, which isn't correct.

**Comment by uzervlad** [comment]
Both are correct

**Comment by peppy** [comment]
I've fixed this.

cc/ @Ephemeralis not sure how this happened.
