### ISSUE TITLE
Proposal: Different Types of Featured Artists

### ISSUE THREAD

**Issue by Rekunan** [ppy/osu-web#9827]
The types would be GFX, artwork (like backgrounds and skin elements), audio (like hitsounds), and music.

**Comment by cl8n** [comment]
@pishifat probably needs ur opinion

**Comment by peppy** [comment]
I don't understand what this is really asking for.

Also I don't think it makes sense in the scope of osu!.

**Comment by Rekunan** [comment]
Similar to how featured artists bring officially licensed music, we'd have officially licensed assets for hitsounds, art, etc. to use for mapping and/or skinning.

**Comment by peppy** [comment]
We don't have the resources for this. If you're interested in making something like this happen. Maybe you could start with a forum thread or something, and get people involved that way.

**Comment by Rekunan** [comment]
Fair enough, yeah, I'll try doing that instead.
