### ISSUE TITLE
Osu-web seems to have reload issues

### ISSUE THREAD

**Issue by Blooshing** [ppy/osu-web#9869]
Forum post: https://osu.ppy.sh/community/forums/topics/1722739

Seems that going moving through forums, to user profile, to forums, then user profile can cause the user profile to not load (not sure if indefinitely) and needing to refresh the browser to get it to load. 

Some have experienced this with Chrome and Opera, where I have experienced this on safari and chrome. When on safari I had no extensions added, but with chrome I have extensions. 

![image](https://user-images.githubusercontent.com/90729492/219523132-27a19303-9d7f-4768-9e01-b1e46eb25032.png)

The way I reproduce it on safari: 

1. Home page 
2. User profile 
3. Forums 
4. Home page 
5. User profile 
6. Sometime in between there the user profile or page will not load and give this issue.

**Comment by marcostudios** [comment]
I've got a Firefox console log of it, sorry if there are lots of extensions errors

[console-export-2023-2-17_2-7-33.txt](https://github.com/ppy/osu-web/files/10762300/console-export-2023-2-17_2-7-33.txt)

**Comment by aryoadhi** [comment]
Is it related to user agent of the browser or the CDN?

I used Brave and it doesn't seem to have any issues. Notification seems to be lagged out compared to phone with same wireless connectivity, but other than that it's fine.

```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
```

**Comment by Corne2Plum3** [comment]
same
