### ISSUE TITLE
Custom identifiers in news posts no longer work

### ISSUE THREAD

**Issue by Walavouchey** [ppy/osu-web#9874]
i was about to make use of one of these links but uh it broke somewhere along the way

example: https://osu.ppy.sh/home/news/2022-12-08-mappers-choice-awards#osu!-maps-high-bpm-alternator
location in file: https://github.com/ppy/osu-wiki/blob/master/news/2022/2022-12-08-mappers-choice-awards.md?plain=1#L53

![image](https://user-images.githubusercontent.com/36758269/219701553-dc64410f-ca71-4a6f-8434-4dca31750e82.png)

it only becomes "visible" on images, but regular custom identifiers just don't work

example: https://osu.ppy.sh/home/news/2020-02-28-mappers-report-february#conclusion
location in file: https://github.com/ppy/osu-wiki/blob/master/news/2020/2020-02-28-mappers-report-february.md?plain=1#L140

(image from github file view)

![image](https://user-images.githubusercontent.com/36758269/219703074-827e5702-0d1f-47f7-993b-e09e2c8ab394.png)

**Comment by nanaya** [comment]
The first one looks like #8057 since the non `osu!` ones do work. As for the other one that's completely missing, it needs to be attached to a block or element.

**Comment by Walavouchey** [comment]
> The first one looks like https://github.com/ppy/osu-web/issues/8057 since the non osu! ones do work.

it's not like they didn't used to work so i'm not getting the full picture, but you're right that the other ones work

> As for the other one that's completely missing, it needs to be attached to a block or element (not actually sure if it can attach to an element).

the mappers' report one may have been broken by https://github.com/ppy/osu-wiki/pull/7837 if that's the case

**Comment by nanaya** [comment]
It's most likely a bug in the library parser which then fixed.

**Comment by Walavouchey** [comment]
will switch these to use the `{id=...}` syntax instead in a moment

**Comment by nanaya** [comment]
I just checked how it was in archive.org and the ids are all cut off on `!` mark so it's never worked correctly in the first place.

![](https://s.myconan.tk/2023/02/firefox_2023-02-18_02-25-28.png)

**Comment by Walavouchey** [comment]
it seems like they only work if they can attach to something, to give it the id attribute

i'm curious if something like this would work

```markdown
--- {#conclusion}

Make sure to tune in to the next NAT Meeting ...
```

![image](https://user-images.githubusercontent.com/36758269/219734840-ddbda95a-631a-4d23-917a-cb0de90bfd92.png)

(i don't know if it's possible to test this using chrome dev tools)

**Comment by nanaya** [comment]
This seems to work
```
{#wat}
---
```

**Comment by Walavouchey** [comment]
same reason why this works, i'm assuming

![image](https://user-images.githubusercontent.com/36758269/219743431-7f8920e0-0ee2-474c-959f-6078cbf5b5e9.png)

**Comment by Walavouchey** [comment]
both 

```markdown
{#wat}
---
```

and

```markdown
---
{#wat}
```

give remark errors

1. "Headings should use atx"
2. "Missing blank line before block node"

**Comment by notbakaneko** [comment]
Custom attributes need to be attached to an element; it's `::{#idgoeshere}::` for news and wiki if you want to have an anchor in the middle of nowhere

**Comment by Walavouchey** [comment]
closing as resolved in https://github.com/ppy/osu-wiki/pull/8817. seems like things are working as intended
