### ISSUE TITLE
users are able to see deleted posts in post history from anyone

### ISSUE THREAD

**Issue by Lyawi** [ppy/osu-web#9881]
![BRwSHdQ](https://user-images.githubusercontent.com/32525896/219978010-5c99f7c8-e6ad-4acd-8379-e8dbcd7b9d3e.png)
![D132pYJ](https://user-images.githubusercontent.com/32525896/219978014-c9c548ee-8670-4280-a9bc-fa065b7a3b07.png)

**Comment by marcostudios** [comment]
Can confirm

![immagine](https://user-images.githubusercontent.com/5209299/219978667-056cd083-38f7-43be-86ae-2a417e14bc6d.png)

**Comment by nanaya** [comment]
The new deleted attribute wasn't in the previous index schema and now has been updated.
