### ISSUE TITLE
The switcher for topic sort is poorly readable

### ISSUE THREAD

**Issue by Teages** [ppy/osu-web#9920]
![image](https://user-images.githubusercontent.com/39217423/221937426-276b1fdf-c5dc-4276-afef-ff543c108fbb.png)

code: [resources/css/sections.less#L127](https://github.com/ppy/osu-web/blob/master/resources/css/sections.less#L127)

Simply deleting these line could be solved but I don't know if it is the best way
(if these css is not used in other place, I think it is the best)
```less
    .u-forum--link-text {
      color: @text !important;
    }
```

after:
![image](https://user-images.githubusercontent.com/39217423/221940098-bdb75be2-c59f-4e29-8f65-2ed8a8815082.png)

btw I saw a lot of `!important` in this file, I think that is not a good idea

**Comment by RockRoller01** [comment]
The issue here stems from the active sort selection being colored according to what forum category the forum is in. Purple for beatmaps, green for general, orange for languages and dark grey for moderation, applied by this rule: `.t-forum-category-beatmaps .u-forum--link-text`
