### ISSUE TITLE
Disable ability to edit / post discussions on beatmaps with `disabled` flag(s)

### ISSUE THREAD

**Issue by peppy** [ppy/osu-web#9924]
Similar to beatmap comments, the discussions page should not allow interaction when this flag is set.

**Comment by nanaya** [comment]
Does this also apply when comment is locked?

**Comment by nanaya** [comment]
oh, and how about deleting existing post?

**Comment by peppy** [comment]
> Does this also apply when comment is locked?

As in should editing be disabled when a single comment is locked?

**Comment by nanaya** [comment]
> As in should editing be disabled when a single comment is locked?

As in when the beatmapset has commenting disabled
