### ISSUE TITLE
An osu! alumni not listed on its group page

### ISSUE THREAD

**Issue by TheRealStevie** [ppy/osu-web#9925]
[This user](https://osu.ppy.sh/users/53) has an osu! Alumni badge. But looking at the [group page](https://osu.ppy.sh/groups/16), the user doesn't seem to be listed on there.

**Comment by nanaya** [comment]
The user for some reason has user type of 3 (`USER_FOUNDER` according to phpbb) which gets filtered out in most cases.

**Comment by cl8n** [comment]
they should be changed to `USER_NORMAL` (`0`) like everyone else, osu-web does not reimplement anything that phpbb used `USER_FOUNDER` for. and yeah osu-web ignores founders in some places where phpbb would have been checking for either user type.

@peppy should be a quick fix? also reindex cuz one of the issues is that you cannot search for this account

**Comment by TheRealStevie** [comment]
> also reindex cuz one of the issues is that you cannot search for this account

This is related to https://github.com/ppy/osu-web/issues/9742.

**Comment by peppy** [comment]
I've fixed the user type. Still very unfortunate phill lost his username 😞
