### ISSUE TITLE
Improving a pinned score results in it being un-pinned

### ISSUE THREAD

**Issue by DanielPower** [ppy/osu-web#9941]
## Steps to reproduce
1. Pin a score
2. Re-play that map, and achieve a better score

## Observed behaviour
The map will be removed from "Pinned Scores"

## Expected behaviour
The new score should replace the old score on the "Pinned Scores" list.

**Comment by nanaya** [comment]
It's actually the expected behaviour. Even for lazer scores the current plan is those pinned scores will stay even if there are higher scores for the map.

**Comment by DanielPower** [comment]
> the current plan is those pinned scores will stay even if there are higher scores for the map.

Is this tracked in an issue somewhere? This does not match the current behavior. Currently, if you get a better score on a map, it will remove your pinned score on that map.

**Comment by nanaya** [comment]
it's only for lazer scores. for stable scores they will be gone instead (at least for now)
