### ISSUE TITLE
Add `kube_namespace` label to custom Datadog metrics

### ISSUE THREAD

**Issue by ThePooN** [ppy/osu-web#9959]
Similar to `pod_name` that was added using the container's hostname, we need the `kube_namespace` label added to Datadog custom metrics in order to differentiate both main (osu.ppy.sh) and lazer (lazer.ppy.sh) deployments in our dashboards.

The namespace can be retrieved in two different ways:
- using the private Kubernetes API exposed from the container
- using an environment variable

The 2nd solution is much easier to test and implement on osu-web, and is also 3 lines of config on my end so I suggest we go with that.

**Comment by notbakaneko** [comment]
does using `DD_ENTITY_ID` not work?

**Comment by ThePooN** [comment]
Looks like that's enough, thanks.
