### ISSUE TITLE
weird alignment of beatmap difficulties in compact mode

### ISSUE THREAD

**Issue by hyyhsuzy** [ppy/osu-web#9967]
This was an issue that wasn't there previously though I noticed it a few months back. 
Thought it was just an issue from my side till I checked and noticed the same on different systems as well as on other users' pcs.

The map difficulties are clearly misaligned and its more obvious on maps with more difficulties.
![image](https://user-images.githubusercontent.com/91675300/223690157-c3065751-f491-46c2-b6b0-5c6c2a2da009.png)

![image](https://user-images.githubusercontent.com/91675300/223690240-8c7ba36a-5ae1-4b24-bac8-e0b2579d0833.png)
Even the widths and spacing are uneven here.

![image](https://user-images.githubusercontent.com/91675300/223690518-0b363015-3ad5-4dc9-93f6-6259b205b927.png)

It is also visible in this layout on the beatmap listing page. In any compact mode, this issue is seen.

**Comment by nanaya** [comment]
Unfortunately that's a browser problem. I don't think there's much can be done here without something like manually drawing the dots (maybe) or outright a different design.

**Comment by hyyhsuzy** [comment]
A different design would be a better idea with just dots instead of these rounded rectangles actually but I don't know if that could be done. I remember very well that this issue just popped out of nowhere randomly a few months back, it was fine till then.
