### ISSUE TITLE
[Question] When the UI gets support for skins, will there be an option to only apply the skins during gameplay?

### ISSUE THREAD

**Issue by duckyondiscord** [ppy/osu-web#9975]
I was reading the *Upgrading to lazer* article(?) recently. And since I like the default triangles skin in the regular UI and not in gameplay, will there be an option for this in the future?

**Comment by zoey-on-github** [comment]
this is a question for [osu!lazer](https://github.com/ppy/osu)

this repo is exclusively for issues/feature requests with the osu! website
