### ISSUE TITLE
Enabling forum tags in the Ranking Criteria subforum

### ISSUE THREAD

**Issue by Hiviexd** [ppy/osu-web#9978]
was asked by peppy to post here. for reference, these are what I'm talking about
![](https://cdn.discordapp.com/attachments/1083320217259749376/1084478634452078712/image.png)

would help a lot with distinguishing proposals that are duplicates, got accepted, or got denied. currently, the only way to check for those is by going into each post and reading replies which can be pretty tedious.

For example, browsing this specific [subforum](https://osu.ppy.sh/community/forums/92) isn't practical at all right now

these should be applied on forum ids 87 and 92

**Comment by nanaya** [comment]
I think it's determined by `ISSUE_FORUM_IDS` config.

**Comment by peppy** [comment]
Has been deployed!
